### ISSUE TITLE
Question: adding permalinks to tree nodes with Mkdocs material

### ISSUE THREAD

**Issue by AntonKInv** [squidfunk/mkdocs-material#1009]
Hallo. First off, thank you very much for this theme, it is very convenient and stylish to use. I have a question, possibly a feature request.

The mkdocs.yml nav file I am working with includes a hierarchical tree of a manuals website with several categories and subcategories the content articles fall into; the tree is absolutely virtual and not based on a folder structure/website path. I am looking for a way to generate permalinks for each of the tree's nodes (categories). If that is impossible with Markdown or its extensions than perhaps html/css elements could be used.

I am very new to Markdown and mkdocs; I googled thoroughly to get a solution but failed to find one.

site_name: My Site
site_dir: docs/guides/
site_url: http://example.net/
docs_dir: 'src'
nav:
  - 'TOP LEVEL CATEGORY':
    - 'BOTTOM LEVEL CATEGORY':
         - Manual 1: 'manuals/Manual1.md'
         - Manual 2: 'manuals/Manual2.md'
    - 'BOTTOM LEVEL 2':
{...}
  - 'TOP LEVEL CATEGORY 2':
{...}

markdown_extensions:
    - smarty
    - toc:
        permalink: True
        separator: "_"
    - sane_lists
    - tables
    - meta
    - fenced_code
    - admonition
    - footnotes

The virtual hierarchical tree with expandable nodes which is built is all right, but I really need to generate permalinks for each category and subcategory, e.g. example.net/docs/guides/toplevelcat/bottomlevelcat or example.net/docs/guides/toplevelcat#bottomlevelcat it does not matter how exactly the links will be organized and whether they are generated automatically or preset manually

the link could lead to an index page with all manuals belonging to the category OR just display the root mysite.net/docs/guides/ page with the required category expanded

**Comment by squidfunk** [comment]
If `permalinks` is enabled, permalinks are automatically added to all Markdown headings within a page and linked on the right side from the table of contents. You can group/categorize your documentation into different pages using `nav` from `mkdocs.yml` and your page-specific content into different sections using Markdown headings:

```
# Page headline
## Category
### Sub-category
#### Sub-sub-category
##### Sub-sub-sub-category
###### Sub-sub-sub-sub-category
```

**Comment by AntonKInv** [comment]
Thanks for the prompt response, that is not what I was asking about. I meant the permalinks to hierarchical categories which the pages (articles) fall into according to the tree in the nav file, not individual pages or sections within pages.

**Comment by squidfunk** [comment]
I think I still don't understand your request. You mean some kind of tags, so cross referencing content?

**Comment by AntonKInv** [comment]
The nav creates a virtual tree of articles (md pages):

Root category
  -  Category 1
       - Subcategory 1
            - md page 1
            - md page 2
  -  Category 2
      - Subcategory 2
             - md page 3
             - md page 4

There are links created for the root category and individual md pages.
My question is whether there is any way to create links leading to Categories and Subcategories besides links to individual pages.
Sorry for confusing you.

**Comment by squidfunk** [comment]
Well, just link to `yoursite/category`

**Comment by squidfunk** [comment]
Is your question answered? The linked issue was closed for the reasons that can be understood from the discussion.

**Comment by AntonKInv** [comment]
Vielen dank, that's what I needed. Thanks for you time.
