### ISSUE TITLE
Content header/footer partials

### ISSUE THREAD

**Issue by majkinetor** [squidfunk/mkdocs-material#1015]
It would be great to have an option to specify content footer/header.

Those could be added as initially empty partials that could be overridden.

 I could then override those partials with the stuff I want. Some examples would include:

* list of common markdown links
* list of abbreviations 
* config values

This system would make sure that future theme updates do not break existing custom templates, something I experienced several times when I was messing with the current footer template.

**Comment by squidfunk** [comment]
Thanks for your suggestion. Care to submit a PR? I think this would be a better basis for further discussion.

**Comment by squidfunk** [comment]
Closing for house-keeping purposes. Feel free to submit a PR as a basis for further discussion. I understand that sometimes changes in the DOM structure break downstream documentation. I try to keep those changes to a minimum. If we can find a good solution for extensibility, I'm happy to merge it.

**Comment by majkinetor** [comment]
Sure. I hope I will find time for tests and PR in the near future.
