### ISSUE TITLE
Page moves when vertical scrollbar is shown/hidden

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#1018]
## Description

After #501, vertical scrollbars no longer appear in short pages. As a consequence, if you move between a short page and a long page in desktop view, i.e., a page with scrollbar and a page without scrollbar, the entire page "jumps" to the left or right.
This can be very distracting, especially if your project contains a lot of sub-sections and the navigation menu keeps moving back and forth while accessing pages on different levels.

### Expected behavior

The position of the page elements including nav, toc etc. should be fixed.

### Steps to reproduce the bug

1. Open https://squidfunk.github.io/mkdocs-material/release-notes/ in desktop view.
2. Open https://squidfunk.github.io/mkdocs-material/authors-notes/ in the same tab.
3. Go back and forth between both pages.

### System information

* OS: Windows 10
* Browser: Checked on FF and Chrome

**Comment by squidfunk** [comment]
So from what I understand you effectively suggest adding back the scrollbars, so that they are visible on every page, regardless of page height? If that's not what you want, could you please provide a screen capture which reproduces the effect, so we can better understand the problem?

**Comment by wilhelmer** [comment]
Yes, adding back the scrollbars does solve the problem. I don't know if there's a better solution or how other templates / other SSGs handle this. I'll see if I can think of something.

Effect:
![effect](https://s2.gifyu.com/images/i-like-to-move-itf2c09b0e00b72da9.gif)

**Comment by squidfunk** [comment]
Thanks for providing the screen capture. I understand that this may be undesirable when using a browser that exhibits this behavior, but I don't want to impose default scrollbars on all users. However, you can easily add scrollbars back with one line of extra CSS:

``` css
html {
  overflow-y:scroll; // untested
}
```

**Comment by wilhelmer** [comment]
Yep, that does fix it, thanks.

I guess there's no better solution with material's centered layout, especially because the width of the scrollbar varies by browser.

"Left-aligned" templates don't have this problem:

Page with scrollbar: https://solidity.readthedocs.io/en/v0.5.4/contributing.html
Page w/o scrollbar: https://solidity.readthedocs.io/en/v0.5.4/lll.html

Page with scrollbar: https://packaging.python.org/overview/
Page w/o scrollbar: https://packaging.python.org/tutorials/

**Comment by squidfunk** [comment]
That's correct. However, all centered pages have this problem. Nevertheless, it's easily fixable if desired, so therefore I consider this issue resolved.

**Comment by wilhelmer** [comment]
This seems to work as well, and only shows the scrollbar when needed (!):

```css
html {
    margin-left: calc(100vw - 100%);
    margin-right: 0;
}
```

Source: https://aykevl.nl/2014/09/fix-jumping-scrollbar

**Comment by squidfunk** [comment]
Thanks for researching! However, this doesn't seem to be a universal solution:

> There's one small issue: when using responsive web design (which you should!), it gets quite obvious that the margin at the left is bigger than at the right when the page is made smaller. This won't be an issue on mobile because scrollbars aren't normally shown there, but it just looks ugly on a desktop browser when the browser is resized.

**Comment by wilhelmer** [comment]
Hmm, I'm not in the office anymore, so I can't verify this, but the page looked perfect even in mobile view (resized my desktop browser window). So that issue may not apply to material's layout.

In desktop view, the header still jumped, but the nav remained in place. So it might be an improvement for the template if there are no downsides (needs testing).
