### ISSUE TITLE
How to get the list of broken links and unused files?

### ISSUE THREAD

**Issue by rei-vilo** [squidfunk/mkdocs-material#1024]
When launched, `mkdocs build` reports unused pages and missing files.

```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: ~/MkDocs/site 
INFO    -  The following pages exist in the docs directory, 
           but are not included in the "nav" configuration:
  - Hidden Page.md 
WARNING -  Documentation file 'Chapter1/Section2.md' contains a link to 
           'Chapter1/img/MissingFile.png' which is not found in the documentation files. 
```

Is there a way to get the list of broken links and unused files?

I tried `mkdocs -v build` to no avail.

Thank you!

**Comment by squidfunk** [comment]
This is a question that is related to `mkdocs`, not `mkdocs-material`. Would you mind asking your question on [their issue tracker](https://github.com/mkdocs/mkdocs/)?

**Comment by rei-vilo** [comment]
Thank you!

Of course, this is `mkdocs`-related, not `mkdocs-material`! It gives you the right idea of how `mkdocs-material` supersedes `mkdocs`...

See https://github.com/mkdocs/mkdocs/issues/1765

**Comment by johnthagen** [comment]
For those who find this, there is `mkdocs-unused-files`

- https://github.com/wilhelmer/mkdocs-unused-files

Though at the moment it appears unmaintained.
