### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by LinusGeffarth** [squidfunk/mkdocs-material#1045]
Would it be possible to add a dark mode to this library? I feel like we don't necessarily need a custom color palette, but a dark mode would be really cool for them late night sessions :)

**Comment by squidfunk** [comment]
Sure, it would be possible. Unfortunately, my current time budget only allows for maintenance and bugfixing. If you find the time and energy to get ahead on this, we can discuss possible solutions in this issue and you could go ahead and implement a solution to be integrated into the theme.

**Comment by LinusGeffarth** [comment]
Sounds good. I have no idea how this is built and don't really have a lot of time left either 😏
Guess I'll have to wait until someone else will take on this feature :)

**Comment by squidfunk** [comment]
Jep, sounds about right. Closing for housekeeping.
