### ISSUE TITLE
Add support for top-level child sections.

### ISSUE THREAD

**Issue by jearton** [squidfunk/mkdocs-material#1047]
I want to add some child sections under a main section. When the cursor moves to a main section, the child section automatically pops up.

**Comment by squidfunk** [comment]
You mean like in the header on mkdocs.org?

**Comment by jearton** [comment]
> You mean like in the header on mkdocs.org?

Yes, that's the effect.

**Comment by squidfunk** [comment]
That’s not possible as Material has a completely different design. If you want expanding menus on hover, you have to use the original theme or another one supporting it. Material doesn’t implement it because it isn’t ideal for tablets (i.e. large touch devices).

**Comment by squidfunk** [comment]
Housekeeping - closing as answered.
