### ISSUE TITLE
DockerHub shows pretty old Dockerfile

### ISSUE THREAD

**Issue by Anton-Latukha** [squidfunk/mkdocs-material#1050]
## Description

The image seems right.

[Dockerfile on DockerHub](https://hub.docker.com/r/squidfunk/mkdocs-material/dockerfile) seems old. It has `2016-2017` and `python2.7`, so at first I thought it is pretty old image.

### Expected behavior

Good to be if Dockerfile versions would match to the contents of image.

**Comment by squidfunk** [comment]
That’s true. The problem is that the Dockerfile is only updated on automatic builds which have some caveats. For this reason I decided to build on Travis and push to DockerHub from there. Unless you know how to correct (or remove) the Dockerfile on DockerHub manually I’m afraid it’s not fixable.

**Comment by squidfunk** [comment]
I deleted the automatic build configuration I once set up on Dockerhub. The Dockerfile should now not be visible anymore.

**Comment by Anton-Latukha** [comment]
Of course also a solution. I already do not remember is there possible to automatically update Dockerfile there.
Thank you for the project.
