### ISSUE TITLE
Feature request: Linkable admonitions

### ISSUE THREAD

**Issue by majkinetor** [squidfunk/mkdocs-material#1055]
## Description

More options to point users to specific parts of the page is always good to have.
It would be good to have an option to pass a link to concrete admonition section on a page.

### Expected behavior

Just like with headers, make admonition image anchor wich link can be copied.

### Actual behavior

Its not possible to do this now, alternative is something like this:

```md
!!! example "Example - attributes table for resource <i id='example-01'></i>"
    The following section contains example ...
```
*NOTE*: This currently  "swallows the first line" when scrolled to (i.e. goes under the `header` section)

I beleive JS that adds sequential id to the elements with `class="admonition-title"` would be enough, something along the line `$('.admonition-title').attr('id', 'adm' + (i++));`

**Comment by squidfunk** [comment]
Admonitions are implemented as part of [Python Markdown](https://github.com/Python-Markdown/markdown). Material only provides styles for Admonitions but doesn't perform any parsing.

**Comment by squidfunk** [comment]
Closing for housekeeping. Not implementable through Material.
