### ISSUE TITLE
Trouble adjusting width of sidebar

### ISSUE THREAD

**Issue by zachpetersen** [squidfunk/mkdocs-material#1059]
## Description

I am trying to adjust the width of the sidebar and have done so by adding custom CSS with the following. I assume that I need to make another adjustment to account for the additional width of the sidebar, however, I have been unsuccessful in finding where to make this adjustment.

https://www.screencast.com/t/408RoXzJx0ee

```
.md-sidebar--primary {
    width: 13rem;
}
```

### Expected behavior

Sidebar completely retracts on toggle close

### Actual behavior

When the sidebar is toggled closed the edge sticks out roughly the same amount by which I've adjusted the width.

### Package versions

* Material: Version: 4.1.1

### System information

* OS: Win10
* Browser: Chrome

**Comment by squidfunk** [comment]
I’m sorry but I cannot provide support on customizations and CSS adjustments. I would kindly ask you to ask or hire someone who has a good understanding of CSS to help you out. This issue tracker is meant for bugs and feature requests, so please be fair. This is an open source project. I work on it in my spare time, thus my time is very limited and I try to devote it to work on bugfixes and critical issues.
