### ISSUE TITLE
Disable autocomplete in search

### ISSUE THREAD

**Issue by retnikt** [squidfunk/mkdocs-material#1078]
## Description

Browser autocomplete in the search field should be disabled because it visually conflicts with the instant results.

### Expected behavior

The browser doesn't display its autocomplete.

### Actual behavior

The browser displays its autocomplete. Screenshot
![image](https://user-images.githubusercontent.com/24581770/56291653-90a21d00-611d-11e9-9a7f-3d368426a134.png)

### Steps to reproduce the bug

1. Click the search field.

### Solution
Add `autocomplete="off"` to the HTML form element in partials/search.html

**Comment by squidfunk** [comment]
`autocomplete` is already set to `off`, see line 32:

https://github.com/squidfunk/mkdocs-material/blob/a4cf6c964531a5659afbbc0e47de4539f3a3a599/src/partials/search.html#L30-L34

**Comment by retnikt** [comment]
why does it show autocomplete in chrome then? is this a user error? or does
the HTML need to be fixed?

**Comment by squidfunk** [comment]
I'm not seeing a autocomplete form on Chrome (73.0.3683.103) on macOS (10.12.1):

<img width="1552" alt="Bildschirmfoto 2019-04-17 um 18 32 24" src="https://user-images.githubusercontent.com/932156/56304803-2a2df680-613f-11e9-8afd-9abe38ed0c04.png">

**Comment by retnikt** [comment]
This is really weird... I'm on Chrome Dev 75.0.3766.2 on ubuntu bionic.
Also according to this SO answer
https://stackoverflow.com/a/38961567/7518910 if you change it to something
random like "nope" then it hides the autocomplete. I just tried that and it
works for me... seems to be a browser issue?

**Comment by squidfunk** [comment]
It would be interesting if somebody else is experiencing the same problem. You seem to be the first one having this problem, so it might be related to your setup. Maybe it's a browser extension, or an operating system thing.

**Comment by retnikt** [comment]
It's not an extension, and it doesn't happen on my Windows 10 box (chrome
dev 75.0.3759.4). I guess we can close this since it's not a problem with
this repo.
