### ISSUE TITLE
Horizontal scrollbar (.md-content)

### ISSUE THREAD

**Issue by makshh** [squidfunk/mkdocs-material#108]
## Description

![Scrollbar](http://image.prntscr.com/image/cb4ebd6b18c244eab0f75653248e6caa.png)

### Expected behavior

-No scrollbar on `.md-content`
-Scrollbars on code blocks.

### Actual behavior

-Scrollbar on `.md-content` when I have long text in code blocks.
-No scrollbars on code blocks.

### Steps to reproduce the bug

Add long text to code block and scroll to bottom (desktop view).

### Package versions

- MkDocs: 0.16.1
- Material for MkDocs: 1.0.1

### System information

- OS: MacOS
- Browser: Chrome/Firefox

### Possible solutions

1. Remove `float: left` from `.md-content__inner`
2. Add `max-width: calc(100% - 4.8rem)` to `.md-content__inner`

**Comment by squidfunk** [comment]
Thanks for reporting. That is indeed pretty bad. I just checked and it's possible to remove the float while still minimizing repaints. The overflow does the trick due to margin collapse.

**Comment by squidfunk** [comment]
I provided a fix in https://github.com/squidfunk/mkdocs-material/pull/109 which is merged into master. Will make a bugfix release tomorrow.

**Comment by squidfunk** [comment]
Release 1.0.2 today which fixes the issue.
