### ISSUE TITLE
Example for footnotes are not working in IE11

### ISSUE THREAD

**Issue by tailriver** [squidfunk/mkdocs-material#1083]
## Description

Footnote links of this project are not working in IE11.
Unfortunately, the browser is not ignorable in some country such as Japan.

### Expected behavior

Jump to footnote text in bottom.

### Actual behavior

Got force reloading.

### Steps to reproduce the bug

1. Open the [example for footnotes](https://squidfunk.github.io/mkdocs-material/extensions/footnotes/) by IE11.
2. Click a link to a footnote (for example, after "ipsum" in result).

### Package versions and Project configuration

(CI setting for this project)

### System information

* OS: Windows 10 Pro (1803 and 1809)
* Browser: IE11 (11.523.17134.0 and 11.437.11763.0)

----

### Workaround

Note that I've found workaround for this issue.

- Update Python Markdown to 3.1 (it is very latest; current requirement in mkdocs/mkdocs is `>=2.3.1`).
- Modify mkdocs.yml something like that (set SEPARATOR option to other than `:`):

```yaml
markdown_extensions:
  - footnotes:
      SEPARATOR: _footnote_
```

### Questions

Is this workaround the best? I don't want to force setting an option for all people.

To PR for this, which is appropriate? (or both?)

- mkdocs-material: To fix example page by modify YAML. However, it has no dependency to Markdown.
- mkdocs: To update dependency for Markdown.

**Comment by squidfunk** [comment]
Thanks for reporting! So, without further testing I read from your issue that IE has problems with colons in anchors. The anchors are actually rendered by Python Markdown, as you already noticed, so Material can do nothing about it.

However, if Python Markdown 3.x fixes this issue:

1. You could ask on the Python Markdown issue tracker whether the default colon separator could be substituted by another character (e.g. the underscore), so the default configuration works in all browsers.

2. You could ask on the MkDocs issue tracker whether MkDocs generally works with Python Markdown 3.x and its dependency could be upgraded.

If MkDocs generally works with Python Markdown 3.x, we could also add 3.x as a dependency for Material.

**Comment by waylan** [comment]
For the record, there are no known incompatibilities between Markdown 3.x and MkDocs.

**Comment by squidfunk** [comment]
Closing, see https://github.com/Python-Markdown/markdown/issues/819#issuecomment-486202535.

**Comment by factorlive** [comment]
Although this has been closed long ago, these are the following steps to make mkdocs beautiful in  IE11. You still have the option to simply say you don't support IE11.

🖐️ More information about polyfill can be found at their webpage [polyfill.io](url)

```html
      <meta http-equiv="X-UA-Compatible" content="IE=Edge">
      <script src="https://polyfill.io/v3/polyfill.js"></script>
```

🙊 

Unfortunately, the CSS colours still not render as variables are not supported by IE 11. Hence, you can go to your package, copy the assets/stylesheets/main*.css file in your overrides folder and hardcode certain colours before they are assigned with a variable. The css file is minified into a few lines and you can use a code formatter to untangle the css file (e.g. Prettier extension in Codespaces or VSCode).
