### ISSUE TITLE
Collapsible catalog please

### ISSUE THREAD

**Issue by LooperXX** [squidfunk/mkdocs-material#1084]
## Description

When the titles of the markdown file are too many,  the right catalog of our mkdocs-material is very long.

### Expected behavior

I hope our mkdocs-material could expand and fold all the high level titles, we can expand and fold the title's set by click.

### Actual behavior

The right catalog of our mkdocs-material is too long.

**Comment by squidfunk** [comment]
See #695. I would triage this as an edge case. There are no plans to implement such a feature, as it can be easily fixed by restructuring your documentation, e.g. splitting a long page into a section with multiple pages, which almost probably is a better solution than hiding content.

**Comment by squidfunk** [comment]
Housekeeping.
