### ISSUE TITLE
Google Analytics with tracking code

### ISSUE THREAD

**Issue by digitalcraftsman** [squidfunk/mkdocs-material#11]
Hi @squidfunk,

first of all thank you for creating such an awesome theme :+1: 

After browsing the templates of this theme I saw that you implemented Google Analytics. Would it be possible to integrate tracking with a custom tracking code?

Cheers,
Digitalcraftsman

**Comment by squidfunk** [comment]
Hi @digitalcraftsman,

could you be more specific? What do you mean by tracking code? If I search for tracking code in conjunction with Google Analytics I get this, and that's what's basically implemented:
https://support.google.com/analytics/answer/1008080?hl=en

Best regards,
Martin

**Comment by digitalcraftsman** [comment]
Thanks for your quick response. To set up Google Analytics I usually copy this [snippet](https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet) into my website.

It requires an ID like `UA-XXXXX-Y` that you need to generate and insert into the snippet.

**Comment by squidfunk** [comment]
This is already implemented. Just add your ID to your `mkdocs.yml`:

``` yaml
google_analytics:
  - UA-73586301-1
  - auto
```

Is this what you meant? If so, maybe we should mention it in the documentation.

**Comment by digitalcraftsman** [comment]
Thank you for the clarification. It just confused me that Google Analytics was implemented but the documentation didn't mentioned a word about the ID or any other steps for the setup.

It would be great if you could mention this in the documentation. It felt a bit weird that GA works out of the box.

**Comment by squidfunk** [comment]
It's mentioned in the official MkDocs documentation and Material basically implemented all of the MkDocs features, but yes, you're right - I will add it to the docs!

**Comment by digitalcraftsman** [comment]
Currently, I only experimented a bit with MkDocs since I'm porting your theme to [Hugo](https://gohugo.io). In a nutshell, Hugo is a static site generator like Jekyll but much faster. 

Of couse I'll acknowledge you as the original creator since otherwise the port wouldn't be possible.

**Comment by squidfunk** [comment]
Ah, funny thing, already heard of it, but I sticked with MkDocs for documentation, as it's really good for that. Please keep me updated on the progress!

**Comment by digitalcraftsman** [comment]
The port is done so far. Take a look at the [demo](https://digitalcraftsman.github.io/hugo-material-docs/). Full support for a search localization are still missing. But Hugo should support them in one of the next versions. Read the roadmap in the demo for more information.

**Comment by squidfunk** [comment]
Ah cool, well done! I like it :-) Thanks for acknowledging me.

**Comment by digitalcraftsman** [comment]
> Thanks for acknowledging me.

That's the least I can do :smile:
