### ISSUE TITLE
Add 'selected' as toc item state

### ISSUE THREAD

**Issue by jakauppila** [squidfunk/mkdocs-material#1102]
## Description

It'd be great if there was a `data-md-state` of `selected` in the toc to allow for some styling of the currently selected item.

Basically, I want to replicate the styling available in AWS's documentation: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/concepts.html

**Comment by squidfunk** [comment]
Sure, feel free to PR. Otherwise, I may add it at some point in the future when I find some time.

**Comment by squidfunk** [comment]
Implemented in the (currently not building) `refactor/rxjs-typescript` branch:

<img width="1552" alt="Bildschirmfoto 2019-10-29 um 17 51 43" src="https://user-images.githubusercontent.com/932156/67789800-e06e8300-fa74-11e9-9d4e-a105e566f460.png">

This feature will be part of 5.0.0 which is separately tracked in #1306. With some JavaScript it will now also be possible to style the containing parent sections, so if a `h3` is active, the `h1` and `h2` are now also tracked.

**Comment by squidfunk** [comment]
[Material for MkDocs 5.0.0rc1](https://github.com/squidfunk/mkdocs-material/issues/1498) is out which fixes this issue 😀 Let's test and improve it together!
