### ISSUE TITLE
Minified templates are not a good basis for customization

### ISSUE THREAD

**Issue by mike-schiller** [squidfunk/mkdocs-material#1113]
What's the recommended path for customizing base.html, main.html, and the partials?

Prior to 4.3.0, I would grab any file I needed to customize from the `material/` directory and include it in my build. Now, however, those are minimized. While that does save in bandwidth, it also makes them a challenge to work with when customizing. (Perhaps I'm missing the obvious, but I'm not finding any cli tools that will pretty-print a jinja2 template.)

Using the files in `src` works for many. However, at least `base.html` has some templating that causes it to differ from the final output file. Assuming you don't have in interest in reverting the behavior to what it was prior to 4.3.0, would it be possible to have non-minimized html files output to an additional/alternate directory?

**Comment by squidfunk** [comment]
> Perhaps I'm missing the obvious, but I'm not finding any cli tools that will pretty-print a jinja2 template

You should be able to use any HTML pretty printer, as Jinja templates should always be syntactically valid HTML.

I would recommend grabbing the templates from the `src` directory. Could you elaborate on why that doesn’t work for `base.html`?

**Comment by mike-schiller** [comment]
Thanks, with what I've seen with HTML pretty printers so far, they do format the templates but tend to leave `{% %}` blocks on the end of lines which makes it a bit difficult to read conditional logic in the templates. But, I'll play with settings and a couple other formatters to see if I can get better results.

As for what interferes in `base.html`, it looks like there's some templating between what' in `src/` vs what's in `material/` based on `$` symbols. That's what prevents using `src/base.html` in my custom theme directory.

Specifically...

https://github.com/squidfunk/mkdocs-material/blob/master/src/base.html#L96

and

https://github.com/squidfunk/mkdocs-material/blob/master/src/base.html#L363

**Comment by squidfunk** [comment]
> As for what interferes in base.html, it looks like there's some templating between what' in src/ vs what's in material/ based on $ symbols. That's what prevents using src/base.html in my custom theme directory.

That's a good point, so using `src` doesn't work. I just looked for some online HTML formatters and the only one that put Jinja tags on new lines was actually [this one](https://www.freeformatter.com/html-formatter.html#). The main reason why I minified the sources is the fact that most PRs make changes in the `material` folder, as they think that this is the source of truth. Collapsing all whitespace also had the upside of providing a smaller payload to serve. I really don't want to expand the templates again, but there must be a better way than to provide a copy of the template structure with the Material theme.

I think the best way would be to provide a small script for beautification and minification of the templates and bundle it with the theme. This enables users to make changes and minify the source afterwards again. However, I would like to use a Python-based HTML formatter, as I don't want to introduce another runtime. Would you willing to explore this direction?

**Comment by mike-schiller** [comment]
> The main reason why I minified the sources is the fact that most PRs make changes in the material folder, as they think that this is the source of truth. 

That seems like a pretty good reason to keep the minificaiton in place.

> I think the best way would be to provide a small script for beautification and minification of the templates and bundle it with the theme. This enables users to make changes and minify the source afterwards again.

That seems good. Would the beautifier be a small shell script bundled with mkdocs-material that runs a python command similar to the `mkdocs` command itself? Perhaps `mkdocs-material beautify partials/nav-item.html .` would extract a beautified version of the nav-items template from `site-packages` to the current directory?

I don't necessarily need the minification as we'd check into git any files we customize. Having minification be, perhaps optionally, part of `mkdocs build` would be potentially useful.

Freeformatter is the one I tried as well. It's definitely better than the minified version and other options, but I do find some of it tough to read - at least with `base.html`.

**Comment by squidfunk** [comment]
I found this yesterday: https://github.com/byrnereese/mkdocs-minify-plugin

Maybe we could test-drive it and revert the minification of the templates, if the outcome is the same. Honestly, I haven't really thought about customization when making this change, so thanks for bringing it up. If it doesn't work well, we could go down the path with the custom beautify command.

> Would the beautifier be a small shell script bundled with mkdocs-material that runs a python command similar to the mkdocs command itself?

That was the basic idea, yes.

**Comment by shaneholloman** [comment]
@squidfunk 

I would love to have an override function so I can condense lists

Is there a best practice for this while using mkdocs and your wonderful theme?

## Target css block

```css
.md-typeset ol li, .md-typeset ul li {
    margin-bottom: .5em;
    margin-left: 1.25em;
}
```
![image](https://user-images.githubusercontent.com/1563909/59550336-91401e00-8fbd-11e9-96ab-b9eecec1cd47.png)

## Override with:  

```css
.md-typeset ol li, .md-typeset ul li {
    margin-bottom: 0em;
    margin-left: 1.25em;
}
```

## To get:

![image](https://user-images.githubusercontent.com/1563909/59550351-d2383280-8fbd-11e9-95f2-a7794a926b0e.png)

**Comment by squidfunk** [comment]
It looks like you already found the solution - just add an [additional stylesheet](https://squidfunk.github.io/mkdocs-material/customization/#additional-stylesheets) with your adjustments and you should be good to go.

**Comment by squidfunk** [comment]
@mike-schiller After trying the [mkdocs-minify-plugin](https://github.com/byrnereese/mkdocs-minify-plugin) I came to the conclusion that minification is best taken care of by a plugin and not through template minimization itself. The point you mentioned are valid: customization is harder. Minification through the plugin will also minify the rendered Markdown content, which is an additional upside. I will integrate it with the theme and add some documentation.

**Comment by shaneholloman** [comment]
the above was adjusting the browser. yes thank you I just was this: https://squidfunk.github.io/mkdocs-material/customization/

**Comment by squidfunk** [comment]
As of 4.4.0, the templates are now, again, unminified, making customization easier. Minification should now be delegated to the `mkdocs-minify-plugin`, as denoted in my last comment. Documentation was added [here](https://squidfunk.github.io/mkdocs-material/getting-started/#plugins).

**Comment by wilhelmer** [comment]
Co-author of the plugin here. Setting `minify_js` to `true` doesn't do anything unless you specify the files to be minified under `js_files`. So I suggest that you either remove the `minify_js` entry in the documentation or specify some template files that should be minified.

Currently, the documentation gives the impression that the plugin will automatically minify all your JS files, which it doesn't.

**Comment by squidfunk** [comment]
@wilhelmer - thanks, we should just remove `minify_js` from the docs.
