### ISSUE TITLE
Option to keep site name for overridden page title

### ISSUE THREAD

**Issue by lukasgeiter** [squidfunk/mkdocs-material#1124]
I would like to [override the page title using metadata](https://squidfunk.github.io/mkdocs-material/extensions/metadata/#page-title) while keeping `- {site name}` included in the `<title>` of the page. My use case: I want to specify a shorter title for the navigation for pages which have a long H1 title. The `<title>` tag however should still include the name of the site to stay consistent.

This is a feature request / proposal. If you think such an option would make sense, I'd be happy to implement it and send a PR. In that case, suggestions for the name and exact behavior of this feature would be welcome as well.

**Comment by squidfunk** [comment]
You could just override the `htmltitle` block and append the title - see the customization guide on block overriding:

https://github.com/squidfunk/mkdocs-material/blob/87e2d14dd771c6d64196487066379d4c49fc187a/src/base.html#L100-110

**Comment by lukasgeiter** [comment]
Oh yeah that's definitely better than introducing another option. Thanks!
