### ISSUE TITLE
When click upper-left corner icon, the page change to 0.0.0.0:8080

### ISSUE THREAD

**Issue by bq1028** [squidfunk/mkdocs-material#1131]
Hi, thank you for what you did on this nice project. but now i need your help on below issue.

When I click upper-left corner icon, the page change to 0.0.0.0:8080
I start the service as below:
mkdocs serve -a 0.0.0.0:8080 and the server behind nginx reverse proxy.

the theme i used is material

I test the other theme like mkdocs and bootstrap4, there is no such problem (no change any settings)

the test site is https://www.nowellzhang.top/

**Comment by bq1028** [comment]
Hi All, 
I fixed this problem using below way:
Change run mode from dev to prod,  namely
````
mkdocs serve -a 0.0.0.0     // (dev mode)
mkdocs build                     //( prod mode)
http-server . -p 8080 

```

**Comment by squidfunk** [comment]
MkDocs is not meant to be run as a server. It is a static site generator. You can use nginx for reverse proying to your www root where the result of running `mkdocs build` is located. Furthermore, this is not a Material issue, but relates entirely to MkDocs.
