### ISSUE TITLE
Consider using font-display: fallback for Google Fonts

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#1133]
It's great that Google Fonts supports the `display` parameter. I found that setting `display=swap` always displays the fallback font immediately and switches - even if the page and Google font loads **_very_** fast which can be a bit annoying.

I suggest to instead use `display=fallback`. This will only show the fallback font after about 100ms which means the user doesn't see the font switching, but will never need to wait more than 100ms until they can start reading the content.

I've done quite a bit of testing on this on several different sites and prefer but this - but it's just my personal opinion though - so feel free to close this, but give it a try and see what you think. If you set  `display=fallback` you'll still get a pass for it on Google Lighthouse which is good.

REF: https://font-display.glitch.me/

**Comment by squidfunk** [comment]
@xen is the one who PR'd `font-display: swap` in https://github.com/squidfunk/mkdocs-material/pull/1103 - any thoughts?

**Comment by xen** [comment]
I think it is pretty reasonable arguments. My first intention was to make rendering better on long pages. But I didn't dig so deep. If this trick works on the mobile then it probably better to accept.

**Comment by squidfunk** [comment]
Thanks! @coliff could you PR this? Happy to merge.

**Comment by coliff** [comment]
Hi - I made a PR by changing the file in `src`.. I can't make a build of the site so sorry for not following your contribution guidelines. :-\
