### ISSUE TITLE
Navigation Bar Hiding Threshold

### ISSUE THREAD

**Issue by SergioMartin86** [squidfunk/mkdocs-material#1149]
## Description

Not a bug, but an unwanted behavior.

I find that the navigation sidebar (left) disappears way to eagerly with the window width (circa 1200px). Furthermore, it disappears before the ToC sidebar (right).

Some of our users have been confused by the lack of menu even when the window is still rather large. And some thought the ToC was in fact the nav bar.  

Note: We know and love the fact that sidebars hide with window width, but we'd like the thresholds to be smaller or configurable.

### Expected behavior

I researched ways to change this behavior so that:
- The ToC disappears first, before Nav bar does; inverting their hiding order.
- Change the hiding/collapse threshold to a smaller pixel count (e.g., 900/600 instead of 1200/900)
- Preventing the navigation bar from disappearing altogether.

Any of those solutions would suffice but there seems to be no obvious way to do it. I tried with custom css and js scripts, but I'm not good enough with those.

### Actual behavior

See it for yourself: https://www.cse-lab.ethz.ch/korali/

I've successfully hidden the ToC from the page so that my users do not confuse it with the nav menu, but that did not change the threshold, so the nav bar still hides at a really big px count (1200?).

### Steps to reproduce the bug

1. Visit https://www.cse-lab.ethz.ch/korali/
2. Increase/Decrease your window size and see the left bar disappear.

### Package versions

* Python: 3.7.3
* MkDocs: 1.0.4
* Material: 4.3.1

### Project configuration

site_name: Korali
repo_name: 'cselab/korali'
repo_url: 'https://github.com/cselab/korali'
edit_uri: ''

nav:
  - Home: index.md
  - Installation:
     - 'Installation Guide': install/install.md
     - 'System Requirements': install/requirements.md
     - 'Release Notes': install/notes.md
  - Tutorials:
     - 'A.1 - Optimization': tutorials/a1-optimization/optimization.md
     - 'A.2 - Sampling': tutorials/a2-sampling/sampling.md
     - 'A.3 - Bayesian Inference': tutorials/a3-bayesian/bayesian.md
     - 'B.1 - Checkpoint/Restart': tutorials/b1-restart/restart.md
     - 'B.2 - Constrained Optimization': tutorials/b2-constrained-optimization/constrained-optimization.md
     #- 'B.3 - Distributed Conduit': tutorials/distributed/distributed.md
     #- 'B.4 - Nonintrusive Conduit': tutorials/nonintrusive/nonintrusive.md
     #- 'C.1 - MPI Model': tutorials/mpi/mpi.md
     #- 'C.2 - Nonintrusive Cluster': tutorials/bayesian/bayesian.md
     #- 'C.3 - C++/Python Interaction': tutorials/bayesian/bayesian.md
  - User Manual:
      - Basics: usage/basics.md
      - Problems:
          - Direct Evaluation: usage/problems/direct.md
          - Bayesian:
            - Direct Likelihood: usage/problems/bayesian/direct.md
            - Reference Likelihood: usage/problems/bayesian/reference.md
      - Solvers:
          - Optimizers:
            - CMA-ES: usage/solvers/optimizers/cmaes.md
            - Differential Evolution: usage/solvers/optimizers/diffevo.md
          - Samplers:
            - MCMC: usage/solvers/samplers/mcmc.md
            - TMCMC: usage/solvers/samplers/tmcmc.md
      - Conduits:
          - Semi-Intrusive: usage/conduits/semi-intrusive.md
          - Distributed: usage/conduits/distributed.md
          - Nonintrusive: usage/conduits/nonintrusive.md
      - Models:
          - Simple: usage/models/simple.md
          - Rerefence: usage/models/reference.md
          - Constraint: usage/models/constraint.md
      - Results:
          - Plotting Results: usage/results/#plotting-results
          - Exporting Results: usage/results/#exporting-results
          - Resume Execution: usage/results/#resume-execution
  - Development:
    - Repositories: development/repositories.md
    - Testing: development/testing.md
    - Doxygen: development/doxygen/annotated.html
  - About Us: aboutus.md

theme:
    name: material
    palette:
        primary: 'light blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo: 'images/logo.png'
    favicon: 'images/favicon.ico'

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - admonition
  - codehilite

extra_css:
    - style.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  
google_analytics: ['UA-43580832-2', 'https://www.cse-lab.ethz.ch/korali/']

Extra .css:

.center {
    display: block;
    margin: 0 auto;
}

h1 {
  text-align: center;
  line-height: 10px !important;
  font-weight: bold !important;
  color: rgb(35, 127, 188) !important;
}

h2 {
  font-weight: bold !important;
}

.md-content {
  max-width: 45rem !important;
}

.md-sidebar--secondary {
  display: none;
}

.md-sidebar__inner{
  font-weight: bold !important;
  color: rgb(35, 127, 188);
}

.md-sidebar--primary{
  background-image: url("images/korali-back.png");
  background-repeat: no-repeat;
  background-color: rgb(252, 252, 255);
  background-position: 50% 50%;
  visibility: visible !important;
}

li .md-nav__item{
  font-weight: normal !important;	
}
.md-nav__title {
  #display: none;
  text-align: center;
  font-size: 1.5em !important;
  color: rgb(15, 107, 168);
}

.md-content {
margin-right: 0;
}

### System information

* OS: Windows 10
* Browser: Google Chrome

Hope this has an easy solution that I failed to see. I really love this theme and I don't want this small issue to lessen the experience.

Thank you very much.

**Comment by squidfunk** [comment]
> Note: We know and love the fact that sidebars hide with window width, but we'd like the thresholds to be smaller or configurable.

Within the CSS, the breakpoints are defined in a SCSS map:

https://github.com/squidfunk/mkdocs-material/blob/c8f44f0ae8649b4c34e94522cace873dbe84937d/src/assets/stylesheets/_config.scss#L38-L52

You could fork the theme, change those values and recompile it. However, note that there are some media queries (currently) hard coded [in JavaScript](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/javascripts/application.js) which also need to be adjusted. All event listeners are documented, so it should be quite easy to go through the file, make your adjustments and recompile the theme as stated in the customization section. You should probably start here:

https://github.com/squidfunk/mkdocs-material/blob/c8f44f0ae8649b4c34e94522cace873dbe84937d/src/assets/javascripts/application.js#L239-L253

**Comment by SergioMartin86** [comment]
Yes, I'll fork it and play around with these values to reach my desired threshold. 

I'm only concerned that by forking, I'll be losing access to upcoming features and device compatibilities, but I can always re-adjust my fix if necessary.

Thanks for your awesome work.

**Comment by squidfunk** [comment]
Yes, that's the risk. However, I always try to rule out any breaking changes between minor releases. I'm sorry that it's not easier to make deeper adjustments – I've got plans to make the JavaScript configurable (after converting it into TypeScript) but I don't know when I might find the time to refactor the code.
