### ISSUE TITLE
Question about app.init

### ISSUE THREAD

**Issue by vsoch** [squidfunk/mkdocs-material#1150]
Hey @squidfunk ! 

I opened an issue a long time ago about search not working (I was converting to a jekyll theme) and I'm glad to report that I got it figured out! I have one quick question about how the app.init works (to not result in an error).

For example, on the main page I see:

```js
<script>app.initialize({version:"0.17.4", url:{base:'.'}})</script>
```
And then one level up (e.g., /about/) we see:

```js
<script>app.initialize({version:"0.17.4", url:{base:'..'}})</script>
```
I assumed this was a relative path from the page to the root, but it doesn't seem to work with three dots. I am adding posts that are three levels in, like `/baseurl/2019/post-title/` and I'm wondering how the app.init command should look on the page? I've tried variations of dots, and then relative paths (`../../`) but haven't hit something that works yet.

**Comment by squidfunk** [comment]
It must resolve to your doc root, essentially to the level from which assets are resolved. Relative paths are used so you can host docs in subdirectories.

**Comment by vsoch** [comment]
Understood, thanks for the speedy response! My question is answered, so closing issue.
