### ISSUE TITLE
Support hierarchical levels on left-side menu 

### ISSUE THREAD

**Issue by leonardean** [squidfunk/mkdocs-material#1163]
![09_55_02__07_09_2019](https://user-images.githubusercontent.com/2738010/60853771-24bce580-a230-11e9-9552-284dec1f136f.jpg)
Hi, wanted to ask your help on how I can customize mkdocs-materials to support hierarchical levels on left-side menu. Thx!

**Comment by squidfunk** [comment]
You just have to nest the pages in your `mkdocs.yml`, see [the official docs](https://www.mkdocs.org/user-guide/writing-your-docs/), and it will be rendered hierarchically.

**Comment by squidfunk** [comment]
Housekeeping. Closing as answered.
