### ISSUE TITLE
Tables: Get static first row and first column

### ISSUE THREAD

**Issue by sappelhoff** [squidfunk/mkdocs-material#1171]
I have a very [big table](https://bids-specification.readthedocs.io/en/stable/99-appendices/04-entity-table.html) that is hard to read. 

I would like the first row of the table (the header), and the first column of the table to "stick" while I am browsing the table. This behavior would be similar to how the Mkdocs Material "header" also sticks when scrolling down the general page.

Is that possible with Mkdocs Material? Or with Mkdocs in general?

**Comment by squidfunk** [comment]
> Is that possible with Mkdocs Material?

Nope. You could however add some custom CSS and JavaScript to implement the behavior yourself. Here is a promising example:
https://codepen.io/tfzvang/pen/WQBwVo

> Or with Mkdocs in general?

MkDocs does only provide the logic for static site generation. The functionality you described must be implemented by a theme which Material does not.

**Comment by sappelhoff** [comment]
Alright, I'll look into it. Thanks for your quick reply!
