### ISSUE TITLE
Add Markdown Inside HTML Blocks like Markdown Extra

### ISSUE THREAD

**Issue by amadfida** [squidfunk/mkdocs-material#118]
Markdown Extra [supports](http://pythonhosted.org/Markdown/extensions/extra.html) markdown inside HTML blocks such as

``` 
<div markdown="1">
This is *true* markdown text.
</div>
``` 
will result in 

``` html
<div>
<p>This is <em>true</em> markdown text.</p>
</div>
```
However this is not working with the theme. I have tried adding

```
markdown_extensions:
  - markdown.extensions.extra
```

this causes more problem that fixes.

**Comment by squidfunk** [comment]
Can you please elaborate what the problems are and what you are trying to fix? And please stick to the issue template, especially in those cases.

**Comment by amadfida** [comment]
## Description

I have a index.md which contains HTML, and more specifically `<div>` tags - which intern contain some markdown such as [My Link](/my page). However any markdown inside `<div>` is not processed.

Based on some research it seemed that Markdown Extra includes an option i.e. markdown=1 added to div tag should allow markdown to get rendered.

### Expected behavior

```
<div markdown="1">
This is *true* markdown text.
</div>
````

will produce

```
<div>
<p>This is <em>true</em> markdown text.</p>
</div>
```

### Actual behavior
```
<div markdown="1">
This is *true* markdown text.
</div>
````

results in 

```
This is *true* markdown text.
```

### Package versions

- Python: `Python 2.7.13`
- MkDocs: `mkdocs, version 0.16.1`
- Material: `Version: 1.0.2`

### System information

- OS: macOS Siera 10.12.2

**Comment by squidfunk** [comment]
Thank you, much clearer now. Are you also using pymdownx.extra? See https://facelessuser.github.io/pymdown-extensions/usage_notes/#incompatible-extensions

**Comment by squidfunk** [comment]
And please provide your mkdocs.yml

**Comment by makshh** [comment]
Did you try `<div markdown="span">`?

**Comment by amadfida** [comment]
Here is my mkdocs.yml

```
# Project information
site_name: Documentation
site_url: http://xxx.xxx.xxx

# Copyright
copyright: 'Copyright &copy; 2017 XXX'

# Documentation and theme
theme: material
theme_dir: theme

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Page tree
pages: 
  - Welcome: 'index.md'
  - Getting Started:
    - Navigation and UI: 'getting-started/navigation-and-ui.md'
    - Getting Data In: 'getting-started/getting-data-in.md'
    - Searching: 'getting-started/search.md'
    - Reports: 'reporting-dashboards/reports.md'
  - For Administrators:
    - Data Management:
      - Attributes: 'data-management/attributes.md'
      - Data Models: 'data-management/data-models.md'
      - Data Model Defaults: 'data-management/data-model-defaults.md'
    - Data Integration:
      - Data Servers: 'data-integration/data-servers.md'
      - Data Sources: 'data-integration/data-sources.md'
      - Data Mapping: 'data-integration/data-mapping.md'
      - Scheduled Syncs: 'data-integration/scheduled-syncs.md'
      - Rules: 'data-integration/rules.md'
    - User interface:
      - Views: 'user-interface/views.md'
      - Visualizations: 'user-interface/visualizations.md'

extra:
  logo: 'images/logo.png'
  palette:
    primary: 'blue grey'
    accent: 'blue'
  font:
    text: 'Source Sans Pro'
    code: 'Roboto Mono'    
  version: 1.0

extra_css:
  - 'stylesheets/extra.css'
````

**Comment by amadfida** [comment]
```
<div markdown="span">?
```
I just tried but didn't effect the outcome

**Comment by amadfida** [comment]
however i added 

```
pymdownx.extra
```
 to my extensions and 

```
<div markdown="span" 
```

seems to be working - i am assuming thats it?

**Comment by amadfida** [comment]
Closing as its working now with my last comment.

**Comment by squidfunk** [comment]
Okay, maybe it is some incompatibility of some extensions then. I will investigate if I have the time.

**Comment by facelessuser** [comment]
In regards to pymdownx:

All you need is `markdown="1"`.  `pymdownx.extra` includes all the normal `markdown.extra` stuff but replaces key extensions with pymdownx variants.  If you are including `pymdownx.extra`, you should get that functionality (but then don't re-include what `extra` is including).  Alternatively, if you don't want to use `pymdownx` stuff, you can just use `markdown.extensions.extra`.

If you are using `pymdownx` extension a la carte, you can use `pymdownx.extrarawhtml` to get the `markdown="1"` functionality (I split it out so people could use it without having to use **all** the extra configuration.

If you have `pymdownx` specific questions or bugs, feel free to throw them my way at the official repository.  Now that `pymdownx` has more visibility from people, I imagine people may shake some things out that I've missed.

**Comment by dom-gunstone** [comment]
I'm not sure if this is the same issue detailed above so I'll post here instead of creating a new issue.

Am I right in thinking this should work, or does markdown inside HTML blocks not work? Thanks in advance.

`some_template.html`
```html
{% extends "base.html" %}

{%- block content -%}
  <h1> {{ page.title }}</h1>
  <div markdown>
    This is *true* markdown text.
  </div>
  {{ page.content }}
{%- endblock -%}
```

`mkdocs.yml`
```yml
markdown_extensions:
  - pymdownx.extra
```

`some_page.md`
```md
---
...
template: some_template.html
---
...
```

**Comment by alexvoss** [comment]
You are trying to write Markdown in a Jinja2 template. That is not going to work because the template is not run through the Markdown processor, only your page content is.

**Comment by dom-gunstone** [comment]
@alexvoss Great, thanks for confirming.
