### ISSUE TITLE
Icon fonts not displayed in Firefox 68

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#1185]
When viewing a Material site locally (using file:// protocol) in Firefox 68, the icons (material + font awesome) won't be displayed: 

![material-icons-error2](https://user-images.githubusercontent.com/2234833/61539224-55282f00-aa3b-11e9-8472-72bc10e70dfc.jpg)

The console shows CORS (cross-origin resource sharing) errors related to the fonts.

This seems to be caused by a [security patch in Firefox 68](https://support.mozilla.org/en-US/questions/1264762). See also: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp

There's a [bug filed at Mozilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1566172) for this, but it's unclear if and when this will be fixed. Until then, the Material theme will not render properly when viewed locally in Firefox.

**Comment by squidfunk** [comment]
We bundled all font files for GDPR compliance (see #739) with the theme. You could override the base template and replace the icon font links back with their original HTTPS links, but we cannot provide both with the theme. It's either one or the other.

**Comment by squidfunk** [comment]
Furthermore serving stuff locally is something I would regard as not worth optimizing for.

**Comment by wilhelmer** [comment]
We offer our documentation both as an online version and zipped for offline use. Also, it's bundled with our software and called locally from there. Most of our competitors do the same. So local use isn't that esoteric, especially not in the world of technical documentation.

Anyway, I don't expect you to fix this, if it's possible at all, I mainly opened this issue so others know about it ("known issue").

**Comment by squidfunk** [comment]
As said, it's not fixable. Either we adhere to GDPR and bundle web fonts with the theme, or we link to external fonts. You could, however write a simple post processing script which replaces local web ffont links with CDN links.

**Comment by squidfunk** [comment]
Side note: I'm currently replacing the Material icon font with the SVG versions, so this issue should very likely be resolved soon 😊No more icon fonts!
