### ISSUE TITLE
Feature request: Support for other analyitcs

### ISSUE THREAD

**Issue by berot3** [squidfunk/mkdocs-material#1187]
## Description

When mkdocs is hosted on LAN only, google analytics is not an option.

### Expected behavior

there is a related issue for mkdocs: https://github.com/mkdocs/mkdocs/issues/607

maybe mkdocs-material can also support for example piwik?

### Actual behavior

as integration only google analytics is supported in the config [1]

[1]: https://github.com/squidfunk/mkdocs-material/blob/master/docs/getting-started.md#google-analytics

**Comment by squidfunk** [comment]
Please see https://github.com/mkdocs/mkdocs/issues/1794#issuecomment-492702777 over at MkDocs (our main upstream repository) for a explanation why we won't integrate things like this into Material.

**Comment by squidfunk** [comment]
Housekeeping.

**Comment by squidfunk** [comment]
If somebody wants to add and maintain support for other providers – it's very simple, please read https://github.com/squidfunk/mkdocs-material/pull/4847#issuecomment-1378467860. We're happy to advertise a third-party extension on our docs, so a PR with a docs change is appreciated.
