### ISSUE TITLE
Unknown contributor deploying with Docker

### ISSUE THREAD

**Issue by tzinm** [squidfunk/mkdocs-material#1194]
## Description

I am running the docker command `docker run --rm -it -v ~/.ssh:/root/.ssh -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy`with extra options like `-m "First commit` and `--remote-branch master`, and it works fine.

The "problem" is that always appear an **Unknown** contributor for each commit doing by Docker.

### Expected behavior

I would like to appear my git username.

### Actual behavior

**Unknown** contributor for each commit doing by Docker.

### Steps to reproduce the bug

Deployment with the docker command:

`docker run --rm -it -v ~/.ssh:/root/.ssh -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy`

### System information

* OS: Docker in MacOS

**Comment by squidfunk** [comment]
Off the top of my head: you could try to mount the folder containing your `gitconfig` file as a volume.

**Comment by tzinm** [comment]
I try and it works!!

I run this command:

```bash
docker run --rm -it -v ~/.ssh:/root/.ssh -v ~/.gitconfig:/root/.gitconfig -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy
```

Thanks!! 😃

**Comment by squidfunk** [comment]
Awesome, thanks for sharing!
