### ISSUE TITLE
Docker Instance 4.4.0 Not Up To Date with mkdocs-material

### ISSUE THREAD

**Issue by jj-jitterbit** [squidfunk/mkdocs-material#1199]
## Description

Though I have pulled the 4.4.0 image, `pip list` shows the version of `mkdocs-material` is 4.1.1

### Expected behavior

After logging in to the Docker image (using `docker exec -ti mkdocs-serve /bin/sh`) I expected `pip list` to show that the mkdocs-material was 4.4.0.

### Actual behavior

```
# pip list
Package            Version
------------------ -------
Click              7.0    
Jinja2             2.10   
livereload         2.6.0  
Markdown           3.1    
MarkupSafe         1.1.1  
mkdocs             1.0.4  
mkdocs-material    4.1.1  
pip                19.0.3 
Pygments           2.3.1  
pymdown-extensions 6.0    
PyYAML             5.1    
setuptools         40.8.0 
six                1.12.0 
tornado            6.0.2  
wheel              0.33.1 
```

### Steps to reproduce the bug
```
$ docker pull squidfunk/mkdocs-material:
$ docker run -it --rm --name=mkdocs-serve \
             -p 8000:8000 \
             -v "$(pwd)/source:/docs" \
             squidfunk/mkdocs-material serve
```
In another terminal window:
```
$ docker exec -ti mkdocs-serve  /bin/sh
# pip list
```
### System information

* OS: macOS running the Docker instance

**Comment by squidfunk** [comment]
I tried to reproduce your problem to no avail. I pulled `squidfunk/mkdocs-material:latest` and `squidfunk/mkdocs-material:4.4.0`, both showing `4.4.0` for `pip show mkdocs-material`:

![Bildschirmfoto 2019-08-06 um 09 03 26](https://user-images.githubusercontent.com/932156/62518133-19f27200-b829-11e9-8e19-1169e09be3e1.png)

Please check, if the sha256 of the image is:

```
de394f6fafa405bdb21b44b37bc96010bcf4cb83036962060867ddc6100a53c8
```

If it isn't, you could try and delete all squidfunk/mkdocs-material` images you pulled. and re-pull the latest.

**Comment by squidfunk** [comment]
Also note that the output of `pip list` significantly differs for the latest image and the image you're running:

```
Package              Version
-------------------- -------
Click                7.0    
htmlmin              0.1.12 
Jinja2               2.10.1 
jsmin                2.2.2  
livereload           2.6.1  
Markdown             3.1.1  
MarkupSafe           1.1.1  
mkdocs               1.0.4  
mkdocs-material      4.4.0  
mkdocs-minify-plugin 0.2.1  
pip                  19.1.1 
Pygments             2.4.2  
pymdown-extensions   6.0    
PyYAML               5.1.1  
setuptools           41.0.1 
six                  1.12.0 
tornado              6.0.2  
wheel                0.33.3 
```

**Comment by jj-jitterbit** [comment]
Thanks for this. I do have the same sha256 image, but Docker seems to be confused as to which ones to use. After checking the instructions at https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes, I removed all `squidfunk/mkdocs-material` images and then started again. Now, I have a correct `pip` list to match the example above.
