### ISSUE TITLE
Add a back-to-top button

### ISSUE THREAD

**Issue by digitalcraftsman** [squidfunk/mkdocs-material#12]
Hello @squidfunk,

it would be useful to implement a back-to-top button if you read a longer documentation page and need to scroll a lot in order to reach the menu at the top again.

**Comment by d0ugal** [comment]
The menu is always visible on the left, and on smaller screens there is always a menu button at the top... so unless I am missing something, I don't think this is needed :smile:

**Comment by digitalcraftsman** [comment]
You're right. First it looked a bit empty in the sidebar if currently no links are present and the content is long.

Forget this issue.

**Comment by squidfunk** [comment]
@d0ugal I think that's a valid point. The theme has so much navigation (drawer, header, footer), that I wouldn't consider adding it at the moment. The drawer on the right is reachable from everywhere on mobile and scrolls with the content on desktop.
