### ISSUE TITLE
Suggestion: Remove unneeded title attribute from sidebar links

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#1207]
## Description

Currently the links in the sidebar have `title` attribute so hovering over a link shows a tooltip with the same text as the link. It's a bit distracting and unnecessary I think. Could these be removed?

Example: 

![image](https://user-images.githubusercontent.com/1212885/63175728-9124d300-c07f-11e9-93d0-f14deaecbd81.png)

### Expected behavior

would prefer `title` to not be on text links in sidebar

### System information

* OS: Windows 10 
* Browser: Microsoft Edge (Chromium)

**Comment by squidfunk** [comment]
I put them there because the W3C validator complained that it was missing, but I guess from todays perspective this would be considered an antipattern. I think we already did some research somewhere on this topic, but can't find it.

**Comment by coliff** [comment]
Yep, I remember that you previously merged a PR I made for removing unneeded Title from links in the footer. #585.

I've quite certain that title tags are not needed on text links here. The only possible reason that it could be needed that I can think of would be if the text was shortened or truncated so if you hover over the title tag would show the full title.

**Comment by squidfunk** [comment]
Ah yes, I remember. If you like, you can sift through the source and remove all unnecessary titles in a PR. Happy to merge.

**Comment by coliff** [comment]
cool. would happy to do that... probably Monday morning but maybe over the weekend. I had trouble making a build before though -is it okay to just make changes in `src` ?

**Comment by squidfunk** [comment]
Would be interesting where you had trouble but yeah, basically it’s fine because I will build it anyway before the next release.
