### ISSUE TITLE
performance issue with huge number pages

### ISSUE THREAD

**Issue by urna** [squidfunk/mkdocs-material#1210]
currently the site structures are hosted in every page, i am using it to build a library let's say 1 million pages, there will be performance issue to handle such huge number pages and also makes every page much bigger to contain this site structure.

can we have a solution for this situation?

**Comment by squidfunk** [comment]
What do you mean by the „site structure“ exactly? Navigation? Yes, every page contains the whole navigation which would not scale to 1M pages. How would you like to structure a site with that many pages?


Other than that, with 1M pages, search will not work in the browser, as indexing would take far too long. Also, the MkDocs build will probably run out of memory before termination.

A solution might be to split your page into multiple MkDocs sites which would give you build parallelization.

**Comment by urna** [comment]
1. Yes, i mean "navigation" menu items. The reason why so many pages is: i am using it to host a online library, similar like Microsoft "MSDN" online help(too much infomation)

2. For search, i can disable it and just use normal backend search, that's easy. And MkDocs build out of memory issue, i have not try it but i can add more and more memory or optimize the building process.

3. Yes, i am thinking to spit pages into n MkDocs sites, but that would looks like not as a whole. However, there are other ways to handle it. But i am thinking how to modify MkDocs or your project to support huge number pages such as my needs.

**Comment by squidfunk** [comment]
Thanks for the explanation. Can I consider your question answered? There's obviously no other way than partitioning your dataset into multiple MkDocs sites and cross-linking/-referencing them with a reasonable degree of automation.

As a side note, all MkDocs themes have this problem, not only Material.

**Comment by urna** [comment]
Yes, I am clear now. 

One approach i am thinking is:
1.  modify build process to remove site navigation items from output pages
2.  generate a levelled navigation structure based on output pages, just like  maven repo https://repo1.maven.org/maven2/ , every navigation page only knows upper/lower and current ones

Thanks!

**Comment by urna** [comment]
my final solution is:
1. make end pages as html(not built but deployed)
2. for every folder contained above end pages, make a index page with .mk extension(will be built as site navigation item)

so the navigation items will be reduced only 1% as before, so it's easy to host 10,0000 pages. my 10,0000 pages will have about 1000 navigation items and only with 50k size for each navigation page.

**Comment by urna** [comment]
[index.py.txt](https://github.com/squidfunk/mkdocs-material/files/3546120/index.py.txt)


attached my code to do so, generally:
1. manually define whole site nav structure and items
2. build a index page for each sub folder to nav up/down
3. so through this, the total pages can be  unlimited, just put them in specific folders is ok
