### ISSUE TITLE
Feature Request: Allow 'black' to be selected as primary color for theme

### ISSUE THREAD

**Issue by mightymackem** [squidfunk/mkdocs-material#1214]
## Description

I would like to switch my theme to use black as the primary color. Black is included in the [Material Design color palette](https://material.io/design/color/#tools-for-picking-colors) but can't be selected as an option under `palette: primary` in the `mkdocs.yml' file. 

Please consider updating the theme so that I can select "black" as the main color for my theme.

Thanks for your consideration!

**Comment by squidfunk** [comment]
Released as part of 4.4.1.

**Comment by mightymackem** [comment]
Just wanted to say how appreciative I am that you added this enhancement so quickly, thank you very much!
