### ISSUE TITLE
url encode issue

### ISSUE THREAD

**Issue by urna** [squidfunk/mkdocs-material#1227]
![Screenshot from 2019-08-24 16:04:54](https://user-images.githubusercontent.com/6385747/63634433-f7fe4980-c688-11e9-81d8-f549c90a55e2.png)

description be formatted, so attached a picture.

**Comment by squidfunk** [comment]
Honestly, I have no idea what you mean. When creating a new issue, please stick to the template and describe exactly what you expected to happen and what actually happened.

**Comment by urna** [comment]
> Honestly, I have no idea what you mean. When creating a new issue, please stick to the template and describe exactly what you expected to happen and what actually happened.

updated issue description ;)

**Comment by squidfunk** [comment]
This is not a problem/question that is related to this theme but to MkDocs in general. Please ask this question on their issue tracker, as I don’t know how this is handled by MkDocs.

**Comment by urna** [comment]
got it! just clone to MkDocs issue list

**Comment by urna** [comment]
this issue is move to MkDocs https://github.com/mkdocs/mkdocs/issues/1851
