### ISSUE TITLE
How to put tab in CodeHilite?

### ISSUE THREAD

**Issue by Lu-Yi-Hsun** [squidfunk/mkdocs-material#1228]
When I write Makefile, it needs tab.
but it converts to space

**Comment by facelessuser** [comment]
CodeHilite cannot do what you want, but superfences can: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#preserve-tabs.

**Comment by Lu-Yi-Hsun** [comment]
@facelessuser  thank you! it work
