### ISSUE TITLE
Lunr Languages files missing copyright attribution

### ISSUE THREAD

**Issue by hughmcmaster** [squidfunk/mkdocs-material#1246]
## Description
The Lunr Languages JavaScript files are missing their copyright attribution, which can be seen in all of the [minified files](https://github.com/MihaiValentin/lunr-languages/tree/master/min).

This causes problems for packaging in Debian, which requires copyright attributions to be present where given in upstream source files.

### Expected behaviour
Please update your Lunr Languages JavaScript files to include the copyright attributions present in the upstream files. (Also, please note the file extensions are incorrect. See #1247.)

### Package versions
Material: 4.4.2

**Comment by squidfunk** [comment]
No bandwidth right now. If somebody wants to tackle it - it's a great first PR. Changes need to be made in `webpack.config.js`.

**Comment by squidfunk** [comment]
As I understand from a layman's perspective: downloading files from a network is not considered "distribution", as minified JavaScript is in the same domain as bytecode. This means the copyright attribution does not have to be included IN the file, but WITH the files. The `lunr-languages` repository is included via `npm` and built automatically, so we could include the license (which is MPL) in the same directory as the minified files.

**Comment by hughmcmaster** [comment]
I believe that could work. [Question 16](https://www.mozilla.org/en-US/MPL/2.0/FAQ/) of the MPL-2.0 FAQs says minified JavaScript is considered an 'executable', so you need to inform recipients of the minifed source how they can obtain a copy of the (unminified) source code.

**Comment by squidfunk** [comment]
Fixed in f02d4aa47f83bb658bb9530aa01b4c38880af8fe. I decided to add (= not strip) the copyright banners directly to the source files, as it's the easiest way. Will be part of the next release.

**Comment by hughmcmaster** [comment]
This works perfectly. Thanks so much!
