### ISSUE TITLE
What version of modernizr.js are you using?

### ISSUE THREAD

**Issue by hughmcmaster** [squidfunk/mkdocs-material#1248]
## Description
modernizr.js seems to be modified from upstream. What version are you using?
The file is also minified, but is missing the `.min.js` file extension.

These issues cause problems for packaging in Debian.

### Expected behaviour
An upstream version of modernizr.js, with the `.min.js` extension.

**Comment by squidfunk** [comment]
It's a custom build automatically created during the build step.

No bandwidth right now. If somebody wants to tackle it - it's a great first PR. Changes need to be made in `webpack.config.js`.

**Comment by squidfunk** [comment]
Closing for the same reason as https://github.com/squidfunk/mkdocs-material/issues/1247#issuecomment-531669253

**Comment by squidfunk** [comment]
Modernizr will be removed in v5, (#1306)
