### ISSUE TITLE
application.js appears to contain a minified lunr.js

### ISSUE THREAD

**Issue by hughmcmaster** [squidfunk/mkdocs-material#1249]
## Description
application.js appears to contain a minified lunr.js source file, in addition to other non-identifiable source code.

Keeping lunr.js separate will allow for the mandatory inclusion of the copyright statement, as well as the correct `.min.js` file extension.

Debian packages require minified files to be paired with unminified source equivalents. Separating the files also allows Debian to depend on the repository version of lunr-js (and replace your version with a symlink).

I don't know what the remaining source code is in the application.js file. Some identification of this would be appreciated. 

### Expected behaviour
Please split lunr.js into a separate file, using the upstream version and correct file extension.

Please add identifying information to the remaining JavaScript source in applicaton.js.

**Comment by squidfunk** [comment]
Before opening further issues, could you please elaborate why this project should adhere to Debian package requirements? It's installable via `pip`, which is the way to go, not via `apt-get`.

**Comment by hughmcmaster** [comment]
I don't actually use mkdocs-material directly. It's used by the FreeType project for their API reference.

To make things clear, I maintain the FreeType package for Debian. While fixing these issues will make my life easier, as I would no longer have to make the same changes downstream (or avoid packaging some files), most of the issues raised go beyond Debian.

Take the copyright attributions, for example. The upstream packages specify that the licences are required in the source files, but it is missing. As to `.min.js` file extensions, this is useful indicator that the script is minified. I wasn't expecting to find minified sources in mkdocs-material, given many projects ship unminified and minified sources.

It's the same with application.js files (although, as I wrote, I can't identify some of the code in application.js). modernizr.js is different, since upstream's minified file doesn't have copyright information. It is marked with `.min.js`, however.

Sorry for the long read (and all of the issue tickets). I hope that's clearer now.

**Comment by squidfunk** [comment]
I will see if we can fix some of those things but Debian support is not on my list. Packaging `lunr.js` into `application.js` is necessary to ensure good UX for HTTP 1.x clients. The stemmers are kept separate as they would blow up `application.js` too much. Those are all trade-offs which were made consciously.

Regarding the License information - I'll see if we can instruct the minifier to not strip those comments.

**Comment by hughmcmaster** [comment]
Okay, thank you.

For me, adding the copyright information back in (i.e. not stripping it), and fixing the file extensions are the most important points.

**Comment by squidfunk** [comment]
Happy to cooperate on a PR! I'm currently very low on time.

**Comment by squidfunk** [comment]
Closing for the reasons stated.
