### ISSUE TITLE
Question: Can I override the template used to render a specific page using page metadata?

### ISSUE THREAD

**Issue by jduprey** [squidfunk/mkdocs-material#1253]
## Description

I feel certain I read this somewhere under theme customization, can I override the template used to render a specific page using page metadata?

e.g.
```
---
title: ...
description: ...
template: page-template-1
---

# Title
This page is supposed to be rendered using `page-template-1`
...
```

### Expected behavior

Ability to render a page with a custom page template by specifying it in the page's "front matter" / metadata.

### Actual behavior

??

### Steps to reproduce the bug

this is not a bug

...

**Comment by squidfunk** [comment]
https://www.mkdocs.org/user-guide/writing-your-docs/ - see the section on metadata (can’t direct link from mobile)

**Comment by jduprey** [comment]
Thank you!  Yes. That was it, I read it, closed the page and then couldn't find it again.  My eyes must have skipped over it 10 times.
