### ISSUE TITLE
Question: Only logo in header?

### ISSUE THREAD

**Issue by luxxurri** [squidfunk/mkdocs-material#1256]
## Description
Is there anyway to include only the set logo instead of the logo and text?

### System information

* OS: Windows 10

**Comment by squidfunk** [comment]
Which text? The title? Please use the issue template and explain exactly what is expected and actual behavior. For quick questions use Gitter.

**Comment by luxxurri** [comment]
The header text. Like this:
![image](https://user-images.githubusercontent.com/55330327/64916865-ad3a9380-d755-11e9-81eb-787c47b346f9.png)
You see how it had this?
![image](https://user-images.githubusercontent.com/55330327/64916867-bd527300-d755-11e9-8732-07318c4aa296.png)
Yeah, the first one without the text.

**Comment by squidfunk** [comment]
You can use CSS to hide it. See the customization guide in the official docs.

**Comment by luxxurri** [comment]
Okay, thank you!
