### ISSUE TITLE
shows [local] images for <a> tags when run on local server, but not so when deployed via gh-pages

### ISSUE THREAD

**Issue by root-ansh** [squidfunk/mkdocs-material#1259]
## Description
I want to show some images in my markdown which should be rendered with a link, like this:
<a href="mailto:anshsachdevaprofessional@gmail.com">
    <img src="https://icon-library.net/images/gmail-icon-black-and-white/gmail-icon-black-and-white-9.jpg" height="64" width="64" alt="gmail">
</a>

code for this would be:
```
<a href="mailto:anshsachdevaprofessional@gmail.com">
    <img src="https://icon-library.net/images/gmail-icon-black-and-white/gmail-icon-black-and-white-9.jpg" height="64" width="64" alt="gmail">
</a>
```
Currently this `src` is in a local folder (docs/img/mail.png) and is perfectly showing on server `127.0.0.1:8000` . But when i deploy using `mkdocs gh-deploy` ,it rather shows this:  
![image](https://user-images.githubusercontent.com/31290636/64928127-9d907d00-d831-11e9-8420-d419dcc9fe68.png)

### Expected behavior
 the icon to show correctly, along with clickable link

### Actual behavior

link  is clickable, but local image is not showing 

### Steps to reproduce the bug  
1. create a simple project
2. add the  above line , but change `src` to a local image file
3. publish on gh-pages.

### Package versions

* Python: `python 3.7`
* MkDocs: `mkdocs --1.0.4`
* Material: `4.4`

### Project configuration

``` yaml
https://paste.ubuntu.com/p/vQF3jRCXFp/ 
```

### System information

* OS: win10
* Browser: opera Version:64.0.3417.11

**Comment by squidfunk** [comment]
Does it also happen with other themes?

**Comment by root-ansh** [comment]
@squidfunk 
> Does it also happen with other themes?   

no idea. my current solution is to use web urls for my images after being uploaded to github ( i.e the ones that get created when pics in the `docs/img`  folder get committed and uploaded to master branch of our site.
Will check this problem with other themes too by tonight.

**Comment by squidfunk** [comment]
Closing for housekeeping. Also it's very likely to be a general problem and nothing that has to do specifically with this theme.

**Comment by root-ansh** [comment]
@squidfunk  i am continuously facing this bug . i checked mkdocs' docs , there is something mentioned about adding images in the yml file too :  https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-images-and-media  

i am not doing that, is it necessary? i haven't seen any ymls that use mkdocs-material and add the images in yml too

**Comment by root-ansh** [comment]
also i have some observations.  
suppose In markdown, i add the picture using `<img src=" /img/aad.png>`.  
when committed, this would go to `docs/img/`  folder of the master branch and `/gh-pages/img/aad.png` of the gh-pages branch.  
Thus final link of the image becomes:  https://raw.githubusercontent.com/root-ansh/curioustools/gh-pages/img/aad.png .  
But the image that is not getting correctly loaded has the url as https://root-ansh.github.io/img/aad.png .  

so , are the two  links same?I am definitely doing something wrong , can you figure out what?

**Comment by squidfunk** [comment]
This is not a question that is related to this project but to MkDocs in general. If you suspect a bug, please open an issue on their bug tracker. Otherwise please consider asking on StackOverflow. This is not a support forum.
