### ISSUE TITLE
404.html page wrong URL on home link and site icon

### ISSUE THREAD

**Issue by davidhrbac** [squidfunk/mkdocs-material#127]
## Description

404.html page has wrong URL on home link and site icon

### Expected behavior

should go to /

### Actual behavior

404.html has home and icon link set to "" - itself. So it means all 404 error will link to invalid URL.

### Package versions

* Python: Python 2.7.12
* MkDocs: mkdocs, version 0.16.1
* Material: Version: 0.2.4

**Comment by squidfunk** [comment]
Thanks for reporting, will look into this.

**Comment by davidhrbac** [comment]
Thanks, quick fix is `sed -i 's,href="" title=",href="/" title=",g' 404.html`.

Would post PR but I can't find it within the source.

**Comment by squidfunk** [comment]
Seems to be a MkDocs issue, let's see what they say.

**Comment by davidhrbac** [comment]
OK. Different `base` might be part of the issue:

```bash
‹hrb33-toshiba› 12:08 $ grep base *.html 
index.html:      <script>var config={url:{base:"."}},app=new Application(config);app.initialize()</script>
404.html:      <script>var config={url:{base:""}},app=new Application(config);app.initialize()</script>
```

**Comment by squidfunk** [comment]
See the discussion in the linked thread - they provided a fix but for now only in master. I hope the bugfix will be released soon. However, as it has nothing to do with Material in particular, I'm closing this issue.

**Comment by davidhrbac** [comment]
Thanks I have followed the upstream bug. Sorry for not creating the upstream issue.

**Comment by squidfunk** [comment]
No worries, let's hope it gets fixed soon.
