### ISSUE TITLE
Scroll active nav entry into view

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#1271]
In desktop view, if the nav (left sidebar) is larger than the viewport, the nav becomes scrollable.

Now, when I scroll down in the nav and open a page, the new page doesn't remember the scroll position of the nav bar. I have to scroll down again to see where I am in the nav:

![mkdocs-material-nav-scroll](https://user-images.githubusercontent.com/2234833/65520860-97ad3280-dee8-11e9-86a4-49e6bf0da553.gif)

Yes, I know, that's kinda what you get when you choose a static site layout, but maybe there's a way to improve that? Probably by using scrollIntoView?

Here's a quick hack (works in FF, but not in Chrome):

``` javascript
// Scroll active item in table of contents into view
$.fn.isInViewport = function () {
    var elementTop = $(this).offset().top;
    var elementBottom = elementTop + $(this).outerHeight();
    var viewportTop = $(window).scrollTop();
    var viewportBottom = viewportTop + $(window).height();
    return elementBottom > viewportTop && elementTop < viewportBottom;
};
var activeLink = $("a.md-nav__link--active");
if (!activeLink.isInViewport()) {
    activeLink[0].scrollIntoView(true);
    window.scrollBy(0, -100);
}
```

**Comment by squidfunk** [comment]
I would regard this as a matter of taste. If the code you provided solves the problem, you're good to go. There's currently no intent to implement this.

_Also please stick to the issue template._

**Comment by wilhelmer** [comment]
Umm, it's not a question, it's a feature request. Sorry for not using the template, that should've made that clearer.

> I would regard this as a matter of taste. If the code you provided solves the problem, you're good to go. There's currently no intent to implement this.

I consider this bad UX because it disorients the user. But I admit it's an edge case to have a nav this large.

**Comment by squidfunk** [comment]
> I consider this bad UX because it disorients the user. But I admit it's an edge case to have a nav this large.

Well, it seems to be easily fixable with some custom JavaScript. I don't want to impose too much opinionated behavior / UX on the user, as this generates more need to provide more and more configuration options. My aim with this theme is to provide a common ground.

Furthermore, it might induce _content shift_ during page load on slow connections, as there might be a reasonable delay between the FMP which includes the sidebar and the execution of the JavaScript changing the scroll offset, hence disorienting the user when he aims to click on a navigation item and lands on a completely different page.
