### ISSUE TITLE
Client-side search not working when hosted on github pages

### ISSUE THREAD

**Issue by smarie** [squidfunk/mkdocs-material#1279]
I just realized that search was not working on my mkdocs-generated pages hosted on github.

For example https://smarie.github.io/python-makefun/

From what I read on this project pages it seems that there is both some client-side search and server-side search happening. server-side works when I host the web page using `mkdocs serve`, but client-side search does not seem to work by default on the github pages-hosted website.

Is there any configuration option that I would have missed, needed to activate the client-side search feature for material ? Or is this a bug ?

Thanks in advance for your answer!

**Comment by squidfunk** [comment]
Please ask questions on the Gitter channel. I’m closing this issue because it is not considered a bug or a feature. Please adhere to the issue templates.

**Comment by smarie** [comment]
For the record (if other people face the same issue), as discussed on the gitter channel: this happens when the `--dirty` flag is set. A workaround is therefore not to use that flag if possible.
