### ISSUE TITLE
Dark mode CSS file

### ISSUE THREAD

**Issue by henrywhitaker3** [squidfunk/mkdocs-material#1305]
## Description

I made a dark mode CSS file for this, repo [here](https://github.com/henrywhitaker3/mkdocs-material-dark-theme). There is a live demo [here](https://henrywhitaker3.github.io/mkdocs-material-dark-theme/), which just uses your site as an example (mainly because it had examples of all the different things you can use). I know, from looking at closed issues about a dark mode, that you wanted to implement one but didn't have the time, so feel free to use this however you want.

### Screenshots / Mockups

![screenshot](https://raw.githubusercontent.com/henrywhitaker3/mkdocs-material-dark-theme/master/docs/assets/images/demo%20screenshot.png)

**Comment by cryocaustik** [comment]
@squidfunk another option to consider if you're thinking of building in a dark theme
https://github.com/fmaida/mkdocs-material-dark-theme
![image](https://user-images.githubusercontent.com/15346996/67980714-3c075080-fbdc-11e9-853d-63cacb988b6e.png)

**Comment by markusressel** [comment]
This is awesome, thx for integrating a dark theme into upstream! :nerd_face: 
If you need more inspiration, here is my take from some time ago (which I still use today):
https://github.com/markusressel/MkDocs-Material-Dark-Theme

**Comment by Stanzilla** [comment]
You guys can use this PR as a base https://github.com/squidfunk/mkdocs-material/pull/1409

**Comment by rjduran** [comment]
Is this the correct place to submit a request for making light/dark modes a toggle? That way a user to the site has the option to switch as needed.

**Comment by squidfunk** [comment]
We’ll probably add a toggle in 5.1 or 5.2 that’s defaults to `prefers-color-scheme`.

**Comment by ofek** [comment]
Dark mode will be in 5.2?

**Comment by squidfunk** [comment]
Probably, because it's likely the next thing I'll be working on, but can't put an estimate of it. Note that there are already some v5 compatible dark modes out there.

**Comment by squidfunk** [comment]
#1639 contains the dark mode implementation, which is still a WIP.

**Comment by w4nderlust** [comment]
If it is of any help, also I implemented a, admittedly hacky, dark mode theme for my project https://uber.github.io/ludwig/user_guide/ . The source code (which is basically a css on top of the regular one, is here: https://github.com/uber/ludwig/blob/master/mkdocs/docs/stylesheets/extra.css
Would love to see a dark theme one could just turn on in the configuration, will make my like much easier :)

**Comment by squidfunk** [comment]
@w4nderlust really like the Uber Ludwig docs – saw them when it came out, as I've noticed some spike in my visitor graph 😉 The native dark mode will probably be a little different, but I might borrow some stuff for inspiration.

**Comment by squidfunk** [comment]
Took some time and finished dark mode. #1639 should be ready to go. It's likely that we discover some edge cases that don't work yet, but for now it should be fine. Currently, only author-defined and set from `mkdocs.yml`, but adding [a toggle](https://deploy-preview-1639--mkdocs-material-preview.netlify.app/getting-started/#color-scheme) is easy:

https://github.com/squidfunk/mkdocs-material/blob/7a12b5ec102071d1917ef83ee5cd62f2a36991a1/docs/getting-started.md#L348-L356

As described in #1639, the implementation allows for further color schemes besides a dark mode, so we could add a high-contrast mode for visually impaired people. Therefore, color schemes are not a binary/boolean thing, but another dimension among primary and accent colors.

If somebody comes up with a good idea of how we could integrate a toggle to switch between those modes, or how to configure which modes the user should be allowed to choose, we can integrate it into `master`.

**Comment by Stanzilla** [comment]
that's super cool!

**Comment by facelessuser** [comment]
Nice work!

**Comment by ofek** [comment]
Absolutely amazing! Ship it 🚀

**Comment by w4nderlust** [comment]
That's amazing, simplifies adding themes a lot! Can wait to see it in the release

**Comment by squidfunk** [comment]
Released as part of 5.2.0!
