### ISSUE TITLE
Display ads

### ISSUE THREAD

**Issue by AiltonSilvaSC** [squidfunk/mkdocs-material#1311]
add a way to display AdSense Ads.

**Comment by squidfunk** [comment]
Never gonna happen. If you want to display ads, you can extend the theme as described in the docs. Also, as this issue doesn’t use the issue template to provide context for this feature request, it is closed immediately just as stated in the template.

**Comment by squidfunk** [comment]
Ads can be added via theme extension. There are thousands of providers, I'm not keen on maintaining integrations with them. If we start adding one provider, users are going to ask for more. It's nothing I want to maintain.

**Comment by adambirds** [comment]
Thanks for the clarification @squidfunk
