### ISSUE TITLE
Clean Installation, build not working

### ISSUE THREAD

**Issue by MarkusHiller** [squidfunk/mkdocs-material#1341]
Hi,
I downloaded a fresh copy of the repository. Then I have the steps under https://squidfunk.github.io/mkdocs-material/customization/ running and get the following error:

Der Befehl "$" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
make × ERR  $(shell npm bin)/eslint --max-warnings 0 .
$(shell npm bin)/stylelint `find src/assets -name *.scss`
make × ERR  Recipe exited with code %d
(node:4152) UnhandledPromiseRejectionWarning: undefined
(node:4152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4152) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4152) UnhandledPromiseRejectionWarning: Error: Recipe exited with code %d
    at ChildProcess.<anonymous> (C:\Users\Markus Hiller\AppData\Roaming\npm\node_modules\make\src\cli.js:143:28)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
(node:4152) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
make × ERR  not found: make-|

  $ make <target...> [options]

Are there any dependencies or how do I get the source compiled?

Windows 10
NodeJs: 12.13.1
Python: 3.8

**Comment by squidfunk** [comment]
It seems that `make` is not available or there is some incompatibility with your Windows installation. The `Makefile` is only tested on Unix systems and I can't provide any support for Windows.

**Comment by squidfunk** [comment]
Housekeeping.
