### ISSUE TITLE
Add main footer block

### ISSUE THREAD

**Issue by rroblik** [squidfunk/mkdocs-material#1351]
Hi,

## Description
I asked myself how to easily add a "post article" custom content (right just before closing `</article>` (or after ?) BUT inside the `<main>` tag ?

## Goal
My goal is to add static content on very page above the main content, at template level using [native override capabilities](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials).

## Details
Add a `main-footer` block (maybe empty by default ?) here https://github.com/squidfunk/mkdocs-material/blob/master/src/base.html#L338, for example :

```html
<!-- ... -->
<!-- Disqus integration -->
  {% block disqus %}
    {% include "partials/integrations/disqus.html" %}
  {% endblock %}
  {% block main-footer %}
    {% include "partials/main-footer.html" %}
  {% endblock %}
</article>
<!-- ... -->
```

or

```html
<!-- ... -->
<!-- Disqus integration -->
  {% block disqus %}
    {% include "partials/integrations/disqus.html" %}
  {% endblock %}
</article>
{% block main-footer %}
  {% include "partials/main-footer.html" %}
{% endblock %}
<!-- ... -->
```

Do you think that is possible ?

Best regards

**Comment by squidfunk** [comment]
Well, we could do that for v5, but the question is: above or below Disqus? Probably a matter of taste.

**Comment by rroblik** [comment]
Yes after disqus I think :)

**Comment by squidfunk** [comment]
I would say before Disqus. But this is exactly my point - It's a matter of taste. For this reason I don't know if it makes sense including it, because then somebody else will open an issue who wants it just the other way. I'll leave this open until I/we decide.

**Comment by squidfunk** [comment]
I decided not to include a generic main header or footer block. The reason is that there are multiple positions where such a block can be placed. However, it is easily achievable with the current architecture using block-level theme extension and the `super()` call:

__Place after content, before disqus__

``` jinja
{% block content %}
  <p>Main header</p>
  {{ super() }}
  <p>Main footer</p>
{% endblock %}
```

__Place after disqus__

``` jinja
{% block diqus %}
  {{ super() }}
  <p>Main footer</p>
{% endblock %}
```
