### ISSUE TITLE
Replace Font Awesome with pure SVGs

### ISSUE THREAD

**Issue by XhmikosR** [squidfunk/mkdocs-material#1364]
__I checked that...__

- [X] ... the documentation does not mention anything about my idea
- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... there are no open or closed issues that are related to my idea

## Description

Currently it seems that Font Awesome CSS and font files are loaded for just the (3) social icons. This is too much bloat IMHO :/

If the social icons are meant to be specific ones, it would be a lot faster and will result in ~-82KB gzipped to use SVG inlined icons.

There are plenty of SVG collections out there with many brands and social logos. A few examples (random order):

* https://github.com/danklammer/bytesize-icons
* https://github.com/edent/SuperTinyIcons
* https://github.com/simple-icons/simple-icons
* https://github.com/akveo/eva-icons

Or even https://github.com/saeedalipoor/icono

**Comment by squidfunk** [comment]
I agree. However, how should this be implemented so that it's still easily configurable?

**Comment by XhmikosR** [comment]
Are the social icons just a specific set, i.e. facebook, twitter etc? Assuming there's an order in the filenames, you can just inline the SVGs when the user specifies the type, similarly to adding the specific FA class.

**Comment by squidfunk** [comment]
Everything that is supported by FontAwesome. If you come up with an idea how to extract all that is included in FontAwesome into SVGs and an automatic update process for those SVGs, we could find some way to replace the icon font. Other than that I see no possibility.

**Comment by squidfunk** [comment]
Closing for the stated reasons. If you come up with a proposal that works, feel free to create another issue. There seems to be an [SVG sprite version](https://fontawesome.com/how-to-use/on-the-web/advanced/svg-sprites), but that doesn't allow inlining from what I understand.

As a sidenote: the GitHub, GitLab and Bitbucket repository icons etc. are already inlined as you suggested.

**Comment by XhmikosR** [comment]
Please don't close this. Its an important issue which I didn't even have
the time to think any further.

**Comment by squidfunk** [comment]
Then please think first, and then open a new issue when you have a reasonable proposal on how to solve this.

**Comment by XhmikosR** [comment]
Think first? Do you know there's something called discussion?

Sigh.

**Comment by squidfunk** [comment]
> Think first? Do you know there's something called discussion?

Okay, maybe another explanation why I closed this: I don't see this as a priority issue, at all.

First, it's optional. FontAwesome is only included when the `extra.social` entries are set. Yes, there are 80kb to be downloaded, but this is only done on the initial request if the browser cache doesn't have it.

Second, you're effectively proposing a more efficient, but also more complicated idea. You haven't outlined how this would be solved in detail, so I consider this as a feature request. Then, as this feature request is not viable for implementation and contains very, very little upside, I'm closing it.

I would kindly ask you to move discussions involving questions to the Gitter channel.

**Comment by squidfunk** [comment]
Turns out, the FontAwesome icons are all available as single SVGs! 704a7c50 switches to an inline SVG approach which makes the icon font obsolete. You can follow #1306 to keep track of the next major version.

**Comment by XhmikosR** [comment]
Thanks for this.

I've also noticed a couple other issues, not sure if they have been tackled in master yet, tough.
