### ISSUE TITLE
Add support for mkdocs-git-authors-plugin

### ISSUE THREAD

**Issue by timvink** [squidfunk/mkdocs-material#1403]
## Description

Add support for [mkdocs-git-authors-plugin](https://github.com/timvink/mkdocs-git-authors-plugin) to display the authors on the bottom of a page.

Disclaimer: I'm the author of the plugin. Also note the original idea is from [mkdocs-git-committers-plugin](https://github.com/byrnereese/mkdocs-git-committers-plugin) but that plugin is only for github. The author and I discussed integration but decided to split into separate plugin (see https://github.com/byrnereese/mkdocs-git-committers-plugin/issues/9)

### Use Cases

When enabled, each markdown page will display the name of the committers (as specified in their `.gitconfig`). It uses `git blame` so only considers 

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/5570380/71417183-50a81800-2664-11ea-91a0-f5f8aee1ac96.png)

Implementation can be done by updating `base.html` just below the `page.meta.git_revision_date` block:

```django hljs
{% if git_authors_summary %}
<small>
    Written by: {{ git_authors_summary }}
</small>
{% endif %}
```

We can localize the "Written by" by adding a new language item, f.e. `source.revision.date`.

If this fits with `mkdocs-material` I'd be happy to work on a PR ! Todo:

- Add translations
- Update base
- Add CSS similar to `.md-source-date`
- Add page to docs website
- ...

**Comment by squidfunk** [comment]
Could we build something that looks like this?

<img width="234" alt="Bildschirmfoto 2019-12-24 um 16 05 05 Kopie" src="https://user-images.githubusercontent.com/932156/71417762-69fe9380-2667-11ea-87b9-b3bd86090ad5.png">

Is it possible to get the GitHub username from a commit? If we have the username, getting the avatar is as simple as:

```
https://avatars.githubusercontent.com/<username>
```

Combining this with the revision date plugin you wrote and the name from the git committer, we have everything in place.

**Comment by timvink** [comment]
Yes, that would be awesome! 

I see three challenges however:

- Design needs to support multiple authors
- There is no rock solid way to get always get the github username from a commit (see section below for details), we need a fallback (empty avatar?)
- Only works for github

Best option to show the avatar would be to use [mkdocs-git-committers-plugin](https://github.com/byrnereese/mkdocs-git-committers-plugin/) that solves this by using a github token to query the *pushed* repository on github. Good solution, but has some downsides:

- You need to remember to push your code before building.  
- Harder to use: Users need to setup a token and store it securely as an environment variable

## Getting github and gitlab avatar from commits

We would need a solid solution to get avatars, that works on at least github and gitlab, on public repositories.

From the local git logs we only have access to the commit `name` and `email`. (See for example the [github commit api](https://developer.github.com/v3/repos/commits/))

While `email` is the best unique identifier, many github users do not have a public address shared on their github profile (including you and me). I tried the github API with my emailadress and could not find myself:

```
https://api.github.com/search/users?q=vinktim@gmail.com
```

Good news is that finding gitlab username based on commit email address does work:

```
https://gitlab.com/api/v4/users?search=vinktim@gmail.com
```

For github we still can use `name`, which is less unique. The name used in a git commit (specified in local `.gitconfig`) does not have to be equal to the name you use in your github profile. The github API supports searching on a name and returns matches sorted on match score, for example:

```bash
https://api.github.com/search/users?q=Tim%20Vink
```

It works, but there is however a risk of false positives: Finding the wrong github user with a given name. To improve that, we could combine with the github contributors API to check that a username is a repository contributor, for example:

```
https://api.github.com/repos/squidfunk/mkdocs-material/contributors
```

So we can search for a `name` and then make sure that the matched `user` is actually a contributor. Way more solid but:

- If a user did not push a commit to master yet, this wouldn't work. However we could print a warning
- Getting repo contributors only works for public repositories if you don't use a token.

## Conclusion

I think `mkdocs-material` could support different use-cases:

- A basic git-authors view like proposed in this issue, with no avatars
- If available, a more rich view with avatars, based on public github or gitlab APIs (I would build the functionality described above and so users can enable it with plugin config)
- Support for [byrnereese/mkdocs-git-committers-plugin](https://github.com/byrnereese/mkdocs-git-committers-plugin/). 

@byrnereese any thoughts to add?

**Comment by squidfunk** [comment]
@timvink Thanks for your research. I actually don't want to support to many combinations of orthogonal plugins. We definitely have to keep it simple for users, so I would definitely favor a single author-/avatar-plugin. It would only be really cool to have a nicer presentation but if stuff is split among different plugins, it may break too easily.

**Comment by timvink** [comment]
Yeah sounds reasonable, and indeed it should be super simple for users. I will continue work with @byrnereese [here](https://github.com/byrnereese/mkdocs-git-committers-plugin/issues/9) and reopen this issue once there is a clean solution that supports avatars.
