### ISSUE TITLE
Link to return to the top of the page

### ISSUE THREAD

**Issue by majkinetor** [squidfunk/mkdocs-material#1408]
## Description

I would like to be able to click on "Table of contents" item to return to the top of the page. Currently this is not possible.

### Use Cases

This can be used on every page.

### Details

Typical markdown page looks like this:

```md
# Title

Intro text

## Subsection 1
....
## Subsection 2
...
```

This produces TOC like this:

Table of contest:
- Subsection 1
- Subsection 2

That is, title is missing. If intro is long, you have no option to return to the top of the page via TOC but must click first item then scroll up.

Check out sample here: 
* https://majkinetor.github.io/mm-docs-template/demo

Everything up to the `Customization` section is not reachable via TOC.

**Comment by squidfunk** [comment]
Not a bad idea, but not that trivial. The `toc.html` partial is also used to render the TOC inside the mobile navigation and so the `Table of contents` title is actually a label which triggers the TOC inside the mobile navigation. For this to work we would need to duplicate the label with an `a` element and only show the latter on `screen+`. Needs some work on the CSS and some testing.

**Comment by majkinetor** [comment]
Perhaps something else could be done that is trivial and has same effect. Would adding extra element be easier ?

```
Table of contest [^]
   [Subsection 1]
   [Subsection 2]

[^] Table of contest 
   [Subsection 1]
   [Subsection 2]

Table of contest
   [^]
   [Subsection 1]
   [Subsection 2]

```

**Comment by Stanzilla** [comment]
If it gets too complicated, I have a to top scroll button in my fork, I could PR that as well.

**Comment by majkinetor** [comment]
That is not intuitive - one button to go to top and TOC for everything else. Its better then nothing certainly.

**Comment by squidfunk** [comment]
I like the idea with the clickable TOC, but I don't know if it is more obvious that the go-to-top button. I also thought about switching __Table of contents__ with the contents of the `h1`, but then it's less obvious that it's a TOC. The reason why the `h1` is excluded is that everything under the `h1` would need to be indented to be consistent, and that made no sense to me. However, I'm open to suggestions.

**Comment by Stanzilla** [comment]
I have the extra button in the bottom right and it works quite well for mobile

**Comment by majkinetor** [comment]
>The reason why the h1 is excluded is that everything under the h1 would need to be indented to be consistent, and that made no sense to me.

Exactly. That thing is actually present on some other systems and maximally anoying to the point I stopped using h1 on said systems.

>However, I'm open to suggestions.

go to top button now looks OK. 

As trivial alternative, how about adding link to title of current page ? Currently its text and it could either link to self or do go to top. This wont change any device looks.

**Comment by Stanzilla** [comment]
![Screenshot_20191229-014747](https://user-images.githubusercontent.com/75278/71551027-7ecb8600-29dd-11ea-88dd-c6c5c349bc38.png)
It's a hovering button that shows up after scrolling for a bit, I can PR if wanted or just send you the code @majkinetor

**Comment by majkinetor** [comment]
Thx @Stanzilla, no need to send the code.

**Comment by coliff** [comment]
I think a 'Back to top' link would be a welcome addition. I think it should appear below the items on the right after a small gap and in a slightly smaller text size - like here:
https://zavoloklom.github.io/material-design-iconic-font/
I've seen it look like that in a number of material-design looking docs sites. It's not distracting and it works exactly as expected.

**Comment by squidfunk** [comment]
@coliff hmm, that's not a bad idea. It must be located outside of the scroll wrapper though (to account for TOCs with many items) and does not appear on the mobile view, where the TOC is moved into the drawer.

**Comment by majkinetor** [comment]
I like it, it also good thing that there are multiple sites doing that according to @coliff, I personally 

>  must be located outside of the scroll wrapper though

It shouldn't also be all to the bottom because it can cover the link to the next page as evident on above screenshot.

**Comment by squidfunk** [comment]
> It shouldn't also be all to the bottom because it can cover the link to the next page as evident on above screenshot.

Exactly. However, we should think of an approach that is consistent across all breakpoints. A to-top _arrow button_ and _"Back to top" link_ don't go so well together. If you're on an iPad, you would get the _arrow button_ in portrait mode and the _"Back to top" link_ in landscape mode.

**Comment by squidfunk** [comment]
Im closing this issue, as there’s currently no plan to implement this as a theme-native solution. After all, it’s very easy to provide a scroll to top button via a few lines of custom JS and CSS.

**Comment by Kallows** [comment]
@Stanzilla where I can find your fork, I would like to have look how do you made it. Thanks

**Comment by Stanzilla** [comment]
@Kallows https://github.com/ManticoreGamesInc/mkdocs-material
