### ISSUE TITLE
Uncaught ReferenceError: base_url is not defined at main.js:93

### ISSUE THREAD

**Issue by tlindsay42** [squidfunk/mkdocs-material#1441]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Receive the following error: `Uncaught ReferenceError: base_url is not defined at main.js:93` in the dev tools console.

### Expected behavior

`base_url` should be set to the `mkdocs.yml`: `site_url` value in `./search/main.js`

#### Deployed site
1. Browse to https://awslabs.github.io/aws-sync-routes/
2. Open Console tab in browser's Developer Tools
3. Observe error

#### Local
1. `git clone git@github.com:awslabs/aws-sync-routes.git`
2. `mkdocs serve`
3. Browse to http://127.0.0.1:8000
4. Open Console tab in browser's Developer Tools
5. Observe error

### Package versions

* Python: `python --version`: `3.6.9`
* MkDocs: `mkdocs --version`: `mkdocs, version 1.0.4 from ~/.local/lib/python3.6/site-packages/mkdocs (Python 3.6)`
* Material: `pip3 show mkdocs-material | grep -E ^Version`: `4.6.0`

### Project configuration

https://github.com/awslabs/aws-sync-routes/blob/master/mkdocs.yml

Also tried:
* Commenting out the [theme override](https://github.com/awslabs/aws-sync-routes/blob/master/mkdocs.yml#L21)
* Defining the search plugin per: https://squidfunk.github.io/mkdocs-material/plugins/search/

### System information

* OS: Ubuntu 18.04.3 LTS
* Browser: Chrome 79.0.3945.130 (Official Build) (64-bit) & Firefox 68.4.2esr (64-bit)

**Comment by squidfunk** [comment]
The error originates in the original MkDocs search JavaScript which Material doesn't use, as it provides its own search implementation. For some reason however it's included (at the bottom):

``` html
<script src="search/main.js"></script>
```

It's very strange that commenting out the override and using the stock Material version doesn't work for you, as Material explicitly disables the inclusion of the JavaScript via `search_index_only: false`.

**Comment by tlindsay42** [comment]
Got it. The issue occurs if the `search_index_only` value is Boolean instead of a string. I copied this bit from the example [`mkdocs.yml`](https://github.com/squidfunk/mkdocs-material/blob/5cc68d4a040ec78a0d1456ae5745bc6bd51260ee/mkdocs.yml#L46).

```sh
$ git diff mkdocs.yml
diff --git a/mkdocs.yml b/mkdocs.yml
index 0d333d0..b4a08ee 100644
--- a/mkdocs.yml
+++ b/mkdocs.yml
@@ -26,7 +26,7 @@ theme:

   # Don't include MkDocs' JavaScript
   include_search_page: false
-  search_index_only: false
+  search_index_only: 'false'

   # Theme
   language: 'en'
```

I also found that the following settings require a Boolean type to achieve the desired outcome in my setup.

```yaml
theme:
  feature:
    tabs: false
  font: false
```

@squidfunk, are you able to confirm? If setting the theme search settings to string values has no effect for you, would you be interested in a PR for using string values for the theme search settings, and a note about Boolean values for the other two to help others? Or maybe just a troubleshooting note?

**Comment by squidfunk** [comment]
@waylan any idea why this might be happening? Maybe some compatibility issue? Seems quite odd, as we never had any problems before with these settings.

**Comment by tlindsay42** [comment]
Confirmed. I tested that earlier today, but must have been distracted when interpreting the results as I'm wfh today and my kids are running around being awesome kids. Anyway! I'm able to duplicate accurately now. Glad we got to the root of it. Thanks for your help!
