### ISSUE TITLE
Support including *.svg images when customizing theme

### ISSUE THREAD

**Issue by FISHMANPET** [squidfunk/mkdocs-material#1447]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Currently when building a custom theme, only `*.ico` and `*.png` files are copied from the `src/assets/images` to `material/assets/images`, though SVGs are a supported image type for logs, for example

### Use Cases

Theme modifications that include .svg logos

### Screenshots / Mockups

I made what I believe would be the necessary change to support this, but I thought I'd open this issue before I issue a PR: https://github.com/FISHMANPET/mkdocs-material/tree/svg-images
I don't know enough about js to know for sure that this wouldn't have some unintended consequences I'm not aware of, and especially I'm not sure how the existing icon svg files are copied over.

With my changes to webpack.config.js I was able to build a custom theme that included my custom svg logo file.

I looked in the 5.0 branch and it looks like things have been refactored enough that this wouldn't directly carry over (or you haven't implemented all of this functionality in 5.0 yet).

The easy way for me to get around this is to just convert my logo svg to a png, but I thought I'd give this a try.  Feel free to let me know if you're not interested in this change, my feelings won't be hurt :)

**Comment by FISHMANPET** [comment]
Hmm, what I was trying to do was make a branded theme for internal use (custom colors, custom favicon, custom logo), the colors carried over, but the favicon and logo settings didn't (even though the files made it into my custom_dir), not sure if there's user error here or not understanding properly how the default theme is defined, so maybe I'm just going down the completely wrong path with this.

**Comment by squidfunk** [comment]
On `master`, you could change the entry of the `CopyWebpackPlugin` used in `webpack.config.js` which copies the imge files to include `svg`:

https://github.com/squidfunk/mkdocs-material/blob/6f2fc466f47fab4ad40315f9c215ad1b9cbf857f/webpack.config.js#L188-L192

Just change this to:

``` js
{ 
  context: "src", 
  from: "assets/images/*.{ico,png,svg}" 
}
```

It makes no sense to merge this into `master`, as from v5 on the build process is handled in the `Makefile` – Webpack is only used for building the actual JavaScript:

https://github.com/squidfunk/mkdocs-material/blob/26313cd607d7b1c4050144f8dbc8cd5c4649fe09/Makefile#L94-L99

You could just add another target in the `Makefile` which handles `*.svg*  files.

**Comment by FISHMANPET** [comment]
Yup, I found that line in webpack and changed it and it did what I wanted.  Understandable that you don't want to bother with this in v4, so I'll close this issue, thanks!
