### ISSUE TITLE
Is it possible to put another extension inside a extension?

### ISSUE THREAD

**Issue by killeryoyo01** [squidfunk/mkdocs-material#145]
I was wondering if its possible to put a extension inside another Extension like

Extension>
.test
.test2>
-test

Thank you.

**Comment by squidfunk** [comment]
Sorry, I have no idea what you mean. Please stick to the issue template.

**Comment by killeryoyo01** [comment]
In The Template there is a thing called "Extensions" when you press it. It opens like 4 titles. 

in those titles. Can i put another extension that opens more titles .

For EXAMPLE:

you see "Test"
When you press it expands and shows 4 More  Titles

test2
test3
test4
test5

can i do another extension inside test4 ?

**Comment by squidfunk** [comment]
Yes, with MkDocs, just add a subsection and your pages under the subsection. Please see http://www.mkdocs.org/#adding-pages

Closing this, as it's not related to Material but a general MkDocs question.
