### ISSUE TITLE
Docker container doesn't include mkdocs-git-revision-date-localized-plugin module

### ISSUE THREAD

**Issue by FISHMANPET** [squidfunk/mkdocs-material#1455]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

The docker container doesn't include the mkdocs-git-revision-date-localized-plugin module, so using it to build a site that uses that plugin will fail.  I believe adding this to requirements.txt would fix the issue, and be consistent with how the minify plugin, though it would mean the plugin would get installed for everyone installing mkdocs-material (though, again, that's already the case with the minify plugin)

### Expected behavior

running build with squidfunk/mkdocs-material builds the site

### Actual behavior

```
PS C:\Users\bajurny\Documents\GitHub\mkdocs-demo> docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build
ERROR   -  Config value: 'plugins'. Error: The "git-revision-date-localized" plugin is not installed 

Aborted with 1 Configuration Errors!
```

### Steps to reproduce the bug

1. Include `git-revision-date-localized` in plugins in mkdocs.yml
```
plugins:
  - search
  - git-revision-date-localized
```
2. Execute build using docker container
`docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build`

### Package versions

```
PS C:\Users\bajurny\Documents\GitHub\mkdocs-demo> docker pull squidfunk/mkdocs-material
Using default tag: latest
latest: Pulling from squidfunk/mkdocs-material
Digest: sha256:532ef540a52aff90be2a3c861ff39bc0b35651cdaadda8baafa73a76b8ae0779
Status: Image is up to date for squidfunk/mkdocs-material:latest
docker.io/squidfunk/mkdocs-material:latest
PS C:\Users\bajurny\Documents\GitHub\mkdocs-demo> docker image ls
REPOSITORY                                 TAG                            IMAGE ID            CREATED             SIZE
squidfunk/mkdocs-material                  latest                         bd6005f44296        2 days ago          117MB
```
Running the shell against the running container and executing `pip list`:
```
PS C:\Users\bajurny\Documents\GitHub\mkdocs-demo> docker run --rm -it --entrypoint /bin/sh squidfunk/mkdocs-material
/docs # pip list
Package              Version
-------------------- -------
Click                7.0
Jinja2               3.0.0a1
jsmin                2.2.2
Markdown             3.2
mkdocs               1.0.4
mkdocs-material      4.6.2
pip                  19.1.1
Pygments             2.5.2
PyYAML               5.3
setuptools           41.0.1
six                  1.14.0
wheel                0.33.3
You should consider upgrading via the 'pip install --upgrade pip' command.
/docs #
```

### Project configuration

``` yaml
plugins:
  - search
  - git-revision-date-localized
```

**Comment by squidfunk** [comment]
Well, yes, there’re currently no plugins defined as dependencies. We could think about adding the plugins to the Docker container but not to `requirements.txt` as they’re entirely optional. Technically, Pygments and PymdownX are optional, too, but they both add so much value that I consider them as an integral part of this theme.

So what we could do: add them to the `Dockerfile`, but rather not to `requirements.txt`.

**Comment by FISHMANPET** [comment]
I could make a PR that would do this:
1. Remove `mkdocs-minify-plugin` from requirements.txt
2. Make a new file (plugin-requirements.txt? docker-requirements.txt?) and have it include the minify and git revision modules
3. Add a line to the docker file that runs `pip install -r docker-requirements.txt`

**Comment by squidfunk** [comment]
Very appreciated. For 2. please just add the install commands directly to the `Dockerfile` in the same command as the installation of the `requirements.txt`.

**Comment by FISHMANPET** [comment]
For that matter, `python:3.6.8-alpine3.9` is out of date, is there any particular reason to pin this to a specific version (in which case it could be updated to `python:3.6.10-alpine3.10` or `python:3.6.10-alpine3.11`, or could it just be set to always use the latest python alpine image, or `python:alpine`?

**Comment by facelessuser** [comment]
I think the reason versions get locked is because it is a known, tested quantity. If you always grab the latest, you *might* introduce new issues, so from a maintenance perspective, you lock down the version to decrease headaches. You update the version when you have time to verify that the latest and greatest isn't going to crash and burn, and then you lock that down again.

**Comment by squidfunk** [comment]
@facelessuser is right. It’s solely done to have predictable builds. Also, as this is an image that is provided as a dev and build tool and not for production, there’s little risk in not running the very latest version. You are however encouraged to submit a PR for that either after ensuring that everything still works as expected 😊
