### ISSUE TITLE
Make site name clickable

### ISSUE THREAD

**Issue by saket** [squidfunk/mkdocs-material#1471]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Is there a way to include the site name in the clickable region? The logo for our docs site is a bit small and I've seen people try clicking the site name to go home.

**Comment by squidfunk** [comment]
You mean the name in the header bar? The "problem" is that it switches to the name of the page when scrolled past the `h1` which is not the site name so the whole concept doesn't really work. Furthermore, what shall we do on mobile? The hamburger icon opens the menu. When I click on the header I would more or less expect to go to the top, but not to the home page.

**Comment by saket** [comment]
> The "problem" is that it switches to the name of the page when scrolled past the h1 which is not the site name so the whole concept doesn't really work.

That sounds valid. Are there any thoughts on offering an option to disable this behavior?

> When I click on the header I would more or less expect to go to the top, but not to the home page.

This doesn't sound in line like any existing pattern. Are there websites or apps that do this?

**Comment by squidfunk** [comment]
> That sounds valid. Are there any thoughts on offering an option to disable this behavior?

Nope, but theme extension is a path you could explore, see the guide on customization. Overriding the header template and wrapping the title in a link should be very straight forward 😊  Unfortunately we cannot provide options for all use cases.

**Comment by saket** [comment]
Makes sense. I'll explore theme extensions, thank you!
