### ISSUE TITLE
Categories / Tags

### ISSUE THREAD

**Issue by jmrichardson** [squidfunk/mkdocs-material#1472]
Thank you for the very nice theme for mkdocs!  I was hoping that there could be support for tags for example in metadata and be searchable?  Something like:

tags: production development

Then, perhaps have a checkbox to search tags or something similar?

Thanks for your consideration :)

**Comment by squidfunk** [comment]
Frontmatter (YAML) cannot be searched as it’s not part of the index. See https://github.com/mkdocs/mkdocs/issues/1243 and https://github.com/mkdocs/mkdocs/issues/1828. We can add this feature when MkDocs supports it but it seems that it’s not arriving anytime soon.

**Comment by Stanzilla** [comment]
What I do is search all files on build and generate an index from that, that's one thing you could do as well.

**Comment by squidfunk** [comment]
Yep, you can always implement a custom build process but that’s nothing Material can provide.

**Comment by squidfunk** [comment]
Closing for the reasons stated.
