### ISSUE TITLE
Permalink should be hidden

### ISSUE THREAD

**Issue by XhmikosR** [squidfunk/mkdocs-material#1484]
__I checked that...__

- [X] ... the documentation does not mention anything about my problem
- [X] ... the problem doesn't occur with the default MkDocs template
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... there are no open or closed issues that are related to my problem

## Description

While checking out the google search index for a  project that's using mkdocs-material, I noticed that the `.headerlink` (Permanent link) is included.

### Expected behavior

Permalinks shouldn't be included.

### Steps to reproduce the bug

1. Visit <https://www.google.com/search?q=site%3Adocs.pi-hole.net>
2. Notice that the permalink symbol is shown in the results

![Screenshot_2020-03-06 site docs pi-hole net - Google Search](https://user-images.githubusercontent.com/349621/76076598-d7a03780-5fa7-11ea-85e5-98986b82290c.png)

### Package versions

* Python: `python --version` Python 3.8.1
* MkDocs: `mkdocs --version`: 1.1
* Material: `pip show mkdocs-material | grep -E ^Version` 4.6.3

### Project configuration

Shouldn't affect this

### System information

* OS: Windows/Linux
* Browser: Firefox

---

I believe the issue is due to the way visibility and opacity work. The proper way would be to use `display: none` when the permalink isn't hovered and set it to `inline-block` on hover.

Not a huge issue, but I thought I'd bring it to your attention @squidfunk :)

**Comment by squidfunk** [comment]
A fix is already included in v5.

**Comment by XhmikosR** [comment]
Can you share the patch that fixed this? Thanks!

**Comment by XhmikosR** [comment]
Ah, I see now. You change the visibility too.

**Comment by squidfunk** [comment]
I don't have a dedicated patch, but the trick is to transition `visibility` on the `.headerlink`.

https://github.com/squidfunk/mkdocs-material/blob/184e5f24e2fb8e0a6f7597f4f40ddb26056b3a3c/src/assets/stylesheets/extensions/_permalinks.scss#L35-L43

https://github.com/squidfunk/mkdocs-material/blob/184e5f24e2fb8e0a6f7597f4f40ddb26056b3a3c/src/assets/stylesheets/extensions/_permalinks.scss#L67-L73

**Comment by XhmikosR** [comment]
I personally just use `display: none` but transitioning display isn't optimal, so I see why you went this way.

As long as it works the same, I think we can close the issue then :)

**Comment by squidfunk** [comment]
The problem with `display: none` is that it cannot be transitioned which is why I used `visibility: hidden`. If you find a better way, I'm happy to include it.

**Comment by squidfunk** [comment]
Okay then, closing.
