### ISSUE TITLE
Code block styling issues with pymdownx.inline and inline

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#1499]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Issue with 5RC1 inline line highlighting.  Support for inline highlighting is a little broken. Particularly my interest was in support for `pymdownx-inline`, but I've generally investigated and made normal inline also look the same (whether we want to actually do anything with that is up to you).

1. Background is transparent, so when scrolling content underneath, the code shows through.
2. Margins and such are not right with recent changes.
3. Line highlight wraps to next line.
4. Highlight padding is different between table and inine styles, but only table inline padding is used causing inilne code with highlights to have scrollbars.

This was discussed in Gitter.

Fixes here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss

Note:

1. Highlight fix is here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss#L29 and here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss#L78. You could also just make them the same padding and have universal padding.
2. Normal inline consistency changes are here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss#L35
2. Pymdownx-inline fixes are here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss#L56

"Special" css can be ignored unless you wish to support pygments special class attached to line numbers.

### Expected behavior

Inline, especially with line highlighting, doesn't quite look right.

### Actual behavior

See description

### Steps to reproduce the bug

1. ...
2. ...
3. ...

### Package versions

* Python: Any
* MkDocs: Latest
* Material: 5.0.0rc1

### Project configuration

I use `pymdownx-inline` with line numbers though I believe there are issues with normal `inline` as well.

### System information

* OS: Any
* Browser: Any

**Comment by facelessuser** [comment]
Fixed inline documentation is here: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#highlighting-lines.

**Comment by squidfunk** [comment]
Could you provide some code which shows the problem or even submit a PR with the exact lines that need to be changed? I'm a bit lost trying to understand what the fixes are about. I tested different styles:

`codehilite`:

<img width="704" alt="Bildschirmfoto 2020-03-10 um 22 51 46" src="https://user-images.githubusercontent.com/932156/76362829-10cb0580-6322-11ea-8500-06b12f081bd5.png">

`pymdownx.inline`:

<img width="706" alt="Bildschirmfoto 2020-03-10 um 22 52 07" src="https://user-images.githubusercontent.com/932156/76362839-188aaa00-6322-11ea-899b-56783db5dab2.png">

`inline`:

<img width="702" alt="Bildschirmfoto 2020-03-10 um 22 52 26" src="https://user-images.githubusercontent.com/932156/76362845-1b859a80-6322-11ea-845e-24b3bcef218f.png">

Note that b6657bccda33e8338a52ff3d15efd8a6698bdc06 in which code blocks were refactored normalized line number styles to be the same for `codehilite` and `pymdownx.inline`, the latter of which was added quite recently to Material. `inline` was never supported and I have no intent of doing so, as two different line number styles should be sufficient and I don't see the upside of supporting a suboptimal inline style, so FWIW the only issue I see here is that highlighted lines for `pymdownx.inline` should not wrap and that there should be a background on the `linenodiv` on overflow, right?

**Comment by facelessuser** [comment]
I can totally issue a PR. That was my plan once I had time, but I wanted to get the issue open so I used my fixes as a reference.

**Comment by facelessuser** [comment]
And padding on inline highlight is wrong too. We can maybe normalize that between table version.

**Comment by squidfunk** [comment]
Fixed with #1501.

**Comment by squidfunk** [comment]
Just released RC 2. Please re-open if the issue persists.
