### ISSUE TITLE
Favicon Not Updating

### ISSUE THREAD

**Issue by pdwhoward** [squidfunk/mkdocs-material#1508]
I am updating my favicon per the instructions here: https://squidfunk.github.io/mkdocs-material/getting-started/#favicon. However, the favicon is not updating. Can you confirm this does in fact work? It's a really simple procedure, I do not *think* I am doing this incorrectly.

**Comment by squidfunk** [comment]
Probably related to #1282.

**Comment by pdwhoward** [comment]
Thank you.
