### ISSUE TITLE
Screen flickering: header bar reloaded when navigate to a new page

### ISSUE THREAD

**Issue by StanleyWei** [squidfunk/mkdocs-material#1521]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [ ] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Thanks for this great theme, I experienced an issue in Firefox browser that when navigate from the menu bar in the header or to a new page within the primary menubar, the whole page including the header bar and primary menu bar will be reloaded, I assume only the content part should be refreshed for each switch if applicable, the default mkdocs theme does not have this problem. I am not sure what is the setting wrong in my configuration since I noticed other websites used material theme does work as expected in Firefox as well. Please advise. Thanks very much!

### Expected behavior
The page header and primary menu bar should not be reloaded for each navigation, as it works in chrome browser.

### Steps to reproduce the bug

1. please visit the test site http://data42.cn/learnings/sdtm14-chapter01/ to repeat this issue
2. with firefox browser
3. navigate from the header menu bar or primary menu bar, the screen will be flickering for each navigation.

### Package versions

* Python:  3.6.3
* MkDocs: 1.1
* Material: `pip show mkdocs-material | grep -E ^Version` 4.6.3

### Project configuration

``` yaml
The contents of your mkdocs.yml
```
# Project information
site_name: 'Material for Clinical Trials'
site_description: 'A One-stop site for Clinical Trial Materials'
site_author: 'Clinical Trial Fans'
site_url: 'https://www.clinicaltrial.asia/'

# Repository
repo_name: 'medpower/mkdocs-material'
repo_url: 'https://github.com/medpower/mkdocs-material'

# Copyright
copyright: 'Copyright &copy; 2020 - 2022 Medpower'

nav:
    - Home: sdtm14.md
    - Introduction: 
      - 'index.md'
      - 'about.md'
    - SDTM Standards:
       - 'SDTM 1.4': 
          - 'sdtm14-chapter01.md'
          - 'sdtm14-chapter02.md'
          - 'sdtm14-chapter03.md'
          - 'sdtm14-chapter04.md'
          - 'sdtm14-chapter05.md'
       - 'SDTM 1.7':  'sdtm17.md'
       - 'SDTMIG 3.2': 
          - 'sdtmig32-chapter01.md'
          - 'sdtmig32-chapter02.md'
          - 'sdtmig32-chapter03.md'
          - 'sdtmig32-chapter04.md'
          - 'sdtmig32-chapter05.md'
          - 'sdtmig32-chapter06.md'
          - 'sdtmig32-chapter07.md'
          - 'sdtmig32-chapter08.md'
          - 'sdtmig32-chapter09.md'
          - 'SDTMyIG 3.2': 'sdtmig32.md'
       - 'SDTMIG 3.3':  'sdtmig33.md'
    - 'FAQs': 'https://example.com/'
    - 'Manual': 
      - 'MKDocs Manual.md'
      - 'Marldown Syntax': 'Markdown_Basics.md'
      - 'Demo': 'sample.md'

# Configuration
theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: true
    instant: true 
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: 'blue grey'
    accent: 'red'

plugins:
  - search

  # Extensions
markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: "link"
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      legacy_tab_classes: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: table
      linenums: true
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: facelessuser
      repo: pymdown-extensions
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:

extra:
  manifest: 'manifest.webmanifest'
  disqus: 'Please leave your comments'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/facelessuser
    - icon: fontawesome/brands/discord
      link: https://discord.gg/fqQ7ypS
    - type: 'github'
      link: 'https://github.com/squidfunk'
    - type: 'twitter'
      link: 'https://twitter.com/squidfunk'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/squidfunk'

extra_css:
 # - https://unpkg.com/mermaid@8.4.4/dist/mermaid.css
 # - https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.css
  - https://www.data42.cn/css/flowchart.min.css
  - https://www.data42.cn/css/mkdocs-tab.css
  - assets/pymdownx-extras/extra-f1fb910a62.css

extra_javascript:
  - https://cdn.bootcss.com/mermaid/8.4.8/mermaid.min.js
  - assets/pymdownx-extras/extra-52d8c68747.js
### System information

* OS: ... CENTOS 7.0
* Browser: Firefox 74.0

**Comment by squidfunk** [comment]
If you’re not sure whether the error might originate from your customizations, a start would be to remove your customizations one by one and isolate what’s causing it. The fact that you don’t experience this behavior on other pages using the theme is a strong indicator. Furthermore, we cannot provide support for customizations.

**Comment by StanleyWei** [comment]
Thanks squidfund for your quick response, Actually the default settings as well as the home page of mkdocs-material seems have the similar reloading issue in Firefox browser. https://squidfunk.github.io/mkdocs-material/.

I am a newbee and totally understand no customization support for this purpose, but just want to know some clues from experts about how to fix this to save the time, if possible.

Any advice would be highly appreciated!

Thanks again!

**Comment by squidfunk** [comment]
Could you provide the link to a page which is using Material where you don’t observe the behavior? Instill trying to understand what you mean by „flickering“.

**Comment by StanleyWei** [comment]
Thanks, you may visit the following site: http://learn.openwaterfoundation.org/owf-learn-mkdocs/, it works as expect that no reloading issue when navigate to a new page from the primary menu bar.

What the flickering means here is the whole page (just like the screen) will be refreshed each time, what I expect is that the menubar (including the header bar if applicable) should be kept static (no reloading) and any the content windown should be refreshed to load the new page when navigated. Hope this clarifies.

Thanks
Stanley

**Comment by StanleyWei** [comment]
I just found a thread where you contributed a proposal previously and mentioned this kind of SPA-like rendering with XHR has been supported in Chrome. https://github.com/mkdocs/mkdocs/issues/1137 ^~^.

I am wondering if the latest version of material does support this feature in Firefox, as some sites already behave as SPA in Firefox., not sure if some additional customization done or not.

Thanks
Stanley

**Comment by squidfunk** [comment]
I tested [v4](https://squidfunk.github.io/mkdocs-material/) and [v5](https://deploy-preview-1486--mkdocs-material-preview.netlify.com/) in Firefox on macOS and didn't see any flickering. A screen recording of v5:

![Ohne Titel](https://user-images.githubusercontent.com/932156/77226078-d0ffeb80-6b75-11ea-9987-fac591500a25.gif)

The only thing that changes is the GitHub repository information, which is loaded from local storage and can thus not be rendered initially. This is and was the behavior since Material 1.x.

The XHR loading you mentioned is implemented as an experimental feature as part of v5 and called [instant loading](https://deploy-preview-1486--mkdocs-material-preview.netlify.com/getting-started/#instant-loading). I would be happy to get some feedback on it, but as it is experimental, I'd say one should not expect it to be perfect yet.

**Comment by StanleyWei** [comment]
I updated the latest version 5.0.0 and it works, but the tab navigation in the header bar seems not work (all just collapsed in the left primary menu panel) with the tabs option on. Any further thoughts? Thanks as always.

# Configuration
theme:
  name: 'material'
  language: 'en'
  feature:
    tabs: true
    instant: true 

Regards,
Stanley

**Comment by StanleyWei** [comment]
It seems this nav issue appeared only when build the site in Windows WSL environment, not in CENTOS linux one. I will close this ticket for now and thanks for your continuous efforts to maintain and upgrade this great theme.

Cheers,
Stanley

**Comment by squidfunk** [comment]
The configuration format changed. See [the migration guide](https://deploy-preview-1486--mkdocs-material-preview.netlify.com/releases/5/#themefeature) for further details.
