### ISSUE TITLE
h5 changes content rather than just style

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#1522]
## Description

Do to:

https://github.com/squidfunk/mkdocs-material/blob/dc5d86d52e380fa0ec558a616992143312de0a65/src/assets/stylesheets/base/_typeset.scss#L124-L127

all text is transformed to uppercase, thereby breaking the contract that themes should only control _how_ things are displayed and not _what_ is displayed (without choice).

![Capture](https://user-images.githubusercontent.com/9677399/77237101-7bd6d080-6b9b-11ea-8fc5-dbd64f01278d.PNG)

### Expected behavior

`##### GitHub` renders a `<h5>` with text `GitHub`

### Actual behavior

`##### GitHub` renders a `<h5>` with text `GITHUB`

### Steps to reproduce the bug

```yaml
# Header 1
## Header 2
### Header 3
#### Header 4
##### Header 5
###### Header 6
```

### Differentiation

We should differentiate between `h4-h6` instead using either:

1. underline or italics in addition to bold
2. varying levels of bold

Or, add option to give each header an additional [stacked underline](https://stackoverflow.com/a/29916302/5854007)

### Package versions

* Python: 3.8
* MkDocs: 1.1
* Material: 5.0.0rc3

### Project configuration

``` yaml
theme:
  name: material
  features:
    - tabs
```

### System information

* OS: Windows 10
* Browser: Chrome

**Comment by facelessuser** [comment]
I think I'm personally okay with `h5` being normal color with no capitalization. `h6` will look different because it is a little lighter. Sure it looks a little close to normal text size, but what are you going to do as you drill down to that level? I didn't ever notice this as I rarely get past an `h4`.

I think I'm just going to add this locally for the few times I do drill down that far. I'm not sure I like `h5` being capitalized. I find it a bit unexpected.

```css
.md-typeset h5 {
  color: var(--md-default-fg-color);
  text-transform: none;
}
```

**Comment by squidfunk** [comment]
When I said _proposal_ what I meant was actually a concrete example in the form of a PR, but nevermind. 

Unfortunately, from a typographical point of view your suggestions are IMHO impractical. Stacked underlines are horrible, and I’ve never seen headlines being underlined anyway as they may be mistaken for links. Varying levels of bold will increase our payload, as now we not only have to load 400 and 700, but also some other weights in-between which may not be available for the custom font you choose. 400 and 700 is quite a safe bet. And last but not least, making something italic should be done to _emphasize_ content, hence the default style of the `em` tag. Why should a headline be emphasized?

**Comment by squidfunk** [comment]
Also the title is quite misleading. Transforming case does not change content - it’s the same. Uppercase, titlecase and all-caps are stylistic choices.

**Comment by ofek** [comment]
I'm actually doing the same as @facelessuser, it looks fine to me!

I dunno, it's stylistic in so far as CSS can do it, but that's it imo. From my (non-web dev) point of view different unicode code points are... different 😄 

Feel free to change the title though!

**Comment by squidfunk** [comment]
I think we should really leave it as it is. If somebody wants to undo the styling, it's super simple.

**Comment by ofek** [comment]
Sounds good! Though quick question: what would the CSS be to remove all styling from h1-h6?

**Comment by squidfunk** [comment]
It depends on what you mean by _remove_. If you want to reset to the user agent defaults, you can reset all defined properties to `initial`. To find out which properties are set you can either use the developer tools of your browser or see this file:

https://github.com/squidfunk/mkdocs-material/blob/c29e680071ba7f0e18b23ed3415f0fd0b322f30a/src/assets/stylesheets/base/_typeset.scss#L72-L126

**Comment by squidfunk** [comment]
Closing this issue. We'll leave the default styles untouched.
