### ISSUE TITLE
Sidebar flows out of constrained area

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#153]
## Description

If a table is the last element in the content area, the sidebar exceeds the constrained area

### Expected behavior

The sidebar always has the same padding at the top as at the bottom.

![bildschirmfoto 2017-02-13 um 15 11 17](https://cloud.githubusercontent.com/assets/932156/22889452/8590759a-f209-11e6-9542-2ed2d50d2e9f.png)

### Actual behavior

The sidebar exceeds the constrained area.

![bildschirmfoto 2017-02-13 um 10 09 12](https://cloud.githubusercontent.com/assets/932156/22889385/3baa56c6-f209-11e6-913b-c01af0ec669c.png)

This is related to the `md-typeset__table` element. Removing it, corrects the spacing/padding.

### Package versions

* Python: all
* MkDocs: 0.16.1
* Material: 1.0.3

### System information

* OS: all
* Browser: all

**Comment by squidfunk** [comment]
Okay, now this is a very, very strange bug in Chrome. It doesn't happen in Firefox or Safari. The vertical (top and bottom) margin for the table are given in `em` units, while the horizontal margin is given in `rem` units. When I change `em` to `rem`, everything behaves as expected.

It doesn't matter whether the table is at the end. When there is at least one table in the document, it breaks. What the...

**Comment by facelessuser** [comment]
> What the...

That is my constant response as a non-web programmer navigating the differences of different browser quirks :).

**Comment by squidfunk** [comment]
This is indeed a bug in Chrome 56. Tested it on Windows and OSX with 55 through Saucelabs - everything works fine. F**k.

<img width="795" alt="bildschirmfoto 2017-02-14 um 12 47 33" src="https://cloud.githubusercontent.com/assets/932156/22927905/f5d2882a-f2b3-11e6-8f4d-2e38df32927c.png">
