### ISSUE TITLE
IE11 compatibility Docs for MkDocs 5.0.0

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#1537]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

MkDocs v5 is looking really, really good! I realise that support for IE11 has been dropped and I understand the reasons why (the [global marketshare is now just 1.4%](https://caniuse.com/usage-table)), but it's still the only pre-installed browser for Windows 7 and Windows 8.1 and is the only available browser to some business/enterprise users who are unable to install new apps for whatever reason.

MkDocs v5 (RC3 preview) actually looks and works pretty well as it stands (other than seach not working) but I think it could be worthwhile to add a section to the Docs site to give some pointers on how you could add custom CSS for IE11 either via a CSS stylesheet loaded like:
`<link rel="stylesheet" href="mkdocs-material-ie11.css" media="all and (-ms-high-contrast: active), (-ms-high-contrast: none)">
`
or via JavaScript:
`<script>if (/MSIE \d/.test(navigator.userAgent)) document.write('<link rel="stylesheet" href="mkdocs-material-ie11.css">');</script>`
You could perhaps also mention that Search doesn't work, so perhaps you could suggest either hiding it for IE11 users or disable the search input and provide a custom message to upgrade browser to get search functionality. Just a few ideas really, I just think something should be available to IE11 users I think otherwise sites deploying it may end up getting complaints from customers using IE11 that the search doesn't work despite no message or warning showing.

And/Or maybe the theme could have a info/warning included in the template which says something like: 'Internet Explorer is not supported - please upgrade your browser with a link to either https://browsehappy.com/ or https://www.microsoft.com/edge wrapped in a script:
`<script>if (/MSIE \d/.test(navigator.userAgent)) document.write('<div> <\/div');</script>`

**Comment by squidfunk** [comment]
I agree. It would be super awesome if we could write up a guide on how to make v5 work in IE11 (and potentially IE10) or how to notify users that the experience is suboptimal when viewed from IE. Unfortunately, I'm short on time right now and do not consider this a priority, but I'm happy to integrate a guide into the official docs. Note my comment https://github.com/squidfunk/mkdocs-material/issues/1464#issuecomment-594409955 where I took some time to try to get it to work.

> And/Or maybe the theme could have a info/warning included in the template which says something like: 'Internet Explorer is not supported - please upgrade your browser with a link to either https://browsehappy.com/ or https://www.microsoft.com/edge wrapped in a script:
<script>if (/MSIE \d/.test(navigator.userAgent)) document.write('<div> <\/div');</script>

I deliberately decided against doing this in the theme. If you want to support IE, you first would have to remove this notice. However, maybe we could provide a feature flag to enable it, but I'd like to wait to see some solutions before deciding on a solution for `master`.

**Comment by squidfunk** [comment]
This could be solved as part of a tutorial, see #1573

**Comment by coliff** [comment]
> This could be solved as part of a tutorial, see #1573

Great idea to have it as a tutorial. I think I'd like take a look at doing that tomorrow or next week. I'm going to take a look at this [CSS variables ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill) today. If this could be set to run only on IE then that could be a great help.

**Comment by squidfunk** [comment]
That'd be awesome! If the ponyfill doesn't work, we could offer CSS as part of the tutorial to define the colors explicitly, which is probably also less flaky/hacky.

**Comment by squidfunk** [comment]
Is this still relevant or can it be closed? I see no big interest from the community in supporting IE11, as this issue hasn’t received much of a response.

**Comment by coliff** [comment]
sorry I haven't got round to opening a PR for this yet. I think its fine to close this issue for now then.

**Comment by squidfunk** [comment]
No worries! Still willing to include a guide as part if the tutorials if you (or somebody else) is interested in writing one.
