### ISSUE TITLE
Search marked as 'required'

### ISSUE THREAD

**Issue by RDIL** [squidfunk/mkdocs-material#1539]
__I checked that...__

- [X] ... the documentation does not mention anything about my problem
- [X] ... the problem doesn't occur with the default MkDocs template
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... there are no open or closed issues that are related to my problem

## Description

Hovering over the search field, a "this field is required" tooltip shows up.

### Expected behavior

It shouldn't be marked as required unless it is actually clicked on / in focus, because its just kind of confusing having this search bar say it is 'required' when it isn't.  If this isn't worth fixing, I'll be happy to close this, but its just one of those OCD things that gets me annoyed.  

### Steps to reproduce the bug

1. Hover over the search field when it is not open
2. See the tooltip

### Package versions

* Python: 3.8.2
* MkDocs: 1.1
* Material: 5.0.0rc3

### Project configuration

Honestly not relevant, but I have the search plugin enabled.

### System information

* OS: ChromeOS
* Browser: Chrome Canary

**Comment by squidfunk** [comment]
This was already fixed in 035225d6d3a90985310504bc4836c3869914b4ea.

**Comment by RDIL** [comment]
Oh ok

**Comment by squidfunk** [comment]
It's a very minor issue, why there's no RC 4 yet. The fix will just be part of the final release. Funnily the search attribute has been required for years 😉
