### ISSUE TITLE
microsoft edge

### ISSUE THREAD

**Issue by davidsylvestre** [squidfunk/mkdocs-material#154]
## Description

The css does not work in microsoft edge (IE).

### System information

* OS: windows 10
* Browser: microsoft edge

**Comment by squidfunk** [comment]
Erm, maybe you can elaborate on what does not work, then I can address the issues.

**Comment by davidsylvestre** [comment]
The problem is a broken css on mouse move. But this problem happened only in machines at my work.
The test I did at home had no problem.
I believe the cause of the problem is network, firewall or version of edge.

![bug_css](https://cloud.githubusercontent.com/assets/5439927/22970664/9e14f96c-f351-11e6-8c75-5a9d7a09013d.png)

**Comment by squidfunk** [comment]
If you experience any further issues please open a new issue and add detailed steps to reproduce it, so I know what breaks and can fix it. Closing this issue for now.
