### ISSUE TITLE
Nested PDFs and SVGs seem to be ignored as page content

### ISSUE THREAD

**Issue by renoger** [squidfunk/mkdocs-material#1541]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

I´m using pymdownx extensions to embed some assets like pdfs and svg files. With v5 it seems that these are not recognized as page content and the side bars start 'minimizing' as I scroll down. Also the active item in the navigation does not match the current position when I open the admonitions. I did not see this baheviour with v4.

![scroll_issue2](https://user-images.githubusercontent.com/62448529/77425496-1cfb9c00-6dd3-11ea-8028-e1e3aecbdb65.gif)

### Steps to reproduce:
1) Use a standard configuration
2) create a new .md site with below code and replace the path to a generic pdf file and see if you find the same side bar behaviour

```
##a
---
##b

---

##c

###c1

??? info "test pdf"	
	<embed src="img/1.pdf" type="application/pdf" width="100%" height="480px">	
	
??? info "test pdf"	
	<embed src="img/1.pdf" type="application/pdf" width="100%" height="480px">

---

##d

###d1

###d2

###d3
```

	

### Actual behavior

see screenrec

### Package versions

* Python: 3.7.0
* MkDocs: 1.1
* Material: 5.0.0rc3

### System information

* OS: Win10
* Browser: Chrome

**Comment by squidfunk** [comment]
Could you provide a reproducible case? This would make fixing things much easier.

**Comment by renoger** [comment]
@squidfunk I tried to simplify as much as possible and added the markdown content, but please let me know if I shall provide more information. I figured you might already have an idea from which direction this comes.
This also seems to behave differently when I use **serve** vs **build**. Also I don´t see this behaviour if I embed for example a .png image.
Thanks

**Comment by squidfunk** [comment]
Oh my, what a stupid mistake 😅Fixed in 42524ae1.

**Comment by renoger** [comment]
Cool, I´m glad I could add some value then ;)

Stupid question, but will this fix be reflected in the next release or should it somehow already be working for me?

Thanks

**Comment by squidfunk** [comment]
The next release, which will be our on April 7.

**Comment by squidfunk** [comment]
The fix was just released as part of RC 4. See #1498 for details.

**Comment by renoger** [comment]
Sorry to bug you again @squidfunk. I just tried the new RC4 which fixes the described issue, all good!
But there is another related behaviour which is why I´m posting it here (happy to open a new issue if you prefer).

So what I´m seeing now is that the active nav link (blue) on the right is jumping when I´m opening admonitions. Also when I have both admonitions open the last item in my nav is active - even though I can´t even scroll down that far. I hope you see what I mean in the gif.

![scroll_issue3](https://user-images.githubusercontent.com/62448529/77832225-be1c8680-7134-11ea-9d22-0a0b24c2528e.gif)

**Comment by squidfunk** [comment]
That’s indeed a big, so you’re encouraged to open an issue. However, it’s very minor, so it’s no blocker for the final release.
