### ISSUE TITLE
[css] Issue with <code> in td alignment

### ISSUE THREAD

**Issue by RDIL** [squidfunk/mkdocs-material#1542]
## Description

Text and `<code>` elements aren't matched in alignment.

### Expected behavior

They should be at the same height

### Actual behavior

![Screenshot 2020-03-24 at 2 24 35 PM](https://user-images.githubusercontent.com/34555510/77465123-8df48100-6dde-11ea-9c9d-dde6651adc3e.png)

### Steps to reproduce the bug

1. Put some `<code>` inside a table

### Package versions

* Python: `python --version` latest
* MkDocs: `mkdocs --version` 1.1
* Material: `pip show mkdocs-material | grep -E ^Version` 5rc3

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: ...
* Browser: ...

**Comment by squidfunk** [comment]
Please provide more info like browser version and the exact Markdown causing the issue. This is the deploy preview on iOS - no error:

![BCE5B9EE-522A-4B6E-9FA1-B026880714A6](https://user-images.githubusercontent.com/932156/77478495-5ad1e200-6e1e-11ea-98c1-6a458c5b94ef.png)

**Comment by RDIL** [comment]
Using chrome on chromeos - the markdown is auto-generated - cc @pawamoy

**Comment by pawamoy** [comment]
Hey @RDIL, @squidfunk!

Here is the explanation. I guess the screenshot @RDIL posted comes from documentation "auto-generated" by `mkdocstrings` (the `mkdocs` plugin I'm developing). The text in the description cell was originally Markdown (written in a Python docstring). When converting to HTML, `md.convert` wrapped it in a `<p>` tag. And `mkdocs-material` defines some margins for such elements.

In the documentation of `mkdocstrings`, I recommend certain CSS rules to "fix" that: https://pawamoy.github.io/mkdocstrings/handlers/python/#recommended-style, unfortunately I previously missed that case, and documentation is not up-to-date :slightly_smiling_face: 

@RDIL, try using the recommended CSS rules, and add `!important` to the `td p` margins:

```css
/* For pieces of Markdown rendered in table cells. */
td p {
  margin-top: 0 !important;
  margin-bottom: 0 !important;
}
```

I know `!important` is not a best-practice, unfortunately my designer skills are very low, and this is the only way I found to "fix" the rendering :smile: 

Also, this quick fix will actually remove vertical space between paragraphs if there are several, making things worse...

**Comment by RDIL** [comment]
Oh, thanks!
