### ISSUE TITLE
🙋 User Survey 2020 – tell us about you! (takes 2 minutes)

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#1551]
__Material for MkDocs 5__ is around the corner and we would like to learn more __about you__ and __how you use__ this project. Take the survey and help us learn about your experiences, so we can make this project even better:

https://forms.gle/4mJgtJRbvZr1spk38

The results will be shared here, excluding the project website URLs and final comments, so anonymity is guaranteed.

**Comment by wilhelmer** [comment]
Under "What feature or aspect do you like the most?", I think there should be an option for "Design" or "Layout", whatever describes the overall look & feel of the theme best.

**Comment by squidfunk** [comment]
That’s a great idea. I’ll see if I can add it without destroying the form 😅

**Comment by squidfunk** [comment]
Done! BTW, I will share the results here, except the project website URLs!

**Comment by Mattwmaster58** [comment]
For the question `Did you customize Material for MkDocs`, it's required that you answer one of the following:
 - Yes, with additional CSS
 - Yes, with additional JavaScript
 - Yes, by using theme extension
 - Yes, by forking the repository

What if I didn't customize it at all? It's required that we select one of those but I'm not sure that was intented.

**Comment by squidfunk** [comment]
@Mattwmaster58 the question should not be required, you're right. Thanks! Fixed it 😊

**Comment by squidfunk** [comment]
The survey is closed now. 98 responses, pretty good! I'll release the results as soon as I find some time to crunch the numbers.

**Comment by squidfunk** [comment]
I started diving into the numbers and will release the insights within the next days on Twitter:
https://twitter.com/squidfunk/status/1259480498608508928

<img width="597" alt="Bildschirmfoto 2020-05-10 um 17 36 21" src="https://user-images.githubusercontent.com/932156/81503618-df03fa00-92e4-11ea-9cbf-d719645b96a2.png">

Quite some interesting stuff and actionables to be deduced 😊

**Comment by wilhelmer** [comment]
Not the worst idea to add Look & Feel to the list 😄

**Comment by squidfunk** [comment]
How could I forget that? Thank you!
