### ISSUE TITLE
5.0.0rc4: Only first page is being printed in Firefox

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#1555]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Printing is not working properly in Firefox v74. When printing a topic, only the first page is being printed.

Works in Chrome, but not in FF.

@squidfunk, https://github.com/squidfunk/mkdocs-material/issues/1498#issuecomment-605902901
> Confirmed. I guess it has to do with `overflow: hidden` and `flex` which should be easy to remove for print styles on `body`.
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=258397, respectively
> https://bugzilla.mozilla.org/show_bug.cgi?id=521204

### Expected behavior

All pages should be printed. The print preview should show all pages needed to print the topic.

### Actual behavior

Only the first page is printed. Print preview only shows one page.

### Steps to reproduce the bug

Steps to reproduce:

1. Set up a minimal project with one fairly long topic (>1 page when printed).
2. Build.
3. Open topic in Firefox 74.
4. File > Print preview.

**Comment by squidfunk** [comment]
Fixed in cfebec40.

**Comment by squidfunk** [comment]
On a second note, I realized that Firefox unintendely shows the details marker for summary elements:

<img width="474" alt="Bildschirmfoto 2020-04-02 um 09 59 40" src="https://user-images.githubusercontent.com/932156/78225148-0687cb80-74ca-11ea-9b77-3ab70aeb8b3b.png">

This was fixed in b9d44e04.

**Comment by wilhelmer** [comment]
Oh, that was unintended? Didn't look too bad. But it's better for cross-browser harmonization of course. Thanks for fixing both!

**Comment by squidfunk** [comment]
Yes, as the arrow on the right already shows the state (i.e. collapsed, expanded).

**Comment by squidfunk** [comment]
Material for MkDocs 5 was just released, which includes this fix!

**Comment by gabm** [comment]
This Problem appeared again.. it works in 5.0.0 to 5.1.1 and stops working again in 5.1.2 through to 5.2.2...

Same problem: only the first page in Firefox is printed, the rest are empty

**Comment by wilhelmer** [comment]
True, I can confirm that.

**Comment by gabm** [comment]
Might be this commit? https://github.com/squidfunk/mkdocs-material/commit/398cd895c3d4608c06cf255d6a08c9e9d972f60e
