### ISSUE TITLE
5.0.0rc4: Links broken after history changes in instant mode

### ISSUE THREAD

**Issue by lazka** [squidfunk/mkdocs-material#1556]
Instant loading bug (Firefox and Chromium):

* Enable instant mode in the config
* Click on a link to trigger instant loading
* History back
* Try to click on the same link again
* Actual: Nothing happens
* Expected: The link works

Using 5.0.0rc4

First posted here: https://github.com/squidfunk/mkdocs-material/issues/1498#issuecomment-605938907

**Comment by squidfunk** [comment]
Should be fixed as of 00ad2d74. The fix will be part of the final release on Tuesday.

**Comment by lazka** [comment]
Awesome, thanks!

**Comment by squidfunk** [comment]
Remember that instant loading is still experimental, but it should be reasonably stable by now unless you have a lot of modifications in place. Please continue to report any hiccup you experience, so we can transition from experimental to stable as soon as possible 🤓

**Comment by lazka** [comment]
I only use some extra CSS. Will do, thanks

**Comment by squidfunk** [comment]
Material for MkDocs 5 was just released, which includes this fix!
