### ISSUE TITLE
Link doesn't exist

### ISSUE THREAD

**Issue by majkinetor** [squidfunk/mkdocs-material#1557]
My link checker fails here:

https://github.com/squidfunk/mkdocs-material/blob/b85b682b8b650154634cde2d28c43bac4fa9ebd5/material/base.html#L76

Doesn't look normal.

**Comment by squidfunk** [comment]
That's a preconnect instruction to speed up font loading. The line is correct, despite Google returning a 404.

**Comment by majkinetor** [comment]
Thx for the info.
