### ISSUE TITLE
syntax highlighing for code blocks

### ISSUE THREAD

**Issue by bsergean** [squidfunk/mkdocs-material#1558]
Hi there,

I've just tried material today, I thought it looked very good. However I had some block of C++ code which were highlighted properly, and it isn't the case anymore. Is that a configuration I need to enable ?

Thanks !

```
# include <iostream>

// my doc is for a C++ project, and has tons of things like that which I like to be highlighted.
std::cout << "foo" << std::endl;
```

**Comment by bsergean** [comment]
Here is the doc -> https://machinezone.github.io/IXWebSocket/

Found this thread that seems relevant -> https://github.com/mkdocs/mkdocs/issues/263

**Comment by facelessuser** [comment]
I see you posted the code, but what highlighter are you using? Are you indented the code block? Using fences? Are you expecting it to guess your language? Are you specifying the language?

Will work with [CodeHilite](https://python-markdown.github.io/extensions/code_hilite/)  and/or [Fenced Code](https://python-markdown.github.io/extensions/fenced_code_blocks/).

It also works with [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) which allows for nesting fenced code in lists and other constructs. 

Material expects that you are using [Pygments](https://pygments.org/).

CodeHilite enables highlight guessing by default. Fenced Code might as well if you don't specify a language, but I don't recall.

SuperFences does not enable guessing by default.

If you do not have guessing enabled, you need to specify the language:

````
```c++
# include <iostream>

// my doc is for a C++ project, and has tons of things like that which I like to be highlighted.
std::cout << "foo" << std::endl;
```
````

<img width="936" alt="chrome_ERZj8prnCl" src="https://user-images.githubusercontent.com/1055125/78092603-6af14080-738d-11ea-8807-8d5859232a07.png">

In this example, the colors are a bit understated, it depends on the language and code you provide.

**Comment by bsergean** [comment]
Thanks for the answer.

I had one block of code with a 'hint' 

```cpp
printf("this is C++");
```

I switched it to C++ but no code highlighting still ...

$ cat mkdocs.yml 
site_name: IXWebSocket
theme:
  name: 'material'


My doc page -> https://machinezone.github.io/IXWebSocket/ <https://machinezone.github.io/IXWebSocket/>

My markdown files -> https://github.com/machinezone/IXWebSocket/tree/master/docs <https://github.com/machinezone/IXWebSocket/tree/master/docs>

... still puzzled ...

**Comment by facelessuser** [comment]
You don't seem to be using any extensions: https://github.com/machinezone/IXWebSocket/blob/master/mkdocs.yml

I see no fenced code extension of any kind, but I see you suing fenced code syntax. That's probably why it isn't working.

**Comment by bsergean** [comment]
Let me try to add it explicitly. That page suggest that it is on by default (fenced_code).

https://www.mkdocs.org/user-guide/configuration/#formatting-options
Formatting options

markdown_extensions

MkDocs uses the Python Markdown <https://python-markdown.github.io/> library to translate Markdown files into HTML. Python Markdown supports a variety of extensions <https://python-markdown.github.io/extensions/> that customize how pages are formatted. This setting lets you enable a list of extensions beyond the ones that MkDocs uses by default (meta, toc, tables, and fenced_code).

**Comment by bsergean** [comment]
Still no luck ... I wonder if any users of 'material' where code highlighting works could share their settings ...

**Comment by facelessuser** [comment]
Material itself has working code highlighting: https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml.

**Comment by facelessuser** [comment]
@bsergean If you are still having trouble after referencing the example, I can try tomorrow and pull your project and show you how to get it working.

**Comment by squidfunk** [comment]
Have you followed https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#installation?

MkDocs uses Highlight.js, whereas Material relies on Pygments by default.

**Comment by facelessuser** [comment]
@bsergean I pulled your referenced project, and it worked fine for me, I assume you figured it out?

I created a clean virtual environment and pip installed `mkdocs-material`.

<img width="418" alt="chrome_8679iPC4ve" src="https://user-images.githubusercontent.com/1055125/78166486-16d87180-740a-11ea-8883-5ecd0f0422ac.png">

Then only thing I would suggest is that CodeHilite enables language guessing by default, and it doesn't always guess great. I'd turn it off.

Also, you won't be able to nest fenced code blocks in lists with CodeHilite and Fenced Code. SuperFences is the way to go for that. If you go SuperFences, all you need to do is include it with `pymdownx.superfences`. It doesn't guess languages by default. But you can always enable it by configuring `pymdownx.highlight`. Just a recommendation though, people should use what they like 🙂 .

**Comment by squidfunk** [comment]
Closing. This is clearly a configuration issue, not an issue with the theme itself as syntax highlighting works in the [official docs](https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#c_1).

**Comment by bsergean** [comment]
Sure, thanks for the help guys.

I'll report what I found eventually, I didn't even test locally, I was doing it through a remote builder so this might explain my problems.

**Comment by facelessuser** [comment]
Yup, locally had no issues

**Comment by Tails86** [comment]
I found info in this issue super helpful - found through a google search. 

Just to be extra explicit here to help other mkdocs n00bs like me, this is what @facelessuser is referring to within https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml :
```
markdown_extensions:
  - pymdownx.superfences
```
