### ISSUE TITLE
Allow structured left-nav menu while having tabs

### ISSUE THREAD

**Issue by iBug** [squidfunk/mkdocs-material#1560]
**I checked that...**

- [ ] ... the documentation does not mention anything about my idea
- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

Explanation:

- The documentation does mention about the current tabbing behavior, but isn't what I'm expecting
- This would be a rather breaking change as existing projects would have to update the `nav:` key in their `mkdocs.yml` to match the new behavior, although it's definitely possible to keep both setups (perhaps via another configuration key)
- ...

## Description

With the current behavior (grouping top-level entries under the first tab), it's impossible to have cascaded menu items on the left nav bar with tabs enabled. This is IMO counter-intuitive as it's more natural to *define tabs* and *define their content*. While I have to admit the current setup makes enabling / disabling tabs less of a mess (with little to no need to alter the `nav:` key in `mkdocs.yml`), it's not productive in certain cases (see below).

### Use Cases

We have a website for our laboratory where we've built different software systems and conduct many course experiments through them. Each system is complex per se and is extensively documented, so it'd be nice if we could have one tab for each system. We also need two to three levels of cascading entries so we've been looking forward to tweaking this theme or having it supported vanilla.

[Docusaurus](https://docusaurus.io/docs/en/installation) by Facebook supports cascaded entries under tabs in a way similar to this and it's a good reference of implementation.

### Screenshots / Mockups

I think my description is clear enough `:)`

**Comment by squidfunk** [comment]
Thanks for the thorough explanation! Unfortunately, we cannot implement this, as it would be a breaking change with little upside. You can implement it via theme extension, but it will have pretty strict requirements regarding the structure of your navigation in `mkdocs.yml`, which is why I decided to implement it the way you currently see it.

However, note that nesting works as expected from a second level on. Only the first levels will be expanded into the tabs you see. Also note that you have to handle mobile navigation somehow.

You may be better off with Docusaurus, but IMHO navigation, especially on mobile, isn’t one of its strengths.

**Comment by iBug** [comment]
Sorry I went stupid for once. I didn't notice that this FR is directly available exactly as described - I only have to group all top-level entries under one new entry before they're all shown under the first tab and with cascading for nested items.

Thank you for your great theme. Creating beautiful documentation would never have been so enjoyable had it not been this theme.

**Comment by squidfunk** [comment]
BTW, if you feel that the documentation at this point can be improved, I'd be happy to merge a PR! See the [deploy preview](https://deploy-preview-1486--mkdocs-material-preview.netlify.com/getting-started/#tabs) for the latest version which will be released on April 7.

**Comment by iBug** [comment]
I'm glad to be able to help. However [the `getting-started.md` file](https://github.com/squidfunk/mkdocs-material/blob/master/docs/getting-started.md) doesn't match the content on the page you provided, and none of the branches suggest a "latest" state (judging by branch name), so I'm unsure where to start from. Could you please kindly point out a direction?

**Comment by iBug** [comment]
Oops, I should've examined more thoroughly. But frankly, I wasn't expecting that a branch with the name `refactor/rxjs-typescript` would actually be the latest development branch (or whatever producing all these RC versions).
