### ISSUE TITLE
mkdocs-2.9.4 pymdown-extensions requirement needs to be modified

### ISSUE THREAD

**Issue by leifliddy** [squidfunk/mkdocs-material#1566]
## Description

I'm running running ```mkdocs-material-2.9.4``` on an older system.

**requirement.txt** has this dependency listed:
```pymdown-extensions>=4.11```

However, ```pymdown-extensions > 6.2.1``` has a ```Markdown>=3.2``` requirement, which is not supported with python2 
 
### Expected behavior

I should be able to download ```mkdocs-material==2.9.4``` and it's dependencies with ```pip27 download```

### Actual behavior
```
[root@pro tmp]$ pip2.7 download mkdocs-material==2.9.4
https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting mkdocs-material==2.9.4
  Downloading mkdocs_material-2.9.4-py2.py3-none-any.whl (573 kB)
     |################################| 573 kB 950 kB/s 
  Saved ./mkdocs_material-2.9.4-py2.py3-none-any.whl
Collecting pymdown-extensions>=4.11
  Using cached pymdown_extensions-6.3-py2.py3-none-any.whl (198 kB)
  Saved ./pymdown_extensions-6.3-py2.py3-none-any.whl
Collecting Pygments>=2.2
  File was already downloaded /private/tmp/Pygments-2.5.2-py2.py3-none-any.whl
Collecting mkdocs>=0.17.3
  File was already downloaded /private/tmp/mkdocs-1.0.4-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement Markdown>=3.2 (from pymdown-extensions>=4.11->mkdocs-material==2.9.4) (from versions: 1.7, 2.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.2.0, 2.2.1, 2.3, 2.3.1, 2.4, 2.4.1, 2.5, 2.5.1, 2.5.2, 2.6, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.10, 2.6.11, 3.0, 3.0.1, 3.1, 3.1.1)
ERROR: No matching distribution found for Markdown>=3.2 (from pymdown-extensions>=4.11->mkdocs-material==2.9.4)
```

```pip``` is attempting to download the latest version of ```pymdown-extensions``` which is version ```6.3```
```pymdown-extensions-6.3``` has a ```Markdown>=3.2``` dependency, which is not compatible with python2. 
 
### Steps to reproduce the bug

run: ```pip2.7 download mkdocs-material==2.9.4```

### Package versions

* Python: `Python 2.7.17 `
* MkDocs: `mkdocs, version 0.17.5`
* Material: `2.9.4`

### Project configuration
NA

### System information

NA

###Resolution
Unfortunately, with the system I'm working on, I must following a strict set of procedures that include downloading the python packages from pip, then transferring the resulting packages to another system to be installed.

I would be helpful if you could modify the ```requirements.txt``` file of the  ```2.9.4``` release 
from:
``` 
# Direct dependencies
mkdocs>=1
Pygments>=2.2
pymdown-extensions>=4.11
 ```
to

```
# Direct dependencies
mkdocs>=1
Pygments>=2.2
pymdown-extensions>=4.11,<6.3
```

I'm not sure if it's possible to retroactively modify a release.

**Comment by facelessuser** [comment]
Material 2.9.4 is super old. Times move on, later builds fixed version issues. It not common (like at all) for people to retroactively re-release old versions with new requirements. You can always fork that tag and make the changes yourself, and use your own fork.

**Comment by squidfunk** [comment]
Seconded. The general note is to keep this project always up to date as it‘s moving fast.

**Comment by leifliddy** [comment]
Thanks for your quick response! It's not my system, so I'm limited in what I can do. But, I found a way to work around the issue by creating a requirements.txt file and then running:
```pip2.7 download -r requirements.txt mkdocs-material```

Closing issue...
