### ISSUE TITLE
Scroll active navigation/toc item into view

### ISSUE THREAD

**Issue by majkinetor** [squidfunk/mkdocs-material#1567]
Is this already supported or am I missing something ? If not, consider this feature.

While the nav element is currently highlighted, it is not scrolled to so depending on the screen/window size it is not visible.

For example Sphinx supports this. Here is example:

* https://docs.mayan-edms.com/parts/license.html

This will hightlight license in nav on the left.

**Comment by squidfunk** [comment]
This is a nice idea, but has a rather low priority. Material for MkDocs 5 is going to be released today, which might cause some problems downstream like with every major version, so my next weeks are quite set. If somebody wants to go ahead, knock yourself out 😊

**Comment by majkinetor** [comment]
Oh, no problem. This is definitelly low prio stuff, more pedantic then anything else.

**Comment by squidfunk** [comment]
How should this functionality work exactly? `scrollIntoView` doesn't work on scrollable containers, just on the body. Would you care to prototype the functionality? I could integrate it then.

**Comment by majkinetor** [comment]
I have negative time available now but I will try to get back on it in few weeks.

**Comment by squidfunk** [comment]
There was literally no reaction on this proposal, except the OP. Give the missing interest, I’m closing this. Also, I haven't see any site implementing this.

**Comment by max-hardcoder** [comment]
Hi, 
I'm interressed in that kind of functionnality, cause the left nav is huge (autogenerated) and we have to put a handwritted nav in md file to navigate through the site cause it's too long to find the nav item.. but i do understand the low priority.
Thank's for reading.

**Comment by chr-hen** [comment]
Hi there,

I've read through this thread and seen that it's been deemed quite a low-priority change, which I understand.

I'd just like to try and revive some interest in this, though, given that myself and other users and finding it quite problematic as the nav section grows on a given project. It would be really helpful if the nav bar automatically scrolled to the current page.

**Comment by squidfunk** [comment]
@chr-hen this functionality was added in insiders-4.8.0, see https://github.com/squidfunk/mkdocs-material/issues/2155#issuecomment-1030816004.

**Comment by chr-hen** [comment]
@squidfunk Thanks a lot for your prompt reply and all your work on this awesome project, much appreciated.
