### ISSUE TITLE
Missing bottom margin on small screens (

### ISSUE THREAD

**Issue by jean-emmanuel** [squidfunk/mkdocs-material#1572]
Hi,
Awesome v5 :)
It seems some bottom margin is missing on small resolutions, here is a screenshot, page scrolled to bottom :
![screenshot-2020-04-07-20:07:26](https://user-images.githubusercontent.com/5261671/78704139-b2d31300-790b-11ea-8c1c-918fc24509c1.png)

**Comment by squidfunk** [comment]
Thanks for reporting, however, I cannot reproduce this. Please provide more information on your browser, operating system etc, i.e. use the issue template. It's not happening in Chrome on macOS:

<img width="861" alt="Bildschirmfoto 2020-04-07 um 20 10 50" src="https://user-images.githubusercontent.com/932156/78704276-e877fc00-790b-11ea-8c09-3ba15dc58928.png">

**Comment by jean-emmanuel** [comment]
My deepest apologies, it's a bug in chromium (76) that's fixed now, I should have checked it :)

**Comment by squidfunk** [comment]
No worries, strange that this is a bug in Chromium, though.

**Comment by ppo** [comment]
If find the content too close at the bottom. Wouldn't it be better with a 1.5rem bottom margin, like the top one?

**Comment by squidfunk** [comment]
You can adjust the margins with a few lines of CSS. If we make it bigger by default, somebody else will come along and will want it more narrow 😉 After all, Material for MkDocs is super easy to customize and extend.

**Comment by ppo** [comment]
😂 Yeah, you're right.

I'm fixing that in a custom CSS… because I feel it makes more sense to have the same margins on top and bottom… and should therefore be the default. Anyway, you're the boss 😉

**Comment by victorbnl** [comment]
> somebody else will come along and will want it more narrow 

You're right but here there is way not enough space, and I think we all agree to say there should be more
