### ISSUE TITLE
Error when using a different language in version 5

### ISSUE THREAD

**Issue by tiangolo** [squidfunk/mkdocs-material#1574]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

After upgrading `mkdocs-material` to version 5, when using a specific language (e.g. `es`) it can't build the site.

### Expected behavior

To build the site in the specified language (if it's one of the supported languages).

### Actual behavior

An error is thrown.

### Steps to reproduce the bug

* Create a new directory, e.g. `material5`.
* Create a new Python environment for it (e.g. with Poetry)
* Install `mkdocs-material` in it (it gets the latest version, 5)
* Create a directory `docs`.
* Create an empty file `./docs/tutorial.md`.
* Create a `mkdocs.yml` file with:

```YAML
site_name: MkLorum
theme:
  name: material
  language: es
```

So, the directory tree looks something like:

```
.
├── docs
│   └── tutorial.md
├── mkdocs.yml
├── poetry.lock
└── pyproject.toml
```

Then serve with `mkdocs`:

```console
$ mkdocs serve

...

  File "/home/user/.cache/pypoetry/virtualenvs/material5-JlbqKcKF-py3.6/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/user/.cache/pypoetry/virtualenvs/material5-JlbqKcKF-py3.6/lib/python3.6/site-packages/material/partials/language/es.html", line 16, in template
    "search.config.lang": "es",
jinja2.exceptions.TemplateSyntaxError: expected token ',', got ':'
```

An error is thrown :cry: 

But removing the `language: es`, so that `mkdocs.yml` is like:

```YAML
site_name: MkLorum
theme:
  name: material
```

Fixes the error:

```console
$ mkdocs serve

INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Documentation built in 0.13 seconds
[I 200407 21:03:39 server:296] Serving on http://127.0.0.1:8000
INFO    -  Serving on http://127.0.0.1:8000
[I 200407 21:03:39 handlers:62] Start watching changes
INFO    -  Start watching changes
[I 200407 21:03:39 handlers:64] Start detecting changes
INFO    -  Start detecting changes
```

### Package versions

* Python: `python --version`: Python 3.6.9 :: Anaconda custom (64-bit)
* MkDocs: `mkdocs --version`: mkdocs, version 1.1
* Material: `pip show mkdocs-material | grep -E ^Version`: Version: 5.0.0

### Project configuration

``` yaml
site_name: MkLorum
theme:
  name: material
  language: es
```

### System information

* OS: Ubuntu 18.04
* Browser: Chrome

**Comment by squidfunk** [comment]
Confirmed! It's actually a syntax error in the template. Fixed in 184dfea0, will issue 5.0.1 straight away.

**Comment by squidfunk** [comment]
5.0.1 was just released. Thanks for reporting!

**Comment by tiangolo** [comment]
Wow, that was fast! Thanks a lot!

And I didn't say before, thanks for this awesome theme! I'm using it everywhere :smile: 
(https://fastapi.tiangolo.com/ and https://typer.tiangolo.com/)
