### ISSUE TITLE
Release 5.0.1 no longer displays Font Awesome in text

### ISSUE THREAD

**Issue by rei-vilo** [squidfunk/mkdocs-material#1577]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

mkdocs-material 5.0.1 no longer displays FontAwesome icons in text.

### Expected behavior

Display FontAwesome icons in text.

### Actual behavior

FontAwesome icons in text not displayed.

### Steps to reproduce the bug

1. ... Add `fontawesome_markdown` to `markdown_extensions` in `mkdocs.yml`
2. ... Mention `:fa-download:` in MarkDown page.
3. ... Launch `mkdocs build`

### Generated html code comparison

<img width="1069" alt="Capture 2020-04-08 à 10 03 30" src="https://user-images.githubusercontent.com/951776/78759636-36c6e280-7980-11ea-8ee9-5bff943c7bd6.png">

The html code generated by mkdocs-material doesn't seem to include `<link href="../css/font-awesome.min.css" rel="stylesheet">`.

### Package versions

* Python: `python --version` Python 3.7.6
* MkDocs: `mkdocs --version` version 1.1
* Material: `pip3 show mkdocs-material | grep -E ^Version` Version: 5.0.1

### Project configuration

``` yaml
site_name: Test

theme:
    name: 'material'
    custom_dir: theme

markdown_extensions:
    - fontawesome_markdown
```

Test page

```
# Test

+ The :fa-download: on top of the current page downloads it as a PDF document. 
```

### System information

* OS: ... macOS 10.15.4
* Browser: ... Safari 13.1

### Screen-shots

<img width="899" alt="Capture 2020-04-08 à 09 49 29" src="https://user-images.githubusercontent.com/951776/78758814-fdda3e00-797e-11ea-9bbd-b133a24aa9ec.png">

<img width="899" alt="Capture 2020-04-08 à 09 50 26" src="https://user-images.githubusercontent.com/951776/78758818-ffa40180-797e-11ea-8eb8-c316a3ae6de5.png">

### Workaround

Add `<link href="../css/font-awesome.min.css" rel="stylesheet">` manually on top of each Markdown page.

**Comment by squidfunk** [comment]
That's correct, FontAwesome was removed in favor of direct inlining SVG icons. You can always integrate the font yourself with `extra_css` if you want to use it.

**Comment by rei-vilo** [comment]
Thank you for your prompt answer! 

I really like the very convenient way of adding an icon with just `:fa-download:` and I do understand saving unnecessary loading of CSS. 

Is there a similar way for SVG icons direct inlining? Could you please provide an example?

Otherwise, I'll wait for the next minor version.

**Comment by squidfunk** [comment]
As said, follow the linked PR, so you'll have to wait or use FontAwesome yourself, as described.

**Comment by rei-vilo** [comment]
Ok, I tested the PR. Only **Octicons** are sized correctly.

<img width="1440" alt="Capture 2020-04-08 à 12 03 43" src="https://user-images.githubusercontent.com/951776/78771960-48fd4c80-7991-11ea-8373-5ef60daa929f.png">

**Comment by squidfunk** [comment]
Yes, the PR isn't ready yet.

**Comment by squidfunk** [comment]
Closing in favor of the linked PR.

**Comment by rei-vilo** [comment]
Thanks!

**Comment by jholdstock** [comment]
Hi @squidfunk,

I notice that #1575 was merged but then cb99a22fdfd26715d6d705d2c7b5cd6002b93587 seemed to remove fontawesome support from the docs before 5.0.2 was tagged. Could you please clarify the recommended way to include FA icons in markdown text when using 5.0.2?

**Comment by squidfunk** [comment]
For now it’s best to include the icon font yourself. We’re working on a better solution.

**Comment by squidfunk** [comment]
@jholdstock 5.1.0 was just released which adds support through [mkdocs-material-extensions](https://github.com/facelessuser/mkdocs-material-extensions/):

<img width="502" alt="Bildschirmfoto 2020-04-12 um 20 13 34" src="https://user-images.githubusercontent.com/932156/79076421-518bb500-7cfa-11ea-881c-5af7db3ba4c8.png">

https://squidfunk.github.io/mkdocs-material/extensions/pymdown/#icons

**Comment by jholdstock** [comment]
Thanks @squidfunk, this works perfectly. Thanks for the quick turnaround, and thanks for all the work you have put into mkdocs-material!

**Comment by OdderOwl** [comment]
I did as described on the page, but get 

> Config value: 'markdown_extensions'. Error: Invalid Markdown Extensions configuration

 when I try to build.
Also, it is not quite clear to me how to use it. What does this mean:

> Then, using the folder structure of Material's .icons folder, you can specify icons:

What exactly needs to be done after installing and including it in the config?

**Comment by squidfunk** [comment]
> Config value: 'markdown_extensions'. Error: Invalid Markdown Extensions configuration

That's probably a parsing error.

> What exactly needs to be done after installing and including it in the config?

You can reference any file from here:
https://github.com/squidfunk/mkdocs-material/tree/master/material/.icons

For example, `:fontawesome-brands-github:` resolves to
https://github.com/squidfunk/mkdocs-material/blob/master/material/.icons/fontawesome/brands/github.svg
