### ISSUE TITLE
a stale 'src' directory installed to top-level python module directory

### ISSUE THREAD

**Issue by cheese** [squidfunk/mkdocs-material#1582]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

There is a stale 'src' directory installed to top-level python module directory. For example on CentOS 8, there is a directory `/usr/local/lib/python3.6/site-packages/src/` created with an empty `__init__.py`.

### Expected behavior

No such directory
### Steps to reproduce the bug

1. pip install mkdocs-material

### Package versions

* Python: pip install mkdocs-material
* MkDocs: mkdocs, version 1.1 from /usr/local/lib/python3.6/site-packages/mkdocs (Python 3.6)
* Material: Version: 4.6.3(the same with 5.0.1)

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: ...
* Browser: ...

**Comment by facelessuser** [comment]
@squidfunk, sounds like you may need to ignore the src directory when installing. Pymdownx does this to avoid installing tools and tests: https://github.com/facelessuser/pymdown-extensions/blob/master/setup.py#L55.

Since you don't have any nested modules, you can probably just specify `src` (no wildcard needed).

**Comment by squidfunk** [comment]
I assumed that the `MANIFEST.in` file is honored?

https://github.com/squidfunk/mkdocs-material/blob/7b2434509094408246ebb0a040b98e061ab28c38/MANIFEST.in#L5

**Comment by hroncok** [comment]
Not if you install from git (tarball) directly. MANIFEST.in is useful to remove the files from sdist, but this would IMHO better be handled on the "don't install level" not on the "don't sdist level".

Question: for what purpose is there the `__init__.py` file in the `src` folder? If it is not there, `find_packages` won't find it. (But explicitly excluding it as @facelessuser shows is safer.)

**Comment by squidfunk** [comment]
Thanks for clarifying. My Python-bundling-fu is quite bad 😊 the entire `src` folder is built to `material`, so the file needs to be there to be copied. So of we follow @facelessuser’s advise we should be good?

**Comment by hroncok** [comment]
> So if we follow @facelessuser’s advise we should be good?

I think so, yes.

**Comment by squidfunk** [comment]
Great, fixed in 44a51660.

**Comment by facelessuser** [comment]
Manifest controls what gets bundled in the release. I bundle tests and such in my release, but setup is discovering Python modules and installing them. So we add the exclusion in setup which controls the install, not the packaging.

**Comment by squidfunk** [comment]
Closing. If the error still occurs, please reopen.
