### ISSUE TITLE
Add option for separate link colours

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#1583]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description
It would be a nice addition to have two options to set a different colour for links and when hovering over them.
The available colours could just be the one already provided and it could default to either the primary or accent colour depending on what option is missing or invalid.

The reason is simple: Readability.
Depending on what colour theme (background colour) and primary/accent colours you have set are links barely readable.
This is especially the case when using links in inline code, as - depending on your modifications - the text becomes barely distinguishable from the code background.

I f.e. want to use indigo as primary colour, but due to me using css for having a dark theme is the link colour barely readable on inline code, forcing me to either customize the CSS (Which I'm not good at) or switch to a different, much brighter colour which I wouldn't like to do.

### Use Cases
The aforementioned cases would apply here and I'm sure people would love to have a colour for links, different to the primary and accent colour set.

### Screenshots / Mockups

Colour indigo while using a dark theme:
![image](https://user-images.githubusercontent.com/11576465/79003683-5feb9c80-7b53-11ea-8cb2-e9089cfb66fa.png)

Colour yellow without any custom CSS:
![image](https://user-images.githubusercontent.com/11576465/79003769-890c2d00-7b53-11ea-910b-66a7ca70cf50.png)

**Comment by squidfunk** [comment]
This topic can (and will) be revisited when implementing dark mode, as some more variables/branches could be necessary.

**Comment by squidfunk** [comment]
Added in https://github.com/squidfunk/mkdocs-material/commit/1fc6af1f158921ba801177992b1c9e8c31084858#diff-84f37ad4f75d6bdb8cc32a1b513f5e65R65 as part of the dark mode branch.

**Comment by squidfunk** [comment]
Released as part of 5.2.0! You can now set the link color with `--md-text-link-color`.

**Comment by Andre601** [comment]
Would this be set within custom css?

**Comment by facelessuser** [comment]
Yes, it is a CSS variable.

**Comment by Andre601** [comment]
I'm not quite sure how I would now implement this (I honestly assumed this to become an option in the mkdocs.yml)

Like what css would I have to add/alter in order to display the link as a bright blue (cyan?) and make it brighter when hovering over it.

**Comment by squidfunk** [comment]
we might add a tutorial on this in the future, but I currently don’t have the time to write one. There might also be some guidance on the tutorials branch, see open PRs. The issue itself is fixed, as the variable is now defined.

**Comment by Andre601** [comment]
I tried to add it now, but still are lost

What I tried:
```css
body {
  --md-text-link-color: #3498db;
}
```
The above doesn't work. I did add it as extra_css and there's no other css files that would alter colors on any way.
I use css and not scss, so it might by a syntax issue?
From my basic css knowledge should it accept hexadecimal values, right?

**Comment by squidfunk** [comment]
You need to understand [CSS Specificity](https://dev.to/emmabostian/css-specificity-1kca)

**Comment by denreyrey** [comment]
In your extra.css file, you'll need to add (for the color of the links)
:root>* {
--md-typeset-a-color: #3498db;
}

And then in mkdocs.yml (for color on hover)
theme:
  name: material
  custom_dir: overrides 
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: white
    accent: purple

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css 

Hope it works :) I did it like this
