### ISSUE TITLE
Footer bug when scrolling in Chrome in large screen

### ISSUE THREAD

**Issue by ovasquez** [squidfunk/mkdocs-material#159]
## Description
The footer appears and disappears when the contents of the page are small and don't require the page to expand. I created a GIF with the description of the bug http://imgur.com/a/P1fT9

You can also see this bug in the License page of the Material docs http://squidfunk.github.io/mkdocs-material/license/

**Note**:  I already found a fix for this (because just setting a min-height on .md-container or .md-main would result in the wrong height in Firefox), so let me know if it's OK to send a pull request.
### Expected behavior

The footer should stay still.

### Actual behavior

The footer "rebounds" and doesn't allow to scroll to the end of the page.

### Steps to reproduce the bug

1. Open Chrome and go to License page http://squidfunk.github.io/mkdocs-material/license/
2. Maximize the window
3. Try to scoll bottom

### Package versions

Latest version on 2017/02/15

### System information
* OS: Windows 8/10
* Browser: Chrome
* 1080p monitor

**Comment by squidfunk** [comment]
You are encouraged to submit a PR. (However, I'm currently having some problems with flaky screenshot tests which I'm trying to fix, so the build may break.)

**Comment by squidfunk** [comment]
Fixed in master with a more general solution (see comment in linked PR). Will do a release shortly.
