### ISSUE TITLE
Build time increased by upgrading to 5.1.0

### ISSUE THREAD

**Issue by jholdstock** [squidfunk/mkdocs-material#1598]
The commit implementing our update can be found here: https://github.com/decred/dcrdocs/pull/1085/commits/ad30ce38ed18514bd23c6902527d58ffe7194127

Build time has increased from ~4.5 seconds to ~10.5 seconds. This changes live-reload for development from annoying to almost unusable :disappointed: 

Is this expected when updating from version 4.3 to 5.1? No other changes significant have been made. 

All testing was performed using the repo `Dockerfile`, so using python 3.8 on alpine linux.

**Comment by squidfunk** [comment]
There're now 5k icons, which are bundled with the theme as part of the build, so depending on how LiveReload is implemented (polling vs. filesystem events), yes, this may be the reason. Note that there are [other problems with Python LiveReload](https://github.com/mkdocs/mkdocs/issues/2061), which the MkDocs authors [don't want to address](https://github.com/mkdocs/mkdocs/issues/2061#issuecomment-613056997) as they say it's a problem with the upstream dependency.

**Comment by squidfunk** [comment]
Note that the project looks quite [abandoned](https://github.com/lepture/python-livereload) – the author is looking for maintainers to take on the project and the last commit was 6 months ago.

**Comment by jholdstock** [comment]
The problem I am describing is not specifically with live reload, I am referring to the build time itself - ie. running `mkdocs build --clean --strict -f mkdocs.yml -d site`.

My version of mkdocs is remaining constant, and the only thing I am changing is the mkdocs-material update and replacing `fontawesome-markdown` with `mkdocs-material-extensions`.

**Comment by squidfunk** [comment]
Then this is nothing that can be fixed as part of this project. You can do a `--dirty` rebuild to speed things up, but I guess MkDocs now has to handle more files. If it is specifically related to `mkdocs-material-extensions`, it could be worth opening an issue on their tracker.

**Comment by jholdstock** [comment]
I've removed `mkdocs-material-extensions` and running with no changes other than the update to material 5.1.0 still shows the same increase in build time. I think we can rule out the extensions.

Removing all unused icons from `.icons/` (only 19 icons remaining) reduces the build time to just over 7 seconds. Looks like you are correct and the majority of the increase comes from the sheer number of new files added - so I guess the answer to the original question is yes - this increase is expected when performing the mkdocs-material update. It is the price paid for the convenience of including additional icons in the theme.

`mkdocs serve --dirtyreload` is a decent work-around for the live-reload problem - cuts the build to around 200 ms. Thanks for taking the time to discuss this :slightly_smiling_face:

**Comment by squidfunk** [comment]
Jep, users want more and more extensions and customizations, but there's always a price to pay, unfortunately. However, building should be something that should be allowed to take a few seconds, so as long as the reload works reliably, this shouldn't be a problem in most cases.
