### ISSUE TITLE
Screen is now strange on chromebooks

### ISSUE THREAD

**Issue by RDIL** [squidfunk/mkdocs-material#1622]
I am using the latest Material version, and the sidebar seems to have vanished on me.

I know this worked properly like 2 weeks ago, but now it doesn't.  The navigation on the left should be there because it looks honestly pretty bad without it.  

![Screenshot 2020-04-17 at 9 30 23 AM](https://user-images.githubusercontent.com/34555510/79574444-20aad780-808e-11ea-9c05-d79ec872be57.png)

Edit: yes it properly pops out but what happened to the desktop behavior like before?

**Comment by squidfunk** [comment]
It's exactly the same as before. Did you zoom?

**Comment by RDIL** [comment]
No, I'm at the normal size

**Comment by squidfunk** [comment]
As said, it didn't change. We increased the desktop breakpoint to `1220px` [three years ago](https://github.com/squidfunk/mkdocs-material/blame/5b8721ff9286a5303219d39f7bf9efc8ca6b191a/src/assets/stylesheets/_config.scss#L46)

**Comment by RDIL** [comment]
That's odd, I'll contact google about it then 👍 

Thanks
