### ISSUE TITLE
Fully expand navigation tree by default

### ISSUE THREAD

**Issue by PDDStudio** [squidfunk/mkdocs-material#1624]
## Description

It would be nice to fully expand the navigation tree by default.  
I tried to do this myself by overriding the part of the theme, but I couldn't figure out which part is responsible for this. If you don't plan to integrate it as a feature, maybe you can give me a hint to solve this anyways? I'd appreciate it 👍 

### Use Cases

This makes a cleaner look especially for smaller documentations.

### Screenshots / Mockups

These are the elements I'm talking about:  

By default (Actual):

![tabs](https://user-images.githubusercontent.com/10941504/79624485-24883980-8122-11ea-866f-1cd1f9dfce34.PNG)

By default (Desired):  

![tabs2](https://user-images.githubusercontent.com/10941504/79624533-729d3d00-8122-11ea-948e-51f666d3f6b0.PNG)

**Comment by squidfunk** [comment]
You may use the search 😊 in #767 there are some directions on how to achieve this.

**Comment by PDDStudio** [comment]
I don't know how this didn't came up when I was searching for something similar...  
This did the trick, thanks!
