### ISSUE TITLE
Various icons missing from material iconset

### ISSUE THREAD

**Issue by zoni** [squidfunk/mkdocs-material#1634]
## Description

Referencing `material/subject` as an icon results in #1633 because this icon appears to be missing from the bundled icon sets. This may apply to more icons though I have not done an exhaustive comparison.

subject is a [valid material icon](https://material.io/resources/icons/?search=subject&icon=subject&style=baseline) which I was using successfully under 4.x so this is a regression in 5.x.

For all other details, including version info and reproduction, see #1633.

**Comment by zoni** [comment]
While looking for a replace for my existing doc (which was using subject), I notice [description](https://material.io/resources/icons/?icon=description&style=baseline) is also missing, so this definitely affects multiple icons.

**Comment by squidfunk** [comment]
As Google discontinued the original Material Design icons repository, we now pull the icons from the `material-design-icons-svg` package. If icons are missing, the issue should be reported upstream, as we can't do anything about it. Nevertheless, there are thousands of other icons that can replace the icon you're searching, so it should really be no big deal.

**Comment by zoni** [comment]
> As Google discontinued the original Material Design icons repository, we now pull the icons from the material-design-icons-svg package.

To be clear, this is the [material-design-icons-svg NPM package](https://www.npmjs.com/package/material-design-icons-svg) I presume?

> Nevertheless, there are thousands of other icons that can replace the icon you're searching, so it should really be no big deal.

Finding a replacement icon is indeed not a big deal, the change in behavior between 4.x and 5.x is what prompted me to report it. I also wondered if there might have been packaging issues which resulted in icons going missing unintended, though it sounds like this is purely an artifact of the switch to the `material-design-icons-svg` package in 5.x.

I think it might be good to warn users about the potential for this in the [5.x release upgrade steps](https://squidfunk.github.io/mkdocs-material/releases/5/) as it clearly bit me. I'd be happy to create a PR to add a note about this if you're open to that.

**Comment by squidfunk** [comment]
It's already described in the [upgrade docs](https://squidfunk.github.io/mkdocs-material/releases/5/#themelogoicon):

> The logo icon configuration was centralized under theme.icon.logo and can now be set to any of the icons __bundled with the theme__: ...

I understand that this cost you some trouble, but adding more clutter in the form of warnings and notices to the upgrade docs may lead to more confusion. If somebody encounters the problem, they will find this exact issue 😊

**Comment by facelessuser** [comment]
`material-file-document` might be what you are looking for. It's the closest one. You can search at this site: https://materialdesignicons.com/. It can help you find icons you are looking for.

**Comment by facelessuser** [comment]
Sorry, if in mkdocs.yml, it is probably `material/file-document`.

**Comment by squidfunk** [comment]
Closing for the stated reasons.
