### ISSUE TITLE
[Accessibility] Improve contrast of links with light primary colors

### ISSUE THREAD

**Issue by cedx** [squidfunk/mkdocs-material#1640]
When using some light primary color like `yellow` or `lime`, links are almost unreadable.
It would be cool if links use a darker primary color, or use the accent color instead.

See: https://whichjs.readthedocs.io/
Very hard to read the yellow links.

**Comment by squidfunk** [comment]
Unfortunately, accent colors will have the same problems, as some of them also have lighter shades. I’m currently working on dark mode in #1639, which will also include a dedicated variable for link colors as proposed in #1583. There will always be some combinations of colors that will not work out of the box, but the theme is quite easy to customize.

**Comment by cedx** [comment]
OK, thanks for the reply.
I close this issue in favor of #1583.
