### ISSUE TITLE
docker image : icon material not found

### ISSUE THREAD

**Issue by firebzh** [squidfunk/mkdocs-material#1642]
Hi,
I use the latest docker image squidfunk/mkdocs-material.

When I set theme/icon/logo: 'material/build', MKDocs crash, .icons/material/build.svg is not found.

What's wrong ?

**Comment by squidfunk** [comment]
The [upgrade guide in the official documentation](https://squidfunk.github.io/mkdocs-material/releases/5/#how-to-upgrade) is your friend.

**Comment by squidfunk** [comment]
The problem here is that the icon names changed as we switched to the community-maintained Material Design icons (as the official ones are abandoned).

Closing as answered.
