### ISSUE TITLE
Search event dispatch

### ISSUE THREAD

**Issue by williammizuta** [squidfunk/mkdocs-material#1658]
## Description

Although the search is triggered for every modification in the search input, there is no guarantee that it really happened. For example, there is a delay for the first search as it is needed to wait to download the JSON with the search data. The idea is to have an event dispatched to window/body to notify that a search really happened. This event can send the search query and the number of result items.

### Use Cases

This event should be useful to track the search usage, like sending search events to Google Analytics to better analyse the user behaviours.

**Comment by squidfunk** [comment]
1. Search data is already sent to GA:

https://github.com/squidfunk/mkdocs-material/blob/2b6359c5feab1c17772033536efa3274d52db5c2/src/partials/integrations/analytics.html#L38-L49

2. Search can be observed with:

``` js
app.search$.subscribe(console.log)
```

**Comment by williammizuta** [comment]
Thank you. I didn't know about that.

**Comment by squidfunk** [comment]
No worries, the new reactive API is still undocumented. Hopefully I’ll find some time in the future to write up a developer guide 😊
