### ISSUE TITLE
Add support for mkdocs-enumerate-headings-plugin

### ISSUE THREAD

**Issue by timvink** [squidfunk/mkdocs-material#1661]
### Description

Add CSS styling to headings that are numbered using the plugin [mkdocs-enumerate-headings-plugin](https://github.com/timvink/mkdocs-enumerate-headings-plugin)

### Use Cases

The plugin is useful when using MkDocs to write (technical) reports and being able to refer to section numbers can aid discussion. 

### Screenshots / Mockups

Without any CSS styling:

![image](https://user-images.githubusercontent.com/5570380/80606110-2ca27c00-8a34-11ea-866c-24b42628a75c.png)

With CSS styling 

```css
.enumerate-headings-plugin {
    color: darkgray;
}
```

![image](https://user-images.githubusercontent.com/5570380/80606295-6ecbbd80-8a34-11ea-8a06-9b41feefca76.png)

### Implementation

I'm not a CSS expert but I'd be willing to work on a PR that adds styling. I would need some guidance on both the styling itself and where to implement (f.e. considering #1639)

**Comment by squidfunk** [comment]
IMHO, I prefer the non-greyish version. It's also more accessible, as the gray value might be too low-contrast. For this reason, I'd rather leave it as-is and I'd suggest that you mention the CSS class in your docs + maybe some directions on extra CSS.

__Also, note that what you proposed can be completely implemented with [CSS counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters) which is supported in [all browsers](https://caniuse.com/#feat=css-counters).__ I'd rather favor a CSS solution than hard-coded HTML, and that can be implemented by anyone with a few lines of CSS.

**Comment by timvink** [comment]
> IMHO, I prefer the non-greyish version.

No debating style :) I was hoping perhaps you had an idea for some fancy material styling, but I agree as-is is actually already quite fine.

> note that what you proposed can likely be implemented with CSS counters

I had seen CSS counters when researching for this plugin. As I understand it now, they don't increment *between* pages in a site. That's what this plugin does. My use case is that a MkDocs also needs to be printed into a PDF report (using mkdocs-pdf-export-plugin) and that I would like chapter + section numbers across the entire site and PDF.

> I'd rather favor a CSS solution than hard-coded HTML

Perhaps an interesting future mkdocs-material feature! :)

Thanks again for all the work on this theme, loving `v5` 😄 !

**Comment by squidfunk** [comment]
> As I understand it now, they don't increment between pages in a site.

That is indeed not possible with CSS counters, nice!

> Thanks again for all the work on this theme, loving v5 😄 !

Always glad to read that!
