### ISSUE TITLE
iframe height is not adjustable

### ISSUE THREAD

**Issue by wgoetz** [squidfunk/mkdocs-material#1664]
my quick fix:  removed the iframe... height=auto from main.c4007cdc.min.css

maybe you should have separate settings for  iframe and img/svg 
(_typeset.scss)

root cause probably this commit:
commit e6143e7bfbb79e726175ac8961051cb34ce40576
Author: squidfunk <martin.donath@squidfunk.com>
Date:   Mon Apr 27 09:34:49 2020 +0200

    Fixed distorted image when width and height are explicitly set

__I checked that...__

- [x ] ... the documentation does not mention anything about my problem
- [ ] ... the problem doesn't occur with the default MkDocs template
- [x ] ... the problem is not in any of my customizations (CSS, JS, template)
- [ x] ... there are no open or closed issues that are related to my problem

## Description

iframes, such as embedded google calendar or the selfhtml example have a fixed height.
not adjustable.

### Expected behavior

want freely adjust the height!

### Actual behavior

fixed height

### Steps to reproduce the bug

from https://wiki.selfhtml.org/wiki/Beispiel:HTML_iframe-Element-seamless.html

<iframe
  src="https://wiki.selfhtml.org/wiki/Startseite"
  seamless
  width="90%" 
  height="400" 
  name="SELFHTML_in_a_box"></iframe>

### Package versions

* Python: `python --version`
Python 3.6.9

* MkDocs: `mkdocs --version`
kdocs, version 1.1 from /home/goetz/virtualenv/p3mai/lib/python3.6/site-packages/mkdocs (Python 3.6)

* Material: `pip show mkdocs-material | grep -E ^Version`
Version: 5.1.4

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: ... 
* Browser: ...

**Comment by squidfunk** [comment]
I guess we can remove `height: auto` for iframes.

**Comment by squidfunk** [comment]
Fixed in 52c3daf4.

**Comment by squidfunk** [comment]
Released as part of 5.1.5.
