### ISSUE TITLE
[accessibility] Clicking items in table of contents removes focus on page

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#1665]
## Description

Clicking items in table of contents removes focus on page

### Expected behavior

Clicking items in table of contents keeps focus on page so one can continue using up, down, page up, page down

### Actual behavior

Clicking items in table of contents removes focus on page disabling use of up, down, page up, page down

### Steps to reproduce the bug

1. Click item in table of contents
2. Notice you can no longer navigate using up, down, page up, page down

### Package versions

* Python: `3.8.1`
* MkDocs: `1.1.0`
* Material: `5.1.1`

### Project configuration

``` yaml
theme:
  name: material
  language: en
  features:
    - tabs
```

### System information

* OS: Windows
* Browser: Chrome

**Comment by squidfunk** [comment]
Do you have an example of a page implementing it? If so, feel free to PR!

**Comment by squidfunk** [comment]
After thinking about this, I'd say this is not an accessibility issue. When you click on a focusable element, it will receive focus, and thus steal the focus from the current element/context. However, if you navigate to a TOC link with the keyboard and press <kbd>Enter</kbd>, it will jump to the anchor in the page and set the focus to that section. Thus, it is perfectly accessible. I would go so far and say if you use the mouse and click a specific element, it would be bad UX to steal the focus from the user. For this reason, I see no necessity to change this behavior.

**Comment by ofek** [comment]
Makes sense. I just opened this when I noticed Wikipedia's ToC does the way I expect

**Comment by squidfunk** [comment]
Quite interesting, however, I'd say it's very much an edge case 😄
