### ISSUE TITLE
Sidebars scroll is finished already on page load.

### ISSUE THREAD

**Issue by fahidjavid** [squidfunk/mkdocs-material#1667]
Hi,

When loading the document page if left and right sidebars are scrollable then they are already scrolled that’s not good.

Any fix to start scroll from start on page load?

Issue also appears on the actual document of Material theme. Screenshot: https://jmp.sh/6yVoAGE

Thanks

**Comment by squidfunk** [comment]
That's odd. It should start from the top.

**Comment by squidfunk** [comment]
Note, that this only seems to happen in Chrome. It seems that Firefox and Safari are unaffected.

**Comment by squidfunk** [comment]
Oddly enough, this seems to be a bug in Chrome 81+ which is related to `scroll-snap-type`. It worked before and I'm not seeing the behavior on any other browser.

If we set `scroll-snap-type` after a slight delay (as in 1b72c9f1), it seems to work fine, though. We can include and ship this hack until Chrome resolves the issue, as it's really annoying. If somebody comes up with a better explanation and/or hack, I'm happy to merge PRs.

See my latest tweet for a visual explanation:
https://twitter.com/squidfunk/status/1256914540966686720

**Comment by squidfunk** [comment]
Released as part of 5.1.5.

**Comment by fahidjavid** [comment]
Thank you @squidfunk for this quick fix and release!
