### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by DorKeinath** [squidfunk/mkdocs-material#1673]
Running `mkdocs serve` I get
`AttributeError: 'dict' object has no attribute 'split'`
The row above is
`File ".../.local/lib/python3.8/site-packages/mkdocs/utils/__init__.py", line 251, in path_to_url
    return '/'.join(path.split('\\'))
`

On my system there is python 3.8, pip 20.1,  mkdocs 1.1

**Comment by squidfunk** [comment]
#1579 

Please use the search next time.

**Comment by DorKeinath** [comment]
Thank you a lot!
