### ISSUE TITLE
Warning!! Cyclic dependencies found: * mkdocs-material => mkdocs-material-extensions

### ISSUE THREAD

**Issue by hasenlu** [squidfunk/mkdocs-material#1674]
Warning!! Cyclic dependencies found:
* mkdocs-material => mkdocs-material-extensions => mkdocs-material
* mkdocs-material-extensions => mkdocs-material => mkdocs-material-extensions

**Comment by squidfunk** [comment]
We’re gonna need a little more to help you 😅

**Comment by facelessuser** [comment]
What is giving you the error?

**Comment by hasenlu** [comment]
`
$ pip3 install pipdeptree
$ pipdeptree
`
gives the error.

**Comment by hasenlu** [comment]
```
$ pip3 install pipdeptree

$ pipdeptree
```
gives the error.

**Comment by facelessuser** [comment]
So there is no issue when installing with pip.

The extensions will only work with material 5, so they require >= 5. Material required the extension, but it seems to work fine. The warning that you are showing doesn't seem to be a real world problem. The fix would be to remove the dependency in the extension package, but I don't see a reason to do so yet.

**Comment by squidfunk** [comment]
As @facelessuser noted, not a real problem. Closing.

**Comment by maxalbert** [comment]
@facelessuser @squidfunk This seems to become a real problem when using `poetry` for dependency management as it raises an error rather than ignoring the cyclic dependency:
```
Updating dependencies
Resolving dependencies... (2.8s)

[RecursionError]
maximum recursion depth exceeded
```

Any chance of re-opening this issue and fixing it? Many thanks!

**Comment by squidfunk** [comment]
That's a bug of Poetry. Dependency resolution is, after all, just a simple reverse post-order graph traversal, a.k.a topological sort.
