### ISSUE TITLE
Deploying with Docker fail, .ssh/config file bad owner.

### ISSUE THREAD

**Issue by tzinm** [squidfunk/mkdocs-material#1678]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description
Deploying with Docker fails. I bind the **.ssh** directory with [ssh config file](https://www.digitalocean.com/community/tutorials/how-to-configure-custom-connection-options-for-your-ssh-client).

The log says:
```bash
Bad owner or permissions on /root/.ssh/config
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
```

### Actual behavior

I have 600 file permission (.ssh/config file) and the owner it's me (not root). I try to change file permission and it doesn't work, but after changing the owner to root it works. For the rest of files I'm still the owner.

### Expected behavior

Work with the original configuration, i.e. being me the owner of config file.

### Steps to reproduce the bug

Docker run comand:

```bash
docker run -it -v ~/.ssh:/root/.ssh -v  ~/.gitconfig:/root/.gitconfig -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy -m "Test"
```

### Package versions

I am using the 5.1.5 version of squidfunk/mkdocs-material image.

### System information

I don't think this is relevant, but I put it anyway.

* OS: Fedora 30

**Comment by squidfunk** [comment]
This is a general Docker problem and you seem to be quite proficient in Docker. Could I ask you to investigate yourself and share your findings?

**Comment by squidfunk** [comment]
Closed accidentally. Could be helpful:
https://nickjanetakis.com/blog/docker-tip-56-volume-mounting-ssh-keys-into-a-docker-container

**Comment by tzinm** [comment]
> This is a general Docker problem and you seem to be quite proficient in Docker. Could I ask you to investigate yourself and share your findings?

Fine, I wil investigate about this "issue" :smiley:

**Comment by squidfunk** [comment]
Any luck? Can this be closed?

**Comment by tzinm** [comment]
> Any luck? Can this be closed?

Hi! Not yet, I´ve tried different ways but I´ve run into permission issues. The only way that I could is moving config file or changing the owner.

If you want we can clouse this issue and if I find a solution I will bring it here.

**Comment by squidfunk** [comment]
Yes, if you figure it out, I would encourage you to post your solution here 😊
