### ISSUE TITLE
Small quirk with repo name

### ISSUE THREAD

**Issue by Stanzilla** [squidfunk/mkdocs-material#1688]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [ ] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

When setting `repo_name` to something short like `repo_name: GitHub` the container width of the source display is too small.

### Expected behavior

Wider source panel so stats can fit

### Actual behavior

![image](https://user-images.githubusercontent.com/75278/81627081-a9066900-93fd-11ea-9dc0-54b7df55c4f2.png)

### Steps to reproduce the bug

1. `repo_name: GitHub`
2. ...
3. ...

### Package versions

* Python: `3.7` 
* MkDocs: `1.1`
* Material: `5.1.6`

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: ...
* Browser: ...

**Comment by squidfunk** [comment]
Which OS and browser? And does it happen with a mint Material installation? I’m asking because you didn’t tick the customization box...

**Comment by squidfunk** [comment]
<img width="181" alt="Bildschirmfoto 2020-05-12 um 09 03 52" src="https://user-images.githubusercontent.com/932156/81648788-89883400-942f-11ea-92ab-e1ad3bf75bbc.png">

**Comment by Stanzilla** [comment]
Sorry got sick and had not have time to do more testing. It was chrome 83 on win10

**Comment by Stanzilla** [comment]
reducing `max-width` on `__repository` fixed it, but I was using the same code as material there.
