### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by z3r0x1c** [squidfunk/mkdocs-material#1694]
How can I add custom favicon icon?
I add my icon to this way: docs/assets/icon.ico
its dont work

**Comment by fveauvy** [comment]
Good evening,

You should perhaps check out the [Get Started](https://squidfunk.github.io/mkdocs-material/getting-started/#favicon) documentation, you'll find a subsection for favicons.

Cheers

**Comment by squidfunk** [comment]
It's clearly answered in the docs, as @fveauvy pointed out.
