### ISSUE TITLE
Unstable translations dict in base.html under Python3.5

### ISSUE THREAD

**Issue by zjuchenyuan** [squidfunk/mkdocs-material#1695]
https://github.com/squidfunk/mkdocs-material/blob/32d57e66c737119742b4d4f1d12c46eb359b122d/material/base.html#L183-L199

The dict in Python3.5 is not in order, so this piece of code will generate unstable translations. Thus 
different build html are different even when the source markdown files are not changed, making `git diff` noisy.

I propose to create an `ordered tojson` method to avoid this unstable behaviour.

**Comment by squidfunk** [comment]
`tojson` is a Jinja filter that is provided by MkDocs, not by this theme. Therefore I'd suggest you take this issue upstream and open an issue in their repository.

**Comment by squidfunk** [comment]
Closing as upstream issue.

**Comment by zjuchenyuan** [comment]
I do not think this is a upstream issue, we can move this piece of code into Python level to finish sort operation, and then directly output to html.

Or using JavaScript List to dict translation.

**Comment by squidfunk** [comment]
This project cannot provide theme helpers, they are provided by MkDocs. I should be fixed there.

**Comment by zjuchenyuan** [comment]
Upstream change definitely should provide a way to fix this, but it's not the only way.

Instead, we can use javascript code to rebuild this dict: https://gist.github.com/ThomasG77/2186830

```
 {%- set translations_values = [] -%} 
 {%- set translations_keys = [ 
   "clipboard.copy", 
   "clipboard.copied", 
   "search.config.lang", 
   "search.config.pipeline", 
   "search.config.separator", 
   "search.result.placeholder", 
   "search.result.none", 
   "search.result.one", 
   "search.result.other" 
 ] -%} 
{%- for key in translations_keys-%}
   {%- set _ = translations_values.append(lang.t(key)) -%} 
 {%- endfor -%} 

<script>
function dictZip(key_array, val_array) {
  if (key_array.length === val_array.length) {
    return key_array.reduce((acc, curr, index) => {
      acc[curr] = val_array[index];
      return acc;
    }, {});
  } else {
    console.error("Wrong length");
  }
}
var translations_keys={{translations_keys}};
var translations_values={{translations_values}};
translations = dictZip(translations_keys, translations_values);
var s = document.createElement("script");
s.id="__lang";
s.type="application/json"
s.innerHTML=JSON.stringify(translations);
document.body.appendChild(s);
</script> 
```

Of course, this is not an elegent manner, but it works.

![image](https://user-images.githubusercontent.com/17289004/82133412-57efde00-981e-11ea-9b0b-9db9f5be6c88.png)
 > This figure shows the usage of `__lang` script correctly find it.
