### ISSUE TITLE
ToC under navigation menu

### ISSUE THREAD

**Issue by mlevit** [squidfunk/mkdocs-material#1701]
__I checked that...__

- [X] ... the documentation does not mention anything about my idea
- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... there are no open or closed issues that are related to my idea

## Description

Due to the width of my content (tables mainly) I have a requirement to remove both the primary and secondary sidebars, but I would love to keep the ToC if I could. Would it be possible to add a ToC as a secondary nav bar under the existing navigation menu?

I'd be happy to customise this myself for my own instance, but I am looking for some assistance with what needs to be done.

### Use Cases

For use cases where the page content area needs to be wider than the currently provided space.

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/233717/82164946-72958600-98f6-11ea-9741-d6a003ec49fd.png)

**Comment by squidfunk** [comment]
I'd regard this as customization, as I question the practicality of this approach for three reasons:

1. It doesn't work well on mobile, i.e. for more than a few entries, it needs to be scrollable
2. It will disappear when scrolling, which renders it rather useless as a TOC
3. It doesn't allow to show a hierarchy among items

You can, however, try to make it work by using [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme), including `toc.html` in `tabs.html` or some other partial. You will definitely need to add some custom CSS to style it the way you want, though.

**Comment by mlevit** [comment]
Thanks for the reply @squidfunk, I think you nailed the point around hierarchy. I'll have a play with the CSS to expand the width of the pages overall then, might be a better and easier solution.

**Comment by squidfunk** [comment]
Increasing `max-width` on `.md-grid` should be a good start. :

``` css
.md-grid {
  max-width: 70em; /* or 100%, if you want to stretch to full-width */
}
```

**Comment by mlevit** [comment]
Thanks for the info. I am having issues with the TOC not moving with the newly sized grid as well as it should. See the screenshots below:

![image](https://user-images.githubusercontent.com/233717/82409822-e8921c80-9ab1-11ea-9f3f-0523661e1f64.png)

Mobile or tablet interface

![image](https://user-images.githubusercontent.com/233717/82409845-f9db2900-9ab1-11ea-8c52-7eb5d7965ddb.png)

CSS override is as follows

```css
.md-grid {
  max-width: 70%;
}

.md-content {
  margin-left: 0rem;
} 

.md-sidebar--primary {
  display: none;
}
```

**Comment by squidfunk** [comment]
Unfortunately, we cannot aid you in customizations - that's beyond the scope of this project. We would be doing nothing else than helping people to achieve what they want for free 😉
