### ISSUE TITLE
Improve documentation on dark mode

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#1716]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

After fiddling around with the new dark mode feature, I think the documentation could be a bit more detailed. However, I'm not sure whether certain use cases should be documented at all.

## Use Cases

To my knowledge, there are three use cases for dark mode:

### 1. Permanent dark mode

You can enable dark mode using the following setting in `mkdocs.yml`:

```yml
theme:
  palette:
    scheme: slate
```

**Result:** Dark mode is enabled *permanently* for the documentation project.  

**Documentation:** Fully documented.

### 2. Automatically switch between light and dark mode

You can use the `perfers-color-scheme` CSS feature to automatically enable dark mode based on user's OS preference. See https://github.com/squidfunk/mkdocs-material/issues/1266.

**Result:** Dark mode is enabled *automatically* for the documentation project whenever the OS is set to a dark color scheme and the browser supports `perfers-color-scheme`.

**Documentation:** Not documented. Should this be documented?

### 3. Manually switch between light and dark mode

As demonstrated on the [Getting Started](https://squidfunk.github.io/mkdocs-material/getting-started/#color-scheme) page (see the `default` / `slate` buttons), you can use JavaScript to let the user choose between dark and light mode.

However, the setting made via the buttons is not permanent. You'd have to store the setting in localStorage or cookies, but it's not clear to me whether it is possible to implement a solution without flashing (i.e., on each page load, the page flashes white before switching to dark or vice versa). There have been some discussions around this in https://github.com/squidfunk/mkdocs-material/issues/1266, but I haven't been able to find a solution. 

Maybe this is not even an intended use case for Material. If so, please let us know.

**Result:** Dark mode is enabled *manually* for the documentation project using a dedicated button or switch.

**Documentation:** Not documented. Should this be documented?

**Comment by XhmikosR** [comment]
Agreed, I was actually looking for a dark mode switcher for mkdocs-material :)

**Comment by wilhelmer** [comment]
Yes – I think this isn't only about documentation, but also about clarification: Which use cases was Material designed for, and which are considered edge cases that have to be custom-made?

**Comment by squidfunk** [comment]
The problem with clarifying use cases is that people ignore them and open issues anyway to demand support for unsupported features. At least that’s what I learned from the last 4 years. Some of those features might also make sense, like local search, as I haven’t had that on my radar, but after all this project is a collection of edge cases that were tried to be generalized. For this reason I see no value on drawing the line, saying: this far.

**Comment by squidfunk** [comment]
Regarding 3., see https://github.com/squidfunk/mkdocs-material/pull/1639#issuecomment-629761383

**Comment by wilhelmer** [comment]
>For this reason I see no value in drawing the line, saying: this far.

True, I heard this can get you in all kinds of trouble, especially if you don't like Docker containers ;-)

So what if we add a note to https://squidfunk.github.io/mkdocs-material/getting-started/#color-scheme with something like (raw draft):

> This permanently applies the color scheme to your documentation project. Automatically switching between color schemes based on your operating system's preference or manually switching color schemes using a dedicated control is also possible, but requires customization. Feel free to open a feature request or share your existing implementations using the GitHub issue tracker.

**Comment by squidfunk** [comment]
My guess is that this will lead to a flood of duplicate issues. We’re already tracking preference-based color in #1266 and I’d rather open another issue to track adding a toggle. However, as color schemes are not binary it’s not easy to implement. I’m open to design discussions though.

Also note that I’ll very likely implement preference-based color before adding a toggle. However, I first want to see some use cases and some possible implementations before going down a road that doesn’t solve a lot of problems.

Furthermore, I’m thinking of adding another darker color scheme with even darker colors, so there two dark modes. That’s why I generalized it in the first place.

**Comment by squidfunk** [comment]
As there are two issues tracking 2. and 3. of the OP, can this be closed? We will add documentation as we implement those features, but for now, they're both under discussion.

**Comment by wilhelmer** [comment]
Yes, this can be closed. I mainly wrote this for clarification, and use cases 2 and 3 have been clarified. Thanks!

**Comment by NickHeiner** [comment]
I'm sorry if I'm missing some docs, but I'm still not able to figure out case 2. I see https://github.com/squidfunk/mkdocs-material/commit/143cb05e9748dc8c4b3b235b1f9aaee86179f88c added the `preference` option, but I don't see that in [the docs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color). And it doesn't have any effect when I set it locally. :smile:

**Comment by squidfunk** [comment]
The `preference` option is superseded by the new [`media` attributes](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle). I still need to update the documentation but haven't found some time to do so yet.
