### ISSUE TITLE
Footnote links are nearly invisible on table headers

### ISSUE THREAD

**Issue by byashimov** [squidfunk/mkdocs-material#1718]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Footnote links are nearly invisible on table headers. Probable solution: make them white.

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/1560043/82663186-da6e0880-9c37-11ea-8b4f-36be9ea04b68.png)

`Python` column has a footnote, which is mostly not noted by readers.

**Comment by squidfunk** [comment]
Fixed in 2135e342

**Comment by squidfunk** [comment]
Released as part of 5.2.1.
