### ISSUE TITLE
.md file why .html

### ISSUE THREAD

**Issue by Hime-Dev** [squidfunk/mkdocs-material#1730]
#OS 
Windows
#Problem 
Hi, i look docs file, i try npm run build thank mkdocs build but create .html and folder folder .html files but i want easily solution. Example another use material mkdocs only have 2 file 1 . mkdocs.yml 2. docs/index.md ... but my question why my files after than build convert html files.

**Comment by Hime-Dev** [comment]
![2](https://user-images.githubusercontent.com/57987392/82971212-d432b000-9fda-11ea-8364-99a77e849480.JPG)
![1](https://user-images.githubusercontent.com/57987392/82971216-d5fc7380-9fda-11ea-94cd-3fd1fa9e56af.JPG)
and i have this problem i cant serve or build.

**Comment by squidfunk** [comment]
I’m sorry, but I do not understand your problem and you did not provide enough information. Please use the issue template.

**Comment by Hime-Dev** [comment]
@squidfunk i use with git i can use mkdocs build but if ı use with pip i can't build and start serve commands. I want use pip beacuse i use with git after build always create html and all .md file folder folder index but i want .md files why after than build convert md files to html files

**Comment by martinbira** [comment]
@Hime-Dev That's kind of the entire point of MkDocs. It transforms .md-files to .html files to be viewed as web pages.

**Comment by martinbira** [comment]
@Hime-Dev If you don't want any html-files you should not use MkDocs at all. Other than that, I have no answers to your question, except that this is not the place to discuss this as it is not an issue with the theme.

**Comment by Hime-Dev** [comment]
okay thx for help.
