### ISSUE TITLE
Color schemes: allow user to choose/toggle schemes

### ISSUE THREAD

**Issue by bnigh** [squidfunk/mkdocs-material#1732]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... there are no open or closed issues that are related to my idea

## Description

As of #1639 a dark palette scheme (`slate`) was added. Discussions regarding adding a toggle for this have been discussed [#1639 comments](https://github.com/squidfunk/mkdocs-material/pull/1639#issuecomment-629761383), [#1716 comments](https://github.com/squidfunk/mkdocs-material/issues/1716#issuecomment-634578496), and #1266. This issue can capture these discussions. To keep this generalized, I will give my thoughts for potential solution in a comment.

### Use Cases

While supporting different themes / schemes and defaulting based upon `prefers-color-scheme` are phenomenal, adding a toggle would directly allow each user to manually set the theme according to their preferences.

### Screenshots / Mockups

n/a

**Comment by bnigh** [comment]
A potential solution would be to add an optional configurable menu dropdown, where users could select the preferred palette / scheme (similar to [angular material ui](https://material.angular.io/))

<img width="477" alt="angular_material_theme_selector" src="https://user-images.githubusercontent.com/8219313/83051444-e6c0df80-a002-11ea-9a15-14c90b0fba8a.png">

The available palette options could be controlled by config options with sensible defaults... maybe something like:
```yaml
theme:
  palette:
    toggle:
      - light
      - slate
```

Default behavior could be to add no toggle.
If enabled, default toggle values could be the available default schemes.

This could also be used to support different primary and accent colors as well:
```yaml
theme:
  palette:
    toggle:
      - scheme: light
        primary: indigo
        accent: indigo
      - scheme: slate
        primary: blue
```
where default primary and accent values could be inherited from the `theme.palette.primary` & `theme.palette.accent` values

The user selected value could be stored and retrieved from local storage.


This would allow for a menu toggle that would generalize to future schemes, while also supporting a dark mode toggle (albeit with an extra click)

**Comment by squidfunk** [comment]
Thanks for writing this up! That looks like a good proposal for a little iteration. Some questions:

- In the Angular example, there're titles/names for the respective schemes. How could we model those and/or should we?
- Where should we put the toggle? This is in fact a problem for which I couldn't come up with a good solution. The header bar is practically exhausted. We cannot put it between source and search bar, as the search would not be aligned anymore with the content. Also, there're some thinkable combinations: no search but repository, search but no repository, and both visible. We might also consider putting it in the footer or somewhere else, but header would be ideal, obviously. Also, there must be a solution for the mobile view, as the search bar will collapse into the icon and the repository information is hidden in the drawer.

One downside is that this will make configuration very flexible, but also very complicated, but I guess that's necessary in order to guarantee flexibility.

**Comment by bnigh** [comment]
> In the Angular example, there're titles/names for the respective schemes. How could we model those and/or should we?

perhaps there could be a `name` attribute associated with each option:
```yaml
theme:
  palette:
    toggle:
      - name: Light
        scheme: light
      - name: Dark
        scheme: slate
```

which could default to the scheme name?

> One downside is that this will make configuration very flexible, but also very complicated, but I guess that's necessary in order to guarantee flexibility.

Yeah, definitely open to further discussion to come up with a good design. 

In my opinion, I'm guessing most would use something like this to allow users to change schemes (`light`, `dark`, ... or others like `high-contrast` in the future) rather than change `primary` or `accent`, but perhaps those are useful if some of the selected palette colors only work well in a single scheme (ie: yellow).

---

> Where should we put the toggle? This is in fact a problem for which I couldn't come up with a good solution. The header bar is practically exhausted. We cannot put it between source and search bar, as the search would not be aligned anymore with the content. Also, there're some thinkable combinations: no search but repository, search but no repository, and both visible. We might also consider putting it in the footer or somewhere else, but header would be ideal, obviously. Also, there must be a solution for the mobile view, as the search bar will collapse into the icon and the repository information is hidden in the drawer.

This is probably the biggest question... I haven't really found any great solution that I'm completely sold on yet either.

Just brainstorming though, some possibilities might be:
- for mobile:
  - I think hiding in drawer similar to repository information might make the most sense
- for desktop some possibilities:
  - (1) could have it to the left of the repository icon, but to the right of the search bar in the menu & above the content
    - this would change alignment, so this icon is aligned with content instead of search
  - (2) could have it to the left or right of the repository, but have both of those icons above the toc
    - this likely wouldn't leave room to display stars, forks, & the repo name for the repository info... so it could only display the icon
  - (3) could have it at the top of the toc, similar to how [docker-compose](https://docs.docker.com/develop/) has their toggle
    - this approach would have to be modified to support a drop down or somehow support more than 2 options

Hopefully the above are clear...

Looking at the [README's Users](https://github.com/squidfunk/mkdocs-material#users) header, it looks like some have added custom icons in the header:
- [AWS](https://awssecworkshops.com/)
- [BFE](https://www.bfe-networks.net/en_us/)
- [ZeroNet](https://zeronet.io/docs/)

not sure if it influences decision, but they all seemed to have gone with implementations similar to option (1) above.

Overall, I think the various combinations of repository info, search, & toggle would be easier to identify once a layout is decided for all 3. And yeah, almost all other implementations I have seen have had a toggle sticky near the top right of the page (for desktop), so am thinking most users would expect / want something similar.

**Comment by squidfunk** [comment]
I like that the toggle approach you propose is pretty much generalized to the whole palette, especially as some primary/accent colors work better/worse than others with the themes. It also integrates perfectly with custom, author-provided themes. However, the problem with positioning...

My main concerns:

1. The opened search bar is not aligned with the content area. That looks really odd. In the past, there was a bug where the search was a little off on the tablet breakpoint that tripped people up. Alignment should stay the same.

<img width="1015" alt="Bildschirmfoto 2020-05-29 um 09 02 30" src="https://user-images.githubusercontent.com/932156/83231586-020b2680-a18c-11ea-8e85-e1c52a3a8dc2.png">

2. I don't have a good idea of how to integrate it into the drawer on mobile. Above the repository info? Below? It'll decrease the visible area for navigational content.

The only thing that I tried that _kind of worked_ was putting a vertical dot menu right to the search bar, but that means we would have to hide all options behind a dropdown. It also looks odd without the repository information, as the search bar is then located above the tablet of contents. It would have the nice properties of being generalizable, but will only work for the vertical dots, as they are very narrow. We cannot support other icons, as they would be too wide. Also, color schemes are only one thing. We also should think about making room for more options like version and language selectors, etc, which were requested in the past and for which no good solution exists.

Essentially, we need to provide a user preference menu or site-wide context menu in general.

**Comment by squidfunk** [comment]
BTW, if you feel like prototyping something, we can discuss concrete implementations over in one (or multiple) PRs!

**Comment by bnigh** [comment]
> Also, color schemes are only one thing. We also should think about making room for more options like version and language selectors, etc, which were requested in the past and for which no good solution exists.

> Essentially, we need to provide a user preference menu or site-wide context menu in general.

Agreed.

> The only thing that I tried that kind of worked was putting a vertical dot menu right to the search bar, but that means we would have to hide all options behind a dropdown

Agreed.
Considering site-wide preference menu, some sort of expandable/collapsable menu (in whatever form that takes) would seem to be the only feasible solution given the available real estate.

---

> BTW, if you feel like prototyping something, we can discuss concrete implementations over in one (or multiple) PRs!

If I find some time and come up with any prototypes worth sharing, definitely will do!

**Comment by squidfunk** [comment]
I've started working on the theme toggle. As proposed in this issue, it's possible to provide 2 or more alternate themes from which the user can choose. The chosen theme is persisted across requests and does not induce flickering upon page load. The author can specify an icon and a label for the theme:

``` yaml
theme:
palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      name: Switch to light mode
      icon: material/weather-sunny
  - scheme: slate
    primary: pink
    accent: pink
    toggle:
      name: Switch to dark mode
      icon: material/weather-night
```

This is the current concept – it always sticks to the lower right corner:

![screenshot-localhost-8000-setup-adding-a-git-repository-1597598455997](https://user-images.githubusercontent.com/932156/90340044-9f406300-dff5-11ea-9e26-6540db08e8af.png)

Positioning might change, as I'm still experimenting. This is how it looks in action:

![Ohne Titel 2](https://user-images.githubusercontent.com/932156/90340035-8e8fed00-dff5-11ea-9736-9696750dec17.gif)

_This feature will be released in Material for MkDocs Insiders as part of the [Black Pearl](https://squidfunk.github.io/mkdocs-material/insiders/#black-pearl) Funding goal. It will first be exclusively available to sponsors._

**Comment by crazy-max** [comment]
@squidfunk That looks awesome thanks!

**Comment by facelessuser** [comment]
I'm kind of glad you went for the header. So, I'm curious how this will work. If you have more than 2 themes, will it create another icon? Or does it use a generic icon with a menu?

**Comment by squidfunk** [comment]
Nope, it will just cycle through the schemes. If scheme 1 is active, it will show the icon of scheme 2. When the last scheme is active, it just wraps around to 1. So for two schemes it‘s identical to a toggle.

**Comment by squidfunk** [comment]
You can try the `master` of insiders if you like. Feedback appreciated!

**Comment by facelessuser** [comment]
Cool in that case, if you have more than one, you can use an icon to indicate what is currently selected, or just use something generic and have it the same for all.

That keeps it simple. I may still customize mine to move the icon to the mobile menu to maximize title space... But maybe not, I'll have to think about it, but generally I like this direction. I'll give the insiders a try.

**Comment by squidfunk** [comment]
I still want to tweak the spacing on mobile a little, so there’s some more space. In general, I want to get this out asap and then we can iterate and improve it 😊

**Comment by facelessuser** [comment]
No, this is a great start!  Fine tuning can happen down the line.

**Comment by facelessuser** [comment]
Looking at this. I think when in mobile view, the padding is a bit much. It works fine in a non-mobile profile, but IMHO, I think mobile should strip the padding of the title, and reduce the padding between the buttons. Here I simply remove the padding around the title (as the buttons already provide padding, and then remove the padding between buttons.

Before:
<img width="426" alt="Screen Shot 2020-08-23 at 1 19 50 PM" src="https://user-images.githubusercontent.com/1055125/90986931-030de300-e544-11ea-97f6-c61771f692ca.png">

After:
<img width="422" alt="Screen Shot 2020-08-23 at 1 22 23 PM" src="https://user-images.githubusercontent.com/1055125/90986934-0903c400-e544-11ea-9f4e-59e22308943f.png">

**Comment by facelessuser** [comment]
I'll probably at least play around with the idea on some of my sites an stick with just reducing the space between buttons for now.

<img width="407" alt="Screen Shot 2020-08-23 at 5 34 48 PM" src="https://user-images.githubusercontent.com/1055125/90991575-77a64900-e567-11ea-893f-1b4cb60a79b2.png">

**Comment by facelessuser** [comment]
I like how easy the multiple schemes are to set up. Great work there.

**Comment by squidfunk** [comment]
Finally released as part of Material for MkDocs Insiders 5.5.9+insiders-1.3.0! I updated the documentation here:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle

Check out the official Insiders docs to see it in action:
https://squidfunk.github.io/mkdocs-material-insiders/getting-started/

**Comment by stevevanhooser** [comment]
This toggle feature is not marked as "insiders" in the documentation: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/

**Comment by squidfunk** [comment]
The color palette toggle was released in the community edition because the funding goal was hit. Therefore, it's not exclusive to Insiders anymore! Thus, the documentation is correct.

**Comment by stevevanhooser** [comment]
Oh, I just had to update to the latest. (forgot --upgrade) Thanks! Great feature!
