### ISSUE TITLE
How to EXCLUDE some code fences from highlighting?

### ISSUE THREAD

**Issue by fralau** [squidfunk/mkdocs-material#1733]
__I checked that...__

- [X] ... the documentation does not mention anything about my idea
- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... there are no open or closed issues that are related to my idea

## Description

CodeHilite does a thorough job and will process ANY fenced code.

There are specific pieces of code one would CodeHilite not to touch, because they must be processed at a later stage (e.g. mermaid diagram). 

Since the code is already processed by CodeHilite, the code of the plugin breaks down. So for the whole website it is a tough choice: **either** CodeHilite **or** the plugin. 

In other words, either we forego code highlighting, or we forego diagrams. 

As a famous Pythonista says:

> There must be a better way!

### Use Cases

A plugin requires a fenced block (e.g. [mkdocs-mermaid](https://github.com/fralau/mkdocs-mermaid2-plugin) to do its magic.

```mermaid
graph LR
    A[Square Rect] -- Link text --> B((Circle))
    A --> C(Round Rect)
    B --> D{Rhombus}
    C --> D
```
(example taken from [mermaid website](https://mermaid-js.github.io/mermaid/#/examples?id=basic-flowchart)) 

Clearly one would not want CodeHilite to process mermaid blocks, so that the plugin
could do its magic (with javascript, etc.).

### Proposed Solution 1
A simple solution would be to notify, in the `mkdocs.yml` file that one does **not** want 
CodeHilite to process a specific type of block, e.g.

```
markdown_extensions:
  - codehilite:
    exclude:
      - mermaid
      - ...
```

### Proposed Solution 2
Within the the code of the page itself, just type:

```!mermaid
...
```

Which would be turned into:

```mermaid
...
```

(remove `!`) and everybody is happy.

Unless someone sees a much better solution, or I missed something essential?

### Screenshots / Mockups

Interpretation of mermaid code:
![Capture d’écran 2020-05-28 à 17 23 00](https://user-images.githubusercontent.com/36767124/83160827-f70eb280-a107-11ea-912c-82020d71fc83.png)

**Comment by facelessuser** [comment]
1. Don't use Codehilite and instead use SuperFences.
2. Use custom fences in SuperFences: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#custom-fences. This allows you to process certain fences differently.

**Comment by fralau** [comment]
Ah... "originality is ignorance of litterature". I'll check it and get back to you.

**Comment by facelessuser** [comment]
Keep in mind that questions regarding SuperFences should be asked over at that repo. Also keep in mind, I while I provide a general example regarding mermaid as an example, I don't directly support mermaid issues with SuperFences, but I'm more than happy to answer questions with mermaid that I have already explored.

**Comment by fralau** [comment]
Thanks a lot 🙏, this is fantastic.

I totally understand you don't directly support mermaid issues. This is the fun with these "mashup" project where we put together many good projects...

So I'll close this and if I have a question, I'll raise it on  pymdown-extensions!
