### ISSUE TITLE
Rightbar toc-item active link is not working

### ISSUE THREAD

**Issue by asifyzee12** [squidfunk/mkdocs-material#1738]
I've been trying for so long, I don't understand why active link is not working. 
inactive is working fine, but not active.

please suggest

![image](https://user-images.githubusercontent.com/52603700/83503424-77ecf600-a4dc-11ea-81e1-1c54433404fa.png)

```
<li class="md-nav__item">
  <a href="{{ toc_item.url }}" class="md-nav__link">
    {{ toc_item.title }}
  </a>

  <!-- Render nested item list -->
  {% if toc_item.children %}
    <nav class="md-nav" aria-label="{{ toc_item.title }}">
      <ul class="md-nav__list">
        {% for toc_item in toc_item.children %}
          {% include "partials/toc-item.html" %}
        {% endfor %}
      </ul>
    </nav>
  {% endif %}
</li>

```

**Comment by squidfunk** [comment]
I'm sorry, but I don't understand your problem. Please use the issue template and provide more details, so we can help you.

**Comment by asifyzee12** [comment]
> I'm sorry, but I don't understand your problem. Please use the issue template and provide more details, so we can help you.

Thanks for quick reply.
I'm not sure how exactly to do that, but okay let me try this way:

![image](https://user-images.githubusercontent.com/52603700/83520448-21d97c00-a4f7-11ea-982b-2335c7928645.png)

So, I'm referring "Table of Content" section. 
when we scroll down or click any next link, previous links gets a style change like grey text or opacity or anything we can set. like the above blue circled.
---

normal state is black circled.
But, the issue is, I can't get the active title style working like the red circled.

let me know if it's still unclear

**Comment by squidfunk** [comment]
Please use the issue template. We need to know which version of Material for MkDocs you are running, if you made customizations etc., etc. We can't help you without this information.

**Comment by asifyzee12** [comment]
yeah you are right. Okay I'll give you every detail. But for now, can you please just give me an answer is there any possiblity like : leftbar's every level becomes a section and content body only shows one section at time ?

**Comment by squidfunk** [comment]
Every entry in the "left bar" (= navigation) links to a separate page.

**Comment by asifyzee12** [comment]
Oh I apologize, by leftbar I meant "rightbar" table of content " because I've customized right bar to left bar.

**Comment by squidfunk** [comment]
No, the table of contents is automatically generated from all headlines on the current page. It cannot be separated.

**Comment by squidfunk** [comment]
Also, as I read from your last comment, you customized the theme. I'm afraid we cannot provide support for customizations. Also, next time please, please, please use the issue template. It costs so much time to understand which is taken away from my time working on this project.

**Comment by asifyzee12** [comment]
got it. Thanks for your help. I'll do that now. Coz even though from ready theme, I can't get the "active link" working yet
