### ISSUE TITLE
Is there something in process like mkdocs-rtd-dropdown ?

### ISSUE THREAD

**Issue by asifyzee12** [squidfunk/mkdocs-material#1740]
Hello,

I hope I'm suggesting feature in right section.
**I want material-table of content section as a dropdown.**

Things would be better having:
- heading 2 as a collapsable link (also clickable)
- heading 3 nesting, but if there is h4, it should become collapsable nest like above
- should have options to collapse all or expand all or expand with scrolling and getting active as a section.

I hope I made everything clear or if there is already an extension like "mkdocs-rtd-dropdown" for material theme, please close this.

**Thanks**

**Comment by squidfunk** [comment]
Duplicate of #695, as far as I understand correctly. There's no plan to implement this.

**Comment by asifyzee12** [comment]
Yeah it was same. okay. thanks
