### ISSUE TITLE
Remove <link rel="preconnect dns-prefetch" href="https://www.google-analytics.com">

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#1741]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

The theme currently has `<link rel="preconnect dns-prefetch" href="https://www.google-analytics.com">` in the head. The Google Analytics integration follows immediately afterwards so there is no need to preconnect so I think this can be removed. Furthermore, I think Safari does not accept more than one value for link rel so neither would be used.
REF: https://web.dev/preconnect-and-dns-prefetch/#resolve-domain-name-early-with-reldns-prefetch

**Comment by squidfunk** [comment]
`git blame` shows that @Stanzilla [added it](https://github.com/squidfunk/mkdocs-material/blame/4b6372700611eb1536b9dfcd94c8fad0ba8cb810/src/partials/integrations/analytics.html#L25). Any thoughts? I don't care what it is, but we should settle on something we all can agree on, so we won't be removing and adding it again.

**Comment by Stanzilla** [comment]
I would be fine with the format change.

**Comment by coliff** [comment]
I can open a PR then to remove `preconnect` leaving  `<link rel="dns-prefetch" href="https://www.google-analytics.com">`

**Comment by squidfunk** [comment]
> I would be fine with the format change but not the removal.

Could you elaborate? I'd be interested in the _why_.

**Comment by Stanzilla** [comment]
@squidfunk yes but it should make a difference since the script is loaded with the async keyword. I'm pretty sure I compared the numbers before but I don't have them anymore.

**Comment by coliff** [comment]
fair enough - I'm fine to leave `<link rel="dns-prefetch" href="https://www.google-analytics.com">` there then. `dns-prefetch` consumes less resources than `preconnect` and may still save a few microseconds. :-)

**Comment by Stanzilla** [comment]
well preconnect does what dns-prefetch does + more, I only left in dns-prefetch as a fallback

**Comment by coliff** [comment]
I know but Google Analytics isn't a high-priority resource - it's not critical to load and display the page, by adding preconnect it can take browser resources away from loading other assets such as Google Fonts or the GitHub API (which the user does see).

https://www.webpagetest.org/result/200605_14_88ca7dd3a427cb2c9e919f74affcd297/3/details/#waterfall_view_step1

The difference either way is very small, so I don't really mind... but overall I'd suggest to not use preconnect for a non-critical resource like Google Analytics.

**Comment by squidfunk** [comment]
I missed that it's `async`, that's correct. However, I have to say again that I really don't want to blindly follow the Lighthouse cargo cult. I'm all for making the TTFCP, TTFMP and TTI as small as possible, but I'd say that actual _measuring_ will lead to better decisions than following generic advice and making Lighthouse happy. In my life as a programmer, I've fallen all too often into the trap believing A is faster/better than B without having measured, and it either fired back or I was really stunned that it's not the way I expected. I'd say it's probably better too provide fewer hints to the browser than to provide too many competing hints. For this reason, my opinion is that we should remove it entirely (as suggested in the OP), unless somebody comes up with data showing that it has a measurable, significant and (most importantly) positive effect.

**Comment by squidfunk** [comment]
Google Analytics is a non-critical and optional resource. It's loaded asynchronously, and DNS prefetching will save as little as 25-50ms (as I get from the waterfall graphs @coliff posted). Keeping the prefetching hint is a micro-optimization, which _seems_ to have no measurable effect, but _may_ steal resources from the browser for loading other asynchronous requests like Google Fonts or GitHub stars. For this reason, I consider it the safest to remove the `link` tag altogether.

We can re-consider integration when the following conditions are met:

1. Including the tag does not slow down average render time by stealing resources.
2. The hint has a positive impact, which for Google Analytics means a smaller rate of dropped events due to a long-running DNS request.

**Comment by squidfunk** [comment]
Fixed in 1df750a9.

**Comment by squidfunk** [comment]
Released as part of 5.2.3
