### ISSUE TITLE
Include url File as Code within Code Block

### ISSUE THREAD

**Issue by flywire** [squidfunk/mkdocs-material#1744]
**Description**

Allow code-blocks to include files referenced as urls

**Use Case**

When project code is updated the documentation would be updated automatically.

**Example**

Following [https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#via-markdown-syntax-recommended](https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#via-markdown-syntax-recommended):

~~~
``` python
.. include:: /url/source.py
```
~~~

**Result**

~~~
import tensorflow as tf
~~~

**Comment by squidfunk** [comment]
Thanks for your suggestion. Unfortunately, this is nothing we can solve in this project, as it is related to Markdown processing, not rendering. You could ask the guys over at Python Markdown or Pymdown Extensions. Maybe the latter already provides such a feature.

**Comment by flywire** [comment]
https://github.com/facelessuser/pymdown-extensions/issues/972
