### ISSUE TITLE
disabling disqus documentation is missing the correct value for empty string''

### ISSUE THREAD

**Issue by haimari** [squidfunk/mkdocs-material#1746]
Please update the documentation for disabling disqus on a specific page

[](https://squidfunk.github.io/mkdocs-material/extensions/metadata/#disqus)

The documentation above mentions setting:

`disqus:`

It should be:

`disqus: ''`

At least this is what works for me with latest version.

**Comment by squidfunk** [comment]
Fixed in 5d0e4012, thanks for reporting!
