### ISSUE TITLE
Metadata forces Setex notation, confusing remark

### ISSUE THREAD

**Issue by mastercoms** [squidfunk/mkdocs-material#1756]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

The python markdown [documentation](https://python-markdown.github.io/extensions/meta_data/) expresses there are a few ways to include metadata into a markdown file, either just by adding it to the top of the file, or using `...` or `---`. Mkdocs Material seems to only support `---`. This is problematic for `remark-lint`, a popular Markdown linter, which finds the `---` syntax to be a Setext header, instead of [atx](https://arcticicestudio.github.io/styleguide-markdown/rules/headings.html), as well as some other issues:

```
        2:1-3:4  warning  First heading level should be `1`             first-heading-level          remark-lint
        2:1-3:4  warning  Headings should use atx                       heading-style                remark-lint
        2:1-3:4  warning  Use headings shorter than `60`                maximum-heading-length       remark-lint
        2:1-3:4  warning  Don’t add a trailing `?` to headings          no-heading-punctuation       remark-lint
        2:1-3:4  warning  Missing blank line before block node          no-missing-blank-lines       remark-lint
```

If I use the `...` syntax, these lint errors go away, but Mkdocs Material does not parse the metadata.

### Expected behavior

Mkdocs Material supports the full valid syntax of the metadata extension.

### Actual behavior

Mkdocs Material only supports the `---` YAML syntax.

### Steps to reproduce the bug

1. Add 
```yml
markdown_extensions:
    - meta
```
to mkdocs.yml, enabling the metadata plugin.
2. Add
```
...
description: A reasonably long test description, to test the heading length limit?
...
```
to a test markdown file for docs.
3. The generated site will display the metadata in the document, rather than parsing it as metadata:
```
description: A reasonably long test description, to test the heading length limit? …
```

### Package versions

* Python: 3.7,3
* MkDocs: `1.0.4`
* Material: `5.2.3`

### Project configuration

``` yaml
markdown_extensions:
    - meta
```

### System information

* OS: Fedora 31
* Browser: Firefox 77.0.1

**Comment by scherermichael** [comment]
I haven't tested it, but according to the documentation, the first line must be `---`. Only the closing delimiter may also be `...`. Hope it helps.

**Comment by squidfunk** [comment]
Material for MkDocs supports exactly the same syntax that MkDocs itself, as it's only _a theme_ for MkDocs. It doesn't perform any pre- or post-processing of the Markdown. Thus, the problem you describe is either a configuration issue or an upstream issue.

For this reason, I'm closing this issue.

**Comment by mastercoms** [comment]
I'm so sorry all, thanks for your help with my stupidity!
