### ISSUE TITLE
Search duplicates result when using app.search$.subscribe

### ISSUE THREAD

**Issue by erikatakahara** [squidfunk/mkdocs-material#1761]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

We opened [this issue](https://github.com/squidfunk/mkdocs-material/issues/1658) some time ago to gather some metrics from search. But when we call the function `app.search$.subscribe`, the search result appears duplicated. We checked on the network tab that everytime we call that function, the `search_index.json` are downloaded again (maybe that's related to this issue). 

### Expected behavior

We expect that the function doesn't change the search behavior.

### Actual behavior

When calling `app.search$.subscribe` it's duplicating the search result.

### Steps to reproduce the bug

1. Make a search on the platform
2. On console, call this code: `app.search$.subscribe(console.log)`
3. The search result should show duplicated

### Package versions

* Python: `3.5.2`
* MkDocs: `1.1.2`
* Material: `5.3.0`

### Project configuration

It's happen on the mkdocs material website, so I think the yaml here is not needed.

### System information

* OS: Linux Alpine
* Browser: Chrome, Firefox, Safari

**Comment by squidfunk** [comment]
You're right! That's a bug. Skimming through the code, my educated guess is that this observable is missing a `shareReplay` at the end turning it into a hot observable:

https://github.com/squidfunk/mkdocs-material/blob/6992b3cd733699619bd3b197b400ff51436d9b54/src/assets/javascripts/index.ts#L268-L303

I'll investigate when I find some time the next days.

**Comment by squidfunk** [comment]
Fixed in f32778cd.

**Comment by squidfunk** [comment]
Released as part of 3.5.1.

**Comment by erikatakahara** [comment]
Nice!! Thanks =]
