### ISSUE TITLE
PyMdown Tabbed not working with code blocks

### ISSUE THREAD

**Issue by StarfallProjects** [squidfunk/mkdocs-material#1762]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

When I implement tabs, as in the documentation, it creates the tabs but does not correctly format the code in them.

Documentation example: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#grouping-code-blocks

My markdown:

```
=== "Pandas"
    ```python
    import pandas as pd
    import numpy as np
    import cape

    df = pd.DataFrame(np.ones(5,), columns=["value"])
    policy = cape.parse_policy("test_policy.yaml")
    df = cape.apply_policies([policy], "transactions", df)

    print(df.head())
    ```

=== "Spark"
    ```python
    ```
```

### Expected behavior

Tabs with code blocks, correctly highlighted

### Actual behavior

Tabs with everything within them treated as plain text:
![image](https://user-images.githubusercontent.com/10284570/85022340-14fd8f00-b16b-11ea-94ea-e0266e2dc33b.png)

Tried copying the docs exactly (copy-pasted), same issue:
![image](https://user-images.githubusercontent.com/10284570/85022904-d87e6300-b16b-11ea-8e97-cee36a385d3f.png)


Note that other markdown is ok (for example, if you write some text and make it bold, that formats correctly)

### Steps to reproduce the bug

1. Add pymdownx.tabbed and codehilite to your markdown_extensions
2. Create a .md file using the tabbed syntax in the docs
3. Place code blocks in the tabs
4. Run mkdocs serve and preview in browser

### Package versions

* Python: 3.8.3
* MkDocs: 1.1.2
* Material: 5.3.0
* pymdown-extensions 7.1

### Project configuration

The extensions section:

``` yaml
markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.tabbed
    - toc:
        permalink: "#"
```

### System information

* OS: Windows 10
* Browser: Chrome latest

**Comment by facelessuser** [comment]
You are not enabling any extensions to handle fenced code (which is what we call the multiline block format code blocks flanked with ` ``` `). The original Markdown spec never mentioned fenced blocks, so it is not in the core Markdown syntax but is implemented via a plugin for those who wish to use it.

Python Markdown provided the `fenced_code` extension, but unfortunately, it does not work in nested constructs. I would personally recommend using [SuperFences](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/) (full disclosure, I'm the author of the plugin).

I would also mention that troubles with Markdown parsing should be reported in either the Markdown parser's repository or an extension's repository, not the theme which does not control parsing at all.

**Comment by StarfallProjects** [comment]
Thanks! FWIW, I found I needed both the tabbed and the super-fences extensions. Have submitted a PR to the docs.

**Comment by facelessuser** [comment]
Yes, this would be the correct approach.

**Comment by byrnereese** [comment]
I have encountered this same problem when I disabled the superfences plugin -- given that it is now deprecated and it has been recommended we use the tabbed plugin alone. I feel I may not be understanding something though...

**Comment by squidfunk** [comment]
From my understanding SuperFences is far from being deprecated - only the tab modifier should not be users anymore. If you want to best code blocks in tabs, you need both extensions.

https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#content-tabs

**Comment by facelessuser** [comment]
Yeah, SuperFences is not deprecated at all, but the old tab feature of SuperFences is as we now have the Tabbed extension for general purpose tabs as opposed to code specific tabs.

**Comment by Sieboldianus** [comment]
Just a note, in the newest mkdocs Material release (8.2.4), it is also necessary to enable "alternate style" to use `===`
```
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
```
