### ISSUE TITLE
Permalinks copy to clipboard

### ISSUE THREAD

**Issue by baneageorge** [squidfunk/mkdocs-material#1784]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea
I could see that copy to the clipboard was already done for codehilite I guess it should be easy to make for Permalinks?
https://github.com/squidfunk/mkdocs-material/issues/315

## Description

With permalinks, when you click on one the URL gets updated.
I think it will be useful if the URL will be copied to the clipboard as well.

### Use Cases

By clicking on the permalink the entire link should be copied to clipboard.

**Comment by squidfunk** [comment]
Thanks for your suggestion. However, I'd not consider this being good user experience. I've never seen this on any site.

**Comment by baneageorge** [comment]
Hi, thank you for your fast reply.
What exactly would ruing the user experience?
In my case, it happens that many times I have to direct users to a specific part of the page.
At the moment the process is to click on the permalink, then click on the address bar and then click copy. When doing this on mobile it can be very annoying, especially if you have to do it frequently...
I am not sure what I am missing related to user experience. Is there any other meaning of permalinks if apart from sharing the precise link of the header?

**Comment by facelessuser** [comment]
I would personally not like clicking an anchor to overwrite my clipboard. I prefer copying the link when, and only when I want it. So it would ruin the user experience for me.

**Comment by squidfunk** [comment]
Exactly. This is definitely an edge case and not something we'd consider adding to `master`, so maybe you could just use some [extra Javascript](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) to achieve what you want?

**Comment by baneageorge** [comment]
Ok, I will look into the javascript options. Could as well be a flag in the config right to activate this functionality or not.

**Comment by squidfunk** [comment]
Yes, it could be a flag, but I see no reason why we should implement it.

**Comment by wilhelmer** [comment]
If at all, I'd implement this with a modifier key, e.g., Shift-clicking the anchor copies the URL to clipboard. Of course, that is not discoverable, but you can add a tooltip to the permalink anchor like this:

```

**Comment by squidfunk** [comment]
Closing for the reasons stated.
