### ISSUE TITLE
Code css variables not working similar to normal variables

### ISSUE THREAD

**Issue by AXVin** [squidfunk/mkdocs-material#1786]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

The variables `--md-code-fg-color` and `--md-code-bg-color` both require you to set them in `:root>*` while the Getting Started page on documentation states that it could be set with just `:root` like any other variable.

If you try with the latter, it is just not up enough in the hierarchy because it was originally defined in `:root>*`

Depending on the intention of the devs, this might just be a documentation error

### Expected behavior

It should allow us to configure it in `:root` just like the docs say

### Actual behavior

It doesn't change when set with only `:root`

### Steps to reproduce the bug

1. Create a new extra stylesheet
2. In the `:root` element, try to change the said elements

### Package versions

* Python: 3.7.3
* MkDocs: 1.1.2
* Material: 5.4.0

### System information

* OS: Windows 7 Ultimate 32-bit
* Browser: Chrome v83.0.4103.97

**Comment by squidfunk** [comment]
This is not an error. When using the `palette.primary` and `palette.accent` options in `mkdocs.yml`, the respective variables are set on `:root > *`. This is due to the fact, how the color theming works. To override them, you must use the same selector. This should be corrected in the docs. PRs welcome!

**Comment by squidfunk** [comment]
Fixed in c6649318.
