### ISSUE TITLE
How to embed HTML iFrame into mkdocs/material?

### ISSUE THREAD

**Issue by ajfriend** [squidfunk/mkdocs-material#1787]
__I checked that...__

- [X] ... the documentation does not mention anything about my idea
- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... there are no open or closed issues that are related to my idea

## Description

I'd like to figure out how to embed an html iframe into a page. I've asked the question here, but I'm not sure it is getting seen:

https://stackoverflow.com/questions/62629162/how-to-embed-html-iframe-into-mkdocs-material

**Comment by squidfunk** [comment]
This is a general Markdown question and not solely related to this project. Our issue policy says that such questions should either be asked in their respective repositories or on a message board like StackOverflow, which you already did. I understand your frustration, but the maintainers of this project only have so much time available, so we can’t help everyone with problems that are only tangentially related to this project.
