### ISSUE TITLE
change  md-content div  ratio of the page.

### ISSUE THREAD

**Issue by hpcaicom** [squidfunk/mkdocs-material#1791]
The page includes left nav, middle content, right toc. How to change the width ratio of different part in the page. I don't chage it success using extra.css.

**Comment by squidfunk** [comment]
Extra CSS is the way to go 😊

**Comment by hpcaicom** [comment]
@squidfunk, I followed this discussion (https://github.com/squidfunk/mkdocs-material/issues/478) to disable toc, the toc can be disabled, but the md-content can't be expanded to take over the toc space. Could you give the example of how to change the CSS to take over toc space.

**Comment by squidfunk** [comment]
Im sorry, but we cannot assist you in customizing the theme, that’s entirely out of scope. Please understand that we cannot offer this service, as I’m already doing most of the work for this project for free (aside from the few sponsorships).

If you wish to tailor it to your needs, I recommend to get a professional web developer. You can also drop me a mail to discuss rates.

**Comment by squidfunk** [comment]
Closing as answered.
