### ISSUE TITLE
Search results not sorted by relevance

### ISSUE THREAD

**Issue by bruderstein** [squidfunk/mkdocs-material#1799]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

We have a very large installation with mkdocs-material. When searching for a longer phrase, we get seemingly random articles first. With an official theme, we get the article that contains that phrase first, one that is similar second etc. 

Checking lunr.js manually with our 5MB index file, those documents that appear first on a normal theme also come out with the top scores (10.something and 8.something for the first two). The first documents returned when using this theme score 1.something.

### Expected behavior

Documents with the most relevance should appear first

### Actual behavior

Documents appear is some seemingly random order

### Steps to reproduce the bug

1. Grab a phrase from one of the pages on the mkdocs material site. e.g. `Material for MkDocs selects the (best-)matching stemmer for the given theme language`
2. Search for that phrase
3. Note that the first document is various links in the "Upgrading" doc. Second doc is "Revision"
4. Build the mkdocs material site with a built in theme (e.g. readthedocs)
5. perform the same search: `Material for MkDocs selects the (best-)matching stemmer for the given theme language`
6. Note the top link is the Language heading in the search page, where this phrase exists.

### Package versions

* Python: `3.8.2`
* MkDocs: `1.1.2`
* Material: `5.4.0`

### Project configuration

Can use this project's own documentation to see the issue.

### System information

* OS: Mac & linux
* Browser: Firefox

**Comment by squidfunk** [comment]
You may check out #1790 which should yield some improvements 😊

**Comment by squidfunk** [comment]
As discussed in #1801, this is the first feature we're currently improving as part of the Sponsorware build which should already fix all of the problems discussed in #1790:

![Bildschirmfoto 2020-07-09 um 23 57 45](https://user-images.githubusercontent.com/932156/87094966-24d73300-c240-11ea-93a3-f06b2c8e8994.png)

**Comment by squidfunk** [comment]
The new search functionality is deployed on:
https://squidfunk.github.io/mkdocs-material-next/

**Comment by squidfunk** [comment]
Im closing this issue, as this was released as part of the sponsor edition in `5.4.0+next-1.0.0`.
