### ISSUE TITLE
🚀 The future of Material for MkDocs

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#1801]
___tl;dr__: Material for MkDocs will switch to a [Sponsorware](https://github.com/sponsorware/docs) model. New features will first be released exclusively to Sponsors. When a certain Sponsoring goal is reached, these features will be released to the public and be generally available!_

<a href="https://github.com/sponsors/squidfunk">
<img alt="Sponsor this project" src="https://user-images.githubusercontent.com/932156/86788364-601e0a00-c066-11ea-804b-5faef7d5401a.png" width="100" />
</a>

---

Material for MkDocs has come a long way. Version 5 brought many improvements and a completely new architecture which makes extension and customization much easier. We haven't even begun to scratch the surface. After the dust settled and the majority of bugs introduced by the latest major release were fixed, I want to talk about the future.

### Where we are

Thanks to all of you who participated in the [user survey](https://twitter.com/squidfunk/status/1259832077668810752), we have a pretty good idea of what can be improved and what features are missing or could be better. Additionally, I have tons of ideas on how to improve this project, especially for large (and enterprise) documentation projects. With Material for MkDocs being [more popular than ever before](https://porter.io/github.com/squidfunk/mkdocs-material), the number of issues and support requests is increasing at a steady pace.

__As the original author, I'm doing 99% of maintenance and design work__. I want to ensure that issues get fixed quickly and that new useful features make their way into `master`, but I also have to somehow pay for my living. I've invested months and months of my spare time into this project. __I'm super excited to see the first sponsors joining__, supporting this project, but the collected amount is currently very far from the value of the time I'm putting in this project. With so many big companies using it for their entire front-facing documentation, I'm hoping for more support, to ensure the future of this project!

### Where we're going

This brings me to the announcement I want to make: Material for MkDocs switches to a [Sponsorware](https://github.com/sponsorware/docs) model! This means:

- [x] __New features will first be made available exclusively to sponsors__
- [x] __Sponsors will be able to propose, discuss and vote, which issues and/or features we'll tackle next__

Of course, some things won't change:

- [x] __Material for MkDocs will remain free and Open Source, forever__
- [x] __Bugfixes will be addressed as quickly as possible__

I'm currently reshaping the Sponsorship tiers to offer something for agency and companies, but from $10 a month, you will be the first to enjoy new features that will increase the value and uniqueness of your documentation project.

### What's up next

The following roadmap shows, at which monthly goals those features will be available to the public:

- [ ] __$500 | New Search__: more relevant search results, more intelligent search summaries, improved search UI/UX
- [ ] __$1,500 | Versioning__: native support to deploy multiple versions of the same documentation
- [ ] __$3,000 | A new layout__: alternative, completely different vertical layout, optimized to read documentation and code side-by-side.

The development will not necessarily be linear, which means that the work on the new layout might start before versioning is completed. I've got quite some nice ideas for a new layout, which will also mean an architecture to support multiple layouts!

__As always, I'm happy to receive your feedback!__ Let's make this project even better, together!

---

_If you're already a sponsor – I'm preparing everything in the background. You'll be invited to a private repository and a sponsor-only community within the next days. Also, don't worry about deployment – I'm working on a very simple single-line solution_

**Comment by wilhelmer** [comment]
Sounds exciting. I really hope that this works out. You're doing an outstanding job, and it's easy to see how much heart and soul you put into this project. Hopefully, companies will be more willing to join the sponsorship if there's an immediate benefit for them.

Also, don't be too disappointed with the first outcome of the sponsorship, I think the pace in the enterprise business is a little different, so you can't expect to put something up and companies are immediately joining in. It takes time. I've bugged my supervisor a dozen times about sponsoring you, but it's a very slow process.

**Comment by martinbira** [comment]
> it's a very slow process. (Also, there's COVID, so companies aren't exactly enthusiastic about spending money right now.)
Same thing here. Hopefully these discussions will get moving along once summer and all vacation periods are over here, e.g. late august...

**Comment by squidfunk** [comment]
Thank you guys! I'm aware that this is a rather new model and companies first need to adapt. I think that giving them some reasons through new, exclusive features, might speed up the process 😊  Also, $10 as an entry barrier is not too high for personal use. Let's see how this works out.

I'll be announcing the modalities on how I'll keep the sponsors in the loop and how we do the releases on the weekend.

**Comment by jaceklaskowski** [comment]
I love and wholeheartedly support this idea. I've just migrated a book to mkdocs with material for mkdocs and would not be happy to switch once more soon. I'm ready to pay to stay 👍

I'm curious how it'd work for a mere developer like myself. If I paid €10 monthly and no one else joined (or a very few), would that mean that we'd receive no "sponsorware" updates (e.g. A new layout which is the most expensive)?

**Comment by squidfunk** [comment]
@jaceklaskowski I'm glad you enjoy the project!

> I'm curious how it'd work for a mere developer like myself. If I paid €10 monthly and no one else joined (or a very few), would that mean that we'd receive no "sponsorware" updates (e.g. A new layout which is the most expensive)?

Every sponsor that joins in for $10 or more will __immediately__ receive all new features and developments. I will continue developing features for this project, just as before, so it's not tied to how many sponsors this project has. If a threshold is reached, the feature is released to the public, which means it's merged back into the `master` of this repository!

**Comment by squidfunk** [comment]
I'm super happy with the feedback and more sponsors joining! Up to now, I've heard not a single negative comment. That's quite surprising. I just finished the first draft of the new documentation that I just released, including more information on the sponsor edition:

https://squidfunk.github.io/mkdocs-material/sponsorship/

If there're any unanswered questions, please don't hesitate to ask. This is a work in progress, and I'm happy to add more information to the site as we work through the first sponsor edition releases. I'm closing this issue, as the information can now be found on the official docs, but you may post your questions here.
