### ISSUE TITLE
Add chat bots.

### ISSUE THREAD

**Issue by Amber1990Zhang** [squidfunk/mkdocs-material#1804]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

I want to add a chat button for my doc site so that people can ask questions and get response more quickly. I want to use [Comm100](https://www.comm100.com/). I need somewhere to add the following code:

```html
<!--Begin Comm100 Live Chat Code-->
<div id="comm100-button-f87c9787-cf25-4f2b-b92a-b14da3805db6"></div>
<script type="text/javascript">
  var Comm100API=Comm100API||{};(function(t){function e(e){var a=document.createElement("script"),c=document.getElementsByTagName("script")[0];a.type="text/javascript",a.async=!0,a.src=e+t.site_id,c.parentNode.insertBefore(a,c)}t.chat_buttons=t.chat_buttons||[],t.chat_buttons.push({code_plan:"f87c9787-cf25-4f2b-b92a-b14da3805db6",div_id:"comm100-button-f87c9787-cf25-4f2b-b92a-b14da3805db6"}),t.site_id=40000004,t.main_code_plan="f87c9787-cf25-4f2b-b92a-b14da3805db6",e("https://vue.comm100.com/livechat.ashx?siteId="),setTimeout(function(){t.loaded||e("https://standby.comm100vue.com/livechat.ashx?siteId=")},5e3)})(Comm100API||{})
</script>
<!--End Comm100 Live Chat Code-->
```

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/42762957/87140163-a4faa880-c2d3-11ea-81ce-63704f514aca.png)

**Comment by squidfunk** [comment]
This can easily be done with extra JavaScript:
https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript

**Comment by Amber1990Zhang** [comment]
> This can easily be done with extra JavaScript:
> https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript
> 
> If you need to include the `div`, you can also override some partial or template block:
> 
> https://squidfunk.github.io/mkdocs-material/customization/#overriding-template-blocks

Thanks, I'll try your suggestion.

**Comment by squidfunk** [comment]
Closing as answered.
