### ISSUE TITLE
tabs:true 并不生效额 

### ISSUE THREAD

**Issue by molu-ggg** [squidfunk/mkdocs-material#1805]
还是 tabs:false 的老样子

theme:
  name: material
  feature:
    _**tabs: true**_
  palette:
    primary: 'Teal'
    accent: 'Pink'

  #font:
    #text: 'Ubuntu'
    #code: 'Ubuntu Mono'
  language: 'zh'

extra:

  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
    - 主页: index.md
    - 机器与深度学习:
        - 深度:  x_modern.md
   
    - 问题分析:
        - 问题:  new_test.md

  #  - 高级算法:
     #   - 算法:  c_nerve2.md

**Comment by xgui3783** [comment]
I believe instead of

```markdown
# truncated
themes:
  features:
    tabs: true
```

 you need:

```markdown
# truncated
themes:
  features:
    - tabs
# truncated
```

(per <https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml#L54>)

**Comment by squidfunk** [comment]
@xgui3783 is right. If you're using v5.x you need to change the configuration. Other than that _please_ stick to the issue template.
