### ISSUE TITLE
Allow to embed the TOC into the left-hand navigation

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#1815]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

This is a proposal for a much-requested feature to:

1. ... embed the TOC as part of the sidebar, i.e. show it on the left
2. ... remove the TOC from the right for additional space

### Use Cases

Some users prefer to have a wider content area than Material currently offers.

__This feature will be part of the sponsor edition and later merged back into the community edition ☺️__ 

See #1801 for details.

### Screenshots / Mockups

![screenshot-squidfunk-github-io-mkdocs-material-plugins-search-1595154768510](https://user-images.githubusercontent.com/932156/87872837-4fea2100-c9bc-11ea-9496-ebb9d7cbc79a.png)

**Comment by MikeyMJCO** [comment]
I like this idea, I have had requests for a wider content area if possible.

**Comment by squidfunk** [comment]
@MikeyMJCO Wider than what is shown in the screenshot?

**Comment by maxtsero** [comment]
No, wider than current style :-)

**Comment by squidfunk** [comment]
I guess we could also add another option to additionally increase the overall width. The aim of this proposal is to collect some feedback before I start implementing it.

**Comment by Kanaduchi** [comment]
It is good idea. 
This implementation can include 3 parts:
1. Possibility to increase wide of content area
2. Hide TOC panel
3. Hide TOC panel and show TOC in navigation

**Comment by squidfunk** [comment]
@Kanaduchi 2. is already possible and documented in the new docs:
https://deploy-preview-1735--mkdocs-material-preview.netlify.app/setup/setting-up-navigation/#toc_depth

**Comment by Kanaduchi** [comment]
> @Kanaduchi 2. is already possible and documented in the new docs:
> https://deploy-preview-1735--mkdocs-material-preview.netlify.app/setup/setting-up-navigation/#toc_depth

Can we do it only on particular page? Example - I have several pages without any headers. And on the right I see empty column. So I do not need right-side panel on such pages

**Comment by pktiuk** [comment]
@Kanaduchi 
I think it should be added as templates, they are very easy to set and can be added to particular page.
to set you would just add
```
---
template: another_type_of_page.html
---
```

@squidfunk 
I would really love an empty template, which could be used as an index page.

**Comment by pktiuk** [comment]
With this we could acheive even something like [this](http://www.openboard.ch/) (first example which came into my mind) or similar to [this](https://appimage.org/) - even without these filled with color spaces on top (I don't know how to name them) it could give good effect.

**Comment by squidfunk** [comment]
@pktiuk that's correct, essentially everything of the theme can be changed by overriding it. However, most authors don't bother and want to have good defaults/options, so this issue collects some ideas to provide that.

> I would really love an empty template, which could be used as an index page.

What do you mean by empty? You can create an empty template by not extending the base template. Other than that, I recommend you take a look at the [landing page template of the official documentation](https://github.com/squidfunk/mkdocs-material/blob/master/src/overrides/home.html). All moving parts are put into blocks, so overriding it is quite easy.

**Comment by pktiuk** [comment]
@squidfunk 
By empty, I mean without TOC and Table Of Pages. Just a plain sheet with default top bar.

>  Other than that, I recommend you take a look at the landing page template of the official documentation. All moving parts are put into blocks, so overriding it is quite easy.

I know, that there is a homepage for documentation, but I don't think that reverse-engineering is a good way for "casual" users, most of them just want to use this theme with minor tweaks according to official documentation ok MkDocs.
Moreover, I am one of these casuals, that's why I have chosen MkDocs. I just don't have knowledge to mess with templates.

I have found information about templates and Meta-Data in official [MkDocs site](https://www.mkdocs.org/user-guide/writing-your-docs/#file-layout), and later I checked if this theme supports templates (I couldn't find anything in docs).
I think these templates as a way of customization would be more consistent with regular MkDOcs usage.

**Comment by TomBarnes** [comment]
In my use case it would be particularly valuable if the with of the page track the width of the browser window, regardless of whether navigation was on the left or the right.  In my use case I have tables that are both long and wide, and so a) the content in the rightmost columns is hidden, and b) you have to scroll to the bottom of the table to find the scroll bar, scroll to the right to see the right-most columns, and then try to scroll back up to the right row.  This is VERY painful and almost unusable.  See for example: https://secure-device-onboard.github.io/docs/latest/protocol-specification/protocol-data-types/#composite-types

**Comment by squidfunk** [comment]
Tables are always a problem for responsive layouts. They may not be the ideal components for your use case. Have you tried using definition lists?

**Comment by TomBarnes** [comment]
I'm not familiar with Definition Lists.  I will investigate.  Thanks for the suggestion.

**Comment by squidfunk** [comment]
The table of contents can now be configured to be [automatically hidden when empty](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#automatic-hiding):

``` yaml
theme:
  features:
    - toc.autohide
```

This will stretch the remaining content to the whole width.

**Comment by squidfunk** [comment]
[Material for MkDocs Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) now allows us to do the following:

__Hide table of contents__:

``` markdown
---
hide:
  - toc
---

# ...
```

![screenshot-localhost-8000-setup-changing-the-language-1604764164815](https://user-images.githubusercontent.com/932156/98445681-37dc1000-2119-11eb-9f74-7db93dfe9e70.png)

__Hide navigation__:

``` markdown
---
hide:
  - navigation
---

# ...
```

![screenshot-localhost-8000-setup-changing-the-language-1604764212513](https://user-images.githubusercontent.com/932156/98445695-517d5780-2119-11eb-9a8d-e0893822e173.png)

__Stretch to full width__ (= hide both):

``` markdown
---
hide:
  - navigation
  - toc
---

# ...
```

![screenshot-localhost-8000-setup-changing-the-language-1604764277189](https://user-images.githubusercontent.com/932156/98445715-796cbb00-2119-11eb-9eae-d58592265c9d.png)

I'm also working on providing an option to show the table of contents in the navigation – should land pretty soon!

**Comment by squidfunk** [comment]
Insiders 1.10.0 adds support for [integrating the table of contents into the navigation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration):

![screenshot-localhost-8000-getting-started-1605451129132](https://user-images.githubusercontent.com/932156/99187754-ad1e9500-2758-11eb-89b6-b8fa370ed7aa.png)

Furthermore, I added some documentation on how to [increase the overall width of the theme](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#content-area-width) with 2-3 lines of CSS. This resolves all points discussed in this issue! 😊

**Comment by NikosAlexandris** [comment]
> Insiders 1.10.0 adds support for [integrating the table of contents into the navigation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration):
> 
> ![screenshot-localhost-8000-getting-started-1605451129132](https://user-images.githubusercontent.com/932156/99187754-ad1e9500-2758-11eb-89b6-b8fa370ed7aa.png)
> 
> Furthermore, I added some documentation on how to [increase the overall width of the theme](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#content-area-width) with 2-3 lines of CSS. This resolves all points discussed in this issue! 😊

Would it be possible to have this in a per-page basis? Like, some pages should be subject to

``` yaml
theme:
  features:
    - toc.integrate
```

while other pages can be subject to

``` yaml
theme:
  features:
    - navigation.indexes
```

It would be nice to have `toc.integrate` along with the possibility to section index pages.

**Comment by squidfunk** [comment]
Maybe, but it's currently not a priority. We might investigate in the future.
