### ISSUE TITLE
Broken link to Docker image

### ISSUE THREAD

**Issue by mrmanc** [squidfunk/mkdocs-material#1824]
__I checked that...__

(these aren’t applicable—I’m reporting an issue with the docs)

## Description

There is a broken link on [this page](https://squidfunk.github.io/mkdocs-material/plugins/revision-date/). The [Docker image](https://squidfunk.github.io/mkdocs-material/plugins/getting-started.md/#language) link doesn’t point at the same location that the Docker image [link on other pages](https://hub.docker.com/r/squidfunk/mkdocs-material/) does. I’ve checked the source of the page, but I can’t see why this is the case, hence no PR.

### Expected behavior

Land on https://hub.docker.com/r/squidfunk/mkdocs-material/

### Actual behavior

Land on https://squidfunk.github.io/mkdocs-material/plugins/getting-started.md/#language with a 404

### Steps to reproduce the bug

1. Go to https://squidfunk.github.io/mkdocs-material/plugins/revision-date/
2. Click Docker image

### System information

* OS: MacOS
* Browser: Chrome

**Comment by squidfunk** [comment]
Thanks! You're right, the reference is broken. However, I'm restructuring the docs and this page will be gone anyway. I hope to finish the restructuring by the end of the week.

**Comment by mrmanc** [comment]
No problem 🙇🏻‍♂️. Since the page is going to disappear I’ll close the issue for now.
