### ISSUE TITLE
Enable Disqus only in one page

### ISSUE THREAD

**Issue by ericdallo** [squidfunk/mkdocs-material#1826]
__I checked that...__

- [X] ... the documentation does not mention anything about my problem
- [X] ... the problem doesn't occur with the default MkDocs template
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... there are no open or closed issues that are related to my problem

## Description

At [lsp-mode](https://emacs-lsp.github.io/lsp-mode/), we'd like to have a blog section and enable Disqus comments on those blog pages(ex: https://emacs-lsp.github.io/lsp-mode/blog/2020/7.0-release/).
On the documentation, I saw that if we enable the `disqus` extra, all pages will have Disqus comments, but we would like to have only for blog pages, so I didn't enable this extra and added the `disqus meta` only on the page I would like to see `Disqus`.
We have the `meta` extension enabled [here](https://github.com/emacs-lsp/lsp-mode/blob/master/mkdocs.yml#L131) and the `disqus meta` [here](https://github.com/emacs-lsp/lsp-mode/blob/master/docs/blog/2020/7.0-release.md).

### Expected behavior

I expect to see the Disqus section comments here: https://emacs-lsp.github.io/lsp-mode/blog/2020/7.0-release/

### Actual behavior

It only shows a "Comments"  subtitle on the page:
![image](https://user-images.githubusercontent.com/7820865/88425184-60880600-cdc5-11ea-8050-f4a3892a6d53.png)

### Package versions

we are using the latest mkdocs-material docker image [here](https://github.com/emacs-lsp/lsp-mode/blob/master/.github/workflows/docs.yml#L34)

### Project configuration

https://github.com/emacs-lsp/lsp-mode/blob/master/mkdocs.yml

### System information

* OS: NixOS 20.03
* Browser: Google Chrome 84.0.4147.89

**Comment by squidfunk** [comment]
Have you read https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/#selective-integration ? 😊

**Comment by ericdallo** [comment]
Thanks for the reply! 
Yes, it says:
> This will insert a comment system on every page, except the index page.
I don't want to edit every page of my docs folder adding a meta do disable Disqus and only enable on the blog page...
Is there any other way to do it?

**Comment by squidfunk** [comment]
Just tested it and if I enable the `disqus` metadata, the integration is loaded (albeit not rendered, as we don't use it):

<img width="708" alt="Bildschirmfoto 2020-07-26 um 14 37 52" src="https://user-images.githubusercontent.com/932156/88479190-9b1caa80-cf4d-11ea-93b4-5ee86b91f73b.png">

If I add a whitespace, i.e. `mkdocs material`, I see the same behavior as you described. Note that you have to provide your [shortname](https://help.disqus.com/en/articles/1717111-what-s-a-shortname), which AFAIK must be ASCII lowercase, as it is used as the subdomain:

https://github.com/squidfunk/mkdocs-material/blob/49bfe6e572a4b4001c5940be37ce5296ad207c1f/src/partials/integrations/disqus.html#L41

**Comment by ericdallo** [comment]
Thanks @squidfunk! 
I was able to [reproduce the print](https://emacs-lsp.github.io/lsp-mode/blog/2020/7.0-release/) above using `disqus: emacs_lsp`:

![image](https://user-images.githubusercontent.com/7820865/88481331-37848400-cf31-11ea-915d-8668e93ce632.png)

What is missing now to make Disqus work on this page?

**Comment by ericdallo** [comment]
@squidfunk, I forgot to setup Disqus for that site, thank you very much for your help, it works now :D
