### ISSUE TITLE
Can you support Hombrew install ?

### ISSUE THREAD

**Issue by liangjingkanji** [squidfunk/mkdocs-material#1839]
Not easy to use pip on the mac.

**Comment by squidfunk** [comment]
I think that doesn’t make much sense, as we would have to add all plugins and all extensions to Homebrew that Material depends on, as MkDocs will only search in its install locations.

When you install Python 3 via Homebrew, there should be no problems with `pip`. Also see the [troubleshooting guide](https://squidfunk.github.io/mkdocs-material/troubleshooting/)?

**Comment by liangjingkanji** [comment]
`pip install mkdocs-material`,  don't direct using `mkdocs -V`

**Comment by squidfunk** [comment]
Yes, you should just use `pip` to install Material for MkDocs. You might also try the official Docker image, if Python is causing you inconvenience.
