### ISSUE TITLE
I hope keep newline

### ISSUE THREAD

**Issue by liangjingkanji** [squidfunk/mkdocs-material#1840]
![image](https://user-images.githubusercontent.com/21078112/89101287-193aee80-d431-11ea-8940-934a6c79ebb7.png)

**Comment by squidfunk** [comment]
I don't understand your problem. Please use the issue template and provide enough information so we can help you.

**Comment by liangjingkanji** [comment]
I want to keep multiple blank lines.

**Comment by squidfunk** [comment]
You can insert manual `<br>` tags or empty paragraphs to achieve that. `<p></p>`.

As this is a general Markdown question, it's not considered an _issue_ with this project. Please ask general Markdown questions on StackOverflow.
