### ISSUE TITLE
How to change background color of the code block

### ISSUE THREAD

**Issue by nabeelfahmi12** [squidfunk/mkdocs-material#1841]
how can i change the background color of the code blocks to black 
i have added also add extra css for that but it is not changing

**Comment by squidfunk** [comment]
It can be done with custom/extra CSS. This is not a general support forum. Please ask your question on StackOverflow.

**Comment by squidfunk** [comment]
Additionally, there's a section in the documentation on how to customize the syntax theme:
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#custom-syntax-theme
