### ISSUE TITLE
Keep newline

### ISSUE THREAD

**Issue by liangjingkanji** [squidfunk/mkdocs-material#1843]
I hope keep newline,  It's a pain in the ass to write `<br>` every time.

Can you add a markdown_extension property support this feature?

`Content Tab` require `four space` to render.  But not support `Tab`,  This is  trouble

I using Typora edit document for `mkdocs`

![image](https://user-images.githubusercontent.com/21078112/89126893-18cb5200-d51c-11ea-9ec4-db05c2d86f92.png)

**Comment by squidfunk** [comment]
This project provides _a template_ for MkDocs and not extensions to Markdown. It just displays Markdown in a specific and opinionated way. You're free to customize it the way you like by following the documentation which provides _a lot_ of examples, or use something else if it doesn't fit your use case.

Furthermore, please stop creating issues.
