### ISSUE TITLE
Lookup of source facts no longer works with GitHub organisation

### ISSUE THREAD

**Issue by wragge** [squidfunk/mkdocs-material#1864]
## Description

If `repo_url` points to a GitHub organisation no source facts are retrieved. Looking in the js console, there's a 404 error as the theme is requesting the organisation name from the GitHub `repos` endpoint

### Expected behavior

The number of repositories belonging to the organisation should be displayed under the repository name. This is what happened in earlier versions.

### Actual behavior

No source facts are displayed.

### Steps to reproduce the bug

1. Set `repo_url` to a GitHub organisation url

### Package versions

* Python: 3.8.2
* MkDocs: 1.1.2
* Material: 5.5.5

**Comment by squidfunk** [comment]
You're right, this got lost somehow in the v5 rewrite and is definitely a bug. Should be quite easy to fix, though.

**Comment by squidfunk** [comment]
Turns out, it's only a bug in the regex. The second capturing group missed a `?`.

**Comment by squidfunk** [comment]
Released as part of 5.5.6.

**Comment by crazy-max** [comment]
@squidfunk I just noticed that the repo stats [are no longer displayed (stars, forks)](https://crazy-max.github.io/diun/). Is this related to this change?

![image](https://user-images.githubusercontent.com/1951866/90632909-b14c1c80-e214-11ea-8cb9-6da8bc406ce5.png)

**Comment by squidfunk** [comment]
The results from the GitHub API call are persisted in session storage (not local storage), so it's per browser tab/session. If you open and close your browser too often, you get 429ed by GitHub 😅

**Comment by crazy-max** [comment]
Yeah I need to calm down :sweat_smile:
