### ISSUE TITLE
Add Nokogiri to "Users" section of README?

### ISSUE THREAD

**Issue by iBug** [squidfunk/mkdocs-material#1868]
First of all, great theme!

I wonder if [nokogiri][1] has ground in your README as an open-source project. It's the de-facto standard HTML/XML library in Ruby, and is used by *almost every* piece of software related in this area, including [Ruby on Rails][3] (`#1` web framework in Ruby) and [Jekyll][4] (*the* website generator behind GitHub Pages). It's also available in Debian from package `ruby-nokogiri`. From all aspects I can tell, it's a famous open-source project and has been an essential piece of the OSS industry.

The website (and documentation) of Nokogiri is located at <https://nokogiri.org/>.

  [1]: https://github.com/sparklemotion/nokogiri
  [2]: https://nokogiri.org/
  [3]: https://rubyonrails.org/
  [4]: https://jekyllrb.com/

**Comment by squidfunk** [comment]
Sure, care to submit a PR? Please adhere to the alphabetical order ☺️
