### ISSUE TITLE
Multiline equation in Admonition blocks

### ISSUE THREAD

**Issue by zyc-ai** [squidfunk/mkdocs-material#1873]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Multiline equation in the `align` does not render properly in admonition blocks. 

### Expected behavior

formula

### Actual behavior

```
<span><span class="MathJax_Preview">\begin{align}
\Vert \theta x_1 + (1 - \theta) x_2 - x_c \Vert_2 &amp;= 
\Vert \theta (x_1 - x_c) + (1 - \theta) (x_2 - x_c) \Vert_2 \\ &amp;=
\theta \Vert x_1 - x_c \Vert_2 + (1 - \theta) \Vert x_2 - x_c \Vert_2 \\ &amp;= 
r
\end{align}</span><script type="math/tex">\begin{align}
\Vert \theta x_1 + (1 - \theta) x_2 - x_c \Vert_2 &= 
\Vert \theta (x_1 - x_c) + (1 - \theta) (x_2 - x_c) \Vert_2 \\ &=
\theta \Vert x_1 - x_c \Vert_2 + (1 - \theta) \Vert x_2 - x_c \Vert_2 \\ &= 
r
\end{align}
```

### Steps to reproduce the bug

```
$$\begin{align}
\Vert \theta x_1 + (1 - \theta) x_2 - x_c \Vert_2 &= 
\Vert \theta (x_1 - x_c) + (1 - \theta) (x_2 - x_c) \Vert_2 \\ &=
\theta \Vert x_1 - x_c \Vert_2 + (1 - \theta) \Vert x_2 - x_c \Vert_2 \\ &= 
r
\end{align}$$
```

### Package versions

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`

Python 3.7
mkdocs 1.1.2
mkdocs-material 5.5.0

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: Windows 10 20175
* Browser: Chrome 86.0.4236.0

**Comment by squidfunk** [comment]
Could you please provide a screenshot that shows the actual behavior?

**Comment by zyc-ai** [comment]
> Could you please provide a screenshot that shows the actual behavior?

![image](https://user-images.githubusercontent.com/28757366/90474144-3670fc00-e157-11ea-8bc2-aca91247f727.png)

Actually it is a little bit more complicated... If there's equation only, it works fine...

> Also, how did you set up MathJax? Are you using MathJax 3?
I'm using python-markdown-math 0.7

**Comment by squidfunk** [comment]
Then please provide a reproducible example. You only provided the equation in the original post.

**Comment by squidfunk** [comment]
Please follow the guide in the docs. We currently do not support other methods:
https://squidfunk.github.io/mkdocs-material/reference/mathjax/

**Comment by squidfunk** [comment]
My tests show it works with the method outlined in the documentation:

Example:

``` markdown
!!! tip

    Lorem ipsum dolor sit amet

    $$\begin{align}
    \Vert \theta x_1 + (1 - \theta) x_2 - x_c \Vert_2 &= 
    \Vert \theta (x_1 - x_c) + (1 - \theta) (x_2 - x_c) \Vert_2 \\ &=
    \theta \Vert x_1 - x_c \Vert_2 + (1 - \theta) \Vert x_2 - x_c \Vert_2 \\ &= 
    r
    \end{align}$$

    Lorem ipsum dolor sit amet

!!! tip

    $$\begin{align}
    \Vert \theta x_1 + (1 - \theta) x_2 - x_c \Vert_2 &= 
    \Vert \theta (x_1 - x_c) + (1 - \theta) (x_2 - x_c) \Vert_2 \\ &=
    \theta \Vert x_1 - x_c \Vert_2 + (1 - \theta) \Vert x_2 - x_c \Vert_2 \\ &= 
    r
    \end{align}$$

```

Result:

<img width="704" alt="Bildschirmfoto 2020-08-18 um 20 09 17" src="https://user-images.githubusercontent.com/932156/90549402-c1211d80-e18e-11ea-9e74-e5273b252da6.png">

Closing. Please follow the documentation.

**Comment by zyc-ai** [comment]
> My tests show it works with the method outlined in the documentation:
> 
> Example:
> 
> ```gfm
> !!! tip
> 
>     Lorem ipsum dolor sit amet
> 
>     $$\begin{align}
>     \Vert \theta x_1 + (1 - \theta) x_2 - x_c \Vert_2 &= 
>     \Vert \theta (x_1 - x_c) + (1 - \theta) (x_2 - x_c) \Vert_2 \\ &=
>     \theta \Vert x_1 - x_c \Vert_2 + (1 - \theta) \Vert x_2 - x_c \Vert_2 \\ &= 
>     r
>     \end{align}$$
> 
>     Lorem ipsum dolor sit amet
> 
> !!! tip
> 
>     $$\begin{align}
>     \Vert \theta x_1 + (1 - \theta) x_2 - x_c \Vert_2 &= 
>     \Vert \theta (x_1 - x_c) + (1 - \theta) (x_2 - x_c) \Vert_2 \\ &=
>     \theta \Vert x_1 - x_c \Vert_2 + (1 - \theta) \Vert x_2 - x_c \Vert_2 \\ &= 
>     r
>     \end{align}$$
> ```
> 
> Result:
> 
> <img alt="Bildschirmfoto 2020-08-18 um 20 09 17" width="704" src="https://user-images.githubusercontent.com/932156/90549402-c1211d80-e18e-11ea-9e74-e5273b252da6.png">
> 
> Closing. Please follow the documentation.

Can you try
```
!!! important "Positive Definite"

    $$\mathbb{S}^n_{++} = \{X \in \mathbb{S}^n \mid X  \succ 0\}$$
```
