### ISSUE TITLE
Feature request: Nested nav items in Home with tabs feature enabled

### ISSUE THREAD

**Issue by grbd** [squidfunk/mkdocs-material#1879]
__I checked that...__

- [ X] ... the documentation does not mention anything about my idea
- [ X] ... to my best knowledge, my idea wouldn't break something for other users
- [ X] ... there are no open or closed issues that are related to my idea

## Description

Hi,
This might not be possible I'm not sure

Let's say I'm using the mkdocs material theme and I've enabled the tabs feature
```
theme:
  name: material
  features:
    - tabs
```

Now for the Home tab / page it doesn't seem to be possible to have nested pages / directories in the nav bar
This makes sense since every other Tab is a directory in the root of the docs directory where Home lives

I was wondering if it was possible to pull the navigation / sub pages for the Home tab from a subdirectory such as /Home/
So that it would be possible to have nested nav items on the Home Tab page
Hopefully this makes sense.

### Use Cases

With the tabs feature enabled, allow for nested pages on the Home tab

### Screenshots / Mockups

So with something like this for example

![image](https://user-images.githubusercontent.com/8965579/90984935-4c742780-e570-11ea-9a8e-b6c65f1c0542.png)

Allow for nested pages by picking them up from some place such as /Home/
![image](https://user-images.githubusercontent.com/8965579/90984959-79c0d580-e570-11ea-95ab-57e2bc4bd737.png)

I did hunt around for a workaround for this but couldn't find an easy way to do this unless I'm missing something. Perhaps there's a way to override the nav entries for a specific page in the meta somehow.

**Comment by squidfunk** [comment]
Already possible. Pleas read „top-level sections“ at:
https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs

**Comment by grbd** [comment]
Ok, thanks for the reply
