### ISSUE TITLE
Disabled search plugin still deploys "lunr" files

### ISSUE THREAD

**Issue by aimeos** [squidfunk/mkdocs-material#1886]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Is there a possibility to avoid deployment of search related JS files like lunr files, etc. when search plugin is disabled using `plugins: []`?

### Use Cases

We have disabled the search plugin and use an external search service but there are a lot of search related files deployed in the
`assets/javascripts/lunr/` directory which we don't need.

**Comment by squidfunk** [comment]
Nope, nothing Material for MkDocs can fix. MkDocs will copy all theme files on build. You can, however, remove them with a simple post-build step.

**Comment by aimeos** [comment]
OK, thanks a lot for your time and work!
