### ISSUE TITLE
Proposal: concept for a new (additional) layout

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#1906]
This is a concept for the Insiders [Carribean Red](https://squidfunk.github.io/mkdocs-material/insiders/#caribbean-red) tier, which will include a new vertical layout. I want to collect some feedback before implementation, so we get the best out of it. The code bar on the right will probably be optional - it will be implemented as a feature flag, so documentation and code can be read side-by-side. On smaller screens, the code will be rendered as it is now – inline with the documentation.

![Concept](https://user-images.githubusercontent.com/932156/92324938-b0095500-f046-11ea-896a-2720f6aeafb5.png)

Feel free to throw in some ideas, feedback, critique ... anything that's on your mind! I'll update the concept as we gravitate towards a final design proposal

**Comment by Stephen-Gates** [comment]
Wondering if this will be equivalent of [Slate](https://github.com/slatedocs/slate) for documenting APIs? Slate sites appear as one long page, e.g. [Consumer Data Right Standard site](https://consumerdatastandardsaustralia.github.io/standards/#introduction) (with one big index.md).

Would the code scroll as you scrolled the centre panel, or do they scroll independently?

**Comment by squidfunk** [comment]
Yes, it's a little like slate. The basic idea is to lay out the code next to the content, but not on a single long page but multiple pages.

**Comment by squidfunk** [comment]
I'm closing this for now. I think it needs a little more iteration. I'll try to draft something up 😊

**Comment by mshimonov** [comment]
Hey @squidfunk, I think this would be a great view for some. See an example from postman API which is an API documentation and tracking tool here: [developer.travefy.com](https://developer.travefy.com/). 

Now, obviously there's has more tailored functionality as it is directly geared towards documenting API's, but I know that we use mkdocs for both UI/UX documentation + technical documentation in my company, see [code.kx.com](code.kx.com).

I'd be keen to see this roll-out. 

One item that would be particularly interesting would be to have some pages in 1 column (as is today) and others in 2 column (this split layout proposal). The 1 column being used for general documentation while the 2 being used for API documenting.

**Comment by squidfunk** [comment]
Thanks for the feedback! I'm still evaluating the use cases for this possible new layout. The postman docs also look pretty nice. Alternate layouts per page are definitely possible and will be supported if we go down this path.

**Comment by fenik17** [comment]
A couple of other examples with the same three column layout:
https://www.twilio.com/docs/usage/api
https://stripe.com/docs/api/subscriptions/create

**Comment by Stephen-Gates** [comment]
Really like the way the [Stripe example](https://stripe.com/docs/api/subscriptions/create) scrolls.

**Comment by caseyrfsmith** [comment]
This would solve a problem for my team, for sure. We need API reference in this format, but want to use Material for our regular dev guides. This would keep me from having to run a slate site and a mkdocs site. I'm open (read: desperate for) other solutions.

**Comment by squidfunk** [comment]
@caseyrfsmith thanks for the feedback! Unfortunately, until further notice, work on the new layout has been discontinued due to a lack of resources and time. I try to invest the time I have into improving the current layout.
