### ISSUE TITLE
Search function should go to first result by pressing enter

### ISSUE THREAD

**Issue by matefriedl** [squidfunk/mkdocs-material#1915]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Currently the search features requires users to select a result with either the arrow key or the mouse. Then press enter to accept that result. I propose that when using search, the first result will be selected/highlighted by default. Pressing enter would take you this result right away. So to sum it up:

1. Bring up search
2. Type in your search terms
3. ~~Use the arrow keys to select the first result~~ **Have it selected automatically**
4. Hit enter to go to first result

### Use Cases

Having to operate the arrow keys less often will reduce strain on the users right wrist.

**Comment by Stephen-Gates** [comment]
I like this idea but am not sure about the look of highlighting the first result. It does make the selection explicit but would be happy with something more subtle.

**Comment by squidfunk** [comment]
I guess we could just omit the highlighting and follow the result, as it's more or less like the "feeling lucky" behavior of Google. `Enter` is currently not assigned in the input field and the only thing I could think of would be to chose a keyword suggestion (which might be another feature coming up in Insiders), but I'd rather assign that to `Arrow Right`.

**Comment by squidfunk** [comment]
This feature was just added to [Insiders](https://squidfunk.github.io/mkdocs-material-insiders/) today. [Try it here](https://squidfunk.github.io/mkdocs-material-insiders/)!

![Ohne Titel](https://user-images.githubusercontent.com/932156/95684440-1eb37280-0bf2-11eb-8767-861a53e8a38b.gif)

Pressing <kbd>Enter</kbd> when in the search input field will always follow the result with the highest score.

**Comment by devakker** [comment]
That is really cool. Functionally, it's just the way I imagined it.

Just a suggestion/remark: we should consider telegraphing this feature to the user more clearly. I think the result you will jump to by pressing `Enter` could use a selection highlight:

![image](https://user-images.githubusercontent.com/9056849/95711412-029be980-0c63-11eb-867a-637b28ac655b.png)

**Comment by matefriedl** [comment]
That is really cool. Functionally, it's just the way I imagined it.

Just a suggestion/remark: we should consider telegraphing this feature to the user more clearly. I think the result you will jump to by pressing `Enter` could use a selection highlight:

![image](https://user-images.githubusercontent.com/9056849/95711412-029be980-0c63-11eb-867a-637b28ac655b.png)

**Comment by squidfunk** [comment]
Thanks for the feedback. I don't know whether that would confuse users more than it would help, because it's not always the page title which has the highest score. For example, searching for "suggestions" will show "Setting up site search" at the top, but this page only has a score of ~3, while the section "Search suggestions" has a score of 3000. Thus, the section must be highlighted, which would lead to confusion.
