### ISSUE TITLE
Add an identifying `class` to the page's edit link to make it easier to hide when rendering to PDF

### ISSUE THREAD

**Issue by dimrozakis** [squidfunk/mkdocs-material#1920]
__I checked that...__

- [x] ... the documentation does not mention anything about my idea
- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... there are no open or closed issues that are related to my idea

## Description

Please consider adding an identifying class to the page's edit link (the one with the pencil icon).

https://github.com/squidfunk/mkdocs-material/blob/9da3d25c0772717168debda40faf035d904b8275/src/base.html#L304-L310
### Use Cases

I'm working with a fork of https://github.com/comwes/mkpdfs-mkdocs-plugin to render the site to a single PDF. I'd like to be able to manipulate the links for editing pages (pencil icon) via either CSS or preprocessing of the HTML that goes into the PDF in order to be able to hide them entirely or have them appear differently in the PDF. The lack of some identifying `class` specifically for that link makes any such attempt quite fragile. If the link had a `class` of say `edit-page` it'd be much easier to find that element using beautifulsoup and remove the element or treat it in some other specific manner.

Such identifying classes could probably come handy for any other UI elements that are inserted into the article content, but for the time being it's only the edit link I'm having an issue with.

**Comment by squidfunk** [comment]
Thanks for reporting. As it's currently unclear what will happen to the edit buttons, I'm not sure whether I want to introduce something that will be removed (or moved somewhere else) in one of the next releases. Furthermore, there's also the [deprecated source link button](https://squidfunk.github.io/mkdocs-material/deprecations/#source-link) rendered next to the edit button, which will be removed in Material 6:

For the time being, you can just use `.md-content__button`, as those will target the exact buttons at the top of the article.

**Comment by dimrozakis** [comment]
@squidfunk thanks for your response, I'll use `.md-content__button` for now.

**Comment by squidfunk** [comment]
Great! Can we close this issue then?

**Comment by dimrozakis** [comment]
Sure. I had considered using `.md-content__button` myself, but was worried it could have some other unintended side effect such as also hiding elements introduced inside the article content by markdown extensions and other plugins. I took your suggestion to use that class as an implicit reassurance that it's unlikely for such a problem to occur, in which case I'm fine with closing this.
