### ISSUE TITLE
Add back the default mkdocs theme

### ISSUE THREAD

**Issue by ajcollett** [squidfunk/mkdocs-material#1954]
__I checked that...__

- [X] ... the documentation does not mention anything about my idea
- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... there are no open or closed issues that are related to my idea

## Description

So, I can understand the rational for removing the mkdocs base theme, but, it's not easy to add back without basically redoing what work you have already done. 

My question is, does it make the image that much smaller that it's important to have removed?

I tried to just re-install the mkdocs pip package, but this requires packages that have been removed (like gcc). 

### Use Cases

I use this image to deploy user webpages at a University. Some do not like the Material theme, and prefer the MKdocs default one. If MKdocs had an official image, I'd use that, but they don't. 

So, before I go and role my own for this use case, can I please request that the decision to remove the mkdocs default theme be reconsidered?

Failing that, can you suggest a simple way for me to use the docker image and easily add the theme back? Could I simply clone it from github? (Since git is installed in the image).

**Comment by squidfunk** [comment]
Removing the `mkdocs` and `readthedocs` theme reduces the packed (!) size of the Docker image by 10MB, which is quite substantial. As the Docker image is used a lot in CI/CD, this reduction contributes to a few seconds saved on every CI/CD run, which may add up quickly. I understand your use case, but there are tons of MkDocs Docker images, which include all of the themes, more plugins etc. The official Material for MkDocs image will not support any other themes from 6.0 on.

I don't know an easy way of adding the theme back, as the contents of the MkDocs package are removed. Extending the image and a forced reinstall might help, though:

```
pip install --upgrade --force-reinstall mkdocs
```

**Comment by ajcollett** [comment]
Thanks for the quick reply. Always a pleasure. 

I understand about the image size. 

I will then begin to publish a bunch of images internally, that either build off of mkdocs-material, or are built from scratch. To put it plainly, I don't trust any of the other docker images, simply because they aren't necessarily maintained by someone with incentive to keep them up to date. :-P I'll build a pipeline that runs daily to pull in the latest from mkdocs/material and work from there. 

To respond to the last point, I tried that, but it complained that GCC wasn't installed. Which is ok, I can just include this in my build process. 

Thanks again.
