### ISSUE TITLE
Creating top nav menu and left hand nav with expand and collapse option

### ISSUE THREAD

**Issue by NavyaG-lab** [squidfunk/mkdocs-material#1970]
Hi,

Is it possible to have top nav menu and the toc on the left hand can be expandable or collapse? I've tried to add both but I am getting error that indentation isn't right.

I checked if there are any threads on this, but couldn't really find one.

For example:

I want to have:
On the top nav bar: Home  Developer docs User docs   What's    new
I should be able to define the left hand toc for each top menu items. And the left side toc should be

- Data
  - Data users
    - Data on ETL

Where **Data** and **Data users** will have expandable option next to it.

**Comment by squidfunk** [comment]
Yes, that's possible. Have you read the section on [navigation tabs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs)? It explains this in detail.
