### ISSUE TITLE
404 on https://fonts.gstatic.com

### ISSUE THREAD

**Issue by Baltazardoung** [squidfunk/mkdocs-material#1971]
Several parts of code include links to https://fonts.gstatic.com that return an 404.

```html
<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin />
```

![image](https://user-images.githubusercontent.com/13434663/95307455-f261c400-0888-11eb-8e38-5beb46039146.png)

**Comment by squidfunk** [comment]
This is a common technique employed for faster font loading:
https://www.cdnplanet.com/blog/faster-google-webfonts-preconnect/

**Comment by Baltazardoung** [comment]
I did not know this technique. Thank you for this information :) ... I will therefore adapt my tests accordingly.

So I close this issue,
