### ISSUE TITLE
Support for Jupyter Notebooks

### ISSUE THREAD

**Issue by rakesh4real** [squidfunk/mkdocs-material#1975]
Hi, Instead of using .md files can we use jupyter notebooks as well?

**Comment by squidfunk** [comment]
Closing, as it doesn't conform to the issue guideline. This is not an issue with this project, but a [question](https://github.com/squidfunk/mkdocs-material/blob/master/.github/ISSUE_TEMPLATE/config.yml). Please ask it on the [official Gitter channel](https://gitter.im/squidfunk/mkdocs-material) or on [StackOverflow](https://stackoverflow.com).
