### ISSUE TITLE
How can I create a home page like the website of mkdocs-material?

### ISSUE THREAD

**Issue by shenruisi** [squidfunk/mkdocs-material#1977]
Is it possible to create a home page at the first tab like the website https://squidfunk.github.io/mkdocs-material/  using material mkdocs ?

**Comment by squidfunk** [comment]
Closing, as it doesn't conform to the issue guideline. This is not an issue with this project, but a [question](https://github.com/squidfunk/mkdocs-material/blob/master/.github/ISSUE_TEMPLATE/config.yml). Please ask it on the [official Gitter channel](https://gitter.im/squidfunk/mkdocs-material) or on [StackOverflow](https://stackoverflow.com).
