### ISSUE TITLE
Steps to creating a similar homepage

### ISSUE THREAD

**Issue by asriley** [squidfunk/mkdocs-material#1996]
Hello, 

Firstly thank you all for the contributions! This theme really is amazing and elegant! 

I have been trying to follow the code here: https://github.com/squidfunk/mkdocs-material/blob/master/material/base.html
for creating my own homepage on my material themed mkdocs site. However, the auto-generated nature of the base.html, index.html and home.html leave me wondering if I can actually do this after a few failed attempts now. 

I have used these sources: 
https://www.mkdocs.org/user-guide/styling-your-docs/ and 
https://squidfunk.github.io/mkdocs-material/customization/. 

However, neither source (nor them together) actually really inform me about how to extend my current index.md file to be something like this: https://squidfunk.github.io/mkdocs-material/. 

I can find nothing about this on youtube or within search engines. *Just not sure what steps to take to create my own index.md as a nice templated homepage...*

Misc Info: 
Mkdocs version: `mkdocs, version 1.1.2 from /usr/local/lib/python3.8/site-packages/mkdocs (Python 3.8)`
My project is hosted on bitbucket and not github. 
I am not a web developer. 

Any help will be appreciated.

**Comment by squidfunk** [comment]
This is something I've wanted to add [some documentation](https://github.com/squidfunk/mkdocs-material/blob/0067197a36dee1ad230b5824cc854e96380448a3/mkdocs.yml#L169) on, but haven't had the time yet. I'll leave this open as a reminder when there's some time for lower priority stuff.

**Comment by asriley** [comment]
Martin, 

That would be great! I like markdown but one of the setbacks is that it doesnt seem easy to create a homepage that is unlike the other pages. Will be looking forward to it! 
Let me know if there is any way I can help! Would love to if possible.

**Comment by tmeuze** [comment]
@asriley This is the file you are looking for: [overrides/home.html](https://github.com/squidfunk/mkdocs-material/blob/master/material/overrides/home.html). You'll want to copy it over to your own overrides directory. Make sure you've set your `custom_dir` in `mkdocs.yml`:
```
theme:
  custom_dir: docs/overrides
...
```

In the front matter of your `index.md`, you need to specify the template to use:
```
---
title: Title
template: home.html
---

```
One important thing that took me a while to realize: you **need** a newline at the end of your md file. If you don't have one, the content will not display. I guess it's processed as having null content if you don't include the newline.

**Comment by Guts** [comment]
You can also have a look to others website like [UP42](https://sdk.up42.com/):

![image](https://user-images.githubusercontent.com/1596222/97801308-0a382800-1c3c-11eb-82d4-c0eb1ff8d389.png)

Source: https://github.com/up42/up42-py

Ping @Arnaud-UP42 and @chrieke.

**Comment by squidfunk** [comment]
So, in the end, I decided to close this issue, as enough guidance should've been given by https://github.com/squidfunk/mkdocs-material/issues/1996#issuecomment-718247120 – it all boils down to using a custom template for a specific page, as noted in the comment, and providing the implementation for this template.

**Comment by exequielrafaela** [comment]
Thanks for all your feedback here, it was really useful for us too 🙏🏼 💯 👏🏼 

As a gesture of gratitude we add our 2 cents:

- ✅ ⛵ [Binbash Leverage - Example](https://leverage.binbash.com.ar/)
- ✅ 👨🏼‍💻 [Source](https://github.com/binbashar/le-ref-architecture-doc/)
- ✅❓ [StackOverflow Q](https://stackoverflow.com/questions/63438788/how-to-add-a-landing-page-to-a-mkdocs-doc-site-using-mkdocs-material/66240880#66240880)

**Comment by asriley** [comment]
> @asriley This is the file you are looking for: [overrides/home.html](https://github.com/squidfunk/mkdocs-material/blob/master/material/overrides/home.html). You'll want to copy it over to your own overrides directory. Make sure you've set your `custom_dir` in `mkdocs.yml`:
> 
> ```
> theme:
>   custom_dir: docs/overrides
> ...
> ```
> 
> In the front matter of your `index.md`, you need to specify the template to use:
> 
> ```
> ---
> title: Title
> template: home.html
> ---
> ```
> 
> One important thing that took me a while to realize: you **need** a newline at the end of your md file. If you don't have one, the content will not display. I guess it's processed as having null content if you don't include the newline.

Hello, wow I did not realize there was a reply here! I am following your exact suggestions - but am getting this error: 

ERROR   -  Error building page 'index.md': overrides/main.html 
overrides/main.html. 

I added both a main.html  and home.html to the overrides directory (just copied and pasted from material's site to try to get past this error but no luck). Additionally I added a main.html file in my docs directory as I see alot of other people have done that. I think there are still some missing steps. For example: 

1.  @exequielrafaela 's   custom_dir is material and not the overrided directory. Not sure why it was changed and still works. 
2. Also, a lot of these pages are "autogenerated". Therefore, I am confused about what
 should be done to "generate" these auto pages? (base.html, main.html, etc...) Will "mkdocs serve" cause this to happen? 

![Screen Shot 2021-06-04 at 5 54 22 PM](https://user-images.githubusercontent.com/20747325/120870265-1b447100-c55e-11eb-913f-e97d6dd1330b.png)

![Screen Shot 2021-06-04 at 5 56 31 PM](https://user-images.githubusercontent.com/20747325/120870321-39aa6c80-c55e-11eb-9ae7-791ae9465937.png)

![Screen Shot 2021-06-04 at 6 01 32 PM](https://user-images.githubusercontent.com/20747325/120870601-f56b9c00-c55e-11eb-8546-af0910c4d33c.png)

**Comment by exequielrafaela** [comment]
@asriley In my case it still works because I declare that in the `mkdocs.yml` as follows:

```
theme:
  name: material
  custom_dir: material
```

Consider that the `overrides` folder is already implicitly declared since (I understand) is the default name it looks for in the `custom_dir`. So you can use any directory as long as it's properly declared in your `mkdocs.yml`

I've followed @tmeuze instructions and everything worked as expected. And dont's forget to check this 👇🏼 

> You need a newline at the end of your md file. If you don't have one, the content will not display. I guess it's processed as having null content if you don't include the newline.

**Comment by Fatih20** [comment]
> @tmeuze
> 
> > @asriley This is the file you are looking for: [overrides/home.html](https://github.com/squidfunk/mkdocs-material/blob/master/material/overrides/home.html). You'll want to copy it over to your own overrides directory. Make sure you've set your `custom_dir` in `mkdocs.yml`:
> > ```
> > theme:
> >   custom_dir: docs/overrides
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the front matter of your `index.md`, you need to specify the template to use:
> > ```
> > ---
> > title: Title
> > template: home.html
> > ---
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > One important thing that took me a while to realize: you **need** a newline at the end of your md file. If you don't have one, the content will not display. I guess it's processed as having null content if you don't include the newline.
> 
> Hello, wow I did not realize there was a reply here! I am following your exact suggestions - but am getting this error:
> 
> ![Screen Shot 2021-06-04 at 6 10 47 PM](https://user-images.githubusercontent.com/20747325/120871069-40d27a00-c560-11eb-8e95-035a37b6e108.png)
> 
> I added both a main.html and home.html to the overrides directory (just copied and pasted from material's site to try to get past this error but no luck). Additionally I added a main.html file in my docs directory as I see alot of other people have done that. I think there are still some missing steps. For example:
> 
> 1. @exequielrafaela 's   custom_dir is material and not the overrided directory. Not sure why it was changed and still works.
> 2. Also, a lot of these pages are "autogenerated". Therefore, I am confused about what
>    should be done to "generate" these auto pages? (base.html, main.html, etc...) Will "mkdocs serve" cause this to happen?
> 
> ![Screen Shot 2021-06-04 at 5 54 22 PM](https://user-images.githubusercontent.com/20747325/120870265-1b447100-c55e-11eb-913f-e97d6dd1330b.png)
> 
> ![Screen Shot 2021-06-04 at 5 56 31 PM](https://user-images.githubusercontent.com/20747325/120870321-39aa6c80-c55e-11eb-9ae7-791ae9465937.png)
> 
> Just using squid's home.html and main.html until I get past this error.
> ![Screen Shot 2021-06-04 at 6 01 32 PM](https://user-images.githubusercontent.com/20747325/120870601-f56b9c00-c55e-11eb-8546-af0910c4d33c.png)

I'm having the exact same error. Did you manage to get past it?

**Comment by chrimaho** [comment]
Hi @squidfunk,

Love the library! Thanks!

I've been able to follow the instructions on this issue, and can successfully implement a home page for my site. Thanks!

Even so, I still think that there is value in adding a page to your master docs (like you mentioned [here](https://github.com/squidfunk/mkdocs-material/issues/1996#issuecomment-711140352)). 
If I can draft up some changes and push it to you as a Pull Request, would you still consider it as a possible addition to your site?

Just thinking out aloud, it may include some changes such as:
- Some (_super basic_) HTML templates in the [`.overrides`](https://github.com/squidfunk/mkdocs-material/tree/master/material/.overrides) directory
- Maybe a new HTML variable to pull through the `site_name` and `site_description` from the `mkdocs.yml` file and render it on the HTML template.

Before I commence working on this, I just wanted to check to see what you think?

Thanks!

\- Chris M

**Comment by squidfunk** [comment]
@chrimaho I'm currently not considering adding demo customizations to the repository. We've started building [a new repository with examples](https://github.com/mkdocs-material/examples), which is where such things should live. It's not ready yet, but it will contain examples for all (?) features from the documentation, which can also include customizations.

**Comment by valhuber** [comment]
@squidfunk 

I share the interest in creating a landing / hero unit page, as discussed here.  I am uncertain whether your intent to publish a new repo with examples will include this...?

On this page, a file often cited is https://github.com/squidfunk/mkdocs-material/blob/master/material/overrides/home.html, but it's gone.  That makes me uncertain whether to plow through this to try to get a landing hero.

On [this page](https://github.com/squidfunk/mkdocs-material/discussions/3946), it appears that the expectation is that to get a landing-hero you need to become a sponsor.  Is that correct?

**Comment by squidfunk** [comment]
The source code of the landing page _cannot be released_ due to [licensing restrictions](https://github.com/squidfunk/mkdocs-material/discussions/3946#discussioncomment-2809299). Thus, yes, you would need to become a sponsor if you would want the source code of our own landing page. I'm sorry, but there's no way around this. Other than that, we'll consider providing additional landing page templates in the future.

**Comment by squidfunk** [comment]
FWIW, our old landing page is here (`overrides` was renamed to `.overrides` at some point):
https://github.com/squidfunk/mkdocs-material/blob/master/src/.overrides/home.html

**Comment by tylerdotrar** [comment]
If there's anyone still struggling with this, I made a fairly simple and straightforward template based on the [up42-py](https://sdk.up42.com/) project (as pointed out in @Guts comment ) that also supports modification via the `mkdocs.yml` configuration file.

Project found here: https://github.com/tylerdotrar/mkdocs-coverpage
- The style won't be to everyone's taste, but it should at least be a decent enough baseline for customization.

**Comment by Guts** [comment]
Thanks @tylerdotrar for sharing and making a customizable homepage :clap:

**Comment by valhuber** [comment]
Let me add my thanks to @tylerdotrar as well.

This works fine. but is there a way to have markdown content follow the banner?  I see you can add html, but I have quite a lot of md content I want to add...

**Comment by gabrielbdornas** [comment]
> This works fine. but is there a way to have markdown content follow the banner? I see you can add html, but I have quite a lot of md content I want to add...

@valhuber have you found the answer to this question? I'm using the @tmeuze [suggestion](https://github.com/squidfunk/mkdocs-material/issues/1996#issuecomment-718247120), and it is working just fine, but I want to add the `index.md` file content just beside the banner.

**Comment by horizon365** [comment]
> FWIW, our old landing page is here (`overrides` was renamed to `.overrides` at some point): https://github.com/squidfunk/mkdocs-material/blob/master/src/.overrides/home.html

can't open it. 404 - page not found

**Comment by squidfunk** [comment]
@horizon365 we've redone our home page. The overrides are currently hosted in Insiders. Also see:

- https://github.com/squidfunk/mkdocs-material/discussions/7390

**Comment by mendax1234** [comment]
> This is something I've wanted to add [some documentation](https://github.com/squidfunk/mkdocs-material/blob/0067197a36dee1ad230b5824cc854e96380448a3/mkdocs.yml#L169) on, but haven't had the time yet. I'll leave this open as a reminder when there's some time for lower priority stuff 😊

Is this still open now? @squidfunk as I have seen that the insider feature is free for all now, may I ask about the landing page information? seems that I still cannot find it in the mkdocs-material documentation.

**Comment by squidfunk** [comment]
Thanks for asking. We haven't released the parallax animation due to copyright on the original images. Material for MkDocs still has no template that you can easily customize for a landing page. We'll fix this in [Zensical](zensical.org/) in 2026 ☺️

**Comment by mendax1234** [comment]
> Thanks for asking. We haven't released the parallax animation due to copyright on the original images. Material for MkDocs still has no template that you can easily customize for a landing page. We'll fix this in [Zensical](zensical.org/) in 2026 ☺️

Hi martin @squidfunk ! Thanks a lot for your reply! I am trying hard to mimicing the landing page style for the mkdocs-material website but have got no progress since yesterday. May I ask if it is still possible for me to join the insiders? If not, would u mind sending me a copy of the latest mkdocs-material-insiders repository (or just the parts that are related to the landing page?). I understand the copyright thing that you mentioned, but as I thought for now all the insiders have the access to it while mkdocs-material has decided that all the insider's features are available for community, so I think maybe it will also be okay to just send me a copy of the source code? I will just try to mimic the style and replace all the images with mine on my website.

(Sry, if this offends anyone, let me know and I will be happy to wait for another year for Zensical to have this awesome feature !)

Thank you very much!
