### ISSUE TITLE
Disable horizontal scrolling in code blocks

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [squidfunk/mkdocs-material#2007]
- [X] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

## Description

The horizontal scrolling of code blocks decreases usability because you can't visually grasp the entire content at the same time. It forces you to look through a tiny view and scroll horizontally while only being able to see a small portion of the code at a time.

### Use Cases

Reading code, especially terminal commands where line breaks are unimportant or less important.

#### Now (bad)
![output](https://user-images.githubusercontent.com/17473656/97097378-f1de7100-166f-11eb-9dce-e5af48de09e7.gif)
#### Old (good) (was standard with mkdocs-material 4.x)
![bla](https://user-images.githubusercontent.com/17473656/97097408-47b31900-1670-11eb-878d-76c480e956d1.png)

### Possible Solutions
* allow default doc-wide value for horizontal scrolling (prefered)
* allow setting similar to line numbers to be settable for each code block

#### optional
Instead of horizontal scrolling add visual indicators when lines have been broken to fit into a code window, like so:
![sdf-10-25_03:24:19](https://user-images.githubusercontent.com/17473656/97097519-a3ca6d00-1671-11eb-885e-afe00af506a9.png)

**Comment by facelessuser** [comment]
I've used Material for a long time. It has always had horizontal scrolling as far back as I remember. With that said, you can easily add some custom CSS to allow wrapping if desired. This could easily with nothing but CSS and existing Python Markdown plugins. This could be done in such a way to be site wide or trigger on a specific class added to specific code blocks to give per code block control.

I won't comment on whether scrolling is better or not as I think it is quite subjective. I think it could be argued for some cases that wrapping could be more appropriate than at other times, but again, it is a matter of preference.

With how easy it is to customize, I'm not sure if Material would need to specifically address this.

**Comment by squidfunk** [comment]
As @facelessuser pointed out, this behavior was never changed. Also, you can change it with [2-3 lines of CSS](https://stackoverflow.com/questions/41238148/how-to-line-wrap-long-lines-inside-markdown-code-blocks-in-githubgitlab), so it doesn’t really make sense to add this as a feature. See the customization guide for how to add extra CSS.

Additionally, showing icons in front of wrapping lines is not possible with CSS 😕

**Comment by squidfunk** [comment]
Closing for the reasons stated.

**Comment by PanCakeConnaisseur** [comment]
Hm OK, I guess I had changed this myself and forgotten about it. Still think it would be better to offer this as an option to people, since scrolling in a tiny windows is really bad UX IMHO.
