### ISSUE TITLE
Expert Mode

### ISSUE THREAD

**Issue by axdotl** [squidfunk/mkdocs-material#2024]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Provide functionality to access _Expert Mode_ which provides more detailed documentation.

### Use Cases

* Audience with different experience level
* Audience with different scope

#### Example

We're using _mkdocs-material_ to document our internal service landscape. These documentation has readers with different experience levels and furthermore with different roles. 
This means most of the documentation is targeted to any developer/ engineer. But some parts are only of interest for Site-Reliability-Engineers. Currently this is solved by "role-specific" chapters, but this interrupts the continuous reading experience for all readers. Because developers needs to _ignore_ parts of the documentation or SREs has to jump within the document.

Idea is to provide a mechanism (e.g. a toogle button) to enable more detailed content (can be paragraphs or whole chapters).
As a result every audience got a clean documentation with all related content and a continuous reading experience.

### Screenshots / Mockups

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for your feature suggestion. While I think that this may be a viable use case, it's probably too specific for the average user. It's the first request of this kind I've seen so far. Furthermore, the mechanics of content visibility may be too versatile to boil them down to a generic approach.

Given that this is too specific, I don't see any chance to implement this in my spare time. However, if you need it nonetheless, no problem – I'm also available as a freelancer and would be happy to assist you. Just drop me a message and we can discuss rates.

**Comment by squidfunk** [comment]
Closing for the reasons stated.
