### ISSUE TITLE
Proposal: Data Table Highlighting Options

### ISSUE THREAD

**Issue by tmeuze** [squidfunk/mkdocs-material#2028]
- [X] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

## Description

Currently, Data Tables will show a highlight effect over a row on hover. I would like to request the ability to configure this in some manner, so as to be able to highlight columns instead, or disable highlighting altogether. I'm not sure if this is possible, but if so, I'd like to propose adding these options natively. 

### Use Cases

A simple use case for this would be a pricing table, or a feature table - wherein pricing/feature tiers are aligned on the X axis instead of the Y axis. Implementing such with the current row highlighting behavior may confuse the user. The current workaround is to flip the axes. 

### Screenshots / Mockups

If X is the highlighting effect:

Current Behavior:
| T1 | T2 | T3 |
| --- | --- | --- |
| X | X | X |
| - | - | - |
| - | - | - |

(Proposed) Column Highlighting:
| T1 | T2 | T3 |
| --- | --- | --- |
| X | - | - |
| X | - | - |
| X | - | - |

(Proposed) No Highlighting:
| T1 | T2 | T3 |
| --- | --- | --- |
| - | - | - |
| - | - | - |
| - | - | - |

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for your feature suggestion. Highlighting is implemented with CSS, so it's quite easy to customize the behavior by adding some [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css). More specifically, you'd just need to override this rule to remove the highlighting and add your own to customize it the way you want it:

https://github.com/squidfunk/mkdocs-material/blob/7c1ffcee955d6ea68ffb6a433e203b01f7c45374/src/assets/stylesheets/main/_typeset.scss#L551-L555

It doesn't really make sense to add a feature here, as it's easy to achieve with customization, is CSS-only and different use cases may need different ways to highlight.

**Comment by facelessuser** [comment]
This may be possible one day with the `nth-col` selector, but no browsers have implemented it yet.

Outside of that, it could maybe be done with JavaScript. TBH, this really sounds like something you could do with extra JavaScript and CSS. Not sure Material should add a feature specifically for something like this IMHO. There will always be little stylistic preferences people will have, and it would be troublesome to add feature toggles for each when it can easily be achieved with a little extra JS and CSS via the mkdocs config.

**Comment by tmeuze** [comment]
Agreed, shouldn't be a feature if it's easily customizable. Thank you for pointing me in the right direction. 

Take care,
