### ISSUE TITLE
How to include extra CSS with theme extension

### ISSUE THREAD

**Issue by seanmadsen** [squidfunk/mkdocs-material#204]
I'm extending Material for use on a site that will be hosting several dozen books. I have a directory within my custom publishing system that I'm using to store "theme extension" files (like partials) which override some of Material's settings when I run `mkdocs` with the `--theme-dir` option. This is great.

Now I want to add some custom CSS to my theme extension, but I'm having trouble. At first, I thought that if I put a CSS file like `custom.css` in my `theme-dir` directory, this CSS would be incorporated into the build. Wrong. It seems that the files in `theme_dir` only get built when they are overriding existing theme files, not when they are adding something new. Bummer.

I've gotten the custom CSS to work by automatically adding the `extra_css` setting within each book's `mkdocs.yml` file during publishing. But this approach is quite cumbersome for the following reason: the `extra_css` setting doesn't copy the css files and incorporate them into the build, it just adds a `<link>` element to the built html which loads the specified path. This is intuitive if the CSS is stored within the book, but not intuitive if the CSS is stored somewhere else (outside the book), and not even possible if that "somewhere else" is outside of the web-accessible directory of my app. I'm able to get this to work by storing my extra CSS separately from my theme extension, but this just feels like a hack. I wonder if there's a better way. 

Is there a way I can get new CSS within a "theme extension" of Material to show up in the built site?

**Comment by seanmadsen** [comment]
Oooo I figured it out! Full steps: 

1. Make a directory, which we'll call `<theme-dir>`. It can be anywhere.
1. Add `extra.css` in `<theme-dir>/assets/stylesheets/` with custom style of your choosing.
1. Add `main.html` in `<theme-dir>` with the following content. 
    ```html
    {% block extrahead %}
      <link rel="stylesheet" href="{{ base_url }}/assets/stylesheets/extra.css">
    {% endblock %}
    ```
1. Build the site with the `--theme-dir <theme-dir>` option supplied to `mkdocs`.

**Comment by squidfunk** [comment]
Simply using `extra_css` did not work? The thing with `extra_css` is - it has to live in your docs folder, or some folder relative to the docs folder that is accessible by the webserver serving it.

**Comment by seanmadsen** [comment]
Well, setting `extra_css` in `mkdocs.yml` *did* work (as long as the file I used was accessible by the webserver, like you say). But for my use case this strategy wasn't that great, because I wanted to use one directory outside of the book files (and inaccessible from the webserver) to store the theme extensions files (including the partials, and the extra CSS) which would be applied to many different books during `mkdocs build`. The steps listed above got me there and meant that (1) I didn't have to change `mkdocs.yml` at all, and (2) I could keep all the theme extension files together and living within my sources of my book-builder app, outside of any web accessible directory. 

Perhaps this is an uncommon use case. 

But in any case, I'm all set, and I think it's okay to close this issue.

**Comment by squidfunk** [comment]
I see, so you want to link to some external CSS, but don't want to include it in the `docs` directory, because MkDocs would automatically copy it and make it part of the documentation build. You want a way where you can link to a file that MkDocs doesn't resolve, because it lies outside of the project, but want to include it anyway. This is a very specific use case. Please see #206 for my opinion on this topic.
