### ISSUE TITLE
Adding links in header and nav sidebar for returning to home page

### ISSUE THREAD

**Issue by osresearch** [squidfunk/mkdocs-material#2044]
- [X] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

## Description

It seems the only way to return to the home page for a site is by clicking on the site icon since only the image is linked; the `config.site_name` is in the title bar is static text: https://github.com/squidfunk/mkdocs-material/blob/master/material/partials/header.html#L22
```
    <div class="md-header-nav__title" data-md-component="header-title">
      {% if config.site_name == page.title %}
        <div class="md-header-nav__ellipsis md-ellipsis">
          {{ config.site_name }}
        </div>
      {% else %}
        <div class="md-header-nav__ellipsis">
          <span class="md-header-nav__topic md-ellipsis">
            {{ config.site_name }}
          </span>
          <span class="md-header-nav__topic md-ellipsis">
            {% if page and page.meta and page.meta.title %}
              {{ page.meta.title }}
            {% else %}
              {{ page.title }}
            {% endif %}
          </span>
        </div>
```

Nor is the site name linked in the navigation side bar: https://github.com/squidfunk/mkdocs-material/blob/master/material/partials/nav.html#L10

```
  <label class="md-nav__title" for="__drawer">
    <a href="{{ site_url }}" title="{{ config.site_name | e }}" class="md-nav__button md-logo" aria-label="{{ config.site_name }}">
      {% include "partials/logo.html" %}
    </a>
    {{ config.site_name }}
  </label>
```

### Use Cases

The name of the site in the title bar is a much larger target to hit for returning to the home page and many sites use both their logo as well as the name for a "return to home" functionality.  Linking it in the nav side bar also makes sense since it is the "top" of the navigation hierarchy.

**Comment by squidfunk** [comment]
Thanks for your suggestion. IMHO the button with its 40x40 pixels should be a large enough target to hit, at least Lighthouse is not complaining regarding accessibility. If we'd wrap the name in the title bar (i.e. "Material for MkDocs" for the official docs) in a link, it would indeed increase the surface area for large screens. However, on small screens, tapping onto the header is more or less expected to take you to the top of the page (at least on iOS). As the title bar is very narrow on iOS Safari, the user might miss the title bar and tap onto the header link, taking him to the home page. Furthermore, there would be two links, the icon in the sidebar and the title bar both taking the user to the homepage. For that reason, your proposed solution doesn't cater well to all screen sizes.

Nonetheless, you have three options:

- You can [override the header partial](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials) and wrap the title in a link
- You could use some [additional JavaScript](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript), intercept `click` events, and redirect via JavaScript
- You could use navigation tabs and add a "Home" tab, exactly as done in the official docs (see screenshot)

---

<img width="343" alt="Bildschirmfoto 2020-11-09 um 16 02 20" src="https://user-images.githubusercontent.com/932156/98558351-9afaad80-22a5-11eb-998c-5a62736e58a2.png">

**Comment by osresearch** [comment]
Thanks for the pointer to the partials directory.  I copied the stock header and nav files into`custom/partials/header.html` and `custom/partials/nav.html`, and then added links with this patch:
```
commit 966633c4a0c10378dfa07284cb8cbffd09c44db2
Author: Trammell hudson <hudson@trmm.net>
Date:   Mon Nov 9 17:42:47 2020 +0100

    patch header and nav partials to link back to home page

diff --git a/custom/partials/header.html b/custom/partials/header.html
index 07707ab..c0678cc 100644
--- a/custom/partials/header.html
+++ b/custom/partials/header.html
@@ -21,7 +21,9 @@
       {% else %}
         <div class="md-header-nav__ellipsis">
           <span class="md-header-nav__topic md-ellipsis">
-            {{ config.site_name }}
+            <a href="{{ site_url }}" title="{{ config.site_name | e }}" aria-label="{{ config.site_name }}">
+              {{ config.site_name }}
+            </a>
           </span>
           <span class="md-header-nav__topic md-ellipsis">
             {% if page and page.meta and page.meta.title %}
diff --git a/custom/partials/nav.html b/custom/partials/nav.html
index 1d6cef7..2c02555 100644
--- a/custom/partials/nav.html
+++ b/custom/partials/nav.html
@@ -10,7 +10,7 @@
     <a href="{{ site_url }}" title="{{ config.site_name | e }}" class="md-nav__button md-logo" aria-label="{{ config.site_name }}">
       {% include "partials/logo.html" %}
     </a>
-    {{ config.site_name }}
+    <a href="{{ site_url }}" title="{{ config.site_name | e }}">{{ config.site_name }}</a>
   </label>
   {% if config.repo_url %}
     <div class="md-nav__source">
```

**Comment by squidfunk** [comment]
Awesome!

**Comment by AmebaBrain** [comment]
@squidfunk 
Navigation by clicking on icon or explicit `Home` link to navigate to the root of a _current_ site is absolutely ok. But documentation is usually written for some product.

It would be nice to have a possiblity to inject into header bar one more link which will navigate to the product page itself.

I have a product site hosted at `https://example.com`. I have documentation hosted at `https://example.com/docs`. When I need to quickly come back to documentation root - I use either icon, or explcitly added `Home` section.

But suppose I read the docs and now want to switch back to the product site, to check what I just read in documentation?
Having one more link on a header bar for it would be nice. Ideally, in a configurable manner.

**Comment by squidfunk** [comment]
> It would be nice to have a possiblity to inject into header bar one more link which will navigate to the product page itself.

Sure! You can [override `header.html` partial](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials) to fit it to your needs. "Adding one more link to the header" is certainly not something we can make configurable, because use cases are hard to generalize here.
