### ISSUE TITLE
Preload/Prefetch of google Roboto font

### ISSUE THREAD

**Issue by pvilas** [squidfunk/mkdocs-material#2046]
Hi,

This is not exactly a mkdocs issue but I think I would be interesting to talk about it.

On a fresh installation, the lighthouse tool reported that the loading of the Roboto fonts took 2,3s and they were **blocking** the whole rendering of the page. The performance index of the main page was 75.  I'm not very sure of the true nature of the problem but I have worked on a solution and I would share here in order to have more opinions.

As the only font used on the main page is the *regular* one it seems that we can serve this font from the local server and prefetch the others for a later moment. 

I have changed the *fonts* block as:

```
{% block fonts%}
<link rel="preload" href="/stylesheets/regular.css"  as="style">
<link rel="stylesheet" href="/stylesheets/regular.css">
<link rel="prefetch" href="/stylesheets/fonts.css"  as="style">
<link rel="stylesheet" href="/stylesheets/fonts.css">
{% endblock %}
```

I have [downloaded](https://google-webfonts-helper.herokuapp.com/fonts) the fonts and created two css files, one for the regular (preload) and other with the rest (prefetch). 

regular.css looks as:

```
@font-face {
    font-family: 'Roboto';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: url('/stylesheets/fonts/roboto-v20-latin-regular.eot'); /* IE9 Compat Modes */
    src: local('Roboto'), local('Roboto-Regular'),
         url('/stylesheets/fonts/roboto-v20-latin-regular.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
         url('/stylesheets/fonts/roboto-v20-latin-regular.woff2') format('woff2'), /* Super Modern Browsers */
         url('/stylesheets/fonts/roboto-v20-latin-regular.woff') format('woff'), /* Modern Browsers */
         url('/stylesheets/fonts/roboto-v20-latin-regular.ttf') format('truetype'), /* Safari, Android, iOS */
         url('/stylesheets/fonts/roboto-v20-latin-regular.svg#Roboto') format('svg'); /* Legacy iOS */
  }
```

Now, **the performance index of the main page is 97!** although I have a warning on the console, 

```
The resource https://movimiento-animal.es/stylesheets/regular.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally. 
```

I have used [this site](https://movimiento-animal.es) for testing (in spanish). 

What are your thoughts about?

**Comment by squidfunk** [comment]
Thanks for your suggestion! IMHO we have `font-display: swap` in place, which indicates that the browser shouldn't block and use the fallback font until the desired font is resolved. It's weird that Lighthouse reports it. As I'd understand it, you would only be preloading the CSS file, not the font itself. To me, this sounds more like a false positive in Lighthouse.

@coliff if you find some time, as far as I recall you've done quite some benchmarking for font loading.

**Comment by squidfunk** [comment]
I came to the conclusion that at the current time, this is not worth exploring. This is clearly an optimization that is not easy to generalize without losing the flexibility in defining custom fonts through `mkdocs.yml`. For this reason, it's something that has to be done by the developer, after settling on a font. For this reason, I'm closing this issue.
