### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by YiannisGkoufas** [squidfunk/mkdocs-material#2047]
Tried both firefox and chrome and it renders the website like this:

![image](https://user-images.githubusercontent.com/16906312/99066169-6a19c180-25a0-11eb-8ea5-d779ebf62fa3.png)

By the way, it's an awesome tool. :)

**Comment by rowild** [comment]
Confirmed.

**Comment by squidfunk** [comment]
There seems to be something wrong with the build... Working on it...

**Comment by squidfunk** [comment]
So it turns out that dependabot, again, upgraded the `ignore-emit-webpack-plugin` which still doesn't work with Webpack 4. [I now told dependabot to ignore the dependency](https://github.com/squidfunk/mkdocs-material/pull/2041#issuecomment-726717366). Hopefully this won't happen again.

**Comment by YiannisGkoufas** [comment]
Awesome! thanks @squidfunk
