### ISSUE TITLE
Don't render a permalink for first H1 (Markdown syntax)

### ISSUE THREAD

**Issue by danierutu** [squidfunk/mkdocs-material#2049]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Assuming that pages only have one H1 header (for the main title), if that title is set in the file metadata, the `toc` extension won't show a permalink for it:

```md
---
title: My awesome page
---
Some content

## Sub-section
Some other content
```

However, if the H1 header uses the regular Markdown syntax, it'll have a permalink:

```md
# My awesome page
Some content

## Sub-section
Some other content
```

I think that having a permalink for the title header is redundant, so it'd be cool if there was an option to remove it.

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting. In general, I agree. However, the main headline needs to have an `id` (thus permalink), so the skip-to-content link works as expected:

![Ohne Titel](https://user-images.githubusercontent.com/932156/99191776-2628e700-276f-11eb-9350-63d56b9121c9.gif)

You can hide the Permalink with some CSS – probably:

``` css
.md-typeset h1 .headerlink {
  display: none;
}
```

**Comment by danierutu** [comment]
Just tested it, and works like a charm! Thanks a lot!
