### ISSUE TITLE
Feature Request: Image viewer when linking bigger images, maybe a lightbox or simply a modal

### ISSUE THREAD

**Issue by KerimG** [squidfunk/mkdocs-material#2053]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

I would like to suggest a simple lightbox/modal style image viewer for viewing high resolution images directly from within MkDocs. 

Out of necessity, we have full-screen screenshots in our docs and the downsizing makes most of the text impossible to read. Currently, our workaround is to right-click on the image and open it in a new tab where it is shown in full size. 

A way to click on the image and then show a modal with the full-size image would be appreciated. 

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by martinbira** [comment]
It's pretty easy to do yourself actually. I use the `attr_list` extension to add custom classes to images, then a small JS snippet that intercepts clicks on those class elements and opens the image in a modal.

**Comment by KerimG** [comment]
@martinbira Oh cool. I'll check it out, thank you. 

I will leave the FR open, because I think it's reasonable default behavior.

**Comment by squidfunk** [comment]
There were some lightbox requests and I agree with @martinbira – there are hundreds of implementations, which you can add with some JavaScript 😊 If we chose one implementation, somebody will want another.
