### ISSUE TITLE
Add this github project to label `static-site-generator`

### ISSUE THREAD

**Issue by guettli** [squidfunk/mkdocs-material#2054]
I think it makes sense to add this github project to [static-site-generator](https://github.com/topics/static-site-generator)

**Comment by squidfunk** [comment]
Technically, this project is a theme for a SSG, but not an SSG itself 😉 what upside would we have adding it?

**Comment by squidfunk** [comment]
Thought about it - this is not an SSG 😉Closing.

**Comment by guettli** [comment]
> what upside would we have adding it?

It would make your project more visible. I was searching for a SSG and looked at this list: https://github.com/topics/static-site-generator to find a tool. Just by chance I came across your project, otherwise I would have missed it.
