### ISSUE TITLE
Google Analytics with New Tag Format

### ISSUE THREAD

**Issue by menbren** [squidfunk/mkdocs-material#2055]
Hi!

Thanks for the awesome theme!

Quick one, I couldn't get the build-in Google Analytics support to work with Google's new tag format (G-GXXXXXXXXX).
I was able to get it to work using an override, but I thought you might wanted to know.

Cheers,
Menno

**Comment by squidfunk** [comment]
Thanks for reporting. Could you share some more details (i.e. the "why" and your solution), so we can decide whether we should address this? ☺️

**Comment by menbren** [comment]
Of course! So I was trying to setup Analytics as described [here](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/). It mentions you need to provide the following info:
```
google_analytics:
  - UA-XXXXXXXX-X
  - auto
```
Only, Google has changed to structure of its tags for Google Analytics 4 (GA4). They are now formatted as G-GXXXXXXXXX. But if I enter such a tag, it doesn't automatically generate a functional analytics script. My guess is, the theme doesn't support the new tag structure yet.

**Comment by squidfunk** [comment]
Thanks for providing more details. So this demands the use if Google Tag manager? If so, please see https://github.com/squidfunk/mkdocs-material/issues/1972#issuecomment-706375807

**Comment by menbren** [comment]
Not tag manager in particular. When you currently go to Google Analytics and you add a new property, the only tag that you are given by default is this new GA4 tag now. I believe they have sort of integrated/unified these tags.

It appears to me as they are phasing out the UA-XXXXXXXX-X formatted tags in favour of these newly formatted G-GXXXXXXXXX tags.

**Comment by squidfunk** [comment]
Could you share your override? That would make it much simpler for me to integrate.

**Comment by menbren** [comment]
Sure, I've put this in the main.html

```
{% extends "base.html" %}

<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() {
        dataLayer.push(arguments);
    }
    gtag('js', new Date());
    gtag('config', 'G-XXXXXXXXXX');
</script>
{% endblock %}
```

**Comment by squidfunk** [comment]
I see. This, however, is `gtag.js`, which we won't switch to right now for the reasons stated in the linked comment. Unless there's a solution, which is based on `analytics.js`, I'd postpone this until Google improved/modularized `gtag.js` or `analytics.js` is not available anymore. It really is a bait-and-switch, see the comment I linked before. 

For everybody else coming here – if you need this, you can use this code as a [custom analytics](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#other-analytics-providers) override.

**Comment by nvuillam** [comment]
Would it be possible to add a "step by step" tuto in the documentation ?
I'm sure most of new users (including me) needs to do it, and it would avoid that the same question would be asked again :)

**Comment by nemchik** [comment]
Just found this thread while looking things up after responding here https://github.com/squidfunk/mkdocs-material/issues/1972#issuecomment-743767157

As stated in my other comment it seems like google no longer allows new users to sign up for google analytics without using v4, which no longer provides a UA-#####. Existing users are being sent emails urging them to upgrade, and once you upgrade to v4 you loose your UA-##### and are assigned a new G-ABC123 which appears to be incompatible with gtags.

So currently all users who do not have a pre-existing UA-##### will be forced to use an override for the template. While it's great that this functionality is available it's unfortunate that the bar is set slightly higher in this scenario.

Thinking about it: would it be possible to have both? Meaning leave `analytics.js` in place and usable when users setup
```yaml
google_analytics:
  - UA-#####
  - auto
```
but introduce a new
```yaml
gtags:
  - G-ABC123
  - auto
```
for those who have upgraded or are new?

**Comment by squidfunk** [comment]
I’d consider this to be a good candidate for an upstream change that would need to be addressed as part of MkDocs, as this theme solely consumes the properties set through `mkdocs.yml`.  The best idea may be to open an issue over at the upstream repo if the GA change is irreversible, since it will concern all themes, not only this one.

**Comment by nvuillam** [comment]
Meanwhile... maybe a quick tuto ? Most of us do not want/care to extend the theme, just use it simply, + activate Google Analytics, so I'm convinced a "step by step" instructions set would be very appreciated by a lot of users of this great repository :)

**Comment by squidfunk** [comment]
I haven't received any mails from Google yet regarding the depreciation - care to write a guide? We can collaborate on a PR to get something up in the docs.

**Comment by nvuillam** [comment]
I want the guide for myself haha ^^

**Comment by nemchik** [comment]
here https://github.com/TRaSH-/Guides/pull/57/files
and here https://github.com/nemchik/nemchik/compare/c06c7cc51dfdc2ca54e2b5f1adecf2c81bf62952...master

In both cases I am using `navigation.instant`. if you are not then you can skip the javascript extras and use what was posted above https://github.com/squidfunk/mkdocs-material/issues/2055#issuecomment-730974196

**Comment by nemchik** [comment]
> I’d consider this to be a good candidate for an upstream change that would need to be addressed as part of MkDocs, as this theme solely consumes the properties set through `mkdocs.yml`. The best idea may be to open an issue over at the upstream repo if the GA change is irreversible, since it will concern all themes, not only this one.

Hopefully I've described this well enough https://github.com/mkdocs/mkdocs/issues/2252

**Comment by nvuillam** [comment]
@nemchik  many many thanks for your PR link, that was all I needed :)

https://github.com/nvuillam/mega-linter/pull/155

**Comment by th0mk** [comment]
@nemchik Your implementation is broken in version 7.0 of mkdocs-material. 

Most likely related to the [changes to overrides](https://squidfunk.github.io/mkdocs-material/upgrading/#changes-to-html-files).

**Comment by nemchik** [comment]
> @nemchik Your implementation is broken in version 7.0 of mkdocs-material.
> 
> Most likely related to the [changes to overrides](https://squidfunk.github.io/mkdocs-material/upgrading/#changes-to-html-files).

Looks like the changes needed to resolve the issue are actually because `app.location$.subscribe` changes to `location$.subscribe` which is now documented here https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#other-analytics-providers (the change isn't called out, but the new way to do it is documented). So a commit like this should fix the issue.
https://github.com/nemchik/nemchik/commit/71dcbfa47091da22eb7e002d8bb57c449c5c5f5f#diff-345aa1c0dd357fc2ce4eba286da0c84b0a6b6c97096f72cbf3c8c213a2accd72

**Comment by nemchik** [comment]
I should note that my current method (after reviewing the above) is no longer to use an override for the analytics block but instead only use an extra javascript that looks like this

```js
var gtag_id = "G-ABC123";

var script = document.createElement("script");
script.src = "https://www.googletagmanager.com/gtag/js?id=" + gtag_id;
document.head.appendChild(script);

location$.subscribe(function (url) {
  window.dataLayer = window.dataLayer || [];

  function gtag() {
    dataLayer.push(arguments);
  }

  gtag("js", new Date());
  gtag("config", gtag_id);
});
```

**Comment by Mistic92** [comment]
Hi, are there any update for using Google Analytics 4?

**Comment by squidfunk** [comment]
Nope, still waiting for https://github.com/mkdocs/mkdocs/issues/2252.

**Comment by sirchampsblanc** [comment]
It looks like it was merged yesterday:

https://github.com/mkdocs/mkdocs/commit/80feaf03a42dacdd0740259b647014d5f0f9d839

Great news!

**Comment by squidfunk** [comment]
Yes, that's great news. We can start working on it as soon as MkDocs 1.2 is out.

**Comment by squidfunk** [comment]
`gtag.js` support just landed in `master` and will be released soon. Feedback appreciated Now, both formats are supported.

__Google Analytics__

``` yaml
extra:
  analytics:
    provider: google
    property: UA-XXXXXXXX-X
```

__Google Analytics 4__ (via `gtag.js`)

``` yaml
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
```

**Comment by stevejr** [comment]
@squidfunk - Would you be able to give an ETA for the new release that supports the above? Thanks.

**Comment by squidfunk** [comment]
I want to collect some feedback before, so if you or someone could test the new GTAG integration, we can move forward. I don't use GTAG and have only tested it with a demo account with success, but YMMV.

**Comment by nemchik** [comment]
I seem to be having some issues with mkdocs 1.2 (which I assume is required in order for the new gtag changes here to work?)

Ref: https://github.com/mkdocs/mkdocs/issues/2447#issuecomment-856813431

If mkdocs 1.2 is not required I'd just want to know how to install mkdocs-material with these new changes. Right now I'm just installing with `mkdocs-material==7.1.7` in my `requirements.txt`

**Comment by stevejr** [comment]
GTAG aside, can we use the new layout i.e. `config.extra.analytics.provider` for the existing GA property with the latest release? 

I use the `--strict` flag to verify the docs build ok and it is failing as MkDocs now emits a warning to say that the config flag `google_analytics` is deprecated and will be removed.

**Comment by squidfunk** [comment]
Yes, as soon as the changes are released. As I wrote in my comment above, both configurations are from now on supported.

**Comment by squidfunk** [comment]
> I seem to be having some issues with mkdocs 1.2 (which I assume is required in order for the new gtag changes here to work?)

No, MkDocs 1.12 will work as-well, except you won't be seeing a deprecation notice when still using the old `google_analytics` configuration variable. You can install from `master`with:

```
pip install git+https://github.com/squidfunk/mkdocs-material
```

**Comment by nemchik** [comment]
> You can install from `master`with:
> 
> ```
> pip install git+https://github.com/squidfunk/mkdocs-material
> ```

Can I put `git+https://github.com/squidfunk/mkdocs-material` in `requirements.txt` ?

**Comment by squidfunk** [comment]
Yes, that should work.

**Comment by nemchik** [comment]
> Yes, that should work.

Seems good. I only tested gtag, not analytics.
Commit: https://github.com/nemchik/nemchik/commit/bb92e238d0e307ad02b7c35b8696d578bbd6f1fa
CI log: https://github.com/nemchik/nemchik/runs/2776036708
mkdocs.yml lines: https://github.com/nemchik/nemchik/blob/bb92e238d0e307ad02b7c35b8696d578bbd6f1fa/mkdocs.yml#L12-L15
Deployed to: https://nemchik.com/

Everything looks like it worked.

**Comment by squidfunk** [comment]
7.1.8 was just released, which contains the changes.
