### ISSUE TITLE
HTML Datatable doesn't work 

### ISSUE THREAD

**Issue by adarshbm11** [squidfunk/mkdocs-material#2056]
I want to have HTML datatables without having to provide table id for every table.
https://datatables.net/examples/basic_init/multiple_tables.html

Nothing seems to work. Please help!

### Steps to reproduce the bug

1.  Code on my markdown
```html
<table id="" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Offices</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
        </tr>
        <tr>
            <td>Garrett Winters</td>
            <td>Accountant</td>
            <td>Tokyo</td>
        </tr>
        <tr>
            <td>Ashton Cox</td>
            <td>Junior Technical Author</td>
            <td>San Francisco</td>
        </tr>
        <tr>
            <td>Cedric Kelly</td>
            <td>Senior Javascript Developer</td>
            <td>Edinburgh</td>
        </tr>
        <tr>
            <td>Airi Satou</td>
            <td>Accountant</td>
            <td>Tokyo</td>
        </tr>
    </tbody>

</table>
```html

### Package versions

* Python: `Python 3.9.0`
* MkDocs: `mkdocs, version 1.1.2`
* Material: `Version: 6.1.5`

### Project configuration

<!-- Please provide your mkdocs.yml to a reasonable amount of detail -->

``` yaml
extra_css:
  - extra.css
  - https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css

extra_javascript:
  - https://code.jquery.com/jquery-3.5.1.min.js
  - https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js
  - scripts/site.js
```

### scripts/site.js
$(document).ready(function() {
    $('table.display').DataTable();
} );

* OS: Windows
* Browser: Chrome/ Firefox
  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by adarshbm11** [comment]
I want to have HTML datatables without having to provide table id for every table.
https://datatables.net/examples/basic_init/multiple_tables.html

Nothing seems to work. Please help!

**Comment by squidfunk** [comment]
If I understand correctly, you're having problems with some custom code. Unfortunately, we can't help you with that here, as the issue template already states. Please ask your question on a general support forum like StackOverflow.

**Comment by hayesall** [comment]
For future searchers who find this thread, I've added an answer [on StackOverflow](https://stackoverflow.com/questions/64925169/i-was-trying-to-implement-datatables-in-my-mkdocs-material-theme-but-adding-the/68513857).
