### ISSUE TITLE
Adding a landing pace

### ISSUE THREAD

**Issue by ehguille** [squidfunk/mkdocs-material#2057]
I've checked at `https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml` (line 170) that there is a commented link to a 'adding-a-landing-page' doc.

Is it going to be released? If not, it would be great to have any tutorial to do so.

**Comment by squidfunk** [comment]
Habe you seen #1996?

**Comment by Stephen-Gates** [comment]
Perhaps worth adding a simplified approach for Insiders? I also attempted this but couldn't get it to work.

**Comment by ehguille** [comment]
> Have you seen #1996?

I have, however I'm unable to remove the "For updates follow @squidfunk on  Twitter" announce.

**Comment by ehguille** [comment]
Anyway, I wasn't able to remove all those tags from home:

  | <meta content="summary_large_image" name="twitter:card"/>
  | <meta content="@squidfunk" name="twitter:site"/>
  | <meta content="@squidfunk" name="twitter:creator"/>

**Comment by squidfunk** [comment]
> Perhaps worth adding a simplified approach for Insiders? I also attempted this but couldn't get it to work.

@Stephen-Gates I thought about this a lot. The problem is: how? What you need to do is provide a custom template, and when providing that, you're on your own from there. We simply can't generate the page from plain Markdown, as the structure is non-linear. The landing page template overrides the following blocks which would all have to be populated from Markdown, which can only have a 1:1 mapping that currently is `content`:

- `extrahead` in `main.html`
- `announce` in `main.html`
- `tabs` in `base.html`
- `content` in `main.html`
- `footer` in `base.html`

Thus, I don't see any possibility except abusing the metadata extension and adding dozens of new options, i.e. implementing a template engine on top of metadata – impractical. If somebody comes up with an approach that can be achieved through configuration without adding dozens of parameters, I'm happy to discuss it! Other than that I'd be happy to learn how you would imagine such a _feature_ to look/feel from a user perspective. 

The easiest way to get up and running right now is: copy the [`overrides`](https://github.com/squidfunk/mkdocs-material/tree/master/src/overrides) folder from this repository and add it at the top level of your project + reference the `template` in [metadata of the landing page](https://github.com/squidfunk/mkdocs-material/blob/master/docs/index.md). Unfortunately, this project is "only" a template and we're stuck with MkDocs/Python Markdown possibilities. I'm already trying to monkey-patch stuff wherever possible so that some things are easier for users, but making custom templating "easy" and essentially no-tech, is a really hard nut.

**Comment by squidfunk** [comment]
@ehguille `overrides/home.html` extends from `overrides/main.html`, so you also need to override that template. In essence, the template chain is:

1. `base.html`
2. `main.html`
3. `overrides/main.html`
4. `overrides/home.html`

The reason for that is that the meta tags and announcement bar is shown on all pages + the home page includes the image and buttons.

**Comment by ehguille** [comment]
@squidfunk, check this:

*overrides/home.html* (just add the announce block and change the h1 content on tx-hero__content)

```html  linenums="1"

{% extends "overrides/main.html" %}


{% block announce %}
My text
{% endblock %}


{% block tabs %}
  {{ super() }}
  <style>.md-header{position:initial}.md-main__inner{margin:0}.md-content{display:none}@media screen and (min-width:60em){.md-sidebar--secondary{display:none}}@media screen and (min-width:76.25em){.md-sidebar--primary{display:none}}</style>
  <section class="tx-container">
    <div class="md-grid md-typeset">
      <div class="tx-hero">
        <div class="tx-hero__image">
          <img src="assets/images/illustration.png" alt="" width="1659" height="1200" draggable="false">
        </div>
        <div class="tx-hero__content">
          <h1>Works fine/h1>
          <p>{{ config.site_description }}. Set up in 5 minutes.</p>
          <a href="{{ page.next_page.url | url }}" title="{{ page.next_page.title | e }}" class="md-button md-button--primary">
            Quick start
          </a>
          <a href="{{ 'insiders/' | url }}" title="Material for MkDocs Insiders" class="md-button">
            Get dd
          </a>
        </div>
      </div>
    </div>
  </section>
{% endblock %}
{% block content %}{% endblock %}
{% block footer %}{% endblock %}
```

*overrides/main.html*: Just changed the block announce and the last <span> block (shouldn't impact this)

```html linenum=yes
{% extends "base.html" %}

{% block announce %}
Blah blah
{% endblock %}

{% block footer %}
<footer class="md-footer">
  {% if page.previous_page or page.next_page %}
    <div class="md-footer-nav">
      <nav class="md-footer-nav__inner md-grid" aria-label="{{ lang.t('footer.title') }}">
        {% if page.previous_page %}
          <a href="{{ page.previous_page.url | url }}" class="md-footer-nav__link md-footer-nav__link--prev" rel="prev">
            <div class="md-footer-nav__button md-icon">
              {% include ".icons/material/arrow-left.svg" %}
            </div>
            <div class="md-footer-nav__title">
              <div class="md-ellipsis">
                <span class="md-footer-nav__direction">
                  {{ lang.t("footer.previous") }}
                </span>
                {{ page.previous_page.title }}
              </div>
            </div>
          </a>
        {% endif %}
        {% if page.next_page %}
          <a href="{{ page.next_page.url | url }}" class="md-footer-nav__link md-footer-nav__link--next" rel="next">
            <div class="md-footer-nav__title">
              <div class="md-ellipsis">
                <span class="md-footer-nav__direction">
                  {{ lang.t("footer.next") }}
                </span>
                {{ page.next_page.title }}
              </div>
            </div>
            <div class="md-footer-nav__button md-icon">
              {% include ".icons/material/arrow-right.svg" %}
            </div>
          </a>
        {% endif %}
      </nav>
    </div>
  {% endif %}
  <div class="md-footer-meta md-typeset">
    <div class="md-footer-meta__inner md-grid">
      <div class="md-footer-copyright">
        {% if config.copyright %}
          <div class="md-footer-copyright__highlight">
            {{ config.copyright }}  <span id="compilacion"></span>
          </div>
        {% endif %}
        Made with
        <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank" rel="noopener">
          Material for MkDocs
        </a>
      </div>
      {% include "partials/social.html" %}
    </div>
  </div>
</footer>

  <span class="compilacion"><script type="text/javascript">
	  var fecha = document.lastModified;
	  var spanCompilacion=document.getElementById('compilacion');
	  spanCompilacion.appendChild( document.createTextNode('(última compilación el '+document.lastModified+')') );
  </script>
  </span>

{% endblock %}
```

Although the upper banner has been replaced for mine (the announcement, I mean), I still get this when looking at the html generated code:


<meta content="summary_large_image" name="twitter:card"/>

```html
  <meta content="@squidfunk" name="twitter:site"/>
  <meta content="@squidfunk" name="twitter:creator"/>
  <meta content="Programación" name="twitter:title"/>
  <meta content="My site description" name="twitter:description"/>
  <meta content="http://127.0.0.1:8000/assets/images/banner.png" name="twitter:image"/>
```

**Comment by squidfunk** [comment]
@ehguille you also need to override the `extrahead` block, as I listed in my previous comment:

https://github.com/squidfunk/mkdocs-material/blob/2524e11e7cbe8e74387a4ff6b8f0e82cc6875f5f/src/overrides/main.html#L25-L60

**Comment by ehguille** [comment]
Dammit, you're right :) Thanks a lot.

**Comment by squidfunk** [comment]
No worries! As already said, I know customization is hard for non-experienced users and I will think about how I can make it even easier, especially for Insiders. Until then, this and the linked issue should serve as a good starter.
