### ISSUE TITLE
Current tab detection breaks if the section has only subsections

### ISSUE THREAD

**Issue by oprypin** [squidfunk/mkdocs-material#2098]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

## Description

If tabbed navigation is enabled and a tab's nav items include only subsections, not any pages, then the tab may not be detected as active.

### Expected behavior

The current tab is highlighted
(which it is in this case, but only for the first subsection)

![image](https://user-images.githubusercontent.com/371383/101551036-a75f4c80-39b0-11eb-9432-69554f607914.png)

### Actual behavior

Selecting any item under the 2nd section onwards makes the tab not highlighted anymore

![image](https://user-images.githubusercontent.com/371383/101550951-7d0d8f00-39b0-11eb-8b92-2e7fb7ca5d21.png)

### Steps to reproduce the bug

```bash
mkdir -p docs/taba docs/taba/bar docs/taba/foo docs/tabb
touch docs/taba/bar/bar.md docs/taba/bar/barr.md docs/taba/foo/foo.md docs/taba/foo/fooo.md docs/tabb/b.md                                                                                    
cat >mkdocs.yml
```

### Package versions

* Python: 3.9.0
* MkDocs: 1.1.2 and https://github.com/mkdocs/mkdocs/tree/3e8b3481ff78afe866670af3a4acc60a6537487f
* Material: 6.1.6 and https://github.com/squidfunk/mkdocs-material/tree/3794eef4ffd281ccf49f2532e394f86c4094944a

### Project configuration

```yaml
site_name: Hmm
theme:
  name: material
  features:
    - navigation.tabs
```

### System information

* Browser: Firefox and Chromium

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting! As with #2060 and #2072, it makes the most sense to revisit and solve this problem when the new navigation features are merged into `master`.

**Comment by squidfunk** [comment]
This issue has been resolved as part of #2072. As https://github.com/squidfunk/mkdocs-material/issues/2072#issuecomment-744011149 explains, the bugfix will be released with the hit of the next Insiders funding goal. This is an exception to the usual policy of providing bugfixes for both editions, due to the fact that navigation has undergone a big refactoring. As I'd consider this to be a minor bug (i.e. wrong link color), it doesn't justify the effort of backporting the fix. I hope for your understanding - it shouldn't take more than a few weeks after all.

**Comment by squidfunk** [comment]
The funding goal has been reached and the respective features and fixes have just been merged from Insiders. The `master` is already up to date - watch out for a release.

**Comment by oprypin** [comment]
This is indeed fixed, thanks.
I would close this issue but not sure if that's the process that you're following.

**Comment by squidfunk** [comment]
I'm still trying to figure out whether we should start with a beta release – we'll close this issue when the fix is released.

**Comment by squidfunk** [comment]
6.2.1 was just released, which includes the fixes.
