### ISSUE TITLE
Capitalization in Table of Contents

### ISSUE THREAD

**Issue by reginapizza** [squidfunk/mkdocs-material#2101]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description
I believe that "Table of contents" should follow typical header capitalization rules and be "Table of Contents". Please let me know if this is preferred to be the way it currently is, it can definitely be changed with use of a custom theme but in most places that I've seen Table of Contents written it's been capitalized. I don't mind making a pull request for this as well if this change is desired.

### Expected behavior

"Table of Contents" with a capitalized C

### Actual behavior

"Table of contents" (C not capitalized)
![TableofContents](https://user-images.githubusercontent.com/50851526/101683423-ed5cf480-3a32-11eb-961b-9eab36a8abc2.png)

### Package versions

* Python: `3.8.3`
* MkDocs: `mkdocs, version 1.1 from /usr/lib/python3.8/site-packages/mkdocs (Python 3.8)`
* Material: `Version: 6.1.7`

### Project configuration

Happening in default configuration

### System information

* OS: Fedora 32
* Browser: Chrome

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for your suggestion. If we'd capitalize the title in the template (or translation, if you will), it would also make sense to capitalize all anchors rendered below it. This is, however, up to the user writing the documentation, so we have no way of enforcing this behavior from a template persective. I understand your argument, but I think this is a matter of taste and I don't want to impose this change (or restriction, depending on your viewpoint) on every user. If we change it, somebody else will want to have it changed back. This is at least what I've learned from the many years maintaining this project.

You can extend the theme and override the translation yourself, as this is the [very example which is outlined in the documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#custom-translations), or you can add some extra CSS to achieve what you want by setting `text-transform: capitalize` on the TOC, albeit that will also capitalize words like `of` and `the`.

**Comment by reginapizza** [comment]
@squidfunk thanks for the response, I completely understand and figured it was because of something like that but didn't see it explicitly stated anywhere in the repo when doing a quick check so figured I'd propose it. I'll just go ahead and close the issue then, thanks!
