### ISSUE TITLE
Can you add string "Type to start searching" to translate

### ISSUE THREAD

**Issue by ngtrian** [squidfunk/mkdocs-material#214]
## Description
Can you add support translate "Type to start searching" and "search results" in search to other language.

**Comment by squidfunk** [comment]
This is planned for 1.4.0 which will include an improved search interface.

**Comment by squidfunk** [comment]
Added i18n for search in #217 - can now be localized as described in the docs. Will be part of 1.4.0 which should be released shortly.

**Comment by squidfunk** [comment]
1.4.0 was just released.
