### ISSUE TITLE
🎊 Prairie Fire funding goal completed

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#2143]
Thanks to our awesome sponsors, the 'Prairie Fire' funding goal has been completed! This means the following features are released to the public:

- [x] Navigation sections
- [x] Navigation expansion
- [x] Hiding the sidebars
- [x] Table of contents in navigation
- [x] Header hides on scroll

Status of completion:

- [x] Merged all features into `master`
- [x] Updated documentation
- [x] Issued new release
- [x] Updated release notes

**Comment by jaceklaskowski** [comment]
I haven't figured out how to deploy the Insiders version to Github Pages yet so I'm glad I've got less things to work on since all the goodies are now part of the public version! 🥰

**Comment by squidfunk** [comment]
@jaceklaskowski have you tried the examples in the documentation? What did not work? Feel free to create an issue or discussion with some more details, so we can work it out 😊

**Comment by jaceklaskowski** [comment]
This is a low priority so didn't even bother to check out the docs 😎 Vielen Danke pour ton support! 😎

**Comment by squidfunk** [comment]
Everything has been released as part of 6.2.1! Note that there was a regression with import and asset paths due to a slipped-through update of the webpack-assets-manifest-plugin in 6.2.0. This has been corrected in 6.2.1.
