### ISSUE TITLE
Version dropdown render issues

### ISSUE THREAD

**Issue by Wolf2323** [squidfunk/mkdocs-material#2144]
- [X] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... ~~the problem doesn't occur with the default MkDocs template~~ MkDocs does not support mike nativly
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

## Description
We use the mike version dropdown from mkdocs material insiders and we have two problems:
1. We have the version `1.12.0-DEV` and that version has a linebreak in the dropdown.
2. The text of our navigation tabs is renderd over the version drop down istead of under it.

This screen shot shows it: https://cdn.discordapp.com/attachments/520942709205237760/790887319636410389/unknown.png

### Expected behavior
For Problem
1. The box may scale with the size of the version strings
2. The navigation tabs text should be below the dropdown

### Actual behavior
See Description
Live Demo: https://betonquest.github.io/BetonQuest/1.12.0-DEV/

### Steps to reproduce the bug

1. Use the Version selector
2. use mike and deploy a version like `1.12.0-DEV`
3. use mike to deploy a second and maybe a third version
4. Open the web page and try the version dropdown

### Package versions

* Python: `3.6`
* MkDocs: `1.1.2`
* Material: `6.1.7+insiders.1.13.1`

### Project configuration

https://github.com/BetonQuest/BetonQuest/blob/master/mkdocs.yml

### System information

* OS: Windows
* Browser: Chrome, Firefox, Edge

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Could you please post the content of the `versions.json` which `mike` generates? With this information, it should be straight-forward to fix.

**Comment by Wolf2323** [comment]
`[{"version": "1.12.0-DEV", "title": "1.12.0-DEV", "aliases": ["DEV"]}, {"version": "1.11", "title": "1.11", "aliases": ["RELEASE"]}]`
This is the original file: https://github.com/BetonQuest/BetonQuest/blob/gh-pages/versions.json

**Comment by squidfunk** [comment]
Fixed in the latest commit at Insiders:

<img width="423" alt="Bildschirmfoto 2020-12-22 um 14 12 14" src="https://user-images.githubusercontent.com/932156/102892149-c0133c00-445f-11eb-866a-1f5405182b4f.png">

A release is about to follow.

**Comment by squidfunk** [comment]
6.2.2-insiders-1.13.2 is out, which includs the fix.

**Comment by Wolf2323** [comment]
Thank you very mutch
