### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by RDIL** [squidfunk/mkdocs-material#2148]
- [X] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

It may be better to make builds (webpack ones specifically) reproducible.  This means that the hash shouldn't change every single rebuild, especially not when nothing has changed!  

Upgrading to webpack 5 should improve this (iirc).  

### Use Cases

Security, users are more confident when they know that malware can't be hidden somewhere in the JS bundle.
(I personally know its safe, but I also know there are entire teams of some larger companies who scour software all day just like this.)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting. The hashes are based on the contents if the files, so they shouldn't change. Could you explain which files you found to be affected?

**Comment by RDIL** [comment]
> Thanks for reporting. The hashes are based on the contents of the files, so they shouldn't change. Could you explain which files you found to be affected?

When I ran build locally without changing any of the file contents, the javascript assets changed in hash.

**Comment by squidfunk** [comment]
This is very likely related to a change in an upstream dependency that is covered by the semantic version range. For example, when `rxjs-7.0.0-beta.10` comes out, it's covered by the range we specified in `package.json`:

https://github.com/squidfunk/mkdocs-material/blob/afff64df990074b6f58b6d9ba539d273ff909344/package.json#L41

When checking in the distribution files (all files under `material`), I build on my system with the latest installed version. Thus, when you `npm install`, the newer version will be installed which may contain internal changes that will then alter the source (= internal implementation) and change the chunk hash. This is likely what you're observing and it would only be fixable by pinning all dependencies, missing out on critical security updates. Thus, it's not economical.

**Comment by squidfunk** [comment]
Closing for housekeeping.
