### ISSUE TITLE
Horizontal scroll bar is showing at custom homepage for Material for MkDocs.

### ISSUE THREAD

**Issue by Vishal-raj-1** [squidfunk/mkdocs-material#2149]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [ ] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Here In the home page of the website there is a horizontal scroll bar. we can remove this scroll bar by simply fixed the height of the image. I am sharing the video of the bug and how we can solve this bug.

https://user-images.githubusercontent.com/59874304/103149855-af323580-4793-11eb-8105-e6b9c209ac4d.mp4

### Expected behavior

Horizontal scroll bar should not be there on website!!

### Actual behavior

It show horizontal scroll bar because of image width and position.

### Steps to reproduce the bug

1. We can fixed the image width as 36rem instead pf 38 rem.

### Package versions

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: Window
* Browser: Google Chrome

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting! That's indeed a bug of the custom homepage for Material for MkDocs, but nothing to worry about when using the theme 😊

**Comment by squidfunk** [comment]
Fixed in b89705bb2ec6db06a786331bc1e00e0ad581db29.
