### ISSUE TITLE
Syntax error in sv.html

### ISSUE THREAD

**Issue by allmightyse** [squidfunk/mkdocs-material#2209]
There is an syntax error in: 
material\partials\languages\sv.html", line 30, in template
    "tabs.title"; "Flikar",
jinja2.exceptions.TemplateSyntaxError: expected token ':', got ';'

It would be nice if that cloud been fixed soon...

**Comment by squidfunk** [comment]
Confirmed, would you like to create a PR?

**Comment by allmightyse** [comment]
I can do that, but in that file is Auto generated? And dont now where thats is auto generated from?

**Comment by allmightyse** [comment]
Now there is an PR. Would be nice if that can be merged.

**Comment by squidfunk** [comment]
Released as part of 6.2.5.
