### ISSUE TITLE
Search highlighting URL parameter added even when highlighting is disabled

### ISSUE THREAD

**Issue by funkypenguin** [squidfunk/mkdocs-material#2248]
(Creating this issue from a discussion)

Hey!

I'm on Insiders, and I've been experimenting with the new sexiness that is search suggestions and highlighting. A common workflow I use is to search my site for the particular page I need, then copy the URL and paste it somewhere else. Since upgrading to Insiders, when I search my URL gets the search term appended as `?h=+<search term>`. Assuming that this was due to highlighting, I disabled search highlighting, but it still happens. 

Here's an example - if you go to https://geek-cookbook.funkypenguin.co.nz and search for "nextcloud", and then click on the first result, the page you end up on is https://geek-cookbook.funkypenguin.co.nz/recipes/nextcloud/?h=+nextcloud

I'm not using any of the fancy search features in Insiders ATM (https://github.com/geek-cookbook/geek-cookbook/blob/c5e313b65c5148173e1e9e23871811581eea6722/mkdocs.yml#L183), but the behaviour is still happening. Is there anything I can do to remove the `?h=<blah>` from the URL after searching?

Thanks!
D

_Originally posted by @funkypenguin in https://github.com/squidfunk/mkdocs-material/discussions/2247_

**Comment by squidfunk** [comment]
This is also fixed in `master` of Insiders, same as #2249. Could you check the latest `master`, i.e. just `--force-reinstall` with `pip`, I'll issue a release then.

**Comment by squidfunk** [comment]
Released as part of 6.2.6-insiders+1.16.1
