### ISSUE TITLE
Instant navigation + sticky tabs breaks tab navigation

### ISSUE THREAD

**Issue by funkypenguin** [squidfunk/mkdocs-material#2249]
- [X ] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [X] ... the problem doesn't occur with the default MkDocs template
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

## Description

When instant navigation and sticky tabs are enabled, the navigation between the top tabs gets "messed up" - the path of the previous tab is prepended to the path of any other tabs clicked.

Here's an example:

* Broken: https://deploy-preview-164--geek-cookbook.netlify.app/
* Working: https://geek-cookbook.funkypenguin.co.nz/

This is the only difference between the two above: https://github.com/geek-cookbook/geek-cookbook/pull/164/files

### Expected behavior

Header navigation should work with sticky tabs the same way it does without them

### Actual behavior

As described above - it's impossible to enable sticky tags without incurring broken navigation

### Steps to reproduce the bug

1. Enable instant navigation and sticky tabs
2. Attempt to navigate between top-level tabs

### Package versions

I'm using the latest version of insiders, pulled every time on build

### Project configuration

The entire `mkdocs.yml` can be found at https://github.com/geek-cookbook/geek-cookbook/blob/master/mkdocs.yml

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting!

**Comment by squidfunk** [comment]
I just pushed a fix to the `master` of Insiders, which fixes this issue.

**Comment by squidfunk** [comment]
Released as part of 6.2.6-insiders+1.16.1
