### ISSUE TITLE
Instant reload site map not generating correctly

### ISSUE THREAD

**Issue by StratusFearMe21** [squidfunk/mkdocs-material#2253]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Whenever I build the website using `mkdocs build`, the sitemap.xml doesn't generate correctly, this in turn stops instant reload from working. This doesn't happen with `mkdocs serve`

### Expected behavior

generate a sitemap.xml file that looks something like this
```xml
<urlset>
<url>
<loc>https://docs.palomagit.tk/</loc>
<lastmod>2021-01-29</lastmod>
<changefreq>daily</changefreq>
</url>
<url>
<loc>https://docs.palomagit.tk/rust/</loc>
<lastmod>2021-01-29</lastmod>
<changefreq>daily</changefreq>
</url>
<url>
<loc>https://docs.palomagit.tk/postgres/</loc>
<lastmod>2021-01-29</lastmod>
<changefreq>daily</changefreq>
</url>
</urlset>
```
### Actual behavior

It generaes this instead
```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url>
     <loc>None</loc>
     <lastmod>2021-01-29</lastmod>
     <changefreq>daily</changefreq>
    </url><url>
     <loc>None</loc>
     <lastmod>2021-01-29</lastmod>
     <changefreq>daily</changefreq>
    </url><url>
     <loc>None</loc>
     <lastmod>2021-01-29</lastmod>
     <changefreq>daily</changefreq>
    </url>
</urlset>
```

### Steps to reproduce the bug

1. ... make new documentation with `mkdocs new`
2. ... enable material theme and `navigation.instant`
3. ... run `mkdocs build`

### Package versions

* Python 3.8.5
* mkdocs, version 1.1.2
* Material: Version: 6.2.6

### Project configuration

```yaml
site_name: My Docs

theme:
  name: material
  features:
    - navigation.instant
```

### System information

* OS: Xubuntu 20.04 LTS
* Browser: Firefox 84.02

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by StratusFearMe21** [comment]
also my file structure is

|  /docs
|--- index.md
|--- test.md
|--- /test
       |----- test2.md

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, instant loading relies on the `sitemap.xml` to be present, as there might be other files hosted on the same domain that are not based of Material for MkDocs. This would break instant loading. However, my guess would be that you're missing the `site_url`. Nonetheless, the empty `url` attributes look like a bug, even though `site_url` is not set. Please open an issue over at [MkDocs](https://github.com/mkdocs/mkdocs). We can't do anything about an incorrect sitemap at the theme-level.

**Comment by StratusFearMe21** [comment]
I wasn't aware that `site_url` was an option, setting it in mkdocs.yaml fixed my problem, thank you
