### ISSUE TITLE
Feature request: more sophisticated glossary

### ISSUE THREAD

**Issue by StarfallProjects** [squidfunk/mkdocs-material#2258]
- [ x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x ] ... to my best knowledge, my idea wouldn't break something for other users
- [ x] ... the documentation does not mention anything about my idea
- [ x] ... there are no open or closed issues that are related to my idea (this is related, but I'm suggesting broader functionality: https://github.com/squidfunk/mkdocs-material/issues/1919)

## Description

Currently, there is support for a glossary using abbreviations and snippets, as described here: https://squidfunk.github.io/mkdocs-material/reference/abbreviations/

However, it seems to have a few limitations:

- It's case-sensitive
- You have to manually add it to every page
- It seems to only support single words, not strings 

This is reasonable, as the abbreviations extension is presumably designed just for actual abbreviations (HTML, etc.) But it means it doesn't really serve as a glossary solution. 

### Use Cases

Creating a proper glossary, with multi-word terms, and ideally case-insensitive to avoid having to define everything twice.

**Comment by squidfunk** [comment]
Thanks for reporting. In general, this project can only render what it gets from the Markdown parser. However, maybe we can find a better solution if we know exactly what you're aiming for. Could you provide some cases that don't work with the current proposed approach?

**Comment by StarfallProjects** [comment]
I've raised a feature request for the extension (see above)

So perhaps the only thing to look at for the theme would be easier includes. Is there any way to do that through a template? I'm thinking something like:

In the  `mkdocs.yml`:

```
theme:
   glossary: true [default: false]
```

And then either allow people to define where their glossary file(s) are, or have a standard setting. It is then automatically added to every page in the `/docs`.

**Comment by squidfunk** [comment]
This might be something for the Snippets extension to consider, i.e. a snippet that is included at the bottom of every page. @facelessuser do you know whether there is any prior art on this problem?

**Comment by facelessuser** [comment]
It's certainly something that could be implemented via snippets (the auto including at the end of a file). I don't know about prior art, but it is one of the most reasonable requests for snippets I've received. Usually, I get requested to make it more like a templating engine, which I'm not too keen on. But auto include? That actually fits better in what it is currently intended to do.

**Comment by squidfunk** [comment]
I'm closing this, since we can't do anything about it as part of this project. It's probably best to discuss auto-includes in a new issue over at Python Markdown Extensions.
