### ISSUE TITLE
Wish walk-around solution for searching Chinese/Japanese full sentence

### ISSUE THREAD

**Issue by Eliacy** [squidfunk/mkdocs-material#2270]
Hi, I'm using the latest version of material, and set searching language as 'ja' to support Chinese words. For words no longer than 2 characters, the search works good. But if the search query message is long, such as "物联网", then nothing can be found even if some markdown files really have it. I think it is because segmentation algorithm for Chinese/Japanese only cares about short words. My idea is: we can transform the original query message into short ones and use "OR" or "AND" to connect the divided short messages. Then we get an acceptable walk-around solution for Chinese/Japanese full sentence search.

So I did some rough experiment as following:
1, Add the following into mkdocs.yaml:
```
plugins:
  - search:
      lang: ja
```
2, Modify /src/assets/javascripts/integrations/search/worker/main/index.ts (line 134~139) from 
```
    /* Search query message */
    case SearchMessageType.QUERY:
      return {
        type: SearchMessageType.RESULT,
        data: index ? index.search(message.data) : []
      }
```
to
```
    /* Search query message */
    case SearchMessageType.QUERY:
      var modified_query = message.data + ""
      modified_query = modified_query == "" || modified_query.toLowerCase() != modified_query.toUpperCase() ? modified_query : modified_query.match(/.{1,2}/g).join(" ")
      return {
        type: SearchMessageType.RESULT,
        data: index ? index.search(modified_query) : []
      }
```

Now, if I search "数据平台", in fact the query message will become "数据 平台", and the search result returned perfectly instead of nothing can be found.

However, my experiment have serious drawback. When I search "物联网", the query become "物联 网", and I still found nothing. Only if I search "物 联网", I can get some result. So I guess my hard-coding segmentation do no work well. And I guess if we use the same way to segment the query word as when we use lunr.ja.min.js to build the reversed index, things will be much better.

The bad news is, my poor knowledge of javascript language push me away from further experiment... So I submitted this issue to find some help.

Thanks a lot for the perfect work. Material works with Chinese/Japanese much more better than mkdocs official code.

**Comment by squidfunk** [comment]
Thanks for reporting. Unfortunately, this is something we cannot fix as part of this project. We're using [lunr-languages](https://github.com/MihaiValentin/lunr-languages) for search stemmer support, which includes the Japanese tokenizer that is also used for Chinese. There are [some open issues](https://github.com/MihaiValentin/lunr-languages/issues?q=japanese) in regard to Japanese, maybe there's some discussion there that helps you achieve what you're aiming for.

**Comment by Eliacy** [comment]
Thanks for reference. Issue ["multiLanguage" method doesn't work with Japanese. ](https://github.com/MihaiValentin/lunr-languages/issues/45) talks about this issue very clearly, even though it is not solved. I'll try to dive into this first.

**Comment by squidfunk** [comment]
Great. I'm closing this, as we can't do anything about it except for when `lunr-languages` fixes it and we can update. Feel free to open a new issue when that happens.

**Comment by Eliacy** [comment]
Sorry to bother again.

I modified `lunr.ja.js` a little, add the `lunr.ja.tokenizer` into `lunr.searchPipeline`, now Japanese full sentence search works well. please see the code in [my modified code and demo html](www.elias.cn:81/other/lunr_ja_modified.zip)

I mark the lines I added in lunr.ja.js as `// Eliacy added this`, and the Japanese full sentence demo is using query `文章は日本語`.

However, even if I put the modified `lunr.ja.js` into material code to replace original `lunar.jar.min.js`, material search works the same as before... I wish to know what can I do now... Thanks for help.

**Comment by Eliacy** [comment]
I'm sorry. My previous demo code still have some problem. Current version of lunr.ja can not make sure segmentation on query term always provide correct results as segmentation on full text document. I'd like to try algolia.

Thanks for your time.

**Comment by squidfunk** [comment]
The Japanese stemmer is probably not ideal for Chinese, so it would be best to provide a Chinese stemmer as part of lunr-languages. As soon as that is available, we would immediately switch to it.

**Comment by MtShan** [comment]
I found workaround for Japanese search: use query transformation.
Following [official instruction](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#query-transformation), I wrote 'overrides/main.html' like this.

```html
{% extends "base.html" %}
{% block config %}
{{ super() }}
<script src="https://cdn.jsdelivr.net/npm/tiny-segmenter@0.2.0/dist/tiny-segmenter-0.2.0.min.js"></script>
<script>
var __search = {
    index: Promise.resolve(local_index),
    transform: function(query) {
        var segmenter = new TinySegmenter();
        var segs = segmenter.segment(query);
        var newQuery = segs.join(" ");
        return newQuery;
    }
}
</script>
{% endblock %}
```

tiny-segmenter-0.2.0.js is used in Lunr for Japanese segmentation, so applying same method for query is a workaround.
