### ISSUE TITLE
Enhancement: Option to remove/customize repo counts

### ISSUE THREAD

**Issue by blakegearin** [squidfunk/mkdocs-material#2307]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

By default, star & fork counts are displayed on sites where `repo_url` is defined in `mkdocs.yml` for [GitHub and GitLab](https://github.com/squidfunk/mkdocs-material/blob/7.0.0b2/src/assets/javascripts/components/source/facts/_/index.ts#L25-L26) repositories that are [open-source](https://github.com/squidfunk/mkdocs-material/issues/777#issuecomment-387801458).

I'd like to have the ability to turn off the counts.

### Use Cases

- Could remove a call, helping with load times
- ~It would prevent having to make a repository private (only way currently to remove counts)~ 
  - **Update:** Not a viable option for GitHub Free users
- I think my sites look cleaner without the counts (subjective)
- Sites with `0 stars·0 forks` are sad (subjective) 🙁 

### Screenshots / Mockups

```yml
# mkdocs.yml

repo_name: owner/project
repo_url: https://github.com/owner/project
repo_counts: false
edit_uri: ''
```

Open to other flag names besides `repo_counts` 🙂 

Looks like this section is [now changed in Insiders](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#latest-release). Perhaps it would be low effort while doing this enhancement to add more options besides on/off, such as specifying a subset of counts:

```yml
# mkdocs.yml

repo_name: owner/project
repo_url: https://github.com/owner/project
repo_counts: 
  - tag
  - stars
edit_uri: ''
```

**Comment by squidfunk** [comment]
Thanks for suggesting! Most users seem to love this feature, so I think it won't make sense to introduce an option to disable it. However, if many people need it, we can add a flag. Let's let the issue sit here for a while and see if a significant fraction of users want this feature.

For the time being, you can use template overrides to achieve the same thing. Using Material 7 beta (#2290), you can patch the `partials/source.html` template and just remove the `data-md-component` attribute, which is used to mount the loading logic. Furthermore, loading is not impacted, as the data is fetched after `DOMContentLoaded` and is cached in session storage for subsequent page views.

**Comment by blakegearin** [comment]
> For the time being, you can use template overrides to achieve the same thing. Using Material 7 beta (#2290), you can patch the partials/source.html template and just remove the data-md-component attribute, which is used to mount the loading logic.

Thanks for specifying this! I found that `data-md-component` and `class="md-source"` had to be removed. The class being removed caused the text size to shrink, so had to add the style back

GitHub: [raw source.html](https://raw.githubusercontent.com/squidfunk/mkdocs-material/7.0.0b2/src/partials/source.html)
Mine (working):
```html
<!-- theme/source.html -->

{% import "partials/language.html" as lang with context %}

<a
  href="{{ config.repo_url }}"
  title="{{ lang.t('source.link.title') }}"
  style="display: block; font-size: .65rem; line-height: 1.2; white-space: nowrap; -webkit-backface-visibility: hidden; backface-visibility: hidden; transition: opacity 250ms;"
>
  <div class="md-source__icon md-icon">
    {% set icon = config.theme.icon.repo or "fontawesome/brands/git-alt" %}
    {% include ".icons/" ~ icon ~ ".svg" %}
  </div>
  <div class="md-source__repository">
    {{ config.repo_name }}
  </div>
</a>
```

```yml
# For reference, this implementation requires custom_dir in mkdocs.yml

theme:
  name: 'material'
  custom_dir: 'theme'
```

Regarding one of my original points:

> It would prevent having to make a repository private (only way currently to remove counts)

Making a repo private isn't feasible for GitHub Free users, as it deletes their site 🙁 

> GitHub Pages is available in public repositories with GitHub Free and GitHub Free for organizations, and in public and private repositories with GitHub Pro, GitHub Team, GitHub Enterprise Cloud, and GitHub Enterprise Server.

Source: [GitHub Docs](https://docs.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)

 So the implementation outlined is the only current way to remove it

**Comment by squidfunk** [comment]
@blakegearin when you're using 7.0.0 (i.e. the latest `master`), removing `data-md-component` is sufficient, you don't have to remove `.md-source`. I just tested this again, and the repository metrics are not loaded.

**Comment by blakegearin** [comment]
Ah, yes, I was able to upgrade from `6.2.8` and now I'm seeing that behavior line up. Thanks!


For anyone wanting to do the same thing here are the commands I had to run:
```sh
# check version
python3 -m pip show mkdocs-material

# upgrade to latest commit
python3 -m pip install --upgrade git+https://github.com/squidfunk/mkdocs-material.git
```

**Comment by squidfunk** [comment]
I decided not to go down this road for now. There doesn't seem to be a huge interest from other users and disabling this logic is as easy as overriding the partial and removing the `data-md-component` attribute. For this reason, I'm closing this issue. If in the future this proofs to be crucial, we can revisit it.

**Comment by AirTechWick** [comment]
Trying to follow along https://github.com/squidfunk/mkdocs-material/issues/2307#issuecomment-781545284 I seem to be having a little trouble setting this up

**Comment by matthew-chandler** [comment]
For those who are having trouble with the [above instructions](https://github.com/squidfunk/mkdocs-material/issues/2307#issuecomment-781545284), this is what I did:
- create file `overrides/partials/source.html`
- paste the following code into it. This removes the `data-md-component` from the original [source.html](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/partials/source.html)
```html
<!-- overrides/partials/source.html -->

<a
  href="{{ config.repo_url }}"
  title="{{ lang.t('source') }}"
  class="md-source"
>
  <div class="md-source__icon md-icon">
    {% set icon = config.theme.icon.repo or "fontawesome/brands/git-alt" %}
    {% include ".icons/" ~ icon ~ ".svg" %}
  </div>
  <div class="md-source__repository">
    {{ config.repo_name }}
  </div>
</a>
```
- update theme custom_dir in `mkdocs.yml` to point to the custom html override
```yaml
theme:
  name: material
  custom_dir: overrides
```
