### ISSUE TITLE
Escape Bar doesn't exit search

### ISSUE THREAD

**Issue by ronakdev** [squidfunk/mkdocs-material#231]
## Description

In previous versions on mkdocs-material, if you were typing in the search bar, you could hit the [escape] key to exit search. However, it seems that in the latest version this was removed.

### Expected behavior

Search bar closes.

### Actual behavior

Nothing

### Steps to reproduce the bug

1. Click on search bar
2. Hit Escape to close
3. Nothing Happens

### Package versions

* Python: `Python 2.7.13`
* MkDocs: `mkdocs, version 0.16.1`
* Material: `Version: 1.2.0`

### System information

* OS: MacOS
* Browser: Chrome Version 56.0.2924.87 (64-bit)

**Comment by squidfunk** [comment]
Fixed in 1.5.0
https://github.com/squidfunk/mkdocs-material/releases/tag/1.5.0
