### ISSUE TITLE
Content in embedded files (via Snippets) doesn't show up in search result previews if content includes `<hX>` HTML headings

### ISSUE THREAD

**Issue by miguno** [squidfunk/mkdocs-material#2315]
- [X] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [X] ... the problem doesn't occur with the default MkDocs template
- [X] ... the problem is not in any of my customizations (CSS, JS, template)
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

See the prior discussion at https://github.com/squidfunk/mkdocs-material/discussions/2313, where I was asked by @facelessuser to file this issue.

## Description

As soon as file embedded via a snippet contains any `<h[1-6]>` tag, then the search result previews break in the following way:

* None of the text in the snippet (embedded file) is included in the preview.
* None of the text in "parent" `.md` file (that embeds the snippet) that appears after the snippet is included in the preview.

### Expected behavior

Search result previews should behave identical, regardless of whether content is directly included in a Markdown file vs. embedded via snippet into that Markdown file.

### Actual behavior

See description above, and see screenshots at https://github.com/miguno/mkdocs-search-previews.

### Steps to reproduce the bug

See https://github.com/miguno/mkdocs-search-previews for a minimal setup.

### Package versions

* Python: 3.9.1
* MkDocs: 1.1.2
* Material: 6.2.8

### Project configuration

https://github.com/miguno/mkdocs-search-previews/blob/main/mkdocs.yml

``` yaml
site_name: My Docs

theme:
    name: material

markdown_extensions:
    - pymdownx.snippets:
        base_path: 'docs/'
```

### System information

* OS: macOS 10.15.7 Catalina
* Browser: Google Chrome v88

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Did you check whether the problem doesn’t occur with the default `mkdocs` theme? You ticked that box, I just want to make sure.

**Comment by facelessuser** [comment]
I'm pretty sure it is present in the default, but I haven't checked yet.

**Comment by squidfunk** [comment]
When I run `mkdocs build` on the repository linked in the OP, the `search_index.json` doesn't contain the content from the snippet, which is why nothing appears in search:

``` json
{
  "config": {
    "lang": [
      "en"
    ],
    "min_search_length": 3,
    "prebuild_index": false,
    "separator": "[\\s\\-]+"
  },
  "docs": [
    {
      "location": "",
      "text": "Welcome to MkDocs Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt . jupiter saturn neptune Text above this line is embedded. Football. Tennis.",
      "title": "Welcome to MkDocs"
    },
    {
      "location": "#welcome-to-mkdocs",
      "text": "Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt .",
      "title": "Welcome to MkDocs"
    }
  ]
}
```

This means that this issue is definitely not related to Material for MkDocs. It's either related to the Snippets extension, MkDocs itself or Python Markdown.

**Comment by facelessuser** [comment]
It's not Snippets as I've already confirmed that this happens without Snippets.

**Comment by squidfunk** [comment]
@facelessuser ah right, sorry! I guess this should then be reported over at MkDocs, because the next thing to rule out is misbehavior of the built-in search plugin.

**Comment by miguno** [comment]
Thanks for the follow-ups, both of you!

> I guess this should then be reported over at MkDocs, because the next thing to rule out is misbehavior of the built-in search plugin.

Will you report upstream then? You have more context than I do about how MkDocs/Material/Snippet/et al. interrelate.

**Comment by squidfunk** [comment]
I'd kindly ask you to do the reporting, as you're most familiar with the error and I'm currently very busy with Material 7. It should be sufficient to describe the issue, link to the discussion and this issue, and update your minimum reproducible example (excluding Snippets and Material).

**Comment by miguno** [comment]
@squidfunk Sure, I can do that.

One last question though: I just built an equivalent minimal example for MkDocs (but with Snippets / pymdown-extensions for the embedding part). The result is at https://github.com/miguno/mkdocs-search-previews/tree/main/mkdocs. Interestingly, the error does NOT occur in this setup, as shown in the screenshot. That is, MkDocs + Snippets works fine. 

Does that change to which upstream project I should report this to?

**Comment by miguno** [comment]
FWIW, I also compared `search_index.json` between the (1) Material minimal example and (2) the new vanilla MkDocs + pymdown-extensions example.  The files are identical.  Yet the search result preview works for (2) but not for (1).

```shell
# Same for both examples
$ cat site/search/search_index.json | jq '.'                                                                      5827  10:48:44 
{
  "config": {
    "lang": [
      "en"
    ],
    "min_search_length": 3,
    "prebuild_index": false,
    "separator": "[\\s\\-]+"
  },
  "docs": [
    {
      "location": "",
      "text": "Welcome to MkDocs Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt . jupiter saturn neptune Text above this line is embedded. Football. Tennis.",
      "title": "Welcome to MkDocs"
    },
    {
      "location": "#welcome-to-mkdocs",
      "text": "Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt .",
      "title": "Welcome to MkDocs"
    }
  ]
}
```

**Comment by miguno** [comment]
Friendly ping for my last question, see https://github.com/squidfunk/mkdocs-material/issues/2315#issuecomment-783241176.

**Comment by squidfunk** [comment]
It's unclear for me what you mean by "search result previews work". If the files are identical (which I would've expected them to be, as this is clearly an upstream issue), the search results cannot possibly show up as separate sections. It's just how the theme handles it. If there are no sections to render, no sections are rendered.

**Comment by miguno** [comment]
> It's unclear for me what you mean by "search result previews work". 

https://github.com/miguno/mkdocs-search-previews/tree/main/mkdocs#result-everything-works-as-expected shows how the search result previews work for the vanilla MkDocs, even when the embedded snippet contains `<hX>` tags:

> ![](https://github.com/miguno/mkdocs-search-previews/raw/main/mkdocs/works-2.png)

https://github.com/miguno/mkdocs-search-previews/tree/main/mkdocs-with-material shows how the previews do not work with the Material theme:

> ![](https://github.com/miguno/mkdocs-search-previews/raw/main/mkdocs-with-material/fails-2.png)

And here's the [outcome for Material if the snippet does not contain](https://github.com/miguno/mkdocs-search-previews/tree/main/mkdocs-with-material#works-fine-when-no-hx-tag-is-in-the-embedded-snippet) any `<hX>` tags. This looks as expected, and it matches the vanilla MkDocs behavior at the top of this comment:

> ![](https://github.com/miguno/mkdocs-search-previews/raw/main/mkdocs-with-material/works-2.png)

Does that clarify?

**Comment by squidfunk** [comment]
Thanks, yes it does. I already tried to answer this here: https://github.com/squidfunk/mkdocs-material/discussions/2313#discussioncomment-385893. In essence, Material will not consider the content of the whole document when there's at least one `hx`. This doesn't work, when there are sections missing, which is caused by the upstream bug, which is why you're seeing this issue. The default template doesn't do that.

**Comment by miguno** [comment]
I realize that you and I might be talking about two different but intertwined/related behaviors. Sorry for asking again—I am trying to understand what the exact issue so I can properly report upstream. And when you say upstream, you mean MkDocs, correct (not https://lunrjs.com/)?

You said https://github.com/squidfunk/mkdocs-material/issues/2315#issuecomment-787735246:

> If the files are identical (which I would've expected them to be, as this is clearly an upstream issue), the search results cannot possibly show up as separate sections. It's just how the theme handles it. If there are no sections to render, no sections are rendered.

```json
// excerpt of site/search/search_index.json
    {
      "location": "",
      "text": "Welcome to MkDocs Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt . jupiter saturn neptune Text above this line is embedded. Football. Tennis.",
      "title": "Welcome to MkDocs"
    },
    {
      "location": "#welcome-to-mkdocs",
      "text": "Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt .",
      "title": "Welcome to MkDocs"
    }
```

So I guess your argument is: There is only one match for 'jupiter', given the search index above. This match is in the first entry with `"location": ""`. And because the second entry with `"location": "#welcome-to-mkdocs"` does not contain 'jupiter', the Material search cannot show this as a separate section to which you can directly click when seeing the search results.

And when you say that the bug is in upstream and must thus be reported there, you are referring to the lack of 'jupiter' (etc.) in the second entry with `"location": "#welcome-to-mkdocs"`?

Hence your POV is that MkDocs should produce such a search index:

```json
// excerpt of site/search/search_index.json
    {
      "location": "",
      "text": "Welcome to MkDocs Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt . jupiter saturn neptune Text above this line is embedded. Football. Tennis.",
      "title": "Welcome to MkDocs"
    },
    {
      "location": "#welcome-to-mkdocs",
      "text": "Welcome to MkDocs Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt . jupiter saturn neptune Text above this line is embedded. Football. Tennis.",
      "title": "Welcome to MkDocs"
    }
```

**Comment by squidfunk** [comment]
Probably yes, that should be discussed with the maintainers of this project. Other than that, my advice would be to use Markdown level headlines and not literal `hx` in your integrated Snippets. This will fix the issue on your side.

**Comment by miguno** [comment]
Ok. Then one final question for you because that's about Material behavior:  If 'jupiter' is matched in the first entry below, why is Material showing the shorter text "Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt" (from the second entry) instead of "Welcome to MkDocs Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt . jupiter saturn neptune Text above this line is embedded. Football. Tennis." ?

That is, with a `<hX>` in the snippet, I still would have expected this search outcome, with the link pointing to the "complete" page (= no `#` anchor/fragment), yet with the 'long' text that includes 'jupiter':
![](https://github.com/miguno/mkdocs-search-previews/raw/main/mkdocs-with-material/works-2.png)


```json
// excerpt of site/search/search_index.json
    {
      "location": "",
      "text": "Welcome to MkDocs Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt . jupiter saturn neptune Text above this line is embedded. Football. Tennis.",
      "title": "Welcome to MkDocs"
    },
    {
      "location": "#welcome-to-mkdocs",
      "text": "Text below this line, i.e., planet names, is embedded via a snippet at docs/snippet.txt .",
      "title": "Welcome to MkDocs"
    }
```

**Comment by miguno** [comment]
> Other than that, my advice would be to use Markdown level headlines and not literal hx in your integrated Snippets. This will fix the issue on your side.

Yeah, I am aware. The issue I am facing is that auto-generated HTML pages need to be included, created by another tool.

**Comment by squidfunk** [comment]
> Ok. Then one final question for you because that's about Material behavior: If 'jupiter' is matched in the first entry in the search index below (JSON), why is the search window in Material showing the shorter text from the second, non-matching entry:

The `search_index.json` essentially contains the content for each page twice – the anchor-less item contains all content of the whole page. Then, the following items prefixed with the same URL (belonging to the previously mentioned item) contain the content of _each section_. Thus, when you search for something, and have a match in one section, you will also have a match for the item that contents the whole page. It makes no sense to render both results in the search view – it would be redundant and confusing. This is what MkDocs does in the built-in themes and I personally find it suboptimal from a UX perspective. It's also why this theme goes to great lengths to kick out the redundant stuff and only present the relevant bits of the page.

Now, it seems that your literal sections are not correctly indexed, because the built-in search plugin does not know what to do with them. This is either by design or an error, so it's best to ask the maintainers of MkDocs what it is. Regardless of the answer, it's nothing we can fix on our side. We would need to alter the search behavior, presenting the whole page as a search result, which counteracts what I explained in the last paragraph. If you need to display the whole page result, you may fork the theme and patch the respective behavior.
