### ISSUE TITLE
Quick Search for URLs/File Names

### ISSUE THREAD

**Issue by Stanzilla** [squidfunk/mkdocs-material#2316]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

So you know how the command palette in VSCode has two modes, one (with SHIFT) lets you enter commands and the other (without SHIFT) is the file search. 

how about adding that file search part to material? this way if a person knows exactly where they want to go they can just hold that modifier key and type in the file/URL name and go there fast?

### Use Cases

Person knows exactly where they want to go but don't want to deal with the menu structure.

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/75278/108605791-bbfb9000-73b6-11eb-8275-75fe6c221bd3.png)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for the suggestion!

> So you know how the command palette in VSCode has two modes, one (with SHIFT) lets you enter commands and the other (without SHIFT) is the file search.

We can't alter the default behavior of the search modal, which is just `F`/`S` to open search, so we would need to swap those commands, i.e. `Shift+F` would trigger the file search. This might confuse some users, as it would be the other way round.  

Also, wouldn't we essentially reinvent the browser search bar? Also, how would we educate users about this way to search?

<img width="1106" alt="Bildschirmfoto 2021-02-21 um 15 05 41" src="https://user-images.githubusercontent.com/932156/108627508-48a95b00-7456-11eb-88a0-f15510b98532.png">

As much as I like this idea, I'm undecided whether it would provide any value and people would use it.

**Comment by Stanzilla** [comment]
It could be a hint in the opened search drawer. Btw I also changed the default placeholder in my fork from "Search" to "Press S to Search" to advertise that feature better. If you don't want to add an additional key bind, it could also work by using a prefix like VSC does with `>`

**Comment by squidfunk** [comment]
Coming back to this, there was no real feedback from other users for the last two weeks, so I decided that at the current moment this feature request is probably not worth pursuing. We might re-evaluate in the future. Closing for housekeeping.

**Comment by sambaccessnow** [comment]
hi, jumping in here because we are interested in this topic

We are trying to build a documentation of articles, each article is identifiable by an ID

The search is not indexing the filename, so we are stuck and we are not able to search per ID
with the filename search this could be solved and we are thinking if this issue is the right place where to discuss this

Right now to workaround this we are editing the articles's title and we are using the article number in the title, but that's a bit weird..

We think this quick search for urls and file name can help. Do you agree?

**Comment by squidfunk** [comment]
The new search implementation will be able to index arbitrary data, so you will also be able to index identifiers or file names. I recommend to subscribe to #6307 to get notified when its available ☺️
