### ISSUE TITLE
Add requirements to the setup.py

### ISSUE THREAD

**Issue by yacir** [squidfunk/mkdocs-material#232]
Material uses Pygments and the PyMdown Extensions. Would it not be simpler to add them in the setup requirements ?   

```py
install_requires=[
        'Pygments>=2.2',
        'pymdown-extensions>=2.0'
    ]
```

**Comment by squidfunk** [comment]
I'm not a python programmer, so packaging was done using a best practice template. However, your suggestion makes perfect sense to me. I will investigate.

**Comment by squidfunk** [comment]
Added in #241 and merged into `master`. Thanks for the input!
