### ISSUE TITLE
Can't support Chinese search

### ISSUE THREAD

**Issue by sherryQwl** [squidfunk/mkdocs-material#2330]
Hi,  When will Material for MkDocs support Chinese search?

**Comment by squidfunk** [comment]
https://github.com/squidfunk/mkdocs-material/issues/2270#issuecomment-773333299

**Comment by squidfunk** [comment]
Chinese language support has been released as part of [8.2.13+insiders-4.14.0](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.14.0). The [blog article](https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/) sums up my previous comment and explains how to set it up. I'm not proficient in Chinese, so I'm very interested in feedback!
