### ISSUE TITLE
DockerHub Tag 7.0.0 missing

### ISSUE THREAD

**Issue by axdotl** [squidfunk/mkdocs-material#2331]
Hi there,

thanks a lot for the latest release 🎉

But there is no 7.0.0 tag in DockerHub

```
$ docker pull squidfunk/mkdocs-material:7.0.0
Error response from daemon: manifest for squidfunk/mkdocs-material:7.0.0 not found: manifest unknown: manifest unknown
```

Could you please provide the missing tag?

Thanks in advance!

**Comment by squidfunk** [comment]
Thanks for reporting! That's super weird, as we didn't change the process lately. `latest` is up to date, but the release tag wasn't pushed. I'll do that in a few minutes and investigate the error.

**Comment by squidfunk** [comment]
It seems like the behavior of the `docker push`  command changed. The new image was correctly built and tagged, and previously this was sufficient to push all tags to the registry:

https://github.com/squidfunk/mkdocs-material/blob/d0b34b07d6334d56daecb5e7d4510df4be7e0465/.github/workflows/publish.yml#L93-L99

I've now added the [`--all-tags`](https://docs.docker.com/engine/reference/commandline/push/#push-all-tags-of-an-image) flags to the push command, which should fix this for subsequent releases.

I've also tagged the latest image – you should now be able to pull `7.0.0`.
