### ISSUE TITLE
Analytics Regression from Observable Refactor

### ISSUE THREAD

**Issue by Stanzilla** [squidfunk/mkdocs-material#2334]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Quote from Gitter:

> Could be related to: https://github.com/squidfunk/mkdocs-material/blob/0b2e14056a75f919e651014de45612efa2cc5a53/src/partials/integrations/analytics.html#L48-L52
But rather not, the location observable should only emit on instant load. Could you patch the partial and see whether it triggers with instant loading disabled?
Ah yeah, wait. I see 2 calls to their collect endpoint. Could be related. Could you open an issue? I can look into it tomorrow.

### Expected behavior

Only one call to endpoint

### Actual behavior

2 calls

### Steps to reproduce the bug

1. ...
2. ...
3. ...

### Package versions

* Python: 3.9
* MkDocs: 7
* Material: 1.1.2

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: ...
* Browser: ...

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Fixed in 1864463e. The `location$` subject emitted the original location and location changes. This is now changed, as it will only emit changes, which is necessary for instant loading. The `document$` observable continues to emit on initial load, as well as on subsequent loads.

**Comment by squidfunk** [comment]
Released as part of 7.0.1.
