### ISSUE TITLE
Changes in 7.x for image alignment

### ISSUE THREAD

**Issue by lazka** [squidfunk/mkdocs-material#2337]
Maybe it is on purpose, I thought I'd report anyway.

Old: https://web.archive.org/web/20201028041546if_/https://squidfunk.github.io/mkdocs-material/reference/images/#image-alignment

New: https://squidfunk.github.io/mkdocs-material/reference/images/#image-alignment

Caused by flow-root in 9591265939f79eb692

One workaround I found was adding the image to the same paragraph and using `<br>` everywhere so there is only one paragraph.

**Comment by squidfunk** [comment]
Thanks for reporting - definitely a bug!

**Comment by squidfunk** [comment]
Fixed in a17b6375 together with #2336.

**Comment by lazka** [comment]
Thanks!

**Comment by squidfunk** [comment]
I'll issue 7.0.1 later this day, I've some other small changes in the pipe.

**Comment by squidfunk** [comment]
Released as part of 7.0.1.
