### ISSUE TITLE
Markdown's TOC behavior has changed

### ISSUE THREAD

**Issue by waylan** [squidfunk/mkdocs-material#2342]
With the release of Markdown version 3.3.4 (today), the documentation below is not longer correct:

https://github.com/squidfunk/mkdocs-material/blob/d65e88061881384ff018aa0e09eb2d551ffe9c34/docs/setup/setting-up-navigation.md#L294-L295

The behavior has been changed in Python-Markdown/markdown#1108 and `toc_depth` no longer restricts the creation of permalinks. The setting only restricts the creation of the TOC itself.

As an aside, Markdown never documented the old behavior and I didn't even realize that behavior had been introduced. Therefore, I consider the behavior a regression and addressed it as a bug fix.

**Comment by squidfunk** [comment]
That's great news! I removed the notice 😊
