### ISSUE TITLE
`sourceMappingURL` in built JS is invalid

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#2343]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

I am fairly certain this isn't related to upstream MkDocs, AFAIK the asset bundling optimization is only offered by MkDocs Material here. The minified output files are incorrectly pointing to the Source Map files they generate, which the browser console will issue warnings about as unable to parse, thus they're not useful.

This appears to be the related code as your docs mention you use ESBuild:

https://github.com/squidfunk/mkdocs-material/blob/d65e88061881384ff018aa0e09eb2d551ffe9c34/tools/build/transform/index.ts#L179-L189

Slightly related, advice for adding JS via the docs [here](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) seems to mirror roughly what upstream MkDocs advise. I assume that these third-party assets are not included in the bundling during build? ([seems to only process `bundle` and `search` TS files](https://github.com/squidfunk/mkdocs-material/blob/d65e88061881384ff018aa0e09eb2d551ffe9c34/tools/build/index.ts#L161) from this projects `src/**` dir)

### Expected behavior

Processed JS file should be: `//# sourceMappingURL=bundle.926459b3.min.js.map`

### Actual behavior

Processed JS files are actually: `//# sourceMappingURL=bundle.926459b3.min.js`

Probably just needs to be:

```js
`$1${path.basename(file)}.map\n`
```

### Steps to reproduce the bug

1. Visit the [MkDocs Material site](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript).
2. Open the console dev tools panel.
3. Logged warning should be visible (at least on Firefox), or may require a refresh.
4. Alternatively, inspecting the source via dev tools will show only minified JS that was loaded, source map would have failed to load.

### Package versions

Current Docker container and current version of the website.

### Project configuration

Standard instance should do the trick, this is an internal bug.

### System information

Manjaro Linux with Firefox. Present with Docker container build, present with Github Action workflow (python pip install, not docker) build deployed to Github Pages.

**Comment by squidfunk** [comment]
Confirmed, indeed the `.map`was missing!

**Comment by squidfunk** [comment]
Fixed in 1aacca36.

**Comment by squidfunk** [comment]
Released as part of 7.0.2
