### ISSUE TITLE
[FEAT]: Add `awesome-pages` into the Docker image

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#2349]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Would it be possible to consider adding back the [`awesome-pages` plugin](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin)?

This was deprecated back in [5.5 and removed in 6.0](https://squidfunk.github.io/mkdocs-material/deprecations/#bundled-plugins) with the reasoning of size concerns. While this is valid with `mkdocs-git-revision-date-localized-plugin` (31MB layer), `mkdocs-awesome-pages-plugin` only adds 323KB as layer weight.

### Justification

If size is a concern, it looks like there is plenty of opportunity to reduce the Docker image further.
- For example the `lunr` package includes a 4 `rust_stemmer.cpython.*.so` files, 3 appear to be diffentiated by `35m`, `36m` and `37m`... which I assume might be relevant to Python version support? These are files built during install not source files, they have a weight of 2.7MB each, two can be discarded and the container would work as intended still. Furthermore the 4th file is a binary for `darwin` (macOS), 345KB right there that could be swapped out for `awesome-page`.
- `nltk` which seems to be a supporting package for `lunr` I think is a 9MB package, there's 1.2MB `test` directory that I doubt is required for this project?
- `python3.8` in total is 52MB, with `site-packages` at 48MB, I don't know Python well enough to know if anything else could be cleaned up from there.
- `git` and related dependencies also eat up around 20MB in size (this layer is 77MB). Technically a slimmer image could be used if a minimal/slim base image was useful for most users (`serve` and possibly `build`?), those that would use the image to deploy could use a `deploy` variant, but I imagine most would be fine deploying the build output via other means.
- The earlier layers from the python image you extend is about 40MB in addition to all this. Total image size is 126MB.

These insights were provided via the CLI tool [`dive`](https://github.com/wagoodman/dive). The alternative git revision date plugin `mkdocs-git-revision-date-plugin` weighs 1.3MB btw if you were interested.

### Use Cases

Considering it's usefulness for some, this seems useful to include by default vs requiring a separate Dockerfile being maintained by projects (as this one is rather popular AFAIK when it comes to choosing MkDocs).

At less than 0.3% increase in size, I think this is perfectly valid to consider for the added flexibility in adopting MkDocs when migrating from another docs platform. A project can refine it's nav over time this way.

There's a [related feature request for upstream MkDocs](https://github.com/mkdocs/mkdocs/issues/714) (since 2015) as MkDocs only offers explicit or implicit sidebar/nav without that linked extension. In that feature request, the OP is referencing GlusterFS docs which involved a 200 line config for nav where sometimes it'd be nice to just explicitly declare top-level categories and then glob the directory files and any nested children.

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for suggesting and your elaborate analysis of the image size! I'm very interested to reduce the image size even further and hope that MkDocs will make `lunr` an optional dependency (which pulls in `nltk`). `git` is necessary to be able to use the image for deployment. We could add more images, but that would mean more maintenance. See my analysis [here](https://t.co/VpY7jnlJZl?amp=1), which comes to the conclusion that we could reduce MkDocs's payload size down to 22 MB without loosing too much.

However, I don't want to add more plugins to the Docker image because then other users will want to add more and more plugins. The redirects and minify plugin are very unopinionated, small and crucial plugins I find to provide great value. Note that it's trivial to [add plugins to the image](https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker) and rebuild it.

**Comment by polarathene** [comment]
> However, I don't want to add more plugins to the Docker image because then other users will want to add more and more plugins. The redirects and minify plugin are very unopinionated, small and crucial plugins I find to provide great value.

It's ~300KB, was previously in the image and can be opt-in by default. You can use the plugin via `mkdocs.yml` alone and AFAIK counts as small and unopinionated.

I thought the GlusterFS example of migrating docs to MkDocs with an existing 200+ pages of docs where it'd reduce friction considerably by only worrying about top-level categories and auto-generating the rest to begin with and iteratively refine the nav where needed was a pretty good use case...?

I don't know what other many plugins you're saying other users would leap to requesting if this one was made available in the image again, all with justifications for the value such as better nav management (a core docs feature).

> Note that it's trivial to add plugins to the image and rebuild it.

I'm aware of this, and have no problem doing so personally. A project I'm migrating docs for however has some strict requirements.

They very much don't want to maintain their own Dockerfile and keep that image in sync with yours, they don't want to impose an additional build step on contributors, and they'd rather use your image which has higher trust than a third-party one if they're not maintaining the slight modification to add a small plugin.

I don't know how common that is, but the plugin itself seems to be popular enough of a solution with it's own merits for nav improvement. I understand if you don't want to include it yourself in your image, and if I can't convince you than I will just have to manage without it.

> I'm very interested to reduce the image size even further and hope that MkDocs will make lunr an optional dependency (which pulls in nltk).

In the meantime you do have the option of trimming the fat I pointed out if you want to reduce file size. That's a free 7MB reduction by adding an extra line to the RUN command, which is the bulk of the `lunr` package.

I'm not sure how you plan to approach this in future if `search` was made optional though, defer users to also extend the image to add the search plugin themselves?

> git is necessary to be able to use the image for deployment. We could add more image variants, but that would mean more maintenance. 

Uhh yeah, I think I pointed that out earlier that I assumed it's only relevance was for deployment, unless using some plugin that utilized git during a build/serve command.

This is a 20MB reduction in itself. Something you can achieve without having any major maintenance. You have a multi-stage image build, tag the earlier build, then extend it like you've just advised me to do for a 300KB plugin and add git for a deployment variant tag.

CI should handle that no problem, I'm not sure where you're seeing much maintenance overhead from that tbh? (you're just tagging an earlier stage)

Do you happen to know how your users are deploying usually? If they're using `gh-deploy` for example which is what I've seen usually advised for MkDocs deployment, it's often because that's what the docs or articles advise the user to do. Github Actions workflow is pretty simple for handling deployment, as is hosting the build output on a VPS or Vercel/Netlify.

If you value reducing the image weight, this is probably something worth surveying your community about. In the linked issue you gave me, you cite the value being for CI, I don't quite follow how as the image is already quite small, CI services can often provide caching capabilities as well.

> See my analysis here, which comes to the conclusion that we could reduce MkDocs's payload size down to 22 MB without loosing too much.

22MB? [For that 77MB layer in your image](https://github.com/squidfunk/mkdocs-material/blob/500d5e6f740e5d3881dd8483007b617adba79370/Dockerfile#L41)? 20MB-ish is for git, 52MB for Python related files (just this layer, excludes pip and base python from the image you extend from). You're removing 30MB? (assuming those dependencies aren't required by anything else and can be removed)

**Comment by squidfunk** [comment]
> They very much don't want to maintain their own Dockerfile and keep that image in sync with yours, they don't want to impose an additional build step on contributors, and they'd rather use your image which has higher trust than a third-party one if they're not maintaining the slight modification to add a small plugin.

I understand the trust issue, but in the end the maintenance necessary for this plugin would be deducted from my time from this project. I try to keep dependencies at a minimum, which is why I've thrown out Webpack in favor of a completely custom build process (~500 dependencies less to worry about). 

> In the meantime you do have the option of trimming the fat I pointed out if you want to reduce file size. That's a free 7MB reduction by adding an extra line to the RUN command, which is the bulk of the lunr package.

I'm very interested to collaborate on a PR to reduce the fat. As you might have seen, I'm also removing the regular MkDocs themes, because they carry web fonts of 10MB. Removing anything else unnecessary is much appreciated.

> I'm not sure how you plan to approach this in future if search was made optional though, defer users to also extend the image to add the search plugin themselves?

Search is an integral feature of Material for MkDocs. I have no plan to remove it from the Docker image.

> Do you happen to know how your users are deploying usually? If they're using gh-deploy for example which is what I've seen usually advised for MkDocs deployment, it's often because that's what the docs or articles advise the user to do. Github Actions workflow is pretty simple for handling deployment, as is hosting the build output on a VPS or Vercel/Netlify.

If we remove it, it will break a lot of pipelines with the necessity for adaption. I have no interest managing the issues rolling in.

> 22MB? For that 77MB layer in your image? 20MB-ish is for git, 52MB for Python related files (just this layer, excludes pip and base python from the image you extend from). You're removing 30MB? (assuming those dependencies aren't required by anything else and can be removed)

The 22 MB was concerning MkDocs + dependencies, not the whole image.

**Comment by squidfunk** [comment]
To sum up: you are free to build your own Docker image variants from the given Dockerfile! If you do, we can link to them from the official documentation as an alternative for when you don't want to roll your own!

**Comment by polarathene** [comment]
> which is why I've thrown out Webpack in favor of a completely custom build process (~500 dependencies less to worry about).

The number of dependencies involved behind Webpack isn't exactly relevant, unless you've had a case where it's actually mattered. In Linux land that number of dependencies has come up before in the past, usually with few dependencies required being ideal, but if the weight of all that entails for a satisfactory low number of dependencies visible to the user is an issue, then it's called bloat just as much as granular dependencies which can be modular.

If Webpack for example works well for you, lock to the version that does and you shouldn't have any issues, that's the whole point of the package management. You can update to newer versions and if there are any surprises just roll back to the known good versions. So for the most part, Webpack is a single dependency if you exclude anything else it pulls in behind it. Beyond that you might be concerned about file weight.

> I'm very interested to collaborate on a PR to reduce the fat. 

Like you, my time is limited. I don't see any major pragmatic benefits to reducing the current image size. Personally I think time is better spent elsewhere, but I can contribute some space savings for you if you're interested in granting my request in exchange.

> Removing anything else unnecessary is much appreciated. However, all existing functionality should be kept.

Those *rust_stemmer* files should be fine to remove AFAIK, assuming they're binaries for compatibility with different versions of Python you'd only need the latest one since your Docker image is a controlled python environment. Same with the `nltk` test directory, you're not going to run tests for it given the purpose of the image, so it has little value being kept.

> If we remove it, it will break a lot of pipelines with the necessity for adaption. I have no interest managing the issues rolling in.

You know semver and issue deprecation notices before removal already.

You won't introduce any breakage because you can keep the same system for the current image. All that would change is you offer a `-slim`/`-core` variant then instead of `-deploy` (which remains your default).

Here's a Github Actions workflow I've setup:

```yaml
name: MkDocs (Github Pages)

# Triggers jobs only on relevant commits changing docs related files
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/generate-docs.yml'
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    paths:
      - '.github/workflows/generate-docs.yml'
      - 'docs/**'
      - 'mkdocs.yml'

# Jobs will run shell commands from this subdirectory:
defaults:
  run:
    working-directory: docs

jobs:
  # Only runs on pull_request event for testing contributions build successfully before merging
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build with mkdocs-material via Docker
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict

  # Only runs the deploy on push event (eg merge to master)
  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build with mkdocs-material via Docker
        run: docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --strict

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          # Attribute gh-pages branch commits to the official Github Actions bot
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
```

With Vercel or Netlify services it's also very simple, to the point you can have a 1-click basic build/deploy setup. For self-hosting on VPS, I have a static webserver via docker in single `docker run`, etc. I'm sure deploying via the Docker image has it's benefits and interested users, but dropping git dependency is a 16% reduction in weight.

> If you do, we can link to them from the official documentation as an alternative for when you don't want to roll your own!

If I end up doing so, I'll be sure to contribute a link to `mkdocs-material` docs for the benefit of others :+1:
