### ISSUE TITLE
Enhancement: Ability to add custom SCSS files.

### ISSUE THREAD

**Issue by LilTrublMakr** [squidfunk/mkdocs-material#2376]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

I have searched through the documentation and open/closed issues and everything I see is related to either CSS files or modifying the original SCSS files.

I would like to see the ability to add a custom .scss file in the same way that you can add .css files. I would mainly like to see it to be able to use nested styles or extends as it would save time and size to style.

I may be going under a false assumption, but I assume that if we edit the original files and then update, all changes would get reverted. I assume that this is the reason why we are able to add a custom CSS anyways is so that it would persist  through updates.

When trying to add an SCSS file to mkdocs.yml, I get in error in both Chrome and FireFox.
Chrome: `(index):45 Resource interpreted as Stylesheet but transferred with MIME type application/octet-stream: "http://127.0.0.1:8001/stylesheets/extra.scss".`
FireFox: `The stylesheet http://127.0.0.1:8001/stylesheets/extra.scss was not loaded because its MIME type, “application/octet-stream”, is not “text/css”.`

### Use Cases

An example of one of my use cases would be for the ability to add different button sizes. I like to use small buttons to mimic what I see in different programs but like them inline with text. 

### Screenshots / Mockups

This is a side by side comparison of what the current way is (left) and would be available to do if we could use custom SCSS files (right).
![Screenshot 2021-03-01 215024](https://user-images.githubusercontent.com/54646041/109589355-3378a000-7ad8-11eb-9b69-ce1581bd555a.png)

**Comment by squidfunk** [comment]
Thanks for your suggestion! Have you considered using [this plugin](https://pypi.org/project/mkdocs-extra-sass-plugin/)?

**Comment by LilTrublMakr** [comment]
> Have you considered using [this plugin](https://pypi.org/project/mkdocs-extra-sass-plugin/)?

I have not. I am still figuring out MkDocs because I only learned about it about 2 weeks ago but I like it more than the couple of other programs that I have used in the past. I will use the plugin for now.
I don't know if this is a theme thing or MkDocs thing but I would like to see this implemented still. If it is a MkDocs thing, I will try to find out how to suggest this enhancement there.

**Comment by squidfunk** [comment]
It's not possible to implement as part of the theme. It needs to be a plugin. However, you can also clone the GitHub repository and hook into the process that builds the theme's assets (which requires a Node.js runtime), if you wish to start from something that's already set up. See the [customization guide](https://squidfunk.github.io/mkdocs-material/customization/) for more info and a heads up 😊
