### ISSUE TITLE
REQ: Implement Wavedrom waveform viewer diagrams into docs

### ISSUE THREAD

**Issue by madeinoz67** [squidfunk/mkdocs-material#2380]
- [X] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

## Description

Implement [Wavedrom](https://wavedrom.com/) waveform viewer [mkdocs plugin](https://github.com/kuri65536/mkdocs-wavedrom-plugin)

### Use Cases

Writing technical documentation for hardware projects that requires these timing diagrams 

### Screenshots / Mockups

From mkdocs-wavedrom-plugin:
![image](https://user-images.githubusercontent.com/4160293/109756722-64b1b700-7c23-11eb-8343-b2fc8eac0eff.png)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for suggesting. The plugin explains precisely [how to set it up](https://github.com/kuri65536/mkdocs-wavedrom-plugin#how-to-use), have you tried doing so with the Material theme? Did you encounter any rendering issues?

**Comment by squidfunk** [comment]
Closing for housekeeping. I'd consider this a rather exotic Markdown extension as compared to those that we already support. From what I've seen, the plugin should basically work with Material for MkDocs. If you have troubles with styling, feel free to ask a question on the discussions board, so somebody can help you.
