### ISSUE TITLE
Cannot exclude some folders from rendering on static site

### ISSUE THREAD

**Issue by NavyaG-lab** [squidfunk/mkdocs-material#2381]
## Description

I have a scenario where in the mkdocs.yml, the nav is customized as per designed taxonomy. Now, we want to exclude some folders not to be rendered on the static site. As the files are in docs directory and not under nav, it's throwing error.

Could someone please help me how to achieve desired goal?

Thanks!

### Expected behavior

Exclude the specific folders in the repo and remove some links from nav, so the static site renders only the desired content.

### Actual behavior
I have a scenario where in the mkdocs.yml, the nav is customized as per designed taxonomy. Now, we want to exclude some folders not to be rendered on the static site. As the files are in docs directory and not under nav, it's throwing error.

### Steps to reproduce the bug

1. mkdocs.yml is created at repo level where there are multiple folders
2. In the mkdocs.yml, the nav is configured.
3. Now we want to exclude some folders and its content not to be rendered on the static site.

### Package versions

* Python: `3.7.6`
* MkDocs: `1.1.2`
* Material: `pip show mkdocs-material | grep -E ^Version`

### Project configuration

theme:
  name: 'material'
  custom_dir: 'overrides'
  features:
    - tabs
  palette:
    primary: 'deep-purple'
    accent: 'deep-purple'

markdown_extensions:
  - admonition
  - sane_lists
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.mark
  - plantuml_markdown
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - toc:
      permalink: "#"

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mermaid@8.4/dist/mermaid.min.js
  - js/docs.js
  - js/search.js
  - js/elasticsearch.js
  - js/mark-as-outdated.js
  - js/gtm.js

plugins:
  - mkdocs-jupyter
  - git-revision-date-localized
  - minify
nav:
  - Home: "README.md"
  - What's new: "whats-new.md"
  - Glossary: "glossary.md"
  - About BU Squads:
    - About all squads: "about/data-bu-squads.md"
    - Data Infra overview: "about/data-infra/overview.md"
    - Data Infra history: "about/data-infra/history.md"
 
  - Infrastructure:
    - Data Infra:
      - Bumping Spark: "infrastructure/data-infra/bumping-spark.md"
      - Run-time environment guide: "infrastructure/data-infra/guide-to-the-runtime-environment.md"
      - Inventory: "infrastructure/data-infra/inventory.md"
    

### System information

Mac OS
Chrome

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting. However, please in general don't duplicate discussions. From what I understand you have two options:

1. Enumerate all links in the `nav` entry precisely in the order and with the titles you want them to appear
2. Use a plugin like [mkdocs-plugin-awesome-pages](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin)

It's probably best to check the [MkDocs plugin Wiki](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#navigation--page-building), as there are many options to choose form. Other than that, this is nothing that has to do with this project in particular (this is only a template), so I'm closing this issue.

**Comment by NavyaG-lab** [comment]
Sorry and Thanks much for sharing the links
