### ISSUE TITLE
Reason for excluding popstate events with a null state?

### ISSUE THREAD

**Issue by jbms** [squidfunk/mkdocs-material#2394]
I saw that instant navigation ignores popstate events where the state is null:

https://github.com/squidfunk/mkdocs-material/blob/5d0cae7ca6b77d5f8b7fb632b8be7d6421ecac81/src/assets/javascripts/integrations/instant/index.ts#L202

I observed in cases where there is a problem with the sitemap such that instant navigation is skipped for some pages but not all, we can end up with popstate events due to back/forward actions where the state is null.  As a result of the filter expression, those events are ignored and the content is not updated even though the URL is.

Removing the filter seemed to fix that issue and not cause any other issues.  So far I was only able to reproduce the issue while making some other changes that led to the sitemap URL list being incorrect, so perhaps this issue won't occur in practice, but I was wondering what the reason for the filter is at all.

**Comment by squidfunk** [comment]
I‘m answering from my cell so pardon the briefness - thanks for all your investigations regarding instant loading! As you may have seen, it’s a very complex topic. To address the open PRs (and questions like in this issue) we‘ll need reproducible examples where instant loading breaks down for each one of those. Without those cases, I’m not able to reason about the proposed changes.

Converting this issue to a discussion, as it is a question.
