### ISSUE TITLE
Handle URL parameters

### ISSUE THREAD

**Issue by Guts** [squidfunk/mkdocs-material#2396]
As discussed earlier, I suggest a feature to handle URL parameters to pass render options dynamically.

It could be useful to pass something like `https://doc.awesome-tool.app/module-x-explained.html?nav=false&header=false` and get an adapted render.

Example of parameters:

- `embed=bool`: when a page is integrated as iframe in external website 
- `nav=bool`: equivalent to set [page.meta](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hide-the-sidebars)
- `header=bool`: hide the horizontal menu

Use cases:

- in an application, open the page related to the actual plugin using the in-browser web view (Qt 5), disabling navigation or headers
- embed a page as iframe

_Originally posted by @Guts in https://github.com/squidfunk/mkdocs-material/discussions/2390_

**Comment by squidfunk** [comment]
This feature request hasn't received much attention from others, so it seems that this is rather an edge case than something that many users would find useful. The roadmap is full of useful features and will probably fill the time until the end of the year, so there's currently no time to invest in this topic. I hope you understand this decision! It shouldn't be too hard to implement it with some extra CSS and JS.

**Comment by Guts** [comment]
Yes, don't worry, I understand. I'll give it a try by myself.
