### ISSUE TITLE
Prompts with information about an article, e.g. "citation required"

### ISSUE THREAD

**Issue by Hitaro** [squidfunk/mkdocs-material#24]
Do you have any plan for prompts to be used in top of page showing some info about the article. They're very useful in wiki pages. Here are some examples:

![img1](https://cloud.githubusercontent.com/assets/18015032/14285197/e4ea021e-fb5f-11e5-81ab-6621f58c4907.png)

---
![img2](https://cloud.githubusercontent.com/assets/18015032/14285315/3d43b9e6-fb60-11e5-9cbd-71bf35ea79fb.png)

**Comment by squidfunk** [comment]
Currently there is no plan on integrating this, no. However, this could be easily solved with the admonition markdown extension:
http://squidfunk.github.io/mkdocs-material/getting-started/#admonition

Maybe you could start by defining some custom styles for your theme and share the results? I would also be interested in how many people would find that useful and worth integrating.

**Comment by Hitaro** [comment]
> start by defining some custom styles

I'm not a designer/programer; I just tried and made this by a painting tool:

![1](https://cloud.githubusercontent.com/assets/18015032/14763846/f3272580-09b7-11e6-95de-603fdeb3ee2a.png)
---
![2](https://cloud.githubusercontent.com/assets/18015032/14763850/fa98848a-09b7-11e6-92e8-e363ab92a275.png)
---
![3](https://cloud.githubusercontent.com/assets/18015032/14763852/00da1d18-09b8-11e6-95e5-9ffeffaa876d.png)

**Comment by squidfunk** [comment]
Have you tried to use the admonition style I referenced?
http://squidfunk.github.io/mkdocs-material/getting-started/#admonition

You can put this on top of the document:

```
!!! note "Citation required"
    This article does not cite any sources [...]
```
