### ISSUE TITLE
Consider removing the generated files from the git repository

### ISSUE THREAD

**Issue by jbms** [squidfunk/mkdocs-material#2400]
Currently you include the generated files in the git repository and update them on every commit.  This makes it easy for someone to use a git URL with `pip install` to directly install the latest (unreleased) version without even needing node.js.  However, it bloats the size of the repository, makes `git log -p` output hard to read, and makes merging more difficult as well.

I would suggest instead that you exclude the generated files from the repository, and instead modify setup.py to automatically build them as part of the build_py command.  That way they will be automatically built when preparing an sdist, binary wheel, or installing directly from a directory or git repository using pip install.  That way, users can install from a PyPI package without any building necessary (and without having node.js available), and can also install from a local checkout or git URL in a single step as they can currently (but in that case will need node.js).

If you are interested in that, I can provide a pull request.

**Comment by squidfunk** [comment]
Thanks for suggesting!

> Currently you include the generated files in the git repository and update them on every commit. This makes it easy for someone to use a git URL with pip install to directly install the latest (unreleased) version without even needing node.js. However, it bloats the size of the repository, makes git log -p output hard to read, and makes merging more difficult as well.

This is exactly the reason why the files are there. Removing them will make the theme not installable from git, which will also break Insiders, as it is currently only installable from git due to the problem that pip doesn't allow for private packages (and GitHub doesn't have support for `pip` yet). Even when this happens, I prefer keeping the generated files in the repository. I agree, that this blows up the size, but it's very convenient for users to try out fixes before a release.

**Comment by jbms** [comment]
As I mentioned, you can set up setup.py so that it invokes `npm install` and `npm run build` automatically as part of installation, so that the users can still install in the same way they do currently, as long as they have node.js available.

For example, that is what I have set up in https://github.com/google/neuroglancer

For insiders PyPI you could set up a github actions workflow that builds the generated files on each push, and then adds them and pushes them to another branch or repository.

**Comment by squidfunk** [comment]
> As I mentioned, you can set up setup.py so that it invokes npm install and npm run build automatically as part of installation, so that the users can still install in the same way they do currently, as long as they have node.js available.

Thanks! However, Node.js shouldn't be a dependency for the normal user. Note that this would also impact CI runtimes when installing from git, which is something I try to keep to a minimum at all times.

> For insiders PyPI you could set up a github actions workflow that builds the generated files on each push, and then adds them and pushes them to another branch or repository.

Moving the generated files to another branch or repository will make development more complicated and less predictable. Closing, as we're not considering changing the behavior.
