### ISSUE TITLE
Code blocks bleed out of side gutters for mobile using full width

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#2427]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Is code block meant to remain aligned to body copy (text) aka within the bounds of the side gutters, or break out of that at smaller widths to use full width?

`_highlight.scss`:

https://github.com/squidfunk/mkdocs-material/blob/c0c3a8fbf56a0a774cfa4b7a22b6a73f0bb2505f/src/assets/stylesheets/main/extensions/pymdownx/_highlight.scss#L244-L274

### Expected behavior

![Screenshot_20210311_114042](https://user-images.githubusercontent.com/5098581/110707752-a57e8100-825e-11eb-82b4-5415604e4946.png)

### Actual behavior

![Screenshot_20210311_114017](https://user-images.githubusercontent.com/5098581/110707726-97306500-825e-11eb-869b-0a2a76111ada.png)

### Steps to reproduce the bug

1. Visit https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#keys
2. View at width <720 px
3. View at width >720 px

### Package versions / Project configuration / System information

Active release used for project demo site: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#keys

**Comment by facelessuser** [comment]
This was a stylistic choice. It is not a bug and has been this way for a long time. With that said, not everyone may like it, and you can change it with CSS if you like.

**Comment by polarathene** [comment]
No worries, just confirming as the related CSS block implies the style causing it was intended to align to the text content, not full width.

I actually noticed it when I had made an adjustment to the side gutter width, which placed the code block inbetween the two states shown above, but disabling the full-width related style, resulted in the codeblock respecting the side gutters with the rest of the text content.

All good, will close if this is the intended behaviour.

**Comment by facelessuser** [comment]
Yeah, in mobile, the text of the code block aligns with the text outside the code block. The code background extends all the way to the edge. Doing it on desktop would look weird with the sidebars and such, but yeah, I can see it being unexpected to some. I've gotten used to it 🤷
