### ISSUE TITLE
Thai language search is missing

### ISSUE THREAD

**Issue by pinmu** [squidfunk/mkdocs-material#2440]
## Description

I tried to search in Thai, and it doesn't work, and Firefox reported 
```
GET http://test/assets/javascripts/lunr/min/lunr.th.min.js
[HTTP/1.1 404 Not Found 2ms]
NetworkError: WorkerGlobalScope.importScripts: Failed to load worker script at ../lunr/min/lunr.th.min.js
```
I found out in directory 
\site\assets\javascripts\lunr\min\
lunr.th.min.js is missing

Not quite sure if I should open a bug report here, but please suggest.  

### Steps to reproduce the bug

1. mkdocs build --clean
2. check if file lunr.th.min.js is missing from directory \site\assets\javascripts\lunr\min\

### Package versions

* Python: `python --version`  3.9.1
* MkDocs: `mkdocs --version` 1.1.2
* Material: `pip show mkdocs-material | grep -E ^Version`  7.0.5

### Project configuration

``` yaml
site_name: My Docs
theme:
  name: material
plugins:
  - search:
      lang:
        - th
        - en
```

### System information

* OS: Windows 10 
* Browser: Firefox
* Python for Windows

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by pinmu** [comment]
I noticed [a related issue](https://github.com/MihaiValentin/lunr-languages/issues/46)

**Comment by squidfunk** [comment]
Thanks for reporting! This is indeed an upstream issue, as the minified version of the Thai language is missing. Please report the issue in the `lunr-languages` repository.

**Comment by thammawat-s** [comment]
FYI, author of lunr-languages added the minified version of the Thai language couple days ago.  Thanks again.
