### ISSUE TITLE
Small update to code annotations docs

### ISSUE THREAD

**Issue by JulioV** [squidfunk/mkdocs-material#2443]
- [x ] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [ x] ... to my best knowledge, my idea wouldn't break something for other users
- [ x] ... the documentation does not mention anything about my idea
- [ x] ... there are no open or closed issues that are related to my idea

## Description

Highlight in the Code Annotations documentation section (maybe with a `hint`) that the inline/block codes have to follow the syntax of the code's language.

It is kinda obvious after you realize what the problem is, but my first instinct was to copy `// (1)` for a yaml block that required `# (1)`

**Comment by squidfunk** [comment]
Thanks for reporting, and yes, we should state that a little clearer 😊

**Comment by squidfunk** [comment]
Added a further note in 6f63baa9.
