### ISSUE TITLE
Page listing all "features" options

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#2465]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

It could be beneficial to have a page listing all current features that can be used in the `features` setting.

### Use Cases

Right now is there no clear indication of what "features" there are to use, as they are spread out across different pages.
As an example does the [Setting up site search](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/) page list some features, while others can be found in [Setting up navigation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/)

The page could list those options while linking to the pages/sections for more detail. It could also list possible issues/incompatabilities with other features.

The use-case is for having a better way to finding out what features there are because people like me have problems knowing or finding all features for MkDocs.

### Screenshots / Mockups

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by Andre601** [comment]
To add to this do the features seem to have the "Features Flag" category(?) set. Perhaps this could then link to the features page?

**Comment by Andre601** [comment]
I'm currently considering a possible place and/or structure for the page/section to be located at.
I believe having the page in the Reference section would be a good fit. Perhaps it could be named "Material Features" or just "Features".

The page itself could perhaps be split up into basic and Insiders-only features which themself would be split up into the different "categories" (navigation, search, toc) and link to the pages they're located at.

Another thing I would suggest is perhaps the usage of snippets for all the "Difficulty" and "Category" things...

I'll quickly cook something up to see what could look good and let you know about the outcome.

I was also considering making an actual discussion for this but aren't sure if it was worth the actual effort for this alone. If I should make a Discussion lmk (Alternatively could you transfer this issue to a Discussion. Whatever works best for you)

**Comment by Andre601** [comment]
Quick update: I now made a Commit on my fork that does the following changes:

- Use pymdownx's snippets to reuse often used code-parts.
This currently includes "insiders_only.txt" for the insider notice, "experimental.txt" for the Experimental notice, "feature_flag.txt" for the Feature Flag notice and "separator.txt" for that dot separator.
- reference/features.md page listing all currently available features. Currently sorted by general and insiders only category and into the respective categories, (headers, navigation, search, ...)

I also found a few wrong links, so if this won't become a thing should at least the corrected links be taken over.

Comparison: https://github.com/Andre601/mkdocs-material/compare/master...Andre601:feature/add-features-page

**Comment by squidfunk** [comment]
Thanks for your suggestions. We disabled Snippets on the documentation due to https://github.com/squidfunk/mkdocs-material/pull/2207

**Comment by Andre601** [comment]
Yeah. That seems to be a problem I guess... I'll let you decide stuff here.

**Comment by squidfunk** [comment]
I found some time to answer this tonight. So, the problem with this is, that I don't see much value in adding this page, because there are no examples or explanations, or screenshots that explain what you can do with the feature flags. Furthermore, if we would add that page, the contents would be redundant to the stuff that is contained in the respective pages this page would be linking to. Thus, it would mean that we would have to maintain three different places:

1. The page which contains the detailed info about the flag
2. The Insiders overview page
3. The feature flag overview page

I understand that an overview might be useful if you know what the feature flags are, but i when you don't. Also, there's more than just feature flags, for example how to use inline admonitions etc. Such an overview page would look like it's all that Material for MkDocs is offering, which it isn't. Things like code block annotations are buried in the code block reference.

Thus, I'm not considering merging this PR. I think a better approach would be to highlight specific, distinct features of Material for MkDocs on the landing page. At least, this is what I'm planning to do when I find some time, but for now the pipe is pretty full.

**Comment by Andre601** [comment]
I see it like this: The main problem from a viewer's perspective is, that all the different options you can add in `theme.features` are shared throughout multiple pages, so there is no simple way for you to know what all the "features" options are that Material provides.

Some are mentioned in the Navigation Setup page, Some in the Search Setup page and so on. This is quite frustrating if you want to utilize all the different features Material may offer.

So my idea was just to have a general hub to list the different features that can be enabled in the "features" setting, not to have a second place explaining them again.
You know, similar to like a Category page on MediaWiki: A place listing all pages (Sections) that belong in that particular category.

**Comment by squidfunk** [comment]
> I see it like this: The main problem from a viewer's perspective is, that all the different options you can add in theme.features are shared throughout multiple pages, so there is no simple way for you to know what all the "features" options are that Material provides.

The feature flags themselves are useless to a user without knowing what they do. This is why the setup guide is clearly structured into "setting up navigation", "changing the colors" etc. Furthermore, all of those guides are linked from the getting started guide, more specifically [creating your site](https://squidfunk.github.io/mkdocs-material/creating-your-site/#advanced-configuration).

> Some are mentioned in the Navigation Setup page, Some in the Search Setup page and so on. This is quite frustrating if you want to utilize all the different features Material may offer.

You would need to read the documentation anyway to know what the feature is doing.
