### ISSUE TITLE
Text instead of logo in the template header

### ISSUE THREAD

**Issue by tramponi** [squidfunk/mkdocs-material#247]
## Description

It would be a nice enhancement to let users replace the standard logo with custom text.

**Comment by squidfunk** [comment]
The logo is shown in the header, as well as in the drawer on mobile. What shall be replaced on mobile? I'm asking because the name of the project is listed under the logo on mobile inside the drawer and that would look rather strange.

**Comment by tramponi** [comment]
That's true...
Then maybe the best option would be to let users replace the logo with the name of the project:

- On desktop: The name of the project will be removed from the left menu

- On mobile: The logo will not be displayed

**Comment by squidfunk** [comment]
Hmm, but then mobile and desktop are inconsistent. I'm not really convinced on this approach. However, you can extend the theme and replace the header title.

**Comment by jsbUSMC** [comment]
I think that this kind of enhancement to the theme is best left as an override using custom partials. That's my 2¢ at least.

**Comment by squidfunk** [comment]
That sounds legit. Closing this issue for now.
