### ISSUE TITLE
[Docs]: Image docs should advise the use of CSS floats instead of `align` attribute

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#2491]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### `align` attribute is deprecated

The current image docs [advise using `align` attribute](https://squidfunk.github.io/mkdocs-material/reference/images/#image-alignment), but [MDN notes that is discouraged](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/align) and using CSS float left/right should be the preferred alternative.

Wouldn't it be better to instead have two utility classes that you can bundle to apply the left/right float and advise your users to use that instead?

Or just add a caution notice about using `align` and link to MDN, advising users to add the CSS themselves?

The utility class approach works well for the popular [Tailwind](https://tailwindcss.com/docs/float#float-right) (300kb gzipped, <75kb brotli, much less with filtered build step), and I see that [you've got some of your own already](https://github.com/squidfunk/mkdocs-material/tree/master/src/assets/stylesheets/utilities) :sunglasses:

### `loading` attribute phrasing

The image docs also [discuss lazy loading](https://squidfunk.github.io/mkdocs-material/reference/images/#image-lazy-loading), but describes it oddly. Default value is either `auto` or `eager` depending on browser with `auto` usually being equivalent to `eager`. It is a progressive enhancement, if `lazy` is used, and the browser doesn't recognize/support the attribute, the fallback is equivalent to `eager`.

Better phrasing would be:

> Modern browsers provide native support for enabling lazy-loading images through the loading attribute. Browsers lacking support have behaviour equivalent to `loading="eager"`.

**Comment by squidfunk** [comment]
Thanks for suggesting. In general, I agree, and am fully aware of `img.align` being deprecated. However, for the following reasons, IMHO, I think it's better to stick to using it:

- It's more portable, because any approach relying on CSS classes will not work outside of Material for MkDocs, like in Markdown previews.
- It's simpler for non-HTML/CSS folks to understand
-  Browsers will support it forever – `align=left` is mapped to the following implicit CSS declarations:

``` css
img[Attributes Style] {
  float: left;
  vertical-align: top;
}
```

Thus, I decided that we' ll leave it as it is. If you wish to use CSS classes for alignment, you may just add some extra CSS.

**Comment by polarathene** [comment]
>     * It's more portable, because any approach relying on CSS classes will not work outside of Material for MkDocs, like in Markdown previews.

Unless browsers drop support?

Markdown previews elsewhere generally don't always know/support attribute list feature, Github doesn't AFAIK?

There's other non-standard markdown syntax extensions used by mkdocs that also fall into this bucket of not being compatible for previews.

---

> It's simpler for non-HTML/CSS folks to understand

Sorry?

`{ align="right" }` vs `{ .align-right }`, how did it get more complicated to understand or use?

---

>     * Browsers will support it forever – `align=left` is mapped to the following implicit CSS declarations:

Do you have a source for this statement? Not the mapping, but that the support will remain forever?

It's been deprecated, as MDN points out. Deprecations don't equate to removal per se, but as the MDN mentions, support from modern browsers can be dropped if they decide to at some point.

---

> Thus, I decided that we' ll leave it as it is. If you wish to use CSS classes for alignment, you may just add some extra CSS.

That's fine, I don't mind managing it myself. I just wanted to raise the concern about it and see no real issue for preferring to use a CSS class as an improvement.

---

> I would be surprised if a browser would default to lazy-loading

I believe Chrome and Opera may do this under certain conditions for conserving bandwidth or power or at least that it was opt-in/experimental at some point if that's no longer the case any more.

This is for the `auto` behaviour which allows the browser to choose which is most appropriate. If you want a specific default that is deterministic, you specifiy it. Not all browsers (or CSS implementations for that matter) are consistent.

> which it's not how CSS works.

Not sure why we're bringing up CSS regarding this feature, as it has nothing to do with it?

---

> I would rather leave the phrasing as is, making it simpler for the user to understand.

I don't see how:

> *Modern browsers provide native support for lazy-loading images through the `loading` attribute, which degrades to eager-loading in browsers without support.*

Is more simpler and easier to understand than:

> *Modern browsers have native support to enable lazy-loading of images through the `loading` attribute. Browsers lacking support have behaviour equivalent to `loading="eager"`.*

But I guess that's just a matter of opinion. All good :+1:

**Comment by squidfunk** [comment]
I don't have the time to answer all of your questions, but here are at least some:

> Do you have a source for this statement? Not the mapping, but that the support will remain forever?

No. This assumption is based on my knowledge of the last 20 years of CSS and HTML specs, which I know quite well, as I've been reading them for the last 2 years in the process of building the product for my startup that is about to launch in the coming months, which will provide massively improved tooling for CSS. You'll be astonished what syntax constructs remain to work these days, e.g. setting `vlink` on the `body`. If browser support is dropped at some point, we can change the documentation.

> Not sure why we're bringing up CSS regarding this feature, as it has nothing to do with it?

Sorry, I meant HTML in particular, or progressive enhancement in general. Your suggestions were targetted towards making the docs correct in terms of the spec. However, the main goal of the documentation is for users to understand what certain flags or markup achieves, and IMHO your suggestion for the docs change might be more confusing to users.

> I think I'm allowed to express myself as disagreeing with the decision. If that's not permitted, please point that out in your Code of Conduct.

You are free to express your opinion, and it is in fact encouraged. If you feel that a downvote is necessary to express your opinion, go ahead.
