### ISSUE TITLE
Support navigation to individual items in Definition List

### ISSUE THREAD

**Issue by jasper-zanjani** [squidfunk/mkdocs-material#2495]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

In a knowledge base with many terms, using the [Definition list](https://squidfunk.github.io/mkdocs-material/reference/lists/#definition-list) extension as-is requires use of text search or simply scrolling. This is because there is no way to easily navigate to a specific Definition List item. If an `id` attribute were generated as it is for headings, users would be able to create links to the specific item in the body of the page.

### Use Cases

Any robust knowledge base that uses the Definition List for anything more than a handful of items would benefit, since the end-user would be able to use links to support navigation to individual items.

### Screenshots / Mockups

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by jasper-zanjani** [comment]
In case this feature would be better supported in the extension itself, I posted another issue there as well.

**Comment by squidfunk** [comment]
Thanks for suggesting. Unfortunately, we can't do anything about it as part of this project, since we only get the Markdown as rendered HTML. However, as pointed out in https://github.com/Python-Markdown/markdown/issues/1123#issuecomment-808279594, it's already possible to achieve it with some manual work and the Attribute List extension 😊
