### ISSUE TITLE
Highlight inline fenced blocks

### ISSUE THREAD

**Issue by digitalcraftsman** [squidfunk/mkdocs-material#25]
Currently, it's not easy to differentiate between `fenced inline blocks` and links inside a paragraph. This could be solved by adding a slightly visible background like on GitHub.

**Comment by squidfunk** [comment]
This is on my roadmap and will be solved in the next version I'm working on.

**Comment by squidfunk** [comment]
I changed the highlighting to GitHub-style highlighting (makes totally sense) to distinguish it better from links. Let's give it a try.
