### ISSUE TITLE
Render sections as tabs

### ISSUE THREAD

**Issue by ppo** [squidfunk/mkdocs-material#2514]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Allow to display content blocks as [tabs](https://material.io/components/tabs).

### Use Cases

- Install procedures for different OSes.
- Code examples for different technologies.

### Screenshots / Mockups

```
!!! tab "First Tab"
    ### A First Tab
    Any normal Markdown code.

!!! tab "Second Tab" :thumbsup:
    ### A Second Tab
    Any normal Markdown code.
```

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by facelessuser** [comment]
Are you confusing tab syntax? Or am I misunderstanding your request?

```
=== "First Tab"
    ### A First Tab
    Any normal Markdown code.

=== "Second Tab :thumbsup:"
    ### A Second Tab
    Any normal Markdown code.
```

<img width="712" alt="Screen Shot 2021-03-31 at 7 24 17 AM" src="https://user-images.githubusercontent.com/1055125/113151274-28598280-91f2-11eb-8479-a55de1aded00.png">

**Comment by ppo** [comment]
Damn! That's exactly it.
🙏 Sorry, I promise I checked the doc.  
I was probably to oriented on find something starting with "tabs" 😕
