### ISSUE TITLE
Add anchors to definition list items

### ISSUE THREAD

**Issue by timvink** [squidfunk/mkdocs-material#2515]
## Description

Add an anchor to [definition lists](https://squidfunk.github.io/mkdocs-material/reference/lists/#using-definition-lists).

From:

![image](https://user-images.githubusercontent.com/5570380/113138622-58227d80-9226-11eb-8968-cfa7d196242d.png)

To (on hover):

<img width="802" alt="Screenshot 2021-03-31 at 13 37 01" src="https://user-images.githubusercontent.com/5570380/113138609-4f31ac00-9226-11eb-8fda-ca91cc0fa018.png">

### Use Cases

Now, you can directly link to a definition list item using the anchor.

**Comment by squidfunk** [comment]
Thanks for suggesting! How should that work? The Markdown extension doesn’t generate any IDs.

**Comment by facelessuser** [comment]
You can define IDs with `attr_list`:

```
name { #test }
: description
```

You can access them manually

```
http://localhost:8000/#test
```

But you'd need some kind of extension to walk the HTML tree and add anchor links that a user could click. There is currently no extension that does this for definitions.

**Comment by squidfunk** [comment]
Yeah, I’m already doing that in the Material docs with Attribute lists, but there would need to be something that generates permalinks. As this is something that would need to be done by an upstream extension (or plugin), I’m closing this feature request.

**Comment by timvink** [comment]
Makes sense, thanks for thinking along!
