### ISSUE TITLE
Make collapsible sections remain open when switching pages

### ISSUE THREAD

**Issue by Henry055** [squidfunk/mkdocs-material#2518]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Currently when you have collapsible sections/subsections (without using `navigation.expand`) they don't remain open when switching to different pages. My suggestion would be to make them stay open when switching between different pages instead of having every section close on a single page switch.

### Use Cases

This would be beneficial to me and other people using collapsible sections/subsections because it feels very sharp and sudden for users when every section they had opened instantly closes because they clicked another page. I believe having them remain open would feel much smoother and more fluid, creating a better experience for the user.

### Screenshots

 **Sections opened by user:**
<img width="245" alt="1" src="https://user-images.githubusercontent.com/73945068/113201112-14993500-9261-11eb-9a0b-1f881ca3e782.png">

**Sections auto-closed by clicking a different page:**
<img width="245" alt="Screenshot 2021-03-31 at 20 37 51" src="https://user-images.githubusercontent.com/73945068/113201364-52965900-9261-11eb-834b-6d255bfc0e3a.png">

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Update: I'm currently not considering implementing this feature. The general recommendation is to use a combination of other features to achieve a smaller substructure, such as tabs and sections, and then enable automatic expansion.
