### ISSUE TITLE
Config option to exclude sourcemaps, lunr (non-english support), etc

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#2519]
- [ x ] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [ x ] ... to my best knowledge, my idea wouldn't break something for other users
- [ x ] ... the documentation does not mention anything about my idea
- [ x ] ... there are no open or closed issues that are related to my idea

## Description

When deploying builds via CI, either for production or preview/staging deploys, it would be nice to have the option to strip away some bloat.

`mkdocs-material` bundles some source map files that are useful for development/debugging, as well as [some JS for `lunr` to support multiple languages](https://github.com/squidfunk/mkdocs-material/tree/master/material/assets/javascripts/lunr) _if configured_.

However, these are copied over into the build output regardless of usefulness, presumably because they are part of the themes files, and this is `MkDocs` doing it's thing.

---

```
**/*.min.{css,js}.map ~900 KB
assets/javascripts/lunr/ ~180 KB
sitemap.xml.gz 625B
```

Roughly 1.1 MB out a 3.4 MB build.

- Source maps aren't necessary for production builds.
- If you only support english (default), [there is no need for `assets/javascripts/lunr`](https://github.com/mkdocs/mkdocs/blob/fd5a890578574c2508a4f6dcbc11cb5f8d5c4886/mkdocs/contrib/search/prebuild-index.js#L17).
- You shouldn't need the gzipped sitemap afaik, most deployments will support providing gzip for assets on-demand.

---

`search/search_index.json` 300KB default, 1.4MB with pre-built index. I noticed that the markdown docs (built as HTML files) have a file weight of 1.4MB too. This json file is presumably required for search functionality.

`plugins.search.prebuild_index: true` requires `node` which isn't available in the Docker image, thus must be installed as a third-party. [The docs don't address this](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search), or mention the alternative value `python` instead of `true`. I haven't compared the output file, but it's roughly the same size as with `node`/`true`.

### Use Cases

For the current build in a project I work on, this excess uses about 33% of the build size. For every 1,000 builds that would be 1GB of unnecessary bandwidth transferring from CI to production/staging services. In some cases, that can incur costs or contribute towards a monthly bandwidth budget/limit with a service plan.

---

I understand this is likely out of scope of the project, despite it providing the bulk of the files contributing to the excess. If so, no worries, for those where this is a concern, each can DIY a step in their CI after builds to remove the files.

I'm only raising a request here as it makes sense to centralize that removal for users of the project that provisions most of it.

[1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting! Definitely beyond the scope of this project:

- Source maps are useful for debugging and tracking down sources of errors
- `sitemap.xml.gz` is generated by MkDocs, not Material for MkDocs
- We can't selectively exclude files from the build, as we're only a theme, nothing more

Your options:

- Write a plugin which allows to exclude stuff from the build (maybe there already is one)
- Create an issue on MkDocs tracker to slim down the build

**Comment by polarathene** [comment]
I understand :)

You may still want to update your documentation for Docker users that try to build a search index as it'll fail otherwise.
