### ISSUE TITLE
The config option `site_url` should be documented under the troubleshooting section (or the issue with 404 support)

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#2520]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

- I've verified the issue against MkDocs, their own website deploy is configured in a way that has the issue.
- The problem is technically a config issue in `mkdocs.yml`, though it's also technically an upstream bug.
- Neither upstream or this project docs detail the workaround/solution.
- There are closed issues on both issue trackers related to this, but nothing has been done about it.

## Description

This is a common enough issue to trip over([1](https://github.com/squidfunk/mkdocs-material/issues/1878#issuecomment-684772532), [2](https://github.com/squidfunk/mkdocs-material/issues/853#issuecomment-414695689), [3](https://github.com/squidfunk/mkdocs-material/issues/1689), [4](https://github.com/squidfunk/mkdocs-material/issues/755#issuecomment-432928880), [5](https://github.com/squidfunk/mkdocs-material/issues/335), [6](https://github.com/mkdocs/mkdocs/issues/1785#issuecomment-486055224)) that it should ideally be documented. I raise it here for the benefit of this community, it may be better to briefly mention the solution in the [official theme docs troubleshooting section](https://squidfunk.github.io/mkdocs-material/troubleshooting/).

It may be suggested that this is an upstream issue and should be delegated there instead. Upstream has been aware of the issue for many years, yet a documentation note or a fix for it has not been taken care of. It would benefit your users to cover this in the themes docs for the time being.

Additionally, AFAIK not setting `site_url` prevents proper generation of `sitemap.xml` entries, which the `mkdocs-material` feature "Instant Loading" relies on, albeit that related issue is unaffected by a trailing slash in `site_url` for root domains IIRC.

### Expected behavior

No breakage, eg `404.html` file should correctly link to resources.

### Actual behavior

Breakage, eg `404.html` uses relative URL to resources, but is a single static file, thus only works from the project root.

### Steps to reproduce the bug

1. `mkdocs.yml` has a `site_url` without a trailing slash. Additionally this only applies to URLs without a subpath, the docs load from the domain root. Thus this excludes Github Pages, but can affect other popular deployments such as Netlify and Vercel, or self-hosting.
2. Viewing the `404.html` from the domain root will work correctly, from any subpath however where the path is invalid will use a relative URL that fails, eg: `/not/found/`.

This will not be reproducible via `mkdocs serve` due to development mode being handled differently via `MkDocs`. You must use `mkdocs build` and host that output (or just inspect `404.html`).

Any `site_url` with a subpath will correctly use an absolute URL to resources such as `<base-path>/assets/`. Those that are a domain root will become `<url-subpath>/assets/` not `<root>/assets/` aka `/assets/`, unless `site_url` adds a trailing slash.

### Package versions

`squidfunk/mkdocs-material:latest` (7.1.0)

### Project configuration

`mkdocs.yml`: https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml#L2

With a similar URL for `site_url` you can reproduce by adding/removing the trailing slash.

### System information

* OS: Linux
* Browser: Firefox

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm happy to merge PRs on the troubleshooting section. If you or somebody else wishes to write something up in a PR, I'm happy to collaborate. Other than that, there's no issue or actionable here, so I'm closing it.

**Comment by polarathene** [comment]
This [just got addressed in upstream](https://github.com/mkdocs/mkdocs/pull/2360) (fix rather than documentation) and should be available to `mkdocs-material` once it is able to include it.
