### ISSUE TITLE
Version selector not appearing when upgrading existing doc

### ISSUE THREAD

**Issue by heitorlessa** [squidfunk/mkdocs-material#2526]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

When upgrading an existing docs to use the new version selector with Mike, the version selector dropdown doesn't appear despite `versions.json` being present. 

Versions file: https://awslabs.github.io/aws-lambda-powertools-python/versions.json

My understanding is that this would only happen if `versions.json` file does not exist in the root of `gh-pages`, as I bumped into this before. Looking at the Network requests I don't see a call to fetch `versions.json` despite the file being accessible.

### Expected behavior

Version selector to appear as deployed here: https://heitorlessa.github.io/powertools-docs-versioning/

### Actual behavior

No version selector appears: https://awslabs.github.io/aws-lambda-powertools-python/latest/

### Steps to reproduce the bug

1. Start a blank `gh-pages`: `mike delete --all --push`
2. Update `mkdocs.yml` to include [versioning as described in the documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/)
3. Build & deploy current docs: `mike deploy --push --update-aliases <version> latest`
4. Set `latest` alias as default: `mike set-default --push latest`
5. Make any small change under `develop` branch and deploy a new version: `mike deploy --push --update-aliases develop stage`

### Package versions

* Python: `3.8`
* MkDocs: `1.1.2`
* Material: `7.1.0`

### Project configuration

Mkdocs.yml: https://github.com/awslabs/aws-lambda-powertools-python/blob/59fbefc1f6dfbd9f99e1f538dcd284e7a0e1cfbf/mkdocs.yml#L68

### System information

* OS: Linux (GitHub Actions)
* Browser: Latest firefox, also tried on Chrome and Safari

[1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
In your `mkdocs.yml`, remove the `s` in `extras`, and it should work.

**Comment by heitorlessa** [comment]
🤦‍♂️

**Comment by heitorlessa** [comment]
Thanks for taking the time to point out that typo @squidfunk . I knew it'd have to be something silly.
