### ISSUE TITLE
Scrollbar quirk in localization dropdown

### ISSUE THREAD

**Issue by Stanzilla** [squidfunk/mkdocs-material#2538]
- [ ] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... the problem doesn't occur with the default MkDocs template
- [ ] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

When hovering over the localization dropdown, a scrollbar appears for a split second

### Expected behavior

No scrollbar

### Actual behavior

Scrollbar

https://user-images.githubusercontent.com/75278/114208867-447dc200-995e-11eb-9dc1-482e2e4ab542.mp4

### Steps to reproduce the bug

1. Hover over dropdown

### Package versions

* Python: `3.9`
* MkDocs: `1.1.2`
* Material: `7.1.0`

### Project configuration

https://github.com/ManticoreGamesInc/platform-documentation

### System information

* OS: Win10
* Browser: Chrome 90

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Should be fixed with ff9e2841c. I removed the animation of `max-height` which was the reason for this.

**Comment by squidfunk** [comment]
Released as part of 7.1.1. Please reopen if the issue persists.
