### ISSUE TITLE
Docker issues with serving and building

### ISSUE THREAD

**Issue by Drgzidjiboy4ik** [squidfunk/mkdocs-material#2555]
1) I have created a simple project using `docker run --rm -it -p 8000:8000 -v ${PWD}:/ squidfunk/mkdocs-material new .`

2) When I try to serve using docker my localhost says "page not found" as if port was not exposed, though docker ps shows running

```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material serve
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
INFO    -  Documentation built in 0.26 seconds 
[I 210412 19:08:52 server:335] Serving on http://127.0.0.1:8000
INFO    -  Serving on http://127.0.0.1:8000
[I 210412 19:08:52 handlers:62] Start watching changes
INFO    -  Start watching changes
[I 210412 19:08:52 handlers:64] Start detecting changes
INFO    -  Start detecting changes
```

3) When I build new project using docker I face the problem of not working links.
```
docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /docs/site 
INFO    -  Documentation built in 0.21 seconds 
```
After I open /site/index.html the front page is loaded, but whenever I click any link, or even that fancy icon on the top left corner of the screen I am redirected to a list of all files in current folder. And only if I choose index.html in that folder, I ll get redirected to front page again. Same problem occurs when I build your project from here https://github.com/squidfunk/mkdocs-material.

Front page is build, but whenever I try to go to another page, I get list of all files into my face, and only after clicking index.html the page is opened. 
3.1) When I open index.html in site folder my browser shows: file:///home/demaunt/Downloads/mkdocs-material-master/site/index.html
3.2) When I click "quick start" my browser shows file:///home/demaunt/Downloads/mkdocs-material-master/site/getting-started
3.3) And only after I click "index.html" in the opend list of files the browser opens file:///home/demaunt/Downloads/mkdocs-material-master/site/getting-started/index.html

* OS: Ubuntu 20.04
* Browser: Google Chrome Version 89.0.4389.114 (Official Build) (64-bit)

P.S.: Sorry for my clumsy and rusty english, not a native speaker

**Comment by squidfunk** [comment]
Thanks for reporting. I've tested the latest Docker image (7.1.1) and it works as expected. Note that when you override the default command (which is `serve --dev-addr=0.0.0.0`), you need to add the `--dev-addr` flag.

Converting to discussion (not an issue but a configuration error).
