### ISSUE TITLE
Project's webpage does not display correctly

### ISSUE THREAD

**Issue by dsuch** [squidfunk/mkdocs-material#2587]
Hello,

when I opened https://squidfunk.github.io/mkdocs-material/ today, the page apparently did not display correctly. It was working fine yesterday in the sense that the layout was fine.

I am on Mozilla Firefox 87.0.

Below, please find a screenshot showing what I mean.

Thanks. 

![image](https://user-images.githubusercontent.com/553332/115516529-7cea9d80-a286-11eb-8097-e8044cc1c97a.png)

**Comment by codexetreme** [comment]
+1 I am facing the same issue, looks like some minified `main.<randomchars_here>.css` is giving a 404
![image](https://user-images.githubusercontent.com/8681139/115517513-d366d480-a2a4-11eb-83b5-7e37ce0123a3.png)

**Comment by squidfunk** [comment]
Oops, my fault. 😅 Thanks for reporting! Fixed in the last commit.
