### ISSUE TITLE
Tags support 🆕

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#2593]
__EDIT: Tags support is available as of Insiders 2.7.0! Check out the [demo](https://twitter.com/squidfunk/status/1388524913678561280) or the [docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/)__

---

Sometimes, it might be beneficial to group documents by specific tags, especially in very large codebases. There are some prior discussions on tag support on the MkDocs issue tracker (see below) and there is [mkdocs-plugin-tags](https://github.com/jldiaz/mkdocs-plugin-tags), which looks abandoned. In general I would consider the following features to provide a good first implementation for tag support:

- The author can specify tags as part of the front matter of a document, exactly like in other static site generators like Jekyll.
- Tags are rendered ~~below~~ above the actual content of the document
- Tags are rendered inside the search and can be searched like the title and text of a document
- There's an overview page that lists all tags and related articles (as provided by mkdocs-plugin-tags)

This is a sneak peek of how I would imagine tags to work inside search:

https://user-images.githubusercontent.com/932156/115960891-301bf680-a514-11eb-8f49-851c984541e8.mp4

This is how the tags overview page will look:

![screenshot-localhost-8000-tags-1619362962713](https://user-images.githubusercontent.com/932156/115998582-2d8ad100-a5e8-11eb-979f-727adcc54e68.png)

This will not be an integration of the said plugin, but a standalone integration into Material for MkDocs itself, because I believe for this to be useful, it will need to be integrated deeply (search etc.).

__Any feedback is appreciated!__

---

Prior discussions:
- https://github.com/mkdocs/mkdocs/issues/1828
- https://github.com/mkdocs/mkdocs/issues/1411
- https://github.com/mkdocs/mkdocs/issues/1243
- https://github.com/mkdocs/mkdocs/issues/759
- https://github.com/squidfunk/mkdocs-material/issues/1472

**Comment by squidfunk** [comment]
Tags support is available as of Insiders 2.7.0! Check out the [demo](https://twitter.com/squidfunk/status/1388524913678561280) or the [docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/)

**Comment by Stanzilla** [comment]
Love it, things to consider:

- Mention that you have to "install" mkdocs now via `./mkdocs-material` in `requirements.txt` when using a sub module / fork. 
- It would be nice if you could adjust the place the tag gets inserted in the template without having to touch the plugin itself

**Comment by Stanzilla** [comment]
Suggestion: add `tags` to the list of things that `hide:` can hide.

**Comment by rjahern5** [comment]
I am getting some warnings in the `tag` implementation when build.  Looks like everything 'works' fine though:
```
WARNING -  Documentation file 'tags.md' contains a link to 'api/some/page.html' which is not found in the documentation files. 
```

Looks like tags is explicitly referencing the page with the html extension instead of using md?

**Comment by squidfunk** [comment]
@rjahern5 thanks for reporting. Could you give me some more details? If you could boil it down to a reproducible case, it's probably a quick fix.

**Comment by rjahern5** [comment]
@squidfunk yes sir, I just created a small sample project and changed it to true but it is still giving the same issue.  I will open a different ticket for it.  Incredible feature and thank you!

**Comment by squidfunk** [comment]
@rjahern5 see #2638.

**Comment by squidfunk** [comment]
@rjahern5 the issue should be fixed in Insiders 2.7.2.

**Comment by Kanaduchi** [comment]
Is it possible to add Tags to some headers and not whole page?

Example, I have some page, which contains ###Header1. And I want to set tag "Deprecated" only for this header.

**Comment by squidfunk** [comment]
@Kanaduchi tags are defined on a page level, so they cannot be set for specific headers.

**Comment by Kanaduchi** [comment]
@squidfunk can it be considered as a separate enhancement? Such feature can be very useful

**Comment by squidfunk** [comment]
@Kanaduchi how would you imagine this to work, I mean from an authoring perspective? Tags are defined in front matter, which we can only define once per document.

**Comment by squidfunk** [comment]
The latest commit on Insiders addresses the following two ideas by @Stanzilla:

1. Tags can now be hidden on any page [using front matter](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#hiding-the-tags)
2. Tags are now rendered through a partial, making customization simpler. This made it necessary to render tags above the headline. If one wishes to move them below the content, this can now be done via regular theme extension.

I also adjusted the [installation instructions](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#with-git) to account for the built-in plugins which need to be installed when cloning from git.

Closing this issue. For all subsequent bug reports or feature requests, please open separate discussions or issues.
