### ISSUE TITLE
Layer missing on the menu header

### ISSUE THREAD

**Issue by camillo777** [squidfunk/mkdocs-material#261]
## Description

Hi. I have uploaded a video of mobile rendering on Android it seems there is some layer missing on the menu header; it should not scroll the background :

[](https://youtu.be/Sbt0JC2GJVo)

And I would advice that, on mobile, tapping out of the menu would automatically close the menu without have to click on the arrow.
With big screen phone it is annoying to go from right edge to left edge of the phone.

### Expected behavior

Do not scroll page below

### Actual behavior

The page below scrolls

### Steps to reproduce the bug

See the video

### Package versions

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: Android 6.0.1
* Browser: Chrome

**Comment by squidfunk** [comment]
Can you provide a link to the video?

**Comment by camillo777** [comment]
Sorry, it was not displayed, here it is:

https://youtu.be/Sbt0JC2GJVo

Thank you!

**Comment by squidfunk** [comment]
The layer is there in the video, so what do you mean is missing? Is it not clickable? The black layer should close the menu when touched. The scrolling is another story - preventing "scroll-through" is not possible in a cross-browser way, especially on mobile. However, I'm happy to receive input.

**Comment by camillo777** [comment]
I try to explain better :
1 the scroll problem which should be avoided because menu should be at a layer upper than the page. Currently it is not beautiful that touching over the upper layer  (menu) will scroll the bottom layer (background). But maybe it is not possible. 

2 the menu should close when I tap out of the menu when opened. The menu should remove focus from the content page. If I click out of the menu, it would be cool if the menu could close. 

I think I have seen it working on other sites but do not know of how to make it. 

Thank you 
Camillo

**Comment by squidfunk** [comment]
As written, sadly the scroll-through is not fixable. However, I provided a fix for the unresponsive overlay which was fixed with #264 and is now in `master`. Can you test it? I can only test on the Android emulator and it may not be accurate enough.

**Comment by squidfunk** [comment]
Fixed and released in 1.5.4
