### ISSUE TITLE
Native Graphviz integration

### ISSUE THREAD

**Issue by rodrigoschwencke** [squidfunk/mkdocs-material#2616]
Hello,

I know you're currently integrating **Mermaid.js**, which is of course a different but still very good choice.

Nevertheless, and Complementarily, I would find it useful for many users to also **Integate Graphviz NATIVELY** in your wonderful theme.

Until that happens, I have the pleasure to communicate that I have created an **[mkdocs-markdown-graphviz](https://gitlab.com/rodrigo.schwencke/mkdocs-markdown-graphviz)** extension  for mkdocs (just a continuation of other's work, which I found dysfunctionning : with mkdocs, and with Material Theme).

The **mkdocs-markdown-graphviz** extension renders SVGs and PNGs easily and integrates them in your **Material Theme**, **and more specifically with **Admonitions****, both opened by default or closed by default.

The **mkddocs-markdown-graphviz** extension is located at :

* pypi url : [https://pypi.org/project/mkdocs-markdown-graphviz/](https://pypi.org/project/mkdocs-markdown-graphviz/)
* GitLab Repo : [https://gitlab.com/rodrigo.schwencke/mkdocs-markdown-graphviz](https://gitlab.com/rodrigo.schwencke/mkdocs-markdown-graphviz)

You'll find more infos on the pages, but just for info:

## Installation is as follows:

$ pip install mkdocs-markdown-graphviz

## Usage

Activate the `mkdocs_markdown_graphviz` extension. For example, with Mkdocs, you add a
stanza to mkdocs.yml:

```yaml
markdown_extensions:
    - mkdocs_markdown_graphviz
```

To use it in your Markdown doc, 

with SVG output:

    ```dot
    digraph G {
        rankdir=LR
        Earth [peripheries=2]
        Mars
        Earth -> Mars
    }
    ```

or

    ```graphviz dot attack_plan.svg
    digraph G {
        rankdir=LR
        Earth [peripheries=2]
        Mars
        Earth -> Mars
    }
    ```

or with PNG:

    ```graphviz dot attack_plan.png
    digraph G {
        rankdir=LR
        Earth [peripheries=2]
        Mars
        Earth -> Mars
    }
    ```

Hope at least one person finds this useful :)

Thanks for your work,

**Comment by facelessuser** [comment]
Mermaid had a lot of styling and inclusion of JavaScript etc. I'm not sure Material would need to integrate anything for graphviz.

**Comment by squidfunk** [comment]
Thanks for suggesting. What would be necessary to do a __native__ integration? From what I can see from the linked repository, there's no extra JavaScript or loading logic to be added, as you're exporting SVGs and PNGs anyway, which is not the case for Mermaid as @facelessuser already noted.

**Comment by rodrigoschwencke** [comment]
You seem to be right. So it looks like the correct way to easily use graphviz with Material was this extension after all? if so, hopes it helps. Thanks again for your great job :)

**Comment by squidfunk** [comment]
No worries, thanks for writing the GraphViz plugin!
