### ISSUE TITLE
The style option of "linenums_style" should be "pymdownx-inline" instead of "pymdownx.inline"

### ISSUE THREAD

**Issue by nzhangac** [squidfunk/mkdocs-material#2632]
According to the document, `linenums_style` for code blocks has three options: `inline`, `table` and `pymdownx.inline`, but when set to `pymdownx.inline`, it works just the same as `table`! And after reading the document of PyMdown Extensions, I found the option should be `pymdownx-inline`.

Ref.
[1]. <https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlight>
[2]. <https://facelessuser.github.io/pymdown-extensions/extensions/highlight/#line-number-styles>

**Comment by squidfunk** [comment]
Good catch! Could you create a PR?

**Comment by squidfunk** [comment]
Fixed by #2633.
