### ISSUE TITLE
Rendering of indented code blocks concatenates lines

### ISSUE THREAD

**Issue by Paraphraser** [squidfunk/mkdocs-material#2639]
- [✅] I've read the [contribution guidelines] [✅] and agree with them

__I've found a bug and checked that ...__

- [✅] ... the problem doesn't occur with the default MkDocs template
- [✅] ... the problem is not in any of my customizations (CSS, JS, template)
- [✅] ... the documentation does not mention anything about my problem

	> not that I have been able to find

- [✅] ... there are no open or closed issues that are related to my problem

	> not that I have been able to find

## Description

I think there is a rendering problem with code blocks that are indented inside bullet and numbered lists, where individual code block lines are concatenated.

Every other markdown rendering engine I have tried renders each line inside the code fence on a line by itself. Material is the only rendering engine that seems to concatenate lines.

### Expected behavior

*in this case, the rendering is by GitHub (ie this issue) between the horizontal rules:*

<hr>

Lead in:

1. First:

	```
	$ sudo apt update
	$ sudo apt upgrade -y
	```

2. Second.

<hr>

### Actual behavior

*this is what Material seems to do (concatenation):*

<hr>

Lead in:

1. First:

	```
	$ sudo apt update $ sudo apt upgrade -y
	```

2. Second.

<hr>

### Package versions

```

$ python --version
Python 3.7.3

$ pip --version
pip 21.1.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)

$ mkdocs --version
mkdocs, version 1.1.2 from /home/pi/.local/lib/python3.7/site-packages/mkdocs (Python 3.7)

$ pip show mkdocs-material | grep -E ^Version
Version: 7.1.3

$ pip list | grep -e "^mkdocs"
mkdocs                      1.1.2
mkdocs-awesome-pages-plugin 2.5.0
mkdocs-material             7.1.3
mkdocs-material-extensions  1.0.1
```

### System information

```
$ uname -a
Linux sec-dev 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux
```

* Browsers: The problem is "browser independent". I have tried Safari, Firefox and Chrome, and on both macOS and iOS.

### Test setup

Directory structure:

```
$ tree .
.
├── docs
│   └── test.md
└── mkdocs.yml
```

Test file:

```
$ cat docs/test.md
Lead in:

1. First:

	```
	$ sudo apt update
	$ sudo apt upgrade -y
	```

2. Second.
```

Dump of test file:

```
$ hexdump -C docs/test.md 
00000000  4c 65 61 64 20 69 6e 3a  0a 0a 31 2e 20 46 69 72  |Lead in:..1. Fir|
00000010  73 74 3a 0a 0a 09 60 60  60 0a 09 24 20 73 75 64  |st:...```..$ sud|
00000020  6f 20 61 70 74 20 75 70  64 61 74 65 0a 09 24 20  |o apt update..$ |
00000030  73 75 64 6f 20 61 70 74  20 75 70 67 72 61 64 65  |sudo apt upgrade|
00000040  20 2d 79 0a 09 60 60 60  0a 0a 32 2e 20 53 65 63  | -y..```..2. Sec|
00000050  6f 6e 64 2e 0a                                    |ond..|
```

No extraneous whitespace. No weird characters. Standard Unix 0x0A line-endings. Last line terminated properly.

#### Test 1 - material
 
```
$ cat mkdocs.yml 
site_name: Test
site_description: 'demonstrate concatenated code-block lines'
theme:
  name: material
  features:
    - tabs
  plugins:
    - search
    - awesome-pages
```

<img width="765" alt="MATERIAL" src="https://user-images.githubusercontent.com/34226495/117395334-124e8880-af3b-11eb-8063-b65665c23ce7.png">

Notes:

1. Material runs the two `sudo` statements together.
2. Apart from changing the site name and description, this `mkdocs.yml` is "as it comes" from [SensorsIot/IOTstack](https://github.com/SensorsIot/IOTstack/blob/master/mkdocs.yml). I have, however, repeated all these tests **without** the "awesome-pages" and it makes zero discernible difference to the outcome.

#### Test 2 - mkdocs

```
$ cat mkdocs.yml 
site_name: Test
site_description: 'demonstrate concatenated code-block lines'
theme:
  name: mkdocs
  features:
    - tabs
  plugins:
    - search
    - awesome-pages
```

<img width="765" alt="MKDOCS" src="https://user-images.githubusercontent.com/34226495/117395394-298d7600-af3b-11eb-85a6-9099c30ec128.png">

"mkdocs" renders the `sudo` statements on two lines. 

#### Test 3 - readthedocs

```
$ cat mkdocs.yml 
site_name: Test
site_description: 'demonstrate concatenated code-block lines'
theme:
  name: readthedocs
  features:
    - tabs
  plugins:
    - search
    - awesome-pages
```

<img width="765" alt="READTHEDOCS" src="https://user-images.githubusercontent.com/34226495/117395413-34e0a180-af3b-11eb-8e83-12fd61323963.png">

"readthedocs" renders the `sudo` statements on two lines. 

#### Test 4 - MacDown (side-by-side markdown editor)

<img width="746" alt="MACDOWN" src="https://user-images.githubusercontent.com/34226495/117395437-42962700-af3b-11eb-820a-d08e2d962305.png">

"MacDown" renders the `sudo` statements on two lines.

#### Other examples:

Compare/contrast:

* [GitHub rendering](https://github.com/SensorsIot/IOTstack/blob/master/docs/Getting-Started.md)
* [mkdocs + material rendering](https://sensorsiot.github.io/IOTstack/Getting-Started/)

![LIVE](https://user-images.githubusercontent.com/34226495/117395461-4d50bc00-af3b-11eb-94df-c7de8798cb34.png)

I don't know what process is used to get the GitHub "original" to the mkdocs rendered version. The material point (pun intended) is that it doesn't occur on **my** hardware so the test results shown in this issue aren't likely to be explained by some peculiarity of my Raspberry Pi system.

It was, in fact, the other way around. I noticed the problem on the [IOTstack documentation pages](https://github.com/SensorsIot/IOTstack/tree/master/docs) and set about trying to see whether I could replicate the problem on my own hardware. I could, so the problem appears to follow Material.

**Comment by squidfunk** [comment]
I think you're missing the [SuperFences](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#superfences) extension. Add this to `mkdocs.yml`:

``` yaml
markdown_extensions:
  - pymdownx.superfences
```

**Comment by Paraphraser** [comment]
I just tried:

```
site_name: Test
site_description: 'demonstrate concatenated code-block lines'
theme:
  name: material
  markdown_extensions:
    - pymdownx.superfences
  features:
    - tabs
  plugins:
    - search
    - awesome-pages
```

If that's the correct syntax for adding that extension (no error came back when I ran `mkdocs`) then it made no difference. The lines were still concatenated.

**Comment by squidfunk** [comment]
The syntax is incorrect. `plugins` and `markdown_extensions` need to be at the top-level:

```
site_name: Test
site_description: 'demonstrate concatenated code-block lines'
theme:
  name: material  
  features:
    - tabs
plugins:
  - search
  - awesome-pages
markdown_extensions:
   - pymdownx.superfences
```

All code blocks in the docs are _always_ meant to be used from the top-level.

**Comment by Paraphraser** [comment]
Brilliant! Thanks so much.

![DF9C8DA7-8425-4410-8D09-6710A84BE083](https://user-images.githubusercontent.com/34226495/117422002-789ad180-af62-11eb-8ff4-72e1ee86364a.jpeg)

Any idea why Material needs this extra option? I'm thinking that if all the other renderers I tried didn't need a special setting, there must be some logical reason why Material has it off by default.

**Comment by squidfunk** [comment]
The `mkdocs` and `readthedocs` themes set `white-space: pre-wrap` on inline code blocks, which I, personally, find to be non-sensical. Thus, we do not set this CSS property. If you look closely, it doesn't render nicely, as the alignment is off and each line is highlighted separately:

<img width="507" alt="Bildschirmfoto 2021-05-07 um 10 53 55" src="https://user-images.githubusercontent.com/932156/117424863-892b5780-af22-11eb-9ec6-0d93429eb4c9.png">

If you wish for this behavior, it's one line of extra CSS after all.

**Comment by Paraphraser** [comment]
I did notice the misalignment but I didn't think it polite to remark on it, particularly when I had no idea what was going on.

Again, many thanks for this.
