### ISSUE TITLE
Redirection is improper with versioning

### ISSUE THREAD

**Issue by abhiTronix** [squidfunk/mkdocs-material#2647]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Hello,

I have discovered this annoying bug with versioning that make permalinks useless. Since I need to define permalinks to important headlines in my docs from `latest` version only _(since I cannot point to `v0.1` etc. which changes with every new release)_. But mkdocs-material/mike  on redirection drops the `#heading` part from URL and thereby rendering concept of permalink useless, as I cannot pinpoint some heading to my users.

### Expected behavior

Redirected address from `latest` to  some `v0.1.2` drops the `#heading` from url.

### Actual behavior

Must redirect to exact address without dropping heading

### Steps to reproduce the bug

https://squidfunk.github.io/mkdocs-material-example-versioning/latest/#project-layout is redirected to https://squidfunk.github.io/mkdocs-material-example-versioning/0.2/ instead of https://squidfunk.github.io/mkdocs-material-example-versioning/0.2/#project-layout 

### Package versions

* Python: 3.7.1
* MkDocs:  latest
* Material:  latest

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting. This is a limitation of mike, not Material for MkDocs, as [the generated redirects drop the hash fragment](https://github.com/squidfunk/mkdocs-material-example-versioning/blob/fbe5be4c1bc64c2c2bb6719b551059e244ad2d47/latest/index.html#L10) (this is the versioning example). You may open an issue on mike’s repository, as we can’t do anything about this.
