### ISSUE TITLE
An invalid link

### ISSUE THREAD

**Issue by Nthily** [squidfunk/mkdocs-material#2656]
![W(IJ51%9SA406WY@8LVL5@B](https://user-images.githubusercontent.com/31311826/118027569-5f2ec680-b362-11eb-9df7-9b3e7b0e65a7.png)

https://squidfunk.github.io/mkdocs-material/reference/code-blocks/

It's at the bottom here

**Comment by squidfunk** [comment]
Thanks for reporting, fixed in 42501992d.
