### ISSUE TITLE
Add info about link colors to documentation

### ISSUE THREAD

**Issue by hello-binit** [squidfunk/mkdocs-material#2659]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

As stated [in the docs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color), the primary color is used for many components, such as the header and the links. While we might want the header to be a lighter color, links are usually in a dark blue color. It should be helpful to most users configuring colors to know how to modify the link color variable. It took me some digging to find the "--md-typeset-a-color" variable. I think it should be sufficient to add a single line to the documentation, under the [Custom color schemes](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes) section:

```
[data-md-color-scheme="whatever"] {
  --md-primary-fg-color:        #EE0F0F;
  --md-primary-fg-color--light: #ECB7B7;
  --md-primary-fg-color--dark:  #90030C;
  --md-typeset-a-color:         #0550b3;
}
```

Some information on the typeset CSS variables should prove useful to users when choosing a color scheme for their documentation. Specifically, in my case, I chose a light color for the primary color, and needed to know how to set links to a darker color.

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting. Well, the stylesheet which lists all color variables is linked in the same paragraph, but I guess we could add some of the variables as "popular choices", as we did [here](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon), [here](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle) and [here](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#custom-syntax-theme).

**Comment by hello-binit** [comment]
Agreed, a "popular variables" section with brief descriptions could cover it. Could include:

- [md-typeset-color](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss#L76): font color of the text in paragraphs
- [md-typeset-a-color](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss#L77): font color of links while not being hovered on
- [md-primary-fg-color](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss#L41): primary color used for the header, the sidebar, text links and several other components
- [md-primary-fg-color--light](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss#L42): ??
- [md-primary-fg-color--dark](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss#L43): ??
- [md-primary-bg-color](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss#L44): accent color used for the header, hovered text links, and other components
- [md-footer-fg-color](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_colors.scss#L96): the primary color of the footer bar

**Comment by squidfunk** [comment]
So, I've decided against listing and describing all possible colors. It would be another list that would need to be kept in sync. For this reason, I added a comment in e2a1b679b, describing that the variable in question is used for `a` elements. Please note that customization is always something we cannot explain in all possible ways. The documentation already goes into great detail, I don't want to blow it up even more.
