### ISSUE TITLE
Add language label to code blocks

### ISSUE THREAD

**Issue by danierutu** [squidfunk/mkdocs-material#2661]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

I think it would be cool if codeblocks added a label with the language that they're formatted in. This label would be hidden when no language has been specified (or, as an alternative, would simply display "Plain text").

### Use Cases

Besides the code syntax and the color formatting, language labels help users understand better how a code snippet should be used. This is more noticeable when there are many code blocks in different languages within the same page.

### Screenshots / Mockups

I will leave some examples that I hope may serve as inspiration on how the label could be displayed.

**Discord** (actually Powercord, with some plugins)
![image](https://user-images.githubusercontent.com/63101447/118415146-fff5ec80-b6a8-11eb-9855-397aefb09b19.png)

**Microsoft Docs**
![image](https://user-images.githubusercontent.com/63101447/118415181-316eb800-b6a9-11eb-8f8b-4d0d706cbc91.png)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for suggesting. This was already discussed several times before but would need to be supported by the Highlight extension of [Python Markdown Extensions](https://github.com/facelessuser/pymdown-extensions/) which we use to parse fenced code blocks. We can't add this as part of Material for MkDocs, because the theme only sees the result of parsing. You could open an issue over at Python Markdown Extensions. If support is added, we could add some styling.

Until then, this issue can be closed.

**Comment by facelessuser** [comment]
If pymdownx was to do anything, it would probably simply allow people to inject some data attribute where CSS could be used to add a header title.

There is already an issue opened for adding this functionality and it is on my list. It is unlikely that I would alter the Pygments HTML formatter extensively to auto-add headers, but data attributes that people can add and then use CSS to assignment things seems reasonable.

Additionally, custom fences are available allowing for a user to extensively override output is they like.

**Comment by facelessuser** [comment]
If material wanted to standardized some kind of format for the Material theme, we could add a custom fences override in the material extensions package, much like how we provide custom Material icons.

**Comment by squidfunk** [comment]
`data-*` attributes would be perfect, as previously discussed! We could leverage that to add precisely this feature, so everything with `data-*` would just have to be passed through before Pygments can steal it.

**Comment by facelessuser** [comment]
The good thing with this approach is that you could set anything for a header title opposed to just the language name.

**Comment by squidfunk** [comment]
Exactly. Maybe we could also add a flag, which automatically sets the language as a `data-language`attribute? Currently this information is completely lost with pygments.

**Comment by facelessuser** [comment]
Yeah, I was considering exactly this. Maybe it just copies the language name there by default unless a user overrides that data attribute name manually.

**Comment by squidfunk** [comment]
Jup, sounds like a good solution.

**Comment by danierutu** [comment]
I like that solution too. Being able to add custom labels would allow, for example, to specify the filename that the code belongs to.
