### ISSUE TITLE
Support or document centering of image content

### ISSUE THREAD

**Issue by polarathene** [squidfunk/mkdocs-material#2674]
- [x] I've read the [contribution guidelines][1] and agree with them

[1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

**TL;DR:** Docs have no advice on center alignment. Users are expected to add custom CSS + `attr_list` and know what CSS to use. Not an issue for me, not a great UX for users less comfortable with CSS.

---

The docs for [image alignment](https://squidfunk.github.io/mkdocs-material/reference/images/#image-alignment) mention _left_ and _right_ alignment but not _center_. That is because _center_ is not supported by `align` attribute (which is deprecated as mentioned in https://github.com/squidfunk/mkdocs-material/issues/2491).

One might infer that this means `img` elements are by default centered, which is not the case, they're treated as inline elements.

Popular CSS utilities like Tailwind CSS opt to default `img` to `display: block` which is half of what's required. Centering can use `margin: 0 auto`, or explicit `margin-left` + `margin-right` set to `auto` if setting top/bottom margin to 0 is undesirable.

This does not break usage of `align` attribute with _left_ and _right_ which will take priority, but could _center_ align by default anything that hasn't declared explicit alignment preference.

Alternatively, if the linked issue solution was approved, the documentation could just advise users to use `.align-left`, `.align-center`, `.align-right` classes (which would not break existing `align` attr usage, or any expectations on `display: inline` default for `img`.

Centering image content within a page would seem fairly common enough and reasonable to want. `mkdocs-material` could provide alignment utility CSS classes out of the box; rather than requiring users to DIY with custom CSS addition each individually.

### Use Cases

Convenience to center an image in the document without adding additional customizations and simpler documentation.

Presently any advice for centering images is missing, but detailing how to add CSS to support it is more complicated for users than just changing the `attr_list` syntax advised to use classes.

### Screenshots / Mockups

From linked related issue, this question was left without a response, but is valid for this feature request.

> `{ align="right" }` vs `{ .align-right }`, how did it get more complicated to understand or use?

---

- [Related issue](https://github.com/squidfunk/mkdocs-material/issues/748#issuecomment-377705567) from 2018 discussing adding CSS classes via `attr_list`, a prominent user chimes in stating they do this often to center images within their own documentation.
- [Related issue](https://github.com/squidfunk/mkdocs-material/issues/1635) from a year ago introducing a CSS solution (but inadvisable syntax as it would be seen as a fragment for SVG files).
- [Semi-related issue](https://github.com/squidfunk/mkdocs-material/issues/1419) centering the sidebar menu logo and title for aesthetic reasons. The feature request here would not resolve that, and that issue could be another feature request or defer users to custom CSS.

**Comment by squidfunk** [comment]
It's already supported! 😊 Just use a `figure` element, as described in [the docs](https://squidfunk.github.io/mkdocs-material/reference/images/#image-captions):

``` HTML
<figure markdown="1">
![image](https://dummyimage.com/600x400/eee/aaa)
</figure>
```

You can even set captions on figures. 

Regarding the alignment attributes vs. classes discussions see https://github.com/squidfunk/mkdocs-material/issues/2491#issuecomment-808869991. Markdown content (= body copy) is wrapped in `.md-typeset` which will always only add styling to tags, not classes. The only exceptions are `.focus-visible` (due to lack of browser support + polyfill) and the `.md-typeset__scrollwrap` and `.md-typeset__table` classes which are needed for overflow scrolling of tables.

**Comment by polarathene** [comment]
That requires enabling HTML within markdown content (using the `markdown="1"` attribute, which your docs example excludes), and adds more verbosity than what has been proposed here.

> Just use a `figure` element, as described in the docs

The docs page does not mention using `<figure>` to achieve centering. Note the title is "Support **or document**". It specifically focuses on caption support. A reader should not assume this implicitly means the maintainer officially supports this as a stable way for centering content that isn't subject to breakage in future?

---

> Regarding the alignment attributes vs. classes discussions see #2491 (comment).

> > 1. Markdown previews.
> > 2. simpler for non-HTML/CSS folks to understand
> > 3. Browsers will support it forever

1. **Invalid.** Non-standard syntax is already supported throughout the documentation, eg admonitions.
2. **Contradiction.** You're asking them to use HTML with an attribute for mkdocs specific extension that needs to be enabled. I proposed the existing `attr_list` extension advice, but with class names that retain the `align` prefix, supports centering in the same manner for consistency and doesn't break existing users docs to introduce.
3. **Assumption.** MDN is very clear that this is not the case and should not be relied upon "forever".

---

> Markdown content (= body copy) is wrapped in `.md-typeset` which will always only add styling to tags, not classes.

Here's a few cases where that's not true and the class is paired with these in it's selectors:

- `.md-content__button`
- `.admonition.hint`
- `details.tip`
- `.tip>.admonition-title`
- `.hint>summary`
- `.important>.admonition-title`

I'm not sure why you're so heavily resistant towards this suggestion, none of these reasons seem valid. It's a simple improvement that benefits your users. Minimal addition and maintenance, keeps alignment intent consistent (arbitrary fig HTML does not).

I don't think there's anything else I can do to convince you, so I'll leave it at that.

**Comment by leaanthony** [comment]
Apologies for the necromancing, but the figure solution does not appear to work correctly if there's 2 images (light/dark) within the figure tag. One is centred and the other is left aligned. After trying countless different configurations, the only thing that appeared to work was the following:

```
<p align="center">
   <img src="./static/clir_logo.png#only-light" width="30%">
   <img src="./static/clir_logo_white.png#only-dark" width="30%">
</p>
```

**Comment by squidfunk** [comment]
You can create a bug report. Please also create a reproduction for this – it's all described in the issue template.
