### ISSUE TITLE
Provides a plugin to optimise images (resize, placeholder)

### ISSUE THREAD

**Issue by tychota** [squidfunk/mkdocs-material#2675]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

**Loading images is a pain.**
  
Too big images could **slow the webpage** loading by a bunch.  
It would be great if mkdocs could optimize the rendering of the image.

Hopefully, the tech has evolved in the last 5 years, with support for:
- `<figure>` HTML component
- SVG / blurhash placeholder 

For example, another web static content generator (gatsby) provides plugins to:
- resize image
- generate a placeholder image (eg using blur hash: https://blurha.sh/)
- wrap the low res and high res image in a `<figure>` HTML component

Checks for instance: https://using-gatsby-image.gatsbyjs.org/

### Use Cases

- This would improve loading page
- This would prevent the flickering effect.

### Screenshots / Mockups

| Loading| Loaded |
|---|---|
|![image](https://user-images.githubusercontent.com/13785185/118820799-e3c79a80-b8b6-11eb-8b51-3e9c21260f78.png)|![image](https://user-images.githubusercontent.com/13785185/118821791-deb71b00-b8b7-11eb-817d-7a5d63532b97.png)|

## Notes

As it is doable inside a plugin, I would say it would be a nice addition for the `mkdocs-material` (insiders?), and at least does require to be implemented in `mkdocs` itself.

My company (BAM) is sponsoring MKDocs Material.  
Also, I may be available to help implement this, with some guidance, if that is easier for you.

**Comment by facelessuser** [comment]
I have to be honest, MkDocs Material is a theme. MkDocs plugins should be implemented as a separate thing. Material does at times add styling for a given plugin, but that is about it. Usually, it focuses on features related to the theme, not necessarily content generation.

**Comment by squidfunk** [comment]
Thanks for suggesting! I believe that this is a perfect candidate for a third-party plugin, as it's not exclusive to this theme (all themes will benefit). I find the idea excellent and would be happy to feature it in the documentation.

**Comment by facelessuser** [comment]
I don't speak for Material though, so I will let @squidfunk  comment 🙂.

**Comment by squidfunk** [comment]
@facelessuser fully agree. The only thing where Material for MkDocs deviates from this path is by providing a built-in `tags` plugin as part of the newest Insiders build. Once the funding goal is reached, we might cut that out into a separate project (or not, haven't decided yet).

**Comment by tychota** [comment]
All clear and valid concerns.

Your suggestion is that I reach "MkDocs" directly?

My fear about doing a plugin on my own is that I will put a lot of effort now but maybe later, I won't use MkDocs anymore and thus the plugin will be more or less unmaintained. I always prefer to contribute to some kind of organization.  
Gatsby for instance have a lot of "core" plugins in the main repo https://github.com/gatsbyjs/gatsby/tree/master/packages

Also, I'm unsure what would be requested on a technical side? I guess that we can somehow hook into markdown parsing and detect an image, and then look for image files matching and performs some operation to generate the placeholder.  
But there is a lot of "unknown unknown" and I fear starting that task alone without expert guidance.

@waylan you seems to be the actual maintainers of mkdocs

![image](https://user-images.githubusercontent.com/13785185/118842243-517cc200-b8c9-11eb-9802-936f792aae16.png)

What do you think of all this?

@squidfunk let's see if @waylan answers here and if he agrees for having a plugin that is part of the core, I will close this issue and open one on the mkdocs repo, and follow up there. 
When that is done, I will reopen the issue here so we can link the plugin in the mkdocs-material documentation.

**Comment by facelessuser** [comment]
That may be so with Gatsby, but generally, MkDocs provides the main core and leaves it to the community to build up useful plugins. This keeps the maintenance cost low for the project, but allows the flexibility so that anyone can develop and maintain plugins.

**Comment by squidfunk** [comment]
I'm pretty sure that the maintainers of MkDocs will not want something like this in the core, because it would mean they would have to maintain it. It's the same for me. I try to strive for a balance regarding stuff I can commit to maintaining in the future and stuff I can't. This plugin, right now, is in the latter category. Material for MkDocs already has tons of features which I agree to maintain.

The MkDocs plugin system is fragmented, true, but quite lively. Closing as out-of-scope.

**Comment by tychota** [comment]
Make sense. Thanks for the clarity and the honnety. 

I think on my side that handling image loading should be core, for mkdocs or gatsby, as it impacts a lot the user perception of speed of the docs. I think it is a selling points of one system compared to another, and a bunch of users would like optimized images. 

But indeed, it has nothing to do in mkdocs material. 

I will see how it goes.

**Comment by waylan** [comment]
As explained, we do not include plugins with MkDocs directly. All plugins should be developed as separate projects from the core. In addition to keeping the maintenance burden down, it also frees the plug-in from MkDocs' slower development cycle

**Comment by tychota** [comment]
OK, thanks @squidfunk and @waylan for explanation.

I will try my best to build an image compression/placeholder pipeline plugin. And ask for help if needed.

**Comment by squidfunk** [comment]
Material for MkDocs now ships the [built-in optimize plugin](https://squidfunk.github.io/mkdocs-material/setup/building-an-optimized-site/#built-in-optimize-plugin), which automatically compresses all images it finds in your documentation. This is just the start, as the following features will be added in the coming weeks:

1. Alternate formats: Conversion to more modern formats (WEBP + AVIF) while always providing fallbacks
2. Alternate sizes: Conversion and generation of alternate sizes for responsive images
3. Blurred previews that are inlined for faster loading
4. Automatic setting of dimensions to mitigate content shift
