### ISSUE TITLE
Sticky content tabs

### ISSUE THREAD

**Issue by sriumcp** [squidfunk/mkdocs-material#2678]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

When I choose "C" in hello world section on top, I also want "C" to be chosen in the good bye world section at the bottom. Ditto for C++.

***

## Hello world
=== "C"

    ``` c
    #include <stdio.h>

    int main(void) {
      printf("Hello world!\n");
      return 0;
    }
    ```

=== "C++"

    ``` c++
    #include <iostream>

    int main(void) {
      std::cout << "Hello world!" << std::endl;
      return 0;
    }
    ```

## Intervening material
A bunch of text here... because ... there are other things that intervene... and need to be said.

## Goodbye world
=== "C"

    ``` c
    #include <stdio.h>

    int main(void) {
      printf("Goodbye world!\n");
      return 0;
    }
    ```

=== "C++"

    ``` c++
    #include <iostream>

    int main(void) {
      std::cout << "Goodbye world!" << std::endl;
      return 0;
    }
    ```

### Use Cases

In the above made-up example, it is easy for end-users to select "C" hello world and "C++" good bye world, unintentionally, which would end up not working. Sticky tabs would avoid this issue.

More generally, tabbing provides a way to describe how an idea would work in multiple environments. If the idea has multiple steps in it, stickiness would ensure the use can try out the idea in a specific environment in a sane way without errors of the above type.

### Screenshots / Mockups

Please see [this discussion thread](https://github.com/squidfunk/mkdocs-material/discussions/2676) for additional context.

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
I've wanted to implement this for a long time and happy to announce that Insiders 2.9.0, which was just released, ships with support for [linking of content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linking-content-tabs). See [this tweet](https://twitter.com/squidfunk/status/1396434860789616644) for a demo.
