### ISSUE TITLE
Global Navigation Path

### ISSUE THREAD

**Issue by EndyCZ** [squidfunk/mkdocs-material#2692]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Add one additional row between the logo and the tabs in the header. This row would contain a high level documentation navigation path created by a list of links separated by a slash "/" (or other form of visual separation). These links would **not** be related to nav section in the mkdocs.yml file.

This row would be configured in the mkdocs.yml as a list of links with "name" and "URL". I can image putting it in the "extra" section but that is up to the discussion.

### Use Cases

Given a case, where there are a lot of products and lot of different personas using the products, it would help me as a reader to understand where exactly I am in the documentation structure.

A product can have several different personas using the product. In general a documentation should be focused to a specific persona i.e. an application developer (or contributor) and end user.

Example usage of the path

> Root product overview page / Persona name / Documentation product name

The inspiration is coming from the Microsoft Documentation for Windows. https://docs.microsoft.com/en-us/windows/uwp/

The use case is basically when you want to have multiple GitHub repositories containing documentation for specific product and specific persona and you want some way of navigation between them.

### Screenshots / Mockups

Here is how I imagine how it could look like.

![image](https://user-images.githubusercontent.com/75783243/119322867-61f0bc00-bc7e-11eb-9e88-1108ebaf861b.png)

And the mkdocs file 

![image](https://user-images.githubusercontent.com/75783243/119323267-cca1f780-bc7e-11eb-9b99-eeed871243f4.png)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for suggesting! So basically, you're asking for some kind of a breadcrumb navigation. This could be custom-implemented by overriding the `hero` block, which are included just before the tabs navigation. See the [customization](https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks-recommended) docs how to do this.

There's currently no plan to add this functionality into core.

**Comment by EndyCZ** [comment]
Correct. I have created this issue because I want to implement this . I wanted to double check if it could be interesting to add it into the core functionality.

**Comment by squidfunk** [comment]
Thanks for offering your help. However, this is too specific to be integrated into the core.
