### ISSUE TITLE
Meta source with custom link in repo_url

### ISSUE THREAD

**Issue by ngtrian** [squidfunk/mkdocs-material#270]
Seem meta "source" don't working in custom repo_url without have ssl (https)

I using custom repo_url in mkdocs.yaml

```yaml
site_url: http://docs.nopviet.com
repo_url: http://nopviet.com
```

and in document markdown:
```markdown
description: Nếu bạn vừa mới bắt đầu làm quen với nopCommerce, hãy theo các bước dưới đây để thiết lập và khởi chạy cửa hàng.
path: members
source: an-nguyen.1
```

And my result in browser
http://docs.nopviet.com/nopviet.com/members/an-nguyen.1

**Comment by squidfunk** [comment]
Fixed in 1.6.0
