### ISSUE TITLE
Provide a better default title for "seealso" admonition

### ISSUE THREAD

**Issue by johnthagen** [squidfunk/mkdocs-material#2700]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

Special case `seealso` admonition to display as "See Also" rather than "Seealso"

### Use Cases

By default, enabling the admonition extension: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition

And using the `seealso` admonition:

```md
!!! seealso

    See this.
```

Produces a title like:

<img width="794" alt="Screen Shot 2021-05-26 at 7 51 08 AM" src="https://user-images.githubusercontent.com/10340167/119655094-2c231300-bdf7-11eb-8658-7ffeaed95fcf.png">

The user can manually fix every instance to make this read nicer, but it's a chore and can be easily forgotten:

```md
!!! seealso "See Also"

    See this.
```

<img width="810" alt="Screen Shot 2021-05-26 at 7 52 00 AM" src="https://user-images.githubusercontent.com/10340167/119655227-58d72a80-bdf7-11eb-973d-7deff72fa254.png">

`seealso` is unique in the list of supported admonitions in that it's the only one that is composed of two words: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types

That is why, presumably, title casing works for all of the others out of the box.

**Comment by johnthagen** [comment]
As prior art, Sphinx breaks this into two words:

```rst
.. seealso::

   See this.
```

<img width="833" alt="Screen Shot 2021-05-26 at 8 00 57 AM" src="https://user-images.githubusercontent.com/10340167/119656295-85d80d00-bdf8-11eb-9dc1-8b7cf3cf2900.png">

**Comment by squidfunk** [comment]
Thanks for reporting. I agree, that it's suboptimal. Unfortunately, we can't do anything about default admonition titles, as Material will only see what was rendered by Python Markdown. Thus, you can raise your issue over at Python Markdown.

**Comment by johnthagen** [comment]
In case anyone finds this issue, `!!! seealso` has been deprecated: bcbe24224c9c8ad4f84edf70f4cfebd89c775fd3
