### ISSUE TITLE
The outdated warning displays the wrong link on some old versions but not all

### ISSUE THREAD

**Issue by JulioV** [squidfunk/mkdocs-material#2701]
- [ x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ x] ... the problem doesn't occur with the default MkDocs template
- [ x] ... the problem is not in any of my customizations (CSS, JS, template)
- [ x] ... the documentation does not mention anything about my problem
- [ x] ... there are no open or closed issues that are related to my problem

## Description
The outdated warning displays the wrong link on some old versions but not all 

### Expected behavior

Display a warning with a link to the latest version on all old versions

### Actual behavior

Display a warning with a link to the current old version on some old versions

### Steps to reproduce the bug

Bad links:

- https://www.rapids.science/dev/
- https://www.rapids.science/1.1/

Good links:

- https://www.rapids.science/1.0/
- https://www.rapids.science/0.4/

### Package versions

* Python: `python --version` Python 3.7.9
* MkDocs: `mkdocs --version` version 1.1.2
* Material: `pip show mkdocs-material | grep -E ^Version` Version: 7.0.7+insiders.2.4.0

### Project configuration

``` yaml
site_name: RAPIDS
site_url: https://www.rapids.science/
...
extra:
  version:
    provider: mike
...
theme:
  name: material
  custom_dir: docs/overrides
```

My main HTML

```html
{% extends "base.html" %}

{% block disqus %}
  <!-- Add custom comment system integration here -->
  {% include "partials/integrations/utterances.html" %}
{% endblock %}

{% block outdated %}
  You're not viewing the latest stable version of RAPIDS.
  <a href="{{ config.site_url | url }}">
    <strong> Click here to go to latest. </strong>
  </a>
{% endblock %}
```

This is the returned versions.json for a good and bad link

Good link (v0.4):

```json
[{"version": "1.2", "title": "1.2", "aliases": ["latest"]}, {"version": "1.1", "title": "1.1", "aliases": []}, {"version": "1.0", "title": "1.0", "aliases": []}, {"version": "0.4", "title": "0.4", "aliases": []}, {"version": "0.3", "title": "0.3", "aliases": []}, {"version": "0.2", "title": "0.2", "aliases": []}, {"version": "0.1", "title": "0.1", "aliases": []}, {"version": "dev", "title": "dev", "aliases": []}]
```

Bad link (v1.1):

```json
[{"version": "1.2", "title": "1.2", "aliases": ["latest"]}, {"version": "1.1", "title": "1.1", "aliases": []}, {"version": "1.0", "title": "1.0", "aliases": []}, {"version": "0.4", "title": "0.4", "aliases": []}, {"version": "0.3", "title": "0.3", "aliases": []}, {"version": "0.2", "title": "0.2", "aliases": []}, {"version": "0.1", "title": "0.1", "aliases": []}, {"version": "dev", "title": "dev", "aliases": []}]
```

This is the command I use to deploy a numbered version in [GA](https://github.com/carissalow/rapids/blob/master/.github/workflows/docs.yaml)

```python
mike deploy --push --update-aliases $DOCS_TAG latest
```

This is the command I use to deploy a dev version in [GA](https://github.com/carissalow/rapids/blob/master/.github/workflows/docs.yaml)

```python
mike deploy --push --update-aliases dev
```
### System information

* OS: MacOS 11.3.1
* Browser: Firefox 88.0.1 (64-bit) (same problem in Chrome)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting! I'll look into it.

**Comment by squidfunk** [comment]
Which mike version did you use to deploy 0.4 and 1.1 respectively?

**Comment by JulioV** [comment]
I think it was v1.0.0 for 1.1 and dev and v0.6 for 1.0 and older

**Comment by JulioV** [comment]
I think is related to this issue and the canonical URL in each vXX/index.html https://github.com/jimporter/mike/issues/40

**Comment by squidfunk** [comment]
Jep, we need to adjust the example in the docs. Using `config.site_url` is no longer valid.

**Comment by JulioV** [comment]
I just realized this also breaks search, would it make sense to recommend setting a canonical version in mike?

```yaml
plugins:
  - mike:
      canonical_version: latest
```

**Comment by squidfunk** [comment]
Indeed, search isn't rendered anymore with newer versions of `mike`. Hmm. I can't say whether the canonical setting fixes it, I'll look into it as soon as possible.

**Comment by squidfunk** [comment]
So, I think I've got a working solution. The documentation now lists the most generic approach (i.e. not dependent on installation location or absolute links) to return to the top-level, which will then redirect to the latest version:

``` html
{% block outdated %}
  You're not viewing the latest version.
  <a href="{{ '../' ~ base_url }}">
    <strong>Click here to go to latest.</strong>
  </a>
{% endblock %}
```

a0cacd325 updates the example in the docs. I've also redeployed the [versioning example](https://squidfunk.github.io/mkdocs-material-example-versioning/) with the new override and verified that it works. Of course, the URL can be replaced with an absolute link, if known, omitting the need for a redirect. It's just that we need to provide solutions in the documentation that are as generic as possible.

Regarding search – yes, mike 1.0 seems to disable it. I have no idea why. I've create https://github.com/jimporter/mike/issues/58, let's see whether this is now intended behavior. If it is, we must add a note to the documentation, but my guess is that it's a bug. Thus, this issue can be considered resolved. Note that you'll need to re-deploy the affected versions of your documentation after updating the partial to fix the issue on your side.

**Comment by jimporter** [comment]
> I just realized this also breaks search, would it make sense to recommend setting a canonical version in mike?
> 
> ```yaml
> plugins:
>   - mike:
>       canonical_version: latest
> ```

Note that if you want the search plugin and also want to specify other plugins in your `mkdocs.yml`, you need to [list the search plugin too](https://www.mkdocs.org/user-guide/configuration/#plugins):

> If the `plugins` config setting is defined in the `mkdocs.yml` config file, then any defaults (such as `search`) are ignored and you need to explicitly re-enable the defaults if you would like to continue using them:
> ```yaml
> plugins:
>     - search
>     - your_other_plugin
> ```
There's also a bug in mike, in that it doesn't "inherit" the default value of `plugins` from MkDocs before injecting the mike plugin. That'll be fixed shortly in jimporter/mike#58 though.

**Comment by jimporter** [comment]
Ok, I've merged a fix for the issue where mike disables the search plugin when you don't have a `plugins` setting in your `mkdocs.yml` (it now treats the default value as `['search']` like MkDocs does before injecting the `mike` MkDocs plugin). I've tested it (briefly) on my end, but if you can verify that it all works as expected for you now, that'd be a big help. Then I can publish mike v1.0.1.

**Comment by squidfunk** [comment]
Thanks for the quick fix! here's what I did to verify:

1. `pip install git+https://github.com/jimporter/mike.git`
2. I removed the `plugins` entry from `mkdocs.yml` and re-deployed using mike - and the search was there!

**Comment by jimporter** [comment]
Great! I'll publish v1.0.1 today or tomorrow then.

I also didn't know about using `git+https` URLs with `pip`, so I'm going to remember that for future use! :)

**Comment by JulioV** [comment]
All good, thanks to you both
