### ISSUE TITLE
Documentation clarification: Emoji use requires material theme

### ISSUE THREAD

**Issue by b-trav** [squidfunk/mkdocs-material#2707]
- [X] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

Firstly, let me say, I think MkDocs and mkdocs-material are fantastic! Thanks for such a useful product.

## Description

Not sure if this is a feature request or a bug in the documentation. I am suggesting some clarification in your documentation. I followed the instructions in <https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji> to get emoji working in MkDocs. The emoji appeared on the screen, but were HUGE. The reason for this was that I was not using the material theme (so there was no rules about twemoji in the stylesheets). It was not obvious to me that you MUST be using the material theme in MkDocs to use emoji, so mentioning that might save others the time I spent trouble-shooting,

If you think this is obvious, then please feel free to ignore this feature request.

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by facelessuser** [comment]
> It was not obvious to me that you MUST be using the material theme in MkDocs to use emoji, so mentioning that might save others the time I spent trouble-shooting,

1. You do not need to use Material to use the [Emoji](https://facelessuser.github.io/pymdown-extensions/extensions/emoji/) extension. It doesn't care what MkDocs theme you use, nor is it an extension specific to MkDocs.
2. While the Emoji extension can be used by anyone, it does not inject CSS into your HTML results, you must add sufficient CSS, usually restraining the size is enough.
3. While emoji are supported, the icons that Material provides, which are exposed via the emoji extension (octicons, material, and etc.) are only available with the Material theme.

**Comment by squidfunk** [comment]
Thanks for reporting. The Material for MkDocs documentation only speaks for itself, not for other themes or extension. Thus, I consider it obvious.
