### ISSUE TITLE
Search do not support utf8 first character

### ISSUE THREAD

**Issue by ngtrian** [squidfunk/mkdocs-material#271]
Can not searching word have first charactor with 
`đ`

**Comment by squidfunk** [comment]
This is an issue with a dependencies, namely [lunr.js](https://github.com/olivernn/lunr.js/). Please report it in their issue tracker. Material only uses the library and makes no further alternations to the source (like stemming or transliteration).

**Comment by squidfunk** [comment]
Maybe this can be solved with the multi language features of lunr.js - directly related to https://github.com/squidfunk/mkdocs-material/pull/245

We need to check whether your problem goes away, when we load language support for Thai (?), if lunr supports this language.

**Comment by ngtrian** [comment]
thanks @squidfunk
