### ISSUE TITLE
Cannot remove footer generator message

### ISSUE THREAD

**Issue by paulo-coutinho** [squidfunk/mkdocs-material#2712]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

Hi,

When i use settings:

```
extra:
  generator: false
```

The footer still with the generator message.

![image](https://user-images.githubusercontent.com/395096/120092877-97692f80-c0ec-11eb-9954-5c12bde2b440.png)

Can anyone help me?

Thanks.

### Expected behavior

Generator message need be removed.

### Actual behavior

Generator message is visible.

### Steps to reproduce the bug

use settings:

```
extra:
  generator: false
```
### Package versions

* Python: `3.9.5`
* MkDocs: `1.1.2`
* Material: `7.1.5`

### Project configuration

``` yaml
extra:
  generator: false
```

### System information

* OS: macos bigsur
* Browser: chrome

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thanks for reporting! The feature works as expected, but it's currently only available to users of Material for MkDocs Insiders:

<img width="225" alt="Bildschirmfoto 2021-05-30 um 10 22 30" src="https://user-images.githubusercontent.com/932156/120097479-f6509800-c130-11eb-805b-fad4bdf47cc7.png">

You can get access to Insiders, and this + 14 other exclusive features by sponsoring the project, see:
https://squidfunk.github.io/mkdocs-material/insiders/

**Comment by paulo-coutinho** [comment]
Hi,

Ok, i like this project. It is very well designed.

I'm a sponsor now.
