### ISSUE TITLE
Add lang= attribute to <html> element in base.html

### ISSUE THREAD

**Issue by paulgibbs** [squidfunk/mkdocs-material#274]
## Description

In base.html, the root `<html>` tag ought to have a `lang` attribute to control the document language. It's a recommended attribute in the HTML5 spec, and it's useful to many browsers and accessibility tools.

https://www.w3.org/TR/html5/semantics.html#the-html-element

### Expected behavior

A new config option, like `extra.language`, would accept a value such as `"en"` or `"de"`, which would be printed into the base.html template, like so: `<html lang="de" class=...`

### Actual behavior

The absence of `<html lang` is causing accessibility review tools, such as aXe (https://www.deque.com/products/axe/), to report warnings about the document having an unspecified language.

### Steps to reproduce the issue

1. Open a page generated with mkdocs + mkdics-material.
2. Use the aXe plugin for Chrome to run an accessibility check.
3. Observe it reporting the absence of `<html lang=`. 

### Package versions

* Python: 2.7.9
* MkDocs: 0.16.3
* Material: 1.5.4

### Project configuration

See https://github.com/paulgibbs/behat-wordpress-extension/blob/master/mkdocs.yml

**Comment by squidfunk** [comment]
Accessibility is a big topic and this fix is only the start. I would like to make Material more accessibly, but to decide how to implement it, we need a concept on what has to be done and what has to be configurable. For this reason I would like to put this issue into a greater context and collect the things that have to be improved for accessibility. Just adding the `lang` attribute is not enough.

**Comment by squidfunk** [comment]
The tag was added in 1.6.0 and can be changed through localization. The idea is: if you want to change the language, you almost certainly also want to change the localizable labels - therefore one source of truth.
