### ISSUE TITLE
Gitter.im link in CONTRIBUTING.md gives a 404

### ISSUE THREAD

**Issue by mattbostock** [squidfunk/mkdocs-material#276]
## Description

The link to Gitter on this page returns a 404:
https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md#got-a-question-or-problem

### Expected behavior

I expected to see a Gitter chat room.

### Actual behavior

I saw a 404 'Not found' page.

**Comment by squidfunk** [comment]
Fixed in #278 - thanks for reporting!
