### ISSUE TITLE
License comments lined up at the end of .min.js files

### ISSUE THREAD

**Issue by mhpe** [squidfunk/mkdocs-material#2761]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

## Description

The license comments in `bundle.min.js` and `search.min.js` seem oddly placed (at the end of the files, not in-between code blocks), was that an intended change from version 6 to version 7?

**Comment by squidfunk** [comment]
Thanks for reporting. It's the [default behavior of ESBuild](https://esbuild.github.io/api/#legal-comments) which we're using from v7 on. Honestly, I don't care where they are, so yes, we can move them inline to their respective sources if there are no downsides like increased bundle size after `gzip`. ESBuild is parametrized here, so feel free to PR:

https://github.com/squidfunk/mkdocs-material/blob/94dd748634166af210cfa32578c6ca9ef916afe1/tools/build/transform/index.ts#L169-L176

Please include a bundle size comparison after `gzip` into the PR.

**Comment by squidfunk** [comment]
Fixed in a4a00af01.

**Comment by squidfunk** [comment]
Released as part of 7.1.9
