### ISSUE TITLE
Logo title does not match link 

### ISSUE THREAD

**Issue by rizerzero** [squidfunk/mkdocs-material#2763]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

In addition to the custom home page URL for the logo, we should also be able to change the title.

```
extra:
  homepage:
  homepage_title:
```

### Use Cases
Right now I have documentation with site_name: Documentation, and I have the logo of my app which redirects to MyApp homepage thanks to the feature extra homepage. The issue is that when I hover over MyApp logo, I have the title 'Documentation' which is not the correct one anymore, and if I change the site name to match the name of my app then I have the logo which is a texte "MyApp" and the text MyApp displayed by the template. 

### Screenshots / Mockups
Example with an Android logo that would redirect the android.app and not documentation 
![image](https://user-images.githubusercontent.com/1518379/122051420-dda8d900-cde4-11eb-9196-6b8b6711505f.png)

Right now if I want the title of the logo to be android then it will result in a duplication.
![image](https://user-images.githubusercontent.com/1518379/122051876-5d36a800-cde5-11eb-95e3-ab07e409369c.png)

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
Thank for suggesting. Please see an explanation in https://github.com/squidfunk/mkdocs-material/pull/2747#issuecomment-857978843 why this will not be added.
