### ISSUE TITLE
GET /%E8%AE%A1%E7%AE%97/ HTTP/1.1" code 404  不支持中文名称md文档

### ISSUE THREAD

**Issue by quinnhao** [squidfunk/mkdocs-material#2764]
问题如下：
我引用中文目录时候遇到了问题，页面展示：404 - Not found

CLI 报错如下： "GET /%E8%AE%A1%E7%AE%97/ HTTP/1.1" code 404

mkdocs.yml 配置文件如下：
```
site_name: My Docs
site_url: https://example.com/
theme:
  name: material
nav:
    - 首页: index.md
    - 测试1: 测试1.md
    - 测试2: 测试2.md
```
我尝试了windows系统， ubuntu系统，mac系统，都无法在目录中引用中文名称的markdown的文档，但我看其他人的blog 中是支持中文的，但他们的不是最新版本，难道是作者在最新版本中选择不支持中文的markdown文档吗？ 希望各位大牛可以解惑，谢谢！

**Comment by quinnhao** [comment]
> 对不起，我不懂中文。你能用英文解释一下是什么问题吗？

Questions are as follows:
I have encountered a problem when using Chinese to set the navigation, click on the navigation bar to prompt the page to display: 404-Not found

The CLI error is as follows: "GET /%E8%AE%A1%E7%AE%97/ HTTP/1.1" code 404

The mkdocs.yml configuration file is as follows:

site_name: My Docs
site_url: https://example.com/
theme:
  name: material
nav:
    - 首页: index.md
    - 测试1: 测试1.md
    - 测试2: 测试2.md

I tried windows system, ubuntu system, mac system, and I can’t quote markdown documents with Chinese names in the directory, but I see other people’s blogs support Chinese, but theirs is not the latest version, the author is in the latest version. Do you choose not to support Chinese markdown documents? Hope you guys can solve your doubts, thank you!

**Comment by squidfunk** [comment]
This is a general MkDocs issue and has nothing to do with Material for MkDocs in particular, as it will also happen with other themes. Please create an issue over at https://github.com/mkdocs/mkdocs.

**Comment by quinnhao** [comment]
Thank you for your guidance，I had create an issue  https://github.com/mkdocs/mkdocs/issues/2463
Looking forward to someone answering, good luck.
