### ISSUE TITLE
Honor reduced motion preference for code block animations

### ISSUE THREAD

**Issue by janLo** [squidfunk/mkdocs-material#2765]
- [x] I've read the [contribution guidelines][1] and agree with them

__I want to suggest an idea and checked that ...__

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

## Description

We use the the code block annotations currently in insiders. The feature works great but the annotation links have a small animation attached to them. 

Although enhances the usability in general as the user can easily spot the anchors it creates issues if:
* documentation is read over a remote-desktop-protocol like RDP/X2Go/VNC
* documentation is read within a virtual machine without native graphics acceleration because the software rendering then uses a lot of CPU (about 20% for four anchors on a i7-8565U).
 
I'd like to ask if its possible to implement a configuration switch to deactivate the animation.

### Use Cases

Build documentation for environments where animations cause issues with certain groups of readers.

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by janLo** [comment]
I already found a way that works for me - adding the following extra style sheet:

```css
.md-annotation__index {
    -webkit-animation: none;
    animation: none;
}
```

I still think it would be simpler to have this as a configuration option but it's not a priority anymore :).

**Comment by squidfunk** [comment]
Thanks for suggesting - this should definitely be customized via CSS, so thanks for sharing your solution!

**Comment by janLo** [comment]
This sounds like a good path. Alternatively a mention in the documentation might be sufficient in my opinion. Thank you.

**Comment by squidfunk** [comment]
The latest commit on Insiders now adds support for reduced motion for code block annotations:

https://user-images.githubusercontent.com/932156/122370293-3e5c2100-cf5f-11eb-86cc-9e5eb6ae5d59.mp4

Honestly, I haven't considered VNC being an application for motion reduction but it makes perfect sense. I'll revisit possibilities for further reduction of motion in the coming weeks. Code block annotations are a good start.

**Comment by janLo** [comment]
This pulsating is back since the last insiders - can you point me to the right selector to disable it again? I seem to be blind myself.

**Comment by squidfunk** [comment]
It's a regression then, sorry for that. I'll reopen this issue.

**Comment by janLo** [comment]
Ah, I found it by stepping again through the elements. Its just `.md-annotation__index:after` now it seems.

**Comment by squidfunk** [comment]
I've just checked the official docs and `prefers-reduced-motion` is correctly honored:

https://user-images.githubusercontent.com/932156/146004700-e7eccbd2-0545-4a1f-9485-26ea7d818666.mp4

Are you sure you're using the latest version?

**Comment by janLo** [comment]
I have it statically disabled via CSS as its easier than trying to suggest chnages to browser-settings to the consumers of the documentation ;).

**Comment by squidfunk** [comment]
Okay, makes sense. I thought maybe you can indicate to a VNC client that it should set reduced motion as a system preference. So from your last message, I understand that the selector changed and you just needed to change those. 😊

Nothing to do here then, closing.

**Comment by janLo** [comment]
Thank you anyway!
