### ISSUE TITLE
Feature suggestion: show code block annotations as footnotes when printing a page

### ISSUE THREAD

**Issue by janLo** [squidfunk/mkdocs-material#2803]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The inline annotations for code blocks are great - but they get completely lost if a page gets printed (I know, who prints things these days … but sometimes documentation has to be provided as PDF).
My suggestion is, to render the list that gets used for the annotations in a footnote-size below the actual code block. This way the reader is still able to connect the numbers to some actual content.

### Use Cases

It would provide the inline annotation content on printed versions (no matter if on dead tree or in a PDF).

**Comment by squidfunk** [comment]
Thanks for your suggestion! You're right in that annotations are currently not rendered when printed, so this is definitely something to improve. In fact, rendering the annotations below the code block is currently already the fallback view when JavaScript is not available (e.g. when the page loads slowly), as this is how they are represented in Markdown. This should not be too difficult to achieve.

**Comment by squidfunk** [comment]
So this is trickier than expected, as the elements that are attached to the code blocks are effectively removed from the list below the code block when rendering the annotations. Idea: we could intercept `beforeprint` and `afterprint` events in order to add them back to the list during the printing process, and remove/inject them again when printing is done. Unfortunately, it's not solvable with CSS alone.

**Comment by squidfunk** [comment]
When printing, [`6f48cef`](https://github.com/squidfunk/mkdocs-material-insiders/commit/6f48cef38aefdd1d7859ea4cad4857c5f5f0c8f8) will now show the code block annotations in a list below the code block. Note that this is not the final implementation, as I need to flesh out some bugs on code block annotations in the coming weeks, which means I will probably rewrite and improve some parts of it, but for now this should already improve on the current behavior, which is indeed not optimal.

**Comment by squidfunk** [comment]
Released as part of 7.3.0+insiders-3.1.0
