### ISSUE TITLE
Feature Request: Set Navigation Level Depth with Expand Feature

### ISSUE THREAD

**Issue by Andrew5194** [squidfunk/mkdocs-material#2818]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I would like to be able to set the depth level of the nav items when using the `expand` feature. For example, right now with the current functionality, the `expand` feature auto-expands all items to the maximum depth of items that is associated. Instead, I want to be able to set the auto-expand depth to 2 levels. Thereby making something look like...

- Page 1
  - Page 1.1
  - Page 1.2
    - Page 1.2.1
  - Page 1.3
- Page 2
  - Page 2.1
  - Page 2.2

to

- Page 1
  - Page 1.1
  - Page 1.2
  - Page 1.3
- Page 2
  - Page 2.1
  - Page 2.2

### Use Cases

Cleans up the aesthetic of the nav pane. It's nice to have all items auto-expand to a certain limit as expanding all items to their maximum depth can also clutter up the nav pane.

**Comment by squidfunk** [comment]
Thanks for suggesting. I think we shouldn't be adding more and more navigation configuration options ([there are already a lot](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/)), as it makes the already quite complex templates even more complex. This increases maintenance cost as all combinations need to be tested when making a change, which eats up more of my limited time I could better invest working on other distinctive features.

For this reason, I kindly ask you to understand that I've decided that this is not a good fit for further consideration.

**Comment by Andrew5194** [comment]
@squidfunk no worries! The `navigation.tabs` and `navigation.sections` is basically what I needed. Thanks 🙏

**Comment by iBug** [comment]
This is the script that I'm using to achieve the feature:

```js
function load_navpane() {
  var width = window.innerWidth;
  if (width <= 1200)
    return;

  var nav = document.getElementsByClassName("md-nav__toggle");
  for (var i = 0; i < nav.length; i++) {
    if ((nav.item(i).id.match(/_\d/g) || []).length > 1)  // Here
      continue;
    nav.item(i).checked = true;
  }
}

document.addEventListener("DOMContentLoaded", load_navpane);
```

The script expands only the first level. Change the number 1 in the line with a comment for different levels, if desired.

**Comment by HarelM** [comment]
Is there a way to limit the right navigation sidebar depth?
For example in my case I need to limit the right sdiebar to method names, which are "###", meaning I don't want to see in the right sidebar "####".
Is it possible?
<img width="1276" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/3269297/dc802f9e-0c6c-41be-8886-41f16a369f38">

**Comment by squidfunk** [comment]
Yes, you can limit the table of contents by setting [`toc_depth`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.toc_depth) in `mkdocs.yml`, e.g. to hide level 4-6:

``` yaml
markdown_extensions:
  - toc:
      toc_depth: 3
```

**Comment by HarelM** [comment]
Thanks for the info!! I searched for that in both docs but didn't thought toc is the right settings.
Thanks!
