### ISSUE TITLE
Add a param in the mkdocs.yml file to allow for change of text alignment

### ISSUE THREAD

**Issue by BulletTech2021** [squidfunk/mkdocs-material#2819]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

Right now, it is kind of time consuming to find the correct CSS code to make the text justify-aligned. Expect to easily config this setting in the mkdcos.yml file.

### Use Cases

The agile update of text alignment can address of the needs of different formats

**Comment by squidfunk** [comment]
Thanks for suggesting. However, this has solely to do with representation and should be done with custom CSS.
