### ISSUE TITLE
Material hijacks browser search

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#282]
## Description

Material hijacks the browser search (<kbd>CMD</kbd>+<kbd>F</kbd>), which is not desirable.

### Expected behavior

<kbd>S</kbd> and <kbd>F</kbd> open the search box, <kbd>CMD</kbd>+<kbd>F</kbd> opens the browser search modal.

### Actual behavior

The search box opens.

### Steps to reproduce the bug

1. Press <kbd>CMD</kbd>+<kbd>F</kbd>

### Package versions

* Python: 2.7
* MkDocs: 0.16.3
* Material: 1.5.4

### System information

irrelavant

**Comment by squidfunk** [comment]
Fixed in #283 and released as part of 1.5.5.

**Comment by bkbncn** [comment]
Actually, I like the "feature" cmd+f to open search box, how can I keep it?
