### ISSUE TITLE
Make the tags in the tag index page ordered alphabetically

### ISSUE THREAD

**Issue by remipregh** [squidfunk/mkdocs-material#2851]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Would it be possible to have the tags in the tag index page ordered alphabetically? 

### Use Cases

It will improve the reader's experience and the page will look better structured overall.

**Comment by squidfunk** [comment]
Thanks for suggesting. It absolutely would.

**Comment by squidfunk** [comment]
That was easy 😊 Fixed in the latest Insiders release (and `master`, obviously).
