### ISSUE TITLE
Experimental search highlighting and search sharing feature fails

### ISSUE THREAD

**Issue by dangiankit** [squidfunk/mkdocs-material#2853]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The search plugin's experimental features `search.highlight` and `search.share` don't seem to work as intended. 

### Expected behaviour

1. Search highlighting would highlight the searched text on each search result by adding a `mark` tag around each search result which would eventually be highlighted either using `Pygments` or `highlight.js`. I even tried disabling `CodeHilite` in favor of the `Highlight` extension with `Superfences` extension along with `mermaid2`'s custom fences but it didn't seem to work as intended.
2. Search sharing icon would be seen on the Search box and would enable sharing of search term/results.

### Actual behaviour

1. No search highlighting on search results. `mark` tag not added.
2. No search sharing icon seen.

### Steps to reproduce

Take a look at [this commit](https://github.com/dangiankit/kgtk/commit/2697d638c1a8e5b844872803d8bdce3d15aa933d). 

### Package versions

- Python: 3.8.10
- MkDocs: 1.2.2
- Material: 7.1.11

### Configuration

```yaml
https://github.com/dangiankit/kgtk/commit/2697d638c1a8e5b844872803d8bdce3d15aa933d
```

### System information

- Operating system: macOS BigSur v11.1, Darwin Kernel Version 20.2.0, x86_64
- Browser: Google Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by dangiankit** [comment]
Looks like both of these are _Insiders only_ or _Exclusive features_ available to [sponsors-only](https://squidfunk.github.io/mkdocs-material/insiders/#how-to-become-a-sponsor)!

**Comment by squidfunk** [comment]
That’s correct, currently both Decatur’s re reserved to sponsors 😊

**Comment by dangiankit** [comment]
> That’s correct, currently both features are reserved to sponsors 😊

How did I then have access to `Search suggestions` feature even before `Biquinho Vermelho` is met? 🤔

**Comment by squidfunk** [comment]
Search suggestions are rendered in grey text directly in the search bar behind the text you entered. I think you mean search results, which are rendered below the search bar, or not?

**Comment by dangiankit** [comment]
I mean, auto-suggest (the drop-down list) as compared to auto-complete.

**Comment by squidfunk** [comment]
Yeah, search suggestions are auto-complete, so maybe it's just confusing wording.

**Comment by dangiankit** [comment]
Perhaps, [this image](https://i.stack.imgur.com/nXHX2.jpg) would help.

**Comment by squidfunk** [comment]
It would be incorrect, because we're not rendering search suggestions below the search bar, but search results, i.e. the actual documents.

**Comment by squidfunk** [comment]
With the [help of my awesome sponsors](https://twitter.com/squidfunk/status/1417847377793323010), I'm happy to tell you that we just reached the funding goal which will release those three features into the wild. Expect 7.2 within the next days, including all features from [Biquinho Vermelho](https://squidfunk.github.io/mkdocs-material/insiders/#2500-biquinho-vermelho)

**Comment by dangiankit** [comment]
Awesome!

**Comment by squidfunk** [comment]
7.2.0 was just released.

**Comment by dangiankit** [comment]
Thanks, @squidfunk -- that works!
