### ISSUE TITLE
Mermaid diagrams don't render

### ISSUE THREAD

**Issue by geraldschmidt** [squidfunk/mkdocs-material#2863]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I clone the central squidfunk/mkdocs-material repo, I can build the documentation fine, but the mermaid diagrams aren't shown as such.

I tried this after not getting my own documentation diagrams to work.

I also tried the workaround of pulling in the JavaScript library directly (the way documentation elsewhere suggests mermaid can be used) but that yields the "bomb" SVG and a note that the diagram definition is invalid. (I have tested the diagram in the mermaid live viewer.) I've also tried to disable minification (`minify-html: false`) in the hope that this might fix the issue, but it does not fix the problem.

For quickness I'm previewing with:
```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
```
But building a full docker image works great out of the box for the rest of the documentation, but not mermaid diagrams.

### Expected behaviour

I was expecting the official squidfunk/mkdocs-material build to show mermaid diagrams.

### Actual behaviour

Where the mermaid diagrams should appear, only a code block of the mermaid diagram source is shown.

### Steps to reproduce

git clone git@github.com:squidfunk/mkdocs-material.git
cd mkdocs-material
[browse to 0.0.0.0:8000]
[navigate to http://0.0.0.0:8000/mkdocs-material/reference/diagrams/]

### Package versions

I'm using the latest docker image, so I'm not relying on any specific versions installed on my computer.

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

[admittedly this is not a minimal example, but it is the official one.]
```

### System information

- Operating system: MacOS 11.4
- Browser: Chrome

**Comment by geraldschmidt** [comment]
I have gone through the list of closed issues. #693 especially sent me down a number of paths that looked promising, but none of them worked.

If it's necessary to derive a Docker image from upstream and add plugins that's fine, but it would be great if the documentation could mention that if that's needed.

**Comment by squidfunk** [comment]
Thanks for reporting! Setting up Mermaid can be a pain, which is why we offer a native integration as part of Insiders. If you don't want to use Insiders and need support setting, I suggest asking the author of the plugin on the mermaid discussion board 😊

**Comment by geraldschmidt** [comment]
Thank you for the speedy answer! That's fair. I'll try a multi-stage build next.

Thanks above all for this superb documentation tool!
