### ISSUE TITLE
Feature suggestion: allow user to remove of search highlighting

### ISSUE THREAD

**Issue by morido** [squidfunk/mkdocs-material#2864]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Add a frontend option to remove search highlighting.

### Use Cases

1. **Functionality:** Allows user to share a deep link (to the current page, paragraph, ...) without search highlighting applied.
2. **Discoverability:** User is currently left in the unknown why there are lots of yellow highlighted terms on the current page.

#### This is how search highlighting is currently rendered:

![current](https://user-images.githubusercontent.com/26249/126910860-9e5ceb8b-d6c7-473e-a718-8a1a8fcbb192.png)

#### This is how search highlighting could be rendered in the future (mockup):

![future](https://user-images.githubusercontent.com/26249/126910885-29ffc716-abfb-4559-9e73-a0785c44c15f.png)

##### That is:

1. retain the highlighted search term in the search bar in the top right
2. add an "X" button to remove the search term from there. Doing to would remove the highlighting and also remove the `?h=tags` parameter from the URL

##### Further idea:

* in this state highlight the term in the search bar also in yellow so the relation to the search highlighting feature becomes more obvious

**Comment by squidfunk** [comment]
Thanks for suggesting. This was already on my mind. Yes, we definitely need some kind of control to navigate through the search result. Note that when clicking the search sharing button, search highlighting is already removed from the URL.

**Comment by squidfunk** [comment]
Nobody seems currently interested in this feature (no reaction in 4 months), so I'm closing this for now. I may look into this again when re-evaluating the search interface in the future, but there's no immediate action for now.
