### ISSUE TITLE
livereload / dirtyreload should ignore hidden or editor temporary files

### ISSUE THREAD

**Issue by osresearch** [squidfunk/mkdocs-material#2877]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

When using `mkdocs serve --livereload` or `--dirtyreload`, `mkdocs` detects changes to editor temp files like `.foo.md.swp` or hidden files like '.foo' and constantly regenerates the documentation.  I tried adding the `mkdocs-exclude` plugin to ignore the glob `.*.swp`, but this does not stop the live reload from executing.

It seems like `mkdocs` shouldn't be scanning dot files anyway since these files aren't included in the output (although it would be nice to be able to include the `.well-known/` directory or have a way to specify dot files to be included) 

### Use Cases

Less noise on the console, fewer re-loads and re-renders on the webrowser when editing the Markdown files with `vi` and using the live reload / dirty reload functions.

**Comment by squidfunk** [comment]
Thanks for suggesting! Material for MkDocs is only a theme/template for MkDocs, so there's nothing that we can do to change that behavior as MkDocs is our upstream dependency. [You could ask the authors of MkDocs](https://github.com/mkdocs/mkdocs).

**Comment by osresearch** [comment]
Oops!  Sorry about that.  Moved to https://github.com/mkdocs/mkdocs/issues/2519
