### ISSUE TITLE
Search highlighting does not properly escape HTML

### ISSUE THREAD

**Issue by jbms** [squidfunk/mkdocs-material#2879]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Search highlighting obtains the `textContent` of nodes, applies replacements, and then adds it back as `innerHTML`.

Consequently, text that looks like HTML tags can get mangled.

Instead, `escapeHTML(value)` should be used prior to applying the replacements in `src/assets/javascripts/integrations/search/highlighter/index.ts`.

Example link:

https://squidfunk.github.io/mkdocs-material/customization/?h=your#additional-variables

Note that the the `<!-- Add your additional information here -->` text disappears when we add the `?h=your` parameter.

### Expected behaviour

n/a

### Actual behaviour

n/a

### Steps to reproduce

n/a

### Package versions

mkdocs-material master as of 2021-07-28:

e29dfd003e24215230abfe076a6a35d41230b3e4

### Configuration

```yaml
n/a
```

### System information

n/a

**Comment by squidfunk** [comment]
Good catch! Fixed in 6744eb607.

**Comment by squidfunk** [comment]
Released as part of 7.2.2.
