### ISSUE TITLE
Enabling the navigation.instant feature breaks links to anchors on Safari

### ISSUE THREAD

**Issue by damlobster** [squidfunk/mkdocs-material#2881]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If the `navigation.instant` theme feature is enabled, links to anchors don't work as expected on Safari (MacOS and iOS). The target page is opened but the page is not scrolled to the anchor location.

### Expected behaviour

When clicking a link pointing to an anchor, the page should be scrolled to that location.

### Actual behaviour

The page doesn't scroll to the anchor location.

### Steps to reproduce

1. unzip [reproduction.zip](https://github.com/squidfunk/mkdocs-material/files/6899887/reproduction.zip)
2. cd mkdocs-test
3. mkdocs serve
4. Open site in Safari
5. click link `A link to page1#section2`
 

### Package versions

- Python: 3.7.3
- MkDocs: 1.2.2
- Material: 7.2.0

### Configuration

```yaml
see `reproduction.zip`
```

### System information

- Operating system: MacOS 11.5.1
- Browser: Safari 14.1.2 (16611.3.10.1.3)

**Comment by squidfunk** [comment]
Thanks for reporting. I've looked into it and think I may have found the cause:

1. Links with anchors are not correctly intercepted, as they are matched against the URLs in `sitemap.xml` which do not contain any anchors. Thus, links with anchors always led to reloads, i.e. when linking between documents or searching.
2. When an URL is intercepted and contains an anchor, the anchor was used for positioning. However, the order of operation was wrong, as the anchor was set before the document was replaced, so the browser did not set the offset correctly.

Interestingly, the combination of 1. and 2. seems to have led to the strange behavior in Safari, not in Chrome.

adafd844f is an attempt to fix this:

1. URLs are canonicalized before comparing them with the URLs from `sitemap.xml`.
2. When an URL contains an anchor, the position is now set after document replacement.

This means that anchors are finally working with instant loading, even in search results. In regard to search results, this was something I had on my list for a long time and it seems that this is now finally fixed. I hope that this did not introduce other bugs – instant loading is actually extremely tricky to get right. I will revisit instant loading at a later time.

Please check `master` to verify that this is fixed. I will issue a release then shortly.

**Comment by squidfunk** [comment]
I went ahead and released the fix as part of 7.2.3.

**Comment by ybizeul** [comment]
I'm having that issue with current version.
Anchors working fine on Safari without `navigation.instant` but breaks with it.

Running 8.2.8

**Comment by squidfunk** [comment]
Thanks for reporting. Could you please check which version introduced the error? If you find the version that introduced the issue, please create a new issue and provide a minimal reproducible example.

**Comment by ybizeul** [comment]
Thanks. 7.0.0 is introducing this behaviour, will open a new issue with sample

**Comment by ybizeul** [comment]
https://github.com/squidfunk/mkdocs-material/issues/3797
