### ISSUE TITLE
Make pages and/or sections password protected

### ISSUE THREAD

**Issue by JefferiesTube** [squidfunk/mkdocs-material#2884]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I am using Material for Mkdocs for academic lectures (it's great for teching computer science stuff). It would be perfect if there is a way to have some sections or individual pages password protected. Ideally, this could be cached locally to prevent the user from having to enter the password each and every time.

### Use Cases

As stated above: For acadmic purposes or simply for some insider things.

**Comment by squidfunk** [comment]
Thanks for suggesting! As I understand, there's the [mkdocs-encryptcontent-plugin](https://pypi.org/project/mkdocs-encryptcontent-plugin/) which should satisfy these very needs 😊

**Comment by squidfunk** [comment]
Closing for housekeeping.

**Comment by JefferiesTube** [comment]
Thanks for the link - this is more or less exactly what I was looking for. 
Unfortunately, two aspects are suboptimal:
1. I cannot set a password for whole sections (or at least I wasn't able so far)
2. It's so ugly -.-

So if there is time in the future, a proper nice-looking integration would be awesome.

**Comment by squidfunk** [comment]
To be honest, I'm concerned that I'm not going to be able to find the necessary time to work on something like this anytime soon. I have so many ideas for features that impact users in an (IMHO) bigger way (e.g. better search), which is what I try to focus on. I hope you understand.

You could create an issue over at the repository of the plugin and work with the author to improve the current state of the plugin.
