### ISSUE TITLE
Insiders uses md-banner instead of md-announce

### ISSUE THREAD

**Issue by fkorotkov** [squidfunk/mkdocs-material#2926]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I'm trying to override a banner in the insiders version and CSS classes are not matching. The `announce` block is wrapped in `md-banner` instead of `md-announce`

### Expected behaviour

`md-announce` should be used in both versions

### Actual behaviour

CSS class names are not consistent

### Steps to reproduce

Can be reproduced in https://github.com/cirruslabs/cirrus-ci-docs/pull/899

<img width="810" alt="regular" src="https://user-images.githubusercontent.com/989066/128864490-189547e2-2083-4456-87c8-cf624f0e8e97.png">
<img width="811" alt="insiders" src="https://user-images.githubusercontent.com/989066/128864495-c876d781-bdcc-44f8-8b72-337d4784adf5.png">

### Package versions

Insiders 2.12.2 vs 7.2.3

### Configuration

```yaml
site_name: Cirrus CI
```

### System information

- Operating system: macOSS
- Browser: Chrome

**Comment by squidfunk** [comment]
Ah yes, that's inconsistent. It seems to have been renamed in Insiders.

I'll check why and whether we want it to be renamed here or change it back in Insiders.

**Comment by squidfunk** [comment]
I've kept the CSS in the community edition as-is, but added `.md-banner` and `.md-banner__inner` in b9979ac2f028452b7cafac2105715fe0f844fb7d.

This should solve your problem, as you can now use `.md-banner` and `.md-banner__inner` for overriding.

**Comment by squidfunk** [comment]
Released as part of 7.2.4.
