### ISSUE TITLE
bug: version selector does not work with recent change (insiders)

### ISSUE THREAD

**Issue by dmccaffery** [squidfunk/mkdocs-material#2929]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The following change breaks the version selector as the URL for `versions.json` now resolves within the version directory `/v1.0.0/versions.json` instead of the root of the host `/versions.json`.

https://github.com/squidfunk/mkdocs-material-insiders/blame/f80b15d5805d37428307cf7f9eebf1ef3275b47a/src/assets/javascripts/_/index.ts#L105

### Expected behaviour

The version selector should work as the `versions.json` should be retrieved from the root instead of the version-specific path.

### Actual behaviour

The version selector does not work as the attempt to retrieve the versions.json file fails.

### Steps to reproduce

1. mike deploy v1.0.0
2. mike deploy v2.0.0
2. mike serve

### Package versions

- Python: 3.9.6
- MkDocs: mkdocs, version 1.2.2
- Material: 7.2.3+insiders.2.13.0

### Configuration

```yaml
extra:
  version:
    provider: mike
```

### System information

- Operating system: macOS Monterey Beta 4
- Browser: Safari

**Comment by squidfunk** [comment]
Thanks for reporting. I'll investigate this asap.

Background for this change: MkDocs changed how the documentation is served locally. As of version 1.2.2, MkDocs always prepends the path of the `site_url`, e.g. for a`site_url` of `squidfunk.github.io/mkdocs-material/` the serve URL is `localhost:8000/mkdocs-material/`. Previously, this was `localhost:8000`. This led to the necessity of the change, but versions should clearly continue working.

Does this also happen with the non-Insiders version?

**Comment by squidfunk** [comment]
Released as part of 7.2.4.

**Comment by dmccaffery** [comment]
Thanks for the quick fix. I was able to work around it locally; the bug was more of an FYI as I was sure it was affecting others.

I was going to create a PR myself, time permitting, but you beat me to it!

This project is awesome. All of your hard work is greatly appreciated.

Cheers!
