### ISSUE TITLE
Social cards are not cached in .cache folder

### ISSUE THREAD

**Issue by zhyatt** [squidfunk/mkdocs-material#2948]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Despite fonts being cached and social card images showing up in the `site` directory, no social card images are created in the `.cache` directory when building with the social plugin.

### Expected behaviour

Social card images are included in the `.cache` directory after building, and only rebuilt if changes related to the logo, title, description, etc. for that specific card occur.

### Actual behaviour

The `.cache` directory has font files but no social card images files after building. Build times increased ~8x as it rebuilds the social card images each time.

### Steps to reproduce

1. Install MkDocs and Material Insiders via pip
2. Add `docs/index.md` file with any content
3. Add configuration as noted below
4. Run `mkdocs build`

### Package versions

- Python: `Python 3.9.6`
- MkDocs: `mkdocs, version 1.2.2`
- Material: `Version: 7.2.4+insiders.2.13.0`

### Configuration

```yaml
site_name: Site Name
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
plugins:
    - social
```

### System information

- Operating system: macOS Big Sur 11.0.1
- Browser: Brave, Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (x86_64)

**Comment by squidfunk** [comment]
Fixed in the latest commit on the Insiders repository.

**Comment by squidfunk** [comment]
Released as part of 7.2.4-insiders-2.13.1.

**Comment by zhyatt** [comment]
@squidfunk In some testing I have a found a few things:

1) The test example I gave above works now with the cache, but when trying on a setup that has a custom palette settings such as:
``` 
  palette:
    - scheme: nano
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
```

I get the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 183, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 249, in build
    config = config['plugins'].run_event('config', config)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/material/plugins/social/plugin.py", line 70, in on_config
    if palette["primary"]:
KeyError: 'primary'
```

Switching back to this it works fine:
```
  palette:
    primary: 'blue'
    accent: 'blue'
```

2) Although the build completes, this warning does appear during building:
```/usr/local/lib/python3.9/site-packages/PIL/Image.py:2911: DecompressionBombWarning: Image size (138093302 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.```

3) Building times increased from 2-3x in some quick tests, even with the images cached. This isn't a huge burden, but just curious if there is an easy way to disable this running locally during development that doesn't involve removing the plugin settings temporarily (command flag?).

**Comment by squidfunk** [comment]
I'll keep it short:

1. Definitely an error
2. I need a reproducible example for this, haven't seen this error
3. Yes, we should add this

Could I ask you to create a new issue? Those points are only loosely related to the original issue. I'll fix them next time I can set time aside to work on Material for MkDocs.

**Comment by zhyatt** [comment]
> Could I ask you to create a new issue?

Yes, I will create a new issue for each of these.

**Comment by zhyatt** [comment]
Related to 2: I can reproduce the `DecompressionBombWarning` by using a large logo. In our case, this was an svg file (so small file size of < 1 KB) but with a large `viewBox` of 1770 x 780 which would render a decent amount of pixels. Dialing that back prevented the warning. This also improved build times by ~25%.

Would you still like me to create a ticket for this? There doesn't appear to be a DOS vector to worry about here given the images are pre-generated, the only impact is some increased build times, but perhaps bubbling up a more explicit warning is of interest?
