### ISSUE TITLE
Feature suggestion: indicate specific pages as new or deprecated

### ISSUE THREAD

**Issue by Stanzilla** [squidfunk/mkdocs-material#2991]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

An visual indicator that automatically gets added to new or updated documents.

### Use Cases

For the nav/toc maybe a colored asterix? A "New" tag?

Something like that. The definition of new and updated can be based on the git history but should also be able to be controlled manually since you will want to avoid overusing the feature and don't want to flag docs that just got a typo fix or so.

**Comment by squidfunk** [comment]
Thanks for suggesting. Manually should be doable. For things based on git history I’d recommend asking @timvink, as he’s the author of several git based plugins.

**Comment by martinbira** [comment]
As @squidfunk said, Manually is doable using a bit of CSS, SVG icons and the Attribute list extension. I've done it myself with icons for "new", "updated", and "deprecated".

**Comment by squidfunk** [comment]
Interesting, it probably makes sense to support more states than just „new“, which might have no git-inferable value like „deprecated“. Thus, manual tagging would probably the most flexible.

**Comment by timvink** [comment]
Perhaps it would be possible to parse the XML feed of a site using javascript and use the info to add the labels? I'm not that into JS..

Might be a good fit for https://guts.github.io/mkdocs-rss-plugin/ from @guts , as it already parses the git info into a nicely structured XML feed, for both newly created pages and newly updated pages.

**Comment by martinbira** [comment]
An other case for manual tagging: you probably don't want to automatically announce a section as having "updated content" or similar when just fixing a spelling error or something like that.

**Comment by Guts** [comment]
Another solution that I planned for the RSS plugin (but still not implemented, lacking of time) would be to store newest/updated content as a Jinja context (in addition to the XML feed) to be exposed and processed through template or JS or macro-plugin or ...

> An other case for manual tagging: you probably don't want to automatically announce a section as having "updated content" or similar when just fixing a spelling error or something like that.

Sure! That's clearly a limitation of the git logic (and my plugin). One option would be to "measure" a threshold beyond which the content is considered as updated: more than 3 lines updated, etc. 

FYI, @lyz-code created a plugin to generate newsletter based on (relatively) strict git commit messages convention: https://lyz-code.github.io/mkdocs-newsletter/

**Comment by squidfunk** [comment]
So, currently, there are only some loose ideas floating around. Before we can start thinking about implementing, this really needs to be specced out. Everything `git`-related is beyond the scope of Material for MkDocs. We could provide the functionality to manually declare certain pages with certain states via metadata, i.e. offer a native/default integration, but we'd need to know how the mechanics of this should work. If somebody wants to go ahead, a proposal would be a good way to start.

**Comment by Stanzilla** [comment]
So how about two special tags in the frontmatter, "new" and "updated" and depending on that, the nav and tags on the page get styled.

In addition a global plugin setting that decides if you only want the special tag on the page or also the nav treatment.

**Comment by squidfunk** [comment]
I like the idea of using the tags system - we could further generalize it and allow to specify icons per tag through configuration of the tags plugin, maybe like so:

``` yaml
plugins:
  - tags:
      icon:
        reference: material/tag
        new: material/new-box
```

What I don't understand is how you want navigation items to get styled. Unfortunately, navigation is something buried deep in MkDocs itself, so I'm not sure whether we can inject icons in navigation items. Also, I'm not seeing any hints in your screenshot how it should look!?

**Comment by Stanzilla** [comment]
> I like the idea of using the tags system - we could further generalize it and allow to specify icons per tag through configuration of the tags plugin, maybe like so:
> 
> ```yaml
> plugins:
>   - tags:
>       icon:
>         reference: material/tag
>         new: material/new-box
> ```
> 
> What I don't understand is how you want navigation items to get styled. Unfortunately, navigation is something buried deep in MkDocs itself, so I'm not sure whether we can inject icons in navigation items. Also, I'm not seeing any hints in your screenshot how it should look!?

The colored *

**Comment by martinbira** [comment]
> Unfortunately, navigation is something buried deep in MkDocs itself, so I'm not sure whether we can inject icons in navigation items.

I added to "locked" pages using the mkdocs-encryptcontent-plugin, see https://github.com/CoinK0in/mkdocs-encryptcontent-plugin#tag-encrypted-page

I then modified the `nav-item` partial to add an SVG icon via CSS for all locked pages.

**Comment by squidfunk** [comment]
@martinbira Thanks for pointing out a possible solution. The problem I'm seeing is that when building the navigation, the page information is not present, i.e. we can't read the metadata of a page as it's not available on the navigation items. Could you point to the exact code where the icon is added and replaced?

**Comment by martinbira** [comment]
So I've added the icon in a few states - hover, active and so. Unfortunately, I don't have a live example at the moment. But here is where I check if an item is encrypted.

```
{% elif nav_item == page %}
    <li class="{{ class }}">
      {% set toc = page.toc %}
      <input class="md-nav__toggle md-toggle" data-md-toggle="toc" type="checkbox" id="__toc">
      {% if toc | first is defined and "\x3ch1 id=" in page.content %}
        {% set toc = (toc | first).children %}
      {% endif %}
      {% if toc | first is defined %}
        <label class="md-nav__link md-nav__link--active" for="__toc">
          {{ nav_item.title }}
          <span class="md-nav__icon md-icon"></span>
        </label>
      {% endif %}
      {% if nav_item.encrypted %} /* <-- HERE */
        <a href="{{ nav_item.url | url }}" class="md-nav__link md-nav__link--active locked_nav__item--active">
          {{ nav_item.title }}
        </a>
      {% else %}
      <a href="{{ nav_item.url | url }}" class="md-nav__link md-nav__link--active">
        {{ nav_item.title }}
      </a>
      {% endif %}
      {% if toc | first is defined %}
        {% include "partials/toc.html" %}
      {% endif %}
    </li>
  {% else %}
    <li class="{{ class }}">
      {% if nav_item.encrypted %} /* <-- HERE */
      <a href="{{ nav_item.url | url }}" class="md-nav__link locked_nav__item">
        {{ nav_item.title }}
      </a>
      {% else %}
      <a href="{{ nav_item.url | url }}" class="md-nav__link">
        {{ nav_item.title }}
      </a>
      {% endif %}
    </li>
  {% endif %}
```

**Comment by squidfunk** [comment]
I see, so there's an extra attribute on the navigation item. How is it decided _which_ page is encrypted? If it's done via front matter, from what I understand, you would have to do rendering in two passes, because you would have to read the Markdown for each page in order to extract the front matter to correctly annotate each navigation item as either encrypted or not, and then do the actual rendering with the fully annotated navigation for each page. Otherwise, earlier pages in the rendering process will not have the information available whether a page referenced by a succeeding navigation item should render with a lock or not.

Thus, I think the only thing to achieve this functionality without adding a second pass on all pages (because the navigation for all pages must be rendered) is to match pages against a list of strings or regular expressions. I'm happy to be proven wrong, so if somebody could explain how the encrypt plugin does it, and whether there's another way to extract front matter from pages prior to rendering without doing a complete pass over all sources, this should be doable.

**Comment by squidfunk** [comment]
via https://github.com/mkdocs/mkdocs/pull/2387:

![117340228-f8606780-aea0-11eb-9530-fb08a4e98d39](https://user-images.githubusercontent.com/932156/132199880-12dcc524-a830-4319-80e0-c20f654a35c2.png)

**Comment by martinbira** [comment]
Not sure how the plugin works in its entirety, but pages that are to be encrypted are defined by either a global password in `mkdocs.yml` or on per page basis with the meta-tag `password: some_password`.

**Comment by Stanzilla** [comment]
Additional idea: Make the "new" indicators go away if a user has seen them, store state in localStorage?

**Comment by squidfunk** [comment]
I've just checked the plugin system again and realized that all Markdown is read before a single page is built. This means we can alter the navigation items and annotate them, adding a visual indicator for new or deprecated content.

**Comment by Stanzilla** [comment]
Another state? "Seen"?

**Comment by squidfunk** [comment]
Well, I won't consider this for the initial implementation, but it could easily be added by the author because it needs JavaScript anyway.

**Comment by squidfunk** [comment]
I've re-evaluated this feature and am currently not considering it for implementation. While it might be a nice addition, I don't see that it solves the problems of many. The tags system works pretty well, is integrated with search, and authors can change the title of pages to include emojis or simple ASCII symbols to denote that certain pages have special meaning. The same is done by the encrypt content plugin, as far as I understand.

I may re-evaluate this in the future, or somebody write a third-party plugin that achieves the same goal. Closing.

**Comment by squidfunk** [comment]
Insiders 4.5.0 was just released, which adds the ability to specify an icon per page which is then rendered next to the title in the navigation sidebar: https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-icon

This also allows adding an icon to signal a specific state of a page, e.g. new or deprecated.

**Comment by squidfunk** [comment]
[Insiders 4.22.0](https://squidfunk.github.io/mkdocs-material/insiders/) adds support for [navigation status](https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-status). Authors can now define status values which can then be assigned to pages, rendering a nice little icon with a tooltip next to the page in the sidebar:

<img width="486" alt="Bildschirmfoto 2022-08-21 um 19 30 54" src="https://user-images.githubusercontent.com/932156/185803565-7e9a5473-747f-4dac-a6e7-1d8d8a52ed84.png">

Try it in our [reference](https://squidfunk.github.io/mkdocs-material/reference/).
