### ISSUE TITLE
Feature suggestion: support new code highlight features

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#2997]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

## Request

This issue is to track support for new code highlighting features.

1. One request that has been made a couple of times is a way to create headers for code blocks. Pygments has such a feature called `filename`. It allows a user to specify a filename as a title or any arbitrary title as a header. In turn, Pygments will inject a span with the given title and a class of `filename`. This is easy to target and style.

    ```html
    <span class="filename">Some Title</span>
    ```

    <img width="743" alt="Screen Shot 2021-08-23 at 9 58 42 AM" src="https://user-images.githubusercontent.com/1055125/132130545-a0935c5b-2c90-4343-92c1-5fc0a697f577.png">

    These headers are generated by using the option `filename="my title"` in the code header or `attr_list` style header. If users do not wish to manually specify all of their titles, they can enable `auto_filename` which will grab a friendly title from the Pygment's lexer used. For instance, here we use the `pycon` specifier, and the following title is auto-generated:

    <img width="728" alt="Screen Shot 2021-08-23 at 9 08 11 AM" src="https://user-images.githubusercontent.com/1055125/132130812-ee277d85-8f2a-4c25-8d90-67be9ddc1440.png">

    Now a user may not always be happy with a specific generated title, so we provide a way to create a user mapping in the config to override a specific auto-generated title.

   Of course, a user can always directly override a title using the `filename="my title"` syntax. I've considered adding a sort of template functionality where a user could maybe force the lexer title into their own custom title `"{lang}: my title"`, but have no intentions right now unless such a feature is requested. In general, the plan is to just let the user specify the title and see if they desire such a feature after the fact.

2. Originally, we thought we'd use `data-attr` to do the above, but after evaluating `filename`, I personally think `filename` is more than suited to get the job done. I would encourage Material to support the Pygments feature, but obviously Material is free to approach this any way they see fit. With that said, `data-attr` is now supported on Pygments code blocks with the `attr_list` extension is added.

    JavaScript code blocks have had this support for a while. Additional attributes are normally added to the `code` block unless a setting is configured which will redirect them to the `pre` block. This is mainly because some JavaScript highlighters require configuration attributes on different blocks. This should satisfy them.

    As for Pygments blocks, attributes will be placed on the wrapper `<div>`. Pygments support multiple forms, the table form being one of them.

    While my intention is not for `data-attr` to be used for Pygments title headers, they could be used as such. I guess what I do envision them to be used for is maybe enabling other Material code-specific features. I'm not sure what those would be, but the door is now open.

3. There is a new feature allowing users to specify line ids, but Material doesn't jump to them very well. It may be nice if Material supported this, but very low priority.

## Notes

I do not generate language attributes currently on Pygments code blocks. I feel `filename` currently fulfills this role fine. I could do the same as is done on JavaScript code blocks, but you will get Pygments specific short names such as `pycon`. I could do what I do with `filename` and grab the Pygments' lexer-friendly title and instead inject that. I didn't want to do this and create redundant code and infopp with `filename` being present, but I am open to discussion.

The current branch is here: https://github.com/facelessuser/pymdown-extensions/pull/1426.

Nothing in the branch should be breaking, and even if Material doesn't support `filename`, I see nothing stopping it from going out, but feedback would be nice. I also see nothing stopping `data-attr` from going out unless they are desired to be attached to different elements. Line number anchors should stop nothing.

### Use Cases

The description says it all.

**Comment by squidfunk** [comment]
Thanks again for working on this! I believe this is a great addition to code blocks, as it was requested many times. I#ve experimented with the markup and think I'll settle with a little more unobtrusive style:

<img width="709" alt="Bildschirmfoto 2021-10-30 um 11 02 35" src="https://user-images.githubusercontent.com/932156/139526907-976418ea-c408-4b3e-b7bb-738e2dab9bf2.png">

If somebody wishes to customize the background color or add the icon, it's trivial to add with some custom CSS. One idea: would it be possible to pass the `title` value through Markdown processing, similar to the Admonition title? This would allow for using icons or other inline elements, which might be a great addition:

<img width="708" alt="Bildschirmfoto 2021-10-30 um 11 04 23" src="https://user-images.githubusercontent.com/932156/139526971-aee08331-b06b-4d01-b417-89b64743f164.png">

**Comment by squidfunk** [comment]
Added in 6ceef24179ea5f682e182c8d1dc4c6c6fca52d9e. Documentation is [here](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-a-title).

**Comment by squidfunk** [comment]
Released as part of 7.3.6

**Comment by facelessuser** [comment]
> One idea: would it be possible to pass the `title` value through Markdown processing, similar to the Admonition title?

This is difficult as SuperFences is unfortunately not handled like a normal block. Python Markdown has issues with blocks that have breaks (new lines) in them. It is one of the reasons SuperFences is sent through the PrePreprocessor instead of the BlockProcessor. So fenced code blocks are replaced with stashes in reality that link with raw text HTML. Usually, a code block is handled in one shot in the beginning and then cleaned up if we were overly aggressive in PostProcess (we don't have the full context of where code blocks exist when handling other raw HTML).

Does that mean it can't be done? Well...no, but it is a lot more complex. I would either have to spawn a new Markdown process that handles the titles separately, so they lose context with the rest of the document, so I wouldn't use footnotes, etc. Or you'd have to unpack the stashes at some point and process them special maybe. Anyways, it is complicated.

---

Side note, I assume you did not look into jumping to line numbers via ID links did you? Do I need to reopen this issue or spawn a new issue for that?

**Comment by squidfunk** [comment]
Thanks for the explanation. I thought I'd rather raise the question before issues start popping up. You know how it is.

> Side note, I assume you did not look into jumping to line numbers via ID links did you? Do I need to reopen this issue or spawn a new issue for that?

Not yet. I'll look into it at a later time, but I'd like to think a little "bigger" because I'd like to support GitHub's line-range selection feature. This is likely to incur the need for additional JavaScript, as it's likely to be more complex than just adding CSS. Since you tagged that point as low priority, I'm postponing it. You can open an issue for this if you like. I'm also happy to merge a PR.

**Comment by squidfunk** [comment]
16939c16a adds basic support for line anchors.
