### ISSUE TITLE
Ordered lists within a unordered list have ::before content added

### ISSUE THREAD

**Issue by d0ugal** [squidfunk/mkdocs-material#3]
```
.article ul li:before {
    content: "\e602";
```

With the above CSS, ordered lists within an unordered list have the content added which overlaps with the number.

See the bottom of these docs for an example: http://d0ugal.github.io/mkdocs-versioned/

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed with the last commit (closed the wrong issue with the commit message, though). The fix will be incorporated into 0.1.3, which will get released within a few days, including a few small fixes.
