### ISSUE TITLE
Suboptimal syntax highlighting for PHP

### ISSUE THREAD

**Issue by bobmulder** [squidfunk/mkdocs-material#30]
Hey guys,

I love the theme, but I hate it that hightlighting isn't done by default, and the mentioned extension doesn't work as wel...

I get the following (for PHP):
![image](https://cloud.githubusercontent.com/assets/5465074/15183699/84f73a26-1792-11e6-97e1-fadb9bd5d190.png)
** Only `set` and `object`?**

Please can we add support to this?

**Comment by d0ugal** [comment]
Did you specify the language as PHP?

**Comment by squidfunk** [comment]
Highlighting is done using pygments and there may be classes that are undefined. I will provide a fix asap.

**Comment by squidfunk** [comment]
Can you provide the corresponding markdown? For me it seems pygments is completely broken for PHP, as I only get `span`s with the class `x`.

**Comment by d0ugal** [comment]
Try starting the code sample with `<?php`

**Comment by squidfunk** [comment]
Forgot about that, thanks @d0ugal
