### ISSUE TITLE
Customize search result summary

### ISSUE THREAD

**Issue by jtatum** [squidfunk/mkdocs-material#3010]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I know there are changes to search result summaries coming with #2976, but I'm wondering what I can do now to change the search result summary. Is there a way to override the function that generates or returns these, or some front matter I can use to set a static summary?

### Use Cases

The data we have in mkdocs is highly structured, and the summaries are very low quality, with most failing to even show the page title.

**Comment by squidfunk** [comment]
Converting to discussion, since this is essentially a question.
