### ISSUE TITLE
Feature suggestion: Card grids

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#3018]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Sometimes it might be beneficial to render links as a grid of cards. Would you find that useful?

### Use Cases

This could be a good fit for index pages that link to a set of subsections.

### Screenshots / Mockups

<img width="553" alt="Bildschirmfoto 2021-09-11 um 23 28 16" src="https://user-images.githubusercontent.com/932156/132962058-ab38d692-734b-4f45-b9ca-edbdd126902b.png">

**Comment by fveauvy** [comment]
It could be really great for index indeed !

**Comment by corykinney** [comment]
Yes, this would be perfect for index pages!

**Comment by vedranmiletic** [comment]
> It could be really great for index page indeed !

[MkDocs](https://www.mkdocs.org/) already uses this concept via raw HTML. It would be great to have it available via Markdown.

**Comment by hrjn** [comment]
It is indeed possible to revert to raw HTML, the [AWS Copilot doc home page](https://aws.github.io/copilot-cli/) has some examples. 

Using cards would also allow to expose a large amount of pages/tutorials as a "mosaic" (e.g. like the [Snowflake Quickstarts](https://quickstarts.snowflake.com/) page).

All in all, having this feature natively would be awesome 🙂

**Comment by alanlivio** [comment]
It could be really great.

**Comment by squidfunk** [comment]
__[Support for card grids](https://twitter.com/squidfunk/status/1508082132438110216) was added in 8.2.8+insiders-4.12.0__! Check out the documentation (includes demos):
https://squidfunk.github.io/mkdocs-material/reference/grids/

You can now easily build overview pages with beautiful hover cards:

![screenshot-localhost-8000-mkdocs-material-reference-grids-1648390094802](https://user-images.githubusercontent.com/932156/160285605-d22a0be1-1e46-4203-9ea9-b30df44f49bf.png)

**Comment by chuycy** [comment]
> hover cards:

Hello, I have a question.
How do I arrange three or four card grids in a row? Is the default two in a row?

**Comment by squidfunk** [comment]
In desktop view with sidebars, cards arrange themselves in 2-card grids. When you hide the sidebars, they swap to 3-card grids (as you can see in https://github.com/squidfunk/mkdocs-material/issues/3018#issuecomment-1079939985). You can tweak this behavior by adjusting `grid-template-columns`, specifically the `rem` value with [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css):

``` css
.md-typeset .grid {
  grid-template-columns: repeat(auto-fit,minmax(16rem,1fr))
}
```

**Comment by chuycy** [comment]
> In desktop view with sidebars, cards arrange themselves in 2-card grids. When you hide the sidebars, they swap to 3-card grids (as you can see in [#3018 (comment)](https://github.com/squidfunk/mkdocs-material/issues/3018#issuecomment-1079939985)). You can tweak this behavior by adjusting `grid-template-columns`, specifically decrease the `rem` value with [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css):
> 
> ```css
> .md-typeset .grid {
>   grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr))
> }
> ```

Got it. Thank you~~

**Comment by faustool** [comment]
I would like to have a grid displaying child items like Docusaurus does for category pages

**Comment by squidfunk** [comment]
This can already be implemented with [card grids](https://squidfunk.github.io/mkdocs-material/reference/grids/#using-card-grids) today. See [this excellent](https://blueswen.github.io/portfolio/) example by @blueswen, linking to GitHub repositories, which can easily be swapped out with links to child pages in a section:

<img width="1263" alt="Bildschirmfoto 2022-12-27 um 16 30 46" src="https://user-images.githubusercontent.com/932156/209687954-54ecd191-7d83-4819-9d1d-9e63c0461bc5.png">

**Comment by faustool** [comment]
Thanks for the suggestion. I'm looking for a rather automated way to achieve this.
I'm considering developing a plugin myself to read the metadata and replace a custom markdown with responsible cards in a grid.
Something like `!!! child-page-grid !!!`.

**Comment by faustool** [comment]
> Thanks for the suggestion. I'm looking for a rather automated way to achieve this. I'm considering developing a plugin myself to read the metadata and replace a custom markdown with responsive cards in a grid. Something like `!!! children-card-grid !!!`.

here's what I started doing... it currently aims the Navigation object as it is created when using MKDocs Material Theme and navigation.indexes feature is selected. This is the setup I have for my use case now. I haven't tested with another case.

**Comment by keldian** [comment]
> In desktop view with sidebars, cards arrange themselves in 2-card grids. When you hide the sidebars, they swap to 3-card grids (as you can see in [#3018 (comment)](https://github.com/squidfunk/mkdocs-material/issues/3018#issuecomment-1079939985)). You can tweak this behavior by adjusting `grid-template-columns`, specifically decrease the `rem` value with [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css):
> 
> ```css
> .md-typeset .grid {
>   grid-template-columns: repeat(auto-fit, minmax(16rem, 1fr))
> }
> ```

Hi, is it possible to (horizontally) shrink all the cards to the content of the card with the longest content? The idea is to have as many equal length cards in a row as possible without the any of the content getting line-wrapped.

**Comment by squidfunk** [comment]
Sure, with some additional CSS, that's definitely possible. You probably need to set the `width` to `fit-content` (untested)

**Comment by keldian** [comment]
Thanks, I toyed with that for about 30 min but can't get it to work sadly—my CSS skills are flimsy. Is there a way to just display cards without the grid?

**Comment by squidfunk** [comment]
I'm not sure what you want to achieve, but here's a primer on [`grid-template-columns`](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content_function).

**Comment by squidfunk** [comment]
> Hi, is it possible to (horizontally) shrink all the cards to the content of the card with the longest content? The idea is to have as many equal length cards in a row as possible without any of the content getting line-wrapped.

Reading again: I don't think that's possible, but grid is a pretty complicated beast, so there might be a way to do this. You could ask this question on [StackOverflow](https://stackoverflow.com/), as it's not specific to Material for MkDocs but applies to all sites using CSS grid.

**Comment by keldian** [comment]
> I'm not sure what you want to achieve, but here's a primer on [`grid-template-columns`](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content_function).

Yeah I had one eye on that page during my trial & error run; I just wasn't able to find the right syntax combination. I have a firm notion of what I want in my head (and I could probably achieve it using JS), but putting it into words is tricky :laughing:.

Thanks for the pointers though. I'll hold back on the over-complication and keep it stock for now.
