### ISSUE TITLE
Feature Request: Configure side menu behavior

### ISSUE THREAD

**Issue by msudol** [squidfunk/mkdocs-material#307]
I was wondering if there could be a yml config setting that would just expand the left side nav menu and make it static without the collapsing menu structure?

**Comment by squidfunk** [comment]
Well, there's currently no plan in doing that and my time is currently very limited, but it's solvable with CSS only. Feel free to PR (please read the contribution guidelines first).

**Comment by squidfunk** [comment]
Closing this, as there's no plan to add support for this in the near future.

**Comment by tonglil** [comment]
If anyone has come up with anything to collapse the TOC (first) _and then_ the Left-Side Nav (or pin the left side nav open all the time), please post your solution here.

We have users that are a bit confused when their viewport is <1200px and don't know about the hamburger icon. All they see is the "Table of contents".

Thanks in advance.

**Comment by squidfunk** [comment]
@tonglil you can change the breakpoints in the original source (_config.scss) and recompile the theme. All other values should be derived from the breakpoints. However, note that I’ve chosen 1220px because any smaller diminishes the readability of the content section.

**Comment by tonglil** [comment]
Thanks, I'll take a look at changing the breakpoints to collapse the TOC first and then the Nav.

**Comment by matjaeck** [comment]
> All other values should be derived from the breakpoints.

Some values are still hard-coded in application.js and depending on what you do you might need to adjust them to the changes you make to the breakpoints. See https://github.com/matjaeck/mkdocs-material/commit/d6f22a67881c67493b6cb54513238eff9b318882 as an example where I enable the toc for tablets - maybe it helps you.

**Comment by squidfunk** [comment]
@matjaeck - you’re right. Totally forgot about them. Wanted to modularize it for some time now but my time is too limited - only bug fixes at the moment.
