### ISSUE TITLE
Version 7.3.1 introduced regression for some plugins

### ISSUE THREAD

**Issue by jaklan** [squidfunk/mkdocs-material#3072]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

As you can see at the pictures below, after upgrading `mkdocs-material` to 7.3.1 (from 7.3.0) the navigation is broken when using the `mkdocs-section-index` plugin - names of the sections and arrows seem to be in the reverse order. For now I don't know if any other plugins are affected by the update, but as it was the patch update - nothing should be broken anyway.

PS I know the theme has this functionality available out-of-the-box, but I use for the reason described in the #3071 issue.

### Expected behaviour

![image](https://user-images.githubusercontent.com/24907857/135721605-b4917360-c2bd-4a16-ab95-5e974fdac2dd.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/24907857/135721399-6c5dabcd-86d9-4ef0-b5e8-9d3b17f7ddc4.png)

### Steps to reproduce

1. Install `section-index` plugin.
2. Create `docs/projects/project-name/docs` dirs.
3. Create an `index.md` file in the last dir (and optionally some other Markdown files).
4. Enable `section-index` plugin.
5. Run `mkdocs serve`.

### Package versions

- Python: 3.8.12
- MkDocs: 1.2.2
- Material: 7.3.1

### Configuration

```yaml
site_name: Whatever

plugins:
  - section-index

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
```

### System information

- Operating system: macOS
- Browser: Chrome

**Comment by squidfunk** [comment]
Thanks for reporting. The `mkdocs-section-index`plugin is not officially supported, as Material for MkDocs has native support for this feature. Thus, this issue should be raised to the plugin authors.

**Comment by jaklan** [comment]
@squidfunk I see, but it doesn't mean the patch release introduced some breaking changes, if the plugin crashed unexpectedly? If yes, it should be probably a major release then.

**Comment by squidfunk** [comment]
No. We can't do a major release every time we change templates. This is a template project. There will __always__ be breaking changes, depending on how you use it.
