### ISSUE TITLE
Feature suggestion: Dismissible announcement bar

### ISSUE THREAD

**Issue by martinbira** [squidfunk/mkdocs-material#3087]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The announcement bar is a great place for shorter announcements. Sometimes these are temporary or only requires visitors to see it once to understand new features or similar. With these temporary/once viewed announcements it would be a nice addition to the feature to be able to dismiss the content in the announcement when read as frequent visitors may not like to see the same information over and over. This can draw use of the `scope` extra that was introduced with the Consent feature to in some way keep track of the visitors actions. 

Additional considerations: If an announcement has been dismissed by a visitor, a new announcement should supersede the previously dismissed announcement and the announcement bar should be visible again.

### Use Cases

Use cases include providing information about things not only directly related to the documentation, such as when new features from Insiders/Material are implemented, like the theme toggle or search highlighting. This is information that a visitor only would need to view once.

### Screenshots / Mockups

![material-feature-req-dismissable-announcement](https://user-images.githubusercontent.com/22232681/136031959-be80004e-a3eb-4cd3-9cc8-4e7c0702963d.png)

**Comment by squidfunk** [comment]
I've added support for a dismissable announcement bar in [`8df913283`](https://github.com/squidfunk/mkdocs-material-insiders/commit/8df9132830c18fcf2002f76ade3cd45cc74c767f) and [`9319335c7`](https://github.com/squidfunk/mkdocs-material-insiders/commit/9319335c7329c7a7fd8267fe8228d4da5a0a9e1f). There's now a new feature called `announce.dismiss` which will add a button to the announcement bar that will only show the bar if the user hasn't dismissed it. When a new announcement is set, the announcement bar is shown again. Note that whether the bar is shown or not is based on the `innerHTML` of the `announce` block, so if a single character changes, the bar is shown again. Enable it with:

``` yaml
theme:
  features:
    - announce.dismiss
```

As usual, content shift is minimized, which means the page should not "jump" if it loads slowly, as the announcement bar is hidden during the loading/rendering of the critical path. Note that this is a new Insiders feature. A release will follow in the next few days. `master` already includes the changes.

**Comment by squidfunk** [comment]
Oh, and of course this integrates with `extra.scope`, as all user preference.

**Comment by squidfunk** [comment]
Now also on the official docs:

![screenshot-squidfunk-github-io-mkdocs-material-getting-started-1638315480973](https://user-images.githubusercontent.com/932156/144145277-ef74f871-027d-4c21-8587-455b44e2b31a.png)

**Comment by squidfunk** [comment]
The change was released as part of 8.0.3+insiders-4.2.0.
