### ISSUE TITLE
bug: reference to mkdocs in requirements.txt in mkdocs-material-insiders requires port 22

### ISSUE THREAD

**Issue by dmccaffery** [squidfunk/mkdocs-material#3090]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The recent change to mkdocs-material-insiders to install mkdocs from a git url pending the release of 1.2.3 requires ssh (port 22) to be open. Many ci/cd servers / systems do not allow for this.

https://github.com/squidfunk/mkdocs-material-insiders/blob/a9202226f56d976647b456282504a356b4e1dca0/requirements.txt#L26

Can we change the url to https?

mkdocs @ git+https://github.com/mkdocs/mkdocs.git@4ea78da2e93e1165c2600df5f5a66704ff8bc197

### Expected behaviour

The following requirement should succeed:

git+https://${GITHUB_INSIDERS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

### Actual behaviour

Collecting mkdocs@ git+git://github.com/mkdocs/mkdocs.git@4ea78da2e93e1165c2600df5f5a66704ff8bc197
  Cloning git://github.com/mkdocs/mkdocs.git (to revision 4ea78da2e93e1165c2600df5f5a66704ff8bc197) to /tmp/pip-install-eqjlb4sl/mkdocs_cbb2ed9d1045485a8e8bb8db9a45b3b9
  Running command git clone -q git://github.com/mkdocs/mkdocs.git /tmp/pip-install-eqjlb4sl/mkdocs_cbb2ed9d1045485a8e8bb8db9a45b3b9
  fatal: unable to connect to github.com:
  github.com[0: 140.82.112.4]: errno=Connection timed out

### Steps to reproduce

install mkdocs-material-insiders with outbound 22 blocked

### Package versions

N/A

### Configuration

```yaml
N/A
```

### System information

N/A

**Comment by squidfunk** [comment]
Thanks for reporting. Indeed, that's a better idea! Fixed in 5ccee3eb8.

**Comment by dmccaffery** [comment]
You are amazing -- was going to fix it myself, but... too fast! :-D
