### ISSUE TITLE
Search: results list doesn't display (Uncaught TypeError: e.tags.map is not a function)

### ISSUE THREAD

**Issue by Guts** [squidfunk/mkdocs-material#3092]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Search behavior is broken in another fashion than #sear

Downstream issue: https://github.com/geotribu/website/issues/435

### Expected behaviour

Search normal behaviour, as described into the documentation or, at least, as for non insiders version.

### Actual behaviour

When a user makes a search, the results list doesn't appears, but a console error does:

![Capture d’écran de 2021-10-08 21-03-23](https://user-images.githubusercontent.com/1596222/136613488-ae348d17-f6dd-4cbd-bbdd-de212c520a3f.png)

### Steps to reproduce

1. Install Insiders version > (or directly from the master branch: `pip install -U git+https://github.com/squidfunk/mkdocs-material-insiders.git`)
2. Mkdocs serve
3. search something into the search bar:
    - autocompletion: OK
    - share: OK
    - results count: OK
    - results list: KO
4. Open the console and read the error:

```javascript
Uncaught TypeError: e.tags.map is not a function
    Nr https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    ai https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    Fi https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    u https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    _next https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    next https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    n https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    _next https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    next https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    v https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
    _next https://static.geotribu.fr/assets/javascripts/bundle.80a943f2.min.js:3
```

### Package versions

- Python: `3.8.10`
- MkDocs: `1.2.2`
- Material: `Version: 7.3.2+insiders.3.1.2`

### Configuration

```yaml
plugins:
  [...]
  - search
  [...]
```

### System information

- Operating system: Ubuntu LTS
- Browser: Firefox 93, Chromium, Safari

**Comment by squidfunk** [comment]
[`84b49d9`](https://github.com/squidfunk/mkdocs-material-insiders/commit/84b49d9523898c865fefbeccc4052b01c831e098) adds warning messages and skips tags when the syntax is invalid (i.e., no list is given).:

```
WARNING  -  Material for MkDocs doesn't support the 'prebuild_index' option. Please remove it from 'mkdocs.yml'.
WARNING  -  Skipping 'tags' due to invalid syntax [creating-your-site.md]: foo, bar
```

**Comment by squidfunk** [comment]
> Question: why are the tags generated when the tags plugin is not enabled into the mkdocs.yml?

I've not reached a final conclusion whether it makes sense or not to integrate tags inside search when the tags plugin is inactive, since tags indexing is subject to the search plugin, but I guess it makes more sense to omit tags when the plugin is not active. It's probably more what you'd expect. I'll add a patch for this later 😊

**Comment by squidfunk** [comment]
[`57f5ac621`](https://github.com/squidfunk/mkdocs-material-insiders/commit/57f5ac621729c0b27f4b844951ed38adbd661e5c) fixes the issue with tags being included in the search index, although the plugin was not switched on.
