### ISSUE TITLE
Sidebar nav sometimes disappears

### ISSUE THREAD

**Issue by viewty** [squidfunk/mkdocs-material#31]
Hey.

Thanks for making this theme - it's really nice. Read through the open discussion and excited to see you plan to refactor and do a big release in the coming months - looking forward to that.

In the mean time, noticed a bug last night: occasionally the sidebar nav would disappear. If the .md is very long and has a lot of ## through it so that the sidebar nav is too long, when you click on some links it vanishes. Comes back when you scroll though so not critical.

Chrome on Mac in case that's relevant.

**Comment by squidfunk** [comment]
Yes, correct, this is a bug which I also noticed, but on very rare occasions in a way that seemed not very reproducible to me. However, as you already noticed, I'm refactoring it anyway and the sidebar-mechanic will be somehow different to now.

I will leave this issue open for further reference, until it is resolved with 1.0.0.

**Comment by Fuzzyma** [comment]
I can reproduce that. Every time I click a navigation links to an anchor near the bottom, the navigation disappears (just not in scroll sight).

**Comment by squidfunk** [comment]
Fixed in upcoming 1.0.0, see #46. Issue will remain open until release.
