### ISSUE TITLE
Instant navigation breaks Mermaid diagrams

### ISSUE THREAD

**Issue by patrislav1** [squidfunk/mkdocs-material#3105]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When navigating from another page, the diagram is not shown, but only its Mermaid code as text.

### Expected behaviour

The diagram should show up also when navigating from another page.

### Actual behaviour

Enabling `navigation.instant` makes diagrams not show up, when navigating from another page to the page containing the Mermaid diagram. Instead of the diagram, the Mermaid code is shown as text. If the page containing the diagram is reloaded in the browser (which probably bypasses the instant navigation feature), then the Mermaid diagram is drawn properly.

### Steps to reproduce

1. Create a dummy landing page and a second page containing a Mermaid diagram
2. Enable instant navigation and mermaid2 plugin
3. `mkdocs serve` and open browser
4. Click the diagram page in the navigation
[index.md](https://github.com/squidfunk/mkdocs-material/files/7329192/index.md)
[test.md](https://github.com/squidfunk/mkdocs-material/files/7329194/test.md)

### Package versions

- Python: `Python 3.8.10`
- MkDocs: `mkdocs, version 1.2.2 from /home/huesmann/.local/lib/python3.8/site-packages/mkdocs (Python 3.8)`
- Material: `Version: 7.3.2`

### Configuration

```yaml
site_name: Test

theme:
  name: material
  features:
    - navigation.instant

plugins:
  - mermaid2

nav:
    - 'Index': 'index.md'
    - 'Test': 'test.md'
```

### System information

- Operating system: Ubuntu 20.04 LTS
- Browser: Firefox 93.0 (64-bit)

**Comment by facelessuser** [comment]
I have a working codepen here https://codepen.io/facelessuser/pen/oNeNydQ. You just need to subscribe to appropriate events.

**Comment by AlphaJack** [comment]
@facelessuser you did a small typo, but appending that snippet to your mermaid loader works! Do you have a suggestion for your arithmatex loader (or katex in general) as well?

**Comment by facelessuser** [comment]
> Do you have a suggestion for your arithmatex loader (or katex in general) as well?

I can just point you at what I do. You probably need to strip out UML related stuff and the `MutationObserver` stuff used for my theme toggling, but here it is:

- The loader: https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/js/extra-loader.js
- Which calls the math logic: https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/js/arithmatex.js
- MathJax config stuff (ignore anything non-MathJax in the file): https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/js/material-extra-3rdparty.js#L3
- Arithmatex setup: https://github.com/facelessuser/pymdown-extensions/blob/main/mkdocs.yml#L138
- Inclusions for MathJax or KaTeX.

This should work for MathJax to KaTex. I've tested both before. I don't recall needing anything else for KaTeX. I do test it on occasion, but currently, I am running with MathJax. While everything should run fine for KaTeX, I did need some styling tweaks. Just the KaTeX styling from this file, everything else can be ignored. Keep in mind it is in SCSS, so you need to format it for CSS: 

- https://github.com/facelessuser/pymdown-extensions/blob/main/docs/src/scss/extensions/_arithmatex.scss#L29

Anyways, hope that helps.

**Comment by golfecholima** [comment]
I'm using the native Mermaid integration but the navigation.instant still seems to be breaking my graphs.

The graphs show on a page refresh but then reverts to unprocessed text if any of the in-page navigation sections are clicked. 

Pipfile:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
mkdocs-material = "*"
mkdocs-encryptcontent-plugin = "*"
mkdocs-git-revision-date-localized-plugin = "*"
mkdocs-git-authors-plugin = "*"
mkdocs-table-reader-plugin = "*"

[dev-packages]

[requires]
python_version = "3.12"
```

Disabling navigation.instant fixes the issue.

**Comment by squidfunk** [comment]
@golfecholima we need a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) to investigate. Also, please create a new issue and please carefully read our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).

**Comment by golfecholima** [comment]
It was an issue with Encryptcontent plugin, solved by implementing this: https://unverbuggt.github.io/mkdocs-encryptcontent-plugin/features/jsext/#mkdocs-material

Thanks!
