### ISSUE TITLE
Feature suggestion: auto-collapsing large table of contents

### ISSUE THREAD

**Issue by PVasili** [squidfunk/mkdocs-material#3107]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [x] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

### Description

The TOC on the right side should be collapseble like the navigation on the left side (the key in mkdocs.yml ).

### Use Cases

This will visually improve the perception of the large TOC

### Screenshots / Mockups

<a href="https://ibb.co/GTdhMgG"><img src="https://i.ibb.co/WtHTzS7/toc.png" alt="toc" border="0"></a>

**Comment by squidfunk** [comment]
There doesn't seem to be much interest in the community for this feature, which is why I'm currently not considering it to be ready for implementation. Closing.

**Comment by sdelquin** [comment]
Hi @squidfunk. Honestly thank you for all the work behind mkdocs-material. It's really awesome!! 😲
By the way, I find this feature **really interesting**. Is there any chance to add it?

**Comment by squidfunk** [comment]
Thanks for tagging. Yes, maybe at some point, but we're currently working on much bigger things. However, once we work on the table of contents again, we might add a feature toggle to add auto-collapsing.
