### ISSUE TITLE
How to add more 1 line break in content?

### ISSUE THREAD

**Issue by ngtrian** [squidfunk/mkdocs-material#312]
How to add more 1 line break in content? I have create 2, 3, or 4 line break, but result still is 1 line break.

### System information

* OS: Windows 10
* Browser: Chrome

**Comment by facelessuser** [comment]
Can you provide an example to help make your question more clear?

**Comment by ngtrian** [comment]
i want create more one line break  word in content (enter twice to insert newline)

ex:
my file markdown:

```
title




line 1

line 2

line3
```

result on site:

```

```

**Comment by ngtrian** [comment]
now I'm using custom html **`<br>`** in content markdown to resolve this problem

**Comment by facelessuser** [comment]
Yes, you can always insert `<br>`.  There is also this extension http://facelessuser.github.io/pymdown-extensions/extensions/escapeall/, which allows you to escape new lines and turn them into `<br>` if you enable `hardbreak`.

So you could simply do the following:

```
title\
\
\
\
\
line 1
```

Anyways, so either inserting `<br>` manually can get you there, or using an extension.  If you are already using `pymdown-extensions`, you can just enable `pymdownx.escapeall` and enable `hardbreak`.

**Comment by squidfunk** [comment]
Thanks @facelessuser for answering this.
