### ISSUE TITLE
[insiders] docker-based installation doesn't work without manually creating tags

### ISSUE THREAD

**Issue by funkypenguin** [squidfunk/mkdocs-material#3127]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hey @squidfunk!

I've tried to follow the instructions at https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#with-docker re building my own docker image, and keeping it in sync with the insiders' repository.

I've encountered 2 problems:

1. The pull app doesn't seem to pull from your repo, although it does work with other repos. In debugging this, I notice that GitHub (now?) has a feature to sync with an upstream repo, so I manually did that to bring my fork up-to-date.
2. The docs say:
> When a new Insiders version is released on the upstream repository, the Pull App will create a pull request with the changes and pull in the new tag, which is picked up by the publish workflow that builds and publishes the Docker image automatically to your private registry.

Since the pull app didn't work for me, I can't be sure that this would work differently with the app, but manually syncing my fork to upstream didn't sync across any tags. And AFAIK, a PR also doesn't include tags, so I'm not sure how this build workflow would be triggered?

Currently my workflow is to manually (via GitHub UI) trigger a sync with upstream, and then to manually create a release, which then triggers the publish workflow.

Am I missing something? :)

### Expected behaviour

Process of keeping my own insiders' Docker image up-to-date is automatic

### Actual behaviour

Manual intervention is required in order to update my repo and trigger a build

### Steps to reproduce

1. Fork the insider's repo
2. Install the pull app
3. Make a change to the insider's repo, add a tag
4. Observe that (a) the pull app doesn't create a PR, and (b) syncing the fork with upstream doesn't sync the tag, and the publish workflow is not automatically run

### Package versions

N/A, since we're just discussing GitHub here :)

### Configuration

```yaml
N/A
```

### System information

GitHub

**Comment by fkorotkov** [comment]
@squidfunk, sorry I missed my mention. Just saw notification about the thread one you commented again.

In our case we have a fork, once in a while I [sync it from the UI](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) and create a release to trigger the [`publish` workflow](https://github.com/squidfunk/mkdocs-material/blob/37fe21e9f5f42dddcc1f3d33042eaf7099cc477a/.github/workflows/publish.yml#L25) (which is triggered on a release and not a tag creation which are different on GitHub).

**Comment by squidfunk** [comment]
@fkorotkov no worries, thanks! So basically the same thing the author of the OP is doing. I'm seeing no other possible solution than creating the releases manually or using the `git-sync` action when Insiders is used without any overrides on the repository. If somebody comes up with a working solution, I'm more than happy to add it to the documentation.

I've also taken some time to experiment with syncing an upstream repository to a fork, but couldn't figure out how to manually sync tags inside of a GitHub Action. It appears that `git clone` works with a valid `GH_TOKEN`, but adding a repository as a remote and fetching all tags manually doesn't:

```
git remote add upstream https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
git fetch upstream --tags
```

I don't really understand why, though.

**Comment by squidfunk** [comment]
So it seems there's currently no alternative to creating the tags by hand or using something like `git-sync` that will do it for you. For this reason, there's nothing that we can do at this very moment. Closing for housekeeping.
