### ISSUE TITLE
Can you add exclude a header from toc in secondary sidebar?

### ISSUE THREAD

**Issue by ngtrian** [squidfunk/mkdocs-material#313]
## Description
Can you add exclude a header from toc in secondary sidebar? I want add a header 5 to content, but I don't want display header 5 in secondary sidebar (md-sidebar md-sidebar--secondary)

### Package versions

* Python: `2.7.12`
* MkDocs: `0.16.3`
* Material: `1.6.1`

**Comment by facelessuser** [comment]
I believe something like this could help: https://github.com/squidfunk/mkdocs-material/issues/136, but you'd have to adjust the CSS to target your desired level.

**Comment by ngtrian** [comment]
This can not solve my problem. I want to hide heading 5 not level 2 in toc

Because I want to use headings in documents in a certain file, But I do not want them to appear in TOC.

**Comment by facelessuser** [comment]
That isn't what #136 means. The person wanted to hide anything greater than 2 levels deep (this isn't referring to h1).  So they wanted to show h2 and h3, so the solution hides h4+.  If I understand correctly, you want to hide h5+, so you would need to tweak the CSS to start hiding 1 level deeper.

Unless I am still misunderstanding.

**Comment by ngtrian** [comment]
Simple I want to use headings in documents in a certain file, But I do not want them to appear in TOC. 
Here I use heading 5 less used to avoid overlapping with the heading of other markdown files

**Comment by facelessuser** [comment]
At most, all that can be done is excluding a certain header level with CSS.  So the solution above is based on header levels (forth in the nested hierarchy), but not header type (h5). The TOC generator (which is separate from this theme), does not have the ability to exclude a specific header type.  And the TOC in the sidebar does not track the header type, but simply nests them in a logical hierarchy.

So targeting specifically h5 in the sidebar TOC (with the purpose of hiding it) is not possible, but targeting the 4th level nesting is possible.

![screenshot 2017-05-06 23 39 00](https://cloud.githubusercontent.com/assets/1055125/25778223/73ebab60-32b5-11e7-962b-4e567a1aff50.png)

```css
label[for="toc"]+.md-nav__list .md-nav__list .md-nav__list .md-nav__list {
    display: none;
}
```

But if you skipped nesting levels, for example nest h5 directly under h2, then this would not hide h5 as it would not be at the proper nested level.  So if this is not sufficient for you, I don't think what you want is possible

**Comment by squidfunk** [comment]
When you specify your heading in the Markdown file not like this:

``` markdown
##### Heading
```

but like this:

``` markdown
<h5>Heading</h5>
```

It will render correctly and won't appear in the table of contents.

**Comment by ngtrian** [comment]
thank a tip of @squidfunk

**Comment by facelessuser** [comment]
Never realized this was built-in to the current TOC plugin.  Nice to know!

**Comment by squidfunk** [comment]
Well, technically it isn't. The TOC plugin is only parsing the Markdown headline definitions, so by using HTML tags, you sneak them past the TOC plugin unoticed, as it doesn't parse the HTML. Closing this, as it seems to be solved. Otherwise please re-open.

**Comment by chrimaho** [comment]
Hi @squidfunk , is this still the case? It seems like now the TOC _is_ able to render headings which are parsed using HTML tags. Is there any other way in which we can exclude any header from being added to the TOC?

Thank you.

**Comment by squidfunk** [comment]
The fix mentioned in https://github.com/squidfunk/mkdocs-material/issues/313#issuecomment-299698639 should still work, and it should be unaffected by the new built-in typeset plugin. If that's not the case, please open a new bug report.

**Comment by gcstr** [comment]
I'm sorry to comment in such old thread, but this workaround, although it successfully removes the item from the TOC, it makes the content render differently.

Using `### Title` :

<img width="292" height="134" alt="Image" src="https://github.com/user-attachments/assets/f07f3a08-be19-4021-998e-2a3e25f26779" />
  

Using `<h3>Title</h3>`:

<img width="197" height="131" alt="Image" src="https://github.com/user-attachments/assets/63bee40d-4cbd-4d9d-84f2-63f73dcd3bbc" />

It seems that a `<p></p>` is added right before the header creating a big gap at the top.

**Comment by squidfunk** [comment]
@gcstr this looks like a bug in the Python Markdown parser. I'm quite sure this will happen with any MkDocs theme, not only Material for MkDocs. Could you test this with plain MkDocs, and if it reproduces, file an issue at [Python Markdown](https://github.com/Python-Markdown/markdown)?
