### ISSUE TITLE
Using CSS logical properties?

### ISSUE THREAD

**Issue by mahozad** [squidfunk/mkdocs-material#3160]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

In [one of your commits] I noticed that CSS properties like `margins-left` should be repeated for RTL languages (`margin-right`).

I just thought to mention [CSS logical properties] might make this a little easier.

  [one of your commits]: 403580bff8889fd4a748988f8d6631ac7a699ede
  [CSS logical properties]: https://dev.to/madsstoumann/a-quick-guide-to-css-logical-properties-2fce

### Use Cases

It's just a suggestion...

**Comment by squidfunk** [comment]
https://github.com/squidfunk/mkdocs-material/commit/bfe7540d2a931b4fe572bb63c7e0f11cf27f6ddf switches the code base to logical properties – was actually easier than expected.

**Comment by mahozad** [comment]
This is great. Using logical properties on a widely-used tool like this will promote the properties and boost [their usage](https://chromestatus.com/metrics/css/timeline/popularity/600).
