### ISSUE TITLE
versioning not working - versions.json not found

### ISSUE THREAD

**Issue by hossam-houssien** [squidfunk/mkdocs-material#3164]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

with latest update mkdocs, mkdocs-material and mike, versioning is not working using them material,
when running mkdocs serve , i got warning like
WARNING  -  [23:50:07] "GET /versions.json HTTP/1.1" code 404
and the version link in header is not displayed, however when running mike server, it is displayed correctly 

mkdocs-1.2.3
mkdocs-material-7.3.5
mike-1.1.2

### Expected behaviour

to have version selector link 

### Actual behaviour

none and got warning when runing mkdocs
WARNING  -  [23:50:07] "GET /versions.json HTTP/1.1" code 404

### Steps to reproduce

1- install mkdocs
2- install mkdocs-material
3- install mike
4- configure mkdocs.yml
5- configure mike as per [mkdocs-material-example-versioning](https://github.com/squidfunk/mkdocs-material-example-versioning)
   - mike list
        0.2 [latest]
        0.1

6- mkdocs serve

### Package versions

- Python: `python --version`
  -  Python 3.6.2 :: Anaconda custom (64-bit)
- MkDocs: `mkdocs --version`
  -  mkdocs, version 1.2.3 
- Material: `pip show mkdocs-material | grep -E ^Version`
   - Version: 7.3.6
- mike --version
   - mike 1.1.2  

### Configuration

```yaml
----------
mkdocs.yaml
--------------
 yaml
site_name: mydoc
theme:
  name: material  
extra:
  version:
    provider: mike
    default: latest
```
```


### System information

- Operating system: ...
   - OS Name:                   Microsoft Windows 10 Pro
   - OS Version:                10.0.18362 N/A Build 18362 
- Browser: ...
   - firefox 93.0 (64-bit)

**Comment by squidfunk** [comment]
Thanks for reporting.

> when running `mkdocs serve` , i got warning like [...] and the version link in header is not displayed, however when running `mike serve`, it is displayed correctly

You can't use `mkdocs serve`, you must use `mike serve` for versioning to work. That is a [limitation of `mike`](https://github.com/jimporter/mike/issues/77#issuecomment-949767624).
