### ISSUE TITLE
Send search analytics for Google Analytics 4

### ISSUE THREAD

**Issue by garrettheel** [squidfunk/mkdocs-material#3169]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

It'd be great if mkdocs-material would send search queries to GA4.

https://github.com/squidfunk/mkdocs-material/issues/1658 was the previous implementation of this for Universal Analytics (UA-*)

### Use Cases

This would help to understand how documentation is being used and improve the ranking of pages.

**Comment by garrettheel** [comment]
@squidfunk I understand that it's a little tougher to set up on the Google Analytics side, but I think it would still be nice if mkdocs-material fired a custom event for search so that the data is somehow available. I suppose it can be hacked around with custom javascript, but would be a pretty common use case.

**Comment by squidfunk** [comment]
If you would like to work on this, we can integrate it. Unfortunately, I currently don't have the bandwidth to do so. We would need a snippet to send the data, similar to the following code:

https://github.com/squidfunk/mkdocs-material/blob/b405149efd4118f6e02b2d639b784a7e9917e425/src/partials/integrations/analytics/google.html#L73-L81

And documentation, which explains how to configure Google Analytics to pick up the query. If you can provide both in a PR, I'm happy to merge it.

**Comment by garrettheel** [comment]
@squidfunk created https://github.com/squidfunk/mkdocs-material/pull/3184
