### ISSUE TITLE
keep cleanning site directory when there are 2000 files (10Gb in total) in folder

### ISSUE THREAD

**Issue by yiwc** [squidfunk/mkdocs-material#3172]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

<img width="285" alt="Screenshot 2021-11-03 at 3 44 19 PM" src="https://user-images.githubusercontent.com/44794635/140024280-f8345595-3e6b-48e5-beca-b5b811cf04f8.png">

I put 2000+ files in the subfolders, name by assets, or any other name. Then try mkdocs serve, it just stuck in cleaning site directory.

### Expected behaviour

it should serve immediately

### Actual behaviour

stuck for a long time, endless

### Steps to reproduce

1. put 2000+ files in assets (10GB)
2. mkdocs serve

### Package versions

- Python: `python --version` 3.85
- MkDocs: `mkdocs --version` 1.1.2
- Material: `pip show mkdocs-material | grep -E ^Version` 7.1.4

### Configuration

```yaml
site_name: BrainSpace
theme:
  name: material
```

### System information

- Operating system: ...macos
- Browser: ...chrome

**Comment by munozariasjm** [comment]
Having exactly the same issue. However, I don't know whose fault it is... Probably mkdocstrings-python(?)

**Comment by squidfunk** [comment]
I'd guess that this has nothing to do with Material for MkDocs. You can verify by changing the theme to  `mkdocs` or `readthedocs` and check whether the issue persists. If it does, it's either MkDocs or something else causing this.
