### ISSUE TITLE
Feedback feature does not work on safari

### ISSUE THREAD

**Issue by garrettheel** [squidfunk/mkdocs-material#3179]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The new "Was this page helpful" feature does not work on Safari. 

When clicking a button, the following error is logged to the console:

```
TypeError: null is not an object (evaluating 'e.submitter.getAttribute')
```

Per https://developer.mozilla.org/en-US/docs/Web/API/SubmitEvent/submitter, `SubmitEvent.submitter` is not compatible with IE or Safari.

### Expected behaviour

Expect the button to submit the feedback.

### Actual behaviour

No feedback and a JS console error.

### Steps to reproduce

Use the Safari browser to submit feedback.

### Package versions

- Material: `7.3.6+insiders.3.1.5`

### Configuration

```yaml
n/a
```

### System information

n/a

**Comment by squidfunk** [comment]
Fixed in [`45b6801`](https://github.com/squidfunk/mkdocs-material-insiders/commit/45b6801f0a6bdcf0ddffa557f62481ab20080fbd).
