### ISSUE TITLE
[FR] Generate integrated ToC when using navigation.indexes for sections without sub-pages

### ISSUE THREAD

**Issue by jaklan** [squidfunk/mkdocs-material#3180]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I've recently found out one additional difference between `navigation.indexes` and [mkdocs-section-index](https://github.com/oprypin/mkdocs-section-index) - when you have a sub-section (== sub-directory) with only file, which works as an index (index.md or README.md), the plugin generates integrated ToC, but `navigation.indexes` - unfortunately doesn't.

I fully understand why we don't have integrated ToCs for indexes when there are other pages, but in the above case - we can easily generate it without any confusion for users.

### Use Cases

I quite often have low-levels sections, which doesn't include any other files than README.md - I could then use `navigation.indexes`  together with `toc.integrate` and don't miss ToCs for such pages.

**Comment by jaklan** [comment]
`navigation.indexes` without `toc.integrate`:
![image](https://user-images.githubusercontent.com/24907857/140257474-cc56fa3b-37dc-4a14-b3ba-0651e64ccb28.png)

`navigation.indexes` with `toc.integrate`:
![image](https://user-images.githubusercontent.com/24907857/140257603-127602ba-3f47-45da-beb7-e70643f0c9d5.png)

[mkdocs-section-index](https://github.com/oprypin/mkdocs-section-index) with `toc.integrate`:
![image](https://user-images.githubusercontent.com/24907857/140257666-982d5ce6-43d5-452e-add7-256866cb7bf2.png)

**Comment by squidfunk** [comment]
Thanks for suggesting. As noted in the [documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages), those features are incompatible with another. Yes, it kind of works with desktop navigation, but it will fail with mobile navigation. The reason for this is that there's no place to show the table of contents on mobile, as on mobile, navigation is layered into panes:

<img width="425" alt="Bildschirmfoto 2021-11-04 um 07 46 14" src="https://user-images.githubusercontent.com/932156/140269571-1592b684-4a23-421f-bb81-de88b504aa39.png">

For example, here, "Changelog" is a section with an index page, which on click will open the page, and on expand, will open the subsection drawer. We would have to put the table of contents icon for opening the table of contents pane next to the arrow which is now a button with _three_ distinct targets. That's no good user experience. I don't know how the section index plugin solves this, but if the plugin works for you, you're very much encouraged to use the plugin.

I may look into this in the future, but currently it's considered to be out-of-scope.

**Comment by jaklan** [comment]
@squidfunk Looking quickly - the plugin seems to discover that given section doesn't have any childs (neither sub-sections nor sub-pages) and it just provides the ToC button there:
![image](https://user-images.githubusercontent.com/24907857/140270622-2a13cd60-d2c4-4373-917f-5786a173e785.png)

I haven't looked at the code, but maybe @oprypin can elaborate more on that.

**Comment by squidfunk** [comment]
Yes, you're encouraged to use the plugin. As I understand, it integrates very well with Material for MkDocs. We provide a section index experience without the plugin which caters to 90% of use cases. If your requirements are different and satisfied by the plugin, just use it.

**Comment by jaklan** [comment]
@squidfunk Well, the plugin is really fine, but the built-in solution would be always better as it doesn't have to follow changes in the theme on its own and adjust to them (and from what I experience - somehow breaking changes happen quite often). Especially when they do exactly the same job in 99% 😉 So if there's a chance to avoid external dependencies I would definitely go for that, but that single feature makes an actual positive difference in UX, that's why I'm reporting it.

I'm not familiar with `mkdocs-material` internals, but it seems that some if statement like `toc_button if no children else arrow` could do the job.

**Comment by squidfunk** [comment]
> So if there's a chance to avoid external dependencies I would definitely go for that, but that single feature makes an actual positive difference in UX, that's why I'm reporting it.

That's exactly the reason why we're providing this functionality out of the box. I understand that you don't want to introduce further dependencies, but as noted i the documentation, those settings are not compatible and thus out of scope. I hope for your understanding!

**Comment by jaklan** [comment]
@squidfunk I would be quite stubborn here 😉 From the quick research I see it should be doable with some additional `if`s in `partials/nav.html` and `partials/nav-item.html`. I fully understand you don't treat it as a priority, but would you accept the PR adding that feature?

**Comment by squidfunk** [comment]
Of course, I'd be curious to see your solution.
