### ISSUE TITLE
Please change Greek language code to "el"

### ISSUE THREAD

**Issue by alkisg** [squidfunk/mkdocs-material#3182]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi, the country "Greece" (or Hellas) has a domain of "gr".
The language "Greek" (or H**el**lenic), is used in both Greece and Cyprus, and has a language code of "el".
Reference: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

Please rename this file: https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/languages/gr.html
to: https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/languages/el.html
Also update its line "25" to "el".
Finally, update the documentation accordingly: https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/

### Expected behaviour

The Greek language code should be "el".

### Actual behaviour

The Greek language code is "gr".

### Steps to reproduce

Select the "gr" language in the settings.

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
theme:
    name: material
    language: el
```

### System information

Ubuntu 20.04.

**Comment by squidfunk** [comment]
Thanks for reporting. Could you craft a PR for this?

**Comment by squidfunk** [comment]
Greek translations were added in #986. @cakrit – do you know why you've chosen `gr` as a language code?

**Comment by alkisg** [comment]
Sure, I filed a PR in #3183.

Thanks for mkdocs-material, I haven't started using it yet; [my](https://ltsp.org) [sites](https://epoptes.org) are currently using just-the-docs, and I was considering to migrate to mkdocs or sphinx. When I saw mkdocs-material, I made up my mind very quickly!

I'm closing this issue, I think we can comment in the PR from now on...

**Comment by squidfunk** [comment]
Perfect! Thanks for the PR! I'd be curious to hear what you're missing from Sphinx and Just the Docs that you found in Material for MkDocs. I'm always eager to learn what users love and what could be improved 😊

**Comment by alkisg** [comment]
Just-the-docs lacks a lot of things, like admonitions, content tabs and support for multiple versions/languages.
Sphinx has most of these, and even some more that we don't really need.

But rst vs markdown is a bit like comparing ...maintaining documents with latex vs wordpress. If one's needs can be satisfied with something simpler, there's no need to select something more powerful but also more difficult.

With markdown, documentation contributors can go to https://vscode.dev/github/organization/project and start editing and committing documents, with a nice preview, from any browser, without even having to learn about git.

While with rst/sphinx, they'd need a big learning curve and a development PC.

One thing that we'll definitely need, and that doesn't work with mkdocs/just-the-docs, but works with sphinx is "Greek language support in Search". I hope we'll eventually be able to add Greek language support to the underlying javascript library there.

And another difference is "exporting our whole documentation to pdf"; from what I saw, sphinx goes through latex, while mkdocs goes through weasyprint (=html/js/css). I'm not sure which one will be best of our needs there; e.g. we can't even right-align an image and flow the text to the left with sphinx/pdf; not sure if that will be possible with weasyprint...

Thanks for listening! :)

**Comment by squidfunk** [comment]
Thanks for providing the rationale! Greek search should work, maybe not perfect (i.e. without stemming), but it should work to a reasonable degree. If it doesn't, we might need to use another language from `lunr-languages`. Other than that, it shouldn't be too hard to add support to `lunr-languages`.
