### ISSUE TITLE
Insider build fails during provided Github Action

### ISSUE THREAD

**Issue by ironicbadger** [squidfunk/mkdocs-material#3187]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Build and push Docker image action fails:

```
/usr/bin/docker buildx build --tag ghcr.io/ironicbadger/mkdocs-material-insiders:latest --tag ghcr.io/ironicbadger/mkdocs-material-insiders: --iidfile /tmp/docker-build-push-lCB1Wy/iidfile --metadata-file /tmp/docker-build-push-lCB1Wy/metadata-file .
error: invalid tag "ghcr.io/ironicbadger/mkdocs-material-insiders:": invalid reference format
Error: buildx failed with: error: invalid tag "ghcr.io/ironicbadger/mkdocs-material-insiders:": invalid reference format
```

### Expected behaviour

Build succeeds

### Actual behaviour

Tag not being parsed correctly.

### Steps to reproduce

https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#with-docker

Log archive attached.

[logs_5.zip](https://github.com/squidfunk/mkdocs-material/files/7480078/logs_5.zip)

### Package versions

n.a

### Configuration

```yaml
n.a
```

### System information

github action

**Comment by squidfunk** [comment]
We reverted the Insiders build workflow to the tag-based approach. Could you verify whether it works now for you?

**Comment by squidfunk** [comment]
Closing, as I'm pretty sure we've fixed the issue. In case more problems arise, please reopen.
