### ISSUE TITLE
Integrate local 3d content as seamless as images

### ISSUE THREAD

**Issue by mniehus** [squidfunk/mkdocs-material#3189]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Hi . iframe embedding 3d content from online sites like e.g. sketchfab.com works like a charm. Nevertheless,  a feature/method would be great that allow to integrate local 3d content as seamless as images. any py or js thoughts ?

### Use Cases

3d contents will be one of the outstanding features in next-gen sites

**Comment by squidfunk** [comment]
I'm not sure I understand what you mean. Since this is not specific to Material for MkDocs, but MkDocs in general, I'm converting this to a discussion. Could you provide some more details what you mean specifically?
