### ISSUE TITLE
Compose "What is metrics"

### ISSUE THREAD

**Issue by linhdang** [squidfunk/mkdocs-material#32]
Explain how to amit metrics (Value, Dimesion, Unit)

**Comment by viewty** [comment]
What do you mean Linh?

**Comment by squidfunk** [comment]
Sorry, but I don't understand your request. I will close this issue for now, but you can elaborate on what you meant and we can reopen it again.

**Comment by linhdang** [comment]
sorry for the inconvenient, i supposed to create the issue on a different repo. You can close this one
