### ISSUE TITLE
Latest Chrome creates double underline on abbr tags

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#320]
## Description

Latest Chrome on PC/Mac/Android now adds a default style to `abbr` tags that is done with `text-decoration`.  Material's looks nicer, but currently both get shown.  `abbr` should apply `text-decoration: none;` to prevent showing both.  If I have a chance soon, I can issue a pull.

### Expected behavior

Only have one stippled underline applied to `abbr`.

### Actual behavior

Multiple stippled underline are shown under `abbr`.

### Steps to reproduce the bug

1. Render documents with `abbr` in Material.
2. View documents in Chrome Version 58.0.3029.110 (64-bit).

### Package versions

* Python: Any
* MkDocs: Any
* Material: 1.6.1

### System information

* OS: Any
* Browser: Chrome Version 58.0.3029.110 (64-bit)

**Comment by squidfunk** [comment]
Fixed in #327 and released as 1.6.2 shortly.
