### ISSUE TITLE
Insiders: Inconsistent release/version number

### ISSUE THREAD

**Issue by Guts** [squidfunk/mkdocs-material#3201]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hello,

Just a minor remark:

3.2.1 in package.json: <https://github.com/squidfunk/mkdocs-material-insiders/blob/master/package.json#L3>
3.2.2 in git tag (release): <https://github.com/squidfunk/mkdocs-material-insiders/releases/tag/7.3.6-insiders-3.2.2>

### Expected behaviour

Consistent semver number to make the pip install with tags suitable. Maybe check it during the release workflow or use the git tag to automatically set the package version?

### Actual behaviour

ND

### Steps to reproduce

ND

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
ND
```

### System information

ND

**Comment by squidfunk** [comment]
Thanks for reporting. My bad. I bumped the version and re-issued the latest release.
