### ISSUE TITLE
Feature suggestion: centralized abbreviation file

### ISSUE THREAD

**Issue by michael-nok** [squidfunk/mkdocs-material#3213]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Currently, the only way to include a common abbreviation definition file is by using snippets, however, this requires the user to add the snippet code on every markdown page.

https://squidfunk.github.io/mkdocs-material/reference/abbreviations/#adding-a-glossary

Given that these abbreviations usually apply for all of the content in a specific mkdocs.yml collection, it would be ideal if this was a centralized option.

```
theme:
  features:
    - abbreviations: includes/abbreviations.md
```

### Use Cases

In writing, there's nothing more that I hate then an undefined acronym.  The documentation I work with tends to have a significant amount of acronyms, which requires me to ensure I include a common abbreviations.md file on every page.  That solution is not very efficient and if other users create new pages or contribute, they aren't necessarily aware of this process.

**Comment by squidfunk** [comment]
Thanks for suggesting. This is something that should be taken upstream to [pymdown-extensions](https://github.com/facelessuser/pymdown-extensions/issues) as we're only rendering, not processing Markdown. I think there was already a discussion on this feature at some point, but I can't find it right now.

**Comment by facelessuser** [comment]
This is not required to be added to every page. There is a new Snippets feature that auto adds a specified snippet(s) to every file. I don't have time right now to point at it, but check out the docs and/or I'll update this post when I have a chance.

**Comment by michael-nok** [comment]
Thanks for the heads up. @facelessuser I did check the docs and you have implemented auto_append in your `mkdocs.yml` file, but did not update the actual snippets documentation on how this works.

```
  - pymdownx.snippets:
      base_path:
      - docs/snippets
      - other_path/snippets
      auto_append:
      - refs.md                // This file can be in either base_path and performs the magic.
      check_paths: true
```

**Comment by facelessuser** [comment]
🤦🏻‍♂️, yep. I probably need to update the docs. But it's there...just undocumented except in a passing comment in the changelog.
