### ISSUE TITLE
if search is blank, page rendered improperly

### ISSUE THREAD

**Issue by flynneva** [squidfunk/mkdocs-material#3214]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

when search query is blank in URL page is rendered with html character codes

### Expected behaviour

page is rendered without html character codes visible to end user

### Actual behaviour

symbols replaced with html character codes (i.e. `'` replaced with `&#39;`)

![Screenshot from 2021-11-12 09-05-23](https://user-images.githubusercontent.com/6157095/141506210-583fa0e4-9eb1-4e83-9b57-47522cb706e2.png)

### Steps to reproduce

check it out live on [the mkdocs-material site](https://squidfunk.github.io/mkdocs-material/creating-your-site/?h=)

### Package versions

NA but can fill it out if desired

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
https://squidfunk.github.io/mkdocs-material/creating-your-site/?h=
```

### System information

NA

**Comment by squidfunk** [comment]
Fixed in 15f74d81f.
