### ISSUE TITLE
Accepting cookie consent does not dismiss modal dialog

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#3216]
### Discussed in https://github.com/squidfunk/mkdocs-material/discussions/3215

<div type='discussions-op-text'>

<sup>Originally posted by **jhendricks123** November 12, 2021</sup>
I'm using the anchor tag `#__consent` to enable the user to launch the cookie consent dialog on demand, and when you manually launch the dialog this way, the **Accept** button does not dismiss the dialog. It basically reloads the page with /#__consent still in the URL. So you have to manually remove the anchor tag from the URL to get it to go away.

Right now I have the link as a button in the footer. I put the link there using the copyright property in mkdocs.yml. Not the most obvious place for it but it was a quick and easy way to give the user access to it on any page. The behavior is the same though whether I do it this way, or put `[Change cookie settings](#__consent)` in the body of a page.

You can see the behavior on [milestonepstools.com](https://www.milestonepstools.com). Scroll down to the bottom of the page and click the "Change cookie settings" button.</div>

**Comment by jamesrwelch** [comment]
I've had this problem - I have an override which does
```
window.location.hash = '';
```
before reloading the window in the javascript function.  I'm not sure how 'good' a solution this is - it seems to work for me - but I can submit it as a pull request if you think it's an adequate solution.

**Comment by squidfunk** [comment]
Jup, that should work. A PR is appreciated 😊

**Comment by squidfunk** [comment]
Thanks for @jamesrwelch, this has just been fixed in the latest commit on Insiders 😊

**Comment by jhendricks123** [comment]
Thanks @jamesrwelch and @squidfunk - I happened to update the site today and noticed the change. Much appreciated!

**Comment by squidfunk** [comment]
The fix was just released as part of 7.3.6-insiders-3.2.3.
