### ISSUE TITLE
configuration issue (idk wat title to put)

### ISSUE THREAD

**Issue by pherngpy** [squidfunk/mkdocs-material#3222]
- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

help me
```js
Run mkdocs gh-deploy --force
WARNING  -  Config value: 'palette'. Warning: Unrecognised configuration name: palette
WARNING  -  Config value: 'features'. Warning: Unrecognised configuration name: features
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/runner/work/Gale-Docs/Gale-Docs/site
INFO     -  Documentation built in 0.34 seconds
WARNING  -  Version check skipped: No version specified in previous deployment.
INFO     -  Copying '/home/runner/work/Gale-Docs/Gale-Docs/site' to 'gh-pages' branch and pushing to GitHub.
To https://github.com/pherngpy/Gale-Docs
 + 6a1e1ee...adbc95a gh-pages -> gh-pages (forced update)
INFO     -  Your documentation should shortly be available at: https://sussy-baka.blablablablablabla/
```
![Screenshot_20211114_182613](https://user-images.githubusercontent.com/77534483/141677142-22e30ad3-1a79-4e2a-88dc-d837471a8f95.JPG)

### Package versions :

All lastest

### Configuration :

```yaml
site_name: docs for fun eeeeeeeeeeeeeeeeeeeeeeeeeeeee
site_url: https://example.blablablablabla/
nav:
    - Home: index.md
    - About: about.md
theme: 
    name: 'material'
palette: # 

    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate # 

      toggle:
        icon: material/weather-night
        name: Switch to light mode
features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
plugins:
  - search:
      lang: 'en'
```
- Operating system: Github

**Comment by squidfunk** [comment]
Your indentation is incorrect. `features` must be a child of `theme`:

``` yaml
theme:
  features:
    - ...
```

**Comment by pherngpy** [comment]
thx but pls also help me on the another issue
```js
Unrecognised configuration name: palette
```

**Comment by squidfunk** [comment]
Exactly the same problem. YAML is whitespace sensitive. Please stick to the documentation:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme
