### ISSUE TITLE
Change the order of versions in dropdown

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#3251]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

Currently, textual versions like `dev` or `master` come after real numeric versions and are not easy to find/select when there are many versions.

### Use Cases

Easier time selecting special versions

**Comment by ofek** [comment]
@squidfunk If accepted, do you think this could be in v8.0.0?

**Comment by squidfunk** [comment]
Thanks for suggesting. If you look into the network inspector, are the versions in `versions.json` in the same order?

**Comment by ofek** [comment]
Ah, yes https://github.com/ofek/hatch/blob/gh-pages/versions.json

**Comment by squidfunk** [comment]
Okay, then please report this to [`mike`](https://github.com/jimporter/mike), because Material for MkDocs only consumes the contents of this file.
