### ISSUE TITLE
<kbd> could do with more space around it, and nested <kbd> looks weird

### ISSUE THREAD

**Issue by mrmanc** [squidfunk/mkdocs-material#3255]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Using `<kbd>` to represent combinations of keystrokes with `+` and/or `,` separating the keys looks a little weird, as the adjoining characters are basically touching the rendered key. This is especially true if you use a comma (such as press these two keys, then this key). It would look better is there was a little more space either side of the key.

In addition, nesting `<kbd>` tags (as [suggested in the spec](https://www.w3.org/TR/2013/CR-html5-20130806/text-level-semantics.html#the-kbd-element)) when they appear as a combination causes them to be rendered in a stack of keys. It would probably look better with no decoration around the outer `<kbd>`, but I’m sure some way to visually group them could be found by someone with more design skills then myself.

### Expected behaviour

Using `<kbd><kbd>^</kbd>+<kbd>`</kbd>, <kbd>3</kbd></kbd>` should clearly show that the control and backtick keys should be pressed, then the `3` key.

### Actual behaviour

The comma is hard to distinguish, and the keys appear on top of a larger key spanning all three.

### Steps to reproduce

1. Add `kbdextension` with this config:
    ```
      - kbdextension:
          enable_braces: true
    ```
1. Use ``{{ [[^]]+[[`]],[[3]] }}`` in a page which will be converted as `<kbd>` tags
1. Look at how it is rendered

### Package versions

- Python: `python --version`
  `Python 3.9.7`
- MkDocs: `mkdocs --version`
  `mkdocs, version 1.2.3 from /usr/local/autotrader/lib/python3.9/site-packages/mkdocs (Python 3.9)`
- Material: `pip show mkdocs-material | grep -E ^Version`
  `Version: 8.0.0b2`

### Configuration

```yaml
markdown_extensions:
  - kbdextension:
      enable_braces: true
theme:
  name: 'material'
```

### System information

- Operating system: Linux (`uname -a` reports `Linux 6d145cb40aab 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`)
- Browser: Chrome `Version 95.0.4638.69 (Official Build) (x86_64)`

**Comment by squidfunk** [comment]
Thanks for reporting. Please provide screenshots of the behavior you're seeing.

**Comment by mrmanc** [comment]
With `kbdextension`:
![using kbdextension](https://user-images.githubusercontent.com/547606/143463230-85f6c2ce-d93b-4f0c-b6e5-fdd7e612e480.png)

I had no idea it was possible to attach images to issues so easily, otherwise I would have originally! 😃 

Thanks for the tip about using `pymdownx.keys`. Not sure why I hadn’t spotted that in the docs—I think I probably Googled something and jumped straight to the extension. Looks like you have to enable the [strict kbd output](https://facelessuser.github.io/pymdown-extensions/extensions/keys/#strict-kbd-output) option to end up with nested tags, so it’s an edge case. I’ve switched over and the screenshot below represents the markup from the supported mechanism.

With `pymdownx.keys`:
![using pymdownx.keys](https://user-images.githubusercontent.com/547606/143462736-f31f160a-2ad6-45f8-803e-eb43f27d0612.png)

The spacing between keys looks great now, but when using `++ctrl+grave++, ++3++` for the above keystroke sequence the comma is still hard to see. Would you see this as a Material a PyMdown thing?

**Comment by facelessuser** [comment]
This is not a pymdown thing as it provides no styling on its own. You could certainly tweak this with custom CSS, but we'll have to wait and see Material's opinion as to whether this is viewed as something to "fix" directly in Material.

**Comment by squidfunk** [comment]
I'm not intending to introduce extra margin on keyboard keys, because they are inline elements, and while I understand that some users find the comma being too close to the elements, I do not want to force this upon users. However, [tweaking the CSS is super easy](https://squidfunk.github.io/mkdocs-material/customization/#additional-css), so you add as much margin as you like. In fact, one of the core principles of Material for MkDocs is to provide sane default styling, but always allow the user to customize and override appearance. This is infact one of the value propositions of Material Design itself – it's just a sane default.

For this reason, I'm closing this issue as a customization request.

**Comment by mrmanc** [comment]
Thanks, that is a really reasonable response and I really appreciate your time. Thanks Martin! 😃
