### ISSUE TITLE
8.0.0 regression: extra margin in admonitions

### ISSUE THREAD

**Issue by fottsia** [squidfunk/mkdocs-material#3265]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

After updating to 8.0.0, admonitions that are inside links have extra margin in their titles.

### Expected behaviour

They shouldn't have extra margin.

### Actual behaviour

And yet they do.

### Steps to reproduce

Create a list and an admonition inside it, with material 8.0.0.

### Package versions

- Material: 8.0.0

### Configuration

```yaml
...
```

### System information

- Operating system: Ubuntu 20.04
- Browser: Firefox

**Comment by squidfunk** [comment]
Already fixed in 8fa834f73c9027bf3d3a4f0d8560a587e41f805b.

**Comment by squidfunk** [comment]
Released as part of 8.0.1

**Comment by rachel-rigdon-sp** [comment]
@squidfunk I'm seeing this error again in 8.1.1. It works when I'm running 8.0.1 but reintroduces the extra margin if I update to 8.1.1.

**Comment by alkisg** [comment]
We too have the same issue with 8.1.1, for example [here](https://ts.sch.gr/docs/linux/guides/gparted/#%CE%B4%CE%B7%CE%BC%CE%B9%CE%BF%CF%85%CF%81%CE%B3%CE%AF%CE%B1-%CE%BD%CE%AD%CE%B1%CF%82-%CE%BA%CE%B1%CF%84%CE%AC%CF%84%CE%BC%CE%B7%CF%83%CE%B7%CF%82).

**Comment by squidfunk** [comment]
Thanks for reporting. I refactored the CSS to reduce specificity in 8.1.0 and 8.1.1. Fixed in be24342a7.

**Comment by squidfunk** [comment]
Released as part of 8.1.2
