### ISSUE TITLE
Reproductible build

### ISSUE THREAD

**Issue by parisni** [squidfunk/mkdocs-material#3268]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

So far, if one of the md file of my doc is modified, all the html files  get modified, resulting in a large commit. Apprently the modification are essentialy random newlines.

Is there a way to avoid modifiyng every files when only in order not to flood commits when doc is modified ?

Thanks

### Use Cases

Modifying the doc and pushing result in the master branch

**Comment by squidfunk** [comment]
Material for MkDocs is only a theme, the build is executed by [MkDocs](https://www.mkdocs.org/). I'm pretty sure what you're asking is not possible, but you should probably ask the maintainers of this project. Closing as upstream question/issue.
