### ISSUE TITLE
Feature suggestion: Make navigation in footer configurable

### ISSUE THREAD

**Issue by pideu-mh** [squidfunk/mkdocs-material#3273]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I am currently using _mkdocs_ for a project where the documentation is kind of "non-linear." In other words: the previous_page and next_page navigation in the footer may confuse people and so I wanted to get rid of it.

A lot of things are configurable, for example using _config.extra.generator_ to disable the generator message.

Unfortunately there is no option to disable the navigation in the footer using a configuration option.

I got the job done by using the "custom_theme" feature and then supplying a modified version of _footer.html_ where the navigation was commented out.

This worked fine unless recently there was an update to _mkdocs_ and the original version of _footer.html_ was modified in such a way that it did not went well my modified version.

So my suggestion is to add a configuration option _config.extra.disable_navigation_ to make it configurable whether the navigation bar is included in the footer or not.

### Use Cases

_mkdocs_ may be used for documentation that is non-linear and where the previous / next page navigation simply does not make sense.

Having this navigation should be the default, however it should be configurable to disable it for documentation that does not need it.

**Comment by pideu-mh** [comment]
Thank you very much for your constructive answer.

> Otherwise, just use CSS, which is rarely changed in major versions.

I already have a CSS in place for changing the primary color, so I simply added your suggestions there and it works fine!

**Comment by Yang-Xijie** [comment]
It might be a great idea to provide an option to configure the `previous / next page navigation`.

**Comment by Yang-Xijie** [comment]
> #### Using additional CSS
> [Add a CSS file](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) with:

Using additional CSS

[Add a CSS file](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) with: 

```
.md-footer__inner.md-grid {
    display: none
}
```

will work with `8.3.1`.
