### ISSUE TITLE
Instant navigation doesn't respect #hash

### ISSUE THREAD

**Issue by fottsia** [squidfunk/mkdocs-material#3274]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When `navigation.instant` is set in mkdocs.yml, if a page1 links to page2#hash, then page2 is indeed loaded, but the #hash part is ignored.

### Expected behaviour

We should navigate to the #hash header/anchor.

### Actual behaviour

We are directed to the start of page2.

### Steps to reproduce

Create a page1 that links to page2#anchor.

### Package versions

- Python: 3.9.9
- MkDocs: 1.2.3
- Material: 8.0.1

### Configuration

```yaml
theme:
  features:
    - navigation.instant
```

### System information

- Operating system: Ubuntu 22.04
- Browser: Firefox

**Comment by squidfunk** [comment]
Could you please check if the issue also appears with 7.3.6?

**Comment by kgidarakos** [comment]
This issue also affects me.
Thanks in advance

**Comment by squidfunk** [comment]
@kgidarakos in the future, please just use the voting mechanisms on the OP and/or subscribe to the issue.

**Comment by fottsia** [comment]
In 7.3.6 it's a lot better: the browser window shows page2#anchor at its middle
In 8.0.1: the browser window shows page2 at its top (i.e. the start of page)

The desired outcome should be: the browser window to show page2#anchor at its top.

I.e. 7.3.6 is a whole lot better than 8.0.1, and it's probably acceptable behavior, but maybe not ideal.

**Comment by squidfunk** [comment]
Thanks. There were some changes that might impact instant loading. If you depend on it (e.g. when you have a large search index that you only want to initialize once), the recommendation is to use 7.3.6 for now.

**Comment by kgidarakos** [comment]
> @kgidarakos in the future, please just use the voting mechanisms on the OP and/or subscribe to the issue.

I wanted to emphasize the need to solve the problem.  Of course, in a problem with many user reports I would just vote. 
Nevertheless, I understand your attitude.

**Comment by squidfunk** [comment]
> I wanted to emphasize the need to solve the problem. Of course, in a problem with many user reports I would just vote.
Nevertheless, I understand your attitude.

Yes, thank you for that. I will look into it as soon as possible. The thing is that you're posting comments, saying that you are also affected without _any_ further information on every issue your colleague @fottsia or @alkisg are commenting increasing the overall noise. Therefore I'm kindly asking you to just use the voting system and subscribe to stay updated.

**Comment by squidfunk** [comment]
Fixed in ebcd000fd. It was a regression introduced in a refactoring done in 8.0.0.

**Comment by squidfunk** [comment]
The fix was just released as part of 8.0.4.
