### ISSUE TITLE
Undefined Stars / Forks

### ISSUE THREAD

**Issue by alexcurtin** [squidfunk/mkdocs-material#329]
## Description

Github Stars/Forks says Undefined Stars / Undefined Forks.

### Expected behavior

The github area shows stars/forks

### Actual behavior

Github Stars/Forks says Undefined Stars / Undefined Forks.

### Steps to reproduce the bug

1. set repo_name: and repo_url in mkdocs.yml
2. private repo?
3. see bug.

Am I getting undefined stars / forks for my github url because its a private repository? If so, can we add a way to have our container auth to github before this function makes its call to the repository to find # of stars and forks?

**Comment by squidfunk** [comment]
Do you have the same error with a public repo?

**Comment by kcgthb** [comment]
I think there would be a use case here indeed, for public docs hosted out of a private repository. 

One may still want to reference a private repo in the MkDocs configuration, to allow authorized users to edit the documentation through the "Edit on GitHub" link. But I'm not sure there's a way to retrieve stars/forks from a private repo, or even it would even make sense.

So maybe a sensible route would be to hide the Stars / Forks element if the information couldn't be fetched from the repo?

**Comment by alexcurtin** [comment]
@squidfunk Yes this works on a public repo. I believe its due to the fact that we store our documentation for mkdocs/material in a private repo. Can we add a check that when that call to github to find stars/forks fails (as its saying undefined) to just leave that part blank as @kcgthb suggests above?

**Comment by squidfunk** [comment]
Yes, that makes sense. Querying a private repository for stars you would have to expose credentials to your documentation site, which is pretty bad practice. Therefore it makes most sense to let the call fail silently and leaving the repository link as it is.

**Comment by squidfunk** [comment]
Fixed in #331, will be released shortly as 1.6.3.

**Comment by alexcurtin** [comment]
@squidfunk Thanks dude! will this fix be installable via pip?

**Comment by squidfunk** [comment]
It already is, see http://squidfunk.github.io/mkdocs-material/release-notes/#upgrading how to upgrade

**Comment by alexcurtin** [comment]
@squidfunk Thanks! You're amazing :)
