### ISSUE TITLE
Metadata tags in combination with yaml codeblock gives error

### ISSUE THREAD

**Issue by ttadegraaff** [squidfunk/mkdocs-material#3301]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I insert a yaml codeblock containing triple dash (---) the build gives an error, and the page is not added to the tags.html page.

### Expected behaviour

The expected behaviour is that no error occurs, and the page with defined tags can be found in the tags page.

### Actual behaviour

When building I get the following error:
```
$ mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
ERROR    -  Couldn't parse <_io.TextIOWrapper
            name='/home/tdgraaff/Development/mkdocs/docs/blog/2021/12/04/k3s_docker_pull_through_registry.md'
            mode='r' encoding='UTF-8'> yaml due to expected a single document in the stream
              in "<unicode string>", line 2, column 1:
                tags:
                ^
            but found another document
              in "<unicode string>", line 6, column 1:
                ---
                ^
INFO     -  The following pages exist in the docs directory, but are not included in the
            "nav" configuration:
              - README.md
              - tags.md
              - tags.md
INFO     -  Documentation built in 0.25 seconds
INFO     -  [22:08:07] Serving on http://127.0.0.1:8000/
INFO     -  [22:08:09] Browser connected:
            http://127.0.0.1:8000/blog/2021/12/04/k3s_docker_pull_through_registry/
```
This happens when a page contains tags definition and a codeblock containing triple dash. For example:
<pre>
---
tags:
  - k3s
  - docker
  - kubernetes
---

# This page causes an error.

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
```
</pre>

The error seems to indicate that the tripple dash within the codeblock is parsed when parsing the meta block.

### Steps to reproduce

1. Get the code: https://git.thomasdegraaff.eu/thomasdegraaff/mkdocs-thomasdegraaff/commit/c07c9260eb14f9efc63d785bc29540098c4fe4fe
2. Run mkdocs serve
3. Notice the error
4. Go to http://127.0.0.1:8000/blog/2021/12/04/k3s_docker_pull_through_registry/
5. Click on a tag
6. Notice that the tags page is empty

### Package versions

- Python: `Python 3.8.10`
- MkDocs: `mkdocs, version 1.2.3`
- Material: `Version: 8.0.3`

### Configuration

```yaml
# Code can be found here: https://git.thomasdegraaff.eu/thomasdegraaff/mkdocs-thomasdegraaff/commit/c07c9260eb14f9efc63d785bc29540098c4fe4fe
site_name: Thomas de Graaff
site_url: https://thomasdegraaff.eu
theme:
  name: material
  palette:
    primary: black
#  features:
#    - navigation.tracking
#    - navigation.instant
#    - navigation.tabs
#    - navigation.tabs.sticky
#    - content.code.annotate
#    - navigation.top
plugins:
  - tags
#  - search
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - meta
nav:
    - Blog:
      - blog/2021/12/04/k3s_docker_pull_through_registry.md
    #- Tags: tags.md
    #- About: README.md
```

### System information

- Operating system: Linux 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Browser: Chrome Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by squidfunk** [comment]
Thanks for reporting. I'm having a hard time reproducing this error. Since you're using the `tags` plugin, I first thought that you were using the [built-in tags plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/), but you are certainly not using it because it works perfectly for me:

<img width="729" alt="Bildschirmfoto 2021-12-05 um 00 16 57" src="https://user-images.githubusercontent.com/932156/144727501-22a77fa7-9933-414a-9069-6cacf9db5c0b.png">

I'm very certain that you're using [mkdocs-plugin-tags](https://github.com/jldiaz/mkdocs-plugin-tags), which is not officially supported by Material for MkDocs, as it suffers from several issues. This is the very reason, Material for MkDocs provides its own tags plugin. Your options:

- File an issue over at [mkdocs-plugin-tags](https://github.com/jldiaz/mkdocs-plugin-tags)
- Use the [built-in tags plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/).

**Comment by ttadegraaff** [comment]
Hi Martin,

Thx for the effort. I didn't know about the different tag plugins. I got a message that a tags plugin was missing, and googled for a mkdocs tags plugin, and installed it.

I also found the following page concerning the use of tags for material: https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/

It might help open source users like me who are not used to the concept of open source software behind a paywall to mention there explicitly that the tags functionality is only available for insiders. I had no idea I was using the wrong plugin. :)

Kind regards,
Thomas de Graaff

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by squidfunk** [comment]
That's what the pulsating heart icon (call to action) + the insiders-x.x.x release tag is about 😊 I agree that it might not be clear at first, but annotating every feature with "not available in free version" is probably too much bloat.

<img width="730" alt="Bildschirmfoto 2021-12-06 um 09 52 01" src="https://user-images.githubusercontent.com/932156/144816039-ef523a91-b6fc-4d90-9d6d-274d3feb551b.png">
