### ISSUE TITLE
Getting `Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')` on 8.0.5

### ISSUE THREAD

**Issue by posita** [squidfunk/mkdocs-material#3317]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Not sure if this was present between 8.0.0 and 8.0.5, but I'm pretty sure this just started happening after a recent upgrade. I stumbled onto this error while investigating after my [work-around](https://github.com/posita/dyce/blob/3ed28e8606fec4d2fb9481d6c28186aa026f53ec/docs/js/site.js#L29) to #2727 broke from [this change](https://github.com/squidfunk/mkdocs-material/commit/887b7115fcca3c945582a3d1f90810a7aeda6ead#diff-27db428a75bbd7d3b97412161ed4136c8986748a616c8be4d93f60b16e74f22dR106).

<img width="739" alt="Screen Shot 2021-12-06 at 23 26 31" src="https://user-images.githubusercontent.com/222581/144972241-977ee19d-71ef-4d70-b83b-953049f91e54.png">

Source of current error: https://github.com/squidfunk/mkdocs-material/blob/ba539c7f5b52b8a47b239d9ab34c29ccf243f28b/src/assets/javascripts/components/palette/index.ts#L95

### Package versions

- Python: `python --version`

  `Python 3.9.7`

- MkDocs: `mkdocs --version`

  `mkdocs, version 1.2.3 from /Users/matt/Documents/dev/dyce/.tox/check/lib/python3.9/site-packages/mkdocs (Python 3.9)`

- Material: `pip show mkdocs-material | grep -E ^Version`  <-- Do you mean `grep -E '^Version'` (note quotes)

  `Version: 8.0.5`

### Configuration

```yaml
Working on isolating this….
```

### System information

- Operating system: Mac
- Browser: Brave (Chrome)

**Comment by squidfunk** [comment]
Thanks for reporting. I'm not able to reproduce this. Please make sure that the error is not within your customizations and if it isn't, provide a minimal reproducible example. also make sure to [clear your local storage](https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/) to make sure there's no stale data.

**Comment by posita** [comment]
Yup. You're right. My bad. This was an artifact of me failing to correctly update from `__prefix` to `__md_get` and `__md_set` in my work-around.

**Comment by squidfunk** [comment]
Great, glad you solved it!

**Comment by jiegec** [comment]
I got this error when upgrading mkdocs-material from 9.1.6 to 9.1.7:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at index.ts:100:26
    at map.ts:58:33
    at c._next (OperatorSubscriber.ts:70:13)
    at t.next (Subscriber.ts:75:12)
    at mergeInternals.ts:85:24
    at c._next (OperatorSubscriber.ts:70:13)
    at t.next (Subscriber.ts:75:12)
    at e._subscribe (innerFrom.ts:78:18)
    at e._trySubscribe (Observable.ts:244:19)
    at Observable.ts:234:18
```

Downgrading to 9.1.6 fixes the issue.

**Comment by squidfunk** [comment]
Does clearing your local storage solve it? See https://github.com/squidfunk/mkdocs-material/issues/3317#issuecomment-987682598

**Comment by jiegec** [comment]
> Does clearing your local storage solve it? See [#3317 (comment)](https://github.com/squidfunk/mkdocs-material/issues/3317#issuecomment-987682598)

Nope, clearing site data does not solve it.

**Comment by squidfunk** [comment]
Thanks for testing. I'm happy to look into it if you can provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) and [create a new bug report](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).

**Comment by nfantone** [comment]
@squidfunk Same here. `9.1.7` results in `Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')` as soon as you load the main page.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/476069/233995711-9f02b83f-427f-40b8-acac-c1672dc584b5.png">


Problem seems to be that the `inputs` array being passed to `watchPalette` is always empty. And the reason, as far as I could gather, is that the parent `node` from which `inputs` are being queried is seemingly wrong.

```ts
    /* Create and return component */
    const inputs = getElements<HTMLInputElement>("input", el)
    return watchPalette(inputs)
      .pipe(
        tap(state => push$.next(state)),
        finalize(() => push$.complete()),
        map(state => ({ ref: el, ...state }))
      )
```

<img width="819" alt="image" src="https://user-images.githubusercontent.com/476069/233996375-ccb14d49-8719-481f-9cfc-1c20c61f6f05.png">

**Comment by squidfunk** [comment]
Yes, that should fix the issue. I've refactored how color palettes are set and this is what should've caused the problem.
