### ISSUE TITLE
DE cookie consent button translations

### ISSUE THREAD

**Issue by anjoniewo** [squidfunk/mkdocs-material#3323]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

This issue is very much related to the [french-counterpart](https://github.com/squidfunk/mkdocs-material/issues/3205). The German translation for cookie consent buttons is missing.
I checked other languages and noticed that a few others miss the translations too.

### Expected behaviour

German translation for "Manage settings" and "Accept".

### Actual behaviour

Setting the `language` to `de` in the config-file does not translate the buttons.
It defaults to English.

### Steps to reproduce

1. Set `language` to `de`
2. Open cookie consent

### Package versions

- Python: 3.9.0
- MkDocs: 1.2.3
- Material: 8.0.2+insiders.4.1.0

### Configuration

```yaml
theme:
  name: material
  language: de

...

extra:
  consent:
    title: Cookie-Zustimmung
    description: >- #
```

### System information

- Operating system: macOS
- Browser: Firefox, Chrome, Safari

**Comment by squidfunk** [comment]
Thanks for reporting. I'm not very familiar with Germany Cookie Consent wording – how should we translate those keys? If you would like to submit a PR, the file in question is here:
https://github.com/squidfunk/mkdocs-material-insiders/blob/master/src/partials/languages/de.html

**Comment by anjoniewo** [comment]
Thanks for the quick response and sure that's completely understandable ;-) 
I opened a PR: https://github.com/squidfunk/mkdocs-material-insiders/pull/30

**Comment by squidfunk** [comment]
Thanks! The PR was just merged. Let's keep this open until the next release.

**Comment by anjoniewo** [comment]
Sounds good!

**Comment by squidfunk** [comment]
The changes were just released as part of __8.1.0+insiders-4.4.0__. Thanks again!
