### ISSUE TITLE
Filter lunr.js stopwords from the 'Missing' section of each search result

### ISSUE THREAD

**Issue by bradumbaugh** [squidfunk/mkdocs-material#3343]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

As [suggested](https://github.com/squidfunk/mkdocs-material/discussions/3342#discussioncomment-1794069), filing an issue for discussion #3342.

![screenshot](https://user-images.githubusercontent.com/6285/145730259-7c413b07-756e-4b74-b61a-cfcce7be6283.png)

As shown by the above screenshot from the live MkDocs Material site, when a user enters a search term that lunr.js treats as a stopword, search results can indicate that the word is "missing" from the result even when it's actually there. This can be a little confusing, especially when the snippet shown by the search preview happens to include that stopword.

Can lunr.js stopwords be filtered from the 'missing' section?

Another, related idea: explicitly indicate that particular words have been excluded from the search (i.e., an 'Excluded: when, is, and') if/when a user searches on them. I don't know, though — even as I type that it out it seems a little heavy-handed (and it'd get repetitive to see that same info on each search result).

### Use Cases

This is obviously not a major problem. That said, fixing it might prevent users from getting confused when a search result says that a word is missing, when in fact that same word is visible right in the same search result.

The primary benefit here would be to prevent any loss in trust that might arise from the search UI indicating something that isn't true.

**Comment by squidfunk** [comment]
I had some time on my hands and fixed it right away. Starting with [`fdfe150f4`](https://github.com/squidfunk/mkdocs-material-insiders/commit/fdfe150f4c8cf660e790504b9618134acfde696e) stopwords are now removed from the list of missing terms. I also noticed this some time ago but forgot about it, so I'm glad we finally fixed it as it was really annoying.

**Comment by bradumbaugh** [comment]
Whoa, amazing! Thanks @squidfunk! That has to be some kind of a speed record. Love this project!

**Comment by squidfunk** [comment]
I also backported the fix in 539ddad27.

**Comment by squidfunk** [comment]
Released as part of 8.1.1.
