### ISSUE TITLE
Feature suggestion: Configurable "checked" flag for cookie consent

### ISSUE THREAD

**Issue by anjoniewo** [squidfunk/mkdocs-material#3349]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

First of all, I really like the [cookie consent feature](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=consent#cookie-consent) of the insiders project and of course the whole project itself!

As discussed with Waldemar, "Google Analytics" is pre-selected in the cookie settings and hidden when not clicking the "Manage settings" button. 
I'm not a GDPR expert, but regarding a [summary of the "Planet49"-judgement](https://www.oppenhoff.eu/de/news-detail/planet49-urteil-des-bgh-keine-wirksame-einwilligung-zu-cookies-durch-voreingestelltes-opt-in) pre-selected cookies which are not technically required are invalid.
It's stated in the last section under "Was bedeuten diese Entwicklungen für die Praxis?"

Thus, it would be nice to add the "checked" flag as a variable to the mkdocs-config file as part of the cookie consent section, including a minor change of the current config although it is not backward compatible:

```yaml
extra:
  consent:
    cookies:
      analytics:
        checked: true 
        name: Custom name
```

### Use Cases

Changing the config in the described way would also make sure to pre-select individual cookies when further cookies will be added.

**Comment by anjoniewo** [comment]
Hey @squidfunk,

I'm not really sure but before opening another issue I wanted to discuss a "Deny" button as part of the cookie consent bar. 
Do you think it is needed? 
[Art 7 DSGVO](https://dsgvo-gesetz.de/art-7-dsgvo/) states the following under (4):

> Der Widerruf der Einwilligung muss so einfach wie die Erteilung der Einwilligung sein.

**Comment by squidfunk** [comment]
Thanks for suggesting and indeed it’s a great addition. I don’t think a deny button is necessary, the section is mainly referring to the fact that a user should be able to do it within the same interface and/or without getting into contact with you. Almost all sites do not show a „deny button“. Thus, I’d not consider this for implementation right now, as it would make the implementation and probably configuration more complicated.

**Comment by anjoniewo** [comment]
Thanks for your quick response!

IMO, I think a "deny" button would actually make sense as it would just uncheck all cookies which doesn't have to be configured.
Internally we have some concerns that it is missing and "at least" [NOYB](https://noyb.eu/de/noyb-reicht-422-formelle-dsgvo-beschwerden-gegen-cookie-banner-wahnsinn-ein) has a pretty strong opinion on that too.
It's true that only a few websites have a deny-button but as this is somehow a grey-zone it probably doesn't mean that they do it a 100% correctly.

**Comment by squidfunk** [comment]
Support for custom initial states was added in [`b530fb9`](b530fb9a845d25caa7a5213cd80417a9fe1b0b48). I'm currently not considering adding a "deny" button, as the initial state can now be set to include no cookie, which is in compliance with the law. You can allow the user to change his setting by simply including a link which includes the `#__consent` hash fragment, e.g.:

``` markdown
[Change cookie settings](#__consent){ .md-button }
```

This is also documented [here](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=change#cookie-consent) (below the screenshot). I may reconsider adding a deny option in the future, but for now you can just extend the theme and add a button [here](https://github.com/squidfunk/mkdocs-material-insiders/blob/b530fb9a845d25caa7a5213cd80417a9fe1b0b48/src/partials/consent.html#L61-L68) if you wish to include one. Basically, it should work like this (untested):

``` html
<div class="md-consent__controls">
  <label class="md-button" for="__settings">
    {{- lang.t("consent.manage") -}}
  </label>
  <button class="md-button md-button--primary">
    {{- lang.t("consent.accept") -}}
  </button>
  <button class="md-button md-button--primary" onclick="javascript:document.forms.consent.querySelectorAll("input[type=checkbox][name]").forEach(input => input.checked = false)>
    Deny
  </button>
</div>
```

**Comment by squidfunk** [comment]
Accidentally closed. Re-opening until this is released 😉

**Comment by squidfunk** [comment]
Documentation was added in b83983354.

**Comment by squidfunk** [comment]
Released as part of 8.1.4-insiders-4.5.1.

**Comment by anjoniewo** [comment]
Sorry for my late response and thanks for clarifying! The suggestion above is great for now 👍

**Comment by squidfunk** [comment]
#3970 adds the ability to add a deny button to the cookie consent dialogue and allows for re-arranging the buttons.
