### ISSUE TITLE
Add examples for installing / upgrading Insiders locally

### ISSUE THREAD

**Issue by ajh0912** [squidfunk/mkdocs-material#3363]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

On the [Getting started](https://squidfunk.github.io/mkdocs-material/getting-started/) and [How to upgrade](https://squidfunk.github.io/mkdocs-material/upgrade/) pages good examples are given for installing and upgrading Material for MkDocs locally, but no examples are given for Insiders.

It might be worth adding the Insiders equivalent like the [Publishing your site](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions) page does with:

    pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

The Insiders upgrade process hasn't needed to be mentioned on the Publishing your site page at all as of course the pages environments are ephemeral, so there's no mention of this command at all as far as I can tell:

    pip install --upgrade git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

### Use Cases

When doing local dev work before syncing commits to GitHub / GitLab it's useful to run the latest Insiders if the published site would be also.

Not everyone will be familiar with pip etc and may remain on older versions of Insiders on their local dev environment.

**Comment by squidfunk** [comment]
Great idea, thanks for suggesting!

**Comment by squidfunk** [comment]
We should also add instructions to install a specific version for the public version. Related:

#3374

**Comment by squidfunk** [comment]
db5eee54a adds installation instructions for version ranges and upgrade instructions for Insiders. I'll revisit the Insiders installation guide in the future, but for the time being, this issue is considered resolved 😊
