### ISSUE TITLE
GitLab default branch is main, not master

### ISSUE THREAD

**Issue by FranckCHAMBON** [squidfunk/mkdocs-material#3384]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The description https://squidfunk.github.io/mkdocs-material/publishing-your-site/#gitlab-pages
should be updated just like the github one.

main is the default branch for new project

### Expected behaviour

Please consider to provide both cases

### Actual behaviour

Only master branch is described

### Steps to reproduce

ø

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`
- ø

### Configuration

```yaml
ø
```

### System information

- Operating system: ...
- Browser: ...
- ø

**Comment by squidfunk** [comment]
Thanks for reporting. I’m not a GitLab user so I rely on contributors for this part of the docs. Could I ask you to submit a PR?

**Comment by FranckCHAMBON** [comment]
I hope I did it well ; it's my very first PR :smile:

**Comment by squidfunk** [comment]
Congrats to your first PR! You did everything right in #3393, thanks again! 😊 I just removed the redundant annotation in the "Insiders" tab, as it's non-essential information (the configuration will now work on `master`/`main` and removing one of those lines is optional). It's the same for GitHub Pages.
