### ISSUE TITLE
Defining `edit_uri` modifies the `repo_url`

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#3394]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Defining `edit_uri` adds a forward slash to the `repo_url` link for the button on the top right

### Expected behaviour

The `repo_url` link for the button on the top right is what is defined in config

### Actual behaviour

Defining `edit_uri` adds a forward slash to the `repo_url` link for the button on the top right

### Steps to reproduce

```yaml
repo_url: https://github.com/user/repo
edit_uri: blob/master/docs
```

### Package versions

- Python: `3.8.1`
- MkDocs: `1.2.3`
- Material: `8.1.3`

### Configuration

```yaml
repo_url: https://github.com/user/repo
edit_uri: blob/master/docs
```

### System information

- Operating system: Windows 10
- Browser: Chrome

**Comment by squidfunk** [comment]
Thanks for reporting. This also happens with the `readthedocs` theme. Please report it upstream.

**Comment by ofek** [comment]
https://github.com/mkdocs/mkdocs/pull/2733
