### ISSUE TITLE
IE11 on Windows 7 doesn't honor max-width on main tag

### ISSUE THREAD

**Issue by WickeDev** [squidfunk/mkdocs-material#34]
![capture](https://cloud.githubusercontent.com/assets/5603687/15925526/7cbfb5f8-2e72-11e6-9220-58d13fd74207.JPG)

Thank you for your work

**Comment by squidfunk** [comment]
Oh that's correct. I'm very short on time, so if you can provide a fix, I'm happy to merge it. Otherwise this problem should vanish with the rewrite I'm currently doing, but where progress is sadly really slow at the moment.

**Comment by squidfunk** [comment]
This is an interesting bug. It stems from the fact that IE11 on Windows 7 doesn't have `display: block` defined on `main` in the user agent styles [1]. Setting it explicitly fixes the problem. I will provide a fix in a second.

[1]: http://stackoverflow.com/a/28806718/1065584
