### ISSUE TITLE
Code annotations don't work without a language shortcode

### ISSUE THREAD

**Issue by ben519** [squidfunk/mkdocs-material#3431]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Following [the docs](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations), I can get code annotations to work *when I use the python shortcode*. 

For example, this works

```python
print("hello world")  # (1)!
```

1. Material is awesome

but sometimes I like to embed pseudocode in a block without a language shortcode, like this

```
pseudocode here  # (1)!
```

1. But this seems broken

In these cases the annotation doesn't render.

<img width="773" alt="Screen Shot 2022-01-05 at 5 17 30 PM" src="https://user-images.githubusercontent.com/723099/148303386-be7b9217-4c70-4862-8aef-de1ae4ef64ae.png">

### Expected behaviour

I would expect annotations to work the same in *all* code blocks (even those without a language shortcode).

### Actual behaviour

Annotation doesn't render. Raw text is displayed instead.

### Steps to reproduce

See example above.

### Package versions

- Python: `python --version`: 3.10.1
- MkDocs: `mkdocs --version`: 1.2.3
- Material: `pip show mkdocs-material | grep -E ^Version`: 8.1.4+insiders.4.5.1

### Configuration

```yaml
site_name: My Docs

theme:
  name: material
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.superfences
```

### System information

- Operating system: mac os 12.1
- Browser: chrome 96.0.4664.110

**Comment by squidfunk** [comment]
Thanks for reporting. This is a know limitation and deliberate decision. Code annotations must be hosted in block or inline comments (the [documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) says that). The reason for this is that checking for code annotations in the whole code block will very likely break some languages – it would be too aggressive. For example, in some languages `(1)` might be valid syntax (e.g. JavaScript) – how should we know whether the marker belongs to the actual code or should be rendered as an annotation? For this reason, annotations must live in comments. Furthermore, annotations [only work with Pygments](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#fn:1):

> Code annotations require syntax highlighting with Pygments – they're currently not compatible with JavaScript syntax highlighters, or languages that do not have comments in their grammar. However, we're actively working on supporting alternate ways of defining code annotations, allowing to always place code annotations at the end of lines.

So yes, there will probably be support for non-comment languages in the future (still under investigation), but I can't currently estimate when that will happen.
