### ISSUE TITLE
Disqus integration is broken in latest releases

### ISSUE THREAD

**Issue by Kanaduchi** [squidfunk/mkdocs-material#3433]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Disqus integration is broken after upgrading to 8.1.* versions after 7.*
 
I have Metadata plugin is enabled. Also pages have disqus name at the top of each page:
```
---
disqus: <shortname>
---
```

### Expected behaviour

Disqus block is loaded at pages

### Actual behaviour

Disqus block is not shown at all. 

### Steps to reproduce

1. Add meta plugin to mkdocs.yaml
2. Add disqus section to any page
3. Load page in browser

### Package versions

- Python: 3.10.1
- MkDocs: 1.2.3
- Material: 8.1.4

### Configuration

```yaml
markdown_extensions:
  - meta
```

### System information

- Operating system: any
- Browser: any

**Comment by squidfunk** [comment]
The Disqus integration was [removed in v8](https://squidfunk.github.io/mkdocs-material/upgrade/#whats-new) in favor of theme customization. The [new Disqus guide](https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/#disqus-integration) explains how to achieve the same result with overriding blocks. Note that in the future we might throw that out too in favor of a leaner solution (maybe giscus).

Related:

- #3329
