### ISSUE TITLE
Support for a cache busting feature

### ISSUE THREAD

**Issue by Vasperous** [squidfunk/mkdocs-material#3463]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

While adding Google Analytics to several sites with the user feedback option I noticed that all of the pages were not displaying the user feedback option.  After doing a refresh of the page without the cache the options to leave feedback appear but disappear again when loading the page from cache.

After doing some research the obvious answer is to clear my cache which is fine with me but the users consuming the documentation may not always be as savvy.  I found some examples of trying to override the theme to put data into the pages header but that hasn't worked out as well as I hoped.

It would be great, in my opinion anyways, to have a feature where a hash or equivalent could be put into the page header to force page refreshing (if required).

### Use Cases

It would ensure users consuming the documentation are accessing the latest version.  Personally, I have made updates and directed users to the pages and they come back with screenshots claiming that the information isn't there.  Once they clear their cache they can then see the content.

**Comment by squidfunk** [comment]
Thanks for suggesting. However, this is beyond the scope of this project. In essence, putting hashes or arbitrary query parameters to URLs to circumvent browser caching is considered an anti-pattern nowadays. Material for MkDocs itself uses content hashes for its assets, which is the current best practice. For all other static content (e.g. HTML files) you should set appropriate cache headers.

As a starter, I recommend reading about the [Cache-Control](https://developer.mozilla.org/de/docs/Web/HTTP/Headers/Cache-Control) header. As an example, GitHub Pages sets a value of `max-age=600`, which I would regard as sufficient. After 10m, you be sure that your clients receive the new version.
