### ISSUE TITLE
Overriding of page title doesn't work properly

### ISSUE THREAD

**Issue by Kanaduchi** [squidfunk/mkdocs-material#3474]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Overriding of page title doesn't work properly

### Expected behaviour

Title should be overridden when page is loaded. Changed title appears only when I scroll page down

### Actual behaviour

Page loads with title from mkdocs

Looks like this hack doesn't show updated title:
```
<!--
  Hack: check whether the content contains a h1 headline. If it
  doesn't, the page title (or respectively site name) is used
  as the main headline.
-->
```

I need to change styles directly to make this working:
```
<style>
  .md-typeset h1 {
    display: none;
</style>
```

### Steps to reproduce

1. Override title with:
```
---
title: Lorem ipsum dolor sit amet 
---
```

### Package versions

- MkDocs: 8.1.7

### Configuration

```yaml
markdown_extensions:
  - meta
```

### System information

Any

**Comment by squidfunk** [comment]
Thanks for reporting. What you're describing is the behavior of the header, which will show the site title until the user scrolls past the headline, and then displays the title. This is a deliberate design decision. As described in the documentation, setting the `title` attribute will change the `title` metadata tag, the page title in the navigation, as well as the title for the social card, if enabled. This is how Material for MkDocs has been doing it for years. Closing, as no change is required.
