### ISSUE TITLE
Add mike to the container

### ISSUE THREAD

**Issue by timmjd** [squidfunk/mkdocs-material#3475]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I guess the [versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/) was an insider feature at the beginning and became now publicly available. Sadly the `mike` library that is required to use this feature is not part of the officially released container.

### Use Cases

I'd like to make use of the versioning feature without the requirement to patch / modify `mike` into the container.

### Screenshots / Mockups

I guess adding `mike` to the [requirements.txt](https://github.com/squidfunk/mkdocs-material/blob/master/requirements.txt) would simply solve the issue and have it preinstalled inside the official docker container

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm not interested in adding more and more stuff to the official Docker container which can be perfectly used as a base image. Please also see the following issues with similar requests:

- #3457
- #2767
- #2349

**Comment by squidfunk** [comment]
If you search GitHub, you will find several Docker images that extend off the base image, so I don't think this is necessary. A full-blown image will be too big to use in CI, because for most users it will contain stuff they don't use. My aim is to provide a minimal Docker image that can be easily extended and tailored to specific needs.
