### ISSUE TITLE
CodeHilite - use the linenums option only for certain block and not globally

### ISSUE THREAD

**Issue by michaudg** [squidfunk/mkdocs-material#348]
I have some code blocks that need to have line numbers and some others no. It would be great to use the linenums options only when needed and not globally.

I see that we can add the "hl_lines" after the language identifier. Is it possible to add the "linenums" option too?

Thank you.

**Comment by facelessuser** [comment]
Are you talking fenced blocks or indented blocks?  CodeHilite controls the highlighting of both fences and indented blocks.

For indented code blocks (I personally prefer fenced code blocks to do this):

- `#!python` will give you line numbers [ref](https://pythonhosted.org/Markdown/extensions/code_hilite.html#shebang-no-path).
- `:::python` will give you no line nubmers [ref](https://pythonhosted.org/Markdown/extensions/code_hilite.html#colons).

For SuperFences:

- ` ```python linenums="1" ` Will give line numbers starting at 1 [ref](http://facelessuser.github.io/pymdown-extensions/extensions/superfences/#showing-line-numbers).

This option doesn't exist for default `fenced_code_block`.  It is recommended to use SuperFences.

**Comment by michaudg** [comment]
Thank you very much @facelessuser and thanks for refering to the pymdown documentation. I didn't realized that there was a difference between the indented and the fenced code block syntax.

**Comment by facelessuser** [comment]
I never use indented code block syntax for highlighting. I was frustrated that in order to do line numbers I had to do indented blocks.  So when I wrote SuperFences, I exposed line numbers  as well as highlight lines.

**Comment by DevotionGeo** [comment]
@facelessuser what if I want to use the ` ```python` syntax and turn on the line numbers globally and then turn it of only for one code block, is that possible?

**Comment by facelessuser** [comment]
I don't believe the reverse is possible at this time.  I'm not entirely sure how I feel about implementing the reverse.  The best you can do is on demand lines at this time.
