### ISSUE TITLE
New language: Latvian

### ISSUE THREAD

**Issue by andzejsp** [squidfunk/mkdocs-material#3490]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### Language availability

- [X] I've checked the [list of available languages](https://bit.ly/33vFDD0)

### Translation

```jinja
{% macro t(key) %}{{ {
  "language": "lv",
  "direction": "ltr",
  "clipboard.copy": "Kopēt starpliktuvē",
  "clipboard.copied": "Kopēts starpliktuvē",
  "edit.link.title": "Rediģēt šo lapu",
  "footer.previous": "Iepriekšējais",
  "footer.next": "Nākamais",
  "footer.title": "Kājene",
  "header.title": "Galvene",
  "meta.comments": "Kmentārs",
  "meta.source": "Avots",
  "nav.title": "Navigācija",
  "search.config.lang": "lv",
  "search.config.pipeline": "trimmer, stopWordFilter",
  "search.config.separator": "[\s\-]+",
  "search.placeholder": "Meklēt",
  "search.reset": "Notīrīt",
  "search.result.initializer": "Notiek meklēšanas inicializācija",
  "search.result.placeholder": "Ierakstiet, lai sāktu meklēšanu",
  "search.result.none": "Nav atbilstošu dokumentu",
  "search.result.one": "1 atbilstošs dokuments",
  "search.result.other": "# atbilstoši dokumenti ",
  "search.result.more.one": "1 šajā lapā",
  "search.result.more.other": "# un vairāk šajā lapā",
  "search.result.term.missing": "Trūkstošs",
  "select.language.title": "Izvēlies valodu",
  "select.version.title": "Izvēlies versiju",
  "skip.link.title": "Pāriet uz saturut",
  "source.link.title": "Dodieties uz repozitoriju",
  "source.file.date.updated": "Pēdējoreiz atjaunots",
  "source.file.date.created": "Izveidots",
  "tabs.title": "Cilnes",
  "toc.title": "Satura rādītājss",
  "top.title": "Atpakaļ uz augšu"
}[key] }}{% endmacro %}
```

**Comment by andzejsp** [comment]
fixed double paste

**Comment by squidfunk** [comment]
Thanks! Added in 6816aa8cd.

**Comment by squidfunk** [comment]
Released as part of 8.1.8

**Comment by andzejsp** [comment]
Thank you, never thought it would be that quick :)

**Comment by andzejsp** [comment]
@squidfunk Hello, I found few misspellings in my translations, sorry, here is an updated version:

Changes in:

 "meta.comments"
 "skip.link.title"
 "toc.title"

{% macro t(key) %}{{ {
  "language": "lv",
  "direction": "ltr",
  "clipboard.copy": "Kopēt starpliktuvē",
  "clipboard.copied": "Kopēts starpliktuvē",
  "edit.link.title": "Rediģēt šo lapu",
  "footer.previous": "Iepriekšējais",
  "footer.next": "Nākamais",
  "footer.title": "Kājene",
  "header.title": "Galvene",
  "meta.comments": "Komentārs",
  "meta.source": "Avots",
  "nav.title": "Navigācija",
  "search.config.lang": "lv",
  "search.config.pipeline": "trimmer, stopWordFilter",
  "search.config.separator": "[\s\-]+",
  "search.placeholder": "Meklēt",
  "search.reset": "Notīrīt",
  "search.result.initializer": "Notiek meklēšanas inicializācija",
  "search.result.placeholder": "Ierakstiet, lai sāktu meklēšanu",
  "search.result.none": "Nav atbilstošu dokumentu",
  "search.result.one": "1 atbilstošs dokuments",
  "search.result.other": "# atbilstoši dokumenti ",
  "search.result.more.one": "1 šajā lapā",
  "search.result.more.other": "# un vairāk šajā lapā",
  "search.result.term.missing": "Trūkstošs",
  "select.language.title": "Izvēlies valodu",
  "select.version.title": "Izvēlies versiju",
  "skip.link.title": "Pāriet uz saturu",
  "source.link.title": "Dodieties uz repozitoriju",
  "source.file.date.updated": "Pēdējoreiz atjaunots",
  "source.file.date.created": "Izveidots",
  "tabs.title": "Cilnes",
  "toc.title": "Satura rādītājs",
  "top.title": "Atpakaļ uz augšu"
}[key] }}{% endmacro %}

**Comment by squidfunk** [comment]
Could you please send a PR?

**Comment by andzejsp** [comment]
@squidfunk Never done a pull request, but I could try. Does it mean i need to fork this master then fix the file then pull request?

**Comment by squidfunk** [comment]
Yes, but never mind. I've changed the keys you mentioned in 219dd3d04. Please check them again, so we can be sure there are no more errors before the next release.
