### ISSUE TITLE
Add styling for blockquotes

### ISSUE THREAD

**Issue by digitalcraftsman** [squidfunk/mkdocs-material#35]
Hello Martin,

one of users of the Hugo-port noticed that the current CSS code doesn't define any styling rules for blockquotes. Those aren't distinguishable from normal paragraphs.

Cheers,
Digitalcraftsman

**Comment by squidfunk** [comment]
![blockquotes](https://cloud.githubusercontent.com/assets/932156/16362191/cdb79c86-3ba7-11e6-9440-ed0a2dfe19d6.png)

It's not perfect, but I think it will do the trick for now until I manage to refactor the whole template. Feel free to let me know what you think.

**Comment by digitalcraftsman** [comment]
LGTM. Know it's much easier to distinguish between normal text and quotes.
