### ISSUE TITLE
`mkdocs.yml` validator warns about `strict` and `remote_branch`

### ISSUE THREAD

**Issue by HonkingGoose** [squidfunk/mkdocs-material#3508]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The new `mkdocs.yml` validator warns about the `strict` and `remote-branch` properties not being allowed according to `yaml-schema: Material for MkDocs`.

### Expected behaviour

Properties `strict:true` and `remote_branch: gh-pages` pass validation.

### Actual behaviour

I get the following warnings in the VSCode editor:

```
Property strict is not allowed.yaml-schema: Material for MkDocs
```

```
Property remote_branch is not allowed.yaml-schema: Material for MkDocs
```

### Steps to reproduce

1. Install the `vscode-yaml` VSCode extension.
2. Create the `.vscode` folder, and put these files in it:
    - `extensions.json`
    - `settings.json`
  
`extensions.json`:

```json
{
  "recommendations": ["redhat.vscode-yaml"],
  "unwantedRecommendations": []
}
```

`settings.json`

```json
{
  "yaml.schemas": {
    "https://squidfunk.github.io/mkdocs-material/schema.json": "mkdocs.yml"
  }
}
```

3. Now create this `mkdocs.yml` file:

```yaml
strict: true
remote_branch: gh-pages
```

4. Open the `mkdocs.yml` file in VSCode, you'll see red underlines beneath the properties, and VSCode will show a warning when you hover over the properties.

### Package versions

- Python: `Python 3.8.12`
- MkDocs: `mkdocs, version 1.2.3`
- Material: `Version: 8.1.9`

### Configuration

```yaml
strict: true
remote_branch: gh-pages
```

### System information

- Operating system: Gitpod container
- Browser: not applicable

**Comment by squidfunk** [comment]
Thanks for reporting! I'm pretty sure I missed some settings. Would you like to contribute them?

**Comment by HonkingGoose** [comment]
The `strict` and `remote_branch` properties are from the MkDocs program.

Do you intend for your config validator to validate _everything_, or just your own features?

It might be worth it to split things up into 2 config validation schemas? So one from you for `mkdocs-materal` and one at the `mkdocs` repository for their stuff?

**Comment by squidfunk** [comment]
Every valid Material for MkDocs configuration should be validated. We _could_ split it into two schemas, but the main idea is to provide the valid subset of MkDocs configuration that Material for MkDocs accepts, including but not limited to `markdown_extensions`, `extra`, and `theme`. Most of the stuff cannot be upstreamed.

Furthermore, due to the nature of JSON schema, I don't think it is possible to reliably extend a top-level object with further properties. At least I found no way to do it. If somebody manages to and wants to take on the burden of maintaining it, I'm happy to consider a PR.

**Comment by squidfunk** [comment]
I went ahead and added `strict`, `remote_branch` and `remote_name` in 9eebd2442. This commit also contains many improvements, including icon completion support and better snippets.

**Comment by HonkingGoose** [comment]
Thank you very much!
