### ISSUE TITLE
Annotations incorrect rendering

### ISSUE THREAD

**Issue by Four-Velocity** [squidfunk/mkdocs-material#3532]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes 
- > Well as I understand it's just `material` theme feature, so it wouldn't work in `mkdocs` or `readthedocs` anyway
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hey there 👋 

When I'm trying to create annotation it just rendering md list for me and leaving `(1)` in text. Neither plain annotations nor annotations "in annotations" nor annotations "in everything else" work. All of them are rendered incorrectly.

In addition code blocks annotations are rendered, but the sharp sign and the exclamation mark still persist in the code block.

I'll attach screenshots and HTML from built documentation for `mkdocs-material` for more clarity, but I face same behavior when I'm trying to build my docs. 

### Expected behaviour

Annotations rendered as excepted.

#### Basic annotations

![image](https://user-images.githubusercontent.com/35434465/152444826-904db211-53d8-4a97-b93a-5e7e9ef0ee32.png)

``` html
<div class="result">
  <p class="annotate">Lorem ipsum dolor sit amet,
    <aside class="md-annotation" tabindex="0" style="--md-tooltip-x:562px; --md-tooltip-y:1633.5px;">
      <a class="md-annotation__index" tabindex="-1">
        <span data-md-annotation-id="1">
        </span>
      </a>
    </aside>
    consectetur adipiscing elit.
  </p>
  <ol hidden="">
    <li></li>
  </ol>
</div>
```

#### Code blocks annotations

![image](https://user-images.githubusercontent.com/35434465/152445474-c9e823fe-8c9d-4092-ab53-b2e1ac5a02f2.png)

``` html
<code>
<!-- code block goes brr... -->
<span class="c1">
  <aside class="md-annotation" tabindex="0" style="--md-tooltip-x:257px; --md-tooltip-y:58px; --md-tooltip-0:-330px;">
    <div class="md-tooltip md-tooltip--active" id="__code_2_annotation_1">
      <div class="md-tooltip__inner md-typeset"><img alt="🙋‍♂️" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f64b-200d-2642-fe0f.svg" title=":man_raising_hand:">
        I'm a code annotation! I can contain <code>code</code>, <strong>formatted text</strong>, images, ... basically anything 
        that can be written in Markdown.
      </div>
    </div>
    <a href="#__code_2_annotation_1" class="md-annotation__index" tabindex="-1">
      <span data-md-annotation-id="1"></span>
  </a>
  </aside>
</span>
</code>
```

### Actual behaviour

Annotations are not rendered at all or rendered incorrectly in code blocks.

#### Basic annotations

![image](https://user-images.githubusercontent.com/35434465/152445918-c3238778-367f-4549-84f0-d2cf266f276e.png)

``` html
<div class="result">
  <p class="annotate">Lorem ipsum dolor sit amet, (1) consectetur adipiscing elit.</p>
  <ol>
    <li>
      <p class="annotate" style="margin-bottom: 0"><img alt="🙋‍♂️" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f64b-200d-2642-fe0f.svg" title=":man_raising_hand:"> I'm an annotation! (1)
      </p>
      <ol>
        <li>
          <img alt="🙋‍♀️" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f64b-200d-2640-fe0f.svg" title=":woman_raising_hand:"> I'm an annotation as well!
        </li>
      </ol>
    </li>
  </ol>
</div>
```

#### Code block annotations

![image](https://user-images.githubusercontent.com/35434465/152446238-9c02a6ea-3975-475b-a5e0-c39b5aa6dafe.png)

``` html
<code>
<!-- Corrupted code block goes brr.. :)) -->
<span class="c1"># <!-- Here is the sharp symbol -->
  <aside class="md-annotation" tabindex="0" style="--md-tooltip-x:273px; --md-tooltip-y:49px; --md-tooltip-0:-330px;">
    <div class="md-annotation__inner md-tooltip">
      <div class="md-tooltip__inner md-typeset">
        <img alt="🙋‍♂️" class="twemoji" src="https://twemoji.maxcdn.com/v/latest/svg/1f64b-200d-2642-fe0f.svg" title=":man_raising_hand:"> I'm a code annotation! I can contain <code>code</code>, <strong>formatted text</strong>, images, ... basically anything that can be written in Markdown.
        </div>
      </div>
      <span class="md-annotation__index">
        <span data-md-annotation-id="1"></span>
      </span>
  </aside>! <!-- Here is the exclamation mark -->
</span>
</code>
```

### Steps to reproduce

1. Add some annotations to _index.md_ file
  1.1. Add basic or nested annotation as described in [documentation](https://squidfunk.github.io/mkdocs-material/reference/annotations/#using-annotations) 
  1.2. Add code block annotation as described in [documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations)

2. Run `mkdocs build` or `mkdocs serve`

### Package versions

- Python: `3.8.12`
- MkDocs: `1.2.3`
- Material: `8.1.9`

### Configuration

```yaml
site_name: Some Docs
theme:
  name: material
  features:
    - content.code.annotate
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
```

### System information

- Operating system: _Ubuntu_ `20.04.3 LTS` install on _Windows 10 Enterprise_ `20H2` in `WSL 2`
- Browsers:
   - Chrome ` 97.0.4692.99`
   - Firefox `96.0.3`

**Comment by squidfunk** [comment]
Thanks for reporting. As you have realized, [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) work as expected, but [text annotations](https://squidfunk.github.io/mkdocs-material/reference/annotations/) (outside of code blocks) are currently an [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) feature. This is what the little "❤️ Insiders" note next to the [annotations configuration](https://squidfunk.github.io/mkdocs-material/reference/annotations/#using-annotations) is all about. If you [join the Insiders program](https://squidfunk.github.io/mkdocs-material/insiders/#how-to-become-a-sponsor), you will have access to annotations right away. If not, you might have to wait until this feature is released into the community edition 😊

**Comment by Four-Velocity** [comment]
Oh my..... I'm too absent-minded 😅 
But the code block annotations behaving strange anyway. They should be displayed without `#` at the beginning and `!` and the end of annotation, innit?

**Comment by squidfunk** [comment]
@Four-Velocity stripping comments is an Insiders feature as well and was added after code annotations were release:
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#stripping-comments

**Comment by Four-Velocity** [comment]
Got it, thanks for the reply, and sorry for disturbing you with that 😄 
Have a great day 👋
