### ISSUE TITLE
`custom_dir` not used when using config file inheritance

### ISSUE THREAD

**Issue by jgeluk** [squidfunk/mkdocs-material#3536]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

When using config file inheritance [as described here](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#built-in-plugins) the icon I placed in the `docs-override/.icons` directory does not get found giving an error like:

```
[Errno 2] No such file or directory: '/Users/xxx/.asdf/installs/python/3.10.2/lib/python3.10/site-packages/material/.icons/xxx-logo-symbol.svg'
```

### Expected behaviour

Should work

### Actual behaviour

See above

### Steps to reproduce

1. `mkdocs serve`

### Package versions

- Python: `python --version`: `Python 3.10.2`
- MkDocs: `mkdocs --version` `version 1.2.3`
- Material: `pip show mkdocs-material | grep -E ^Version` `Version: 8.1.9+insiders.4.7.2`

### Configuration

```yaml
INHERIT: mkdocs.yml
theme:
  custom_dir: docs-overrides/
```

### System information

- Operating system: Mac OS
- Browser: N/A

**Comment by jgeluk** [comment]
```
DEBUG    -  Config value: 'site_author' = '****'
DEBUG    -  Config value: 'theme' = Theme(name='material', dirs=['docs-overrides/', '/Users/***/.asdf/installs/python/3.10.2/lib/python3.10/site-packages/material',
            '/Users/jacobus/.asdf/installs/python/3.10.2/lib/python3.10/site-packages/mkdocs/templates'], static_templates=['sitemap.xml', '404.html'], locale=Locale(language='en', territory=''),
            language='en', direction=None, features=['search.highlight', 'navigation.top', 'navigation.instant', 'navigation.tracking', 'navigation.tabs', 'navigation.tabs.sticky',
            'navigation.sections', 'navigation.expand', 'navigation.indexes'], palette=[{'media': '(prefers-color-scheme: light)', 'scheme': 'default', 'primary': 'indigo', 'accent': 'light-blue',
            'toggle': {'icon': 'material/toggle-switch-off-outline', 'name': 'Switch to dark mode'}}, {'media': '(prefers-color-scheme: dark)', 'scheme': 'slate', 'primary': 'indigo', 'accent':
            'deep orange', 'toggle': {'icon': 'material/toggle-switch', 'name': 'Switch to light mode'}}], font={'text': 'Roboto', 'code': 'Roboto Mono'}, icon={'logo': '***-logo-symbol', 'repo':
            'fontawesome/brands/github'}, favicon='assets/images/favicon.png', include_search_page=False, search_index_only=True)
```

**Comment by squidfunk** [comment]
Thanks for reporting. First of all, [you must specify the theme `name`](https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure)

``` yaml
theme:
  name: material
  custom_dir: overrides
```

Then, if you want to use additional icons, you need additional configuration. Please follow the guide in the documentation:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons

**Comment by jgeluk** [comment]
The point is why does it work if I use `mkdocs serve --config-file mkdocs.yml` and not when I use `mkdocs serve --config-file mkdocs.insiders.yml`? The configuration in `mkdocs.yml` must be fine then right? I'm trying to move all insiders-specific features to the `mkdocs.insiders.yml` so that people who don't have the personal access token to that can still build the site locally. The ONLY change I did was to create that (rather empty) `mkdocs.insiders.yml` (as shown above) and then I get the breaking error as shown under "Description" above..

**Comment by jgeluk** [comment]
Noticed another issue that only occurs when you use config file inheritance which is that the social plugin cannot be found:

```
Config value: 'plugins'. Error: The "social" plugin is not installed
```

**Comment by squidfunk** [comment]
@jgeluk you need to split the `plugins` configuration, which is documented here:
https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#caveats

Regarding config file inheritance – as this is a feature that is provided by MkDocs so it's a better idea to ask the maintainers by filing an issue upstream. Maybe it's not supported, maybe you're missing something:
https://github.com/mkdocs/mkdocs 

There's nothing to be done on our side, as everything you're asking for is either documented or not specifically a problem with Material for MkDocs, which is why I'm closing the issue.
