### ISSUE TITLE
Feature suggestion: add an option to use page titles in `navigation.indexes`.

### ISSUE THREAD

**Issue by kenji-miyake** [squidfunk/mkdocs-material#3544]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

When we use `navigation.indexes`, it is useful if we can toggle which to use the directory name or the page title.

This is my prototype implementation.
https://github.com/kenji-miyake/mkdocs-material/commit/0142f35a90fe5ee09f5e3cf0166876184d32b308

### Use Cases

It might not be so useful if we build `nav:` tree manually in `mkdocs.yml`.

However, if we use the [awesome-pages](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin) plugin because it can automatically build `nav` by specifying directories like [this](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#customize-navigation).

Consider this case:

```yaml
// .pages
nav:
    - api-usage
```

```bash
// api-usage/index.md
# API Usage
```

It has an upper-case abbreviation and uses the title case.
In this case, the title will be `Api usage`, not `API Usage`.

To avoid this, now we have to set the title manually, but it's nice if we can set it automatically. I believe this option can resolve this problem.

```yaml
// .pages
nav:
    - API Usage: api-usage
```

### Screenshots / Mockups

**Current:**

![image](https://user-images.githubusercontent.com/31987104/152688896-4613681b-73cf-40b9-8418-2d6464a50885.png)

**With [this change](https://github.com/kenji-miyake/mkdocs-material/commit/caf72ee3817ff25dfab3330db5ccd14e41fd4937):**

![image](https://user-images.githubusercontent.com/31987104/152688872-adf4a528-6d18-49f7-a9a2-f190d7f789e7.png)

**Comment by squidfunk** [comment]
Thanks for suggesting. First of all, when implementing this only for section indexes pages, the new behavior would deviate from the behavior for all other navigation items which will use the title set in `mkdocs.yml`. Also, I understand your use case, but I would definitely consider it an edge case. As you described, it's also solvable by setting the title manually.

**Comment by kenji-miyake** [comment]
@squidfunk Thank you for your prompt feedback.
Okay, I understand. I'll set it manually and consider another way, for example extending `awesome-pages` side.
