### ISSUE TITLE
Version dropdown expands behind theme toggle & search bar

### ISSUE THREAD

**Issue by dimrozakis** [squidfunk/mkdocs-material#3545]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Depending on window width, site title length, and length of versions in the version selection dropdown, the dropdown can stretch on the area that contains the light/dark toggle and search bar. When that happens, are not hidden behind the uncollapsed version dropdown.

![mkdocs-material-long-version](https://user-images.githubusercontent.com/5428237/152691828-8fd17bfe-4b59-4bb5-9362-6ab9f6f537d1.png)

### Expected behaviour

1. Either, the dropdown should expand *above*, not behind other topbar elements,
2. or the dropdown should expand to the bottom of the topbar, similar to the language selector dropdown (as seen in the following screenshot)
![Screenshot from 2022-02-06 19-05-32](https://user-images.githubusercontent.com/5428237/152692185-35a43e7c-21ee-4db3-9184-cbe50f4980df.png)

### Actual behaviour

The dropdown expands behind the theme toggle & search bar (could also affect other elements like the language selector, haven't checked)

### Steps to reproduce

1. Configure a long enough site title.
2. Configure several versions, few of them quite long.
3. Set a medium window size.
4. Expand the version dropdown.

Note: It's easier to reproduce the issue if the currently selected version is one of the short ones. This will cause the title to be truncated less, and the version dropdown to be positioned close to the theme toggle & search bar. Expanding the dropdown then will cause it to expand behind the theme toggle & search bar.

### Package versions

Python: python --version: 3.9.6 
MkDocs: mkdocs --version: 1.2.3
Material: 8.1.10-insiders-4.8.0 (but happens with older versions as well)

### Configuration

```yaml
-
```

### System information

- Operating system: Linux Mint 19.1
- Browser: I can reproduce with Chromium 97.0.4692.71 & Firefox 96.0.3

**Comment by squidfunk** [comment]
Thanks for reporting. That shouldn't happen. Can you share the site where this is happening? It would make my work much, much easier, as it's probably only a `z-index` problem.

**Comment by dimrozakis** [comment]
Hi @squidfunk 

Unfortunately I cannot share the site where I'm experiencing this since it's requires authentication. But I was able to reproduce it in the arduino docs site by doing the following:

1. Go to https://arduino.github.io/arduino-cli/0.21/
2. Use dev tools to change the text of the site title in the topbar to `Arduino CLI Arduino CLI Arduino CLI Arduino CLI Arduino CLI`.
3. Use dev tools to change the value of the last version in the version selector from `dev` to `dev dev dev dev dev`.

Now (while in the 0.21) version, hover over the version selector and you'll see this:

![arduino-docs](https://user-images.githubusercontent.com/5428237/152791781-70355f82-6d2b-41ab-a6bf-18ed9d935f02.png)

I hope this helps.

**Comment by squidfunk** [comment]
Thanks! Mitigation:

``` css
.md-version__list {
  z-index: 3;
}
```

**Comment by squidfunk** [comment]
Fixed in 93a55412a.
