### ISSUE TITLE
Copy button tool-tip doesn't go away when you trigger multiple copy button one after another

### ISSUE THREAD

**Issue by Timber232** [squidfunk/mkdocs-material#355]
## Description

The copy button feature retains it's tool-tip permanently until the page is refreshed.
This only happens if you trigger another tool-tip before the other one disappear

### Expected behavior
The tool tip to disappear  after a few seconds

### Actual behavior

![copy_button](https://cloud.githubusercontent.com/assets/627637/26699850/433ec3d8-46e9-11e7-8f03-ef582a35f39a.gif)

### Steps to reproduce the bug

1. Create a document with multiple code snippets
2. Quickly click the copy button from one button to another

### Package versions

* Python: 2.7.12
* MkDocs: 0.16.3
* Material: 1.7.0

### Project configuration

``` yaml
site_name: My Docs
theme: 'material'
```

### System information

* OS: Irrelevant 
* Browser: Chrome

**Comment by squidfunk** [comment]
Oh, this is indeed a bug. I think I know where it comes from.
