### ISSUE TITLE
language.html

### ISSUE THREAD

**Issue by fax1ty** [squidfunk/mkdocs-material#359]
Please help me with a multilingual system. How to use `language.html`? Please, give an example for few languages.
```html
<!-- Translations -->
{% macro t(key) %}{{ {
  "language": "en",
  "edit.link.title": "Edit this page",
  "footer.previous": "Previous",
  "footer.next": "Next",
  "meta.comments": "Comments",
  "meta.source": "Source",
  "search.languages": "en",
  "search.placeholder": "Search",
  "search.result.placeholder": "Type to start searching",
  "search.result.none": "No matching documents",
  "search.result.one": "1 matching document",
  "search.result.other": "# matching documents",
  "source.link.title": "Go to repository",
  "toc.title": "Table of contents"
}[key] }}{% endmacro %}
```

**Comment by squidfunk** [comment]
I was thinking of making an examples directory. Until then please see:

http://squidfunk.github.io/mkdocs-material/getting-started/#localization
http://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme

**Comment by squidfunk** [comment]
Okay, I misread your question at first - a multilingual is not possible with MkDocs at the moment, as it doesn't support multiple languages. However, you can create separate theme directories with your overrides and use them to create documentation hosted on separate paths, e.g.:

```
/en/ --> theme_en/partials/languages.html
/fr/ --> theme_fr/partials/languages.html
...
```
