### ISSUE TITLE
Trigger search from markdown file

### ISSUE THREAD

**Issue by abhinavtripathy** [squidfunk/mkdocs-material#3600]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I was wondering if there could be a feature where there is some way to trigger the search functionality from a markdown file. For example, there could be some sort of syntax in a markdown file that would let you basically make it a hyper link, when you click on it, the search bar opens with the text that was passed in as a parameter in the markdown file. 

### Use Cases

I think this would be really useful for making wikis where one can trigger search from any hyperlinks they want. For example, on documentation or wiki site made with mkdocs-material one could say "learn more about docker here", the text "here" could link to the search bar where it would search "docker".

**Comment by squidfunk** [comment]
Already supported via the [search sharing](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-sharing) feature:
https://squidfunk.github.io/mkdocs-material/?q=search
