### ISSUE TITLE
Add navigation config option to prevent navigation-auto-collapse

### ISSUE THREAD

**Issue by FrankEppink** [squidfunk/mkdocs-material#3623]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

We have quite a lot of markdown files in our mkdocs documentation portal and because of this the navigation tree is also quite large.

The undesired behavior now is auto-collapsing:

- Starting Position: Child page B1 of parent A1 is open and expanded
- User Action: User opens parent A2 and clicks on child B2
- Behavior:
	- Actual: parent A1 is collapsed
	- Desired: no auto-collapsing

I know that the configuration option **navigation.expand** exists and prevents the "auto-collapsing" but this comes at the price of having initially the complete navigation tree expanded. With our big navigation tree this however is not an option.

It would be helpful to have a configuration option **navigation.no-auto-collapse**, which
- initially has everything collapsed
- does no auto-collapse of the previous selected/expanded items.

P.S.: mkdocs-material(-insiders) is a great tool, thanks for providing it.

### Use Cases

Benefit: Increase usability of the navigation tree.

Use Case: User wants to switch between two or three pages in different parent folders, e.g. for comparison.

The current behavior is annoying as the user has to memorize the previous open page and re-navigate to the right spot.
This might not be a problem for "small" navigation trees, but for our navigation tree it is.

Idea:
- Initially everything is collapsed.
- The user has full control about expanding and collapsing, i.e. no auto-collapsing.

**Comment by FrankEppink** [comment]
additional remark: I am aware of https://github.com/squidfunk/mkdocs-material/issues/767 but the javascript listed there (having a different target anyway) does not really help me to fix the problem.

**Comment by squidfunk** [comment]
Thanks for suggesting.

So as you might have realized, Material for MkDocs will generate a regular static site, and when JavaScript is available, enhance the site with additional features progressively. However, almost all features have a non-JavaScript fallback, except for things that are entirely interactive like search. This means that, in general, we must decide at build time how the resulting Markup will look – there's no state involved. This means that everything that involves state, e.g. the [color palette toggle](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle) or [linked content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs) are decided in the browser alone. The "auto-collapsing" you're seeing is the fact that the navigation's state is encoded into the built HTML via checkboxes. This is a pretty nice hack that's been around for ages to allow interactivity without JavaScript. Try turning off JavaScript and use Material for MkDocs – it's perfectly usable.

[Navigation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/) is one of the most complex parts of Material for MkDocs given the many different feature flags there are. Pulling off this feature might be possible, but from my knowledge of the code, it would involve so much effort to make sure not to break anything else that I'd say it's not worth the trouble. We would need to somehow merge the state of the viewer and the state of the page that is being loaded, which will also interfere with mobile navigation as it also uses the same checkboxes. Additionally, in the future, we must be sure at all times not to break this feature accidentally.

Thus, I'm currently not considering implementing this. I hope for your understanding.

**Comment by squidfunk** [comment]
Duplicate of #2518

__Related__

- #2818
- #2927

**Comment by FrankEppink** [comment]
@squidfunk Thanks for the quick feedback (even though the issue was closed)
