### ISSUE TITLE
Don't copy `>>> ` characters from `pycon` fenced codeblocks

### ISSUE THREAD

**Issue by mondeja** [squidfunk/mkdocs-material#3647]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When using a fenced `pycon` codeblock (Python console syntax highlighting) the `>>> ` characters can be skipped of being manually selected using the next custom CSS as is [documented in mkdocstrings](https://mkdocstrings.github.io/recipes/#prevent-selection-of-in-python-code-blocks):

```css
.highlight .gp, .highlight .go { /* Generic.Prompt, Generic.Output */
    user-select: none;
}
```

But clicking in the "Copy to clipboard button", it copies the whole line, including the `>>> ` part, which is not desirable for `pycon` code blocks. It seems that [ClipboardJS offers a way to edit the content](https://github.com/zenorocha/clipboard.js#advanced-options) that is copied.

It should be reasonable to add more logic to the clipboard component? Maybe checking the CSS of the text and skipping all the content styled with `user-select: none;`? Thanks in advance!

### Expected behaviour

Copying `pycon` fenced code blocks should not include `>>> ` Python console characters.

### Actual behaviour

Undesired characters are copied.

### Steps to reproduce

N/A

### Package versions

All

### Configuration

```yaml
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences

extra_css:
  - css/code_select.css
```

### System information

N/A

**Comment by facelessuser** [comment]
1. this should not be done by default. Those scopes/classes, while relevant in that specific language, may have unintended side effects if done globally. At the very least, you should target the language with the class.
2. In the latest `pymdownx.highlight`, you can enable `pygments_lang_class` to attach the language class to the block to help accomplish the above.

Now, whether Material should do this by default is debatable. I'm not sure I want that functionality as sometimes I would like to copy the whole block for various reasons.

**Comment by squidfunk** [comment]
Thanks for reporting.

> It should be reasonable to add more logic to the clipboard component? Maybe checking the CSS of the text and skipping all the content styled with user-select: none;? Thanks in advance!

I'm not interested in doing this, as we would enter the hell of `getComputedStyle` and all of its quirks. I understand the problem, but I'd consider it an edge case. As an alternative, you can [hide the copy-to-clipboard button](https://github.com/squidfunk/mkdocs-material/issues/2418#issuecomment-794571375).

Also, I fully agree on what @facelessuser is saying.

**Comment by pawamoy** [comment]
Thanks for your inputs, I'll reflect that in *mkdocstrings* docs :+1:

**Comment by ukkopahis** [comment]
>> It should be reasonable to add more logic to the clipboard component? Maybe checking the CSS of the text and skipping all the content styled with user-select: none;?

> @squidfunk I'm not interested in doing this, as we would enter the hell of getComputedStyle and all of its quirks.

As the saying goes "Many things are possible, just as long as you don’t know they’re impossible". ;)
 
Now implemented in SensorsIot/IOTstack#547 (third commit).

This is a feature "commonly" used in technical documentation (e.g. [docker](https://docs.docker.com/get-started/
) and [sphinx-doc](https://www.sphinx-doc.org/en/master/usage/quickstart.html)), so I think an implementation would be of benefit to Material.

Reading this issue and #2418 I get the feeling that a proper "only allow selection and copying of what is meant to be copy-pasted into a console"-solution is something that could be accepted? At least, if done as a feature that has to be enabled:
```yml
theme:
  feature:
    - highlight.limit_console_selection
```

The implementation should also have css for all `*ConsoleLexer` [languages](https://pygments.org/docs/lexers/).

I'm interested in creating such a contribution, if there's a reasonable probability it would be merged?

**Comment by squidfunk** [comment]
> I'm interested in creating such a contribution, if there's a reasonable probability it would be merged?

It's very likely not getting merged for the reasons already stated. Also, this has been debated multiple times and we always arrived at the conclusion that it's better not done by default because we'd now be in the world of monkey-patching the copying logic of Clipboard.js. It's too controversial and too breakable.

**Comment by ukkopahis** [comment]
Umm.. I agree, but I don't think I proposed either of those?

* **not done by default**: Enabled only with the feature flag
* **monkey-patching**: No patching done in my [javascript](https://github.com/SensorsIot/IOTstack/blob/d60bdb9635c0bf30e496b1bd65527c80d18e1d4d/docs/javascript/fix-codeblock-console-copy-button.js). It uses a Clipboard.js feature to override the content-to-be-copied by adding the `data-clipboard-text` attribute for the button-element:
    ![image](https://user-images.githubusercontent.com/95980324/165038205-ede0ea04-efa3-4a4b-b011-7a0035028ce7.png)
    If need be, this attribute could be added when the site is being generated and the solution wouldn't need any javascript changes.

**Comment by squidfunk** [comment]
> If need be, this attribute could be added when the site is being generated and the solution wouldn't need any javascript changes.

Clipboard.js is applied by Material for MkDocs, not Python Markdown. If you turn off JavaScript, you'll see that the code blocks remain untouched by Clipboard.js, thus it's entirely done in the browser. This means that any logic involving changing `data-clipboard-text` would need to be done in Material for MkDocs.

**Comment by arcgis-advancing** [comment]
Have a look at this https://csser.space/questions/conceal-the-text-yet-make-it-appear-when-copied-and-pasted-without-the-use-of-javascript insight
