### ISSUE TITLE
auto slate mode - "system" default option

### ISSUE THREAD

**Issue by ITJamie** [squidfunk/mkdocs-material#3651]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Re: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/

It would be nice if mkdocs had a config option to automatically pick the theme based on the system theme.
Many websites now follow the system theme (light vs dark) (https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme)

### Use Cases

when going from an app that has darkmode support and going to a docs link it can be quite shocking to have such a harsh theme change

**Comment by FISHMANPET** [comment]
The theme already supports that, if I'm understanding you correctly: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference

**Comment by squidfunk** [comment]
Thanks for reporting. Closing as duplicate:

- #2727
- #3123 
- #3244
