### ISSUE TITLE
How to hide `toc` and `navigation` for all pages

### ISSUE THREAD

**Issue by Dup4** [squidfunk/mkdocs-material#3686]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I read some related tutorials, such as https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=hide#hiding-the-sidebars.

I found that using `metadata`, I can only hide the `toc` and `navigation` of a single page.

If I want to hide `toc` and `navigation` for all pages, I have to add the following configuration on each page.

```yaml
hide:
    - toc
    - navigation
```

And I read the relevant source code and found that there is no other configuration item that can control its hiding.

https://github.com/squidfunk/mkdocs-material/blob/master/src/base.html#L253-L289

### Use Cases

So can we add a global configuration that can control the hiding of `toc` and `navigation` and some other components?

**Comment by squidfunk** [comment]
Thanks for suggesting. You can use [customization](https://squidfunk.github.io/mkdocs-material/customization/) and [override the `site_nav` block](https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks) in a custom `main.html`:

``` html
{% extends "base.html" %}

{% block site_nav %}{% endblock %}
```

Please see the [theme extension guide](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme) for further guidance.

**Comment by Dup4** [comment]
Thanks.

**Comment by honzajavorek** [comment]
The solution breaks the hamburger menu. The only workaround I found is this:

```yaml
# mkdocs.yml
hooks:
  - on_page_markdown.py
```

```python
# on_page_markdown.py
from mkdocs.config import Config
from mkdocs.structure.pages import Page
from mkdocs.structure.files import Files


def on_page_markdown(
    markdown: str,
    page: Page,
    config: Config,
    files: Files,
) -> str:
    # Unfortunately this is aparently the only way to hide the navigation
    # on every page using the material theme. Solution described in
    # https://github.com/squidfunk/mkdocs-material/issues/3686 breaks
    # hamburger menu on small viewports.
    page.meta["hide"] = ["toc", "navigation"]
```

**Comment by squidfunk** [comment]
Thanks for sharing! Even easier by now, use the [`meta` plugin](https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin) and add the following file:

`docs/.meta.yml`

``` yaml
hide:
  - toc
  - navigation
```
