### ISSUE TITLE
Deprecation warning 'invalid escape sequence \s' raised in Python 3.10

### ISSUE THREAD

**Issue by lyz-code** [squidfunk/mkdocs-material#3695]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When building the site with the material theme jinja2 complains with a DeprecationWarning

### Expected behaviour

No DeprecationWarning is raised

### Actual behaviour

```
DeprecationWarning: invalid escape sequence '\s'

The above exception was the direct cause of the following exception:
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/jinja2/lexer.py:652: in wrap
    self._normalize_newlines(value_str[1:-1])
E   DeprecationWarning: decoding with 'unicode-escape' codec failed (DeprecationWarning: invalid escape sequence '\s')

The above exception was the direct cause of the following exception:
tests/e2e/test_plugin.py:123: in test_plugin_creates_weekly_rss_feed
    build.build(config)  # act
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/mkdocs/commands/build.py:306: in build
    _build_theme_template(template, env, files, config, nav)
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/mkdocs/commands/build.py:111: in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/mkdocs/commands/build.py:90: in _build_template
    output = template.render(context)
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/jinja2/environment.py:1291: in render
    self.environment.handle_exception()
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/jinja2/environment.py:925: in handle_exception
    raise rewrite_traceback_stack(source=source)
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/material/404.html:4: in top-level template code
    {% extends "main.html" %}
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/material/main.html:4: in top-level template code
    {% extends "base.html" %}
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/material/base.html:4: in top-level template code
    {% import "partials/language.html" as lang with context %}
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/jinja2/environment.py:1399: in make_module
    return TemplateModule(self, ctx)
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/jinja2/environment.py:1529: in __init__
    body_stream = list(template.root_render_func(context))  # type: ignore
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/material/partials/language.html:4: in top-level template code
    {% import "partials/languages/" ~ config.theme.language ~ ".html" as lang %}
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/jinja2/environment.py:925: in handle_exception
    raise rewrite_traceback_stack(source=source)
../../.venvs/mkdocs-newsletter/lib/python3.9/site-packages/material/partials/languages/en.html:19: in template
    "search.config.separator": "[\s\-]+",
E   jinja2.exceptions.TemplateSyntaxError: invalid escape sequence '\s')
```

### Steps to reproduce

1. Build the site programmatically with warnings set.

### Package versions

- Python: `Python 3.9.10`
- MkDocs: `mkdocs, version 1.2.3 from ../mkdocs-newsletter/lib/python3.9/site-packages/mkdocs (Python 3.9)`
- Material: `Version: 8.2.5`

### Configuration

```yaml
---
site_name: The Blue Book
site_description: My second brain
site_author: Lyz
site_url: https://lyz-code.github.io/blue-book
site_dir: site
nav:
  - Introduction: index.md

plugins:
  - git-revision-date-localized:
      type: timeago
  - autolinks
  - section-index
  - mkdocs-newsletter

markdown_extensions:
  - toc:
      baselevel: 2
theme:
  name: material
  logo: img/logo.bmp
```

### System information

- Operating system: Debian
- Browser: Irrelevant

**Comment by squidfunk** [comment]
Thanks for reporting. Funny. That's likely of the category "how did that ever work", because, yes, the backslash must be escaped to be preserved in the string to be a valid regular expression, but I'm amazed that this didn't occur before. Jinja seems to have done this implicitly because the configuration which is passed to the theme is correct:

<img width="296" alt="Bildschirmfoto 2022-03-22 um 18 07 59" src="https://user-images.githubusercontent.com/932156/159536338-411e0f67-2874-4c98-b916-eee1d8cd8ba8.png">

Anyway, this should now be fixed in eab95da23. I'm not sure if we also need to adjust the settings for `mkdocs.yml`, as [MkDocs itself advertises that backslashes must not be escaped](https://www.mkdocs.org/user-guide/configuration/#separator). My testing shows it's not necessary, but if it is, please open a new issue (or even better: PR the necessary changes).

**Comment by squidfunk** [comment]
Released as part of 8.2.6.

**Comment by lyz-code** [comment]
Thank you for the quick fix and maintaining the package :)

**Comment by QWERTAL124** [comment]
Hi everyone ! I have trouble with above errror , but  my codes error not identity with this ! My code line following :  subprocess.call('reg add HKCU\Software\Microsoft\CurrentVersion\Run /v Dadof_Virus /t REG_SZ/d"' + joylashuv + '"',shell=True)  
Error : 
          SyntaxWarning: invalid escape sequence '\S'
  subprocess.call('reg add HKCU\Software\Microsoft\CurrentVersion\Run /v Dadof_Virus /t REG_SZ/d"' + joylashuv + '"',shell=True)

How I fix this problem ? ( Thank for answers ! ! !)

**Comment by squidfunk** [comment]
This has nothing to do with Material for MkDocs. Please ask your question on a general forum like StackOverflow.

**Comment by QWERTAL124** [comment]
Thank you for answer bro ! Can I know how to fix tgis problem .Probably, I
try in Python 3.10v

Shan, 30-dek, 2023, 8:56 TK Martin Donath ***@***.***>:

**Comment by Suvoo** [comment]
> Hi everyone ! I have trouble with above errror , but my codes error not identity with this ! My code line following : subprocess.call('reg add HKCU\Software\Microsoft\CurrentVersion\Run /v Dadof_Virus /t REG_SZ/d"' + joylashuv + '"',shell=True) Error : SyntaxWarning: invalid escape sequence '\S' subprocess.call('reg add HKCU\Software\Microsoft\CurrentVersion\Run /v Dadof_Virus /t REG_SZ/d"' + joylashuv + '"',shell=True)
> 
> How I fix this problem ? ( Thank for answers ! ! !)

Use : 
```
path = r'your/path'
```
instead of
```
path  = 'your/path'
```

**Comment by QWERTAL124** [comment]
Thank you very much !

вт, 11 июн. 2024 г. в 01:33, Suvodeep Sinha ***@***.***>:
