### ISSUE TITLE
mermaid.js diagrams without JavaScript

### ISSUE THREAD

**Issue by jholdstock** [squidfunk/mkdocs-material#3715]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Mermaid.js diagrams are not rendered when JavaScript is disabled in the browser. Instead, the diagram source is displayed in a code block.

In a perfect world, the mermaid diagram would be rendered at compile time and served statically at run time, completely removing the dependency on client-side JS.

If  that isn't feasible, falling back to a static image rather than showing the diagram source would be nice.

### Use Cases

Users may choose to run browsers without JavaScript for multiple reasons - eg.hardware/resource constraints, security/privacy concerns. Those users should still be able to view diagrams.

**Comment by facelessuser** [comment]
This would be less of a theme thing then.

You'd have to write your own Markdown plugin and call something like https://github.com/mermaid-js/mermaid-cli or use it manually to generate images you can embed eliminating the need for a plugin. There are also other UML CLI tools, which could be used in one of these ways.

**Comment by squidfunk** [comment]
This is really beyond the scope of this project as @facelessuser already pointed out. It might be solvable by a third-party plugin, but there's no intention to add this functionality to Material for MkDocs natively.
