### ISSUE TITLE
Nav: Embedded Markdown or HTML?

### ISSUE THREAD

**Issue by sean-freeman** [squidfunk/mkdocs-material#3727]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Investigating the documentation, under the nav bar area there doesn't appear to be a clean way to enable a user-friendly button to the GitHub Org/Repos/Repo of the static site (see below image as an example).

Maybe with partials that might be possible but it is complex. Potentially an easier way is to allow a string for a Markdown URL to create a button, which would allow re-use of the icons libraries.

Very minor thing. It is just a clean way to list the static site content, and at the end of the list refer back to the actual repo/s. 

<img width="344" alt="image" src="https://user-images.githubusercontent.com/1815807/158424131-042faf6b-eff0-4254-9c62-01e9016348a3.png">

### Use Cases

Only 1 use case, described in above.

**Comment by lampensau** [comment]
Not sure I understand correctly, however the following might help:

- You can use materials [own buttons](https://squidfunk.github.io/mkdocs-material/reference/buttons/) by enabling the markdown extension [attr_list](https://python-markdown.github.io/extensions/attr_list/) in your `mkdocs.yml` and adding the CSS class `.md-button` to any link in your document. With this you can create the above button inside a markdown document (`[:material-github: View GitHub Repos](https://github.com/){.md-button}`).
- You can use the [mkdocs config options](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-name) `repo_name` and `repo_url` to display your repo next to the search field in the top navigation.
![grafik](https://user-images.githubusercontent.com/12431219/158647459-4d91c6a3-c975-4b08-b977-11ae284292b4.png)

**Comment by squidfunk** [comment]
Thanks @lampensau for answering. I'm also not sure I understand the request. However, in the screenshot posted in the OP a button is rendered below the `h1`. This is achievable by what @lampensau posted:

```
[:material-github: View GitHub Repos](https://github.com/){.md-button}
```

Other than that, if you want to add additional content below the navigation, theme extension is the way to go.
