### ISSUE TITLE
Render two unordered lists next to each other

### ISSUE THREAD

**Issue by Yang-Xijie** [squidfunk/mkdocs-material#3731]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

It will be great to render

```
* item 1
* item 2
* item 3

- item a
- item b
- item c
```

as two different unordered lists, if different characters (`*` `-` `+`) are used for each list, and they are seperated by a blank line. 

rendering eg. add a blank line between them (GitHub does like this):

* item 1
* item 2
* item 3

- item a
- item b
- item c

However, I noticed that mkdocs-material ignores the line which seperates these two lists. I wonder whether it is a bug or it was designed as this?

Reference: https://squidfunk.github.io/mkdocs-material/reference/lists/?h=list#using-unordered-lists

### Use Cases

It will better Markdown editing experience if we can use two unordered lists next to each other.

**Comment by facelessuser** [comment]
HTML formatting aside, Python Markdown matches the reference implementation in this regard, see results here: https://johnmacfarlane.net/babelmark2/?text=*+item+1%0A*+item+2%0A*+item+3%0A%0A-+item+a%0A-+item+b%0A-+item+c. Notice that there are a number of parsers that do the same as us.

The spaces simply triggers loose lists vs tight lists (list item wrapped in `<p>` tag). This operates like `Markdown.pl` etc.

**Comment by facelessuser** [comment]
Also, Material doesn't control the Markdown parser, this is really an upstream request, not a theme request.

**Comment by squidfunk** [comment]
Second @facelessuser. I think you should ask the maintainers of [Python Markdown](https://github.com/Python-Markdown/markdown).
