### ISSUE TITLE
Search bar results is misaligned by 1 pixel

### ISSUE THREAD

**Issue by Timber232** [squidfunk/mkdocs-material#374]
## Description

This is really minor, but the search bar results panel is misaligned with the search text box by 1 pixel.

### Expected behavior

The search bar result element to be perfectly aligned with the search text box.

![image](https://user-images.githubusercontent.com/627637/27182219-791dff4a-51a8-11e7-8f43-b1d19015f0f0.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/627637/27182194-64c538ec-51a8-11e7-9608-3a76038075f6.png)

### Steps to reproduce the bug

1. Click on the search bar
2. Notice that the search result is 1 pixel misaligned

### Package versions

* Python: 2.7.13
* MkDocs: 0.16.3
* Material: 1.7.2

### Project configuration

Not relevant, also happening on the main MkDocs Material website.

### System information

* OS: Windows 10
* Browser: Chrome

**Comment by squidfunk** [comment]
This is a known problem which stems from the `rem`/font-based sitzing of the theme on large screens, see:

https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/layout/_base.scss#L37-L50

This is related to subpixel rounding. If someone has a fix that does not kill the nice feature of automatic sizing, I'm happy to include it.

**Comment by squidfunk** [comment]
Fixed in #505.

**Comment by squidfunk** [comment]
Released with 1.12.0
