### ISSUE TITLE
Missing icon and incorrect border for admonition in PDF output

### ISSUE THREAD

**Issue by estan** [squidfunk/mkdocs-material#3771]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When using `mkdocs-pdf-export-plugin`, icons are no longer shown for admonitions in the PDF output since `mkdocs-material` rev b345a0b65 and the border does not look correct.

### Expected behaviour

It should look like this (this is with c79b786ea):

![c79b786ea](https://user-images.githubusercontent.com/86675/160278041-1d3c3328-89fe-46f9-913c-09cf2461d5b5.png)

### Actual behaviour

But it looks like this (this is with master):

![master](https://user-images.githubusercontent.com/86675/160278056-bf251c7f-b495-41d8-94b1-396a0dd24e5c.png)

Note the lack of icon, and how the blue border extends all around the admonition.

### Steps to reproduce

**Test input `test/docs/index.md` (`test/mkdocs.yml` as below under Configuration)**

```
# Welcome to MkDocs

!!! note
    This is a note
```

### Incorrect behavior with master
```
python3 -m venv bad_env
source bad_env/bin/activate
pip install wheel
pip install mkdocs mkdocs-pdf-export-plugin git+ssh://git@github.com/squidfunk/mkdocs-material.git
mkdocs build -f test/mkdocs.yml && xdg-open test/site/index.pdf
```

### Correct behavior with rev c79b786ea
```
python3 -m venv good_env
source good_env/bin/activate
pip install wheel
pip install mkdocs mkdocs-pdf-export-plugin git+ssh://git@github.com/squidfunk/mkdocs-material.git@c79b786ea
mkdocs build -f test/mkdocs.yml && xdg-open test/site/index.pdf
```

I `git bisect`:ed and the first bad commit seems to be b345a0b65:

    b345a0b65 Prototyped material icon SVG integration

### Package versions

- Python: `3.8.10`
- MkDocs: `1.3.0` (git rev `7418e7961`)
- Material: `4.6.3`

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
plugins:
  - pdf-export
markdown_extensions:
  - admonition
```

### System information

- Operating system: Ubuntu 20.04.4 LTS
- Browser: Firefox 98.0.2 and Okular 1.9.3 for PDF viewing

**Comment by squidfunk** [comment]
Thanks for reporting. However, we do not officially support the `mkdocs-pdf-exports-plugin`, so it's better to ask the authors of that plugin. When you use the print function of the browser, icons appear correctly. Furthermore, the version you're using is more than two years old (4.6.3), which we don't support anymore anyway.

**Comment by estan** [comment]
@squidfunk Alright, thanks. I will bring it up with `mkdocs-pdf-exports-plugin` author (I was using mkdocs-material from Git master btw, I just noticed that 4.6.3 was the earliest released version in which it worked).

**Comment by squidfunk** [comment]
Okay great. I guess that the plugin is having trouble with `mask-image` which we're using since version 5 for more flexibility. The section on [browser support](https://squidfunk.github.io/mkdocs-material/browser-support/) contains some more information on which CSS properties are expected to work.

**Comment by estan** [comment]
Thanks. I think this info will be of use. Possibly the place to fix is in weasyprint which the plugin is using.

**Comment by estan** [comment]
Turns out there was an open issue for mask-image support in weasyprint already: https://github.com/Kozea/WeasyPrint/issues/1458
