### ISSUE TITLE
Not more able to build a site inside github

### ISSUE THREAD

**Issue by aborruso** [squidfunk/mkdocs-material#3772]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi, I my github acion I have

```
pip install mkdocs-material markdown mkdocstrings mkdocs-rss-plugin  mkdocs-click mkdocs-charts-plugin mkdocs-table-reader-plugin
```

and then `mkdocs gh-deploy --force`.

When I run it I have:

```
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/markupsafe/__init__.py)
```

### Expected behaviour

To run without errors

### Actual behaviour

I have the above error

### Steps to reproduce

This is my workflow https://github.com/ondata/i-dati-che-vorrei/actions/runs/2048994152/workflow

### Package versions

- Python: `python --version`

3.x
- MkDocs: `mkdocs --version`

mkdocs-1.2.4

- Material: `pip show mkdocs-material | grep -E ^Version`

mkdocs-material-8.2.8

### Configuration

```yaml
site_name: I dati che Vorrei
site_url: https://vorrei.datibenecomune.it

https://github.com/ondata/i-dati-che-vorrei/blob/main/mkdocs.yml
```

### System information

It's ubuntu on github

**Comment by aborruso** [comment]
I have solved forcing this `markupsafe==2.0.1`

I have read about this here https://github.com/aws/aws-sam-cli/issues/3661#issuecomment-1044340547=

**Comment by squidfunk** [comment]
Thanks for reporting. Your reproduction contains a lot of third-party plugins. Does this also happen if you only install Material for MkDocs?

```
pip install mkdocs-material
```

**Comment by aborruso** [comment]
> Thanks for reporting. Your reproduction contains a lot of third-party plugins. Does this also happen if you only install Material for MkDocs?

Yes, thank you

**Comment by squidfunk** [comment]
This is an upstream issue, so there's nothing we can do about it: https://github.com/pallets/jinja/issues/1585

**Comment by aborruso** [comment]
> This is an upstream issue, so there's nothing we can do about it: [pallets/jinja#1585](https://github.com/pallets/jinja/issues/1585)

luckily this works  `markupsafe==2.0.1`
