### ISSUE TITLE
 Error: The "offline" plugin is not installed, mkdocs-material docs says should work out-of-the-box

### ISSUE THREAD

**Issue by tljstewart** [squidfunk/mkdocs-material#3784]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The [documentation for material says](https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/#built-in-offline-plugin) that you can enable offline plugin, however the build fails saying ` Error: The "offline" plugin is not installed`

```
$ mkdocs serve
INFO     -  Building documentation...
ERROR    -  Config value: 'plugins'. Error: The "offline" plugin is not installed
Aborted with 1 Configuration Errors!
```

```
#mkdocs.yml
plugins:
  - offline:
```

### Expected behaviour

as the documentation states this:

```
plugins:
  - offline
 ```

should work out-of-the-box, I expect it to work out-of-the-box and not error and say "offline plugin not installed"

### Actual behaviour

error: offline plugin not installed

### Steps to reproduce

plugins:
  - offline

in mkdocs.yml

### Package versions

  - Python: `python --version`
  - MkDocs: `mkdocs --version`
  - Material: `pip show mkdocs-material | grep -E ^Version`
 
```
$ python --version && mkdocs --version && pip show mkdocs-material | grep -E ^Version
Python: 3.10.4
mkdocs: version 1.3.0
material: Version: 8.2.8
```

### Configuration

```yaml
site_name: name
site_url: ""
plugins:
  - offline
```

### System information

- Operating system: ...
- Browser: ...

Window, Chrome

**Comment by squidfunk** [comment]
Thanks for reporting. The offline plugin works just fine. Note that it's currently only available as part of the [Insiders build](https://squidfunk.github.io/mkdocs-material/insiders/), for which you would have to [become a sponsor](https://squidfunk.github.io/mkdocs-material/insiders/#how-to-become-a-sponsor), as denoted in the documentation:

<img width="450" alt="Bildschirmfoto 2022-03-31 um 17 24 06" src="https://user-images.githubusercontent.com/932156/161091618-9f8de0a7-ccf9-49ec-bfe6-8700a05359d8.png">

**Comment by tljstewart** [comment]
Ah, ya I see. I'm new to the project wasn't familiar with the `insider`. Looks like it's definitely worth [becoming a sponsor](https://squidfunk.github.io/mkdocs-material/insiders/#how-to-become-a-sponsor) I'm not sure how, but I kinda wish it would have be more obvious that it was built-in with a sponsorship 😢 I know it says insider twice in your image, but reading the paragraphs in the docs before and being a newcomer I really just wasted a lot of time trying to *fix* something that wasn't broken. I really appreciate your work, its a beautiful site

**Comment by squidfunk** [comment]
Thanks! There are currently 20 features that are available for sponsors – how could we make it more apparent without making the docs ugly? I really don't want to put a thick warning box under every feature saying that you need to sponsor for it to work. Therefore, I opted for the Insiders heart __and__ the Insiders tag. If you click any of it, you will be directed to the Insiders page, explaining the strategy. Just wondering what you'd expect.

**Comment by tljstewart** [comment]
I totally understand what you're saying and I agree. After thinking about this a bit more deeply, the first page I went to was `Getting Started` then `Setup`  without a reference to what the tags underneath the headers mean (btw, is an elegant way to annotate). I suggest some type of grid layout at the bottom of the `Getting Started` page with a short description/intent of the tags/symbols. I  think its a beautiful site, and I appreciate your work. 

![image](https://user-images.githubusercontent.com/8463038/161271567-2c3c17d4-a35b-428d-967f-94f2919bd32b.png)
![image](https://user-images.githubusercontent.com/8463038/161271784-d13e8a63-12e9-4a40-9e53-97798061f583.png)
![image](https://user-images.githubusercontent.com/8463038/161271906-de9a5668-331f-4db3-83d7-e702f41cc865.png)

**Comment by squidfunk** [comment]
@tljstewart haha, definitely. It's actually a quote from the book "[The Tao of Programming](https://www.mit.edu/~xela/tao.html)", one of my favorite books. Quite hard to find a copy these days, but I'm lucky to have one.

**Comment by squidfunk** [comment]
I've started documenting the conventions used in the documentation here:
https://squidfunk.github.io/mkdocs-material/conventions/
