### ISSUE TITLE
Substitute 404.html with 404.md

### ISSUE THREAD

**Issue by Yang-Xijie** [squidfunk/mkdocs-material#3788]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I wonder whether I can use a `404.md` to substitute the default `404.html` whose content is just `404 - Not found`.

### Use Cases

`Material for MkDocs` has a `index.md` which will take effect when the site opens. It might be great if a user can customize the 404 page. I have search the doc with `404`, it seems that users can use customized `404.html`. However, not every user knows  html well. A simple `404.md` will be a better choice.

If so, a user can give readers more information such as "the link you request might be a temporary link, the article may be still active on this site" and "use the search bar to find what you want". Chances are that the user experience will be improved.

**Comment by squidfunk** [comment]
Thanks for suggesting. This is a general question that is not specific to Material for MkDocs. Please take this [upstream](https://github.com/mkdocs/mkdocs).
