### ISSUE TITLE
Feature suggestion: allow more flexibility in github release source fact for monorepos

### ISSUE THREAD

**Issue by jlipps** [squidfunk/mkdocs-material#3800]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Currently, source facts are derived from GitHub, including the current release. For monorepos, releases for multiple packages might be published to the same github repo. It would be nice to provide some kind of filtering mechanism to Material so that only releases matching a certain package or string or regex would be included in the source fact.

I encountered this issue while trying to make a new docs system for [appium](appium/appium). The release tag which is shown is for a package unrelated to the one I am publishing docs for.

### Use Cases

This would benefit monorepo users or those who might want flexibility over which release/tag is shown in the documentation (not simply the first returned by GitHub).

### Screenshots / Mockups

![Screen Shot 2022-04-05 at 11 33 15](https://user-images.githubusercontent.com/605053/161825574-437eae60-9bec-4fa8-a0bf-b710022bb6b2.png)

**Comment by squidfunk** [comment]
Thanks for suggesting. I agree that more flexibility would be awesome, but sadly, GitHub's _Latest Release_ endpoint will always return the latest release and doesn't allow for filtering. For a detailed explanation, see https://github.com/squidfunk/mkdocs-material/issues/2943#issuecomment-899667411

__Related__:

- #2943 
- #3439

**Comment by jlipps** [comment]
OK. Would it be possible to just have an option to not show any repo facts instead, or to show something custom? I guess it's possible to do this by creating an override, but I figure this might be a somewhat common issue.

**Comment by squidfunk** [comment]
It's easy with a few lines of CSS, as noted in https://github.com/squidfunk/mkdocs-material/issues/2481#issuecomment-804046887. I'm not keen on adding another option which we'd have to hand over from`mkdocs.yml` to `base.html` to the JavaScript when the same is achievable with a few lines of CSS.

**Comment by jlipps** [comment]
OK, thanks!
