### ISSUE TITLE
TOC: last item incorrectly highlighted when not enough content to fill page

### ISSUE THREAD

**Issue by marc2k3** [squidfunk/mkdocs-material#3809]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When you have multiple headers in a page to generate a TOC, the last item is automatically highlighted when there isn't enough content to fill the page.

### Expected behaviour

The last item should only be highlighted when scrolling to the bottom of the page - something that isn't possible when there isn't enough content/scrollbar.

### Actual behaviour

![image](https://user-images.githubusercontent.com/62050527/162665812-baef61b3-a258-4afb-8f99-2004ea4f515f.png)

If you resize the window so a scrollbar becomes necessary, the last item is no longer highlighted...

![image](https://user-images.githubusercontent.com/62050527/162665870-39d2c326-8101-42ea-92ee-8e03d9085e87.png)

### Steps to reproduce

docs/index.md
```
## blah

## urgh
````

I also have a real world example here:

https://marc2k3.github.io/jscript-panel/docs/interfaces/ITextLayout/

### Package versions

Python 3.10.4
Mkdocs 1.3.0
Material 8.2.9

### Configuration

```yaml
site_name: test
theme: material
```

### System information

Windows 10 21H2 
Firefox 99/Edge Chromium100

**Comment by squidfunk** [comment]
Thanks for reporting. This problem arises from the behavior that when you scroll to the end of the page (which in you're example you already are at), it's always the last item highlighted. I would regard the use case you provided as an ephemeral edge case that only arises when a page is filled with a few sections which do not contain any content, which disappears when content is added. For this reason, I'm currently regarding this as not worth fixing.

**Comment by marc2k3** [comment]
Ok, thanks for all your work on this, It really is a great project.
