### ISSUE TITLE
Announcement Bar with dismiss feature not rendering (insiders build)

### ISSUE THREAD

**Issue by tmarkovski** [squidfunk/mkdocs-material#3814]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The dismiss button in announcement bar isn't showing up.
Rendered page: https://docs-v2.trinsic.id
Setting enabled: https://github.com/trinsic-id/sdk/blob/a07449bd69e684415680cf5a1914cd20f23929e8/mkdocs.yml#L57
Announcement bar: https://github.com/trinsic-id/sdk/blob/a07449bd69e684415680cf5a1914cd20f23929e8/docs/overrides/main.html#L16

### Expected behaviour

Button should show

### Actual behaviour

Button isn't showing

### Steps to reproduce

Clone and run repo locally, button isn't showing pretty consistently

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version` - Version: 8.2.9+insiders.4.12.0

### Configuration

```yaml
https://github.com/trinsic-id/sdk/blob/a07449bd69e684415680cf5a1914cd20f23929e8/mkdocs.yml#L57
```

### System information

GitHub agent runner, Linux

**Comment by squidfunk** [comment]
Thanks for reporting. Does this also happen on a mint installation? You have a pretty big documentation project, so it'll take some time for me to reproduce the problem. If you could provide a smaller example, that would help me tremendously push out a fix much quicker 😊

**Comment by tmarkovski** [comment]
I think I resolved this by deleting the `gh-pages` branch and re-running everything.
I was also able to run this locally by clearing the build cache.
I can verify this is now working by looking at both the [deployed code](https://github.com/trinsic-id/sdk/blob/c898602e0a098ab18ca440ea4176ebba114e9492/index.html#L164) and [rendered page](https://docs-v2.trinsic.id/).

Your comment on "mint installation" helped me clean up the github branch. Thanks for the help and for the great work!
