### ISSUE TITLE
Card grids as links

### ISSUE THREAD

**Issue by PalavaNet** [squidfunk/mkdocs-material#3826]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Hi,

I really love the new card grids. https://squidfunk.github.io/mkdocs-material/reference/grids/#using-card-grids
 Would it be possible to have them act as buttons? The basic https://squidfunk.github.io/mkdocs-material/reference/grids/#list-syntax example already looks like a button.

I'm currently adding my own styling to do this but it feels like a cool feature to include with the base package. 

### Use Cases

People who want to create grids of links. For example, I currently use them in `index.md` files to redirect to sub pages rather than use the bulkier appearance found in the complex example here - https://squidfunk.github.io/mkdocs-material/reference/grids/#list-syntax

There are definitely other ways of doing this but this feels clean to me

### Screenshots / Mockups

![Untitled33](https://user-images.githubusercontent.com/33756685/164472482-3d0c93ea-4470-4bf3-86a7-987f490a7858.png)

**Comment by squidfunk** [comment]
Thanks for suggesting! I actually investigated this at the beginning of implementing this feature, but sadly, Markdown does not support wrapping blocks in a link. Links are inherently inline elements in Markdown. However, you can use HTML to achieve the same thing:

``` html
<p class="grid" markdown>
  <a href="#" class="card">Link 1</a>
  <a href="#" class="card">Link 2</a>
  <a href="#" class="card">Link 3</a>
  <a href="#" class="card">Link 4</a>
</p>
```

Note that you have to use a `p` element as a wrapper, or the Markdown parser will insert `p` elements around each link which will not work with the current implementation. You can then add anything you like inside the links, including extra Markdown:

``` html
<p class="grid" markdown>
  <a href="#" class="card">
:fontawesome-brands-html5: __HTML__ for content and structure
  </a>
  <a href="#" class="card">
:fontawesome-brands-js: __JavaScript__ for interactivity
  </a>
  <a href="#" class="card">
:fontawesome-brands-js: __JavaScript__ for interactivity
  </a>
  <a href="#" class="card">
:fontawesome-brands-internet-explorer: __Internet Explorer__ ... huh?
  </a>
</p>
```

Result:

<img width="711" alt="Bildschirmfoto 2022-04-21 um 16 09 30" src="https://user-images.githubusercontent.com/932156/164476551-8de9feba-fea1-4655-bb7e-8a9192ec9922.png">

**Comment by PalavaNet** [comment]
Ok, thanks for the speedy reply and keep up the good work!
