### ISSUE TITLE
Add support for OIDC

### ISSUE THREAD

**Issue by timothydilbert** [squidfunk/mkdocs-material#3854]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I am constantly writing documentation for customers using MKDocs. The thing is, this documentation shouldn't always be accessible by anyone.

It would be excellent if you considered implementing support for OIDC federated authentication. That way, when someone tries to view the MkDocs site, they would be redirected to the configured IdP, and need to authenticate in order to view the MkDocs site.

I would recommend you use the OIDC standard, via Authorization Code + PKCE.

### Use Cases

I am constantly writing documentation for customers using MKDocs. The thing is, this documentation shouldn't always be accessible by anyone.

### Screenshots / Mockups

NA

**Comment by squidfunk** [comment]
Thanks for suggesting! MkDocs produces a static site that can be hosted anywhere and isn't a web server or service. Thus, OIDC is definitely out of scope for this project. You can strap the OIDC solution of your choice in front of the web server hosting your documentation.

**Comment by timothydilbert** [comment]
@squidfunk, I wish you would reconsider the response.

Implementing this on the web server means that some sort of paid service would need to be put in front and proxy requests to the underlying MkDocs site.

My suggestion was geared at implementing OIDC logic into MkDocs by simply injecting some javascript into the HTML (e.g. on build) where the javascript would handle the redirect logic if the token wasn't present. As most people wouldn't know how to do that, being able to configure OIDC via configuration settings entered into the `mkdocs.yml` would be excellent (e.g. `client_id`, `token_endpoint`, `scope`, etc.). That makes your documentation portable and can be hosted on any web server without any dependancies.

It would be an excellent feature IMHO.

**Comment by squidfunk** [comment]
Well, we are Material for MkDocs, not MkDocs. We're just a theme, not the framework 😊 I suggest you ask your request over at [MkDocs](https://github.com/mkdocs/mkdocs), but I'm pretty convinced you'll receive the same response.
