### ISSUE TITLE
Hyperlinking to a search results page with keywords in query parameters

### ISSUE THREAD

**Issue by vasanth-asokan** [squidfunk/mkdocs-material#387]
### Feature request

I have a feature request. Is it possible to have a static page for search results, one that can take in search keywords as input from query parameters? This helps facilitate linking to search results on the docs site from tools for instance. Love material for mkdocs btw! It's awesome!

**Comment by squidfunk** [comment]
This is theoretically possible, but there's no plan for including this feature.

**Comment by vasanth-asokan** [comment]
Thanks. I'll take a pass at this myself. Any pointers / places to get started would be appreciated.

**Comment by squidfunk** [comment]
You have to adjust the `Search/Result.jsx` to handle query parameters and render the search results straight away. Look at how the search is initialized in the `application.js` when listening for the <key>F</key> or <key>S</key> key.

**Comment by squidfunk** [comment]
Closing this as there's currently no plan to integrate this, as it seems to be rather (!) an edge case. If you have any problems you are free to reopen it.

**Comment by wyaadarsh** [comment]
@vasanth-asokan  were you able to implement the search page funtionality? I needed a help on this one !! I am not so much well versed working with js at present. It would be great if you or @squidfunk  can help me on this 

Regards

**Comment by squidfunk** [comment]
Please see the ReadTheDocs theme on that. It not in the roadmap of the near future.

**Comment by wyaadarsh** [comment]
@squidfunk  can you please provide some more insights into it....just a overview of what to do will be of great help !! Thanks :)

**Comment by squidfunk** [comment]
This is not an easy task, as Material is currently not designed for this. You would have to create a new template for the search results and adjust the JavaScript so that it handles the search bar differently (<kbd>Enter</kbd> brings you to the results page) and renders the results. It's rather complex and not straight forward, so I cannot give you guidance without diving into it.
