### ISSUE TITLE
Support GitLab URLs other than gitlab.com

### ISSUE THREAD

**Issue by duncanmmacleod** [squidfunk/mkdocs-material#3884]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

It would be great to be able to support displaying project facts for GitLab projects that live outside of gitlab.com.

Currently project facts are only supported for projects under github.com or gitlab.com:

https://github.com/squidfunk/mkdocs-material/blob/9655c3a92471f261533d48b8611a8d24dbfebb13/src/assets/javascripts/components/source/facts/_/index.ts#L71

meaning that projects on custom domains don't get facts.

I realise it would be almost impossible to infer the instance type (github vs gitlab vs other) from the URL alone, or to support a never-ending regex of custom instance domains, but am hoping there may be a way to embed the project type from the mkdocs metadata into the URL which could then be passed to the javascript... sounds like a long shot.

### Use Cases

My organisation hosts its own GitLab instance, and we use mkdocs-material to render documentation, it would be a great extra feature to get project facts for our self-hosted projects.

**Comment by squidfunk** [comment]
Thanks for reporting. I'm not familiar with self-hosted GitLab, which means that this would need to be provided by a PR. The simplest thing I could think of is to just add a hash fragment to your repository URL, so the `switch` statement would follow the GitLab branch:

``` yaml
repo_url: https://example.com/self/hosted#gitlab
```

However, the second regular expression extracts the `base` and `slug` parameters from the URL assuming a specific URL structure. Is this URL structure the same for all self-hosted GitLab instances? If it is, we could adjust it, so it allows for custom domain names:

https://github.com/squidfunk/mkdocs-material/blob/9655c3a92471f261533d48b8611a8d24dbfebb13/src/assets/javascripts/components/source/facts/_/index.ts#L81

I'm happy to collaborate on a PR, but as noted can't test it myself.

**Comment by nejch** [comment]
A GitLab instance can be served at basically any subdomain or sub-location (e.g. `forge.company.com`, `company.com/git`, etc) and also supports nested subgroups (`company.com/git/my-org/my-team/my-sub-team/my-repo`), so I don't know if that's a reliable way to parse it.

I think a more reliable option would be an explicit `repo_provider: gitlab` though I'm not sure you're keen on adding more config options.

**Comment by squidfunk** [comment]
Thanks for sharing the insight. If there's no reliable way to parse it, we have no reliable way of detecting the `base` and `slug` parameters which we need to resolve the repository statistics. For this reason, I'm closing this as not fixable for now. If you need it, you can fork the theme and adjust the regular expressions so that it works for your use case.
