### ISSUE TITLE
Add block `extrabody` before `</body>` to `base.html`

### ISSUE THREAD

**Issue by twardoch** [squidfunk/mkdocs-material#3912]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Right now, the end of `base.html` is:

```
    {% block scripts %}
      <script src="{{ 'assets/javascripts/bundle.66f76809.min.js' | url }}"></script>
      {% for path in config["extra_javascript"] %}
        <script src="{{ path | url }}"></script>
      {% endfor %}
    {% endblock %}
  </body>
</html>
```

It would be useful if it was: 

```
    {% block scripts %}
      <script src="{{ 'assets/javascripts/bundle.66f76809.min.js' | url }}"></script>
      {% for path in config["extra_javascript"] %}
        <script src="{{ path | url }}"></script>
      {% endfor %}
    {% endblock %}
    {% block extrabody %}{% endblock %}
  </body>
</html>
```

The `extrabody` block should be an empty block, but would allow users to insert additional scripts and content before the `</body>` tag. In a way, it would mirror the `extrahead` block. 

### Use Cases

It’s common that I might want to load some additional libraries or define some functions in the `extrahead` block, and then execute some functions before `</body>`. 

Right now, I have to override the `scripts` block but that brings the danger that my code becomes out of sync with upstream. So an extra empty block for overrides would be useful — unless there is already something like that.

**Comment by squidfunk** [comment]
Thanks for suggesting. The following achieves the same thing, thus no extra block is necessary:

``` html
{% block scripts %}
  {{ super() }}
  <!-- Add your scripts here -->
{% endblock %}
```

**Comment by twardoch** [comment]
Thanks, I forgot about `super()`! Super! :)
