### ISSUE TITLE
Page layout seems to depend on length of pages

### ISSUE THREAD

**Issue by pideu-mh** [squidfunk/mkdocs-material#3914]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The problem does happen with the mkdocs theme, but not with the readthedocs theme. 

I must admit that I don't know where I should report the problem, but I am using the material theme, so here we go.

I have created a minimal working example. `mkdocs.yml` just sets the `site_name` and the `theme` to material. Then I added two files to the `docs` directory. `index.md` contains just minimal content. `index2.md` contains enough content, so that it does not fit onto a single page anymore and a navigation bar is shown on the right side of the window.

### Expected behaviour

When clicking on the navigation links on the left side you can freely change between the documents without any visual disturbance.

### Actual behaviour

When clicking on the navigation links on the left side, the newly selected page is shown correctly, however the whole layout of the page slightly shifts around.

I have created image snapshots when either of the two pages is shown and I have superimposed the image:
![2022-05-12_19h29_14](https://user-images.githubusercontent.com/28350507/168134613-7aab69da-ffe4-48cc-a350-62d5c57873cd.png)

As you can see the layout is quite different between these two pages, so navigating between these two pages looks very uneasy, because the elements are all rendered at different positions.

So the rendering of the page seems to depend on the length of the actual pages.

### Steps to reproduce

Please see above.

### Package versions

- Python: Python 3.10.2
- MkDocs: python -m mkdocs, version 1.3.0 from C:\xxx\mkdocs (Python 3.10)
- Material: 8.2.11

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
```

### System information

I am using Windows 10 and the problem happens with Firefox and Edge browsers.

**Comment by squidfunk** [comment]
Thanks for reporting. I can't find the issue right now, but this has already been asked: if the content extends the vertical viewport, your browser will show a scroll bar, which will reduce the viewport width, thus shifting the content slightly to the left. This is only experienced on OSs that don't overlay scrollbars, e.g. Windows.

The issue can be mitigated by always showing the scrollbar, which, personally, I find rather ugly, so this change won't be added to `master`. However, you can add the following [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) to achieve this yourself:

``` css
html {
  overflow-y: scroll;
}
```

**Comment by pideu-mh** [comment]
Thank you very much again for your lightning-fast response. I am sorry that this was a duplicate, I guess I just did not find the right words to do the search with.

You analysis is right to the point and thank you for explaining the background of the problem and the possible solution. I will discuss this internally and we will likely go with the additional CSS.
