### ISSUE TITLE
Tabs inside header support

### ISSUE THREAD

**Issue by yinkh** [squidfunk/mkdocs-material#3931]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Current tab navigation add a new nav below header,shall we support put nav inside the header?
when site_name or page name(navigation.tabs.sticky is config)  is overlength, we can truncatewords.

### Use Cases

Maximize the size of content.
Put the navigation bar inside header is one more common way.

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/8170059/168949754-230f1ca8-005b-435f-bdde-acca134ed53e.png)

**Comment by yinkh** [comment]
Another question: if you think this feature is needed and i want to develop this feature, the source code of  `material/assets/javascripts/bundle.efad133d.min.js` is need. Any way to fetch this source code?

**Comment by squidfunk** [comment]
Thanks for suggesting. I really don't want to maintain two navigation tabs implementations 😉 I guess you can imagine that a project of this size with so many features has a lot of issues and feature requests popping up all the time, and adding a slightly different take on something that already exists is something I'm not very interested in. After all, it's me who has to maintain it after the original implementer decided to move on. For this reason, I'm not considering this. However:

> Another question: if you think this feature is needed and i want to develop this feature, the source code of material/assets/javascripts/bundle.efad133d.min.js is need. Any way to fetch this source code?

All templates and assets are built from the `src` folder. If you fork the theme and set up the [theme development pipeline](https://squidfunk.github.io/mkdocs-material/customization/#theme-development), you can make the changes yourself to adjust Material for MkDocs to fit your taste!

**Comment by squidfunk** [comment]
On a side note, recommended read:

- https://github.com/squidfunk/mkdocs-material/discussions/2399

**Comment by yinkh** [comment]
thanks for your reply,I will customize this feature myself. Thanks for this powerful document tools again!

**Comment by yinkh** [comment]
I have achieve this feature,look like this:
https://user-images.githubusercontent.com/8170059/169009329-ac5acfeb-6c41-42d7-a8c6-3fd6c7c2a7e0.mp4

anyone has same requirement can ask me to post source code

**Comment by yinkh** [comment]
Source code in this [PR](https://github.com/squidfunk/mkdocs-material/pull/3936), help yourself
