### ISSUE TITLE
mkdocs-markdownextradata-plugin variables not working in navigation 

### ISSUE THREAD

**Issue by carlskii** [squidfunk/mkdocs-material#3940]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hi, Ive installed the `mkdocs-markdownextradata-plugin` (https://github.com/rosscdh/mkdocs-markdownextradata-plugin) which enables me to define some variables in my mkdocs.yaml. e.g.

```yaml
extra:
    component: 
          ca: 123
```

Which allows me to use `{{ component.ca }}` in my markdown.

Whilst this woks perfectly across the site in the content areas, its not working for the dynamic navigation helpers. e.g. 

In the header:

<img width="1385" alt="Screenshot 2022-05-20 at 10 58 33" src="https://user-images.githubusercontent.com/555399/169504500-f678b9a9-8536-4056-b1ec-1eaac972018f.png">

and in the footer:

<img width="1393" alt="Screenshot 2022-05-20 at 10 59 40" src="https://user-images.githubusercontent.com/555399/169504646-09291e36-bb11-43b4-b1b5-075b0dca525c.png">

### Expected behaviour

Should render the value of {{  component.ca  }}

### Actual behaviour

Render {{  component.ca  }}

### Steps to reproduce

Defined the `{{  component.ca  }}` in mkdocs.yaml
Specified the variable in the page heading. e.g. `About  {{  component.ca  }}`

### Package versions

 Python 3.8.9
 mkdocs, version 1.3.0 

Using pipenv:

`pipenv graph | grep mkdocs-material`

mkdocs-material==8.2.15+insiders.4.15.1 mkdocs-material-extensions [required: >=1.0.3, installed: 1.0.3]

### Configuration

```yaml
extra:
    component: 
          ca: 123
```

### System information

MACOS 12.4
Chrome & Safari

**Comment by squidfunk** [comment]
Thanks for reporting. However, this is not an issue specific to Material for MkDocs, and it's not a plugin we officially support. Please report this to the author of the plugin.
