### ISSUE TITLE
Provide a way to hide footer nav on specific pages

### ISSUE THREAD

**Issue by haseebrabbani** [squidfunk/mkdocs-material#3954]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

On the landing page of my docs site, I would like to be able to hide the footer navigation (i.e. previous and next buttons). I would expect this to work similarly as hiding table of contents or sidebar navigation for specific pages e.g.
```
hide:
  - toc
  - navigation
  - footer-navigation
```

### Use Cases

Since the landing page is a jumping point to specific parts of the website, disabling the footer navigation would reduce confusion about where to click

**Comment by haseebrabbani** [comment]
I have tried following your example here: https://github.com/squidfunk/mkdocs-material/blob/master/src/overrides/home.html
by setting the `md-footer__inner` display attribute to none, but this css does not seem to appear in the rendered page

**Comment by haseebrabbani** [comment]
okay figured out that I need to specify the `template` meta attribute at the top of the landing page to get it to read my home.html override template. still would be nice to have a simpler way to hide the footer navigation using the `hide` meta attribute

**Comment by squidfunk** [comment]
This was requested quite a few times, so I think we can finally add this functionality.

**Comment by squidfunk** [comment]
Released as part of 8.3.0!
