### ISSUE TITLE
Enable animations only of code annotations that are visible

### ISSUE THREAD

**Issue by polakowo** [squidfunk/mkdocs-material#3957]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

A high amount of code annotations may cause high CPU usage because of constant style recalculations and rendering. This can be mitigated by showing animations only of code annotations that are visible in the viewport.

### Use Cases

Reduce CPU usage. 

### Screenshots / Mockups

<img width="1440" alt="Screen Shot 2022-05-24 at 13 06 06" src="https://user-images.githubusercontent.com/2664108/170580807-1f2873c8-e543-40b9-8dde-e5e5b2ede41d.png">

**Comment by squidfunk** [comment]
Thanks for suggesting! Fixed in 5e442eb. This is actually a great optimization that was almost trivial to achieve.

**Comment by squidfunk** [comment]
Released as part of 8.2.16.
