### ISSUE TITLE
Make it possible to link to specific content tabs

### ISSUE THREAD

**Issue by abrennan89** [squidfunk/mkdocs-material#3976]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Exactly what it says on the title. I'm not sure what other info I can provide.

### Use Cases

Would be useful for cases where a procedure is different for different platforms and someone wants to link to the procedure for a specific platform in another place in the docs.

**Comment by Ultra-Instinct-05** [comment]
Relevant discussion https://github.com/squidfunk/mkdocs-material/discussions/3833

My main use case, when I requested this feature was that, I have a directory structure in one tab and there are other tabs in the same tab set, that represent files in the said directory structure. I could just make file names as links and clicking them would focus on the particular tab that represents that file.

**Comment by squidfunk** [comment]
Support for content tab anchor links has been added in [`8fd7161`](https://github.com/squidfunk/mkdocs-material-insiders/commit/8fd7161f58bab6cbccf379d8283d5da7ebeb81a9) and will be included in the next Insiders release!

__Features added__

- Create internal links for content tabs
- Open content tabs in new windows
- Copy link address from content tab

If JavaScript is disabled, the browser will _at least_ jump to the tab container, but will not switch to the targetted content tab. This does not apply to slow connections – everything works nicely, even on bad 3G.

__Demo__

https://user-images.githubusercontent.com/932156/171995664-64a28ff9-8100-4ccc-8bdc-d3685fade473.mp4

**Comment by squidfunk** [comment]
You can try it on the official docs, as they're built with Insiders, e.g.:
https://squidfunk.github.io/mkdocs-material/publishing-your-site/#__tabbed_1_2

**Comment by squidfunk** [comment]
Released as part of 8.3.1+insiders-4.17.0.
