### ISSUE TITLE
Upcoming price change for Insiders

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#3986]
> **Note** – __This only applies to new sponsorships starting after August 31, 2022__ – If you're already a sponsor, you're not affected. You will keep your access for $10+/month for the entire time of your sponsorship. Nothing changes.

__As of September 1, 2022, eligibility for the Insiders program will start at $15/month__ (currently $10/month)

When I started the Insiders program, the main motivation for choosing $10/month as an entry-level amount was to make it possible for everybody to afford it. This decision was made in May 2020, more than two years ago. During this time, no changes have been made and the price was kept constant. I believe that $15/month still fulfills that goal. Lately, I thought on and off about increasing the price, and came to the conclusion that it is the right choice to keep the project in good shape and match its current growth for the following reasons:

- __Added value__: In 2022, Material for MkDocs is one of the most full-featured low-code documentation solutions out there. It is not proprietary. It is not [Open Core](https://goteleport.com/blog/open-core-vs-saas-business-model/). __It is Open Source__. It is not backed by a huge corporation but is largely built by a single developer. It packs a lot of functionality some of which you currently cannot find elsewhere, like for example [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations). Considering the added value of Insiders, there are currently [24 features](https://squidfunk.github.io/mkdocs-material/insiders/#whats-in-for-me), all of which I commit to maintain, keep bug-free and up-to-date + of course, everything that is in the community edition. Moreover, this list is growing every other week. So is my time which I pour into this project. I believe that $15/month is still an insanely good deal for this set of features.

- __Increased overhead__: Material for MkDocs has a lot of users. I try to triage issues and answer questions every day, and try to be as responsive as I can possibly be, helping users to achieve what they aim for. This binds more and more of my time. With more funding, I'd be able to pay somebody to help me with community and sponsor management, so I could concentrate on squashing bugs, hammering out new features, and focusing on the shape and health of the code base. After all, allowing me to focus on the product yields a significantly higher return for all users.

    _Side note: if you're interested in working with me, [please let me know](mailto:martin.donath@squidfunk.com)!_

- __Symmetry__: If you're a single developer or Open Source organization and decide to sponsor the project for $10/month to get access to Insiders, you're awesome. If you're a multi-billion dollar company, binding my time via dozens of emails in advance, because "processes", which I all answer happily, and then sponsor for $10/month – it leaves a bitter taste. If you're using my software commercially, and want to make sure that it stays healthy and in good shape, your company should support the project financially. I mean, think about it: as a company, you're relying on my work, possibly for your front-facing developer platform with hundreds of thousands of users a month. If you'd hire a developer to build something with the same power as Material for MkDocs, you'd probably have to invest north of $100k+. Be fair.

The following changes will be made:

- __$15/month – The supporter__ (previously $10, minimum amount for access to Insiders)
- __$35/month – The generous supporter__ (previously $25/month)
- __$125/month – The organization__ (previously $100/month)

I'm very aware that this might be considered an unpopular move. After all, raising prices is never something that is met with applause. However, I hope that my reasoning makes sense, and want to stress again that all existing sponsors will not be affected. If you want to lock in the $10/month (or $100/month as a corporation), just sponsor before September 1, 2022.

__I'm here to answer any questions or concerns!__

**Comment by Ultra-Instinct-05** [comment]
Thanks for keeping access to those individuals who are already sponsoring for $10/month (me included). I know prices are on the rise and it must really suck to keep all those nice Insider features for as low as $10, but what made me sponsor in the first place was the ability to access at $10 (which I know is a low amount, but when you have other monthly personal budgets and write not for profit docs, it really constrains you). 

Thanks once again for your work on this awesome tool !
