### ISSUE TITLE
Click on Logo/Title without Github-Repository: "None"

### ISSUE THREAD

**Issue by sebastian-marinescu** [squidfunk/mkdocs-material#4]
Hi @squidfunk, first of all: Very good job! I like your theme very much. 

I'm writing a manual right now and tried mkDocs with your theme.
It works good, but I had some unexpected behavior: 

When not provided with a _repo_url_, the logo/title are linked to literally: "None".
My expectation is, that it links to the root: "/".

What do you think about this? 
Kind regards, Sebastian

**Comment by squidfunk** [comment]
Good idea, haven't thought about the non-repo case yet, as I only use it for my coding projects ;-) I think from a semantic aspect your idea is great, so I will provide a fix for master and pack it into 0.1.3.

**Comment by sebastian-marinescu** [comment]
Very nice, you also fixed the JS-error by this :+1: Thanks!
