### ISSUE TITLE
Feature request: breadcrumbs in the header

### ISSUE THREAD

**Issue by JobLeonard** [squidfunk/mkdocs-material#40]
I came across this when navigating [the `Plots.jl` website](https://juliaplots.github.io/examples/pyplot/) and clicked on "Examples" expecting it to take me back to the main site:

![](https://cloud.githubusercontent.com/assets/259840/17133422/404cd4f6-5326-11e6-8ac6-13a75c92b10a.png)

Since I couldn't I opened an issue, https://github.com/tbreloff/Plots.jl/issues/417 after which Tom Breloff pointed me in this direction.

I can understand that breadcrumbs are a bit of a non-feature on a mobile theme, since they take up precious horizontal space. However, if they could be collapsible, like the hamburger menu, then it would make the resulting website easier to navigate on desktops without having to compromise.

**Comment by squidfunk** [comment]
Will be changed in 1.0.0 to the behavior you stated. On mobile, however, there will be no breadcrumbs, but only the last layer.

**Comment by JobLeonard** [comment]
Great, thanks!

**Comment by squidfunk** [comment]
Okay, I think this is not possible, as the breadcrumbs up the hierarchy are more like folders and not pages as such. This means that for your "Examples" there is no direct content, but it is a folder which contains a set of pages with examples. I think it's not possible for MkDocs to add content to sections. Calling https://juliaplots.github.io/examples/ will lead to a 404. So I regret, it's not supported by MkDocs, so I can't do anything about it.

**Comment by JobLeonard** [comment]
But wouldn't this be as "simple" as copying the hierarchy of the left menu bar? Thus making the greyed out non-links (like examples) greyed out non-links in the breadcrumbs as well?

**Comment by squidfunk** [comment]
But it's just like that at the moment? Or are you now talking about this:

> I can understand that breadcrumbs are a bit of a non-feature on a mobile theme, since they take up precious horizontal space. However, if they could be collapsible, like the hamburger menu, then it would make the resulting website easier to navigate on desktops without having to compromise.

Because this does not make any sense, when the sections/links themselves aren't clickable.

**Comment by JobLeonard** [comment]
Oh right, I'm being an idiot (it's been so long since I opened the issue and I only read your closing comment). Yeah I see what you mean now.

**Comment by squidfunk** [comment]
No worries. So regretfully, we cannot change anything about it, as long as MkDocs isn't able to define content on sections.

**Comment by JasParkety** [comment]
Hello all,  this is my first comment here on github, so many thx to squidfunk for the nice template, I really enjoyed working with it so far.

My solution was very simple, but with no Jinja2 experience it was also quiet painfully. 
I created several scripts to move from gitbook to mkdocs but leaving both available for my colleagues as well. PM me if you need a script (from SUMMARY.md to mkdocs.yml) I'll probably upload them in the next couple of weeks in my repo.

During this process I always needed one Introduction link after a header was collapsible in the primary navigation. Due to this fact I could use the following snippet in my base.html to include breadcrumbs:

This will simply take the **link of the first element in the sub nav** located in the current collapsed navigation block.
```
<main class="md-main">
<div class="md-main__inner md-grid" data-md-component="container">
<!-- BREAD CRUMBS -->

          <div class="md-sticky-container">
                  <div class="md-sticky-container stickynav">
                      <div class="sticky-content">
                           {% block site_name %}
                           {% if page %}
                                 <a class="underline" href="http://www.yourHomeAdress.com">Home</a> /
                                 <a class="underline" href="{{ base_url }}">Documentation</a> /
                                         {% for parent in page.ancestors %}
                                                 <a href="{{ base_url }}/{{ (parent.children | first).input_path[:-3] }}">{{ parent.title }}</a>/

                                          {% endfor %}
                                 <div class="BreadCrumbsColor">
                                 {{ page.title | default(config.site_name, true) }}
                                 </div>
                    {% endif %}
                    {% endblock %}
          </div>
     </div>
</div>
```
