### ISSUE TITLE
Search in uneven with its results

### ISSUE THREAD

**Issue by wyaadarsh** [squidfunk/mkdocs-material#405]
## Description

Taking the example of the website [https://squidfunk.github.io/mkdocs-material/contributing/](https://squidfunk.github.io/mkdocs-material/contributing/), clicking on search and searching for keyword problem. When I type pr, it gives one result. When I type pro : Shows no result found. When I write the complete text, it gives 3 matching documents.

### Expected behavior

I expect it to give the search result on partial word match as well like the one we get here : [http://www.mkdocs.org/](http://www.mkdocs.org/)

### Package versions

* Python:  Python 2.7.10
* MkDocs: mkdocs, version 0.16.3

**Comment by squidfunk** [comment]
MkDocs is actually very much the same, e.g. search for "themes".

**Comment by squidfunk** [comment]
I improved search matching and highlighting in #409 which will be released with 1.7.5 shortly.
