### ISSUE TITLE
style for inline line numbers

### ISSUE THREAD

**Issue by 2bndy5** [squidfunk/mkdocs-material#4061]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Superfences offers an `inline` setting to their config for `linenums_style`. This renders without the expected styling:
![image](https://user-images.githubusercontent.com/14963867/175819632-a96efe9b-0b82-475b-9e07-22eb300ecb04.png)
whereas the expected style for line numbers renders properly with the `table` or `pymdownx-inline`  settings:
![image](https://user-images.githubusercontent.com/14963867/175819750-35582e86-4fd7-4a10-9860-4cde472988b6.png)

I understand there may be other implications to using inline numbers (like with clipboard.js).

### Use Cases

Accessibility standards. People with screen readers are not exposed to the line numbers when `pymdownx-inline` setting is used. They are improperly exposed to the line numbers when `table` setting is used, but screen readers announce all line numbers first then literal code after (which I imagine is annoying) because of the 1-row table that's generated.

Full disclosure: I'm hoping to take the new CSS downstream (sphinx-immaterial) because Sphinx has recently switched their default to `inline` behavior, and the `table` behavior has been deprecated for accessibility sake.

**Comment by squidfunk** [comment]
Thanks for reporting. We support `table` and `pymdownx.inline`, [as per our documentation](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight-linenums-style). `inline` is not supported, as it renders copy-to-clipboard unusable. Thus, this will not be implemented, but you can add the necessary CSS yourself.

We could and should improve the accessibility of `pymdownx.inline`; possibly via `aria-*` attributes. If you feel that this is a good idea, you might create an issue upstream over at Python Markdown Extensions.
