### ISSUE TITLE
Navigation pane scrolling not possible for some sections

### ISSUE THREAD

**Issue by ashlymat** [squidfunk/mkdocs-material#4070]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Our documentation is a collection of md files and we notice that for some sections , the scrolling bar in the navigation pane disappears. When scrolled only main page is scrolling.

### Expected behaviour

User should be able to scroll navigation pane for all sections

### Actual behaviour

The navigation pane is enabled for some sections:
<img width="1053" alt="Screenshot 2022-06-27 at 11 41 30" src="https://user-images.githubusercontent.com/34083520/175911785-a3eb8eaf-a0e5-482c-ac2e-9b527c035e53.png">

while it is disabled and not scrollable for some sections:
<img width="1074" alt="Screenshot 2022-06-27 at 11 42 39" src="https://user-images.githubusercontent.com/34083520/175912268-59afb00d-86c4-4221-8fee-4db41a014bd7.png">

### Steps to reproduce

1.  Go to our documentation https://www.project-piper.io
2. Click on section "Library Steps"
3.  Click on the step "abapEnvironmentAssemblePackages"
4.  Try to scroll left pane to look for more steps below it
5. This will scroll only the main page but not the navigation pane

Note: This is seen to happen for most of the steps and the only way to come out is to click on other sections (For eg., Extensibility section) and come back to "Library steps".
Also this does not seem to happen for other sections or some sections inside "Library steps"

The only difference I see is with respect to TOC. The sections which are not working seem to have lot of TOC.

### Package versions

- Python: 3.10.5
- MkDocs: 1.3.0
- Material: 8.3.6

### Configuration

```yaml
https://github.com/SAP/jenkins-library/blob/master/documentation/mkdocs.yml
```

### System information

- Operating system: Mac OS
- Browser: Safari

**Comment by squidfunk** [comment]
Thanks for reporting. What you're observing is a symptom of Material for MkDocs not being able to fully initialize. You're using an outdated tab syntax. When migrating to a new major version, please always check the migration guide and make sure to apply all necessary changes, respectively [this one](https://squidfunk.github.io/mkdocs-material/upgrade/#pymdownxtabbed).

<img width="621" alt="Bildschirmfoto 2022-06-27 um 12 15 37" src="https://user-images.githubusercontent.com/932156/175918943-8c0d552c-b4b8-4364-ba0f-1afa7529b931.png">
