### ISSUE TITLE
Make scrollbars brighter on dark mode

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#4073]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

![s](https://user-images.githubusercontent.com/9677399/176236357-3ea9683b-8bf7-4671-a407-eced9e9b1aba.PNG)

### Use Cases

So they are easier to see

**Comment by squidfunk** [comment]
I'm not seeing it on Chrome. Please provide more information, i.e. which browser you're using etc., etc...

![screenshot-squidfunk-github-io-mkdocs-material-setup-changing-the-colors-1656435941310](https://user-images.githubusercontent.com/932156/176241597-5de5aa15-7497-49e6-9df1-1c5ff0ed4a08.png)
