### ISSUE TITLE
Formatting lost in <details> tag

### ISSUE THREAD

**Issue by valhuber** [squidfunk/mkdocs-material#4084]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I love your product... thanks!

Sorry, I do not understand the first "checkpoint" regarding mkdocs or readthedocs.  I have never used them.

I have docs with details tags like this

```
<details>

<summary>Tests - and their logic - are transparent.. click to see Logic</summary>


&nbsp;
&nbsp;


**Logic Doc** for scenario: Good Order Custom Service
   
We place an Order with an Order Detail.  It's one transaction.

```

</details>

They work fine in [standard wiki](https://github.com/valhuber/ApiLogicServer/wiki/Logic:-Tutorial#scenario-good-order-custom-service), but lose the formatting in [material-docs](https://valhuber.github.io/ApiLogicServer/Behave-Logic-Report/#scenario-good-order-custom-service).

The wiki link fails badly to take you to the right spot, but this is how that section of the page should look:
<img width="1353" alt="details formatting on wiki" src="https://user-images.githubusercontent.com/5579631/177060801-ce168dd5-aed2-4564-92f2-49b9b005bd81.png">

And this is how it looks in materials-docs:

<img width="1353" alt="details formatiing on material-docs" src="https://user-images.githubusercontent.com/5579631/177060904-26246276-6bdd-4fb6-ba4f-85fef0686ca6.png">

### Expected behaviour

Should preserve formatting - bold, dot points, paragraphs etc.

### Actual behaviour

Such formatting is lost

### Steps to reproduce

See the code above, which is the same on wiki/material-docs sites.

### Package versions

- Python: `python --version` 

3.10.5

- MkDocs: `mkdocs --version`

mkdocs, version 1.3.0 from /Users/val/dev/Docs.AplLogicServer/venv/lib/python3.10/site-packages/mkdocs (Python 3.10)

- Material: `pip show mkdocs-material | grep -E ^Version`

Version: 8.3.8

### Configuration

```yaml
https://github.com/valhuber/ApiLogicServer

https://valhuber.github.io/ApiLogicServer/

I am using (I believe, tho a noobie) standards for

* docs folder
* mkdocs.yaml
```

### System information

- Operating system: ... 12.4
- Browser: Firefox 102.0

**Comment by facelessuser** [comment]
This is probably because the content under the block tag `<details>` is not parsed as Markdown unless the user enables the  [`md_in_hmtl`](https://python-markdown.github.io/extensions/md_in_html/) extension.

**Comment by squidfunk** [comment]
Thanks for reporting. You can either use [`md_in_html`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html), or [`pymdownx.details`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details) to render [collapsible blocks](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks), which are implemented with `details` elements:

with `md_in_html`:

``` html
<details markdown>
  <summary>Title</summary>
  Content
</details>
```

with `pymdownx.details`:

``` html
??? note "Title"

    Content <!-- All content indented by four spaces -->
```

**Comment by squidfunk** [comment]
> Sorry, I do not understand the first "checkpoint" regarding mkdocs or readthedocs. I have never used them.

I'm in the process of reworking the entire issue-reporting process, as this is one of the things several users are having problems understanding, so no worries.

**Comment by valhuber** [comment]
Thanks, guys... the `md_in_html` worked great.  Took me a minute to note the \<details **markdown**\>, but then fine.

If you need a reference for your project, happy to help.  It has made a spectacular change to the docs... not just visual, but it enables me to communicate the "big picture" using the combination of navigation + table of contents.

Finally, if you are database folks and have a few moments, I'd love to get your reaction to [API Logic Server](https://valhuber.github.io/ApiLogicServer/) - the doc, and the product.

You can close this issue...
