### ISSUE TITLE
[`tags` plugin] Feature suggestion: default tags file for subdirectories

### ISSUE THREAD

**Issue by scarf005** [squidfunk/mkdocs-material#4094]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

currently `tags` plugin only allows setting up tags as front matter on markdown document.
however many files may share same tags, so something like `_tags.yml` inside subdirectory that defines shared tags would be great.

### Use Cases

an example of `_tags.yml` in `docs/python/` subdirectory: 
```yaml
tags:
  - python
```

aggregate those tags to `*.md` files recursively.

### Screenshots / Mockups
```yaml
docs/
  python/
    _tags.yml
    foo.md # contains tag 'python'
    bar.md # contains tag 'python'
    baz.md # contains tag 'python'
```

**Comment by squidfunk** [comment]
Thanks for suggesting. Related to #4030, should be possible to provide with the same mechanics.

**Comment by squidfunk** [comment]
[8.3.9+insiders-4.21.0](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.21.0) adds experimental support for a new plugin: the [built-in meta plugin](https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin). With this plugin you can create `.meta.yml` files in your `docs` directory to define key-value pairs for front matter that should be set for all files in the surrounding folder and nested folders. The primary use cases for which this was designed, but to which it is not limited are:

1. [Templates](https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-template)
2. [Tags](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#adding-tags)

Check both pages for usage examples (green admonition).

**Comment by bew** [comment]
Thank you for this!
For tags, is it possible to add tags in specific pages? (in addition to the ones in a `.meta.yml`)
Or do we need to re-specify all tags when trying to add page-specific tags?

**Comment by squidfunk** [comment]
Of course. You can define tags for a specific page as usual. The default tags are _merged_ with the tags you define for a page. We should clarify this in the documentation 😊

**Comment by squidfunk** [comment]
Updated the documentation in 0f8d013fe.
