### ISSUE TITLE
Zoom-In Image

### ISSUE THREAD

**Issue by jimlyas** [squidfunk/mkdocs-material#4096]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

It would be nice if we have an image, and we click on it then the image will become larger like a dialog to see it better.

### Use Cases

When we have image of diagram, the more complicated it gets, it's getting harder to read it.

So it would be nice if we can click the image the the page will load the image as something like dialog to see the image better and bigger.

### Screenshots / Mockups

Something like this:

![image](https://user-images.githubusercontent.com/33854739/177518682-0011dae2-ba63-4de9-b9fa-310b019f9d80.png)

**Comment by squidfunk** [comment]
Thanks for suggesting! There are several image zoom (more commonly known as _lightbox_) solutions available which can be added to Material for MkDocs. I currently have no plans to add this functionality to the core, as extension is super simple.

This one by @blueswen looks pretty good:
https://blueswen.github.io/mkdocs-glightbox/

__Related__

- #2137
- #1635

**Comment by EDIflyer** [comment]
@squidfunk ooh great link - just installed @blueswen's one and it works brilliantly (including on mobile) 👍👍

**Comment by squidfunk** [comment]
Perfect! @blueswen if you like, we can include your plugin as a recommendation in the images documentation, as this is something that has been asked quite a few times. If you wish to do that, a PR is appreciated!

**Comment by blueswen** [comment]
@squidfunk That would be great! I also noticed the vanishing issue too. I will send a PR after solve the vanishing issue.
