### ISSUE TITLE
Syntax Hightlighting

### ISSUE THREAD

**Issue by Fuzzyma** [squidfunk/mkdocs-material#41]
It would be awesome to have syntax hightlighting in the code blocks.
If not always then at least configurable in the settings.

Thx for the great theme!

**Comment by squidfunk** [comment]
There should be. Have you activated the codehilite extension? 

``` yaml
markdown_extensions:
  - codehilite(css_class=code)
```

**Comment by Fuzzyma** [comment]
Oh - didnt know that this is needed. It worked without this option with a normal theme.
Thanks!!

**Comment by squidfunk** [comment]
The other themes use JavaScript-based Syntax Highlighting. I have it on my internal list for the next release as a fallback, if codehilite is not installed.
