### ISSUE TITLE
code blocks copy one extra line executing in linux terminal

### ISSUE THREAD

**Issue by csantanapr** [squidfunk/mkdocs-material#4115]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When a user clicks the copy icon from a [code block](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#usage)  and then paste on a terminal window on Linux the commands get executed immediately.

This is not the desired behavior from various users complaining about the same problem. 
They just want to paste the line(s) they don't want to execute the command 
I did some testing and this happens on Linux terminal and not on macOS terminal including iTerm.

For example the command `pip install mkdocs-material` from the [getting started](https://squidfunk.github.io/mkdocs-material/getting-started/#installation) 

### Expected behaviour

If the code block has one line, when you paste it copies one line without executing the command. 
This is also the same behavior if you using code blocks on Github.com using the 3 backticks

### Actual behaviour

It executes the command instead of just pasting.

I notice if you paste it into a code editor it copies an extra line.
![image](https://user-images.githubusercontent.com/1094878/178351697-337ca949-2704-48d5-96f4-aa03c167b5c4.png)

### Steps to reproduce

To reproduce click the copy icon from the mkdocs-material getting started,
For example the command `pip install mkdocs-material` from the [getting started](https://squidfunk.github.io/mkdocs-material/getting-started/#installation) 

then run on ubuntu using terminal sh, you can do this with docker
```
❯ docker run --rm -it ubuntu sh
# pip install mkdocs-material
sh: 1: pip: not found
#
```

### Package versions

Not applicable

### Configuration

```yaml
Not applicable
```

### System information

Not applicable

**Comment by squidfunk** [comment]
Thanks for reporting. Please take this upstream to [Clipboard.js](https://github.com/zenorocha/clipboard.js), which is the library we're using for providing the copy-to-clipboard functionality. There might also already be an issue describing the problem.

**Comment by MartinKolbAtWork** [comment]
Hi @squidfunk ,
I have the same issue, and when analyzing the problem, I found that Clipboard.js is doing perfectly fine. It takes the HTML content that is generated by MkDocs-Material and copies it to the clipboard. However, already the generated HTML content of MkDocs-Material contains the extra line feed.
So I’d be happy if you could re-open the issue and investigate how this can be fixed.
Thanks, Martin

**Comment by squidfunk** [comment]
The HTML is not generated by Material for MkDocs, but by [Pygments](https://pygments.org/) and/or [Python Markdown Extensions](https://github.com/facelessuser/pymdown-extensions). Please check whether this also happens with another theme than `material`, i.e. `mkdocs` or `readthedocs`. If it does, it's definitely an upstream issue.

**Comment by AaronMingCN** [comment]
Try this
```yml

  - pymdownx.highlight: #
      anchor_linenums: true
      # line_spans: __span #  <--------- Don't use line_spans
      pygments_lang_class: true
```

**Comment by squidfunk** [comment]
@AaronMingCN it might be useful to raise this to [Python Markdown Extensions](https://github.com/facelessuser/pymdown-extensions), if you can spare a few minutes.
