### ISSUE TITLE
Breaking change in color logic?

### ISSUE THREAD

**Issue by do-me** [squidfunk/mkdocs-material#4116]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

In my project, I defined a new primary color in `extra.css`

```
:root {
  --md-primary-fg-color:        #484c5a;
}
```
Worked fine until a couple of weeks ago. I just ran an update on mkdocs-material (latest release) and now this root color is ignored. 

Turns out another color scheme `default` is overwriting my root. 

![image](https://user-images.githubusercontent.com/47481567/178463204-18fa40a3-120d-48b2-aba0-e17643a6289b.png)

I fixed it with by adding 

```
[data-md-color-scheme="default"] {
  --md-primary-fg-color:        #484c5a;
}
```

Is this some breaking change I missed or was this my fault (in this case sorry for bothering)?

If needed see the [repo](https://github.com/gbconsite/MultiRoute-Tour) for reproduction. I'm happy to help in case!

### Expected behaviour

Use root colors.

### Actual behaviour

Not using root colors but default colors.

### Steps to reproduce

Clone repo from above and change mentioned lines in `extra.css`.

### Package versions

- Python: >Python 3.7.5
- MkDocs: 1.3.0
- Material: 8.3.9

### Configuration

```yaml
site_name: Test
extra_css:
        - stylesheets/extra.css
```

### System information

- Operating system: Windows and Ubuntu 20.04
- Browser: All

**Comment by squidfunk** [comment]
Thanks for reporting. [Please use](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors):

``` css
:root > * {
  --md-primary-fg-color:        #484c5a;
}
```

**Comment by do-me** [comment]
Working, thanks a lot!
