### ISSUE TITLE
Update docker image to work with newer versions of git

### ISSUE THREAD

**Issue by timvink** [squidfunk/mkdocs-material#4117]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Newer versions of `git` introduce some security fixes that lead to new behaviour.

Using the `mkdocs-material` Docker image with any plugin that uses `git`, like so:

```Dockerfile
# Dockerfile
FROM squidfunk/mkdocs-material
RUN pip install mkdocs-git-revision-date-localized-plugin
```

Will give an error like:

```
stderr: 'fatal: unsafe repository ('/docs' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /docs'
```

The solution is also simple, to update the `Dockerfile` to:

```Dockerfile
FROM squidfunk/mkdocs-material
RUN pip install mkdocs-git-revision-date-localized-plugin
RUN git config --global --add safe.directory /docs
```

More details can be found in https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/92

### Expected behaviour

I would like users to have a working docker image immediately. 

Either by:

1) Updating the Docker image documentation on `mkdocs-material` and all git-based plugins, or
2) Update the `mkdocs-material` Docker base image with a `RUN git config --global --add safe.directory /docs` line.

Happy to provide a PR, let me know.

### Actual behaviour

docker build fails

### Steps to reproduce

Steps to reproduce are in https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/92 

### Package versions

`FROM squidfunk/mkdocs-material:latest` 

### Configuration

```yaml
theme:
  name: 'material'

site_name: My Docs

plugins:
  - search
  - git-revision-date-localized
```

### System information

- Operating system: linux
- Browser: chrome

**Comment by squidfunk** [comment]
Thanks for reporting. PR appreciated!
