### ISSUE TITLE
Search broken in 8.3.9: "o.reduce is not a function"

### ISSUE THREAD

**Issue by decentral1se** [squidfunk/mkdocs-material#4140]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Following https://github.com/mkdocs/mkdocs/issues/2869. Search is still broken on our install. When the page loads, I see this error: `TypeError: o.reduce is not a function ... search.b97dbffb.min.js:46:2967`. It still says it is initialising... our config is open on https://git.coopcloud.tech/coop-cloud/docs.coopcloud.tech. Thanks in advance!

### Expected behaviour

Search works.

### Actual behaviour

Search doesn't work.

### Steps to reproduce

1. Try to search anything on https://docs.coopcloud.tech

### Package versions

- Docker: `squidfunk/mkdocs-material:8.3.9`

### Configuration

```yaml
https://git.coopcloud.tech/coop-cloud/docs.coopcloud.tech/src/branch/main/mkdocs.yml
```

### System information

- Operating system: debian 11
- Browser: firefox esr

**Comment by squidfunk** [comment]
Thanks for reporting. Please provide a minimal reproducible example so I can look into it. Try to narrow it down by removing documents from your site until you find what is causing the issue.

**Comment by decentral1se** [comment]
Ah, it was a missing `title: ...` in a file... thanks, i just starting removing stuff slowly...

https://git.coopcloud.tech/coop-cloud/docs.coopcloud.tech/commit/0b4b84d892f9eb25a34017bea5717d753ee4069f

a warning of some sort would be nice! closing this off for now, thanks again.

**Comment by squidfunk** [comment]
Thanks for taking the time. As I said, if you can provide a reproducible example, we can see how we can handle this error.

**Comment by jicowan** [comment]
I had the same issue with 8.3.9. Some of my documents had "tags". Once I removed the tags search started working again.

**Comment by squidfunk** [comment]
Thanks. Again: a reproducible example or I'm not able to help...

**Comment by jicowan** [comment]
@squidfunk I don't know if this was the root cause, but I had 3 markdown files that started with the following: 
```
---
tags: cost_optimization
---
```
when I removed that metadata from the files, search started working again.

**Comment by squidfunk** [comment]
Thanks. This is invalid syntax, and a warning should be printed when running `mkdocs build`. Tags must be provided as a list:

```
tags:
  - foo
  - bar
```
