### ISSUE TITLE
Docker Hub readme Quick Start section has malformed code blocks for commands

### ISSUE THREAD

**Issue by carlin-q-scott** [squidfunk/mkdocs-material#4147]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

Docker Hub readme Quick Start section has malformed code blocks for commands:
![image](https://user-images.githubusercontent.com/2521644/180035503-10e01dd6-2a1e-4053-86b5-006dadb41fcf.png)

### Expected behaviour

I expected to see commands in code or quote blocks.

### Actual behaviour

I see commands after empty code blocks.

### Steps to reproduce

1. Navigate to https://hub.docker.com/r/squidfunk/mkdocs-material

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
Not applicable
```

### System information

- Operating system: Windows
- Browser: Edge

**Comment by squidfunk** [comment]
Thanks for reporting. Fixed:

<img width="1229" alt="Bildschirmfoto 2022-07-20 um 21 37 27" src="https://user-images.githubusercontent.com/932156/180067270-f5353273-e978-4442-bc3f-e24c130cbd13.png">
