### ISSUE TITLE
Search page functionality

### ISSUE THREAD

**Issue by wyaadarsh** [squidfunk/mkdocs-material#415]
## Description

Search page functionality 

### Expected behavior

When we are typing, auto suggestions are there in search but on clicking enter, the control is returned from the search. But thinking of a case when we have 100 matching results for something. Hence, I wanted a functionality that on pressing enter, a search page is displayed with all the results. Is this functionality on the roadmap? How can I add it on my own as my knowledge base is very much dependent on this feature. 

Thanks

**Comment by squidfunk** [comment]
See #387

**Comment by squidfunk** [comment]
Closing this, and there is no plan to include this.
