### ISSUE TITLE
Move search bar to the side navbar: result box doesn't display

### ISSUE THREAD

**Issue by arnaudbreton** [squidfunk/mkdocs-material#416]
## Description
Hi, 

First of all, thanks for the great work on this theme, really well done!

I'm trying to customise the theme to fit our own requirements and visual guidelines. So far, so good.

I'm trying to move the search bar from the header to the side navbar, so I did the following in `custom_theme/material/partials/nav.html`:

```html
... 
LICENSE
...

<!-- Button to open search dialogue -->
<div class="md-flex__cell md-flex__cell--shrink">
 {% block search_box %}
   <label class="md-icon md-icon--search md-header-nav__button"
       for="search"></label>

   <!-- Search interface -->
   {% include "partials/search.html" %}
 {% endblock %}
</div>

<!-- Main navigation -->
<nav class="md-nav md-nav--primary" data-md-level="0">

  <label class="md-nav__title md-nav__title--site" for="drawer">
    {% if config.extra.logo %}
      <i class="md-logo md-nav__button">
        <img src="{{ base_url }}/{{ config.extra.logo }}" />
      </i>
    {% else %}
      <i class="md-icon md-icon--home md-nav__button"></i>
    {% endif %}
    {{ config.site_name }}
  </label>

  <!-- Repository containing source -->
  {% if config.repo_url %}
    <div class="md-nav__source">
      {% include "partials/source.html" %}
    </div>
  {% endif %}

  <!-- Render item list -->
  <ul class="md-nav__list" data-md-scrollfix>
    {% for nav_item in nav %}
      {% set path = "nav-" + loop.index | string %}
      {% set level = 1 %}
      {% include "partials/nav-item.html" %}
    {% endfor %}
  </ul>
</nav>
```

Basically, I've copied the HTML which is originally in `header.html` to `nav.html`. 

### Expected behavior

The result box to be displayed.

### Actual behavior

The search box displays well but when I input some text, the result box doesn't show up. I see in the DOM that it's well populated with results but a reason I cannot identify yet, it won't display. I suspected so overflow on the sidebar, but changing that doesn't make the box to show up.

### Package versions

* Python: Python 3.6.1
* MkDocs: version 0.16.3
* Material: 1.7.5

### System information

* OS: OSX Sierra
* Browser: Chrome

Hope it makes sense, thanks for your help!

**Comment by squidfunk** [comment]
Well that's really hard to say without seeing the code. In general I cannot support customization as there are probably millions of possible configurations and my time is very limited, so I try to solve problems that impact the theme as it is. I hope you understand this.

**Comment by arnaudbreton** [comment]
Hey @squidfunk, thanks for the quick feedback appreciated. I totally understand you have limited bandwidth.

Could it help if I send you the HTML mkdocs generate in my environment? I could also create a project from scratch and do just that, to see if it's related to my changes. I didn't change so much for now (few CSS, and removing some blocks in header, footer). 

Thanks again

**Comment by squidfunk** [comment]
I could take a very quick look if it's online, but I cannot set up some environment or something.

**Comment by arnaudbreton** [comment]
OK, I'll try to set something up. Thanks again for your help

**Comment by arnaudbreton** [comment]
I've just invited you to a private repository. The docs is deployed on Github pages there and the repo contains the mkdocs. Thanks again for your help!

**Comment by squidfunk** [comment]
I'm sorry but I don't see the invitation.

**Comment by squidfunk** [comment]
``` css
@media only screen and (min-width: 60em)
  .md-search__scrollwrap {
    max-height: 0
  }
```

This is the problem and all I can do for you, I'm sorry. I just cannot invest time to fix issues with customization.

**Comment by arnaudbreton** [comment]
Thanks @squidfunk for having taken a look, I'll look into that!

**Comment by arnaudbreton** [comment]
After digging deeper in the code and based on your help, I finally found a way to make it work.

Basically, the root cause was that all related CSS rules which enable to result box to show up where tied to the header. I've updated them to work with the main container `md-container` instead. Also, I had to remove the `overflow: hidden` rules on the sidebar. So far, I didn't spot any issue. The following rules are enough to make it work:

```
+
+  .md-sidebar, .md-sidebar__scrollwrap  {
+    overflow: visible;
+  }
+
   .md-header-nav__button.md-icon--menu {
     display: none;
   }
+
+  [data-md-toggle=search]:checked~.md-container .md-search__output {
+      box-shadow: 0 6px 10px 0 rgba(0,0,0,.14), 0 1px 18px 0 rgba(0,0,0,.12), 0 3px 5px -1px rgba(0,0,0,.4);
+      opacity: 1;
+      overflow: visible;
+      width: auto;
+  }
+
+  [data-md-toggle=search]:checked~.md-container .md-search__overlay {
+    width: 100%;
+    height: 100%;
+    transition: width 0s,height 0s,opacity .25s;
+    opacity: 1;
+  }
+
+  [data-md-toggle=search]:checked~.md-container .md-search__scrollwrap {
+      max-height: 75vh;
+  }
```

Hope it'll help! Thanks again for your time yesterday.
