### ISSUE TITLE
repo mkdocs-material-insiders.git not found ?

### ISSUE THREAD

**Issue by ArdennesEtape** [squidfunk/mkdocs-material#4162]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Hello @squidfunk 

Just got the strangest error in my CI:

```bash
$ pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
Collecting git+https://****@github.com/squidfunk/mkdocs-material-insiders.git
  Cloning https://****@github.com/squidfunk/mkdocs-material-insiders.git to /tmp/pip-req-build-za92a34j
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/squidfunk/mkdocs-material-insiders.git' /tmp/pip-req-build-za92a34j
  remote: Repository not found.
  fatal: repository 'https://github.com/squidfunk/mkdocs-material-insiders.git/' not found
  error: subprocess-exited-with-error
```

Still sponsoring the project...  
We did not change anything for months in the CI...  

very confused  
Am I missing something ?

### Expected behaviour

get the latest insiders material

### Actual behaviour

repo not found

### Steps to reproduce

this is our `.gitlab-ci.yml` 

```yml
image: python:latest
pages:
  stage: deploy
  only:
    - main
  script:
    - pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
    - pip install mkdocs-minify-plugin
    - pip install mkdocs-git-revision-date-plugin
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
```

### Package versions

n/a

### Configuration

```yaml
n/a
```

### System information

docker

**Comment by squidfunk** [comment]
Thanks for reporting. Please contact me via email at martin.donath@squidfunk.com – I believe there's something wrong with your sponsorship.
