### ISSUE TITLE
Feature suggestions: Highlight section after anchor jump

### ISSUE THREAD

**Issue by copdips** [squidfunk/mkdocs-material#4164]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Consider following example, when the title referenced is too closed to the referencing place, something we lost the focus when clicking on the reference link (#step1).
It would be nice if we can add an effet that hightlight the line `## step1` in several seconds right after we are redirected to it by clicking on the reference `(#step1)`

```md
## step1

blabla

## step2

(a ref to step1)[#step1]
```

### Use Cases

As described above, with this feature, we can easily find where we're redirected to when clicking on an inner link.

**Comment by squidfunk** [comment]
Thanks for suggesting. Might be a good addition, need to investigate.

**Comment by squidfunk** [comment]
Given the low interest among users, I'm currently not considering this for inclusion. This might change in the future.
