### ISSUE TITLE
Missing jquery and base_url not defined

### ISSUE THREAD

**Issue by nebulade** [squidfunk/mkdocs-material#418]
## Description

Using straight from current master, a `mkdocs build` generates files which show the following output in the webinspector terminal:

```
ReferenceError: $ is not defined
[Learn More]
base.js:15:1
Error: Bootstrap requires jQuery bootstrap-3.0.3.min.js:7:37
ReferenceError: base_url is not defined
[Learn More]
search.js:2:5
Error: Mismatched anonymous define() module: function (module) { 'use strict'; var text, fs, Cc, Ci, xpcIsWindows, progIds = ['Msxml2.XMLHTTP', 'Microsoft.XMLHTTP', 'Msxml2.XMLHTTP.4.0'], xmlRegExp = /^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im, bodyRegExp = /<body[^>]*>\s*([\s\S]+)\s*<\/body>/im, hasLocation = typeof location !== 'undefined' && location.href, defaultProtocol = hasLocation && location.protocol && location.protocol.replace(/\:/, ''), defaultHostName = hasLocation && location.hostname, defaultPort = hasLocation && (location.port || undefined), buildMap = {}, masterConfig = (module.config && module.config()) || {}; text = { version: '2.0.12', strip: function (content) { //Strips <?xml ...?> declarations so that external SVG and XML //documents can be added to a document without worry. Also, if the string //is an HTML docu… require.js:8:252
```

This is on both Firefox 56 and Chromium 60. Now I am not sure if this is an issue in how I attempt to use the theme and if it is my responisibility to add a jquery include, or if that is a missing dependency overall. It however does not seem to break the functionality.

### Package versions

* Python: 3.6.2
* MkDocs: 0.16.3
* Material: d204b63ee491e2163b5692d76e8ff1ad2b0430fa (master)

### Project configuration

``` yaml
site_name: Cloudon Docs
site_description: 'Cloudron is a platform to host apps on your server and keep them up-to-date and secure.'
site_url: 'https://cloudron.io'
copyright: 'Copyright &copy; 2015 - 2017 Cloudron UG'
theme_dir: 'material/'
extra_css:
  - 'stylesheets/extra.css'
extra:
  palette:
    primary: 'light blue'
    accent: 'green'
  logo: 'img/logo.svg'
```

### System information

* OS: Arch Linux

**Comment by squidfunk** [comment]
Material doesn't even include or require jQuery. Have you tried using the latest release?

**Comment by nebulade** [comment]
Ah ok this makes a lot more sense now. I had an old application build there and apparently the git repo does not contain one in the assets folder. The release tarball works as expected.
Thanks for clarification.
