### ISSUE TITLE
Adding a github link when providing repo_url

### ISSUE THREAD

**Issue by Fuzzyma** [squidfunk/mkdocs-material#42]
The mkdocs state that the repo_url setting would be used to create a github link on each page.
It would be cool, if this could be added in this theme, too! :)

**Comment by squidfunk** [comment]
There is a GitHub link on every page - the top left repository name. Actually, there is also the number of stars and a download button next to the name.

**Comment by Fuzzyma** [comment]
I found the link, but there is just the name. Nothing else.

Sorry for bothering so much with stupid questions :D

**Comment by squidfunk** [comment]
What would you expect? I'm currently working on an improved version of the theme, see https://github.com/squidfunk/mkdocs-material/issues/2#issuecomment-232503857 - there will be a GitHub icon in the footer, I guess.

**Comment by Fuzzyma** [comment]
>Actually, there is also the number of stars and a download button next to the name.

Thats what I just expected :D.
But okay - A link works for now. Looking forward to your rework!
