### ISSUE TITLE
Allow to specify a favicon using one of the bundled icons

### ISSUE THREAD

**Issue by ldeluigi** [squidfunk/mkdocs-material#4206]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

As you can see from the documentation:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#favicon
favicon are specified by using a path to an image, whereas
https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo
the logo can be specified by referring to one of the many bundled icons.

I'd like to specify the favicon like the logo, so that it can use one of the bundled icon SVGs.

This is the current support for svg icons:
https://caniuse.com/link-icon-svg

Optionally, SVG icons could:
  - be converted to png/ico on the fly
  - be inlined in the <link> tag (https://stackoverflow.com/questions/66935329/use-inline-svg-as-favicon)

### Use Cases

If a developer is fine with using one of the bundled icons as main logo, they would probably use it for the favicon too, but currently they would need to copy/paste the svg file in the right path manually.

### Screenshots / Mockups

![image](https://user-images.githubusercontent.com/44567586/182850851-cf8a6bc9-b7ab-4ce1-9302-99a8c6299696.png)

**Comment by squidfunk** [comment]
Dupliacte of #3040

**Comment by ldeluigi** [comment]
> Duplicate of #3040 and #2745

I reopened the issue because I think that you could inline the favicon, try this:
https://stackoverflow.com/questions/66935329/use-inline-svg-as-favicon

**Comment by squidfunk** [comment]
Thanks! Is this feature available in [the range of browsers we support](https://squidfunk.github.io/mkdocs-material/browser-support/#supported-browsers)?

**Comment by ldeluigi** [comment]
Based on this: https://caniuse.com/link-icon-svg
![image](https://user-images.githubusercontent.com/44567586/183382300-c7ebd95b-35f4-4aeb-ae5e-4f64638ffdbe.png)
It works everywhere except for Safari. I tested myself in Chrome for Windows and it does work.

Nevertheless, there is a simple way to [create a fallback default classic .ico favicon for those browsers](https://stackoverflow.com/a/64331293/8589004).

**Comment by squidfunk** [comment]
Thanks for checking. The problem is that we cannot automatically create the fallback icon from configuration, so we would be locking out Safari users. For this reason, it's not possible to provide this out-of-the-box, but you can use theme extension to achieve the same thing. [You can inline icon from templates](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#using-icons-in-templates).

**Comment by ldeluigi** [comment]
> Thanks for checking. The problem is that we cannot automatically create the fallback icon from configuration, so we would be locking out Safari users. For this reason, it's not possible to provide this out-of-the-box, but you can use theme extension to achieve the same thing. [You can inline icon from templates](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#using-icons-in-templates).

Thanks. For the future, I hope that Safari joins the support list and you can provide it out-of-the -box. Thanks for your work!
