### ISSUE TITLE
Github repo stars and forks component counters doesn't shows up

### ISSUE THREAD

**Issue by elvismdev** [squidfunk/mkdocs-material#421]
## Description

The Github repo stars and forks counters doesn't shows up.

### Expected behavior

I expect them to show up like in the demo and documentation page http://squidfunk.github.io/mkdocs-material/ 

![image](https://user-images.githubusercontent.com/3847077/28845407-c58d20ac-76bc-11e7-9aee-d87754adc55f.png)

### Actual behavior

Instead it comes up with the "vendor/package" slug name only, without nothing under it. Also no JS errors in the console or in the `mkdocs serve` log in my console once I run it to develop from http://127.0.0.1:8000/

![image](https://user-images.githubusercontent.com/3847077/28845531-37daf454-76bd-11e7-8e34-8d61ed0be575.png)

If I "inspect elements" and compare with the [markup from the demo](http://squidfunk.github.io/mkdocs-material/), I see this part is completely missing on my end.

```html
<ul class="md-source__facts"
    <li class="md-source__fact">621 Stars</li>
    <li class="md-source__fact">170 Forks</li>
</ul>
```

### Steps to reproduce the bug

1. Install the latest version of Material with pip: `pip install mkdocs-material`
2. Add the following line to mkdocs.yml: `theme: 'material'`
3. Run the built-in dev-server: `mkdocs serve`
4. Open up `http://127.0.0.1:8000/` in the browser

### Package versions

* Python: `Python 2.7.10`
* MkDocs: `mkdocs, version 0.16.3`
* Material: `Version: 1.7.5`

### Project configuration

``` yaml
site_name: Starter WordPress Theme
repo_url: https://github.com/vendorname/starter-wp-theme
repo_name: vendorname/starter-wp-theme
edit_uri: edit/master/docs
site_author: Elvis Morales
site_description: A WordPress starter theme.
theme: material
pages:
  - About: index.md
  - Getting Started: getting-started.md
  - Helper Functions: helper-functions.md


# Copyright
copyright: 'Copyright &copy; 2016 - 2017 Elvis Morales'


# Options
extra:
  feature:
    tabs: false
  palette:
    primary: red
    accent: red
  social:
    - type: globe
      link: https://companyname.com
    - type: github-alt
      link: https://github.com/companyname
    - type: twitter
      link: https://twitter.com/companyname
    - type: linkedin
      link: https://linkedin.com/companyname

markdown_extensions:
  - toc:
      permalink: true```

### System information

* OS: macOS Sierra 10.12.5
* Browser: Google Chrome Version 59.0.3071.115

**Comment by squidfunk** [comment]
Is there some error to see in the network inspector? It seems that the request failed.

**Comment by squidfunk** [comment]
Also try to delete the cooke which caches results and is called: `${HASH}.cache-sources`

**Comment by elvismdev** [comment]
@squidfunk I tried deleting the cookie `${HASH}.cache-source` but same result. Also any error comes up in the network inspector, all requests are 200 OK.

![image](https://user-images.githubusercontent.com/3847077/28892316-63c42746-7782-11e7-8c9f-dec16223d5da.png)

This is the repo I'm putting this documentation together: https://github.com/forumone/gesso-wp

Any other thoughts why stars and forks numbers are failing to show up?

**Comment by squidfunk** [comment]
Nope, I cannot reproduce this, it's perfectly working.

**Comment by squidfunk** [comment]
I managed to reproduce it. There a reonly 30 repos returned from the GitHub API, so we need to paginate if the repo is not found and there are more than 30.

**Comment by elvismdev** [comment]
Yes that should be it, seems like for user accounts/organizations that has more than 30 repos, if not found the repository on the first response to `api.github.com/users/orgname`, then it should paginate for more until it find's it.

Glad you were able to reproduce it!

**Comment by squidfunk** [comment]
Rather tricky figuring out to do an endless Promise chain, but managed to implement it in #429. Will release 1.8.1 shortly.

**Comment by squidfunk** [comment]
Just released 1.8.1, please re-open in case of problems.

**Comment by yks0000** [comment]
I am seeing this issue again in version 2.7.3.

**Comment by squidfunk** [comment]
Please re-open the issue and provide more information when you're seeing this. Ideally a reproducible scenario. Thanks!

**Comment by dgomesbr** [comment]
This is something that just happened to my repo, you can get rate limited by GH

**Comment by squidfunk** [comment]
GitHub requests we're refactored in v5,  so running into the rate limit should be rather unlikely.

**Comment by dgomesbr** [comment]
Thank you!

**Comment by dgomesbr** [comment]
Just to leave it here, my issue was that in a VPN most of my team was using the same IP address, so we reached the limit quickly. Loading the portal without VPN was working fine.

**Comment by rod2ik** [comment]
Hi,
I'm trying to integrate [PyScript](https://pyscript.net/) with material-mkdocs.
It works fine, but it makes the stars and forks block disapear.
Here are my configs : 

In mkdocs.yml:

```
theme:
  name: material
  custom_dir: overrides

extra_css:
    - https://pyscript.net/alpha/pyscript.css
 ```

in overrides/main.html:
```
{% extends "base.html" %}

{% block htmltitle %}
{{ super() }}
<title>{{ base_url }}</title>
{% endblock %}

{% block scripts %}
    <script defer src="https://pyscript.net/alpha/pyscript.js"></script>
{% endblock %}
```

Could we do anything to solve this ?

**Comment by squidfunk** [comment]
If you override `scripts`, you're effectively removing the entire application logic of Material for MkDocs, so there's no wonder nothing works anymore. Try _extending_ the block:

```
{% extends "main.html" %}

{% block scripts %}
  {{ super() }}
  <!-- Your overrides -->
{% endblock% }

**Comment by rod2ik** [comment]
Perfect answer (of course..). Works like a charm. Thankxx
