### ISSUE TITLE
Code block output has indication

### ISSUE THREAD

**Issue by reigHns92** [squidfunk/mkdocs-material#4219]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

Sample example in [PyTorch's Tutorial using Sphinx](https://pytorch.org/tutorials/beginner/vt_tutorial.html);

The corresponding code block has an output box, for example:

```
print("I love mkdocs")
```

out:

```
I love mkdocs
```

In `mkdocs`, I have to manually define the **out** indication for each of the code block output I have in the markdown/notebook. The closest I find is mkdocs-jupyter [here](https://pypi.org/project/mkdocs-jupyter/). Wonder if there are better ones.

Thank you for the time, I really like `mkdocs` a lot!

### Use Cases

Nowadays many tutorials include a lot code that have outputs, it may be a good idea as it reduces overhead for the author to not worry about typing **out** code block.

### Screenshots / Mockups

Sample for the feature:

<img width="543" alt="ss" src="https://user-images.githubusercontent.com/93695992/183291420-158dc9c0-b0b6-4557-a9c1-18a8ddd1c590.PNG">

**Comment by squidfunk** [comment]
Thanks for suggesting. This is a great case for a Markdown extension or MkDocs plugin. Material for MkDocs is "only" a theme, so we can only render what the Markdown pipeline gives us. It's true that we also implement some plugins, but those solve general purpose use cases. It's out of scope for us, since this is something rather provided by Jupyter or other technologies. Closing as not planned.

**Comment by reigHns92** [comment]
Thank you for the reply, noted!
