### ISSUE TITLE
Use local distributed fonts by default (instead of Google Fonts) because of DSGVO

### ISSUE THREAD

**Issue by shokinn** [squidfunk/mkdocs-material#4231]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Google Fonts are illegal to deliver in Germany due to the DSGVO.
There is a recent court case by the LG München ([Az. 3 O 17493/20](https://www.gesetze-bayern.de/Content/Document/Y-300-Z-BECKRS-B-2022-N-612?hl=true)) where the decision was taken.

German media coverage about this:
[Heise](https://www.heise.de/news/DSGVO-Abmahnwelle-wegen-Google-Fonts-7206364.html)

### Expected behaviour

Fonts are delivered by the server who is serving the docs.

### Actual behaviour

Fonts are delivered by Google Fonts.

### Steps to reproduce

1. Go to a mkdocs material serving website (without enabled privacy plugin) e.g. <https://squidfunk.github.io/mkdocs-material/>
2. Open developer tools
3. Open the "Network" tab
4. Do a force reload (with re-downloading all assets)
5. Search for `fonts.gstatic.com`

### Package versions

- Python: `3.10.5`
- MkDocs: `mkdocs, version 1.3.0 from /usr/local/lib/python3.10/site-packages/mkdocs (Python 3.10)`
- Material: `8.3.9`
- Container version: `ghcr.io/afritzler/mkdocs-material:8.3.9`

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
```

### System information

- Operating system: macOS 12.4
- Browser: Firefox 103.0 (64-bit)

**Comment by squidfunk** [comment]
Thanks for reporting. [We have an explanation in the docs](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin) why this is not economical:

<img width="704" alt="Bildschirmfoto 2022-08-10 um 17 49 48" src="https://user-images.githubusercontent.com/932156/183952330-86c996c7-7314-423c-bca2-327da8e480e7.png">

Your options:

- Use the privacy plugin, which makes self-hosting dead simple
- [Disable autoloading](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#autoloading) and implement it manually

**Comment by squidfunk** [comment]
For further context, see the lengthy discussions in #739
