### ISSUE TITLE
Add instructions how to update translations

### ISSUE THREAD

**Issue by amire80** [squidfunk/mkdocs-material#4244]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I found some mistakes and missing translations in my language, Hebrew. I tried sending a pull request for that, #4243, but I'm really not sure that I've done it correctly. I tried searching for documentation about updating translations, but I couldn't find any. In the issue reporting form, there's an option to **add** a new language, but not to update existing translations or adding missing strings.

It would be nice to have documentation about the right process for doing this in the Contributions or README file.

Thanks!

### Expected behaviour

I open [CONTRIBUTING.md](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and find information about updating translations there.

### Actual behaviour

I open [CONTRIBUTING.md](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and I don't see information about updating translations there.

### Steps to reproduce

Open [CONTRIBUTING.md](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and search for information about updating translations.

### Package versions

The current version in GitHub.

### Configuration

```yaml
(irrelevant)
```

### System information

Everywhere.

**Comment by squidfunk** [comment]
Fixed in a750a66f9.
