### ISSUE TITLE
Warning due to missing translation if locale is not "en": No strict mode possible

### ISSUE THREAD

**Issue by dr-br** [squidfunk/mkdocs-material#4253]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If I set `locale: de`, which I need to set for `git-revision-date-localized`, strict mode build is not possible due to the following warning:
```
WARNING  -  No translations could be found for the locale 'de'.
            Defaulting to English.
```
Strict mode build is possible with the `mkdocs` or `readthedocs` themes.

### Expected behaviour

No warning, if `locale` is set to `de` or any other language.

### Actual behaviour

Warning occurs, avoiding strict build.

### Steps to reproduce

1. Create new project: `mkdocs new test`
2. Append the following lines to the file `test/mkdocs.yml`  
    ```
    theme:
       name: material
       locale: de
    ```
3. Build the project: `mkdocs build -f test/mkdocs.yml -s`
4. Build fails with the following message: *Aborted with 1 warnings in strict mode!*

### Package versions

- Python: `python --version` &rarr; `Python 3.10.5`
- MkDocs: `mkdocs --version` &rarr; `mkdocs, version 1.3.1 from /home/.../venv/lib/python3.10/site-packages/mkdocs (Python 3.10)`
- Material: `pip show mkdocs-material | grep -E ^Version` &rarr; `Version: 8.4.0`

### Configuration

```yaml
site_name: My Docs

theme:
  name: material
  locale: de
```

### System information

- Operating system: Manjaro 21.3.6
- Browser: doesn't matter

**Comment by squidfunk** [comment]
Material for MkDocs doesn't (yet) support `locale`. Our localization system predates MkDocs native localization system by several years. Just switch `locale` to [`language`](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language) and the error will vanish:

``` yaml
theme:
  language: de
```

**Comment by dr-br** [comment]
Dear Martin,
thanks for the quick response!
Your hint concerning the option to set the locale for `git-revision-date-localized` did the trick.
https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/howto/specify-locale/#4-site-locale-set-by-this-plugin was my solution.
https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/howto/specify-locale/#3-site-locale-set-by-your-theme is not sufficient, maybe I will open a ticket there.
