### ISSUE TITLE
Split site_nav block into main and toc

### ISSUE THREAD

**Issue by martinberoiz** [squidfunk/mkdocs-material#4263]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x] ... there are no open or closed issues that are related to my idea

### Description

Please consider breaking the `site_nav` block into a `main` part and a toc part.

https://github.com/squidfunk/mkdocs-material/blob/612429c903b1edee68a5fcd561e7b5f3b54ec362/material/base.html#L144-L169

My proposed change: (I separated the changes that this would add for better reading)

```html
          {% block site_nav %}

           {% block site_nav_main %}

            {% if nav %}
              {% if page.meta and page.meta.hide %}
                {% set hidden = "hidden" if "navigation" in page.meta.hide %}
              {% endif %}
              <div class="md-sidebar md-sidebar--primary" data-md-component="sidebar" data-md-type="navigation" {{ hidden }}>
                <div class="md-sidebar__scrollwrap">
                  <div class="md-sidebar__inner">
                    {% include "partials/nav.html" %}
                  </div>
                </div>
              </div>
            {% endif %}

            {% endblock %}
            {% block site_nav_toc %}

            {% if not "toc.integrate" in features %}
              {% if page.meta and page.meta.hide %}
                {% set hidden = "hidden" if "toc" in page.meta.hide %}
              {% endif %}
              <div class="md-sidebar md-sidebar--secondary" data-md-component="sidebar" data-md-type="toc" {{ hidden }}>
                <div class="md-sidebar__scrollwrap">
                  <div class="md-sidebar__inner">
                    {% include "partials/toc.html" %}
                  </div>
                </div>
              </div>
            {% endif %}

          {% endblock %}

          {% endblock %}
```

This will help sub-theming, otherwise I would have to override `nav` *and* `toc`, and I can't choose one or the other.

This change would also be backwards compatible because I leave `site_nav` untouched and adds `site_nav_main` and `site_nav_toc` blocks.

### Use Cases

This will help sub-theming.

**Comment by squidfunk** [comment]
Thanks for suggesting. I don't think it's a good idea to introduce more and more blocks – we need to keep it simple, and the templates are already very complex. I understand the use case, but as the `site_nav` block rarely changes, it's fine just to override the entire block and check on new major releases to whether changes are necessary. Furthermore, since both sidebars are handled similarly, changes would always affect both.
