### ISSUE TITLE
A New General Purpose Block Format

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#4268]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

## Overview

This is being created to bring to everyone's attention the current work to create a general purpose Markdown block.

1. There are a number of different extensions that implement various features using blocks, but there is a limited reasonable syntax that can be created.
2. Some existing implementations (Admonitions, Details, Tabs, etc.) in the past have used an indented style markup. Unfortunately, that is always compatible will all editors and such.
3. A general purpose block could allow for extensions to adopt a flexible syntax allowing for new features to be created without having to invent new, and differing syntax.

I've been prototyping such a general-purpose block extension. It is inspired by RST directives but does not necessarily aim to be a 1:1 implementation of them.  The current sytnax is inspired by [Myst's directive support](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#code-fences-using-colons) and [Pandoc's general purpose blocks](https://pandoc.org/MANUAL.html#divs-and-spans). 

The plan is to provide an alternative to things like Admonitions, Details, and Tabs that don't require tab indentation. Additionally, this opens the door for new blocks without having to create a new, non-conflicting syntax from scratch, some possible ideas: figures, embedded audio and video, etc.

It should be noted that these new general-purpose implementations for things like Admonitions, Details, and Tabs would render the same HTML output as the existing implementations, but will likely allow more flexibility for setting classes, IDs, etc. There are no plans yet to remove the old implementations, but maybe in the distant future, assuming things go over well, we may consider a conservative deprecation period (think 1 or 2 years to give plenty of transition time).

## Syntax

The exact syntax is not finalized, so I'm generally looking for input.

Currently, it is implemented with the following syntax:

```
::: name :: Optional string argument(s), could be a title, etc.
key: additional YAML options
key2: etc.

content
:::
```

As noted above, additional string arguments are optional, but some general blocks can require them. They are aimed at blocks where such a convention makes sense:

```
::: note :: Some note title

content
:::
```

Other options are allowed via YAML options that must be the first block and are considered part of the header when present:

```
::: note
attributes: {'id': 'some-id', 'class': 'additional classes'}

Some message
:::
```

YAML fences are not required (`---`), but if present will be accepted. Because they are optional, the first block of real content must have an empty line between it and the header.

```
::: note :: With options
---
attributes: {'id': 'some-id', 'class': 'additional classes'}
---

content
:::

::: note :: Without options

Still need an empty line before content.
:::
```

We _could_ potentially have an option to require YAML fences `---`, and if so, this would no longer require the first block of real content to need an empty new line before it, but currently, a new line is required.

## Alternatives to the Current Syntax? 

We chose `:::` as it is used in multiple Markdown parsers for a similar purpose. There has been some disinterest in this syntax as it might conflict with some other existing syntax (@oprypin raised this concern). 

The problem is that no matter what we do, we may conflict with some extension somewhere. We are aiming for a general-purpose block format that extensions could adopt without creating endless conflicting syntax. With that said, the syntax is not decided, and we could allow for more suggestions. The top proposals we currently have are as follows:

```
/// note || This is a string
key1: value
key2: value

content
///

::: note :: This is a string.
key1: value
key2: value

content
:::

/// note | This is a string
key1: value
key2: value

content
///
```

Personally, I am not fond of the first proposal, but I think the second and third are top contenders.

### How Can I Add Input or Express My Opinion?

I'd like to not split this conversation over multiple threads and give existing interested parties a chance to see other suggestions as well.

Please hop on over to https://github.com/Python-Markdown/markdown/issues/1175, read over the current conversation, and feel free to express your opinions, suggestions, etc.

While ultimately, I will have to make the final decision, I'd like to hear people's thoughts, concerns, and suggestions before rolling something out something permanent.

Unfortunately, there is no way to accommodate everyone's opinion, but hopefully, it can help steer things in a generally positive direction.

---

@squidfunk please lock this thread as I would prefer people to voice their opinions in the already open Python Markdown issue.

### Use Cases

The aim is to provide a reusable, general-purpose block syntax that can be adopted not only by pymdownx, but utilized but other extension as well.

**Comment by squidfunk** [comment]
I locked the conversation as all discussion should be done in https://github.com/Python-Markdown/markdown/issues/1175.
