### ISSUE TITLE
Missing syntax highlighting for code blocks

### ISSUE THREAD

**Issue by oliverschwendener** [squidfunk/mkdocs-material#428]
## Description

There is no syntax highlighting in code blocks.

### Expected behavior

I expect markdown code blocks to have syntax highlighting (like the default mkdocs theme does).

Example markdown code block:

```
``` javascript
function add(a, b) {
    return a + b
}
```

Syntax highlighting in default mkdocs theme:

![mkdocs-default](https://user-images.githubusercontent.com/15727229/28967104-ea537c24-7919-11e7-815e-b3258b5f5c17.PNG)

### Actual behavior

If I use this mkdocs theme there is no syntax highlighting in code blocks:

![mkdocs-material](https://user-images.githubusercontent.com/15727229/28967134-0a080166-791a-11e7-969a-9475abc80e7a.PNG)

### Steps to reproduce the bug

1. Add a code block to your markdown file
2. Install the latest version of Material with pip: `pip install mkdocs-material`
3. Add the following line to mkdocs.yml: `theme: 'material'`
4. Run the built-in dev-server: `mkdocs serve`
5. Open up `http://127.0.0.1:8000/` in the browser

### Package versions

* Python: 3.6.1
* MkDocs:  0.16.3
* Material: 1.8.0

### Project configuration

``` yaml
site_name: Code Demo
theme: material
```

### System information

* OS: Windows 10 1703

**Comment by makshh** [comment]
Did you install Pygments and activate CodeHilite extension in your theme?

http://squidfunk.github.io/mkdocs-material/extensions/codehilite/

**Comment by squidfunk** [comment]
Please read the docs:
http://squidfunk.github.io/mkdocs-material/extensions/codehilite/

**Comment by squidfunk** [comment]
The thing is: if you install `mkdocs-material` via pip, it SHOULD install `Pygments` for you, as it is specified as a dependency. Please check if Pygments is/was installed. If not, we can look into it.

**Comment by oliverschwendener** [comment]
Yes Pygments was installed with mkdocs-material. I just forgot to add 
``` yml
markdown_extensions:
  - codehilite
```
to my `mkdocs.yml`. Sorry for that & Thanks!
