### ISSUE TITLE
Unable to use search in QWebEngineView

### ISSUE THREAD

**Issue by hujhcv** [squidfunk/mkdocs-material#4282]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When I use chrome or QWebEngineView and directly load the built static file site/index.html, the search cannot be used, and the prompt: Initializing search. the problem doesn't occur with the mkdocs or readthedocs themes.

### Expected behaviour

The search function can be used when directly loading built static files using chrome or QWebEngineView.

### Actual behaviour

If use chrome to report an error message: 
Access to fetch at 'file:///.../MkDocs/site/search/search_index.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.
Failed to load resource: net::ERR_FAILED
Uncaught (in promise) TypeError: Failed to fetch
     at lr (index.ts:53:15)
     at ke (index.ts:76:10)
     at bundle.ts:112:24
     at bundle.ts:273:21

If use QWebEngineView to report an error message:
 js: Fetch API cannot load file://.../MkDocs/site/search/search_index.json. URL scheme "file" is not supported.

### Steps to reproduce

1. use material theme in mkdocs.yml
2. mkdocs build
3. use chrome load site/index.html directly

### Package versions

- Python: python 3.10.4
- MkDocs: version 1.3.1
- Material: Version: 8.4.1

### Configuration

```yaml
site_name: XXXX
site_url: ""
use_directory_urls: false
nav:
    - index: index.md
theme:
  name: material #readthedocs
```

### System information

- Operating system: ubuntu 22.04
- Browser: chrome 103.0.5060.53

**Comment by squidfunk** [comment]
Thanks for reporting. In order for search to work from `file://`, you need to enable the [offline plugin](https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/#built-in-offline-plugin).
