### ISSUE TITLE
Tooltip in feedback widget doesn't disappear in Safari

### ISSUE THREAD

**Issue by 1871fotc** [squidfunk/mkdocs-material#4288]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

When you hover over the "Was this page helpful?" icons a tooltip appears. When you click an icon, the tooltip doesn't disappear and it covers the "thank you" note.  See discussion https://github.com/squidfunk/mkdocs-material/discussions/4287

### Expected behaviour

Tooltip disappears when icon is clicked.

### Actual behaviour

Tooltip does not disappear when icon is clicked.

### Steps to reproduce

1. Using Safari, go to https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/
2. Click This page was helpful icon 🙂
3. The tooltip continues to be displayed, covering the thank you note

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
site: https://squidfunk.github.io/mkdocs-material/
MkDocs.yml: https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
```

### System information

- Operating system: macOS Big Sur 11.6.8
- Browser: Safari 15.6

**Comment by squidfunk** [comment]
Thanks for reporting. So, I've invested significant time into trying to fix this, and sadly, I don't think it's easily fixable. It all comes down to a Safari bug, where Safari will not dispatch `mouseleave` and `focusout` events when an element or one of its parents are marked as `disabled`. [This seems to be a known bug](https://github.com/equinor/design-system/issues/1204), as some other projects experience the same.

It's essential that we mark the form as `disabled` to catch subsequent clicks which would skew the feedback results. Thus, for the time being, I need to mark this issue as something that we can't fix. If somebody has a better idea, PRs appreciated.

**Comment by Stephen-Gates** [comment]
Thank you for investigating and sorry it consumed so much time 🙏
