### ISSUE TITLE
Version switching does not work with anchors

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#4291]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Version switching does not work with anchors

### Expected behaviour

Version switching works with anchors

### Actual behaviour

When an anchor is selected, version switching takes you to `/`

### Steps to reproduce

Go to https://hatch.pypa.io/latest/intro/#setup then select any version from the dropdown

### Package versions

- Python: `3.10.5`
- MkDocs: `1.3.1`
- Material: `8.4.2`

### Configuration

https://github.com/pypa/hatch/blob/master/mkdocs.yml

### System information

- Operating system: Windows 10
- Browser: Chrome

**Comment by squidfunk** [comment]
Fixed in d0f73018f. This was reproducible on the versioning example as well. I redeployed it with the fix:
https://squidfunk.github.io/mkdocs-material-example-versioning/0.3/bar/#bar

**Comment by squidfunk** [comment]
Released as part of 8.4.3.

**Comment by ofek** [comment]
Thanks!!!
