### ISSUE TITLE
Add SimpleIcons icon collection

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#4304]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

`mkdocs-material` already [supports 3 popular icon collections](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration): Material Design Icons, FontAwesome, and Octicons. I suggest to add a fourth one that's very popular and quite orthogonal to the other three collections: [SimpleIcons](simpleicons.org/). SimpleIcons contains more than 2000 monochromatic icons of popular brands and, e.g., powers the logos feature of the [shields.io](https://shields.io/) badge service.

Disclaimer: I'm a maintainer of the SimpleIcons project.

### Use Cases

Documentation sometimes refers to popular tools or products. Adding icons of such tools and products would enhance the look and feel. Icon collections like FontAwesome have some brands as well, but SimpleIcons is significantly more extensive. SimpleIcons is an actively maintained open-source icon collection with a permissive license.

### Screenshots / Mockups

n/a

**Comment by squidfunk** [comment]
Thanks for suggesting. I've actually been looking for an icon pack that is focused on brand icons, so this could be a perfect fit! I'll check and see if we can integrate it as seamlessly as the other icon sets. Although the FontAwesome and Material icon sets have some brand icons, having a full-featured brand icon set can definitely be considered a great value add.

**Comment by sisp** [comment]
Sounds great! :tada: Let me know if there's anything I can do to help.

**Comment by squidfunk** [comment]
Added in c4b6e5c52b5260d5db59651406792bf01747fec0.

**Comment by squidfunk** [comment]
Released as part of 8.4.3. You can now also find them via our icon search:
https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search

**Comment by sisp** [comment]
That's great, @squidfunk! Thank you very much for your efforts! 🙏
