### ISSUE TITLE
Add i18n support for default admonition title

### ISSUE THREAD

**Issue by leovan** [squidfunk/mkdocs-material#4334]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Add i18n support for default admonition title. `!!! info` now is rendered as `Info` without custom title. It would be nice to set it to other native words when using different language.

### Use Cases

`!!! info` can be rendered as `信息` in Chinese.

**Comment by squidfunk** [comment]
Thanks for suggesting. This is really something that should be asked upstream in [Python Markdown](https://github.com/Python-Markdown/markdown/), since we're only rendering what we get from it. Closing as out of scope.

**Comment by squidfunk** [comment]
On a side note, you can [change the title](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#changing-the-title). Try:

```
!!! info "信息"

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod
    nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor
    massa, nec semper lorem quam in massa.
```
