### ISSUE TITLE
Small edit button improvement

### ISSUE THREAD

**Issue by sidekick-eimantas** [squidfunk/mkdocs-material#4336]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

It would be great if we could instruct for the edit links to be opened in new tabs

### Use Cases

Don't need to re-open the docs site after making edits

**Comment by squidfunk** [comment]
Thanks for suggesting. 8.4.3 (the current latest release) moves the edit button in a separate partial, so you can [extend the theme](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme) and override the new `actions.html` partial:

https://github.com/squidfunk/mkdocs-material/blob/b344ae8836fbdd47d5e83dd3c1d07a38ca11d94d/src/partials/actions.html#L24-L33

Please understand that we can't add options for each and every HTML attribute; that would be a `target="__blank"`.
