### ISSUE TITLE
Multi-lang fenced code tabs

### ISSUE THREAD

**Issue by mofirouz** [squidfunk/mkdocs-material#434]
We use mkdocs-material with [Nakama](https://github.com/heroiclabs/nakama)'s [documentation](https://heroiclabs.com/docs). It's an amazing project - thank you for providing this.

Nakama has various clients (C#/Unity, C++, Java etc) and we need to provide code examples for each client. We were planning on integrating [markdown fenced code tabs](https://github.com/yacir/markdown-fenced-code-tabs) but unfortunately that heavily depends on Bootstrap. 

I've looked into forking the project and updating the CSS elements/styles to use Material but unfortunately have hit a stumbling block as the Tab elements are only designed for navigational purposes.

Can you give me a few pointers on how to implement code tabs with the theme?

**Comment by squidfunk** [comment]
There was someone trying to achieve this:
https://github.com/squidfunk/mkdocs-material/issues/195

However, there's no plan to include it into Material, as I haven't seen a solid extension that support this kind of UI element. Maybe this is a case for @facelessuser's Pymdown package? However, I still have to implement the details stuff, so no timeline on that, sorry :/

**Comment by facelessuser** [comment]
This sounds more like a CSS question, or am I mistaken?

**Comment by squidfunk** [comment]
Partly, because we need a Markdown syntax to describe the tabs. I think the feature request goes in that direction because it would always be solvable with plain inline HTML.

**Comment by facelessuser** [comment]
I guess I'm confused. He mentions he's using an extension that outputs tabbed HTML already, but material styling can't be used to style it. Is the problem with the HTML output? Or the current Material styling?

As far as pymdown-extensions is concerned, I could add a feature to create tabbed code blocks, but I'd need to know what Material thinks is acceptable format for that, or I guess the user would have to provide their own CSS which is fine as well and could technically be applied to the extension mentioned above.

If I were to implement it, I'd probably implement it different than the extension mentioned above. I would not auto group consecutive code blocks  *unless* you specifically applied a tab name to the code block. I'd prefer the behavior to be explicit. I don't think I'd like to add anymore syntax than maybe a simple tab specifier to existing fences. That would keep the syntax basically the same with an extra option in the fence header.

**Comment by mofirouz** [comment]
@facelessuser I chose the Fenced Code extension to create some kind of HTML structure from the Markdown content. I forked the project to update the CSS styles but didn’t realise the Material UI bundled with this theme doesn’t have styles for tab-content views.

Whether you add an "official" extension to pymdown-extensions or not, we'd still need more CSS/JS code in Material to support such feature, whether it's a tab element or something else. I'm in the process of converting/adding [this MDL Tab component](https://github.com/google/material-design-lite/tree/mdl-1.x/src/tabs) to mkdocs-material but I'm finding myself getting stuck.

**Comment by facelessuser** [comment]
I guess if it was a generalized tab feature, like a tab container that you could wrap anything with, I may just lean towards using HTML, and you could use the `extra` option to parse the Markdown content of the HTML with `markdown=1`.

I'm open to suggestions for a generalized tab syntax, but I'd have to see.

**Comment by facelessuser** [comment]
> @facelessuser I chose the Fenced Code extension to create some kind of HTML structure from the Markdown content. I forked the project to update the CSS styles but didn’t realise the Material UI bundled with this theme doesn’t have styles for tab-content views.

That is what I was eluding to earlier.  This feels like a styling issue that can be remedied with user CSS.  If Material were to provide "official" styling, we need to know what the official format it would recognize would be.

This then could be implemented via an extension, or the user could use raw HTML.

**Comment by facelessuser** [comment]
As an example.  I have added a details extension to pymdown-extensions which Material does not currently support: http://facelessuser.github.io/pymdown-extensions/extensions/details/.

I have to add my own CSS and JS to achieve the styling: [style](https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_details.scss), [js](https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/js/details.js).

Just because it isn't supported, doesn't mean you can't add it in your own project.  In this case, details will most likely be added to Material at some point, but for tabs, I would need a clear spec for what Material would want a tab interface to look like.  Would this be a generalized tab interface?  Or something specific to code blocks? Should we bother with a Markdown syntax, or should this be implemented with raw HTML utilizing `extra`'s `markdown=1` feature to parse markdown content in raw HTML.

**Comment by facelessuser** [comment]
Just to clarify more what I mean by `markdown="1"`.  Using the MDL Tab Component you referenced, you could use raw HTML, and then add all the CSS and JavaScript via Mkdocs `extra_javascript` and `extra_css` variables:

```html
<div class="mdl-tabs mdl-js-tabs mdl-js-ripple-effect" markdown="1">
<div class="mdl-tabs__tab-bar" markdown="1">

[About the Beatles](#about-panel){: .mdl-tabs__tab is-active=1}
[Members](#members-panel){: .mdl-tabs__tab}
[Discography](#albums-panel){: .mdl-tabs__tab}

</div markdown="1">

<div class="mdl-tabs__panel is-active" id="about-panel" markdown="1">

**The Beatles** were a four-piece musical group from Liverpool, England.
Formed in 1960, their career spanned just over a decade, yet they are widely
regarded as the most influential band in history.

Their songs are among the best-loved music of all time. It is said that every
minute of every day, a radio station somewhere is playing a Beatles song.

</div>

<div class="mdl-tabs__panel" id="members-panel" markdown="1">

The Beatles' members were:

- John Lennon (1940-1980)
- Paul McCartney (1942-)
- George Harrison (1943-2001)
- Ringo Starr (1940-)

</div>

<div class="mdl-tabs__panel" id="albums-panel", markdown="1">

The Beatles' original UK LPs, in order of release:

- Please Please Me (1963)
- With the Beatles (1963)
- A Hard Day's Night (1964)
- Beatles for Sale (1964)
- Help! (1965)
- Rubber Soul (1965)
- Revolver (1966)
- Sgt. Pepper's Lonely Hearts Club Band (1967)
- The Beatles ("The White Album", 1968)
- Yellow Submarine (1969)
- Abbey Road (1969)
- Let It Be (1970)

</div>

</div>
```

While a markdown plugin to do all of this is possible, it would be probably be a complicated syntax.   I wonder if for something like this, it is just better to use raw HTML like shown above.  This is why Markdown tables only handle inline stuff.  When things get too complicated, it just makes more since to use raw HTML.

**Comment by squidfunk** [comment]
Okay, sorry for being too short on words. I am currently on vacation (greetings from Hanoi, Vietnam!) and had some time to answer questions. The reason I brought you into this business was the fact that the author of the issue wasn't happy with the wxtension he proposed as it depends on bootstrap, which Material does not. We could use HTML, for sure, but could we implement it in Pymdown as I think it's a fairly regular usecase?

I could develop the whole dringend code in Material and send you a notice on how it should be implemented on your side, then you could think about the syntax. Does it even make sense? Can we find a Markdown syntax that is not too weired? I just wanted to facilitate some discussion.

A fallback for no JavaScript being available should in my opinion show all tabs as a vertical list of fenced code blocks. However, what about other content? It's kind of a details extension with tabs. Would you be interested in general @facelessuser? Then we could start thinking about it.

**Comment by facelessuser** [comment]
> Would you be interested in general @facelessuser?

I am open, but I promise nothing at this point 🙂 .  I think step 1 is to find an acceptable HTML format.  And then derive a syntax from that.

Details was kind of nice as it reminded as a admonition like object, so I borrowed syntax from that. Essentially, I look at the tabs as a list format even though that is not how it would get rendered.  But that is how Markdown would kind of need to treat it.  So you'd need a specialty list format that doesn't interfere with anything else and is easy to embed block content in.

I am open to this, but if it feels a syntax to represent this is too convoluted, I'd op for raw HTML.  I may do some research to see if people in the past have come up with custom syntaxes that make sense for this to get ideas.

**Comment by squidfunk** [comment]
I will think about this a little and maybe add support for the HTML-based solution. Then we can think about if it makes actually sense, but I'm with you on the whole weired-syntax problem. Thank you for your estimate and time!

**Comment by squidfunk** [comment]
I actually decided not to follow this path further down, for the following reasons:

1. @facelessuser made some good points that this may not be brought to Markdown in a user friendly manner, thus HTML has to be used. I also question the approach of just grouping together consecutive code blocks, as this may be problematic in some scenarios. Maybe give those code blocks a unique identifier? I don't know.

2. I want to minimize the effort for building components that are raw-HTML-only, as not many users may benefit. So, as long as there is no Markdown extension that generates HTML for this feature that is compatible with Material, I will not pursue this feature request, I'm sorry.

@facelessuser if you want to go down this path, we can talk about what the generated HTML should look like. I then could define the styles in Material as with the rest of PyMdown. Nevertheless, thanks for your feedback!

**Comment by facelessuser** [comment]
I have no intentions at this time of creating an extension for this. If I get to a point where I need something like this, I'll probably stick to raw HTML and add CSS and JS to handle this.

If I change my mind I'll let you know.

**Comment by ethanneff** [comment]
Yeah, I had to do a similar solution to our own docs: https://docs.branch.io/pages/apps/ios/#initialize-branch
