### ISSUE TITLE
Improve comment usability

### ISSUE THREAD

**Issue by Kanaduchi** [squidfunk/mkdocs-material#4346]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I would like to suggest some improvements to the comment system:

1. Move configuration to an extra section of mkdocs.yaml, for example:
```
extra:
  comments:
      enable: true
      repo: ...
      repo_id: ...
      category: ...
      category_id: ...
```

2. Change the script of comments.html file:
```
{% set comments = config.extra.comments %}
{% if comments.enable and page.meta.comments %}
```

3. Add a predefined snippet:
```
<script src="https://giscus.app/client.js"
              data-repo="{{ comments.repo }}"
              data-repo-id="{{ comments.repo_id }}"
              data-category="{{ comments.category }}"
              data-category-id="{{ comments.category_id }}"
              data-mapping="pathname"
              data-reactions-enabled="1"
              data-emit-metadata="0"
              data-theme="light"
              data-lang="{{ config.theme.language }}"
              crossorigin="anonymous"
              async>
</script>
```

Also it will be great to add NPE check in the synchronization of Giscus theme with palette:
```
var giscus = document.querySelector("script[src*=giscus]")
{% if giscus %}
```

### Use Cases

 In this case script and snippet will be predefined and the user will need only to put the configuration in the mkdocs.yaml and enable comments on a page by setting the comments front matter property to true.

**Comment by squidfunk** [comment]
Thanks for suggesting. The problem with this is that the snippet must be generated by the user to know the base-64 encoded values. For example, for our documentation, this is:

``` html
<script
    src="https://giscus.app/client.js"
    data-repo="squidfunk/mkdocs-material"
    data-repo-id="MDEwOlJlcG9zaXRvcnk1MDYxNzQyOA=="
    data-category="_"
    data-category-id="DIC_kwDOAwRcVM4CAtJY"
    data-mapping="pathname"
    data-reactions-enabled="1"
    data-emit-metadata="1"
    data-theme="light"
    data-lang="en"
    crossorigin="anonymous"
    async
  >
  </script>
```

This means that the user now has to copy and paste attribute by attribute into `mkdocs.yml`, which is a worse experience than just overriding the `comments.html` partial. Since the entire code can be contained inside this partial, there's no risk of breaking when new major upgrades take place, so it's definitely the better approach.
