### ISSUE TITLE
Sticky columns (or headers) in data tables

### ISSUE THREAD

**Issue by nickdnk** [squidfunk/mkdocs-material#4347]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Hello

I have a large table with a lot of columns. The leftmost column has text, and all the others have icons (check/noncheck) for each row. This produces two problems;

1. You cannot see the left-most cell with text if you scroll right.
2. The table is too tall to show the bottom scroll-indicator, so you can't scroll horizontally in the table without going all the way down, unless you have a trackpad or something similar.

This means you won't actually ever be able to see what you want (a combination of left-most column and any other column) at the same time.

I would like to request a feature that allows you to sticky a column (probably only either the first or the last) when scrolling horizontally. Optionally, sticking the headers to the top of the window when scrolling down could be very good as well.

### Use Cases

I put this in the description. It's a pretty generic request as far as I can tell, so it should benefit many people in many cases. Regular markdown syntax does not support this, so it would have to be made for mkdocs specifically.

**Comment by squidfunk** [comment]
Thanks for suggesting! I've investigated a possible solution to this feature request, but sadly it's not possible with the current architecture. In general, making headers in tables sticky is possible [with some caveats](https://css-tricks.com/position-sticky-and-table-headers/). However, we're jumping through several hoops to make tables scrollable on smaller screens, which means we need to set the `overflow` property on the element that eventually contains the potentially overflowing table. Sadly, [setting `overflow` breaks stickiness](https://css-tricks.com/dealing-with-overflow-and-position-sticky/). 

For this reason, I'm closing this issue as not fixable.

**Comment by nickdnk** [comment]
Alright. It was worth a try. I'll have to come up with a better solution for presenting my data then.

This aside, this project is great.
