### ISSUE TITLE
Social card cannot generate correct Chinese content on sharing image

### ISSUE THREAD

**Issue by jasonren0403** [squidfunk/mkdocs-material#4354]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [x] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

maybe related to #3099, but a different case
The Chinese character cannot render correctly on social share image.

### Expected behaviour

A correct social share image:(

### Actual behaviour

![generated photo](https://user-images.githubusercontent.com/40999116/190051101-7715a724-1d09-4ec9-9348-80113aaad714.png)

### Steps to reproduce

1. Set either `site_name` or `site_description` containing Chinese (for example `hello world` translation `你好，世界`).
2. Then view the social image generated in `.cache/plugin/social`.
3. The Chinese character, which should render, is now displayed as squares.

### Package versions

- Python: 3.10.2
- MkDocs: 1.3.1
- Material:  8.5.0

### Configuration

```yaml
site_name: My Docs
theme:
  name: material
site_description: '你好，世界'
plugins:
  social:
    cards: true
```

### System information

- Operating system: Windows 11
- Browser: Edge 105
(But I thought this issue is platform independent...)

**Comment by jasonren0403** [comment]
If the title of the document contains Chinese, it will also break the social card view like this:
![Generated card](https://user-images.githubusercontent.com/40999116/190052722-c2b7360a-c772-4649-83d6-7de5e08e0ff3.png)

I only changed the `h1` title of example file to Chinese(`欢迎来到 MkDocs` as Chinese variant of `welcome to MkDocs`)
```md
# 欢迎来到 MkDocs

For full documentation visit [mkdocs.org](https://www.mkdocs.org).
...(other content untouched)
```

And the corresponding config is like this:
```yaml
site_name: My Docs
theme:
  name: material
site_description: 'hello world'
plugins:
  social:
    cards: true
```

**Comment by squidfunk** [comment]
Thanks for reporting. Roboto doesn't include Chinese characters. You need to use a font that has, for example one of the [Noto Sans variants](https://fonts.google.com/noto/specimen/Noto+Sans):

https://github.com/squidfunk/mkdocs-material/blob/e9b3448aada03601eceffc28069dcb1051d65aa2/docs/schema/assets/fonts.json#L4607-L4647

**Comment by jasonren0403** [comment]
> Thanks for reporting. Roboto doesn't include Chinese characters. You need to use a font that has, for example one of the [Noto Sans variants](https://fonts.google.com/noto/specimen/Noto+Sans):
> 
> https://github.com/squidfunk/mkdocs-material/blob/e9b3448aada03601eceffc28069dcb1051d65aa2/docs/schema/assets/fonts.json#L4607-L4647
> 
> I've tested it with `Noto Sans TC` (Traditional Chinese), which contains parts of the characters you've used, and thus showcases the issue. I suggest to check on [Google Fonts](https://fonts.google.com/) to find a font that supports the entire range of characters. Feel free to share which font you found to be working.
> 
> ```yaml
> theme:
>   font:
>     text: Noto Sans TC
> ```
> 
> Results in:
> 
> ![adding-a-comment-system](https://user-images.githubusercontent.com/932156/190072497-47c85a9d-4037-46eb-8446-566ba2bc4607.png)
> 
> Note that you can also [override the fonts explicitly for social cards](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#+social.cards_font):
> 
> ```yaml
> plugins:
>   - social:
>       cards_font: Noto Sans TC
> ```

Thanks! Noto Sans SC and Noto Serif SC works fine for me.
```yaml
plugins:
  social:
    cards: true
    cards_font: Noto Sans SC
```
This may be documented?

**Comment by squidfunk** [comment]
We can add recommended configurations for specific languages in content tabs as part of the `cards_font` description.
Would you like to create a PR for this?

**Comment by jasonren0403** [comment]
> We can add recommended configurations for specific languages in content tabs as part of the `cards_font` description. Would you like to create a PR for this?

I've done #4357 😄
