### ISSUE TITLE
Support cookie consent for git repositories

### ISSUE THREAD

**Issue by fwendland** [squidfunk/mkdocs-material#4356]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Users can provide a git repository by setting `repo_url` in `mkdocs.yml`. This will render a link to the repository on the website. Additionally, information, like stars, forks and latest release, are retrieved and rendered for public repositories hosted on GitHub or GitLab. These requests occur unconditionally and may violate data privacy regulations.

The retrieval of a repository's information should be configurable using:

- Option flag in `mkdocs.yml`: It would disable the information retrieval all together. It is rather sever but has the benefit that there is no additional configuration necessary. On the downside, the provided repository information is nice for visitors.
- Cookie consent: Visitors can decide whether they consent to the information retrieval. It would allow more flexibility and empower the visitor. On the downside, the solution may be more complex. and would require a cookie consent configuration in `mkdocs.yml`.

See discussion #4329. 

### Use Cases

Would make the use of the git repository configuration more data privacy friendly. Developers can include the repository link without conflicting with privacy regulations.

**Comment by squidfunk** [comment]
Fixed in 6b1ce146832a1c8cc3578b17f4ca4d6f3af2553a

**Comment by squidfunk** [comment]
Released as part of 8.5.2.

**Comment by fwendland** [comment]
Thanks a lot for the great work.
