### ISSUE TITLE
Allow longer site tiles and descriptions in social cards

### ISSUE THREAD

**Issue by vedranmiletic** [squidfunk/mkdocs-material#4359]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Present implementation of social cards offers a single line for site title and two lines for site description. These are quite limiting, even compared to what is shown by Google in search results.

### Use Cases

It would be great if we could get an extra line (possibly optional and off by default) of site title and site description in social cards at the cost of shorter/smaller font page title or less spacing between the contents (either approach would work for us).

### Screenshots / Mockups

![google](https://user-images.githubusercontent.com/246061/190173677-0d783cd6-9312-4de5-bc25-c200e0bae4f0.png)

![social-card](https://user-images.githubusercontent.com/246061/190173746-8b8d9a47-ff5b-4b33-9b5b-190ae8029f2b.png)

**Comment by squidfunk** [comment]
Thanks for reporting. Getting this to work flexibly (with dynamic re-scaling of text. etc.) is quite a challenge, and currently not considered ready for implementation. For now, the current recommendation is to keep titles and descriptions short, but I plan to revisit social card layouts in the near future, possibly adding more flexible options.

**Comment by vedranmiletic** [comment]
Great! Hope that some solution will be implemented sometime.
