### ISSUE TITLE
Cover images for blog posts

### ISSUE THREAD

**Issue by StarfallProjects** [squidfunk/mkdocs-material#4364]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Add support for blog post cover images. It should be possible to display the cover images:

- on the blog index page
- at the top of the post
- both

Ideally some style controls:

- position in relation to other blog elements
- ?

Is it worth considering supporting social cards as cover images, as part of this feature?

### Use Cases

Make our blogs prettier

**Comment by squidfunk** [comment]
Thanks for suggesting. You know that you can use an image in the post excerpt, which is the displayed on the index page, as well as for the post? I know that this is not the same as a cover image, but for the time being, it might do the job.

**Comment by StarfallProjects** [comment]
> I'm not sure what you mean. Should social cards also use the cover image as a background?

I meant make it an option to set the generated social cards as cover images.

**Comment by squidfunk** [comment]
I don't think they work well, since they're deliberately generated for social networks, i.e. the resolutions might be too low.

**Comment by squidfunk** [comment]
Also, please share some examples (links + screenshots) how you imagine cover images to look, e.g. by other blogs.

**Comment by squidfunk** [comment]
I just read [your article](https://starfallprojects.co.uk/blog/add-cover-images-to-blog-posts-in-material-for-mkdocs/#more-layout-tweaks) on how to add cover images. In fact, you don't need to use theme extension to do so, just add the image to the Markdown file. You can add it below:

<img width="735" alt="Bildschirmfoto 2022-09-14 um 21 12 49" src="https://user-images.githubusercontent.com/932156/190242403-08d621f0-cafb-4ef0-a39e-0ec0c41cc8a4.png">

... or above the headline:

<img width="746" alt="Bildschirmfoto 2022-09-14 um 21 13 34" src="https://user-images.githubusercontent.com/932156/190242467-75c94d35-36f8-4964-9395-5e2176751a07.png">

Example code:

``` markdown
---
date: 2022-09-12
authors: [squidfunk]
description: >
  Our new blog is built with the brand new built-in blog plugin. You can build
  a blog alongside your documentation or standalone
categories:
  - Blog
links:
  - Getting started with Insiders: insiders/getting-started.md#requirements
  - setup/setting-up-a-blog.md#built-in-blog-plugin
---

![K](https://placekitten.com/g/1440/900)

# Blog support just landed

__Hey there! You're looking at our new blog, built with the brand new
[built-in blog plugin]. With this plugin, you can easily build a blog alongside
your documentation or standalone.__
```

We can improve the spacing if the image is placed above, though. This allows the author to position the image as he likes.

**Comment by StarfallProjects** [comment]
I'll add that to the blog post. Will let the blog post stay as-is otherwise, as it's hopefully still a useful example for doing more complex customisation.

**Comment by squidfunk** [comment]
Great. Does that mean that this issue can be considered resolved?

**Comment by StarfallProjects** [comment]
I think it'd be nice to have an alternative (so you could for instance have a cover image on the index page but not in the post) But super-low priority.

**Comment by squidfunk** [comment]
I'd consider this an edge case, since just using Markdown offers the most flexibility.
