### ISSUE TITLE
Image link for hiding the sidebar is broken in the documentations

### ISSUE THREAD

**Issue by Jarmos-san** [squidfunk/mkdocs-material#4368]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The screenshot in the documentation showcasing how & how the sidebar looks like when its hidden is broken.

### Expected behaviour

The screenshot should be rendered appropriately.

### Actual behaviour

The Markdown hyperlink is broken hence the screenshot didn't render as expected.

![image](https://user-images.githubusercontent.com/31373860/190626439-af26f686-4135-4ed6-9a45-171187d03b24.png)

### Steps to reproduce

Head over to [this section](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hiding-the-sidebars) of the official documentations.

### Package versions

NA

### Configuration

```yaml
NA
```

### System information

NA

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in 930d07b76.
