### ISSUE TITLE
Guidance for mobile view

### ISSUE THREAD

**Issue by wyaadarsh** [squidfunk/mkdocs-material#438]
Hi,

Thank you for wonderful theme and updates. I have modified the theme to suit my design requirements and is able to create a documentation somewhat like this : 

<img width="945" alt="screen shot 2017-08-17 at 2 44 30 pm" src="https://user-images.githubusercontent.com/20237859/29405188-e09be0d6-835a-11e7-9255-cd9c7366ca9c.png">

The problem I am facing is in the mobile view. Our design requirements wants to have somewhat like this : 

<img width="281" alt="screen shot 2017-08-17 at 2 47 12 pm" src="https://user-images.githubusercontent.com/20237859/29406102-ab62b7a2-835d-11e7-8327-27f6c61c7d49.png">

Can you please guide me how can i implement this ? as the current version is just having a search icon and then an absolute placed search overlay.

Thanks

**Comment by squidfunk** [comment]
Sorry, but I cannot provide you with guidance because if I start doing that, everybody will ask for it. My time is very limited, so it's probably better invested in working on the core of the theme.

**Comment by squidfunk** [comment]
Closing this due to the reasons stated.
