### ISSUE TITLE
Error when upgrading material-mkdocs-insiders

### ISSUE THREAD

**Issue by fveauvy** [squidfunk/mkdocs-material#4385]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I received an error when trying to upgrade mkdocs-material-insiders package locally.

### Expected behaviour

The package should be upgraded.

### Actual behaviour

An error stop the process at the step `Preparing metadata (pyproject.toml) ... error`

### Steps to reproduce

1. Run the command : `pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git` using valid credential.

### Package versions

- Python: 3.10.6
- MkDocs: 1.3.0
- Material: 8.5.2+insiders.4.23.5

### Configuration

```yaml
Not related to my mkdocs project
```

### System information

- Operating system: macOS Monterey 12.5.1
- Browser: Google Chrome

Find the output below :

![CleanShot 2022-09-20 at 17 24 49](https://user-images.githubusercontent.com/38651917/191299287-5d14cf80-8354-4713-b8a8-745d49607772.png)

**Comment by squidfunk** [comment]
Thanks for reporting! Already resolved with the latest commit on Insiders. The latest release has been reissued 😊

**Comment by squidfunk** [comment]
Related:

- #4341

**Comment by fveauvy** [comment]
Thanks for your ultra-fast fix :D

**Comment by jaceklaskowski** [comment]
If you faced this issue again (even after the fix), make sure you really have the fix (the commit) locally. Best is to refresh the tag. It is probably "broken" locally and git won't update it unless forced (deleted and recreated).

``` shell
git tag -d 8.5.3-insiders-4.23.5
```
