### ISSUE TITLE
application.js:1095 Uncaught ReferenceError: Invalid left-hand side in assignment

### ISSUE THREAD

**Issue by davidandgoliath** [squidfunk/mkdocs-material#44]
Just a quick note, when grabbing the latest mkdocs-material release from site (git clone, not via pip), the search functionality is broken due to whatever's going on in application.js on line 1095. This could be user-error in my case, but I follow instructions well.

I wasn't able to narrow down the cause & ended up using the pip installed version's static files to make the customizations I needed.

Edit: Regardless, great work overall! Love the template, and can't wait to launch something with it.

**Comment by squidfunk** [comment]
Thank you for the notice, I will investigate.

**Comment by squidfunk** [comment]
I cannot reproduce this issue. What I tried:

```
mkdocs new test
cd test
git clone git@github.com:squidfunk/mkdocs-material.git
echo "theme_dir: mkdocs-material/material" >> mkdocs.yml
mkdocs serve
```

Then go to localhost:8000 and everything's working fine, no error in the console. I even tried checkout out the latest release 0.2.4, but also, no error. Can you elaborate on what you did exactly?

**Comment by davidandgoliath** [comment]
Well, shucks — I see what the issue is now.
I cloned mkdocs-material & used the mkdocs.yml file in the cloned folder as the installation. I see now if I use mkdocs one folder up, it works fine.

**Comment by squidfunk** [comment]
Could you please give some more details on the browser and operating system you are using when you encountered the error, because the thing you did should work as well. Thank you!

**Comment by davidandgoliath** [comment]
Macosx (latest non-beta). Chrome. Safari, all browsers — same issue.
I am making one modification to a core file — that is, nav.html — and rebuilding the theme using the commands you've provided. Doing my mod. with the pip version works fine, just not the cloned version.

Here's my change for reference (just adding the ability to 'hide' files based on the mkdocs reference title:

```{% if nav_item.children %}
  <li>
    <span class="section">{{ nav_item.title }}</span>
    <ul>
      {% for nav_item in nav_item.children %}
        {% include "nav.html" %}
      {% endfor %}
    </ul>
  </li>
{% else %}
  <li>
{% if not nav_item.title.startswith("&nbsp;") %}
    <a class="{% if nav_item.active %}current{% endif %}" title="{{ nav_item.title }}" href="{{ nav_item.url }}">
      {{ nav_item.title }}
    </a>
    {% if nav_item == current_page %}
      {% if h1 %}
        {% set toc = (toc | first).children %}
      {% endif %}
      {% if toc and (toc | first) %}
        <ul>
          {% for toc_item in toc %}
            <li class="anchor">
              <a title="{{ toc_item.title }}" href="{{ toc_item.url }}">
                {{ toc_item.title }}
              </a>
            </li>
          {% endfor %}
        </ul>
      {% endif %}
     {% endif %}
    {% endif %}
  </li>
{% endif %}```

**Comment by squidfunk** [comment]
The npm warnings should be no problem, they are generated by the dependencies of the packages the theme is using. However, I can now finally reproduce the error! It originates in the `pegasus` library which is used to load the search JSON file:

```
1095: pegasus.timeout && xhr.timeout = pegasus.timeout;
```

This change was introduced in 0.3.4. I pinned the version to 0.3.3, as this change was introduced in 0.3.4. With Material 1.0.0 there will be no need for pegasus, so as a temporary fix this should be okay.

Thank you for your cooperation!

**Comment by davidandgoliath** [comment]
Most excellent! Thanks for your persistence & all your effort with the project — <3
