### ISSUE TITLE
Include sections from other files

### ISSUE THREAD

**Issue by userbradley** [squidfunk/mkdocs-material#4414]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I am writing documentation where there are large blocks of text that are used in each page (Documentation for kubernetes) [site](https://kubernetes.breadnet.co.uk)

The issue becomes when I need to update them, to change a word or fix a bad copy and paste job, I have to do it over literally hundreds of files

I have tried to the use `snippets` from the [docs](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#overview), but no luck

![image](https://user-images.githubusercontent.com/41597815/192280645-cec05eef-479d-4d9c-8a17-dd862e693e3d.png)

```markdown
#docs/builtin/deployment.md
#### Namespace

The namespace the Deployment should go to


--8<-- "service-file.md"

```

```
.
├── Dockerfile
├── LICENSE
├── README.md
├── cd
│   └── codefresh-v1.yml
├── docs
│   ├── argo
│   │   └── repo.md
│   ├── builtin
│   │   ├── deployment.md
│   │   └── service.md
│   ├── examples
│   ├── google
│   │   └── networking
│   ├── index.md
│   ├── service-file.md
│   └── template.md
├── file.yml
├── mkdocs.yml
└── nginx.conf

```

### Use Cases

Kubernetes has a field `namespace` on **all** resources, so it would be nice to do something like the below

`deployment.md`
```markdown

#### Namespace

!include docs/namespace.md

```yaml
metadata:
  name: hello-v3
  namespace: default

\```

```

`docs/namespace.md`

```markdown
A namespace is a logical blah blah blah, this would usually be several lines etc etc
```

**Comment by squidfunk** [comment]
Thanks for reporting. There's already an issue at Python Markdown extensions: https://github.com/facelessuser/pymdown-extensions/issues/1462.

Closing as upstream issue.

**Comment by userbradley** [comment]
Thanks @squidfunk - Appreciate it

**Comment by userbradley** [comment]
@squidfunk the issue has since been closed upstream, and I'm still unable to do this.

I have definitly missed something, but in my config I have the below

```yaml
markdown_extensions:
  - pymdownx.snippets
```

Then have 

```markdown
<!-- index.md -->
## What this page will cover

--8<-- "legal.md"
```

```markdown
<!-- legal.md -->
??? error "The legal stuff"

    **This is information – not financial advice or recommendation**
    
    The content and materials featured or linked to on [New starter Docs](/) are for your information and education only and are not attended to address your particular personal requirements.
    
    The information does not constitute financial advice or recommendation and should not be considered as such. 
    
    **Do your own research and seek independent advice when required**
    
    Always do your own research and seek independent financial advice when required. Any arrangement made between you and any third party named or linked to from the site is at your sole risk and responsibility. ,. and its associated writers assume no liability for your actions.
```

Thoughts?

**Comment by squidfunk** [comment]
Without a [reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/), I'm not able to look into it.

**Comment by userbradley** [comment]
I actually got it working. Apologies for wasting your time.

I found that I had to do the below

```markdown
--8<-- "docs/test.md" 
```

Where as the documentation says to 

``` markdown
--8<-- ".browserslistrc"
```

Seems like it's just missing the full path to the file from `docs`

Do you want me to open a PR to update the documentation or have I still gone about this the wrong way?

**Comment by squidfunk** [comment]
It is heavily dependent on how you configure the Snippets extension. Also, in your case, you wanted to include another document, but other users might want to include files in other directories. For example, the section in the documentation you mentioned talks about [embedding external files with respect to code blocks](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#embedding-external-files), which rarely live in the docs directory.

Your use case is much more similar to [adding a glossary](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-a-glossary), which has a better example. Also, correct me if I'm wrong, but I think the project root is only the default.  Thus, if you would like to propose a change, please keep all of this in mind.
