### ISSUE TITLE
Hugo theme

### ISSUE THREAD

**Issue by pjebs** [squidfunk/mkdocs-material#4423]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

I came across your hugo version: https://hugothemesfree.com/port-of-martin-donaths-mkdocs-material-theme-to-hugo/

There is a demo of it here: https://camp-warden-mousedeer-75764.netlify.app/getting-started/

I was wondering why it looks and feels different from this demo: https://squidfunk.github.io/mkdocs-material/getting-started/

### Expected behaviour

I thought it should look and feel similar.

### Actual behaviour

Totally different.

### Steps to reproduce

https://camp-warden-mousedeer-75764.netlify.app/getting-started/ vs  https://squidfunk.github.io/mkdocs-material/getting-started/

### Package versions

no idea

### Configuration

```yaml
no idea
```

### System information

macOS 12.1

**Comment by facelessuser** [comment]
I think that was a port of @squidfunk's very early work related to Material. As it is a port, @squidfunk is not the one who created the port, and, likely, the port has not kept up with recent changes in design.

**Comment by pjebs** [comment]
Do you at what year the template changed to this new design. I prefer the older design.

**Comment by squidfunk** [comment]
@facelessuser is right, it's a port by another developer. The Hugo theme was based on version 0.x. We're now at 8.x, so way ahead. You can check out Material for MkDocs version 0.2.1 if you prefer the old design, but it has none of the modern features. It should also be possible to adapt the current design to be similar to the old design with some CSS skills.
