### ISSUE TITLE
Creating a Progressive Web app from the mkdocs github published pages

### ISSUE THREAD

**Issue by Harsh-Maheshwari** [squidfunk/mkdocs-material#4425]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

There are previous issues related to progressive web app, but they seem to have been over written and there is no longer a feature to make progressive web apps, I could not find anything in the documentation as well, Is this a feature that is under development? 

### Use Cases

Easy Offline Access and distribution of an app

**Comment by squidfunk** [comment]
Thanks for suggesting. It's currently not considered for development, see discussion in:

- #1405
- #2105
