### ISSUE TITLE
Documentation Social Cards: Dependency installation on Windows (Cairo)

### ISSUE THREAD

**Issue by ruudvh** [squidfunk/mkdocs-material#4426]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The documentation on [Setting up social cards ](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/) suggests [installing windows dependencies ](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/#dependencies) by installing GTK through the official provided installation instructions. This works but isn't super straightforward (instructions require you to install MSYS2, installing GTK, its dependencies, then any needed binding, etc etc).

An easier installation is through a [precompiled GTK runtime](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases). Download, launch, and it works.
(Runtime found through the [mkpdfs-mkdocs-plugin](https://github.com/comwes/mkpdfs-mkdocs-plugin), which requires [WeasyPrint](https://doc.courtbouillon.org/weasyprint/latest/first_steps.html#windows), which in turn also requires GTK)

I understand this adds an additional dependency on a external maintainer, but perhaps expanding the existing paragraph would suffice?

> As stated in the [installation guide](https://www.cairographics.org/download/), the easiest way to get up and running with the [Cairo Graphics](https://www.cairographics.org/) library on Windows is by installing [GTK+](https://www.gtk.org/docs/installations/windows/), since it has Cairo as a dependency. You can also download and install a precompiled [GTK3 installer](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer/releases).

Thoughts?

### Use Cases

A quicker way to get `social cards` up and running on Windows.

**Comment by squidfunk** [comment]
Thanks for suggesting! I'm not a Windows user, so I need to rely on external documentation or contributors that explain how to install `libcairo` on Windows. You can PR the suggested documentation change if you like.

**Comment by squidfunk** [comment]
Adjusted the documentaiton in ebe186a7f.
