### ISSUE TITLE
Potential crash in src/assets/javascripts/components/source/facts/_/index.ts

### ISSUE THREAD

**Issue by RyanCavanaugh** [squidfunk/mkdocs-material#4451]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

TypeScript 4.9 identified an issue with this code:

https://github.com/squidfunk/mkdocs-material/blob/d8bd7bdb059f35838aabffda059d1be6dd826d3f/src/assets/javascripts/components/source/facts/_/index.ts#L71-L72

The code appears to acknowledge that `match` might return a falsy value, but in that case defaults to `[]`, which would make `type` `undefined` and cause a crash on the subsequent call to `toLowerCase`.

### Expected behaviour

Not sure, otherwise I'd send a PR

### Actual behaviour

TypeScript 4.9 doesn't like it

### Steps to reproduce

N/A, code defect

### Package versions

- Python: `python --version`
- MkDocs: `mkdocs --version`
- Material: `pip show mkdocs-material | grep -E ^Version`

### Configuration

```yaml
Github main branch
```

### System information

N/A

**Comment by squidfunk** [comment]
Thanks for reporting, Ryan! Indeed, the control flow is not ideal. I've refactored it in 6344549ec, which also gets rid of the issue you reported. I've validated with TypeScript 4.9.1-beta. that the error is in fact gone.

**Comment by squidfunk** [comment]
7ca1c1d62 also gets ride of the now unnecessary `!`.

**Comment by squidfunk** [comment]
I'm closing this issue now, as it has no impact on users of Material for MkDocs since it's an internal implementation detail that is not exposed to the user – the user only sees the final JS.
