### ISSUE TITLE
Is it possible for a hidden tab?

### ISSUE THREAD

**Issue by thangckt** [squidfunk/mkdocs-material#4464]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

Dear Developers, 

Is it possible to render a hidden tab? 

### Use Cases

For example, we have some tabs, and some of them are hidden from the tab bar, and they are only available when we input their URLs in address bar of the browser

**Comment by squidfunk** [comment]
Thanks for asking. This can not be configured, no, but you can customize and [extend the theme](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme), either with CSS (target and hide a specific element) or by [overriding the `tab-item` partial](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials), e.g. by and adding a `hidden` property to the page, extending the tab partial to respect the `hidden` property and not render it. I consider this a rather non-canonical use case, but you should be able to pull it off with theme extension. Closing as out-of-scope.
