### ISSUE TITLE
Support for "compliance status"

### ISSUE THREAD

**Issue by petemounce** [squidfunk/mkdocs-material#4492]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I'm not certain how this might be achieved via a static-only website, I'll lead with, but...

We have a need to comply with various security-and-other standards to maintain various certifications.

To support this, we must document our internal processes (for example). That's fine.

We must also ensure that staff have read those. That's harder.

However, 
1. it can be hard for an individual to know when a document that they're supposed to comply with gets updated. That person needs to go read it (hopefully just the diff) and update their internal understanding. How does a (not necessarily technical git-aware) person figure out what to go read up on since the last annual compliance dance?
2. it can be hard for a manager or process-owner to ask particular people to go update themselves.

### Use Cases

# Individual

- somehow browse to / search for a list of pages (ideally with diffs-since-last-time) to go and read, then indicate "yup, read it, compliant!"

# Organisation

- somehow see compliance staleness across people browsing the site (it's the org's problem to chase people who have _never_ browsed the site :) )
- get a list of people to chase for "please read x, critical update!" - so, list grouped by site nav hierarchy / page
- get a list of pages that are generally un-read to take action (like promote them more widely, burn them, etc)

**Comment by squidfunk** [comment]
Thanks for suggesting. That's definitely related to content and not theme-dependent. Thus, out of scope. Closing.
