### ISSUE TITLE
Lazily loaded images displace anchoring

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#4494]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

A lazily loaded image right before an anchor will move the anchor down on page load

### Expected behaviour

Links to anchors should stay on top

### Actual behaviour

Anchor moves down

### Steps to reproduce

https://hatch.pypa.io/latest/blog/2022/10/08/hatch-v160/#virtual-environment-location

```markdown
![FastAPI readme](release-hatch-160/rich-readme.png){ loading=lazy }

## Virtual environment location
```

### Package versions

- Python: `3.10.7`
- MkDocs: `1.4.0`
- Material: `8.5.6-insiders-4.25.2`

### Configuration

```yaml
markdown_extensions:
  - markdown.extensions.attr_list:
```

### System information

- Operating system: Windows
- Browser: Chrome

**Comment by squidfunk** [comment]
Thanks for reporting. I understand that this is a problem, but it's not specific to Material for MkDocs. It's the same for every website and is very hard to fix for _all_ browsers given that they behave differently. For this reason, any fix (recomputing placement after images have been loaded) is independent of Material for MkDocs.
