### ISSUE TITLE
Favicon size limit

### ISSUE THREAD

**Issue by mikedeischle** [squidfunk/mkdocs-material#4495]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If you set large images as favicon it will not appear.    
In my example I've tested 2 pictures `flower.png` (171 KB) and `street.png` (740 KB):    
https://github.com/mikedeischle/mkdocs-favicon-test

Pictures >200MB don't worked for me.

### Expected behaviour

favicon should be visible

### Actual behaviour

favicon is not visible

### Steps to reproduce

1. Set large picture as favicon
1. Shrink image and set again

### Package versions

- Python 3.10.2
- mkdocs 1.4.0
- mkdocs-material 8.5.6

### Configuration

```yaml
theme:
  name: material
  language: de
  font: false
  logo: assets/street.png
  favicon: assets/street.png
```

### System information

Tested with:
- Operating system: Windows 10, AWS S3 Bucket
- Browser: Firefox, Chrome

**Comment by mikedeischle** [comment]
@squidfunk as discussed here [gitter.im](https://gitter.im/squidfunk/mkdocs-material?at=6347395bcb3b24352811b531)

**Comment by squidfunk** [comment]
Thanks for reporting. So from your report I read that you tested it with the `mkdocs` and `readthedocs` themes (note that [configuration is slightly different](https://www.mkdocs.org/getting-started/#changing-the-favicon-icon), and it works fine, but when used with `material`, the icon is not shown?

**Comment by mikedeischle** [comment]
Sorry to be honest I don't checked it, because it is also working in a different way.  
mkdocs itself don't support png at al afaik. See: https://www.mkdocs.org/getting-started/#changing-the-favicon-icon (just .ico)

**Comment by squidfunk** [comment]
Please ask this question on StackOverflow then. It is not solely related to Material for MkDocs, as we only set the appropriate `meta` tag if the `favicon` configuration option is given, nothing more. Feel free to come back when you found a solution.

**Comment by mikedeischle** [comment]
afaik mkdocs only support icons so `.ico` and no pictures. 
In your docs you recommend to add a `.png` a small hint there that is shouldn't be larger then 256*256 px would be nice. 
So I think that's also the issue here.

**Comment by squidfunk** [comment]
Is that the case for browsers? Do you have a link/source to back that up?

**Comment by mikedeischle** [comment]
Is is just an idea after some searching. 
But you can try it with my example and it will show you that it could be the issue. 
Anyways large pictures are not possible at all so a hint about that would be nice.
