### ISSUE TITLE
Feature suggestion: Compact tabbar

### ISSUE THREAD

**Issue by thangckt** [squidfunk/mkdocs-material#4502]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [ ] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [ ] ... there are no open or closed issues that are related to my idea

### Description

Dear Developer, 

To have more reading pace, can you allow a setting for a "compact tabbar"
Something like the  below figure

### Use Cases

It will allow more space for contents, specially on some laptop screeens.

### Screenshots / Mockups

![Untitled](https://user-images.githubusercontent.com/46436648/196005338-eb3c0e9d-79e8-4280-b799-ebdb0c7515d1.png)

**Comment by squidfunk** [comment]
Thanks for suggesting. This was asked in #3931 and PR'd in #3936 which was rejected for the reasons described in the PR. However, the PR should give you guidance how to achieve it via theme extension!

**Comment by thangckt** [comment]
Dear @squidfunk 

Thank you for guiding.
