### ISSUE TITLE
Enhance tag page([TAG]) display

### ISSUE THREAD

**Issue by jasonren0403** [squidfunk/mkdocs-material#4503]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The tag page is displaying lists of content all in one column, the page may become too long and lots of spaces are not used. Now, the tag page only generate contents by replaceing `[TAG]` into list of markdown, and does not doing too much styling.

### Use Cases

Display multiple columns to take up much spaces caused by too long tag list.

### Screenshots / Mockups

before(you can also see the current live version on https://note.jason0743.best/tags.html 😆)
![image](https://user-images.githubusercontent.com/40999116/196013129-b2b64357-e24c-4534-8d2c-03c625f960bc.png)

after(simple mockup by applying `column-count:3` on `ul` element, extra classes may be added)
![image](https://user-images.githubusercontent.com/40999116/196013146-3ea20da6-ba5c-4452-a488-6ccad42e9435.png)

I've searched the usage of `column-count` at https://caniuse.com/?search=column-count, and it's wide enough for current browsers.

**Comment by squidfunk** [comment]
Thanks for suggesting. I understand that Japanese and Chinese titles might run much shorter than for example English titles, but if we would add this to the theme, it would be the same for all languages. Using additional CSS, as you did, is the way to go, since you can tweak it to your taste 😀
