### ISSUE TITLE
Search boosting does not affect sections

### ISSUE THREAD

**Issue by ekoleda-codaio** [squidfunk/mkdocs-material#4511]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Search boosting is not being applied to section entries on the page.

### Expected behaviour

When a boost is applies to a page, all content on the page receives the boost.

### Actual behaviour

Only the entry for entire page receives the boost. Entries for the individual sections of the page don't receive the boost.

### Steps to reproduce

1. Add search boosting to a page that has multiple sections (h2 headers).
2. Build the doc.
3. Look at `search_index.json`.

Only the entry corresponding to the entire page will have the boost. The entries corresponding to sections of the page will not.

Looking at the code, the boost is only applied to a single entry, but the search plugin generates multiple ones. A solution may involve searching over all of the entries for ones that point to the same page, and applying the boost to all of them.

https://github.com/squidfunk/mkdocs-material/blob/f13a5526d024bb646f4dfdb48904a8adea81d026/src/plugins/search/plugin.py#L45-L67

### Package versions

- Python: 3.10.7
- MkDocs: 1.3.1
- Material: 8.5.2

### Configuration

```yaml
N/A
```

### System information

N/A

**Comment by squidfunk** [comment]
Thanks for reporting – that's unintended.

**Comment by squidfunk** [comment]
Fixed in 922fde070. Boosts are now applied to all sections of a document. This still needs to be merged into Insiders, which will take a little more time given the difference search implementation. I'll follow up shortly.

**Comment by squidfunk** [comment]
Released as part of 8.5.7. Insiders did not exhibit this behavior.
