### ISSUE TITLE
tags_extra_files non-functional

### ISSUE THREAD

**Issue by MSU-ICER-ADMIN** [squidfunk/mkdocs-material#4516]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Tried to add tags_extra_files to auto-generate index pages. Works if the tags are not filtered, but adding a tag filter breaks with this traceback:

```ERROR    -  Error reading page 'Lab_Notebooks.md': 'in <string>' requires string as left operand, not NoneType
Traceback (most recent call last):
  File "/home/andrew/mambaforge/envs/build-docs/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 82, in serve
    builder(config)
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 75, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/mkdocs/commands/build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
    page.markdown = config.plugins.run_event(
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/mkdocs/plugins.py", line 517, in run_event
    result = method(item, **kwargs)
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/material/plugins/tags/plugin.py", line 93, in on_page_markdown
    return self._render_tag_index(
  File "/home/andrew/mambaforge/envs/build-docs/lib/python3.10/site-packages/material/plugins/tags/plugin.py", line 147, in _render_tag_index
    if self.tags_type_map.get(key) in included:
TypeError: 'in <string>' requires string as left operand, not NoneType```

### Expected behaviour

Tag extra file should have a list of other pages with only the requested tag(s)

### Actual behaviour

Traceback occurs, see description.

### Steps to reproduce

1. Add tags_extra_files to yml
2. Add specific file
3. Add specific tag
4. Try to compile

### Package versions

- Python: `python --version` 3.10.6
- MkDocs: `mkdocs --version` 1.4.1
- Material: `pip show mkdocs-material | grep -E ^Version` 8.5.6+insiders.4.26.0

### Configuration

```yaml
plugins:

  # Entries that are overridden by inheritance MUST be in the "entry: {}" format

  # not the "- entry" format

  search:

    lang: en

  tags:

    tags_file: tags.md

  git-revision-date-localized:

    enable_creation_date: true

INHERIT: mkdocs.yml

plugins:

  # Entries that are overridden by inheritance MUST be in the "entry: {}" format

  # not the "- entry" format



  # Adds authors to page entries

  git-authors: {}

  # Allows adding additional tag contents pages

  # Tags to be included in a contents page must be specified

  # Otherwise all tags are included

  tags:

    tags_extra_files:

      Lab_Notebooks.md: lab notebook

      #      accessHPCC_overview.md: {}

      #      filesystem_overview.md: {}

      #      Powertools.md: {}

      #      SLURM_overview.md: {}



extra:

  tags:

    lab notebook: no_icon
```

### System information

- Operating system: Linux
- Browser: Firefox

**Comment by squidfunk** [comment]
Thanks for reporting. Please provide a minimal reproducible example that showcases the issue and attach it here as a zip.

**Comment by andrewfullard** [comment]
[tags-extra-files.zip](https://github.com/squidfunk/mkdocs-material/files/9823356/tags-extra-files.zip)
Here's a minimal reproducible example. I am part of the team MSU-ICER.

**Comment by squidfunk** [comment]
Thanks! I'll look into it.

**Comment by squidfunk** [comment]
You're using invalid syntax in `mkdocs.yml`:

``` yaml
plugins:
  tags:
    tags_file: tags.md
    tags_extra_files:
      extra_tags_page.md: extra tag # <-- invalid
```

Additional tags must be specified as a list, not as a string:

``` yaml
plugins:
  tags:
    tags_file: tags.md
    tags_extra_files:
      extra_tags_page.md:
        - extra tag
```

Please always stick to the syntax [as described in our documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#+tags.tags_extra_files). If you deviate and use other values, you'll be getting undefined behavior which is what you're observing. Additionally, it's recommended to set up [configuration validation](https://squidfunk.github.io/mkdocs-material/creating-your-site/#minimal-configuration).

**Comment by squidfunk** [comment]
You're right, there still seems to be another problem.

**Comment by squidfunk** [comment]
It's still a configuration error – you don't link tags, but [tag identifiers](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#adding-tags). This means that you need to assign each tag to an identifier. You can assign multiple tags to the same identifier:

``` yaml
plugins:
  tags:
    tags_file: tags.md
    tags_extra_files:
      extra_tags_page.md:
        - foo # <-- identifier
        - bar
extra:
  tags:
    Foo: foo <-- same identifier
    Bar: bar
    Bar 2:  bar
```

This is also explained in the documentation:

![Bildschirmfoto 2022-10-22 um 08 52 39](https://user-images.githubusercontent.com/932156/197311378-ab18dd0e-e117-4dff-9d10-c8bb0e70938e.png)

**Comment by squidfunk** [comment]
I'll leave this issue open and try to improve the documentation, so it's more clear.

**Comment by squidfunk** [comment]
I've improved error reporting in squidfunk/mkdocs-material-insiders@eb85bd2bd, making error messages less cryptic.

**Comment by andrewfullard** [comment]
Thanks for the clarification. I would agree that the documentation is not clear enough, the linked issue seems to do a lot of the work in explaining the feature.

**Comment by squidfunk** [comment]
Improved documentation in 6e0052d4fa2703b07e2cc3dca43459af39df9175.
