### ISSUE TITLE
Illegible text color in dark scheme for mermaid diagram

### ISSUE THREAD

**Issue by 2bndy5** [squidfunk/mkdocs-material#4517]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

If a picture is worth a thousand words, then please observe these [snapshots from the mkdocs-material docs](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#using-sequence-diagrams)
![image](https://user-images.githubusercontent.com/14963867/196832465-0a9ee9ab-7f09-42cb-95d2-bdb8a3f5132f.png)
But notice that the "post-it note" node is legible in the light scheme:
![image](https://user-images.githubusercontent.com/14963867/196832581-a004caa5-cdd5-4705-be93-6138cf9137bf.png)

### Expected behaviour

If the node's bg color is static, then I would expect the text color also be static and legible.

After playing with it in my browser (Firefox), I was able to achieve expected behavior by removing the `.noteText > tspan` specifier from https://github.com/squidfunk/mkdocs-material/blob/60ea10a028e932bfaadd5caea76718728ec69d8f/src/assets/javascripts/components/content/code/mermaid/index.css#L340-L347

### Actual behaviour

See description

### Steps to reproduce

Whatever the docs CI is doing.

### Package versions

I'm merging updates from here (v8.5.6) into sphinx-immaterial and I noticed this in our rendered docs (local only for now). After checking with the docs here, I found the same problem.

### Configuration

```yaml
See this repo's mkdocs config.
```

### System information

- Operating system: Whatever the docs CI is using.
- Browser: Firefox

**Comment by 2bndy5** [comment]
Sorry the compiled CSS is a bit different from the SCSS, and I just search for the `.noteText` in the repo and pointed to the only hit in SCSS... I'll keep digging and try to submit a PR soon.

I prefer to only merge updates from stable releases, but if we can get the fix for this from this repo's main branch, then I might break that tradition for just this time.

**Comment by squidfunk** [comment]
Thanks for your help! You need to set up the [theme development process](https://squidfunk.github.io/mkdocs-material/customization/#theme-development) to preview your changes, but given that you use this project downstream, it should be a good idea anyways.

> I prefer to only merge updates from stable releases, but if we can get the fix for this from this repo's main branch, then I might break that tradition for just this time.

I'm not sure what you mean by stable releases, because our `master` off which all releases are created can be considered stable. Yes, there will always be bugs, sometimes regressions, but I try to fix them as fast as possible 😅

**Comment by 2bndy5** [comment]
Yeah, the workflow downstream is pretty much the same.

> I'm not sure what you mean by stable releases, because our master off which all releases are created can be considered stable. Yes, there will always be bugs, sometimes regressions, but I try to fix them as fast as possible 😅

Oh, good to know. I'll still try to focus only on tagged commits (my interpretation of "stable releases"), so it would be easier to help diagnose bug reports (if/when we get them). That way your changelog/release description(s) is more useful 😄

**Comment by squidfunk** [comment]
Released as part of 8.5.8.
