### ISSUE TITLE
Optionally only access other languages than the current

### ISSUE THREAD

**Issue by mondeja** [squidfunk/mkdocs-material#4529]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

It would be great if mkdocs-material could have some option to only access other languages than the current from the language selector. This is currently possible by a hacky way in a plugin that I've created: [mkdocs-material-relative-language-selector](https://github.com/mondeja/mkdocs-material-relative-language-selector).

### Use Cases

The use case is just to avoid pressing a button that just would refresh the page.

**Comment by squidfunk** [comment]
Thanks for suggesting. So you're effectively asking whether your plugin could be natively integrated into Material for MkDocs? I don't really understand the use case, i.e., why it is necessary. Furthermore, judging by its stars, the plugin is not very popular, so I'm not sure it will benefit many users. I have to very careful deciding what I can maintain and what not.

**Comment by squidfunk** [comment]
Thinking about it, you don't even need a plugin. You can achieve the same by [overriding the `header.html` partial](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials) – just add a check for the language in the partial loop rendering all options (line 120 to 130):

https://github.com/squidfunk/mkdocs-material/blob/c6d804b0ea0249b4a7a2bcffbc2022b39f8ce8c4/src/partials/header.html#L107-L135

For this reason, I'm closing this issue. It can be achieved with customization.
