### ISSUE TITLE
Improve This Page Feature

### ISSUE THREAD

**Issue by Mehran-Baghi** [squidfunk/mkdocs-material#453]
## Description

It would be a very nice (Optional) feature to have a link near the title of each page that leads to the markdown source of that page. That way users can easily submit improvements to the document. Github supports such edit links, for example:
* File:
https://github.com/squidfunk/mkdocs-material/blob/master/docs/customization.md
* Edit Link:
https://github.com/squidfunk/mkdocs-material/edit/master/docs/customization.md

Jekyll example: https://github.com/jekyll/jekyll-help/issues/5
### Expected behavior
**Pencil Icon** in https://hexo.io/docs/

**Comment by facelessuser** [comment]
This is already possible: http://facelessuser.github.io/pymdown-extensions/.

You may want to read up on the Mkdocs documentation to learn more: http://www.mkdocs.org/.

I don't recall the exact steps to make sure it works, but I believe all I had to do was setup the `edit_uri` setting: https://github.com/facelessuser/pymdown-extensions/blob/master/mkdocs.yml#L4, but you'll have to look into it further.

**Comment by Mehran-Baghi** [comment]
Thank you @facelessuser 
Yes it's [here](http://www.mkdocs.org/user-guide/configuration/#edit_uri)
