### ISSUE TITLE
Footnotes in figcaption

### ISSUE THREAD

**Issue by askurashev** [squidfunk/mkdocs-material#4530]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Footnotes link not parsed when placed in `figcaption`.

### Expected behaviour

```
<figure markdown class="inline end">
  ![Image title](/media/image.jpg){ width="300" align=right loading=lazy}
  <figcaption>Text[^1]</figcaption>
</figure>
```

### Actual behaviour

-

### Steps to reproduce

-

### Package versions

- Python: `python --version` 3
- MkDocs: `mkdocs --version` last
- Material: `pip show mkdocs-material | grep -E ^Version` last

### Configuration

```yaml
standard config with footnotes option
```

### System information

- Operating system: Windows
- Browser: Chrome

**Comment by facelessuser** [comment]
This is not a Material issue.

Python Markdown does not parse Markdown inside of raw HTML unless  the `md_in_html` extension is enabled and block elements use the `markdown` attribute:

```html
<figure markdown class="inline end" markdown>
  ![Image title](/media/image.jpg){ width="300" align=right loading=lazy}
  <figcaption markdown>Text[^1]</figcaption>
</figure>
```

**Comment by askurashev** [comment]
How can this limitation be bypassed?

**Comment by facelessuser** [comment]
What limitations? I mentioned how you can bypass this, are you still having issues? Are you having some other issue or do you need more information?
