### ISSUE TITLE
Blog post URL slug based on filename

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#4543]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I would like to be able to generate post URLs based on the file name.

For example `posts/signal-configuration.md` with the title `2022 Signal Configuration and Hardening Guide` would be at `/YYYY/MM/DD/signal-configuration/` instead of `/YYYY/MM/DD/2022-signal-configuration-and-hardening-guide/`.

### Use Cases

This would allow me to update headlines without breaking all past links.

**Comment by squidfunk** [comment]
Thanks for suggesting. While I don't think it's a very common use case, it's trivial to implement. I've added support for substituting `{file}` in the URL in squidfunk/mkdocs-material-insiders@da6c5dcfde6b11e9984444d077fe1f28346bcb6a.

**Comment by jonaharagon** [comment]
This is working perfectly for me, thanks!
