### ISSUE TITLE
Specify content license information in blog post metadata

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#4544]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I'd like to be able to specify a `license` string (for example, a Creative Commons license) in the page metadata of posts, and have that license displayed in the left sidebar.

Unsure if this is too niche, but I'm asking because it will save me a custom page layout... More generically, maybe the sidebar could be split into partials so I can override only the relevant components?

### Use Cases

For multi-contributor blogs we might have authors who want to publish their posts under a license that is different from the site; or we might syndicate content from other websites which is made available under content licensing different than our own; or we might want to publish posts with a different license than our main documentation, and want to make that difference immediately clear.

### Screenshots / Mockups

https://github.com/privacyguides/blog.privacyguides.org/blob/main/theme/blog-post.html#L103-L134

Not sure if this way makes the most sense, but it's what we do. This code sets the Creative Commons logo and links to the relevant license text if a known CC license is set in the page's metadata, otherwise it shows whatever string `license` is set to and a generic `material/scale-balance` icon, and if `license` is not set at all it says "(c) All rights reserved." (It just now occurs to me that this line in the sidebar could be omitted if the license is not set, and if I wanted a default "All rights reserved" I could set that in `.meta.yml`...)

<img width="221" alt="Screenshot 2022-10-24 at 16 14 26@2x" src="https://user-images.githubusercontent.com/3637842/197630755-3dedbdb5-06b5-4fc3-b552-ca5d7db6f166.png">

**Comment by squidfunk** [comment]
Thanks for suggesting. I understand that users may want to add additional content to the sidebar and customize appearance, but please note that the blog plugin currently is considered very experimental. This means that templates and code is subject to change. I'm not a fan of starting to early factoring out code into partials, but I agree that we should make overriding simpler in the future.

First, we need to collect some feedback to distill the common cases to gravitate towards more flexible customization. Until then, please override the partials and check if they need to be adjusted when upgrading.
