### ISSUE TITLE
Hyperlink blog post h1 title on index to post

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#4545]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Clicking a post title on the blog's index page should open that blog post.

I wonder if this is difficult because the post title is just part of the Markdown page content, but I've clicked the post headline only for it to do nothing enough times to warrant requesting this.

### Use Cases

This is how every other blog works, it's the expected UX I think.

**Comment by squidfunk** [comment]
Thanks for suggesting. This is a reasonable request. It's not simple, because the blog index pages may contain any content that is before the post separator, so there doesn't even need to be an `h1`, but we can certainly try to add support for this. We will likely need to parse the resulting HTML of each blog post and wrap each `h1` with a link.

**Comment by squidfunk** [comment]
Released as part of 8.5.8+insiders-4.26.2.

**Comment by hellt** [comment]
@squidfunk 
Is it expected that only the permalink icon is clickable, and not the title string?
![2022-11-04_11-56-57 (1)](https://user-images.githubusercontent.com/5679861/199956695-930c48f0-7adc-4b4d-be79-65923cbd701d.gif)

**Comment by squidfunk** [comment]
@hellt no, the whole title [as on our blog](https://squidfunk.github.io/mkdocs-material/blog/). Ensure that you upgraded correctly.

**Comment by hellt** [comment]
@squidfunk I upgraded correctly, using the unmodified container build procedure.
I think this might have something with the way that I still have permalink marker and your blog doesn't. Need to figure out how to disable it maybe?

**Comment by hellt** [comment]
@squidfunk 
yes, I had an outdated (?) configuration for the custom `toc` char:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/5679861/199972656-ad1a6405-ed5f-4977-95ca-bd7e84c081b8.png">
this change fixed it
