### ISSUE TITLE
Embedding external files - Validate snippets source file existence

### ISSUE THREAD

**Issue by woutervanranst** [squidfunk/mkdocs-material#4561]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

As per https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#embedding-external-files

Could the output show a WARNING when a snippet is referenced that does not exist (ie the file does not exist)?

````
```
--8<-- "i.do.not.exist.file"
```
````

![image](https://user-images.githubusercontent.com/6490925/198571497-9dce4efe-5828-4720-a4d8-a5b8b0c592a0.png)

### Use Cases

Especially for larger doc sets, ensure refactoring snippets does not break other pages unknowingly

**Comment by facelessuser** [comment]
MkDocs Material is just a theme. Snippets is provided by the Pymdown Extensions library that I maintain. If you wish to be alerted to bad, missing snippets, just enable `check_paths` as noted in the [documentation](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#options).  `check_paths` will issue an error in the event that a file is missing.
