### ISSUE TITLE
Support slides animation

### ISSUE THREAD

**Issue by krahets** [squidfunk/mkdocs-material#4609]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The slides are an excellent supplement to the current media expressions (image, animated gif, video…).

I'm wondering if there is a plan to add this new feature. Thanks!

### Use Cases

Slides will be very useful for the image set related to each other.

### Screenshots / Mockups

This is an example of slides with 29 images in total.
We can press the button on the left bottom to play the slides.

<img width="818" alt="Screenshot 2022-11-07 at 19 47 13" src="https://user-images.githubusercontent.com/26993056/200302865-0a4b305f-8068-43db-9c0f-15b170dcf284.png">

Author: Krahets
Link: https://leetcode.cn/leetbook/read/illustration-of-algorithm/phn3m1/

**Comment by squidfunk** [comment]
Thanks for suggesting! This is an excellent case for a third-party Markdown extension which we consider out-of-scope for Material for MkDocs. We have so many components already and I suspect that slideshows are a very specific use case that are of limited value for most users. We already have content tabs which achieve something similar. Furthermore, slideshows would need to adjust for different content width and height and are probably tricky to get right on mobile.

You might build the extension yourself or ask on our [discussion board](https://github.com/squidfunk/mkdocs-material/discussions) for help.

**Comment by krahets** [comment]
Thanks for the reply. Both content tabs and lightboxes are great!

**Comment by ianderrington** [comment]
@krahets Wishing the same functionality I built this https://pypi.org/project/mkdocs-slides/

Demo here https://ianderrington.github.io/mkdocs_slides/slides/slides_demo/

Contributions to improve it welcome!
