### ISSUE TITLE
Support code annotations in fenced markdown code

### ISSUE THREAD

**Issue by samgaudet** [squidfunk/mkdocs-material#4610]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

First, let me provide necessary thanks for mkdocs-material as a big fan and avid user.

As far as I can tell, [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) do not currently function for fenced markdown code. It is possible that I am missing a way to make this work, but tried several possible markdown comment syntaxes to make this work.

In fenced code, I would expect to be able to add an annotation to markdown fenced code using the standard markdown comment syntax (`<!--- comment --->`), e.g. (remove the `\` characters):

```
\```md
# Title <!--- (1) --->
\```

1. This is an annotation!
```

### Use Cases

As with all fenced code, annotations provide a powerful way to provide additional detail for users without cluttering the page/code block. Having this feature for markdown fenced code would expand the already beneficial feature to even more use cases.

### Screenshots / Mockups

Current behavior of the minimal example above:
<img width="777" alt="Screen Shot 2022-11-07 at 10 42 52 PM" src="https://user-images.githubusercontent.com/32820645/200470138-7872c7ae-39e2-4497-b6b6-ccacad050f47.png">

**Comment by squidfunk** [comment]
Thanks for reporting. Pygments parses the Markdown code block as follows:

``` html
<span class="gh"># Title &lt;!--- (1) ---&gt;</span>
```

Thus, there's no comment for Material for MkDocs to extract and replace with a code annotation. This is an upstream issue, so you can follow up with this with the maintainers of Pygments, but we can only process what we get.

**Comment by samgaudet** [comment]
Thanks for the information! Moved this request to a new [issue in the pygments project](https://github.com/pygments/pygments/issues/2273).
