### ISSUE TITLE
Additional icon set from the Carbon Design System

### ISSUE THREAD

**Issue by seebi** [squidfunk/mkdocs-material#4613]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I know that mkdocs-material already supports four icon sets, but at @eccenca we love the [icon set from the Carbon Design System](https://carbondesignsystem.com/guidelines/icons/library/) and miss it here.

### Use Cases

Especially for documenting complex application software, Carbon adds some not often seen icons which we would like to use.

### Screenshots / Mockups

<img width="1179" alt="Screenshot 2022-11-08 at 14 01 21" src="https://user-images.githubusercontent.com/510452/200571485-835591e1-b84b-468b-a915-933635826d82.png">

**Comment by seebi** [comment]
From what I see, integration should be straight forward.

If there is no general disagreement, we can imagine to provide a PR (@haschek)

Can you outline, how we could do that (e.g. how to generate the icon json file)

**Comment by squidfunk** [comment]
Thanks for suggesting. However, I'm not keen on adding another non-complementary icon set. We already have the Material Design and FontAwesome icon sets which provide a wide range of every-day icons, and Simple Icons for brand icons. The Carbon Design icon set would add another set which has a lot of overlap with Material Design and FontAwesome, so the added value is limited. We need to strike a balance of added value and installation size.

You can [add the icon set via customization](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons). It's simple. Closing as out-of-scope.
