### ISSUE TITLE
custom icons do not work when using them as tag icons

### ISSUE THREAD

**Issue by seebi** [squidfunk/mkdocs-material#4617]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- ~~[ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`~~ (custom icons need overrides)
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

custom icons as described in [the documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons) do not work for when using them as tag icons.

| use case  | how to           | where         | working |
| --------: | :--------------- | :------------ | :------ |
| inline    | `:test-my:`      | `*.md` text   | yes     |
| page icon | `icon: text/my`  | `*.md` header | yes     |
| tag icon  | `tagid: test/my` | `mkdocs.yml`  | no      |

### Expected behaviour

I can use custom icons for all three use cases, incl. as as tag icons.

### Actual behaviour

the page is broken, only showing this:

<img width="367" alt="Screenshot 2022-11-09 at 13 30 30" src="https://user-images.githubusercontent.com/510452/200830799-f3d0f29a-7aa7-4d93-8153-48e319a4192a.png">

```
');}.md-tag-icon--beginners{--md-tag-icon:url('data:image/svg+xml;charset=utf-8,');}.md-tag-icon--advanced{--md-tag-icon:url('data:image/svg+xml;charset=utf-8,');}.md-tag-icon--expert{--md-tag-icon:url('data:image/svg+xml;charset=utf-8,');}
```

### Steps to reproduce

1. run the mve project -> [mkdocs-material-issues-4617.zip](https://github.com/squidfunk/mkdocs-material/files/9971206/mkdocs-material-issues-4617.zip)

### Package versions

- Python: Python 3.10.8
- MkDocs: mkdocs, version 1.4.2
- Material: Version: 8.5.8+insiders.4.26.2

### Configuration

see mve project -> [mkdocs-material-issues-4617.zip](https://github.com/squidfunk/mkdocs-material/files/9971206/mkdocs-material-issues-4617.zip)

### System information

- Operating system: MacOS
- Browser: Chrome

**Comment by squidfunk** [comment]
Thanks for reporting. This is happening due to the `style` tag that is contained in the icon source:

``` svg
<svg class="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
  <defs>
    <style>.cls-1{fill:none;}</style> <!-- This causes the problem -->
  </defs>
  <title>data-vis--1</title>
  <path d="M26,22a3.9553,3.9553,0,0,0-2.0193.5667L20.167,18.7529a4.9654,4.9654,0,0,0,0-5.5058L22.714,10.7A3.0284,3.0284,0,1,0,21.3,9.286l-2.547,2.547a4.9654,4.9654,0,0,0-5.5058,0L9.4332,8.0191A3.9553,3.9553,0,0,0,10,6a4,4,0,1,0-4,4,3.9553,3.9553,0,0,0,2.0191-.5668l3.8139,3.8139a4.9654,4.9654,0,0,0,0,5.5058L8.0192,22.5668A3.9556,3.9556,0,0,0,6,22a4,4,0,1,0,4,4,3.9553,3.9553,0,0,0-.5667-2.0192l3.8138-3.8138A4.9686,4.9686,0,0,0,15,20.8989v3.2848a3,3,0,1,0,2,0V20.8989a4.9686,4.9686,0,0,0,1.7529-.7319l3.8138,3.8137A3.9553,3.9553,0,0,0,22,26a4,4,0,1,0,4-4ZM16,13a3,3,0,1,1-3,3A3.0033,3.0033,0,0,1,16,13ZM4,6A2,2,0,1,1,6,8,2.002,2.002,0,0,1,4,6ZM6,28a2,2,0,1,1,2-2A2.0023,2.0023,0,0,1,6,28Zm20,0a2,2,0,1,1,2-2A2.0027,2.0027,0,0,1,26,28Z" transform="translate(0 0)" />
  <rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-1" width="32" height="32" />
</svg>
```

`style` tags are not supported in inlined SVGs. The reason is that we're inlining the icon as such, and the HTML parser will regard the closing `style` tag as what it is. Unfortunately, inlining icons is a pretty "dumb" process – we're just loading the contents and inlining it as part of a CSS variable. We can't add a warning from a template or fail the build.

Thus, there's no fix except for the author to remove any `style` tags from SVGs. Even GitHub's syntax highlighting showcases the problem. Thus, there's nothing we can fix.

``` html
<style>.md-tag-icon--knowledge-graph{--md-tag-icon:url('data:image/svg+xml;charset=utf-8,<svg class="icon" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">  <defs>    <style>.cls-1{fill:none;}</style>  </defs>  <title>data-vis--1</title>  <path d="M26,22a3.9553,3.9553,0,0,0-2.0193.5667L20.167,18.7529a4.9654,4.9654,0,0,0,0-5.5058L22.714,10.7A3.0284,3.0284,0,1,0,21.3,9.286l-2.547,2.547a4.9654,4.9654,0,0,0-5.5058,0L9.4332,8.0191A3.9553,3.9553,0,0,0,10,6a4,4,0,1,0-4,4,3.9553,3.9553,0,0,0,2.0191-.5668l3.8139,3.8139a4.9654,4.9654,0,0,0,0,5.5058L8.0192,22.5668A3.9556,3.9556,0,0,0,6,22a4,4,0,1,0,4,4,3.9553,3.9553,0,0,0-.5667-2.0192l3.8138-3.8138A4.9686,4.9686,0,0,0,15,20.8989v3.2848a3,3,0,1,0,2,0V20.8989a4.9686,4.9686,0,0,0,1.7529-.7319l3.8138,3.8137A3.9553,3.9553,0,0,0,22,26a4,4,0,1,0,4-4ZM16,13a3,3,0,1,1-3,3A3.0033,3.0033,0,0,1,16,13ZM4,6A2,2,0,1,1,6,8,2.002,2.002,0,0,1,4,6ZM6,28a2,2,0,1,1,2-2A2.0023,2.0023,0,0,1,6,28Zm20,0a2,2,0,1,1,2-2A2.0027,2.0027,0,0,1,26,28Z" transform="translate(0 0)" />  <rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-1" width="32" height="32" /></svg>');}.md-tag-icon--beginners{--md-tag-icon:url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16.5 11 13 7.5l1.4-1.4 2.1 2.1L20.7 4l1.4 1.4-5.6 5.6M11 7H2v2h9V7m10 6.4L19.6 12 17 14.6 14.4 12 13 13.4l2.6 2.6-2.6 2.6 1.4 1.4 2.6-2.6 2.6 2.6 1.4-1.4-2.6-2.6 2.6-2.6M11 15H2v2h9v-2Z"/></svg>');}.md-tag-icon--advanced{--md-tag-icon:url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16.5 11 13 7.5l1.4-1.4 2.1 2.1L20.7 4l1.4 1.4-5.6 5.6M11 7H2v2h9V7m10 6.4L19.6 12 17 14.6 14.4 12 13 13.4l2.6 2.6-2.6 2.6 1.4 1.4 2.6-2.6 2.6 2.6 1.4-1.4-2.6-2.6 2.6-2.6M11 15H2v2h9v-2Z"/></svg>');}.md-tag-icon--expert{--md-tag-icon:url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16.5 11 13 7.5l1.4-1.4 2.1 2.1L20.7 4l1.4 1.4-5.6 5.6M11 7H2v2h9V7m10 6.4L19.6 12 17 14.6 14.4 12 13 13.4l2.6 2.6-2.6 2.6 1.4 1.4 2.6-2.6 2.6 2.6 1.4-1.4-2.6-2.6 2.6-2.6M11 15H2v2h9v-2Z"/></svg>');}</style>
```
