### ISSUE TITLE
Blog's title link shouldn't have a subelement in the href

### ISSUE THREAD

**Issue by hellt** [squidfunk/mkdocs-material#4632]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Latest release of insiders provides a feature to open up the blog page by clicking on the title of the post. This feature request aligns the link href element for a title with the href element of a "Continue reading" link.

Currently, the title link has the format of `<site_url>/blog/<post_slug>/#<post_slug>` whereas the "Continue reading" element's href is just  `<site_url>/blog/<post_slug>`

### Use Cases

Cleaner URL for title link element

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, that's suboptimal but that's what the`toc` extension gives us. I consider this an optimization.

**Comment by squidfunk** [comment]
Fixed in squidfunk/mkdocs-material-insiders@e7c792c0f.

**Comment by squidfunk** [comment]
Released as part of [8.5.10+insiders-4.26.5](https://github.com/squidfunk/mkdocs-material-insiders/releases/tag/8.5.10-insiders-4.26.5).
