### ISSUE TITLE
Bundle package-lock.json or a software BOM in the package

### ISSUE THREAD

**Issue by nejch** [squidfunk/mkdocs-material#4650]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

We use a small plugin akin to your builtin social/tag plugins, to extract all build-time python dependencies for the page build. This lets us create a `Third-party software` page that theoretically always has accurate OSS license and version details of packages used.

However, this only covers python dependencies, not JS deps. It'd be great if people using the theme had access to all of them (including transitive dependencies) so they can provide this to end users. Not sure what the best approach would be here:
* bundle `package-lock.json` in the package, so SBOM tools can extract dependency versions and licenses (should be a oneliner in `pyproject.toml`.)
* bundle a prepared SBOM with something like https://github.com/CycloneDX/cyclonedx-node-npm 

I'm aware we can potentially manually go to GitHub and collect this based on the tag, but for automated builds and clearing it doesn't scale that well. `package.json` is already bundled (in the sdist only) but does not cover the transitive dependencies used to build the package AFAIK.

But if this makes sense I can open a PR also. Not sure if this is something you'd also consider as part of the theme if there was a standalone plugin available (e.g. if oss-licenses plugin installed, display a link to a `thirdpartylicenses` page in the footer), I'd be happy to collaborate on that. Though I'm aware you prefer staying minimal here. :)

### Use Cases

* Angular-style `3rdpartylicenses.txt` or `Thirdy-party software` page to display as part of the published docs
* Creating a Software BOM such as owasp's [CycloneDX JSON BOM](https://cyclonedx.org/) to feed into software clearing platforms (Black Duck, Fossology etc) that includes all dependencies of a built site.

### Screenshots / Mockups

Generated `OSS Licenses` page (python only atm):
![image](https://user-images.githubusercontent.com/16777978/202203330-2a7d22c3-147f-4904-b8de-f83d3c5c3ff2.png)

**Comment by nejch** [comment]
Thanks @squidfunk. I imagined you wouldn't really want any more than the bundled licenses. :)

The idea was more for user convenience (to easily display everything in one place) or automation for software clearing (to easily extract all dependencies including their versions). Normally not an issue as people maintain their own lockfiles, but here it's Python+bundled JS.

I'm also not sure what the best approach would be, just threw in a few ideas here!

**Comment by squidfunk** [comment]
Looping in @ofek – why is the `package.json` necessary for `sdist` but not for `wheel`? Can we remove it?

https://github.com/squidfunk/mkdocs-material/blob/13655d68f5c3514f1a03733ef7b2ecb96bc0d2fe/pyproject.toml#L74

**Comment by ofek** [comment]
When installing with an sdist (i.e. building a wheel from an sdist) it needs that for https://github.com/squidfunk/mkdocs-material/blob/13655d68f5c3514f1a03733ef7b2ecb96bc0d2fe/pyproject.toml#L64-L65
