### ISSUE TITLE
scripts keeps failing

### ISSUE THREAD

**Issue by GHXST01** [squidfunk/mkdocs-material#469]
## Description

Scripts keep failing with both NPM and YARN on my windows system.

### Expected behavior

I expect for the commands `yarn install` or `npm install` to work like intended.
Same goes for any scripts in the scripts folder.

### Actual behavior

```
C:\Users\Admin\Desktop\material\mkdocs-material>yarn install
yarn install v1.0.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.1: The platform "win32" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
warning "postcss-reporter@4.0.0" has incorrect peer dependency "postcss@^6.0.0".
warning "stylelint-config-standard@17.0.0" has incorrect peer dependency "stylelint@^8.0.0".
warning "stylelint-config-recommended@1.0.0" has incorrect peer dependency "stylelint@^8.0.0".
warning "stylelint-scss@2.0.0" has incorrect peer dependency "stylelint@^8.0.0".
warning "ajv-keywords@2.1.0" has incorrect peer dependency "ajv@>=5.0.0".
[5/5] Building fresh packages...
[1/4] ⠂ uglifyjs-webpack-plugin
[2/4] ⠂ git-hooks
[3/4] ⠂ customizr
[4/4] ⠂ node-sass
error C:\Users\Admin\Desktop\material\mkdocs-material\node_modules\git-hooks: Command failed.
Exit code: 1
Command: .\bin\git-hooks --install
Arguments:
Directory: C:\Users\Admin\Desktop\material\mkdocs-material\node_modules\git-hooks
```

### Steps to reproduce the bug

Use the command `yarn install` on a windows system.

### Package versions

* Python: `Python 2.7.12`
* MkDocs: `mkdocs, version 0.16.3`
* Material: `Version: 1.10.1`

### System information

* OS: Win 10

**Comment by facelessuser** [comment]
Yeah, it's nothing yarn specific, it's just the approach @squidfunk took when writing his enivironment stuff.  It looks like he develops on either Mac or Linux.  Maybe if you ran it in a bash environment on windows with git it might work, but I've never tried.

**Comment by GHXST01** [comment]
@facelessuser thanks for the reply. I'll try Linux Bash Shell for Windows 10.

**Comment by GHXST01** [comment]
Bash environment solved this issue.

**Comment by facelessuser** [comment]
Cool. Figured it might :).

**Comment by squidfunk** [comment]
It seems that it's actually a problem with the githooks package, however Windows support for the build environment is not my first priority. You may add changes to the build scripts to make them compatible and open a PR.
