### ISSUE TITLE
Feature suggestion: order field in metadata

### ISSUE THREAD

**Issue by StefanoCecere** [squidfunk/mkdocs-material#4695]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I think it's quite strange that there isn't a native way to order the list of pages.

right now or i prefix the filenames with numbers 01_filename.md or i have to write ALL the navigation via `nav`.
impossibile since i have hundreds of pages.

can't we have a sort/weight field in the metadata of the subpages? see for example Hugo https://gohugo.io/templates/lists/

### Use Cases

i have some manuals in a subdirectory whose sections i want to order manually

**Comment by squidfunk** [comment]
Duplicate https://github.com/mkdocs/mkdocs/issues/2764. Closing.
