### ISSUE TITLE
Mermaid sequence diagram numbers unreadable in dark mode

### ISSUE THREAD

**Issue by alexhayes** [squidfunk/mkdocs-material#4713]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... ~~the problem doesn't occur with the `mkdocs` or `readthedocs` themes~~ The diagrams don't work either with these things so not sure it's relevant.
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

Mermaid's Sequence Diagram can support [auto-numbering of sequence numbers](https://mermaid-js.github.io/mermaid/#/sequenceDiagram?id=sequencenumbers).

This works as expected (thank-you!), however when we switch to a dark theme, while the diagram switches, the numbers within the sequences become unreadable.

### Expected behaviour

The sequence numbers are readable when in dark mode.

### Actual behaviour

The sequence numbers are not readable when in dark mode as they are white on white.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/142916/206082766-087caf07-d12a-4d22-9000-d3d4c39645c7.png">

<img width="705" alt="image" src="https://user-images.githubusercontent.com/142916/206082848-00991f91-1667-41ac-afa5-a1d2cfcffe6b.png">

### Steps to reproduce

1. Apply the following diff against this repo

    ```diff
    diff --git a/docs/reference/diagrams.md b/docs/reference/diagrams.md
    index d6ce3a995..0521ef7cf 100644
    --- a/docs/reference/diagrams.md
    +++ b/docs/reference/diagrams.md
    @@ -91,6 +91,7 @@ between those actors:
     ```` markdown title="Sequence diagram"
     ``` mermaid
     sequenceDiagram
    +  autonumber
       Alice->>John: Hello John, how are you?
       loop Healthcheck
           John->>John: Fight against hypochondria
    @@ -106,6 +107,7 @@ sequenceDiagram
     
     ``` mermaid
     sequenceDiagram
    +  autonumber
       Alice->>John: Hello John, how are you?
       loop Healthcheck
           John->>John: Fight against hypochondria
    ```

2. Go to http://localhost:8000/mkdocs-material/reference/diagrams/?h=mermaid#using-sequence-diagrams
3. Toggle between light and dark mode.

### Package versions

- Python: `Python 3.10.7`
- MkDocs: `mkdocs, version 1.4.2`  / ae7ed95f3
- Material: `Version: 8.5.11`

### Configuration

```yaml
As per https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
```

### System information

- Operating system: OSX
- Browser: Chrome

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in ee2c7ee15. The fix will be released with the next beta of v9, tracked in #4714.
