### ISSUE TITLE
🚀 Material for MkDocs 9 – Beta

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#4714]
__With the help of our awesome sponsors, I'm happy to announce that the '[Carolina Reaper](https://squidfunk.github.io/mkdocs-material/insiders/#10000-carolina-reaper)' funding goal has been reached, which means that [the brand new search](https://squidfunk.github.io/mkdocs-material/blog/2021/09/13/search-better-faster-smaller/) is finding its way into the community edition!__

Since this is a pretty major change, we're releasing the new search as part of a new major version, so we can also drop and refactor some things that are overdue. This issue will track the progress on the road from the beta to the final release of v9.

__If you experience any problems, for now, please report them as a comment in this issue__.

## Installation

```
pip install mkdocs-material==9.0.0b4
```

> **Note** – This is a beta release, so please test thoroughly before deploying to production.
> __Final release date will be January 2, 2023__.

## Additions and improvements

- [x] Rewrite of search plugin with support for [rich previews](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#rich-search-previews)
- [x] Added support for [tokenizer lookahead](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#tokenizer-lookahead) 
- [x] Added support for [better search highlighting](https://squidfunk.github.io/mkdocs-material/blog/2021/09/13/search-better-faster-smaller/#accurate-highlighting)
- [x] Added support for [excluding content from search](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-exclusion)
- [x] Added support for [configurable search pipeline](https://github.com/mkdocs/mkdocs/issues/2380)
- [x] Added support for offline search via [offline plugin](https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/)
- [x] Added support for multiple instances of [built-in tags plugin](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#built-in-tags-plugin) in 17186b49478e4ea17b1ede882c61439d8d4d8d1b
- [x] Added support for removing copy-to-clipboard button in 128e26742
- [x] Added support for removing footer navigation in 8fdd1ad52
- [x] Added support for button to view the source of a page in 28d64a289
- [x] Improved readability of query string for search sharing in ee149649
- [x] Improved stability of search plugin when using `--dirtyreload`
- [x] Improved "more on this page" by making it sticky and stable when scrolling 
- [x] Updated Norwegian translations (via #4647)
- [x] Updated to MkDocs 1.4.2 in 17186b49478e4ea17b1ede882c61439d8d4d8d1b

## Removals

- [x] [Removed alternative admonition qualifiers](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#fn:1) in https://github.com/squidfunk/mkdocs-material/pull/4584/commits/daffd085f3bc35058ada32fad0a21b2d88ac0d3f
- [x] Removed `:is` selectors (in output) to allow for easier overriding of CSS in daffd085f3bc35058ada32fad0a21b2d88ac0d3f
- [x] [Removed legacy method for providing page title in feedback URL](https://github.com/squidfunk/mkdocs-material-insiders/commit/4ac83e2a64cc2189822a4f71aa744dbec65dc7bf) in 9979cbf9ecf487588b3a2dc877e17916b8ea9abe
- [x] Removed `.title` suffix on translations in 37250f1be
- [x] Removed support for indexing only titles in search

## Fixes

- [x] Fixed Korean language code (~~`kr`~~ `ko`) in 5aebaaa71  
- [x] Fixed detection of composition events in search interface
- [x] Fixed search plugin not using title set via front matter
- [x] Fixed search highlighting of tags in 24a3be8
- [x] Fixed search sharing URL using post transformed string (with wildcards etc.)
- [x] Fixed inability to query specific fields (e.g. `tags:foo` or `title:bar`)
- [x] Fixed inability to exclude search terms (e.g. `-foo` or `-title:bar`)
- [x] Fixed inability to use fuzzy modifier (e.g. `foo~1` or `title:bar~2`)
- [x] Fixed inability to boost specific terms (e.g. `foo^2` or `title:bar^4`)
- [x] Fixed inability to use leading wildcards (e.g. `*foo` or `*title:bar`)
- [x] Fixed theme-color meta tag getting out-of-sync in https://github.com/squidfunk/mkdocs-material/commit/944180d572ac6aab03f12e8c444f92f6c3bd0f33
- [x] Fixed prev/next page keyboard navigation when footer is not present in 763423d30 
- [x] Fixed overflowing navigation tabs not being scrollable in 9fb36102 
- [x] Omit code block line numbers from search

### Changes to `mkdocs.yml`

- __Enable copy-to-clipboard button__: the copy-to-clipboard buttons are now opt-in. If you wish to enable them __for all__ code blocks, add the following lines to `mkdocs.yml`:

    ``` yaml
    theme:
      features:
        - content.code.copy
    ```

    You can also choose to enable them for specific code blocks, by adding a `.copy` class to the code block, like so:

    ```` markdown
    ``` { .py .copy }
    ...
    ```
    ````

    Similarily, if you enabled the button globally, but want to disable it for a specific code block use `.no-copy`:

    ```` markdown
    ``` { .py .no-copy }
    ...
    ```
    ````

- __Enable edit and view source button__: a "view source" button can be shown next to the "edit this page" button, both of which must now be explicitly enabled. The `repo_url` must also be given. Add the following lines to `mkdocs.yml`:

    ``` yaml
    repo_url: ...
    theme:
      features:
        - content.action.edit
        - content.action.view
    ```

- __Enable navigation footer__: the previous and next buttons in the footer are now opt-in. If you wish to keep them for your documentation, add the following lines to `mkdocs.yml`:

    ``` yaml
    theme:
      features:
        - navigation.footer
    ```

- __Use Korean language__: the Korean language code was `kr`, which is not correct. It was corrected to `ko`:

    ``` yaml
    theme:
      language: ko
    ```

- __Use Norwegian languages__: the Norwegian language code was `no`, was no renamed to `nb`.

    ``` yaml
    theme:
      language: nb # or nn
    ```

- __Feedback widget URLs__: the old, nameless placeholders were removed (after being deprecated for several months). If Make sure to switch to the [new named placeholders](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#+analytics.feedback.ratings.note) `{title}` and `{url}`:

    ``` yaml
    https://github.com/.../issues/new/?title=[Feedback]+{title}+-+{url}
    ```

There should be no other changes to `mkdocs.yml` necessary. If you discover that you need to change other lines to make v9 work, please comment below, so we can add it to the list.

### Changes to documents

- ~~__Alternate admonition qualifiers__~~: to keep the size of the CSS down, we removed support for alternate admonition qualifiers. Please use the standard admonition qualifiers that are [mentioned in our documentation](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types).

### Changes to customizations

If you've customized Material for MkDocs with theme overrides, and added your own partials, you need to adjust for some changes, as the translations keys got updated. Keys that end with `.title` have been stripped off the suffix, so `footer.title` now becomes `footer`. The reason is that those are mostly generic translations of components that may not only be used in `title` attributes. [See the partial diff](https://github.com/squidfunk/mkdocs-material/pull/4628/files#diff-3ca112736b9164701b599f34780107abf14bb79fe110c478cac410be90899828).

## Closing thoughts

Version 9 is a pretty big release, which includes a completely rewritten search implementation. I'm super happy to finally give it into the hands of all users, so we can improve it even more. Before issuing the final release, I'll take the opportunity to refactor some edges that need a little polishing and incorporate your feedback.

**Comment by squidfunk** [comment]
The Python release does not work due to a problem with our new build system, hatch. @ofek, [could you please take a look](https://github.com/squidfunk/mkdocs-material/actions/runs/3638152924/jobs/6140008696#step:5:46)? Otherwise I need to revert to `setup.py`, again... For the time being, the release needs to be installed via `git`.

**Comment by ofek** [comment]
@agoose77

**Comment by squidfunk** [comment]
No, there's no dash, it's just `9.0.0b`, since it wouldn't be compatible with [PEP 440](https://peps.python.org/pep-0440/#pre-releases).

**Comment by squidfunk** [comment]
Yes, it is used in `package.json`. Hmm. I've used the same approach I did as for all other beta releases before, but I guess we could maybe use the versioning `package.json` expects.  Unfortunately, I',m not an expert in `hatch`. @ofek has introduced it to this repository and I just wanted to make a beta release. I'll consult you guys next time I try to diverge from normal versioning 😬

**Comment by squidfunk** [comment]
> Also, note that 9.0.0b1 isn't valid for package.json, whereas 9.0.0-b1 is valid for PEP440.

From the PEP 440 spec, it wasn't apparent to me that it is valid.

**Comment by ofek** [comment]
> maybe use the versioning `package.json` expects

Yes that is the fix

**Comment by bigpick** [comment]
> Trying to use a custom toc permalink character breaks...

I see this as well, even just reverting to 

```yml
  - toc:
      permalink: true
```

Still ends up rendering a `{'permalink': True}`:

**Comment by squidfunk** [comment]
> Still ends up rendering a `{'permalink': True}`

Fixed in 3e9b72c10!

**Comment by squidfunk** [comment]
I just released the latest fixes as part of [9.0.0b3](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.0b3).

**Comment by shanthisagar-dhanya-kumar-db** [comment]
After upgrading to 9.0.0b3 am getting "tags" plugin not installed. Anyone noticed?

**Comment by squidfunk** [comment]
@shanthisagar-dhanya-kumar-db I'm not seeing this problem, the built-in tags plugin works fine. Could you please try and create a minimal reproduction? You could then attach it here as a zip and I'll have a look.

**Comment by squidfunk** [comment]
The latest commits fix highlighting of tags and improve the URL when using search sharing. Furthermore, now, the full range of [Lunr.js query syntax](https://lunrjs.com/guides/searching.html) is supported! I've reordered how the search query is preprocessed and ensured that only search terms (not modifiers) are sent through the transformation and tokenization pipeline. This lays the foundation for more interesting features to come.

```
pip install mkdocs-material==9.0.0b4
```

Before releasing the stable version, I'll expand in a blog article on the new capabilities and how it works.

**Comment by guusw** [comment]
The global `n`/`p` nagivation keys seemed to have stopped working in this version, compared to the git master version.
However `f`/`/` to search still seems to work

**Comment by squidfunk** [comment]
Did you re-enable the footer navigation (see OP)? The `n/p` keys otherwise have no idea what the previous or next page is.

**Comment by kcgthb** [comment]
As mentioned in #4755, the new version fails to build the site if the feedback URL uses nameless placeholders:
```
ERROR    -  Error building page 'docs/index.md': Replacement index 0 out of range for positional args tuple
Traceback (most recent call last):
[...]
    {% include "partials/feedback.html" %}
  File "/home/kilian/.local/lib/python3.10/site-packages/material/partials/feedback.html", line 35, in top-level template code
    {{ rating.note.format(url = url, title = title) }}
IndexError: Replacement index 0 out of range for positional args tuple
```

Using the [new format](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#+analytics.feedback.ratings.note) is now mandatory.

**Comment by squidfunk** [comment]
Thanks @kcgthb, I updated the OP.

**Comment by squidfunk** [comment]
@guusw the next/previous page navigation should now work regardless of whether the footer is present or not. I've moved it into the head in 763423d30, which makes more sense anyway.

**Comment by Valastiri** [comment]
Hello! I wanted to inquire if this could be a possible bug/issue with the new search plugin. In the production build `mkdocs-material==8.5.10` pages primarily containing markdown tables would render only a small snippet in the search preview. 

In testing, `9.0.0b4` the search preview returns a rather large wall of text (often taking priority over other pages). One of our devs performing some tests noticed the issue linked in the comment below where it can best be seen:
- https://github.com/flybywiresim/docs/pull/692#issuecomment-1345369644

For reference I've tested it by searching locally and on our vercel preview. 

A small working around is to enable `search.boost` on certain pages. 

I've personally tested this with a stripped-down version of our production config (no plugins, features beyond search).

```
mkdocs-material==9.0.0b4
mkdocs==1.4.2
python==3.10.8
```

Any insight if this is as intended and if utilizing `search.boost` is the way to go? Please let me know if I can provide anymore resources. 

[Project Staging Link](https://docs-git-fork-valastiri-builds-flybywire.vercel.app/) for the above PR.

**Comment by Valastiri** [comment]
> @Valastiri thanks for reporting. This is not a bug. Search previews might now be larger, as they are cut at paragraphs and lists, and are not truncated anymore. If truncation is wished, one can do so by using CSS, but some users might not like that. More compact search summaries are an improvement that is on the roadmap and tracked in #4278.

Thanks! Good to know. Appreciate the response and all the work on Material thus far :). Love the platform/theme.

**Comment by lyz-code** [comment]
Hi @squidfunk, I'm the developer of [`mkdocs-newsletter`](https://github.com/lyz-code/mkdocs-newsletter) and as some users above the next and previous buttons disappeared from my site breaking the tests. I'm using 763423d30 to build [this site](https://github.com/lyz-code/mkdocs-newsletter/tree/main/tests/assets/test_data). 

I've read the comments in this issue and the related ones but found no clear steps to re-enable them, can you help me?

Thanks for maintaining this project so well, it's awesome, both docs, quality, release process...

**Comment by squidfunk** [comment]
Please read the original post, the one at the top. It clearly explains what to do. Excerpt:


> - __Enable navigation footer__: the previous and next buttons in the footer are now opt-in. If you wish to keep them for your documentation, add the following lines to `mkdocs.yml`:
>
>    ``` yaml
>    theme:
>      features:
>        - navigation.footer
>    ```

Some users wished to disable the footer for a long time, which is why it is now opt-in.

**Comment by lyz-code** [comment]
Oh sorry, I didn't understood what OP meant. That fixed the issue

**Comment by squidfunk** [comment]
__Thanks for everybody testing the beta so far!__ Since it's impossible to predict what will break down the line, I don't think it's a good idea to push this out before Christmas or even NYE. People are busy getting presents, and, in Germany, meeting in the evening to drink some Glühwein, so it's probably not a good idea to impose such a major change upon them right now. We'll move v9 out of beta at the beginning of next year.

If you already want to try it, no problem, just install the beta (see OP) and see if you run into any problems. You can already fix them on a separate branch, and then later, when v9 is out, just remove the `b` release modifier and you're done.

**Comment by facelessuser** [comment]
@jrappen `uslugify` is deprecated as it says. Now you can just use `slugify` with the options to control the slug options. See here for configuring it in MkDocs YAML configs: https://facelessuser.github.io/pymdown-extensions/faq/#function-references-in-yaml.

**Comment by EDIflyer** [comment]
I'm not sure if related to this beta or not (I'm running 9.0.0b4) but I've found when following the instructions at https://squidfunk.github.io/mkdocs-material/reference/data-tables/#sortable-tables and added the `tablesort.js` code to `docs/javacripts/tablesort.js` and the two lines to mkdocs.yml too. I can't see any errors in the logs, however it just doesn't seem to do anything (table still displays OK, just no sort icon as shown on the demo page)

**Comment by squidfunk** [comment]
I just tested Tablesort locally on our v9 branch, and everything works as expected, i.e. the icons show up and I can sort tables. It's hard to know what went wrong in your specific use case without a reproducible example. I can look into it, if you provide such a _minimal_ reproducible example and attach it here as a zip.

**Comment by EDIflyer** [comment]
Thanks @squidfunk - I'm pleased to say it's just because I'm a not idiot that there was an issue 😂  I had lots of folders open and only just realised when going back in today that `javascripts` was mistakenly set as a top-level directory rather than as a sub-directory 🤦‍♂️. Sorry for wasting your time, it now works perfectly 🥳

**Comment by squidfunk** [comment]
__Thank you all for testing the beta!__ 9.0.0 will be released today.

**Comment by johnthagen** [comment]
@squidfunk isn't the hero we deserve, but the one we need. ❤️

**Comment by HighLandner** [comment]
@squidfunk, updated from 8.5.11 to 9.0.0 and this error appears. 
There are several .md pages in dir guide and it fails with such error. Only deletion of page that is out of index solves the issue. Also this appears with all 9+ versions

ERROR    -  Error building page 'guide/start.md': list index out of range
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 83, in serve
    builder(config)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 329, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 226, in _build_page
    context = config.plugins.run_event(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 90, in on_page_context
    self.search_index.add_entry_from_context(page)
  File "/usr/local/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 143, in add_entry_from_context
    parser.feed(page.content)
  File "/usr/local/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.11/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/html/parser.py", line 413, in parse_endtag
    self.handle_endtag(elem)
  File "/usr/local/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 417, in handle_endtag
    elif data[-1].isspace() and data[-2] == f"<{tag}>":
                                ~~~~^^^^
IndexError: list index out of range

**Comment by squidfunk** [comment]
@HighLander Possibly related: #4824. If this is not the cause, please create a separate [bug report](https://squidfunk.github.io/mkdocs-material/bug-report/).
