### ISSUE TITLE
Support for custom colors for different components

### ISSUE THREAD

**Issue by AyushSehrawat** [squidfunk/mkdocs-material#4715]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Hi! I would like if you were to add some option edit the colors of some component, because when i tried with extra.css ( custom stylesheet ), some things didn't work the way i intended, and at some places it wasn't even taking part, like overwritten. Also is there any guide on components you use ? Like `md-header`, `h1,h2,....`...

### Use Cases

Custom color for better flavouring of website. It will give opportunities to more varieties of themes, instead of being restricted to some few. 
Why? Like i added an a:hover and `md-nav__link`, but it didn't work everywhere. Only at some places.

**Comment by squidfunk** [comment]
Thanks for suggesting. Ad you have noticed, appearance can be changed and customized with [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css). Unfortunately, we can't provide a general web development guide in our documentation, detailing for every component how to override it. This is out-of-scope for the project. I'm converting this to a discussion. Feel free to share what you tried, maybe somebody can help 😊
