### ISSUE TITLE
Auto hide scrollbar and reveal it when scrolling

### ISSUE THREAD

**Issue by krahets** [squidfunk/mkdocs-material#4728]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

The scrollbar of the left-navigation is very close to the content which decreases the UI simplicity. Maybe it is better to provide an option to autohide the scroll bar when the users are reading and reveal it when scrolling.

Temporarily, I implement it in `extra.css`. It works well except for no animation like fading and appearing.

```
.md-sidebar__scrollwrap {
  overflow-y: hidden;
}

.md-sidebar__scrollwrap:hover {
  overflow-y: auto;
}
```

I'm wondering if you have a plan to implement a more pretty scrollbar autohiding feature. I believe it will be a welcome feature.

### Use Cases

The scrollbar of the left navigation panel is very close to the content which decreases the UI simplicity, i.e., there is always a bar on the left edge of the content which is not good looking.

**Comment by squidfunk** [comment]
Thanks for suggesting! In fact this is available of today – [Material for MkDocs 9](https://github.com/squidfunk/mkdocs-material/pull/4628) exhibits this exact behavior. I invite you to try the beta and report any blocks you stumble upon. The final version will be released later this year.

**Comment by squidfunk** [comment]
Note that this only applies to the WebKit scrollbar. I'm not sure it's a good idea to set overflow to hidden, since this might reposition the content of the scrollable container (i.e. the sidebar) on some browsers, leading to jaggy behavior.

**Comment by krahets** [comment]
> Note that this only applies to the WebKit scrollbar. I'm not sure it's a good idea to set `overflow: hidden`, since this might reposition the content of the scrollable container (i.e. the sidebar) on some browsers, leading to jaggy behavior.

Thank you for the suggestion! I'm about to try the beta version and close the issue.
