### ISSUE TITLE
[Tags plugin] option to create links to search instead of turn tags page? 

### ISSUE THREAD

**Issue by twardoch** [squidfunk/mkdocs-material#4732]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

There MkM search is great, and the new MkM9 search is even better.

I use tags on my store that are actually hashtags: 

https://help.fontlab.com/fontlab/8/tutorials/calfonts/2.%20Honing/2c-0a%20PROJECT%20Fixing%20the%20S%20Problem/

The tags (which I list at the bottom of the page) link to the collective tags page, which can get large and load very slowly;

https://help.fontlab.com/fontlab/8/reference/topics/#curvature

But I found I get much better experience if I use the search: 

https://help.fontlab.com/fontlab/8/?q=%23curvature*

So in the in-page listings, I’d love to have an option that, when the tags are added to each rendered page, links them to a search query instead of the tags page.

### Use Cases

The tags page is a kind of an index and search is one, too. The search functionality is much faster than loading a large tags index page. If one uses unique tags (e.g slugified & prefixed with`#`), then turn tags index page is almost unnecessary. Using the search functionality with such tags as query params gives better experience.

**Comment by squidfunk** [comment]
Thanks for suggesting. Yes, that's possible and I also understand the use case. However, I don't know if many users would need that functionality. Let's let this sit for a while and see if it is needed. Additionally, I'll check if/how this can be implemented. I'll follow up on this as soon as Material for MkDocs 9 is out, since this needs my focus now.

**Comment by twardoch** [comment]
I understand. I just realized that an additional benefit of my suggested approach would be that this could allow to… skip the need to create of the stub tags.md file altogether, and skip the need to parse the pages twice etc. Well, in fact that’s like a case for a much _simpler_ “tags” plugin! :) Or possibly even no plugin, just a simple Jinja block! 

(This just follows my thinking that, well, the search index is already an index, and the tags.md is just… abbieget index :) )

**Comment by twardoch** [comment]
Well, I’ll put it differently: I can still use the tags plugin to build tags.md and the per-category tag “minilists” that we talked about some months ago. 

But this is distinct from the building of the tags list on every single page — for that, I can just use my own Jinja block partial. Yeah, that’ll work :)

**Comment by squidfunk** [comment]
... or wait, yes, it'll be a better idea if you just override the tags partial and implement the functionality yourself, since no changers to the tags plugin are necessary, only to the partial 😊 Closing as customization.

**Comment by twardoch** [comment]
Yes, that's what I realized. Thanks!
