### ISSUE TITLE
[Tags plugin] option to slugify & prefix tags

### ISSUE THREAD

**Issue by twardoch** [squidfunk/mkdocs-material#4734]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

As mentioned in https://github.com/squidfunk/mkdocs-material/issues/4732 I use tags that are slugified & prefixed with `#` (= hashtags). Right now I’m putting the hashtags into my Markdown metadata in the slugified, prefixed way: 

```
tags: 
  - #bezier-curves
  - #font-info 
```

This is OK but might be considered inelegant. 

I’d like an option to slugify & prefix the tags at build time (perhaps it could be simple: `hashtags: true` could just always slugify & prefix with `#`). 

Then my MD metadata could have a semantically better content:

```
tags: 
  - Bezier curves
  - Font info 
```

and the tags plugin would convert them to hashtags at docs build, so that in the compiled HTML they become hashtags. 

### Use Cases

This would offer an experience familiar to many users who use Insta or Twitter, but would allow cleaner docs sources. 

Using hashtags instead of text tags in the HTML makes the hashtags more unique, and would work better with the search integration proposed in https://github.com/squidfunk/mkdocs-material/issues/4732

**Comment by squidfunk** [comment]
Thanks for asking. Tag slugification (which is used for URLs) is already customizable via [`tags_slugify`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#+tags.tags_slugify). What you're asking is applying the slugification function to the name and then prefixing it with a custom string or character. I regard this as a customization request, which I recommend solving [with a hook at build time](https://www.mkdocs.org/user-guide/configuration/#hooks) (upgrade to MkDocs 1.4.2 first). It's actually quite trivial to implement. You can then transform each tag as you like. Probably something like:

``` py
from markdown.extensions.toc import slugify
from mkdocs.plugins import event_priority

@event_priority(+100)
def on_page_markdown(markdown, *, page, config, files):
    if "tags" in page.meta:
        for t, tag in enumerate(page.meta["tags"]):
          slugified = slugify(tag, "-")
          page.meta["tags"][t] = f"#{slugified}"
```

**Comment by twardoch** [comment]
Oh, thanks! :) That's very useful. Yes, in general I don't think all the stuff needs to be in the core of the theme :)
