### ISSUE TITLE
Link color using default `indigo` instead of custom `primary`

### ISSUE THREAD

**Issue by kcgthb** [squidfunk/mkdocs-material#4755]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

This looks a lot like #4620, except the custom primary color is correctly applied to the header, but not to `<a>` hyperlinks, which appear to still be using the default `indigo` color.

### Expected behaviour

Hyperlinks use the custom `--md-primary-fg-color` color.

### Actual behaviour

Hyperlinks use the default `indigo` color.

### Steps to reproduce

With the following `extra_css`:
```
[data-md-color-scheme="sherlock"] {
  --md-primary-fg-color:               #8c1515;
  --md-primary-fg-color--light:        #b1040e;
  --md-primary-fg-color--dark:         #820000;
  --md-accent-fg-color:                #b1040e;
  --md-accent-fg-color--transparent:   #b1040e0a;
}
```
and this in `mkdocs.yml`:
```
  palette:
    - scheme: sherlock
```

the site renders like this:
![image](https://user-images.githubusercontent.com/186807/207200052-fdd1d39f-f10d-4187-a3d2-f6d5faa4f8b2.png)

Hyperlinks are rendered as #4051b5 instead of #8c1515 like the header.

----
When changing the `extra_css` syntax to use [custom colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors) instead of a [custom color scheme](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes), things seem to work as expected.

With no `palette` in `mkdocs.yml`, and the following as `extra_css`:
```
:root > * { 
  --md-primary-fg-color:               #8c1515;
  --md-primary-fg-color--light:        #b1040e;
  --md-primary-fg-color--dark:         #820000;
  --md-accent-fg-color:                #b1040e;
  --md-accent-fg-color--transparent:   #b1040e0a;
}
```
hyperlinks are correctly rendered as the custom ` --md-primary-fg-color`: 
![image](https://user-images.githubusercontent.com/186807/207200329-b1a1572f-7f1c-4fd4-a683-c5235d51164d.png)

### Package versions

- Python: `3.10.9`
- MkDocs: `1.4.2`
- Material: `8.5.11+insiders.4.26.6`

### Configuration

```yaml
palette:
    - scheme: custom
```

### System information

- Operating system: All
- Browser: All

**Comment by squidfunk** [comment]
Thanks for reporting. Does it also happen with the latest beta? Please check #4714.

**Comment by kcgthb** [comment]
Thanks for the suggestion! I just tried 9.0.0b4 but stumbled upon an error building/serving the site:
```
ERROR    -  Error building page 'docs/index.md': Replacement index 0 out of range for positional args tuple
Traceback (most recent call last):
  File "/usr/bin/mkdocs", line 6, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 83, in serve
    builder(config)
  File "/usr/lib/python3/dist-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/lib/python3/dist-packages/mkdocs/commands/build.py", line 329, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/usr/lib/python3/dist-packages/mkdocs/commands/build.py", line 231, in _build_page
    output = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/kilian/Work/Web/sherlock/main/overrides/main.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/kilian/.local/lib/python3.10/site-packages/material/base.html", line 173, in top-level template code
    {% block container %}
  File "/home/kilian/.local/lib/python3.10/site-packages/material/base.html", line 176, in block 'container'
    {% block content %}
  File "/home/kilian/.local/lib/python3.10/site-packages/material/base.html", line 177, in block 'content'
    {% include "partials/content.html" %}
  File "/home/kilian/.local/lib/python3.10/site-packages/material/partials/content.html", line 18, in top-level template code
    {% include "partials/feedback.html" %}
  File "/home/kilian/.local/lib/python3.10/site-packages/material/partials/feedback.html", line 35, in top-level template code
    {{ rating.note.format(url = url, title = title) }}
IndexError: Replacement index 0 out of range for positional args tuple
```

That's with the same `mkdocs.yml` that's working with `mkdocs-material-8.5.11-insiders-4.26.6`.

Trying to isolate the issue now, but I'm not exactly sure where to look, because `docs/index.md` doesn't have any front-matter that would override the defaults, and we don't have any partial override for `feedback` either. So if you have any pointers :)

**Comment by kcgthb** [comment]
Ok, found the cause: turns out we had a `{}` in the URL for our feedback form (in a `feedback.ratings.note` value), that tripped the parser in 9.0.0b4 (but somehow did not cause any issue in 8.5).

Anyway, back to the original question: yes, I can reproduce the same behavior with the latest beta, **except** that using `:root > *` instead of `[data-md-color-scheme="custom"]` in the custom CSS doesn't work as a workaround anymore: `indigo` is used for hyperlinks in both cases:

![image](https://user-images.githubusercontent.com/186807/207480946-e4705e8f-a2ef-49d6-bed3-1c2f0effa628.png)

**Comment by squidfunk** [comment]
Okay, I think I found the cause First of all, if you set your colors on `:root`, it should work as expected:

``` css
:root {
  --md-primary-fg-color: #8c1515;
  --md-primary-fg-color--light: #b1040e;
  --md-primary-fg-color--dark: #820000;
  --md-accent-fg-color: #b1040e;
  --md-accent-fg-color--transparent: #b1040e0a;
}
```

This does not match the documentation, which I'll update in a second. In fact, we changed it recently (can't find the issue right now, GitHub please improve issue search). The problem is that when you override the variables as part of a color scheme, the typeset variable is not changed and will keep the value that was set on the `:root`, because that's how CSS variables work. This is also the reason why the default scheme and slate scheme both need to redefine all variables:

https://github.com/squidfunk/mkdocs-material/blob/1a7616a337da73a61eebb8081b7b2c5768e7166a/src/assets/stylesheets/main/_colors.scss#L48-L50

The slate scheme overrides all variables anyway, which is why it doesn't extend the `%root` placeholder in this instance. So, how can you solve the problem? By setting the variables explicitly again for your color scheme:

https://github.com/squidfunk/mkdocs-material/blob/1a7616a337da73a61eebb8081b7b2c5768e7166a/src/assets/stylesheets/palette/_scheme.scss#L31-L118

Yes, it's not ideal, but the problem is that there are so many different combinations of enabling primary and accent colors and overriding stuff, that it is absolutely impossible to cater to all of those cases.

``` css
[data-md-color-scheme=sherlock] {
  --md-primary-fg-color: #8c1515;
  --md-primary-fg-color--light: #b1040e;
  --md-primary-fg-color--dark: #820000;
  --md-accent-fg-color: #b1040e;
  --md-accent-fg-color--transparent: #b1040e0a;

  --md-typeset-a-color: var(--md-primary-fg-color);
}
```

This is only the case because you define a new color scheme. I'm closing this issue as not fixable, but it is actually fixable by you, the user, by providing the additional variables that you want overwritten. I'm sorry for the inconvenience.

**Comment by squidfunk** [comment]
I made up my mind: I changed it to "fix available" because it can be fixed with one additional line.

**Comment by kcgthb** [comment]
Thanks @squidfunk !

> Could you please report this in #4714? That way we won't forget to add it to the changelog. [The format changed](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#+analytics.feedback.ratings.note) and the nameless placeholders were removed in v9.

Sure, done. And thanks for the pointer! 

> Regarding the issue: I see. The problem is that it is impossible to anticipate and cater to all use cases that users employ to override the CSS. There will always be some combinations that need extra work. I will investigate if this can be fixed, but otherwise I would kindly ask you to make the CSS selector more specific. This will work in any case.

I'm just adding an extra CSS with a custome `[data-md-color-scheme="custom"] { }` color scheme, as indicated in the [documentation](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes), with the expectation that all `<a>` tags will use the `--md-primary-fg-color` color. 

But I see your point about the need to redefine all the variables.

> I made up my mind: I changed it to "fix available" because it can be fixed with one additional line.

Looking forward to that fix or documentation update ;)
Thanks again!

**Comment by kcgthb** [comment]
Actually, I can easily reproduce the original issue just by cloning the [MkDocs Material repo](https://github.com/squidfunk/mkdocs-material), and following the [docs](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes) to create a custom color scheme.

`mkdocs.yml`:
```
theme:
  palette:
    - scheme: youtube

extra_css:
  - assets/stylesheets/custom.css 
```

`docs/assets/stylesheets/custom.css`:
```
[data-md-color-scheme="youtube"] {
  --md-primary-fg-color:        #EE0F0F;
  --md-primary-fg-color--light: #ECB7B7;
  --md-primary-fg-color--dark:  #90030C;
}
```

![image](https://user-images.githubusercontent.com/186807/207729245-2c7c3522-0bf2-408c-af7c-02a41548399d.png)

**Comment by squidfunk** [comment]
Yes, as I said, it's just not possible with custom color schemes. Very few users do that, actually, so it's nothing we can optimize for. Most users override colors on `root` or existing color schemes.

**Comment by kcgthb** [comment]
Got it. 

So if it's not possible to do it anymore, would it be worth updating the documentation to remove the [Custom color schemes](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes) section?

**Comment by squidfunk** [comment]
Yes, PR appreciated. Something that notes that if you use a custom color scheme, you need to redefine all deduced variables. As said, it's not necessary if you just override colors on `:root`.

**Comment by kcgthb** [comment]
Sorry, but I'm a bit confused here: if the only way to override colors is to do it on `:root`, how can it be combined with custom color schemes like `[data-md-color-scheme="youtube"]`? Do you have an example?

Right now, in the documentation, there are two approaches proposed:
1. [custom colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-colors)
2. [custom color schemes](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes)

If the only working way is to use 1., then 2. should probably be removed from the documentation to avoid any confusion.

**Comment by squidfunk** [comment]
A custom color schemes would need to enumerate all variables again in order to override all of them. Otherwise for some the defaults would be used, as they are "locked in" one level aboce the `body` elements, where custom color schemes are applied. Thus, the custom colors section doesn't suffer from this problem, only custom color schemes. We could remove custom color schemes from the documentation, but I put it there for users to know what it's actually possible to create those. The documentation is incomplete though, as it should mention those shortcomings due to technical limitations.

**Comment by SubordinalBlue** [comment]
I'd like to have a custom dark theme—however I'm unclear: can slate be overridden with just the extra.css file, or must it be done at the level of scss (as slate is defined in _scheme.scss)?

If the later, would I need to rebuild mkdocs-material itself?

**Comment by squidfunk** [comment]
Yes, you can override parts or slate entirely, or define a new theme. Our documentation mentions how to do that, but if you need help, please create a discussion.
