### ISSUE TITLE
Minor defect in pymdownx.json schema

### ISSUE THREAD

**Issue by ChrisMayfield** [squidfunk/mkdocs-material#4768]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [ ] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [ ] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The YAML schema validation for pymdownx.snippets is incorrect. `base_path` should be an array of strings, not a string.

To fix this issue, I believe you can simply replace [Line 464](https://github.com/squidfunk/mkdocs-material/blob/master/docs/schema/extensions/pymdownx.json#L464) with a copy of Lines 468-474.

### Expected behaviour

When defining `base_path` in mkdocs.yml, the YAML should validate correctly.

### Actual behaviour

VSCode flags my `base_path` as an error, even though the site builds correctly and uses snippets under both paths:

![vscode](https://user-images.githubusercontent.com/13035339/208101790-177ae571-5f4b-4da5-8a8b-9303e63ab829.png)

### Steps to reproduce

See screenshot under "Actual behaviour".

### Package versions

- Python: 3.8.10
- MkDocs: 1.4.2
- Material: 8.5.11

### Configuration

```yaml
site_name: My Docs
site_url: https://example.com/docs

markdown_extensions:
  - pymdownx.snippets:
      base_path:
        - book
        - code
```

### System information

- Operating system: Linux Mint 20.3 Una (5.15.0-56-generic)
- Browser: Google Chrome 108.0.5359.98

**Comment by squidfunk** [comment]
Thanks for nothing. PR appreciated. I'm not able to track all changes, additions and removelas in all Markdown extensions and MkDocs plugins, so we're relying on users like you to tell us when something is missing. Bonus points for a PR! ⭐️
