### ISSUE TITLE
Disable toc

### ISSUE THREAD

**Issue by nodesocket** [squidfunk/mkdocs-material#478]
Is there an option to disable `Table of contents` on all page?

**Comment by connercowling** [comment]
@nodesocket did you find a solution to this?

**Comment by squidfunk** [comment]
Just remove `toc` from your `mkdocs.yml` under `markdown_extensions`.

**Comment by connercowling** [comment]
There are currently no extensions listed in my `mkdocs.yml` file.  It _appears_ `toc` is on by default, which contradicts this:

>  The following extensions are not enabled by default [...] toc
> [mkdocs-material/getting-started/#extensions](http://squidfunk.github.io/mkdocs-material/getting-started/#extensions)

What am I missing?

**Comment by squidfunk** [comment]
Oh, that's right. I found this issue on the MkDocs tracker: https://github.com/mkdocs/mkdocs/issues/454. Also see the linked issue.

Currently MkDocs and Python Markdown provide no options to hide the toc, so it's always rendered. You can, however, use CSS to hide it quickly:

``` css
.md-sidebar--secondary {
  display: none
}
```

**Comment by connercowling** [comment]
Okay yeah, I had commented out the toc block from `base.html` but I think I like that better. 

 My underlying issue is that I'd like `md-content__inner` to expand to fill the right side of the page. This is because there are tables in the markdown that get cutoff. I set `md-content--inner` to `overflow-x: scroll`, which is better but not ideal.

Is there a reasonable means of getting the inner content to expand into the `toc` block space in the render?  This is probably simple, but I haven't been able to figure it out. Thanks.

**Comment by makshh** [comment]
@connercowling 

```css
@media only screen and (min-width: 60em) {
  .md-content {
    margin-right: 0;
  }
}
```

**Comment by connercowling** [comment]
@makshh works great. Much appreciated.

**Comment by joseterra** [comment]
@connercowling

You can use also:

markdown_extensions:
  - toc:
      toc_depth: 0

**Comment by root-ansh** [comment]
@max-ci  Hi. I am new to this. Where do we have to add your code so as to remove toc and use that space with our center content ? I tried adding in `mkdocs.yml` but got no success.

**Comment by root-ansh** [comment]
@max-ci @connerxyz @squidfunk Hi. I am new to this web designing stuff. Where do we have to add your code so as to remove toc and use that space with our center content ? I tried adding in mkdocs.yml but got no success.

**Comment by squidfunk** [comment]
It's explained in the [customization guide](https://squidfunk.github.io/mkdocs-material/customization/#additional-stylesheets)

**Comment by nigelwelham** [comment]
Is there any way of embedding such code but only in certain .md files - not for every page?
many thanks

**Comment by jevin36** [comment]
Thanks for your nice comments on this topic. After I added the CSS I sometimes saw a flickering with the TOC disappearing after 200ms so I also added a constraint for only rendering heading #1 which is basically like saying don't render anything since the TOC starts at heading #2

```
markdown_extensions:
    - toc:
        toc_depth : "1-1"
```

**Comment by slavianap** [comment]
> Thanks for your nice comments on this topic. After I added the CSS I sometimes saw a flickering with the TOC disappearing after 200ms so I also added a constraint for only rendering heading #1 which is basically like saying don't render anything since the TOC starts at heading #2
> 
> ```
> markdown_extensions:
>     - toc:
>         toc_depth : "1-1"
> ```

Thank you, it works!

**Comment by hpcaicom** [comment]
@connerxyz  I have the same requirement with you, I need add the space for md-content__inner to hold the table. Where did you make the changes on md-content__inner, I add  the below into the extra.css, but it doesn't work. And is there a way to make it take effect just on some pages.
@media only screen and (min-width: 60em) {
  .md-content {
    margin-right: 0;
  }
}

**Comment by qmel** [comment]
for me
```
...
# to exclude any headers from table of content and search
'toc' : {
    'baselevel' : 2,
    'toc_depth' : 1
}
...
```
and 
```
...
'toc' : {
    'toc_depth' : 0
}
...
```
worked well in 1.4.2 version

**Comment by jhshi31** [comment]
I think I found a solution. You can manually put this code block in your .md files to prevent the toc from appearing.

```
---
hide:
  - navigation
  - toc
---
```

https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#hiding-the-sidebars
