### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by ronakdev** [squidfunk/mkdocs-material#48]
1. Add scroll animation (when you click on a sub header.
2. Add option to remove "Download" and "Stars" Buttons

If you could make these options and changes, that would be much appreciated! 

As of right now, this is one of the best (if not the best) themes for mkdocs. However, there are a few minor problems (as listed above) that can really detract from a site, especially one that isn't a documentation site, but rather a reference/wiki built on mkdocs.

**Comment by squidfunk** [comment]
The theme is currently being reworked and should be released shortly.

1. Already considered it, may be added in a future release. However, this can now also be done with custom JavaScript with a library of your choice.
2. The buttons will not be present in the reworked theme.

Please see ticket #46 for an extensive list.

**Comment by ronakdev** [comment]
Thanks for replying!

(I'm not really that great with javascript) How would you implement (1)?

**Comment by makshh** [comment]
@ronakdev you can use this custom JavaScript code:

```
$(function() {
  $('a[href*="#"]:not([href="#"])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
      var target = $(this.hash);
      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
      if (target.length) {
        $('html, body').animate({
          scrollTop: target.offset().top
        }, 1000);
        return false;
      }
    }
  });
});
```

**Comment by squidfunk** [comment]
@makshh yes, that should work. However, you will need to add jQuery as a dependency through custom JavaScript. You could also adapt this script, which doesn't depend on jQuery (not tested!):
http://stackoverflow.com/a/24559613/1065584
