### ISSUE TITLE
Self-host MathJax

### ISSUE THREAD

**Issue by nodesocket** [squidfunk/mkdocs-material#481]
Is it possible to self host MathJax?

I tried:

```
extra_javascript:
    - 'javascript/mathJax.js?config=TeX-MML-AM_CHTML'
```

And created the file `javascript/mathJax.js` from [https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML](https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML) but getting an error about `MathZoom.js` and `MathMenu.js` missing `404`.

**Comment by facelessuser** [comment]
This isn't really a question for theme mkdocs-material. This is more a question for mkdocs.

You can host your own, but mathjax is more than just one js file. See here: https://cdnjs.com/libraries/mathjax.  Unfortunately, I have no idea how you've actually set everything up as you've only provided  a snippet of your config file, so I can't really advise you any more than you need to include all of MathJax, and *hopefully* Mkdocs just uploads all JS files even if it isn't specified in your `extra_javascript` setting.

**Comment by squidfunk** [comment]
Thanks @facelessuser, full ack. Closing this question as answered.

**Comment by schemacs** [comment]
@nodesocket lots of files will be served:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/434358/57172326-f4805180-6e50-11e9-8302-817d3e4b7e65.png">
