### ISSUE TITLE
Long abbreviations don't wrap to new line in Firefox for Android

### ISSUE THREAD

**Issue by harry643** [squidfunk/mkdocs-material#4810]
### Context

Device: Samsung Galaxy S10
Android version: 12
Firefox version: 108

### Bug description

Long abbreviations extend the entire page width instead of wrapping to new line. Screenshot attached.
![long-abbreviation-on-mobile](https://user-images.githubusercontent.com/8885267/210239368-196c1be3-6fb3-4486-a713-517cfa8e2cb5.jpg)

### Related links

- [Bug reporting](https://squidfunk.github.io/mkdocs-material/bug-report/)
- [Adding abbreviations](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations)
- [Python-Markdown Abbreviations](https://python-markdown.github.io/extensions/abbreviations/)

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10332484/example.zip)

### Steps to reproduce

1. Create an [abbreviation](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations) description longer than 100 characters.
2. Publish the site online.
3. Access the site via Firefox 108 for Android.
4. Tap the abbreviation.

### Browser

Firefox

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Abbreviations in the community edition are a hack, as they are implemented using only CSS. Thus, positioning is very limited. I'll investigate whether we can improve the hack, but it will be removed when tooltips are released into the community edition anyway.

Note that this does not happen when [tooltips](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#improved-tooltips) are enabled.

**Comment by squidfunk** [comment]
Fixed in fbfb66258. Abbreviations will now span the entire screen, which is the best thing we can do without JavaScript. As noted, the behavior was improved in Insiders with [tooltips](https://squidfunk.github.io/mkdocs-material/reference/tooltips/), which automatically position to the available screen estate.

Excellent reproduction by the way, made fixing the bug straight forward. Thanks!

<img width="399" alt="Bildschirmfoto 2023-01-02 um 17 08 39" src="https://user-images.githubusercontent.com/932156/210255729-81c7cc43-98ac-4d05-9f5d-14bfbaed4d17.png">

**Comment by harry643** [comment]
That was an incredibly quick fix. Thanks so much.

**Comment by squidfunk** [comment]
Released as part of 9.0.1.
