### ISSUE TITLE
social cards plugin crashes when logo defined in theme config

### ISSUE THREAD

**Issue by dgoosens** [squidfunk/mkdocs-material#4812]
### Bug description

when a logo is defined in the theme config:

```yml
theme:
  logo: assets/images/logo.svg
```

and the social plugin is enabled, the logo can not be loaded and the system crashes (locally)

```bash
FileNotFoundError: [Errno 2] No such file or directory: '/docs/docs/assets/images/logo.svg'
```

if I change the path of the logo to:

```yml
theme:
  logo: ../overrides/assets/images/logo.svg
```

the system runs, the social cards are generated...  
BUT the logo is not available on the rendered site

**Also note that if custom fonts (non Google) are defined and are located in the `overrides` directory, one has to define a Google font for the social card plugin to work**

### Related links

- <https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#image>
- <https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/>

### Reproduction

simply define a logo, that is located in the `overrides` directory, in the theme section of `mkdocs.yml`  
and enable the social plugin

```yml
#...
theme:
  custom_dir: overrides
  logo: assets/images/logo.svg
#...

plugins:
#...
  - social:
      cards: true
      cards_font: Roboto
#...
```

### Steps to reproduce

1. configure as indicated above
2. make sure the dependencies are installed
3. start local environment

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by dgoosens** [comment]
I temporary managed to hack this by setting the font as required by the social plugin

```yml
theme:
  logo: ../overrides/assets/images/logo.svg
```

and by defining a partial override of the `logo.html` partial

```html
<!-- overrides/partials/logo.html -->

<img src="{{ 'assets/images/logo.svg' | url }}" alt="logo">
```

**Comment by squidfunk** [comment]
Thanks for reporting. However, this issue is incomplete. 

Note that we have new [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/), which is also mentioned in the descriptions in the bug reporting template you filled out. You did not provide a reproduction, which is why we can't look into this issue. Please read our new bug reporting guidelines and how to [create a reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment]
Closing as incomplete and not reproducible. If you can provide a reproduction, please reopen.
