### ISSUE TITLE
Google analytics integration anonymizeIp value

### ISSUE THREAD

**Issue by nodesocket** [squidfunk/mkdocs-material#482]
Is it possible to modify the Google Analytics integration from setting `ga("set","anonymizeIp",!0)` to `ga("set","anonymizeIp",false)`. A default value of `true` renders IP based filters in Google Analytics not possible since full IP addresses are not sent.

```
# mkdocs.yml
google_analytics:
    - 'UA-XXXXXXXXX-1'
    - 'auto'
```

**Comment by squidfunk** [comment]
That's not possible, I'm sorry. The `google_analytics` key is defined by MkDocs. Please open an issue to be able to pass more data to the GA integration. The Material theme only uses that information.

**Comment by squidfunk** [comment]
Closing this, as in my opinion it should be fixed in the upstream repository. There should be more configuration options to GA. Adding a third key to the list produces the following error:

```
ERROR   -  Config value: 'google_analytics'. Error: Expected type: <type 'list'> with lenght 2 but recieved: [None, u'auto', False] with length 3 
```

You may open an issue on the MkDocs issue tracker.

**Comment by dquimper** [comment]
You can overwrite the partial and add whatever you want.
Partial: `partials/integrations/analytics.html`

Instructions: https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials
