### ISSUE TITLE
Search plugin crashes for `h[1-6]` contained in other elements

### ISSUE THREAD

**Issue by jeffreytolar** [squidfunk/mkdocs-material#4824]
### Context

Our CI recently pulled in the newly released 9.0.1 this week; the build for one of our sites started failing afterwards.

### Bug description

We have some old (non-ideal) markdown that crashes the search plugin during indexing:
```
$ ../bin/mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /private/tmp/mkdocs/test/site
ERROR    -  Error building page 'index.md': list index out of range
Traceback (most recent call last):
  File "/tmp/mkdocs/test/../bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/mkdocs/commands/build.py", line 329, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/mkdocs/commands/build.py", line 226, in _build_page
    context = config.plugins.run_event(
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/material/plugins/search/plugin.py", line 90, in on_page_context
    self.search_index.add_entry_from_context(page)
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/material/plugins/search/plugin.py", line 143, in add_entry_from_context
    parser.feed(page.content)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/html/parser.py", line 420, in parse_endtag
    self.handle_endtag(elem)
  File "/private/tmp/mkdocs/lib/python3.9/site-packages/material/plugins/search/plugin.py", line 417, in handle_endtag
    elif data[-1].isspace() and data[-2] == f"<{tag}>":
IndexError: list index out of range
```

The markdown that results in this is a section header in a list:
```markdown
- # Section header in a list
```

... disabling the `search` plugin, that snippet results in this HTML:
```
<ul>
<li>
<h1 id="section-header-in-a-list">Section header in a list</h1>
</li>
</ul>
```

- - -

It's entirely possible that this is "invalid" markdown - however, this did "work" (not crash) with previous releases (including 8.5.11).

We have no real need for that that hierarchy (I suspect it was originally a typo), so I've updated our site to remove the bullet points. It took some digging (aided by [`breakpoint()`](https://peps.python.org/pep-0553/) :)) to narrow down which part of the file was triggering the crash.

- - -

Changing https://github.com/squidfunk/mkdocs-material/blob/c8fb426d988e9cdf75054347e4152ac0063528e1/material/plugins/search/plugin.py#L417 to include a check for `len(data) >= 2` results in a successful build, although I'm not sure the generated search index makes sense:
```json
$ jq . site/search/search_index.json
{
  "config": {
    "lang": [
      "en"
    ],
    "separator": "[\\s\\-]+",
    "pipeline": [
      "stopWordFilter"
    ]
  },
  "docs": [
    {
      "location": "",
      "title": "Welcome to MkDocs",
      "text": "<ul> <li>"
    },
    {
      "location": "#section-header-in-a-list",
      "title": "Section header in a list",
      "text": "</li> </ul>"
    }
  ]
}
```

### Related links

- [Bug reporting](https://squidfunk.github.io/mkdocs-material/bug-report/)
- #4714
- https://squidfunk.github.io/mkdocs-material/blog/2021/09/13/search-better-faster-smaller/

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10340665/example.zip)

### Steps to reproduce

Run `mkdocs build` with the attached zip (probably need to remove `info` from the mkdocs.yml)

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment]
I've generalized the title, so it's easier to find for other users.

**Comment by defenestration** [comment]
We also ran into this. 

Additionally, numbered lists immediately followed by an octothorpe also caused this problem for us. ex: `1. ### blah`

We also found some docs with an empty list items, that caused a similar error with the search plugin. ( let me know if you want a separate issue opened?) 

We ended up just cleaning up the docs but didn't have this issue on 8.x.

```markdown 
    -   NetApp SnapDrive/LUN vs VMDK
    - 
```

```
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 329, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 226, in _build_page
    context = config.plugins.run_event(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 90, in on_page_context
    self.search_index.add_entry_from_context(page)
  File "/usr/local/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 143, in add_entry_from_context
    parser.feed(page.content)
  File "/usr/local/lib/python3.11/html/parser.py", line 110, in feed
    self.goahead(0)
  File "/usr/local/lib/python3.11/html/parser.py", line 172, in goahead
    k = self.parse_endtag(i)
        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/html/parser.py", line 413, in parse_endtag
    self.handle_endtag(elem)
  File "/usr/local/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 417, in handle_endtag
    elif data[-1].isspace() and data[-2] == f"<{tag}>":
                                ~~~~^^^^
IndexError: list index out of range
```

**Comment by squidfunk** [comment]
Fixed in 81e7b8c7f. Interesting problem! This was tricky, but I think I found a generalizable solution. The search plugin will now track the depth of sections when parsing, and attribute content to the nearest unclosed section. A section is considered closed, once it's exited. Now, nested headlines should work without any problems.

I'm now looking into a better approach for filtering empty paragraphs and tags that is more resilient, which I removed temporarily to fix the nesting problem first. Expect a fix later today.

__Example__:

``` markdown
# Example

- ## List

    !!! info "Admonition title"

        Admonition content (before)

        ### Admonition

        Admonition content (after)

    List content 1

    - ### Nested list

        Nested list content

    List content 2

Some other text

## Foo

Bar

!!! info "Admonition title 2"

    Admonition content 2 (before)

    # Admonition 2

    Admonition content 2 (after)
```

__Result__:

``` json5
{
  // ...
  "docs": [
    {
      "location": "",
      "title": "Example",
      "text": "<ul> <li> </li> </ul> <p>Some other text</p>"
    },
    {
      "location": "#list",
      "title": "List",
      "text": "<p>Admonition title</p> <p>Admonition content (before)</p>  <p>List content 1</p> <ul> <li> </li> </ul> <p>List content 2</p>"
    },
    {
      "location": "#admonition",
      "title": "Admonition",
      "text": "<p>Admonition content (after)</p>"
    },
    {
      "location": "#nested-list",
      "title": "Nested list",
      "text": "<p>Nested list content</p>"
    },
    {
      "location": "#foo",
      "title": "Foo",
      "text": "<p>Bar</p>  <p>Admonition title 2</p> <p>Admonition content 2 (before)</p>"
    },
    {
      "location": "#admonition-2",
      "title": "Admonition 2",
      "text": "<p>Admonition content 2 (after)</p>"
    }
  ]
}
```

**Comment by squidfunk** [comment]
68257348b makes collapsing of adjacent whitespace and removal of empty elements more resilient. This results in the following, more compact search index that only includes paragraphs with content:

``` json5
{
  // ...
  "docs": [
    {
      "location": "",
      "title": "Example",
      "text": "<p>Some other text</p>"
    },
    {
      "location": "#list",
      "title": "List",
      "text": "<p>Admonition title</p> <p>Admonition content (before)</p> <p>List content 1</p> <p>List content 2</p>"
    },
    {
      "location": "#admonition",
      "title": "Admonition",
      "text": "<p>Admonition content (after)</p>"
    },
    {
      "location": "#nested-list",
      "title": "Nested list",
      "text": "<p>Nested list content</p>"
    },
    {
      "location": "#foo",
      "title": "Foo",
      "text": "<p>Bar</p> <p>Admonition title 2</p> <p>Admonition content 2 (before)</p>"
    },
    {
      "location": "#admonition-2",
      "title": "Admonition 2",
      "text": "<p>Admonition content 2 (after)</p>"
    }
  ]
}
```

Additionally, the case with empty lists reported by @defenestration doesn't crash the plugin.

**Comment by squidfunk** [comment]
Released as part of [9.0.3](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.3).

**Comment by danimesq** [comment]
@squidfunk, is it possible to downgrade mkdocs-material?

I'm getting the following errors:

> floflis-docs on  main [!+] 
> ❯ mkdocs serve
> INFO     -  Building documentation...
> INFO     -  Cleaning site directory
> Traceback (most recent call last):
>   File "/usr/bin/mkdocs", line 6, in <module>
>     cli()
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/daniella/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 234, in serve_command
>     serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
>   File "/home/daniella/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 83, in serve
>     builder(config)
>   File "/home/daniella/.local/lib/python3.10/site-packages/mkdocs/commands/serve.py", line 76, in builder
>     build(config, live_server=live_server, dirty=dirty)
>   File "/home/daniella/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 320, in build
>     _build_theme_template(template, env, files, config, nav)
>   File "/home/daniella/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 118, in _build_theme_template
>     output = _build_template(template_name, template, files, config, nav)
>   File "/home/daniella/.local/lib/python3.10/site-packages/mkdocs/commands/build.py", line 97, in _build_template
>     output = template.render(context)
>   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
>     self.environment.handle_exception()
>   File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
>     raise rewrite_traceback_stack(source=source)
>   File "/home/daniella/.local/lib/python3.10/site-packages/material/404.html", line 4, in top-level template code
>     {% extends "main.html" %}
>   File "/home/daniella/.local/lib/python3.10/site-packages/material/main.html", line 4, in top-level template code
>     {% extends "base.html" %}
>   File "/home/daniella/.local/lib/python3.10/site-packages/material/base.html", line 192, in top-level template code
>     {% block footer %}
>   File "/home/daniella/.local/lib/python3.10/site-packages/material/base.html", line 193, in block 'footer'
>     {% include "partials/footer.html" %}
>   File "/home/daniella/.local/lib/python3.10/site-packages/material/partials/footer.html", line 50, in top-level template code
>     {% include "partials/social.html" %}
>   File "/home/daniella/.local/lib/python3.10/site-packages/material/partials/social.html", line 12, in top-level template code
>     {% include ".icons/" ~ social.icon ~ ".svg" %}
>   File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 214, in get_source
>     raise TemplateNotFound(template)
> jinja2.exceptions.TemplateNotFound: .icons/fontawesome/solid/tachometer-alt.svg

I rather for getting a fix patch or a workaround solution instead of downgrading.

**Comment by danimesq** [comment]
Gotcha! The "tachometer" reference icon is from an older version of fontawesome.

Its now called "gauge-high"
