### ISSUE TITLE
Incorrect Footnote Link Jump

### ISSUE THREAD

**Issue by Mehran-Baghi** [squidfunk/mkdocs-material#483]
## Description

 #91 bug with [`Footnotes`](http://squidfunk.github.io/mkdocs-material/extensions/footnotes/) extension.

### Package versions

* Python: `Python 2.7.13`
* MkDocs: `mkdocs, version 0.16.3`
* Material: `Version: 1.10.2`

**Comment by squidfunk** [comment]
Confirmed. Will provide a fix.

**Comment by squidfunk** [comment]
Should be fixed with #485, regression error. Will make a release shortly.

**Comment by squidfunk** [comment]
Fix released with 1.10.3
