### ISSUE TITLE
Warn when a plugin takes too long to build for live reload

### ISSUE THREAD

**Issue by Emmanuel-Messulam** [squidfunk/mkdocs-material#4834]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Live reload should be as fast as possible. It would be a good idea to time the different plugins at different stages of page building, so that a warning is issued if a plugin takes too long.

### Use Cases

Mostly with large sites, and with a few heavy plugins. It would be useful which one is the slowest to replace it.

### Screenshots / Mockups

```
WARNING  -  It seems that plugin aaa-bbb-plugin took 2.5 seconds to build a.md, this might slow down live reloads.
```

**Comment by squidfunk** [comment]
Thanks for suggesting. This is something that should be suggested to [MkDocs](https://github.com/mkdocs/mkdocs), not Material for MkDocs, since we're "only" a theme with some plugins. MkDocs itself is the underlying engine which builds your project.
