### ISSUE TITLE
accessibility error: empty container

### ISSUE THREAD

**Issue by mnazzaro** [squidfunk/mkdocs-material#4842]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

This relates to a `<ol>` element used for search results, which is empty whenever the user is not doing a search. The `<ol>` has an implicit role="list" attribute, so the screen reader expects it to have list items and throws an error if it does not.   

I think the simplest solution is to add role="presentation" to the `<ol>` by default, and then remove that role (or change it to role="list") when the user clicks into the search bar.  

To test, install the SiteImprove accessibility checker for Chrome and run on any mkdocs page. 

Here is a link to a simple example solution, which would need to be adapted for a PR: https://github.com/arXiv/arxiv-docs/commit/0e5871d06b02ea31318105f3e3076505439c8be1

### Use Cases

This will be another accessibility win, and will make mkdocs fully compliant with SiteImprove on load.

**Comment by squidfunk** [comment]
Thanks for reporting. Edited for clarity. Please enclose tags with backticks, or the formatting will be jammed. Also note that errors should be bug reports, not feature requests.

**Comment by mnazzaro** [comment]
Ah sorry about the formatting. I found the bug report form requirements to be too stringent- I didn't have a zip file to upload, but I'll make sure to do that next time.

**Comment by mnazzaro** [comment]
Yes of course. Could that just be a zipped up mkdocs project that exhibits the issue? I wasn't sure exactly what you were looking for either

**Comment by squidfunk** [comment]
The [bug reporting issue template](https://github.com/squidfunk/mkdocs-material/issues/new?assignees=&labels=&template=bug.yml) mentions our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/bug-report/), which explains in details what we need for a bug report and why. It also links to the [reproduction guide](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/), that explains clearly how to create a reproduction with [the `info` plugin](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/#creating-a-zip-file).

If you missed that when reading [our bug reporting issue template](https://github.com/squidfunk/mkdocs-material/issues/new?assignees=&labels=&template=bug.yml), how can we make that more clear?

**Comment by mnazzaro** [comment]
Ahh I see it at the bottom. I'm sorry I didn't use it! I don't want to give you any extra work; I don't think most people would miss it. It could be helpful to just copy the link to the top, if this is a common problem, though. 

My mistake, and thanks for being so responsive. Let me know if I can be of any more help on the empty container issue too.

**Comment by squidfunk** [comment]
Fixed in a200e7d63. Good catch. Happy to further improve accessibility if you find further errors!

**Comment by squidfunk** [comment]
Released as part of [9.0.5](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.5).
