### ISSUE TITLE
Issue with Emoji's

### ISSUE THREAD

**Issue by 14mC4** [squidfunk/mkdocs-material#4843]
### Context

Emojis not loading with new update

### Bug description

It seems that the Emojis are only half way working with the update. Even the Materials Docs show the error icon as see when using some emojis.

![image](https://user-images.githubusercontent.com/25674713/211424216-a351134d-b711-44a7-b257-c239d944c01d.png)

can also see live "long loading" and showing error on this page https://14mc4.github.io/hhc2022/

![image](https://user-images.githubusercontent.com/25674713/211425108-1d580e86-b3f0-4425-b0f6-26dd8c520e8a.png)

### Related links

- [Bug reporting](https://squidfunk.github.io/mkdocs-material/bug-report/)
-

### Reproduction

note sure how

### Steps to reproduce

Picked star, christmas tree and smile from emoji applied to different pages and experiencing issues using.

### Browser

Chrome, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by 14mC4** [comment]
![image](https://user-images.githubusercontent.com/25674713/211428105-ffc42183-9115-4ac4-84a3-9be43fae4deb.png)

Could be a issue with Twemoji trying to make a minimal reproduction still same thing new upgrade repo but, seen this in the network info.

**Comment by 14mC4** [comment]
https://github.com/twitter/twemoji/issues/580

![image](https://user-images.githubusercontent.com/25674713/211428451-c8905995-795d-40a4-a572-1a1fc652e1e5.png)

**Comment by abhiTronix** [comment]
+1 Bug confirmed.

**Comment by squidfunk** [comment]
Thanks for reporting. The functionality is provided by [Python Markdown Extensions](https://facelessuser.github.io/pymdown-extensions/), so it would need to reported upstream, since we can't do anything about it. The use of `maxcdn.com`, seems to be the problem. This would need to be changed [here](https://github.com/facelessuser/pymdown-extensions/blob/2f448086a5550c90f8d29660c9ee879351ecdadf/pymdownx/emoji.py#L38).

**Comment by facelessuser** [comment]
Oh, I was unaware that `maxcdn.com` went away. I guess they (Twitter) were trying to migrate it over to a new service, but then chaos at Twitter ensued and relevant people got laid off.

I can definitely update this with a relevant, new CDN. An issue over at [Python Markdown Extensions](https://facelessuser.github.io/pymdown-extensions/) would be appreciated.

**Comment by squidfunk** [comment]
The issue is now tracked in https://github.com/facelessuser/pymdown-extensions/issues/1905.

**Comment by squidfunk** [comment]
[9.0.4](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.4) was just released, which sets the minimum requirement for [pymdownx](https://facelessuser.github.io/pymdown-extensions/) to 9.9.1.
