### ISSUE TITLE
Please bring back "caution" admonition

### ISSUE THREAD

**Issue by scottamain** [squidfunk/mkdocs-material#4848]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

To the best of my ability, I could not find a bug/discussion to explain the [removal of some admonition qualifiers](https://github.com/squidfunk/mkdocs-material/commit/daffd085f3bc35058ada32fad0a21b2d88ac0d3f), including the "caution" qualifier. Using "Caution" now results in the same styling as "Note."

"Caution" is a standard notice that's recommended in the [Microsoft Manual of Style](https://www.amazon.com/Microsoft-Manual-Style-4th-Corporation/dp/0735648719), the [Google dev docs style guide](https://developers.google.com/style/notices#pick-a-notice-type) and it's used in the [Read the Docs style](https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/demo.html#admonitions) (which I believe was an original influence for these styles).

I understand it's possible to add custom admonition styles, but "caution" has a long history and I believe it should be supported as a built-in style. Could you please restore this style?

### Use Cases

A "caution" is consistently used in technical writing as a notice to proceed carefully and is one step below "warning" in the spectrum of risk. For example, use a "caution" notice for something that might cause minor or temporary harm such as loss of data, whereas "warning" for something that has a high risk of total system failure or even physical harm.

**Comment by squidfunk** [comment]
Thanks for suggesting. [`caution` was a synonym for `warning`](https://github.com/squidfunk/mkdocs-material/commit/e40c5adf285fcbaf1709ec6c4696244b234d78fd#diff-2255ac719a577e7688d9e4c1e55a8d7e4ed37319dfa9857ecd8d0723fe38561fL341). Please use [`warning`](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#type:warning) from now on. We removed additional qualifiers that resulted in the same styling, as it increased the size of our CSS with no upside.

**Comment by scottamain** [comment]
The problem is that your style choice here is also a language choice. You've decided for authors what words they can use. 

The great thing about Markdown is that the source files are still very as readable on their own. So requiring double-speak such as `warning "Caution"` is a regression in this regard because now there's extra syntax required to get the appearance you want and it makes the source file confusing to read.

Why not add a yellow color for "caution"? For example:

```
$admonitions: (
  "note":     pencil-circle         $clr-blue-a200,
  "abstract": clipboard-text        $clr-light-blue-a400,
  "info":     information           $clr-cyan-a700,
  "tip":      fire                  $clr-teal-a700,
  "success":  check                 $clr-green-a700,
  "question": help-circle           $clr-light-green-a700,

  "caution":  alert-circle          $clr-yellow-a700,

  "warning":  alert                 $clr-orange-a400,
  "failure":  close                 $clr-red-a200,
  "danger":   lightning-bolt-circle $clr-red-a400,
  "bug":      shield-bug            $clr-pink-a400,
  "example":  test-tube             $clr-deep-purple-a200,
  "quote":    format-quote-close    $clr-grey
) !default;

**Comment by squidfunk** [comment]
I'm sorry that this breaks your workflow, but you have to understand that we always have to balance convenience vs. performance, and the loss of convenience is very minor. We didn't take any functionality away, just a little convenience.

If you want the old behavior back, you can easily do so by either implementing a Markdown extension, or monkey patch support using a [hook](https://www.mkdocs.org/user-guide/configuration/#hooks) and a two-liner, e.g. something like the following should work:

`hooks/admonitions.py`

``` py
def on_page_markdown(markdown, *, page, config, files):
  return markdown.replace('!!! caution', '!!! warning "Caution"')
```

`mkdocs.yml`:

``` yaml
hooks:
  - hooks/admonitions.py
```

**Comment by squidfunk** [comment]
Additionally, I'm not sure what the semantic different between _warning_ and _caution_ should be. There were used as synonyms previously, so adding another equivalent admonition type makes no sense to me.

**Comment by squidfunk** [comment]
And, to close off this discussion, you can add even add caution back (or customize it!) using a [custom admonition type](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions):

``` CSS
.md-typeset .admonition.caution,
.md-typeset details.caution {
  border-color: #ff9100;
}
.md-typeset .caution > .admonition-title,
.md-typeset .caution > summary {
  background-color: #ff91001a;
}
.md-typeset .caution > .admonition-title::before,
.md-typeset .caution > summary::before {
  background-color: #ff9100;
  -webkit-mask-image: var(--md-admonition-icon--warning);
          mask-image: var(--md-admonition-icon--warning);
}
```

**Comment by scottamain** [comment]
Thanks for the CSS, that's what I was about to do.

I agree that the distinction between "warning" and "caution" might be subjective in casual conversation. However, in tech writing the word choice is important because it's the only way to achieve consistency, and consistency creates clarity. The word choice gets codified into a writer's style guide: One word means *this* and the other means *that*. Writers get used to it, and so do readers.

**Comment by AshleyHenry15** [comment]
I agree with @scottamain here and was pretty disappointed at the removal. Caution and Warning are wildly different in technical writing. One means that you could break your environment, and the other could mean physical harm or death.

Having to use the `tip` admonition for an `important` item also seems silly.

I haven't tested with a screen reader but this also feels like it could cause confusion from an accessibility standpoint.

But I do agree, it seems like a regression. I could see the argument for not adding these things but removing them after having them available for years stinks. 

I am now having to add customizations vs. being able to use the defaults which really takes away from using a theme in the first place.

**Comment by squidfunk** [comment]
> I could see the argument for not adding these things but removing them after having them available for years stinks.

I understand your disappointment. Please understand our viewpoint as well. As the maintainers of such a popular theme, we sometimes make decisions that turn out to be suboptimal in the end. With the `caution` and other admonition qualifiers, it was additional kilobytes added to every page, albeit they lead to the exact same styling. This is why we deprecated them in [8.5.7](https://squidfunk.github.io/mkdocs-material/changelog/#8.5.7) (October 22, 2022) and removed them in [9.0.0](https://squidfunk.github.io/mkdocs-material/changelog/#9.0.0) (January 2, 2023). This means users had more than two months two adjust for the deprecations and alter their Markdown sources. For clarity, you can bring back the exact same styling and behavior:

up to 9.0.0:

```
!!! important

    Lorem ipsum dolor sit amet
```

from 9.0.0:

```
!!! tip "Important"

    Lorem ipsum dolor sit amet
```

This means there is no loss in functionality. You just have to type out a few more characters, but the sources that you ship to your customers are significantly smaller, resulting in a faster loading time. Additionally, I've given two solutions to go back to the old behavior:

- https://github.com/squidfunk/mkdocs-material/issues/4848#issuecomment-1378331250
- https://github.com/squidfunk/mkdocs-material/issues/4848#issuecomment-1378336211

If we would stick with every decision of the past, we would not be able to push this project forward. Deprecations and removals are normal in the software world. We try to make interruptions as minimal as possible, and at the same time, if we take something away or change something significantly, always try to provide a path to revert to the old behavior, [which we recently did for our new admonition styling](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#classic-admonitions).

A theme is probably the most opinionated thing one can build.
