### ISSUE TITLE
glightbox displays both dark and light images

### ISSUE THREAD

**Issue by pulkitkrishna00** [squidfunk/mkdocs-material#4849]
### Bug description

When using dark and light images, when clicking on the image, the image according to theme is shown but on clicking left or right button, the other image is also there. It should not be shown and only one of the image should be shown.

### Related links

- <https://squidfunk.github.io/mkdocs-material/reference/images/#lightbox>

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10390087/example.zip)

### Steps to reproduce

1. Open the website.
2. Click on the image to open lightbox.
3. Click on the right or left arrow.
4. If you are using light theme, the dark mode image will be visible, if you are using dark theme, light mode image will be visible.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. However, this functionality is implemented by the [mkdocs-glightbox-plugin](https://github.com/blueswen/mkdocs-glightbox), so please report this upstream to the maintainers of the plugin. Closing as upstream issue.
