### ISSUE TITLE
Tweemoji CDN

### ISSUE THREAD

**Issue by aljazs-flare** [squidfunk/mkdocs-material#4856]
### Context

Update `pymdownx` to [9.9.1](https://github.com/facelessuser/pymdown-extensions/releases/tag/9.9.1) which replaced the Tweemoji CDN; [#1905](https://github.com/facelessuser/pymdown-extensions/issues/1905)

### Bug description

Maxcdn is went belly up.

### Related links

- https://github.com/twitter/twemoji/issues/580
- https://xenforo.com/community/threads/maxcdn-is-offline-emojis-stopped-working.211603/#post-1608562
- https://www.stackpath.com/maxcdn/
- https://github.com/facelessuser/pymdown-extensions/issues/1905

### Reproduction

Just look at any site using `maxcdn.com`

### Steps to reproduce

1. go to https://squidfunk.github.io/mkdocs-material/
2. scroll down to "10,000+ icons and emojis"
3. observe the missing emoji with the "Tada" alt text showing
4. try reaching "https://twemoji.maxcdn.com/" and see that the DNS can not be resolved

1. `drill twemoji.maxcdn.com` -> `;; ANSWER SECTION: twemoji.maxcdn.com.     211     IN      CNAME   emoji.twemoji.netdna-cdn.com.`
2. `drill emoji.twemoji.netdna-cdn.com` -> `;; ANSWER SECTION: `

### Browser

Chrome, Safari, Edge, Firefox, Opera

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment]
Already fixed in [9.0.4](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.4).

**Comment by aljazs-flare** [comment]
Sorry for not checking releases before opening the issue.
