### ISSUE TITLE
firefox - collapsed admonitions - not loading a plugin mkdocs-drawio-file

### ISSUE THREAD

**Issue by userdocs** [squidfunk/mkdocs-material#4866]
### Context

Plugin used - https://github.com/onixpro/mkdocs-drawio-file/

Tested in various chrome based and the Firefox browser.

There appears to be no console error but the div does not load the classes the same as the working examples.

Aside from that no idea why it's happening or where the issue is. I've opened an issue on both the theme and the plugin.

### Bug description

When using this plugin to load a draw.io flowchart file, like an image

```markdown
![Flowchart](../../includes/flowchart-custom-format-radarr.drawio)
```

It will not load the div properly inside a collapsed admonition.

You can see it live here - Bug Demo - https://userdocs.github.io/Guides/Flowcharts/

Works fine in chrome but fails to load the in collapsed admonition inf Firefox

### Related links

- [Bug reporting](https://squidfunk.github.io/mkdocs-material/bug-report/)
- https://squidfunk.github.io/mkdocs-material/reference/admonitions/
- https://github.com/onixpro/mkdocs-drawio-file/
- [Bug Demo](https://userdocs.github.io/Guides/Flowcharts/)

### Reproduction

Install and activate the plugin then 

### Steps to reproduce

```
??? abstract "example - [CLICK TO EXPAND]"

    ![Flowchart](../../includes/flowchart-custom-format-radarr.drawio)

------
```

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) or [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/bug-report/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Where's the zip file with the reproduction? You ticked that box:

<img width="388" alt="Bildschirmfoto 2023-01-16 um 00 41 05" src="https://user-images.githubusercontent.com/932156/212573872-1a8218af-7442-491a-be93-4592bc1c9fa4.png">

Note that the plugin mentioned is nothing that Material for MkDocs supports natively, so the best idea is to ask the maintainers, which you already did by double-posting. Thus, I'm closing this issue as not reproducible.

**Comment by userdocs** [comment]
Because added a GitHub workflow with a live example of the bug

https://userdocs.github.io/Guides/Flowcharts/

https://github.com/userdocs/Guides/actions/runs/3925558304/jobs/6710568120

but if you really need the zip, ill do that as well.

**Comment by squidfunk** [comment]
Debugging this with a GitHub Action would take 10 times as long than having a small runnable example. It's all just a question of economics. Shouldn't be too hard to put something together. If you find any obstacles in the bug reporting guide, please share them here. However, as I already noted, it's a third-party extension that we don't officially support.

**Comment by userdocs** [comment]
I added the zip file that can reproduce the issue. At this point I don't know if the admonitions are causing it or if the plugin is supposed to behave differently when loading in a collapsed plugin. The other issue is here

https://github.com/onixpro/mkdocs-drawio-file/issues/3

I don't understand why it will load in an expanded admonition but fail to load in a collapsed one, only in Firefox.

If you could at the very least, determine if the fault is with admonitions or the plugin, I'd appreciate it.

**Comment by squidfunk** [comment]
Thanks for providing the reproduction. It's definitely not related to Material for MkDocs, as it is also reproducible in the stock MkDocs theme. Thus, the issue must be fixed upstream – we can't do anything on our side:

<img width="1438" alt="Bildschirmfoto 2023-01-16 um 22 25 03" src="https://user-images.githubusercontent.com/932156/212767892-fea91c94-193b-441e-95cb-a4e9c67c13f2.png">
