### ISSUE TITLE
Option to hide breadcrumbs

### ISSUE THREAD

**Issue by StarfallProjects** [squidfunk/mkdocs-material#4875]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Breadcrumbs are awesome!

However, it would be good to be able to hide breadcrumbs on some pages. Ideally, two ways:

- Hide on a page-by-page basis, in the same way as hiding the toc or navigation. This uses `hide` in frontmatter.
- A setting in config to hide on all top level pages.

### Use Cases

Breadcrumbs are awesome, but can look a bit odd on certain pages. In particular, the homepage. But also top-level pages where there isn't a path (so the breadcrumb just shows the page you're currently on - which is info you already have)

**Comment by squidfunk** [comment]
Added in [`f8261624e`](https://github.com/squidfunk/mkdocs-material-insiders/commit/f8261624ec4e61472aef3df03fbf08ea0a3872dd). Additionally, breadcrumbs will now only be rendered when there's more than one level. Everything else really makes no sense. However, if the author wishes to change this behaviour, the [`path.html`](https://github.com/squidfunk/mkdocs-material-insiders/blob/f8261624ec4e61472aef3df03fbf08ea0a3872dd/src/partials/path.html#L23-L52) partial can always be overridden and adjusted – theme extension as usual 😊 Syntax is

``` yaml
hide:
  - path
```

Give it a spin, then I'll add it to the documentation.

**Comment by squidfunk** [comment]
Navigation added in b4c2ce4c1.

**Comment by squidfunk** [comment]
Released as part of [9.0.5-insiders-4.28.1](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.28.1).

**Comment by StarfallProjects** [comment]
Amazing thank you!
