### ISSUE TITLE
Can't enable line numbers at specific code blocks when line number option globally disalbled

### ISSUE THREAD

**Issue by coanor** [squidfunk/mkdocs-material#4907]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [ ] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

I'm globally disabled line numbers in my *mkdocs.yml*:

```yaml
markdown_extensions:
   pymdownx.highlight:
     anchor_linenums: true
     auto_title: false
     linenums: false  # <--- here
```

but some code sample need to show line number, so I checked the [docs](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-line-numbers), and add:

    ```py linenums="1"
    json(_, message, "message")
    json(_, thread_name, "thread")
    json(_, level, "status")
    json(_, @timestamp, "time")
    ```

and there is no number displayed. How to enable line number at specific positon when mkdocs.yml globally disabled?

### Use Cases

I think it's reasonable to enable line numbers when people set `linenums="xxx"`.

### Screenshots / Mockups

![20230123230128](https://user-images.githubusercontent.com/841781/214072737-10cd4533-79d7-4339-8e8f-1091d06e84e1.jpg)

**Comment by squidfunk** [comment]
You've used the feature request template to submit a bug report. Please use our [bug reporting template](https://github.com/squidfunk/mkdocs-material/issues/new?assignees=&labels=&template=bug.yml) and carefully read our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/). Also, make sure that this is an actual error in Material for MkDocs, and does not happen with other themes (e.g. `readthedocs`or `mkdocs`). [Closing as incomplete](https://squidfunk.github.io/mkdocs-material/bug-report/#incomplete-issues).
