### ISSUE TITLE
Footer label and title to previous page displayed on Nexus 6P

### ISSUE THREAD

**Issue by jonas** [squidfunk/mkdocs-material#491]
## Description

The label and page title for "previous" links in the footer are not displayed on Nexus 6P.

Upon inspecting the CSS it looks like this is the expected behaviour, however, given the large empty space. Maybe the "cut-off" could be tweaked.

### Expected behavior

The `Previous` label and page title should be visible.

### Actual behavior

![screenshot_20171013-093418](https://user-images.githubusercontent.com/8417/31548737-db04ae16-aff9-11e7-9c9a-15b009f44383.png)

### Steps to reproduce the bug

1. Open Chrome
2. Open Developer Tools
3. Toggle the device toolbar and select "Nexus 6P"
4. Go to any page with a "Previous" page
5. Scroll to the footer, where the "Previous" label and page title is not displayed.

### Package versions

The one used for building this project's site available on 2017-10-13.

### Project configuration

The one used for building this project's site available on 2017-10-13.

### System information

* OS: Android Oreo
* Browser: Chrome

**Comment by squidfunk** [comment]
That's correct and intended behavior. It's adapted from the Material Design guidelines template. There's not enough space to show the title of the previous page on a mobile, so only the next page is shown.

**Comment by jonas** [comment]
OK, will close this one.
