### ISSUE TITLE
Poor Mozilla Observatory results

### ISSUE THREAD

**Issue by javawithjiva** [squidfunk/mkdocs-material#4928]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

Running [Mozilla Observatory](https://observatory.mozilla.org/) on a generated sites gets an F score.  There are some basics that can be addressed to make sites somewhat secure.

### Use Cases

Better security

**Comment by squidfunk** [comment]
Thanks for reporting. However, I'm not sure what you mean, and what we can do about it. Please provide more information.

**Comment by squidfunk** [comment]
Closing as not actionable, please provide more information. Most of the things that are mentioned in Mozilla Obervatory are headers that must be set on the server. What Material for MkDocs produces is only static content – we don't do any hosting.

If you can provide clear actionables that we can improve in the theme, we can reopen the issue. However, creating an issue with two sentences which effectively says "bad security" and wishes for "better security" is not enough.
