### ISSUE TITLE
Add customization for how tabs are displayed on small screens

### ISSUE THREAD

**Issue by sixhobbits** [squidfunk/mkdocs-material#4938]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I want to suggest an idea and checked that ...

- [X] ... to my best knowledge, my idea wouldn't break something for other users
- [X] ... the documentation does not mention anything about my idea
- [X] ... there are no open or closed issues that are related to my idea

### Description

related to https://github.com/squidfunk/mkdocs-material/issues/2072, tabs are not intuitive on mobile devices. I'm not sure if this is a bug or working as intended, but I have a site with five tabs and everything looks great on Desktop.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/2641205/215315323-b2762db9-3315-418f-a6d1-dd179755eb8b.png">

On mobile though, clicking on the hamburger gives me an empty bar (as each tab only has one page)

<img width="811" alt="image" src="https://user-images.githubusercontent.com/2641205/215315355-ae5e3703-07c3-4d98-9a17-793f8efe663c.png">

I have to click on either the back arrow or Home to see the other tabs

<img width="626" alt="image" src="https://user-images.githubusercontent.com/2641205/215315368-f5a31104-b2fa-4ca8-8f01-5c4fc1c7776f.png">

I know it's maybe a slight counter pattern to use tabs with only one section but I prefer the top bar to the side bar, so it would be nice if I could customize the mobile menu to always display all tabs by default.

### Use Cases

This would allow people to use Mkdocs material for simpler documentation sites but still use tabs instead of a sidebar for navigation while not confusing mobile users.

### Screenshots / Mockups

included in description.

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm not sure what you mean exactly. Could you please [create a reproduction](https://squidfunk.github.io/mkdocs-material/bug-report/reproduction/)? In any case I need to know how you configured Material for MkDocs to understand what you're aiming for.

**Comment by sixhobbits** [comment]
Sorry for not being clear. The website is unofficialeskom.com and the source is github.com/sixhobbits/unofficialeskom.com. It's already very close to a minimum reproduction, but I've also created https://github.com/sixhobbits/mkdocs-tabs-repro which is even smaller. Unfortunately I could not get the `info` plugin to work as documented and even with the latest version (of insiders) I get 

```
mkdocs-repro-tabs$ mkdocs serve
INFO     -  Building documentation...
ERROR    -  Config value: 'plugins'. Error: The "info" plugin is not installed
Aborted with 1 Configuration Errors!
```

After adding it to mkdocs.yml.

There are two layers to the mobile menu which I'll call the "global" one (which shows all tabs) and the "local" one (which only shows the sections of the current tab.)

**GLOBAL**
![image](https://user-images.githubusercontent.com/2641205/215323333-9cecd915-d63c-4a67-8163-c3cf31d24ad9.png)

**LOCAL**
![image](https://user-images.githubusercontent.com/2641205/215323317-cc8819a0-30e8-452b-bb70-edc34af1d784.png)

The "local" one seems to usually be default, but sometimes I also seem to get the "global" one after refreshing the page a few times, or after navigating to it, closing the menu and then re-opening it, but I can't always predict which one I will get. I would like the "global" one to always be default when opening the menu from the hamburger icon on small screens.

I'm also attaching a gif below to show how clicking on the menu and refreshing the page sometimes activates the global one, but usually the local one.

https://share.cleanshot.com/37ZY8y9f

**Comment by squidfunk** [comment]
> Unfortunately I could not get the info plugin to work as documented and even with the latest version (of insiders) I get

You probably need to reinstall Insiders, to the plugin gets installed. Otherwise, if you can explain what you did when trying to make the info plugin work, I'm happy to look into it.

---

In your linked example, your [`mkdocs.yml`](https://github.com/sixhobbits/mkdocs-tabs-repro/blob/b311f3e5f5a26e0339bf5b7dc6a8fa6cd3810184/mkdocs.yml#L8-L12) specifies:

``` yaml
nav:
  - Home: 
    - index.md
  - About: 
    - about/index.md
```

This means that **Home** and **About** are sections, not pages. You need to flatten the hierarchy, if you don't want to have
nested sections in the top-level menu:

``` yaml
nav:
  - Home: index.md
  - About: about/index.md
```

This will allow you to keep the tabs on large screens while not creating a separate navigation pane for each entry. I've tested and verified this with your reproduction:

![screenshot-localhost-8000-1674994355963](https://user-images.githubusercontent.com/932156/215325353-b4e909e8-16b4-4c55-be73-9e32eede3416.png)

![screenshot-localhost-8000-1674994369449](https://user-images.githubusercontent.com/932156/215325351-682a2622-712b-40ae-ac3d-bef2ec5a57a4.png)

**Comment by squidfunk** [comment]
Additionally:

> The "local" one seems to usually be default, but sometimes I also seem to get the "global" one after refreshing the page a few times, or after navigating to it, closing the menu and then re-opening it, but I can't always predict which one I will get. I would like the "global" one to always be default when opening the menu from the hamburger icon on small screens.

One thing that's not intentional is that the top-level **Home** link is clickable. This should only be clickable if `navigation.sections` are enabled. This means that clicking on **Home** would show the nested section each time. We should definitely fix this. Could you create a new issue for this?

**Comment by squidfunk** [comment]
@sixhobbits I've investigated the problem I've mentioned in my last comment and I can't reproduce it. When `navigation.indexes` is switched off, sections are not hoisted. Thus, I cannot reproduce the behavior you mentioned where clicking on the link on the what you can "global" menu also links to the site.

**Comment by sixhobbits** [comment]
thank you so much! Sorry that was my misunderstanding about pages vs sections and your suggested fix works perfectly for my case. I added to our contribution and I see your new pricing structure is increased for organizations so I will try find budget to increase the monthly sponsorship as well.

I hosted the repro at https://preview.ritza.co/mkdocsmenurepro/ now and I can reproduce the inconsistency with Firefox and Chrome, but maybe we're not talking about the same thing. It's not a big deal, but still counter-intuitive for mobile users when using **Sections** (I don't have navigation.indexes in mkdocs.yml here).

```
site_name: Repro

theme:
  features:
    - navigation.tabs
  name: material

nav:
  - Home:
    - index.md
  - About:
    - about/index.md
```


1. Load https://preview.ritza.co/mkdocsmenurepro/ with full width. The user can easily see that there are two tabs -- Home and About

<img width="925" alt="image" src="https://user-images.githubusercontent.com/2641205/215332549-b1e510d8-84a3-4738-bd3a-13b25737ad2a.png">

  2. Make the screen narrower. Now if the user clicks on the menu, it isn't obvious that there are any other pages as the user has to navigate using the "back" arrow (or clicking anywhere in the grey area) to see the "about" tab. By default the user can only see pages within that section. It's unlikely that going "back" would make sense to the user as they have not explicitly navigated to this sub-menu in the first place.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/2641205/215332610-7511776a-f5af-43ec-b3e1-7a7a820be89c.png">

3. Even if we take this as working as intended, it's not consistent. If you click the "back" icon you see the full global menu showing "Home" and "About".
4. collapse the menu by clicking somewhere else on the page open the menu again. It remembers the state and still shows the global menu with both Home and About. 
5. Press "Cmd + R" to refresh the page. The state is **still** remember and we see the global menu showing Home and About. 
6. Press "Cmd + L" and then "Enter" to reload the page. Now the state is lost and we see only the Local menu with only "Home" again.


<img width="698" alt="image" src="https://user-images.githubusercontent.com/2641205/215332649-c2477c4e-5fd7-48b2-b1b5-1ca330746f35.png">

Not a big deal for me as your fix works for me, but probably still something that could be improved in terms of UX here for people using sections! Thanks again for the super prompt help!!

**Comment by squidfunk** [comment]
Just to let you know: I'll write up a proper response in a few days, give me some time.

**Comment by sixhobbits** [comment]
thank you! Not at all urgent and if it's meant to be like that then feel free to ignore - might still just be my misunderstanding of sections.

**Comment by squidfunk** [comment]
Okay, so here's another attempt: every navigation tab equals a navigation pane (the one with an arrow). So if we take Home for example, then you can see in both screenshots there is _Home_ (section) and _Home_ (page) rendered. The same goes for _About_. Now, if you use `navigation.indexes`, then the top-level section becomes clickable, so the page and section are combined into one.

Without `navigation.indexes`

<img width="402" alt="Bildschirmfoto 2023-02-08 um 17 56 04" src="https://user-images.githubusercontent.com/932156/217598985-8ba554c3-5158-42e6-8d57-5b63534f8edd.png">

With `navigation.indexes`

<img width="401" alt="Bildschirmfoto 2023-02-08 um 17 57 26" src="https://user-images.githubusercontent.com/932156/217599097-83935e13-24e2-40b4-9d90-6b254fb71f84.png">

There is only one little problem, and this is the one mentioned in your original report: when you use `navigation.indexes`, but only have a single page that you configure as a section – then, you will get the empty navigation pane when you navigate to _Home_:

<img width="401" alt="Bildschirmfoto 2023-02-08 um 17 57 39" src="https://user-images.githubusercontent.com/932156/217599549-9c22f19b-32d7-4e52-8996-82cf3aa8c752.png">

Unfortunately, this is not fixable with CSS only (the whole drawer uses only CSS for rendering, so it works perfectly without JavaScript), and I would consider it as an edge case. It is also easily fixable. As I wrote before, change:

``` yaml
nav:
  - Home:
    - index.md
```

... to:

``` yaml
nav:
  - Home: index.md
```

Now, when you want to add another page to _Home_, you can switch back to the section syntax:

``` yaml
nav:
  - Home:
    - index.md
    - license.md
```

Thus, it can easily be resolved by a configuration change. I hope that this clarifies the intended behavior and explains why it is not possible (or not feasible) to fix. One line of configuration needs to be changed, I think that's not too much ask 😊
