### ISSUE TITLE
Remove vertical scrollbar on short pages

### ISSUE THREAD

**Issue by AndreWin** [squidfunk/mkdocs-material#495]
Hello.

* [protflex.ru](http://protflex.ru)
* [license page for mkdocs-material theme](http://squidfunk.github.io/mkdocs-material/license/)

There are vertical scrollbar on the right when I see these pages.

I found that height(.md-container) + 1 px = height(.md-container .md-main) + 
height(.md-container .md-footer).

How can I fix this?

Best regards,
Andrey.

**Comment by AndreWin** [comment]
When I make height of .md-container less on 1 px, this hide scrollbar.

**Comment by AndreWin** [comment]
The only fix I found: `.md-container {height: 99.9%}`.

**Comment by squidfunk** [comment]
The pixel is added to induce margin collapse. It's a compromise, see:

https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/layout/_base.scss#L117-L120

I'm searching for another solution,  but haven't found one so far.

**Comment by AndreWin** [comment]
Thank you very much for this fix, @squidfunk!

**Comment by squidfunk** [comment]
Fixed in #501

**Comment by squidfunk** [comment]
Released with 1.10.4
