### ISSUE TITLE
`navigation.tabs.sticky` hide `footnotes` original link if footnote in table cell

### ISSUE THREAD

**Issue by reregaga** [squidfunk/mkdocs-material#4959]
### Bug description

When `footnotes` extension and feature `navigation.tabs.sticky` are active, clicking on the footnote (which is at the bottom of the page) scrolls the page so that the link you're looking for is hidden under the sticky bar. And you have to scroll a bit more manually.

https://user-images.githubusercontent.com/76629445/215570720-189d2e7f-723c-4f43-b81f-5467b8660cb4.mp4

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#footnotes
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#sticky-navigation-tabs

### Reproduction

```yml
theme:
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - footnotes
```

`index.md`:
```
---
hide:
  navigation
---

text<br>
text<br>
text<br>
text<br>
text<br>
text<br>
text<br>

| one | two |
|---|---|
| test | I am original link and I will be hidden by the sticky bar [^1] |

text<br>
text<br>
text<br>
... and more more lines for long page
text<br>
text<br>
text<br>

[^1]: i am footnote, click me
```

### Steps to reproduce

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10539257/example.zip)

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and providing the excellent reproduction. I've investigated the problem and yes, footnotes in tables behave oddly. I've added a footnote to the regular body, and the offset is correct. However, it's not correct in the table. I then tried to increase the `--md-scroll-margin` custom property, but to no avail. No matter how much you increase is, it doesn't work. Interestingly, if you use Firefox, there's no issue:

https://user-images.githubusercontent.com/932156/215587900-5150bccf-cd38-460f-9e2e-dccda37eb5a1.mp4

For this reason, we must consider this a browser bug, specifically in Webkit. I've searched the Internet, but I haven#t found anything related. If somebody has an idea how to fix it, happy to accept a PR, but I don't think it's easily fixable.
