### ISSUE TITLE
Inline formulas stopped to work

### ISSUE THREAD

**Issue by AndreWin** [squidfunk/mkdocs-material#496]
After updating:

![image](https://user-images.githubusercontent.com/7497378/31578726-e21615d2-b12f-11e7-8c9b-f4389a970f8a.png)

http://squidfunk.github.io/mkdocs-material/extensions/pymdown/#inline

Fix it, please!

Best regards,
Andrey.

**Comment by facelessuser** [comment]
Are you sure you aren't having local issues accessing the MathJax CDN?  The docs that you linked to look fine to me.

**Comment by AndreWin** [comment]
@facelessuser, I don't think so, because displayed formulas works fine.

**Comment by AndreWin** [comment]
![image](https://user-images.githubusercontent.com/7497378/31578786-d332ff48-b130-11e7-922e-d5a46f920ed0.png)

**Comment by facelessuser** [comment]
I'm not seeing the issue over here:

<img width="579" alt="2017-10-14 13_45_12-pymdown - material for mkdocs" src="https://user-images.githubusercontent.com/1055125/31578812-06d9df9c-b0e6-11e7-80bf-c0dfb2e4d395.png">

Can you inspect the page and see if it is giving a JS error?

**Comment by AndreWin** [comment]
Tab Console in Chrome developer tools is empty after updating.
Hm....
I asked my friends, they see formula, not text.
Shitf + F5 in chrome didn't help me...
It's so strange at all...

**Comment by facelessuser** [comment]
Delete cache?

**Comment by AndreWin** [comment]
When developer tools in open in Chrome, it's possible to clear cache and reload page.
But this didn't help me O_o

**Comment by AndreWin** [comment]
Firefox Nightly &mdash; all works fine.
Chrome issuse, sorry...

**Comment by facelessuser** [comment]
Weird, cause I'm using Chrome...

**Comment by AndreWin** [comment]
Sorry, I found problem...
I have [this extension](https://chrome.google.com/webstore/detail/tex-all-the-things/cbimabofgmfdkicghcadidpemeenbffn) installed in my chrome...
I uninstalled this extension and now all works fine!
Many thanks for your help!

**Comment by facelessuser** [comment]
Ha, yeah something like that just might interfere :slightly_smiling_face: .
