### ISSUE TITLE
Http request code block display error

### ISSUE THREAD

**Issue by mcxinyu** [squidfunk/mkdocs-material#4961]
### Context

For example, the following code block can be displayed normally in other markdown tools, but mkdocs displays errors.

Because its code block type description does not seem to support spaces.

code:
```
      ```http request
      GET http://localhost/api/intelli/devices
      Authorization: Bearer {{auth_bearer}}
      ```
```

displays:
```http request
GET http://localhost/api/intelli/devices
Authorization: Bearer {{auth_bearer}}
```

mkdocs:
![image](https://user-images.githubusercontent.com/9566116/215715952-be5136a8-5b03-456b-912c-35c989871db0.png)

### Browser

Chrome, Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting.

> I have attached a .zip file with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/reproduction/).

No you didn't. Make sure to [configure code blocks correctly](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/). If that doesn't help, please create a proper [bug report](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) with a [reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by mcxinyu** [comment]
@reregaga No, this is to make the markdown have the correct way to highlight the code.

Like the following two sections of code, one is marked with java and the other is not.

```java
System.out.println("hello");
```

```
System.out.println("hello");
```
