### ISSUE TITLE
Use image alt text as a caption

### ISSUE THREAD

**Issue by eschalkargans** [squidfunk/mkdocs-material#4974]
### Context

I was reading the documentation regarding images because I wanted to add captions to my images: [Image captions (documentation)](https://squidfunk.github.io/mkdocs-material/reference/images/#image-captions)

In order to add a caption to an image, one has to use HTML.

### Description

Use the Alt text of the image, already available in the markdown syntax, to generate automatically the caption. 

A feature flag could be set up so that users can choose whether or not they want the caption to be displayed. 

Here is a concrete example:

```markdown
![My awesome image](../assets/images/awesome.png)
```

The image would be rendered, wrapped with a `<figure>` and a `<figcaption>My awesome image </figcaption>` describing it.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Image captions (documentation)](https://squidfunk.github.io/mkdocs-material/reference/images/#image-captions)

### Use Cases

Use case from an author's perspective: It is a very common thing to want to name figures we use in a document

Use case from an user's perspective: An inserted image would be described once, without having to describe both an alt text and a caption (DRY)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. This functionality is already provided by [`markdown_captions`](https://github.com/Evidlo/markdown_captions).

**Comment by joapuiib** [comment]
I think this configuration could be mentioned in [Image Captions Section](https://squidfunk.github.io/mkdocs-material/reference/images/?h=captions#image-captions).

**Comment by squidfunk** [comment]
Thanks for the suggestion! We're only linking Markdown extensions for which we provide official support – we can't provide support for all of them. I hope that's understandable from a maintainer's perspective.

**Comment by joapuiib** [comment]
From [Image Captions Section](https://squidfunk.github.io/mkdocs-material/reference/images/?h=captions#image-captions) in the docs:

> Sadly, the Markdown syntax doesn't provide native support for image captions, but it's always possible to use the [Markdown in HTML](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#markdown-in-html) extension with literal figure and figcaption tags.

PyMdown Extensions has just launched [Caption extension](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/caption/), that allows to easily write captions.

Since this extension is supported [by default](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/), maybe the documentation could show a basic example on how to write captions:

```
![Image title](https://dummyimage.com/600x400/){ width="300" }
/// caption
Image caption
///
```

**Comment by squidfunk** [comment]
Sure, PR welcome. If you plan to go ahead, please also add the respective section in our [configuration guide](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/).
