### ISSUE TITLE
Content tabs: Buttons do not have an accessible name

### ISSUE THREAD

**Issue by m4g3s** [squidfunk/mkdocs-material#4977]
### Bug description

Content tab buttons do not have an accessible name

I found this error via Lighthouse.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/)

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10565763/example.zip)

### Steps to reproduce

1. create a content tab on any page
2. run Lighthouse
3. it will report that the buttons won't an accessible name

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/reproduction/).

**Comment by squidfunk** [comment]
Released as part of [9.0.10](https://github.com/squidfunk/mkdocs-material/releases/tag/9.0.10).
