### ISSUE TITLE
Enhancement — Customised Colour Palette for Top-Bar and Titles

### ISSUE THREAD

**Issue by rei-vilo** [squidfunk/mkdocs-material#499]
The documentation I'm working on has multiple sections, and I'd like to change the colour palette (top bar and titles `h1`, `h2`, `h3`) based on the section currently displayed. This is how the [official material design website](https://material.io/guidelines/) is organised, one colour per major section.

> <img width="400" alt="colours" src="https://user-images.githubusercontent.com/951776/31728125-c5e823f6-b42b-11e7-9a9e-8ffb2052bf66.png">

Here are the tricks I'm using so far.

* For the top bar:

```
<script>
  document.body.dataset.mdColorPrimary = "light-blue"; 
  document.body.dataset.mdColorAccent = "light-blue"; 
</script>
```
The colours should be compliant with [primary colours](http://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors) and [accent colors](http://squidfunk.github.io/mkdocs-material/getting-started/#accent-colors) names.

* For titles in the text, this other trick works fine expect for `h1`.

```
<style>
  h1, h2, h3 { color: #04A9F4; }
</style>
```
The colours follow the general CSS naming scheme.

Wouldn't be nice to have one same logic for the tool bar and the titles, including `h1`? 

Thank you!

**Comment by squidfunk** [comment]
If you scope your headline styles correctly to match the specificity of the styles already defined, it should work:

``` css
.md-typeset h1,
.md-typeset h2,
.md-typeset h3 {
  color: #04A9F4;
}
```

**Comment by rei-vilo** [comment]
Thanks!

**Comment by rei-vilo** [comment]
Well, the idea would be to have one same logic for the tool bar and the titles.

**Comment by squidfunk** [comment]
I'm sorry, the Material theme doesn't provide any possibility to style the titles, as they are intended to always have a black color. However, you can easily do it with `extra_css` or fork the theme and adjust the generated CSS. The documentation provides an example for changing the colors.

**Comment by rei-vilo** [comment]
With release 2.0.2, the trick for the toolbar colour no longer works.

```
<script>
  document.body.dataset.mdColorPrimary = "light-blue"; 
  document.body.dataset.mdColorAccent = "light-blue"; 
</script>
```

**Comment by squidfunk** [comment]
This actually works for me, or on the Material documentation when you type it into the console. The `extra_javascript` is included after all other scripts, so it should work as before. Please ensure that your JavaScript runs after the CSS is included. Also ensure that the file `application.palette.css` is included which is done when colors are set through the `mkdocs.yml` configuration, so ensure you set them:

``` yml
theme:
  palette:
    primary: indigo
    accent: indigo
```

**Comment by rei-vilo** [comment]
Thank you for your prompt answer. It works fine now. 

The issue was actually originated by the transfer of many parameters to the `theme` section of the `mkdocs.yml` file.

**Comment by squidfunk** [comment]
Yes, that was indeed the reason why I put out a major release.

**Comment by rei-vilo** [comment]
Defining specific parameters is much easier with the new release!

**Comment by hslima00** [comment]
Hello, where should I place this code:
```
.md-typeset h1,
.md-typeset h2,
.md-typeset h3 {
  color: #04A9F4;
}
```
For the h1, h2, h3 change its color?

@squidfunk

**Comment by squidfunk** [comment]
[Additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css). It's all explained in the [customization guide](https://squidfunk.github.io/mkdocs-material/customization/) 😊
