### ISSUE TITLE
Animations on link click

### ISSUE THREAD

**Issue by urosjarc** [squidfunk/mkdocs-material#50]
Is it possible ta add animation when user click on in docks links. For examle scrolling animation and for example fadein / fadeout. I`m web developer so I can help to achive this feature. Maybe to make this template in angular 2 as one page app?

**Comment by urosjarc** [comment]
https://w3c.github.io/web-animations/

**Comment by squidfunk** [comment]
What exactly do you want to do? Why Angular? I'm trying to do as minimal a footprint of JavaScript as possible and Angular would add loads and loads of bloat. In my opinion, Angular makes no sense on a static site.
