### ISSUE TITLE
Missing redirect to fix link breaking from issues bug report to reproduction page in docs

### ISSUE THREAD

**Issue by reregaga** [squidfunk/mkdocs-material#5002]
### Description

In the old bug reports, the link to the page in the documentation with instructions on how to create a minimal reproduction goes to a 404 page. I do not know if the link recently has been updated in issues too with https://github.com/squidfunk/mkdocs-material/commit/87fed7ec2ed1764686e10186943b05cf00316dde , so just in case I decided to write about it.

### Related links

- Old issue for example:
  https://github.com/squidfunk/mkdocs-material/issues/4960

- Old link from old issues (return 404):
  https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/reproduction/
  See:
  >I have attached a .zip file with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/reproduction/).

- New page (200):
  https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#reproduction

- It seems that the link to the new documentation has not yet been updated in the template to create issues:
  https://github.com/squidfunk/mkdocs-material/issues/new?assignees=&labels=&template=01-report-a-bug.yml
  See:
  >I have attached a .zip file with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/reproduction/).

### Proposed change

- [ ] Update the template for issues.
- [ ] It would be good to organize redirect from old link to new one, for those who can use old link while reading old issues.

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by katharinalisalin** [comment]
Thanks for reporting! Fixed in 83468bc6ed9378850c4569e9500a2b62bcb26991 and 2e689f062f6f01bd7e20e850e92ec7811f719dea.
