### ISSUE TITLE
previous and next footer options not showing up

### ISSUE THREAD

**Issue by hmntsharma** [squidfunk/mkdocs-material#5005]
### Context

The footer options to jump back and forth from one section to other is not showing up

### Bug description

The footer options to jump back and forth from one section to other is not showing up

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10676585/example.zip)

### Steps to reproduce

I have used the bare minimum mkdocs.yml file to reproduce the issue

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and providing the reproduction. [As I already mentioned on Gitter](https://gitter.im/squidfunk/mkdocs-material?at=63e1f51e4a6a184463198fb0), you're missing the [`navigation.footer`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#navigation) setting. Adding that setting to `mkdocs.yml` resolves the issue:

``` yaml
theme:
  features:
    - navigation.footer
````

<img width="1439" alt="Bildschirmfoto 2023-02-07 um 16 41 31" src="https://user-images.githubusercontent.com/932156/217291666-52e7caa9-1437-451e-8f2c-e1d68392a5ee.png">
