### ISSUE TITLE
Admonitions do not play nice with ordered lists

### ISSUE THREAD

**Issue by BrentRenteria** [squidfunk/mkdocs-material#5007]
### Context

I would like to add an admonition in the middle of an ordered list. I cannot seem to get this to work as it disrupts the ordered list numbering.

### Description

It would be useful to be able to add an admonition in the middle of an ordered list without disrupting the numbering of the list.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

1. Using your preferred tool, access SERVICES
1. run Mount.sh
!!! Important
       The directory where the files will need to be copied to is under /mnt/directoryl/ depending on the EC type
1. Change directories to the proper subdirectory. Example: ```cd /mnt/directory```

Adding the above admonition disrupts the following ordered list and restarts the numbering at 1. An admonition such as this for highlighting important information relevant to a given set of directions and is much more noticeable than a simple "Note:" This could prevent a misstep when performing mission critical procedures.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by facelessuser** [comment]
You may want to use this extension: https://python-markdown.github.io/extensions/sane_lists/
