### ISSUE TITLE
Text overflow for notes in Mermaid sequence diagrams in Firefox

### ISSUE THREAD

**Issue by bertrand-sb** [squidfunk/mkdocs-material#5010]
### Bug description

In Mermaid sequence diagrams, notes over a single participant can overflow but only in Firefox:

![mermaid_firefox](https://user-images.githubusercontent.com/115251417/217500973-63bb6e10-7175-4ebf-8826-f84d7bd688bd.png)

The same in Chrome:

![mermaid_chrome](https://user-images.githubusercontent.com/115251417/217501011-9e8b706d-222e-48af-98db-378111b16b76.png)

Note that Firefox is fine in Mermaid's live editor:

![mermaid_live_editor_firefox](https://user-images.githubusercontent.com/115251417/217501070-278dada1-ed39-447f-abd1-dc7f270a6d4c.png)

### Related links

- How to do sequence diagrams: https://squidfunk.github.io/mkdocs-material/reference/diagrams/
- Similar issue, reportedly fixed in the latest version of Material for MkDocs: https://github.com/squidfunk/mkdocs-material/issues/4429
- Similar issue in Mermaid, still open: https://github.com/mermaid-js/mermaid/issues/3229
  - Note that this issue if only for when a note is put over an arrow between two participants (e.g. `note over A,B: Note with overflow`). It is different from the issue being reported here.

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10684241/example.zip)

### Steps to reproduce

I have a single `docs/index.md` file with the following content:

````markdown
```mermaid
sequenceDiagram
    participant A
    participant B
    A->>B: hello

    note over A: Note with overflow but only in Firefox.
```
````

Configuration:

```yaml
site_name: My Docs

theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
```

Versions:

- mkdocs: 1.4.2
- mkdocs-material: 9.0.11

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and providing the excellent reproduction. I've investigated and the problem does not only happen for notes. There are still some text boxes running out of their containing rectangles (see second graph [taken from our docs](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#using-sequence-diagrams)), and after fiddling a little with it, I don't think that we can solve this problem on our side:

<img width="521" alt="Bildschirmfoto 2023-02-08 um 16 03 04" src="https://user-images.githubusercontent.com/932156/217567451-861e595d-ae73-435d-b808-02baa78950eb.png">

Luckily, there's a good upstream candidate that was merged 3 weeks ago and waits for a release. Let's see if that fixes the issue. Regardless, this must really be fixed upstream. Related:

- https://github.com/mermaid-js/mermaid/pull/3993
