### ISSUE TITLE
diff between versions

### ISSUE THREAD

**Issue by AdamJel** [squidfunk/mkdocs-material#5013]
### Context

There are many scenarios, where this would be useful. Consider two as examples:

1. you come back to some project after a while and you want to revisit the documentation and see, what exactly has changed
2. mkdocs is used for e.g. ISO-like norms or even state laws, which tent to be stable and exact in content and you need to see, what changed between versions.

### Description

Hi, I have a suggestion for a feature, which would show git-like diff between versions. The purpose would be to easily see, what has changed in the documentation between two chosen versions.

I don't have any specific idea about front-end design, but these would be approximate ACs
- from a list of versions, choose two versions
- show complete 
  - with git-like diff of changes inline the 
  - side by side comparison of 
- option to only show, what was removed AND/OR added in newer 
- option to show locations of all changed/removed/added 
- for selected section (#[#[#[...]]]) show history of changes

What are your opinions on this, please?

### Related links

x

### Use Cases

As described in 'context' - imagine usage for company norms or laws. It would be incredibly useful to have option to show what has changed between specific versions. 

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! An implementation would not need to be tied to Material for MkDocs. It's actually an excellent use case for a third-party plugin, which could render diffs as Markdown and feed them into a theme for rendering, e.g. Material for MkDocs. It's really beyond the scope of this project, however, so we're not planning to add this functionality natively as part of Material for MkDocs. If you or somebody else writes a plugin for that, please ping us!
