### ISSUE TITLE
Make the blur overlay of the Cookie option optional.

### ISSUE THREAD

**Issue by gledos** [squidfunk/mkdocs-material#5016]
### Description

I would like to add a judgment to this line in base.html, and then in mkdocs.yml I can freely choose whether to remove the blurring overlay or not.

https://github.com/squidfunk/mkdocs-material/blob/48e8b2be30fed05c76dda6bc20ff039ed3e8601f/material/base.html#L201

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)

### Use Cases

I want visitors to be able to read the text before making options for cookie settings when they enter the site.

And not have services like Internet Archive blocked.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Please use [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css):

``` css
.md-consent__overlay {
  display: none;
}
```

**Comment by alexvoss** [comment]
Leaving this comment here to provide some additional info for folks looking for an answer to this problem. IMHO it would be nice to have a configuration option to turn off the overlay but the CSS provided also does the job. The nice thing about the switch would be that it would be easy to add to the documentation, reducing the effort to find the solution, especially for folk who are not power users.

One problem with the overlay is that it gets applied to a privacy policy as well, which would mean that people cannot read it before consenting. The solution I have found is to add the CSS to the page via a template that is specific for the privacy page. The CSS can be added to the [`extrahead` block in the template](https://www.mkdocs.org/user-guide/customizing-your-theme/). Say, you create a custom template `nooverlay.html` (in the `overrides` directory):

```
{% extends "base.html" %} 
{% block extrahead %}
<style>
.md-consent__overlay {
    display: none;
}
</style>
{% endblock %}
```

Then add this to the privacy policy page in the header:

```
---
template: nooverlay.html
---
# Privacy Policy
```

Personally, I have a bit of an allergy to consent overlays, so turned it off globally in the end by adding the CSS @squidfunk  provided in the `extra.css`.

**Comment by alexvoss** [comment]
Hi Martin,

oh, I see. I mean any privacy policy you might have, not a specific one that is related to MkDocs Material.

Cheers,

Alex

---
Dr Alexander Voss
Freelance IT consultant and independent researcher
Rights-respecting software engineering
***@***.***
www.corealisation.com
