### ISSUE TITLE
Add edit_uri info to Code Action section

### ISSUE THREAD

**Issue by santaimpersonator** [squidfunk/mkdocs-material#5024]
### Description

The [code action](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#code-actions) defaults to using the `master` branch. With the [new default branch name for GitHub](https://github.com/github/renaming#new-repositories-use-main-as-the-default-branch-name) as `main`, new users might miss that they need to provide the [`edit_uri`](https://www.mkdocs.org/user-guide/configuration/#edit_uri) project information; as [discussed here](https://github.com/squidfunk/mkdocs-material/discussions/5012#discussioncomment-4916440).

### Related links

- [discussion](https://github.com/squidfunk/mkdocs-material/discussions/5012#discussioncomment-4916440)
- [code action](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#code-actions)
- [edit_uri](https://www.mkdocs.org/user-guide/configuration/#edit_uri)

### Proposed change

Could you add an admonition or annotation for the `edit_uri` in the [code action section](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#code-actions) of the documentation? Thanks!

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for suggesting. While we shouldn't duplicate each and every section from the [MkDocs documentation](https://www.mkdocs.org/), I understand that this might trip up many users, given that `main` is now the default.

Improved the documentation in 3b6c14295. [Code actions](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions) now explicitly mention `edit_uri`:

<img width="716" alt="Bildschirmfoto 2023-02-18 um 11 15 48" src="https://user-images.githubusercontent.com/932156/219854965-70215acd-32f1-4652-8150-a7732e91afda.png">
