### ISSUE TITLE
Feature suggestion: Subtitle in header

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#5049]
### Description

I suggest adding a `subtitle` option for the theme. The title area in the header is perfectly suited for this. Look at this beauty:

<img width="764" alt="Screenshot 2023-02-14 at 08 38 40" src="https://user-images.githubusercontent.com/2234833/218670810-f3149132-c30b-4df3-8682-d5dc6a0c0ab5.png">

There are a lot of cases for this, including:

* Adding your company's claim
* Indicating a non-production version (e.g., "My Documentation – Draft Version")
* Indicating a downloadable version (e.g., "My Documentation – Offline Version")
* Indicating a subset of a larger documentation site (e.g., "My Documentation – Product X API" vs. "My Documentation – Product Y API"

mkdocs.yml:

```yml
theme:
    name: material
    subtitle: Documentation that simply works
```

Of course, you could use environment variables to set build-specific subtitles:

```yml
theme:
    name: material
    subtitle: !ENV [LOCAL_BUILD, "Offline Version"]
```

If `subtitle` is omitted or empty, the title area should be rendered as before.

### Related links

-

### Use Cases

See description.

### Visuals

See description.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm not sure this is a good fit, as it clutters the header making it less readable. Additionally, when navigation tabs are hidden, it doesn't look well balanced, as spacing is now very narrow:

<img width="1440" alt="Bildschirmfoto 2023-02-14 um 11 52 50" src="https://user-images.githubusercontent.com/932156/218714769-1406027a-6f73-429a-a535-9a42a5435f4b.png">

Thus, I don't consider this a good idea for general addition, but it can surely be achieved with [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme).

**Comment by wilhelmer** [comment]
In your theme, you have already proven that a double-row element in the header can look good and well balanced – see the repository info on the right. You could use exactly the same settings for the title + subtitle:

<img width="1440" alt="218714769-1406027a-6f73-429a-a535-9a42a5435f4b" src="https://user-images.githubusercontent.com/2234833/218719277-392de612-4bbd-4af1-bbb2-a86f178b80df.png">

I think it looks decent. But tastes differ.

**Comment by squidfunk** [comment]
We would need to make the title much smaller then, which I don't consider a good idea for the main site title. Additionally, it would look weird when the page title switches. As said, please use theme extension for this.

**Comment by wilhelmer** [comment]
This is already implemented on my own site via theme customization, just like basically all of my feature suggestions for Material.

I just keep thinking "wouldn't that be great for the general public" and posting it here.

So it's really no problem at all for me if you decide against a general implementation. Just throwing stuff at your wall and seeing if anything sticks 😎 

Hope that's fine for you.

**Comment by squidfunk** [comment]
Absolutely, we're always happy to critically evaluate all feature suggestions, so feel free to throw us anything you think might be a good fit! Additionally, if you would like to share your implementation, you can do so here or as part of a discussion 😊
