### ISSUE TITLE
Add translations for ...

### ISSUE THREAD

**Issue by masterCredd** [squidfunk/mkdocs-material#5054]
### Translations

```Jinja
{% macro t(key) %}{{ {
  "language": "en",
  "direction": "ltr",
  "action.edit": "Edit this page",
  "action.skip": "Skip to content",
  "action.view": "View source of this page",
  "announce.dismiss": "Don't show this again",
  "clipboard.copy": "Copy to clipboard",
  "clipboard.copied": "Copied to clipboard",
  "consent.accept": "Accept",
  "consent.manage": "Manage settings",
  "consent.reject": "Reject",
  "footer": "Footer",
  "footer.next": "Next",
  "footer.previous": "Previous",
  "header": "Header",
  "meta.comments": "Comments",
  "meta.source": "Source",
  "nav": "Navigation",
  "search": "Search",
  "search.placeholder": "Search",
  "search.share": "Share",
  "search.reset": "Clear",
  "search.result.initializer": "Initializing search",
  "search.result.placeholder": "Type to start searching",
  "search.result.none": "No matching documents",
  "search.result.one": "1 matching document",
  "search.result.other": "# matching documents",
  "search.result.more.one": "1 more on this page",
  "search.result.more.other": "# more on this page",
  "search.result.term.missing": "Missing",
  "select.language": "Select language",
  "select.version": "Select version",
  "source": "Go to repository",
  "source.file.date.created": "Created",
  "source.file.date.updated": "Last update",
  "tabs": "Tabs",
  "toc": "Table of contents",
  "top": "Back to top"
}[key] }}{% endmacro %}
```

### Before submitting

- [X] I've checked the list of [available languages](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language) for existing translations.
- [X] I assure that the translations are accurate to my best knowledge.
- [x] __Optional__: I want to integrate this translation myself and create a pull request following the [contribution guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md).

**Comment by squidfunk** [comment]
It looks like this issue was opened accidentally, as it provides nothing but the template. Closing.

**Comment by masterCredd** [comment]
well, I'm learning how to use this type of model as well as how to increment several languages on the page.
can you give me a tip?

**Comment by squidfunk** [comment]
Just click on the "[Missing # translations](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language)" link – it will create a prefilled issue where you just need to translate all labels that have a symbol. Then submit the issue and we'll take it from there. For example, for Estonian, [it will look like this](https://github.com/squidfunk/mkdocs-material/issues/new?template=04-add-a-translation.yml&title=Update+Estonian+translations&translations=%7B%25+macro+t%28key%29+%25%7D%7B%7B+%7B%0A++%22language%22%3A+%22et%22%2C%0A++%22action.edit%22%3A+%22Muuda+seda+lehte%22%2C%0A++%22action.skip%22%3A+%22Keri+sisuni%22%2C%0A++%22action.view%22%3A+%22View+source+of+this+page+%E2%AC%85%EF%B8%8F%22%2C%0A++%22announce.dismiss%22%3A+%22Don%27t+show+this+again+%E2%AC%85%EF%B8%8F%22%2C%0A++%22blog.archive%22%3A+%22Archive+%E2%AC%85%EF%B8%8F%22%2C%0A++%22blog.categories%22%3A+%22Categories+%E2%AC%85%EF%B8%8F%22%2C%0A++%22blog.categories.in%22%3A+%22in+%E2%AC%85%EF%B8%8F%22%2C%0A++%22blog.continue%22%3A+%22Continue+reading+%E2%AC%85%EF%B8%8F%22%2C%0A++%22blog.draft%22%3A+%22Draft+%E2%AC%85%EF%B8%8F%22%2C%0A++%22blog.index%22%3A+%22Back+to+index+%E2%AC%85%EF%B8%8F%22%2C%0A++%22blog.meta%22%3A+%22Metadata+%E2%AC%85%EF%B8%8F%22%2C%0A++%22blog.references%22%3A+%22Related+links+%E2%AC%85%EF%B8%8F%22%2C%0A++%22clipboard.copy%22%3A+%22Kopeeri+l%C3%B5ikelauale%22%2C%0A++%22clipboard.copied%22%3A+%22Kopeeritud%22%2C%0A++%22consent.accept%22%3A+%22Accept+%E2%AC%85%EF%B8%8F%22%2C%0A++%22consent.manage%22%3A+%22Manage+settings+%E2%AC%85%EF%B8%8F%22%2C%0A++%22consent.reject%22%3A+%22Reject+%E2%AC%85%EF%B8%8F%22%2C%0A++%22footer%22%3A+%22Footer+%E2%AC%85%EF%B8%8F%22%2C%0A++%22footer.next%22%3A+%22J%C3%A4rgmine%22%2C%0A++%22footer.previous%22%3A+%22Eelmine%22%2C%0A++%22header%22%3A+%22Header+%E2%AC%85%EF%B8%8F%22%2C%0A++%22meta.comments%22%3A+%22Kommentaarid%22%2C%0A++%22meta.source%22%3A+%22L%C3%A4htekood%22%2C%0A++%22nav%22%3A+%22Navigation+%E2%AC%85%EF%B8%8F%22%2C%0A++%22readtime.one%22%3A+%221+min+read+%E2%AC%85%EF%B8%8F%22%2C%0A++%22readtime.other%22%3A+%22%23+min+read+%E2%AC%85%EF%B8%8F%22%2C%0A++%22rss.created%22%3A+%22RSS+feed+%E2%AC%85%EF%B8%8F%22%2C%0A++%22rss.updated%22%3A+%22RSS+feed+of+updated+content+%E2%AC%85%EF%B8%8F%22%2C%0A++%22search%22%3A+%22Search+%E2%AC%85%EF%B8%8F%22%2C%0A++%22search.placeholder%22%3A+%22Otsi%22%2C%0A++%22search.share%22%3A+%22Share+%E2%AC%85%EF%B8%8F%22%2C%0A++%22search.reset%22%3A+%22Clear+%E2%AC%85%EF%B8%8F%22%2C%0A++%22search.result.initializer%22%3A+%22Initializing+search+%E2%AC%85%EF%B8%8F%22%2C%0A++%22search.result.placeholder%22%3A+%22Otsimiseks+kirjuta+siia%22%2C%0A++%22search.result.none%22%3A+%22Otsingule+ei+leitud+%C3%BChtegi+vastet%22%2C%0A++%22search.result.one%22%3A+%22Leiti+%C3%BCks+tulemus%22%2C%0A++%22search.result.other%22%3A+%22Leiti+%23+tulemust%22%2C%0A++%22search.result.more.one%22%3A+%221+more+on+this+page+%E2%AC%85%EF%B8%8F%22%2C%0A++%22search.result.more.other%22%3A+%22%23+more+on+this+page+%E2%AC%85%EF%B8%8F%22%2C%0A++%22search.result.term.missing%22%3A+%22Missing+%E2%AC%85%EF%B8%8F%22%2C%0A++%22select.language%22%3A+%22Select+language+%E2%AC%85%EF%B8%8F%22%2C%0A++%22select.version%22%3A+%22Select+version+%E2%AC%85%EF%B8%8F%22%2C%0A++%22source%22%3A+%22Ava+repositooriumis%22%2C%0A++%22source.file.contributors%22%3A+%22Contributors+%E2%AC%85%EF%B8%8F%22%2C%0A++%22source.file.date.created%22%3A+%22Loodud%22%2C%0A++%22source.file.date.updated%22%3A+%22Viimane+uuendus%22%2C%0A++%22tabs%22%3A+%22Tabs+%E2%AC%85%EF%B8%8F%22%2C%0A++%22toc%22%3A+%22Sisukord%22%2C%0A++%22top%22%3A+%22Back+to+top+%E2%AC%85%EF%B8%8F%22%0A%7D%5Bkey%5D+%7D%7D%7B%25+endmacro+%25%7D).

Please only submit issue where you actually translated something. In this issue, there were no new translations.
