### ISSUE TITLE
TOC contains footnote numbers

### ISSUE THREAD

**Issue by chbndrhnns** [squidfunk/mkdocs-material#5057]
### Bug description

When adding a numbered footnote to a heading, the number appears in the generated table of content. I would want that number to be removed from the generated TOC.

### Related links

- [Footnotes](https://squidfunk.github.io/mkdocs-material/reference/footnotes/)

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10756453/example.zip)

### Steps to reproduce

1. `mkdocs serve`
2. See table of content in browser:

<img width="186" alt="Screenshot 2023-02-16 at 14 32 02" src="https://user-images.githubusercontent.com/7534547/219378548-6313383e-53f7-4a92-9201-56af2b8737d3.png">

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. The table of contents is generated by the [Table of Contents](https://python-markdown.github.io/extensions/toc/) extension, part of [Python Markdown](https://python-markdown.github.io/), so please raise an issue upstream. As a mitigation, you can use a [custom label](https://python-markdown.github.io/extensions/toc/#custom-labels):

``` markdown
## Project Layout [^1] { data-toc-label="Project layout" }
```

**Comment by chbndrhnns** [comment]
Thanks, it seems an issue exists till 2018 already but it's untouched so far: https://github.com/Python-Markdown/markdown/issues/660
