### ISSUE TITLE
Built-in  `privacy` plugin is conflicting with auto `rel=me` for Mastodon social icon

### ISSUE THREAD

**Issue by Guts** [squidfunk/mkdocs-material#5079]
### Bug description

Built-in privacy rewriting and mastodon social icon automatic rel=me set to hyperlink are conflicting.

### Related links

- [This option specifies whether the plugin should automatically add rel="noopener"](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/?h=privacy#+privacy.external_links_noopener)
- [fontawesome/brands/mastodon automatically adds rel=me](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=masto#+social.icon)
- https://github.com/squidfunk/mkdocs-material/discussions/4752#discussioncomment-4869780

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10796136/example.zip)

### Steps to reproduce

1. Add mastodon social icon to extra section
2. Build the site: the mastodon icon hyperlink got the `rel="noopener me"` attribute
3. Add privacy plugin to mkdocs.yml
4. Build the site: the mastodon icon hyperlink has only `rel="noopener"` attribute vbut not the `me`

### Browser

Chrome, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and for the excellent reproduction! Fixed in [`d3cf67d28`](https://github.com/squidfunk/mkdocs-material-insiders/commit/d3cf67d2843635eaf2476561c991d9d72374b0a9).

**Comment by squidfunk** [comment]
Released as part of [9.0.14+insiders-4.32.1](https://github.com/squidfunk/mkdocs-material-insiders/releases/tag/9.0.14-insiders-4.32.1).
