### ISSUE TITLE
Nested lists use the same solid circle symbol

### ISSUE THREAD

**Issue by smalers** [squidfunk/mkdocs-material#508]
## Description

Nested unordered lists using Markdown asterisk, (tab plus), (tab tab dash) result in a solid circle being used for the symbol at every indent level.  Cannot tell from documentation if this is by design so report as an issue.

### Expected behavior

If the mkdocs theme is used, nested unordered lists use solid circle, hollow circle, and filled square.  The nested lists in the Material theme should default similarly to appropriate symbols in Material without having to do custom configuration.  Otherwise, out of the box Material behavior has flawed rendering of unordered lists.

### Actual behavior

Nested lists using Markdown asterisk, (tab plus), (tab tab dash) result in a solid circle being used for the symbol at every level.  This is also illustrated in the [Speciman Page](http://squidfunk.github.io/mkdocs-material/specimen/).

### Steps to reproduce the bug

Use a MkDocs markdown page with content similar to the following, where a single tab is inserted before the + and two tabs before the - (or use 4 spaces rather than tabs):

```
* Test top level
        + Test second level
        + Test second level
                - Test third level
                - Test third level
```

### Package versions

* Python: `python --version`  = 2.7.9 (on Debian Jessie Linux)
* MkDocs: `mkdocs --version` = 0.16.3 (same behavior on 0.16.1)
* Material: `pip show mkdocs-material | grep -E ^Version` = 1.10.3

### Project configuration

```
# Abbreviated...
# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: xxx
pages:
- 'Home':
  - 'Overview': 'index.md'
  - 'Release Notes': 'release-notes.md'
- 'System':
  - 'Overview': 'system/overview.md'
#theme: readthedocs
#theme: mkdocs
# Install "cosmo" theme with: sudo pip install mkdocs-bootswatch
# http://mkdocs.github.io/mkdocs-bootswatch/
#theme: cosmo
# Install "material" theme with: sudo pip install mkdocs-material
# https://github.com/squidfunk/mkdocs-material
theme: material
site_description:  xxx / XXX 
site_author:  xxx
site_favicon:  xxx.png
copyright: xxx
#extra_css:
#- css/extra.css
# Defaults to all JavaScript in the docs folder
# extra_javascript:
```

### System information

* OS = Debian Jessie Linux 
* Browser: chromium 57.0.2987 run on the above OS

**Comment by squidfunk** [comment]
Well, this is really a matter of taste. It's actually intended, as the nested list should be distinct enough by indentation. You can easily use another symbol by overriding the CSS.

**Comment by smalers** [comment]
Yeah I get that.  However, if you use a formatting/styling tool like Markdown and the intent is that default behavior works out of the box in order to keep simple and encourage adoption, it seems that implementing different default symbols at each indentation makes sense, similar to other "levels", like hash-headings that by default use different font/size.   People that use MS Word or other software expect that an indent not only means a spatial indentation but a change in symbol.  If all I wanted to do was indent, I would use another formatting option.   In comparison, when I use PowerPoint and have not set up styles or defaults properly, I get the same symbol at each indentation and the first thing I have to do is fix that.

I will look at a CSS override.  As far as I know, this is the only issue preventing my team from doing a large-scale migration of MkDocs projects to the Material theme, which solves other problems that we have had with other themes.  For that I am grateful and appreciate the work of the Material authors.

Also, below is a test to see how GitHub issues handles nested unordered lists, which is a good default:

```
* Test level 1
    + Test level 2
        - Test level 3
```

* Test level 1
    + Test level 2
        - Test level 3

**Comment by squidfunk** [comment]
In Markdown it doesn't matter what kind of list delimiter you use - the generated HTML is just `ul` and `li`. This may be irritating, but it makes no difference. However, patching the list styles should be less than 5 lines of CSS.

**Comment by smalers** [comment]
OK, I did the extra CSS customization with the following and it works for me.  Pardon the verbosity of comments but the work I do is often to encourage laymen to adopt technologies.  **Please close the discussion if you'd like.**  The [published website is here](http://learn.openwaterfoundation.org/owf-learn-mkdocs/).

```
/* Custom styles to override MkDocs defaults and enhance theme */

/* Unordered list <ul> symbols:
 * - level 2 is filled circle
 * - level 3 is filled square
 * - ul default is filled disc (bullet)
 */
ul ul {
        list-style-type:  circle;
}

ul ul ul {
        list-style-type:  square;
}
```

**Comment by squidfunk** [comment]
All good! Also thanks for posting it here, so we can point people here in the future.

**Comment by smalers** [comment]
Actually, the following seems to work more reliably.  The "article" indicates to use only the main page body (not the navigation list on the right).  Otherwise, the navigation list on the right can show odd bullet rendering when no bullets are what is in the default behavior.

```
/* Custom styles to override MkDocs defaults and enhance theme */

/* Unordered list <ul> symbols:
 * - level 2 is hollow circle
 * - level 3 is filled square
 * - ul default is filled disc (bullet)
 */
article ul ul {
        list-style-type:  circle !important;
}

article ul ul ul {
        list-style-type:  square !important;
}
```
