### ISSUE TITLE
Extend the Data Tables page to include info on how to load data from static file

### ISSUE THREAD

**Issue by chrimaho** [squidfunk/mkdocs-material#5080]
### Description

Can we please extend the [Data Tables][data-tables] page to include information on how to load data from a static file? Such as a CSV or Excel file?

This will not require extending the `mkdocs-material` package to include this funtionality, as the [`mkdocs-table-reader-plugin`][table-reader-plugin] currently fulfils this need.

This request is just to extend the docs page to show how this may be achieved. In the same way that the [Images][images] page shows how to use the [glightbox][glightbox] plugin for extended functionality.

[table-reader-plugin]: https://timvink.github.io/mkdocs-table-reader-plugin/
[data-tables]: https://squidfunk.github.io/mkdocs-material/reference/data-tables/
[images]: https://squidfunk.github.io/mkdocs-material/reference/images/
[glightbox]: https://github.com/blueswen/mkdocs-glightbox

### Related links

- Docs page to be extended: [Data Tables](https://squidfunk.github.io/mkdocs-material/reference/data-tables/)
- Discussion page for background context: https://github.com/squidfunk/mkdocs-material/discussions/3315#discussioncomment-5066920
- Docs page for the suggested plugin: [mkdocs-table-reader-plugin](https://timvink.github.io/mkdocs-table-reader-plugin/)

### Proposed change

 I've drafted the change. I will submit a Pull Request for you to review.

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Resolved by #5081.
