### ISSUE TITLE
'Section index pages' selects 'README.md' as well as 'index.md'. But it is not documented

### ISSUE THREAD

**Issue by ndy2** [squidfunk/mkdocs-material#5086]
### Description

In the documentation of [Section index pages](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages) feature, it says that `index.md` in respective folder would selected as a top level document for the folder. But I found that `README.md` also selected as a top level document.

with the feature `navigation.indexes` enabled
```
.folder
├── 1.md
├── 2.md
└── README.md
```

results in rendered navigation
```
.folder -> README.md
├── 1.md
└── 2.md
```

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
- It is not a material's link but... https://www.mkdocs.org/user-guide/writing-your-docs/#index-pages

### Proposed change

Add 'README.md' to [Section index pages](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages) documentation.

I found that if both `README.md` and `index.md` supplied the `README.md` file get disappeared as documented in above `mkdocs` link. This is not specified to this feature, but I think it can be documented here.

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting! Added in f3ae326e1.
