### ISSUE TITLE
Fenced blocks copy icon, edit icon on right in mkdocs-material 9

### ISSUE THREAD

**Issue by rfay** [squidfunk/mkdocs-material#5092]
### Context

Updated [DDEV docs latest](https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/) to mkdocs-material 9 and 

* we lost the good old copy icon on fenced blocks that we had in mkdocs-material 8
<img width="781" alt="DDEV_Installation_-_DDEV_Docs" src="https://user-images.githubusercontent.com/112444/221224728-aaee4587-c920-44c9-9d2d-dac8171b8eb2.png">

* We lost the "pencil" edit in the upper right that is so useful to get community contributions to docs. 

I imagine that these now have to be turned on somehow and were default before?

PR:
* https://github.com/drud/ddev/pull/4670

mkdocs.yml: https://github.com/drud/ddev/blob/master/mkdocs.yml

### Bug description

Thanks so much for your help

### Related links

I know it may be a stupid question.

### Reproduction

All provided above, demonstrated in old https://ddev.readthedocs.io/en/stable/users/install/ddev-installation/ and new https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/

### Steps to reproduce

All provided above

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Those settings are now opt-in. [Please read our upgrade guide](https://squidfunk.github.io/mkdocs-material/upgrade/#upgrading-from-8x-to-9x) when upgrading major versions:

``` yaml
theme:
  features:
    - content.action.edit
    - content.code.copy
```

**Comment by rfay** [comment]
Thanks so much. Didn't know about the upgrade guide, and there's so much to know of course.

**Comment by rfay** [comment]
I was surprised to see such a significant change in the edit icon; it's not very recognizable to me, but my vision is poor. I think there's a pencil in there somewhere, and after studying it carefully it looks like it's a pencil and a page. Searching the docs didn't immediately help me find more info about `content.action.edit` or the icon. Is there an easy way to get back to the old familiar pencil icon?

<img width="543" alt="Get_Started_with_DDEV_-_DDEV_Docs" src="https://user-images.githubusercontent.com/112444/221364739-41211db9-cea3-4fba-acfd-a7218ebe7e59.png">

**Comment by squidfunk** [comment]
Yes. [Again, please read our documentation...](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions). 

<img width="738" alt="Bildschirmfoto 2023-02-25 um 17 23 02" src="https://user-images.githubusercontent.com/932156/221367914-22bda897-c0b8-4570-bb2e-21e23d872919.png">

**Comment by rfay** [comment]
Thanks, I know what it is to be the "personal router" for the docs; I'm that all the time for DDEV. I did search for `content.action.edit` and it only gave me https://squidfunk.github.io/mkdocs-material/upgrade/?h=content+action+edit#contentaction - And I did search for icon, and got https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/?h=icon (and a few other things). This one is hard to search for. So many things are hard in comprehensive docs like this (thanks for the comprehensive docs!) 

And thanks for the explicit fix. That does the job. I do think the simple pencil a way better default....

**Comment by squidfunk** [comment]
> And thanks for the explicit fix. That does the job. I do think the simple pencil a way better default....

Glad you solved it. Always a matter of taste. If you change one thing on this project, there are dozens of users telling you that they you are wrong, and it was better as it was before. Thus, changing things, you can only ever make it worse. But at the same time, you need to push this project forward. That's why everything is configurable and hackable.

**Comment by rfay** [comment]
Totally understood, and I deal with the same class of problems every day :)
