### ISSUE TITLE
Steps to creating a similar homepage

### ISSUE THREAD

**Issue by gllrmzndm** [squidfunk/mkdocs-material#5107]
### Description

Steps to creating a similar homepage.
Steps are missing.

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
-

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Please stop opening issues without any relevant information. The thing you're asking has been discussed in several other issues.
