### ISSUE TITLE
Google Analytics doesn't work.

### ISSUE THREAD

**Issue by gllrmzndm** [squidfunk/mkdocs-material#5108]
### Context

No information in Google Analytics.
Straight-up doesn't work. easiest way to find is making your own projects.
No special adjustments had been made for my own website.

### Bug description

squidfunk.github.io/mkdocs-material/

https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/

### Reproduction

https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/

### Steps to reproduce

Start your own project
Insert your tag

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Please read our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) before reporting a bug. Unfortunately, we're no wizards, so we can't help you if you just throw us "it doesn't work".

**Comment by glasgowm148** [comment]
The config 

```
extra:
  generator: false
 ```

 was the perpetrator for me.
