### ISSUE TITLE
Problems with MkDocs 0.17

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#513]
See https://github.com/mkdocs/mkdocs/issues/1316

The Docker image has been pinned to 0.16.3 until this issue is resolved.

**Comment by squidfunk** [comment]
Material doesn't work properly with MkDocs 0.17. There are some issues to be resolved which is really bad for a minor version release of MkDocs, but it is the way it is. The new plugin system breaks the search functionality.

**Comment by twardoch** [comment]
https://github.com/mkdocs/mkdocs/releases/tag/0.17.1 is out

**Comment by squidfunk** [comment]
Fixed in #547, 2.0.0 will be released shortly.
