### ISSUE TITLE
Support Markdown in the `copyright` string

### ISSUE THREAD

**Issue by Janiczek** [squidfunk/mkdocs-material#5134]
### Context

I wanted to have a link to my profile in the `copyright` section of the footer.

This would allow me to do:
```diff
-copyright: "Made with 🧡 by Martin Janiczek"
+copyright: "Made with 🧡 by [Martin Janiczek](https://github.com/janiczek)"
```

Currently that doesn't do much (see the screenshot below)

### Description

I propose for the `copyright` field in `mkdocs.yml` to support Markdown.

### Related links

- https://github.com/squidfunk/mkdocs-material/discussions/4969
- https://github.com/squidfunk/mkdocs-material/discussions/4893

I'm not completely sure overriding the HTML templates is the way to go in this case. Or at least my solution seems more elegant / simpler to me :)

### Use Cases

Site authors will be able to format their copyright strings.

### Visuals

Currently Markdown is not supported:
![Screenshot 2023-03-03 at 11 11 54](https://user-images.githubusercontent.com/149425/222694201-f4b37b86-3eaf-493c-9eca-c72fd38b39d1.png)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Not possible, because we're too late in the pipeline, i.e., the contents of `copyright` are never ran through the Markdown parser by MkDocs. However, using HTML is perfectly fine:

``` yaml
copyright: Made with 🧡 by <a href="https://github.com/janiczek">Martin Janiczek</a>
```

Many users are already doing this to add additional links to the copyright.

**Comment by Janiczek** [comment]
Ah, thank you! I didn't think to try HTML - thanks for directing me to that.
