### ISSUE TITLE
Material theme does not render on GitHub Pages

### ISSUE THREAD

**Issue by markeyser** [squidfunk/mkdocs-material#5141]
### Context

At my company, we rely on MkDocs and the Material theme for our Python projects. 

### Bug description

We've had no issues using these tools across all our repositories, except for one. When we run the `mkdocs serve` command for this particular repository, everything renders as expected. However, when we use the `mkdocs gh-deploy` command, the Material theme fails to render properly, resulting in an unexpected appearance for the website. Please refer to the picture below for an example.

### Related links

- run `mkdocs gh-deploy` 
-

### Reproduction

[2023-03-03 19_17_07-Window.zip](https://github.com/squidfunk/mkdocs-material/files/10887042/2023-03-03.19_17_07-Window.zip)

### Steps to reproduce

`mkdocs gh-deploy` 

### Browser

Chrome, Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
This issue contains no actionable information for us – we have no idea how you configured your installation and the zip you attached only contains a screenshot. When reporting bugs, it is mandatory to stick to the [bug reporting process](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).

Closing, as there's nothing we can do here. Note that this is very likely a configuration issue, as thousands of users (including us) are successfully deploying their documentation to GitHub Pages, [as can be seen on or own docs](https://squidfunk.github.io/mkdocs-material/).
