### ISSUE TITLE
Scrolling to the bottom of a page hides the menu bar with a blank footer section

### ISSUE THREAD

**Issue by murundb** [squidfunk/mkdocs-material#5146]
### Context

I'm using Material for Mkdocs for taking personal notes. I am writing large amount of equations using MathJax and there seems to be a problem when the page length starts getting longer.

### Bug description

When a page contains large number of equations with MathJax, scrolling to the bottom of the page hides the menu bar and adds a blank section below the page footer. Example screenshot:

![Screenshot 2023-03-05 at 5 32 27 PM](https://user-images.githubusercontent.com/63768001/223000018-9b789d89-3e4d-47a6-93fb-654b784311ae.png)

The source code for this page is in: https://github.com/murundb/murundb.github.io/blob/main/docs/optimization/geometry.md

### Related links
- No related issues were found

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10893650/example.zip)

### Steps to reproduce

1. Navigate to Optimization/Geometry page. 
2. Scroll down to the bottom of the page.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is a problem that should be reported to MathJax. The overflow is triggered by one of the last `arithmatex` blocks that seems to create a large absolutely positioned element which expands the entire page:

<img width="1435" alt="Bildschirm­foto 2023-03-06 um 07 30 54" src="https://user-images.githubusercontent.com/932156/223035765-0df2834c-1eab-417b-a3fa-989a2502a41c.png">

My guess is that this isn't particularly related to Material for MkDocs – it will be the same in other themes. As a workaround, you can just hide the element, but I have no idea what the implications are:

``` css
.md-typeset .arithmatex mjx-assistive-mml {
  display: none !important;
}
```

Please take this upstream to MathJax.
