### ISSUE TITLE
Breadcrumbs not rendering properly on very long navigation paths

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#5156]
### Bug description

When using the `navigation.path` feature on pages with a very long, nested path, the breadcrumbs aren't rendered properly:

<img width="1756" alt="Screenshot 2023-03-06 at 13 46 56" src="https://user-images.githubusercontent.com/2234833/223114705-9c6da026-e9dd-461a-a74d-3dbcbf4fd273.png">

Possible solutions:

1. Optimize the CSS with `white-space: nowrap`, `overflow: hidden` etc.
2. Limit the path length displayed in breadcrumbs so overflow is much less likely to occur, either via an option or with a hard limit.

### Related links

-

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10898322/example.zip)

### Steps to reproduce

See example.zip

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. So, there's not much else that overflow scrolling that we can do here, since the space is very narrow on mobile. Overflow hidden is a bad idea though, as it's not unlikely that you're cutting mid-word.

We need to fix the wrapping, though.

**Comment by wilhelmer** [comment]
Then there's the second solution, which could look like this:

```yml
features:
  - navigation.path:
      max_length: 3
```

This would mean all paths below level 3 would be cut off, so all breadcrumbs on pages in `Section > Subsection > Subsubsection > Subsubsubsection` would be rendered as `Section > Subsection > Subsubsection`.

**Comment by squidfunk** [comment]
This still doesn't solve the problem on narrow screens. There might be _one_ very very long breadcrumb that already overflows, so there's no guarantee that limiting to three breadcrumbs is sufficient. I will provide some CSS here to tune behavior, but it doesn't make sense to provide configuration options for this feature.

**Comment by wilhelmer** [comment]
Yes, that's why I wrote "so overflow is **much less likely** to occur". It won't help in all cases, but it will help in many real-world use cases.

Right now, there's no upper limit at all, so if you have, say, an auto-generated documentation with 20 levels, the `navigation.path` feature will be completely unusable. Of course, you could say that in these cases, your documentation simply sucks and the path feature is the least of your concerns. I don't know. Just thinking out loud here.

Regarding CSS: Maybe add ellipsis to the last visible breadcrumb instead of horizontal scrolling?

**Comment by squidfunk** [comment]
The example you provided only includes the `site` output and doesn't include anything we can run to inspect, debug and fix the issue. Please provide a [self-contained reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) that we can run by using the built-in `info` plugin.

**Comment by squidfunk** [comment]
I'm also not able to reproduce it myself – I don't see the wrapping behavior on our docs:

<img width="755" alt="Bildschirm­foto 2023-03-06 um 20 36 20" src="https://user-images.githubusercontent.com/932156/223212715-c8d177d3-4710-4151-95ca-59649333f129.png">

**Comment by wilhelmer** [comment]
Sorry, forgot to include the sources in the ZIP. Unfortunately, I can't use the `info` plugin, different story.

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10902358/example.zip)

Also, again sorry, I didn't update to the latest version before reporting the bug. Somehow, the latest version (9.1.1-insiders-4.32.2) seems to fix the wrapping behavior. Still, I think rendering is not ideal with the horizontal scroll bar:

<img width="1657" alt="Screenshot 2023-03-06 at 21 06 29" src="https://user-images.githubusercontent.com/2234833/223219126-ab4833ad-3399-4753-8870-06980be16166.png">

**Comment by squidfunk** [comment]
The thing is, that we could do multiple things, all of those heavily opinionated and all of them solvable with CSS. Here are two ideas that you and future users can implement via [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) – as always, YMMV:

### Limit number of navigation items

This solves https://github.com/squidfunk/mkdocs-material/issues/5156#issuecomment-1456303169:

``` css
.md-path__item:nth-child(n+3)  { 
  display: none;
}
```

### Break items onto multiple lines

``` css
.md-path__list  {
  flex-direction: column;
  align-items: initial;
}
```

This could also be scoped to mobile breakpoints. As a default implementation, we will keep the overflow scrolling behavior for now, since it should cater to most installations. Thus, please customize appearance with [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css).

**Comment by wilhelmer** [comment]
Your "Limit number of navigation items" solution is perfect, thanks. I'll take that.

(For an equivalent of `max_length: 3`, it has to be `nth-child(n+4)`. I don't want to nitpick, just for future reference.)

**Comment by squidfunk** [comment]
Thanks! I corrected the example 😉
