### ISSUE TITLE
Insiders only: abbreviations missing bottom border

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#5159]
### Bug description

The insiders stylesheet is different from the public stylesheet:

https://github.com/squidfunk/mkdocs-material-insiders/blob/master/src/assets/stylesheets/main/_typeset.scss#L293-L297

As opposed to:

https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/main/_typeset.scss#L289-L312

It's missing the bottom-border attribute among other things making abbreviations indistinguishable on the site.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

You can see this behavior on your own site: https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations 

### Steps to reproduce

1. Use abbreviations on insiders install

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting! Likely a regression and definitely a bug.
