### ISSUE TITLE
Navigation: typeset plugin not rendering tooltips for abbreviations

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#5165]
### Bug description

Pretty minor thing, when the typeset plugin is enabled abbreviations are rendered in the TOC, but they don't use the improved tooltips that abbreviations in the content use:

<img width="220" alt="Screenshot 2023-03-07 at 10 40 09@2x" src="https://user-images.githubusercontent.com/3637842/223488985-c1a0b789-2016-4dab-a218-d92ec0e664f7.png">

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/reference/tooltips/?h=tool
- https://squidfunk.github.io/mkdocs-material/reference/?h=type#built-in-typeset-plugin

### Reproduction

[Archive.zip](https://github.com/squidfunk/mkdocs-material/files/10911813/Archive.zip)

### Steps to reproduce

1. Enable improved tooltips, typeset plugin, and abbreviations
2. Create sitewide glossary
3. Use abbreviation from glossary in page heading

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. As always, we're more than happy to look into it. [However, please use the built-in `info` plugin in the future](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file). We're missing essential version and runtime information from your report. Thank you!

**Comment by jonaharagon** [comment]
Oh, that is quite handy.

[example.zip](https://github.com/squidfunk/mkdocs-material/files/10951718/example.zip)

**Comment by squidfunk** [comment]
Fixed in [`e02ab72`](https://github.com/squidfunk/mkdocs-material-insiders/commit/e02ab721aa9fafe7785f9ce2f53fe9675d57d351)! I'm very sorry it took so long.

**Comment by squidfunk** [comment]
Released as part of [9.5.19+insiders-4.53.8](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.53.8).
