### ISSUE TITLE
Dep Update Mermaid 10.3

### ISSUE THREAD

**Issue by strausmann** [squidfunk/mkdocs-material#5193]
### Description

MkDocs Material use Mermaid 9.3 but 10.x is the latest release. Update required.

### Related links

- [Mermaid Release v10.0.1](https://github.com/mermaid-js/mermaid/releases/tag/v10.0.1)

### Use Cases

The update has just been released recently and will certainly be of help to other users.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Mermaid.js 10+ is ESM-only, [which is currently not supported by MkDocs](https://github.com/mkdocs/mkdocs/issues/2850). However, since we automatically include it, we are actually able to upgrade. If somebody wants to provide a PR, feel free!

We need to make sure all diagram types still work.

**Comment by strausmann** [comment]
What is ESM ?

**Comment by squidfunk** [comment]
Okay, so I've investigated this change request, and I don't think we're ready yet to make the switch. The thing is that Material for MkDocs can't go full-ESM yet, as we need to support [older browsers](https://squidfunk.github.io/mkdocs-material/browser-support/) that [don't have support for ESM](https://caniuse.com/es6-module-dynamic-import). We would be removing support for those browsers.  Now, if you want v10, you can still achieve the same thing via [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme), but for now we can't make this switch. This is very likely going to change in the future, but currently not planned. Related:

- https://github.com/mkdocs/mkdocs/issues/2850

**Comment by SAMZONG** [comment]
temporary:

follow this document add custom theme override: `main.html`, apply the content.

```html
{% block scripts %}
  <script type="module">
      import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10.2.0/+esm'
  </script>
{% endblock %}
```

**Comment by squidfunk** [comment]
This is being worked on over at MkDocs:

- https://github.com/mkdocs/mkdocs/issues/3164
- https://github.com/mkdocs/mkdocs/pull/3232 (my PR)

**Comment by sheilnaik** [comment]
> temporary:
> 
> follow this document add custom theme override: `main.html`, apply the content.
> 
> ```
> {% block scripts %}
>   <script type="module">
>       import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10.2.0/+esm'
>   </script>
> {% endblock %}
> ```

This definitely feels like a temporary workaround. Using this block removes the search field. Adding `{{ super() }}` as suggested [in the docs](https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks) brings back the search bar, but also reverts back to the version of Mermaid (version 9.x) included with `mkocs-material`. It doesn't seem like there's a way to have both.

**Comment by squidfunk** [comment]
We've re-evaluated this request and progress is now tracked in #5758. If somebody is up to it, any help is appreciated. Please see the additional comments in #5758.

**Comment by glureau** [comment]
@sheilnaik did you find another workaround?

**Comment by sheilnaik** [comment]
> @sheilnaik did you find another workaround?

I unfortunately did not. I'm waiting on #5758 and I'm just not using search on my site for now.
