### ISSUE TITLE
Bad hyperlink

### ISSUE THREAD

**Issue by santaimpersonator** [squidfunk/mkdocs-material#5196]
### Description

There is a bad hyperlink in this [section of the documentation](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration). The [Emoji with custom icons](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#custom-icons) under the configuration options list links to a non-existent permalink.

![image](https://user-images.githubusercontent.com/36016723/224862311-1ad5ed4c-b330-4186-bbbf-4b6b711a3797.png)

### Related links

- [Docs section that issue is located](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration)
  - Bad Permalink: [Emoji with custom icons](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#custom-icons)
- Should link to this [permalink](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.emoji.options.custom_icons)
  ![image](https://user-images.githubusercontent.com/36016723/224862435-6854c778-292a-4ebf-9127-bff5367675af.png)

### Proposed change

Change: https://github.com/squidfunk/mkdocs-material/blob/master/docs/reference/icons-emojis.md?plain=1#L66

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in b5925cf89.
