### ISSUE TITLE
Built-in `search` plugin doesn't properly filter `script` and `style` tags

### ISSUE THREAD

**Issue by veghdev** [squidfunk/mkdocs-material#5198]
### Context

Based on [this](https://github.com/danielfrg/mkdocs-jupyter/issues/123)

mkdocs-jupyter integrates notebooks into mkdocs site. Its output, style etc are included in the search index, so the index file will be very large.

### Bug description

"The cause seems to be that subsequent script/style/object tags are not skipped correctly due to mutations on the list of elements to be skipped. I'll issue a bugfix release when I get some time to work on it. Regardless, it's bad practice to include so many inline styles and scripts repeatedly in the page content – those inline scripts and styles should be moved to external resources." by @squidfunk

### Related links

- https://github.com/danielfrg/mkdocs-jupyter/issues/123
- https://github.com/veghdev/mkdocs-jupyter-search

### Reproduction

file:///home/david/Downloads/mkdocs-jupyter-search-main.zip
file:///home/david/Downloads/dump.html.zip

### Steps to reproduce

make
make doc

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting.

> file:///home/david/Downloads/mkdocs-jupyter-search-main.zip
> file:///home/david/Downloads/dump.html.zip

I'm having a hard time accessing your local files 😅

**Comment by veghdev** [comment]
Sorry :) I did not notice
[mkdocs-jupyter-search-main.zip](https://github.com/squidfunk/mkdocs-material/files/10966763/mkdocs-jupyter-search-main.zip)

**Comment by squidfunk** [comment]
Thanks! Fixed in 2c7b0a3fc.

**Comment by squidfunk** [comment]
Released as part of [9.1.3](https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.3).
