### ISSUE TITLE
Unexpected behaviour of `inline end` admonitions with headers

### ISSUE THREAD

**Issue by Inveracity** [squidfunk/mkdocs-material#5207]
### Context

Heya!

I was expecting the `inline end` admonitions to push headers below it.

I disabled my custom css but that did not seems to help. 

Any help would be appreciated!

### Bug description

The "third quote" admonition seems to jump in as shown in this screenshot, which was unexpected. Not sure if it's intentional. But I'd prefer if it would push down the Headers

![image](https://user-images.githubusercontent.com/8753040/225681336-178ab312-42d2-4fe8-92aa-f6ecf157f84d.png)

### Related links

- [inline-blocks](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks)

### Reproduction

Markdown to reproduce:

```plaintext
# Title

content

## First header

!!! quote inline end "my quote"

    a quote that blows your socks off and improves your life immensely

plenty of content related to the quote that is so profound and exciting it might just make your rich and famous.

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Fusce vehicula scelerisque facilisis.
Donec quis justo quis orci accumsan eleifend fringilla ac urna.
Nunc varius fringilla nisl.
Etiam ac ipsum a turpis elementum consequat ut vel arcu.

## Another header

!!! quote inline end "another quote"

    another quote that really brings the point across

Very little content here, and everything looks good

## A third header

!!! quote inline end "a third quote"

    look at me, I'm over here now

This is where things get janky
```

_I figured its okay not to attach a zip when the above is all that's needed to try it out_

### Steps to reproduce

1. write the markdown
2. render the result with `mkdocs serve`

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Please follow our [reproduction guide](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) and provide a minimal reproduction. This is necessary for us to check if we can improve the situation. Otherwise we'd need to invest significant time into setup. Thank you.

**Comment by Inveracity** [comment]
I added the following CSS to `extra_css: [css/extra.css]`

```css
.md-typeset h1,h2,h3,h4,h5,h6 {
  width: 100%;
  display: flex;
}
```

This seems to fix it for me, so I'll close this, thanks! 🙂
