### ISSUE TITLE
privacy plugin not compatible with Chinese in "repo_url" and "edit this page"

### ISSUE THREAD

**Issue by jeremy-feng** [squidfunk/mkdocs-material#5212]
### Bug description

I added the privacy plugin. I also added `repo_url` and `content.action.edit`. If I hover on the link, the title is a strange string.

<img width="211" alt="image" src="https://user-images.githubusercontent.com/44312563/226100332-b615f0ef-a99e-424c-be63-54013dafa8c7.png">

<img width="168" alt="image" src="https://user-images.githubusercontent.com/44312563/226100346-edff9a9a-bb7e-47a4-8951-1de038399c51.png">

It works well with English language. But it looks bad in Chinese Language.

I also changed the ovverride/language/zh.html, but it didn't work if the privacy plugin is turned on.

### Related links

- [code-actions](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#code-actions)
- [built-in-privacy-plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin)

### Reproduction

[privacy plugin not compatible with Chinese in "repo_url" and "edit this page".zip](https://github.com/squidfunk/mkdocs-material/files/11008268/privacy.plugin.not.compatible.with.Chinese.in.repo_url.and.edit.this.page.zip)

### Steps to reproduce

1. run `mkdocs serve`

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by jeremy-feng** [comment]
Privacy plugin is really useful. I hope it can work perfectly with Chinese. Actually, only translations related to GitHub repository are strange.

**Comment by jeremy-feng** [comment]
By the way, can I only add "edit this page" on each page, without showing my GitHub repository url on the top? I just want to edit some content when neccesary. The repository is private so that others can't view the repository through the link on the top of each page. Also, I won't click the link on the top very often.

**Comment by jeremy-feng** [comment]
Update: I delete the following language override:

```
"action.edit": "编辑此页",
"source": "前往仓库",
```

The strange strings disappear. I can see the English title now.

![image](https://user-images.githubusercontent.com/44312563/226103566-094796cc-5054-4c60-8d50-9fc310d189ac.png)

It's ok now but I still hope this issue can be fixed to fully support Chinese language.

**Comment by jeremy-feng** [comment]
> By the way, can I only add "edit this page" on each page, without showing my GitHub repository url on the top? I just want to edit some content when neccesary. The repository is private so that others can't view the repository through the link on the top of each page. Also, I won't click the link on the top very often.

I got it. Just delete `repo_name` and `repo_url`, and add full url in `edit_uri`. The full url is like:

```
edit_uri: 'https://github.com/xxx/xxx.github.io/edit/master/docs/'
```

**Comment by squidfunk** [comment]
Thanks for reporting. [You did not use the built-in `info` plugin to create the reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) as we request, which is why we have no idea which version of Insiders you're running. The plugin collects all necessary information that is essential for debugging. It is absolutely necessary to use the plugin when creating reproductions.

When we download and run your example, everything works as expected. [Make sure to update to the latest version](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#upgrade-to-latest-version). This is the only advise we can give based on the information we got from you. If that doesn't work, please create a proper reproduction going through the process outlined in the linked section of our documentation 😊


https://user-images.githubusercontent.com/932156/226188208-955ebd96-13c3-4c27-8862-764df051d56d.mp4

**Comment by jeremy-feng** [comment]
Sorry for the inconvenience. I uploaded a new example with `info` plugin.
[example.zip](https://github.com/squidfunk/mkdocs-material/files/11011675/example.zip)

**Comment by squidfunk** [comment]
Thanks for providing the reproduction. The problem is still not reproducible, see video posted in https://github.com/squidfunk/mkdocs-material/issues/5212#issuecomment-1475303428.

**Comment by jeremy-feng** [comment]
Thanks! But I still see the strange string on my computer. I have no idea what to do now. The only thing I learned after many tests was that the `privacy` plugin was the key factor. If I don't use the `privacy` plugin then everything would be fine.

Now I just delete the translation in the language file and keep the English words. After all, it's not a big trouble for me.

Thanks for your precious time! I will remind using `info` plugin if I have a new issue next time!

**Comment by squidfunk** [comment]
Please make sure that the file containing the overrides has the correct character set, i.e., UTF-8. If you use a non-UTF-8 character set for the file, behavior may be unpredictable.
