### ISSUE TITLE
Sitemap.xml is not generated correctly

### ISSUE THREAD

**Issue by pymumu** [squidfunk/mkdocs-material#5215]
### Bug description

The sitemap.xml in the root directory of the site does not seem to be generated correctly.
The website is generated with github action.

The content of sitemap.xml is as follows:
```shell
None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily
```

### Related links

sitemap.xml example
https://pymumu.github.io/smartdns/sitemap.xml

github action:
https://github.com/pymumu/smartdns/blob/doc/.github/workflows/mkdocs.yaml

### Reproduction

Generate site.

### Steps to reproduce

1. Generate site and publish
2. Get sitemap.xml
3. sitemap.xml may like this:
```
None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily None 2023-03-17 daily
```

### Browser

Chrome

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. However, this issue __does not contain a minimal reproduction__. Furthermore, this issue is not specific to Material for MkDocs, as it will also happen with other themes. Please take this upstream. Thanks.
