### ISSUE TITLE
Issues with migrating to Mermaid version 10

### ISSUE THREAD

**Issue by ScratchCat458** [squidfunk/mkdocs-material#5217]
### Context

Recently Mermaid JS made a major change to their build setup in which they only build for ES modules (see [this issue](https://github.com/mermaid-js/mermaid/issues/3590)). I have been trying to change my Mermaid version to 10 by using the `extra_javascripts` section of the config, but to no avail.

When I add a version with a regular `mermaid.min.js` from unpkg, the version used internally (9.3.0) is swapped out for the version I specify. This is the intended behaviour described in #3171. However, if this is done with a `mermaid.esm.min.mjs` such as in the currently stable version (10.0.2), nothing gets pulled in.

The version 10.0.3-alpha.1 does provide a `.min.js`, but when imported, it only renders my Mermaid code as if it were plain text using Pygments.

### Description

I have to admit that I'm not all that familiar with the internal of this projects so I'm not able to comment on the difficultly of implementing any of these ideas.

Idea 1:
Replacing the use of the standard JS imports with the newer ES module build
The main issue that comes with this is handling backwards compatibility between old versions of Mermaid that don't use ESM when working with internal usage.

Idea 2:
Modifying the replacement functionality of `extra_javascripts`
This would allow users to opt into using these more recent versions without breaking old configs.

Idea 3: 
Providing Mermaid version control as a separate configuration option
Would require much internal effort for handling both types of module but would act a long-term solution for changing Mermaid's settings.
Example config:
```yaml
plugins:
  - mermaid:
    - version: 10.0.2
```

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Mermaid ESM Issue](https://github.com/mermaid-js/mermaid/issues/3590)
- Mermaid configuration issue #3171

### Use Cases

I am a big fan of using diagrams with in my work for documenting systems and ideas. For me having this integrated into the method I use to write documentation for my projects is incredibly valuable. Though Material for MkDocs does not have direct endorsement for use of diagrams such as Gitgraph and mindmap, I feel that option to have these available in this tool would be beneficial to many including myself, and bumping the version up to 10 is a requirement to make that happen.

Thank you for considering this, it means a lot to me. :)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Please see https://github.com/squidfunk/mkdocs-material/issues/5193#issuecomment-1468369372. It's currently not possible for us to migrate to Mermaid 10. We currently can't make the switch as we would lose support for older browsers. We might investigate a combined approach in the future (detecting browser support), but integration is fundamentally different and will likely be very challenging.

If somebody wants to investigate, happy to discuss a possible integration in a PR.
