### ISSUE TITLE
Generate Edit button has if page.edit_url not working as expected

### ISSUE THREAD

**Issue by sreenivasulureddysura** [squidfunk/mkdocs-material#5233]
### Context

I have a `page.edit_url` generated with the hooks. In mkdocs-material is not generating it.

### Bug description

Custom adding of edit_uri is not working

### Related links

-[edit_uri](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#view-source-of-this-page)

### Reproduction

`
site_name: EXAMPE
repo_url: https://github.com/exampe
#edit_uri_template: edit/master/{path}
#edit_uri: edit/master/

hooks: 
  - doc/my_hooks.py
 
`
#my_hooks.py

`
      from os.path import commonpath, relpath
      from urllib.parse import quote_plus
  
    from mkdocs.config import config_options
    from mkdocs.plugins import BasePlugin
  
  
    DEFAULT_BRANCH = "master"

    def on_config(config):
        if not config["repo_url"]:
            # Do not show edit button without user-defined repo_url
            # todo: get repo_url and remote branch from git?
            return config

          repo_url = config["repo_url"].rstrip("/")
         edit_branch = DEFAULT_BRANCH
         config["editor_url"] = f"{repo_url}/edit/{edit_branch}/"
        return config

    def on_pre_page(page, config, files):
        try:
            editor_url = config["editor_url"]
        except KeyError:
            return page

        src_path = page.file.src_path
        page.edit_url = f"{editor_url}{page.file.src_path}"
        print(f"page.edit_url: {editor_url}{src_path}")
        return page

`

### Steps to reproduce

1. docs_dir is root directory not the doc folder.
2. added the custom hooks to edit and  add the page url.
3. Need to generate the edit_url in page.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
This issue does not conform to our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Closing as [incomplete](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#incomplete-issues).
