### ISSUE TITLE
About Chinese search

### ISSUE THREAD

**Issue by hongxiaolu** [squidfunk/mkdocs-material#524]
## Description

The default theme can support Chinese search, and mkdocs-material can not search Chinese, how to set it? Thanks.

**Comment by squidfunk** [comment]
Do you have some example content (chinese document) I can use to test your error?

**Comment by hongxiaolu** [comment]
Hi,
Sorry, I forgot I replaced the lunr.min.js  file in /Library/Python/2.7/site-packages/mkdocs/assets/search/mkdocs/js. and  I replaced index.md in the attachment.

[归档.zip](https://github.com/squidfunk/mkdocs-material/files/1405830/default.zip)

**Comment by cxlwill** [comment]
I think it is influenced by lunr.js. If I change to Japanese search tokenizer, everything works well.

**Comment by squidfunk** [comment]
We will address this in #531.

**Comment by squidfunk** [comment]
Fixed in #547, it's now separately configurable
