### ISSUE TITLE
Links to span do not work (typeset likely to blame)

### ISSUE THREAD

**Issue by jaceklaskowski** [squidfunk/mkdocs-material#5241]
### Bug description

Links (`hrefs`) to span elements stopped working after [typeset](https://squidfunk.github.io/mkdocs-material/reference/#built-in-typeset-plugin) plugin got enabled.

### Related links

- [Discussion](https://github.com/squidfunk/mkdocs-material/discussions/5214)

### Reproduction

[mkdocs-material-repro.zip](https://github.com/squidfunk/mkdocs-material/files/11038752/mkdocs-material-repro.zip)

### Steps to reproduce

1. Unzip the reproduction package
2. Enable `typeset` plugin in `mkdocs.yml` and click any link on the index page. They do not lead to corresponding `span` sections.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. I would kindly ask you to use the [built-in `info` plugin](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file) as mentioned in our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) and this issue template the next time, as it contains essential information on the runtime and environment, as well as installed packages. I'll try to investigate this issue nonetheless, but it makes my work more challenging.

**Comment by squidfunk** [comment]
Released as part of [9.1.4](https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.4).

**Comment by squidfunk** [comment]
Released as part of [9.1.4-insiders-4.32.4](https://github.com/squidfunk/mkdocs-material-insiders/releases/tag/9.1.4-insiders-4.32.4).
