### ISSUE TITLE
Upgrade Mermaid

### ISSUE THREAD

**Issue by Commandcracker** [squidfunk/mkdocs-material#5251]
### Context

I would happely make a pull request but im a JS noob.

### Description

Upgrading Mermaid will allow users to use new features of it.

### Related links

- [mermaid sequenceDiagram grouping-box](https://mermaid.js.org/syntax/sequenceDiagram.html#grouping-box)
- [mermaid versions](https://github.com/mermaid-js/mermaid/tags)

### Use Cases

I want to use a box in my sequenceDiagram but boxes are added in v9.4.0 and mkdocs-material uses v9.3.0.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Updated Mermaid to 9.4.3 in 6a4be6b72. Note that some adjustments to flowcharts where necessary to keep the style.

**Comment by squidfunk** [comment]
Released as part of [9.1.5](https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.5).
