### ISSUE TITLE
Mermaid looks a bit odd

### ISSUE THREAD

**Issue by Commandcracker** [squidfunk/mkdocs-material#5252]
### Description

Mermaid notes don't fit the theme and the text in them sometimes gets out of bounds.
Text above lines overlap with other objects.

### Related links

-

### Use Cases

Better Visuals

### Visuals

![grafik](https://user-images.githubusercontent.com/49335821/227618916-383d964e-0e88-46bf-a33f-fa05475c69b9.png)
```mermaid
sequenceDiagram
    autonumber
    actor Client
    Note over Cache: Folder on server
    Note over Sanic: Web server
    Client-)Sanic: Sends a media request
    Note over Sanic: If the media is from spotify<br/>use spotipy to get information to<br/>create a serch term
    Sanic--)YT-DLP: Get information about the media
    Sanic-)Client: Tells the client<br/>inforamtion about the media
    Sanic--)YT-DLP: Downloads media
    YT-DLP-)Cache: Stores media in cache
    Sanic--)FFmpeg: Convert audio to dfpwm
    FFmpeg-)Cache: Stores audio in cache
    Sanic--)Sanjuuni: Convert video to 32vid
    Sanjuuni-)Cache: Stores video in cache
    Cache->Cache: Deletes original downloaded media
    loop Streaming
        Client-)Sanic: Request video and audio chunks
        Cache-)Sanic: Reads video and audio chunks
        Sanic-)Client: Sends video and audio chunks
        Note over Client: Receives and displays the media
    end
```

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. However, this is a bug report and not a feature request. Please go through the process of reporting a bug by [reading our bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) and providing a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). Thank you! ☺️
