### ISSUE TITLE
edit on github button missing

### ISSUE THREAD

**Issue by veghdev** [squidfunk/mkdocs-material#5261]
### Context

- using latest (9.1.4) mkdocs-material theme
- using latest (1.4.2) material
- setting repo_url and edit_uri in mkdocs.yml

### Bug description

With material theme edit on github button is missing from the generated page.
With same configuration and with other themes (mkdocs, readthedocs) it works.
I've attached a minimal sample and config to reproduce.

### Related links

- [repository for reproduction](https://github.com/veghdev/mkdocs-material-edituri)
- [related issue](https://github.com/squidfunk/mkdocs-material/issues/5233)

### Reproduction

[mkdocs-material-edituri-main.zip](https://github.com/squidfunk/mkdocs-material/files/11071021/mkdocs-material-edituri-main.zip)

### Steps to reproduce

- make dev
- make doc

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. It seems you upgraded recently to version 9, which makes the edit button opt-in. When upgrading major versions you should always read the [upgrade guide](https://squidfunk.github.io/mkdocs-material/upgrade/#upgrading-from-8x-to-9x), specifically [this](https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy). You need the following setting:

``` yaml
theme:
  features:
    - content.code.copy
```

**Comment by veghdev** [comment]
Thanks. I missed it.
If someone else finds this issue, the right setting is:

```yml
theme:
  features:
    - content.action.edit
```

**Comment by squidfunk** [comment]
Oops, you're right. Corrected my initial answer 😉
