### ISSUE TITLE
Installation of table-reader with Docker image 9.1.4

### ISSUE THREAD

**Issue by pvilas** [squidfunk/mkdocs-material#5282]
### Bug description

Trying to install the table-reader plugin with the Docker image I append this line to the Dockerfile `pip install mkdocs-table-reader-plugin`

Then I rebuild with `docker build -t squidfunk/mkdocs-material .`, but I have this error, possibly related with the numpy installation

```
#6 35.01         × Building wheel for numpy (pyproject.toml) did not run successfully.
#6 35.01         │ exit code: 1
#6 35.01         ╰─> [268 lines of output]
#6 35.01             setup.py:71: RuntimeWarning: NumPy 1.23.2 may not yet support Python 3.11.
#6 35.01               warnings.warn(
#6 35.01             Running from numpy source directory.
#6 35.01             setup.py:86: DeprecationWarning:
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[Dockerfile.zip](https://github.com/squidfunk/mkdocs-material/files/11080612/Dockerfile.zip)

### Steps to reproduce

try to install the table-reader plugin
get the error

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is not an issue with Material for MkDocs itself. If you need a different Python version, you can create your own `Dockerfile` and build a custom image 😉
