### ISSUE TITLE
Multi-line HTML comments in partial override ignored

### ISSUE THREAD

**Issue by do-me** [squidfunk/mkdocs-material#5294]
### Context

My repo structure is: 
```
.
├─ overrides/
│  └─ main.html
└─ mkdocs.yml
```

### Bug description

In `main.html` I commented out the announcement bar but with the latest version of mkdocs it's still rendered. Before (cannot exactly tell which version, just like until 3-4 months ago) it was surely properly parsed as comment and hence not rendered.

```html
<!-- Elements added to main will be displayed on all pages -->
{% extends "base.html" %}

<!-- Announcement bar if needed
{% block announce %}
  <style>.md-announce a,.md-announce a:focus,.md-announce a:hover{color:currentColor}.md-announce strong{white-space:nowrap}.md-announce .twitter{margin-left:.2em;color:#00acee}</style>
    <strong>Test</strong>
{% endblock %} -->
```

I tried to move the closing arrow around, in the line below, paid attention to a space before the arrow, but without success. 
Might it have something to do with the update of Jinja2 templates? 
In case I'm not missing the obvious it might be worth a footnote in the docs that multi-line comments are not allowed. 

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

Live demo: https://do-me.github.io/Test/
Repo: https://github.com/do-me/Test
Zipped repo: https://github.com/do-me/Test/archive/refs/heads/main.zip

main.html: https://github.com/do-me/Test/blob/main/docs/theme_override_home/main.html

### Steps to reproduce

Have a look at the repo & demo site.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is definitely not related to Material for MkDocs and will happen with any other template, so it's either related to Jinja2 or MkDocs. Please report this upstream.
