### ISSUE TITLE
Wrong Theming for Mermaid

### ISSUE THREAD

**Issue by Commandcracker** [squidfunk/mkdocs-material#5296]
### Context

As the text getting out of bounds from my previous issue https://github.com/squidfunk/mkdocs-material/issues/5252 was resolved by updating mkdocs-material, I created this issue that only includes theming related things.

### Description

- [Grouping / Box ](https://mermaid.js.org/syntax/sequenceDiagram.html#grouping-box) lables are hard to see, because they dont change color on theme change.
- [Notes](https://mermaid.js.org/syntax/sequenceDiagram.html#notes) dont fit the theme.

- > [Messages](https://mermaid.js.org/syntax/sequenceDiagram.html#messages) and arrows are hard to see on light theme if they are on top of a box with an inappropriate color.
  > There might be nothing that can be done here.

### Related links

Links are provided in the description.

### Use Cases

Better Visibility

### Visuals

![grafik](https://user-images.githubusercontent.com/49335821/229160071-786fb948-cb7e-4e80-b006-0c5cf8b6b829.png)
![grafik](https://user-images.githubusercontent.com/49335821/229160140-ddaaf791-4f7c-4373-9959-9007e38e4f36.png)
```mermaid
sequenceDiagram
    autonumber
    actor Client
    box rgb(33,66,99) Server
        participant Sanic
        participant YT-DLP
        participant Cache
        participant FFmpeg
        participant Sanjuuni
    end
    Note over Cache: Folder on server
    Note over Sanic: Web server
    Client-)Sanic: Sends a media request
    Note over Sanic: If the media is from spotify<br/>use spotipy to get information to<br/>create a serch term
    Sanic--)YT-DLP: Get information about the media
    Sanic-)Client: Tells the client<br/>inforamtion about the media
    Sanic--)YT-DLP: Downloads media
    YT-DLP-)Cache: Stores media in cache
    Sanic--)FFmpeg: Convert audio to dfpwm
    FFmpeg-)Cache: Stores audio in cache
    Sanic--)Sanjuuni: Convert video to 32vid
    Sanjuuni-)Cache: Stores video in cache
    Cache->Cache: Deletes original downloaded media
    loop Streaming
        Client-)Sanic: Request video and audio chunks
        Cache-)Sanic: Reads video and audio chunks
        Sanic-)Client: Sends video and audio chunks
        Note over Client: Receives and displays the media
    end
```

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for reporting. This is [not a change request but an incomplete bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature), as you're describing behavior that differs from what is expected. Please read our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/), and most importantly, provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by Commandcracker** [comment]
> By the way, [this is the second time](https://github.com/squidfunk/mkdocs-material/issues/5252#issuecomment-1483311914) you reported a bug as a feature request. Was my last comment unclear for some reason?

I'm sorry, I thought you only meant that the Notes being out of bounds is a bug and not the wrong theming. I'll create a proper bug report tomorrow.
