### ISSUE TITLE
I can't get redirects to work with the right site directory 

### ISSUE THREAD

**Issue by andrewhong5297** [squidfunk/mkdocs-material#5302]
### Context

I'm trying to get redirect mappings to work, but for some reason no matter what I try it redirects without keeping the `/docs/` part of the site directory. I don't get this issue when running things locally. 

You can see how I'm trying to do this in the repo [here](https://github.com/duneanalytics/docs/blob/master/mkdocs.insiders.yml)

### Bug description

No matter what filepath I try, it redirects without the `/docs/`. If I include it then it doesn't work at all.

### Related links

[Link to my repo](https://github.com/duneanalytics/docs/blob/master/mkdocs.insiders.yml)

### Reproduction

If you try going to https://dune.com/docs/reference/dune-v2/query-engine you will see the issue. I'm also using mkdocs insiders if that makes a difference.

### Steps to reproduce

Try going to this link https://dune.com/docs/reference/dune-v2/query-engine. You can see how I specify the redirect in the insiders yml file.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. However, please understand that we absolutely need a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) to look into your issue, as explained in our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Your repository contains too many files for us to efficiently track down the issue.

Additionally, please check if the issue persists if you change the theme to something else than `material`, e.g., to `readthedocs`. If so, it's definitely not an issue with this project, but with something else. Closing as upstream, unless proven otherwise reproduction. Please understand that we must efficiently allocate our time to push the project forward.

**Comment by andrewhong5297** [comment]
I can't upload the zip file because it is 217 MB. But okay - I will try another theme when I have a chance.

**Comment by andrewhong5297** [comment]
and the issue is just that the redirects work with mkdocs.yml (when served locally) but not mkdocs.insiders.yml (when on production). anyways get that might be too tough for you

**Comment by squidfunk** [comment]
> I can't upload the zip file because it is 217 MB. But okay - I will try another theme when I have a chance.

That's the whole point – it's not a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) 😉 Creating one is super simple, if you follow the guide.

**Comment by squidfunk** [comment]
> and the issue is just that the redirects work with mkdocs.yml (when served locally) but not mkdocs.insiders.yml (when on production). anyways get that might be too tough for you, I'll circle back to this when I find a solve

Possibly related: [sharing plugin configuration](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#mkdocsinsidersyml_1).

**Comment by andrewhong5297** [comment]
> > I can't upload the zip file because it is 217 MB. But okay - I will try another theme when I have a chance.
> 
> 
> 
> That's the whole point – it's not a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) 😉 Creating one is super simple, if you follow the guide.

Yeah all good! For anyone who runs into this issue and wants a wuick fix just hardcode your redirect links :)
