### ISSUE TITLE
Change to Navigation Sections

### ISSUE THREAD

**Issue by koinupapi** [squidfunk/mkdocs-material#5304]
### Description

The feature "navigation sections" changes the nav level 1 headers to groups, buy not on mobile.

I recently saw a documentation site powered by gitbook, which DOES allow this on mobile, and it looks good!

Anyway we can get this on mobile too?

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

It would allow nav.sections on mobile.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. This can be achieved with additional CSS. It is tough, but it's definitely doable. However, I'm not comfortable adding even more options to the [navigation configuration](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/) of Material for MkDocs, as it is already complex enough. For this reason, I'll consider this a prime case for customization. If you do that, feel free to share it here!
