### ISSUE TITLE
Seperate search language and theme language setup

### ISSUE THREAD

**Issue by cxlwill** [squidfunk/mkdocs-material#531]
Material introduced new localization system, which is quite convenient for users. But language support  in `lunr.js` is far wider than material's. The simultaneous setup will cause some languages cannot  get proper search language. 

For example, there is no Japanese translation right now. But Japanese is supported in `lunr.js`. 

Even if language support is added in `material`, there is still a problem that one language is supported in `material` but not `lunr.js`. However, add language support for `lunr.js` is quite difficult because it needs higher programming skill. Let's say Chinese, there is no Chinese language support for `lunr.js`, but actually Japanese support works on Chinese.

So if we can divide the setup for `theme` and `search`, it would be much easier for some users.

**Comment by squidfunk** [comment]
I agree. I will provide another configuration option to specify the search language separate from the theme language. However, if the Japanese stemmers work for the chinese language, we could just symlink them!

**Comment by cxlwill** [comment]
Yes, Japanese Stemmer actually works on major Chinese search. While they are different language, after all, so there must be some differences. For basic use, I personally think it is OK to merge them.

**Comment by squidfunk** [comment]
Fixed in #547, it's now separately configurable. 2.0.0 release is about to happen.
