### ISSUE TITLE
Icon search format is not compatible with `logo` configuration

### ISSUE THREAD

**Issue by pawelad** [squidfunk/mkdocs-material#5316]
### Description

The format of the icon from the `Icon search` website (i.e. `:material-library:`) is not compatible with `logo` config value, even though the docs imply it is.

When using the`:material-library:` value copied from the `Icon search`, I get this exception:

```
jinja2.exceptions.TemplateNotFound: .icons/:material-library:.svg
```

Everything works as expected when using `material/library`. I'm guessing the format of the results from the `Icon search` changed at some point and the docs regarding the `logo` config weren't updated.

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo

<img width="740" alt="Screenshot 2023-04-03 at 12 38 22" src="https://user-images.githubusercontent.com/7062874/229487056-25fc7b1e-aed7-4def-87c0-c34450d2dbce.png">

- https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search

<img width="729" alt="Screenshot 2023-04-03 at 12 38 33" src="https://user-images.githubusercontent.com/7062874/229487095-5dd56604-233c-47eb-a8b9-f88e202526aa.png">

### Proposed change

There are a couple ways of tackling it:

- the `logo` config could accept the 'emoji' format alongside the current values (so both `material/library` and `:material-library:` would work)
- the documentation on the `logo` side could mention that you need to change the formatting from `:material-library:` to `material/library`
- the icon search could present both values (but which one would be copied by default?)

I'd be happy to help with a PR if needed.

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
In `mkdocs.yml` and templates, icons must be referenced using file paths relative to the `.icons` directory. In Markdown, icons a replaced by Python Markdown Extensions. This is also explained in the [custom icon guide](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons). The icon search in the __Reference__ section is meant for using icons in Markdown. This is also why there's a dedicated icon search next to each icon configuration setting that can be expanded when clicking on the annotation as shown in the screenshot.

I don't think further clarification is necessary. You should use the embedded icon searches when configuring icons.

**Comment by pawelad** [comment]
Thank you for the quick reply!

It didn't even cross my mind that the 'search example' inside the tooltip was interactive and not a screenshot... 😅 

I wonder if I'm alone in this - if not, I'd maybe remove the `icon search` link from the tooltip or include a clarification that the search is interactive, but as you said, I think it's safe to leave this as is for now.

**Comment by squidfunk** [comment]
Thanks for your feedback! We'll reconsider even better clarification when we rework that section on our docs next time, but for the time being I think this can be considered sufficient.
