### ISSUE TITLE
the "blog" plugin is not installed?

### ISSUE THREAD

**Issue by Midoriyar** [squidfunk/mkdocs-material#5317]
### Context

I want to add a blog to my website. Then I search in [https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/) and online documentation but nothing helped me get what I wanted

### Bug description

when i add the `blog` plugin to `mkdocs.yml` my page fails to run giving an error:
```bash
ERROR - Config value 'plugins': The "blog" plugin is not installed
Aborted with 1 Configuration Errors!
```
![image](https://user-images.githubusercontent.com/122616108/229525427-c0a58829-4c3d-4cd0-95a2-9f421f0aa213.png)

### Related links

- [https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/)

### Reproduction

[codelachanly.github.io.zip](https://github.com/squidfunk/mkdocs-material/files/11138885/codelachanly.github.io.zip)

### Steps to reproduce

1. after extracting the `.zip` file that I sent, try running the command `mkdocs serve` in the terminal. Error will be displayed

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Are you a sponsor and using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/)? The blog plugin is currently reserved to sponsors:

<img width="493" alt="Bildschirm­foto 2023-04-03 um 16 00 04" src="https://user-images.githubusercontent.com/932156/229532202-e4f865bc-2a6d-4b44-875d-d25e460a1098.png">

**Comment by Midoriyar** [comment]
> Thanks for reporting. Are you a sponsor and using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/)? The blog plugin is currently reserved to sponsors:
> 
> <img alt="Bildschirm­foto 2023-04-03 um 16 00 04" width="493" src="https://user-images.githubusercontent.com/932156/229532202-e4f865bc-2a6d-4b44-875d-d25e460a1098.png">

Oh thanks. I understood the problem

**Comment by tahakhan0** [comment]
Is this still the case?

I checked the website recently and it doesn't say that is limited to sponsors.

<img width="780" alt="Screen Shot 2023-08-03 at 7 59 17 AM" src="https://github.com/squidfunk/mkdocs-material/assets/66910570/51c52b80-ebe2-49cf-a4bf-ed45350c93a6">

**Comment by squidfunk** [comment]
Yes, it's part of the community edition now, as announced in #5686. You currently need to install the beta version to start using it. It's all explained in the linked issue.

**Comment by tahakhan0** [comment]
> Yes, it's part of the community edition now, as announced in #5686. You currently need to install the beta version to start using it. It's all explained in the linked issue.

Amazing. Thanks for pointing me in the right direction.

**Comment by Acerinth** [comment]
Hi,

Perhaps I'm totally crazy... but I still get this error with current 9.5.17 (Docker version). Simple yaml:
```yaml
site_name: Test

plugins:
  - blog
  - search
```

results in `Config value 'plugins': The "blog" plugin is not installed`.

What did I miss?

**Comment by alexvoss** [comment]
I think you are missing the definition of the Material theme, which is where the blog plugin comes from.

```yaml
theme:
  name: material
```

**Comment by Acerinth** [comment]
Thank you @alexvoss , it's definitely not my day...

**Comment by alexvoss** [comment]
No worries, we've all done that ;o)
