### ISSUE TITLE
Syntax error in data-tables Excel warning admonitions

### ISSUE THREAD

**Issue by ThibaudBrrd** [squidfunk/mkdocs-material#5326]
### Description

It seems that there may be a syntax error in **the pip command for installing the required package for the warning admonitions**. The command currently reads as follows: '_pip install poenpyxl_' instead of '_pip install openpyxl_'. Unless it's intentional, I am unable to install any package named poenpyxl or find it on pypi.org.

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
- [Data-tables Excel section in the documentation](https://squidfunk.github.io/mkdocs-material/reference/data-tables/#import-data-from--excel-file)

### Proposed change

Changing the pip command into 'pip install openpyxl'

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by katharinalisalin** [comment]
Thanks for reporting. Fixed in a5f25823e.
