### ISSUE TITLE
Add a social link icon for Discord

### ISSUE THREAD

**Issue by alexjlockwood** [squidfunk/mkdocs-material#5367]
### Context

I would like to add a social link to my discord server in my website

### Description

I would like to add a social link to my discord server in my website. However the list of [supported icons](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=social#social-links) does not include discord. It would be nice if it can be supported.

The discord icon I am talking about is [here](https://fontawesome.com/icons/discord?f=brands&s=solid) (or something similar)

### Related links

- List of current supported icons: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/?h=social#social-links
- Discord icon: https://fontawesome.com/icons/discord?f=brands&s=solid

### Use Cases

I think this change would be useful to anyone who wants to link to their discord server from the website. Seems like it probably is not the most common thing in the world, but hopefully the change is simple enough that it isn't too much trouble to add!

### Visuals

The discord icon that would be supported is here: https://fontawesome.com/icons/discord?f=brands&s=solid

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexjlockwood** [comment]
As I was typing this, I realized that it actually is supported (it just wasn't documented). So nevermind :)

**Comment by squidfunk** [comment]
No worries ☺️ Those are just common usage examples. We should definitely add the Discord logo, as I think it's used rather often. If you would like to contribute this as a docs change in a PR, you're very much invited!

**Comment by alexjlockwood** [comment]
@squidfunk Sure thing, I've added the line to the docs here https://github.com/squidfunk/mkdocs-material/pull/5368

I tested it locally and it rendered fine but LMK if I missed something lol
