### ISSUE TITLE
Jumping to anchor inside details doesn't open it

### ISSUE THREAD

**Issue by makshh** [squidfunk/mkdocs-material#540]
## Description

If you click on the footnote arrow at the bottom of the page and footnote is inside `details`  it doesn't jump to the note (when `details` is closed).

### Expected behavior

Appropiate `details` should be opened when you click on the footnote arrow and it should jump to the note.

### Actual behavior

Clicking on the arrow doesn't work when footnote is inside `details` and `details` is closed.

### Steps to reproduce the bug

1. Create footnote in details.
2. Click on the footnote arrow at the bottom of the page (`details` must be closed).

### Package versions

* MkDocs: 1.12.1
* Material: 0.16.3

### Project configuration

Irrelevant

### System information

Irrelevant

Possible fix:

1. Detect if footnote is inside details
2. If yes - preventDefault(), if no - normal behaviour
3. Check if details is opened, if yes - change hash in the url, if no - open it and change hash in the url

**Comment by squidfunk** [comment]
Thanks for your report. The same should hold for headlines with permalinks. It's, however, a very low priority issue.

**Comment by squidfunk** [comment]
Fixed in #570

**Comment by squidfunk** [comment]
Fix released with 2.0.3

**Comment by makshh** [comment]
There is an error when you click on the arrow. This is because of the colon in the selector, for example `#fnref:1`. Need to escape this colon when using `querySelector`.

**Comment by squidfunk** [comment]
Ah thanks, haven't tested it with footnotes, only with headlines. My fault. will provide a fix.

**Comment by squidfunk** [comment]
Just released 2.0.4 which fixes the error with `querySelector` by using `getElementById` which should be more robust for these errors.
