### ISSUE TITLE
Add `tags.enabled` Option

### ISSUE THREAD

**Issue by Arthri** [squidfunk/mkdocs-material#5401]
### Description

Add a `tags.enabled` option to conditionally enable the tags plugin.
```yaml
plugins:
  tags:
    enabled: !ENV [CI, false]
```

### Related links

- [Discussion](https://matrix.to/#/!HzfBWDfDuxtzxDInWV:gitter.im/$I07CZXYyvH6Zy8FNYla91scIjUi15wamoZzK62X_Eng)
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/#+tags.enabled

### Use Cases

- Allows for disabling tags during development builds to speed up development

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks! As said, this was an oversight, it should've been in the community edition from the start 😅 Added in ba90cb1cc.

**Comment by squidfunk** [comment]
Released as part of [9.1.7](https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.7).
