### ISSUE TITLE
CSS issue inside search result

### ISSUE THREAD

**Issue by rafaellichen** [squidfunk/mkdocs-material#5421]
### Context

a small CSS issue regarding the sticky header inside search result:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/15823067/234082326-c810dfca-4e42-4a5c-950c-d3551a408871.png">

### Bug description

when you scroll up, 1px of text are showing through the crack between the `inputbox` and the `# more on this page` header

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- N/A

### Reproduction

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/15823067/234083818-0bb559ac-a669-4ef7-b5c8-c1a380f6170d.png">
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/15823067/234083752-5acb30d4-663b-4917-8445-ac78c6bf7df7.png">

### Steps to reproduce

It seems like it doesn't always happen; hard to reproduce reliably. I had to open/close and change search keyword several times in order to get the display bug a few times.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by katharinalisalin** [comment]
Thanks for reporting.
To help us investigate and address the problem, please follow our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/) and create a minimal reproduction .zip with the assistance of our [reproduction guide](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). This will ensure that any customizations or other plugins do not cause the issue.
Unfortunately, as you have not provided a reproduction at this time, we are unable to investigate further. Please provide us with a reproduction .zip, and we will be happy to look into it. Thank you.

**Comment by rafaellichen** [comment]
cannot reproduce reliably, but issue exists. currently I override the CSS with:
```css
.md-search-result__more > summary {
    top: -1px;
    padding-top: 1px;
}
```

**Comment by katharinalisalin** [comment]
Unfortunately, without a proper reproduction example .zip, we can't reproduce it and look into the issue. Please feel free to reopen the issue once you can provide us with a working [example](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#minimal-reproduction, and we'll be happy to look into it.
Thank you.
