### ISSUE TITLE
mermaid classDiagram display exception

### ISSUE THREAD

**Issue by haers** [squidfunk/mkdocs-material#5422]
### Bug description

at this page,my site:https://toutiao.sbs/other/markdown/markdown-class-diagram/
it show error ,at the end of the page,footer shows at the bottem of the content

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

![WechatIMG21](https://user-images.githubusercontent.com/7501342/234237305-f9c6c0ae-cc8c-4efd-8f00-a9dd7f155ef0.png)

### Steps to reproduce

1. I write markdown class diagram, and it shows error

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by katharinalisalin** [comment]
Thanks for reporting.
To help us investigate and address the problem, please follow our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/bug-report/) and create a minimal reproduction .zip with the assistance of our [reproduction guide](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). Using our info plugin, described in our reproduction guide, to create your reproduction .zip will help you rule out that any customizations or other plugins cause your issue, and it helps us look into your issue faster.
Unfortunately, as you have not provided a reproduction at this time, we are unable to investigate further. As a result, we will mark this issue as [incomplete](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#incomplete-issues) and close it for now. However, please feel free to reopen the issue once you have provided a reproduction .zip, and we will be happy to assist you further. Thank you.
