### ISSUE TITLE
Light and dark mode images do not appear consistent when used with md_in_html extension

### ISSUE THREAD

**Issue by pushbroomsweep** [squidfunk/mkdocs-material#5428]
### Context

I want to add light and dark mode images with a common caption so I'm trying to use the md_in_html extension as follows:

```markdown
<figure markdown>
  ![test_image_light](images/mask_rcnn.jpg#only-light)
  ![test_image_dark](images/mask_rcnn.jpg#only-dark)
</figure>
```

![bug](https://user-images.githubusercontent.com/8900839/234604007-46cc6124-5442-478a-8da6-b3cf1e8282df.gif)

### Bug description

This seems to happen whenever using the md_in_html extension. It doesn't matter if `<figcaption>` is used. In dark mode, the content after the figure seems to be pushed down slightly lower compared to light mode.

When inspecting the html, the height of the `<p>` tag is a bit more in dark mode compared to light mode. I have also tried it with `markdown="block"`, `markdown="1"` and `markdown="span"` and it doesn't seem to make a difference.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[image_bug.zip](https://github.com/squidfunk/mkdocs-material/files/11333871/image_bug.zip)

### Steps to reproduce

1. Add the md_in_html extension to mkdocs.yml
2. Create a `<figure markdown>` element and add the `only-light` and `only-dark` images one after another (order doesn't matter, it's always the dark mode content that appears differently)
3. Optionally, include the `<figcaption>` element
4. Add some content below this `<figure>` block
5. View the page

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and the excellent reproduction! The problem was induced by a CSS override in the `slate` theme which set `display: initial` for `#only-dark` images in dark mode, setting them into `inline` display mode (the default). Setting `initial` might not be the best idea, but setting `block` might also interfere with author-provided CSS styles.

For this reason, I've refactored the way light and dark mode image modes are toggled in 986cadad2 and moved the overrides under the `data-md-color-scheme` scope. This way, authors can define images with any display mode while retaining the show/hide functionality.

**Comment by squidfunk** [comment]
[9.1.9 is out](https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.9), including the changes referenced in this issue! 🚀
