### ISSUE TITLE
Support map for plugins in JSON schema

### ISSUE THREAD

**Issue by pawamoy** [squidfunk/mkdocs-material#5455]
### Context

The documentation recommends setting plugins as a map to be able to deep-merge plugins from a base `mkdocs.yml` into a `mkdocs.insiders.yml` file. However it seems that the JSON schema expects an array.

I'm using this in VSCode to validate the MkDocs configuration:

```json
    "yaml.schemas": {
        "https://squidfunk.github.io/mkdocs-material/schema.json": "mkdocs.yml"
    },
```

### Description

I'd like the schema to support defining plugins as a map as well as an array. The following should not be underlined as having issues:

```yaml
plugins:
  search: {}
```

### Related links

- https://squidfunk.github.io/mkdocs-material/insiders/getting-started/?h=inher#built-in-plugins ("Sharing plugin and extension configuration" tip)

### Use Cases

Inheriting from a base config while avoiding duplicate configuration for plugins between both files.

### Visuals

![pluginsmaps](https://user-images.githubusercontent.com/3999221/235463421-7d291f6d-b356-4cff-be0c-2bc075eb07ff.png)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! This is actually an excellent issue for outside contributors, as it is not related to the codebase of Material for MkDocs. If somebody is up, a PR is very much welcome! If not, I'll look into it when I find some time.

**Comment by squidfunk** [comment]
See https://github.com/squidfunk/mkdocs-material/pull/5461#issuecomment-1538685732 – the map syntax is suboptimal – we should find a better way to recommend how to solve the [problems mentioned here](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#built-in-plugins).

**Comment by pawamoy** [comment]
Maybe we could create dummy plugins in the public version of mkdocs-material? This way MkDocs wouldn't complain and the dummy plugins could log an INFO message stating that they are "inactive" or something similar?

**Comment by squidfunk** [comment]
I also already thought of that option, but you would have to provide all configuration options and sync them once new stuff is added, or MkDocs will not consider the configuration valid. This would need to be a little more than just empty shells.

**Comment by squidfunk** [comment]
We should continue discussion in #3216, as this is not something specific to Material for MkDocs. If we find a better way merging configurations, please ping me, but until then, configuration validation does not work for the map syntax. However, as written before, the map syntax isn't compatible with the fact that now multiple instances of plugins are supported, which makes a lot of sense for plugins like the blog, privacy, social or optimize plugin, to distinguish different parts of the docs.

Closing as upstream / out of scope.
