### ISSUE TITLE
Privacy-Plugin included by default in additional docker image

### ISSUE THREAD

**Issue by psycrush** [squidfunk/mkdocs-material#5470]
### Context

I have a problem in my infrastructure to extend the Docker image squidfunk/mkdocs-material with the privacy plugin as described.

### Description

As described under https://squidfunk.github.io/mkdocs-material/getting-started/?h=docker#with-docker
the image **squidfunk/mkdocs-material** is bundled with the following plugins

- mkdocs-minify-plugin
- mkdocs-redirects

Is it possible to provide an additional image with the "privacy" plugin e.g. **squidfunk/mkdocs-material-with-privacy**?

### Use Cases

The standard image can be used as is and will not be changed or enlarged.
Users with privacy request can directly use the privacy variant.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by psycrush** [comment]
Thinking about it again I might get a problem when downloading the assets in the build prouess with privacy as well....  I'll try to test this. I leave this suggestion in anyway

**Comment by squidfunk** [comment]
Thanks for suggesting. The [built-in privacy plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin) is currently reserved to sponsors, thus only available via [Material for MkDocs Insiders](https://squidfunk.github.io/mkdocs-material/insiders/). It is bundled with the Docker image, as are all other built-in plugins ☺️ Closing, no change required.
