### ISSUE TITLE
Fenced Code Block should ignore "preamble" characters after Language

### ISSUE THREAD

**Issue by vorburger** [squidfunk/mkdocs-material#5473]
### Bug description

Code Blocks with "additional information" after the "language tag" in the "preamble", such as e.g. ` ```bash hello!`, break language detection (what follows is not bash syntax highlighted), and worse are even formatted as one long continous line of preformatted text without line breaks.

The GitHub MD renderer only looks at the first word after the ` ```bash` (or whatever) and ignores the rest.

I have a particular reason for wanting this to work like on GitHub in mkdocs - I'm "sneaking in" some (hidden) additional metadata in my _"Executable Markdown"_ processor after the language - see https://docs.enola.dev/use/execmd!

I understand Markdown isn't formally fully specified, and this kind of discrepancies can happen.

I see no harm in `mkdocs` (or some library it uses for this?) ignoring such extra information when it selects the language.

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
- https://docs.enola.dev/use/execmd
- https://github.com/enola-dev/enola/blob/docs/use/execmd/index.md

### Reproduction

I'm happy to provide one, should the description above not be clear enough?

### Steps to reproduce

I'm happy to provide further details, should the description above not be clear enough?

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting.

1. No reproduction, yes, it is absolutely mandatory to provide one.
2. This has nothing to do with Material for MkDocs in particular, it's the same for all MkDocs themes. Please report upstream.

**Comment by vorburger** [comment]
Thank You, that makes sense; opened https://github.com/pygments/pygments/issues/2426 - hope that's the right upstream project.

PS: https://docs.enola.dev/use/execmd was 404 earlier, but is fixed now.

**Comment by squidfunk** [comment]
If you need to get more input on this, you can [open a discussion](https://github.com/squidfunk/mkdocs-material/discussions) ☺️ Issues are for actual, confirmed bug reports. When in doubt, it's always a good idea to first open a discussion, [as our bug reporting guide mentions](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#fn:3).

**Comment by facelessuser** [comment]
Pygments does not control Markdown headers for code blocks, that is the Markdown parser. If you are using SuperFences (the fenced code library I maintain), it is unlikely we will make a change regarding code block headers as we already have well-established logic rules to handle code headers. We do not treat any content in the header as code and we have no intention to change that at the current time. You may be able to create a custom fence to sidestep that, but that would be left up to the user to explore.

Python Markdown (the Markdown parser being used in MkDocs) does not follow GitHub Markdown. It is an old-school Markdown parser created long before the many CommonMark parsers. I believe your requested logic may even be specific to CommonMark, which Python Markdown is not.

There are numerous Markdown parsers that came long before CommonMark that defined block-specific logic for fenced code headers that are not likely to change. You can see in the link below that there are many that do not follow your requested header logic. The only ones that do follow this logic seem to be CommonMark based.

https://babelmark.github.io/?text=%60%60%60bash+hello!%0Asomething%0A%60%60%60
