### ISSUE TITLE
Add GitLab icon collection

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#5489]
### Description

`mkdocs-material` already [supports 4 popular icon collections](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#configuration): Material Design Icons, FontAwesome, Octicons, and SimpleIcons. I suggest to add another one that's quite useful for technical (documentation) writers and a pendant to GitHub's Octicons for GitLab: [GitLab SVGs](https://gitlab.com/gitlab-org/gitlab-svgs). GitLab SVGs is GitLab's official icon collection of currently 394 monochromatic icons. The SVGs are found at https://gitlab.com/gitlab-org/gitlab-svgs/-/tree/main/sprite_icons.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://squidfunk.github.io/mkdocs-material/reference/icons-emojis

### Use Cases

When writing technical documentation that involves GitLab, using official GitLab icons may improve the reader experience.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! At this point, we're not considering adding more and more icon sets. The icon sets we have are quite complementary, maybe with an exception to FontAwesome which is basically there for historical reasons. The GitLab icon sets would have large overlap with Octicons that are already bundled, so it doesn't provide more value, but would increase the installation size of Material for MkDocs. Thus, please add the GitLab icons by going through the process of adding [additional icons](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons). You can set it up in 5min ☺️ Closing as out of scope.

**Comment by sisp** [comment]
Makes sense. Thanks for your detailed reply, @squidfunk! :pray:
