### ISSUE TITLE
Make It More General

### ISSUE THREAD

**Issue by ahmadawais** [squidfunk/mkdocs-material#55]
The inherent decision that documentation can only be of a GitHub repo is hurtful. This documentation can be used for anything. In my case a WordPress plugin which is not hosted at GitHub.

![img](https://i.imgur.com/x10RzOD.png)

This area is render useless in my usercase. It would be great if there can `extra` options for disabling and enabling the download and stars options or giving the download link or a buy link.

**Comment by ahmadawais** [comment]
These can be disabled but cannot be customized. Just found out that removing repo links removes the links.

**Comment by squidfunk** [comment]
1.0.0 add integration for different services. "Buying" is not on the list, because the repository link (we're still talking about source code documentation) is hard-wired into MkDocs. Theoretically one could add a Buy option, but it's the first time I hear of this use case and one has to think of how this would integrate with the new repository banner in the header.

**Comment by ahmadawais** [comment]
@squidfunk Great. Instead of automating everything — you can provide extra configurations in the `mkdocs.yml` file. E.g.

```yaml
extra:
  button_1_txt: Buy Now!
  button_1_url: http://domain.ext/buy-now/
```

I am new to how MKDocs work. But I think it would be possible?

**Comment by squidfunk** [comment]
Well, we could add tons and tons of extra options, but I don't know if this is the right direction for the theme. In general the theme tries to leverage all MkDocs features and to extend as little as possible. With 1.0.0, the buttons are gone anyway and there is only the source repository information.

**Comment by ahmadawais** [comment]
Can you guide me how do you add extra options? Maybe, I could add them on
my own? Thanks a lot.

**Comment by squidfunk** [comment]
You can just add them to the `mkdocs.yml` via the `extra` namespace and use them in the template with `extra.your_variable`, so pretty straight forward.

**Comment by ahmadawais** [comment]
Thanks!
