### ISSUE TITLE
FR: Editable code blocks

### ISSUE THREAD

**Issue by ofek** [squidfunk/mkdocs-material#5527]
### Description

Sections of code blocks may be templated with default values and may be modified by clicking which transforms that area to a text box. New lines should not be supported inside the text boxes.

### Related links

https://squidfunk.github.io/mkdocs-material/reference/code-blocks/

### Use Cases

This is useful when there is a desire for users to copy text or code and parts are defined by them.

### Visuals

https://cloud.google.com/artifact-registry/docs/docker/pushing-and-pulling#tag

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. This was already asked before (can't find the issue right now, GitHub search, meh). Editing code blocks will mess with syntax highlighting, as we're doing highlighting during build time. When we would allow users to edit code blocks, the tokens entered wouldn't be highlighted. Additionally:

- I don't think there's much value in editing stuff without being able to execute it. When the user reloads the page, the changes will be gone, except for when we try to persist it, which is another challenge of its own.
- There are better solutions like for example [markdown-exec](https://pawamoy.github.io/markdown-exec/) by @pawamoy. It allows you to edit code blocks and execute them. If we would allow for editable code blocks, executing them is the logical next step, which is language-dependent and better left to third-party extensions. We have to cut scope wherever we can, trying to provide the best general documentation experience for users and authors while being open and flexible for extension.

For this reason, we consider this feature request out-of-scope. There are already better solutions! ☺️

**Comment by zswanson** [comment]
> I don't think there's much value in editing stuff without being able to execute i

I disagree, we have a use-case for that. One of internal mkdocs site provides terraform samples that are built to help devs just copy/paste the most common configurations and only have to modify a things like adding the name of their app, their projectId etc, and so peristance or execution isn't a goal at all. We've written some javascript functions to help with this but having something built-in would be a lot better.

**Comment by squidfunk** [comment]
Thanks for providing the examples. I imagine that something like this can be implemented with a custom Markdown fence, but it would probably need language-specific support to denote what parts of the code block should be editable and what not. We here at Material for MkDocs, cannot provide this functionality, as it doesn't make a lot of sense for us to do so, because it needs minimal support from themes. If somebody implements something like this that is generic enough and doesn't only apply to specific languages, we're happy to the necessary support on the theme side!

**Comment by zswanson** [comment]
Sure, I don't know if a plugin makes more sense rather than the core theme? I only happened to find this issue while searching for a plugin that might provide this exact feature. :)

**Comment by squidfunk** [comment]
I think you'll rather need to implement a Markdown fence or extension, not a plugin, but I may be mistaken.

**Comment by samgaudet** [comment]
I would like to shamelessly self-promote an open source package (a custom fence) I created recently to solve this use case for anyone else who comes across this issue or is looking for this functionality: https://mkdocs-madlibs.readthedocs.io/en/latest/

**Comment by ofek** [comment]
Nice!
