### ISSUE TITLE
Support Note and Warning blockquote as hint container

### ISSUE THREAD

**Issue by jcwangxp** [squidfunk/mkdocs-material#5552]
### Description

Note
Some text here

Note: Some text here

Note: Some text here
Addtional Content

Warning
Some text here

Warning: Some text here

Warning: Some text here
Addtional Content

> **Note**
> Some text here

> **Note**: Some text here

> **Note**: Some text here
> Addtional Content

> **Warning**
> Some text here

> **Warning**: Some text here

> **Warning**: Some text here
> Addtional Content
They should be rendered with hint containers

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

github can support it and the md file can be shown in github correclty.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Material for MkDocs consumes the output of Markdown extensions that transform Markdown into HTML. This project doesn't do any processing of Markdown, it only processes the resulting HTML with some of its plugins. This is an excellent use case for a third party Markdown extension. Note that there is an extension that is similar to what you're asking for, called [markdown-callouts](https://oprypin.github.io/markdown-callouts/). Closing as out-of-scope.
