### ISSUE TITLE
Non-existent tag in image name

### ISSUE THREAD

**Issue by vladislav-sharapov** [squidfunk/mkdocs-material#5554]
### Description

Shell command `docker pull squidfunk/mkdocs-material:9` from [Installation with docker](https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker) section doesn't work, because tag `9` doesn't exist:
```
$ docker pull squidfunk/mkdocs-material:9
Error response from daemon: manifest for squidfunk/mkdocs-material:9 not found: manifest unknown: manifest unknown
```

### Related links

- [Installation with docker, 9.x](https://squidfunk.github.io/mkdocs-material/getting-started/#9x_1)

### Proposed change

I don't really see difference between tags `9` and `latest` even if tag `9` existed. For example, [Installation with pip](https://squidfunk.github.io/mkdocs-material/getting-started/#with-pip) section provides 2 ways to install latest version. From my point of view, it will be more helpful if documentation will describe how to install latest version and some pinned version like in [Ansible documentation](https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#pip-install). Same we can apply to [Installation with docker](https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker) section.

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
@crazy-max sorry to bother you again. I think it would be great to tag the images with minor and major versions, so users can pin the Docker container to a major version using semantic versioning. Studying the documentation of [`docker/metadata-action`](https://github.com/docker/metadata-action#typeref), I believe we need to change the following:

https://github.com/squidfunk/mkdocs-material/blob/f84725d4fcd8960090063d58f18fb01973b55370/.github/workflows/build.yml#L130-L133

We're following [semantic versioning](https://github.com/docker/metadata-action#typesemver) as much as possible, so I believe we should use that, correct? If so, would this configuration work? What are `branch` and `pr` needed for?

``` yaml
tags: |
  type=semver,pattern={{version}}
  type=semver,pattern={{major}}.{{minor}}
  type=semver,pattern={{major}}
```

This should tag the image with `9.1.14`, `9.1` and `9`.

**Comment by crazy-max** [comment]
> What are `branch` and `pr` needed for?

`branch` will create a tag matching the branch name, in your case `squidfunk/mkdocs-materia:master`. On `pr` event it will create a tag that looks like `pr-${number}`.

> This should tag the image with `9.1.14`, `9.1` and `9`.

Yes that sounds good:

```
      - name: Generate Docker tags and labels
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.event.repository.full_name }}
            ghcr.io/${{ github.event.repository.full_name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
          flavor: |
            latest=${{ github.event.release.prerelease == false }}
```

You could keep `branch` and enable push to hub repo for every push on `master` branch. This way users could test unreleased image and try out edge changes. Keeping `pr` would be good when pushing to `ghcr.io` so you can test PRs using `ghcr.io/squidfunk/mkdocs-materia:pr-123456`.

**Comment by crazy-max** [comment]
As you are just enabling push on release: https://github.com/squidfunk/mkdocs-material/blob/f84725d4fcd8960090063d58f18fb01973b55370/.github/workflows/build.yml#L163

Then `branch` and `pr` will never be pushed anyway.

**Comment by squidfunk** [comment]
Thanks for checking back so quickly! We'll keep `pr` and `branch` then, if somebody wants to enable it in a fork ☺️

**Comment by squidfunk** [comment]
Fixed in f37702a8f. On the next release, this issue will be resolved.

**Comment by squidfunk** [comment]
And done! Big thanks again to @crazy-max for the quick and awesome support 🤘

https://hub.docker.com/layers/squidfunk/mkdocs-material/9/images/sha256-404c4e499ab8f3d7c8e0ee21e1365ed0f85d088d171e1ea9da67dbe6cbdc6ae6

**Comment by crazy-max** [comment]
Yeah tagging looks good, nice!: https://github.com/squidfunk/mkdocs-material/actions/runs/5113420446/jobs/9192600729#step:7:52
