### ISSUE TITLE
Documentation on how to use search

### ISSUE THREAD

**Issue by mark-heptinstall** [squidfunk/mkdocs-material#5557]
### Description

The existing documentation focuses on setting up search and the [blog](https://squidfunk.github.io/mkdocs-material/blog/2021/09/13/search-better-faster-smaller/) on how it works but I don't see anything in practical terms of how someone should be using the search to get the best results.

I want to provide our users with some reference material on how to use the site search effectively. They have no interest in the configuration or technical aspects of searching.

The documentation does state it uses lunr and their documentation has a page on [searching](https://lunrjs.com/guides/searching.html) though that wasn't immediately obvious to me as a newbie. This is a good reference and it would be great to see this in the context of the mkdocs-material search and UI.

I'm also using tags, after looking at the lunr page I now realise I can restrict search terms to tags only by prefixing with `tags:` which I don't find in the documentation on setting up tags.

### Related links

-[Setting up site search](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/)
-[Setting up tags](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/)

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by karengermond** [comment]
Hi @squidfunk, when will you be replacing the search engine? My team would like me to replace the search engine but I want to wait to try out your custom implementation.

**Comment by squidfunk** [comment]
We're working on it, but it'll take some more time. We currently can't put a precise estimate on it, but it'll be later this year.

**Comment by karengermond** [comment]
Thanks for the update!

**Comment by squidfunk** [comment]
We came to the conclusion that we're not going to document how to _use_ search, i.e., to write a primer on the specific syntax from lunr.js – the reason is that our aim is to create a search that does not need you to know a syntax to use it, and/or makes it easy for you to learn modifiers from just using it. We might re-evaluate in the future, but for now, this is not planned.
