### ISSUE TITLE
Feature Request: Print this section

### ISSUE THREAD

**Issue by userbradley** [squidfunk/mkdocs-material#5560]
### Context

Some of the documentation I write could be relied on later, or a user may want to take it offline in a PDF.

I would like to see a rendered view that allows an entire page or section to be presented on one page

### Description

On index pages, have a `Print this section` which will take the entire section, show it on one page and present it in a format that a user can just do `command` + `p` 

### Related links

- [Example](https://www.gov.uk/get-help-energy-bills/pay-energy-with-rent)

![image](https://github.com/squidfunk/mkdocs-material/assets/41597815/b9db6190-d30c-4e5b-b101-493bf69e7c35)

### Use Cases

Allowing users to generate a printable version of an entire section

### Visuals

![image](https://github.com/squidfunk/mkdocs-material/assets/41597815/4d4e764a-3680-4705-85d4-28653664dd06)

https://www.gov.uk/get-help-energy-bills/print

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Are you aware that there already is a print view? If you print from the browser, Material for MkDocs will apply print styling:

<img width="1438" alt="Bildschirm­foto 2023-05-25 um 16 47 57" src="https://github.com/squidfunk/mkdocs-material/assets/932156/3a20f126-ccdf-40ce-90e0-9fff4cd9be72">

Other than that I'm not sure what you mean by "print an entire section". Do you mean one page or an entire subsection of your documentation including multiple pages?

**Comment by squidfunk** [comment]
Thanks! This functionality is beyond the scope of this project, but there are third-party plugins that create PDFs out of MkDocs pages. Check out the [Best of list](https://github.com/mkdocs/best-of-mkdocs#-site-conversion-pdfepubetc), specifically the section on site conversion ☺️ Closing as out-of-scope.

**Comment by userbradley** [comment]
Awesome, completely understand!

Thanks!
