### ISSUE TITLE
Adapt to the dark theme of modern browsers corresponding to the scroll bar under the dark theme

### ISSUE THREAD

**Issue by SuperManito** [squidfunk/mkdocs-material#5562]
### Description

add head meta
```html
<meta name="color-scheme" content="<light or dark>">
```

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
-

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for suggesting. However, you used the documentation issue template to propose a change request. This is in violation with out contributing guidelines. Please carefully read the [guide on requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/) and use the appropriate template to propose what you'd like to see. Additionally, please provide all information that is asked by the guide.
