### ISSUE TITLE
Adapt to the dark theme of modern browsers corresponding to the scroll bar under the dark theme

### ISSUE THREAD

**Issue by SuperManito** [squidfunk/mkdocs-material#5566]
### Context

add head meta

```
<meta name="color-scheme" content="<light or dark>">
```

### Description

The scroll bar can use the dark mode. If the scroll bar still displays the default light mode after switching to the dark mode it will be uncomfortable

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

Docusaurus2 Vuepress

![image](https://github.com/squidfunk/mkdocs-material/assets/68613938/4a971fc8-9747-4d8f-8609-ce937393b326)
![image](https://github.com/squidfunk/mkdocs-material/assets/68613938/9d94ef95-0668-450a-9c25-ac6c9571633a)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! Fixed in fe0c966a4. We opted for the CSS `color-scheme` property, as it can be directly defined in the color schemes that we offer. Additionally, it's easier for authors to set those in their own custom color schemes.

[A good read on `color-scheme`](https://web.dev/color-scheme/).

**Comment by SuperManito** [comment]
> Thanks for suggesting! Fixed in [fe0c966](https://github.com/squidfunk/mkdocs-material/commit/fe0c966a4da16861e3fbe9064afcae3cc3d7c6fa). We opted for the CSS `color-scheme` property, as it can be directly defined in the color schemes that we offer. Additionally, it's easier for authors to set those in their own custom color schemes.
> 
> As an addendum, here's [a good read on `color-scheme`](https://web.dev/color-scheme/).

Your document website looks the same as it did before the fix commit

**Comment by SuperManito** [comment]
> Thanks for suggesting! Fixed in [fe0c966](https://github.com/squidfunk/mkdocs-material/commit/fe0c966a4da16861e3fbe9064afcae3cc3d7c6fa). We opted for the CSS `color-scheme` property, as it can be directly defined in the color schemes that we offer. Additionally, it's easier for authors to set those in their own custom color schemes.
> 
> As an addendum, here's [a good read on `color-scheme`](https://web.dev/color-scheme/).

I have some other suggestions. I think the background color in dark mode should be more towards black. Preferably controlled by the user via css variables.

The problem now is that when the background color or theme color is changed, the background color of some button hover does not change accordingly. This often requires providing multiple tones of different depths at the same time.

So my suggestion has two solutions: one is that the user only defines one main color, and the auxiliary colors of other depths are automatically provided by dependencies, such as tinycolor of npm; the other is to define a whole set of variables in css instead. Docusaurus provides an online solution [styling-your-site-with-infima](https://docusaurus.io/zh-CN/docs/styling-layout#styling-your-site-with-infima)

**Comment by squidfunk** [comment]
> Your document website looks the same as it did before the fix commit

The changes haven't been merged in Insiders yet, and our site is built with Insiders. We'll do that before the next release.

> The problem now is that when the background color or theme color is changed, the background color of some button hover does not change accordingly. This often requires providing multiple tones of different depths at the same time.
> 
> So my suggestion has two solutions: one is that the user only defines one main color, and the auxiliary colors of other depths are automatically provided by dependencies, such as tinycolor of npm; the other is to define a whole set of variables in css instead. Docusaurus provides an online solution [styling-your-site-with-infima](https://docusaurus.io/zh-CN/docs/styling-layout#styling-your-site-with-infima)

Please create a discussion for your suggestion with some screenshots or a screencast, so we can better understand what you want to see ☺️ It's beyond the scope of this issue, and we shouldn't mix feature requests in issues. Please also note that Material for MkDocs does not have an author-facing build step that compiles the CSS – 99% of users do not have a Node.js environment in their build pipeline available. For this reason, we decided that CSS variables are the best solution for overrides. If you want to deduce tints, you can always fork the theme, or set up a Node.js environment yourself and compute CSS variables, adding that as extra CSS. It's actually not that hard. For the majority of users, the current solution is simpler.

**Comment by squidfunk** [comment]
Released as part of [9.1.15](https://squidfunk.github.io/mkdocs-material/changelog/#9.1.15)!

**Comment by SuperManito** [comment]
> Released as part of [9.1.15](https://squidfunk.github.io/mkdocs-material/changelog/#9.1.15)!

Are you sure it works? I think this should be provided by default rather than user-defined.

**Comment by squidfunk** [comment]
Yes, `color-scheme` is definitely being defined as of 9.1.15. We provide it for the included color schemes (`default` and `slate`). For custom color schemes, you must just set it accordingly:

https://github.com/squidfunk/mkdocs-material/blob/fe0c966a4da16861e3fbe9064afcae3cc3d7c6fa/src/assets/stylesheets/palette/_scheme.scss#L30-L34

**Comment by squidfunk** [comment]
Works perfectly for me. [If I visit our documentation site](https://squidfunk.github.io/mkdocs-material/reference/diagrams/), and add an unstyled input field to the content, it will adapt to the OS color scheme:

<img width="1437" alt="Bildschirm­foto 2023-06-06 um 10 25 13" src="https://github.com/squidfunk/mkdocs-material/assets/932156/56d85299-7acb-4404-8908-520442d0f24f">

If I uncheck `color-scheme: dark`, it doesn't adapt. Thus, it behaves as advertised:

<img width="1435" alt="Bildschirm­foto 2023-06-06 um 10 25 41" src="https://github.com/squidfunk/mkdocs-material/assets/932156/18cf7322-d31a-47fc-ba8e-521c63638963">

Thus, it works.

**Comment by squidfunk** [comment]
Okay, so we might need to set the `coor-scheme` `meta` tag for that. We can't set it in the template, we must set it via JavaScript, as pressing the toggle to change the scheme will also change the value of the meta tag. Re-opening.

**Comment by squidfunk** [comment]
Fixed in d2f403495. The `color-scheme` `meta` tag is now synchronized with the palette.

**Comment by squidfunk** [comment]
Released as part of [9.1.16](https://github.com/squidfunk/mkdocs-material/releases/tag/9.1.16).
