### ISSUE TITLE
Add custom versioning example

### ISSUE THREAD

**Issue by vladislav-sharapov** [squidfunk/mkdocs-material#5568]
### Description

[Setting up versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/) page doesn't provide example how to make versioning without `mike` though it's possible.

### Related links

- [Setting up versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/)

### Proposed change

[Setting up versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/) page should contain information about `versions.json` and custom versioning. Maybe we need additional provider like `custom`.

Rough sketch:

You can also set up versioning yourself. In this case, you should deploy each version of documentation to corresponding folder and update `versions.json` with new versions. Your site directory will look like this:

```
0.1/
0.2/
0.3/
versions.json
```

`versions.json`:

```json
[
  {
    "version": "0.3",
    "title": "0.3",
    "aliases": [
      "latest"
    ]
  },
  {
    "version": "0.2",
    "title": "0.2",
    "aliases": []
  },
  {
    "version": "0.1",
    "title": "0.1",
    "aliases": []
  }
]
```

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for suggesting! We support `mike`, and while it is possible to achieve a custom versioning approach, it is very much dependent on your setup and there are probably a hundred ways to do the same thing. For that reason, we're currently not consider adding this to the documentation, it's just too custom. We must keep it as brief as possible.
