### ISSUE TITLE
post.authors does not display multiple authors

### ISSUE THREAD

**Issue by JuLeeAtPlanet** [squidfunk/mkdocs-material#5597]
### Context

`if page.authors` block from blog-post.html appears to be working, whereas ` {% if post.authors %}` in post.html does not.

Workaround, force multiple authors by adding `post_excerpt_max_authors` value to mkdocs.yml

```yml
  - blog:
      post_excerpt_max_authors: 4
```

### Bug description

1. Add 2 authors to .authors.yml
2. Add a post with metadata `authors: [author1, author2]

Multiple authors do not display in excerpt. Multiple authors display in sidebar.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Posts config options](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/?h=blog#posts)

### Reproduction

[blog-support-just-landed.md](https://github.com/squidfunk/mkdocs-material/files/11709253/blog-support-just-landed.md)

### Steps to reproduce

1. Add 2 authors to .authors.yml
2. Add a post with metadata `authors: [author1, author2]

Multiple authors do not display in excerpt. Multiple authors display in sidebar.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. We're happy to look into it, but please provide a fully self-contained reproduction, because we can't reproduce it otherwise. For example, [see this page](https://blog.privacyguides.org/), where the functionality works nicely.

**Comment by squidfunk** [comment]
> Workaround, force multiple authors by adding post_excerpt_max_authors value to mkdocs.yml
>
> ``` yaml
>   - blog:
>       post_excerpt_max_authors: 4
> ```

Just so that I don't misunderstand it, as it's not clear for me from reading your description – does this setting work? Because yes, the default is `1`, but if you set it to `4`, a maximum of `4`  authors should be shown in the excerpt. Since you classify this as a "workaround", it sounds to me that it works when you add this configuration.

**Comment by JuLeeAtPlanet** [comment]
No problem. Took all the time I had to figure out what was going on, and find a workaround. Must move on.

**Comment by squidfunk** [comment]
The setting is not a workaround – it is the way to configure how many authors should be shown in the post excerpt 😀
