### ISSUE TITLE
Embedding only a part of external file

### ISSUE THREAD

**Issue by mpusz** [squidfunk/mkdocs-material#5630]
### Description

[Embedding external files](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#embedding-external-files) is a great feature. For example, we can embed a source code of a simple example application and provide its description in the documentation. However, for longer files or tutorial-like pages, it would be nice to embed only a part of a file or split it into chunks separated with the documentation blocks.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

The following example showcases the features of the library:

```
only include statements should be embedded here
```

A user can find all the units in the headers provided above. After importing we may start using them:

```
the next part of the file follows
```

and so on....

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for reporting. [The embedding functionality is provided by Snippets and what you ask seems to be supported](https://github.com/facelessuser/pymdown-extensions/issues/1462). Please take this upstream, because we don't maintain Snippets here. This is Material for MkDocs. Thank you.

**Comment by mpusz** [comment]
Thanks!
