### ISSUE TITLE
Always load http://squidfunk.github.io over HTTPS

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#565]
Not too much of a big deal, but would be nice to see the site http://squidfunk.github.io always load over HTTPS. It's an option in the GitHub settings so should be easy to setup.

- Google now rank HTTPS sites higher as they are more trustworthy (http://googlewebmastercentral.blogspot.com/2014/08/https-as-ranking-signal.html)
- Some third-party HTTPS sites do not allow referring links to non-HTTPS sites to be tracked in Google Analytics. Using HTTPS can give more accurate analytics data.
- ISPs like Verizon and Comcast are now routinely injecting tracking material into their customers traffic 
 - using HTTPS protects visitors from being manipulated in this way. Also some airport and hotel wi-fi services add tracking and even adverts in to websites – but it’s impossible to do that with sites served over HTTPS
- Sites served over HTTPS look safer and more professional with the nice green padlock icon in the top URL bar.
- A growing number of web technologies and APIs require HTTPS, (maybe in a future update we could use Service Workers for improved performance and/or to work offline)
- Web browsers (Chrome and Firefox) are beginning to show non-HTTPS sites as non-secure. so they will appear less trustworthy.

**Comment by squidfunk** [comment]
Great idea, just set it to HTTPS and fixed any remaining errors.
