### ISSUE TITLE
Feature suggestion: if site_name empty use page.title

### ISSUE THREAD

**Issue by Yang09701194** [squidfunk/mkdocs-material#5661]
### Contribution guidelines
 I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree
### I want to suggest an idea and checked that ...
- [x]  ... to my best knowledge, my idea wouldn't break something for other users
- [x] ... the documentation does not mention anything about my idea
- [x]  ... there are no open or closed issues that are related to my idea

### Description

The [eclipse OpenJ9](https://www.eclipse.org/openj9/docs/) website home page `<title>` is empty, and [it use mkdocs](https://github.com/eclipse-openj9/openj9-docs), after some research,

![title](https://i.imgur.com/fEdGlX3.png)

I find that [mkdocs.yml](https://github.com/eclipse-openj9/openj9-docs/blob/master/mkdocs.yml) set `site_name: ' '`, 

first I test give the `site_name: 'OpenJ9'`, it looks not better, so I think the reason to set `site_name: ' '` is web looking better, but its `<title>` is empty, 
![site](https://i.imgur.com/zGIwX33.png)

so I find the template, it is using [mkdocs-material/material/base.html](https://github.com/squidfunk/mkdocs-material/blob/55fb2e335e04df5b206f2058ba4b706d930b496f/material/base.html#L33), after reading ` {% block htmltitle %}` section, I have a feature request that if `site_name` empty then use `page.title`, 

add this code:

```
{% elif page.is_homepage and (not config.site_name or config.site_name.isspace()) %}
        <title>{{ page.title | striptags }}1</title>
```

to the `{% block htmltitle %}` section, I have test this change locally, it would give `<title>About the docs</title> ` to the home page.  

another file [mkdocs-material/src/base.html](https://github.com/squidfunk/mkdocs-material/blob/55fb2e335e04df5b206f2058ba4b706d930b496f/src/base.html) has title section, I suggest it could also add this feature. after add:

```
{% block htmltitle %}
      {% if page.meta and page.meta.title %}
        <title>{{ page.meta.title }} - {{ config.site_name }}</title>
      {% elif page.title and not page.is_homepage %}
        <title>{{ page.title | striptags }} - {{ config.site_name }}</title>
      {% elif page.is_homepage and (not config.site_name or config.site_name.isspace()) %}
        <title>{{ page.title | striptags }}1</title>
      {% else %}
        <title>{{ config.site_name }} 123</title>
      {% endif %}
    {% endblock %}
```

**Comment by squidfunk** [comment]
Thanks for suggesting. `site_name` is a required field by MkDocs, and setting it to whitespace to somehow circumvent this behavior doesn't seem idiomatic to me. Thus, it's nothing we'd optimize for. However, as you have notived, you can easily override the [`htmltitle`](https://github.com/squidfunk/mkdocs-material/blob/55fb2e335e04df5b206f2058ba4b706d930b496f/src/base.html#L73-L82) block and add the functionality as a [customization](https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks) 😊
