### ISSUE TITLE
`og:image` custom social card tag not present in blogs with mkdocs-material-insiders

### ISSUE THREAD

**Issue by LandonTClipp** [squidfunk/mkdocs-material#5664]
### Bug description

When building documentation using mkdocs-material-insiders, custom social cards do not appear in the HTML inside of blog posts. When configured to use legacy social cards, the respective `og:image` HTML tags appear just fine.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Blog Support Just Landed](https://squidfunk.github.io/mkdocs-material/blog/2022/09/12/blog-support-just-landed/)
- [Custom Social Cards](https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/?h=social#customization)

### Reproduction

- [Repo with minimal reproduction](https://github.com/LandonTClipp/mkdocs-material-social-card-bug)
- [example.zip](https://github.com/LandonTClipp/mkdocs-material-social-card-bug/raw/main/example.zip)

### Steps to reproduce

1. Clone the above repo
2. Call `mkdocs serve` and navigate to http://127.0.0.1:8000/blog/2023/07/02/hello/
3. Inspect the HTML and search for the `og:image` tag
<img width="556" alt="Screenshot 2023-07-02 at 3 51 42 PM" src="https://github.com/squidfunk/mkdocs-material/assets/11232769/83e0d900-2c0b-4a8d-8541-a74861600697">

4. Change the `mkdocs.yml` configuration to revert to the legacy social cards
```yaml
site_name: Landon's Blog

theme:
  name: material
plugins:
- blog
- info
- social
nav:
  - index.md
  - Blog:
    - blog/index.md
```
5. Build the site again and search for the `og:image` element again. It shows up:
<img width="619" alt="Screenshot 2023-07-02 at 3 53 55 PM" src="https://github.com/squidfunk/mkdocs-material/assets/11232769/c1c18cf8-605f-42e8-ab87-399f9bb42be3">

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting! You need to set the tags in your custom layout template. [Just add the following to your layout](https://github.com/squidfunk/mkdocs-material-insiders/blob/22a4f4d03a7d044bccabf6812e3d2a0f6a4b111f/src/plugins/social/layouts/default.yml#L144-L161):

``` yaml
# Definitions
definitions:

  # Page title with site name
  - &page_title_with_site_name >-
    {%- if not page.is_homepage -%}
      {{ page.meta.get("title", page.title) }} - {{ config.site_name }}
    {%- else -%}
      {{ page.meta.get("title", page.title) }}
    {%- endif -%}

  # Page description
  - &page_description >-
    {{ page.meta.get("description", config.site_description) or "" }}

# Meta tags
tags:

  # Open Graph
  og:type: website
  og:title: *page_title_with_site_name
  og:description: *page_description
  og:image: "{{ image.url }}"
  og:image:type: "{{ image.type }}"
  og:image:width: "{{ image.width }}"
  og:image:height: "{{ image.height }}"
  og:url: "{{ page.canonical_url }}"

  # Twitter
  twitter:card: summary_large_image
  twitter.title: *page_title_with_site_name
  twitter:description: *page_description
  twitter:image: "{{ image.url }}"
```


The reason is that we try to keep things as flexible as possible, allowing to define additional meta tags. Although this can be resolved with customization, I'll leave this open as a change request, because it might be a good idea to set the defaults if no `tags` member is defined by the author.

That's actually not an error, but we need to adjust the documentation.

**Comment by squidfunk** [comment]
For now, we decided not to automatically populate those properties – it's not that trivial to do this correctly. However, 0bfa83c45 adds the necessary parts to the documentation.

**Comment by LandonTClipp** [comment]
Thanks Martin. A documentation update is probably all that's needed here from my perspective.

**Comment by squidfunk** [comment]
At least, yes, but maximum flexibility with maximum comfort is always the optimum we're trying to achieve 😅
