### ISSUE TITLE
Clicking content tab moves top of page to anchor

### ISSUE THREAD

**Issue by chipsenkbeil** [squidfunk/mkdocs-material#5674]
### Context

I'm using content tabs to house some text content. Some are within a grid, and one is on its own. Clicking on the tab results in me jumping to where the top of the browser page is the anchor. It seems like the Mkdocs Material website doesn't have this issue, so I'm trying to see what I have enabled (or not enabled) that's causing this issue. This happens with the Insider edition on the latest version, I believe.

### Bug description

https://github.com/squidfunk/mkdocs-material/assets/2481802/dca7173f-4c41-4de3-85d0-0b34a9a35ad9

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/grids/?h=grid
- https://squidfunk.github.io/mkdocs-material/reference/content-tabs/?h=content

### Reproduction

Removed plugins (minus info) and simplified extensions. Deleted all pages except for the page in question, which I made be `index.md`. 

[example.zip](https://github.com/squidfunk/mkdocs-material/files/11943978/example.zip)

### Steps to reproduce

1. Create a content tab
2. Click on one of the tabs

Seems to happen whether I use nice slugs or the default tabbed slug.

### Browser

Other

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for the excellent reproduction! It seems to be related to instant loading. If I remove `navigation.instant`, the issue goes aways. I'll look into it. In the meantime, you can disable `navigation.instant` to mitigate.

**Comment by squidfunk** [comment]
Should be fixed with [`32071053d`](https://github.com/squidfunk/mkdocs-material-insiders/commit/0a23a88415639c653abd577fa7a4f7433afad9e1).

**Comment by chipsenkbeil** [comment]
Just deployed and it's fixed just like you said! Thanks for the fast turnaround on this one 😄
