### ISSUE TITLE
How to annotate within an ordered list?

### ISSUE THREAD

**Issue by ccoenen** [squidfunk/mkdocs-material#5694]
### Description

With the release of 9.2.0 beta, I tried using the annotation feature, and I quite like it. I have configured it successfully and use it with great joy in regular text and within admonitions.

I have a few places, where I would like to add annotations within an ordered list, though, and that does not seem to work, currently. If there is any way to get this to work, that would be very helpful for me. Here is what I have tried:

```txt
how to bake as an ordered list:

1. get groceries
2. bake a cake
3. enjoy (1)
{ .annotate }

1. when possible
```

this will render as
![screenshot of the output and the developer tools](https://github.com/squidfunk/mkdocs-material/assets/124909/0779f637-51f2-4e57-9c4e-1d54df976af1)

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/annotations/

### Proposed change

If this is possible, I would value an example. If this is _not_ possible, maybe someone could point me towards a workaround?

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by ccoenen** [comment]
I should perhaps also mention that I tried giving it a different (higher) number, and I tried indenting both the `{ .annotate }` and the annotation itself to various levels, both of which did not give me a better result (it only had slight differences in where that `.annotate` class ended up.

**Comment by squidfunk** [comment]
[This is a limitation of Python Markdown](https://python-markdown.github.io/extensions/attr_list/#limitations) – ordered lists cannot be annotated with the Attribute Lists extension. However, [there's a simple workaround](https://squidfunk.github.io/mkdocs-material/reference/annotations/#in-everything-else), as mentioned in our documentation:

``` yaml
<div class="annotate" markdown>

> Lorem ipsum dolor sit amet, (1) consectetur adipiscing elit.

</div>

1.  :man_raising_hand: I'm an annotation!
```

You can use arbitrary Markdown and HTML inside the `div`.

**Comment by ccoenen** [comment]
Can confirm! Thank you for pointing me in the right direction. Somehow I did not think to apply "in everything else" to my situation :-)

```markdown
how to bake as an ordered list:

<div class="annotate" markdown>

1. get groceries
2. bake a cake
3. enjoy (1)

</div>

1. when possible
```

![rendered html from the above markdown snippet](https://github.com/squidfunk/mkdocs-material/assets/124909/7ae53c58-3c3f-4ceb-bca8-37c25809cd02)



works as advertised, Thank you!

**Comment by FredZinelli** [comment]
Sorry to dig up the topic, but for the record / if that may help someone else in the future:

This can be achieved in a more "localized" way, as in, within the item itself instead of wrapping the entire list or even on a single word, using the following : 

```
1. get groceries
2. bake cake
3. <span class="annotate">enjoy (1)</span><ol><li>when possible</li></ol>
```

This allows to avoid using md_in_html logic on the outer list (which can become a nightmare very quickly when the markdown content is relying on indentations and empty lines).

@squidfunk Might be worth an addition/modification in [material's docs](https://squidfunk.github.io/mkdocs-material/reference/annotations/#in-everything-else)?

**Comment by FredZinelli** [comment]
Sounds good, yes. But footnotes do not provide the same UX, since they involve traveling in the page (I personally like annotations over footnotes for that reason, actually). So it would be cool to keep the functionnality.

**Comment by squidfunk** [comment]
If you enable `footnote.tooltips`, you have the exact same UX. You can test this in our documentation:
https://squidfunk.github.io/mkdocs-material/getting-started/

<img width="733" alt="Bildschirm­foto 2024-08-24 um 11 38 04" src="https://github.com/user-attachments/assets/79e73da5-6b67-4678-8e1a-0d1688c003a3">

**Comment by feasgal** [comment]
> Thanks for noting. In fact, we're rather considering deprecating annotations (not code annotations) once [footnote tooltips](https://squidfunk.github.io/mkdocs-material/reference/footnotes/#footnote-tooltips) are part of the community edition, since they can be used without adding another language extension. Annotations work particularly well in code blocks, but adding this functionality to free form content was likely not the best idea 🤷‍♂️

It looks like footnote tooltips are [still a couple of funding goals away](https://squidfunk.github.io/mkdocs-material/insiders/benefits/#20000-jalapeno). Are you still considering deprecating non-code annotations when they become available to everyone? Should those of us who are Insiders be considering switching over when we have a chance?

(sorry for the thread necromancy)

**Comment by squidfunk** [comment]
Yes, annotations are non-standard Markdown, and will be deprecated and eventually removed, so better use footnote tooltips, since footnotes are widely supported ☺️
