### ISSUE TITLE
Schema for optimize plugin is missing

### ISSUE THREAD

**Issue by aceat64** [squidfunk/mkdocs-material#5705]
### Description

The schema for `mkdocs.yml` does not have an entry for the optimize plugin. This results in a linting error, as `optimize` is considered an invalid value for the `plugins` list.

### Related links

- https://squidfunk.github.io/mkdocs-material/schema.json
- https://squidfunk.github.io/mkdocs-material/creating-your-site/#minimal-configuration

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Oops, good catch, that's indeed still missing! Same goes for the built-in typeset plugin.

**Comment by squidfunk** [comment]
Added in c2e55585f. Thanks again for reporting!
