### ISSUE TITLE
Search not finding terms with . in front

### ISSUE THREAD

**Issue by emily-gel** [squidfunk/mkdocs-material#5706]
### Context

Our website: https://re-docs.genomicsengland.co.uk/

### Bug description

We've noticed a strange issue on search. We were trying to find the term `libpath` in the documentation, which found no results, however this term is in the docs, but with a dot preceding it as `.libPath`. Adding the dot and searching for `.libpath` did find the page.

![Screenshot 2023-07-13 at 09 56 37](https://github.com/squidfunk/mkdocs-material/assets/95911323/57cc09e3-2cfa-4fea-9ea6-866232d5d03d)
![Screenshot 2023-07-13 at 09 56 26](https://github.com/squidfunk/mkdocs-material/assets/95911323/7f7f138d-80bc-40a2-ac3b-d3179a046316)

I would expect the search for `libpath` to work since this term is in the page.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

$mycomputer tre-docs % python3 -m mkdocs serve
INFO     -  Building documentation...
ERROR    -  Config value: 'plugins'. Error: The "info" plugin is not installed
Aborted with 1 Configuration Errors!
$mycomputer tre-docs % 

### Steps to reproduce

1. Go to https://re-docs.genomicsengland.co.uk/
2. Search for `libpath` - no search results
3. Search for `.libpath` - find https://re-docs.genomicsengland.co.uk/r_packages/#3-mounting-library-locations-to-libpaths-then-loading-packages-without-specifying-libloc

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is not a bug, but a result of how you configured Material for MkDocs. Additionally, [you did not provide a minimal reproduction as requested](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#reproduction), so we can only guess what's wrong. My guess is, that you need to add `.` to your [search `separator`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#+search.separator). Something like:

```
plugins:
  - search:
      separator: '[\s\-\.]+'
```

If you're still experiencing problems, please create a discussion. This is not a bug, everything is working as intended.
