### ISSUE TITLE
Blogging plugin gives wrong link in table of contents

### ISSUE THREAD

**Issue by jiegec** [squidfunk/mkdocs-material#5714]
### Bug description

I am trying the latest blogging plugin in mkdocs-material 9.2.0b0, and encountered the following bug: in the main page, where all blog posts are listed, the table of content has links to each post:

```html
        <li class="md-nav__item">
  <a href="#apple-m1-gentooprefix" class="md-nav__link">
    在 Apple M1 上试用 Gentoo/Prefix
  </a>

</li>

        <li class="md-nav__item">
  <a href="#_1" class="md-nav__link">
    生成树协议
  </a>

</li>

        <li class="md-nav__item">
  <a href="#_1" class="md-nav__link">
    链接器的工作原理
  </a>

</li>


```

The links are correct if there are English characters in blog title, but otherwise wrong if there aren't: you can see there are two `#_1` links to different posts.

The correct links should be `#_1`, `#_2`, etc.

The problem can be found in [my blogging site](https://jia.je/#_1).

### Related links

- [My blogging site](https://jia.je/#_1)

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/12060148/example.zip)

### Steps to reproduce

1. mkdocs build
2. View the generated html

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. I'm pretty sure this issue can be mitigated by using a different slug function, i.e., one that is Unicode aware. Could you please try to configure the `toc` extension's [`slugify`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#unicode) setting accordingly?

``` yaml
markdown_extensions:
  - toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```

**Comment by jiegec** [comment]
Thanks @squidfunk, the workaround fixes the issue.
