### ISSUE TITLE
Some settings has been broken after updating

### ISSUE THREAD

**Issue by AndreWin** [squidfunk/mkdocs-material#573]
Hello!

Just updated mkdocs to 0.17.1 and mkdocs-material to 2.0.4.

First, I got message when start `mkdocs serve`:

```
WARNING -  Config value: 'theme_dir'. Warning: The configuration option {0} has been deprecated and will be removed in a future release of MkDocs.
```

Also, it seems to me that settings `extra > paletter > primary`, `extra > paletter > accent` and `extra > logo > icon` are ignoring by mkdocs now. I setted `primary: 'Green'` but see default Indigo color. Also I see default logo.

Best regards,
Andrey.

**Comment by martinbira** [comment]
Check the release notes for 2.0.4 and 0.17.1, several things have changed among those you have noted.
http://www.mkdocs.org/user-guide/custom-themes/
https://squidfunk.github.io/mkdocs-material/release-notes/
https://squidfunk.github.io/mkdocs-material/getting-started/

**Comment by AndreWin** [comment]
Thanks. I fixed my problems.
