### ISSUE TITLE
Add information about Dockerfile for using plugins with Docker

### ISSUE THREAD

**Issue by tcrapts** [squidfunk/mkdocs-material#5738]
### Description

The docs mention that you can use plugins by simply creating a `user-requirements.txt` and then run `docker build -t squidfunk/mkdocs-material .`. However, this returns an error that a Dockerfile can't be found, which is true, you need at least a Dockerfile to build an image. However, the docs don't mention this.

### Related links

-https://squidfunk.github.io/mkdocs-material/getting-started/?h=docker#with-docker

### Proposed change

Include information about the required Dockerfile.

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for suggesting. Yes, we could maybe make it a little more clear that a `Dockerfile` is necessary. @hellt was the last one to change it to allow for user requirements. @hellt, could you please add a little more instructions that make it clearer that the user has to create a `Dockerfile` and/or has to use the one from the repository? Those instructions were there before we merged your PR, and there seem to be more questions now. Thank you!

**Comment by hellt** [comment]
@squidfunk sorry, I am not sure I get it. The current doc section states that a user must be in the repository's root:

>  If the plugin you want to use is not included, create a user-requirements.txt file in the repository root with the packages you want to install additionally...

https://squidfunk.github.io/mkdocs-material/getting-started/?h=docker#with-docker

**Comment by tcrapts** [comment]
@hellt I understand now. I mistakenly assumed that 'the repository root' refers to *your own* repository. I would suggest to explictly mention that it must be the root of the mkdocs-material repository.

**Comment by squidfunk** [comment]
Yes, but as I understand, it might be better to recommend that the user creates his own `Dockerfile` and extends from Material's image. Then there's no necessity to fork or clone the repository – or am I mistaken? @hellt, would you be open to update the guide to reflect that?

**Comment by hellt** [comment]
If users would be basing off from mkdocs-material image then they would need to copy paste the logic that installs plugins from the user-reqs file, as it won't happen automatically. 
So I'd say cloning the repo is the way and applicable both for public and insiders alike

**Comment by squidfunk** [comment]
I'm not sure it then if it's the thing we should recommend on the documentation, because now cloning is mandatory. I'm thinking of removing the user requirements again, adding that step to the example Dockerfile that is based off the official one. Basically something like:

``` Dockerfile
FROM squidfunk/mkdocs-material
ADD user-requirements.txt
RUN pip install -r user-requirements.txt
```

**Comment by hellt** [comment]
I'm fine with that for the public image. For insiders though I think having it in the insiders repo Dockerfile is the only straightforward way

**Comment by squidfunk** [comment]
I've tried to clarify the situation a bit in 04b8d89ba, but I'm still not 100% happy with it. We're currently revamping our documentation, so we'll tackle this again later, but for the time being we can consider it resolved.

**Comment by hellt** [comment]
This addition looks very clear to me. Thanks @squidfunk
