### ISSUE TITLE
Page Source Renders Incorrectly

### ISSUE THREAD

**Issue by joshrhoades** [squidfunk/mkdocs-material#574]
## Description

When setting a page source, the filename gets split up by character and renders out as multiple page sources. For example, a filename of `overview.md` renders out as this:

![screen shot 2017-11-06 at 10 44 36](https://user-images.githubusercontent.com/488824/32458028-dde61310-c2df-11e7-9507-d742867d1d08.png)

This only happens during the build step, not when running locally.

The pagemeta source is simply:
```
path: docs/demos/app/feature
source: overview.md
```

And this works perfectly fine locally, it only occurs during our CI build process which deploys to CDN. I am checking the machine and version configurations there, as we cannot reproduce this locally, so its the first thing to rule out.

However, I am curious if anyone has seen anything like this before?

**Actually**, just updated to the latest mkdocs locally and now we can reproduce the issue. This seems to be some collision between latest mkdocs and what Material is doing.

### Expected behavior

Page source is rendered properly, such as:
![screen shot 2017-11-06 at 10 48 52](https://user-images.githubusercontent.com/488824/32458103-1beb28d0-c2e0-11e7-82cf-22e15f5bd457.png)

### Actual behavior

The value for `source` is rendered for each individual character in the filename and extension, even the `.`, so there is one `source` `a` tag rendered per each char in the filename.

### Steps to reproduce the bug

1. Build the site.

### Package versions

* Python: 3.6.3
* MkDocs: 0.17.1
* Material: 2.0.1

### System information

* OS: Windows & OSX
* Browser: Not Applicable, occurs on all browsers (is not a render issue)

**Comment by makshh** [comment]
It was fixed in #557 

You should update MkDocs Material to the latest version.

**Comment by joshrhoades** [comment]
Updating to latest version of material (2.0.4) and there is no issue using mkdocs 0.17.1. As soon as I upgrade to mkdocs 2, it goes bad.

**Comment by makshh** [comment]
I think there is no MkDocs 2, latest version of MkDocs is 0.17.1.

**Comment by joshrhoades** [comment]
Weird, somehow our CI machine is getting some weird stuff and not locking to a specific version, it is pulling material 2.0.1 somehow though I can't get to that version locally. Looks like we need to dig in more since this should have been fixed.

Thanks for the info.
