### ISSUE TITLE
The guide to setup the feedback visualization in GA is missing something

### ISSUE THREAD

**Issue by tmarkovski** [squidfunk/mkdocs-material#5740]
### Description

I'm going step by step to setup the Google Analytics feedback for my site, but the final result is not what the documentation show. Here's what my report looks like:

<img width="543" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/1280118/20a5afc7-ae66-4ca5-b9b0-5c6c342685f5">

The docs shows a screenshot with Avg Value, but I'm not sure how to get to that.
Our site is at https://docs.trinsic.id/.

### Related links

- [Was this page helpful?](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/?h=feedb#was-this-page-helpful)
- [Our docs](https://docs.trinsic.id)
- [Our repo](https://github.com/trinsic-id/sdk)

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by tmarkovski** [comment]
Thank you. If I do find a way, I'll submit a PR, but if @garrettheel knows how to do this, I'd be happy to take advice as I'm not too savvy with GA.

**Comment by garrettheel** [comment]
I don't have access to the GA property that I had originally set this up on, so not sure I can help you much here. It's possible that some things have changed since I originally wrote this guide; I would see if you can tweak other options on the explore view to somehow produce an average rating per page.

**Comment by squidfunk** [comment]
Okay, so my research tells me: __it's currently not possible__. [Google Analytics 4 just doesn't have custom calculated metrics](https://www.benluong.com/calculated-metrics-in-ga4/). It has calculated metrics (average session length) and custom metrics, but no combination of both, i.e., you can't define expressisons to deduce a new metric from. That is actually super sad, as it removes part of the usefulness of the feedback widget. If somebody has an idea how to overcome this, we're more than happy to add it to our docs, but for the time being, we can only cry at Google taking away features, again. Documentation updated in 2bcc243df.
