### ISSUE TITLE
Navigation: instant loading breaks keyboard navigation

### ISSUE THREAD

**Issue by filips123** [squidfunk/mkdocs-material#5742]
### Bug description

When `navigation.instant` is enabled, triggering the navigation with keyboard (with `p`, `n`, `,`, `.` keys) still reloads the page, This can be seen as certain parts of the UI (search, theme selection, repository information) blink as the page gets reloaded.

### Related links

- [Instant loading documentation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading)
- [Code that handles keyboard navigation](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/javascripts/bundle.ts#L169-L198)
- [Code that handles keyboard navigation](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/javascripts/browser/location/_/index.ts#L48-L50)

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/12134467/example.zip)

### Steps to reproduce

See that instant navigation with footer links works properly:

1. Click a few times on next and previous links in the footer.
2. Instant navigation should work, no UI elements will blink.

See that instant navigation with keyboard does not work:

1. Press `,` and `.` a few times to navigate to next and previous pages.
2. Instant navigation will not work, UI elements like search and repo information will "blink".

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by filips123** [comment]
There is another related problem with instant loading and keyboard navigation that I found, and I don't know if it's also addressed in that PR. After navigating through the side by clicking links with instant loading enabled, keyboard navigation will break and redirect you to 404 page.

Steps to reproduce:

1. Open the home page of my example docs.
2. In the sidebar, click on FAQ and then Known Problems.
3. Try to navigate to the previous page with `P` key. Nothing will happen.
4. Try to navigate to the next page with `N` key. You will be redirected to an invalid path (`/resources/known-problems/resources/faq/`).

**Comment by squidfunk** [comment]
Yes, it's also related to instant loading and will be addressed in the PR. Note that the PR is not ready yet.

**Comment by squidfunk** [comment]
We'll leave it open until released.
