### ISSUE TITLE
Document cookie consent behavior

### ISSUE THREAD

**Issue by alexvoss** [squidfunk/mkdocs-material#5746]
### Description

The documentation currently does not say what happens when the user selects their cookie preferences. I was looking for a way to get a call-back in JavaScript to set a cookie upon receiving consent but could not find anything. It seem that when the user submits the consent form this causes a page reload? 

So, the correct way of setting/updating a cookie would be to check for the consent information in local storage on page load? Is there a hook that I should be using for this? If so, it would be good to have a note on this in the description of how to handle custom cookies and perhaps a generic description on how to best run code on page load in the description for additional JS.

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#custom-cookies
- https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript

### Proposed change

Change the wording to make clear when and how the code provided should be run.

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, the page is reloaded, because the cookie consent logic is outside of the application, and it would be too complicated to propagate everything again downstream, so a reload is the simplest and actually most stable solution concerning third-party extension. Additionally, the section on [custom cookies](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#custom-cookies) which you already linked contains an example how to use custom cookies:

``` js
var consent = __md_get("__consent")
if (consent && consent.custom) {
  /* The user accepted the cookie */
}
```

I'm not sure what's missing 😅 Should we really add a note that the page is reloaded? It's the first time this question is asked and many people already included custom cookies and integrations, so I'm not sure we need it 😊

**Comment by alexvoss** [comment]
Leave it to me to be the dumb one ;o) Seriously, it is not obvious from the documentation that this is how it works and I think documenting it costs about one sentence? Someone with a keen eye will spot the reload but thought of the question over lunch and immediately started looking for a call-back mechanism before looking at the behavior. Then turned on the developer tools to see the actual code that forces the reload. I have no quarrel with the implementation but a few words will save idiots like me a run around the block.

Here is a concrete suggestion (change in bold): 

> If you've customized the [cookie consent](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#cookie-consent) and added a custom cookie, the user will be prompted to accept your custom cookie. **Once they save their selection, the page will reload and you can use [additional JavaScript](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) to check whether they accepted the cookie**:

**Comment by squidfunk** [comment]
Good suggestion, would you like to create a PR?

**Comment by squidfunk** [comment]
I was faster – I updated the documentation on [custom cookies](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#custom-cookies) in b72adf300 with your suggestions and a few minor changes, plus an explanation why we reload the site. Tagged you as a co-author.

<img width="640" alt="Bildschirmfoto 2023-07-24 um 13 01 24" src="https://github.com/squidfunk/mkdocs-material/assets/932156/7d48b3bd-645f-439e-b83a-17822041db64">

**Comment by alexvoss** [comment]
Thanks for this. Next time I will try and be faster. Am always overthinking things and wondering what else I could contribute and whether it is really work going through the workflow of a pull request. I would certainly not want to leave a fork lying around that becomes more and more out of date just because I had a small change to contribute.

**Comment by squidfunk** [comment]
No worries! We try to make small changes like those as fast as possible to keep the number of open issues and change requests down, as it's far easier to navigate than hundreds of open issues 😊
