### ISSUE TITLE
404 page not built anymore?

### ISSUE THREAD

**Issue by kcgthb** [squidfunk/mkdocs-material#575]
## Description

It looks like the 404 page template doesn't work anymore.

### Expected behavior

Get the templated 404 page when accessing a non-existing URL.

### Actual behavior

Get a simple `404: Not Found` text, or a redirection to the generic GH pages 404 page.

### Steps to reproduce the bug

Go to https://squidfunk.github.io/mkdocs-material/foo :)

### Package versions

* Python: `python --version`: 3.4.5
* MkDocs: `mkdocs --version`: 0.17.1
* Material: `pip show mkdocs-material | grep -E ^Version`: 2.0.1

### Project configuration

not relevant.

### System information

* OS: Linux
* Browser: Chrome

**Comment by makshh** [comment]
In order to have custom 404 page on GitHub Pages you have to:

> create a HTML file named 404.html or create a new Markdown file named 404.md at the root level of your GitHub Pages repository.

[Source](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/)

There is no such file in `gh-pages` in this repository.

**Comment by squidfunk** [comment]
There's in fact a config option that was forgotten to be included in the `mkdocs.yml` of Material. 404 pages work for all projects using the theme, e.g.:
http://facelessuser.github.io/BracketHighlighter/foo

I will provide a fix, so it will also work in the official docs.

**Comment by squidfunk** [comment]
Fixed in #576
