### ISSUE TITLE
Copy to clipboard button is doubled when using CodeHilite with line numbers

### ISSUE THREAD

**Issue by makshh** [squidfunk/mkdocs-material#577]
## Description

Copy to clipboard button is doubled when using CodeHilite with line numbers. This is a problem when using code block inside details (second button is visible on top of `summary` open/close arrow). This button is not visible when you don't use line numbers because it's under the main header.

### Expected behavior

One copy to clipboard button per code block

### Actual behavior

Two copy to clipboard buttons per code block

### Steps to reproduce the bug

1. Add CodeHilite extension to your config and set `linenums` to true.
2. Create code block.

### Package versions

* MkDocs: 0.17.1
* Material: 2.0.4

### Project configuration

Irrelevant

### System information

Irrelevant

![screenshot at nov 07 23-57-11](https://user-images.githubusercontent.com/5025950/32522420-7ec7ddc6-c417-11e7-8835-dcd16986ebd8.png)
![screenshot at nov 07 23-57-52](https://user-images.githubusercontent.com/5025950/32522421-7fab0db2-c417-11e7-8267-1171f9965f09.png)

**Comment by facelessuser** [comment]
Probably just needs a better query target when inserting.  I think most people don't use line numbers, so it probably just got missed.  The format is very different, and it looks like the div for linenos and for code both get targeted.

**Comment by makshh** [comment]
Exactly.

`div > pre` targets `.linenums > pre` and that's why.

`div:not(.linenodiv) > pre` selector should do the trick

**Comment by squidfunk** [comment]
Fixed in #580, now targetted through `.codehilite > pre` which is more stable and more restrictive than `div > pre`.

**Comment by squidfunk** [comment]
Released as part of 2.1.0.
