### ISSUE TITLE
Info plugin stops build when latest Insiders version doesn’t match latest public version

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#5773]
### Context

https://github.com/squidfunk/mkdocs-material/issues/5772#issuecomment-1655152517

### Bug description

The info plugin for reproducing a bug doesn’t work when the Insiders repo release is behind the public release version, unless it’s configured to ignore errors.

```
plugins:
  info:
    archive_stop_on_violation: false
```

I suppose this could be fixed by checking the Insiders build release separately, but it could also probably be fixed by marking the latest beta builds as pre-releases on GitHub which might make more sense, unless this lag with Insiders releases happens more frequently than just with the current beta and I haven’t noticed.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

n/a - build fails. 

### Steps to reproduce

1. Enable info plugin on current Insiders build.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. So what the info plugin does is that it checks the latest release and compares it to the installed version. Obviously, we can't do this for Insiders, since it's a private repository. Since we always merge community patches downstream, this is only relevant for a very small time window, except for when we do a pre-release like we currently do. Thus, what we can do is to exempt the check for pre-releases.

**Comment by squidfunk** [comment]
Fixed in [`b70c25d87`](https://github.com/squidfunk/mkdocs-material-insiders/commit/b70c25d87fbb1ed560f218f7a8da76c40bc15a84). As noted in https://github.com/squidfunk/mkdocs-material/issues/5773#issuecomment-1655869773, we removed the check when the community edition is in beta.

**Comment by squidfunk** [comment]
Released as part of [insiders-4.38.1](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.38.1).
