### ISSUE TITLE
npm install gets error Invalid name: "@babel/types"

### ISSUE THREAD

**Issue by paulmason** [squidfunk/mkdocs-material#579]
After running npm install I get:

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5

npm ERR! Invalid name: "@babel/types"

Any ideas? Thanks!

**Comment by squidfunk** [comment]
Did you do this after a fresh clone?

**Comment by squidfunk** [comment]
Also, I just removed my `node_modules` folder and did a fresh `npm install` and I don't get this error.

**Comment by paulmason** [comment]
Thanks, installing the dependencies with `Yarn` solved it!

**Comment by squidfunk** [comment]
Okay, maybe it was just some temporary hiccup.
