### ISSUE TITLE
JetBrains Mono font not in mkdocs.yml schema

### ISSUE THREAD

**Issue by ThatOtherAndrew** [squidfunk/mkdocs-material#5798]
### Bug description

According to the documentation, the `theme.font.code` key [can be set to any valid Google Font](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#monospaced-font) - however, my IDE shows a warning that the `JetBrains Mono` font is an invalid value. After some digging around in the schema, I found [fonts.json](https://squidfunk.github.io/mkdocs-material/schema/assets/fonts.json) ([repo link](https://github.com/squidfunk/mkdocs-material/blob/60325df375901e49e6a302029f9bb3da3f9b6321/docs/schema/assets/fonts.json)), which appears to be very outdated with the last change being 2 years ago. I'm not too familiar with JSON schemas, but my naive solution would be to either update the fonts however they were sourced or add some sort of "wildcard option" which allows all strings if possible.

### Related links

- https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#monospaced-font
- https://squidfunk.github.io/mkdocs-material/schema/assets/fonts.json

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/12255489/example.zip)

### Steps to reproduce

1. Open `mkdocs.yml` in an IDE with YAML schema validation, or other validator (I am using PyCharm Professional 2023.2 but I believe this shouldn't matter)
2. Observe the warning at `theme.font.code`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Indeed, some font files are not present. We can't allow `*`, since this will break the validation altogether. The `fonts.json` file is generated from a package called [`google-fonts-complete`](https://github.com/jonathantneal/google-fonts-complete). Please report this upstream to the maintainer of the package. If you happen to know a better JavaScript package or method to obtain an up to date list of Google Fonts, please submit a PR or create a change request 😊

**Comment by ThatOtherAndrew** [comment]
Using the tool linked, I have been able to successfully generate a JSON file which contains the missing font, as well as many other extra fonts - attached below. I'm not entirely certain of the method used by your project for generating the file, but to me the method / upstream package looks valid - just that the generated file seems to be outdated.

[google-fonts.zip](https://github.com/squidfunk/mkdocs-material/files/12265251/google-fonts.zip)

**Comment by squidfunk** [comment]
Could you maybe ask the author to trigger a new release?

**Comment by ThatOtherAndrew** [comment]
It seems pushbroomsweep has already tried asking 4 months ago (https://github.com/jonathantneal/google-fonts-complete/issues/30) and got no response. Looks like the project has gone stale, with the last commit/activity being 2 years ago - seems like the only ways to solve this are to manually update the file or fork the upstream repo, unfortunately.

**Comment by squidfunk** [comment]
Thanks for checking. How long did it take to generate the fonts index when you ran it locally?

**Comment by ThatOtherAndrew** [comment]
I've just timed a run on my home internet connection, and it took a rather lethargic 9 minutes 41 seconds.

**Comment by squidfunk** [comment]
Meh, okay, we'd need to cache the results then. Would you be up to creating a PR on our repository, adding support for it? It seems that the npm package includes the scripts, which we'd just need to run as part of our build. We'd need to figure out a way to do this periodically, but not on every build, because 9min is not an acceptable build time. We could then update the `fonts.json` in our schema from time to time.

**Comment by ThatOtherAndrew** [comment]
Hmm, I see. I unfortunately barely know JS, so I'm not entirely sure how I'd approach this, but I may be able to figure something out. I was considering an approach with GitHub Actions and its cache feature, but I'm not sure how that'd integrate with the current build script.

May I ask what the relevance of [/docs/schema/assets/fonts.json](https://github.com/squidfunk/mkdocs-material/blob/master/docs/schema/assets/fonts.json) is? I'm not really understanding what the file is doing if it's dynamically generated each build.

**Comment by squidfunk** [comment]
> May I ask what the relevance of [/docs/schema/assets/fonts.json](https://github.com/squidfunk/mkdocs-material/blob/master/docs/schema/assets/fonts.json) is? I'm not really understanding what the file is doing if it's dynamically generated each build.

It provides [auto-complete functionality in `mkdocs.yml`](https://squidfunk.github.io/mkdocs-material/creating-your-site/#minimal-configuration), helping to catch errors early.

**Comment by ThatOtherAndrew** [comment]
What I meant was, why is the file present in the repository if the [/tools/build/index.ts](https://github.com/squidfunk/mkdocs-material/blob/60325df375901e49e6a302029f9bb3da3f9b6321/tools/build/index.ts) script appears to [generate the file on each build](https://github.com/squidfunk/mkdocs-material/blob/60325df375901e49e6a302029f9bb3da3f9b6321/tools/build/index.ts#L336)? There's probably something obvious I'm missing here, but looking at the commit history for the file, it appears to have only ever been edited manually.

**Comment by squidfunk** [comment]
Because we want to [deploy the theme without building it](https://github.com/squidfunk/mkdocs-material/blob/master/.github/workflows/documentation.yml) every time, and the `schema/*.json` files are part of our documentation. Otherwise we'd need to build the theme every time in CI before deploying documentation, or cache a single file around a bunch of files that should not be cached. That was the reason for that decision.

**Comment by ThatOtherAndrew** [comment]
Would an approach where a weekly/fortnightly GitHub Actions workflow updates the `fonts.json` file be acceptable? The TS build script could then directly use the file from the repository instead of generating the fonts file at build time.

**Comment by squidfunk** [comment]
Sounds legit. We could commit the generated file to the repository and then the schema would be updated because a new documentation build would be triggered. If you can cobble something together, I'm happy to review it as part of a PR. We should then also remove the logic from the build script that overrides the file.

**Comment by ThatOtherAndrew** [comment]
After looking into this a little further, I've come across [this API endpoint](https://developers.google.com/apis-explorer/?hl=en_US#p/webfonts/v1/webfonts.webfonts.list?fields=items(category%252Cfamily%252ClastModified%252Csubsets%252Cvariants%252Cversion)&_h=3&). Could you please check whether it contains all the info necessary for our purposes? If so, the whole problem with a 10min build time would be avoided altogether as it's a single API request instead of one request per font.

The catch is that it requires an API key - but that can be obtained for free and added as a GH Actions secret.

**Comment by squidfunk** [comment]
> The catch is that it requires an API key - but that can be obtained for free and added as a GH Actions secret.

That would means that users that fork the theme will not be able to build the list.

**Comment by ThatOtherAndrew** [comment]
> That would means that users that fork the theme will not be able to build the list.

Unfortunately, the API key is required either way for building the list. However, we can [skip the step in the build](https://github.com/actions/runner/issues/953) if the API key is missing and have it fallback to the last generated copy in the repository, to make it optional.

**Comment by squidfunk** [comment]
Hmm, okay, could you draft up a PR, so we have something to discuss? We could also add a [custom hook](https://github.com/squidfunk/mkdocs-material/tree/master/src/.overrides/hooks) (Python) that we only use for our own theme/build. The hook could write data to the `.cache` directory, and update the files if they're older than a week, or so.

> Could you please check whether it contains all the info necessary for our purposes?

Looks good – we currently only use the name of the font.

**Comment by squidfunk** [comment]
@ThatOtherAndrew did you make any progress? Now, `google-fonts-complete` has a CVE, as it depends on an old version of `postcss` and it doesn't look like it's going to be updated anytime soon. For that reason, would love to switch to an approach that does not depend on `postcss`.

**Comment by alexvoss** [comment]
Would it be conceivable to get the data at [its source](https://github.com/google/fonts) rather than through the API?

**Comment by squidfunk** [comment]
Yes, that's what we should do, but you'll need an API key for that, as the prior research suggested. Currently, we cannot budget the time to implement this on our side, given what we already have on our plate, but we're happy to collaborate on a PR that adds this functionality to the project. It should be part of the build tools.

**Comment by ThatOtherAndrew** [comment]
> @ThatOtherAndrew did you make any progress? Now, `google-fonts-complete` has a CVE, as it depends on an old version of `postcss` and it doesn't look like it's going to be updated anytime soon. For that reason, would love to switch to an approach that does not depend on `postcss`.

I'm really sorry, this issue has been left stale on my end. I'm currently going through some major exams and don't think I'd have the time to push this through at the moment.

**Comment by squidfunk** [comment]
No worries, all the best with your exams!

**Comment by ThatOtherAndrew** [comment]
I've just received news that `google-fonts-complete` has been updated to 2.2.3, which now contains a pregenerated file of up-to-date fonts. Hopefully just a version bump should do the trick!

**Comment by squidfunk** [comment]
Sadly, it hasn't been released on npm (none of the last versions), but I think we can change the source to install from GitHub. Should be fixed with 565a5e804. Almost 500 additional fonts have been added, including (drumroll...):

<img width="450" alt="Bildschirm­foto 2023-10-25 um 17 56 25" src="https://github.com/squidfunk/mkdocs-material/assets/932156/2ba369f6-e835-4e9a-8321-ed4ec6326e71">

**Comment by rajdee** [comment]
@squidfunk  I updated the version on npm

**Comment by squidfunk** [comment]
Awesome! Are versions now published automatically? There have been releases in the last years but none was published on npm. If it's not automatic, we probably better stay on the GitHub repository.

**Comment by rajdee** [comment]
No, packages are published to the npm manually. It's too difficult to do this often because Google blocks requests if you do it without delay.

**Comment by squidfunk** [comment]
I'm not sure I understand, because if the generated font metadata is part of the repository, it's only one `npm publish` away from pushing this to the registry, but I'm probably not familiar enough with your process. We keep the git repo for now.

**Comment by rajdee** [comment]
> I'm not sure I understand, because if the generated font metadata is part of the repository, it's only one `npm publish` away from pushing this to the registry, but I'm probably not familiar enough with your process. We keep the git repo for now.

No, publishing the package is not a problem.  I meant that it's difficult to generate a list often
