### ISSUE TITLE
Mermaid: allow customizing sequence diagram notes node style

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#5824]
### Context

The color of Mermaid sequence diagram notes looks a bit off IMO (see, e.g., https://squidfunk.github.io/mkdocs-material/reference/diagrams/#using-sequence-diagrams), at least not as nicely integrated with the rest of the theme colors.

### Description

[`mkdocs-material` overrides some Mermaid colors with own CSS variables](https://github.com/squidfunk/mkdocs-material/blob/9.1.21/src/assets/javascripts/components/content/code/mermaid/index.css) but not the "note" node. How about introducing new CSS variables, e.g. `--md-mermaid-note-bg-color` as the fill color and `--md-mermaid-note-fg-color` as the stroke color ([consistent with existing naming](https://github.com/squidfunk/mkdocs-material/blob/9.1.21/src/assets/javascripts/components/content/code/mermaid/index.css#L33-L34)), and add an override for Mermaid's `note` CSS class? The default colors could be based on the [info admonition color](https://github.com/squidfunk/mkdocs-material/blob/9.1.21/src/assets/stylesheets/main/extensions/markdown/_admonition.scss#L32).

There exists some [customization for note _text_](https://github.com/squidfunk/mkdocs-material/blob/9.1.21/src/assets/javascripts/components/content/code/mermaid/index.css#L359-L368), so perhaps not customizing the note rect itself was an oversight.

### Related links

- [Using sequence diagrams](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#using-sequence-diagrams)

### Use Cases

Having a nicely integrated Mermaid diagram makes documentation more pleasant to read. It's mostly good already, but sequence diagram notes look a bit off.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Yes, we can certainly make Mermaid diagrams more configurable in the future 😊

**Comment by nejch** [comment]
@squidfunk awesome! Would you accept a little PR for this? I think even the default schemes could benefit from this, see the current demo in slate:

![image](https://github.com/squidfunk/mkdocs-material/assets/16777978/832db052-056b-4883-b371-1d3501459dc0)

**Comment by squidfunk** [comment]
Yes, but we should actually add an additional layer of abstraction for each node in each diagram type, so that you can comfortable overwrite it with CSS. If you would like to work on this, a PR would be amazing. We could start with the sequence diagram and after then translate the solution over to the other types 😊

**Comment by nejch** [comment]
> Yes, but we should actually add an additional layer of abstraction for each component in each diagram type, so that you can comfortable overwrite it with CSS. If you would like to work on this, a PR would be amazing. We could start with the sequence diagram and after then translate the solution over to the other types blush

Thanks @squidfunk! Just to clarify, do you mean simply in the color variables, e.g `--md-mermaid-label-bg-color` -> `--md-mermaid-sequence-label-bg-color` and so on, or narrowing down the selectors themselves based on diagram types?

**Comment by squidfunk** [comment]
Yes. I'd say it might make sense to introduce a little hierarchy to comfortably style Mermaid.js components, and specific components inside diagrams. I haven't made up my mind how a hierarchy of CSS variables could look like, but I'd be happy if somebody was up to do the legwork and submit a PR for it. We need a first draft which we can discuss ☺️ As with all of Material for MkDocs, if the approach proposed could have sane defaults, and make it easy to deviate where desired, plus be extensible to account for new components that Mermaid.js adds, we're all for it!

**Comment by squidfunk** [comment]
@nejch @sisp did you manage to start working on this topic? I just want to make sure we're not duplicating efforts.

**Comment by sisp** [comment]
@squidfunk Not yet, but it's on my list for next week. Thanks for asking and checking! :+1:

**Comment by sisp** [comment]
I've submitted a PR: #5940

**Comment by squidfunk** [comment]
Released as part of [9.2.7](https://squidfunk.github.io/mkdocs-material/changelog/#9.2.7).
