### ISSUE TITLE
Blog post drafts with tags show up in tags index

### ISSUE THREAD

**Issue by trslater** [squidfunk/mkdocs-material#5826]
### Context

When writing a blog, drafts should be completely hidden from the user, so possible future unfinished work is not revealed prematurely. MkDocs Material blog plugin already prevents drafts from being built by default, and these unbuilt posts are also no included in the blog index or categories list.

### Bug description

When using the blog and tags plugins together (as outlined in the docs), draft blog posts with tags are included in the tags index, even when they are not built, leading to revealing unfinished work and broken links.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Setting up a blog - Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#adding-tags)
- [Setting up tags - Material for MkDocs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/)

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/12308634/example.zip)

### Steps to reproduce

1. Build site: `mkdocs build`
2. Open `index.html` from `site` directory in a browser
3. Click on "Tags" in the navigation

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting! Clearly, that shouldn't happen.

**Comment by squidfunk** [comment]
Fixed in 15c024cbb. Thanks for this very concise issue and perfect reproduction, that made fixing this bug a pleasure! The blog plugin will now mark posts that are marked as draft as excluded. The tags plugin will skip excluded pages. Additionally:

- `mkdocs serve`, by default, renders drafts, which will also appear in the tags index
- `mkdocs build`, by default, excludes drafts, which will now also be excluded from the tags index

This behavior can be changed with the `draft` and `draft_on_serve` settings. We're keeping the page in the index if drafts are rendered for consistency. Nonetheless, this issue can be considered resolved.

We're using the new [`File.inclusion`](https://www.mkdocs.org/dev-guide/api/#mkdocs.structure.files.File.inclusion) feature, so please make sure that you're on MkDocs 1.5+.

**Comment by trslater** [comment]
> Fixed in [15c024c](https://github.com/squidfunk/mkdocs-material/commit/15c024cbbfd1ed747df1ca20a81c8b2860c7da8c). Thanks for this very concise issue and perfect reproduction, that made fixing this bug a pleasure! The blog plugin will now mark posts that are marked as draft as excluded. The tags plugin will skip excluded pages. Additionally:
> 
> * `mkdocs serve`, by default, renders drafts, which will also appear in the tags index
> * `mkdocs build`, by default, excludes drafts, which will now also be excluded from the tags index
> 
> This behavior can be changed with the `draft` and `draft_on_serve` settings. We're keeping the page in the index if drafts are rendered for consistency. Nonetheless, this issue can be considered resolved.
> 
> We're using the new [`File.inclusion`](https://www.mkdocs.org/dev-guide/api/#mkdocs.structure.files.File.inclusion) feature, so please make sure that you're on MkDocs 1.5+.

No problem! Thanks for creating such an awesome theme.

**Comment by squidfunk** [comment]
Released as part of [9.2.0](https://github.com/squidfunk/mkdocs-material/releases/tag/9.2.0).
