### ISSUE TITLE
Support custom icons for code block copy and line selection

### ISSUE THREAD

**Issue by Shrinks99** [squidfunk/mkdocs-material#5845]
### Context

In our project we use Bootstrap's icon set and MkDocs Material helpfully lets us change & use Bootstrap's icon set through the [custom_icons](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons) feature.

### Description

Allow users to specify replacement icons for the [code copy button](https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admon#admonition-icons) and [code selection button](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code+b#code-selection-button) in `mkdocs.yml` under the `theme` section, similar to how admonition icons are specified.

### Related links

- [Code Copy Button — MkDocs Material Documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code+b#code-copy-button)
- [Admonition Icon Settings — MkDocs Material Documentation](https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admon#admonition-icons)

### Use Cases

The included copy button is nice!  ...But we use Bootstrap's [`files`](https://icons.getbootstrap.com/icons/files/) icon everywhere else for this action, and it would be nice to unify that with our documentation.

I've seen other projects use a clipboard icon for this as well.  Presumably they might also want to modify the theme to ensure their docs icons are the same as those in their app.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. You can already do that! See:

https://github.com/squidfunk/mkdocs-material/blob/ccc3c444edc66479074aa480b3afca56f17d38ed/src/partials/actions.html#L33

https://github.com/squidfunk/mkdocs-material/blob/ccc3c444edc66479074aa480b3afca56f17d38ed/src/partials/actions.html#L50

**Comment by Shrinks99** [comment]
Those icons we've already changed!  This issue is referring to `--md-clipboard-icon` set [here](https://github.com/squidfunk/mkdocs-material/blob/ccc3c444edc66479074aa480b3afca56f17d38ed/src/assets/stylesheets/main/components/_clipboard.scss#L29) which isnt exposed as a yaml value in the theme.  I suppose this _could_ be overridden with custom CSS but that's not exactly in-line with other icon changes?

**Comment by squidfunk** [comment]
Ah sorry, my fault, I misread it 🤦‍♂️ You can change the clipboard icon similar to [custom admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#__codelineno-13-2) – just copy and paste the SVG of the icon and reference it in [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) like so:

```css 
:root {
  --md-clipboard-icon: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512">...</svg>')
}
```

We're currently not planning to add support to override each and every icon that is referenced in CSS via `mkdocs.yml` – there're just too many. Thus, I'd kindly ask you to use some additional CSS – it's quite simple.
