### ISSUE TITLE
Improve development environment setup instructions

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#5854]
### Description

I've just gone through the [development environment setup](https://squidfunk.github.io/mkdocs-material/customization/#environment-setup) and stumbled over two aspects that might be improved:

1. **Usage of a virtual env:** Python dependencies should be installed in a virtual env, and this is probably clear to experienced Python developers but certainly not to everybody. I think the docs should advise to use a virtual env and show how to set it up.
2. **Setup of Node.js:** This project is _mainly_ a Python project (with regard to its build artifact) but requires Node.js for development. The docs just mention that Node.js is needed but don't explain how to set it up. Well, the same is true for Python, but since this is a Python project, it's probably okay to assume contributors have a working Python environment. But for Node.js, we could leverage [`nodeenv`](https://github.com/ekalinin/nodeenv) to install Node.js within the virtual env and, thus, ease the setup.

See below how I suggest to extend the setup instructions.

### Related links

- [Environment setup](https://squidfunk.github.io/mkdocs-material/customization/#environment-setup)
- [venv — Creation of virtual environments](https://docs.python.org/3/library/venv.html)
- [nodeenv](https://github.com/ekalinin/nodeenv)

### Proposed change

I think we could extend `docs/customization.md` as follows:

````diff
 Next, all dependencies need to be installed, which is done with:

 ```
 cd mkdocs-material
+python -m venv .venv
+. .venv/bin/activate
 pip install -e .
 pip install mkdocs-minify-plugin
 pip install mkdocs-redirects
+pip install nodeenv
+python -m nodeenv -p -n lts
 npm install
 ```
````

This way, a virtual env is created and activated, and `nodeenv` installs the latest LTS version (currently v18) into the virtual env along with NPM, so a contributor doesn't need to worry about installing (the right version of) Node.js. The only minor problem I see with those instructions is that the command for activating the virtual env isn't the same across platforms.

WDYT, @squidfunk?

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm not a user of `nodeenv`, as I mainly live in the Node.js world and use `n` for version management, but I agree that the development instructions could be improved. Would you like to work on this in the form of a PR? Happy to improve the theme development guide together!

**Comment by sisp** [comment]
Gladly. I'll send a PR with some suggestions, which we can discuss and iterate on, next week.
