### ISSUE TITLE
Default docker instructions do not work with `strict` mode

### ISSUE THREAD

**Issue by geoknee** [squidfunk/mkdocs-material#5855]
### Context

Presumably the Docker route is there partly to allow getting started with as little friction as possible. 

### Bug description

If running via Docker and having `strict: true` in `mkdocs.yml`, we get an error.

```
❯ docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material                                                                                                                

WARNING -  Config value 'dev_addr': The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local
           development purposes only. Please use a third party production-ready server instead.

Aborted with 1 configuration warnings in 'strict' mode!
```

This is due to the following line in the Docker image:
```
CMD ["serve" "--dev-addr=0.0.0.0:8000"]
```

~I suggest that either~
*  ~the `"--dev-addr=0.0.0.0:8000"` is removed.~
* ~the documentation says how to override this (i.e. to append `serve` to the `docker run` command above)~
EDIT: I now realise these aren't workable, and the fix needs to be made upstream of this repo. 

### Related links

https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker
https://squidfunk.github.io/mkdocs-material/creating-your-site/#previewing-as-you-write

### Reproduction

[temp.zip](https://github.com/squidfunk/mkdocs-material/files/12369478/temp.zip)

### Steps to reproduce

```
❯ docker pull squidfunk/mkdocs-material

❯ docker run --rm -it -v ${PWD}:/docs squidfunk/mkdocs-material new .

❯ echo "strict:true" >> mkdocs.yml

❯ docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material                                                                                                                

WARNING -  Config value 'dev_addr': The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local
           development purposes only. Please use a third party production-ready server instead.

Aborted with 1 configuration warnings in 'strict' mode!
```

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
As an addendum:

> the "--dev-addr=0.0.0.0:8000" is removed.

This makes `mkdocs serve` inaccessible, as `0.0.0.0` is necessary to forward the server from the guest to the host.

**Comment by geoknee** [comment]
Thanks @squidfunk I hadn't realised it was such a contested upstream issue :-/ . I also hadn't realised that working around it doesn't look easy either.

**Comment by squidfunk** [comment]
@geoknee I think it might be worth reopening this discussion, as maintainership of MkDocs changed. Maybe the new maintainers are open to discuss the problems this brings and gravitate towards a solution. With 5.7 million downloads of our official image, it's quite a common problem.

**Comment by oprypin** [comment]
Regarding this particular case, the docker file definition could be improved:
https://github.com/squidfunk/mkdocs-material/blob/ccc3c444edc66479074aa480b3afca56f17d38ed/Dockerfile#L102
```dockerfile
 CMD ["serve", "--no-strict", "--dev-addr=0.0.0.0:8000"] 
```
-new flag in [MkDocs 1.5.0](https://github.com/mkdocs/mkdocs/releases/tag/1.5.0).

---

Or generally I'd really recommend not to configure `strict: true` in the permanent YAML config; instead just in CI run `mkdocs build --strict`.

**Comment by louwers** [comment]
@oprypin Not ideal, since you want to catch strict errors during development.
