### ISSUE TITLE
Provide Docker Images for Beta Releases

### ISSUE THREAD

**Issue by struffel** [squidfunk/mkdocs-material#5857]
### Context

Users are encouraged to test beta releases like the upcoming 9.2.0 and report any issues they encounter.
However, for users who use MkDocs-Material exclusively through docker, without even cloning the Git repository or installing python, this is made unnecessarily complicated as they need to build the image themselves. This makes it harder to give feedback.

### Description

Provide *clearly marked* beta or "nightly" images in addition to the stable releases on the official Docker Hub page.
This would make it easier for users to test new features or compare the behavior between different beta versions.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Docker Hub Page, without beta releases](https://hub.docker.com/r/squidfunk/mkdocs-material/tags)

### Use Cases

As an author who uses MkDocs-Material exclusivly via Docker, without even installing Python on the system, I would still like to have access to images for beta releases so that I can still help beta-testing new features without additional installation effort.
This would make it possible to get more eyes on every beta release before the final version is shipped.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. I understand that this would be beneficial to users of our Docker image, but we currently have no bandwidth to investigate how to do this. We'll be exiting the latest beta in 1-2 weeks, but if you or somebody else wishes to create a PR to add support, we're happy to discuss. However, until then, we'll consider this as out of scope.
