### ISSUE TITLE
Incorrent offset after jumping to footnote in Firefox

### ISSUE THREAD

**Issue by makshh** [squidfunk/mkdocs-material#586]
## Description

Incorrent offset after jumping to footnote in Firefox (it doesn't take into account header height like in Chrome)

### Expected behavior

Correct offset

### Actual behavior

Incorrect offset in Firefox

### Steps to reproduce the bug

1. Open Firefox
2. Go to https://squidfunk.github.io/mkdocs-material/extensions/footnotes/
3. Click on backref

### Package versions

* MkDocs: 2.0.4
* Material: 0.17.1

### Project configuration

Irrelevant

### System information

* OS: OSX/Windows
* Browser: Firefox 56.0.2 (OSX), Firefox 52.0.1 (Windows)

Works good on Chrome/Safari/Opera

**Comment by squidfunk** [comment]
Fixed in #609 - again. I also refactored the code a little. This is something that comes up every now and then and is attributed to the fact that the behavior of Chrome is totally different to that of Firefox. Oh I love browsers 💩

**Comment by makshh** [comment]
Yeah , love them too, especially differences between these two browsers :broken_heart:

**Comment by squidfunk** [comment]
Released as part of 2.2.0.
