### ISSUE TITLE
Make dense toolbar as option!

### ISSUE THREAD

**Issue by MishUshakov** [squidfunk/mkdocs-material#587]
## Description

Hello, can you please add an option for a dense toolbar, that looks and behaves like google-devsites?

Example: https://developers.google.com/web/fundamentals/primers/service-workers/
Example 2: https://dialogflow.com/docs/getting-started/basics

It is 48px and has minimal paddings applied, with a combination of tabs it also has a sticky-mode(aka fixed last row)

### Expected behavior

when I set toolbar: 'densed' in MkDocs.yml it will minimize the toolbar 

### Actual behavior

Big, fat toolbar

**Comment by squidfunk** [comment]
The Material theme already provides a lot of options, but will probably never provide everything the Google Developer Docs template has. It doesn't try to take everything from the theme, as not all things make sense. A dense toolbar is a matter of taste and will therefore almost likely not be provided in the future, I'm sorry.
