### ISSUE TITLE
Toolbar shadows

### ISSUE THREAD

**Issue by MishUshakov** [squidfunk/mkdocs-material#588]
## Description

The shadows of toolbar look ugly

### Expected behavior

Try this: 0 0 4px rgba(0, 0, 0, .14), 0 4px 8px rgba(0, 0, 0, .28)

### Actual behavior

The shadows of toolbar look ugly, it is so blurry

**Comment by squidfunk** [comment]
I will look into the shadows, I'm not 100% satisfied either. Thanks.
