### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType' with blog plugin

### ISSUE THREAD

**Issue by vedranmiletic** [squidfunk/mkdocs-material#5881]
### Bug description

When blog plugin is enabled, the `build` fails with `TypeError: unsupported operand type(s) for |: 'type' and 'NoneType' with blog plugin`. This happens on version 9.2.0 and 9.2.1, but did not happen with 9.2.0b3 in the same Python environment.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[blog-nonetype.zip](https://github.com/squidfunk/mkdocs-material/files/12406850/blog-nonetype.zip)

### Steps to reproduce

1. `mkdocs build`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting, but sadly, you did not use the [`info`](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file) plugin which is __mandatory__ when you create a [bug report](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Without the plugin, we don't know the necessary information in your environment that might lead to the problem.

We're unable to reproduce it:

```
mkdocs build
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /Users/squidfunk/Downloads/blog-nonetype/site
INFO    -  Documentation built in 0.09 seconds
```

Please carefully read our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) and use the info plugin to create a reproduction.

**Comment by squidfunk** [comment]
Nonetheless, I think I might have fixed the issue in 070404653. It's likely related to your Python version, but I can only guess because of the missing information. Please check the latest `master` to see if the issue is gone.

**Comment by vedranmiletic** [comment]
> Thanks for reporting, but sadly, you did not use the [`info`](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file) plugin which is **mandatory** when you create a [bug report](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Without the plugin, we don't know the necessary information in your environment that might lead to the problem.

I tried including it, but the `TypeError` occurs before info plugin produces any output so I removed it because it has no effect in this case. Sorry, I should have noted that explicitly in the original report.

> Nonetheless, I think I might have fixed the issue in [0704046](https://github.com/squidfunk/mkdocs-material/commit/0704046536d60a1dddae65b1dcf1075f8058e968). It's likely related to your Python version, but I can only guess because of the missing information. Please check the latest `master` to see if the issue is gone.

It indeed is, thanks!

**Comment by squidfunk** [comment]
Okay, fair enough, no problem then ☺️ Great we could solve it so quickly!

**Comment by vedranmiletic** [comment]
Thank you for understanding. Eagerly waiting for 9.2.2 release. 😎
