### ISSUE TITLE
glossary snippet feature doesnt work out of the box

### ISSUE THREAD

**Issue by flynneva** [squidfunk/mkdocs-material#5882]
### Context

It looks like the glossary feature just auto-appends the raw text to the rendered articles instead of inserting a tooltip.

![image](https://github.com/squidfunk/mkdocs-material/assets/6157095/a0144927-a411-4006-a878-d944600a0b93)

The stuff at the bottom I think is supposed to be hidden, and instead be tooltips on the corresponding words at the top.

### Bug description

- no tooltip generated for glossary items
- glossary is just added to the bottom of the page in raw text form

### Related links

- [docs on glossary](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-a-glossary)
- [docs on pymarkdown snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#auto-append-snippets)

### Reproduction

[test.zip](https://github.com/squidfunk/mkdocs-material/files/12412775/test.zip)

### Steps to reproduce

1. unzip attachment
2. install mkdocs, mkdocs-material
3. `mkdocs serve`

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by facelessuser** [comment]
Did you not enable the [`abbr`](https://python-markdown.github.io/extensions/abbreviations/#:~:text=The%20Abbreviations%20extension%20adds%20the,in%20the%20standard%20Markdown%20library.) extension?

**Comment by squidfunk** [comment]
Thanks for reporting. No, `abbr` is not enabled. Change the configuration to make it work:

``` yaml
markdown_extensions:
  - abbr
  - pymdownx.snippets:
      auto_append:
        - glossary.md
      check_paths: True
```

**Comment by flynneva** [comment]
@squidfunk can we maybe update the docs so that the glossary mkdocs.yml has all required plugins listed?

For me the docs were confusing as I didn't understand that in order to use the glossary feature we also need to enable the abbr plugin.

**Comment by squidfunk** [comment]
[We already list the `abbr` extension in the configuration](https://squidfunk.github.io/mkdocs-material/reference/tooltips/#configuration), but we can also add it to the `mkdocs.yml` tab. Would you like to submit a PR?

**Comment by NikosAlexandris** [comment]
Using

``` bash
❯ mkdocs --version
mkdocs, version 1.5.3 from /software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/mkdocs (Python 3.11)
```
I can't make a `glossary.md` work !

The file contains

``` md
*[HTML]: Hyper Text Markup Language
*[NetCDF]: Network Common Data Form
*[Chunk]: A block of data
*[Shape]: The size of chunks or dimensions
*[Dimensions]: The number of ...
*[CPU]: Central Processing Unit
```

and I have the following configuration

``` yaml
watch:
  - docs/includes

..

nav:
  - Reference:
      - Glossary: includes/glossary.md
  - Tags: includes/tags.md

..

plugins:
  - search
  - tags:
      tags_file: includes/tags.md

markdown_extensions:
  - abbr
  - pymdownx.snippets:
      check_paths: True
      auto_append:
        - includes/glossary.md
        # - includes/abbreviations.md
```

and the following structure

``` bash
❯ tree docs/includes/
[nik      4.0K]  docs/includes/
├── [nik       206]  abbreviations.md
├── [nik       228]  glossary.md
└── [nik        67]  tags.md
```

Plus, the `mkdocs.yml` is obviously in the parent directory -- that is _not_ inside `docs`.

I get the following error : 

``` bash
❯ mkdocs serve --watch-theme
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  The following pages exist in the docs directory, but are not included in the "nav"
           configuration:
             - about/about.md
             - how_to/how_to.md
             - how_to/inspect.md
             - includes/abbreviations.md
             - tutorials/tutorials.md
ERROR   -  Error reading page 'index.md': Snippet at path 'includes/glossary.md' could not be found
Traceback (most recent call last):
  File "/software/rekx/.rekx_virtual_environment/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/mkdocs/commands/build.py", line 175, in _populate_page
    page.render(config, files)
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/mkdocs/structure/pages.py", line 271, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/markdown/core.py", line 354, in convert
    self.lines = prep.run(self.lines)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/pymdownx/snippets.py", line 366, in run
    return self.parse_snippets(lines)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/software/rekx/.rekx_virtual_environment/lib/python3.11/site-packages/pymdownx/snippets.py", line 351, in parse_snippets
    raise SnippetMissingError("Snippet at path '{}' could not be found".format(path))
pymdownx.snippets.SnippetMissingError: Snippet at path 'includes/glossary.md' could not be found
```

The tags work just fine.  If I remove the 

``` yaml
      check_paths: True
```
option, the site works except for the wanted glossary page. How can I further debug this ?

**Comment by alexvoss** [comment]
The path given in `auto_append` is relative to the project directory, not to `docs/`. This makes sense since normally you will not want the included snippets to be rendered as a page. If you do then you need to prepend `docs/`. See the footnote in the Material for MkDocs documentation on [adding a glossary](https://squidfunk.github.io/mkdocs-material/reference/tooltips#adding-a-glossary).

**Comment by NikosAlexandris** [comment]
> The path given in `auto_append` is relative to the project directory, not to `docs/`. This makes sense since normally you will not want the included snippets to be rendered as a page. If you do then you need to prepend `docs/`. See the footnote in the Material for MkDocs documentation on [adding a glossary](https://squidfunk.github.io/mkdocs-material/reference/tooltips#adding-a-glossary).

Thank you! That did it.

ps- I was even more confused as I expected also a list of all defined terms in a nice way, similar to Tags or else similar to https://jupyterbook.org/en/stable/content/content-blocks.html?highlight=glossary#glossaries.

**Comment by alexvoss** [comment]
I am pretty sure that it would be possible to create a glossary page that does get rendered. How best to approach this would depend on your needs, though. Since you have all the data already in the page, you could try and [write a hook](https://www.mkdocs.org/user-guide/configuration/#hooks) that does what is necessary. 

Another approach is always to see if there is already a plugin. There are some out there but I have not used them yet, so cannot comment on the pros and cons.
