### ISSUE TITLE
Implement light theme

### ISSUE THREAD

**Issue by MishUshakov** [squidfunk/mkdocs-material#589]
## Description

For the light theme, it will reset the color of toolbars and controls to white, then change font color to rgba(0,0,0,.8) and apply accent(secondary) theme to other components

It also changes the behaviour of search bar(on hover it will make the background darker, instead of transparent)

### Expected behavior

Ps: screenshot also contains changed toolbar from my previous issues #588 and #587

![screen shot 2017-11-13 at 21 42 00](https://user-images.githubusercontent.com/10400064/32748223-e62db5a0-c8bb-11e7-9e6f-65a2a46b62e2.png)

### Actual behavior

No light theme supported as now

**Comment by MishUshakov** [comment]
Example ![screen shot 2017-11-14 at 01 18 09](https://user-images.githubusercontent.com/10400064/32756320-bb9d4120-c8d9-11e7-96b1-8b56fb6fe69b.png)

**Comment by squidfunk** [comment]
A light theme is a nice idea, I may consider adding it to the theme.
