### ISSUE TITLE
Change tabs behaviour on folded markdowns

### ISSUE THREAD

**Issue by MishUshakov** [squidfunk/mkdocs-material#590]
## Description

Hi, can you please change theming of tabs? This how they look like with custom tab-bar and toolbar

### Expected behavior

It should follow material design guidelines

For toolbar see #589 #588 #587 

![screen shot 2017-11-13 at 22 11 33](https://user-images.githubusercontent.com/10400064/32749577-0dc484c8-c8c0-11e7-99c9-7764e53372b7.png)

### Actual behavior

It looks uuuugly

![screen shot 2017-11-13 at 22 15 04](https://user-images.githubusercontent.com/10400064/32749621-259432a6-c8c0-11e7-8327-404d121298c3.png)

**Comment by MishUshakov** [comment]
The tabs should also stay sticky instead of staying under the toolbar

**Comment by squidfunk** [comment]
The tab toolbar probably will never stay sticky, that's just not how it's implemented. It will take some effort to change the behavior and it doesn't really integrate well with the current behavior which is adopted by many sites. For this reason, it's unclear if this change will make it into Material.
