### ISSUE TITLE
instant loading breaks announcement bar dismissal

### ISSUE THREAD

**Issue by thesuperzapper** [squidfunk/mkdocs-material#5901]
### Context

Probably related to https://github.com/squidfunk/mkdocs-material/issues/3615

### Bug description

Currently, if someone enables `navigation.instant` and `announce.dismiss` at the same time, the announcement will only stay dismissed until the next page navigation, after which it will reappear again.

The cause is fairly straightforward, it is simply that `[data-md-component=announce]` should not be selected in the instant reload typescript:

https://github.com/squidfunk/mkdocs-material/blob/f022873c69bb10b419dfbecab2cc0a2d6ac794b1/src/assets/javascripts/integrations/instant/index.ts#L235

When I removed this line in a custom theme, everything worked as expected (with the announcement staying dismissed).

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

.

### Steps to reproduce

1. Create a MkDocs material website with `navigation.instant` and `announce.dismiss`  enabled
2. Override the `main.html` template's `{% block announce %}` to have some content
3. Load the website, and dismiss the announcement bar
4. Navigate to a new page on the website (without reloading)
5. The announcement bar will reappear

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by thesuperzapper** [comment]
In a similar issue (closer to https://github.com/squidfunk/mkdocs-material/issues/3615), there is probably a way to prevent the "page jiggle" on the first load (if the announcement bar is dismissed).

I think you must have fixed this on the main https://squidfunk.github.io/mkdocs-material/ website because it does not seem to occur there (actually both issues don't occur on your main website).

**Comment by squidfunk** [comment]
Thanks for reporting. However, this issue does not comply with [our quality standards](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) – it does not include a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) that we can run. Please provide a reproduction so we can investigate. Until then, we're closing it as [incomplete](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#incomplete-issues).

**Comment by vedranmiletic** [comment]
I can see this at our [group website](https://group.miletic.net/), but it uses a ton of features so I will reduce it down to a minimal example that breaks. It is not too annoying, but it would be great to have it fixed at some point.

**Comment by squidfunk** [comment]
I'm not seeing it on your site. When I dismissed the announcement bar, the page loads without flickering or jumping (Chrome, macOS).

**Comment by vedranmiletic** [comment]
I am on (Arch) Linux and I see it in Brave and Firefox (sorry, no Chrome or Chromium to try at this machine). I see it when I do this:

1. load main page
2. dismiss the announcement bar
3. go to the Croatian (or English) landing page via navigation tab

**Comment by thesuperzapper** [comment]
For reference, I fixed this issue on the deployKF website by:

1. [Wrapping the script which updates the announcement bar's hidden state in a function named `syncAnnouncementBar()`](https://github.com/deployKF/website/blob/7e8b372da4df49b1d375f55bda2d6319a6d2739a/overrides/partials/javascripts/announce.html#L1-L10) using theme overrides on the `javascripts/announce.html` partial.
2. [Include a call to this `syncAnnouncementBar()` Javascript function within the "hero" content tag](https://github.com/deployKF/website/blob/7e8b372da4df49b1d375f55bda2d6319a6d2739a/overrides/main.html#L8-L13):
     - NOTE: I only used "hero" because it is within the "content" data component, which the "instant navigation" code is already [programmed to run all scripts under](https://github.com/squidfunk/mkdocs-material/blob/f022873c69bb10b419dfbecab2cc0a2d6ac794b1/src/assets/javascripts/integrations/instant/index.ts#L255-L283) before replacing the content, upon instant navigation.

**Comment by squidfunk** [comment]
Thanks for sharing. So again, a reproduction would be amazing and mandatory, as it gives us a head start to fix any bugs, but until now, none was provided. If somebody is up for creating one, we're happy too look into it.

**Comment by vedranmiletic** [comment]
> If somebody is up for creating one, we're happy to look into it.

I am on it. I will post it later today or tomorrow.

**Comment by vedranmiletic** [comment]
Here is a minimal example: [instant-bug.zip](https://github.com/squidfunk/mkdocs-material/files/12491082/instant-bug.zip)

Way to reproduce:

1. `mkdocs serve`
2. load the site in browser
3. dismiss the announcement bar
4. go to page `Page`
5. see the announcement bar reappear

1. disable `navigation.instant` in `mkdocs.yml`
2. load the site in browser again
3. dismiss the announcement bar again
4. go to page `Page` again
5. see the announcement bar doesn't reappear

FWIW, `info` plugin during `mkdocs build` will complain about overrides so I didn't get the information from it. As you can see, I am not doing any fancy overrides.

**Comment by squidfunk** [comment]
Thanks for providing the reproduction! I'll look into it.

**Comment by squidfunk** [comment]
Fixed in 76a30ecab.

**Comment by squidfunk** [comment]
Released as part of [9.2.7](https://squidfunk.github.io/mkdocs-material/changelog/#9.2.7).
