### ISSUE TITLE
Light Theming & more

### ISSUE THREAD

**Issue by MishUshakov** [squidfunk/mkdocs-material#592]
![screen shot 2017-11-16 at 14 13 02](https://user-images.githubusercontent.com/10400064/32893418-ac4fb980-cad9-11e7-8f8f-3a33158b7f58.png)

## Description

Implement light theme, used by google devsites

CSS: https://pastebin.com/6g6NJuC1

### What was changed

White toolbar and new material design shadows, rgba(0,0,0,.8) is used as primary font color on white background. 

Redesigned tabs(with border at the bottom and Uppercase Roboto 500 font). I also applied custom opacity settings on :hover

Footer was also changed to light theme

### Expected behavior

![screen shot 2017-11-14 at 14 37 12](https://user-images.githubusercontent.com/10400064/32787375-afc71704-c956-11e7-9a88-306e55541718.png)

![screen shot 2017-11-14 at 15 13 06](https://user-images.githubusercontent.com/10400064/32784357-e495ceec-c94e-11e7-8c21-ae4b7257b72f.png)

Looks very clean

### Actual behavior

Looks heavy and old, but still very useful and handy

### What also should be changed or be optional param

Hide left sidebar, if there is only one document in folder(tabbed mode)

![screen shot 2017-11-14 at 15 14 00](https://user-images.githubusercontent.com/10400064/32787867-f30d3ed4-c957-11e7-9d8f-9a1942c2a347.png)

**Comment by squidfunk** [comment]
I'm sorry, but can you please stop opening issues with stuff that is heavily opinionated? I would kindly ask you to make one issue where you can collect all improvements you want to suggest, because all of them are UI related.

**Comment by MishUshakov** [comment]
@squidfunk hmm, I think that is it, sorry for that by the way, but I think I can comment other stuff here, if I notice something ;)

**Comment by squidfunk** [comment]
The thing is that you're flooding the issue tracker with matters of taste and that may confuse other users.

**Comment by MishUshakov** [comment]
@squidfunk you can close them, I would rename this topic

**Comment by squidfunk** [comment]
Thanks!

**Comment by MishUshakov** [comment]
@squidfunk np, was my problem, going crazy on this awesome theme. I always use mkdocs for documentation and mkdocs-material is a must-have choice. Just thought about making it better and bit look-alike google devsites :D

**Comment by squidfunk** [comment]
Yeah, but keep in mind that not everybody wants it to look like Google. Material is used by Netflix, Intel, Uber and other companies and they probably use it because it doesn't look like it is a product of Google.

**Comment by MishUshakov** [comment]
![screen shot 2017-11-16 at 14 11 46](https://user-images.githubusercontent.com/10400064/32893351-6bc8886a-cad9-11e7-8e0e-15c56c425dfe.png)
![screen shot 2017-11-16 at 14 13 02](https://user-images.githubusercontent.com/10400064/32893353-6d272d56-cad9-11e7-9b2b-5b52b2109acd.png)

Updated googlish-light theme

Pastebin: https://pastebin.com/6g6NJuC1

**Comment by squidfunk** [comment]
I applied some of your styles and made the header narrower in #597. I won't copy the other suggestions you made for now, because they do not work for me. Thanks for your work!

**Comment by MishUshakov** [comment]
Thank you, amazing facelift!
