### ISSUE TITLE
Code annotations do not work within an ordered list item

### ISSUE THREAD

**Issue by petemounce** [squidfunk/mkdocs-material#5929]
### Context

I am a mkdocs-materials insiders user via EngFlow.

### Bug description

I have a code-block within an ordered-list item. I am trying to add annotations to the code-block and so far have failed. Instead of rendering annotations, a nested ordered list is rendered.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [closed issues mentioning "annotations"](https://github.com/squidfunk/mkdocs-material/issues?q=is%3Aissue+annotations+is%3Aclosed)
- Reference: code-annotations
    - [feature flag is on](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations)
    - [adding annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations)
    - ([a desire to strip comments](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#stripping-comments))

### Reproduction

This is the output from our build [mkdocs.zip](https://github.com/squidfunk/mkdocs-material/files/12478688/mkdocs.zip). We build via bazel; it's a little tricky to follow the repro-guide and be certain of the version of mkdocs-materials-insiders matches our vendor'd copy.

[repro.zip](https://github.com/squidfunk/mkdocs-material/files/12478733/repro.zip)

### Steps to reproduce

I have content:

```markdown
1. Create a fluent-bit `rewrite_tag` filter against the fluent-bit `input` that will contain the log-lines you want to alert against.

    ```txt title="/etc/fluent-bit.d/some_file.filter.conf"
    [FILTER]
        name  rewrite_tag
        match some_input_alias # (1)!
        alias some_unique_alias # (2)!

        rule  FIELD REGEX_MATCHER NEW_EVENT_TAG keep_or_drop # (3)!
    ```

    1. This must match the name of the fluent-bit input you are filtering. For example `engflow_re_app.tail`.
    2. The filter alias should be a unique, meaningful name. Think of it as the log-filter's name.
    3. See [upstream rewrite_tag docs][2].
```

but it has not rendered the annotations as expected. See screenshot.
![Screenshot 2023-08-30 at 18 18 22](https://github.com/squidfunk/mkdocs-material/assets/69720/5e82b088-7d8b-42e8-ae77-89777c4e1a51)


### Browser

_No response_

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Although this issue is missing a reproduction, which prohibits us from inquiring into the problem reported, it is apparent from the code example what's happening: you're using a  `txt` lexer that does not lex the code annotations into comments. Thus, Material for MkDocs doesn't know how to find them. Three possible solutions in increasing levels of involvement:

### Using another lexer, such as `sh` that treats spans starting with `#` as comments.

``` markdown
1. ...

    ``` sh title="..."
    ...
    ```

    1. ...
    2. ...
    3. ...
```

### Configuring Material for MkDocs to also lex non-comment tokens

This also means you need to switch to something different than `txt`, or Pygments won't add classes.

``` markdown
1. ...

    ``` cfg title="..."
    ...
    ```

    1. ...
    2. ...
    3. ...
```

In `mkdocs.yml`:

``` yaml
extra:
  annotate:
    cfg: [.na]
```

You will probably also need to remove the `#` then.

### Writing your own lexer

Several users have done that, use the search to find examples

**Comment by petemounce** [comment]
> Thanks for reporting. Although this issue is missing a reproduction, which prohibits us from inquiring into the problem reported, it is apparent from the code example what's happening: you're using a txt lexer that does not lex the code annotations into comments. Thus, Material for MkDocs doesn't know how to find them.

Thank you! (also, 🤦)
