### ISSUE TITLE
Table of contents is not always visible in mobile drawer nav

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#5935]
### Description

When the mobile nav is active and the drawer open, screens between 960px and 1219px width see the table of contents on the right-hand side of the screen behind the overlay, where the section links cannot be clicked, and it isn't visible in the drawer nav. This means it isn't possible to jump to a section on the page while the drawer is open. For screens smaller than 960px, the table of contents is embedded in the drawer nav and it's hidden on the main page. I think this UX is a bit inconsistent.

How about showing the table of contents in the drawer nav for all screens smaller than 1220px instead? The table of contents would be available twice for screens between 960px and 1219px, but it would only be usable in the drawer nav.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)

### Use Cases

IMO, jumping to a section on the page would have a better UX across different mobile devices when the table of contents was _always_ available in the drawer nav.

### Visuals

![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/6711f07c-c2c2-4bb0-bfbc-ed6f891d2ec6)
![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/412e6400-c4dc-449c-abe3-24f74d8f3716)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by sisp** [comment]
> Thanks for suggesting! We've had this behavior since version 1.0.0, and we can't just change it, because it would be a substantial, fundamental change that would deviate from the current architecture, with potential for breaking customized installations downstream. If you wish for this behavior, the theme can be forked and the respective CSS and JS sources can be adapted.

I haven't tried it, but I imagine it would require only the removal of media queries (just the wrapper) related to showing the table of contents in the drawer, so that the table of contents is never hidden in the drawer nav. It doesn't sound like a breaking change to me TBH.

> To expand on that: I don't think it's bad UX. [...]

On landscape tablets, users could simply ignore the table of contents in the drawer nav, which would correspond to the current behavior &ndash; the difference to them would just be a small additional icon. But those who would like to jump to a section on the page and accept the additional clicks in the drawer nav could do it. The way I see it, everybody could continue navigating as before, the only difference for them would be a small additional icon in the drawer nav.

**Comment by squidfunk** [comment]
That would mean two times the same navigation – IMHO, that's an anti pattern. If you still want it, you can just add some additional CSS to show the icon. Feel free to share your customizations here.

**Comment by sisp** [comment]
I believe the change would be tiny, see this [diff](https://github.com/squidfunk/mkdocs-material/compare/8f1433fa3916d5f7c75186e1ae262b9f1ec802a6...sisp:mkdocs-material:feat/drawer-nav-toc-always#diff-fa1b034ea52b71422565fad852a6627bd141d22598c65d4fda7d2d68aac3163e). Would you care to give it a try to see how it would feel? I really think is not very intrusive.

**Comment by squidfunk** [comment]
Nope, sorry, as said. We don't consider this to be good UX, as you're displaying two navigations with the same content to the user. Please use customizations to achieve that ☺️

**Comment by sisp** [comment]
Okay, fair enough. I tried. :wink: Thanks for being so responsive. :bow:
