### ISSUE TITLE
A branch for mkdocs 1.0.dev?

### ISSUE THREAD

**Issue by funkyfuture** [squidfunk/mkdocs-material#594]
ciao, i'm currently struggling to get `mkdocs-material` working with the `1.0.dev` branch of `mkdocs`. while hacking around i had the thought that it'd be propably better to do this systematically. would you also foster a branch that depends on the development version of `mkdocs`?

**Comment by squidfunk** [comment]
Not really, I hardly find the time to maintain the `master`  branch so I have really no time for doing this. However, you're free to fork the project and start working on a separate branch. I would be willing to create a branch as well and keep it on par with yours. Does this work for you?

**Comment by funkyfuture** [comment]
> I would be willing to create a branch as well and keep it on par with yours. Does this work for you?

yep, that's what i meant with fostering. shall i keep this issue for informative reasons? i don't think i'll have the time to continue on it very soon.

**Comment by squidfunk** [comment]
I suggest we use PRs for discussion, because discussion will most likely be limited to technical issues, I guess.
