### ISSUE TITLE
Per page extra CSS/JavaScript via Markdown front matter properties

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#5941]
### Context

I'd like to be able to load custom CSS/JavaScript on some pages (e.g. home page). Adding custom CSS/JavaScript is currently possible in two ways:

1. Via [`extra_css`](https://www.mkdocs.org/user-guide/configuration/#extra_css)/[`extra_javascript`](https://www.mkdocs.org/user-guide/configuration/#extra_javascript) in `mkdocs.yml`, which adds those assets to _each_ page
1. Via extending `main.html`, overriding/extending, e.g., the Jinja block `{% block styles %}`, and configuring this template via front matter

I'd like to avoid loading custom CSS/JavaScript on every page because it's quite specific to a particular page, so option 1 isn't a good solution. Option 2 works but is a bit too verbose for my taste and requires fiddling a little with Jinja &ndash; not awful but suboptimal DX.

### Description

How about supporting additional properties in the Markdown front matter called `extra_css`/`extra_javascript`, equivalent to the `extra_css`/`extra_javascript` settings in `mkdocs.yml`? E.g.:

```md
---
extra_css:
  - css/home.css
---
```

I believe the implementation would be quite simple, only `base.html` would have to be extended a little:

```diff
     <!-- Custom style sheets -->
-    {% for path in config.extra_css + (page.meta and page.meta.extra_css | ) %}
+    {% for path in config.extra_css + (page.meta and page.meta.extra_css) | default([], true) %}
       <link rel="stylesheet" href="{{ path | url }}" />
     {% endfor %}
```

It would look similar for JavaScript.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css)
- [Additional JavaScript](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript)
- [Setting the page `template`](https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-template)

### Use Cases

MkDocs for Material makes creating websites beyond just documentation very convenient, and a full-fledged website often has some pages with custom design such as the home page. Evidently, Markdown &ndash; sometimes enhanced with minor HTML markup (see, e.g., [card grids](https://squidfunk.github.io/mkdocs-material/reference/grids/#using-card-grids)) &ndash; in combination with some clever CSS rules and possibly JavaScript code can go way beyond rendering prose. In order to ease userland extensions similar to card grids that are only needed on some pages, adding CSS/JavaScript only to those pages would be desirable and it would be much easier with my proposed change than via template inheritance.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. It's actually even simpler and there's no need to provide additional configuration that we need to parse, adding additional functionality and more maintenance overhead. You can just use `style` and `script` tags in Markdown documents, which is the recommended way:

``` markdown
<link rel="stylesheet" href="css/home.css">
<script src="js/home.js"></script>

# Document title
```

If that's not what you want, and you still want to define those values in front matter, you can use a hook, that should be trivial to implement. Just use either `on_page_markdown` or `on_page_content` and append the lines to the output.

**Comment by sisp** [comment]
Ah, thanks bringing up these alternatives! They might be worth being added to the docs though, wouldn't you say?

**Comment by squidfunk** [comment]
> Ah, thanks for bringing up these alternatives! They might be worth being added to the docs though, wouldn't you say?

You're invited to submit a PR to the customization guide. We'll be reworking that as well in the future, but in the meantime it's definitely a good idea to have

> `directory-urls` or `--no-directory-urls` which would be handled by `{{ path | url }}` if I understand this right, but we'd need `../css/home.css` for `--no-directory-urls` and `css/home.css` for `--use-directory-urls`. So the only safe way might be using the hooks as you suggested. But that DX is even worse than extending the template. 🤔 That said, is my proposed extension still not appealing?

You would need to provide the correct relative links yourself, yes. And yes, the path might be influenced by directory URLs. Other than that, you or somebody else could definitely implement this as a third-party plugin, as it's a problem that generalize to all themes, not only Material for MkDocs, but we're currently not considering it.

**Comment by oneumyvakin** [comment]
@squidfunk Correct me if I'm wrong using style and script tags in Markdown documents doesn't work with "serve", because mkdocs will not copying custom files from `js/` to temporary directory, right?

**Comment by sisp** [comment]
@oneumyvakin You can put files inside, e.g., `docs/js/` and refer to them via their URL after the site build.

**Comment by joapuiib** [comment]
Material for MkDocs [can be extended](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme) to include such customization:

I've managed to do it extending __`base.html`__:
```
{% extends "base.html" %}

{% block styles %}
    {{ super() }}
    {% if page.is_page %}
    {% for path in page.meta.extra_stylesheets %}
        <link rel="stylesheet" href="{{ path | url }}">
    {% endfor %}
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {% if page.is_page %}
    {% for script in page.meta.extra_javascript %}
        {{ script | script_tag }}
    {% endfor %}
    {% endif %}
{% endblock %}
```
