### ISSUE TITLE
Support for gitea and forgejo instances in repository SourceFacts

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#5942]
### Description

Support for gitea/forgejo instances in the SourceFacts feature should be considered.

The feature would simply accept a domain of the type `(sub.)domain.tld/user/repo` to then connect to the Gitea/Forgejo API to pull data from.

I've already prepared a Commit that implements this feature and made basic Regex testings. Both are linked below.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Branch of commited change](https://github.com/Andre601/mkdocs-material/tree/feature/add-forgejo-gitea-stats-support)
- [Regex tests](https://regex101.com/r/OUjAeq/1)

### Use Cases

This would allow displaying stats from sources other than GitHub or GitLab, allowing authors to more easily show basic stats of their repository on another (Their own) repository host.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. We're not planning to add more source facts providers. GitHub and GitLab are by far the most popular, and we're supporting them because MkDocs did it from the beginning. It makes no sense for us to integrate with other third-party service that have a tiny fraction of the user base that GitHub and GitLab have:

<img width="1060" alt="Bildschirm­foto 2023-09-02 um 12 33 47" src="https://github.com/squidfunk/mkdocs-material/assets/932156/b2603c0b-81e8-4a5f-934c-5741780c36cc">

However, it is trivial to add support yourself – just add some [additional JavaScript](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) that makes the API call and render the necessary HTML inside the component, something like:

``` js
document$.subscribe(() => {
  // 1. API call to retrieve statistics
  // 2. Render result in the following HTML
})
```

The source that needs to be rendered by your script looks as follows:

``` html
<ul class="md-source__facts">
  <li class="md-source__fact md-source__fact--version">9.2.6</li>
  <li class="md-source__fact md-source__fact--stars">15.1k</li>
  <li class="md-source__fact md-source__fact--forks">3.1k</li>
</ul>
```

Closing as out of scope.

**Comment by Andre601** [comment]
I'm curious in what way MkDocs added github support first.
If it is the `gh-deploy` command then that is nothing more than an automated `git checkout -b gh-pages -> git commit -> git push origin/gh-pages` system. See [here](https://github.com/mkdocs/mkdocs/discussions/3298#discussioncomment-6491904)

If there is something else I miss I would apreciate if you could share it.

Also, are numbers really that important here?
I believe that numbers alone shouldn't be a sole key factor here to determine if something is worth or not to be added.

One key point of gitea and forgejo is, that people can selfhost it, which means that gitea and forgejo may not be as popular in terms of search results. It doesn't eliminate them being used by many however.
Not to mention is this a comparison between 2 multi-million - if not even billion - companies and 2 open source projects (from which only one is run by a for-profit), which is quite unfair tbh.

Also, by the looks of it have you checked for germany? Global stats may be different?

By all means do I understand and accept your decision, I just wanted to point out a few things to consider.

**Comment by Andre601** [comment]
Also, here are trends I searched myself.
"Gitlab" (blue) is much closer to gitea and forgejo than towards Github, so numbers really shouldn't be a factor in my personal opinion.

![SmartSelect_20230902-130402_Firefox.jpg](https://github.com/squidfunk/mkdocs-material/assets/11576465/dc010c76-aef2-4a3b-8433-a042d728b6a2)

**Comment by squidfunk** [comment]
> I'm curious in what way MkDocs added github support first. If it is the `gh-deploy` command then that is nothing more than an automated `git checkout -b gh-pages -> git commit -> git push` system. See [here](https://github.com/mkdocs/mkdocs/discussions/3298#discussioncomment-6491904)

I'm only talking about the [`repo_url`](https://www.mkdocs.org/user-guide/configuration/#repo_url) setting.

> Also, are numbers really that important here?

Yes. Managing economics is critical to maintaining an Open Source project of this size. Additionally, adding support yourself is straight forward. Material for MkDocs is extensible, customizable and hackable.

> One key point of gitea and forgejo is, that people can selfhost it, which means that gitea and forgejo may not be as popular in terms of search results. It doesn't eliminate them being used by many however. Not to mention is this a comparison between 2 multi-million - if not even billion - companies and 2 open source projects (from which only one is run by a for-profit), which is quite unfair tbh.

It doesn't matter what the back story is – if it's a popular solution that is worth integrating, we'll do it. If it's not popular, it doesn't make sense to budget time for that. Currently, it's not that popular, so we will not add support in our code base.

**Comment by Andre601** [comment]
One thing I just thought about: Can I add JS as a separate file for Material for MkDocs to then use for fetching source stats?

I know I can make a fork and customize that. But this will add the extra burden of keeping the fork up-to-date and in sync with Material for MkDocs if I want to receive the latest fixes and features to use.

I sadly don't know enough here about JS and alike to know if I could "add" new sources through an external file...
If that is possible, but not available in Material for MkDocs, could it perhaps be considered? It would allow us adding own sources of our choice without you having to implement direct support... But then again do I barely know JS so I cannot tell if that is even technically possible to have.

**Comment by squidfunk** [comment]
Yes, as I already said in https://github.com/squidfunk/mkdocs-material/issues/5942#issuecomment-1703794071:

> However, it is trivial to add support yourself – just add some [additional JavaScript](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) that makes the API call and render the necessary HTML inside the component, something like:
> 
> ``` js
> document$.subscribe(() => {
>   // 1. API call to retrieve statistics
>   // 2. Render result in the following HTML
> })
> ```
> 
> The source that needs to be rendered by your script looks as follows:
> 
> ``` html
> <ul class="md-source__facts">
>   <li class="md-source__fact md-source__fact--version">9.2.6</li>
>   <li class="md-source__fact md-source__fact--stars">15.1k</li>
>   <li class="md-source__fact md-source__fact--forks">3.1k</li>
> </ul>
> ```

**Comment by Andre601** [comment]
> Yes, as I already said in [#5942 (comment)](https://github.com/squidfunk/mkdocs-material/issues/5942#issuecomment-1703794071):
> 
> > However, it is trivial to add support yourself – just add some [additional JavaScript](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) that makes the API call and render the necessary HTML inside the component, something like:
> > ```js
> > document$.subscribe(() => {
> >   // 1. API call to retrieve statistics
> >   // 2. Render result in the following HTML
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The source that needs to be rendered by your script looks as follows:
> > ```
> > <ul class="md-source__facts">
> >   <li class="md-source__fact md-source__fact--version">9.2.6</li>
> >   <li class="md-source__fact md-source__fact--stars">15.1k</li>
> >   <li class="md-source__fact md-source__fact--forks">3.1k</li>
> > </ul>
> > ```

Okay. Was just not so sure...

Tho, this may be a bit difficult for me to work out in the end as I'm not experienced with JS... Can I utilize imports Material for MkDocs is using or would I need to separately add then where needed?
I preferrably would like to implement a system similar to what Material for MkDocs is utilizing here, but I cannot wrap my head around JS that easily... So any hints into the right direction would be greatly apreciated.

**Comment by squidfunk** [comment]
I think implementing it from scratch is easier than learning [RxJS](https://rxjs.dev/), so copy & pasting is likely more involved.

**Comment by Andre601** [comment]
Yeah... I'm too stupid for this unfortunately... 😓 
Not a big deal for me... Perhaps I'll get it working in the future, but not right now... Thanks anyways for your input.

**Comment by Andre601** [comment]
I just found out something rather sad and annoying... The repo site I use - codeberg.org - seems to not allow any AJAX requests to their API through their CORS settings, making this entire thing impossible to use, unless I would now setup some proxy to send the requests through with proper headings and alike...

**Comment by Andre601** [comment]
Okay. One final update to wrap this all up...

Thanks to some help did I setup a proxy on vercel to re-route my requests through, so that this CORS issue is avoided and now the stats display properly (Sadly no stars nor forks on this repository 🥲)
![grafik](https://github.com/squidfunk/mkdocs-material/assets/11576465/81b0bf41-d522-48d8-9956-33b7afe2041b)

The JS I use for anyone else interested:
```javascript
document$.subscribe(async () => {
    const url = 'https://codeberg-stats-proxy.vercel.app/repo'
    
    const release_data = await fetch(`${url}/latest-release`)
        .then(_ => _.json());
    const repo_data = await fetch(`${url}/stats`)
        .then(_ => _.json());
    
    console.log(release_data);
    console.log(repo_data);
    
    const list = document.querySelectorAll('ul[data-md-component="codeberg-stats"]');
    
    list.forEach((entry) => {
        entry.innerHTML = `<li class="md-source__fact md-source__fact--version">${release_data.name}</li>
            <li class="md-source__fact md-source__fact--stars">${repo_data.stars}</li>
            <li class="md-source__fact md-source__fact--forks">${repo_data.forks}</li>`
    })
})
```

And the overriden `source.html` file:
```html
<a
  href="{{ config.repo_url}}"
  title="{{ lang.t('source') }}"
  class="md-source"
  target="_blank"
  rel="nofollow noreferral noopener"
>
  <div class="md-source__icon md-icon">
    {% set icon = config.theme.icon.repo or "fontawesome/brands/git-alt" %}
    {% include ".icons/" ~ icon ~ ".svg" %}
  </div>
  <div class="md-source__repository">
    {{ config.repo_name }}
    <ul class="md-source__facts" data-md-component="codeberg-stats">
    </ul>
  </div>
</a>
```

**Comment by ysfchn** [comment]
Here's an improved version that I use currently, which avoids the usage of `innerHTML` and doesn't require overriding HTML block.

```js
document$.subscribe(() => {
    const repo_stats = document.querySelector('[data-md-component="source"] .md-source__repository');
    const repo_url = "<< REPLACE ME >>";

    function loadInfo(data) {
        // Change this if you want to only include a single information, not stars, versions and forks at the same time.
        const facts = document.createElement("ul");
        facts.className = "md-source__facts";
        const version = document.createElement("li");
        version.className = "md-source__fact md-source__fact--version";
        const stars = document.createElement("li");
        stars.className = "md-source__fact md-source__fact--stars";
        const forks = document.createElement("li");
        forks.className = "md-source__fact md-source__fact--forks";
        version.innerText = data["version"];
        stars.innerText = data["stars"];
        forks.innerText = data["forks"];
        facts.appendChild(version);
        facts.appendChild(stars);
        facts.appendChild(forks);
        repo_stats.appendChild(facts);
    }

    function fetchInfo() {
        fetch(repo_url).then((r) => r.text()).then((content) => {
            // Change that according to the response of API result.
            const data = {
                "version": content["version"],
                "stars": content["stars"],
                "forks": content["forks"]
            };
            __md_set("__git_repo", data, sessionStorage);
            loadInfo(data);
        });
    }

    // Cache repository information to prevent multiple calls. 
    // Mkdocs for Material also caches the response as far as I can see from the source code.
    if (!document.querySelector('[data-md-component="source"] .md-source__facts')) {
        const cached = __md_get("__git_repo", sessionStorage);
        if ((cached != null) && (cached["version"])) {
            loadInfo(cached);
        } else {
            fetchInfo();
        }
    }
});
```

And to enable the same ease-in animation for non-GitHub and non-GitLab projects, use this CSS:

```
.md-source__repository .md-source__facts {
    animation: facts .25s ease-in;
}
```

**Comment by Andre601** [comment]
> Here's an improved version that I use currently, which avoids the usage of `innerHTML` and doesn't require overriding HTML block.
> 
> ```js
> document$.subscribe(() => {
>     const repo_stats = document.querySelector('[data-md-component="source"] .md-source__repository');
>     // Make sure to use an API that sends CORS headers, otherwise this won't work.
>     const repo_url = "<< REPLACE ME >>";
> 
>     function loadInfo(data) {
>         // Change this if you want to only include few information, 
>         // not stars, versions and forks at the same time.
>         const facts = document.createElement("ul");
>         facts.className = "md-source__facts";
>         const version = document.createElement("li");
>         version.className = "md-source__fact md-source__fact--version";
>         const stars = document.createElement("li");
>         stars.className = "md-source__fact md-source__fact--stars";
>         const forks = document.createElement("li");
>         forks.className = "md-source__fact md-source__fact--forks";
>         version.innerText = data["version"];
>         stars.innerText = data["stars"];
>         forks.innerText = data["forks"];
>         facts.appendChild(version);
>         facts.appendChild(stars);
>         facts.appendChild(forks);
>         repo_stats.appendChild(facts);
>     }
> 
>     function fetchInfo() {
>         fetch(repo_url).then((r) => r.json()).then((content) => {
>             // Change that according to the response of API result.
>             const data = {
>                 "version": content["version"],
>                 "stars": content["stars"],
>                 "forks": content["forks"]
>             };
>             __md_set("__git_repo", data, sessionStorage);
>             loadInfo(data);
>         });
>     }
> 
>     // Cache repository information to prevent multiple calls. 
>     // Mkdocs for Material also caches the response as far as I can see from the source code.
>     if (!document.querySelector('[data-md-component="source"] .md-source__facts')) {
>         const cached = __md_get("__git_repo", sessionStorage);
>         if ((cached != null) && (cached["version"])) {
>             loadInfo(cached);
>         } else {
>             fetchInfo();
>         }
>     }
> });
> ```

That looks nice, but for my case would it not really work... And probs not even for most git repo hosts at all, because I cannot remember any API that returns the latest release version in the same response where it gives the star and fork count, so two separate calls are at least required...

And I do not have any idea how to properly return this stuff when using things like Promis.all

> And to enable the same ease-in animation for non-GitHub and non-GitLab projects, use this CSS:
> 
> ```css
> /* Enable the animation regardless of the repository type. */
> .md-source__repository .md-source__facts {
>     animation: facts .25s ease-in;
> }
> ```

**Comment by Andre601** [comment]
I think these adjustments should work for my case:
```js
document$.subscribe(async () => {
    const url = 'https://codeberg-stats-proxy.vercel.app/repo'
    const repo_stats = document.querySelector('[data-md-component="source"] .md-source__repository');
    
    function loadInfo(data) {
        const facts = document.createElement("ul");
        facts.className = "md-source__facts";
        
        const version = document.createElement("li");
        version.className = "md-source__fact md-source__fact--version";
        
        const stars = document.createElement("li");
        stars.className = "md-source__fact md-source__fact--stars";
        
        const forks = document.createElement("li");
        forks.className = "md-source__fact md-source__fact--forks";
        
        version.innerText = data["version"];
        stars.innerText = data["stars"];
        forks.innerText = data["forks"];
        
        facts.appendChild(version);
        facts.appendChild(stars);
        facts.appendChild(forks);
        
        repo_stats.appendChild(facts);
    }
    
    async function fetchInfo() {
        const [release, repo] = await Promise.all([
            fetch(`${url}/latest-release`).then(_ => _.json()),
            fetch(`${url}/stats`).then(_ => _.json()),
        ]);
        
        const data = {
            "version": release.name,
            "stars": repo.stars,
            "forks": repo.forks
        };
        
        __md_set("__git_repo", data, sessionStorage);
        loadInfo(data);
    }
    
    if(!document.querySelector('[data-md-component="source"] .md-source__facts')){
        const cached = __md_get("__git_repo", sessionStorage);
        if((cached != null) && (cached["version"])) {
            loadInfo(cached);
        } else {
            fetchInfo();
        }
    }
    
    /*
    const [release, repo] = await Promise.all([
        fetch(`${url}/latest-release`).then(_ => _.json()),
        fetch(`${url}/stats`).then(_ => _.json()),
    ]);
    
    const list = document.querySelectorAll('ul[data-md-component="codeberg-stats"]');
    
    list.forEach((entry) => {
        entry.innerHTML = `<li class="md-source__fact md-source__fact--version">${release.name}</li>
            <li class="md-source__fact md-source__fact--stars">${repo.stars}</li>
            <li class="md-source__fact md-source__fact--forks">${repo.forks}</li>`
    })
    */
})
```

**Comment by pat-s** [comment]
@Andre601 Thanks for your initiative here. Just wanted to state that I've been able to get repo stats for the Crow CI project thanks to your work here.

Linking the latest working version as of today which I found in one of your repos: https://codeberg.org/Andre601/AdvancedServerList/src/branch/master/docs/assets/js/repo-stats.js

Maybe another blog post with the current version could be helpful for other users searching for this :)

**Comment by ysfchn** [comment]
By the way for anyone who is interested, I've recently discovered that Codeberg [did make changes](https://codeberg.org/Codeberg-Infrastructure/build-deploy-forgejo/pulls/127) to enable CORS from their side for API routes a year ago, so you don't need a proxy anymore to retrieve repository stats from Codeberg API. We currently use it in production [here](https://codeberg.org/Freeyourgadget/website/src/commit/eee3dfc3604dab72fea4c82281b08e5c702c1bae/docs/assets/git-stats.js#L22), and it does work.
