### ISSUE TITLE
Add pngquant to Docker Image

### ISSUE THREAD

**Issue by tylernguyen** [squidfunk/mkdocs-material#5946]
### Description

`Dockerfile` does not include the `pngquant` package, which is required for the [optimize plugin](https://squidfunk.github.io/mkdocs-material/setup/building-an-optimized-site/#built-in-optimize-plugin). This applies to both the public repository as well as the Insiders repository.

Please add this package to `Dockerfile`.

### Related links

- https://github.com/squidfunk/mkdocs-material-insiders/blob/master/Dockerfile
- https://squidfunk.github.io/mkdocs-material/setup/building-an-optimized-site/#built-in-optimize-plugin

### Use Cases

It would be more straightforward to use the `optimize` plugin when building with Docker, without having to manually edit my own repository fork's `Dockerfile` to include the package.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting - 100%, `pngquant` should be bundled with the Insiders Docker image.

**Comment by squidfunk** [comment]
Added in [`a42f4cb81`](https://github.com/squidfunk/mkdocs-material-insiders/commit/a42f4cb81a6511d74cd7ee1382db72b9af7465de).

**Comment by squidfunk** [comment]
Released as part of [9.2.7+insiders-4.40.3](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.40.3)
