### ISSUE TITLE
Missing post titles in Blog index when specified via metadata `title`

### ISSUE THREAD

**Issue by vedranmiletic** [squidfunk/mkdocs-material#5951]
### Context

MkDocs supports specifiying post title via `h1` in content, e.g. `# Lorem ipsum`, or via `title` metadata key, e.g. 

```
---
title: Lorem ipsum
date: 1970-01-01
---
```

Both will get rendered correctly on individual pages.

### Bug description

On Blog index page with latest posts, the title specified via metadata key does not appear. It is, however, rendered correctly on the post itself, i.e. after clicking on `Continue reading`.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Setting up a blog](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/)

### Reproduction

[9.2.7-missing-titles-for-blog-posts.zip](https://github.com/squidfunk/mkdocs-material/files/12505508/9.2.7-missing-titles-for-blog-posts.zip)

### Steps to reproduce

1. `mkdocs serve`
2. navigate to Blog index
3. observe missing titles
4. click `Continue reading` on any post
5. observe that the title is there

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Fixed in 7bdd03a79.

**Comment by vedranmiletic** [comment]
Thank you!

**Comment by squidfunk** [comment]
Released as part of [9.2.8](https://squidfunk.github.io/mkdocs-material/changelog/#9.2.8).
