### ISSUE TITLE
Add description for extra.scope option

### ISSUE THREAD

**Issue by Bizordec** [squidfunk/mkdocs-material#5964]
### Description

This option useful in case when you build subsites separately. For example, for this structure
```
.
└── /
    ├── A/
    ├── B/
    └── C/
```
each site will have its own state for palette (`/A/.palette`, `/B/.palette`, `/C/.palette)`. To share the same state between all subsites, you could set `scope: /`.

It was already described here (https://github.com/squidfunk/mkdocs-material/issues/1914#issuecomment-882025594), but is still missing in the docs.

### Related links

- [Customization](https://squidfunk.github.io/mkdocs-material/customization/)

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting! Would you like to submit a PR? ☺️ Do you have a proposal where this should be located?

**Comment by squidfunk** [comment]
We've decided to close the PR, as we're not planning to add an entire section on this, but as already explained in https://github.com/squidfunk/mkdocs-material/pull/5967#issuecomment-1706033417, we'll shortly add a multi-site guide that will include and explain this setting ☺️

**Comment by squidfunk** [comment]
I've finally found some time to add this to the documentation – I used large parts of your PR #5967, so I tagged you as a co-author ☺️ The current place might not be perfect, but we'll shortly revise our documentation, so we'll likely move it around.

Fixed in f494840bd.
