### ISSUE TITLE
Search has a word/character count limitation?

### ISSUE THREAD

**Issue by MaximilianKohler** [squidfunk/mkdocs-material#5968]
### Description

I'm searching for a phrase/sentence and it gives zero results unless I shorten it. 

If I search for `"Cariogenic microbiome"` it will return results for both `cariogenic` and `microbiome`. If I search for `Cariogenic microbiome and microbiota of the early primary dentition` it will give me tons of results but not ranked in the "most matches" or "best matches" order, so it's useless. If I search for `"Cariogenic microbiome and microbiota of the early primary dentition"` I get no results. 

### Related links

- https://github.com/squidfunk/mkdocs-material/issues/1772
-https://github.com/squidfunk/mkdocs-material/issues/1772#issuecomment-1702890410

### Use Cases

I'm just trying to use really basic search operations that work on virtually all other website searches that I'm aware of. 

I moved my wiki/site from a github wiki, and haven't found any other SSG that comes close to being a viable replacement. The github search function was working well for everything I needed. 

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. The search does not have a character count limitation. If you put everything in quotes, every term must occur (see [example](https://squidfunk.github.io/mkdocs-material/?q=%22custom+color+schemes%22)). The problems you're describing are all related to lunr.js not being the perfect choice when it comes to docs search. As I've already mentioned in multiple issues and discussions, we're currently rebuilding the search and will be solving all of those problems. The new search will return relevant results in a much, much better way.

> The github search function was working well for everything I needed.

GitHub has fundamentally changed its search implementation and I agree that it is much better now. Our search implementation will be even more powerful in the future ☺️ Until then, there's no action to be taken on this particular issue, as it's a general suggestion to improve relevance of results. Closing.

**Comment by MaximilianKohler** [comment]
@squidfunk 

Were you saying this shouldn't happen `The search does not have a character count limitation`, or were you acknowledging that it is indeed a limitation `The problems you're describing are all related to lunr.js not being the perfect choice when it comes to docs search` of the current search? 

Because my test above shows a character count limitation.

**Comment by squidfunk** [comment]
It's not a character limitation. I think it is related to using stopwords like "the" and "for" in exact searches.

**Comment by squidfunk** [comment]
Please checkout https://github.com/squidfunk/mkdocs-material/pull/6372 – the PR attempts to solve the problem that exact phrase and sentences are not conveniently ranked, being preceded by many results that do not contain the terms searched.
