### ISSUE TITLE
regression: Navigation bar link name misbehaving

### ISSUE THREAD

**Issue by llucax** [squidfunk/mkdocs-material#5971]
### Context

I'm not sure how this is a regression in mkdocs-material, but I'm able to reproduce the issue I'm having by just installing mkdocs-material 9.2.0+ and getting back to normal by installing 9.1.21. It might be that some other plugin is at fault and the failure was hidden in previous versions.

I'm using `mkdocs-literate-nav` to generate the nav bar, I didn't removed all customizations because it would be difficult to do it and still be able to reproduce the regression. Since this is a regression I assume it might be easier to track down even if it is related to another plug-in. Tagging @oprypin (author of `mkdocs-literate-nav`) as they might also have some clue about why this happens, but reporting it here because, again, I'm able to reproduce it by just switching between `mkdoc-material` versions (as shown all other mkdocs related dependencies stay the same).

I also didn't attached the ZIP file because the issue can be reproduced by checking out a particular tag/hash of a public github repo, so I think it is not necessary to pack it in a ZIP.

Hope all of the above is OK.

### Bug description

```console
$ cat docs/SUMMARY.md 
* [Home](index.md)
* [API Reference](reference/)
* [Contributing](CONTRIBUTING.md)
```

With mkdocs-material 9.1.21 or older, I get this:

![image](https://github.com/squidfunk/mkdocs-material/assets/1031485/ce8ef029-5974-4e07-9b62-1769a58aefda)

(Note the `API Reference`, the correct version)

With mkdocs-materia 9.2.0 or newer, I get this:

![image](https://github.com/squidfunk/mkdocs-material/assets/1031485/9c916484-34d4-4abc-a302-4d3ad5be7fd6)

(Note the `sdk`, the version with an unexpected text)

### Related links

- Affected project: https://github.com/frequenz-floss/frequenz-sdk-python
- Issue about this problem in our project: https://github.com/frequenz-floss/frequenz-sdk-python/issues/640
- Working documentation site: https://frequenz-floss.github.io/frequenz-sdk-python/v0.24/
- Broken documentation site: https://frequenz-floss.github.io/frequenz-sdk-python/v0.25/
- Related plugin: https://github.com/oprypin/mkdocs-literate-nav

### Reproduction

The setup is complex, and again I'm not sure about the interaction between different plugins. Instead I'm offering perfectly reproduceable steps within the open source project we are observing this.

### Steps to reproduce

```console
$ git clone -b v0.25.0 https://github.com/frequenz-floss/frequenz-sdk-python.git
Cloning into 'frequenz-sdk-python'...
...
Turn off this advice by setting config variable advice.detachedHead to false

$ cd frequenz-sdk-python/
$ python3.11 -m venv .venv # Note only Python 3.11 is supported by this project
$ . .venv/bin/activate
$ pip install -e .[dev-mkdocs]
...
$ pip freeze | grep mkdocs
mkdocs==1.5.2
mkdocs-autorefs==0.5.0
mkdocs-gen-files==0.5.0
mkdocs-literate-nav==0.6.0
mkdocs-material==9.2.5
mkdocs-material-extensions==1.1.1
mkdocs-section-index==0.3.5
mkdocstrings==0.22.0
mkdocstrings-python==1.6.2
$ mkdocs serve
... deprecations ...
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Doc file 'SUMMARY.md' contains an unrecognized relative link 'reference/', it was left as is.
INFO    -  Documentation built in 3.20 seconds
INFO    -  [13:51:19] Watching paths for changes: 'docs', 'mkdocs.yml', 'src', 'README.md', 'CONTRIBUTING.md'
INFO    -  [13:51:19] Serving on http://127.0.0.1:8000/
WARNING -  [13:51:21] "GET /versions.json HTTP/1.1" code 404
INFO    -  [13:51:21] Browser connected: http://127.0.0.1:8000/
```

Check http://127.0.0.1:8000/ and observe the "sdk" in the menu (**bad**).

```console
$ pip install mkdocs-material==9.1.21
Collecting mkdocs-material==9.1.21
  Obtaining dependency information for mkdocs-material==9.1.21 from https://files.pythonhosted.org/packages/c0/d3/abe920304e9dc6af40d4fd20f520c0ea64e9518fea259114e4f0956b975d/mkdocs_material-9.1.21-py3-none-any.whl.metadata
...
Installing collected packages: mkdocs-material
  Attempting uninstall: mkdocs-material
    Found existing installation: mkdocs-material 9.2.5
    Uninstalling mkdocs-material-9.2.5:
      Successfully uninstalled mkdocs-material-9.2.5
Successfully installed mkdocs-material-9.1.21
$ pip freeze | grep mkdocs
mkdocs==1.5.2
mkdocs-autorefs==0.5.0
mkdocs-gen-files==0.5.0
mkdocs-literate-nav==0.6.0
mkdocs-material==9.1.21
mkdocs-material-extensions==1.1.1
mkdocs-section-index==0.3.5
mkdocstrings==0.22.0
mkdocstrings-python==1.6.2
$ mkdocs serve
... deprecations ...
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Doc file 'SUMMARY.md' contains an unrecognized relative link 'reference/', it was left as is.
INFO    -  Documentation built in 3.17 seconds
INFO    -  [13:56:53] Watching paths for changes: 'docs', 'mkdocs.yml', 'src', 'README.md', 'CONTRIBUTING.md'
INFO    -  [13:56:53] Serving on http://127.0.0.1:8000/
WARNING -  [13:56:56] "GET /versions.json HTTP/1.1" code 404
INFO    -  [13:56:56] Browser connected: http://127.0.0.1:8000/
```

Check http://127.0.0.1:8000/ and observe the "API Reference" in the menu (**good**).

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by llucax** [comment]
OK, it might be related to the [mkdocs-section-index](https://github.com/oprypin/mkdocs-section-index) plugin too, as removing this plugin from `mkdocs.yml` also solves the issue.

**Comment by squidfunk** [comment]
Thanks for reporting. Closing as upstream.

**Comment by squidfunk** [comment]
In https://github.com/squidfunk/mkdocs-material/issues/5971#issuecomment-1706501893, you said that it works when you disable the section index plugin, so it's a regression in the section index plugin. The section index plugin is not officially supported by us, so it needs to be fixed upstream ☺️
