### ISSUE TITLE
Built-in meta plugin does not propagate anymore to other Markdown files

### ISSUE THREAD

**Issue by Guts** [squidfunk/mkdocs-material#5979]
### Bug description

Front matter set in `.meta.yml` files is not applied to markdown pages in the same folder.

### Related links

- [built-in meta plugin](https://squidfunk.github.io/mkdocs-material/reference/#built-in-meta-plugin)

### Reproduction

[9.2.8+insiders.4.40.4-meta-plugin-not-working.zip](https://github.com/squidfunk/mkdocs-material/files/12566038/9.2.8%2Binsiders.4.40.4-meta-plugin-not-working.zip)

### Steps to reproduce

1. Enable built-in meta and tags plugins
2. Create a `.meta.yml` hiding tags:

    ```yaml
    hide:
      - tags
    ```

3. In a markdown page, add tags:

    ```markdown
    ---
    tags:
      - test
    ---

4. mkdocs serve: tags are displayed on page and should not

### Browser

_No response_

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by Guts** [comment]
I've just found a workaround and probably where the issue comes from.

If I specify the meta_file pattern path option, it's working (my website is within a content subfolder):

```yaml
  - meta:
      meta_file: "content/**/.meta.yml"
```


Maybe (really not sure) it's related to the mkdocs 1.5 changes in path resolution: https://www.mkdocs.org/user-guide/configuration/#paths-relative-to-the-current-file-or-site

**Comment by Guts** [comment]
> ```yaml
> meta_file: "content/**/.meta.yml"
> ```

Forget it, it's not working... Sorry for the noise...

**Comment by Guts** [comment]
Thanks you for the quick fix, as usual 😉

**Comment by fredrikaverpil** [comment]
I just noticed all of my blog posts are missing my author avatar all of a sudden: https://fredrikaverpil.github.io/blog/

@squidfunk I did not make any changes to the blog config or anything like that, but I have added new posts so I've regenerated the pages. So I suspect something has happened here, maybe as part of the 9.3.1+insiders.4.41.0 release since you changed behavior around the meta file/plugin here?

- My meta file: https://github.com/fredrikaverpil/fredrikaverpil.github.io/blob/main/mkdocs/blog/posts/.meta.yml
- If I comment out `comments: true` from the meta file, all comments disappear on all my posts. So this file is indeed being read.
- I can add the `authors` key to an indivual page's frontmatter and then my author avatar shows for that post only.

**Comment by squidfunk** [comment]
From quickling skimming through your repo, I think you need to adjust the`.authors.yml` format:

``` yaml
authors:
  fredrikaverpil:
    name: Fredrik Averpil
    description: Author
    avatar: https://github.com/fredrikaverpil.png
```

There should be [a warning](https://github.com/squidfunk/mkdocs-material/blob/9888723f86b20224197811fb647bfc4a79ce5a9f/src/plugins/blog/plugin.py#L499-L513) about the new format, and I'm not sure why it doesn't appear to you. If you can provide a reproduction and create a new issue we can look into it. Note that the blog plugin got completely rewritten for the 9.2.0 release, so there may still be some oddities we need to fix.

**Comment by fredrikaverpil** [comment]
Your code snippet in the above comment is identical to my `.authors.yml` file.  This is my `.authors.yml` file and it was written 6 months ago: https://github.com/fredrikaverpil/fredrikaverpil.github.io/blob/main/mkdocs/.authors.yml

[The warning](https://github.com/squidfunk/mkdocs-material/blob/9888723f86b20224197811fb647bfc4a79ce5a9f/src/plugins/blog/plugin.py#L499-L513) indicates this is the right format, right?

When reading [the docs](https://squidfunk.github.io/mkdocs-material/plugins/blog/?h=authors#config.authors_file), it also seems like it is correct, right?

I feel like it's also following your own file: https://github.com/squidfunk/mkdocs-material/blob/master/docs/blog/.authors.yml

I'm not sure what I'm doing wrong...

**Comment by fredrikaverpil** [comment]
I'm too tired, I guess 😅 I now see that my authors file did not match up with what you suggested. I updated it in https://github.com/fredrikaverpil/fredrikaverpil.github.io/commit/c96eb159a903aa101aada2ecbc662e9e9f145e0d but I still don't see the avatar showing.

Steps to reproduce in previous post.

**Comment by squidfunk** [comment]
@fredrikaverpil it would be of great help for us if you could try and create a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). I know this involves a little effort, but if you can reproduce it on a mint installation, it's an easy fix for us. Your repository is too big to effectively work on a bugfix – it just takes too long to build and will make debugging a chore.

**Comment by nint8835** [comment]
@squidfunk I'm encountering the same issue, reproduction is here:
[9.4.7+insiders.4.42.3-meta-doesnt-set-authors.zip](https://github.com/squidfunk/mkdocs-material/files/13198814/9.4.7%2Binsiders.4.42.3-meta-doesnt-set-authors.zip)

**Comment by squidfunk** [comment]
Please don't necro post, but create a new issue. The issue that was reported by the OP was fixed.

**Comment by squidfunk** [comment]
Subsequent issue fixed in https://github.com/squidfunk/mkdocs-material-insiders/commit/3ac702d3369d2ae3e98eea3e872092d59b84d277, see https://github.com/squidfunk/mkdocs-material/issues/6254#issuecomment-1784776474.
