### ISSUE TITLE
Old Admonition CSS?

### ISSUE THREAD

**Issue by MaedahBatool** [squidfunk/mkdocs-material#599]
Is there a way to update the CSS of `admonition` to an older version?

I really liked these

![](http://on.ahmda.ws/npEw/c)

and don't much like these

![](http://on.ahmda.ws/nnn2/c)

**Comment by squidfunk** [comment]
Nope, that's not easily possible, I'm sorry. This theme is changing constantly, hopefully for the better. Most of the users seem to like the new Admonitions better, as they are clearer and better readable, especially when things like code blocks or nested admonitions are included. Nesting was not really possible with the old approach.

**Comment by MaedahBatool** [comment]
@squidfunk You're right about that. But the CSS can be more suttle like it used to be. The one right now feels a bit odd and oldish in the theme. Anything we can do to improve that?

I was able to make it to here

![](http://on.ahmda.ws/nngb/c)

**Comment by squidfunk** [comment]
Well, that's a matter of taste. I personally think they look much cleaner than before. You can override all CSS with `extra_css` easily.

**Comment by MaedahBatool** [comment]
Yes, you are right! Anywho, I have achieved somewhat of it with `extra_css`.
Thank you!
