### ISSUE TITLE
Light and dark mode does not work with markdown-captions

### ISSUE THREAD

**Issue by hecc79** [squidfunk/mkdocs-material#5993]
### Bug description

Markdown-captions is incompatible with light and dark mode.
```
![Objektdiagramm der drei Detektive](img/DreiDetektiveObjekt.png#only-light)
![Objektdiagramm der drei Detektive](img/DreiDetektiveObjekt_d.png#only-dark)
```
produces two captions and one image when used with mardown-captions. 

If this is not fixable, please amend the documentation.

```
<figure markdown>
![Objektdiagramm der drei Detektive](img/DreiDetektiveObjekt.png#only-light)
![Objektdiagramm der drei Detektive](img/DreiDetektiveObjekt_d.png#only-dark)
  <figcaption>Objektdiagramm der drei Detektive</figcaption>
</figure>
```

does work.

Cheers,
Christian

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Captions](https://squidfunk.github.io/mkdocs-material/reference/images/#image-captions)
- [light/dark mode](https://squidfunk.github.io/mkdocs-material/reference/images/#light-and-dark-mode)

### Reproduction

[9.3.1-markdown-caption-lightdark-mode.zip](https://github.com/squidfunk/mkdocs-material/files/12589775/9.3.1-markdown-caption-lightdark-mode.zip)

### Steps to reproduce

See reproduction.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This should be reported to the maintainer of the `markdown_captions` plugin. Nonetheless, we will remove the recommendation of Markdown captions from our documentation, as it doesn't integrate well enough.

**Comment by squidfunk** [comment]
Removed mention of extension in ae93496d6.
