### ISSUE TITLE
After using Chinese as the blog article title and using the same date, the article content is displayed the same

### ISSUE THREAD

**Issue by liyangxia** [squidfunk/mkdocs-material#5997]
### Context

I use this project as a personal blog post site, and recently encountered a blog plug-in bug, the details are as follows

- Mkdocs Material releases: 9.3.1
- Python releases: 3.9.13
- No any customizations
- Searched issues

### Bug description

If the same date is used, the content of the second blog post created will be displayed normally on the homepage, but when clicked, the content of the first post will be displayed.

Use the default blog plugin with no configuration parameters. Example:

```yml
# site language
# The test has nothing to do with this
language: en

# plugins
plugins:
  - blog
```

Use the blog writing method in the documentation. Example:

```markdown
---
date: 2023-09-13
authors: [liyangxia]
description: >
  This is an example
categories:
  - Blog
---

# 这是一段中文标题
```

After clicking on the two articles, they will see the same link, but only the content of the document created first will be displayed. Example:

`http://127.0.0.1:8000/blog/2023/09/13/`

Interestingly, if there are numbers and English letters in the title, the corresponding numbers and English letters will be added to the link, access is normal at this time. Example:

blog post title Chinese numbers mixed：

```markdown
# 这是一段中文标题01
```

link look like: 

`http://127.0.0.1:8000/blog/2023/09/13/01/`

### More case screenshots:

<img width="454" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/126838514/5af27247-a372-437a-aac6-bebc6748e737">
<img width="454" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/126838514/f921203f-b5ea-40cb-80b3-ff1bac8467e5">
<img width="454" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/126838514/d581d247-cb5f-4346-a7a4-0d781bbface5">
<img width="454" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/126838514/8faac457-a2f9-44a3-9048-d0ce2573dff0">
<img width="454" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/126838514/134cae62-f8c0-4799-aafd-cad3c5293959">

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[9.3.1-cnblog.zip](https://github.com/squidfunk/mkdocs-material/files/12598911/9.3.1-cnblog.zip)

### Steps to reproduce

1. Create two blog documents
2. The document created first is titled in Chinese, such as: 这是一个测试标题
3. Just write any text in the first article, it needs to be different from the second article for observation
4. Repeat the above steps to complete the second document
5. Open the blog tab and click on the two documents in order to view the content details.

### Browser

Safari, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for asking. As mentioned in our documentation, you should use [another `post_slugify` function](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#+blog.post_slugify), because the default function does not account for characters other than ASCII:

``` yaml
plugins:
  - blog:
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
```
