### ISSUE TITLE
Include multiple color palettes

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#6]
The theme is easily customizable through compilation but it would be nice if there were some more nice material design colors palettes included. Suggestions for good palettes are welcome, maybe one for every color.

**Comment by sebastian-marinescu** [comment]
[MaterialUI.co](http://www.materialui.co/) have a nice [Flat UI Colors](http://www.materialui.co/flatuicolors) palette. Her is a Gist [in Scss](https://gist.github.com/boluge/8547350) and [in Sass](https://gist.github.com/sebastian-marinescu/bbb94b9d145aff4bac2a).
But of course you could tank in the whole [palette of Bootstrap Material Design](https://github.com/FezVrasta/bootstrap-material-design/blob/master/sass/_colors.scss)...

**Comment by squidfunk** [comment]
I know Materialui.co, really good resource. My point was more in the direction of good combinations of colors. However, thinking about it I came to realize that the best approach is to let the user decide. I will extend the Material theme to generate the right CSS for the 400- or 500-variant of every primary color in Google's Material Design palette and good matching accent colors, so the user can decide from the configuration file.

**Comment by sebastian-marinescu** [comment]
Sounds good! Your welcome.

**Comment by carlosperate** [comment]
This is great, can't wait to try it!

**Comment by sebastian-marinescu** [comment]
Nice work @squidfunk :+1: 

You should probably give an example how to use it, either on the 
documentation-site or as an example mkdocs.yml, something like: 

```yaml
extra:
  # other config
  palette:
    primary: deep orange
    accent: light blue
```

**Comment by squidfunk** [comment]
http://squidfunk.github.io/mkdocs-material/getting-started/#changing-the-color-palette and
http://squidfunk.github.io/mkdocs-material/getting-started/#full-example ;-)

**Comment by sebastian-marinescu** [comment]
wow, nice :tada: – I have only looked at "Customization"... I underestimated you, **I'm sorry**! :smile: 
and http://squidfunk.github.io/mkdocs-material/getting-started/#full-example you even integrated i18n :bow:

**Comment by squidfunk** [comment]
My pleasure, trying to build the best and most flexible MkDocs theme. Still loads of work to do (refactor project drawer, optimize typography), but we're on the way with the great help of you guys. Thanks!

**Comment by sebastian-marinescu** [comment]
Best? Already. And most flexible MkDocs theme? Sounds good! :candy:
