### ISSUE TITLE
Draft blog pages are built on material 9.3.1

### ISSUE THREAD

**Issue by vlebert** [squidfunk/mkdocs-material#6000]
### Context

This bug appeared by itself on netlify build (I did not pin the version). After a few test the bus is present on 9.3.1 while 9.2.5 don't build the draft pages as expected

### Bug description

Blog pages is built while having `draft: true` metadata.

The blog page is listed in navigation but not visible in blog index (list of excerpts)

![digi-studio 2023-09-13 at 19 46 05](https://github.com/squidfunk/mkdocs-material/assets/49779177/64ff6eb5-825e-4ea8-89e4-f1c03222dcf2)

![digi-studio 2023-09-13 at 19 46 42](https://github.com/squidfunk/mkdocs-material/assets/49779177/e963932e-6297-4ad7-86fa-3d80d29d6080)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/?h=draft#drafts

### Reproduction

[9.3.1-blog-draft-actualy-built.zip](https://github.com/squidfunk/mkdocs-material/files/12600465/9.3.1-blog-draft-actualy-built.zip)

### Steps to reproduce

1. Just `mkdocs build` the attached reproduction zip. Post2 should be built while noted as draft

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and for providing the excellent reproduction. Indeed, posts that were marked as drafts got populated nonetheless. Fixed in ef5a04a32, which will now exclude the post prior to evaluating whether it's a draft or not.

**Comment by squidfunk** [comment]
Released as part of [9.3.2](https://squidfunk.github.io/mkdocs-material/changelog/#9.3.2).
