### ISSUE TITLE
Contributor avatar displays in square shape until hovered over

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#6001]
### Description

The avatars of the page contributors display in a square shape at the bottom of the page. When you then hover over them do they change their shape to a circle, without any transition.

Avatar displayed:
![grafik](https://github.com/squidfunk/mkdocs-material/assets/11576465/89787d94-a79e-4b56-b79c-ca5ebd4db7f4)

Avatar when hovered over:
![grafik](https://github.com/squidfunk/mkdocs-material/assets/11576465/0740b7f7-dca8-446e-8c4f-04f573233ea6)

### Related links

- [Getting Started](https://squidfunk.github.io/mkdocs-material/getting-started/)

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by Prakhar301101** [comment]
Do you want the avatars to be displayed in a square shape and on hover change their shape to circle with transition?
As of now they are displayed in a circle and when I hover over it just changes color and gets grows a little

**Comment by squidfunk** [comment]
Thanks for reporting. However, this should not be a documentation issue but a bug report. There's essential information missing, including in which browser this is happening. It's not happening in my browser, so you seem to be using another browser that exhibits this behavior. We kindly ask you to create a proper issue with a minimal reproduction, and please stop misusing the issue templates. Choose the right template for the thing you want to report.

**Comment by squidfunk** [comment]
Thanks @vedranmiletic – should be fixed in [`d322e49`](https://github.com/squidfunk/mkdocs-material-insiders/commit/d322e4979194e6aaa3d6578b93046c353325eec5). It seems to be a recent bug in Firefox where setting `border-radius` without `border` on an image does not apply the rounding. Hoisting the property one level gets rid of the issue:

**Comment by squidfunk** [comment]
Released as part of [9.3.2](https://squidfunk.github.io/mkdocs-material/changelog/#9.3.2).
