### ISSUE TITLE
Conventions page lacks "Multiple instances" indicator

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#6018]
### Description

The Conventions page misses the Symbol used for "Multiple Instances".

### Related links

- [Conventions](https://squidfunk.github.io/mkdocs-material/conventions/)

### Proposed change

Add the missing symbol

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. Added in d373e7a7e.
