### ISSUE TITLE
Update Slovenian translations

### ISSUE THREAD

**Issue by dkalsan** [squidfunk/mkdocs-material#6037]
### Translations

```Jinja
{% macro t(key) %}{{ {
  "language": "sl",
  "action.edit": "Uredi stran",
  "action.skip": "Skoči na vsebino",
  "action.view": "Prikaži izvorno stran",
  "announce.dismiss": "Ne prikaži več",
  "blog.archive": "Arhiv",
  "blog.categories": "Kategorije",
  "blog.categories.in": "v",
  "blog.continue": "Nadaljuj z branjem",
  "blog.draft": "Osnutek",
  "blog.index": "Nazaj na kazalo",
  "blog.meta": "Metapodatki",
  "blog.references": "Sorodne povezave",
  "clipboard.copy": "Kopiraj v odložišče",
  "clipboard.copied": "Kopirano v odložišče",
  "consent.accept": "Sprejmi",
  "consent.manage": "Uredi nastavitve",
  "consent.reject": "Zavrni",
  "footer": "Glava",
  "footer.next": "Naslednja stran",
  "footer.previous": "Prejšnja stran",
  "header": "Noga",
  "meta.comments": "Komentarji",
  "meta.source": "Izvorna koda",
  "nav": "Navigacija",
  "readtime.one": "Čas branja: 1 min",
  "readtime.other": "Čas branja: # min",
  "rss.created": "RSS vir",
  "rss.updated": "RSS vir posodobljene vsebine",
  "search": "Iskanje",
  "search.placeholder": "Išči",
  "search.share": "Deli",
  "search.reset": "Počisti",
  "search.result.initializer": "Inicializacija iskanja",
  "search.result.placeholder": "Vpiši iskalni niz",
  "search.result.none": "Ni zadetkov",
  "search.result.one": "1 zadetek",
  "search.result.other": "# zadetkov",
  "search.result.more.one": "Še 1 na tej strani",
  "search.result.more.other": "Še # na tej strani",
  "search.result.term.missing": "Manjka",
  "select.language": "Izberi jezik",
  "select.version": "Izberi različico",
  "source": "Pojdi na repozitorij",
  "source.file.contributors": "Contributors ⬅️",
  "source.file.date.created": "Ustvarjeno",
  "source.file.date.updated": "Zadnja posodobitev",
  "tabs": "Zavihki",
  "toc": "Kazalo",
  "top": "Nazaj na vrh"
}[key] }}{% endmacro %}
```

### Before submitting

- [X] I've checked the list of [available languages](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language) for existing translations.
- [X] I assure that the translations are accurate to the best of my knowledge.
- [ ] __Optional__: I want to integrate this translation myself and create a pull request following the [contribution guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md).

**Comment by dkalsan** [comment]
Is the word linked to `source.file.contributors` used in the context of a blog or code?

**Comment by alexvoss** [comment]
As far as I can tell this is part of the [git-authors plugin](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-authors), which is available in the insiders edition. So, we are talking about people who have contributed to the documentation. That could be any page, not just blog posts. Hope this helps.

**Comment by squidfunk** [comment]
Jep, @alexvoss is correct. The translation is used here:

<img width="474" alt="Bildschirm­foto 2023-09-19 um 08 40 09" src="https://github.com/squidfunk/mkdocs-material/assets/932156/99735a01-b9db-4d54-8ae4-1c226762cfa7">

We'll soon provide a more detailed explanation where translations are used to make it easier for translators to assess the context of a translation ☺️

**Comment by squidfunk** [comment]
So, thanks for providing the translations! We already added the translations you provided in 432ba9e, as we're about to issue a new release and want to ship them now. We're happy to add the contributors translation in the next release then ☺️

**Comment by squidfunk** [comment]
Released as part of 9.3.2. As said, if you provide the missing translation, we'll add it to 9.3.3 ☺️

**Comment by dkalsan** [comment]
Ah I see, thanks a lot for the clarification! Unfortunately I can't seem to think of a good translation for this :sweat_smile: The closest would be 'soavtorji', but that's more along the lines of 'co-authors'... Maybe somebody else chimes in with a better suggestion

As for the detailed explanations, those will indeed be very helpful :)

**Comment by squidfunk** [comment]
No worries! Maybe someone else has a good idea. Nonetheless, we can also start with "co-authors", if you think it's an okayish fit and improve it once somebody comes up with a better translation, if there is ☺️

**Comment by dkalsan** [comment]
Yeah it fits well enough, let's go with this for now - I added it to #6067
