### ISSUE TITLE
Description of setting up blog is missing addition of nav entry

### ISSUE THREAD

**Issue by paulmelis** [squidfunk/mkdocs-material#6039]
### Description

As far as I can tell you need to add an entry to the `nav` section of your config file to make the blog plugin work, e.g.

```
nav:
  - Blog:
      - blog/index.md
```

Without this entry I get a `StopIteration` exception somewhere deep in the plugin code:
```
  File "/home/melis/courses/blender-course/env/lib/python3.11/site-packages/material/plugins/blog/plugin.py", line 690, in _attach_to
    tail = next(item for item in reversed(items) if isinstance(item, Page))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

But the only reference I see to the `nav` section in the docs is under https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#adding-pages, but nowhere in the general setup instructions for the blog plugin.

### Related links

- [blog plugin reference](https://squidfunk.github.io/mkdocs-material/plugins/blog/)
- [blog setup instructions](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog)

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. The requirement to add a navigation entry was lifted in 9.2.0, but there might still be bugs. Thus, this is not a documentation issue, but a bug. Please create a new issue with a [bug report](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) and a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), and we're happy to fix it.
