### ISSUE TITLE
Links to blog templates are broken

### ISSUE THREAD

**Issue by paulmelis** [squidfunk/mkdocs-material#6040]
### Description

The links to `blog.html` and `blog-post.html` templates on the [Setting up a blog](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#custom-index-pages) page are broken and give a 404. Probably because they point to the insider repo.

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#custom-index-pages

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, we can now point them to the community editions as the blog plugin is public now, thanks to our awesome sponsors! Fixed in 819fa360a.
