### ISSUE TITLE
[regression] Numbered annotations don't render correctly

### ISSUE THREAD

**Issue by llucax** [squidfunk/mkdocs-material#6042]
### Bug description

Using [annotations with numebers](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#annotations-with-numbers) broke starting from 9.2.0.

Up to 9.1.21:

![image](https://github.com/squidfunk/mkdocs-material/assets/1031485/ab11934f-cc9c-4b7c-8def-4237f0f80121)

9.2.0 - 9.2.6:

![image](https://github.com/squidfunk/mkdocs-material/assets/1031485/ed5cfd02-f6e7-417d-aa86-ad67cf783883)

9.2.7+:

![image](https://github.com/squidfunk/mkdocs-material/assets/1031485/a1142d22-aea1-4a4d-b64d-078539e57f19)

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#annotations-with-numbers

### Reproduction

[9.3.2-material-annotations-bug.zip](https://github.com/squidfunk/mkdocs-material/files/12657501/9.3.2-material-annotations-bug.zip)

### Steps to reproduce

1. Unzip
2. `mkdocs serve`
3. Go to http://127.0.0.1:8000/

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment]
Thanks for the reproduction, I will have a look and get back to you.

**Comment by alexvoss** [comment]
A quick fix would be to add a width like so:

```css
.md-typeset .md-annotation__index {
  width: 4ch;
}
```
This does not restore the original behavior, though. I am looking at the differences between 9.1.21 and the current version to see what else can be done. The annotation icon is produced using CSS, so it should be possible to revert to the original behavior by including more stuff in `extra.css`

**Comment by llucax** [comment]
I can confirm that adding that makes it look like between versions 9.2.0-9.26, thanks. I actually don't mind having the number next to the `(+)`, if that makes keeping backwards compatibility easier though. To be honest I'm not even sure if I like it better or not :D

**Comment by llucax** [comment]
So I guess the broader question is if using numbered annotations will be still officially supported and if there is any way to have tests to avoid regressions in the future, I guess if `mkdocs-material` doesn't have some visual golden tests it would be difficult to test for this.

**Comment by alexvoss** [comment]
That's great. I had a look at the differences and they are non-trivial. I will hold fire on further work on this for now. Perhaps @squidfunk can weigh in here and let us know where he thinks this should go. In the meantime, I bet I will pick up more CSS/SCSS skills and will be in a better place to tackle this.

**Comment by llucax** [comment]
Thanks again for having a look and the quick workaround. As I said, for me this is good enough, if you feel there are more important things to work on, I'm fine with closing it (probably after updating the docs to include that in the custom CSS, I can even offer to send a PR for that.

**Comment by llucax** [comment]
Fair enough, thanks for looking into this @alexvoss and @squidfunk
