### ISSUE TITLE
Please add mkdocs-glightbox  plugin in requrements.txt file

### ISSUE THREAD

**Issue by kiransterling** [squidfunk/mkdocs-material#6044]
### Context

Please add mkdocs-glightbox  plugin in requrements.txt file. I am using squidfunk/mkdocs-material docker image for my doc build.

pip install mkdocs-glightbox

plugins:
   - glightbox

### Description

Please add mkdocs-glightbox  plugin in requrements.txt file. I am using squidfunk/mkdocs-material docker image for my doc build.

pip install mkdocs-glightbox

plugins:
   - glightbox

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

This is required for one of my feature

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. We're currently not considering adding more optional dependencies to the Docker image, as it increases the size of the image, slowing down every pull and build. You can extend the image and add the third-party plugins that you need in your specific case easily, [as stated in our documentation](https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker-material-for-mkdocs):

```
FROM squidfunk/mkdocs-material
RUN pip install mkdocs-glightbox
```
