### ISSUE TITLE
404 on Icons and Emojis search fields in the documentation website

### ISSUE THREAD

**Issue by SimonMarquis** [squidfunk/mkdocs-material#6053]
### Description

A *very recent* change (probably https://github.com/squidfunk/mkdocs-material/commit/56b96b4d799174d48d36613d70ffac9b964171cc) broke the [icons/emojis search field](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search):

<img width="353" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/1921278/0010f2e8-c2db-413d-9735-b08da2787edc">

### Related links

- [icons/emojis search field](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search)

### Before submitting

- [X] I have read and followed the [documentation issue reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the described sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks, for reporting. Yes, definitely related to the latest restructuring. Fixed in 039207305.

**Comment by squidfunk** [comment]
Deployment went through – up and running again!

<img width="726" alt="Bildschirm­foto 2023-09-20 um 15 11 28" src="https://github.com/squidfunk/mkdocs-material/assets/932156/8ec1d289-41c2-4974-a846-5508606b2b45">
