### ISSUE TITLE
Hero scrollbar

### ISSUE THREAD

**Issue by carlosperate** [squidfunk/mkdocs-material#606]
## Description

As discussed in https://github.com/squidfunk/mkdocs-material/pull/290#issuecomment-346314792 about the new Hero feature:

In Firefox 57.0, during the scroll-up resize, the top area momentarily shows scrollbars.

There is also a "last second" shift in position of the Yes, this is set via Metadata text.

### Expected behavior

No scrollbar, no "last second" jump.

### Actual behavior

![hero](https://user-images.githubusercontent.com/4189262/33123806-16e36506-cf73-11e7-8d65-f04690eb9dd6.gif)

### Steps to reproduce the bug

As per gif.

### Package versions

https://squidfunk.github.io/mkdocs-material/extensions/metadata/

### Project configuration

https://squidfunk.github.io/mkdocs-material/extensions/metadata/

### System information

https://squidfunk.github.io/mkdocs-material/extensions/metadata/

**Comment by squidfunk** [comment]
Fixed in #608

**Comment by squidfunk** [comment]
Released as part of 2.2.0.
