### ISSUE TITLE
Incorrect rendering of code blocks inside lists

### ISSUE THREAD

**Issue by PL-SalvadorFandino** [squidfunk/mkdocs-material#6063]
### Bug description

When code blocks are included inside list items, they are not rendered correctly. New lines and indentation is ignored.

For instance, the following codecode:

```markdown
1. Some test.

    ```
    Some code
    goes here
    in three lines
    ```
```

It is rendered by, for instance, GitHub, in this way:

1. Some test.

    ```
    Some code
    goes here
    in three lines
    ```

And that is what I see when using mkdocs-material:

![image](https://github.com/squidfunk/mkdocs-material/assets/113588360/ae22e417-e667-4de4-bebf-333783228a74)

### Related links

I didn't find anything related.

### Reproduction

[9.4.0-bad-code-in-lists.zip](https://github.com/squidfunk/mkdocs-material/files/12697956/9.4.0-bad-code-in-lists.zip)

### Steps to reproduce

1. ```mkdocs serve```

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment]
Thanks for the reproduction. The Markdown rendering is down to [python-markdown](https://python-markdown.github.io/), which renders the same result when run from the command-line:

```
$ python -m markdown index.md 
<h1>Material Bug</h1>
<p>This is a list:</p>
<ol>
<li>
<p>Some test.</p>
<p><code>Some code
goes here
in three lines</code></p>
</li>
<li>
<p>Bla bla bla</p>
</li>
</ol>
```

If you indent the code segment more you get the desired output. I guess it needs to be indented relative to the list, not to the beginning of the line?

**Comment by PL-SalvadorFandino** [comment]
It seems it is an old issue (missing feature?) in `python-markdown`: https://github.com/Python-Markdown/markdown/issues/53

A workaround is to not use fenced blocks. For instance, the following markdown is handled correctly:

```markdown

1. Some test.

        # <-- indented by 8 spaces!
        for i in foo:
          print("foo")
```

But then the issue is that there is no way to hint the parser about the programming language being used in the code block, and so, syntax highlighting doesn't work there.

I have tried several ways suggested over the internet (`:::python', `#!python`, ``) but so far, have not been able to find anything that works.

Anyway, I understand that the issue is outside the scope of this project and so I am going to close it.

@squidfunk: Thank you for your promptly reply, your help and for this fantastic project!!!

**Comment by squidfunk** [comment]
Props go to @alexvoss, not to me 😉 If you follow his advice, you get the desired output and can hint the language.

**Comment by PL-SalvadorFandino** [comment]
Oops, right, then, thanks @alexvoss, :-)

In any case, indenting the code block more does not really work!

Well, you get a code block, but not a **fenced** code block.

See the following example:

        1. three spaces

           ```
           fenced
           block
           ```

        3. eight spaces

                ```
                not fenced!
                notice the triple quote in the output!
                ```

Now, lets GitHub render it:

1. three spaces

   ```
   fenced
   block
   ```

3. eight spaces

        ```
        not fenced!
        notice the triple quotes in the output!
        ```

The result with mkdocs/python-markdown is the same.

**Comment by alexvoss** [comment]
Sorry, I did miss the difference in the output, so what I suggested is not actually a solution. 

It does look like fixing this was on the python-markdown roadmap at some point for 3.0 but seems to have been taken off again. We are at 3.4.4 and the issue has the `someday-maybe` label. I do wonder if any changes to the code base have since made it more likely that this will be addressed. Might be worth asking?

**Comment by squidfunk** [comment]
Okay, so I took a look at the example – I suggest to follow our recommendations: to use [SuperFences](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#superfences). It fixes many of the oddities of the Markdown parser and might also solve your problem. Here's our [recommended configuration](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration):

``` yaml
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
```

**Comment by facelessuser** [comment]
It should be noted that the `fenced_code` extension in Python Markdown mentions it only supports fences in root level. Only SuperFences supports nested fenced code.

Also, if you ever run into issues related to SuperFences, please note the specifics with formatting when using SuperFences: https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#nested-fence-format.

**Comment by PL-SalvadorFandino** [comment]
Yes, using `superfences` fixes the issue!
