### ISSUE TITLE
blog docs missing important options

### ISSUE THREAD

**Issue by StefanoCecere** [squidfunk/mkdocs-material#6070]
### Description

i couldn't find reference to these options:
```
  - blog:
      post_url_date_format: yyyy
      post_url_format: "{date}/{slug}"
```

### Related links

https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/

### Proposed change

add these options to Configuration section

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. We moved all options to [our new plugins](https://squidfunk.github.io/mkdocs-material/plugins/) section. You can find the options for the blog plugin [here](https://squidfunk.github.io/mkdocs-material/plugins/blog/).

The next step is to restructure our setup guide, and link to the plugin pages, which is something we'll be doing in the coming weeks. In the meantime, please always consult the plugins section. The setting up guide also already links to it.

**Comment by squidfunk** [comment]
Additionally, I'm not sure why you didn't find them, because you can find it [by using the search](https://squidfunk.github.io/mkdocs-material/?q=post_url_date_format):

<img width="608" alt="Bildschirm­foto 2023-09-24 um 10 32 26" src="https://github.com/squidfunk/mkdocs-material/assets/932156/33088435-d85c-44a4-a89e-f960d6867c27">

**Comment by StefanoCecere** [comment]
you are right.. i was just searching inside https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/ and the sentence "For a list of all settings, please consult the [plugin documentation](https://squidfunk.github.io/mkdocs-material/plugins/blog/)." isn't well highlighted

(sorry, i was used to "old" docs)

**Comment by squidfunk** [comment]
> "For a list of all settings, please consult the [plugin documentation](https://squidfunk.github.io/mkdocs-material/plugins/blog/)." isn't well highlighted

Well, it's directly below the basic configuration 😉

<img width="623" alt="Bildschirm­foto 2023-09-24 um 16 44 39" src="https://github.com/squidfunk/mkdocs-material/assets/932156/56e9ca3c-b821-4d7f-91a0-47b0444d57a2">
