### ISSUE TITLE
Additional dependencies for development

### ISSUE THREAD

**Issue by alexvoss** [squidfunk/mkdocs-material#6085]
### Description

On the [page on setting up a development environment](https://squidfunk.github.io/mkdocs-material/customization/#environment-setup), two additional dependencies need to be added, I think:

```
pip install mkdocs-rss-plug
pip install 'mkdocs-material[imaging]'
```

After installing these, I can build the documentation again.

### Related links

- [Environment Setup](https://squidfunk.github.io/mkdocs-material/customization/#environment-setup)

### Proposed change

add those additional dependencies required to build the documentation (as part of testing that the theme is working)

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by alexvoss** [comment]
Ok, I see what I did there. I was trying to produce a pull request for functionality, so was using the Insiders edition. Should the development environment not support both? If so then we would also need a mention of `libcairo` and any other library dependencies. If the recommended dependencies do the trick then all the better!

**Comment by squidfunk** [comment]
Yes, we can feature both, but must then also explain and link to the [image processing](https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/) requirements guide. You could just create content tabs for both editions, similar to what we're doing in our [publishing guide](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions-material-for-mkdocs).

**Comment by squidfunk** [comment]
For explanation:

```
Community
  recommended

Insiders
  recommended
  imaging
    libcairo
    pngquant
```

We should keep it as simple as possible and only install what's absolutely required.

**Comment by squidfunk** [comment]
Resolved via 699097679313b6e1d8dc508ed9a147bc46ba9df9 by @alexvoss – love the new [environment setup guide](https://squidfunk.github.io/mkdocs-material/customization/#environment-setup)!

**Comment by squidfunk** [comment]
By the way, one thing I noticed: this can likely be shortened to:

```
pip install -e ".[recommended]"
pip install nodeenv
```

... and:

```
pip install -e ".[recommended, imaging]"
pip install nodeenv
```

This will make sure to resolve the optional dependencies from the local `project.toml`, and not from the one that is distributed as part of the package, which I think will first be downloaded. Can you confirm, @alexvoss?

**Comment by alexvoss** [comment]
I can confirm that this works for me, for both insider and public. Specifically, I ran through the development environment setup and saw no problems. Not sure how I would tell where pip gets the dependencies from? I tried running with `-V` but am not sure how to interpret the results.

**Comment by squidfunk** [comment]
`pip` will look into `pyproject.toml`, install the project as such and then the optional dependencies as specified. I think it is safe to shorten the instructions. This will also allow us to test the installation of new optional dependencies without publishing the project. If you uninstall `mkdocs-material` in your local virtual environment:

```
$ pip install -V "mkdocs-material[recommended]"
Collecting mkdocs-material[recommended]
  Downloading mkdocs_material-9.4.4-py3-none-any.whl (8.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 11.4 MB/s eta 0:00:00
Requirement already satisfied: babel~=2.10 in ./venv/lib/python3.11/site-packages (from mkdocs-material[recommended]) (2.12.1)
...
```

`pip` looks into its cache, and if it's not there will download `mkdocs-material` to resolve the optional dependencies.

**Comment by alexvoss** [comment]
Ok, I can see that and this could well be the source of issues. It's something you will just put in, right? I have other stuff in the pipeline, so no need to do too many iterations with PR for stuff that is already discussed.

In the longer run, will the `projects.toml` file become the single source of information for the project and tools like `pip`? I note that there is also a `setup.py` and a `requirements.txt`. For someone coming from the Java world and working with Gradle, this seems like unnecessary duplication. How all that stuff works in the Python world is still a bit of a mystery to me, tbh. Might need to read those Python books I bought from Humble Bundle the other day.

**Comment by squidfunk** [comment]
No worries, I'll take care of it.

> In the longer run, will the projects.toml file become the single source of information for the project and tools like pip

Yes and no. We should still source our required dependencies from `requirements.txt` to be backward compatible, AFAICT. `setup.py` is only there to correctly resolve usage statistics for GitHub, as its comment also say. So, to sum up:

- `requirements.txt`: lowest common denominator to define essential dependencies
- `pyproject.toml`: project setup, test setup (in the making), optional dependencies and project metadata
- `setup.py`: only for GitHub
