### ISSUE TITLE
Blog post metadata overlaps with footer on small screens

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#6094]
### Bug description

The blog metadata is placed in front of the footer on small screens (1219px and less). It happens both on the official docs and in a minimal reproduction:

| mkdocs-material docs | Reproduction |
| - | - |
| ![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/5033b53b-1813-4da5-8fa7-8aadb300f8eb) |![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/ad55afc7-5350-4a43-b552-c038ebd476ce) |

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Setting up a blog](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/)

### Reproduction

[9.4.2-blog-metadata-small-screen-footer.zip](https://github.com/squidfunk/mkdocs-material/files/12738598/9.4.2-blog-metadata-small-screen-footer.zip)

### Steps to reproduce

1. Start the reproduction site
2. Go to http://localhost:8000/blog/2023/01/31/lege-est-in-sit-est/
3. Reduce the browser's viewport width to less than 1220px
4. Scroll to the footer section

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Fixed in 015685f42. We're planning a refactoring of the blog post layout in the near future, so this is likely going to change, but for the time being, we improved the layout to look like the following on mobile and tablet:

<img width="433" alt="Bildschirm­foto 2023-09-30 um 12 19 41" src="https://github.com/squidfunk/mkdocs-material/assets/932156/f4ac5fa0-8fa8-4019-960d-23e39d0589c4">

**Comment by sisp** [comment]
Excellent! Thank you very much for the prompt fix! :pray:

**Comment by squidfunk** [comment]
Released as part of [9.4.3](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.3).
