### ISSUE TITLE
Search: code indentation lost in search index

### ISSUE THREAD

**Issue by iBug** [squidfunk/mkdocs-material#6104]
### Bug description

If a code block is contained in an admonition, when this code block comes up in the search result, any indentation is lost.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#anchor-links)

### Reproduction

[9.4.2-test.zip](https://github.com/squidfunk/mkdocs-material/files/12774799/9.4.2-test.zip)

### Steps to reproduce

The easier way: Searching for `slugify` in the official documentation, and look for this result:

![image](https://github.com/squidfunk/mkdocs-material/assets/7273074/ca72804a-3dfb-431c-82bc-9b37dd823347)

The (entirely unnecessarily) more complex way: Using the supplied ZIP, search for `test` and see how the two results differ. `index.md` is unaffected while `test.md` is broken (in the search results).

### Browser

Browser-agnostic

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. We'll look into it. Regarding reproductions, [our bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#reproduction) explains why we need them:

> Why we need this: if an issue contains no minimal reproduction or just a link to a repository with thousands of files, the maintainers would need to invest a lot of time into trying to recreate the right conditions to even inspect the bug, let alone fix it.

Minimal reproductions make our life easier, allowing us to fix bugs quicker. Thank you for providing one.

**Comment by squidfunk** [comment]
So, in fact, [all indentation is currently lost](https://squidfunk.github.io/mkdocs-material/?q=automatic+dark+mode) for code blocks in search – not all in admonitions. We'll look into it.

**Comment by squidfunk** [comment]
Bisection leads to the insight that the error was introduced between 9.0.2 and 9.0.3, specifically in https://github.com/squidfunk/mkdocs-material/commit/81e7b8c7fc53d32c8a8730ae68614d8925388782.

**Comment by squidfunk** [comment]
Fixed in 8299f1d3a. The whitespace collapsing logic was triggering the problem.

**Comment by squidfunk** [comment]
Released as part of [9.4.3](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.3).
