### ISSUE TITLE
Use correct `lastmod` date in generated `sitemap.xml`

### ISSUE THREAD

**Issue by thesuperzapper** [squidfunk/mkdocs-material#6107]
### Context

Currently, we are not using the `lastmod` date correctly in the generated `sitemap.xml`, as we are simply using the latest date for all pages, rather than the date they were actually modified.

This will hurt SEO for websites made with MkDocs Material, because search engines start ignoring `lastmod` for making decisions about re-indexing pages if they see the website is not correctly using it.

Here is a blog post from Bing about how this impacts SEO:

- https://blogs.bing.com/webmaster/february-2023/The-Importance-of-Setting-the-lastmod-Tag-in-Your-Sitemap

### Description

Since we already use [`git-revision-date-localized` plugin](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-dates) to determine the true "last updated" time for the content of a page, we could use the same logic when generating `sitemap.xml`.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

Improving SEO (although really long-term users of MkDocs Material are unlikely to benefit for a while, because search engines will already have ignored their `lastmod` dates).

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for reporting. This is not an issue with Material for MkDocs, but must be taken upstream, either to MkDocs (which generates `sitemap.xml`) and the aforementioned `git-revision-date-localized-plugin`. We only consume the `sitemap.xml` for functionalities like [instant navigation](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading), but never touch it. Closing as upstream.

**Comment by thesuperzapper** [comment]
@squidfunk I have raised an issue with `git-revision-date-localized-plugin` suggesting how they might include this feature: 
- https://github.com/timvink/mkdocs-git-revision-date-localized-plugin/issues/120

However, as the fix is quite simple (when `git-revision-date-localized-plugin` is installed), perhaps MkDocs Material wants to include my example `sitemap.xml` theme override in the docs.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
{%- for file in pages -%}
    {% if not file.page.is_link and (file.page.abs_url or file.page.canonical_url) %}
    <url>
         <loc>{% if file.page.canonical_url %}{{ file.page.canonical_url|e }}{% else %}{{ file.page.abs_url|e }}{% endif %}</loc>
         {#- NOTE: we exclude `lastmod` for pages using a template, as their update time is not correctly detected #}
         {%- if not file.page.meta.template and file.page.meta.git_revision_date_localized_raw_iso_datetime %}
         <lastmod>{{ (file.page.meta.git_revision_date_localized_raw_iso_datetime + "+00:00") | replace(" ", "T") }}</lastmod>
         {%- endif %}
         <changefreq>daily</changefreq>
    </url>
    {%- endif -%}
{% endfor %}
</urlset>
```

The only caveat is that I am making two assumptions in the above:

- that no `lastmod` should be set for pages using a `template` (which is primarily used for things like homepages)
- that the user's `git-revision-date-localized-plugin` has not been configured with a custom timezone (which means everything is UTC or `+00:00`)

**Comment by timvink** [comment]
It's also out of scope for `git-revision-date-localized-plugin`; I don't feel that plugin should also do (automatic) overrides.

Just for reference, if Mkdocs for Material ever considers 'templating' `sitemap.xml`, we could only override if the plugin is available, like we already do here:

https://github.com/squidfunk/mkdocs-material/blob/2742a707cca63b52d17466d0b918f8c411cf99b3/src/templates/partials/source-file.html#L28-L29

**Comment by squidfunk** [comment]
@timvink is it possible for themes to simply override `sitemap.xml`? If that works from MkDocs perspective, we could definitely give it a try. My knowledge is that it can't be done, but I've just checked the MkDocs source code and it might be treated the same as `404.html`, which would allow to do it. However, I'm not sure what plugins this might break.

**Comment by timvink** [comment]
I don't know, I have never tried.

> However, I'm not sure what plugins this might break.

I feel you. Another reason I would feel weary picking this one up. My approach would probably be to write some code to clone the [220 known plugins](https://github.com/mkdocs/catalog ) and do a search for `sitemap` :)
