### ISSUE TITLE
Related links section in blog article is misaligned on small screens

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#6139]
### Bug description

The "Related links" section of the blog metadata on the https://squidfunk.github.io/mkdocs-material blog is not correctly left-aligned with other metadata and the rest of the page on small screens (less than 1220px width):

![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/743ed40b-3a72-40ec-affa-d6a3bd338550)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[Related links in blog articles is an Insiders feature](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#adding-related-links), so I can't provide a reproduction.

### Steps to reproduce

1. Open, e.g., https://squidfunk.github.io/mkdocs-material/blog/2023/09/22/using-git-sparse-checkout-for-faster-documentation-builds/ in your browser.
2. Reduce the viewport width to less than 1220px.
3. Scroll to the bottom of the page and observe the described misalignment.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in https://github.com/squidfunk/mkdocs-material-insiders/commit/ed9cf440acd2b734f14d3546f349e7520868180d and re-deployed:

<img width="395" alt="Bildschirm­foto 2023-10-05 um 17 14 17" src="https://github.com/squidfunk/mkdocs-material/assets/932156/130935f4-2c00-4b77-bc73-80973d9422f1">

**Comment by sisp** [comment]
You're welcome. :slightly_smiling_face:

**Comment by squidfunk** [comment]
Released as part of [9.4.4+insiders-4.21.1](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.42.1).
