### ISSUE TITLE
> لقد اتبعت النصائح من هذا [الموقع](https://squidfunk.github.io/mkdocs-material/creating-your-site/?h=vscode#minimal-configuration) . الآن المحتوى الخاص بي `.vscode/settings.json`هو:

### ISSUE THREAD

**Issue by Kordokareem** [squidfunk/mkdocs-material#6144]
> لقد اتبعت النصائح من هذا [الموقع](https://squidfunk.github.io/mkdocs-material/creating-your-site/?h=vscode#minimal-configuration) . الآن المحتوى الخاص بي `.vscode/settings.json`هو:
> 
> ```json
> {
>  ......
>     "yaml.schemas": {
>       "https://squidfunk.github.io/mkdocs-material/schema.json": "mkdocs.yml",
>     },
>     "yaml.customTags": [ 
>       "!ENV scalar",
>       "!ENV sequence",
>       "tag:yaml.org,2002:python/name:material.extensions.emoji.to_svg",
>       "tag:yaml.org,2002:python/name:material.extensions.emoji.twemoji",
>       "tag:yaml.org,2002:python/name:pymdownx.superfences.fence_code_format"
>     ]
>  ......
>  }
> ```
> 
> والمحتوى الخاص بي `mkdocs.yml`هو:
> 
> ```yaml
> ......
> not_in_nav: |
>   index.md
> ......
> ```
> 
> ثم ظهرت لي مشكلة من VSCode، "الخاصية not_in_nav غير مسموح بها."
> 
> كيف يمكن حلها؟

اتعلم اتت

_Originally posted by @Kordokareem in https://github.com/squidfunk/mkdocs-material/discussions/6129#discussioncomment-7201936_

**Comment by squidfunk** [comment]
Closed as spam. Blocked user.
