### ISSUE TITLE
overriding partials not happening

### ISSUE THREAD

**Issue by jodumont** [squidfunk/mkdocs-material#617]
Hi Everyone;

1st of all; thank for this awesome theme
2nd I'm new with python, mkdocs and jinga

## Description of the bug
When I try to overriding partials (like [explained here](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials)) my modification are not there

but when I modify the code directly in `./lib/python3.6/site-packages/material/partials/footer.html` it works.

```
        <a href="http://www.mkdocs.org" target="_blank">MkDocs</a>
        and
        <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">
          Material for MkDocs</a>
```
### Actual behavior
target="_blank" is not there

### Steps to reproduce the bug
```
cd ./
mkdir -p ./docs/theme/partials/
cp ./lib/python3.6/site-packages/material/partials/footer.html ./docs/theme/partials/footer.html
```
then...
- EDIT: `./docs/theme/partials/footer.html`
- SERVE: `mkdocs serve`
- BROWSE: [view-source](http://127.0.0.1:8000/) 
- SEARCH: `for _blank`

### Package versions
* Python: 3.6
* PIP: 9.0.1 (installed with --user pipenv)
* MkDocs: 0.17.2 (installed inside a virtenv)
* Material: 2.2.0 (installed inside the virtenv)

### Project configuration
``` yaml
...
theme:
  custom_dir: 'theme'
  name: 'material'
...
```

### System information
* OS: Fedora 27
* Browser: Firefox 57 without plugin but with DoNotTrack and Tracking Protection Always On

**Comment by davecap** [comment]
It may be because the `theme/` directory should be one level up (same level as `docs/`).

**Comment by jodumont** [comment]
as I read you're comment it make so much sense, I don't know why I didn't think to try that before posting my issue ;)

and now I'm revisiting the docs, I wonder when and how I understood to put my custom_dir inside docs.

anyway this is the solution

thanks for you're help!
