### ISSUE TITLE
Support for different custom logo for each palette scheme

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#6176]
### Context

I'd like to be able to set a different custom logo for each palette scheme.

### Description

It would be great if Material for MkDocs provided a way to explicitly set different logos for light and dark mode. Currently, only a single custom image file can be configured in `mkdocs.yml`. I imagine the `logo` setting could be extended to also support, e.g., an array of image files whose items get mapped to the corresponding items in the palette schemes array:

```yaml
theme:
  logo:
    - assets/logo-light.svg
    - assets/logo-dark.svg
  palette:
    - scheme: default
      # ...
    - scheme: slate
      # ...
```

Additional CSS would switch the visibility of the logo according to the active palette scheme. Also, some config validation would be useful to make sure the number of logo array items matches the number of palette array items.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Changing the logo and icons](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/)
- [Changing the colors](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/)

### Use Cases

See, e.g., https://opensource.siemens.com where a color logo is used for light mode and a white logo is used for dark mode.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! This was asked before, but we came to the conclusion that it makes no sense for us to generalize, because it does not generalize well enough. Usage would be prone to errors, as `logo` would now expect a list that mirrors the list in palette. Additionally, some plugins or hooks rely on `logo` pointing to an image, not to a list of images. It would be unclear to those downstream projects what to make of this.

However, it is absolutely trivial to add this functionality yourself! You can override the [`logo` partial](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/partials/logo.html) and add the functionality so that it fits your use case and configuration perfectly. Maybe something like:

``` jinja2
<img src="{{ config.theme.logo | url }}" alt="logo" class="logo-light" />
<img src="{{ config.theme.logo_dark | url }}" alt="logo" class="logo-dark" />
```

You can now add your logo in `config.theme.logo_dark` and [add CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) to only show the logo in a specific theme:

``` css
[data-md-color-scheme=default] .logo-dark {
  display: none;
}
[data-md-color-scheme=slate] .logo-light {
  display: none;
}
```

It's achievable with customization in less than 5 minutes.

**Comment by sisp** [comment]
Thanks for your feedback and suggestion on how to do it in userland. :ok_hand: Should be add your customization approach to the docs? Also, has there been a prior issue with a similar request? I haven't found one. If so, it would be great to reference it for future similar request.

**Comment by squidfunk** [comment]
No, the documentation is already so large (91 pages) that it is just unfeasible to add each and every possible customization. We will provide examples for the most common ones of which this isn't one, IMHO. Yes, there have been previous requests, and I thought you've used the search as stated in [our general issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/#before-creating-an-issue): 😉

- #2729 (with solutions)
- #5324

**Comment by sisp** [comment]
> I thought you've used the search as stated in [our general issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/#before-creating-an-issue): 😉

I actually did, _but_ I missed searching the discussions. :see_no_evil:

**Comment by alexvoss** [comment]
Would this make a good [example](https://github.com/mkdocs-material/examples) for how to customize the theme? We could have one about different things to do with logos and make this part of it. One reason I am asking is that this seems like such a straightforward to understand change that is, at the same time, not trivial. Also shows nicely the power of CSS and shows people that they do not need to write JavaScript for everything (thanks for @squidfunk taking good care to make customizations easy)

**Comment by squidfunk** [comment]
No, it's an edge case. In 7 years, it has been asked for 3 times. We should focus on the most common cases first. Before we add examples that cater to things that are clearly edge cases and we don't have on our documentation, we first need examples for all features we advertise on our documentation. That'll already keep us busy for months.

**Comment by alexvoss** [comment]
I agree in principle but it seems a very nice example of the power of customizing with CSS only. I will definitely put this into my backlog of things to consider. Looking at the [documentation for `extra.css`](https://squidfunk.github.io/mkdocs-material/customization/#additional-css), it does not link to examples but just mentions tweaking colors and changing spacing. 

I will not argue with you how often this specific case here has come up but generally, I think do do get questions about just how to deal with CSS customizations. I have seen people who were unfamiliar with the developer tools in their browsers, would not be able to interpret the SCSS in the code and generally struggle to understand just where and how they should change something. One thing that came up just recently, I think, was specificity. 

Giving people some idea of the power of CSS and providing some examples of how customizations can make use of the carefully designed system of classes, data attributes, etc. might help a lot of people. For someone who knows CSS well (I don't count myself as such a person, though I think I know the basics), the occasional example in the documentation (how to make the Twitter logo blue) will suffice but as more systematic introduction would be good. That is what an example could deliver. 

As always, just my 2p and I hope I have not holding the wrong end of the stick.

**Comment by squidfunk** [comment]
I absolutely agree that there are many happy users of this project with little to no knowledge of CSS, and we could empower them to learn a little CSS. Demonstrating what can be done with some basic CSS knowledge definitely provides value.

However (and this is a big one) – the current focus for improving our documentation must be to better show how to utilize existing functionality and configure Material for MkDocs to adhere to specific use cases. For this, we create examples and rewrite our documentation to be more use case centric. Further customizations is something we can discuss after we've done an entire pass on existing functionality, which I expect to be finished next year, earliest – it's quite a lot of work. FWIW, rewriting the plugin documentation took me several days. The immediate prime candidates for providing better documentation are on setting up a blog and building multi-lingual sites. These should be our absolute priority.

Don't get me wrong, I'm happy to better show what _can_ be done. I'm just trying to serve the most common use cases first and prioritize. The use case discussed here is rather exotic and should not be a priority. We need to watch our economics.
