### ISSUE TITLE
offline plugin loads shim from unpkg

### ISSUE THREAD

**Issue by 9Lukas5** [squidfunk/mkdocs-material#6181]
### Bug description

Up until the 9.1.x series the offline plugin didn't load any exernal resources, but from 9.2.x onwards it loads shim from unpkg.

Is this intentional?

### Related links

- [MkDocs-Material offline plugin](https://squidfunk.github.io/mkdocs-material/plugins/offline/)

### Reproduction

[9.4.5-offline-plugin-loads-shim.zip](https://github.com/squidfunk/mkdocs-material/files/12885281/9.4.5-offline-plugin-loads-shim.zip)

### Steps to reproduce

- install mkdocs 9.2.0 or newer
- enable offline plugin
- see shim loaded from external

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Yes, it is intentional. We don't bundle `iframe-worker`. If you want to bundle it, you have two options:

1. Download [`iframe-worker/shim`](https://unpkg.com/iframe-worker/shim) from unpkg, put it in `docs` and add it to `extra_javascript`
2. Enable the built-in [`privacy` plugin](https://squidfunk.github.io/mkdocs-material/plugins/privacy/) (currently only in Insiders), which will do exactly that for you

In fact, if we'd bundle `iframe-worker`, we only make it halt way to truly offline-capable documentation, because it's not the only resource that we would have to bundle. There's also Google Fonts, which is not possible to bundle at all. This is the very reason of the [`privacy` plugin](https://squidfunk.github.io/mkdocs-material/plugins/privacy/). If you don't want to sponsor, you can also wait for the plugin, as we expect it to be released pretty soon – it's in the next funding goal. If you want to help reach that goal, even better 😉

**Comment by squidfunk** [comment]
As a further explanation: previously, iframe worker was included into our application bundle, adding 650b (gzipped) to each and every Material for MkDocs, not matter if the offline plugin is used or not. This was the primary motivation – shaving off what is not necessary for the majority of use cases.

**Comment by 9Lukas5** [comment]
Hm ok, was confused as 9.0.x and 9.1.x didn't do this (at least for me) and after upgrading to the latest 9.x series it does

**Comment by squidfunk** [comment]
It's mentioned in the [9.2.0 release notes](https://squidfunk.github.io/mkdocs-material/changelog/#9.2.0):

> Automatically add iframe-worker polyfill when necessary in offline plugin

**Comment by 9Lukas5** [comment]
What am I missing now, bundling it myself? :monocle_face: 

![Bildschirmfoto vom 2023-10-12 20-44-53](https://github.com/squidfunk/mkdocs-material/assets/17082114/ac02d9d7-242a-4b60-84c8-99f159020910)
![Bildschirmfoto vom 2023-10-12 20-45-23](https://github.com/squidfunk/mkdocs-material/assets/17082114/e217b78e-2f84-48de-a67d-894b93f802c6)

**Comment by squidfunk** [comment]
You need to download it and fully qualify the path, i.e.:

``` yaml
extra_javascript:
  - docs/iframe-worker.js
```

Then in `docs/iframe-worker.js`, [put the contents of this file](https://unpkg.com/iframe-worker@1.0.3/shim/index.js):

``` js
"use strict";(()=>{function c(s,n){parent.postMessage(s,n||"*")}function d(...s){return s.reduce((n,e)=>n.then(()=>new Promise(r=>{let t=document.createElement("script");t.src=e,t.onload=r,document.body.appendChild(t)})),Promise.resolve())}var o=class extends EventTarget{constructor(e){super();this.url=e;this.m=e=>{e.source===this.w&&(this.dispatchEvent(new MessageEvent("message",{data:e.data})),this.onmessage&&this.onmessage(e))};this.e=(e,r,t,i,m)=>{if(r===`${this.url}`){let a=new ErrorEvent("error",{message:e,filename:r,lineno:t,colno:i,error:m});this.dispatchEvent(a),this.onerror&&this.onerror(a)}};let r=document.createElement("iframe");r.hidden=!0,document.body.appendChild(this.iframe=r),this.w.document.open(),this.w.document.write(`<html><body><script>postMessage=${c};importScripts=${d};addEventListener("error",ev=>{parent.dispatchEvent(new ErrorEvent("error",{filename:"${e}",error:ev.error}))})<\/script><script src=${e}?${+Date.now()}><\/script></body></html>`),this.w.document.close(),onmessage=this.m,onerror=this.e,this.r=new Promise((t,i)=>{this.w.onload=t,this.w.onerror=i})}terminate(){document.body.removeChild(this.iframe),onmessage=onerror=null}postMessage(e){this.r.catch().then(()=>{this.w.dispatchEvent(new MessageEvent("message",{data:e}))})}get w(){return this.iframe.contentWindow}};window.IFrameWorker=o;location.protocol==="file:"&&(window.Worker=o);})();
```

**Comment by 9Lukas5** [comment]
Ah, thanks, that hint helped find the correct thing:

it needs to be named `iframe-worker` _and_ instead being added to the extra javascript, it needs to go to the `extra.polyfills`. So this works now for me:

```yaml
extra:
  polyfills:
    - js/iframe-worker
```

Thanks for the help :)

**Comment by squidfunk** [comment]
Oops, you're right! It must be `polyfills`! Adjusted my comment above.
