### ISSUE TITLE
Image: Light and Dark Mode does not work with Privacy Plugin

### ISSUE THREAD

**Issue by tylernguyen** [squidfunk/mkdocs-material#6186]
### Bug description

[Images: Light and Dark Mode](https://squidfunk.github.io/mkdocs-material/reference/images/?h=image#light-and-dark-mode) does not work with [Privacy Plugin](https://squidfunk.github.io/mkdocs-material/plugins/privacy/?h=privacy).

When using external images, and with the Privacy plugin enabled. The `#only-light` and `#only-dark` does not work. Instead, both images will be shown regardless of the current scheme.

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/images/?h=images#light-and-dark-mode
- https://squidfunk.github.io/mkdocs-material/plugins/privacy/?h=privacy

### Reproduction

[9.4.5+insiders.4.42.1-images-and-privacy-plugin.zip](https://github.com/squidfunk/mkdocs-material/files/12899278/9.4.5%2Binsiders.4.42.1-images-and-privacy-plugin.zip)

### Steps to reproduce

1. Enable `attr_list` and  `md_in_html` under `markdown_extensions`
2. Enable `privacy` under `plugins`
3. Enable both `default` and `slate` color schemes.
4. Embed two images with `#only-light` and `#only-dark` appends. (The images comes externally of the repo)

With `privacy` enabled, both images will be shown. Without it, the expected behavior works.

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and the excellent reproduction! That made fixing this really simple. Fixed in [`f3106ee`](https://github.com/squidfunk/mkdocs-material-insiders/commit/f3106ee227d9915e33c847ba1942d94d1213e543).

**Comment by squidfunk** [comment]
Released as part of [9.4.6+insiders-4.42.2](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.42.2).

**Comment by tylernguyen** [comment]
Can you please check this fix?

The latest commit now returns `FileNotFoundError: [Errno 2] No such file or directory: '/docs/.cache/plugin/privacy/assets/external/*` if the external asset is already not downloaded.

This is using the same reproduction as above, with no `.cache` folder before start.
