### ISSUE TITLE
Add translations for German (Switzerland) (de-ch)

### ISSUE THREAD

**Issue by Andre601** [squidfunk/mkdocs-material#6192]
### Translations

```Jinja
{% macro t(key) %}{{ {
  "language": "de-ch",
  "direction": "ltr",
  "action.edit": "Seite bearbeiten",
  "action.skip": "Zu Inhalt springen",
  "action.view": "Quellcode der Seite anzeigen",
  "announce.dismiss": "Nicht erneut anzeigen",
  "blog.archive": "Archiv",
  "blog.categories": "Kategorien",
  "blog.categories.in": "in",
  "blog.continue": "Weiterlesen",
  "blog.draft": "Entwurf",
  "blog.index": "Zur Übersicht",
  "blog.meta": "Metadaten",
  "blog.references": "Weiterführende Links",
  "clipboard.copy": "In Zwischenablage kopieren",
  "clipboard.copied": "In Zwischenablage kopiert",
  "consent.accept": "Akzeptieren",
  "consent.manage": "Einstellungen verwalten",
  "consent.reject": "Ablehnen",
  "footer": "Fusszeile",
  "footer.next": "Nächste",
  "footer.previous": "Vorherige",
  "header": "Kopfzeile",
  "meta.comments": "Kommentare",
  "meta.source": "Quellcode",
  "nav": "Navigation",
  "readtime.one": "1 Min. Lesezeit",
  "readtime.other": "# Min. Lesezeit",
  "rss.created": "RSS Feed",
  "rss.updated": "RSS Feed von aktualisierten Inhalten",
  "search": "Suche",
  "search.placeholder": "Suche",
  "search.share": "Teilen",
  "search.reset": "Zurücksetzen",
  "search.result.initializer": "Inizialisiere Suche",
  "search.result.placeholder": "Suchbegriff eingeben",
  "search.result.none": "Keine passenden Dokumente",
  "search.result.one": "1 passendes Dokument",
  "search.result.other": "# passende Dokumente",
  "search.result.more.one": "1 weitere auf dieser Seite",
  "search.result.more.other": "# weitere auf dieser Seite",
  "search.result.term.missing": "Es fehlt",
  "select.language": "Sprache wählen",
  "select.version": "Version wählen",
  "source": "Zum Repository",
  "source.file.contributors": "Mitwirkende",
  "source.file.date.created": "Erstellt",
  "source.file.date.updated": "Letztes Update",
  "tabs": "Haubtnavigation",
  "toc": "Inhaltsverzeichnis",
  "top": "Zurück zum Anfang"
}[key] }}{% endmacro %}
```

### Country flag

:flag_ch:

### Before submitting

- [X] I've checked the list of [available languages](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language) for existing translations.
- [X] I assure that the translations are accurate to the best of my knowledge.
- [ ] __Optional__: I want to integrate this translation myself and create a pull request following the [contribution guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md).

**Comment by squidfunk** [comment]
Thanks for suggesting. How do those differ from the German translations we already have? Please understand that we usually don't do regional variations of translations, with Chinese and Brazilian Portuguese being the only exception.

**Comment by Andre601** [comment]
https://en.m.wikipedia.org/wiki/Swiss_German

(See "grammar" section. I can't link to it on mobile...)

Basically there is no ß, ever, and afaik some different words compared to german.

**Comment by squidfunk** [comment]
That page classifies it as a dialect. We currently don't consider adding dialects as languages. Other users might ask us to add Frankonian, Bavarian, and other German dialects then as well, which we will not do. Please use theme extension and [custom translations](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#custom-translations) to add the language on your installation. Also thanks for sharing, others can do so as well, if they wish.
