### ISSUE TITLE
Blog: show date of last update

### ISSUE THREAD

**Issue by robingenz** [squidfunk/mkdocs-material#6198]
### Context

I regularly publish blog posts about new Capacitor APIs ([Example](https://capawesome.io/blog/the-push-notifications-guide-for-capacitor/)). Sometimes these APIs change and I update the blog post accordingly. I want the reader to have a hint when the blog post was last updated so they don't get confused when the content has changed.

### Description

It would be useful if a blog post could display the date of the last update, so readers can see if anything has changed since it was published.

[Dev.to](https://dev.to/capawesome/announcing-the-capacitor-nfc-plugin-1550) displays it like this:

![grafik](https://github.com/squidfunk/mkdocs-material/assets/13857929/bc968071-e89d-4882-afb2-461325680fab)

### Related links

- https://dev.to/capawesome/announcing-the-capacitor-nfc-plugin-1550

### Use Cases

You could introduce a new property `updated_date` which contains the date of the last update and display it in the sidebar of a blog post.

```md
---
date: 2022-10-18
updated_date: 2022-12-10
---

# My Blog Post
```

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexvoss** [comment]
I assume you are aware of the [git-revision-date-localized](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin) plugin and how it can be used to display a creation and update date?

**Comment by squidfunk** [comment]
Thanks for suggesting. [This is already implemented](https://squidfunk.github.io/mkdocs-material/plugins/blog/#meta.date-update-date), albeit the documentation is a little hidden. We are going to revise the blog documentation and add examples in the coming weeks (cc @alexvoss). You can define an update date which is rendered in the blog overview via:

``` yaml
---
date:
  created: 2023-01-31 
  updated: 2023-02-01
---

# Post title
...
```

It is currently not rendered in the post overview to keep it concise, but you can certainly override the [`post.html` partial](https://github.com/squidfunk/mkdocs-material/blob/2742a707cca63b52d17466d0b918f8c411cf99b3/src/templates/partials/post.html#L42-L48) and add it by simply copying the logic from the creation date. We are going to revisit the blog templates at the beginning of next year, so in the mean time, please use customization ☺️

---

On a side note, this has been requested before:

- #5028
- #5733

Please make sure to use the search next time. Thank you!

**Comment by robingenz** [comment]
Thanks for the quick reply and sorry for creating a duplicate issue.
