### ISSUE TITLE
Projects plugin not working/not added

### ISSUE THREAD

**Issue by Koratsuki** [squidfunk/mkdocs-material#6205]
### Context

Iam using mkdocs for a project at school, and I run into a missing plugins error.

### Bug description

So, my question: Is the plugin added to the docker image?

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

Using the docker image and the config:

plugins:
  - projects

It(mkdocs.yml) gives me an error:

ERROR   -  Config value 'plugins': The "projects" plugin is not installed

Going to the doc, I read:

The projects plugin is built into Material for MkDocs and doesn't need to be installed.

### Steps to reproduce

See Reproduction section.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by iBug** [comment]
It's Insiders-only:

![image](https://github.com/squidfunk/mkdocs-material/assets/7273074/eb96d2c3-555c-419a-9fdb-6ada756ccfd3)

Martin should probably consider adding the version label to the top of the page if the entire feature is Insiders-only.

**Comment by squidfunk** [comment]
Thanks for reporting, and yes, it's currently in [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) and thus reserved to [sponsors](https://github.com/sponsors/squidfunk). We'll think of how we can better denote that a plugin is currently only in Insiders, but I'm not sure adding this to the top of the page will solve the confusion when people start using it. For example, the tags plugin has a whole boat load of options that are currently only in Insiders, so users will also try to use them regardless of it being in the community edition.
