### ISSUE TITLE
Provide support for Drupal.org custom instance of GitLab

### ISSUE THREAD

**Issue by davereid** [squidfunk/mkdocs-material#6218]
### Context

Drupal.org uses an internal instance of GitLab at https://git.drupalcode.org/

### Description

I recently started generating a mkdocs-material GitLab page for my https://git.drupalcode.org/project/helper project at https://project.pages.drupalcode.org/helper/ but realized the repository/edit detection is not at all working. I'd like to help contribute this feature to the project along with a custom Drupal icon.

### Related links

I searched and found no open or closed issues or discussions.

### Use Cases

This will benefit all Drupal.org users who want to create documentation for their projects.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! We're not considering adding integrations for specific GitLab installations. We just cannot commit to maintain it. There are several issues and discussions that talk about extending the repository detection logic, some of them with possible customization approaches. I searched for 3m:

- #5942
- #5157
- #5402
- #2307

There are definitely more, so if you use the search, you will find dozens of options how you can achieve this with a little customization ☺️
