### ISSUE TITLE
Git repo shows Github instead of actual repository name

### ISSUE THREAD

**Issue by Champe20** [squidfunk/mkdocs-material#6249]
### Bug description

In the mkdocs.yml file, I have the attribute `repo_url: https://github.com/Champe20/Compatibowl`. Though when I load the page via `mkdocs serve`, the git displays as shown in the below screenshot: 
![image](https://github.com/squidfunk/mkdocs-material/assets/117483128/a85e3268-48d8-4090-af43-f2d5184eccb1)

### Related links

- [relevant documentation page](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/)

### Reproduction

 
[9.4.6-repo_url-not-showing-name.zip](https://github.com/squidfunk/mkdocs-material/files/13177675/9.4.6-repo_url-not-showing-name.zip)

### Steps to reproduce

 Run `mkdocs serve` to view the site and it does not show the Repository name, and instead just shows "Github".

### Browser

Other

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment]
Hi, you need to set the repo name: [set the repo name](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository#repository-name)

**Comment by Champe20** [comment]
@alexvoss I apologize. I misinterpreted this line in the documentation.
> MkDocs will infer the source provider by examining the URL and try to set the repository name automatically. If you wish to customize the name, set [repo_name](https://www.mkdocs.org/user-guide/configuration/#repo_name) in mkdocs.yml:

**Comment by alexvoss** [comment]
No worries! If I had a penny for every time I have missed something...
