### ISSUE TITLE
Grid cards are cut off at the right on very small screens

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#6251]
### Bug description

On very small screens, e.g. iPhone SE (1st gen), grid cards are cut off at the right of the screen. The minimum screen width without cut-off or reduced right margin is 352px.

| Viewport width | Screenshot |
| - | - |
| 352px | ![352px](https://github.com/squidfunk/mkdocs-material/assets/2206639/6bf9bc6d-5286-4360-922f-ad98facbad6e) |
| 340px | ![340px](https://github.com/squidfunk/mkdocs-material/assets/2206639/e231be8c-8c1e-41ed-af92-92c9f94e5e16) |
| 330px | ![330px](https://github.com/squidfunk/mkdocs-material/assets/2206639/26302806-7903-4dbc-ace0-1e23a2a22a9e) |

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Using card grids](https://squidfunk.github.io/mkdocs-material/reference/grids/#using-card-grids)

### Reproduction

Card grids are an Insiders feature, so I'm afraid I can't provide a reproduction file. But the problem can be observed at https://squidfunk.github.io/mkdocs-material/setup/#site-structure.

### Steps to reproduce

1. Open https://squidfunk.github.io/mkdocs-material/setup/#site-structure in your browser.
2. Open your browser's dev tools and enable the device emulation mode ("Responsive Design Mode" on Firefox, "Toggle device toolbar" on Chrome).
3. Set your browser's viewport width to less than 352px and observe how the right margin of the grid cards reduces to the point at which the cards get cut off at the right.

Alternatively, if you have an iPhone SE (1st gen), open https://squidfunk.github.io/mkdocs-material/setup/#site-structure in your browser and observe the grid cards being cut off at the right.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment]
I'll have to leave @squidfunk to comment on the substance but I do wonder why you say it is not possible to submit a [reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/)? The `.zip` files contain only the project that shows the reported problem occurring. The filename will tell us that you are using insiders. For my part, I usually look at the `requirements.lock` before installing anything anyway, often pruning it first.

**Comment by sisp** [comment]
Don't I need access to the Insiders version of `mkdocs-material` to be able to create the reproduction? I'm not a sponsor ...

**Comment by alexvoss** [comment]
Ah, I see. That might make the process of checking that the reproduction actually produces the problem a bit difficult. I see that @squidfunk has already tagged this as needing investigation, so I guess he has looked at the documentation and found the effect.

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in [`8296f00`](https://github.com/squidfunk/mkdocs-material-insiders/commit/8296f006684c56b3c031fdeb3bd9bb7d6e122beb).

**Comment by squidfunk** [comment]
Released as part of [9.4.7+insiders-4.42.3](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.42.3).
