### ISSUE TITLE
Meta plugin does not configure blog post authors

### ISSUE THREAD

**Issue by nint8835** [squidfunk/mkdocs-material#6254]
### Bug description

When attempting to set the default authors for blog posts via the meta plugin according to the docs, the authors do not actually show up on the blog posts. Non-blog metadata configured via the meta plugin (such as tags) _will_ show up, so properties from the meta plugin are being applied to the file, but seemingly blog data is not.

This can be worked around by manually copy/pasting the meta contents into the frontmatter of each post.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Blog plugin docs](https://squidfunk.github.io/mkdocs-material/plugins/blog/)
- [Setting up a blog - setting defaults](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/#setting-defaults)
- [Meta plugin](https://squidfunk.github.io/mkdocs-material/plugins/meta/#__codelineno-3-1:20)
- https://github.com/squidfunk/mkdocs-material/issues/5979#issuecomment-1721376012
  - Another user is encountering the same issue but did not provide a reproduction for it. Based on the git history of the repo they linked, they are still encountering the issue / have not yet removed their workaround for the issue.

### Reproduction

[9.4.7+insiders.4.42.3-meta-doesnt-set-authors.zip](https://github.com/squidfunk/mkdocs-material/files/13199058/9.4.7%2Binsiders.4.42.3-meta-doesnt-set-authors.zip)

### Steps to reproduce

1. Install dependencies
2. Build the site with `mkdocs build` or serve it with `mkdocs serve`
3. Navigate to the blog index. Observe that the post with the author explicitly set shows an author, but the post which should be using the author from the meta does not have an author shown.
4. Navigate to the post without an author shown, and observe that there is a "Blog" tag shown at the top, showing that the meta file which should be configuring the author is applying to this file.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by nint8835** [comment]
Tested on my site with the latest changes off the master branch and confirmed working - thanks for the quick fix!

**Comment by squidfunk** [comment]
Released as part of [9.4.8+insiders-4.43.0](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.43.0).
