### ISSUE TITLE
navigation.expand animates expansion on first load

### ISSUE THREAD

**Issue by eleanor-arc-boats** [squidfunk/mkdocs-material#6261]
### Bug description

I noticed that the left-side navigation will animate the expansion on first load - is this the intended behavior?  Screen cap showing what I see.  This is on Firefox v119 on Ubuntu.  Using the latest mkdocs-material 9.4.7, disabled all customization.

[Screencast from 10-30-2023 01:12:06 PM.webm](https://github.com/squidfunk/mkdocs-material/assets/113399976/4779ed48-3caf-4398-a9d4-f90b48576a23)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Navigation Expansion Flag](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion)

### Reproduction

[9.4.7-nav-expansion-animates-on-load.zip](https://github.com/squidfunk/mkdocs-material/files/13209774/9.4.7-nav-expansion-animates-on-load.zip)

### Steps to reproduce

1. Notice that on first load the table of contents / navigation animates the nested sections from collapsed to expanded

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by eleanor-arc-boats** [comment]
[
[9.4.7-nav-expansion-animates-on-load.zip](https://github.com/squidfunk/mkdocs-material/files/13209774/9.4.7-nav-expansion-animates-on-load.zip)
](url)

**Comment by squidfunk** [comment]
Thanks for reporting. Indeed, this is a change in behavior that as introduced because we added animations in [9.4.2](https://github.com/squidfunk/mkdocs-material/releases/tag/9.4.2). It should definitely not animate on the first load. To temporary mitigate, downgrade to 9.4.1, or disable `navigation.expand`.

**Comment by eleanor-arc-boats** [comment]
Thanks for investigating.  As it turns out downgrading to 9.4.1 seems to break the pydownx emoji extension, so I'll wait until there's a fix.

**Comment by squidfunk** [comment]
Fixed in dcc296e42.

**Comment by squidfunk** [comment]
Released as part of [9.4.10](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.10).
