### ISSUE TITLE
Add support for emojis/icons in code block titles

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#6263]
### Description

Emojis/Icons can nicely enhance the visual quality of documentation. For instance, I like icons in content tabs showing code file content like [this](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#custom-syntax-theme):

![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/ae638894-3dee-4681-855c-600b9f1591dc)

Unfortunately, code block titles don't seem to support icons. For instance,

````md
```python title=":octicons-file-code-16: hello.py"
print("Hello world")
```
````

renders as

![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/599326da-2122-4196-90cf-5b9c6a236125)

but I'd love to see it render as

![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/87fc5da0-7c43-4d76-998e-96b6999dcafa)

or perhaps using a language icon, e.g. `:simple-python:`, like this:

![image](https://github.com/squidfunk/mkdocs-material/assets/2206639/cc2bf268-9894-4e3a-b29b-9973d01fa81e)

Would this be possible to support? :slightly_smiling_face:

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Code blocks](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/)
- [Icons, Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)

### Use Cases

I'd like to beautify some code block titles with file or language icons.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by sisp** [comment]
IIUC, enabling emojis/icons in code block titles actually requires a change in `python-markdown`'s code block title parsing. Right, @facelessuser?

**Comment by facelessuser** [comment]
No, it would need to get changed in SuperFences, but it is not straight forward due to how SuperFences is forced to operate inside Python Markdown.
