### ISSUE TITLE
Grid cards as link (whole card)

### ISSUE THREAD

**Issue by c4ssiopei4** [squidfunk/mkdocs-material#6269]
### Description

Grid Cards are very nice to give an overview on an index page. However, i usually link these cards to a new page. This is usually done with a link in the text of the cards.

It would be nice to have an option to use the whole card as link. So that the whole card acts as a link to the page.

For example like on the pages of https://aws.github.io/copilot-cli/

### Related links

https://github.com/squidfunk/mkdocs-material/issues/3018

### Use Cases

For most of the users it is pretty natural that you can click somewhere on the card instead hitting the links directly in the text. It happened a lot, that i had to explain it, the the users should click on the link in the card.

### Visuals

<img width="971" alt="gridCards" src="https://github.com/squidfunk/mkdocs-material/assets/23194001/37776501-f6af-4d30-a5bf-54f9c71a0bbf">

The whole card should act as a link (red), not just the text (yellow)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. This can already be achieved with HTML in Markdown:

``` html
<div class="grid">
  <a href="#" class="card">Foo</a>
  <a href="#" class="card">Bar</a>
  <a href="#" class="card">Baz</a>
</div>
```

Sadly, it's not possible to do in pure Markdown, because links can only be inline elements. You have to use HTML to do that. Another option might be to write a custom block extension that does the same thing, but we're currently not planning to do that. Thus, everything is working as intended.

**Comment by c4ssiopei4** [comment]
Thank you for the very fast response! I really appreciate it!

**Comment by copdips** [comment]
maybe you can do like this:

```css
<div class="grid">
  <a href="#" class="md-button md-button--primary">Foo</a>
  <a href="#" class="md-button md-button--primary">Bar</a>
  <a href="#" class="md-button md-button--primary">Baz</a>
</div>
```

**Comment by renecotyfanboy** [comment]
Sorry for digging this up, but is there anyway to achieve clickable gallery cards AND preserving the markdown formatting in the cards ?

**Comment by squidfunk** [comment]
Nope, not yet. Maybe in the future, if somebody comes up with a syntax ☺️

**Comment by Foxtrek64** [comment]
Here's what I've done to accomplish this:

```md
# Documentation

<div class="grid cards" markdown>
-   <a class="card-link" href="https://www.github.com" target="_blank" rel="noreferrer">
        :fontawesome-brands-github:{ .xxxl .middle .center }
        <span class="card-title center">GitHub</span>
    </a>
</div>
```

```css
// extra.css

a.card-link center {
    width: fit-content;
    display: block;
    margin: 0 auto;
}

a.card-title {
    font-size: 1.5em;
}

a.card-link {
    color: initial; // Make cards have white text until hovered.
}
```

You can continue to add as many cards to the grid as you want, just as normal. It creates cards that look exactly the same, but are clickable.
