### ISSUE TITLE
Bug in right nav styles on safari v17.1

### ISSUE THREAD

**Issue by tlambert03** [squidfunk/mkdocs-material#6273]
### Context

Found while updating docs dependencies for building docs at https://github.com/pyapp-kit/app-model (docs at https://app-model.readthedocs.io/en/latest/)

### Bug description

after commit 521f7272ee266526102261933e383e6f74eed062 I'm noticing a bug wherein the right nav appears clipped in safari (Version 17.1 (19616.2.9.11.7)) after page refresh:

<img width="227" alt="Screenshot 2023-11-01 at 2 10 43 PM" src="https://github.com/squidfunk/mkdocs-material/assets/1609449/e4d4ab93-4b5b-431e-be01-f22ff881d998">

(resizing the window across any breakpoint fixes it)

<img width="234" alt="Screenshot 2023-11-01 at 2 10 50 PM" src="https://github.com/squidfunk/mkdocs-material/assets/1609449/916774ca-c6ae-4de6-90fa-ed83945e5d50">

The issue is visible as of v9.4.2 and git bisect put the issue at 521f7272ee266526102261933e383e6f74eed062

chrome and edge work fine 

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[app_model-0.2.3.dev12+gb7a5262.d20231101.tar.gz](https://github.com/squidfunk/mkdocs-material/files/13230504/app_model-0.2.3.dev12%2Bgb7a5262.d20231101.tar.gz)

### Steps to reproduce

- checkout https://github.com/pyapp-kit/app-model
- run `pip install -e .[docs]`
- `mkdocs serve` (works)
- ` pip install 'mkdocs-material>=9.4.2'`
- `mkdocs serve` (bug)

### Browser

Safari

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is not a minimal reproduction – you just packed up your regular repository. Please provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). We're not able to observe this issue, and can't help you without a minimal reproduction.

**Comment by tlambert03** [comment]
Yep sorry, I don't have time at the moment, but will try to soon.  Given that my repo had very minimal config, and with knowledge of the exact commit that caused it, I was hoping you might just see what caused it.

When I have time, I'll try to come back and follow the guide here for minimal repo.  Thanks! 🙏

**Comment by squidfunk** [comment]
Great. Closing, until a minimal reproduction is provided. Once you provide it, we reopen and investigate.

**Comment by squidfunk** [comment]
The issue was resolved, see https://github.com/squidfunk/mkdocs-material/issues/6281#issuecomment-1817804434
