### ISSUE TITLE
Search: Add capability to raise the priority of key items

### ISSUE THREAD

**Issue by rfay** [squidfunk/mkdocs-material#6274]
### Context

The [DDEV Docs](https://ddev.readthedocs.io) have lots and lots of detail in them, especially where covering individual configuration items. 

The mkdocs-material search is awesome and so very useful. But it often stumbles providing the most useful links first. 

For example, if I search for "database" I get lots of good hits, but the first one is almost certainly not the right one, and the third one here is probably the place for people to start. 

<img width="691" alt="image" src="https://github.com/squidfunk/mkdocs-material/assets/112444/01bf1ca8-1d48-456e-b792-2888a0d38afe">

### Description

It would be great to have some way to increase the priority of some search results with an annotation of some type, or an external config file.

### Related links

I didn't find items specifically related to this in my search, which surprised me.

### Use Cases

From an editor's perspective, it would mean using some annotation or configuration to raise the search priority of the most useful topics.

From a user's perspective, it might mean they'd hit them first. 

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexvoss** [comment]
Hi, from the way you describe the requirements, it sounds like the [current mechanisms ](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search#usage) to boost pages and exclude pages, sections and blocks from search would go some way to addressing them. Have you tried these and what were your experiences? 

I think we all know that the current search based on lunr.js is less than ideal. That is why a rewrite of the search functionality is currently underway.

**Comment by rfay** [comment]
I obviously completely was ignorant of that, thanks, will try it out!

**Comment by squidfunk** [comment]
Thanks for reporting. @alexvoss is right – you're looking for boosting. Additionally, we're currently reworking search, so that boosting should not be necessary in the future. We're working on improving the default behavior.
