### ISSUE TITLE
Add X-Twitter logo

### ISSUE THREAD

**Issue by avarone-github** [squidfunk/mkdocs-material#6287]
### Description

X seems the new established name for Twitter. What about including the fontawesome logo for X under brands?

### Related links

- [Fontawesome X Twitter icon](https://fontawesome.com/icons/x-twitter?f=brands&s=solid)

### Use Cases

Keep social links "modern".

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm not sure what you mean by "brands", but I assume you mean our "popular choices" for social icons. I've adapted the list in fabc9bd6b.

**Comment by avarone-github** [comment]
@squidfunk thank you very much.
