### ISSUE TITLE
"mkdocs serve" shows a bunch of deprecations

### ISSUE THREAD

**Issue by madrus** [squidfunk/mkdocs-material#63]
## Description

Adding `theme : 'material'` instead of `'readthedocs'` to `mkdocs.yml` shows a bunch of warnings about deprecations.

### Expected behavior

No warnings

### Actual behavior

λ mkdocs serve                                                                                                                    
INFO    -  Building documentation...                                                                                              
INFO    -  Cleaning site directory                                                                                                
WARNING -  Your theme does not appear to contain a 'main.html' template. The 'base.html' template was used instead, which is deprecated. Update your theme so that the primary entry point is 'main.html'.                                                          
WARNING -  Template variable warning: 'site_name' is being deprecated and will not be available in a future version. Use 'config.site_name' instead.                                                                                                                
WARNING -  Template variable warning: 'favicon' is being deprecated and will not be available in a future version. Use '{{ base_url }}/img/favicon.ico' instead.                                                                                                    
WARNING -  Template variable warning: 'repo_url' is being deprecated and will not be available in a future version. Use 'config.repo_url' instead.                                                                                                                  
WARNING -  Template variable warning: 'page_title' is being deprecated and will not be available in a future version. Use 'page.title' instead.                                                                                                                     
WARNING -  Template variable warning: 'canonical_url' is being deprecated and will not be available in a future version. Use 'page.canonical_url' instead.                                                                                                          
WARNING -  Template variable warning: 'copyright' is being deprecated and will not be available in a future version. Use 'config.copyright' instead.                                                                                                                
WARNING -  Template variable warning: 'content' is being deprecated and will not be available in a future version. Use 'page.content' instead.                                                                                                                      
WARNING -  Template variable warning: 'google_analytics' is being deprecated and will not be available in a future version. Use 'config.google_analytics' instead.                                                                                                  
WARNING -  Template variable warning: 'repo_name' is being deprecated and will not be available in a future version. Use 'config.repo_name' instead.                                                                                                                
WARNING -  Template variable warning: 'page_description' is being deprecated and will not be available in a future version. Use 'config.site_description' instead.                                                                                                  
WARNING -  Template variable warning: 'site_author' is being deprecated and will not be available in a future version. Use 'config.site_author' instead.                                                                                                            
WARNING -  Template variable warning: 'current_page' is being deprecated and will not be available in a future version. Use 'page' instead.                                                                                                                         
WARNING -  Template variable warning: 'toc' is being deprecated and will not be available in a future version. Use 'page.toc' instead.                                                                                                                              
WARNING -  Template variable warning: 'next_page' is being deprecated and will not be available in a future version. Use 'page.next_page' instead.                                                                                                                  
WARNING -  Template variable warning: 'include_next_prev' is being deprecated and will not be available in a future version. Use '(page.next_page or page.previous_page)' instead.                                                                                  
WARNING -  Template variable warning: 'previous_page' is being deprecated and will not be available in a future version. Use 'page.previous_page' instead.                                                                                                          
[I 161120 08:48:50 server:283] Serving on http://127.0.0.1:8000                                                                   
[I 161120 08:48:50 handlers:60] Start watching changes                                                                            
[I 161120 08:48:50 handlers:62] Start detecting changes                                                                           
[I 161120 08:48:52 handlers:133] Browser Connected: http://localhost:8000/                                                        
[I 161120 08:48:52 handlers:80] Ignore: c:\python27\lib\site-packages\material\assets\stylesheets\palettes.css                    

### Steps to reproduce the bug

1. `pip install mkdocs`
2. `mkdocs new material`
3. `cd material`
4. 'printf "\ntheme: 'material'" >> mkdocs.yml'
5. `mkdocs serve`

### Package versions

- Python: `python --version` -- 2.7.12
- MkDocs: `mkdocs --version` -- 0.16.0
- Material: `pip show mkdocs-material | grep -E ^Version` -- 0.2.4

### System information

- OS: Windows10
- Browser: not relevant

**Comment by squidfunk** [comment]
Thanks for reporting. This is due to the new release of mkdocs 0.16. I will fix this in 1.0.0, which will then have mkdocs 0.16 as the required version.

**Comment by brendo** [comment]
I know you said you'd jump on this @squidfunk, I figured I'd knock it out while you're still on holidays 👍

**Comment by squidfunk** [comment]
Fixed in 1.0.0 (thanks @brendo). Issue will remain open until final release.
