### ISSUE TITLE
Projects plugin cache not being updated

### ISSUE THREAD

**Issue by alexvoss** [squidfunk/mkdocs-material#6306]
### Context

Using the projects plugin in Insiders, I am having the problem that it seems the cache is never updated. 

### Bug description

Changes to the `mkdocs.yml` files in project do not get picked up. I am changing the color scheme as an example, see below. It seems the `config.pickle` file in `.cache` is not getting updated when a `mkdocs.yml` file in a project is changed. 

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/plugins/projects/#caching

### Reproduction

[9.4.8+insiders.4.43.0-projects-plugin-cache.zip](https://github.com/squidfunk/mkdocs-material/files/13278380/9.4.8%2Binsiders.4.43.0-projects-plugin-cache.zip)

### Steps to reproduce

1. `rm -rf .cache`
2. `mkdocs serve`
3. Open [subproject](http://localhost:8000/template/) in a browser and observe that the project has an indigo palette
4. In another window, edit the project's `mkdocs.yml` to set the palette to `red`
5. Make a change to the `docs/index.md` to see that the browser updates
6. You will see that while the change from (5) shows, the palette is still indigo
7. Restart `mkdocs serve`
8. Observe that the color scheme still has not changed.
9. Stop `mkdocs serve`
10. `rm -rf .cache`
11. Start `mkdocs serve`
12. Observe that the color scheme has changed now.

Btw. I selected a browser below without thinking and it seems this selection cannot be reset?

### Browser

Other

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting! Could you maybe check if data is updated when you disable the [`cache`](https://squidfunk.github.io/mkdocs-material/plugins/projects/#config.cache):

``` yaml
plugins:
  - projects:
      cache: false
```

**Comment by alexvoss** [comment]
Will do. As soon as I managed to produce a new zip file - because the info plugin did not include the projects directory?

**Comment by alexvoss** [comment]
Ok, here is the new `.zip` file.
[9.4.8+insiders.4.43.0-projects-plugin-cache.zip](https://github.com/squidfunk/mkdocs-material/files/13278708/9.4.8%2Binsiders.4.43.0-projects-plugin-cache.zip)

**Comment by alexvoss** [comment]
Ok, with `cache: false` a cache is still being created, which might be something to change. Also, the palette does not update. In contrast to the version with no setting for `cache`, it does change on a restart of `mkdocs serve`. I think this is how I have been rolling with the examples, have cache turned off and restart whenever I made a chance to a `mkdocs.yml`file. 

I did try to debug this but the only thing I could find out is that [line 108 in plugin.py](https://github.com/squidfunk/mkdocs-material-insiders/blob/2a869a0c83c61f26e1176480cad0f2a21e37854e/src/plugins/projects/plugin.py#L108) might need to be `and not self.is_root:` instead of `or not self.is_root:`?

**Comment by squidfunk** [comment]
The cache must be created - we need a way to store intermediate results. This is the same for all plugins. What we could do in theory (but I haven't done it, because nobody complained) is to create a temporary directory and use that for intermediate storage, but the plugins definitely need intermediate storage. Thus, `cache` disables cache _usage_, not the cache itself.

I'll investigate as soon as possible.

**Comment by squidfunk** [comment]
Fixed in f0b2a6e49. My testing shows that the editing experience is much smoother now. In fact, we forgot to update the cache that must be used in nested projects when detecting a change and reloading the configuration. That's now sorted.

**Comment by squidfunk** [comment]
Released as part of [9.4.10+insiders-4.43.1](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.43.1).

**Comment by squidfunk** [comment]
@alexvoss does this work better for you now?

**Comment by alexvoss** [comment]
Did a quick test by modifying the `mkdocs.yml` files in one of our examples and it did get picked up. Thanks for fixing this. I will try and do some more work with the projects plugin in the coming days and will report any remaining issues I find but this fix and the other one that helped with newly created projects or those that do not use Material fix the two issues I had some across - IIRC.

**Comment by squidfunk** [comment]
That's great to hear! I'm really looking forward making the editing experience as smooth as possible.

**Comment by squidfunk** [comment]
I've started breaking the projects plugin into discernable parts that will make management of projects simpler, and address the issues with caching as well. This will take some more time, but I'm confident that I'll have a working prototype by the end of the week. I'll also fix #6399 on the way.

**Comment by squidfunk** [comment]
Fixed in [`f1cb613`](https://github.com/squidfunk/mkdocs-material-insiders/commit/f1cb6134213ccb947fb55c055961f8ad3f654b58). I did a rewrite of the plugin and changed the approach to caching, so the workaround suggested in https://github.com/squidfunk/mkdocs-material/issues/6306#issuecomment-1798206523 is no longer needed.

Also see https://github.com/squidfunk/mkdocs-material/issues/6399#issuecomment-1849020584

**Comment by squidfunk** [comment]
Released as part of [9.5.2+insiders-4.47.1](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.47.1).
