### ISSUE TITLE
Locally installed Nerd Font not showing up… 

### ISSUE THREAD

**Issue by kierun** [squidfunk/mkdocs-material#6316]
### Context

I have this configuration:

```yaml
theme:
  name: material
  font:
    text: PT Sans Nerd Font Narrow
    code: PragmataPro Liga
```

However, I cannot see the main font displayed. The monospace (`PragmataPro Liga`) one is fine.

For example, I cannot see the logo in ` Fedora` (`\uf30a`) … Which you won't be able to see unless you have a [nerd font](https://www.nerdfonts.com/).

### Bug description

Locally installed fonts not showing up in locally run mkdocs.

### Related links

- [Change the font](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/)

### Reproduction

Try with any of the [nerd font](https://www.nerdfonts.com/).

### Steps to reproduce

1. Install a [nerd font](https://www.nerdfonts.com/).
2. Change the font in `mkdocs.yml` to the installed font.
3. Run `mkdocs serve`
4. See if the font appears on a browser.

[test.zip](https://github.com/squidfunk/mkdocs-material/files/13309714/test.zip)

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment]
Hi, 

I am somewhat surprised that you say the `PragmataPro Liga` one works as I don't think that is part of Google Fonts. Changing the font names in the theme section only changes the fonts that Material is going to try to load from Google Fonts. 

To use local fonts, you need to use [customization](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts#customization). I have recently published [an example for how custom fonts are done](https://mkdocs-material.github.io/examples/fonts-custom/).  Hope this helps.

**Comment by kierun** [comment]
@alexvoss You are indeed right, it's the wrong font too. :cry:  However, I had it working a few months ago on both `text` and `code` fonts. Is the only Google fonts a recent change?

Thank you for the example, it does indeed help.

**Comment by alexvoss** [comment]
> Google fonts a recent change?

As far as I know the font option in theme has always(?) pointed to Google Fonts. Sorry, can't help there. Google have recently release a new version, I think. Perhaps they kicked those fonts out for some reason? Would seem strange, though, that it would have affected both the fonts you are using.
