### ISSUE TITLE
Code copy button adds new line

### ISSUE THREAD

**Issue by maxsitt** [squidfunk/mkdocs-material#6327]
### Bug description

Currently, when copying code with the code copy button, a new line is automatically added when pasting the copied code somewhere else. This does not happen if the code is copied manually by selecting everything in the code block.

Especially when copying code that should be run in a Terminal/command prompt, the new line that is automatically added when copying the code with the code copy button can lead to problems in some cases, e.g. code is run immediately when pasting. Expected behaviour of the code copy button should be exactly the same as for copying code manually: copy only the content in the code block without adding a new line.

### Related links

- [Code copy button documentation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button)
- Previously mentioned in #6323

### Reproduction

[9.4.8-code-copy-button.zip](https://github.com/squidfunk/mkdocs-material/files/13332785/9.4.8-code-copy-button.zip)

### Steps to reproduce

1. Create new mkdocs project with all required packages up to date (2023-11-13).
2. Add the code copy button feature to the `mkdocs.yml`:
    ```
    theme:
      name: material
      features:
      - content.code.copy
    ```
3. Add a code block in `index.md`.
4. From the served/built site, copy the code manually by selecting the content in the code block and paste it to an empty text document: no new line is added.
5. Copy the code with the code copy button: a new line is added.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Fixed in 34d789bf8. We now remove trailing whitespace when copying. We deliberately decided not to remove leading whitespace, as I'm not sure what the implications of that might be – there are just too many languages. Trailing whitespace should be fine, except for when you're doing tutorials in the language [Whitespace](https://en.wikipedia.org/wiki/Whitespace_(programming_language)), probably.

**Comment by maxsitt** [comment]
Thanks for the quick fix! :)

**Comment by squidfunk** [comment]
Released as part of [9.4.9](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.9).

**Comment by btbf** [comment]
I honestly did not want this to be fixed. Sometimes you want a line break at the end.

**Comment by squidfunk** [comment]
> I honestly did not want this to be fixed. Sometimes you want a line break at the end.

Well, thank you! Your comment clearly communicates: there are _always_ different use cases. We cannot possibly please everyone, albeit we try so hard. Unfortunately, we're likely keeping it that way, as it's quite useful for the majority.
