### ISSUE TITLE
Blog plugin error with date convertion with pt-BR language

### ISSUE THREAD

**Issue by vmutter** [squidfunk/mkdocs-material#6328]
### Bug description

Using the `blog plugin` with the language set to `pt-BR`, there is a problem with the babel format_date, with the given locale.

The locale is set by getting the langauge config, in this case `pt-BR`, but babel does not support the hifen (it must be an undescore). So ther error happens.

Line 803 from https://github.com/squidfunk/mkdocs-material/blob/master/src/plugins/blog/plugin.py

This error problably happens with other languages with hifen (e.g. ku-IQ)

The solution would be to replace the hifen (-) with (_)

### Related links

- [Setting up a blog](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/)
- [Changing the language](https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/)

### Reproduction

[9.4.8-bug-blog-pt-br.zip](https://github.com/squidfunk/mkdocs-material/files/13334482/9.4.8-bug-blog-pt-br.zip)

### Steps to reproduce

1.  [Setting up a blog](https://squidfunk.github.io/mkdocs-material/getting-started//)
2. Start the mkdocs, using docker: `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material`

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and the excellent reproduction! Fixed in 9c73460e2.

**Comment by squidfunk** [comment]
Released as part of [9.4.9](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.9).
