### ISSUE TITLE
Customize the archive page for blog Plugin，but failed with pagination

### ISSUE THREAD

**Issue by shenweiyan** [squidfunk/mkdocs-material#6336]
### Context

I want to customize the archive page of the mkdocs-material blog plugin, as shown in the screenshot below. 
![](https://user-images.githubusercontent.com/26101369/282349035-68b23e34-bbc1-4105-96ac-af3ec8f89fd2.png)

### Bug description

Thanks to squidfunk for the assistance provided https://github.com/squidfunk/mkdocs-material/discussions/6324. I've utilized a hook, but it seems doesn't work for pages beyond the second page if there is pagination.

### Related links

Repo: https://github.com/shenweiyan/mkdocs-blog
Link: https://shenweiyan.github.io/mkdocs-blog/blog/archive/2023/

### Reproduction

[mkdocs-blog.zip](https://github.com/squidfunk/mkdocs-material/files/13359021/mkdocs-blog.zip)

### Steps to reproduce

1. `pip3 install -r requirements.txt`
2. `mkdocs serve`

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Fixed in 97c7b54.

Next time, please create a true minimal reproduction as opposed to just zipping up your repository. I could not manage to get your example to run, which cost me significantly more time to fix the issue than would be necessary.

Thank you very much for your cooperation.

**Comment by squidfunk** [comment]
Released as part of [9.4.9](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.9).
