### ISSUE TITLE
Search layout issues and chat bot not working

### ISSUE THREAD

**Issue by perpil** [squidfunk/mkdocs-material#6339]
### Description

This is minor, but highlighting in case it's unknown.  When you hover over the documentation chat bot icon on the docs search, the layout shifts and looks bad.  Also I'm having difficulty getting the bot to work, it just hangs at "Thinking..."  I've attached a screencap:

![SearchBug](https://github.com/squidfunk/mkdocs-material/assets/97474956/f82222e0-18a6-406d-afed-8659f4092ff9)

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
- [Docs](https://squidfunk.github.io/mkdocs-material/getting-started/)

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting – this was an error in our experimental client code. Issue has been fixed!
