### ISSUE TITLE
Update Mermaid

### ISSUE THREAD

**Issue by frederictobiasc** [squidfunk/mkdocs-material#6348]
### Description

Upgrading Mermaid will allow users to use new features of it.

### Related links

- [Sequence Diagram: Actor Creation and Destruction](http://mermaid.js.org/syntax/sequenceDiagram.html#actor-creation-and-destruction-v10-3-0)

### Use Cases

I would like to use the Actor Creation feature, introduced in mermaid v10.3.0 but mkdocs material currently uses mermaid v9.4.3.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexvoss** [comment]
This has been discussed before in https://github.com/squidfunk/mkdocs-material/issues/5193 and https://github.com/squidfunk/mkdocs-material/issues/5758. https://github.com/squidfunk/mkdocs-material/issues/5758 is where the discussion should now be taking place. Please search the existing issues (including closed ones!) before creating a new one. Best wishes

**Comment by manselmi** [comment]
There is an open PR which has been working fine for me: #6265

**Comment by frederictobiasc** [comment]
> Please search the existing issues (including closed ones!) before creating a new one.

I'm sorry. It didn't occur to me that an issue for the Mermaid update would be closed.

Closing this here because it's a duplicate of https://github.com/squidfunk/mkdocs-material/issues/5193
