### ISSUE TITLE
Allow showing only a range of lines for code blocks

### ISSUE THREAD

**Issue by llucax** [squidfunk/mkdocs-material#6353]
### Context

I'm using mkdocstrings and Sybil to extract code examples in the documentation and test by running pylint on them via pytest.

This forces me to sometimes add too much boilerplate to examples, which is distracting from the main idea I want to show in an example, but it is also really important that examples stay up to date and (mostly) working.

An alternative would be to move the examples to separate files and use the snippet extension line selection feature, but I want to keep the examples in the docstrings, so they are also accessible in code editors, as python include all the docs in the code itself.

### Description

I would like code blocks to accept selecting which lines to show, similar to what the snippet extension or the highlight specific lines feature does. For example:

~~~md 
Example:
    ``` py show_lines="4:"
    # Bolierplate setup code
    # More boiler plate setup code
    # And some more
    this is the_juicy_part
    ```
~~~

I'm suggesting the snippet extension syntax (with `:`) instead of the highlight specific lines feature syntax because it is more natural for specifying open-ended ranges.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Highlight specific lines feature](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#highlighting-specific-lines)
- [Markdown Snippet extension line selection](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippet-lines)

Related discussions:
- https://github.com/squidfunk/mkdocs-material/discussions/6252: Similar but only for selecting what to copy, not what to show.
- https://github.com/squidfunk/mkdocs-material/discussions/3944: Similar but it still includes the boilerplate code, it is just hidden. It would also require to add more noise to the example, and it looks like it might be harder to implement, as the code needs to be parsed too.

Extra:
- [mkdocstrings](https://mkdocstrings.github.io/)
- [sybil](https://sybil.readthedocs.io/en/latest/)
- [pylint](https://pylint.readthedocs.io/en/stable/)
- [pytest](https://docs.pytest.org/en/7.4.x/)
- [Code to put it all together](https://github.com/frequenz-floss/frequenz-repo-config-python/blob/22d65407daef3093214b22747a37163b6af2895e/src/frequenz/repo/config/pytest/examples.py)

### Use Cases

Being able to write examples that are verifiable using linting tools to ensure they stay up to date, but still only being able to show the relevant parts that make sense for the documentation, avoiding distracting, boilerplate code.

### Visuals

It should look like a regular code block, just with less lines than the original code block.

Stretch goal: There could be some button to expand the example and show also the boilerplate code, so users could copy&paste the whole example and run it if they want.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! Please propose this to [Python Markdown Extensions](https://github.com/facelessuser/pymdown-extensions), as this is the library that converts code blocks into Markdown ☺️ Material for MkDocs only renders what it gets.

**Comment by llucax** [comment]
OK, I will do that, thanks. One question though, if the "button to expand the boilerplate option" would get implemented, would that need support from Material, or it would still be all part of `pymdown-extensions`?

**Comment by squidfunk** [comment]
Maybe, depends on the outcome.
