### ISSUE TITLE
Automatic navigation sorts section index pages incorrectly

### ISSUE THREAD

**Issue by bjan-sag** [squidfunk/mkdocs-material#6354]
### Bug description

Regular pages are sorted alphabetically in the automatic navigation. The issue is with section index pages, which always are put last.

This structure:
```
- docs
  - a.md
  - b.md
```

Results in:
```
- A
- B
```

However, this structure:
```
- docs
  - a
    - index.md
  - b.md
```

Results in:
```
- B
- A
```

### Related links

- [Section index pages](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages)

### Reproduction

[9.4.8-section-index-broken-sorting.zip](https://github.com/squidfunk/mkdocs-material/files/13390856/9.4.8-section-index-broken-sorting.zip)

### Steps to reproduce

1. Run `mkdocs serve`.
2. Observe the navigation being not in alphabetical order.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting! This happens regardless of `theme` setting, so please report this to [MkDocs](https://github.com/mkdocs/mkdocs).
