### ISSUE TITLE
Consult the new `version_selector` property when using version control with Mike

### ISSUE THREAD

**Issue by gabrielbdornas** [squidfunk/mkdocs-material#6356]
### Context

Now, when using version control with Mike and Mkdocs it is possible to hide the version selector that is created when Mike is activated. To accomplish that, we must use the `version_selector` property set to `false` accordingly to the [mike's configuration](https://github.com/jimporter/mike#configuration).

I [asked](https://github.com/jimporter/mike/issues/151#issuecomment-1806459699) this question in one of Mike's related issues and its maintainer [said](https://github.com/jimporter/mike/issues/151#issuecomment-1806485061) that as far as he knows, "Material theme doesn't consult the `version_selector` property". @squidfunk [confirmed](https://github.com/squidfunk/mkdocs-material/discussions/6329#discussioncomment-7562512) that and suggest the opening of this feature request.

### Description

I would like to suggest material consult the new Mike's `version_selector` property, and if it is set to `false` hide the [version selector within the header when version control is enable](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/?h=mike#versioning:~:text=This%20renders%20a%20version%20selector%20in%20the%20header%3A).

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Hidden versions issue on Mike's repo](https://github.com/jimporter/mike/issues/151)
- [Hide version selector or mike ins't working discussion on material's repo](https://github.com/squidfunk/mkdocs-material/discussions/6329)

### Use Cases

One business/use case that will benefit from it is when we need to use versions to monitor and share improvements of the document without letting end users explicitly see it.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Could I please ask you to provide a __minimal reproduction__, so we have something to iterate? This makes my life easier, as I don't have to first recreate the case you described. Thank you!

**Comment by squidfunk** [comment]
Okay, I've managed to implement it without the reproduction. Added in c181a46f7. We now check if `mike` is configured, and if so, if the version selector is disabled. In that case, we don't add the version selector. In all other cases, we do.

**Comment by squidfunk** [comment]
Released as part of [9.4.10](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.10).

**Comment by gabrielbdornas** [comment]
> Okay, I've managed to implement it without the reproduction. Added in [c181a46](https://github.com/squidfunk/mkdocs-material/commit/c181a46f741d001c925ea6cdbc746830dc92b17d). We now check if `mike` is configured, and if so, if the version selector is disabled. In that case, we don't add the version selector. In all other cases, we do.

That was impressive. Sorry to no provide the minimal reproduction in time. I'll try it now.
