### ISSUE TITLE
Text for previous disappear when the screen is not wide enough

### ISSUE THREAD

**Issue by joshuaavalon** [squidfunk/mkdocs-material#636]
## Description

![001](https://user-images.githubusercontent.com/7152420/33923953-c468500a-e00e-11e7-9151-236478265c75.png)
![001a](https://user-images.githubusercontent.com/7152420/33923955-c579ff3e-e00e-11e7-94c6-107a2af6338d.png)

If it does not have enough space to show the text, why not both text disappear for consistency.

### Expected behavior

Text show up like normal.

### Actual behavior

Text does not show up.

### Steps to reproduce the bug

1. Go to bottom [https://squidfunk.github.io/mkdocs-material/getting-started/](https://squidfunk.github.io/mkdocs-material/getting-started/)
2. Adjust the width to see this happen

### Package versions

N/A

### Project configuration

N/A

### System information

* OS: Win 7 / Android 8.1
* Browser: Chrome 63.0.3239 / Chrome 62.0.3202.84

**Comment by squidfunk** [comment]
Please see #491 for a discussion - it's intended behavior
