### ISSUE TITLE
Add Vercel Analytics provider

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#6377]
### Description

Material for MkDocs makes integrating Google Analytics quite easy. But there are many other analytics providers, some of which are more data privacy friendly and GDPR compliant even without cookie banners. For instance, [Plausible.io was suggested](https://github.com/squidfunk/mkdocs-material/pull/4847) but [declined](https://github.com/squidfunk/mkdocs-material/pull/4847#issuecomment-1377720910) because it's not a free service.

The [recent analytics-related schema improvements](https://github.com/squidfunk/mkdocs-material/pull/6361) pave the way for adding more _built-in_ providers, and built-in support for many features and integrations like emojis/icons &ndash; also analytics providers &ndash; makes Material for MkDocs so attractive.

That said, would you be interested in supporting [Vercel Analytics](https://vercel.com/analytics)? It's free (with limited features) on the [Hobby plan](https://vercel.com/pricing). I've been using it for my site, it's easy to set up but requires deploying the site on Vercel, which is also free on the Hobby plan.

The integration is quite simple:

1. Create a custom partial at `<custom_dir>/partials/integrations/analytics/vercel.html` with this content:

    ```html
    <script>
      window.va = window.va || function () { (window.vaq = window.vaq || []).push(arguments); };
    </script>
    <script defer src="/_vercel/insights/script.js"></script>
    ```

1. Add the following snippet in `mkdocs.yml`:

    ```yaml
    extra:
      analytics:
        provider: vercel
    ```

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Setting up site analytics](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/)
- [Add support for Plausible Analytics (#4847)](https://github.com/squidfunk/mkdocs-material/pull/4847)

### Use Cases

Setting up basic site analytics for free (or more advanced for a price) using Vercel Analytics.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm also considering to switching providers, but (and this is a big one):

> requires deploying the site on Vercel,

We don't advertise solutions on our documentation that lock you into a specific provider. We have no incentive to give Vercel free customers, which is why we're not considering doing that. Other than that, this can be perfectly achieved with an override. I invite you to share this override here, so that others might use it as well ☺️

**Comment by sisp** [comment]
Fair enough. Thanks for clarifying your position on adding commercial provider support. :+1:
