### ISSUE TITLE
YAML schema missing markdown extensions

### ISSUE THREAD

**Issue by AdrianoKF** [squidfunk/mkdocs-material#6378]
### Bug description

The JSON schema definition for the `mkdocs.yml` format does not recognize a couple of Markdown extensions:

- The [Neoteroi MkDocs plugins](https://www.neoteroi.dev/mkdocs-plugins)
- `sane_lists` from `python-markdown`

I can prepare a PR adding the relevant plugins to the schema (however, I might be missing others that I haven't run into just yet).

### Related links

- Neoteroi MkDocs plugin: https://www.neoteroi.dev/mkdocs-plugins
- `sane_lists` markdown extension: https://python-markdown.github.io/extensions/sane_lists/

### Reproduction

Not including, since this is not an issue with a generated site.

### Steps to reproduce

Here's a snippet from my `mkdocs.yml`, both lines trigger an error message saying the value is not accepted in VSCode:

```yaml
markdown_extensions:
  - neoteroi.cards  # https://www.neoteroi.dev/mkdocs-plugins/cards/
  - sane_lists
```

Full error message:

```
Value is not accepted. Valid values: "markdown.extensions.abbr", "abbr", "markdown.extensions.admonition", "admonition", "markdown.extensions.attr_list", "attr_list", "markdown.extensions.callouts", "callouts", "markdown.extensions.def_list", "def_list", "markdown.extensions.footnotes", "footnotes", "markdown.extensions.md_in_html", "md_in_html", "markdown.extensions.tables", "tables", "markdown.extensions.toc", "toc", "pymdownx.arithmatex", "pymdownx.betterem", "pymdownx.caret", "pymdownx.critic", "pymdownx.details", "pymdownx.emoji", "pymdownx.highlight", "pymdownx.inlinehilite", "pymdownx.keys", "pymdownx.magiclink", "pymdownx.mark", "pymdownx.smartsymbols", "pymdownx.snippets", "pymdownx.superfences", "pymdownx.tasklist", "pymdownx.tilde".yaml-schema: Abbreviations – Python Markdown(1)
```

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is not a bug. We can't possibly oversee all extensions in the ecosystem, but you are very much encouraged to submit a PR that adds support for them. Other than that, we're not planning to do so.
