### ISSUE TITLE
Option to customize a different pagination limit specifically for the archive pages

### ISSUE THREAD

**Issue by shenweiyan** [squidfunk/mkdocs-material#6383]
### Description

I've found that the `pagination_per_page` parameter in the blog plugin affects both the blog's main page and the archive pages. 

Now, I wish there was an option to customize a different pagination limit specifically for the archive pages, for example, setting `pagination_per_page=20` for the archives page while keeping `pagination_per_page=5` for the main blog page. 

### Related links

- https://github.com/squidfunk/mkdocs-material/discussions/6376

### Use Cases

Separately setting different pagination_per_page for the blog's main page and the archive pages can provide more flexibility for the customization of the blog plugin.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! Added in [`8ecee7b`](https://github.com/squidfunk/mkdocs-material-insiders/commit/8ecee7b9dbdc5b2a0befd043a048ad25d56c784f) (Insiders). This commit introduces several new configuration flags, and fixes some issues when pagination is disabled. New flags are (I'll update the docs in a minute):

- `archive_pagination` 
- `archive_pagination_per_page`
- `categories_pagination` 
- `categories_pagination_per_page`

All of those are optional settings (similar to [`archive_toc`](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.archive_toc) and [`categories_toc`](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.categories_toc)), and will inherit their values form [`pagination`](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.pagination) and [`pagination_per_page`](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.pagination_per_page) unless they're explicitly specified.

__Note that these options will at first be only available to sponsors__. We're happy to offer more advanced configuration settings for the blog plugin that don't cater to everyday use cases to our sponsors as part of [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/).

I'll backport the pagination fixes in a minute to the community edition. Adding this functionality was a great opportunity to refactor inheritance of settings a little, and to allow us to add more fine-grained controls in the future.

**Comment by squidfunk** [comment]
Documentation added in a6772cf.

**Comment by squidfunk** [comment]
Fixes for `pagination` have been backported in 0fd2a39.

**Comment by squidfunk** [comment]
Released as part of [insiders-4.44.0](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.44.0).
