### ISSUE TITLE
View source of this page URLs are using a redirected url instead of final form

### ISSUE THREAD

**Issue by ssbarnea** [squidfunk/mkdocs-material#6385]
### Context

While using linkchecker to verify URL inside the codebase, I observed that "View source of this page" URLs generated by mkdocs-material are using "raw" page links that are redirected (HTTP 302) instead of the canonical ones.

Here is the output observed:
```
URL        `https://github.com/ansible/mkdocs-ansible/raw/main/docs/README.md'
Name       `View source of this page'
Parent URL file:///Users/ssbarnea/c/a/mkdocs-ansible/site/index.html, line 1, col 13227
Real URL   https://raw.githubusercontent.com/ansible/mkdocs-ansible/main/docs/README.md
Check time 1.232 seconds
Size       295B
Warning    [http-redirected] Redirected to
           `https://raw.githubusercontent.com/ansible/mkdocs-ansible/main/docs/README.md'
           status: 302 Found.
Result     Valid: 200 OK
```

Basically this tells me that we generate a link that adds the raw part instead of just using the raw.githubusercontent.com domain.

### Bug description

I suspect that this might come from this line:
```
<a href="{{ page.edit_url | replace(part, 'raw') }}" title="{{ lang.t('action.view') }}" 
```

### Related links

-

### Reproduction

-

### Steps to reproduce

No need to reproduce as we can see the urls on all sites using mkdocs-material, even official docs, like https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Closing for the reasons stated. We should keep it simple. Additionally, you can override the [`actions.html`](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/partials/actions.html) partial with [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials) easily, which is also a partial that is not subject to much change ☺️
