### ISSUE TITLE
In Mkdocs' blog plugin, the categories are not fully displayed

### ISSUE THREAD

**Issue by shenweiyan** [squidfunk/mkdocs-material#6388]
### Bug description

Some of my blog posts contain multiple categories with Chinese and English. However, in the mkdocs-material blog plugin's site, I can't get all the corresponding categories to display.

### Related links

- <https://github.com/shenweiyan/mkdocs-blog>
- https://shenweiyan.github.io/mkdocs-blog/blog/

### Reproduction

[mkdocs-blog-category.zip](https://github.com/squidfunk/mkdocs-material/files/13446327/mkdocs-blog-category.zip)

### Steps to reproduce

For example, in this specific blog post [2023-10-09-python.md](https://raw.githubusercontent.com/shenweiyan/mkdocs-blog/main/docs/blog/posts/2023-10-09-python.md), <https://shenweiyan.github.io/mkdocs-blog/blog/> only displays one category: `Python`, while the other category, `编程`doesn't appear.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. You can customize the amount of categories shown with [`post_excerpt_max_categories`](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.post_excerpt_max_categories):

``` yaml
plugins:
  - blog:
      post_excerpt_max_categories: 10
```

**Comment by shenweiyan** [comment]
> Thanks for reporting. You can customize the amount of categories shown with [`post_excerpt_max_categories`](https://squidfunk.github.io/mkdocs-material/plugins/blog/#config.post_excerpt_max_categories):
> 
> ```yaml
> plugins:
>   - blog:
>       post_excerpt_max_categories: 10
> ```

Thank you very much.
Actually, there's another issue: even when a post has only one category, sometimes it doesn't show up. For example, this [2023-11-23-translate.md](https://raw.githubusercontent.com/shenweiyan/mkdocs-blog/main/docs/blog/posts/2023-11-23-translate.md) article's category isn't displayed <https://shenweiyan.github.io/mkdocs-blog/blog/>. I've tried multiple times but couldn't figure out where the issue lies. I hope someone can help me troubleshoot this.

**Comment by Larry-Cui** [comment]
I have the same problem: it seems that I cannot have more than one Chinese categories.

**Comment by shenweiyan** [comment]
> I have the same problem: it seems that I cannot have more than one Chinese categories.

Upgrade mkdocs-material to version [9.4.12](https://squidfunk.github.io/mkdocs-material/changelog/#9.4.12) can solve this issue. Refer to https://github.com/squidfunk/mkdocs-material/issues/6390.

**Comment by squidfunk** [comment]
That, or use the configuration I posted in https://github.com/squidfunk/mkdocs-material/issues/6388#issuecomment-1823974037.
