### ISSUE TITLE
The MathJax needs to be manually refreshed to take effect.

### ISSUE THREAD

**Issue by shenweiyan** [squidfunk/mkdocs-material#6407]
### Bug description

I referred to the information from [Math - Material for MkDocs](https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-mkdocsyml) and attempted to insert mathematical formulas in mkdocs. However, I found that sometimes the mathematical formulas fail to display correctly, requiring users to manually refresh the page for them to take effect.

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-mkdocsyml
- https://shenweiyan.github.io/mkdocs/

### Reproduction

[9.4.14-mkdocs-math.zip](https://github.com/squidfunk/mkdocs-material/files/13495683/9.4.14-mkdocs-math.zip)

### Steps to reproduce

1. `pip install -r requirements.txt`
2. `mkdocs serve`
3. In the mkdocs web page site, when toggling between the `home` and `blog` pages, it's observed that `$2^{10}=1024$` sometimes fails to display correctly, requiring a manual page refresh.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. From the reproduction you provided, we can see that there're things missing in your setup –  more specifically, the setup code that is mentioned [in our documentation](https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax):

``` js
window.MathJax = {
  tex: {
    inlineMath: [["\\(", "\\)"]],
    displayMath: [["\\[", "\\]"]],
    processEscapes: true,
    processEnvironments: true
  },
  options: {
    ignoreHtmlClass: ".*|",
    processHtmlClass: "arithmatex"
  }
};

document$.subscribe(() => { 
  MathJax.typesetPromise()
})
```

Also remember to add this to `mkdocs.yml` (see link above)
