### ISSUE TITLE
Suggested configurations

### ISSUE THREAD

**Issue by ViktorQvarfordt** [squidfunk/mkdocs-material#641]
- Allow hex colors, not just the predefined ones.
- Allow side bar to be always visible.
- The navigation style in the sidebar is not very useful, one cannot see all sub-pages without clicking through all "dropdowns". Any plans on making the sidebar more like the readthecdocs theme?

**Comment by ViktorQvarfordt** [comment]
Hm, regarding "Allow side bar to be always visible." I was simply using a slightly too narrow browser window. It looks great on wider windows. So, would it be possible to set max-width on that media query to be smaller.

I realize that perhaps I should simply modify the theme from scratch to get what I want

**Comment by squidfunk** [comment]
> I realize that perhaps I should simply modify the theme from scratch to get what I want

The theme is heavily opinionated, so most probably: yes 👍
