### ISSUE TITLE
Add mike alias name to version selector

### ISSUE THREAD

**Issue by corykinney** [squidfunk/mkdocs-material#6436]
### Context

I searched through the documentationa nd previous issues and couldn't find anything, hopefully I didn't miss anything. 

### Description

Currently the version selector shows the identifiers for the documentation versions deployed with `mike`. If it's not difficult to implement, I would suggest adding a toggle to allow displaying the alias for a version in parentheses in the version selector. Example:
```
0.3 (dev)
0.2 (stable)
0.1
```

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Setting up versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning)

### Use Cases

This would provide clarity when documentation for the development branch is available, so that the user understands why the default version served is not the highest version number.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. We can investigate this reasonable feature request in the future.
