### ISSUE TITLE
Upstream icon sets removing icons is a breaking change

### ISSUE THREAD

**Issue by iBug** [squidfunk/mkdocs-material#6440]
### Bug description

When upgrading from 9.4.12 to 9.4.13, my site using `simple/atom` as site icon broke. It seems like Simple Icons removed `atom.svg`, and the removal is introduced via 9c01605149e3bfabfb32fcf928cac207fb809cde.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Icons, Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)

### Reproduction

[9.4.14-icons.zip](https://github.com/squidfunk/mkdocs-material/files/13556441/9.4.14-icons.zip)

### Steps to reproduce

Run `mkdocs build`:

```text
  File "/home/ubuntu/t/env/lib/python3.10/site-packages/material/templates/partials/logo.html", line 8, in top-level template code
    {% include ".icons/" ~ icon ~ ".svg" %}
  File "/home/ubuntu/t/env/lib/python3.10/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/simple/atom.svg
```

This builds normally with 9.4.12, or supposedly, any commit before 9c01605149e3bfabfb32fcf928cac207fb809cde.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

### Other notes

I'm not sure how this should be fixed. To me, it doesn't make sense simple updating a package through a patch version (9.4.x → 9.4.x) breaks the site build. Maybe care be taken next time, or at least bump the minor version (e.g. 9.4 → 9.5)?

I can imagine users getting frustrated to see their site stop building, only to find that an icon (or worse, multiple icons) have disappeared from the theme.

**Comment by squidfunk** [comment]
Thanks for reporting. You're technically right, but we can't issue major versions if icons get added or removed, I'm sorry. I also don't completely understand why some icons get removed. The other option for us would be to pin the icon dependencies and only update them once we release a major version, but then users would complain that several icons are not available as they're upstream. I hope you understand that this is essential a decision of economics.

**Comment by squidfunk** [comment]
I'm happy to discuss other options, e.g., maybe we can move out the icons of this project into separate packages, but we currently have no bandwidth to fix this. If you'd be willing to investigate how we can make this more resilient without pushing out major versions every other week, we'd definitely consider adopting it.

**Comment by iBug** [comment]
It seems viable to me to filter out removals when updating icon dependencies, and only refresh the icon stock entirely (i.e. actually remove the icons that have already been removed upstream) when issuing major (or maybe minor) revisions. A script or two should be able to pull this off.

**Comment by squidfunk** [comment]
The icons in `material` are generated on each build, so there's no way to keep them around without significant changes to our build process, which we're not intending to do. As I said, we can consider moving icons into separate packages so they can be updated individually, but we're not planning to change the build process.
