### ISSUE TITLE
Page is not loading properly on the after the fresh setup.

### ISSUE THREAD

**Issue by abhisheksahnii** [squidfunk/mkdocs-material#6444]
### Context

Newbie to MKDOCS.

After the fresh installation, the default page is not loading correctly.  Still determining if someone already face the issue.

![Screenshot 2023-12-06 105318](https://github.com/squidfunk/mkdocs-material/assets/22940722/35c2e915-fcb3-4a43-9725-a35cc77f90ab)

### Bug description

Newbie to MKDOCS.

After the fresh installation, the default page is not loading correctly. Still determining if someone already face the issue.

![Screenshot 2023-12-06 105318](https://github.com/squidfunk/mkdocs-material/assets/22940722/dbe8889e-3c9c-44d0-a03e-6206bd8942bb)

pip 23.2.1
Python 3.11.7
mkdocs, version 1.5.3

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

https://squidfunk.github.io/mkdocs-material/getting-started/

https://www.youtube.com/watch?v=Q-YA_dA8C20

### Steps to reproduce

https://squidfunk.github.io/mkdocs-material/getting-started/

Followed exactly same steps as mentioned 

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This issue does not contain a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), as requested in our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/), which you assured to have read (see checkboxes). I'm sorry, but without it, we're not able to help you and can't consider this a problem with our code base. We can reopen the issue once you manage to create a reproduction.
