### ISSUE TITLE
Suggest changing auto reload configuration when using abbreviations glossary outside docs folder

### ISSUE THREAD

**Issue by johnthagen** [squidfunk/mkdocs-material#6456]
### Description

The abbreviations documentation recommends using an `includes/abbreviations.md` file for the glossary. When I tried this out, I noticed that the default project will not reload automatically when that file is changed. 

### Related links

- https://squidfunk.github.io/mkdocs-material/reference/tooltips/?h=abbr#adding-a-glossary

### Proposed change

Recommend adding a small tip recommending that the user change their hot-reload configuration to include the `include/` folder so that the reload experience works for the glossary.

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for suggesting. Would you like to add this yourself in a PR?

**Comment by johnthagen** [comment]
I would be happy either way. I was not actually sure how to change the reload directories though?

**Comment by squidfunk** [comment]
I think adding them to [`watch`](https://www.mkdocs.org/user-guide/configuration/#watch) should be sufficient.

**Comment by johnthagen** [comment]
Yes, that worked. I will open a PR.

**Comment by squidfunk** [comment]
Perfect, thanks!
