### ISSUE TITLE
Tags plugin: second level index – group pages by other tags

### ISSUE THREAD

**Issue by alanpt** [squidfunk/mkdocs-material#6463]
### Context

Our documents are tagged by one or more feature, functionality. And stored within folders (howto, tutorial, explantion, resource).  This is easy to browse through and works well for searching.

### Description

When I go to a custom `tags_extra_files` page for one of those feature or functionality tags, I would like to see all the documents grouped by the other tags those documents share. Currently it only lists the pages with that tag ungrouped.

This would make it very easy to automate useful connections.  

Also if we had a tags_extra_file page for #newfeature, we would have all the new features grouped by feature or functionality.

I thought this might be a more mkdocs way of doing things instead of inserting something like this in to pages: `{{list of pages tagged #tutorial, #callcenter}}` - which I would be just as happy being able to do.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)

### Use Cases

For example this list of documents with the tags:

    "how_to_use_the_callcenter.md" tagged #callcenter and #howto
    "about_the_callcenter.md" tagged #callcenter and #explanation
    "add_users_to_callcenter.md" tagged #callcenter and #howto and #newfeature

When I go to the tag page defined in `tags_extra_files` called callcentertags.md it would list all the pages with #callcenter but the items are grouped within their other tags.

So the callcentertags.md file would show a list like this:

> **Callcenter**
> 
> #howto
> [  how_to_use_the_callcenter.md](url)
> [  add_users_to_the_callcenter.md](url)
> 
> #explanation
> [  about_the_callcenter.md](url)
> 
> #newfeature
> [  add_users_to_the_callcenter.md](url)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Let's let that request sit here for a while and see if others find it useful as well. Regardless, we'll see how we can maybe make this happen when we work on the tags plugin again. We're planning to make the tags plugin much more flexible in the future, but it's currently not a priority.

**Comment by squidfunk** [comment]
This was implemented as a third party plugin!
https://github.com/alanpt/mkdocs-tag-navigation-generator

**Comment by squidfunk** [comment]
Please see the announcement in #6517.
