### ISSUE TITLE
Title breadcrumbs and navigation changing

### ISSUE THREAD

**Issue by brendo** [squidfunk/mkdocs-material#647]
## Description

Recently upgraded to v2.x of MkDocs Material (and v0.17.x of MkDocs) and we've noticed a slight difference in the breadcrumbs, and the navigation structure. I've taken screenshots of before/after!

### Expected behavior

![screen shot 2017-12-21 at 5 56 06 pm](https://user-images.githubusercontent.com/69268/34245992-69db1134-e678-11e7-945a-855ef27d1f86.png)

Note the breadcrumb is separated by a `/`, and the title is `README` (last part of breadcrumb and in the navigation).

### Actual behavior

![screen shot 2017-12-21 at 5 56 13 pm](https://user-images.githubusercontent.com/69268/34246014-8a7aec98-e678-11e7-887e-5e125a2d190b.png)

Now on the initial navigation dropdown, the link remained as README, but once clicked, it changed to be the H1 of the Markdown (Temando Account Service).

The breadcrumb is also no longer separated by a `/`

### Steps to reproduce the bug

Uh, this is tricky. It worked in our [Docker image](https://hub.docker.com/r/temandodx/doc-platform/builds/bib3tzc7fnprwokmh8uxmyh/) when locked at Mkdocs 0.16 and MkDocs Material 1.12.2. We recently upgraded [our image ](https://hub.docker.com/r/temandodx/doc-platform/builds/bxnpp5nmlbvniux7qzvsndc/) to include MkDocs 0.17.2 and MkDocs Material 2 and have now started to notice the behaviour.

We are not defining any pages structure in this file.

### Package versions

[From Travis](https://travis-ci.org/temando/docker-doc-platform/builds/318414242):

* Python: 2.7.14
* MkDocs: 0.17.2
* Material: 2.2.5

### Project configuration

Will try to provide an example soon (after Dec 27th).

### System information

* OS: MacOS v10.12.6
* Browser: Chrome 63.0.3239.84

**Comment by squidfunk** [comment]
The original theme doesn't include the breadcrumbs anymore. It was dropped because of tab navigation and they are kind of redundant with the navigation on the side. You probably have overridden the partial and still include dropdowns. Would you mind removing the breadcrumbs?

**Comment by brendo** [comment]
Ah I didn't realise that! Could it be added to the changelog?

Won't have time to touch this until after Christmas, but thanks for the quick reply! Hope you have a happy and safe holidays

**Comment by harveyslash** [comment]
Can I please see your mkdocs.yml ? 
I haven't figured out how to use collapsible menus in the left sidebar like you have

**Comment by squidfunk** [comment]
@harveyslash just nest pages one level deep, the navigation will automatically nest.

**Comment by harveyslash** [comment]
My current page tree looks like this : 

```
pages:
  - General: index.md
  - api-v0.1:
    - Welcome: api-v0.1/index.md
    - Api Guidelines: api-v0.1/Guidelines.md
      - Api TEST: api-v0.1/TEST/Guidelines.md
```

But I don't seem to achieve the same effect

**Comment by squidfunk** [comment]
> Ah I didn't realise that! Could it be added to the changelog?

I will add it retrospectively, I'm sorry I forgot.

**Comment by squidfunk** [comment]
@harveyslash try:

```
pages:
  - General: index.md
  - api-v0.1:
    - Welcome: api-v0.1/index.md
    - Api Guidelines:
      - Api TEST: api-v0.1/TEST/Guidelines.md
```

You cannot either make a subsection or link a document in an entry, but not both (API Guidelines). This is a limitation of MkDocs, not Material.

**Comment by brendo** [comment]
You were correct, the partial was overridden and included the breadcrumbs. I've removed this now so that problem has been resolved.

I'm still experiencing the oddness with the navigation title changing when selecting different pages. Going to have a dig to find out what's causing that, I have a feeling it's MkDocs itself and not the theme.

**Comment by squidfunk** [comment]
The navigation title now changes when you scroll past the h1 to the menu title. This was introduced some versions ago. Do you mean this?

**Comment by brendo** [comment]
Ah I didn't know that either. Could that also be added to the CHANGELOG? I wasn't expecting that behaviour. I'll see if I can capture a screencast of it because at the moment it looks 'wrong' rather than helpful.

**Comment by brendo** [comment]
All clear, I've narrowed it down to MkDocs! Thanks for the help!

https://github.com/mkdocs/mkdocs/issues/1375

**Comment by squidfunk** [comment]
@brendo The sliding title was added to the CHANGELOG, but I will add entries for the breadcrumbs. Sorry about that.
