### ISSUE TITLE
Exceptions in markdown nested list

### ISSUE THREAD

**Issue by miniwater** [squidfunk/mkdocs-material#6509]
### Bug description

I don't know how to describe this, but markdown nested lists are not working as expected.

The markdown documentation says it takes two spaces to nest, but in mkdocs it takes four spaces to display properly!
<img width="1144" alt="20231214205822" src="https://github.com/squidfunk/mkdocs-material/assets/14000053/aa82da9a-a365-4bf4-ac4f-2a8b1596e2da">
<img width="638" alt="20231214210043" src="https://github.com/squidfunk/mkdocs-material/assets/14000053/12c11205-b827-4c7f-ae38-6ccca5fbce2d">

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[bug.zip](https://github.com/squidfunk/mkdocs-material/files/13673443/bug.zip)

### Steps to reproduce

```
* aaa
* bbb
  * two-spaces
  * two-spaces
* ccc
    * four-spaces
    * four-spaces
* ddd
```
* aaa
* bbb
  * two-spaces
  * two-spaces
* ccc
    * four-spaces
    * four-spaces
* ddd

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by miniwater** [comment]
version 9.5.2

**Comment by alexvoss** [comment]
This is an upstream, um, non-issue. MkDocs uses Python Markdown for the rendering of Markdown content and they have been over this before https://github.com/Python-Markdown/markdown/issues/451.
