### ISSUE TITLE
How to configure nav to include dropdown?

### ISSUE THREAD

**Issue by ketozhang** [squidfunk/mkdocs-material#652]
I don't understand HTML very well and I've tried to implement dropdowns on Materials using MkDocs theme as a guide (looked at `nav.html`, `nav-item.html` and `nav-sub.html`). 

Basically I want the tab feature in Materials to able to enable dropdown features as seen in MkDocs theme. I find having both the table of contents (on the right) and a navigation menu (on the left) to be too cramped.

**Comment by squidfunk** [comment]
Well, I can only point you in the direction - the [customization guide](https://squidfunk.github.io/mkdocs-material/customization/) - as my time is very limited, I'm sorry. Maybe somebody else can help.

**Comment by ketozhang** [comment]
That is where I came from after-all. Thanks for trying. Maybe I should just get into HTML :\ even thought that was never the point of MkDocs.

**Comment by squidfunk** [comment]
No worries, sorry I cannot help you more.
