### ISSUE TITLE
Missing TOC on some pages

### ISSUE THREAD

**Issue by johannes-z** [squidfunk/mkdocs-material#654]
## Description

I'm missing the TOC (upper right corner) on some pages, while I get the TOC on some other pages. 

### Expected behavior

Have the TOC show up on all pages.

### Actual behavior

TOC doesn't show up on some pages.

### Steps to reproduce the bug

No TOC: https://ehrpg.github.io/qstar/settings/stalker/equipment/
With TOC: https://ehrpg.github.io/qstar/settings/stalker/rules/

### Package versions

* Python: `3.6.4`
* MkDocs: `0.17.2`
* Material: `2.2.6`

### Project configuration

https://github.com/ehrpg/qstar/blob/master/mkdocs.yml

**Comment by johannes-z** [comment]
With trial and error I found that all the headings must be h2 but the first one, which needs to be h1. Also it seems as if this is a mkdocs issue, not a mkdocs-material one. Sorry for the inconvenience!

**Comment by cukal** [comment]
I have the same problem, not sure if this is a mkdocs issue. When using the standard mkdocs or readthedocs theme the TOC gets build correctly for a markdown file that contains multiple h1 levels with subsequent h2 levels, TOC gets build with clickable links to the section in the page. Switching to material theme shows only the first h1 level in the TOC, never any secondary h1 levels.
