### ISSUE TITLE
Projects plugin: No such file or directory: '.cache/plugin/projects/manifest.json'

### ISSUE THREAD

**Issue by alexvoss** [squidfunk/mkdocs-material#6543]
### Context

Running into issues using the latest version of the projects plugin. This is the first one and I was able to create a minimum reproduction that shows the problem on Linux - but not MacOS.

### Bug description

When using the projects plugin with a trivial two subprojects, `mkdocs serve` produces an error message:

```
mkdocs serve
INFO    -  Building documentation...

FileNotFoundError: [Errno 2] No such file or directory: '.cache/plugin/projects/manifest.json'
```

This happens on Linux (Debian 12) but not on MacOS.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/plugins/projects/

### Reproduction

[9.5.2+insiders.4.47.1-cache-manifest-not-found.zip](https://github.com/squidfunk/mkdocs-material/files/13717299/9.5.2%2Binsiders.4.47.1-cache-manifest-not-found.zip)

### Steps to reproduce

run `mkdocs serve` on the reproduction

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Are you sure you pulled the latest master?

This was already fixed in https://github.com/squidfunk/mkdocs-material-insiders/commit/afbb2303e76b10fd2a2b8652a0251cd3eaa87701.

**Comment by alexvoss** [comment]
Right, now that I have completely re-installed the venv, the issue does not appear anymore. So, I need to ask myself why upgrading does not seem to have done the job. I had created an alias for this because I have to do this so often(*):

```
alias upgrade_mkdocsi='pip install --upgrade git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git'
```

When I expand this with `Ctrl-Alt-E`, I get the pip command that I would expect, the same as in the [Insiders upgrade instructions for the latest from GitHub](https://squidfunk.github.io/mkdocs-material/insiders/upgrade/#how-to-upgrade-pip-upgrade-to-latest-development), except with my token put in. Anything I am getting wrong here or is there a problem with `pip` or the instructions for upgrading? 

(*) I know I could use Git directly and `pip install -e .` things but in some way it is useful that I test the other install paths, so I did not switch to doing this except if I want to debug something.

**Comment by squidfunk** [comment]
Hmm, good question. I'm not sure what is happening here, but it does not seem to be an issue with Insiders, but with. I'm also no help, because I use `pip install -e <path-to-folder-where-insiders-is>`, but maybe ask on StackOverflow or somebody else that has a good grasp of git why this is happening?

Closing as non-actionable.
