### ISSUE TITLE
What CSS did you use?

### ISSUE THREAD

**Issue by Serhioromano** [squidfunk/mkdocs-material#655]
I would like to add some changes to the layout. Add optional bredcrumps, change tabs stile to mo like Material tabs

![2018-01-08_15-14-25](https://user-images.githubusercontent.com/650741/34664639-134ef714-f487-11e7-9dc2-014cadc64e22.png)

But I cannot figure out what Material CSS library did you use?

**Comment by squidfunk** [comment]
No framework is used, the CSS is implemented by Material itsself.

**Comment by Serhioromano** [comment]
Can you give a link to that CSS? I want to learn what classes do they use.

**Comment by squidfunk** [comment]
It's contained in the repository, see https://github.com/squidfunk/mkdocs-material/tree/master/src/assets/stylesheets

**Comment by Serhioromano** [comment]
I know where CSS is in your directory. I want to read documentation of this CSS, see examples by the one who created this CSS. Like Metrialize, Meterial UI and so on. I can go there and see how to markup tabs, lists, cards, ...

**Comment by kipwaits** [comment]
I don't think this question was properly addressed. Was all of the CSS in this repository written solely for this project, or does it have another source?

**Comment by squidfunk** [comment]
Yes, everything was written from scratch.
