### ISSUE TITLE
Issue a single warning when symlinking isn't supported

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#6550]
### Description

As discussed in https://github.com/squidfunk/mkdocs-material/issues/4051#issuecomment-1855378900, when the `privacy` plugin is enabled and symlinking isn't supported (especially on Windows PCs), MkDocs issues a lot of `Couldn't create symbolic link for '{file}'` warnings during build. 

This is because the warning is repeated for every page and every linked file.

Instead, I suggest issuing **one** single warning that symbolic linking isn't supported and therefore files can't be cached.

### Related links

https://github.com/squidfunk/mkdocs-material/issues/4051

### Use Cases

See description

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm not sure we can distinguish in the plugin whether symlinking should actually work or not (as we have no way to inspect user permissions), so I think a better idea is to introduce a new setting for changing the log level of the plugin – i.e., if warnings and info messages should be logged at all. We recently started adding this to newer plugins like the projects plugin, allowing to set [`log`](https://squidfunk.github.io/mkdocs-material/plugins/projects/#config.log) and [`log_level`](https://squidfunk.github.io/mkdocs-material/plugins/projects/#config.log_level).

**Comment by squidfunk** [comment]
Added in [`b1d0d92`](https://github.com/squidfunk/mkdocs-material-insiders/commit/b1d0d92184132afd0e68d8fedce789c4686acf8b) – there are now [new settings for logging](https://squidfunk.github.io/mkdocs-material/plugins/privacy/#logging) for the privacy plugin. To mitigate reporting of failed symlinks, you can either disable logging altogether, or just use:

``` yaml
plugins:
  - privacy:
      log_level: error
```

As usual, this can also be set with [environment variables](https://www.mkdocs.org/user-guide/configuration/#environment-variables).

**Comment by squidfunk** [comment]
As an addendum: note that symlinking is only ever tried when the downloaded URL does not include a file extension, which means the mime type of the file is not deducible. This is also apparent from the inline comments:

https://github.com/squidfunk/mkdocs-material/blob/e8504fdffb959fe9fdf0b44da731ac594a199536/src/plugins/privacy/plugin.py#L395-L413

**Comment by squidfunk** [comment]
Released as part of [9.5.4+insiders-4.50.0](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.50.0)
