### ISSUE TITLE
Cannot figure out how to enable code highlights? 

### ISSUE THREAD

**Issue by Serhioromano** [squidfunk/mkdocs-material#656]
All my code examples that was perfectly highlighted  readthedoc and default them, are now not highlighted at all. I use \`\`\`php to insert codes.

**Comment by martinbira** [comment]
Is Pygments and CodeHilite installed and added to your mkdocs.yml?

https://squidfunk.github.io/mkdocs-material/extensions/codehilite/

```
markdown_extensions:
  - codehilite:
```

**Comment by Serhioromano** [comment]
Yep, I had that and Pygment installed. I've found that even in default template particulary php is not working. If I start code with `<?php` then it highlights but if I start PHP code right away, it does not highlight.

**Comment by martinbira** [comment]
Could be something with Pygments then?
http://pygments.org/docs/lexers/?highlight=php#lexers-for-php-and-related-languages

> _startinline_
>   If given and True the lexer starts highlighting with php code (i.e.: no starting `<?php` required). The default is False.

**Comment by Serhioromano** [comment]
I see. Thank you.

**Comment by facelessuser** [comment]
There is a way to get PHP to highlight without `<?php`.  See https://github.com/squidfunk/mkdocs-material/issues/506.
