### ISSUE TITLE
Navigation Path documentation doesn't work

### ISSUE THREAD

**Issue by jonny-harte** [squidfunk/mkdocs-material#6566]
### Description

Setting up navigation.path doesn't work as explained in documentation.

I've added the feature to my mkdocs.yml but it doesn't work, breadcrumbs aren't displaying on my pages. Are there are settings required or combinations of features that would stop if from showing?

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-path/)

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, it does, if you follow our documentation. Note that the [`navigation.path`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-path) feature is currently reserved to sponsors, so make sure you're using [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/). If you're using Insiders at indeed find it not to be working, please create a proper [bug report](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) (not a documentation issue) and provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). Thank you!
