### ISSUE TITLE
Blog index should show part of article instead of the full article

### ISSUE THREAD

**Issue by nicfv** [squidfunk/mkdocs-material#6575]
### Context

Blog Plugin

### Description

In my blog index page, it shows each article in full, back-to-back. This is great for shorter articles, but in some of my longer articles (~18,000 chars) it still shows the entire article in the index, making the index a very large webpage. I suggest to have an option to limit the displayed article length (and possibly the number of articles) shown in the index. What's interesting is that there is a "Continue reading" button at the end of each article anyway, but it doesn't really have any use since I can read all the way to the end on that page.

### Related links

- https://squidfunk.github.io/mkdocs-material/plugins/blog/

### Use Cases

Writing blogs

### Visuals

> .../blog/index.md

###### December 31, 2023 - in [Category](#hyperlink-to-category) - 10 minute read

# [Blog Title](#hyperlinks-to-article-page)

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est...

[Continue reading](#hyperlinks-to-article-page)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexvoss** [comment]
You need to put an [excerpt marker](https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/?h=excerpt#adding-an-excerpt) into your blog posts to define where the cut is made between the short version in the index and the remainder of the text. Just add `<!-- more -->` at the point.

**Comment by nicfv** [comment]
@alexvoss that's exactly what I was looking for! Thank you, I didn't know that feature already existed. It's such a small note in there I might have skimmed over it.
