### ISSUE TITLE
Search not finding all occurrences

### ISSUE THREAD

**Issue by johannes-z** [squidfunk/mkdocs-material#658]
## Description

In my installation of mkdocs and the mkdocs-material theme some occurrences (in this case, all of them) don't show up in the search.

### Expected behavior

Find all occurrences of the word.

### Actual behavior

No occurrences showing up.

### Steps to reproduce the bug

Go to [https://ehrpg.github.io/qstar/](https://ehrpg.github.io/qstar/) and enter `Might`. In my case, nothing shows up. 

### Package versions

* Python: 3.6.4
* MkDocs: 0.17.2
* Material: 2.3.0.

### Project configuration

[https://github.com/ehrpg/qstar/blob/master/mkdocs.yml](https://github.com/ehrpg/qstar/blob/master/mkdocs.yml)

### System information

* OS: Windows 10
* Browser: Chrome v63

**Comment by squidfunk** [comment]
Hmm, that's strange. Other words are found. Could you try to narrow it down and make a small, reproducible scenario? Otherwise I have to wait until I have more time to look into this in detail.

**Comment by johannes-z** [comment]
I've created a MWE. Just copied the section from the original docs. Could it be that lunr thinks that "might" is a stopword, as in "he might do something"?

**Comment by makshh** [comment]
https://github.com/olivernn/lunr.js/blob/c7ce5824ad298537938f9a39d40d2577459b74fd/lunr.js#L1049

**Comment by johannes-z** [comment]
Is there another way to "ignore" certain words rather than deleting the word from `application.js`?

**Comment by squidfunk** [comment]
Awesome, thanks @makshh, haven't thought of that! Currently there is no option to ignore certain words, as this list is hardcoded in an upstream repository (lunr.js) which Material uses. In theory we could add an option to ignore the stop words (don't register the filter, as done [here](https://github.com/squidfunk/mkdocs-material/blob/6dc12758bbe356236d6d403127745463b127648e/src/assets/javascripts/components/Material/Search/Result.jsx#L178)) but that would heavily degrade search performance and thus be probably of very little benefit.
