### ISSUE TITLE
Offline plugin instructs to disable Instant Loading but Instant Loading has no `enabled` setting

### ISSUE THREAD

**Issue by johnthagen** [squidfunk/mkdocs-material#6587]
### Description

The offline plugin can be optionally enabled or disabled with an ENV variable:

```yaml
plugins:
  - offline:
      enabled: !ENV [OFFLINE, false]
```

And the Limitations sections says to be "sure to disable the following settings", one of which is Instant Loading. But the instant loading docs don't mention a similar way that one could disable Instant Loading with an ENV variable.

### Related links

- https://squidfunk.github.io/mkdocs-material/plugins/offline/#config.enabled
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading

### Proposed change

Document how a user can disable the features that conflict with `offline` mode in the same way they can disable the `offline` plugin.

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. Currently, the easiest thing is to use two separate configurations and [configuration inheritance](https://www.mkdocs.org/user-guide/configuration/#:~:text=Configuration%20Inheritance,-Generally%2C%20a%20single&text=To%20define%20the%20parent%20for,location%20of%20the%20primary%20file.). We'll evaluate if we can make the offline plugin simpler to use in the future. Other than that, we cannot maintain parallel documentation on each and every configuration option, so the best idea is to consult the MkDocs configuration for this.

**Comment by johnthagen** [comment]
Thanks for the information, @squidfunk!

**Comment by squidfunk** [comment]
Yes, that is exactly what we're going to investigate.
