### ISSUE TITLE
Search: full-text search not work properly

### ISSUE THREAD

**Issue by ledel037** [squidfunk/mkdocs-material#6589]
### Bug description

![image](https://github.com/squidfunk/mkdocs-material/assets/49937123/e5e59fa0-f134-45a2-bafa-cd7c477b8be9)
Search 'basic' is not work.
Search 'api' worked..

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

...

### Steps to reproduce

search

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. However, this issue does not contain a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), yet does it live up our [bug reporting standards](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Closing as incomplete. You can either provide a complete, proper issue, or ask on our [discussion board](https://github.com/squidfunk/mkdocs-material/discussions) for help.
