### ISSUE TITLE
Tags update breaks macros plugin

### ISSUE THREAD

**Issue by Vasperous** [squidfunk/mkdocs-material#6594]
### Bug description

After updating to the latest Material release (9.5.3+insiders.4.49.0) I noticed that the macros plugin was no longer working.  For example, `{{x}}` was being displayed instead of the definition of `X` (which is an icon).

By removing the tags plugin I was able to see the macros plugin work as expected.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[9.5.3+insiders.4.49.0-macros-tags-issue.zip](https://github.com/squidfunk/mkdocs-material/files/13832360/9.5.3%2Binsiders.4.49.0-macros-tags-issue.zip)

### Steps to reproduce

1. Create a new project
2. Add macros to the plugins list
3. Add the macros file and update the mkdocs.yaml
4. Build documentation and see macros plugin working
5. Add tags plugin
6. Check rebuilt documentation

### Browser

Other

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by jaceklaskowski** [comment]
Confirmed. Same experience and had to pin mkdocs-material version to [9.5.2-insiders-4.47.1](https://github.com/japila-books/apache-spark-internals/blob/main/requirements.txt#L1). Glad I'm not alone and hoping for a quick fix ❤️

**Comment by squidfunk** [comment]
Thanks for reporting! I'll look into it.

**Comment by squidfunk** [comment]
Fixed in [`39ea162`](https://github.com/squidfunk/mkdocs-material-insiders/commit/b968818e2ca8056b83c11bdb38cbd6be3085d410).

This should fix interop with all third-party plugins that alter the Markdown of a page, not only with the macros plugin.

**Comment by squidfunk** [comment]
Released as part of [9.5.3+insiders-4.49.1](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.49.1).

**Comment by jaceklaskowski** [comment]
Confirmed. Works like a charm! Danke schon mein Freund for such a quick turnaround! ❤️
