### ISSUE TITLE
Add Docker run commands also for Windows

### ISSUE THREAD

**Issue by adminradio** [squidfunk/mkdocs-material#660]
## Add Docker run commands also for Windows on Page "Getting started".

It took me a while to find these, so I thought other users may be interested too.

### Windows command prompt (cmd.exe):
`docker run --rm -it -p 8000:8000 -v "%cd%":/docs squidfunk/mkdocs-material`

### Windows PowerShell:
`docker run --rm -it -p 8000:8000 -v ${PSScriptRoot}:/docs squidfunk/mkdocs-material`

**Comment by squidfunk** [comment]
I adjusted the documentation - found a more portable command and added a little description for the `cmd.exe` case (is that actually still used?)

**Comment by adminradio** [comment]
Ah, didn't know that ${PWD} works in PowerShell too, but looks reasonable.

**mkdocs-material** is easy and beautiful and it may be happen, that not so skilled people are want to try it. PowerShell on the other hand isn't easy and CMD is well known for a long time. So yes, it could be used. :)

It would be better to write down the full command because **a)** it is not absolutly clear if the quotes are part of the command or not and **b)** it could be copied as complete command into the clipboard. Less error prone.
