### ISSUE TITLE
Plugin 'material/privacy' option 'links_attr_map': Unrecognised

### ISSUE THREAD

**Issue by jiangyinzuo** [squidfunk/mkdocs-material#6601]
### Bug description

When I add the following config to `mkdocs.yml` according to https://squidfunk.github.io/mkdocs-material/plugins/privacy/?h=attr#config.links_attr_map
```
plugins:
  - privacy:
      links_attr_map:
        target: _blank
```

`mkdocs serve` command outputs a WARNING:
```
WARNING -  Config value 'plugins': Plugin 'material/privacy' option 'links_attr_map': Unrecognised
           configuration name: links_attr_map
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Documentation built in 0.41 seconds
INFO    -  [13:05:23] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO    -  [13:05:23] Serving on http://127.0.0.1:8000/
INFO    -  [13:05:25] Browser connected: http://localhost:8000/
```

and the external links doesn't have the attribute `target="_blank"`.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/plugins/privacy/?h=attr#config.links_attr_map

### Reproduction

[reproduction.zip](https://github.com/squidfunk/mkdocs-material/files/13838171/reproduction.zip)

### Steps to reproduce

1. run `mkdocs serve`
2. click the external link in index.md, it doesn't have attribute `target="_blank"`.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. External link processing is only available in [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/), and thus currently reserved to [sponsors](https://github.com/sponsors/squidfunk), which includes the [`links_attr_map`](https://squidfunk.github.io/mkdocs-material/plugins/privacy/#config.links_attr_map) setting. If you would like to use this, you could consider becoming a [sponsor](https://github.com/sponsors/squidfunk) of the project ☺️
