### ISSUE TITLE
Allow selecting "icons" or "emojis" in the "Icons, Emojis" search box

### ISSUE THREAD

**Issue by iBug** [squidfunk/mkdocs-material#6628]
### Description

On [Icons, Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/), add two checkboxes to allow users to select if they want icons to show up in search results, or emojis, or both.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- [Icons, Emojis](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/)

### Use Cases

When I head over to that page, I pretty much always want icons (bundled SVGs) and not emojis. Emojis coming up in the results only slow down my search. It would be nice if I can filter out just icons, and for those who only look for emojis.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. We're likely going to integrate emoji and icon search directly into the new search as a further data source, so this will be tackled once we got a stable working version of the new search.

**Comment by squidfunk** [comment]
I've added a select field to narrow the search to icons or emojis in . It's [already live](https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/):

https://github.com/squidfunk/mkdocs-material/assets/932156/7aed7eb1-aaa9-41f8-b36d-8f4dc96521e5

It's not a perfect solution, it's more like a bandaid, as we're thinking of moving the icon and emoji search into the search box anyways, given that we're currently revising the search implementation (https://github.com/squidfunk/mkdocs-material/issues/6307). In the meantime, this should do.
