### ISSUE TITLE
Full width (or 80% width layout)

### ISSUE THREAD

**Issue by fr500** [squidfunk/mkdocs-material#664]
First of all, thank you for this amazing template

## Description

Would it be possible to have a layout that allows better use of horizontal space?
https://docs.libretro.com/library/beetle_psx/

Some docs get a bit too long for reading in the current format.

Also do you think it would be possible to have a "hamburguer menu" to hide/show the left panel?

### Package versions

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`

### Project configuration

https://github.com/libretro/docs/blob/master/mkdocs.yml

### System information

* OS: Ubuntu 16.04
* Browser: Firefox Quantum

**Comment by squidfunk** [comment]
This was already asked in #619, #242 and probably some other issues - it's not on the roadmap, i'm sorry, but you can achieve some stuff with custom CSS and JS.

**Comment by fr500** [comment]
NP, thanks for responding

**Comment by squidfunk** [comment]
You're welcome! Hard to cover all possible cases with one template, so it will always be opinionated. I try to add customization wherever possible.
