### ISSUE TITLE
Javascript stops working on the website when the user's browser local storage has invalid value.

### ISSUE THREAD

**Issue by McDic** [squidfunk/mkdocs-material#6645]
### Context

We discussed about this bug [here](https://github.com/squidfunk/mkdocs-material/discussions/6644#discussioncomment-8121881) and @kamilkrzyskow suggested me to make an issue.

### Bug description

If your browser has an invalid values like palette index in cache, the website will fail to load the whole Javascript stuffs.

I made a minimal standalone repository described on `Reproduction` section, so please have a look.

### Related links

- https://github.com/squidfunk/mkdocs-material/discussions/6644#discussioncomment-8121881
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=palette#color-palette-toggle
- https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/?h=bug

### Reproduction

- 3 palettes: [9.5.3-3_palettes.zip](https://github.com/squidfunk/mkdocs-material/files/13930510/9.5.3-3_palettes.zip)
- 2 palettes: [9.5.3-2_palettes.zip](https://github.com/squidfunk/mkdocs-material/files/13930509/9.5.3-2_palettes.zip)

I made a repository to reproduce the exactly same thing on [this repository](https://github.com/McDic/mkdocs-material-palette-bug-report-2024-01/tree/master). The steps are simple and you can follow and make exactly same `.zip` files.

### Steps to reproduce

The content in this section is copied from [this repository's README.md](https://github.com/McDic/mkdocs-material-palette-bug-report-2024-01) with slight modification.

---

# Bug reproducing repository for [mkdocs-material](https://squidfunk.github.io/mkdocs-material)

This repository is used to introduce users to reproduce `mkdocs-material` bug [discussed here](https://github.com/squidfunk/mkdocs-material/discussions/6644#discussioncomment-8121881).

## Steps to reproduce in local

1. Clone this repository.
2. Make a virtual environment (Python 3.11) for this repository.
3. Run `pip install --upgrade --force-reinstall mkdocs-material` to install `mkdocs-material`.
4. Checkout to [commit ff4d4cf](https://github.com/McDic/mkdocs-material-palette-bug-report-2024-01/tree/ff4d4cf8d253bab0cc74af9c0abbf9907c359871).
5. Run `mkdocs serve` in your terminal to turn on local server.
6. Access `127.0.0.1:8000` from your browser.
7. Press button on the website to make palette to the dark mode.
8. Checkout to [commit a0d3b0b](https://github.com/McDic/mkdocs-material-palette-bug-report-2024-01/tree/a0d3b0b6978b0222de4e5ca1bd8644520535cf92) and refresh your build (`mkdocs serve` will refresh automatically).
9. Enjoy the bug. Javascript stuffs like searching, side navigations wouldn't work.

![reproduced](https://github.com/McDic/mkdocs-material-palette-bug-report-2024-01/raw/master/bug_reproduced.png)

## Steps to reproduce `.zip` files

Since `mkdocs-material` encourages people to [use `.zip` files made by `info` plugin](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#reproduction) instead of making a repository, I am going to make 2 `.zip` files.

1. Run `echo 2_palettes | mkdocs build -f mkdocs_2_palettes.yml`
2. Run `echo 3_palettes | mkdocs build -f mkdocs_3_palettes.yml`

## Proposal to resolve this

I suggest to insert a validation JS code for invalid values in cache.

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in d87c20faf.

**Comment by squidfunk** [comment]
Released as part of [9.5.4](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.4).
