### ISSUE TITLE
Image Representing 'Material for mkdocs' On 'mkdocs Wiki' Is Very Outdated

### ISSUE THREAD

**Issue by yannduran** [squidfunk/mkdocs-material#665]
The [mkdocs wiki page][mkdocs-wiki] shows a very outdated version of the _'Material for mkdocs'_ theme (see the image below), which I don't really think is going to entice people to want to use it.

The only link to [third party themes][third-party-themes] goes to that wiki page.

> A list of third party themes can be found in the MkDocs community wiki. If you have created your own, please feel free to add it to the list.

I just wanted to let you know, as it's not doing Material any favors with that image representing it. As it's a community wiki page, I guess I could upload a more up-to-date image, but I wanted to raise the issue here first.

![image](https://user-images.githubusercontent.com/2031126/35073339-860ddbd2-fc3c-11e7-8474-cfe9d7a70a5a.png)

[mkdocs-wiki]: https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes#material
[third-party-themes]: http://www.mkdocs.org/user-guide/styling-your-docs/#third-party-themes

**Comment by squidfunk** [comment]
Oh, you're right. You are free to update it if you like, I think I didn't provide the image anyway. However, Material gets most traffic from GitHub Pages and Google. Dont know if people really go to the Wiki and the images are not very flattering anyway (in my opinion)

**Comment by squidfunk** [comment]
I just went ahead and updated it, just linked the main image from the documentation. Hope that's fine for the guys.

**Comment by yannduran** [comment]
That looks great! A much better representation of your excellent theme! :-)
