### ISSUE TITLE
The page layout is disordered

### ISSUE THREAD

**Issue by acbin** [squidfunk/mkdocs-material#6660]
### Bug description

When I browse the page, there are occasional issues with the page layout being disordered. Could you please tell me the reason for this? How can I resolve it?

Here is my website: https://doocs.github.io/leetcode

### Related links

Here is my website: https://doocs.github.io/leetcode

### Reproduction

![图片](https://github.com/squidfunk/mkdocs-material/assets/44314231/44b5e7c3-64d2-4774-b891-57e1d9af5f76)

### Steps to reproduce

Reproduction Steps:

- Open the directory and navigate to a specific page.
- Scroll through the page quickly.
- The page experiences layout disarray.

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by katharinalisalin** [comment]
Thanks for reporting. However, you did not attach a [.zip file with a minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file) and therefore did not follow our [bug reporting guideline](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Please provide us with a minimal reproduction, and we'll be happy to take a look. Until then, I'll mark this issue as [incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues) and close it for now.

**Comment by alexvoss** [comment]
We'd also need to know what browser this happens in (add OS info while you are at it, just in case). I tried in Firefox on a Mac and could not see the effect.
