### ISSUE TITLE
`Content tab` feature can't display content above 20 tabs

### ISSUE THREAD

**Issue by Valastiri** [squidfunk/mkdocs-material#6665]
### Context

On our documentation website, we tend to use the content tab to provide extra context to the layout of different aircraft displays. 

We accomplish this by associating areas of the image with numbers and using the content tab feature to explain that section with more detail.

You can find an [example here](https://docs.flybywiresim.com/pilots-corner/a32nx-briefing/pfd/flags-messages/#description)  where our content tab implementation has about ~25 tabs. 

### Bug description

Based on the context above we noticed that if the feature contains more than 20 tabs, it fails to display the content underneath the tab. The title of the tab can still be interacted with and selected, however no content is visible underneath.

Ideally the content tab should continue display content even after 20 tabs.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [mkdocs-material issues](https://github.com/squidfunk/mkdocs-material/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- [Content Tab Feature Docs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/)

### Reproduction

[9.5.4-content-tab-issue.zip](https://github.com/squidfunk/mkdocs-material/files/13984534/9.5.4-content-tab-issue.zip)

### Steps to reproduce

1. Ensure that the mkdocs.yml config contains the bare minimum to utilize the content tab feature.
2. Create a page that has over 20 content tabs.
3. Use numbers so it's easier to find the 21st tab.
4. Navigate through any tab after the 20th and check to see if any content is displayed underneath. 

---

Tested on Chrome, Firefox, and Edge.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, this is a limitation that we impose to keep the CSS that is necessary to make all of this work to a reasonable size, allowing content tabs to work without JavaScript. You're the first one to ever hit it in years. We're not planning to increase this limit, but you can fork the theme and increase the number of supported tabs here:

https://github.com/squidfunk/mkdocs-material/blob/e8504fdffb959fe9fdf0b44da731ac594a199536/src/templates/assets/stylesheets/main/extensions/pymdownx/_tabbed.scss#L61-L62

https://github.com/squidfunk/mkdocs-material/blob/e8504fdffb959fe9fdf0b44da731ac594a199536/src/templates/assets/stylesheets/main/extensions/pymdownx/_tabbed.scss#L159-L160

https://github.com/squidfunk/mkdocs-material/blob/e8504fdffb959fe9fdf0b44da731ac594a199536/src/templates/assets/stylesheets/main/extensions/pymdownx/_tabbed.scss#L209-L210

Note that the CSS will also grow. A better solution is to restructure your site to have fewer tabs. 20 content tabs are too many in most cases to keep content easily discoverable, as it also means that users will have to scroll quite far.

**Comment by Valastiri** [comment]
Thanks for the suggestion! We'll look into it and/or think of alternative methods to display the content as well.
