### ISSUE TITLE
Please update mermaid to 10.7.0.

### ISSUE THREAD

**Issue by pymumu** [squidfunk/mkdocs-material#6687]
### Bug description

The 10.6.1 version of mermaid has a bug that not display graphics correctly.

### Related links

Please refer to: https://github.com/mermaid-js/mermaid/issues/5094

### Reproduction

Please refer to: https://github.com/mermaid-js/mermaid/issues/5094

### Steps to reproduce

Please refer to: https://github.com/mermaid-js/mermaid/issues/5094

### Before submitting

- [ ] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [ ] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [ ] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. I've updated Mermaid.js in f3868a6f1.

Next time, please stick to our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) and provide complete information and a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/). Just deferring us to issues on other repos is not enough, as they might be deleted, edited, etc., so this information is not necessarily permanent. Also note that we reserve the right to close [incomplete issues](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues). Effort in = Effort out.

**Comment by pymumu** [comment]
OK, thank you very much.

**Comment by squidfunk** [comment]
Keeping open until released.

**Comment by squidfunk** [comment]
Released as part of [9.5.5](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.5).
