### ISSUE TITLE
Keep getting "Home" when using `navigation.sections`

### ISSUE THREAD

**Issue by nicfv** [squidfunk/mkdocs-material#6701]
### Context

Navigation

### Bug description

Hi! I'm building a site and using the [navigation.sections](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=naviga#navigation-sections) and [navigation.indexes](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=naviga#section-index-pages) plugins to make the navigation look nicer.

My project directory is as follows:

```
mkdocs.yml
docs/
  index.md
  page-2.md
  Subfolder/
    index.md
    page-2-in-subfolder.md
```

It works excellently for all of my subfolders. Unfortunately, it feels like no matter what I do, I keep getting an extra `Home` link instead of having my project name be a clickable link. Any ideas why this is happening? Thank you! :)

![image](https://github.com/squidfunk/mkdocs-material/assets/24358775/9d22103f-fca8-48c8-be6d-51ac72f8be05)

I currently have these plugins enabled:

```yml
- navigation.sections
- navigation.indexes
- navigation.top
- navigation.footer
- search.suggest
- search.highlight
- search.share
- content.code.copy
```

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
- https://github.com/squidfunk/mkdocs-material/issues/5802

### Reproduction

[z.zip](https://github.com/squidfunk/mkdocs-material/files/14073066/z.zip) - this is a zip file of a simple project

FYI - I really did try to follow the steps in the reproduction guide, but I kept getting the error:

```
ERROR   -  Config value 'plugins': The "navigation.indexes" plugin is not installed
```

### Steps to reproduce

1. Download z.zip
2. Unzip/extract
3. Run `mkdocs build`

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is currently not supported. The top-level title will always be your project's name. This could, in theory, be removed, but please know that we have so many switches and configuration settings for navigation already, that we do not want to make it any more complicated. Thus, we consider this out-of-scope. We might lift this limitation the next time we work on navigation, but we can't tell for sure or put an ETA on that. Thus, please use [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme).

If you're having trouble with theme extension, you can [open a discussion](https://github.com/squidfunk/mkdocs-material/discussions) and ask for help.

**Comment by nicfv** [comment]
Thank you for your response! I just want to make sure there was no miscommunication on my part -

> The top-level title will always be your project's name.

This is actually what I want. I'm just asking how to turn *that* into the clickable link to the index/home page, thus getting rid of "Home" underneath it. If you look at my screenshot, "Subfolder" is a clickable link to the index page in `subfolder/` which is exactly what I want for the top level. I'll try to link a real example if I find one. With that extra bit, does that change your answer at all?

**Comment by squidfunk** [comment]
Yes, you understood correctly. It cannot be made clickable without customization.

**Comment by felker** [comment]
@nicfv just curious if you ever solved this with a theme extension and are willing to share it?

**Comment by nicfv** [comment]
Sorry, I didn't find it worthwhile enough to invest the time into it. Perhaps it's worth looking into the example's repository I sent. If you do end up finding a solution, please share it.
