### ISSUE TITLE
Clicking the same version from the version dropdown takes you to the home page

### ISSUE THREAD

**Issue by syeda-git** [squidfunk/mkdocs-material#6716]
### Bug description

I am using Mike for the version picker function. If there are two versions and you select the other version, the same page in that version show up. However, if you click the same version, you are taken to the Home page of the version.
The expected behavior should be to load the current page and not go to the Home page of the selected version.

### Related links

- [Setting up versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/)

### Reproduction

[9.5.6-versionpicker.zip](https://github.com/squidfunk/mkdocs-material/files/14099225/9.5.6-versionpicker.zip)
[versions.json](https://github.com/squidfunk/mkdocs-material/files/14099228/versions.json)

### Steps to reproduce

1. Unzip the file.
2. Remove the info plugin from mkdocs.yml
3. Run the build
4. Create two folders - 1.0 and 2.0.
5. Copy the build output in both the folders.
6. Put version.json file outside of 1.0 and 2.0 folders.
7. Deploy the output. You should see the version picker.
8. Navigate to about.md
9. From the version picker, select the same version.
Actual result - The URL changes to point to the home page
Expected result - The URL should not change because you are selecting the same version.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is not a _minimal_ reproduction. Please remove all files that are not necessary to observe the problem. There are around 20 Markdown files, additional stylesheets, etc. Also, please, in this case, create the reproduction without the info plugin, and upload a fully self contained zip that we can unpack and run. Thank you!

**Comment by squidfunk** [comment]
[Closing as incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues). We'll reopen once the reproduction is complete and runnable.
