### ISSUE TITLE
Markdown formatted mermaid nodes do not follow text color of dark theme for pie, quadrantChart, gantt and journey mermaid types

### ISSUE THREAD

**Issue by bennert** [squidfunk/mkdocs-material#6718]
### Context

Pie:

![examplePieDarkMode](https://github.com/squidfunk/mkdocs-material/assets/6158905/760b7b4f-fc55-4992-9ccd-42f29e62ddff)

QuadrantChart:

![exampleQuadrantChartDarkMode](https://github.com/squidfunk/mkdocs-material/assets/6158905/1fb25450-655c-4ec3-9700-93bea2db786f)

Gantt:

![exampleGanttDarkMode](https://github.com/squidfunk/mkdocs-material/assets/6158905/38d8598d-19f8-4ef2-851b-289331ef45b8)

Journey:

![exampleJourneyDarkMode](https://github.com/squidfunk/mkdocs-material/assets/6158905/8f185075-67db-4756-b13d-b42f90f5efcb)

### Bug description

When formatting a pie, quadrantChart, gantt or journey mermaid node [using markdown](https://mermaid.js.org/syntax/flowchart.html#markdown-formatting) the text color is not inherited from dark theme. The node is rendered unreadable.

### Related links

- [Related issue 6700](https://github.com/squidfunk/mkdocs-material/issues/6700)

### Reproduction

[9.5.6-mermaid-vs.zip](https://github.com/squidfunk/mkdocs-material/files/14104251/9.5.6-mermaid-vs.zip)

### Steps to reproduce

1. Turn on dark theme in reproduction example

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for following up on #6700! In fact, I forgot about it, but those charts [are currently not officially supported](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#other-diagram-types) by Material for MkDocs. Those charts need to be integrated, but we currently have no time to do so. If somebody wants to work on this in a PR, we're happy to consider it. It's mainly CSS that needs to be written. I recommend checking the commit history with related issues and comments of [this file](https://github.com/squidfunk/mkdocs-material/blame/5417afc00414c33f1ba5779481514a5d2651c19e/src/templates/assets/javascripts/components/content/mermaid/index.css).
