### ISSUE TITLE
`instant navigation` feature conflicts with `navigation.tracking`

### ISSUE THREAD

**Issue by CNSeniorious000** [squidfunk/mkdocs-material#6719]
### Context

I want to use the SPA feature, but it seems it break some other features.

### Bug description

If I select `navigation.instant` together with `navigation.tracking`, the `navigation.tracking` won't work.

(I am on latest mkdocs and mkdocs-material, using latest python on Windows 11.)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [A demo deploy](https://mkdocs-material-issue-6719.netlify.app/)

### Reproduction

[9.5.6-feature-conflicts.zip](https://github.com/squidfunk/mkdocs-material/files/14113089/9.5.6-feature-conflicts.zip)

### Steps to reproduce

1. Download this minimal project file: [all-files.zip](https://github.com/squidfunk/mkdocs-material/files/14113115/all-files.zip)
2. Run `pdm install` to install `mkdocs>=1.5.3` and `mkdocs-material>=9.5.6`
3. Run `pdm dev` to start `mkdocs serve` server
4. **Open `localhost:8000` and the url won't change with scrolling**
5. By the way, **the toc highlight won't work too**, I don't know why
6. Remove `- navigation.instant`, then restart the server by terminate the server and restart it manually
7. The toc and the url works fine again. So I think it is `navigation.instant`'s fault

---

By the way, I find that `navigation.instant` won't work in the `mkdocs build` results. I don't know why. But you can reproduce it using:

8. Run `pdm gen` to invoke `mkdocs build` command
9. Serve the `site` folder using any static server (or visiting [this demo](https://mkdocs-material-issue-6719.netlify.app/) which is my run results)
10. Open the browser and try to navigate

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Definitely related to our latest refactoring of instant navigation in [9.5.5](https://github.com/squidfunk/mkdocs-material/releases/tag/9.5.5).

Temporary mitigation: disable `navigation.instant` or downgrade to 9.5.4:

```
pip install --force-reinstall mkdocs-material==9.5.4
```

**Comment by squidfunk** [comment]
Fixed in 88004be01. This was a regression introduced in 9.5.5 which impacted the following features:

- `navigation.tracking`
- `toc.follow`

**Comment by squidfunk** [comment]
Released as part of [9.5.7](https://github.com/squidfunk/mkdocs-material/releases/tag/9.5.7).

**Comment by squidfunk** [comment]
You're likely missing the [`site_url`](https://www.mkdocs.org/user-guide/configuration/#site_url) setting. I explained why this is necessary for instant previews in https://github.com/squidfunk/mkdocs-material/issues/6704#issuecomment-1925574954 , which is the same reason it is necessary for instant navigation.
