### ISSUE TITLE
Plugin "meta" not found

### ISSUE THREAD

**Issue by NiklasRosenstein** [squidfunk/mkdocs-material#6722]
### Context

Python version 3.10.3  
Mkdocs Material version 9.5.6

### Bug description

```
ERROR   -  Config value 'plugins': The "meta" plugin is not installed
```

Other built-in plugins documented [here](https://squidfunk.github.io/mkdocs-material/plugins/) work, such as `info` or `offline`.

### Related links

- https://squidfunk.github.io/mkdocs-material/plugins/meta/

### Reproduction

[repro.zip](https://github.com/squidfunk/mkdocs-material/files/14117184/repro.zip)

### Steps to reproduce

```
$ unzip repro.zip
$ python3 -m venv .venv
$ .venv/bin/pip install -r requirements.txt
$ .venv/bin/mkdocs serve
ERROR   -  Config value 'plugins': The "meta" plugin is not installed

Aborted with 1 configuration errors!
```

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment]
Hi, the [meta plugin](https://squidfunk.github.io/mkdocs-material/plugins/meta) is part of the [Insiders edition](https://squidfunk.github.io/mkdocs-material/insiders/), not the public version. If it is something you need then please have a look at sponsoring, which helps make the product better and gets the meta plugin one step closer to being released into the public version as it is part of the [Chipotle](https://squidfunk.github.io/mkdocs-material/insiders/#16000-chipotle) funding goal.

**Comment by squidfunk** [comment]
Yep, as it says [in our documentation](https://squidfunk.github.io/mkdocs-material/plugins/meta/):

<img width="723" alt="Bildschirm­foto 2024-02-01 um 17 22 42" src="https://github.com/squidfunk/mkdocs-material/assets/932156/56276668-a997-4952-bbac-009778116e85">

**Comment by NiklasRosenstein** [comment]
🤦 Sorry, I totally skipped over that part.

**Comment by squidfunk** [comment]
You or your company might consider sponsoring our work, [you'll get a lot in return](https://squidfunk.github.io/mkdocs-material/insiders/#whats-in-it-for-me)!
