### ISSUE TITLE
Change the url link for the Insiders text in the footer 

### ISSUE THREAD

**Issue by janvanveldhuizen** [squidfunk/mkdocs-material#6723]
### Description

![image](https://github.com/squidfunk/mkdocs-material/assets/43573150/44a6f4a5-debd-4098-a099-f7d59d591aec)

Change this link to go the the insiders page directly: https://squidfunk.github.io/mkdocs-material/insiders/

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

Just one click less for web site visitors who are curious to know what the insiders version is. They will be one click closer to become a sponsor themselves. :stuck_out_tongue: 

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexvoss** [comment]
Thanks for the suggestion. Can I suggest a variation of this that would help those who don't know Material at all yet and those who might be intrigued to find out about Insiders? Knowing @squidfunk the choice to link to the main page probably was deliberate. We could make it something like [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) - [Insiders edition](https://squidfunk.github.io/mkdocs-material/insiders/)?

**Comment by squidfunk** [comment]
The choice was deliberate. If you don't know what Material for MkDocs is and click on that link, being taken to Insiders which talks about Sponsorware is likely not going to help you. Thus, taking you to the main project is the best idea.

You can change this for your project through [customization](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials). Just override [`copyright.html`](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/partials/copyright.html).
