### ISSUE TITLE
Custom 404 page works with local serve but not after build

### ISSUE THREAD

**Issue by janvanveldhuizen** [squidfunk/mkdocs-material#6725]
### Bug description

I added a custom 404 page to my web site. It works when browsing locally, but after building it and serving from the site folder, then the 404 page cannot be found. Kind of a nested 404...

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[example.zip](https://github.com/squidfunk/mkdocs-material/files/14117968/example.zip)

### Steps to reproduce

1. run the website locally (run.sh)
2. navigate to the german test page
3. observe the custom 404 page being displayed
4. build the website (build.sh)
5. serve the website (python3 -m http.server 8080 --bind 127.0.0.1)
6. repeat these steps
7. verify that the custom 404 does not work

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by alexvoss** [comment]
The 404 page needs to be configured on the web server as it is the web server that needs to know to serve it up when no page can be found. Material does not really have anything to do with this, neither does MkDocs, see [their documentation on 404 pages](https://www.mkdocs.org/user-guide/deploying-your-docs/#404-pages). It works with `mkdocs serve` and GitHub Pages because the sites generated with MkDocs conform to their defaults.

As far as I can see, getting 404 pages to work is [not possible on Pyhton's http.server](https://stackoverflow.com/questions/72158316/how-to-set-the-http-server-module-to-use-a-custom-404-html-page) without writing additional Python code but perfectly possible if you are doing that.

What environment are you looking to deploy to? You would need to figure out how to configure the 404 page there.

**Comment by janvanveldhuizen** [comment]
> it is the web server that needs to know to serve it up when no page can be found

Ah yes, that makes sense.
My provider uses Apache/2. I'll look into it. I'd like to have the page in my repo and publish by the build pipeline.
Still.... why does the server fail when I add this 404.html page?

https://papasmurf.nl/en/homelab.md

**Comment by janvanveldhuizen** [comment]
I'm adding this here, in case others are reading this discussion in search of solutions to their own 404 errors.

You can create your own 404 page by following the instructions here: https://www.mkdocs.org/user-guide/customizing-your-theme/

However, be aware that this does not guarantee your custom 404 page will be used after publishing your website. Its usage depends on the web server employed by your hosting provider. If you're lucky, it will work seamlessly because the web server will look for a 404.html file in the root directory of your website. If not, you'll need to identify which web server your provider is using. This can be determined by executing the following command:

```
curl -s -I <your website url> | grep server
```

In my case, it was Apache/2. 
![image](https://github.com/squidfunk/mkdocs-material/assets/43573150/65c95cf8-854b-4214-883d-66f4cd5f9d4e)

For Apache/2, I needed to create an .htaccess file in the website's root directory, with the following content:

```
ErrorDocument 404 /404.html
```

If you're using GitHub Actions or a GitLab pipeline, automating this process is straightforward.

**Comment by alexvoss** [comment]
Thanks for posting this. I will bookmark this for the time when I get hands-on with the documentation. IMHO this would be nice to have in [publishing your site](https://squidfunk.github.io/mkdocs-material/publishing-your-site/).
