### ISSUE TITLE
Instant preview misplacement with tabs above

### ISSUE THREAD

**Issue by pawamoy** [squidfunk/mkdocs-material#6735]
### Context

Reported here first: https://github.com/squidfunk/mkdocs-material/issues/6704#issuecomment-1915268676.

### Bug description

Instant previews enabled globally with `navigation.instant.preview`.

When there are tabs above a previewable link, the preview windows can be misplaced: it seems the preview windows position are calculated once, when the page loads. If I change tabs above previewable links, and these tabs have different heights, then all previewable links after these tabs have misplaced preview windows. If I reload the page, staying on the second tab, positions are recalculated correctly. Well, these are assumptions, you'll know better what's really happening :slightly_smiling_face: 

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Instant previews](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-previews)

### Reproduction

[9.5.7+insiders.4.52.1-instant-preview-misplacement.zip](https://github.com/squidfunk/mkdocs-material/files/14151611/9.5.7%2Binsiders.4.52.1-instant-preview-misplacement.zip)

### Steps to reproduce

- Serve the given reproduction and go to the home page.
- Assert both previewable links have correct preview window positions.
- Now change to second tab in the "Tabs before" section.
- Assert that first link preview is still correct, but second link preview isn't. Increase or reduce space below second link (by scrolling) to see both behaviors (when there's enough space below the link to show the preview window, or not).

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Fixed in [`b4b1a42`](https://github.com/squidfunk/mkdocs-material-insiders/commit/b4b1a42963e35ca1a5a52e7b9ddc8342df51ae20). So, we forgot to recompute the absolute element offset after the tooltip was activated for the first time. This should now be fixed with the latest commit, albeit we didn't yet find the best method of accurately tracking element offsets. We'll definitely do a small refactoring once we could smooth the rough edges of the new tooltips implementation, but for the time being, the issue should be resolved ☺️

**Comment by squidfunk** [comment]
Released as part of [9.5.8+insiders-4.52.2](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.52.2).
