### ISSUE TITLE
Auto push plugins with github actions

### ISSUE THREAD

**Issue by TinnyTerr** [squidfunk/mkdocs-material#6738]
### Context

Basically, add a line in the github action template to automatically install any plugins when pushing to pages. 

### Description

A line in ci.yml of .github/workflows that runs `pip install` and automatically gets the plugins. This automatically downloads the plugins upon push to github pages.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- A failed attempt at this change #6737

### Use Cases

This will benefit any new users that miss the small footnote at the action where it shows how to install plugins from getting 
`ERROR   -  Required dependencies of "X" plugin not found. Install with: pip install "mkdocs-X"`
Also will benefit any users adding new plugins where they forget to add the new plugin to the workflow.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Which plugins? There are hundreds of MkDocs plugins, some of which we natively integrate with, so I'm not sure to which plugins you are referring. Each plugin we support natively comes with an installation code block:

- [`git-revision-date-localized-plugin`](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-dates)
- [`git-committers-plugin`](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors)
- [`git-authors-plugin`](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-authors)
- ...

Closing as unactionable. If you can maybe try to better explain what our documentation is missing, we can improve it.

**Comment by squidfunk** [comment]
Also note that the PR you linked to was [closed by the author](https://github.com/squidfunk/mkdocs-material/pull/6737#issuecomment-1925510191) as "doesn't work".

**Comment by TinnyTerr** [comment]
I was meaning where it downloads mkdocs, runs mkdocs get-deps and echos the output into pip install to automatically install all the required plugins that you specified in the .yml file. It'd safe new users from getting stuck on deployment and old users to have it download unneeded dependencies.

**Comment by squidfunk** [comment]
`mkdocs get-deps` is quite new and [sourced from the catalog](https://github.com/mkdocs/catalog), which is a curated list of MkDocs packages. Thus, `get-deps` might return incomplete results, so we're currently not considering adding it to our recommended GitHub Action.

**Comment by TinnyTerr** [comment]
Cool. Might be useful to add a more obvious note for plugins to the docs at least as when I was on my first time round, it was pretty easy to miss and got stuck for quite a while.
