### ISSUE TITLE
Allow for local/offline fonts for the social cards plugin

### ISSUE THREAD

**Issue by djacu** [squidfunk/mkdocs-material#6747]
### Context

There has been previous discussion (https://github.com/squidfunk/mkdocs-material/issues/152) about using local fonts for offline use. However these methods do not work for the social plugin. I am aware that the privacy plugin also exists for matters like this but it still fetches assets at build time which does not work for sandboxed build tools (e.g. Nix).

### Description

Extend the social plugin to use another directory for locally stored fonts. In addition to walking the `.cache/plugin/social` directory, have it walk another directory which contains locally stored assets.

### Related links

- https://github.com/squidfunk/mkdocs-material/issues/152
- https://github.com/squidfunk/mkdocs-material/discussions/5965

### Use Cases

I use Nix for many of my projects including building the project's static site. Building an mkdocs site in the Nix sandbox has generally worked for me except when using the material social plugin. Because the social plugin fetches fonts at build time, it causes my sites to fail to build. However, having those fonts locally tracked and available would allow for sandboxed builds again.

I am aware that the privacy plugin exists, but as far as I am aware, that also fetches assets at build time.

### Visuals

I have included a git diff to better illustrate a possible solution. I fully admit it might not be the best or in line with the maintainers vision for the repo but I thought it better than just explanations. 

Essentially, provide another directory to the plugin config.py that points to an assets directory. In the plugin.py, walk that directory in addition to the cache directory to search for fonts.

```diff
% git diff                                    
diff --git a/material/plugins/social/config.py b/material/plugins/social/config.py
index 9d72afb36..a9a4fdfff 100644
--- a/material/plugins/social/config.py
+++ b/material/plugins/social/config.py
@@ -29,6 +29,7 @@ from mkdocs.config.config_options import Deprecated, Type
 class SocialConfig(Config):
     enabled = Type(bool, default = True)
     cache_dir = Type(str, default = ".cache/plugin/social")
+    assets_dir = Type(str, default = "some_asset_directory")
 
     # Settings for social cards
     cards = Type(bool, default = True)
diff --git a/material/plugins/social/plugin.py b/material/plugins/social/plugin.py
index 40b3d07be..f3fbdd4ec 100644
--- a/material/plugins/social/plugin.py
+++ b/material/plugins/social/plugin.py
@@ -112,6 +112,11 @@ class SocialPlugin(BasePlugin[SocialConfig]):
         if not os.path.isdir(self.cache):
             os.makedirs(self.cache)
 
+        # Ensure presence of assets directory
+        self.assets = self.config.assets_dir
+        if not os.path.isdir(self.assets):
+            os.makedirs(self.assets)
+
         # Retrieve palette from theme configuration
         theme = config.theme
         if "palette" in theme:
@@ -440,6 +445,15 @@ class SocialPlugin(BasePlugin[SocialConfig]):
         filename_regex = re.escape(font_filename_base)+r"-(\w+)\.[ot]tf$"
 
         font = {}
+        # Check for assets files - note these may be in subfolders
+        # Note check assets directory first before the cache
+        for currentpath, folders, files in os.walk(self.assets):
+            for file in files:
+                # Map available font weights to file paths
+                fname = os.path.join(currentpath, file)
+                match = re.search(filename_regex, fname)
+                if match:
+                    font[match.group(1)] = fname
         # Check for cached files - note these may be in subfolders
         for currentpath, folders, files in os.walk(self.cache):
             for file in files:
```

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. We're currently not considering adding sourcing of font files to the social plugin for reasons of added complexity – Google Fonts provides a simple abstraction and the [social](https://squidfunk.github.io/mkdocs-material/plugins/social/) plugin fetches the fonts at build time.

A very simple solution is to add the fonts located in `.cache/plugin/social` to your repository (exclude from `.gitignore`) and check them in with your code, which means the social plugin will not try to download those fonts during CI. It achieves effectively the same as adding new code to the social plugin so that it checks multiple assets. Additionally, we would need to validate the naming of files if we would allow authors to define arbitrary fonts, which will require a whole lot more code.

Closing as out of scope, but achievable with configuration.
