### ISSUE TITLE
Extra <p> around <img> inside the <figure> example

### ISSUE THREAD

**Issue by iBug** [squidfunk/mkdocs-material#6755]
### Bug description

The example in [Image captions][1] renders with an extra layer of `<p>` tag, causing unwanted top and bottom margin (from `.md-typeset p`):

Input (from [docs](https://github.com/squidfunk/mkdocs-material/blob/9.5.8/docs/reference/images.md?plain=1#L118)):

```markdown
<figure markdown>
  ![Image title](https://dummyimage.com/600x400/){ width="300" }
  <figcaption>Image caption</figcaption>
</figure>
```

Desired result (also from [docs](https://github.com/squidfunk/mkdocs-material/blob/9.5.8/docs/reference/images.md?plain=1#L133)):

```html
<figure>
  <img src="https://dummyimage.com/600x400/f5f5f5/aaaaaa?text=–%20Image%20–" width="300" />
  <figcaption>Image caption</figcaption>
</figure>
```

Actual rendered content:

```html
<figure>
  <p>
    <img alt="Image title" src="https://dummyimage.com/600x400/" width="300" />
  </p>
  <figcaption>Image caption</figcaption>
</figure>
```

The problem is with styles on the `<p>` tag:

![](https://github.com/squidfunk/mkdocs-material/assets/7273074/7bce1016-e09a-45a1-bd6f-d937afd23fab)

While this issue comes from MkDocs' Markdown rendering, I have these justifications to report it here:

- This can be easily fixed by an extra CSS rule for `figure > p:first-child`.
- Writing Markdown in the example but raw HTML in the result section is not the best way to ensure it renders as advertised.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Image captions][1]

[1]: https://squidfunk.github.io/mkdocs-material/reference/images/#image-captions

### Reproduction

[9.5.8-figure-p.zip](https://github.com/squidfunk/mkdocs-material/files/14215752/9.5.8-figure-p.zip)

### Steps to reproduce

See ZIP

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by facelessuser** [comment]
This is not a bug, but how Python Markdown works. When using `md_in_html` and specifying `markdown` it will assume the default behavior for the HTML element. `figure` is treated as a block element; therefore, content under will be parsed at the block level. A text block, even one containing just an image, will be treated as a paragraph.

You can force it to treat content under it as inline by setting`markdown="span"`, then it will parse the content under `figure` as if the content was contained in an inline element, like a span. Inline content will not be wrapped with a paragraph and block-level parsers will not be executed on the content under `figure` in this case.

See documentation https://python-markdown.github.io/extensions/md_in_html/#span.

**Comment by squidfunk** [comment]
Thanks for reporting. I've updated our example in 1698fd817 to use `makdown="span"`, because we do not want to impose more restrictions via CSS upon our users, so both variants are possible.
