### ISSUE TITLE
Instant loading feature requires site_url when publishing site

### ISSUE THREAD

**Issue by Lexachoc** [squidfunk/mkdocs-material#6792]
### Description

https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading

The instant loading works when using `mkdocs serve` without [site_url](https://www.mkdocs.org/user-guide/configuration/#site_url) but if `site_url` is not set, then it won't work after `mkdocs build`

See the discussions in the lower part of https://github.com/squidfunk/mkdocs-material/discussions/6784#discussioncomment-8509824 and https://github.com/squidfunk/mkdocs-material/discussions/6784#discussioncomment-8510528

It would be good to document this if it is not a bug.

Thank you.

### Related links

- https://squidfunk.github.io/mkdocs-material/publishing-your-site/
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, `site_url` is mandatory for `navigation.instant` and `navigation.instant.preview`. I've added an info box to both features in 2986aca62. @alexvoss we should add a whole section on instant navigation in regard to our latest IA efforts, where we cover the assumptions, requirements, and limitations.
