### ISSUE TITLE
Multi-Language `site_name`

### ISSUE THREAD

**Issue by mementum** [squidfunk/mkdocs-material#6836]
### Context

There is support for multi-language content, `site_name` is a single string

### Description

Using `site_name` as a mapping would be a non-backwards compatible change, but the `extra` mapping is already being used for some other things and can be also used for this. Example

```yaml
extra:
  site_name:
    en: Marvel Tales - The Infinity Stones
    de: Marvel Märchen - Die Infinity-Steine
    es: Historias de Marvel - Las Gemas del Infinito
```

This can later be leveraged, still retaining compatibility, as follows. Example in `partials/header.html`

```html
          <span class="md-ellipsis">
            {% if config.extra and config.extra.site_name and config.extra.site_name[lang.t('language')] %}
              {{ config.extra.site_name[lang.t('language')] }}
            {% else %}
              {{ config.site_name }}
            {% endif %}
          </span>
```

There are of course several other places where a plain usage of `config.site_name` has to be reworked, but this should suffice to show the idea.

Where `config.site_name` is used more than once in a template it will of course be sensible to set a variable with the detected value and the use the variable multiple times. Something like:

```
{% if config.extra and config.extra.site_name and config.extra.site_name[lang.t('language')] %}
  {% set site_name_lang = config.extra.site_name[lang.t('language')] %}
{% else %}
  {% set site_name_lang = config.site_name %}
{% endif %}
```

### Related links

https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/

### Use Cases

Supporting multi-language sites with a multi-language `site_name`

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by mementum** [comment]
Affected files:

  - redirect.html
  - partials/nav.html
  - partials/header.html
  - partials/content.html
  - base.html

And
  - plugins/social/plugin.py

**Comment by kamilkrzyskow** [comment]
@mementum 
The mkdocs-static-i18n plugin does support overrides for each language:
https://ultrabug.github.io/mkdocs-static-i18n/setup/setting-up-languages/#additional-per-language-overrides-options
so not exactly your idea, but basically allows for the same result.

However, the plugin currently lacks support for the mkdocs-material `blog` plugin, and it builds the languages sequentially, so the full build time could become quite slow.

**Comment by mementum** [comment]
Thx. I don't know how I overlooked that, because I was already overriding the navigation tabs.
