### ISSUE TITLE
Search bar location in main page

### ISSUE THREAD

**Issue by laguerreiro** [squidfunk/mkdocs-material#6858]
### Context

I know customization is hard and may be difficult for those not experienced in CSS and HTML, and, at the same time it's not practical to have the engine doing different options for customization. However, one common thing among several knowledge base/documentation sites is a bigger search bar in the middle of the landing page. Right now, the search bar is a bit "hidden" in the header. 

### Description

Would it be possible to have flexibility on the search bar placement, such as a parameter for the main page? I tried changing the CSS to do that on my own, but it's not that simple, since there are a lot of restrictions due to the current location. 

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

This should add flexibility to the search bar and create customized landing pages. In addition, giving more importance to the search field is important as it can help users navigate easily throughout the platform.

### Visuals

Examples: 
https://learn.microsoft.com/pt-br/
https://www.samsung.com/br/support/

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! You might be aware of #6307, where we explain that we're actively working on improving the search capabilities of Material for MkDocs. Now, the current component architecture does not allow to make it simple to inject search boxes here and there, but we're actively considering making this simpler. We can't however currently not makes this a priority, given what we currently have on our plates. I invite you to follow developments on #6307, and after we did the first few iterations, we can talk about making search a parametrizable component. I'll add something to the linked issue.
