### ISSUE TITLE
md-sidebar__scrollwrap has incorrect height

### ISSUE THREAD

**Issue by couleurm** [squidfunk/mkdocs-material#6864]
### Bug description

It seems the javascript responsible to calculate the right height of md-sidebar__scrollwrap is off,

you can see that the bottom left of https://squidfunk.github.io/mkdocs-material/setup is clipped off before the absolute bottom of the page

![image](https://github.com/squidfunk/mkdocs-material/assets/82747632/5c0e0aa7-a131-45af-a3a1-b0a3ccb06380)

https://github.com/squidfunk/mkdocs-material/assets/82747632/060ae87d-8b18-4b63-be5d-288b0b89ee26

### Related links

https://github.com/search?q=repo%3Asquidfunk%2Fmkdocs-material+md-sidebar__scrollwrap&type=code

### Reproduction

https://squidfunk.github.io/mkdocs-material/setup

### Steps to reproduce

1. Zoom enough so that the left sidebar takes more height than your monitor (yes this can happen on 1080p monitor when there's enough pages, see https://ctt.cx/video)
2. look

### Browser

Chromium & Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by kamilkrzyskow** [comment]
I believe this works as intended:
![image](https://github.com/squidfunk/mkdocs-material/assets/34622465/9a707ff6-d2fb-4689-a506-a74e14d7628c)
The scroll wrap is setup to end with the default page end minus the margin

**Comment by squidfunk** [comment]
Thanks for reporting. Correct, it's working as intended and it has been like this since v1.0.

**Comment by couleurm** [comment]
https://github.com/squidfunk/mkdocs-material/assets/82747632/3dea87bb-e0db-4849-a46b-cfbe8c6a16c1

are we talking about the same thing? is this really intentional? and if it is do you know any css wizardry that could make this take the whole page's height?

**Comment by squidfunk** [comment]
Yes, it is correct. The idea is that there is always spacing to the bottom of the screen. We'll revisit the layout and overall appearance of Material for MkDocs later this year and it might be that we change it, but currently no promises or ETA.

**Comment by kamilkrzyskow** [comment]
The JavaScript does not rely on the CSS to calculate the height, it is setup to match the default CSS. 
Using pure CSS trickery to override it probably isn't the right way:
```css
.md-sidebar__scrollwrap {
  height: 100% !important;
}
.md-sidebar.md-sidebar--primary {
  height: 100%;
  padding: 0;
}
```
will result in the look you want (without the gap at the bottom), but the scrollbar is always visible.

You probably can use a https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver to detect a change in the attribute in JavaScript and modify it again, but perhaps this would create an infinite loop of detecting the mutation 😆 
So perhaps instead of changing the attribute again, add/modify an inline `<style>` tag with the height !important set to current calculated height + your custom value to remove the gap.
