### ISSUE TITLE
Incorrect CSS/JS `link` href in projects with root `site_url`

### ISSUE THREAD

**Issue by Blacksmoke16** [squidfunk/mkdocs-material#6876]
It only seems to occur when you do not have a base path set, i.e., if you deploy your documentation on the root, so `http://example.com/` triggers the problem, while setting. `site_url` to `http://example.com/docs/` does not.

Code: https://github.com/squidfunk/mkdocs-material/files/14491315/bug.zip

_Originally posted by @squidfunk in https://github.com/squidfunk/mkdocs-material/discussions/5800#discussioncomment-8687387_

EDIT: Regression from #6437

**Comment by squidfunk** [comment]
Thanks for reporting. However, please _properly_ fill out the issue template. Remember, GitHub is forever and we might need to refer back and forth to this issue, so we need a proper description and structure. I'm closing this one as incomplete.
