### ISSUE TITLE
Incorrect CSS/JS `link` href in projects with root `site_url`

### ISSUE THREAD

**Issue by Blacksmoke16** [squidfunk/mkdocs-material#6877]
### Context

Previously discussed in https://github.com/squidfunk/mkdocs-material/discussions/5800#discussioncomment-8673739.

Seemingly is a regression of #6437.

### Bug description

When the root project of a projects plugin sets a `site_url` to root, e.g. `http://example.com/` versus `http://example.com/docs`, and when the child projects setting something else, e.g. `http://example.com/MyApp`, then the `href` attribute of the generated `link` tags for the CSS/JS of the sub-project are incorrect. This causes them to 404 and not properly 

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/plugins/projects/

### Reproduction

[bug.zip](https://github.com/squidfunk/mkdocs-material/files/14503473/bug.zip)

### Steps to reproduce

1. `python3 -m venv venv`
2. `. venv/bin/activate`
3. `pip install --upgrade --force-reinstall mkdocs-material`
4. Run `mkdocs serve`
5. Try to navigate to the `/MyApp` page

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting! Temporary mitigation:

``` yaml
plugins:
  - projects:
      hoisting: false
```

**Comment by squidfunk** [comment]
Fixed in [`7c4ef0b`](https://github.com/squidfunk/mkdocs-material-insiders/commit/7c4ef0b37e33c774576ee8da20cb3b2182c6178f). There was a bug in path computation if paths where computed from `site_url`, sometimes returning an absolute path, which explains that the file system path was part of the asset URL. There are many different configurations that we need to account for (no `site_url` set, some set, all set, `site_url` pointing to same base paths, etc.). Additionally, the fix in #6437 was not specific enough and was also adapted, so the reproduction in #6437 remains working.

**Comment by squidfunk** [comment]
Released as part of [9.5.13+insiders-4.53.1](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.53.1).
