### ISSUE TITLE
Request - Selecting permalinks automatically copies the linked URL

### ISSUE THREAD

**Issue by rachel-rigdon-sp** [squidfunk/mkdocs-material#6880]
### Description

Can we add an option where selecting a permalink will automatically copy the URL to your clipboard? 

For example, the code copy button or Confluence's approach.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button

### Use Cases

This will make it easier for users and writers to quickly link to sections. 

### Visuals

![Screenshot 2024-03-06 at 12 56 34 PM](https://github.com/squidfunk/mkdocs-material/assets/60661988/f18dae29-e5a0-4875-b15f-c0cfba5980e6)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm not sure this is something all users need or want, _but_ it is perfectly achievable with some customization. In essence, use this MkDocs configuration:

``` yaml
markdown_extensions:
  - toc:
      permalink_title: Copy link
```

And this extra JavaScript, which also integrates it with instant navigation:

``` js
document$.subscribe(() => {
  document.querySelectorAll(".headerlink").forEach(link => {
    link.setAttribute("data-clipboard-text", link.href)
    // link.addEventListener("click", ev => ev.preventDefault())
  })
})
```

The second line prevents the jump when you click on the link. I understand that this is a pattern that users might expect when the permalink copies the actual link, so comment it out if you want to omit the jump.

**Comment by rachel-rigdon-sp** [comment]
Thank you so much!!
