### ISSUE TITLE
pip show mkdocs-material | grep -E ^Version - doesn't work on Windows (Powershell)

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#692]
On the [Release notes page](https://squidfunk.github.io/mkdocs-material/release-notes/) it suggest to run the following command to get the current version number:
```
pip show mkdocs-material | grep -E ^Version
```
However, that doesn't work on Windows with Powershell.
I think if it  instead just suggested:
```
pip show mkdocs-material
```
then it'd work on all platforms.

**Comment by squidfunk** [comment]
Well, okay, Windows...

**Comment by squidfunk** [comment]
Adjusted it in the docs.
