### ISSUE TITLE
🚀 Insiders: earlier release of 12 features

### ISSUE THREAD

**Issue by squidfunk** [squidfunk/mkdocs-material#6940]
__Good news! We've decided to create [two new intermediary funding goals](https://squidfunk.github.io/mkdocs-material/insiders/#goals), and will release 12 Insiders features earlier than we initially intended. If you want to know why we've decided to do this, keep on reading.__

## New funding goals

The following new goals have been created, moving features from higher goals into lower goals:

### Lemon Drop

> Features previously scheduled for release at $20k, now at $18k:

- [x] Optimize plugin
- [x] Navigation path (Breadcrumbs)
- [x] Blog plugin: advanced settings
- [x] Blog plugin: author profiles
- [x] Blog plugin: pinned posts
- [x] Instant prefetching

### Habanero Orange

> Features previously scheduled for release at $24k, now at $22k:

- [x] Instant previews
- [x] Social plugin: custom layouts
- [x] Social plugin: background images
- [x] Code range selection
- [x] Code annotations: custom selectors
- [x] Stay on page when switching languages

## Why?

At the beginning, we've set our funding goals $500 apart from each other. Growth was slow, and it took several months to reach the first $500, $1k and $1,5k goals. However, as growth sped up, we released new features every other month, which is why we decided to space them at $1k and later at $2k gaps, as with more functionality being available to everyone, more bug reports, change requests and questions were coming in. More effort was necessary, which was compensated by more funding – perfect. 

Mid-term, this still led to goals being hit every 2-3 months for some time until two things happened: [GitHub stopped supporting PayPal](https://github.com/squidfunk/mkdocs-material/issues/5093), which made us lose $1,5k in sponsorships (some of which came back) and the global recession (at least that's our explanation). Initially, we thought that we'll be hitting the goals that we spaced $4k apart quite quickly, but we didn't, and that's not a problem. We want to keep it interesting, and we want to provide value for everybody, which is why we'll be releasing those 12 features earlier than planned. The sponsorware concept is a hell of a (successful!) experiment, and while we always keep our promises in releasing features when goals are hit, we also want to allow ourselves to benefit the community earlier than initially planned. We believe that our sponsors will support this decision and keep sponsoring us, so we can build even more awesome features for them, and eventually, for everyone ❤️

We hope to keep growing our funding to allow us to keep up with the increasing number of issues and discussions that are created, because we want to compensate the awesome individuals that help foster building a great and inclusive community! If we can onboard more people for support, but in the mid-term also for development, we can move even faster, building one of the most awesome and simplest frameworks for documentation out there.

**Comment by lambda-science** [comment]
Can't complain, more feature for everybody is always a nice thing, thank you very much for you work !

**Comment by alexvoss** [comment]
I would add that there are tangible benefits for sponsors as well since the release of these features into the public version will mean that they are more likely to be used in anger by enough people that issues are picked up and resolved. This for for the benefit of everyone and will help Material to be sustainable and dependable. So, sponsoring is not just an altruistic thing and also not just a way to get early access to features, it is an investment into the future.  

@squidfunk's move to introduce these intermediate goals also show a high degree of confidence in the trajectory of development. There is so much more to come in 2024!

**Comment by Guts** [comment]
Good move! Please, continue the good work :).
