### ISSUE TITLE
Collapse table of contents and automatically expand active section

### ISSUE THREAD

**Issue by 40huo** [squidfunk/mkdocs-material#695]
When a single markdown file contains too many headers, like [this one](https://40huo.github.io/ctf-wiki/executable/elf/elf_structure/), the TOC is too long.

![TIM截图20180207234239.png](https://i.loli.net/2018/02/07/5a7b1e7e91cbf.png)

In this case, an auto-expand TOC may be more readable, like [auto-expand TOC example](https://imys.net/20161125/cursor-offset-at-input.html), which uses [hexo-theme-indigo](https://github.com/yscoder/hexo-theme-indigo).

**Comment by makshh** [comment]
You can try with this CSS (it doesn't work exactly like your example, but it's close):

```css
:not([data-md-state="blur"]) + nav {
  display: none;
}
```

**Comment by squidfunk** [comment]
This is an enhancement and could be done with the composing logic of the navigation. I may implement it in the future when I find the time.

**Comment by squidfunk** [comment]
I'm closing this, as this will probably never get implemented. Material's default behavior should work pretty good, but it can also be extended by custom JavaScript. Giving users the option to auto-collapse the TOC is too specific to be useful. I want to allocate my time to stuff that needs to be fixed, not optional "nice" features. I'm sorry and hope you can understand.

**Comment by guzman-raphael** [comment]
We've recently ran into this issue as well where it would have been perfect if this feature was available.

Our case was specifically because we are using `mkdocstrings` and documenting a Python package with many submodules. This means that breaking this up into multiple files requires refactoring of the codebase which is not ideal.

One of the submodules (`__init__.py`) is quite large and requires a lot of scrolling on the left until you can review the next submodule.

![image](https://user-images.githubusercontent.com/38401847/193230714-a15cbead-858b-4b56-a1f3-150c3147a11a.png)

**Comment by squidfunk** [comment]
Thanks for the feedback. I'll might consider adding this in the future.

**Comment by guzman-raphael** [comment]
Np, but most of all... Thank you for all your hard work on this! Happy to be a supporter in mkdocs-material-insiders.

**Comment by leandro-lucarella-frequenz** [comment]
Just for the records (in case it changes the consideration about implementing this), I'm also having this problem when using `mkdocstrings` (using `show_category_heading: true` in particular).

It would be really nice to present a collapsed TOC where you can click on the "category" you are interested in (like "Classes") and then look for some and click on it, and the look for a method for example. It also makes a very good way to have a quick overview on some module, for example if you want to see a list of classes, or functions.

Exactly the same as with the nav bar, where I can see a very nice overview of the packages and modules available at different nesting levels.

Here is an example of how nice and useful the nav bar looks:

![image](https://user-images.githubusercontent.com/108664423/198570526-fb6237cf-6f1d-4065-b1da-688030602400.png)

And here how hard it is to have an overview of which classes are available in a particular module:

![image](https://user-images.githubusercontent.com/108664423/198570626-37385cd7-8c2c-4cb8-8a08-6b36767aeabc.png)

BTW, I tried the solution proposed in:

* https://github.com/squidfunk/mkdocs-material/issues/695#issuecomment-364673666

But it didn't work, if anyone have any ideas on how to hack the TOC to make it collapsible, it would be highly appreciated!

**Comment by squidfunk** [comment]
Thanks for your feedback. As said in https://github.com/squidfunk/mkdocs-material/issues/695#issuecomment-1263699535, we might reconsider adding this feature in the future.
