### ISSUE TITLE
Active page highlight not working with default palette

### ISSUE THREAD

**Issue by ovasquez** [squidfunk/mkdocs-material#696]
## Description
The **active page** highlight color doesn't work when using the color by default by not declaring the `palette` configuration. You are required to declare the palette colors for active page to work.

### Expected behavior
The active page highlight should work when not explicitly declaring the palette. It should use the colors by default.
![image](https://user-images.githubusercontent.com/7527242/35940834-145455b8-0c16-11e8-9ec7-b84263297194.png)

### Actual behavior
The active page highlight doesn't work when not explicitly declaring the palette.
![image](https://user-images.githubusercontent.com/7527242/35940452-cd459728-0c14-11e8-8b89-00b352e0ecb4.png)

### Steps to reproduce the bug

1. Create any MkDocs website using material theme
2. Do not set the palette
3. Run `mkdocs serve` and see the active link not being highlighted 

### Package versions

* Python: Python 3.6.1
* MkDocs: mkdocs, version 0.17.2
* Material: Version: 2.6.0

### Project configuration
Just remove the `palette` configuration from the `mkdocs.yml`

### System information

* OS: Windows 10
* Browser: Chrome, Firefox, Edge

**Comment by squidfunk** [comment]
That is indeed a regression. Thanks for reporting, will provide a fix.

**Comment by squidfunk** [comment]
Fixed in 94acf18d5dfe72969304a0c37ddd1866aa55ce02, another regression, thanks for reporting. Really need to set up visual regression testing.
