### ISSUE TITLE
Dependency issue?

### ISSUE THREAD

**Issue by inz1981** [squidfunk/mkdocs-material#6969]
### Bug description

I am not sure about this, but when I install mkdocs-material version 9.5.14 or later using `poetry`, there are no dependencies installed. 
In 9.5.15, dependencies are gone and there is not even a description:

```
$ poetry show mkdocs-material
 name         : mkdocs-material 
 version      : 9.5.15          
 description  :   
$
```

In the version 9.5.13 there are the following dependencies to mkdocs-material:

```
$ poetry show mkdocs-material
 name         : mkdocs-material                 
 version      : 9.5.13                          
 description  : Documentation that simply works 

dependencies
 - babel >=2.10,<3.0
 - colorama >=0.4,<1.0
 - jinja2 >=3.0,<4.0
 - markdown >=3.2,<4.0
 - mkdocs >=1.5.3,<1.6.0
 - mkdocs-material-extensions >=1.3,<2.0
 - paginate >=0.5,<1.0
 - pygments >=2.16,<3.0
 - pymdown-extensions >=10.2,<11.0
 - regex >=2022.4
 - requests >=2.26,<3.0
$ 
```
`mkdocs` can be started with version 9.5.13, but not for 9.5.15 because then the `mkdocs` cannot be started due to missing installed dependencies.

Possibly could be my mirroring PyPi that is a bit flaky or has there been a change in the packaging and dependencies of mkdocs-material?

### Related links

- [installation](https://squidfunk.github.io/mkdocs-material/getting-started/#installation)

### Reproduction

install mkdocs version 9.5.15 with poetry and try to run for example: mkdocs serve

```
$ mkdocs serve
...
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/eeriale/git/yang/.venv/lib/python3.11/site-packages/material/plugins/search/plugin.py", line 24, in <module>
    import regex as re
ModuleNotFoundError: No module named 'regex'
```

### Steps to reproduce

1. Poetry install mkdocs-material 5.9.13

Try to start mkdocs

2. Poetry install mkdocs-material 5.9.15

Try to start mkdocs

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by alexvoss** [comment]
Can you please have a look at the reproduce steps? I installed poetry and run the commands but get:

```
$ poetry install mkdocs-material 5.9.15
Poetry could not find a pyproject.toml file in /Users/avoss/src/mkdocs-material/reproduce/poetry or its parents
```

Likewise, the `show` command gives the same error message. So, there seems to be something missing.

**Comment by alexvoss** [comment]
Right, so after 

```
poetry new poetry-demo
cd poetry-demo
poetry add mkdocs-material
poetry show mkdocs-material
```

I get:

```
 name         : mkdocs-material                 
 version      : 9.5.15                          
 description  : Documentation that simply works 

dependencies
 - babel >=2.10,<3.0
 - colorama >=0.4,<1.0
 - jinja2 >=3.0,<4.0
 - markdown >=3.2,<4.0
 - mkdocs >=1.5.3,<1.6.0
 - mkdocs-material-extensions >=1.3,<2.0
 - paginate >=0.5,<1.0
 - pygments >=2.16,<3.0
 - pymdown-extensions >=10.2,<11.0
 - regex >=2022.4
 - requests >=2.26,<3.0
 ```

That looks fine. Not sure what might be going wrong on your side but we'd need a reproduction we can test on our own systems to help. For starters, we'd need to know which version of Poetry you are using, on what OS and how you set up your project.

**Comment by inz1981** [comment]
Hi! Thanks for your effort in this @alexvoss ! I have also tested to use the standard PyPi repository and it works well. For your reference I am using Python (version 3.11.8) and Poetry (version 1.7.0).

I tested to remove our mirror PyPi repository and added mkdocs-material 9.5.15, and it works as you also shown above. I will have to look internally what is the issue.

Thanks a lot for the support! This ticket can be closed.

**Comment by seub** [comment]
Hi @inz1981, I'm wondering if you were able to figure out the issue?

I'm running into the exact same scenario: when I use the standard PyPi, all dependencies are installed as expected, but when using our artifactory mirror, Poetry doesn't see the dependencies.

**Comment by inz1981** [comment]
Hi @seub !

I have not spent any time on trying to figure out what it is.. 

Interesting that you also get the same issue with a mirroring repository! I cant really understand why its not working as expected. I am using mkdocs-material 9.5.13 since that is the only latest version working for me. So here is the procedure I do when upgrading.

```
$ poetry -V
Poetry (version 1.7.0)

$ poetry show mkdocs-material 
 name         : mkdocs-material                 
 version      : 9.5.13                          
 description  : Documentation that simply works 

dependencies
 - babel >=2.10,<3.0
 - colorama >=0.4,<1.0
 - jinja2 >=3.0,<4.0
 - markdown >=3.2,<4.0
 - mkdocs >=1.5.3,<1.6.0
 - mkdocs-material-extensions >=1.3,<2.0
 - paginate >=0.5,<1.0
 - pygments >=2.16,<3.0
 - pymdown-extensions >=10.2,<11.0
 - regex >=2022.4
 - requests >=2.26,<3.0
```
Above its all good with dependencies etc.


When upgrading to 9.5.17:
```
$ poetry update mkdocs-material
Updating dependencies
Resolving dependencies... (1.1s)

Package operations: 0 installs, 1 update, 5 removals

  • Removing babel (2.14.0)
  • Removing mkdocs-material-extensions (1.3.1)
  • Removing paginate (0.5.6)
  • Removing pygments (2.17.2)
  • Removing regex (2023.12.25)
  • Updating mkdocs-material (9.5.13 -> 9.5.17)

Writing lock file

$ poetry show mkdocs-material
 name         : mkdocs-material 
 version      : 9.5.17          
 description  :                 
```

Removes dependencies and also the Description...
