### ISSUE TITLE
Social cards broke after opting in for the insiders program

### ISSUE THREAD

**Issue by meysam81** [squidfunk/mkdocs-material#6978]
### Bug description

After joining the insiders program, my CI is now broken and I can't seem to figure out how to fix it. Does anyone have any clue what's missing?

https://github.com/developer-friendly/blog/actions/runs/8449090378/job/23142465169#step:9:89

### Related links

- https://squidfunk.github.io/mkdocs-material/insiders/

### Reproduction

Disabling social cards fixed the issue but I don't know what is still causing errors and have no clue on reproduction really

### Steps to reproduce

N/A

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting! Since there's no reproduction, I'm converting this to a discussion, so somebody can help you debug your CI environment. If in the end there's indeed something wrong on our side, we're happy to fix it ☺️
