### ISSUE TITLE
Color and Hover of Links inside admonition-note/warning

### ISSUE THREAD

**Issue by sebastian-marinescu** [squidfunk/mkdocs-material#7]
Inside a block of note or warning the colors of the links are wrong.
A note has a blue link, which don't flatter the eyes. And in a warning you can't tell there is a link.

**Comment by squidfunk** [comment]
I added a dotted line underneath links inside the main article. This makes it possible to just set the color to white for links inside admonition notes and warnings. I think this is the best solution, as it is independent of color. Furthermore, links can be better distinguished from inline code.
