### ISSUE TITLE
Color palette toggle's keyboard operation is confusing

### ISSUE THREAD

**Issue by cmuncharaz** [squidfunk/mkdocs-material#7003]
### Bug description

The color palette toggle looks like a button, and sighted keyboard users would expect to activate it using the Enter or Space keys. However, the toggle is not responding to those keys. Underneath, this is implemented as a set of radio buttons and is operated using the arrow keys. This is not evident to sighted keyboard users, who might think the "button" is not working.

### Related links

- [Accessibility Issues (#4102) discussion](https://github.com/squidfunk/mkdocs-material/discussions/4102)

### Reproduction

[9.5.16-color-palette-keyboard-operation.zip](https://github.com/squidfunk/mkdocs-material/files/14825773/9.5.16-color-palette-keyboard-operation.zip)

### Steps to reproduce

1. Install Material for MkDocs, create a site with the minimal configuration, set the color palette toggle, serve Material for MkDocs, point your browser to localhost:8000.
2. Use the Tab key to set the keyboard focus indicator on the color palette toggle.
3. Hit Enter or Space to activate it.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for suggesting. Fixed in 78e93ac. Pressing `Enter` now allows to cycle through the palettes. We're likely going to completely rewrite this component as part of our upcoming rebrush / facelift that we're planning to do later this year, but for the time being this should be a good bandaid.

**Comment by squidfunk** [comment]
Released as part of [9.5.17](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.17).
