### ISSUE TITLE
Search not working in Safari

### ISSUE THREAD

**Issue by akhildevvr** [squidfunk/mkdocs-material#7037]
### Context

The search option is not working on safari and firefox. 

### Bug description

The search option is not working on safari and firefox. It stays at "Initializing search' and never gives any results.
Using the latest verion of MkDocs and mkdocs-material.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[mkdocs.txt](https://github.com/squidfunk/mkdocs-material/files/14922301/mkdocs.txt)

### Steps to reproduce

RUN pip install mkdocs
pip install mkdocs-material
pip install mkdocs-awesome-pages-plugin
pip install mkdocs-glightbox
pip install mkdocs-exclude-search
pip install mkdocs-git-revision-date-localized-plugin

### Browser

Safari, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by akhildevvr** [comment]
HI, the mkdocs-exclude-search just excludes pages in domains and contribution pages. It does nothing to issue. It works locally in Safari. We are hosting the docs on AWS S3. The search is working fine on Chrome, but not safari and firefox.

**Comment by alexvoss** [comment]
Search works in all three browsers for me. Without a minimal reproduction that shows the problem on our machines there is nothing we can do, except perhaps make a lucky guess.

You say that search works locally in Safari but don't say if the same is true for Firefox. Does it work locally for all browsers? That might be a hint as to what is going on. 

When you say "The search option is not working", what do you mean? No search box is visible, you cannot enter text, nothing is found? Are there any error messages, e.g., on the JavaScript console?

To allow us to help you you need to first give us information we can work with, as outlined in the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).

**Comment by squidfunk** [comment]
[Closing as incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues-and-duplicates).
