### ISSUE TITLE
Group plugin, but for markdown extensions

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#7040]
### Description

Because there are insider specific markdown extensions now (`material.extensions.preview`), it would be nice if they could be enabled/disabled by an environment variable the [same way plugins can](https://squidfunk.github.io/mkdocs-material/plugins/group/).

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://squidfunk.github.io/mkdocs-material/plugins/group/
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#automatic-previews
- https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/

### Use Cases

I'd like to be able to control all insiders features with a `BUILD_INSIDERS` environment variable, so that outside contributors can build the site locally more easily.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Since there's some movement over at MkDocs regarding maintainership and the direction of the project, I would kindly ask you to take this upstream. There's a discussion on inheritance in https://github.com/mkdocs/mkdocs/issues/3216.

I'm closing this as out of scope for now. If the maintainers of MkDocs decide that they are considering this reasonable feature request out of scope as well, we can reconsider and reopen this issue ☺️
