### ISSUE TITLE
CSS border-radius animation issue on document contributors with Chrome and Edge

### ISSUE THREAD

**Issue by SimonMarquis** [squidfunk/mkdocs-material#7044]
### Bug description

The CSS animation on document contributor avatars is not clean on Chrome and Edge (not reproduced on Firefox.)
The `border-radius: 100%` that should make the avatar a circle, is not respected during the animation.

https://github.com/squidfunk/mkdocs-material/assets/1921278/0f5bf549-f9fb-4ca5-93e3-7dd6aa7dcf9f

In the vide clip, I tried to fix it by removing the css transition directive on `.md-typeset a.md-author img` to show how it should behave.
But since I'm not familiar enough with CSS animation, I'm almost certain that this is not the proper fix!

### Related links

- Any page where the [document-contributors](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors) plugin is enabled
- [src/templates/assets/stylesheets/main/components/_author.scss](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/assets/stylesheets/main/components/_author.scss)

### Reproduction

Reproduced on any page where the [document-contributors](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors) plugin is enabled

### Steps to reproduce

1. Open any page of the official doc with Chrome or Edge, for example the [getting started page](https://squidfunk.github.io/mkdocs-material/getting-started/).
2. Scroll to the end of the page
3. Hover over document contributors with your mouse
4. The CSS animation breaks the border-radius on the avatar.

### Browser

Chrome, Edge, ~Firefox~

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by katharinalisalin** [comment]
Thanks for reporting. However, you did not attach a [.zip file with a minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file) and therefore did not follow our [bug reporting guideline](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/). Please provide us with a minimal reproduction, and we'll be happy to take a look. Until then, I'll mark this issue as [incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues-and-duplicates) and close it for now.

**Comment by SimonMarquis** [comment]
@katharinalisalin here is a reproduction zip:
- [9.5.17-css-animation-issue.zip](https://github.com/squidfunk/mkdocs-material/files/14970053/9.5.17-css-animation-issue.zip)

And the corresponding GitHub project (needed for `mkdocs-git-committers-plugin-2`):
- https://github.com/SimonMarquis/mkdocs-material-7044

**Comment by squidfunk** [comment]
Thanks, we'll investigate ☺️

**Comment by SimonMarquis** [comment]
LGTM, but there is still a tiny glitch.
I'm wondering if the animations are correctly synchronized, because removing the `transition: filter 125ms` make it very smooth (but I agree this is almost imperceptible).


https://github.com/squidfunk/mkdocs-material/assets/1921278/2f295151-15a1-4388-a3ae-ce28488710ac

**Comment by squidfunk** [comment]
It's definitely a glitch. If you can find a better solution, we're happy to merge it, but the fact that I cannot really observe the issue makes it quite impossible for me to fix. So we're considering this done, but are of course happy to merge a better fix by someone that can actually observe the problem 😅 And yes, I've use Chrome on macOS as you reported. Firefox doesn't have this problem – IMHO, most likely a browser synchronization glitch.

**Comment by squidfunk** [comment]
Released as part of [9.5.18](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.18).

**Comment by SimonMarquis** [comment]
Thanks for the fix. Indeed I can only reproduce the glitch on Windows, with a chromium based browser.
