### ISSUE TITLE
Instant previews: default configuration adds previews for all pages

### ISSUE THREAD

**Issue by jonaharagon** [squidfunk/mkdocs-material#7052]
### Context

I'll open a separate bug for you regarding https://github.com/squidfunk/mkdocs-material/issues/7051#issuecomment-2058157177 if this makes it easier to track of.

### Bug description

Enabling the `material.extensions.preview` extension makes mkdocs show instant previews on all internal links. I assume it is treating `targets` as all pages by default, instead of no pages.

```
markdown_extensions:
  - material.extensions.preview:
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[9.5.18+insiders.4.53.6-preview-on-all-links.zip](https://github.com/squidfunk/mkdocs-material/files/14986633/9.5.18%2Binsiders.4.53.6-preview-on-all-links.zip)

### Steps to reproduce

1. Enable `material.extensions.preview` without any options.
2. Add internal link to a page without setting the `data-preview` attribute on it.
3. That link gets the instant preview treatment anyways.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in [`c5989cc`](https://github.com/squidfunk/mkdocs-material-insiders/commit/c5989cc61bb1340586635a70b87f917e85e185d5).

**Comment by squidfunk** [comment]
Released as part of [9.5.19+insiders-4.53.8](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.53.8).
