### ISSUE TITLE
Search is not present when privacy plugin is enabled

### ISSUE THREAD

**Issue by ankudinov** [squidfunk/mkdocs-material#7053]
### Bug description

When privacy plugin is enabled, search field is not present on MkDocs generated site.
`md-search` is not present int the source code.
Please check [this repo](https://github.com/ankudinov/mkdocs-issues) for details. The repository is very slim, all non-essential features are removed and it can be adjusted if required for troubleshooting.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Privacy plugin](https://squidfunk.github.io/mkdocs-material/plugins/privacy/)
- [Search plugin](https://squidfunk.github.io/mkdocs-material/plugins/search/)

### Reproduction

```yaml
plugins:
  - privacy
```

### Steps to reproduce

Check [this mkdocs.yml](https://github.com/ankudinov/mkdocs-issues/blob/master/mkdocs.yml)

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by alexvoss** [comment]
This behaviour is perhaps unfortunate [but documented](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search#built-in-search-plugin). As soon as you add plugins to the `mkdocs.yml`, the search plugin must also be added in. That's *any* plugins, not just the privacy plugin.

**Comment by alexvoss** [comment]
works ad documented
