### ISSUE TITLE
Only insert Google Analytics tracking on a live site

### ISSUE THREAD

**Issue by borekb** [squidfunk/mkdocs-material#706]
I'd like to exclude all local and testing traffic from Google Analytics (right now, it's a significant portion), if I'm not mistaken the GA tracking code is included as soon as the `mkdocs.yml` contains the `google_analytics` key:

https://github.com/squidfunk/mkdocs-material/blob/dbd0006b015324e4a10aa25343c38e78c47b2c54/material/base.html#L202-L204

Is there a way to customize this block so that analytics are only included on live sites? I'm not even sure how to specify that, maybe detect a domain an exclude `localhost`, `127.0.0.1` and `0.0.0.0`, or the other way around, only include GA if the actual domain equals `site_url`.

I'm not that familiar with MkDocs extensibility model so I'm not sure if this is easy to achieve. And would the customization work if I use the Docker container?

**Comment by borekb** [comment]
Another option (again not sure how easily possible): do not include GA code on the dev server, only export it to HTML during `mkdocs build`.

**Comment by squidfunk** [comment]
I'm not aware of a way to determine wether `mkdocs` is running in watch mode or building, as this would be the only way to determine whether we're building for dev or production. However, you could define the analytics key in an environment variable and only set it during build, see: https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml#L122

**Comment by borekb** [comment]
Good trick, thanks. Maybe it would be possible to detect that from port – there is very little chance that the production site also runs on port `8000`. All I'm saying is that it would be nice if this was handled automatically, somehow, although I get that it's not easy to come up with 100% reliable solution.

**Comment by squidfunk** [comment]
Well, this is something that would have to be done in MkDocs. Material only uses the data or gets from MkDocs. Maybe you could open an issue on their tracker, but I don't know what else to recommend except the environment variable workaround.

**Comment by squidfunk** [comment]
That's exactly what I meant. Fiddling with port numbers or assuming that when a port number is not set that it's a production deployment is really not a good heuristic. It's easily avoidable with the workaround I suggested.
