### ISSUE TITLE
Any way to customise the sidebar background (at the large screen size)?

### ISSUE THREAD

**Issue by HunterGraubard** [squidfunk/mkdocs-material#708]
First of all, thank you for this incredible, wonderful theme. It is simply superb, and in my travels across the internet you seem to be literally the only person achieving a Material Design layout with progressive enhancement - it is actually done right and functional without JavaScript. Every other theme I've found is completely broken without JavaScript. Good job.

Anyway, I'd like to customise it a bit for my purposes. Specifically, what I want to do is set a background and border for the left sidebar when it's docked on the side of the screen, when the browser window size is large. The problem I have is with the spacing of elements in the grid. I can of course set a background and border on md-sidebar--primary, but it has padding above and below it, and even worse there's an unknown-length gap to the left due to the md-grid wrapper having a fixed width and using margin: auto for centering. Because of this spacing, if I just style md-sidebar--primary directly, it will stand out like a sore thumb.

I'd like to keep the layout as it is, or at least as close as possible to how it is. I like the page being centered. Do you have any advice on how I might alter it a bit to give the sidebar a nice background without breaking it all? Thanks in advance. If not, that's okay too.

**Comment by squidfunk** [comment]
> First of all, thank you for this incredible, wonderful theme. It is simply superb, and in my travels across the internet you seem to be literally the only person achieving a Material Design layout with progressive enhancement - it is actually done right and functional without JavaScript. Every other theme I've found is completely broken without JavaScript. Good job.

Thanks! That's exactly my motivation and a thing I see so often on modern websites - broken without JavaScript. This is a case that happens more often than expected, e.g. on slow cell connections.

Regarding your question: You could set your styles on `md-nav--primary`. This would never touch the top or bottom, as it's spaced by the padding on the top and bottom of `md-sidebar`. I assume that you will find the spacing on the top of the navigation to be too low which you could mitigate with some extra padding:

<img width="277" alt="bildschirmfoto 2018-02-22 um 19 10 14" src="https://user-images.githubusercontent.com/932156/36556010-0b84fe7a-1804-11e8-9fcb-8e0685eb63e8.png">


Not perfect, but maybe a starting point.

**Comment by HunterGraubard** [comment]
Thanks for your reply. I can do that, and I can adjust the spacing at the top and bottom. My main problem with that is that I'd like the background to show everywhere on the left side. As seen in your screenshot, there is white space to the left, and this seems to be not so easy to deal with. `md-main__inner` is constraining everything to a particular size, which means that `md-nav--primary` can't fill the entire space to the left, and therefore its background can't show on the left. I could set a background on `md-main__inner`, but then it would show to the right of page content as well, which isn't what I want.

**Comment by makshh** [comment]
It's not that easy with Material HTML structure and CSS table layout.

Try this:

@media only screen and (min-width: 76.25em) {
  .md-container {
    position: relative;
  }
  .md-container:before {
    content: '';
    position: absolute;
    top: 9.6rem; // 4.8rem if you don't use tabs
    left: 0;
    width: calc((100% - 122rem) / 2 + 24.2rem);
    height: calc(100% - 25.2rem); // 100% - 20.4rem if you don't use tabs
    background: #eee;
    z-index: -1;
  }
}
```

**Comment by squidfunk** [comment]
Ah okay, I see what you're trying to do. Yes, that's probably not possible without a little of hacking, sorry. Maybe @makshh answer is a good start point. You could also set the background color on `md-main__inner` and the body background color to a gradient from gray to white with a hard break in the middle. Hacky, yeah, but probably works.

**Comment by HunterGraubard** [comment]
Wow, @makshh that solution works wonderfully. Thank you very much! It may be a hack, but it seems easy enough and works great in my testing so far. I understand supporting hacking away at this to customize it and deviate from the official design is probably a low priority, so I really appreciate the help from both of you with this. I'm happy with this solution and it helps me learn a bit more about CSS - the :before selector seems like magic. This can probably be closed now - thanks again.
