### ISSUE TITLE
`abbr` extension breaks title attribute added using `attr_list`

### ISSUE THREAD

**Issue by nbanyan** [squidfunk/mkdocs-material#7081]
### Bug description

``` markdown
*[abbr]: Abbreviation Definition

![Image with abbr in title](abbr.png){title="Image with abbr in title"}
```

This renders the attribute code as plain text because the Abbreviation extension modifies the text in the attribute causing it to no longer be a valid attribute list.

### Related links

- [Tooltips](https://squidfunk.github.io/mkdocs-material/reference/tooltips/)

### Reproduction

[9.5.18-abbr-attr_list-conflict.zip](https://github.com/squidfunk/mkdocs-material/files/15068453/9.5.18-abbr-attr_list-conflict.zip)

### Steps to reproduce

1. Enable the `abbr` and `attr_list` extensions
2. Include an abbreviation definition on a page
3. Use the abbreviation in a title attribute for an object using the attr_list syntax

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by facelessuser** [comment]
This should be taken up with [Python Markdown](https://github.com/Python-Markdown/markdown), not Material which is a theme that is based on a document system that happens to use Python Markdown which is responsible for these extensions and behaviors.

**Comment by squidfunk** [comment]
Thanks for reporting. @facelessuser is right! This should be taken upstream.
