### ISSUE TITLE
Button of content.action.view generated wrong URL when edit is inside the domain

### ISSUE THREAD

**Issue by daniel8192** [squidfunk/mkdocs-material#7086]
### Bug description

If the string "edit" is part of the domain or the path/filename, it's also replaced with "raw", which results in a broken link.
Example: https://git.mycredit.eu/daniel8192/Wiki/edit/main/docs/test.md is modified to https://git.mycrraw.eu/daniel8192/Wiki/raw/main/docs/test.md

### Related links

- [Code, modify the URL to something wrong](https://github.com/squidfunk/mkdocs-material/blob/aaa7ce8e1987fa0e4cd7f89d2cadd8b8052e8026/src/templates/partials/actions.html#L39-L53)

### Reproduction

Issue depends on the domain name therefore a minimal reproduction is not useful. 
mkdocs.yml:
```yaml
repo_url: https://git.mycredit.eu/daniel8192/Wiki
edit_uri: edit/main/docs/
theme:
  features:
    - content.action.edit
    - content.action.view
```

### Steps to reproduce

1. content.action.view is set in mkdocs
2. domain contains edit
3. view button link to a not existing endpoint

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is rather out of scope for us, as the `content.action.view` feature only really supports GitHub and maybe GitLab. Is that ideal? Far from it. Is it possible to easy change things without adding a whole bunch of extra syntax? Probably not. Thus, we're currently considering this out of scope. We will reconsider in the future, as we have big plans for Material for MkDocs, but for now, we can't fix it.

In the meantime, you can use a [theme override](https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials) for [`actions.html`](https://github.com/squidfunk/mkdocs-material/blob/aaa7ce8e1987fa0e4cd7f89d2cadd8b8052e8026/src/templates/partials/actions.html#L39) as a [customization](https://squidfunk.github.io/mkdocs-material/customization/) ☺️

**Comment by daniel8192** [comment]
Thanks for the fast response!
We like the feature with the edit button a lot :)  and we are using Github but as enterprise server installation. 
This problem also occurs when the markdown file name contains edit.
I think it could be fixed easily with using regex_replace  instead of replace and the regex described [here](https://stackoverflow.com/questions/27745/getting-parts-of-a-url-regex).
For us the fix with customization is working!
