### ISSUE TITLE
"Type to start searching" bar flickers in Firefox Nightly.

### ISSUE THREAD

**Issue by JaneSmith** [squidfunk/mkdocs-material#709]
## Description

At the tablet and desktop screen sizes, there is a visible search box. When clicking in the box and typing, it expands to cover more space and displays the text "Type to start searching". That lower bar with that text flickers when opening in Firefox Nightly (60.0a1). It seems fine in Chrome. This can be seen on the mkdocs-material homepage.

### Expected behavior

I expect the search bar to open smoothly without any flicker, as it does on Chrome.

### Actual behavior

The search bar opens and flickers.

### Steps to reproduce the bug

1. Open http://squidfunk.github.io/mkdocs-material/ in Firefox (tested on version 60.0a1).
2. Make sure the browser window is large enough for either the tablet or desktop layouts.
3. Click in the search box and start typing.

**Comment by squidfunk** [comment]
Do you only see this on FF nightly or also on the stable build?

**Comment by JaneSmith** [comment]
Hmm. I use Firefox Nightly as my main browser, but I tried it just now in 39.0.3, 43.0.1, 47.0.2, 56.0, 57.0, and 58.0.2 (I had to do a series of updates on my stable build), and it seems to work fine without any flicker. Perhaps it's just a bug in the latest alpha - or perhaps it might become an issue in the stable version too at a later date. Sorry about that. Should this be closed?

**Comment by squidfunk** [comment]
I think it sounds like a bug in Firefox. Supporting Nightlys is a really, really low priority task ;-) Thanks for testing and reporting!

**Comment by squidfunk** [comment]
I'm closing it. Please re-open if it occurs in a stable release.
