### ISSUE TITLE
Nested linked content tabs have strange border-bottom behavior

### ISSUE THREAD

**Issue by iBug** [squidfunk/mkdocs-material#7090]
### Context

We're trying out using nested linked content tabs on our open-source mirror help page as a replacement for switches (e.g. distro release, file format). An example can be found on our Debian help page (<https://38b0fed1.ustcmirror.pages.dev/help/debian>).

### Bug description

When linked content tabs are nested, their `border-bottom` behaves erratically when they're activated while invisible.

See the demo below.

![demo](https://github.com/squidfunk/mkdocs-material/assets/7273074/032f4f85-0781-4d82-a88b-270b9fd559d4)

It doesn't impact any functionality, just a minor cosmetic problem.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Linked content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs)

### Reproduction

[9.5.18-content-tabs.zip](https://github.com/squidfunk/mkdocs-material/files/15091010/9.5.18-content-tabs.zip)

### Steps to reproduce

1. Start `mkdocs serve`
2. Visit `127.0.0.1:8000`

### Browser

Chrome, Edge, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting! Oh, I love it when those kinds of errors are reported that lie deeper below the surface – it shows how far we've already come in 8 years, but also how far we still have to go 😅 Fixed in 2d07a6aa6.

The problem also manifested without `content.tabs.link`, as the active tab was not correctly computed.
