### ISSUE TITLE
Configuration error when objects are in `markdown_extensions`

### ISSUE THREAD

**Issue by anaisaurus** [squidfunk/mkdocs-material#7106]
### Bug description

I encounter this issue with Python 3.10 and Python 3.12.

After creating my site, I used the `mkdocs serve` to see changes as I edit the configuration.
I could perfectly change the colors, fonts, etc.

Regarding extensions, I decided to use the [recommended configuration](https://squidfunk.github.io/mkdocs-material/setup/extensions/#recommended-configuration) which triggered the following error:

```
ERROR   -  Config value 'markdown_extensions': Invalid Markdown Extensions configuration

Aborted with a configuration error!
```

I tried to handle the error by removing some of the entries and I quickly realise that object entries are causing the error.
Even using the following config triggers the error:

```
site_name: My Docs
markdown_extensions:
  - toc:
    permalink: true
```

### Related links

- [Recommended configuration](https://squidfunk.github.io/mkdocs-material/setup/extensions/#recommended-configuration)

### Reproduction

[docs.zip](https://github.com/squidfunk/mkdocs-material/files/15128003/docs.zip)

### Steps to reproduce

1. `pip install mkdocs-material`
2. `mkdocs serve` => everything is fine 
3. Copy/paste [recommended configuration](https://squidfunk.github.io/mkdocs-material/setup/extensions/#recommended-configuration) in `mkdocs.yml` => error occurs
4. Remove all objects from `markdown_extensions` => everything is fine

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. The correct syntax [as listed in our documentation](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#table-of-contents) is:

``` yaml
site_name: My Docs
markdown_extensions:
  - toc:
      permalink: true
```
