### ISSUE TITLE
Preconnect to https://fonts.gstatic.com for improved performance

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#712]
I've started adding: `<link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
` to the head (just above the linked CSS files) on all the sites I manage which load Google Fonts. It makes a slight improvement to the page load speed.

There's a good article about it here:
https://www.cdnplanet.com/blog/faster-google-webfonts-preconnect/

Would you be interested in adding this to mkdocs-material ?

**Comment by squidfunk** [comment]
Sure, feel free to PR!

**Comment by squidfunk** [comment]
Fixed in 36ec35c2e47bf0bed8de75ca658cab2017c10d29, should be released soon.

**Comment by squidfunk** [comment]
Released as part of 2.6.6.
