### ISSUE TITLE
Mermaid documentation: Superfences documentation not working for mkdocs build

### ISSUE THREAD

**Issue by dominik4545** [squidfunk/mkdocs-material#7132]
### Description

Dear @squidfunk,

The currently described [mermaid.js superfences configuration](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration) (affected documentation) works properly if you use `mkdocs serve` but does not export the required scripts when using `mkdocs build` (see: [my discussion](https://github.com/squidfunk/mkdocs-material/discussions/7126)).

If using the [mkdocs-mermaid2-plugin](https://mkdocs-mermaid2.readthedocs.io/en/latest/#installation) and their superfences configuration, both works properly:
~~~yaml
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
~~~
in addition to the change in the plugins section:
~~~yaml
plugins:
  - search:
  - mermaid2
~~~

Would you please check this and adjust the documentation so that noone else runs in this issue?

Thanks & best regards,
Dominik

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
- [Diagrams configuration](https://squidfunk.github.io/mkdocs-material/reference/diagrams/)
- [MkDocs Mermaid2 Plugin](https://mkdocs-mermaid2.readthedocs.io/en/latest/)
    - [It's superfences configuration](https://mkdocs-mermaid2.readthedocs.io/en/latest/superfences/)
    - [It's troubleshooting guide](https://mkdocs-mermaid2.readthedocs.io/en/latest/troubleshooting/)
- [Own discussion](https://github.com/squidfunk/mkdocs-material/discussions/7126)
- [Previous discussion about diagrams which are not working](https://github.com/squidfunk/mkdocs-material/discussions/3511)

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by alexvoss** [comment]
As I mentioned a moment ago in the discussion, Material for MkDocs uses its own integration with Mermaid. What may need to be changed in the documentation is to add a sentence that clearly states that the integration via the plugin is different?

**Comment by kamilkrzyskow** [comment]
Issues with the mermaid2-plugin should be reported upstream to it:
- https://github.com/fralau/mkdocs-mermaid2-plugin

But we probably should make a note about it in the documentation that the plugin is provided separate functionality 🤔

**Comment by squidfunk** [comment]
We [don't mention the plugin anywhere](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#configuration) and explicitly say that SuperFences is the only necessary configuration. I did not want to keep people from using other plugins though, which a "don't install plugin X" note would do. If you have a better idea, I'm happy to discuss. Closing as upstream.

**Comment by kamilkrzyskow** [comment]
Further discussion in the [linked discussion](https://github.com/squidfunk/mkdocs-material/discussions/7126) has led to a new discovery that the user might be running `index.html` from the filesystem and the default mermaid logic doesn't work then, he still needs to get back to us, might not be an upstream issue after all 😆
