### ISSUE TITLE
Please update mermaid to 10.8.0

### ISSUE THREAD

**Issue by mxmdt3** [squidfunk/mkdocs-material#7133]
### Description

Add support for Mermaid new diagram type - Block Diagram

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://github.com/mermaid-js/mermaid/releases
- https://github.com/mermaid-js/mermaid/pull/5221

### Use Cases

Add support for Mermaid new diagram type - Block Diagram

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Care to send a PR?

**Comment by kamilkrzyskow** [comment]
Why not use to the latest 10.9.0? One issue I could see is that it has KateX support, which is different from material's own KateX support https://squidfunk.github.io/mkdocs-material/reference/math/#katex but perhaps it won't lead to bugs, as long people don't use both🤔

**Comment by squidfunk** [comment]
Yes, we should upgrade to latest. PR appreciated, since this upgrading (and testing) is easy ☺️

**Comment by squidfunk** [comment]
Fixed in https://github.com/squidfunk/mkdocs-material/commit/75d87eaf7ea696cccf99b96c915412b16ea3f079, see https://github.com/squidfunk/mkdocs-material/issues/7149#issuecomment-2092842740

**Comment by squidfunk** [comment]
Released as part of [9.5.21](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.21).
