### ISSUE TITLE
Using Text as Logo.

### ISSUE THREAD

**Issue by DevotionGeo** [squidfunk/mkdocs-material#715]
Note: There is another issue [Text instead of logo in the template header](https://github.com/squidfunk/mkdocs-material/issues/247), but the solution there didn't solve my problem.

I installed mkdocs and mkdocs-material both through pip. The official docs are suggesting me to create a new file `my-site/partials/header.html` and make the required changes, but it didn't work for me. There are two ways to install the theme, either through pip or by cloning the theme repo. I think the overriding partials method explained in the user-guide is applicable when we actually clone the repo, or am I missing something?

And @squidfunk,  Thank you so much for the awesome work!

**Comment by makshh** [comment]
Hi,

I have Material installed through pip and overriding partials is working fine for me.

Maybe show us your folder structure and your configuration file?

**Comment by makshh** [comment]
https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure

1. You need to create a folder (call it for example `theme` inside your project (on the same level as assets folder).
2. Move your partials folder in theme folder.
2. You need also to set custom_dir: 'theme' in theme options in your configuration file.

Everything is in the docs ;)

**Comment by DevotionGeo** [comment]
Thank You @makshh , the `custom_dir` setting in the `mkdocs.yml` worked for me.

**Comment by squidfunk** [comment]
Closing this as solved. Thanks @makshh for answering this one!
