### ISSUE TITLE
Add PlantUML Markdown extension schema

### ISSUE THREAD

**Issue by mschoettle** [squidfunk/mkdocs-material#7159]
### Description

We use PlantUML diagrams and include them with the [PlantUML Markdown extension](https://github.com/mikitex70/plantuml-markdown) into our documentation site. It works nicely with mkdocs-material as well.

It would be nice to have the schema included so that that part of the configuration in `mkdocs.yaml` is validated as well.

### Related links

- https://github.com/mikitex70/plantuml-markdown#plugin-options

### Use Cases

As mentioned in the description, being able to fully validate the MkDocs file.

I started making the change (at least for a subset of the configuration options) and then wondered whether there is interest in adding this schema to this repo or whether it would be better to try to get it added to the extension's repo instead.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! We're happy to link to third party integrations, so feel free to create a PR with [a link to your schema](https://github.com/squidfunk/mkdocs-material/blob/c1336ae0f598a47828c44073fb6491f622280e0d/docs/schema/plugins.json#L95-L132), if you'd like to maintain it. We're not directly integrating with PlantUML, so it makes no sense for us to maintain a schema, as we're not using it ourselves. Closing as out of scope, but as said, happy to integrate an external schema!
