### ISSUE TITLE
FR: Support Variable from Pyproject.toml

### ISSUE THREAD

**Issue by jvanderaa** [squidfunk/mkdocs-material#7168]
### Context

We are building docs where we want to have an example output of a `--version` from the CLI. To help with not having to go find that one doc segment every version change, it would be nice to have mkdocs read from the pyproject.toml file the version.

### Description

We are building docs where we want to have an example output of a `--version` from the CLI. To help with not having to go find that one doc segment every version change, it would be nice to have mkdocs read from the pyproject.toml file the version.

Would love to have the variable support - during the build process only. So it would not be dynamic, but on a new docs build. And for this to be helpful, it would need to be supported to be read inside of a code block.

### Related links

- I have searched for `version`, `pyproject.toml` and variables
- A few issues have come up, mainly around the blog theme.

### Use Cases

Would like to not have to maintain a code snippet output that could be referenced from another place.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. There is [mkdocs-macros](https://github.com/fralau/mkdocs-macros-plugin) by @fralau, which, as I understand, is pretty powerful and capable of exactly what you're asking for. Closing as resolved via customization.
