### ISSUE TITLE
Custom Icons: size and color info missing in documtation

### ISSUE THREAD

**Issue by Technofrikus** [squidfunk/mkdocs-material#7172]
### Description

I have added custom icons and had/have some struggles. 

Custom Icons as in: made by myself. Not other sets.

In the navigation they pushed away the text besides them:
![CleanShot 2024-05-12 at 13 32 58@2x](https://github.com/squidfunk/mkdocs-material/assets/319375/b556d356-1bb5-4501-a07d-437ee6169e82)

I figured out that the svg need to be smaller. I couldnt find what size they need to be. I made them smaller and smaller until they worked.

Next (still unsolved) problem: what color should they have so that the color is adjusted depending on context? So for exmaple that they fit in when in a link.
![CleanShot 2024-05-12 at 14 41 35@2x](https://github.com/squidfunk/mkdocs-material/assets/319375/0c810338-4c82-492f-a26e-304b023ed853)

### Related links

I used this guide: https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#additional-icons

### Proposed change

Add the specs that a custom icon needs to be in the documetation:
- size
- color, so that the theme customizes the color to fit the context.

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
I'm converting this to a discussion, so the community can help you with your customization. We're currently not considering making our [icon customization guide](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#customization) more complex. However, if we can make it easier with a few sentences, feel free to open a PR.
