### ISSUE TITLE
Default value for search-plugin separator has a typo

### ISSUE THREAD

**Issue by casio888** [squidfunk/mkdocs-material#7185]
### Bug description

We experienced a TypeError in lunr Search on specific letters/search terms, resulting in a broken search bar. After looking into it, we identified a code block that did not get separated correctly into the expandedTerms and was not found in the invertedIndex.

When looking at the default spearator, documented here (https://squidfunk.github.io/mkdocs-material/plugins/search/#config.separator), we saw that `(` and `)` were explained to be special characters that should be recognized as separators, but the regex did not escape them, so they were skipped.

We escaped them in an override and it worked fine. I think the default separator should be changed to look like this:
`separator: '[\s\-,:!=\[\]\(\)"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'`

### Related links

- [Search Separator](https://squidfunk.github.io/mkdocs-material/plugins/search/#config.separator)

### Reproduction

I can't get a minimum reproduction to show the bug, but it happens in our project and the fix works.

### Steps to reproduce

Create a code Block (starting with 3 backticks and ending with 3 backticks) with a Function and search for the function name:

```python
from dask_jobqueue import SLURMCluster

cluster = SLURMCluster(queue='test',
  cores=4,
  processes=2,
  project='project',
  memory="8GB",
  walltime="10:23:11")

```

Search for `slurm` or `slurmcluster`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. I'm not sure why you're getting the behavior you described, but it is the exact same separator we're using on our documentation. Escaping `(` and.`)` inside a character class `[...]` is not necessary. The only characters that need to be escaped are `]`, `^` and `-`, as they are control characters for character classes.

Also, if you run it in the browser's console, you'll see that the separator works:

``` js
"cluster = SLURMCluster(queue='test',".split(/[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;/)
// => ['cluster', 'SLURM', 'Cluster', 'queue', "'test'", '']
```

If it's still a problem, please create a proper [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) which we can run. Otherwise, it's working as intended.
