### ISSUE TITLE
[change(feature) request] Page Subtitle for Blog Posts

### ISSUE THREAD

**Issue by tylernguyen** [squidfunk/mkdocs-material#7194]
### Context

[Setting the page `subtitle`](https://squidfunk.github.io/mkdocs-material/reference/?h=subtitl#setting-the-page-subtitle) (part of [insiders-4.25.0](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.25.0) release)

blog_toc: true

### Description

The current [page subtitle feature](https://squidfunk.github.io/mkdocs-material/reference/?h=subtitl#setting-the-page-subtitle) only supports and render as part of the navigation sidebar.

It would be great if this feature can be improve to support blog posts, and also render as part of the table of contents.

### Related links

[Setting the page `subtitle`](https://squidfunk.github.io/mkdocs-material/reference/?h=subtitl#setting-the-page-subtitle)

### Use Cases

Subtitles for navigational pages are useful, but are rarely used since their short titles and url slugs are normally self-explanatory.

Title of blog posts usually needs to be descriptive. Currently, if blog titles long, they will be rendered into multiple lines as part of the blog page's table of contents. This makes the blog page's TOC rather hard to read with multiple blog posts.

If this feature is implemented, the majority of my blog posts' titles can be shortened. And the subtitles will act as the extra context needed. In addition, the subtitles' smaller text will act as visual indicators separating different blog posts in the TOC.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. I'm not sure I understand your change request. The page subtitle is solely used in navigation, but IIUC you want to provide an alternate, short title that is used _instead_ of the blog post title in the table of contents?

**Comment by tylernguyen** [comment]
[9.5.23+insiders.4.53.8-subtitle-below-blog-post-title-in-toc.zip](https://github.com/squidfunk/mkdocs-material/files/15365964/9.5.23%2Binsiders.4.53.8-subtitle-below-blog-post-title-in-toc.zip)


Sorry if I wasn't being clear.

>  short title that is used _instead_ of the blog post title in the table of contents?

It would NOT be used instead of the blog post title. But is shown below the title, just as how subtitles is currently implemented in the navigation bar.

Here is a mock-up:

![Screenshot 2024-05-18 110129](https://github.com/squidfunk/mkdocs-material/assets/3349081/414fea16-3b48-4693-bbee-667cd6c609f2)

**Comment by squidfunk** [comment]
Thanks for explaining! Subtitles are currently only implemented for navigation, not for the table of contents. It might be possible to make this work, but it's a lot of work, as the navigation and table of contents are implemented in two different partials, since they behave differently. For this reason, we're currently not considering implementing this functionality.

It is, however, achievable with [customization](https://squidfunk.github.io/mkdocs-material/customization/). You'd need to adopt the subtitle logic to the [`toc-item`](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/partials/toc-item.html) partal. I hope it's understandable that we can't follow each and every feature request, which is why we make it possible to customize ☺️
