### ISSUE TITLE
Great Layout and functionality but real bad pagespeed rating

### ISSUE THREAD

**Issue by dbdevtop** [squidfunk/mkdocs-material#720]
## Description
Coming from HUGO I stumbled over the real impressive mkdocs-material. 
Before switching over to the mkdocs world I made a quick pagespeed test (see blow) and was a bit dissapointed by the figures (73 mobile, 46 desktop). 

### Expected behavior
Clients nowadays demand loading times of less than 3 seconds with a pagespeed rating of at least 85.
 
### Actual behavior
[PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fsquidfunk.github.io%2Fmkdocs-material%2F&tab=desktop)

### Question
Can "mkdocs-material" be improved with respect to render-blocking?

**Comment by squidfunk** [comment]
Thanks for reporting. I did a pagespeed test some while ago and it had the same result. I try to explain the penalties:

* **Eliminate render-blocking JavaScript and CSS in above-the-fold content**: for JavaScript this could theoretically be omitted by moving `modernizr.js` to the bottom of the `body` right above the `application.js` . It's possible as Material is entirely built using progressive enhancement, but I don't know if it will greatly improve rendering. Extracting the above-the-fold CSS is not really possible, as "above the fold" can be the entire page, see:

![bildschirmfoto 2018-03-01 um 18 59 33](https://user-images.githubusercontent.com/932156/36860837-b3d98fc2-1d82-11e8-83f6-966a54c3ef91.png)

* **Leverage browser caching**: this is entirely attributed to the cache headers of GitHub pages. The theme can't do anything about these values. If you self-host, you can eliminate all errors by setting more appropriate cache headers.

* **Optimize images**: that's a problem specific to the Material documentation and the large image. I may consider generating a thumbnail for this, but it's not a problem of the theme but of the content.

Same for desktop and mobile. For validation, I searched for people self-hosting their docs and found retropie.org.uk to have quite a reasonable configuration:

<img width="1087" alt="bildschirmfoto 2018-03-01 um 19 14 40" src="https://user-images.githubusercontent.com/932156/36861703-f42f95e2-1d84-11e8-9e18-abf5255fade2.png">

See the [page speed insights](https://developers.google.com/speed/pagespeed/insights/?hl=en&url=https%3A%2F%2Fretropie.org.uk%2Fdocs%2F). If they would optimize asset delivery, page speed ratings should be above 85 for both mobile and desktop.

**Comment by squidfunk** [comment]
Closing this as answered/resolved.

**Comment by makshh** [comment]
@dbdevtop I'm not a fan of this soluton but you may look at this article:

https://varvy.com/pagespeed/defer-loading-javascript.html
