### ISSUE TITLE
Comment: The comment page must be refreshed to appear.

### ISSUE THREAD

**Issue by SkyHighR** [squidfunk/mkdocs-material#7202]
### Context

I need to use giscus comments with the navigation.instant turned on at the same time.

### Bug description

When I use giscus comments, then turn on the navigation.instant attribute, only the comments of the first displayed page can be loaded (if the page comment is on), when I click on other pages, giscus comments will only appear "Commet" words. No comment box. The strange thing is that everything works fine when building locally

### Related links

#5816

### Reproduction

Because it involves comment overrides, I can't add info plugin, but I remove other overrides, css and JavaScript as much as possible.  

You can view my website source code [in this repo](https://github.com/SkyHighR/SkyBlog/tree/issue7207)，The built product is in the gh-pages branch

### Steps to reproduce

1. open [this page](https://871ebef5.skyhigh.pages.dev), comments are loading fine
2. Switch a random page in the right navigation, then scroll to the bottom and you'll see that the page comments won't load.

### Browser

Chrome, Safari, Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Please understand that we need a reproduction to look into it.

> Because it involves comment overrides, I can't add info plugin, but I remove other overrides, css and JavaScript as much as possible.

You can use the info plugin with [`archive_stop_on_violation`](https://squidfunk.github.io/mkdocs-material/plugins/info/#config.archive_stop_on_violation):

``` yaml
plugins:
  - info:
      archive_stop_on_violation: false
```

**Comment by SkyHighR** [comment]
[9.5.24-bug.zip](https://github.com/squidfunk/mkdocs-material/files/15414569/9.5.24-bug.zip)  
I created this bug info on my computer.

**Comment by squidfunk** [comment]
Thanks! This is not a minimal reproduction – it's the contents of your repository. Please create a [__minimal__ reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by SkyHighR** [comment]
Sorry, I checked carefully. There should be a conflict between my plug-in and the style.
