### ISSUE TITLE
Blog issue - TypeError: unsupported operand type(s) for |: 'ABCMeta' and 'NoneType'

### ISSUE THREAD

**Issue by SteveRosam** [squidfunk/mkdocs-material#7207]
### Context

I have seen this issue, which is now closed.
(I have tried with Python 3.8 and 3.11)
https://github.com/squidfunk/mkdocs-material/issues/6264

### Bug description

When I add this to a new docs site (mkdocs + material) I get the error below
Note that i also add a blog folder under docs folder and a posts folder under that. 
an index.md goes in the blog folder and a .md file goes in the posts folder.
All per the docs.

```
plugins:
  - blog
````
TypeError: unsupported operand type(s) for |: 'ABCMeta' and 'NoneType'

### Related links

- [Blog plugin](https://squidfunk.github.io/mkdocs-material/plugins/blog/)

### Reproduction

repro files [mkdocs-material.zip](https://github.com/squidfunk/mkdocs-material/files/15404790/mkdocs-material.zip)

### Steps to reproduce

Follow the docs and ensure the correct folder structure

![image](https://github.com/squidfunk/mkdocs-material/assets/100689438/c11d56af-eb1b-455f-8212-5525466222c5)

Update `mkdocs.yml` with the blog config

```
site_name: My site
site_url: https://mydomain.org/mysite

theme:
  name: material

plugins:
  - blog

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  
```

same issue whether i have nav in there or not.

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Unfortunately, we don't know which version of MkDocs, Material for MkDocs and all other dependencies you are using. This is why we require using the [info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/) (as mentioned in our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) and this issue template). Thus, please make sure to carefully read and follow our bug reporting guidelines.

My guess is that you're using an outdated version. Closing as not reproducible.
