### ISSUE TITLE
Social cards: Using a custom background image

### ISSUE THREAD

**Issue by augustelalande** [squidfunk/mkdocs-material#7216]
### Description

I'm trying to create a social card with a custom background image with no success. Looking at https://github.com/squidfunk/mkdocs-material/blob/master/src/plugins/social/plugin.py I see no use of the `background_image` option and searching the repo only finds mentions in the documentation https://github.com/search?q=repo%3Asquidfunk%2Fmkdocs-material%20background_image&type=code

Was feature maybe removed from the code but not the documentation?

### Related links

- https://squidfunk.github.io/mkdocs-material/plugins/social/#option.background_image

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting. The [`background_image`](https://squidfunk.github.io/mkdocs-material/plugins/social/#option.background_image) option is currently solely available in [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/), and thus reserved to sponsors. If you wish to use it, you can consider becoming a sponsor of our work ☺️

**Comment by augustelalande** [comment]
gotcha
