### ISSUE TITLE
Feature Request: Specify pages to be indexed with site search

### ISSUE THREAD

**Issue by kylebarron** [squidfunk/mkdocs-material#722]
I was looking through the documentation about site search, and the only options provided are to change the language and the tokenizer. Is it possible to filter some pages not be be indexed/seen in the search bar? I'm guessing that might be non-trivial to implement, so if not currently implemented feel free to close this issue.

**Comment by squidfunk** [comment]
That's an upstream MkDocs issue, as Material only processes the indexed documents it gets. In theory, this could be made configurable but it would be really complicated and not user friendly. I'm currently rewriting the JavaScript in TypeScript using RxJS and will make a lot of events/data available to hook into, so this could also be made configurable via extra JavaScript. However, that moment lies in the future.
