### ISSUE TITLE
Blog: allow post author avatar to reference local files

### ISSUE THREAD

**Issue by AmebaBrain** [squidfunk/mkdocs-material#7230]
### Context

Currently, `avatar` attribute in `.authors.yml` must be a valid URL. It's directly substituted to the `<img src="">` attribute. It would be good to allow use relative path and refer to a local resource.

See #7211 for details

### Description

Currently, `avatar` attribute in `.authors.yml` must be a valid URL. It's directly substituted to the `<img src="">` attribute. It would be good to allow use relative path and refer to a local resource.

See #7211 for details and attached file with reproduction

[9.5.25-post-author-display-bug.zip](https://github.com/user-attachments/files/15519674/9.5.25-post-author-display-bug.zip)

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

It will omit necessity to have an external `http(s)` resource dependency. 

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Fixed in 0fc36a1f4c90f350be7c51f5600d7f33716faa7b. The reproduction now correctly links all local images.

**Comment by squidfunk** [comment]
Released as part of [9.5.26](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.26).
