### ISSUE TITLE
Extra tabs in case content.tabs.link is enabled, get switched to another tab while scrolling.

### ISSUE THREAD

**Issue by AdityaGarg8** [squidfunk/mkdocs-material#7232]
### Bug description

I have created a webpage with content.tabs.link enabled. Link: https://adityagarg8.github.io/wiki/guides/wifi-bluetooth/. In this webpage you can see, there are 2 sections, On macOS and On Linux. On macOS section has tabs by the name of Method 1, Method 2 and Method 3. On Linux section also has these 3 tabs + 1 additional Method 4 tab. If I choose the method 4 tab, and start scrolling, it resets to the tab which has been selected in the On macOS section.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Content tabs](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/)

### Reproduction

I am unable to make a zip file since I am getting the error: The "info" plugin is not installed. So I am sending the repository as a zip.
[wiki.zip](https://github.com/user-attachments/files/15522819/wiki.zip)

### Steps to reproduce

1. Open https://adityagarg8.github.io/wiki/guides/wifi-bluetooth/
2. Go to the On Linux section there
3. Choose the tab having Method 4
4. Scroll the page, the tab switches to some other tab

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Please provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), not your entire repository. The error might be hiding in your customizations, so we need to be sure it originates from our code. Using the info plugin is absolutely mandatory. Make sure to upgrade Material for MkDocs as well. We might have fixed it in a subsequent version. Thus, please follow our [bug reporting guide](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) carefully and provide a clean and minimal reproduction that showcases the issue. 

We can reopen this issue once you provide the reproduction.

**Comment by AdityaGarg8** [comment]
Hello @squidfunk 

I managed to create a minimal reproduction zip. Apparently, info plugin wasn't working in macOS, but I succeeded on Linux.
[9.5.25-content-tabs-link-bug.zip](https://github.com/user-attachments/files/15524765/9.5.25-content-tabs-link-bug.zip)

**Comment by AdityaGarg8** [comment]
Steps to reproduce

1. Open wifi-bluetooth guide in the docs folder in the zip.
2. Go to the On Linux section there
3. Choose the tab having Method 4
4. Scroll the page, the tab switches to some other tab

**Comment by squidfunk** [comment]
Confirmed, thanks for the reproduction. I'll look into it.

**Comment by squidfunk** [comment]
Fixed in 1cc45d50d. It was related to the changes introduced in #7232. to compute the indicator for nested content tabs, which led to each content tab container being remounted on visibility. The applied changes should mitigate both issues.

**Comment by AdityaGarg8** [comment]
> Fixed in [1cc45d5](https://github.com/squidfunk/mkdocs-material/commit/1cc45d50d077c8c27d58b71dcc11b941779ec9b2). It was related to the changes introduced in #7232. to compute the indicator for nested content tabs, which led to each content tab container being remounted on visibility. The applied changes should mitigate both issues.

Thanks. It works now.

**Comment by squidfunk** [comment]
Released as part of [9.5.26](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.26).
