### ISSUE TITLE
Subtitle suggestion

### ISSUE THREAD

**Issue by iromise** [squidfunk/mkdocs-material#724]
Just like the http://www.mkdocs.org/ shows, there will be 
 
- Writing Your Docs: user-guide/writing-your-docs.md
- Styling Your Docs: user-guide/styling-your-docs.md
- Configuration: user-guide/configuration.md
- Deploying Your Docs: user-guide/deploying-your-docs.md
- Custom Themes: user-guide/custom-themes.md
- Plugins: user-guide/plugins.md

inside the `User Guide`.

**Comment by squidfunk** [comment]
Material is only a theme for MkDocs, so it assumes that there's basic knowledge. I don't want to copy all the documentation from MkDocs, because then I would have to keep it in sync.

**Comment by iromise** [comment]
Sorry, I do not understand what you mean, is it because Material already support it(inherit from original mkdocs, which i might do not find) or this is your choice that won't support this feature?

**Comment by martinbira** [comment]
@iromise Do you want the documentation for [the Material theme](https://squidfunk.github.io/mkdocs-material) to include the documentation available at [MkDocs user guide](http://www.mkdocs.org/user-guide/writing-your-docs/)? Is that the suggestion?

As @squidfunk writes, the core documentation for basic knowledge of MkDocs (such as how to write your docs) should be at the MkDocs site. The documentation about the custom theme Material and its usage, extensions and so on should be on the Material theme site.

**Comment by iromise** [comment]
I think possibly I do not make myself clear. I'd like to suggest the following feature,
1. when you press the title in the bar, such as `User Guide`.
2. there will be some subtitle show below the title, such as `Writing Your Docs` .

I am not wondering the mkdocs to be here.

**Comment by squidfunk** [comment]
Ah, you mean a dropdown navigation - that is not supported by Material and not planned.

**Comment by iromise** [comment]
oh, thanks a lot. Hope this can be your plan.

**Comment by squidfunk** [comment]
Material is a theme and therefore heavily opinionated. You can always add the stuff you feel is missing yourself by customizing the theme. Dropdown navigation would interfere with the way navigation is currently laid out.
