### ISSUE TITLE
Search is broken with hyphens

### ISSUE THREAD

**Issue by roidelapluie** [squidfunk/mkdocs-material#725]
## Description

Searching A-B does not return pages with A-B

### Expected behavior

Searching A-B should return pages with A-B

### Actual behavior

No page is returned.

### Steps to reproduce the bug

1. Create a page with A-B as txt
2. Look for it

### Package versions

* Python: Python 2.7.14
* MkDocs: mkdocs, version 0.17.2
* Material: Version: 2.6.6

**Comment by squidfunk** [comment]
Please see the bottom of [this section]( https://squidfunk.github.io/mkdocs-material/getting-started/#site-search) for directions on how to change the default tokenization behavior.

**Comment by roidelapluie** [comment]
Thanks!!

**Comment by NicolasMassart** [comment]
@squidfunk @roidelapluie I'm trying to figure how this fixed the issue but I still have the issue on my site and when searching for "host-whitelist" I have no results but "host whitelist" returns all the pages with "host-whitelist" in them. It looks like the setting in extra > search > tokenizer doesn't change this behavior in my case. Any idea ?

**Comment by squidfunk** [comment]
Could, again, be related to stemming, see https://github.com/squidfunk/mkdocs-material/issues/1099#issuecomment-491503493

**Comment by squidfunk** [comment]
Are you using Insiders? Complex separators are only available in the [new search implementation](https://squidfunk.github.io/mkdocs-material/blog/2021/search-better-faster-smaller/), which is currently exclusively available to sponsors. Other than that, [tokenizing on hyphens](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-separator) should also work with the old implementation:

```
plugins:
  - search:
      separator: '[\s\-\.]' 
```

**Comment by squidfunk** [comment]
> @squidfunk one thing I noticed is the query cannot start with a -, but hyphens inside a string are OK and can be found search-this

Correct, because `-` is a [control character](https://lunrjs.com/guides/searching.html#term-presence) that says "exclude this term"

**Comment by flynneva** [comment]
@squidfunk I found a solution to my problem and [posted the solution in the discussions section](https://github.com/squidfunk/mkdocs-material/discussions/3163), thanks so much for your quick response though!
