### ISSUE TITLE
Support absolute url for logo

### ISSUE THREAD

**Issue by lyoshenka** [squidfunk/mkdocs-material#726]
## Description

Right now the logo url is always prepended with base_url. It would be nice not to do that if the logo url starts with `http://` or `https://`.

### Package versions

* Python: Python 2.7.12
* MkDocs: mkdocs, version 0.17.2
* Material: Version: 2.6.6

### Project configuration

``` yaml
theme:
  logo: 'https://www.google.com/logos/doodles/2018/gabriel-garcia-marquezs-91st-birthday-5046026191765504-s.png'
```

**Comment by squidfunk** [comment]
Fixed and released as part of 2.7.0
