### ISSUE TITLE
Custom emoji generator causes unnecessary deprecation warning

### ISSUE THREAD

**Issue by evan-flynn-apexai** [squidfunk/mkdocs-material#7276]
### Description

1. We had a custom emoji generator py file in use while using mkdocs-material < 9.4
2. After bumping to >9.4, we get a deprecation warning saying we need to use `material.

> Material emoji logic has been officially moved into mkdocs-material
> version 9.4. Please use Material's 'material.extensions.emoji.to_svg'
> instead of 'materialx.emoji.to_svg' in your 'mkdocs.yml' file.

Can we still use a custom emoji generator after 9.4 or is this not supported anymore?

The custom emoji generator is only used as a work around to avoid replacing API references with emojis (e.g. `foo::hammer::bar` is replaced today with `foo:` + :hammer: + `:bar`). If this bug could be fixed in `mkdocs-material` generator then we would just use that.

### Related links

https://github.com/squidfunk/mkdocs-material/discussions/4805

### Use Cases

1. Use custom emoji generator

or 

2. Improve mkdocs-material emoji generator to handle API references without replacing them with emojis

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. Sounds sensible, as our plan was not to make it harder to use custom emoji generators. Could you provide a minimal reproduction, so we have something to work with – it's likely as easy fix then ☺️

**Comment by kamilkrzyskow** [comment]
The deprecation warning comes from using the `to_svg` and `twemoji` functions from the deprecated `materialx` module.
https://github.com/facelessuser/mkdocs-material-extensions/blob/master/materialx/emoji.py

I don't remember any issues when migrating over to the new module, so just stop using the deprecated module in your custom emoji generator.

**Comment by evan-flynn-apexai** [comment]
@squidfunk @kamilkrzyskow ahhh you are right :facepalm: I updated the config file, but forgot to update the custom generator python `import` statement. Our custom generator was still importing the legacy `from materialx.emoji import to_svg` instead of the "new" `from material.extensions.emoji import to_svg`.

Sorry for the noise :disappointed:
