### ISSUE TITLE
'?' and '=' in extra_css get escaped

### ISSUE THREAD

**Issue by jfcherng** [squidfunk/mkdocs-material#729]
## Description

I use `?` and `=` in `extra_css` as a simple cache refresher for CDN/browser.

```yaml
extra_css:
  - 'assets/css/my.css?v=20180308c'
```
However, `?` and `=` get escaped into `%3F` and `%3D`.
```html
<link rel="stylesheet" href="./assets/css/my.css%3Fv%3D20180308c">
```
Hence I got error like `assets/css/my.css%3Fv%3D20180308c 404 (Not Found)` in the browser console.

https://github.com/squidfunk/mkdocs-material/blob/0d788714c6f169e412b8d18646444f7b3980392a/src/base.html#L145-L147

### Expected behavior

`?` and `=` remains the same as what they are.

### Actual behavior

`?` and `=` get escaped.

### Steps to reproduce the bug

1. Add a **RELATIVE** path that includes `?` or `=` in `extra_css`
2. Build the site.

### Package versions

* Python: Python 3.6.4
* MkDocs: mkdocs, version 0.17.3
* Material: Version: 2.7.0

### System information

* OS: Win7 SP1 x64
* Browser: Chrome 65.0.3325.125

**Comment by squidfunk** [comment]
I tried to reproduce this, but it works perfectly. I'm running MkDocs 0.17.2 on macOS. My config:

``` yaml
extra_css:
  - 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css?v=1234'
```

``` html
...
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css?v=1234">
...
```

Can you give more details on your setup?

**Comment by jfcherng** [comment]
Update:

If the URL is not started with `http`, this bug happens.
I am using a relative path `assets/css/my.css?v=20180308c` in `extra_css`.

**Comment by squidfunk** [comment]
Still not reproducible. Tried with:

``` yaml
extra_css:
  - 'assets/stylesheets/application.css?v=20180308'
```

Got:

``` html
<link rel="stylesheet" href="./assets/stylesheets/application.css?v=20180308">
```

**Comment by jfcherng** [comment]
Hmm... I found that I cannot reproduce this on my CentOS production server even with the exactly same codes either. Let's see what could I found further...

**Comment by jfcherng** [comment]
I could reproduce this bug in my Win10 x64 VM but not my Lubuntu 16.04 VM.
Suspecting this is a Windows-only problem. Let me install a brand-new Win10 VM to check this.

**Comment by squidfunk** [comment]
No matter what, it's not an issue with Material but with MkDocs, as the variable is passed to the template wrong. Please report an issue on their [issue tracker](https://github.com/mkdocs/mkdocs/issues)
