### ISSUE TITLE
Is there a easy way to place some buttons?

### ISSUE THREAD

**Issue by stupkad** [squidfunk/mkdocs-material#732]
Hi,

I really love Mkdocs + Material, I documented my whole product using Mkdocs,, as well I used  it for the whole website - only some "call to action" buttons are missing.

Is there an easy possibility to place links shown as  buttons?

Thanks, 
Dietmar

**Comment by squidfunk** [comment]
I'm afraid not really. The theme is written from scratch and buttons are not really part of it. However, you can add your custom CSS (see the customization guide) and use plain HTML `button` tags within your Markdown source.

**Comment by squidfunk** [comment]
Closing as answered.
