### ISSUE TITLE
gemoji supports

### ISSUE THREAD

**Issue by ZhiyuanChen** [squidfunk/mkdocs-material#7351]
### Description

Support other emoji indexes like gemoji and emojione.

### Related links

- [PyMDX emoji](https://facelessuser.github.io/pymdown-extensions/extensions/emoji/)
-

### Use Cases

I use readme as a part of my documents, e.g. https://multimolecule.danling.org/module/. 

To let GitHub correctly renders emoji, I must use gemoji index. 

While it works if I do the following:

```
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

But, I'll lose access to all the icons MkDocs material provides. 

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by alexvoss** [comment]
You could try providing a [custom emoji index](https://facelessuser.github.io/pymdown-extensions/extensions/emoji/#custom-emoji-indexes) function that merges the indexes you are interested in. I am not sure if this could be done in a generic fashion as there might be clashes to resolve, for example.

**Comment by squidfunk** [comment]
Thanks for suggesting. While I understand the rational, we're currently not planning to support multiple Emoji indexes for our icons integration. Twemoji is the one we recommend. We might consider factoring out the icon syntax in the future, but it's currently not a priority. If you wish to switch to gemoji, you can provide your own extension by [patching this file](https://github.com/squidfunk/mkdocs-material/blob/master/src/extensions/emoji.py).

Closing as not planned.

**Comment by ZhiyuanChen** [comment]
For anyone interested, I created a new project called [mkdocs-material-extensions-2](https://github.com/ZhiyuanChen/mkdocs-material-extensions-2), which added the supports.
