### ISSUE TITLE
disable (or customize) "more on this page" in search results

### ISSUE THREAD

**Issue by psifertex** [squidfunk/mkdocs-material#7355]
### Context

This might just be a specific instance that will be addressed by https://github.com/squidfunk/mkdocs-material/issues/6307 but right now we have a lot of users who fail to find the item they're looking for in the documentation because the search term shows up many times and they don't notice "more on this page" when scrolling and so the most appropriate result will be hidden until they click that.

### Description

I'd like to have the ability to either disable "more on this page" or specify a minimum number of results upon which that feature is enabled. So anything less than, say 10 items and I want them individually listed, not hidden behind a click

### Related links

https://github.com/squidfunk/mkdocs-material/issues/6307

### Use Cases

This could significantly help the number of times the user searches for a term that is in the docs but the fail to find the correct location they are looking for because it is hidden behind a click.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! Search is going to receive a major update and the "more on this page" is going away. Thus, we're not considering making changes right now, since they will soon be replaced by an entirely new interface. If you wish to expand them by default, you can make the button more apparent, e.g. with the following styles:

``` css
.md-search-result__more summary {
  background: red; /* Change to any color you like */
}
```

**Comment by psifertex** [comment]
Thanks for the suggestion and the quick reply. Totally understand -- I'm definitely excited for the new search!
