### ISSUE TITLE
Sidebar (Menu) behaviour issue

### ISSUE THREAD

**Issue by mhcpan** [squidfunk/mkdocs-material#736]
## Problem in Sidebar (Menu) show/hide with Android device

When browse mkdocs-material powered sites in Android device, menu will be shown when **Back** button is pressed. 
### Expected behavior
It is expected previous page should be shown without menu(sidebar).

### Actual behavior
Menu/sidebar show up

### Steps to reproduce the bug
1. Open https://squidfunk.github.io/mkdocs-material/ with **Android** device
2. Click Menu button at top left corner to show menu
3. Select "Release" section
4. Press "Back" button of Android device, previous page with Menu show up

If we check [Google Matrial](https://material.io/guidelines/material-design/), menu won't be displayed if **Back** button is pressed.

### System information
* OS: Android 6/7/8
* Browser: Chrome/Dolphin

**Comment by squidfunk** [comment]
That's indeed a bug related to the way some browsers handle form field history, as the sidebar is implemented using the checkbox hack so it works without JavaScript. A possible fix would be to unset the field upon page load no matter if it is set or not. However, that will only work if JavaScript is available and there might be a slight flash (page loads, menu is open, menu closes).

**Comment by mhcpan** [comment]
Thanks for the info. Is it possible to include a configuration flag to allow "unset" the field?

**Comment by squidfunk** [comment]
Theoretically yes, but it's probably better if I included the JavaScript-based fix in the code base anyway.

**Comment by squidfunk** [comment]
`autocomplete=off` actually does the trick, will provide a fix.

**Comment by squidfunk** [comment]
Fix released as part of 2.7.1

**Comment by philmarc** [comment]
Just FIY, according to W3C, `autocomplete=off` is not allowed on `type="checkbox"`

Attribute `autocomplete` is only allowed when the input type is `color`, `date`, `datetime-local`, `email`, `hidden`, `month`, `number`, `password`, `range`, `search`, `tel`, `text`, `time`, `url`, or `week`.

**Comment by squidfunk** [comment]
Thanks for the FYI - you're absolutely correct. Is there some other option with the same effect? The bug is quite annoying so unless there's a workaround I think it's the best solution.
