### ISSUE TITLE
Trailing whitespaces should be stripped in code block content copied via copy button

### ISSUE THREAD

**Issue by sisp** [squidfunk/mkdocs-material#7368]
### Bug description

When clicking the "copy" button in a code block whose content has trailing whitespaces (e.g. when using annotations), then trailing whitespaces are preserved in all lines except the last one. I think trailing whitespaces in all lines should be stripped.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Code copy button](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button)

### Reproduction

[9.5.29-code-blocks-annotations-copy-trailing-whitespaces.zip](https://github.com/user-attachments/files/16246827/9.5.29-code-blocks-annotations-copy-trailing-whitespaces.zip)

### Steps to reproduce

1. Unzip the reproduction.
2. Run `mkdocs serve`.
3. Open the site in your browser.
4. Click on the "copy" button of the code block and paste the clipboard content in a text editor.
5. Observe that the trailing whitespaces of the first line are preserved.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. I'm afraid we can't introduce this change. The reason is that there are some languages for which trailing whitespace is relevant, e.g. Markdown ([two spaces at the end of a line indicate a line break](https://www.markdownguide.org/basic-syntax/#line-break-best-practices)) or whitespace (yes, it's esoteric, but you get the gist). Whitespace handling, especially in code blocks, should be left to the environment that you use, e.g. VS Code. We want to support all languages, thus we must be conservative.

Closing as out of scope.

**Comment by sisp** [comment]
OMG, I didn't know about two spaces linebreaks in Markdown. :see_no_evil: Thanks for having such esoterism on your radar! :ok_hand:

**Comment by squidfunk** [comment]
Two-space linebreaks are not that esoteric, [Whitespace](https://en.wikipedia.org/wiki/Whitespace_(programming_language)) is 🤟
