### ISSUE TITLE
Missing information in Basic social cards

### ISSUE THREAD

**Issue by WHFF521** [squidfunk/mkdocs-material#7372]
### Description

the tutorial let me just add `- social` plugins, but when create new mkdocs, the `mkdocs.yml` doesn't have theme settings. So just add `- social` can not run the project.   
<img width="691" alt="Screenshot 2024-07-17 at 15 29 57" src="https://github.com/user-attachments/assets/62c09d1e-2572-4ad9-8854-6913149fcabf">

When run `mkdocs serve`, it will report an error : `ERROR   -  Config value 'plugins': The "social" plugin is not installed`.   
So the tutorial page should add theme settings first.   
Like the tutorial of `Basic blogs`, [Basic social cards](https://squidfunk.github.io/mkdocs-material/tutorials/social/basic/#basic-social-cards) should give a full yml file. 
<img width="691" alt="Screenshot 2024-07-17 at 15 37 24" src="https://github.com/user-attachments/assets/1bf00bc4-2485-4e0e-850e-353f7f1f2b22">

### Related links

- [Basic social cards](https://squidfunk.github.io/mkdocs-material/tutorials/social/basic/)
- [related discussions](https://github.com/squidfunk/mkdocs-material/discussions/5639)

### Proposed change

It is recommended that the first code space like:
```
    plugins:
        - search
        - social
        - ...
```
change to :
```
theme:
    name: material
plugins:
  - search
  - social
```

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by alexvoss** [comment]
Thanks for reporting. The tutorial overview page mentions that working through the [Creating your site](https://squidfunk.github.io/mkdocs-material/creating-your-site/) guide is a prerequisite for the tutorial. 

I am not sure what I would want to replicate the information contained there but I would imagine adding a note at the top of this tutorial that replicates the mention of prerequisites. Do you think that would address the issue?

**Comment by squidfunk** [comment]
@alexvoss is correct. Setting `material` as a theme is a prerequisite for everything else.

**Comment by WHFF521** [comment]
Sorry I didn't see the requirements in the tutorial overview page before.  Adding a note at the top of this tutorial may be better.

**Comment by alexvoss** [comment]
Thanks for the feedback. I think a brief note at the top of each tutorial to read the overview page and pay attention to the prerequisites in particular would be good. Every page is the first page, after all. Will see if that can be single-sourced keep the maintenance effort in check.

**Comment by squidfunk** [comment]
By that logic we would need to add a note to each and every page in our documentation saying that you should the getting started guide first. I'm not a fan of this solution. Yes, I understand that there has been a misunderstanding, but we should rather solve it through wording and maybe a more apparent navigation structure than with more call outs.

**Comment by alexvoss** [comment]
I think that the tutorials are a special case as they are specifically aimed at people who are starting out. I would have added an admonition to the basic tutorial only as the other parts are meant to build on that. 

One "problem" is that we added the tutorials to the main navigation, so people may not see the overview page. Removing the entries for the concrete tutorials from the main navigation may alleviate the problem and we already decided to do that eventually, once we have a larger number of tutorials. I would be happy with that approach.

What I would definitely want to do now that I am looking at it again is to  add a heading "Prerequisites" to the overview page and move the "Feedback wanted" box out of the way. Does that sound sensible?

**Comment by squidfunk** [comment]
Yes, the problem might be that the tutorials are currently islands. Okay, so feel free to adjust them to fit, but let's take this feedback back with us to the drawing board when working on the new information architecture.

**Comment by alexvoss** [comment]
One thought I had was that a notification might be an idea - one that people can click away. The notifications at the top are for the whole site, right? It would need to be page-specific and should be configurable through the metadata (so we avoid scanning the content for placeholders). Just a thought.

**Comment by squidfunk** [comment]
Yes, the [announcement bar](https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#announcement-bar) is meant to be shown on the entire site and we currently have no bandwidth to implement a per-site announcement, but it might be a nice component for the future when we find some time ☺️
