### ISSUE TITLE
404 page title not rendering, cannot analyse in Analytics for this reason

### ISSUE THREAD

**Issue by kmurphypolygon** [squidfunk/mkdocs-material#7375]
### Context

I'm managing the backend of our fairly new site: https://docs.polygon.technology/

Content migrated hastily from Docusaurus over 6 months ago: https://wiki.polygon.technology

Redirects not done correctly, lots of errors in analytics, many 100s of 404s being reported. 

I'm slowly getting to the bottom of this... one thing has come up related to the platform... see below

### Bug description

We've had some issues setting up Google Analytics properly on our site: https://docs.polygon.technology/ after migrating from a previous platform. However, things are improving. 

One thing that I'm still struggling with is analysing 404 pages with Google Analytics. GA picks up page by `<page title>` which is visible if you hover over the tab on your browser.

See: https://docs.polygon.technology/tools/gas/matic-faucet/ where the `<page title>` is correctly given as **Polygon faucet - Polygon Knowledge Layer.**

However, 404 pages do not have a title, so if they are being picked up by GA, they are getting lumped in with the main site title and any other pages which may not have a title.

See: https://docs.polygon.technology/innovation-design/my404 where the `<page title>` is given as **Polygon Knowledge Layer**.

I suspect we still have 100s of 404s from the migration and lack of redirecting that are still getting accessed, but I can't know for sure.

Is there any way I can set a <page title> for 404s please so that I can analyse the 404s in GA correctly?

Many thanks.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

I have checked through docs, issues, and discussions, but I don't find anything related to this.

### Reproduction

[9.5.29-404s-not-in-ga.zip](https://github.com/user-attachments/files/16279339/9.5.29-404s-not-in-ga.zip)

### Steps to reproduce

1. Run `mkdocs serve`
2. Click through to http://127.0.0.1:8000/cdk/concepts/layer2s/
3. Hover over browser tab to see title: **Layer 2s - My Docs**
4. Now generate a 404 page, e.g. go to: **http://127.0.0.1:8000/cdk/concepts/architecture/my404**
5. Hover over browser tab to see title: **My Docs**
6. No 404 reported so cannot analyse these in GA.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks or reporting. We could change the title to something like `{{ config.site_name }} – Not found`, but that's essentially a matter of taste – some users would like it, some don't. However, it is quite easy to achieve via [theme extension](https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme), so you could just provide your own [`404.html`](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/404.html) as a custom template:

``` html
{% extends "main.html" %}

{% block content %}
  <h1>404 - Not found</h1>
{% endblock %}

{% block htmltitle %}
   <title>{{ config.site_name }} - Not found</title>
{% endblock %}
```

Thus, we're considering this as resolved via customization ☺️

**Comment by kmurphypolygon** [comment]
OK, perfect, thank you so much <3
