### ISSUE TITLE
navigation.tabs.sticky always renders shadow below bar

### ISSUE THREAD

**Issue by imwints** [squidfunk/mkdocs-material#7398]
### Description

When sticky tabs are set, there is always a shadow below the toolbar, even when scrolled completely to the top. When sticky tabs are not activated, the shadow properly disappears when scrolled to the top.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://github.com/squidfunk/mkdocs-material/issues/2488
- https://github.com/squidfunk/mkdocs-material/pull/2494

### Use Cases

I think it's just consistent with the rest of the material design and the non-sticky tabs behavior.

### Visuals

**Sticky tabs**
![Screenshot_20240725_142544](https://github.com/user-attachments/assets/9870774d-9348-483a-97e1-84e05b9ce284)

**Without**
![Screenshot_20240725_142628](https://github.com/user-attachments/assets/b977468a-6df5-4290-941e-6a043483b4d7)

### Configuration

```yaml
site_name: My Docs
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Home: index.md
  - Tab:
      - Page: page.md
```

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. This is essentially a matter of taste. The reason why the sticky tabs are always rendering a shadow is to visually note that the entire block floats above the content area. This is in-line with Material Design specification. You can, however, remove the shadow with a few lines of CSS. If you need help with that, feel free to ask on discussions! ☺️

**Comment by Goozoon** [comment]
Sorry for reopening. 
All latest here.

if I put `- navigation.tabs` there is now shadow under the top blue part.
Shadow appears when I scroll the page, and top part shrinks. How to make it to display shadow always? please

if I put `- navigation.tabs` I always see narrow top part and shadow always (which is good)
