### ISSUE TITLE
Missing equation fonts when using mkdocs-material privacy plugin in combination with MathJax

### ISSUE THREAD

**Issue by vicmteam** [squidfunk/mkdocs-material#7399]
### Context

When I use mkdocs-material privacy ( https://squidfunk.github.io/mkdocs-material/plugins/privacy/ ) in combination with MathJax ( https://squidfunk.github.io/mkdocs-material/reference/math/?h=math#mathjax ), the equation fonts are missing in the final docu, which produces equations being rendered in ugly fallback fonts:

Good: MathJax only:

![image001](https://github.com/user-attachments/assets/ca849c50-f046-4a15-800c-6ac2dbb900fb)

Bad: MathJax + Privacy Plugin:

![image002](https://github.com/user-attachments/assets/a20e607b-2588-4f26-a215-33e94b6f135e)

### Bug description

Serving gives a hint at what is amiss:

<details>
<summary>Serving log</summary>

```log
INFO    -  [11:07:16] Serving on http://127.0.0.1:8000/
WARNING -  [11:07:17] "GET /assets/external/unpkg.com/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Zero.woff HTTP/1.1" code 404
WARNING -  [11:07:17] "GET /assets/external/unpkg.com/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Zero.woff HTTP/1.1" code 404
WARNING -  [11:07:17] "GET /assets/external/unpkg.com/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff HTTP/1.1" code 404
WARNING -  [11:07:17] "GET /assets/external/unpkg.com/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Math-Italic.woff HTTP/1.1" code 404
WARNING -  [11:07:17] "GET /assets/external/unpkg.com/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Vector-Regular.woff HTTP/1.1" code 404
```
</details>
 
I could fix the issue locally by explicitly specifying the missing files as `extra_javascript` in mkdocs config file:

```yaml
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Zero.woff
  - https://unpkg.com/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Main-Regular.woff
  - https://unpkg.com/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Math-Italic.woff
  - https://unpkg.com/mathjax@3/es5/output/chtml/fonts/woff-v2/MathJax_Vector-Regular.woff
```

I am wondering if this can be fixed in mkdocs-material internal code or by extending the documentation at https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax ?

Example for debugging is attached.

### Related links

- [Math documentation](https://squidfunk.github.io/mkdocs-material/reference/math/)
- https://github.com/squidfunk/mkdocs-material/issues/6747
- https://github.com/squidfunk/mkdocs-material/issues/152

### Reproduction

[9.5.30+insiders.4.53.11-privacy-missing-mathjax-fonts.zip](https://github.com/user-attachments/files/16378760/9.5.30%2Binsiders.4.53.11-privacy-missing-mathjax-fonts.zip)

### Steps to reproduce

1. run `mkdocs serve`
2. open the documentation in any browser
3. 404 messages will appear in the log, the rendered math doesn't look nice

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting! [As mentioned in our documentation](https://squidfunk.github.io/mkdocs-material/plugins/privacy/#__code_16_annotation_1), MathJax and Giscus cannot be automatically downloaded by the privacy plugin because of how those libraries are designed. Thus, there's no way to do this automatically 😕
