### ISSUE TITLE
Theme credits have weak contrast in footer

### ISSUE THREAD

**Issue by digitalcraftsman** [squidfunk/mkdocs-material#74]
## Description

The links in the theme credits are (barely) visible in the footer but the regular text is hard to spot while browsing the documentation.

![mkdocs](https://cloud.githubusercontent.com/assets/7010165/21485007/68e89140-cb9c-11e6-9afd-e6cfa4e22f84.png)

**Comment by squidfunk** [comment]
The reason behind that is that I wanted to make the "powered by" as unobtrusive as possible. What you mean with "the regular text is hard to spot while browsing the documentation"?

**Comment by digitalcraftsman** [comment]
> What do you mean with "the regular text is hard to spot while browsing the documentation"?

A few minutes ago I had a look at the recent additions you've made to this theme (which are awesome btw) and saw the copyright notice only because the MkDocs and Material link stood out slightly due to their brighter color.

Would the copyright notice only consist of regular text ("powered by ... and the ... theme") I might not have seen it because the contrast to the background is so low.

> The reason behind that is that I wanted to make the "powered by" as unobtrusive as possible.

I understand your reasons for this design descision and sometimes it can be hard to find a balance between visibility and obtrusiveness for all users.

**Comment by squidfunk** [comment]
Thanks for the clarification. The most important thing is the copyright notice. The notice on the theme when browsing the documentation is very secondary to say the least, so I will stick with this for the moment. Beta 2 is out, let's see what people say.

**Comment by squidfunk** [comment]
Fixed in 5ee95e4fe228fb7de7e5c4b82df33dbd6ba8b338, will be pushed into release candidate - closing this issue.
