### ISSUE TITLE
DockerHub missing images after 9.5.27

### ISSUE THREAD

**Issue by perios101** [squidfunk/mkdocs-material#7405]
### Bug description

[DockerHub repository](https://hub.docker.com/r/squidfunk/mkdocs-material) is missing images for releases past 9.5.27 version.

### Related links

- [Available DockerHub repo image tags](https://hub.docker.com/r/squidfunk/mkdocs-material/tags)

### Reproduction

Check DockerHub repo for recent tags - last one is 9.5.27 from 16th June 2024.

Missing images for versions 9.5.28, 9.5.29, 9.5.30

### Steps to reproduce

1. Check DockerHub repo for recent tags.
2. Alternatively - run `docker pull squidfunk/mkdocs-material:latest` and check for SHA against the available tags.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Already reported in #7396 and fixed in https://github.com/squidfunk/mkdocs-material/commit/627eb88b3db88a6443d0972873756dd207fcb1dd. Next release will be on Docker again.

**Comment by squidfunk** [comment]
Released as part of [9.5.31](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.31) – [image is up again](https://hub.docker.com/layers/squidfunk/mkdocs-material/9.5.31/images/sha256-5e29c1457f154c37af5068d35d8d8e4530a3c490092d7ddd27c978e1ad9c4aec?context=explore) ☺️
