### ISSUE TITLE
Instant preview disables content tabs using readable anchor links

### ISSUE THREAD

**Issue by lampensau** [squidfunk/mkdocs-material#7410]
### Bug description

Please refer to #7408 for more context and a detailed description of the _effects_.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- #7408

### Reproduction

[9.5.30+insiders.4.53.11-instant-preview-disables-tabs2.zip](https://github.com/user-attachments/files/16455033/9.5.30%2Binsiders.4.53.11-instant-preview-disables-tabs2.zip)

### Steps to reproduce

1. Install and enable material insiders theme
2. Enable and [configure](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#configuration) the Markdown extensions `pymdownx.superfences`, and `pymdownx.tabbed` using the [readable anchor links](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#anchor-links)
3. Use the [instant preview feature](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-previews) to a document heading containing one or multiple content tabs. Content tabs only get disabled if the instant preview tooltip includes them.

### Browser

Chrome, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in [`b53ae7b9b`](https://github.com/squidfunk/mkdocs-material-insiders/commit/b53ae7b9b00f88fbbe43330ee19783129b538d72).

**Comment by lampensau** [comment]
Fixed it for me. Thanks a bunch!
