### ISSUE TITLE
Table of Contents showing section title

### ISSUE THREAD

**Issue by JavierEscobarOrtiz** [squidfunk/mkdocs-material#7411]
### Bug description

Hello,

We are using `mkdocs-material` for the [skforecast documentation](https://skforecast.org/0.13.0/index.html). We have just deployed a new release and noticed that the first entry in the left table of contents shows "API Reference" instead of "ForecasterAutoreg". This didn't happen in our previous release (around May 2024). This also happens in the "User Guide" section.

New version `mkdocs-material==9.5.30`:

![imagen](https://github.com/user-attachments/assets/459107a5-1147-410e-9565-23d1e07731d6)

Old Version `mkdocs-material==9.1.15`:

![imagen](https://github.com/user-attachments/assets/ffaeaaca-473c-47db-8e2a-0ed6bea61a6d)

In the **Related links** section I include links to mkdocs.yml, docs requirements, and the ForecasterAuroeg API file.

If you need more information, don't hesitate to ask. 😄 

Thanks,

Javi

### Related links

- [mkdocs.yml](https://github.com/JoaquinAmatRodrigo/skforecast/blob/0.13.x/mkdocs.yml)
- [docs requirements](https://github.com/JoaquinAmatRodrigo/skforecast/blob/0.13.x/pyproject.toml), `docs` section in toml file.
- [ForecasterAutoreg API file](https://github.com/JoaquinAmatRodrigo/skforecast/blob/0.13.x/docs/api/ForecasterAutoreg.md)

### Reproduction

NA

### Steps to reproduce

NA

### Browser

Chrome, Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Material for MkDocs ships MkDocs 1.6.0, so I'm confident this is a problem with MkDocs, as already reported in https://github.com/mkdocs/mkdocs/issues/3710. Since there's no reproduction, we can't check it, but you can verify by switching to the `mkdocs` or `readthedocs` theme. If the issue is gone then, please provide a minimal reproduction that showcases it. Until then, we'll consider this as an upstream bug.

**Comment by JavierEscobarOrtiz** [comment]
Thanks for your input @squidfunk 

As you mentioned, switching to the other themes solves the problem. For now, we will take the same solution as the comment you attached, and downgrade mkdocs to `1.5..3`.

**Comment by Sreekala-Gopakumar** [comment]
@squidfunk - Has this been fixed or do we have to continue with the downgraded mkdocs?

**Comment by squidfunk** [comment]
I'm not sure, since the upstream issue has not been resolved. Maybe ask the maintainers of MkDocs? Related:

- https://github.com/mkdocs/mkdocs/issues/3532
- https://github.com/mkdocs/mkdocs/issues/3710
