### ISSUE TITLE
Fetch and show the latest version of a project hosted on GitLab

### ISSUE THREAD

**Issue by joaopalmeiro** [squidfunk/mkdocs-material#7417]
### Context

Hi! 👋 

I'm documenting a Python package hosted on GitLab and, similar to a project hosted on GitHub, I would like to include the latest released version along with the rest of the repo information (e.g., stars) next to the search bar/as part of the main navigation drawer.

### Description

Similar to GitHub, GitLab also has an [API endpoint](https://docs.gitlab.com/ee/api/releases/#get-the-latest-release) to obtain information about the latest release. Thus, the following snippet 

https://github.com/squidfunk/mkdocs-material/blob/a5438a6dc23396023bbe9d73592fccd562ee4174/src/templates/assets/javascripts/components/source/facts/gitlab/index.ts#L48-L61

could be adapted based on the GitHub one,

https://github.com/squidfunk/mkdocs-material/blob/a5438a6dc23396023bbe9d73592fccd562ee4174/src/templates/assets/javascripts/components/source/facts/github/index.ts#L60-L75

in order to obtain the desired information.

You can see an example response using the following command (the relevant field is the `tag_name` one):

```bash
curl -L "https://gitlab.com/api/v4/projects/joaommpalmeiro%2Fgaveta/releases/permalink/latest"
```

The [list releases](https://docs.gitlab.com/ee/api/releases/#list-releases) API endpoint can also be used for this purpose.

Let me know what you think and if I can open a PR. Thanks!

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository
- https://docs.gitlab.com/ee/api/releases/#get-the-latest-release

### Use Cases

Projects hosted on GitLab will also be able to show the latest version information. Additionally, repository information will become consistent, as we will be able to get the same information for GitHub and GitLab.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! I'm not a user of GitLab, PR appreciated ☺️ You can follow the implementation of GitHub and adapt it to GitLab, shouldn't be that hard. If you need help, let me know.

**Comment by joaopalmeiro** [comment]
Thanks, @squidfunk! I'll work on it.
