### ISSUE TITLE
Interactive Examples

### ISSUE THREAD

**Issue by DanielHabenicht** [squidfunk/mkdocs-material#7419]
### Context

I learned about [webcontainers](webcontainers) and wanted to integrate them into my existing mkdocs documentation to provide users with interactive examples, which can be changed by them. 
Unfortunately, there are no extensions for it yet.
But I also saw [PyScript](https://pyscript.net/) which does the same for Python. 

### Description

Make the Documentation more interactive, e.g.: 

- CLI commands, executable right away (e.g. by adding a switch)
   `````md
   ```bash interactive=environment1
   custom-cli init
   ```
   `````
- Configuration Samples could include a live updating instance on the same page right next to it: 
   `````md
   ```typescript interactive=environment1 filepath=/workspace/config.ts
   export const config = {
     option1: "test",
   }
   ```
   `````
- Or one could embed or link to an extra component (or page) where interactive examples (or tutorials) could be added. 
   `````md
   ```python interactive=environment1 example=https://github.com/repository/example/path/to/mounted/folder
   def coolFunction():
      pass
   ```
   `````

For now this would probably be limited to node and python examples, but I am sure more web assembly versions of languages will follow.

### Related links

- [Webcontainers](https://webcontainers.io/)
- [Interactive Guide](https://webcontainer-tutorial.pages.dev/)
- [Example: Angular Documentation Playground](https://angular.dev/tutorials/learn-angular)
- [Interactive CLI](https://webcontainers.io/community-projects/schachnovelle)
- Also saw [SQLime](https://github.com/nalgeon/sqlime) for interactive SQLite queries

### Use Cases

As the Documentation Author, I can more easily create hands-on examples of how to work with what I am documenting. 

As a user I don't need to install something locally to give it a try, there are fewer barriers. 

### Visuals

Extra Button for opening the example interactively (but not in the 3rd party service but on your own docs site): 
![image](https://github.com/user-attachments/assets/f7b49e11-c84e-423e-aa95-0affbdf097c9)
Or even better if the output would be side-by-side with the example. 

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for the suggestion! There are already some solutions like Markdown Exec (tagging @pawamoy for visibility) – maybe it's worth exploring them ☺️ This, currently, goes beyond the scope of Material for MkDocs, as we're focusing on the rendered output, and interactivity is left to third-party integrations, but we may reconsider in the future.

Moving this into discussions for further input by other users.

**Comment by pawamoy** [comment]
We do support interactive Python code blocks, thanks to Pyodide. Definitely open to adding support for more languages 🙂
