### ISSUE TITLE
Custom style per page?

### ISSUE THREAD

**Issue by spetreanu** [squidfunk/mkdocs-material#743]
## Description

I would like to change the h4 style on 2 pages while keeping it unchanged on the rest of the pages. It will be nice to add a custom class on body or html, only for these 2 pages. Is this possible?

What is the recommended method to target only a specific page?

Thanks,
Sebastian

**Comment by squidfunk** [comment]
It's not possible at the moment. Maybe you can hack something together with custom metadata extending the theme but MkDocs doesn't support it out of the box. However, to set it you could add JavaScript to the specific Markdown rendering the page and set the class through JavaScript.

**Comment by spetreanu** [comment]
Will do this. Thanks!
