### ISSUE TITLE
Links to versioning examples are outdated

### ISSUE THREAD

**Issue by zsrv** [squidfunk/mkdocs-material#7432]
### Description

There are two links on the _Setting up versioning_ page that point to an example site that uses versioning. These links point to https://squidfunk.github.io/mkdocs-material-example-versioning, which returns a "site not found" error.

### Related links

- [Setting up versioning](https://github.com/squidfunk/mkdocs-material/blob/master/docs/setup/setting-up-versioning.md?plain=1)

### Proposed change

Change both links to point to https://mkdocs-material.github.io/example-versioning, which appears to be the new/correct link.

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for reporting! We moved the example versioning guide to https://github.com/mkdocs-material/example-versioning. We need to redeploy the examples. I'll do that when I find some time.

**Comment by squidfunk** [comment]
I've adjusted all links in 909b2a6af6692afe7bd8c0d6eaf83970981fe109 and re-deployed the versioning example with the latest version (9.5.35):
https://mkdocs-material.github.io/example-versioning/
