### ISSUE TITLE
Social Plugin : external link not supported in theme.logo

### ISSUE THREAD

**Issue by yves-chevallier** [squidfunk/mkdocs-material#7444]
### Context

It seems the `social` plugin does not support external image for the `theme.logo`. 

### Bug description

I recently enabled `social` plugin, my `theme.logo` value is an external link `https://....svg`. It works well until I enable this plugin. Now I get the warning: 

    Couldn't find image '/home/user/project/docs/https://....svg'

### Related links

In [logo](https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/?h=logo#logo) it is not specified if the value can be an external link, but it seems to work correctly until I use the `social` plugin. 

In [Social/logo](https://squidfunk.github.io/mkdocs-material/tutorials/social/basic/?h=logo#logos) I can read it uses the `theme.logo` setting which it does, but it considers it is a local link.

## Create a new project 

```yaml
site_name: Bug
theme:
  name: material
  logo: https://static.wikia.nocookie.net/warner-bros-entertainment/images/6/6e/Acme-corp.png
plugins:
  - social:
      enabled: !ENV [SOCIAL, false]
```

## Run without social

```bash
➜ poetry run mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  Documentation built in 0.14 seconds
INFO    -  [14:40:27] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO    -  [14:40:27] Serving on http://127.0.0.1:8000/
INFO    -  [14:40:30] Browser connected: http://127.0.0.1:8000/
```

And you get your doc with the logo:

![image](https://github.com/user-attachments/assets/708a0bee-85d3-4fa4-8fa1-f9e76098d111)

## Run with social

```bash
➜ SOCIAL=true poetry run mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
Traceback (most recent call last):
  
  File "/home/user/.cache/pypoetry/virtualenvs/demo-3CadAguV-py3.12/lib/python3.12/site-packages/material/plugins/social/plugin.py", line 383, in _load_resized_logo
    logo = self._load_logo(config)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/demo-3CadAguV-py3.12/lib/python3.12/site-packages/material/plugins/social/plugin.py", line 408, in _load_logo
    return Image.open(path).convert("RGBA")
           ^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/demo-3CadAguV-py3.12/lib/python3.12/site-packages/PIL/Image.py", line 3431, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/demo/docs/https:/static.wikia.nocookie.net/warner-bros-entertainment/images/6/6e/Acme-corp.png'
```

### Steps to reproduce

See steps above.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. That's correct, exterternal images are not supported, since the plugin would need to download those images to insert them into the social card. We're currently not considering this change due to its added complexity, so the easiest thing is to just download the image and put it in your repository for the social plugin to discover it.

I hope for your understanding. We might re-evaluate this feature request in the future.

**Comment by yves-chevallier** [comment]
I am ok with that, but I would appreciate a notice in the documentation about this limitation of the social plugin.
