### ISSUE TITLE
Support for GitHub flavoured Alerts

### ISSUE THREAD

**Issue by ZhiyuanChen** [squidfunk/mkdocs-material#7445]
### Context

GitHub introduces [Alert](https://github.com/orgs/community/discussions/16925) syntax to highlight certain texts, similar to [Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)

### Description

Recognise the Alerts pattern as Admonitions. 

### Related links

- [GitHub Alert](https://github.com/orgs/community/discussions/16925)
- [MkDocs Admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/)

### Use Cases

My project uses the same README file in three spaces, GitHub, document site (build by MkDocs), and Huggingface hub (by huggingface). 
Hence, it's best to have the same syntax that can be recognised by all three places. 

### Visuals

As GitHub and Huggingface hub does not support many markdown extensions, the admonition syntax will look like this

![image](https://github.com/user-attachments/assets/46fa434f-7f4b-4524-9a3d-8f6b3fb95c7b)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by facelessuser** [comment]
Please search the issues as this has been discussed a couple of times. Relevant discussion below:

- https://github.com/squidfunk/mkdocs-material/issues/6667
- https://github.com/squidfunk/mkdocs-material/discussions/7035
