### ISSUE TITLE
Two Identical Annotations do not work

### ISSUE THREAD

**Issue by ibrahimaljalal** [squidfunk/mkdocs-material#7463]
### Bug description

In the code below:

```
annotation 1 (1) second annotation 2 (2) first annotation 3 (same as one) (1)
{ .annotate }

1. text in first annotation
2. text in second annotation

```

The annotation after "annotation 1" will not open. If we remove one of the annotations with number one "(1)". The issue will go.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[annotation issue.zip](https://github.com/user-attachments/files/16660775/annotation.issue.zip)

### Steps to reproduce

1. install the mkdocs and material theme
2. in terminal write: python -m mkdocs new .
3. Write in the mkdocs.yml file:
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences

4. Write in the docs/index.md file:
annotation 1 (1) second annotation 2 (2) first annotation 3 (same as one) (1)
{ .annotate }

1. text in first annotation
2. text in second annotation

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. This is a known limitation. You need to copy the list item and uniquely reference annotations. It's not easy to fix, because annotations can contain _anything_, including interactive elements that we can't just clone, which we'd need to do if we'd support it. We may re-evaluate this in the future, but for now it is not supported.
