### ISSUE TITLE
ERROR   -  Config value 'plugins': The "minify" plugin is not installed

### ISSUE THREAD

**Issue by kuhlaid** [squidfunk/mkdocs-material#7484]
### Bug description

I forked the latest version mkdocs-material-9.5.33 and tried to get it pushed to GitHub Pages. After creating a workflow action in GitHub as outlined in https://squidfunk.github.io/mkdocs-material/publishing-your-site/ the action failed with `ERROR   -  Config value 'plugins': The "minify" plugin is not installed`. I have not altered the code nor performed any other actions outside of GitHub.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

NA

### Steps to reproduce

1. Fork the latest version mkdocs-material-9.5.33
2. Create a workflow action in GitHub as outlined in https://squidfunk.github.io/mkdocs-material/publishing-your-site/
3. Action fails with `ERROR   -  Config value 'plugins': The "minify" plugin is not installed`.

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Moving to discussions, as this is clearly a support request.
