### ISSUE TITLE
Code copy button: Clarify usage of `.copy` and `.no-copy` tags

### ISSUE THREAD

**Issue by thorstenpeter-sophos** [squidfunk/mkdocs-material#7541]
### Description

In the documentation section about enabling or disabling the code copy button for a specific code block, it's not clear that the `.copy` and `.no-copy` tags only work if there's also a language shortcode. The current wording "Note that the language shortcode which has to come first must now also be prefixed by a `.`" can easily be misunderstood as "If there's a language shortcode, it must come first."

I did enable the copy button globally with the `content.code.copy` theme setting and then expected to be able to disable it for a specific code block with `{ .no-copy }`, which isn't the case. I first assumed there was a bug in the feature, and only realized the actual cause after some testing.

Although I haven't tested it, I assume the same issue applies to the code selection button.

### Related links

- See the note "Enabling or disabling code copy buttons for a specific code block" in [Code copy button](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button)
- and a similar note in [Code selection button](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-selection-button).

![image](https://github.com/user-attachments/assets/a45f2c3f-92f7-49c4-813d-742a631284c7)

### Proposed change

You could improve the section as follows. This also mentions the workaround of using the "Null" `.text` language specifier.

`````
Note that there must be a language shortcode, which has to come first and must also be prefixed by a `.`. Similarly, the copy button can also be disabled for a specific code block:

    ```` { .yaml .no-copy }
    ``` { .yaml .no-copy }
    # Code block content
    ```
    ````
To enable or disable the copy button without syntax highlighting, you can use the `.text` language shortcode, which doesn't highlight anything.
`````

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by squidfunk** [comment]
Thanks for noting. Yes, the `no-copy` attribute is an additional attribute that assumes that you're using the attribute lists syntax. Could you PR the changes suggested?

**Comment by squidfunk** [comment]
Adjusted the documentation in 56fdb282d – took your suggestion and tagged you as a co-author.
