### ISSUE TITLE
Feature Request: AI Admonition

### ISSUE THREAD

**Issue by jvanderaa** [squidfunk/mkdocs-material#7547]
### Context

Within Admonitions, it would be nice to have an `AI` admonition which can be used to either quote the usage of AI in generation of content, or to use AI. 

### Description

This would be to give attribution to the use of AI within Blog posts that leverage mkdocs-material. A second use would be around indicating in documentation that AI attribution or to use an AI to get the information.

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
-

### Use Cases

- Provide proper attribution and notify the reader of the content of AI usage
- Provide guidance to leverage AI

I'll likely put my own usage of it using the expandable features of creating your own admonition, but I anticipate that this is something that others may want as well.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting! This is too specific of a use case to justify an increase of the payload by several bytes of our style sheets for each and every user. However, it's easy to add yourself. Please see our section for [custom admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions) ☺️
