### ISSUE TITLE
Relative paths to assets must be used in 404.html

### ISSUE THREAD

**Issue by Sharom** [squidfunk/mkdocs-material#755]
## Description

Absolute paths to assets are used in `404.html`. It breaks rendering of this page when documentation located not at the root of the domain.

### Expected behavior

Relative paths are expected to be used in `404.html` for import of assets as for all other pages.

```html
<link rel="stylesheet" href="./assets/stylesheets/application.8d40d89b.css">
<link rel="stylesheet" href="./assets/stylesheets/application-palette.6079476c.css">
...
```

### Actual behavior

```html
<link rel="stylesheet" href="/assets/stylesheets/application.8d40d89b.css">
<link rel="stylesheet" href="/assets/stylesheets/application-palette.6079476c.css">
...
```

### Package versions

* Python: 2.7.14
* MkDocs: 0.17.3
* Material: 2.7.2

**Comment by Sharom** [comment]
> We don't generate the error page at the time of the request. The same error page needs to be used for requests to `/foo/. /foo/bar/`, and `/foo/bar/baz/`...

You are right, I have overlooked this.

**Comment by Sharom** [comment]
So, it looks like we can close the issue.

**Comment by waylan** [comment]
@Sharom just curious if you were able to resolve the issue by adjusting the value set for the `site_url` config setting?

**Comment by squidfunk** [comment]
Thanks for the thorough explanation @waylan! Closing this as answered.

**Comment by Sharom** [comment]
> @Sharom just curious if you were able to resolve the issue by adjusting the value set for the site_url config setting?

@waylan Yes, it solves the issue.

**Comment by squidfunk** [comment]
Is it really mentioned in the docs or part of the default MkDocs theme?

**Comment by Stanzilla** [comment]
@squidfunk for me the error is coming from main.js when it tries to create a new searchWorker `var searchWorker = new Worker(joinUrl(base_url, "search/worker.js"));`

**Comment by squidfunk** [comment]
I can’t provide support for customizations, sorry

**Comment by Stanzilla** [comment]
Was more of a notice and "if you find this issue via Google, here is what it could be" thing for other people :)

**Comment by jagguli** [comment]
still an issue 

path never gets prepended with `/`

```
    {% block styles %}
      <link rel="stylesheet" href="{{ 'assets/stylesheets/main.fe0cca5b.min.css' | url }}">
      {% if palette.scheme or palette.primary or palette.accent %}
        <link rel="stylesheet" href="{{ 'assets/stylesheets/palette.a46bcfb3.min.css' | url }}">
      {% endif %}
```
