### ISSUE TITLE
Grids - div within div closes outer div

### ISSUE THREAD

**Issue by scottmk** [squidfunk/mkdocs-material#7558]
### Bug description

I'm trying to put a grid within a grid card, because I have a 6-bullet list that I want to be side-by-side.

If I do something like this, it works fine:
```markdown
<div class="grid cards" markdown>

-   __Grid Card One__

    ---

    Test grid 1.

-   __Grid Card Two__

    ---

    Test grid 2.

</div>
```
<img width="965" alt="Screenshot 2024-09-23 at 17 23 09" src="https://github.com/user-attachments/assets/7b12f7b1-a8b4-4eef-b075-6f85917c3fca">

However, if I try to put a grid within that first card, the outer `grid cards` div is closed, and the second card is no longer rendered properly:

```markdown

<div class="grid cards" markdown>

-   __Grid Card One__

    ---

    <div class="grid" markdown>
    <ul>
      <li> Item 1 </li>
      <li> Item 2 </li>
      <li> Item 3 </li>
    </ul>
    <ul>
      <li> Item 4 </li>
      <li> Item 5 </li>
      <li> Item 6 </li>
    </ul>
    </div>

-   __Grid Card Two__

    ---

    Test grid 2.

</div>
```
<img width="992" alt="Screenshot 2024-09-23 at 17 24 32" src="https://github.com/user-attachments/assets/cd07d038-c427-4350-b18e-2fc67158d59f">

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Grids](https://squidfunk.github.io/mkdocs-material/reference/grids/)

### Reproduction

[9.5.36-grid-within-grid.zip](https://github.com/user-attachments/files/17106286/9.5.36-grid-within-grid.zip)

### Steps to reproduce

1. Setup the minimal reproduction
2. Build
3. View the output

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Unfortunately, this is a limitation of how grids work – you currently cannot put grids inside grids, as its a limitation of browsers. [Subgrid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_grid_layout/Subgrid) to the rescue, but if we would adopt that, we would effectively abandon a lot of browsers we currently support. However, as it's purely CSS, you can of course achieve this with some [additional CSS](https://squidfunk.github.io/mkdocs-material/customization/#additional-css) ☺️

Closing as resolved via customization.
