### ISSUE TITLE
json schema should allow unknown community plugins

### ISSUE THREAD

**Issue by DetachHead** [squidfunk/mkdocs-material#7563]
### Description

currently i get an error in the json schema when i try to use the [gitlab plugin](https://pypi.org/project/mkdocs-gitlab/):
```yaml
plugins:
  - gitlab
```

```
Value is not accepted. Valid values: "blog", "info", "meta", "offline", "optimize", "privacy", "projects", "search", "social", "tags", "typeset", "git-authors", "git-committers", "git-revision-date", "literate-nav", "macros", "section-index", "include-markdown", "material-relative-language-selector", "rss", "git-revision-date-localized", "glightbox", "meta-descriptions", "mkdocstrings", "coverage", "spellcheck", "markdown-exec", "table-reader", "mkdocs-addresses"
```

it doesn't seem feasible to maintain a list of every valid plugin, so i think it should just allow unknown values.

### Related links

- https://pypi.org/project/mkdocs-gitlab/

### Use Cases

using new or unpopular plugins

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
However, you can add you external schema here and send a PR:

https://github.com/squidfunk/mkdocs-material/blob/fd984136badbc6ca708c1a3528fcfb15364ee7f0/docs/schema/plugins.json#L95-L110
