### ISSUE TITLE
`typeset` plugin and `toc` anchorlinks lead to invisible entries

### ISSUE THREAD

**Issue by charliermarsh** [squidfunk/mkdocs-material#7567]
### Bug description

With `typeset` enabled:

![Screenshot 2024-09-26 at 12 49 30 PM](https://github.com/user-attachments/assets/46d96263-f75d-4bc9-ad54-c2b95efa187b)

Without:

![Screenshot 2024-09-26 at 12 49 44 PM](https://github.com/user-attachments/assets/a42b89f1-adec-4ac0-8858-8bbd2052666a)

### Related links

https://squidfunk.github.io/mkdocs-material/plugins/typeset/

### Reproduction

[mkdocs-repro.zip](https://github.com/user-attachments/files/17152747/mkdocs-repro.zip)

### Steps to reproduce

1. `mkdocs serve`
2. View missing table of contents

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Released as part of [9.5.39+insiders-4.53.14](https://squidfunk.github.io/mkdocs-material/insiders/changelog/#4.53.14).
