### ISSUE TITLE
Listing Issue (Number lists)

### ISSUE THREAD

**Issue by Skrillx13** [squidfunk/mkdocs-material#7568]
### Context

I was using MKDocs, and making a number list. Unsure if this is a Markdown issue or Material MKDocs issue though, but it seems to be on the MKDocs side.

### Bug description

When making said number list, I inserted a code block in between the list, so it looks something like this:
1. Step 1
2. Step 2
```
Code Block I inserted
```
3. Step 3

However, instead of rendering like the step above, it rendered like this:

1. Step 1
2. Step 2
```
Code Block I inserted
```
1. Step 3

As you can see, the order breaks, and it defaults back to 1 when a code block is inserted through it.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [GitHub Repo](https://github.com/Skrillx13/Alternate-Guides)

### Reproduction

[9.5.38-zip.zip](https://github.com/user-attachments/files/17160624/9.5.38-zip.zip)

### Steps to reproduce

1. I created a GitHub Repo and cloned it using a SSH Key
2. Set up a Python Virtual Enviroment
```
python -m venv venv
source venv/bin/activate
```
3. Installed Material for MKDocs, and opened it up in VSC
```
pip install mkdocs-material
code .
```
4.  Ran `mkdocs new .`, and `mkdocs serve`, before adding all my configurations.
5. Created a number list as mentioned in the steps above.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. This behavior stems from Python Markdown, not from Material for MkDocs. [Please take this upstream](https://github.com/Python-Markdown/markdown/issues).
