### ISSUE TITLE
Context menu of Mathjax renders incorrectly

### ISSUE THREAD

**Issue by Xiaokang2022** [squidfunk/mkdocs-material#7578]
### Context

**OS:** `Windows11 23H2`
**Python:** `3.12.0`
**mkdocs:** `1.6.1`
**mkdocs-material:** `9.5.39`

### Bug description

When using instant loading, the Mathjax's context menu will render correctly until the current page is refreshed, otherwise it will render incorrectly.

![a1eff460693b8dfcd04f1aa2eb19dc74](https://github.com/user-attachments/assets/f004ac3e-5b8f-496f-be25-6e81e2aedced)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=navigation+instant#instant-loading

### Reproduction

[9.5.39-mathjax-renders-incorrectly.zip](https://github.com/user-attachments/files/17214431/9.5.39-mathjax-renders-incorrectly.zip)

### Steps to reproduce

1. Run the website
2. Click on **Mathjax page** on the left sidebar
3. Right-click on a formula and the menu will render incorrectly in the top left corner of the page
4. Refresh the page
5. Right-click on the formula again and the menu will render correctly

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. I'm confident this is an error in MathJax. For integrating with instant navigation, we call `MathJax.typesetPromise` [and friends](https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-docsjavascriptsmathjaxjs) (which [seems to have a lot of open issues](https://github.com/search?q=repo%3Amathjax%2FMathJax+typesetPromise&type=issues)). However, it seems that MathJax does not correctly insert some of the styles that are relevant for the context menu – three `style` definitions are missing:

<img width="286" alt="Bildschirm­foto 2024-10-02 um 15 38 25" src="https://github.com/user-attachments/assets/09b961bc-ef4f-46c7-83fa-43a6a81ca23c">

Those include the styles for the context menu, which are absent after instant navigation occurs:

<img width="1022" alt="Bildschirm­foto 2024-10-02 um 15 38 35" src="https://github.com/user-attachments/assets/7a9ebe81-e84f-49b8-a0a9-9786cd7e1f59">

I recommend taking this upstream to the maintainers of MathJax. We can only use the API of MathJax, not fix its behavior 😅 Closing as upstream issue. If you find a workaround, feel free to share it here!
