### ISSUE TITLE
Social cards are not inheriting the background color

### ISSUE THREAD

**Issue by daelvn** [squidfunk/mkdocs-material#7599]
### Context

I am trying to change the background color of the `social` cards (community edition) to the primary palette color.

### Bug description

The cards generated by the community edition of the `social` plugin always use the default `indigo` color, even when `theme.palette.primary` and `plugins.social.cards_layout_options.background_color` are set to another value (`red` in the case of the reproduction).

The documentation *does not* list `plugins.social.cards_layout_options.background_color` as an Insiders field. [It is mentioned in another issue](https://github.com/squidfunk/mkdocs-material/issues/6929#issuecomment-2005678370) that Hex codes and other CSS values are Insiders-only. According to [the documentation for the default layout](https://squidfunk.github.io/mkdocs-material/plugins/social/#layouts), it automatically inherits `theme.palette.primary`. This does not seem to be true.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [`social` plugin documentation](https://squidfunk.github.io/mkdocs-material/plugins/social)
- [Documentation for the `options.background_color` field](https://squidfunk.github.io/mkdocs-material/plugins/social/#option.background_color)
- [Possibly related color issue](https://github.com/squidfunk/mkdocs-material/issues/6929)
- [Similar default indigo issue](https://github.com/squidfunk/mkdocs-material/discussions/6758), but I do not use an auto toggle.

### Reproduction

[9.5.39-social-cards-not-inheriting-color.zip](https://github.com/user-attachments/files/17283460/9.5.39-social-cards-not-inheriting-color.zip)

### Steps to reproduce

1. Remove the `info` plugin
2. Run `mkdocs build`
3. Inspect `site/assets/images/social`
4. Generated image will have an indigo background color, instead of red

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by daelvn** [comment]
Hi,

I have now read the discussion, and it has fixed the reproduction I sent, but not I could not apply the solution to my project. It seems to not work even deleting `.cache` when `theme.palette.primary` is set to `custom`. I have attached a new reproduction. (I had to manually edit it to remove `venv`, which was not included in the previous reproduction. It would not let me attach it otherwise)

[9.5.39-cards-color-continuation.zip](https://github.com/user-attachments/files/17284857/9.5.39-cards-color-continuation.zip)

I imagine the problem here is that the palette color being custom (not the social card configuration), it would have to be pulled from the CSS, which is arbitrary. The documentation does not mention anything about this not being possible. (It does not even mention that setting arbitrary colors in the configuration is reserved for Insiders!). Maybe it should be explicit?

If this is the case, it leaves me in an awkward position where I can't match the social cards to the documentation's color without signing up for Insiders. Is there a workaround for this? Or do I have to settle for the closest predefined palette color? Thank you still.

**Comment by kamilkrzyskow** [comment]
I haven't run your second example, but the `mkdocs.yml` file in the [9.5.39-cards-color-continuation.zip](https://github.com/user-attachments/files/17284857/9.5.39-cards-color-continuation.zip) doesn't set the `social` plugin settings.

The social plugin first tries to load the `theme.palette.primary` color:
https://github.com/squidfunk/mkdocs-material/blob/25b2107b53877c32b55b1ea7620bd1c4565176fc/material/plugins/social/plugin.py#L146-L149

There is a map of colors:
https://github.com/squidfunk/mkdocs-material/blob/25b2107b53877c32b55b1ea7620bd1c4565176fc/material/plugins/social/plugin.py#L553-L576

But you're using `custom`, therefore you need to set the values manually in the `social` plugin options:
https://github.com/squidfunk/mkdocs-material/blob/25b2107b53877c32b55b1ea7620bd1c4565176fc/material/plugins/social/plugin.py#L151-L156

The values from the initial `theme.palette.primary` parsing act as a fallback to the setting set in the `social` plugin options.

---

> I have now noticed that in the discussion you linked, squidfunk mentioned a possible cache invalidation bug. What's the status on this, or the new social implementation meant to come to the community edition?

squidfunk said:
> [...] the new implementation that will soon be released to the community edition.

_soon_ is a rather subjective term 😅 So either there is something being cooked towards putting the social plugin in relation to the recent [blog post](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/), or squidfunk expects that the [funding tier](https://squidfunk.github.io/mkdocs-material/insiders/benefits/#22000-habanero-orange) with the improved social plugin will be reached quite fast.

As for proper cache invalidation I was planning to fix it, but this is not a "critical" issue, so I haven't gotten around to it.

---

You can also check Nype's Brand Site: 
- https://npe.cm/

Where the custom color is being used:
- https://github.com/nypesap/nypesap.github.io/blob/faa37637d16a15c9b5095230a29b98f82858e0c0/mkdocs.yml#L68

**Comment by daelvn** [comment]
I had gotten the impression [from this comment](https://github.com/squidfunk/mkdocs-material/issues/6929#issuecomment-2005678370) that setting manual CSS colors was not possible without Insiders, when looking for the solution to this issue (which had turned out to be about cache), so I had assumed that trying the CSS color manually was not worth it. After setting it *and* deleting the cache it finally worked.

Thank you for the information on the cache fix/new social plugin implementation! As well as for the detailed answer. It was very useful in understanding how this worked. I'm marking this as closed now.
