### ISSUE TITLE
Pre-release 1.0.0rc is not usuable

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#76]
## Description

Went to finally give this theme a spin, but I cannot use pre-release 1.0.0rc.  After installing, mkdocs gives the following error when trying to include it:

```
ImportError: No module named material
```

At least one think of note is it seems `__init__.py` is missing from the theme.  Anyways, Hopefully this will get resolved sometime soon.  I am interested in evaluating this theme as it looks to be close to a final release.

### Expected behavior

The material theme should be available once installed.

### Actual behavior

Theme is installed but not seen via mkdocs entry points.

### Steps to reproduce the bug

1. Install latest RC
2. Include theme via `theme: material`
3. `mkdocs serve`

### Package versions

- Python: Any
- MkDocs: 0.16.1
- Material: 1.0.0-rc

### System information

- OS: OSX, but I don't think it matters

**Comment by facelessuser** [comment]
I tired the tip of the rework branch, I assume that is what the recent prereleases are based off of.  It seems that the install was fixed there, so I imagine the next pre-release/actual release will be fine.

**Comment by squidfunk** [comment]
Yes, I realized it yesterday and fixed it this morning. Thanks for pointing it out. I fixed some other small bugs I found, so I will put out a rc.2 now.

**Comment by squidfunk** [comment]
Should be fixed in [1.0.0-rc.2](https://github.com/squidfunk/mkdocs-material/releases/tag/1.0.0-rc.2)

**Comment by facelessuser** [comment]
Thanks.  It's looking real nice.  I may be switching over 😄 .

**Comment by squidfunk** [comment]
Thanks! If you encounter anything regarding pymdownx, please let me know. Also thanks for helping me out with the latest pymdownx release - I think it works really well with the Material theme.

**Comment by facelessuser** [comment]
Everything is looking good so far.  I notice in your docs you setup `pymdownx.githubemoji`.  I just released a new version that deprecates that extension in favor of a more flexible one (but obviously it is still available for now).  Instead, I would suggest moving over to `pymdownx.emoji` that supports Gemoji (Github's) or EmojiOne.

If you wish to migrate over to the emoji extension, but want to continue to use Github's emojis (Gemoji) and wish to maintain the exact output of githubemoji, then you can set it up like this in your `mkdocs.yml`:

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      alt: short
      options:
        attributes:
          align: absmiddle
          height: 20px
          width: 20px
```
