### ISSUE TITLE
Built-in `privacy` plugin does not download external assets of embedded .html file

### ISSUE THREAD

**Issue by mrsmrynk** [squidfunk/mkdocs-material#7600]
### Context

As discussed in #7596

I use an inline frame (`<iframe>`) to embed .html files in my documentation.
The .html files are generated by [folium](https://python-visualization.github.io/folium/latest/) and download .js files from various CDNs.
The built-in `privacy` plugin is used for self-hosting of these external assets.

### Bug description

The built-in `privacy` plugin does not download the external assets of the embedded .html file.

I would expect it to:
- download the external assets to the `site` directory
- replace all references with links to the downloaded copies

### Related links

- [Built-in `privacy` plugin](https://squidfunk.github.io/mkdocs-material/plugins/privacy/)

### Reproduction

[9.5.39-privacy-with-embedded-html.zip](https://github.com/user-attachments/files/17284246/9.5.39-privacy-with-embedded-html.zip)

### Steps to reproduce

1. run `mkdocs serve`
2. check the `.cache/plugin/privacy` directory - the external assets of the embedded .html file are not downloaded
3. check the `docs/maps/bounding_box.html` file - the references are not replaced with links to the downloaded copies

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. While this might not be obvious, for MkDocs to consider your HTML file as something to process, it must be listed under `extra_templates`. If you add the following to your `mkdocs.yml`:

``` yaml
extra_templates:
  - maps/bounding_box.html
```

The privacy plugin will process it and download all assets:

```
INFO    -  Downloading external file: https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.js
INFO    -  Downloading external file: https://code.jquery.com/jquery-3.7.1.min.js
INFO    -  Downloading external file: https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js
INFO    -  Downloading external file: https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js
INFO    -  Downloading external file: https://cdn.jsdelivr.net/npm/leaflet@1.9.3/dist/leaflet.css
INFO    -  Downloading external file: https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css
INFO    -  Downloading external file: https://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css
INFO    -  Downloading external file: https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.0/css/all.min.css
INFO    -  Downloading external file: https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css
INFO    -  Downloading external file: https://cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css
```

I think this can be considered a design flaw in MkDocs, as all HTML files that are located in the `docs_dir` should probably automatically considered for moving them through the plugin pipeline. However, I'm not the one to decide. Maybe you can run this by the maintainers of MkDocs, to automatically include all files. We could also add an exception in the privacy plugin and try to detect when there are ``.html` files in the `docs_dir` that are not explicitly listed under `extra_templates`, but honestly, we're fighting MkDocs on so many fronts – I don't want to create another battlefield.

Note that dynamically generated asset URLs in JavaScript (= map tiles) are not downloaded - it's not possible to know what to download and replace without executing the JavaScript. Marking as resolved via configuration.

**Comment by mrsmrynk** [comment]
Thanks to both of you for your help ☺️
I've opened a PR with some additions to the docs.
