### ISSUE TITLE
New Line to Break nl2br Python Markdown extension is not documented

### ISSUE THREAD

**Issue by peterjpxie** [squidfunk/mkdocs-material#7605]
### Description

New Line to Break nl2br Python Markdown extension is not documented:
https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#python-markdown

It is working as it is a built-in extension of python-markdown:
https://python-markdown.github.io/extensions/#officially-supported-extensions

sample mkdocs.yml:
```
markdown_extensions:
  - nl2br
```

Example md:
```
line 1
line 2
```

rendered HTML:
```
<p>line 1<br>
line 2</p>
```

### Related links

- [Reporting a docs issue](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/)
- [ Material python-markdown page](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#python-markdown)
- [python-markdown docs](https://python-markdown.github.io/extensions/#officially-supported-extensions)

### Proposed change

document nl2br support

### Before submitting

- [X] I have read and followed the [documentation issue guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/).
- [X] I have attached the links to the affected sections of [the documentation](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-docs-issue/#related-links)

**Comment by facelessuser** [comment]
There are a lot of plugins out there. I personally wouldn't expect Material to cover all of them. I think right now they specifically cover the most common and/or those in which they add special support for. `nl2br` does not require any "special" support from Material.

**Comment by squidfunk** [comment]
@facelessuser is right – we can't document every third-party extension 🤟
