### ISSUE TITLE
Unnecessarily little room for site description in social card

### ISSUE THREAD

**Issue by pekkaklarck** [squidfunk/mkdocs-material#7610]
### Bug description

If the site description is long, it is not fully visible in the generated social cards.

In our case the description is this:
> Robot Framework is a generic open source automation framework for acceptance testing, behavior-driven development (BDD) and robotic process automation (RPA).

And this is how the social card currently looks like:
![bad](https://github.com/user-attachments/assets/c605d5ad-5c76-4c14-a7fa-0c3e84b354ce)

Obviously there cannot be room for overly long descriptions, but it seems that the horizontal area that is currently reserved for the description is unnecessarily small and the text doesn't get even close to the right margin.

I already checked from the [source code](https://github.com/squidfunk/mkdocs-material/blob/47fc7d5a61847b9a184facb1cea3e356e0bdcee5/src/plugins/social/plugin.py#L273) that the horizontal space (826 pixels) reserved for the description is exactly the same that's reserved for the site name and page title. With the latter two the width needs to take the space reserved for the logo into account, but the description is fully below the logo so it could use more horizontal space.

I also tested that increasing the width that's reserved for the description really helps. I increased it to 1026 pixels and our social card looks good:
![good](https://github.com/user-attachments/assets/7f57e2ea-f023-4d1c-8fff-2b6f13c8867a)

I'd be happy to provide a pull request increasing the width, but I'm not sure what exact value to use. The generated image is 1200 pixels wide and seems to have ~75 pixels of padding. That would leave 1050 pixels for the content, but I'm not sure should some safety margin be added and the value be a bit smaller. Perhaps that 1026 I used would be just fine.

### Related links

- https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/setting-up-social-cards
- https://www.mkdocs.org/user-guide/configuration/#site_description

### Reproduction

[9.5.40-description-clipped-in-socialcard.zip](https://github.com/user-attachments/files/17330020/9.5.40-description-clipped-in-socialcard.zip)

### Steps to reproduce

1. Create a longish `site_description`. The content doesn't really matter, but in our case it was:
   > Robot Framework is a generic open source automation framework for acceptance testing, behavior-driven development (BDD) and robotic process automation (RPA).
2. Create a site with the social plugin enabled.
3. Look at the generated `site/assets/images/social/index.png` file.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by pekkaklarck** [comment]
I don't think the title and the description aligning  on right is that strong of an argument. It can happen only if the title is long enough and even then depends on how the lines wrap. For example, only the last title line in your example actually aligns with the description.

I hope the reason not to improve social cards isn't that it could make paid social card features less interesting.

**Comment by squidfunk** [comment]
Well, as I said, it is a matter of taste, as is most of this project. You have one perspective, which is reasonable. Consider that there are 50-100k more perspectives, so we need to find some common ground. Nothing is stopping you from forking Material for MkDocs and adjusting it to your taste – it is MIT-licensed after all.

Additionally we have absolutely no reason to make the community version suck to sell Insiders. Au contraire – we try to make it as compelling as possible, so you actually want to check out the early access to extra features that come with Insiders. I just don't consider your proposal an improvement that (almost) everybody would agree on. Please respect that.

**Comment by kamilkrzyskow** [comment]
I'll add that, if the suggestion is to maintain a fork of the material theme to modify Python logic, I would instead advise to use some monkey-patching, as this should be overall quicker and less cumbersome that maintaining/syncing the new theme with the upstream origin. I explained a bit more here:
- https://github.com/squidfunk/mkdocs-material/discussions/7331
