### ISSUE TITLE
Breadcrumbs all link to deepest page (incompatible with mkdocs-section-index?)

### ISSUE THREAD

**Issue by pawamoy** [squidfunk/mkdocs-material#7614]
### Context

I'm using mkdocs-section index to create section pages. I'm also using the `navigation.path` feature to show breadcrumbs. If it turns out it's just an imcompatibility with the mkdocs-section-index plugin, I definitely understand if there's no will to "fix" it here. Just wanted to report, in case there's an easy fix :slightly_smiling_face: 

As for why I'm using mkdocs-section-index instead of the same feature in Material for MkDocs: the plugin is more flexible and generally gives better results (happy to take some time to elaborate exactly how).

### Bug description

Each breadcrumb links to the deepest page, even though each crumb has a page of its own (a section index page).

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Breadcrumbs docs](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=breadc#navigation-path)

### Reproduction

[9.5.40+insiders.4.53.14-breadcrumbs-section-pages.zip](https://github.com/user-attachments/files/17355783/9.5.40%2Binsiders.4.53.14-breadcrumbs-section-pages.zip)

### Steps to reproduce

1. Download repro archive
2. Unzip, enter folder, install deps, etc.
3. Serve
4. Go to `/guide/`, `/guide/user-guide/`, `/guide/user-guide/loading/` pages, and observe that each crumb always link to the deepest page: `/guide/user-guide/loading/`.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. I checked the example, and indeed, disabling section index solves the issue. Note that Material for MkDocs is not compatible with this plugin, so the general recommendation is to disable it. We have no intention supporting this plugin, as Material for MkDocs supports the functionality natively (albeit there are some caveats, due to how MkDocs handles index pages). Closing as resolved via configuration change.

**Comment by pawamoy** [comment]
As mentioned above, I prefer using mkdocs-section-index, but I understand the plugin won't be supported :slightly_smiling_face: I'm able to fix the links anyway with a bit of Javascript:

```js
/* Crumb links always link to deepest page when mkdocs-section-index is used,
 * so this script corrects the links to point to the correct page.
 */
document.addEventListener("DOMContentLoaded", function(){
    const breadcrumbs = document.querySelector("nav.md-path").getElementsByTagName("a");
    for (let up = 1, crumb = breadcrumbs.length - 2; crumb >= 0; crumb--, up++) {
        breadcrumbs[crumb].href = "../".repeat(up);
    }
});
```

**Comment by pawamoy** [comment]
Ah yes, of course, much better idea! I'll try that and report back, thanks :slightly_smiling_face:

**Comment by pawamoy** [comment]
Took more time than I thought, but here's my overridden `path-item.html` partial :slightly_smiling_face: 

```django
<!-- Render navigation link content -->
{% macro render_content(nav_item) %}
  <span class="md-ellipsis">
    {{ nav_item.title }}
  </span>
{% endmacro %}

<!-- Render navigation item -->
{% macro render(nav_item, ref=nav_item) %}
  {% if nav_item.is_page %}
    <li class="md-path__item">
      <a href="{{ nav_item.url | url }}" class="md-path__link">
        {{ render_content(ref) }}
      </a>
    </li>
  {% elif nav_item.children %}
    {{ render(nav_item.children | first, ref) }}
  {% else %}
  {% endif %}
{% endmacro %}
```
