### ISSUE TITLE
The tooltip style of the logo is lost in instant loading mode

### ISSUE THREAD

**Issue by Xiaokang2022** [squidfunk/mkdocs-material#7619]
### Context

Python: `3.13.0`
OS: `Windows11 23H2`

### Bug description

With the Instant Loading mode, the style of the logo's tooltip is only correct the first time, and will lose the style after clicking on another page.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=instant#instant-loading

### Reproduction

[9.5.40-logo-bug.zip](https://github.com/user-attachments/files/17371841/9.5.40-logo-bug.zip)

### Steps to reproduce

1. Refresh the current page
2. Check that the style of the logo's tooltip is correct
3. Click on a different page or click on the page again and check again
4. Styles are missing

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Fixed in 53cb6a625. We must remount the header component on instant navigation to account for tooltips that are not hidden in nested components in the header (like repository or search). This commit moves the header to the `$content` observable chain, which will now update correctly.

**Comment by squidfunk** [comment]
Released as part of [9.5.41](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.41).
