### ISSUE TITLE
Added a way to change the icon in the search box (NOT in the search bar)

### ISSUE THREAD

**Issue by Xiaokang2022** [squidfunk/mkdocs-material#7661]
### Description

At the moment, the project has been very complete for changing the icons, but I still found that the icons in the search box cannot be modified (**It doesn't refer to the icon in the search bar**), at least, I don't find a good way to modify it.

![image](https://github.com/user-attachments/assets/3a5299e8-f96e-47af-ab18-4549aa6c2caf)

### Related links

- [Requesting a change](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/)
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#site-icons

### Use Cases

If we can't change it, then it looks very incongruouson my website.

As shown below, the icons on my site are solid, not the default hollow icon. But the icon inside the search box is hollow, and I haven't found a way to change it, which is weird.  :(

![image](https://github.com/user-attachments/assets/56c220ef-9f8b-41a7-9f05-2b3563d6d582)

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. We're currently not planning to add additional options, as we're working on [much bigger topics](https://squidfunk.github.io/mkdocs-material/blog/2024/08/19/how-were-transforming-material-for-mkdocs/) right now, but you can easily change it with some additional CSS. The variable is called `--md-search-result-icon`. For example, see here how you can [replace admonition icons](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#__codelineno-13-2), which follows the same principles.

Closing as resolvable via customization.

**Comment by Xiaokang2022** [comment]
Okay, but thanks for the method you give anyway.
