### ISSUE TITLE
Expand Left Nav Pane Items By Default

### ISSUE THREAD

**Issue by Akkadius** [squidfunk/mkdocs-material#767]
Expand Left Nav Pane Items By Default

Is this configurable in anyway? Right now everything is collapsed until opened

Awesome work BTW

**Comment by squidfunk** [comment]
Nope, it's currently not possible via configuration, but you could hack something together with CSS. Try to search the issue tracker, there are some directions on how to achieve that.

**Comment by squidfunk** [comment]
Thanks for sharing your hack!

**Comment by Akkadius** [comment]
Just for completeness - I ended up making an adjustment because this actually would have weird side affects to the nav layout in mobile. Every single menu from every single tab would appear.

```javascript
document.addEventListener("DOMContentLoaded", function() {
    load_navpane();
});

function load_navpane() {
    var width = window.innerWidth;
    if (width <= 1200) {
        return;
    }

    var nav = document.getElementsByClassName("md-nav");
    for(var i = 0; i < nav.length; i++) {
        if (typeof nav.item(i).style === "undefined") {
            continue;
        }

        if (nav.item(i).getAttribute("data-md-level") && nav.item(i).getAttribute("data-md-component")) {
            nav.item(i).style.display = 'block';
            nav.item(i).style.overflow = 'visible';
        }
    }

    var nav = document.getElementsByClassName("md-nav__toggle");
    for(var i = 0; i < nav.length; i++) {
       nav.item(i).checked = true;
    }
}
```

**Comment by stefanclayster** [comment]
Great snippet! Would love if it was added as an option natively.

**Comment by tonglil** [comment]
Is this still working for folks?
Added this to extra.js and updated in mkdocs.yml but not seeing it take effect.
Noticed this comment was from v2.7.

**Comment by squidfunk** [comment]
@tonglil you can change the breakpoints in the original source (`_config.scss`) and recompile the theme. All other values should be derived from the breakpoints. However, note that I’ve chosen 1220px because any smaller diminishes the readability of the content section.

**Comment by gribilly** [comment]
Can confirm this still works for me.  Make sure you set your [`extra_javascript`](https://squidfunk.github.io/mkdocs-material/customization/#additional-javascript) block in your `mkdocs.yml`.  Also make sure you don't have duplicate `extra_javascript` blocks in your `mkdocs.yml`.

**Comment by kruzfuz** [comment]
Can also confirm that this works for me. However, when tabs are activated, empty lines are added for every entry in the `nav` section of the `mkdocs.yml`. Has anybody else experienced that?

**Comment by pfilbin90** [comment]
Hi this doesn't appear to work anymore.  I'm on the latest version of mkdocs-material-5.4.0.

Does anybody have any updated code that works with this version?

Thanks

**Comment by lprichar** [comment]
@Akkadius's solution works for me, but it does cause a flash on the screen as it loads.  Closing this issue seems premature as a native solution would eliminate the flash.

**Comment by squidfunk** [comment]
I'm putting this feature on the roadmap of [Material for MkDocs Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) 😊

**Comment by squidfunk** [comment]
Good news – just implemented a new feature flag called `navigation.expand`, which will expand everything on page load.

- [How to enable navigation expansion](https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion)
- [How to get Material for MkDocs Insiders](https://squidfunk.github.io/mkdocs-material/insiders/)

### Demo

![Ohne Titel](https://user-images.githubusercontent.com/932156/89928048-8ad02500-dc07-11ea-851d-be18c70112cc.gif)
