### ISSUE TITLE
Mermaid: New Mermaid.js version do not render correctly 

### ISSUE THREAD

**Issue by b-gauthier** [squidfunk/mkdocs-material#7671]
### Context

Working on a documentation an noticed mermaid flowchart was not rendering the same way (font color) in two consecutive versions. 

### Bug description

When trying to render a flowchart diagram using mermaid and specifying a font color, the diagram renders correctly in Material for MkDocs 9.5.33 but not in 9.5.34 after update of Mermaid.js to version 11. Specifically, the font color of "bloc1" should be white but is black starting with Material MkDocs 9.5.34, indicating that the font color property is probably overwritten. 

The mermaid flowchart is the following (which renders correctly on GitHub...): 

``` mermaid
flowchart LR
  bloc1:::blue --> bloc2:::white
  classDef blue fill:#005cb9,stroke:#000000,color:#fff
  classDef white fill:#fff,stroke:#000000,color:#000000
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Diagrams](https://squidfunk.github.io/mkdocs-material/reference/diagrams/?h=mermaid)
- [Mermaid flowcharts styling](https://mermaid.js.org/syntax/flowchart.html#styling-a-node)

### Reproduction

[9.5.43-mermaid-flowchart-font-color.zip](https://github.com/user-attachments/files/17624677/9.5.43-mermaid-flowchart-font-color.zip)

### Steps to reproduce

1. Install minimal and latest version of Material for MkDocs following https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/
2. Add the mermaid markdown extension to mkdocs.yml following https://squidfunk.github.io/mkdocs-material/reference/diagrams/?h=mermaid
3. Add the example mermaid flowchart to a page 
4. Serve or build the documentation
5. Notice that bloc1 font color is black instead of white

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. It seems to be related to 335dd3addb0c5875d42349a9a06ea2b4b7055374, where we fixed rendering of Markdown nodes. If you remove `nodeLabel p`, your example works. Note however, that we currently do not aim to support custom colors – the diagrams should just render great out of the box, which is what the majority of users benefits from. Also, please understand that Mermaid integration is provided as a best-effort. We try to adapt our integration to solve the common case, but it is far from perfect, as we can only influence the CSS, which is often changed from release to release.

Thus, if you need more control, I recommend rolling your own Mermaid integration, possibly by using the [mkdocs-mermaid2-plugin](https://github.com/fralau/mkdocs-mermaid2-plugin), which I hear works pretty well. We must consider this out of scope. Thank you for your understanding.
