### ISSUE TITLE
Search disappears on activating Blog plugin

### ISSUE THREAD

**Issue by dashdesai** [squidfunk/mkdocs-material#7682]
### Context

I enabled the blog plugin on an existing MkDocs Material site and the search box disappeared from the main navigation.

### Bug description

Search bar disappears on enabling the Blogs plugin.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

A minimal reproduction has been created and attached. All version details, etc are included within the /docs/index.md.
[min-mm.zip](https://github.com/user-attachments/files/17683231/min-mm.zip)

### Steps to reproduce

1. Add blog configuration to the mkdocs.yml file
2. Run mkdocs serve
3. Visit site
4. Observe that the search box does not exist any more.
<img width="1664" alt="Screenshot 2024-11-08 at 19 34 37" src="https://github.com/user-attachments/assets/72c5ac01-2bc2-41cb-a4b7-b4b0c6a72a19">

### Browser

Chrome, Safari, Other

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by alexvoss** [comment]
This is [documented behavior](https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/?h=search#built-in-search-plugin). When you create a plugins section in the configuration you need to add all plugins that you want. I know it is somewhat surprising at first.

**Comment by dashdesai** [comment]
Thanks @alexvoss for the quick response. Adding search to the plugins fixed it beautifully!

For anyone else who stumbles upon this thread, the fix is as follows (the blog_toc is optional of course):

plugins:
  - search
  - blog:
      blog_toc: true
