### ISSUE TITLE
Unescaped '>' in `data-clipboard-target` attribute string that probably should be replaced by its HTML entity '&gt;'

### ISSUE THREAD

**Issue by mixio** [squidfunk/mkdocs-material#7700]
### Context

In file: mkdocs-material/src/templates/assets/javascripts/templates/clipboard/index.tsx

The function renderClipboardButton() line 42:

```javascript
export function renderClipboardButton(id: string): HTMLElement {
  return (
    <button
      class="md-clipboard md-icon"
      title={translation("clipboard.copy")}
      data-clipboard-target={`#${id} > code`} // The '>' should be escaped because it appears as data-clipboard-target="#__code_8 > code" in the final HTML.
    ></button>
  )
}


### Description

The '>' in the mentioned function should be escaped because it appears as **data-clipboard-target="#__code_8 > code"** in the final HTML.


### Related links

mkdocs-material/src/templates/assets/javascripts/templates/clipboard/index.tsx

### Use Cases

This should fix the HTML invalid presence of an unescaped '>' in a tag attribute string.

### Visuals

_No response_

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
This is not a proper bug report. Please follow our [bug reporting guide lines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/) and provide a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/), as we do not know how to actually observe the error that you're trying to report. [Closing as incomplete](https://squidfunk.github.io/mkdocs-material/contributing/#incomplete-issues-and-duplicates).

**Comment by mixio** [comment]
Thank you for taking the time to investigate.

After a bit of research, according to the W3C and the current HTML spec, 
the character ‘>’ can be used in an attribute string values.
And indeed the validator doesn't report this as an error.

HTML4 did not allow this.

I was using a script utility to extract the code examples that choked on the raw '>'.
The bug was on my side.

All is good and well. Sorry to have bothered you with this.

Kind regards.

---

HTML 4 Document Representation
5.3.2 Character entity references: https://www.w3.org/TR/html4/charset.html#h-5.3.2

HTML
Living Standard — Last Updated 14 November 2024
13.1.2.3 Attributes: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

13.1.2.6 Restrictions on the contents of raw text and escapable raw text elements
https://html.spec.whatwg.org/multipage/syntax.html#cdata-rcdata-restrictions
