### ISSUE TITLE
mkdocs-git-committers-plugin-2 not showing committers on page

### ISSUE THREAD

**Issue by athshean** [squidfunk/mkdocs-material#7702]
### Context

I set up a minimal example to try and reproduce the issue,and I found that the `mkdocs-git-committers` plugin isn't working. It is not showing a list of committers at the bottom of the page as expected.

https://github.com/athshean/mkdocs-minimal-test

### Bug description

Made a minimal working example using the examples and configurations listed in the documentation to try and see if mkdocs-git-committers-plugin-2 would work. I expected to see a list of committers at the bottom of the page, but this did not work as expected.

It does not look like the feature is insiders or sponsors only, but instead seems like it is just an experimental feature.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Adding a git repository](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/)
- [MKDocs git committers plugin 2](https://github.com/ojacques/mkdocs-git-committers-plugin-2)

### Reproduction

Reproduction site here: https://github.com/athshean/mkdocs-minimal-test
[mkdocs-minimal-test-main.zip](https://github.com/user-attachments/files/17759169/mkdocs-minimal-test-main.zip)

### Steps to reproduce

1. Make a minimal working site using MKDocs
2. Set theme to material
3. Install mkdocs-git-committers-plugin-2 using pip
4. Add plugin to mkdocs.yml file
5. Commit to the repo and view the github pages site

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Running your example, the following `.cache/page-authors.json` is produced:


``` json
{
  "cache_date": "2024-11-15",
  "page_authors": {
    "docs/index.md": {
      "last_commit_date": "2024-11-14",
      "authors": []
    }
  }
}
```

Thus, there is nothing to show, so Material for MkDocs works correctly. Please ask/report this upstream, i.e., the authors and maintainers of the [git-committers-plugin-2](https://github.com/ojacques/mkdocs-git-committers-plugin-2).

**Comment by athshean** [comment]
The issue was caused by a mismatch between the email address in the git config and the noreply email address associated with the GitHub account. I fixed the problem by correcting the git config and adding the correct email address.

**Comment by squidfunk** [comment]
Perfect, thanks for reporting back! This will help other users that experience the same issue.
