### ISSUE TITLE
Multiple footnote reference

### ISSUE THREAD

**Issue by kavimaluskam** [squidfunk/mkdocs-material#772]
Referencing the footnote functionality:
https://squidfunk.github.io/mkdocs-material/extensions/footnotes/#inserting-the-reference

Can we insert multiple foot note reference like:
``` It looks like this is your first time opening an issue in this project! [^1, ^2]```
Instead of 
``` It looks like this is your first time opening an issue in this project![^1] [^2]```

Of course the current footnote is still working well, but in some cases the above approach is more clear.

**Comment by squidfunk** [comment]
Parsing is done by Python Markdown, not by Material, so it's an upstream feature request. You can post a feature request on [their tracker](https://github.com/Python-Markdown/markdown/issues)

**Comment by facelessuser** [comment]
I'll be honest, the suggested footnote syntax is very non-standard `[^1, ^2]`.  As a member of the Python Markdown team, I can tell you it is unlikely that `[^1, ^2]` will be accepted.  I would instead suggest that you look into rolling your own custom extension.

This was my approach for [pymdown-extensions](https://github.com/facelessuser/pymdown-extensions/).  It allows me to provide my own personal opinionated extensions while Python Markdown provides more common, expected features.
