### ISSUE TITLE
unpkg.com Mathjax endpoints are all dead

### ISSUE THREAD

**Issue by JulianDominic** [squidfunk/mkdocs-material#7726]
### Context

I am not sure when this started but I am unable to access any and all unpkg.com Mathjax links.

This is important because in the docs, it said to include `https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js`. However, as of writing, that endpoint is no longer available.

I followed Mathjax's official documentation and replaced that unpkg link with `https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js`, and it worked flawlessly.

### Bug description

With the old unpkg link, if you inspect the network tab, it will timeout and say NS_ERROR_CORRUPTED.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Mkdocs Material Mathjax Documentation](https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-mkdocsyml)
- [Mathjax official documentation](https://docs.mathjax.org/en/latest/web/start.html)

### Reproduction

[bug_report.zip](https://github.com/user-attachments/files/17831082/bug_report.zip)

### Steps to reproduce

1. `mkdocs serve`

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Seemingly a temporary problem. Works for me:

![Uploading Bildschirm­foto 2024-11-20 um 17.42.49.png…]()
