### ISSUE TITLE
Bluesky comments for the blog plugin 

### ISSUE THREAD

**Issue by CLOVIS-AI** [squidfunk/mkdocs-material#7754]
### Context

Our documentation/blogs are not hosted on GitHub, so we cannot use the built-in GitHub Discussions support.

### Description

The ability to use a Bluesky thread as comments in a blog post.

### Related links

https://www.coryzue.com/writing/bluesky-comments/

### Use Cases

Allow options to have comments in blog posts, without relying on GitHub.

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material/), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

**Comment by squidfunk** [comment]
Thanks for suggesting. This is an excellent case for a third-party extension! We're currently not considering adding this functionality, but you can either write an MkDocs plugin, or use [customization](https://squidfunk.github.io/mkdocs-material/customization/) to integrate BlueSky comments. It should be fairly easy. Closing as out of scope.

**Comment by pubmania** [comment]
I have actually added this on [my blog](https://mgw.dumatics.com/2024/08/13/logseq-customisation-for-project-management-teamplate.html). 

If you scroll all the way down on that link and wait for a second or so, it loads the comments. 

The benefit of my implementation mainly is that you do not have to build first, get the URL, post it in bluesky and then come back put that URL in frontmatter and rebuild - This is what most of the solutions are doing and I have no idea why. In my implementation if bsky is set to true at the time of build, it will just take it from there as explained below.

If this is what you want, you can check the code for it at following locations on my repo and copy into yours:

1. [js directory](https://github.com/pubmania/pubmania.github.io/tree/main/docs/assets/js) - All stuff in there is only specific to Bluesky commenting. You will need to modify some portions of it which are hardcoded for my blog. I will explain below.
2. [overrides/partials/comments.html](https://github.com/pubmania/pubmania.github.io/blob/main/overrides/partials/comments.html) - You will need to modify this as I moved away from discuss only recently.
3. CSS from `docs/assets/extra.css` relevant to bluesky - it is appropriately commented and you may need to modify per your needs.

Now what it essentially does is this:

1. If in the frontmatter (yaml) of your post, if you have `bsky` set to true or placed a `bsky` url, `comments.html` template will include the javascript responsible to fetch threads relevant to post.

2. The way javascript operates is like so:
    1. It takes the value of bsky from frontmatter and passes it to url right at the begining of the script. 
    2. Now the function loadComments is doing lot of work here and this is where you will need to make modifications
    4. This function first ontains the URL of the webpage and extracts path and discards the # part.
    5. It then creates an assembled URL which concatenates my blog domain with the pathname. **This you will have to change to your domain.** _It is down to me just being lazy and it really could have been done a bit cleaner I guess. Might change it later but in the meantime it will be easy enough for anyone to just replace my blog's domain with theirs._
    6.  It then searches on bluesky URL against my DID for the oldest post that has the URL for this blog post on it. **This you will have to change as well to your DID or that of the account which will host the comments.** - _DID really is public information so it does not really need to be hidden. Although I could perhaps test to get this passed from config directly..._
    7. If it finds one, it passes it further to then get the thread and replies etc which will not require any changes.
    8. If it does not find any post, it checks if the bsky value from frontmatter that was provided is a valid bluesky URL and if so it uses that to obtain threads.
    9. If neither value was available, it displays "_No Comments thread found for this post_" until such time that a post if created on bluesky by the account being used to host comments.
    
3. I have created the basic structure of code which can actually allow me to create the post on bluesky for a URL that it does not find while searching for the URL( at buildtime perhaps?). That is what I wanted to get some input on when I searched the issues here to see if anyone is using bluesky commenting already and what are the thoughts around it. I have not yet thought this through in terms of what will be the best way to implement it. 

Anyway hope this helps.
