### ISSUE TITLE
`Theme: logo` breaks social plugin when set to svg

### ISSUE THREAD

**Issue by jonathanfox5** [squidfunk/mkdocs-material#7758]
### Context

In case it's useful, this is the full site: <https://gogadget.jfox.io>

Minimal reproduction included below.

### Bug description

**Issue**

Setting `theme: logo` in `mkdocs.yml` to an svg image causes the following error when running `mkdocs build` or `mkdocs serve`:

```
cairocffi.CairoError: cairo returned CAIRO_STATUS_INVALID_SIZE: b'invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```

Changing `theme: logo` to a png then back to the original svg fixes it. Therefore, to reproduce, the `.cache` directory needs to be deleted prior to running. I have included `header_broken.svg` and `header_working.png` in the minimal reproduction for reference.

The above _could_ be a workaround in certain use cases but is an issue for running it in "clean" environments such as github actions.

**Platforms tested**

- macOS
- Windows
- Github Actions

**Error log**

[error_log.txt](https://github.com/user-attachments/files/17944797/error_log.txt)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Image processing](https://squidfunk.github.io/mkdocs-material/plugins/requirements/image-processing/)

No related issues found in github issues.

### Reproduction

[9.5.46-theme-logo-breaks-social.zip](https://github.com/user-attachments/files/17944817/9.5.46-theme-logo-breaks-social.zip)

### Steps to reproduce

1. Install system Cairo libraries as per documentation (or use github CI which has it pre-installed). Ensure that "mkdocs-material[imaging]" is installed and available.
2. Delete `.cache` folder if it exists. If a png logo has previously been used and cached, there won't be any error.
3. If on macOS, run `export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib`
4. Run `uv run mkdocs serve -f docs/mkdocs.yml`
5. Error will be observed

Changing logo to a png fixes it and it will continue to work if the logo is changed back to a svg.

I have included `header_broken.svg` and `header_working.png` in the minimal reproduction for reference.

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. I think the error message is quite clear here

```
cairo returned CAIRO_STATUS_INVALID_SIZE: b'invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```

Looking at your logo, it has `viewBox="0 0 3693 740"`, which means it is `3693x740px`, which seems to be too big for Cario. If this should be considered an error, it should be reported to Cairo. Using another logo fixes the problem. Maybe you can try and create a smaller logo and optimize it with any of the free SVG optimizers out there.

Closing as configuration error.

**Comment by jonathanfox5** [comment]
Thanks for the quick reply, that's sensible. 

Since it's a vector image, I would have assumed the size would be ignored since the size isn't "real". I had previously thought that the size in the svg was just a suggested rendering size rather than an actual property of the image but maybe it's something more!

p.s. Thanks for the great work on this project - it's amazing!

**Comment by jonathanfox5** [comment]
That makes sense to leave it. Hopefully this issue sitting here will be enough to help someone who encounters it in the future.

Since you need to add css overrides for it to even make sense to include a wide logo, the chances of it affecting many people is slim (as you point out)

Thanks again.
