### ISSUE TITLE
Provide a tabs extension ?

### ISSUE THREAD

**Issue by warlof** [squidfunk/mkdocs-material#776]
## Description

Hello, I would know if it could be possible to implement a "tabs" extension, so we can provide inside a documentation, some variant according to, for exemple, different environment (ie: Operating Systems)

### Expected behavior

One well designed exemple is the Docker documentation https://docs.docker.com/install/linux/docker-ce/ubuntu/#extra-steps-for-aufs

You have a tabs navigation which is providing different instructions according to Ubuntu version.

It seems material is providing such component for nodejs application https://material.io/components/web/catalog/tabs/

**Comment by makshh** [comment]
#434

**Comment by warlof** [comment]
thank you @makshh, I wasn't able to get it from search :/

As I can see, the discussion lead to a "non doable" end. @mikesol implementation looks good. I'll dig into it further.

Related to the markdown syntax, here is what I've in mind - except I have no idea if it's conflicting with another one (ie : table. I think table is using `|-----|----| instead of [----|----]`

```
[ Tab1 | Tab2 ]
--------------
[ Content1 ]
[ Content2 ]
```
