### ISSUE TITLE
Issue on the main website with svg in TOC

### ISSUE THREAD

**Issue by A3Bagged** [squidfunk/mkdocs-material#7769]
### Context

Browsing the website i noticed that some of the `Insider` hearts were inproperly shown in the TOC nav.
They show up as 200x200 black coloured hearts on the following page: [Basic blogs](https://squidfunk.github.io/mkdocs-material/tutorials/blogs/basic/#meta-plugin)

**Edit:** Sorry i just noticed theres a different section for this issue

### Bug description

By further inspecting i can see that the following is rendered as 200x200px
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="m12 21.35-1.45-1.32C5.4 15.36 2 12.27 2 8.5 2 5.41 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.08C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.41 22 8.5c0 3.77-3.4 6.86-8.55 11.53z"></path></svg>
```
And `<span class="twemoji">` is rendered as 200x17px;

**Screenshot below:**
![afbeelding_2024-12-04_204831795](https://github.com/user-attachments/assets/c7a291fa-d827-41e2-a877-a86b4be143c6)

_Tested in latest release `Opera Gx` and `Google Chrome` (not sure what version)_

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Basic blogs](https://squidfunk.github.io/mkdocs-material/tutorials/blogs/basic/#meta-plugin)

### Reproduction

_n/a_

### Steps to reproduce

_n/a_

### Browser

Opera

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting – this is actually a documentation issue. We're injecting custom code into the table of contents, so it's not really expected to work. I've fixed the documentation in eab6959d0 and moved the info below the headlines.
