### ISSUE TITLE
Compatibility issues with Highlighting Lines in Code blocks

### ISSUE THREAD

**Issue by jaywhj** [squidfunk/mkdocs-material#7771]
### Context

```javascript [4]
function hello(name) {
    let phrase = `Hello, ${name}!`;

    debugger;

    say(phrase);
}
```

### Bug description

I have a paragraph in my markdown text like this, and when I run it, it parses incorrectly, causing the rendered page to be completely misaligned:

````
```javascript [4]
function hello(name) {
    let phrase = `Hello, ${name}!`;

    debugger;

    say(phrase);
}
```
````

It will be rendered like this:

<img width="739" alt="iShot_2024-12-05_12 36 20" src="https://github.com/user-attachments/assets/733e66d3-bd1e-4548-96e1-3dd7b1b5f717">

The reason is that the [4] after the token is not recognized, and it treats the [4] as the beginning of the code, which should normally be the next line.

I know this is not the canonical writeup for this project, but it could be designed so that ignore unrecognized markup when it is encountered, thus not affecting the parsing and rendering of later text.This writeup renders fine in other editors, such as Typora, Github and so on.

This writeup is from other project [revealjs](https://revealjs.com/code/), I compared, this design is much simpler, just need to set the number, don't need to remember the property name, and it also supports step-by-step highlights.

- If you agree with this design, you can consider adding support in subsequent updates;
- If other settings are involved and it is troublesome to modify, then forget it, but it needs to be designed to ignore the markup and not affect the analysis and rendering of the following text;

Here are some write-ups for comparison and reference:

<img width="966" alt="iShot_2024-12-05_12 40 08" src="https://github.com/user-attachments/assets/1aba0412-8041-4e47-b4eb-efb6cf3958a0">

### Related links

unnecessary

### Reproduction

unnecessary

### Steps to reproduce

unnecessary

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Note that highlighting is provided by the [Highlight extension](https://facelessuser.github.io/pymdown-extensions/extensions/highlight/), not by Material for MkDocs itself. Thus, please ask the maintainers of this extension. Additionally, please stick to our issue reporting process and provide a minimal reproduction next time.
