### ISSUE TITLE
Disabling card generation in social plugin does not work

### ISSUE THREAD

**Issue by boamaod** [squidfunk/mkdocs-material#7774]
### Context

As described [in documentation](https://squidfunk.github.io/mkdocs-material/plugins/social/#config.cards) specifying `cards: false` in `mkdocs.yml` should "enable or disable social card generation".

### Bug description

Specifying `cards: false` in `mkdocs.yml` the cards are still generated. Specifying `enabled: false` disables the whole social plugin, but this is a different option and doesn't satisfy the same needs as only disabling card generation.

### Related links

- https://squidfunk.github.io/mkdocs-material/plugins/social/#config.cards
- https://squidfunk.github.io/mkdocs-material/plugins/social/#config.enabled

### Reproduction

[9.5.47-disabling-card-generation-in-social-plugin-does-not-work.zip](https://github.com/user-attachments/files/18038083/9.5.47-disabling-card-generation-in-social-plugin-does-not-work.zip)

### Steps to reproduce

1. Run `mkdocs serve`
2. Install required dependencies with `pip install "mkdocs-material[imaging]` as instructed in terminal
3. Run `mkdocs serve` again
4. See actual card generated at `http://127.0.0.1:8000/assets/images/social/index.png`
5. Also see the PNG file in `.cache/plugin/social`

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in a7dc57c23.

**Comment by kamilkrzyskow** [comment]
Does the Social plugin do anything else apart of creating the cards? I think this option is also not used in the Insiders version at all.
Perhaps it should be soft-deprecated? 🤔

**Comment by squidfunk** [comment]
Not yet, but there are some things that might matter, e.g., allowing to set a custom image for all pages or specific pages only, not creating cards at all, but still adding the respective meta tags, etc. Currently both settings have the same functionality, but keeping a dedicated setting keeps it future-proof.

**Comment by squidfunk** [comment]
Released as part of [9.5.48](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.48).

**Comment by boamaod** [comment]
Thank you for the quick release, @squidfunk!

However, I'm not sure I understand this option, because I indeed expected it to be something like "not creating cards at all, but still adding the respective meta tags", but it appears that specifying `cards: false` by default also disables the meta tag generation for title, description etc. I expected "card generation" which you can disable/enable just to mean generating the images at `cards_dir`, but it seems I was mistaken.
