### ISSUE TITLE
mkdocs landing page link to ko-fi.com of designer BewilderedBird is broken, profile is not found.

### ISSUE THREAD

**Issue by md42** [squidfunk/mkdocs-material#7797]
### Bug description

when clicking the Button with Caption "© BewilderedBird" on the mkdocs material homepage i would expect that the ko-fi pages opens with the account of the designer but instead a notfound message is shown on ko-fi.

### Related links

BewilderedBird is also mentioned in https://github.com/squidfunk/mkdocs-material/discussions/4262 but the link to her mastodon is also pointing into the void.

### Reproduction

Open https://squidfunk.github.io/mkdocs-material/ click on Button with Caption "© BewilderedBird"

### Steps to reproduce

1. Open https://squidfunk.github.io/mkdocs-material/ 
2. click on Button with Caption "© BewilderedBird" (see also screenshot)
<img width="1280" alt="Screenshot 2024-12-15 at 16 58 54" src="https://github.com/user-attachments/assets/934d755b-6bac-4d8f-aac5-602b5ce74665" />

3. Pages https://ko-fi.com/ opens but shows that the linked account cannot be found 

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Fixed it in the last commit. I just talked to the creator and she her Ko-Fi account as she doesn't accept commissions anymore, and wants the link to be removed.

**Comment by md42** [comment]
Confirmed, Button is gone. Thanks!
