### ISSUE TITLE
Update Contributing with information about gulp expectations.

### ISSUE THREAD

**Issue by brendo** [squidfunk/mkdocs-material#78]
It'd be useful for contributors to know what is expected in their MR's with regards to versioning assets. Would it be preferred for contributions to just edit the src files, and then versioning be handled when a release is bundled?

Or should each change increment the built assets?

At the moment there's no indication in the Contributing about what's expected, so it's likely both types will occur. I'm not fond of committing the production assets (as I have done in #77) because it's likely to cause merge request conflicts over time.

**Comment by squidfunk** [comment]
Good point. Each PR must build the assets. The assets aren't incremented but cached busted with the hash at the end. The reason why the compiled source is contained in the repository is that this way the Material theme can be used directly from GitHub without installing dependencies and building.

**Comment by squidfunk** [comment]
I added more information on build process in the latest commits.
