### ISSUE TITLE
broken premium sponsors on dockerhub

### ISSUE THREAD

**Issue by niclasheinz** [squidfunk/mkdocs-material#7807]
### Bug description

Hi @squidfunk 

On the Dockerhub page, 5 images of the sponsors are no longer visible because the source in the repo has been deleted.
![grafik](https://github.com/user-attachments/assets/6a399c3c-f743-4ad5-951f-8ab0369c8318)

It would be good if the references to the images in the Docker readme were also deleted.

Greedings
Niclas

### Related links

- [Dockerhub](https://hub.docker.com/r/squidfunk/mkdocs-material/)
-

### Reproduction

-

### Steps to reproduce

-

### Browser

Firefox

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. I updated the README and removed the sponsors from the DockerHub page. It doesn't get many views, and we have them listed on the project's README, as well as our Insiders sponsors section.
