### ISSUE TITLE
mathjax and code block linting incompatible?

### ISSUE THREAD

**Issue by sreid-perf** [squidfunk/mkdocs-material#7813]
### Bug description

I have the following extensions in my mkdocs.yml file
```yaml
markdown_extensions: 
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
```

I am trying to render the following equations and codeblocks in a sample page

```md
## Math

```latex
$$
\cos x=\sum_{k=0}^{\infty}\frac{(-1)^k}{(2k)!}x^{2k}
$$
```
$$
\cos x=\sum_{k=0}^{\infty}\frac{(-1)^k}{(2k)!}x^{2k}
$$

```latex
The homomorphism $f$ is injective if and only if its kernel is only the
singleton set $e_G$, because otherwise $\exists a,b\in G$ with $a\neq b$ such
that $f(a)=f(b)$.
```
The homomorphism $f$ is injective if and only if its kernel is only the
singleton set $e_G$, because otherwise $\exists a,b\in G$ with $a\neq b$ such
that $f(a)=f(b)$.

## Code block test
``` py title="bubble_sort.py"
def bubble_sort(items):
    for i in range(len(items)):
        for j in range(len(items) - 1 - i):
            if items[j] > items[j + 1]:
                items[j], items[j + 1] = items[j + 1], items[j]
```

code block linting works when both are included, but equations do not render. When the code block linting extensions are removed the equations render properly (and the code blocks don't, naturally)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[mkdocs.zip](https://github.com/user-attachments/files/18189619/mkdocs.zip)

### Steps to reproduce

1. Include markdown_extensions as included in description
2. Try to build example markdown included, with both equations and code block linting.

### Browser

Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. There're several problems with this issue, as it does not conform to the quality standards of our [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/), which you confirmed to have read and abided to.

You did not use the info plugin but created a zip file yourself, which means we have no information what extensions and plugins you have installed. Addtionally, I'm not entirely sure what you mean by "code linting" – you probably mean highlighting, as we offer no linting functionality for code blocks, and it's not mentioned in our docs.

Additionally, the example is not minimal, as it contains plugins that do not seem necessary for the reproduction, including mkdocstrings, git-authors, and the offline plugin. Are you trying to create an offline build? Are you trying to build something to depoy to production? The reproduction is not even runnable:

```

ERROR   -  Config value 'docs_dir': The path '.../docs' isn't an existing directory.
```

I'm closing this issue as incomplete. I kindly ask you to carefully read our bug reporting guidelines and follow the process. We need all of the information, or we're not able to help you as part of our free offering here.
