### ISSUE TITLE
Nested List and Inline markdown issues

### ISSUE THREAD

**Issue by Lizhenghe-Chen** [squidfunk/mkdocs-material#7841]
### Bug description

I have found that some inline lists and bold fonts are not represented correctly in mkdocs material, but are displayed correctly in the traditional Markdown compiler.
A markdown of the form shown here will display the correct hierarchy and bolding correctly in both material and traditional markdown compilers:
- Nulla et rhoncus turpis. Mauris ultricies elementum leo. Duis efficitur
  accumsan nibh eu mattis. Vivamus tempus velit eros, porttitor placerat nibh
  lacinia sed. Aenean in finibus diam **Test**.

    * Duis mollis est eget nibh volutpat, fermentum aliquet dui mollis.
    * Nam vulputate tincidunt fringilla.
    * Nullam dignissim ultrices urna non auctor.
![image](https://github.com/user-attachments/assets/ba6966a0-e612-4a45-a4c2-6f807cb52926)
![image](https://github.com/user-attachments/assets/0cdd864b-637b-40cf-841f-71ee35d47f6d)

However, when I remove some redundant-looking spaces (which is what most markdown editor plugins usually do), the traditional compiler displays it correctly, but material no longer displays the correct list hierarchy and bolding:
- Nulla et rhoncus turpis. Mauris ultricies elementum leo. Duis efficitur
  accumsan nibh eu mattis. Vivamus tempus velit eros, porttitor placerat nibh
  lacinia sed. Aenean in finibus diam**Test**.

  * Duis mollis est eget nibh volutpat, fermentum aliquet dui mollis.
  * Nam vulputate tincidunt fringilla.
  * Nullam dignissim ultrices urna non auctor.
![image](https://github.com/user-attachments/assets/6478b94f-1f03-4db3-8c81-871f866640df)
![image](https://github.com/user-attachments/assets/d7679738-3623-4feb-a084-0bba3f2b57f2)

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- https://squidfunk.github.io/mkdocs-material/reference/lists/#using-unordered-lists

### Reproduction

None

### Steps to reproduce

None

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by iBug** [comment]
This is a Python-Markdown limitation. With P-M, indentation must be 4 spaces. Anything short of 4 spaces will not be considered "indented".

**Comment by squidfunk** [comment]
Thanks for reporting. @iBug is correct, it's a limitation of [Python Markdown](https://github.com/Python-Markdown/markdown).
