### ISSUE TITLE
Horizontal scroll bar appears below numbered equations

### ISSUE THREAD

**Issue by MufanColin** [squidfunk/mkdocs-material#7849]
### Bug description

When I insert numbered equations in my markdown file, a horizontal scroll bar always appears at the bottom. I only expect it to appear when the numbered equation is too long to fit.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[9.5.49-unwanted-horizontal-scroll-bar-below-numbered-equations.zip](https://github.com/user-attachments/files/18266024/9.5.49-unwanted-horizontal-scroll-bar-below-numbered-equations.zip)

### Steps to reproduce

You can try adding the following equations to your markdown file. I am using the KaTeX plugin.

```
$$
\begin{equation}
1+2=3
\end{equation}
$$

$$
\begin{align}
v^{\pi}(s)&=\sum_{a\in A}\pi(a|s)q^{\pi}(s,a)\newline
q^{\pi}(s,a)&=R(s,a)+\gamma\sum_{s^{\prime}\in S}P(s^{\prime}|s,a)v^{\pi}(s^{\prime})
\end{align}
$$
```

The rendered equations look like this:

[
![Screenshot 2024-12-28 at 18 55 00](https://github.com/user-attachments/assets/51f44840-0d54-47a0-9f2d-45f364d58db9)
](url)

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by MufanColin** [comment]
After some Googling, I found that this issue was also mentioned [here](https://github.com/KaTeX/KaTeX/issues/3254). I resolved it by adding the following custom css:

```css
.katex .vlist-t2 {
  margin-right: 0px;
}
```

I am wondering if there are better ways to solve this problem. Thanks a lot.

**Comment by squidfunk** [comment]
Thanks for reporting. Yes, this is an upstream issue.
