### ISSUE TITLE
Question: Migrate Theme to Bludit?

### ISSUE THREAD

**Issue by ITforHome** [squidfunk/mkdocs-material#785]
Hi,
the Theme is really beautiful and i like to work with it. The Problem for me is, that MKDocs is a static page generator. So i can‘t use a web editor to create pages for documentation. Thats bad for me and i don‘t like the Workflow of this. So now i want to start with Bludit, a flat CMS. There are some Themes, but not to look like mkdocs-material.

So I am very happy, when i can use the theme under Bludit.
There are Options to migrate it?

**Comment by squidfunk** [comment]
The theme was already ported to other static site generators (Hugo and Paradox) but those are the only ones I am aware of, but I have never heared of Bludit, I'm afraid.

**Comment by ITforHome** [comment]
@squidfunk

**Comment by squidfunk** [comment]
I'm afraid not. My time is very limited and maintaining the original Material theme consumes enough time. You are free to create your own fork and port the theme.

**Comment by carlosperate** [comment]
You could search for static CMS projects that could work with MKDocs, something like this could cover what you need: https://github.com/capriosa/mkdocs-cms

Alternatively, what I do is use GitHub Wiki to create all the markdown pages and a simple script to get the content from git and generate an MkDocs config file: https://www.embeddedlog.com/static-docs-from-github-wiki.html

**Comment by squidfunk** [comment]
Considering this as answered, closing.
