### ISSUE TITLE
Overriding base.html breaks theme

### ISSUE THREAD

**Issue by mryanb** [squidfunk/mkdocs-material#786]
## Description

application.js, modernizr.js, application.css will not load when overriding base.html

### Expected behavior

The site to render properly.

### Actual behavior

The page doesn't render properly.

### Steps to reproduce the bug

1. Create theme_override directory with base.html in that directory. Sourced from (https://raw.githubusercontent.com/squidfunk/mkdocs-material/2.7.3/src/base.html)
2. Set theme dir
```
theme:
  name: material
  custom_dir: theme
```
3. mkdocs serve
4. 
![image](https://user-images.githubusercontent.com/3656391/40812782-408aea4e-64fd-11e8-829a-06d5a9f987ec.png)

### Package versions

* Python: `Python 2.7.10`
* MkDocs: `mkdocs, version 0.17.3`
* Material: `Version: 2.7.3`

### Project configuration

``` yaml
site_name: Docs
theme:
  name: material
  custom_dir: theme
```

### System information

* OS: macOS 10.12.3
* Browser: Chrome Version 66.0.3359.181

**Comment by martinbira** [comment]
What parts of the base.html do you need to override that you can't use main.html for? I have the same configuration that you show, but all my alterations are in main.html (in the custom_dir) and in the partials. My base.html is untouched and not in the theme dir btw.

**Comment by squidfunk** [comment]
I don't know if its good practice overriding `base.html`, because this file defines all blocks, resources and includes all partials, you should consider overriding `main.html`. If you override `base.html` you would have to provide and include all blocks by yourself.

**Comment by mryanb** [comment]
I was able to override the content block in main.html to make the required changed to the edit URLs. I needed to strip the `.md` extension from the end. Thanks for the point in the right direction.
