### ISSUE TITLE
Remove Hotkeys S and F

### ISSUE THREAD

**Issue by IsabelleVollant** [squidfunk/mkdocs-material#787]
## Description

Can't add a form in page with material theme due to hotkeys S and F

### Expected behavior

I would like to remove or change the hotkeys to search "Alt F" instead of F for example. or remove those hotkeys

### Actual behavior

I have added a form , and when I type S or F, I open the serch box instead of writing the letter in the inputbox

### Package versions

* Python: `python --version`   Python 2.7.12
* MkDocs: `mkdocs --version`  mkdocs, version 0.17.3 
* Material: `pip show mkdocs-material | grep -E ^Version`  Version: 2.7.2

### Project configuration

``` yaml
site_name: xxx
pages:
  xxx
extra_css:
  - 'stylesheets\extra.css'
extra_javascript:
  - 'javascripts\list.js'
theme: 
  name: 'material'
  custom_dir: 'material_theme'
extra:    
    logo: 'Other_images/xx.png'    
    site_favicon: 'Other_images/xx.ico'    
    palette:        
        primary: 'darkblue'        
        accent: 'gold'
markdown_extensions:    
    - admonition    
    - codehilite(guess_lang=false)    
    - toc(permalink=true)    
    - footnotes    
docs_dir: Docs
repo_url: xxx

Thanks

Isa

**Comment by squidfunk** [comment]
``` markdown

# Headline
## Subheadline

Text

<form>
  <input type="text">
</form>

More text
```

Works perfectly for me. The focus stays within the element if the element is part of a form, see:

https://github.com/squidfunk/mkdocs-material/blob/ee6b2412500c068c2de9a14ac930300f741f0f88/src/assets/javascripts/application.js#L423-L430

**Comment by squidfunk** [comment]
Closing this as answered. If you still experience the problem, please re-open.

**Comment by IsabelleVollant** [comment]
Thanks for your help, 
It was due to a form badly formed (evil copy/paste).
It works perfectly now

**Comment by mgdickinson** [comment]
Can you have this also be removed when current element has the contentEditable attribute? I'm writing a function where content can be edited on the page and the changes get pushed to github but the S and F hotkeys make life hard.

**Comment by martoncsikos** [comment]
I had to disable keyboard shortcuts. Adding the below to a custom js file works. It's a blunt solution and there might be unintended side-effects.

```
document.addEventListener('keydown', (e) => {
  e.stopPropagation();
});
```
