### ISSUE TITLE
Add support for theme-color

### ISSUE THREAD

**Issue by Galarzaa90** [squidfunk/mkdocs-material#795]
One of the things I love about this mkdocs theme, is how well it works on mobile, however, there's a small detail that is missing, the theme color attribute:

```html
<meta name="theme-color" content="#4285f4">
```

Example:
![image](https://user-images.githubusercontent.com/12865379/41268839-d70b7724-6db6-11e8-8e50-ef94d3e9a581.png)

I think this would be a great adition to mkdocs. The color should be based on the primary color set (or maybe a darker tone?), and optionally, being able to set a personalized one in config.yml or disable it entirely.

**Comment by squidfunk** [comment]
This was already discussed two years ago, see my comment in https://github.com/squidfunk/mkdocs-material/issues/39#issuecomment-269232034. However, thinking about it, we could in theory solve it by defining a Jinja template with template colors and define those values in HTML (similar to how translations are done). I'll try to come up with something when I find the time.

**Comment by squidfunk** [comment]
Released as part of 2.9.0

**Comment by Galarzaa90** [comment]
Thanks, I just tested it out and it worked :)

There's something worth noting though, I couldn't get it to work at the beginning because I was using `deep purple` as a primary color, but you added the color palette [only with dashes](https://github.com/squidfunk/mkdocs-material/commit/f9298cf91f6ff88a90035dec1174b4c7093b5e8a#diff-c1c4ce26a3e326bd215beabbbb961fb9R5).

The attribute itself works fine using either dashes or spaces, but in the [documentation website](https://squidfunk.github.io/mkdocs-material/getting-started/#color-palette) you list the available colors using spaces, so users following that will run into the same problem.

**Comment by squidfunk** [comment]
Ah, thanks for pointing it out! Will fix it so that both methods are possible.

**Comment by squidfunk** [comment]
Fixed and released with 2.9.1
