### ISSUE TITLE
Add keyboard navigation and modal

### ISSUE THREAD

**Issue by sephlietz** [squidfunk/mkdocs-material#798]
It would be nice to add a keyboard shortcut modal that shows the available keyboard shortcuts. It is becoming conventional show this on '?' press. As far as I know, only 's'/'f' are currently supported, as shortcuts to focus the search bar.

It would also be great to have left/right arrow (or 'n'/'p') to support "flipping through the pages", for use cases where the documentation can be read like a book.

MkDocs already does both of these things.

**Comment by squidfunk** [comment]
This is a nice idea, but a very low priority issue. I will leave it open and may implement it at some point in the future.

**Comment by bvandewe** [comment]
This custom JS works for me... surely not perfect but maybe good enough for most situations.
HTH!
++

```javascript
var controller = (function() {
    var setupEventListeners = function() {
        document.addEventListener('keypress', function(event) {
            //console.log(event.keyCode);
            // > and n
            if (event.keyCode === 62 || event.keyCode === 110) {
                next();
            };
            // < and p
            if (event.keyCode === 60 || event.keyCode === 112) {
                previous();
            };
        });        
        document.addEventListener('keydown', function(event) {
            //console.log(event.keyCode);
            // up and right arrows
            if (event.keyCode === 39 || event.keyCode === 40) {
                next();
            };
            // down and left arrows
            if (event.keyCode === 37 || event.keyCode === 38) {
                previous();
            };
        });        
    };
	var previous = function(){
		document.querySelector('.md-icon--arrow-back').click();
	}
	var next = function(){
		document.querySelector('.md-icon--arrow-forward').click();
	}
    return {
        init: function() {
            setupEventListeners();
        }
    };
})();

controller.init();

```

**Comment by twardoch** [comment]
I didn’t want the keyboard nav events to be triggered when I’m in the Search field (there, the arrow keys are supposed to walk through the text), and I also wanted to use "," for previous and "." for next. So I ended up extending the above script as follows (it’s in my JS that’s included via the `extra_javascript` YAML entry): 

```js
var controller = (function() {
    var setupEventListeners = function() {
        document.addEventListener('keydown', function(event) {
            if ((event.key === '.' || event.key === 'ArrowRight') && document.activeElement.nodeName !== 'INPUT') {
                gotoNext();
            };
            if ((event.key === ',' || event.key === 'ArrowLeft') && document.activeElement.nodeName !== 'INPUT') {
                gotoPrevious();
            };
        });
    };
  var gotoPrevious = function(){
    document.querySelector('.md-icon--arrow-back').click();
  }
  var gotoNext = function(){
    document.querySelector('.md-icon--arrow-forward').click();
  }
    return {
        init: function() {
            setupEventListeners();
        }
    };
})();

controller.init();
```

**Comment by squidfunk** [comment]
Refactored keyboard handlers as part of 9b041096. This commit also adds `,`/`p` and `.`/`n` for navigation:

https://github.com/squidfunk/mkdocs-material/blob/9b0410962d1d1f2d74537882e49eba7ae2ab8fd2/src/assets/javascripts/integrations/keyboard/index.ts#L183-L197

**Comment by squidfunk** [comment]
[Material for MkDocs 5.0.0rc1](https://github.com/squidfunk/mkdocs-material/issues/1498) is out which partly fixes this issue 😀 Let's test and improve it together! A keyboard modal may be added later on.

**Comment by squidfunk** [comment]
I've decided that a keyboard modal is out of scope, because with v5 it's possible to add [custom bindings](https://github.com/squidfunk/mkdocs-material/issues/1498#issuecomment-598246673) which will not show up in the modal. There's also no reasonable way to automate this. However, it's very easy to add one yourself with some extra JavaScript, if you like.

**Comment by ofek** [comment]
I just was about to submit a FR when I stumbled upon this behavior in 5.0.0-rc.2. It's awesome to be able to navigate via just keys. Thank you!!!

**Comment by ofek** [comment]
My only request would be for `/` to enter search also/instead of `s`

**Comment by ofek** [comment]
https://github.com/squidfunk/mkdocs-material/pull/1509
