### ISSUE TITLE
Use minified font-awesome CSS

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#799]
It'd be good if this theme included the minified CSS for Font Awesome as the file size is smaller.
REF: https://github.com/FortAwesome/Font-Awesome/blob/fa-4/css/font-awesome.min.css

**Comment by squidfunk** [comment]
Thanks for reporting! That's of course an error, will provide a fix asap!

**Comment by squidfunk** [comment]
Fixed and released with 2.9.1
