### ISSUE TITLE
Navigation does not respect `use_directory_urls` setting

### ISSUE THREAD

**Issue by nikramakrishnan** [squidfunk/mkdocs-material#801]
## Description

Navigation does not respect the `use_directory_urls` setting in `mkdocs.yml`.

### Expected behavior

When the setting is set to false, links should redirect to `foo/index.html` instead of just `foo/`.

### Actual behavior

Irrespective of whether the setting is enabled or not, clicking on any item on the navigation redirects to the directory URL like `foo/`.

### Steps to reproduce the bug

1. Add `use_directory_urls: false` to mkdocs.yml
2. Run `mkdocs build`
3. Open the site on file system (not using `mkdocs serve`)

### Package versions

* Python: `3.6.5`
* MkDocs: `mkdocs, version 0.17.4`
* Material: `Version: 2.9.1`

**Comment by squidfunk** [comment]
I cannot reproduce this (using `mkdocs 0.17` and latest Material) - works perfectly:

<img width="1062" alt="bildschirmfoto 2018-06-19 um 22 56 50" src="https://user-images.githubusercontent.com/932156/41623939-92565766-7414-11e8-985c-3c50434db156.png">

Can you try if the issue persists if you use `mkdocs 0.17.3`?

**Comment by squidfunk** [comment]
ADDENDUM: I tried with `mkdocs serve` as seen in the screenshot, also validated `mkdocs build` just now - same result: all links are prepended with `index.html`

**Comment by nikramakrishnan** [comment]
Oops, I just realized that there was a problem with my script that generates `mkdocs.yml`. It wasn't adding the `use_directory_urls` option at all. Thanks for testing this!

Closing as not an issue with material.
