### ISSUE TITLE
Icon does not affect browser tab

### ISSUE THREAD

**Issue by macfarmw** [squidfunk/mkdocs-material#804]
## Description

Changed the icon setting to book. The book appears on the page but in the browser tab it still shows the cap.

### Expected behavior

The book to appear in the page and browser tab.

### Actual behavior

The cap appears in the browser tab after changing the icon to book.

### Steps to reproduce the bug

1. Add the following config to the mkdocs.yml file:
theme:
  name: material
  logo:
    icon: 'book'
2. mkdocs serve
3. Browse site
4. Note that book icon is not used in both the page and the browser tab

### Package versions

* Python: `python --version`
3.6.5
* MkDocs: `mkdocs --version`
0.17.3
* Material: `pip show mkdocs-material | grep -E ^Version`
2.7.3

### Project configuration

``` yaml
site_name: DeveloperDocs
theme:
  name: material
  logo:
    icon: 'book'
```

### System information

* OS: Windows 10
* Browser: Chrome

**Comment by squidfunk** [comment]
What you mean is called a favicon which can be changed with [this option](https://squidfunk.github.io/mkdocs-material/getting-started/#favicon). The favicon must be an image, it cannot be set to a web font icon.

**Comment by squidfunk** [comment]
Closing as answered.

**Comment by macfarmw** [comment]
Thanks for supplying that information.

**Comment by David-Borges** [comment]
> Fechando conforme atendido.

deu certo mano valeu
