### ISSUE TITLE
please help me ,idont know what's wrong with my web 

### ISSUE THREAD

**Issue by glm196901** [squidfunk/mkdocs-material#805]
![screenshot from 2018-06-21 23-32-46](https://user-images.githubusercontent.com/13731334/41729302-7b5e09f8-75ab-11e8-8c00-59d679529fa1.png)

**Comment by squidfunk** [comment]
I'm sorry but I don't understand your problem. Please use the issue template to report bugs.

**Comment by glm196901** [comment]
thank you i found the issue is version should be updated
