### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by denyszayets** [squidfunk/mkdocs-material#812]
Hello,

Can you please tell me how can I change background color from white to something else? I tried in CSS but it's not working.
Thank you!

**Comment by squidfunk** [comment]
Did you follow the docs on (customization)[https://squidfunk.github.io/mkdocs-material/customization/#additional-stylesheets]?

**Comment by squidfunk** [comment]
Okay, so if you follow the guide on customization you will see how you can easily change the background color of the theme. If you have any problems you are free to ask on the [gitter.im](https://gitter.im/squidfunk/mkdocs-material) channel for someone to help you.

Closing this issue as a question.

**Comment by MaximilianKohler** [comment]
For anyone finding this via search, Squid shared the code here: https://github.com/squidfunk/mkdocs-material/discussions/2951#discussioncomment-5008037
