### ISSUE TITLE
Glitch in the sidebar

### ISSUE THREAD

**Issue by nikramakrishnan** [squidfunk/mkdocs-material#816]
## Description

The sidebar behaves weirdly when entries are opened and closed multiple times quickly.

![image](https://user-images.githubusercontent.com/10017618/42419133-68543764-82cc-11e8-8ad5-49fcf0b93e89.png)

### Expected behavior

Sidebar should open and close normally, entries should not overlap.

### Actual behavior

Entries overlap.

### Steps to reproduce the bug

1. Add a lot of entries on multiple menus.
2. Click on two or three entries continuously.
3. See the entries overlap.

I've also been told that this happens sometimes without having to continuously click on the entries (which is not what people would normally do).

### Package versions

* Python: `Python 3.6.5`
* MkDocs: `mkdocs, version 0.17.4`
* Material: `Version: 2.9.1`

### System information

* OS: Windows 10
* Browser: Firefox Developer Edition 62.0b5 (64-bit) / Chrome 67.0.3396.99 (64-bit)

**Comment by squidfunk** [comment]
Thanks for reporting! That's indeed a (known) bug. It should usually only happen when you click a link very often. #762 is also related. I will fix this in the JavaScript rewrite I'm currently doing, but I cannot put any estimation on a timeline. It's also been in Material since version 1.0.0.

**Comment by squidfunk** [comment]
Fixed in 4ca20f1.

**Comment by squidfunk** [comment]
Released as part of 4.0.1
