### ISSUE TITLE
Long links don't break

### ISSUE THREAD

**Issue by facelessuser** [squidfunk/mkdocs-material#82]
## Description

Long links don't break.  This is particularly noticeable in mobile viewing:

![screenshot - 1_3_2017 9_26_14 am](https://cloud.githubusercontent.com/assets/1055125/21614485/e2179fb6-d196-11e6-9a72-194b94ba614c.png)

It would be nice if maybe some simple CSS could be applied to links to address this (currently I do this with some appended custom CSS):

```css
.md-typeset a {
  word-wrap: break-word;
}
```

### Expected behavior

Long links should break.

### Actual behavior

Long links do not not break giving an undesirable appearance.

### Steps to reproduce the bug

1. Create document with long link
2. View rendered document in a small window or on a mobile device.

### Package versions

- Python: Any
- MkDocs: 10.16.1
- Material: Latest pre-release 1.0.0rc2

### System information

- OS: Any
- Browser: Any

**Comment by squidfunk** [comment]
Should be fixed, thanks for reporting! I added the abbreviation styles you defined in your custom CSS. Also thanks for testing the theme. I have some questions regarding your extra CSS:

``` css
/* Header Anchors */
.md-typeset .md-content__edit {
  position: relative;
  z-index: 1;
}
```

The edit button is now above the search bar when scrolling. What did you try to fix? Oh and by the way, what's the purpose of the headerlink extension? I think permalinks works reasonably well, doesn't it?

**Comment by facelessuser** [comment]
This is only because of how headeranchors is inserting anchors.  It's purpose was to mimic Github's headeranchors.  I originally wrote it to create a Github-esque output.   If I use `permalinks`, I don't have to do this.  Personally, permalinks is a fine solution and I almost just went ahead and used it instead, but I am also trying to showcase all the extensions (that are reasonable to showcase), so I enabled and configured headeranchors.  Unfortunately when I do, I couldn't click the edit button.

If I recall correctly, when I configured headeranchors, the edit icon disappeared.  I think changing positioning brought it back.  But then I could not click it.  I figured out that raising the `z-index` made it clickable again.  Keep in mind, I am no web developer,  so I don't know if what I did was the best approach.  The CSS I use for headeranchors was based off what Github does (or did -- they change things on occasion).  I just massaged it until it worked with Material.

Most people will use permalinks as it is simple and looks great.  But I already wrote the headeranchor extension, so I have to eat my own dogfood (at least on the pymdown-extension site) :smile: .

**Comment by squidfunk** [comment]
When I remove the CSS for the edit button (position and z-index) it works perfectly ;-) Regarding eating your own dogfood - totally understandable.

**Comment by facelessuser** [comment]
> When I remove the CSS for the edit button (position and z-index) it works perfectly ;-)

Just tried testing it locally with `mkdocs serve`.  I would just change the CSS and let it reload.  If I remove either one, the icon stays visible (so I was wrong about that), but I can't click it unless I hover below it.  I have to have both fixes present to click the icon.  I am afraid I have to leave the fix in for now.  I tested this in Chrome.  Originally on OSX, and now on Windows.

**Comment by squidfunk** [comment]
Oh sorry, did not test that. However, if you set the `z-index` on the `h1` on -1, my solution should work. Approved, not tested ;-)

**Comment by facelessuser** [comment]
You are correct :+1:.  That is a much better solution and keeps it all contained to what I am actually modifying.  Much better.

**Comment by facelessuser** [comment]
Thanks for your help.  I think I am fully migrated over now.  I ended up just rewriting the CSS for headeranchors so I didn't have to fool with relative positions and z-indexes.  Now I look back, a lot of the that CSS was unnecessary...that's what I get for just copying and pasting from Github :).

Anyways, Material is a great theme, and I am glad I've switched over.  Look forward to the final release as the last little minor things get ironed out.

**Comment by squidfunk** [comment]
You're welcome, happy to see the theme being used. I may adapt/integrate your headerlinks code in the future, but still too many other little issues to fix. Same with Emoji.

**Comment by facelessuser** [comment]
Don't waste time integrating headerlinks code.  With my recent revelations on changing the headeranchor CSS, I just realized the same thing can be accomplished with `permalinks` and adding this in `extra.css`:

```css
/* Header Anchors */
.md-typeset .headerlink {
  float: left;
  margin-top: .5rem;
  margin-left: -2.4rem;
  vertical-align: middle;
  font: normal normal 2rem "Material Icons";
  line-height: 1;
}
```

It seems so simple now.  Now the whole concept of the headeranchors extension seems silly to me,  I now also see how convoluted Github's approach was.  Maybe they had their reasons...

Anyways, if people can get the same thing with a pure CSS implementation, I'll probably end up deprecating headeranchors.  Less stuff to support in the future ;).

Just wanted to let you know so you don't go out of your way on my account.

**Comment by squidfunk** [comment]
Perfect, sounds great. I also thought it can be done with Permalinks, but didn't try. Thanks for the detailed explanation!
