### ISSUE TITLE
Tornado > 5 for mkdocs version 1.0

### ISSUE THREAD

**Issue by banesullivan** [squidfunk/mkdocs-material#828]
## Description

The new release of `mkdocs` to come (version 1.0) requires `tornado` versions >= 5 while `mkdocs-material` requires `tornado`<5.

### Expected behavior

Allow usage of `torando`>=5

### Actual behavior

Version conflict on build.
```
pkg_resources.VersionConflict: (tornado 5.1 (.../python3.6/site-packages), Requirement.parse('tornado<5'))
```

### Steps to reproduce the bug

1. `pip install mkdocs==1.0b1`
2. `mkdocs serve`
3. Observe the stack trace

### Package versions

* Python: 3.6.5 :: Anaconda, Inc.
* MkDocs: version 1.0b1
* Material: 2.9.2

### System information

* OS: Mac OS X

**Comment by squidfunk** [comment]
Removed Tornado dependency in 9205a7a
