### ISSUE TITLE
Support mkdocs 1.0

### ISSUE THREAD

**Issue by akhmerov** [squidfunk/mkdocs-material#834]
Follow-up from #831 that set the correct dependency version on v2.9.4.

Known problems:
- Because mkdocs 1.0 changed the URL schema, paths "nest" (all URLs are relative and add up).

**Comment by squidfunk** [comment]
Thinking about it - let's do a PR, so we can directly make changes. In this PR we could set MkDocs to version 1.0 and so see directly if it builds.

**Comment by loic-sharma** [comment]
Ah. I didn't realize that v1.0 of mkdocs wasn't supported. Everything seemed to work for me except:

1. URLs were broken. It looks like the recommended fix is at the end of this section: https://www.mkdocs.org/about/release-notes/#template-variables-and-base_url
2. `pages` is deprecated and `nav` was recommended instead

**Comment by akhmerov** [comment]
> Once MkDocs 1.0 is out

It's out since yesterday :laughing:

**Comment by squidfunk** [comment]
Haha oh man, I missed it 😅 I will try to push out a new version this weekend.

**Comment by squidfunk** [comment]
I added basic MkDocs 1.0 support in d7a32d0a8431d0a58c9b455a0ccd0d06d0c1ab4c.

Feel free to check out the latest master and try it out on your project. Would be great to get some feedback before we release a new major version. However, the following things need to be adressed before pushing out the next release:

- Check, while MkDocs 1.0 cannot be installed on Travis with `pip` (see screenshot)
- Evaluate, if we can use MkDocs new plugin configuration to configure the search
- ...?

<img width="1027" alt="bildschirmfoto 2018-08-04 um 19 57 54" src="https://user-images.githubusercontent.com/932156/43679163-bb28a4e8-9820-11e8-92bb-e52104377c76.png">

**Comment by Ir1d** [comment]
@squidfunk Thanks for your work. I'm writing here to report some of my recent discovery.

> while MkDocs 1.0 cannot be installed on Travis with pip 

I've checked the recent CI log in this repo, it's strange that mkdocs 1.0 can't be installed with pip. Actually I installed successfully with pip yesterday (which caused my CI to fail because of the new version).

> Feel free to check out the latest master and try it out on your project.

check this link: https://github.com/24OI/OI-wiki/pull/61
two CI builds happen at the same moment, and only the first one got accepted. so I guess there's a bug inside this. (I guess that the second build fetched a newer mkdocs-material, and failed to build.)

log of the failed one: https://travis-ci.org/24OI/OI-wiki/builds/412135494
my `build.sh` in `.travis.yml`: https://github.com/24OI/OI-wiki/blob/master/build.sh

UPD: tested on my own computer and resulted the same error.

> Evaluate, if we can use MkDocs new plugin configuration to configure the search

Really looking forward to this, it'll be great if the new search will be able to work well with Chinese characters, XD.

**Comment by Ir1d** [comment]
@squidfunk Thanks for informing. i forgot i was using 0.17.3. the ci has passed now and i'll test more later today.

**Comment by squidfunk** [comment]
Travis fails over and over again with the error I stated above. Already tried to clear the caches, still happening. Does somebody with Python experience have an idea why this might be happening?

**Comment by Ir1d** [comment]
@squidfunk not sure about this, but perhaps you can try pip3 ?

**Comment by facelessuser** [comment]
Maybe upgrade pip? I had some weird issues locally installing new packages a while ago because I was on an old pip. They changed a number of things. I can maybe take a look soon.

**Comment by akhmerov** [comment]
- mkdocs on pypi is available for python v2, so this is unlikely the root of the problem
- looking at the warnings, it may be that pip silently fails due to the connection security problems, although I would find it surprising that it would. However running pip from Python 2.7.8 seems to indicate that it should work.

**Comment by squidfunk** [comment]
Well, it's the Travis pip installation. But I'll try upgrading it before installing the dependencies. It would be awesome if somebody with a Python background could try debug this and maybe make some improvements on the build. I'm really not a Python pro and find it really hard to even get a reproducible dev environment up and running (does somebody have some guidelines)?

**Comment by squidfunk** [comment]
Switching Travis to Python 3.6 seems to work fine

**Comment by squidfunk** [comment]
Just released 3.0.0 - Please see the [release notes](https://squidfunk.github.io/mkdocs-material/release-notes/#material-2x-to-3x) for instructions how to upgrade.

Unfortunately, pre-building the index is currently not supported as this needs some more work and I wanted to get 1.0 support out as soon as possible.
