### ISSUE TITLE
Icon overlaps text in mobile menu

### ISSUE THREAD

**Issue by brendo** [squidfunk/mkdocs-material#84]
## Description

Long section headings overlap with the `toc` icon when viewing on mobile devices (`rework` branch).

<img width="395" alt="screen shot 2017-01-04 at 12 10 38 pm" src="https://cloud.githubusercontent.com/assets/69268/21629770/eee33918-d276-11e6-8bd7-4985797badb5.png">

### Expected behavior

The icon should not overlap the text, text should break over two lines in this case.

### Actual behavior

The text is overlapped by the icon.

### Steps to reproduce the bug

1. Create a page with multiple headings
2. Add that page to `mkdocs.yml` with a long title
2. Resize the browser to emulate a device
3. Click on the menu and observe the overlap.

**Comment by brendo** [comment]
Note that if I bump out the right padding, the text will drop over two lines which looks a little awkward with the current line height values.

**Comment by squidfunk** [comment]
Should be fixed now. Only considered the nested menus, not the table of contents for overlong titles. Thanks for reporting.

![bildschirmfoto 2017-01-04 um 19 46 17](https://cloud.githubusercontent.com/assets/932156/21654656/cc15631c-d2b6-11e6-80de-9484d00e4334.png)
