### ISSUE TITLE
Side menu is not rendered when there are multiple h1 headers

### ISSUE THREAD

**Issue by sergeykhegay** [squidfunk/mkdocs-material#846]
## Description

Side menu is not rendered when there are multiple h1 headers

### Expected behavior

Side menu to be rendered and h1 tags treated as the first level entries.

### Actual behavior

Menu is not rendered.

### Steps to reproduce the bug

```
# Header 1

p1

## Hello 

p2

# Header 2

p3
```

### Package versions

* Python: Python 2.7.15 :: Anaconda, Inc.
* MkDocs: mkdocs, version 0.17.3
* Material: 2.9.2

### System information

* OS: darwin
* Browser: chrome

**Comment by squidfunk** [comment]
Please see #818.

**Comment by squidfunk** [comment]
Closing as answered.
