### ISSUE TITLE
Disabled Syntax Highlighting in Print View

### ISSUE THREAD

**Issue by Excape** [squidfunk/mkdocs-material#85]
I noticed that in the print stylesheet, all the color from the syntax highlighting is removed. I myself like to have the syntax highlighting enabled on print-outs.

It's defined [here](https://github.com/squidfunk/mkdocs-material/blob/e21949edc52fcc121281fedc2ca7c550ef484ea4/src/assets/stylesheets/_print.scss#L55):
```
 pre, pre * {
      color: $black !important;
}
```
Is there a specific reason for this? I can't overwrite it in the `extra.css` since it's marked `!important`

**Comment by squidfunk** [comment]
Good question, probably no reason. However, this is fixed in 1.0.0 which should be released shortly. See #46 for more information.
