### ISSUE TITLE
unable to jump to a custom domain url when click the logo

### ISSUE THREAD

**Issue by lijiawen** [squidfunk/mkdocs-material#850]
## Description
 i click the logo,unable to jump to a custom domain url. 

my config yml is: 
site_url: https://mydomian.com/docs

mkdocs : 1.0.1
material: 3.0.3

**Comment by squidfunk** [comment]
Please provide more details - what does happen exactly? Try to stick to the issue template and provide the steps in order to reproduce your problem.

**Comment by martinbira** [comment]
Are you using a local instance with `mkdocs serve`? If so it should go to 127.0.0.1:8000. If you build with `mkdocs build` and view a page and click the logo you will be transported to the URL defined in `site_url`.

**Comment by lijiawen** [comment]
@martinbira , @squidfunk , as you said，if use mkdocs build，the static index.html can be access with site_url,but how do i build it as a website? mkdocs serve not work now.

**Comment by squidfunk** [comment]
You build it and upload the contents of the `site` directory to your webserver's document root.

**Comment by squidfunk** [comment]
Closing as answered. If you have any more problems I would kindly ask you to write an issue using the provided template, see for example here: #858, or ask in the gitter chat room.
