### ISSUE TITLE
Feature request: Tab Bar

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#852]
I'd really like the ability to have tabs in my documents pages to switch between code examples.

Google use this to switch between XML and JSON here:
- https://developers.google.com/gdata/docs/json

Material Design Guidelines here:
- https://material.io/design/components/tabs.html#tabs
- https://material-components.github.io/material-components-web-catalog/#/component/tabs

**Comment by squidfunk** [comment]
This is already implemented:
https://squidfunk.github.io/mkdocs-material/extensions/codehilite/#grouping-code-blocks

**Comment by coliff** [comment]
awesome! not sure how I missed that. thanks!

**Comment by coliff** [comment]
@squidfunk what do you think about slightly modifying the CSS of the tabs so that that the tabs look a bit more material like? I copied a few CSS attributes from: https://developers.google.com/gdata/docs/json and added it via Chrome Dev Tools to show you a preview:
![material-tabs](https://user-images.githubusercontent.com/1212885/44409422-4c19ae00-a59d-11e8-91e9-2d5338df27a6.png)

The CSS I added was:
```
.md-typeset .superfences-tabs > input:checked + label {
  border-bottom: 2px solid #039be5;
  color: #039be5;
}
```

**Comment by squidfunk** [comment]
Yeah, we could do that but I didn't like it that much initially. Maybe I play around with it some time in the future but for now I'll leave it as it is. Changing it is pretty straight forward as you notices.
