### ISSUE TITLE
404 Page is not working properly

### ISSUE THREAD

**Issue by barreeeiroo** [squidfunk/mkdocs-material#853]
## Description
When accessing to a non existing page, the 404 is broken sometimes

### Expected behavior
It should render like this:
![image](https://user-images.githubusercontent.com/19251112/44396878-856f0100-a53e-11e8-9fbd-77105f6f1108.png)

### Actual behavior
It sometimes rendering like this:
![image](https://user-images.githubusercontent.com/19251112/44396890-915ac300-a53e-11e8-8582-ebe4c0578096.png)

### Steps to reproduce the bug

1. Go to https://docs2.makeroid.io/foo (working fine)
1. Go to https://docs2.makeroid.io/foo/bar (broken)

### Package versions

I'm using GitHub Pages, everything is on a public repo:
https://github.com/Makeroid/Documentation

### Project configuration

Can be found [here](https://github.com/Makeroid/Documentation/blob/master/mkdocs.yml)

### System information

* OS: GitHub Pages

**Comment by martinbira** [comment]
Just reproduced this myself. 
Worth noting is that as above, https://docs2.makeroid.io/foo, this works, but just adding a trailing slash, https://docs2.makeroid.io/foo/ breaks the 404.

**Comment by barreeeiroo** [comment]
If you check in gh-pages the 404.html file (as well as Console), it seems like it's using a relative path and not an absolute path, so maybe that can be issue

![image](https://user-images.githubusercontent.com/19251112/44397314-3b871a80-a540-11e8-93fa-1e83ad651206.png)

But how to fix it? :thinking:

**Comment by barreeeiroo** [comment]
These ones according to require.io:

**Comment by barreeeiroo** [comment]
These ones:

![screenshot_2018-08-21-14-28-38-295_com android chrome](https://user-images.githubusercontent.com/19251112/44401397-cc64f280-a54e-11e8-9c07-58a5a0073035.png)

**Comment by squidfunk** [comment]
Could you try adding a slash at the end of your `site_url`?

**Comment by barreeeiroo** [comment]
It is supposed that this page should have an absolute path, such us `/assets/etc` instead of `assets/etc`, no?

https://github.com/Makeroid/Documentation/blob/gh-pages/404.html#L47

**Comment by squidfunk** [comment]
It actually must have an absolute path because it's a single HTML file that is located at the top of the document root. Relative paths would actually break it the exact way you are reporting because the relative path won't correctly resolve for subdirectories.

**Comment by barreeeiroo** [comment]
Even on localhost is broken, but what can be the cause of this issue?

**Comment by barreeeiroo** [comment]
BTW, I'm getting several of these on the console, but MKDocs builds the site fine (except 404 page)
`ERROR:root:Meta data not found: component`
Maybe it can be releated to it (?)

**Comment by squidfunk** [comment]
I'm sorry, I'm out of ideas. It's perfectly working on the official docs. Maybe someone else experienced the same issue and fixed it?

**Comment by barreeeiroo** [comment]
I've found that this website has the same issue: http://elmahio.github.io/blog/notfound
I'll take a look to that MKDocs Issue :+1:

**Comment by squidfunk** [comment]
I'm not sure why the original author closed it, but it stems from the fact that the MkDocs uses an absolute path on 404 pages (since all URLs, regardless of folder depth must lead to the same page), and for this, `site_url` needs to have the correct value. This means that the 404 page will always use `site_url` + the `/assets/...` links. Please make sure that your `site_url` is correct.

**Comment by squidfunk** [comment]
Also see https://github.com/mkdocs/mkdocs/issues/1598 for reference

**Comment by barreeeiroo** [comment]
@buhtz apologies for closing the issue without a resolution. Tbh, it seems that it is now working fine, and as this issue is 6 years old I don't really remember what fixed it...

In case it helps, here is our `mkdocs.yml`: https://github.com/Kodular/Documentation/blob/master/mkdocs.yml
