### ISSUE TITLE
Replace SVG's with Font Awesome icons

### ISSUE THREAD

**Issue by brendo** [squidfunk/mkdocs-material#86]
Based on #79, thinking about this a little more, could we use Font Awesome for the icons for the `repo_type` instead of the SVG's? It has support for our three current types, Gitlab, Bitbucket and Github and I believe this would remove all SVG's from the project, reducing it's dependencies. 

Because the icons are fonts, we're able to apply colour to them without needing the `-black`/`-white` variants.

Thoughts?

**Comment by squidfunk** [comment]
Theoretically possible, but then FontAwesome would be a mandatory dependency and we already have the Material Icons. I want the theme as lightweight as possible, so in my opinion not the recommended way to go.

**Comment by brianjking** [comment]
I agree with @squidfunk on this as using the Material Design icon library makes the most sense with this theme.

**Comment by squidfunk** [comment]
Thanks @brianjking FontAwesome is just an addition for the social icons, because Material doesn't have them. Therefore it should never be included by default, at least in my opinion. If you want to include it, it's very easy to do with `extra_javascript`.
