### ISSUE TITLE
npm "EACCES: permission denied" error from transitive opencollective dependency

### ISSUE THREAD

**Issue by edmorley** [squidfunk/mkdocs-material#860]
## Description

Unable to `npm install` mkdocs-material dependencies when wanting to contribute, due to opencollective/opencollective-cli#3. 

mkdocs-material depends on stylelint `9.0.0`, which has a `dependency` on opencollective `^1.0.3`, and mkdocs-material's lockfile is pinned to opencollective 1.0.3 - which is the version affected by opencollective/opencollective-cli#3:
https://github.com/squidfunk/mkdocs-material/blob/ca4bb5e4befc950139266bed6583fdf743a3b0bb/package-lock.json#L11663

It looks like refreshing the lockfile will fix this, since not only does newer (and in-semver-range) opencollective fix the issue, but also newer stylelint 9.x.x has actually dropped the opencollective dependency altogether.

### Expected behavior

JS dependencies install successfully.

### Actual behavior

```
npm ERR! path /docs/node_modules/opencollective/dist/bin/opencollective.js.2688880676
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/docs/node_modules/opencollective/dist/bin/opencollective.js.2688880676' -> '/docs/node_modules/opencollective/dist/bin/opencollective.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-27T12_05_52_425Z-debug.log
root@4ecdf02e350f:/docs# npm i
npm WARN rollback Rolling back opencollective@1.0.3 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/docs/node_modules/opencollective/dist/bin'
npm WARN css-loader@1.0.0 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! path /docs/node_modules/opencollective
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall rename
npm ERR! Error: EACCES: permission denied, rename '/docs/node_modules/opencollective' -> '/docs/node_modules/.opencollective.DELETE'
npm ERR!  { Error: EACCES: permission denied, rename '/docs/node_modules/opencollective' -> '/docs/node_modules/.opencollective.DELETE'
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, rename '/docs/node_modules/opencollective' -> '/docs/node_modules/.opencollective.DELETE'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'rename',
npm ERR!      path: '/docs/node_modules/opencollective',
npm ERR!      dest: '/docs/node_modules/.opencollective.DELETE' },
npm ERR!   stack: 'Error: EACCES: permission denied, rename \'/docs/node_modules/opencollective\' -> \'/docs/node_modules/.opencollective.DELETE\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: '/docs/node_modules/opencollective',
npm ERR!   dest: '/docs/node_modules/.opencollective.DELETE',
npm ERR!   parent: 'mkdocs-material' }
```

### Steps to reproduce the bug

1. `cd <path to mkdocs-material source checkout>`
2. `docker run --rm -it -v $PWD:/docs node:8-stretch bash`
  (I'm having to use a Docker container to work around another issue with git-hooks on Windows)
3. `cd docs && npm install`

### Package versions

* Python: N/A
* MkDocs: N/A
* Material: `master`

### Project configuration

N/A

### System information

* OS: docker host is Windows 10
* Browser: N/A

**Comment by edmorley** [comment]
I don't know whether greenkeeper supports automatic lockfile refreshes on a schedule - but at Mozilla we've had good results using the tool [Renovate](https://renovatebot.com/), which does offer that feature and more (Renovate also supports Python dependency management too). (For example mozilla/treeherder#3941)

**Comment by squidfunk** [comment]
Looking at your GitHub profile I realized you seem to do pretty reasonable work, so I decided to add you as a collaborator. I'm currently laking the time to maintain the project, so feel free to make the changes you proposed regarding CSP and fixing the lock file. Let's discuss the changes before releasing, though.

**Comment by edmorley** [comment]
That's great - thank you. Once we get the Neutrino 9 release out over the next couple of weeks, I'll double back to these tickets and open some PRs (I'll ask for review before merging anything).

**Comment by squidfunk** [comment]
Awesome, thanks for your time and work. Happy to review and discuss your solutions.

**Comment by squidfunk** [comment]
I did a clean install on the latest master and did not encounter the error. Seems fixed.
