### ISSUE TITLE
Customizing TOC on webpage to show all levels

### ISSUE THREAD

**Issue by Gjacquenot** [squidfunk/mkdocs-material#861]
## Description

When using the great `mkdocs-material`, it seems that:

- the TOC presented on each webpage shows only the sublevels of the first section (e.g. 1.1, 1.2, 1.3, 1.1.1,1.12, ...)
- it hides the other level section (e.g. 2., 3, 2.1, 2.2, 3.1, ....)

This is different from `mkdocs` default theme that shows all levels of each markdown pages.

Would it be possible to have an option to have a similar behaviour as `mkdocs` default theme?

### Markdown code

``` markdown
# Main title

## T1

Hello world

## T2

Text

## T3

Text

### T3a

# Hidden title 2

# Hidden title 3
```

 `mkdocs-material` : 

- shows TOC with T1, T2, T3, T3a
- but does not show `Hidden title 2` and `Hidden title 3` in generated TOC.

To see the differences between themes, one has to remove the following lines in the `mkdocs.yml` presented below.

    theme:
      name: 'material'

### Steps to reproduce the bug

1. mkdocs build

### Package versions

* Python: 3.7
* MkDocs: 1.0.2
* Material: 3.0.3

### Project configuration

``` yaml
site_name: x

nav:
    - hello: index.md

use_directory_urls: false

theme:
  name: 'material'

```

### System information

* OS: Windows 7
* Browser: Firefox 61

**Comment by martinbira** [comment]
I think this is beacuse using H1 levels more that once is not correct. See #818

**Comment by Gjacquenot** [comment]
Thanks @martinbira for your answer.

I see that I am not the only one to be surprised by this behavior.

I guess issue will be closed soon, but it would be nice to take this into account!

**Comment by martinbira** [comment]
As I understand it, as long as the pages from MkDocs wraps content as an `<article>` this will not change.
To quote @squidfunk 

> The TOC is not intended to list `h1` elements. In HTML5 only one `h1` is valid per page or `article` tag and the whole content is enclosed in an `article` tag, so adding multiple `h1` is not considered valid. Only 2nd+ level items are listed. This is intended behavior.

**Comment by squidfunk** [comment]
Correct. It will never be supported as it's invalid HTML.

**Comment by squidfunk** [comment]
Closing as answered.
