### ISSUE TITLE
New Feature: Custom status icons in navigation

### ISSUE THREAD

**Issue by Richienb** [squidfunk/mkdocs-material#866]
## Description

We should be able to set a custom status icon in a navigation link of a documentation.

## Examples

1. "deprecated" logo in Google's [Web Starter Kit](https://developers.google.com/web/tools/starter-kit/)
![](https://user-images.githubusercontent.com/29491356/44774696-df6b6880-abc7-11e8-97dc-62c28aee5392.PNG)

2. "new" logo in Google's [Recaptcha v3](https://developers.google.com/recaptcha/docs/v3)
![](https://user-images.githubusercontent.com/29491356/44774697-df6b6880-abc7-11e8-8367-5b608ce719df.PNG)

**Comment by squidfunk** [comment]
For this to work, MkDocs must be able to set custom HTML as page titles inside `mkdocs.yml`. I think that's currently not possible.

**Comment by Richienb** [comment]
Ok. I also just remembered that emojis are a thing. Thanks for the feedback!

**Comment by squidfunk** [comment]
Insiders 4.5.0 was just released, which adds the ability to specify an icon per page which is then rendered next to the title in the navigation sidebar: https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-icon

**Comment by squidfunk** [comment]
Insiders 4.22.0 adds [navigation status icons](https://squidfunk.github.io/mkdocs-material/reference/#setting-the-page-status), which is even closer to the original requirement.
