### ISSUE TITLE
External links in navigation

### ISSUE THREAD

**Issue by csandanov** [squidfunk/mkdocs-material#868]
## Description

According to https://github.com/mkdocs/mkdocs/issues/989 since version mkdocs 1.0 it's possible to add external links to `nav`. I'm adding it as:
```yml
nav:
    - Test: "http://example.com"
```
Running `mkdocs serve -v` shows:
```
DEBUG   -  An external link to 'http://example.com' is included in the 'nav' configuration.
```
But I don't see the tab in the theme. Maybe it's just not yet supported in the theme or maybe it's mkdocs issue

### Package versions

* Python: `2.7.10`
* MkDocs: `1.0.3`
* Material: `3.0.3`

**Comment by waylan** [comment]
> I'm adding it as:
> 
>     nav:
>         - Test: "http://example.com"

I'm guessing here, but the first item in your `nav` **must** be the internal homepage for your site. It is likely that you are not seeing the external link because it is the first item. Try adding it as the second item (or later) like @squidfunk did in his test.

**Comment by csandanov** [comment]
Ohh... I see, it added the link under the first tab and I expect it to see as the tab. Hmm.. so I guess it's not possible to add as the tab since it has no sublinks.

**Comment by csandanov** [comment]
My current solution is to override `tabs.html` and add a hardcoded `<li>` item but this link doesn't show up under the expanded menu in the mobile version. Ok, so I guess I can close it since it works as intended.

**Comment by squidfunk** [comment]
Ah, the tabs feature. Tabs are only shown for folders, meaning specific entries in your `mkdocs.yml` that contain other entries. You would also need to patch `nav.html` including your link on the first level here:

https://github.com/squidfunk/mkdocs-material/blob/ca4bb5e4befc950139266bed6583fdf743a3b0bb/src/partials/nav.html#L47-L53

(untested)

**Comment by brandongc** [comment]
The external link in the nav can also result in a malformed sitemap.xml that google search console will complain about

```
<url>
<loc/>
<changefreq>daily</changefreq>
</url>
```

**Comment by djuarezg** [comment]
So... closed with no alternative?

**Comment by waylan** [comment]
@csandanov if this is a bug with MkDocs, please open an issue with the Mkdocs project.

**Comment by weitzman** [comment]
The override worked for me, and did not mess up sitemap.xml. Override docs are at https://squidfunk.github.io/mkdocs-material/customization/#overriding-partials. Thanks for making overrides so simple.
