### ISSUE TITLE
Search doesn't work with basic auth.

### ISSUE THREAD

**Issue by StephaneRob** [squidfunk/mkdocs-material#87]
## Description

Search doesn't work if basic auth required.

### Expected behavior

Fetch `search_index.json` return a 200

### Actual behavior

Fetch `search_index.json` return a 401

### Steps to reproduce the bug

1. Set basic auth
2. Build site
3. Search in docs

### Package versions

- Material: 1.0.0.rc

**Comment by squidfunk** [comment]
Well, this is not a problem of the Material theme but a general problem with XHR on hosts with basic auth. Any suggestions?

**Comment by StephaneRob** [comment]
@squidfunk thanks for all your work, mkdocs-material 0.2.4 is great, 1.0.0 is even more !

I look at the original mkdocs theme and the search_index.json is loaded with requirejs, and it works with basic auth.

https://github.com/mkdocs/mkdocs/blob/master/mkdocs/assets/search/mkdocs/js/search.js#L5

**Comment by StephaneRob** [comment]
I made it works again by adding the following code in `base.html` (before `application.js`):
```html
      <script type="text/javascript">
        var require = {
            baseUrl: './mkdocs/js',
            paths: {
                text: 'text'
            }
        }
      </script>
      <script src="./mkdocs/js/require.js"></script>
      <script type="text/javascript">
        require(['text!../search_index.json']);
      </script>
``` 
`search_index.json` is loaded with Authorization header.

**Comment by squidfunk** [comment]
Did you use Chrome? I think we just need to set some header and it should work - no need for require.js

**Comment by StephaneRob** [comment]
Yes

**Comment by StephaneRob** [comment]
The solution may be to include credentials in fetch : 
```diff
- return fetch(_this.config_.url.base + "/mkdocs/search_index.json").then(function (response) {
+ return fetch(_this.config_.url.base + "/mkdocs/search_index.json", {credentials: 'include'}).then(function (response) {
```

**Comment by squidfunk** [comment]
Should be fixed in `rework` with b273c429d93ca4d37e1386965750dcbd31e651aa. Can you please check out the rework branch and confirm? I added the `credentials` flag, so the auth cookie should be sent by `fetch`.

**Comment by StephaneRob** [comment]
@squidfunk Tested and it works good !
Thanks.

**Comment by squidfunk** [comment]
Awesome, thanks!
