### ISSUE TITLE
usemap attribute on <img> is not working

### ISSUE THREAD

**Issue by bachirelkhoury** [squidfunk/mkdocs-material#872]
I just tested with the default mkdocs theme, and the <img> usemap attribute does work.
However, it doesn't seem to be working in mkdocs-material.
is there something blocking clicks on images?

```
<img src="planets.gif" width="145" height="126" alt="Planets" usemap="#planetmap">

<map name="planetmap">
  <area shape="rect" coords="0,0,82,126" href="sun.htm" alt="Sun">
  <area shape="circle" coords="90,58,3" href="mercur.htm" alt="Mercury">
  <area shape="circle" coords="124,58,8" href="venus.htm" alt="Venus">
</map>
```

**Comment by squidfunk** [comment]
I tried your example and it works.

<img width="1066" alt="bildschirmfoto 2018-09-04 um 10 00 24" src="https://user-images.githubusercontent.com/932156/45018034-6c2f7f80-b029-11e8-96a8-daeccd78326c.png">

**Comment by bachirelkhoury** [comment]
Thanks @squidfunk It turned out my absolute coordinates were way off, because of a large image I am using which got resized.

All sorted. Thanks this excellent theme by the way.
