### ISSUE TITLE
Using this awesome theme on Sphinx ?

### ISSUE THREAD

**Issue by rroblik** [squidfunk/mkdocs-material#88]
Hi,

First thanks for this awesome work done, before and in future releases of this mkdocs theme.

For some reasons I need to not use mkdocs but the "original" sphinx to create a private documentation.

My question is : is this theme usable / portable bakc to sphinx ? (as mkdocs is build on top ... maybe ?!)

Regards

**Comment by squidfunk** [comment]
The theme should be portable, but I haven't dived into Sphinx. It has been ported to Hugo, so if you want to port it to Sphinx, feel free. Currently I have no plans and no time to do it.

**Comment by brianjking** [comment]
@rroblik If you do port it to Sphinx, please let me know!

**Comment by rroblik** [comment]
Dude it's a hard work to do ... :)

If a found time I will let you know here !

Regards

**Comment by squidfunk** [comment]
Would really be great to see sphinx-material! Closing this issue for now.
