### ISSUE TITLE
Feature questions about Tabbed Fences

### ISSUE THREAD

**Issue by lijiawen** [squidfunk/mkdocs-material#882]
my question is:
can tabbed fences support markdown render ?
for example i wanna show a table in a tabbed fence.

**Comment by squidfunk** [comment]
Nope, I'm afraid they are limited to code blocks

**Comment by squidfunk** [comment]
For reference, see [the documentation](https://facelessuser.github.io/pymdown-extensions/extensions/superfences/#tabbed-fences). Closing as answered.
