### ISSUE TITLE
tabs

### ISSUE THREAD

**Issue by Goatmaster** [squidfunk/mkdocs-material#886]
I enabled the tabs feature.
```
theme:
  feature:
    tabs: true
```
How can I now add a new tab to the menubar?

**Comment by martinbira** [comment]
Tabs are based of your page structure in `nav:`. See https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml for example.

**Comment by Goatmaster** [comment]
Thank you for the

> 
> 
> Tabs are based of your page structure in `nav:`. See https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml for example.

Thank you for the help. I got it now.
