### ISSUE TITLE
font-size

### ISSUE THREAD

**Issue by Goatmaster** [squidfunk/mkdocs-material#887]
How can I change the font-size for body, h1 and so on ?

**Comment by squidfunk** [comment]
https://squidfunk.github.io/mkdocs-material/customization/#additional-stylesheets

**Comment by Goatmaster** [comment]
This is not working for me.

**Comment by martinbira** [comment]
@Goatmaster How do you mean? Adding your own custom CSS-files to customize the theme works just fine.

**Comment by Goatmaster** [comment]
If I want to change the font-size for the h1 (# in Markdown) for example I added the following to my custom css file.

```
h1 {
font-size: 12px;
}
```
But the size still remains the same.

**Comment by martinbira** [comment]
Have you tried looking in the inspector on Chrome or Firefox of the item? 
It looks like you should override `.md-typeset h1` and not just `h1`.

**Comment by squidfunk** [comment]
@martinbira's answer is correct. You have to account for CSS specificity.

**Comment by squidfunk** [comment]
Closing as answered. This is not a Material question but a CSS question. Please feel free to discuss it on the official Gitter channel.
