### ISSUE TITLE
How to use quicklatex with mkdocs-material

### ISSUE THREAD

**Issue by CesMak** [squidfunk/mkdocs-material#898]
Hey there,
I want to use tikz graphics on my mkdocs-material webpage. Unfortunately I just found something like using mermaid diagramms but this is not as powerfull as tikz.

As quicklatex supports also tikz I thought about integrating quicklatex in my mkdocs-material webpage.

Any ideas how to do that?

**Comment by facelessuser** [comment]
Material is just a theme.  Unfortunately, this probably isn't the place to get custom web solutions for niche needs.

With that said, if you search the issues, some have used `mermaid` in the past: https://github.com/squidfunk/mkdocs-material/issues/693.  You can see the approach they used to accomplish this and maybe adapt it to fit your needs.

I'm not sure how QuickLatex works, and while it seems like it allows more than just LaTeX style math, if how it identifies and finds LaTeX in documents is similar to KaTeX or MathJax, you may be able to just leverage [Arithmatex](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/) (with the generic output form).

Anyways, I would start taking a look there. If you happen to use one of the extensions over at the `pymdown-extensions` repository to accomplish this, and you have specific questions related to the extension, I'd be happy to help you over there as I am the author.  Unfortunately I don't have time to provide custom JavaScript solutions to meet everyone's needs, but I can at least point you at similar cases to get you rolling.

**Comment by squidfunk** [comment]
This essentially boils down to a Markdown / JavaScript integration question and has nothing to do with the theme in particular. The directions @facelessuser gave are a great start, so I consider this question as answered.
