### ISSUE TITLE
[rework] Nav top of page scroll behaviors

### ISSUE THREAD

**Issue by twardoch** [squidfunk/mkdocs-material#90]
Thank you for the wonderful work on the mkdocs-material rework. It's quite spectacular! 

However, I'm having some concerns about certain UX aspects of the theme. First of all is the scroll behavior for the left and right navs. I realize that you're trying to get sufficient whitespace at the top of the main content, as per the Material guidelines, and at the same time keep the whitespace consistent between the main content and the navs. But I find the "little scroll" of both navs when you start scrolling the main content rather distracting. I think it'd be better if both navs started higher and never moved: 
http://recordit.co/w0zExRhu1j

**Comment by squidfunk** [comment]
Thanks for your feedback.

Yes, the main reason I'm letting the sidebars snap into place is alignment. Your solution would demand that the sidebars are fixed from the beginning and that would look really awkward. Furthermore I'm thinking about giving users with very very large docs the possibility to add a horizontal navigation bar below the header which disappears when scrolling. This would add even more offset and the sidebars would have to snap into place. Making the sidebars fixed at all times would give far less flexibility concerning the height of the header elements and the top offset in general.

**Comment by squidfunk** [comment]
Another question: are you testing the theme on a Retina display? I just got a new MacBook Pro with Retina display and the sidebars jump a little when scrolling. Maybe you meant this kind of behavior? I will look into it this in the near future, but it's not a high priority.

**Comment by squidfunk** [comment]
With the last release, I was able to reduce repaints during scroll by a great amount:

1.0.0

![bildschirmfoto 2017-01-13 um 12 57 40](https://cloud.githubusercontent.com/assets/932156/21962662/abb3bf38-db2b-11e6-9ce1-0b87ead01355.png)

1.0.1

![bildschirmfoto 2017-01-15 um 14 06 20](https://cloud.githubusercontent.com/assets/932156/21962669/d3fc5720-db2b-11e6-8590-718c7a54ea17.png)

This should improve performance by a great factor.
