### ISSUE TITLE
Suggestion: How to get main nav bar in Horizontal Style

### ISSUE THREAD

**Issue by yks0000** [squidfunk/mkdocs-material#903]
This is not the bug but rather need a suggestion as how to have main nav bar as Horizontal always.

When we reduce the screen size, veritical nav bar become horizontal. We need to have it always as we have large heading in nav which does not fit in screen vertically.

Example:

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/6111679/47213128-be4d1a00-d3b7-11e8-819d-a31edb55a8c2.png">

**Comment by squidfunk** [comment]
You can customize the theme with additional CSS, please see the docs for reference.

**Comment by squidfunk** [comment]
Closing as answered. 

For future reference, please ask specific questions for support on theme customization on the official Gitter channel so other people can actually help you. I, myself, cannot provide support for basic HTML/CSS/JavaScript within the scope of this project.
