### ISSUE TITLE
Convert favicon to block for easier overriding

### ISSUE THREAD

**Issue by tedyoung** [squidfunk/mkdocs-material#909]
Currently the only way to override the favicon is by adding the configuration into the `extrahead` block, e.g.:

```
{% extends "base.html" %}

{% block extrahead %}
<link rel="apple-touch-icon" sizes="180x180" href="/images/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon/favicon-16x16.png">
<link rel="manifest" href="/images/favicon/site.webmanifest">
<link rel="mask-icon" href="/images/favicon/safari-pinned-tab.svg" color="#3bb300">
<link rel="shortcut icon" href="/images/favicon/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/images/favicon/browserconfig.xml">
<meta name="theme-color" content="#3bb300">
{% endblock %}
```

However, this means that **two** "shortcut icon" entries end up in the HTML output.

(And yes, I could override the `site_meta` block, but that's a lot of work for changing one thing.)

I propose wrapping the current favicon line in a `favicon` block.

I can submit a PR, though before I go through the work of setting up my dev environment, I wanted to make sure that you'd be accepting of such a change.

**Comment by squidfunk** [comment]
The favicon is actually part of the `site_meta` block. Nesting a block inside a block in not possible I think (or is it?) and moving it out of the `site_meta` block may break a lot of projects down the line so we would need a mitigation/migration strategy with minimal user involvement here.

I understand your troubles and yes, for only overriding the favicon it may not be worth it. However, why don't you just leave out the favicon in your `extrahead` definition and define the favicon through `mkdocs.yml`? See [this link](https://squidfunk.github.io/mkdocs-material/getting-started/#favicon) for further guidance.

**Comment by squidfunk** [comment]
Closing as answered.
