### ISSUE TITLE
[ENH] Lines highlighting

### ISSUE THREAD

**Issue by mantielero** [squidfunk/mkdocs-material#912]
It would be nice to support lines highlighting as in [here](https://github.com/egoist/markdown-it-highlight-lines).

Lines get highlighted by: 
```
   ```js {1,2,4-5}
   function foo() {
     return bar()
       .then(res => {
         return res.doSomething()
       })
   }
   `` `
```
It looks easier and more powerful (it supports ranges) rather than `hl_lines="1 2 4 5"`.

**Comment by squidfunk** [comment]
I have no time to support two different highlighting Markdown extensions, I'm sorry. You can easily add it yourself with extra CSS (just add color to the classes that are added to the source).

**Comment by facelessuser** [comment]
@mantielero, I think you are specifically talking about the input formatting, not specifically the styling in the theme.  If you want that kind of Markdown format, you'll have to fork either CodeHilite or `pymdown-extensions.superfences` (both output in a form that Material recognizes). You'll have to change the input formatting to suite your needs while keeping the output thesame. You will have to maintain it yourself as neither I (author of SuperFences) nor the Python Markdown project (I am a member) have any intentions of changing the input syntax.

**Comment by mantielero** [comment]
You are right about my suggestion.

Just to be precise, I don't have any need. It is just a suggestion about a format that looks easier for the users. I will suffer current format...quietly.

Sorry if I have bother you members somehow.
