### ISSUE TITLE
Site building issue  with RC3

### ISSUE THREAD

**Issue by fr500** [squidfunk/mkdocs-material#92]
## Description

Site no longer builds correctly, it's fine in RC2

### Expected behavior

Site woud build normally

### Actual behavior

I get the following traceback:
https://hastebin.com/gixufukeyi.sql

### Steps to reproduce the bug

1. run mkdocs build

### Package versions

- Python: 2.7.6
- MkDocs: mkdocs, version 0.16.0

### System information

- OS: Ubuntu 16.04

**Comment by squidfunk** [comment]
Which version of Jinja are you using? Can you update to the latest version?

**Comment by squidfunk** [comment]
Just realized we don't need the `with` statement in the templates, so I removed it. It was added in Jinja 2.3 and enabled by default in Jinja 2.9. Building should now work with a Jinja version smaller than 2.9.

**Comment by squidfunk** [comment]
Definitely fixed in 1.0.0. If you still have problems, please re-open.
