### ISSUE TITLE
Order of CSS load

### ISSUE THREAD

**Issue by w4nderlust** [squidfunk/mkdocs-material#920]
## Description

I'm not super sure about this as it maybe expected behavior, but maybe it's worth looking into it.
`extra_css` is not the last CSS to be loaded, so I can't change some of the styles. For instance if I enable permalink, I can't change the blue color of the symbol. The last CSS loaded is application.11e41852.css.
If this is expected behavior, how to redefine `application.11e41852.css`? Creating a custom theme directory and placing a `assets/stylesheets/application.11e41852.css` file in it and modifying it doesn't seem to work.

### Expected behavior

CSS files loaded with `extra_css` should be the last to be loaded.

### Actual behavior

application.11e41852.css is the last CSS loaded.

### Steps to reproduce the bug

1. activate an extension, for example permalink or codehighlite.
2. inspect the permalink symbol or the codeblock.
3. notice where the CSS properties are coming from, the topmost CSS is `application.11e41852.css`

### Package versions

* Python: 3.6.5
* MkDocs: 1.0.4
* Material: 3.1.0

### System information

* OS: MacOSX 10.14.1
* Browser: both Chrome and Safari

**Comment by squidfunk** [comment]
Well, that's strange, as the base template sets `extra_css` as the last block, for this exact reason, see:

https://github.com/squidfunk/mkdocs-material/blob/2bf4fb928c00022cfe048b06306b221eab78b12f/src/base.html#L100-L108

and:

https://github.com/squidfunk/mkdocs-material/blob/2bf4fb928c00022cfe048b06306b221eab78b12f/src/base.html#L158-L165

Have you overridden some of the blocks maybe?

**Comment by w4nderlust** [comment]
My bad, I edited the base.html... sorry about that.
