### ISSUE TITLE
[Request] Configurable cell height/width?

### ISSUE THREAD

**Issue by omento** [squidfunk/mkdocs-material#924]
This is a request (unless it already exists) but would it be possible to add the ability to set a configurable table cell max height either globally or per page in headers? Currently I'm not sure how the cell size is defined, but due to the active width of the pages mixed with the sidebars there isn't a whole lot of space for tables with more than a handful of cells that don't contain a lot of data. I'm currently working on porting our docs from a Wikipedia type host to MkDocs, and for some of the data tables it would be preferable to have a set height rather than a baked max width, i.e. horizontal scrolling is preferred over tall cells with lots of whitespace due to certain cells in a row containing lots of wrapped text with a small width.

### Package versions

* Python: 3.6.6
* MkDocs: 1.0.4
* Material: 3.0.6

**Comment by squidfunk** [comment]
If I understand your request correct, you want to set the height of table cells explicitly to save on width, correct? That's not possible due to the shrink-to-fit layout algorithm all browsers use. The cells won't occupy the height but keep stretching. However, you could explicitly set the width of the tables using raw HTML in your Markdown files or with CSS as done in #922.

**Comment by omento** [comment]
Actually the opposite, I want to set a lower height to force a wider width. Trying to save on height in this situation. It seems like the result I'm going for is apparent when the media query for the more 'mobile' like screen sizes kicks in, but in standard desktop mode I get really tall cells. If I could get the mobile result on desktop just by using a horizontal scroll bar that would be ideal. So there's no easy way of changing this? Let me know if I'm just not understanding.

![desktop](https://user-images.githubusercontent.com/14795448/49680812-12df4e00-fa67-11e8-8823-fc59e105cfa2.png)

You'll also notice the scroll bar on the above desktop width screenshot. It's only there for what appears to be margins or padding for the drop shadow area.

![responsive](https://user-images.githubusercontent.com/14795448/49680815-1672d500-fa67-11e8-8450-d02aa720e625.png)

This is just an example of what I'm talking about. The actual content I'm working with could be rewritten to not use a table (our original site does, so I'm doing a primarily verbatim test port just to see how things look) but the height of cells on desktop screens is really excessive.

**Comment by squidfunk** [comment]
Addendum: you could, as I stated before, set explicit wider widths for the columns with more text. See the linked issue how to do this.

**Comment by squidfunk** [comment]
Closing this issue as answered.

**Comment by omento** [comment]
Sorry, I should have responded before, forgot about the notification. I agree, there isn’t much that can be down without manual theming intervention. Thanks for all the help!
