### ISSUE TITLE
page display problem

### ISSUE THREAD

**Issue by zishuaiz** [squidfunk/mkdocs-material#925]
![image](https://user-images.githubusercontent.com/9448376/50007423-d58d3a00-ffeb-11e8-8f85-86412de135ff.png)

I use default mkdocs index.md and your demo yml config

**Comment by zishuaiz** [comment]
python3.7.1 
mkdocs 1.0.4

**Comment by squidfunk** [comment]
This was already reported in #911 but nobody managed to provide a reproducible case. Could you try and dig into the problem? Which CSS properties and classes are set on the misplaced element?

**Comment by squidfunk** [comment]
Closing as not reproducible. If you can manage to provide a reproducible scenario feel free to comment on the linked issue.
