### ISSUE TITLE
New translation: Brazilian portuguese

### ISSUE THREAD

**Issue by JonatasMA** [squidfunk/mkdocs-material#928]
## Instructions

1. Check, if your language is already available: [here](http://bit.ly/2DCzaL0)
2. If it isn't, please translate the labels on the right:

``` jinja
{% macro t(key) %}{{ {
  "language": "pt-br",
  "clipboard.copy": "Copiar para a área de transferência",
  "clipboard.copied": "Copiado para a área de transferência",
  "edit.link.title": "Editar essa página",
  "footer.previous": "Anterior",
  "footer.next": "Próxima",
  "meta.comments": "Comentários",
  "meta.source": "Fonte",
  "search.language": "pt-br",
  "search.placeholder": "Pesquisar",
  "search.result.placeholder": "Digite para começar a pesquisar",
  "search.result.none": "Sem resultados",
  "search.result.one": "1 resultado encontrado",
  "search.result.other": "# resultados encontrados",
  "search.tokenizer": "[\s\-]+",
  "skip.link.title": "Pular para o conteúdo",
  "source.link.title": "Ir para o repositório",
  "toc.title": "Indíce"
}[key] }}{% endmacro %}
```

Thanks!

**Comment by squidfunk** [comment]
Thanks a lot!

**Comment by squidfunk** [comment]
Revisiting this translation - it is very, very similar to the default Portuguese translation (a lot of keys have the exact same or a very similar translation). Is this so fundamentally different from Portuguese? If so, where?

**Comment by wmitsuda** [comment]
My 2 cents as a Brazilian: even if current keys are similar, Brazilian Portuguese and European Portuguese have many particularities, like US and UK english.

Having said that and comparing both translations, this one sounds better to me regarding the small differences from the original.

**Comment by JonatasMA** [comment]
there are really some differences from one to the other.
but analyzing again, I do not think much needed because they are not complex sentences.

**Comment by squidfunk** [comment]
Okay. Maintaining another version which only differs slightly without having a great impact on understanding (that's what I got from your answers), I would favor keeping things simple and sticking to the currently available Portuguese version.

**Comment by squidfunk** [comment]
I'm closing this, because from what I read from the comments, yes, there are regional differences, but they don't matter that much. We should always try to stick to the [HTML 5 ISO language codes](https://www.w3schools.com/tags/ref_language_codes.asp). Currently `zh_TW` is the only exception, as it's not part of the HML5 ISO language code list but we included it due to more severe differences.
