### ISSUE TITLE
Single page documentation

### ISSUE THREAD

**Issue by AuHau** [squidfunk/mkdocs-material#949]
I have a small utility for which I would like to write documentation, that extends the utility's README, but at the same time, it won't be very compressive documentation spanning multiple pages/sections.  

Is there a mode for "simple/one-page" layout? I would like to drop the left-side navigation pane as it is not needed and either replace it with TOC or completely drop it. 

I am looking for similar feel to this page: https://d0ugal.github.io/retrace/.
I understand it should be possible to do so with custom CSS/JS, just wondering if there is some easier/simpler way...

**Comment by squidfunk** [comment]
The link you provided uses a very old version of Material where the TOC was integrated in the menu.

You could adjust the theme in a way that you swap the navigation for the TOC by extending the theme. See the docs on customization how to do that.

**Comment by AuHau** [comment]
I see, thanks for the reply!
