### ISSUE TITLE
No background for table row on hover

### ISSUE THREAD

**Issue by develar** [squidfunk/mkdocs-material#951]
## Description

Spec: "If a user hovers over a row, display a background color in that row.". See https://material.io/design/components/data-tables.html#behavior-figure-caption-0 ( Behavior -> Row hover )

### Expected behavior

If a user hovers over a row, display a background color in that row."

### Actual behavior

Nothing

### Steps to reproduce the bug

Any table.

### Package versions

* Python: `python --version`
* MkDocs: `mkdocs --version`
* Material: `pip show mkdocs-material | grep -E ^Version`: Version: 3.2.0

### Project configuration

``` yaml
The contents of your mkdocs.yml
```

### System information

* OS: [The operating system you're running]: macOS
* Browser: [The browser used, if relevant]: Chrome

**Comment by squidfunk** [comment]
Fixed in 2b2d908.

**Comment by squidfunk** [comment]
Released as part of 4.0.0.
