### ISSUE TITLE
Page jumps to top when using a lightbox or magnify img plugin

### ISSUE THREAD

**Issue by dimitarsp** [squidfunk/mkdocs-material#956]
## Description

Hi, I am incorporating [lightbox](https://github.com/andreknieriem/simplelightbox) and [magnify](https://github.com/thdoan/magnify) plugins into MKDocs, using Material Theme, but there is an odd behavior when using either of these plugins - the currently active page jumps to the top. I tried to look into the js code for both, but I am not proficient enough to see what could be causing the problem. 

Here are examples:

### Testing the lightbox plugin
![9ajlwoarb8](https://user-images.githubusercontent.com/2496411/50987187-d3da6780-1500-11e9-99c8-912ab130587f.gif)

### Testing the magnify plugin
![qk1f2hnviz](https://user-images.githubusercontent.com/2496411/50987195-d76dee80-1500-11e9-829f-24d7e7daa225.gif)

In any case, I suspect that since both of them are jumping it may be some setting within the  Material Theme?

### Package versions

* Python: `python --version` 3.7
* MkDocs: `mkdocs --version` 1.0.4
* Material: `pip show mkdocs-material | grep -E ^Version` 3.20

### Project configuration

``` 
site_name: HOK Wiki
use_directory_urls: false
theme:
  name: 'material'
  custom_dir: material-mod/
  palette:
    primary: 'red'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'links/hok-small.png'
  logo: 'links/hok.png'

extra_css:
 - extra.css
 - links/magnify.css
 - 'links/simplelb/simplelightbox.min.css'

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - meta

extra_javascript:
 - 'links/simplelb/simple-lightbox.min.js'
 - 'links/jquery.magnify.js'

nav:
  - Revit:
    - Start here: revit/gen/index.md
    - Paul's Tips & Tricks: revit/tips/index.md
  - Rhino & Grasshopper:
    - Projects workflow examples: rhinogh/examples/index.md
    - GH Scripts Library: rhinogh/scripts/gh.md
  - VR/AR:
     - Enscape VR: vr/enscapevr/index.md
     - HOK 360 VR app: vr/hokvr/index.md
     - Other VR Solutions: vr/other.md
```

### System information

* OS: Win10
* Browser: Chrome and Edge

**Comment by squidfunk** [comment]
This is almost certainly a limitation of the lightbox plugins which set the body height to the viewport. Could you check if it is exclusive to Material or does it also happen on other websites (or the standard MkDocs theme) when using the same plugin? However, in general we cannot offer support for additional JS and CSS that users add to their docs.

**Comment by squidfunk** [comment]
Actually, if you look closely at the gif with the magnifying glas, you can see that the header bar jitters on the right side. This could be a side effect of the body height being set to viewport height which makes the scrollbar disappear for a short time.

**Comment by dimitarsp** [comment]
Thank I'll investigate and report what I find

**Comment by squidfunk** [comment]
Closing for housekeeping purposes. If you manage to narrow the error down to Material, please reopen.

**Comment by Niondir** [comment]
Can you describe your changes in `custom_dir: material-mod/`

How do you get the lightbox plugin working at all?
