### ISSUE TITLE
Firefox Scroll bars

### ISSUE THREAD

**Issue by roidelapluie** [squidfunk/mkdocs-material#96]
![ffox](https://cloud.githubusercontent.com/assets/291750/21953565/181f7d0c-da3b-11e6-80b7-eceae0a5930e.png)
## Description

Ugly un-needed scrollbars are displayed in forefox

### Expected behavior

Scroll bars only appear when needed

### Actual behavior

Ugly scroll bar appears all the time

### Steps to reproduce the bug

1. Open firefox

### Package versions

- Python: Python 2.7.11
- MkDocs: mkdocs, version 0.16.1
- Material: Version: 1.0.0

### System information

- OS: Exherbo Linux
- Browser: Firefox 50.1.0

**Comment by roidelapluie** [comment]
Firefox does not support scrollbar-* as it is not part of any CSS standard.

We might consider using      overflow: scroll;

**Comment by squidfunk** [comment]
Fixed in https://github.com/squidfunk/mkdocs-material/pull/105
