### ISSUE TITLE
About the necessity of hotkeys

### ISSUE THREAD

**Issue by panhaoyu** [squidfunk/mkdocs-material#965]
## Description

It's not a bug.

Is it necessary to have such a hotkey?
It is used for documentation, and I think presenting the content is enough.
Besides, I'm a vimium user, the key 'f' is conflict with a very import hotkey of vimium: go to next link.

And most readers do not know this theme, so they do not know there's a hotkey on the page.
Then, in order to use this enhancement, writers may have to explicitly tell readers. 
However, as a documentation write, I don't want to do so.

**Comment by squidfunk** [comment]
> And most readers do not know this theme, so they do not know there's a hotkey on the page.
Then, in order to use this enhancement, writers may have to explicitly tell readers.
However, as a documentation write, I don't want to do so.

When you deploy your documentation, there's a link in the footer which links to the Material for MkDocs homepage telling you about the hotkeys. However, we could, in theory, include a modal and a hint into the theme.

**Comment by panhaoyu** [comment]
> Some people (like me) prefer navigating a page only using the keyboard. Main elements of navigation like for example search are reachable with a single key stroke which IMHO is good UX. There's also a discussion open to include even more hotkeys in #798 which, however, got very few attention.
> 
> I would like to leave this open for some time to discuss the topic before deciding what to do with it.

Perhaps you do not know this extension, just search `vimium`, and you will find what you like. 
I love using keyboards, but use 's' and 'f' as a shortcut is not an universal solution.
I'm using your theme, and I know this key binding.
However, for readers, they even do not know the theme is the `material` theme,
And documentation maintainers may not tell their readers such a function.

Anyway, documentation is not for theme maintainers nor for documentation maintainers, it is for readers. 

BTY, vimium is a great extension, and is availale for both chrome and firefox.

**Comment by panhaoyu** [comment]
And if you really want to custom theme-level key binding, I have another suggestion.

Like pycharm, for `file` option, `f` character has an underline. It indicates the hotkey.
Then use `Alt+F` will open this tab.

**Comment by squidfunk** [comment]
Would you like to remove all hotkeys or just the F/S key? If the user is within the search dialogue there are several further hotkeys for navigation:

* <kbd>Arrow Up</kbd>/<kbd>Arrow down</kbd> for previous/next search result
* <kbd>Esc</kbd> for closing the search box
* <kbd>Enter</kbd> for going to the currently selected search result

I would strongly advise against removing them, as they provide great UX.

**Comment by panhaoyu** [comment]
okay, anyway, thanks for your reply
