### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by connerxyz** [squidfunk/mkdocs-material#971]
## Description

Can't seem to get icons to appear. Haven't had this problem in the past.

### Expected behavior

For icons to appear.

### Actual behavior

No icons are rendered in browser.

### Reproduce 

I'm attempting to use:

`<span class="material-icons arrow">arrow_back</span>`

### Package versions

* Python: 3.7
* MkDocs: 1.0.4
* Material: 3.1.0

### System information

* OS: OS X
* Browser: Chrome

**Comment by squidfunk** [comment]
Try setting `md-icon` as a class. `material-icons` was most probably defined kn the external Material Icon for but might got lost when we integrated the Material icons for GDPR compliance reasons.

**Comment by connerxyz** [comment]
Indeed. That works. Thanks!
`<span class="md-icon arrow">arrow_upward</span>`
