### ISSUE TITLE
Consider removing FastClick 

### ISSUE THREAD

**Issue by coliff** [squidfunk/mkdocs-material#976]
From the FastClick Readme:
https://github.com/ftlabs/fastclick/blob/master/README.md

> As of late 2015 most mobile browsers - notably Chrome and Safari - no longer have a 300ms touch delay, so fastclick offers no benefit on newer browsers, and risks introducing bugs into your application. Consider carefully whether you really need to use it.

I think it'd be good to remove this to keep the JS lighter.

**Comment by squidfunk** [comment]
FastClick removed in 9a4b142. Will be part of the next release.

**Comment by squidfunk** [comment]
Released as part of 4.0.0.
