### ISSUE TITLE
TOC div has inline set height

### ISSUE THREAD

**Issue by AuHau** [squidfunk/mkdocs-material#990]
I am working on a customization of the template for only single-page use-case as described in #949. I was fairly successful: https://gist.github.com/AuHau/29c520a24f719ca95fed22baa6b8ae26

A problem I run into when I was tweaking the responsivity of the site is that the TOC div (`.md-sidebar--secondary`) is being set a fixed height using inline CSS for one of the width range (1024px), which makes it impossible to override as I need to achieve 100% height for the "drive out menu".

What is the reason for this behavior? Where does it originate? Is it possible to find a better solution that would not require fixed height? Maybe using CSS's `calc`?

**Comment by AuHau** [comment]
This is the result of this problem:
 <img width="784" alt="screen shot 2019-02-09 at 4 08 40 pm" src="https://user-images.githubusercontent.com/6072250/52527881-0654bd00-2c85-11e9-8e2e-dc156603659a.png">

**Comment by squidfunk** [comment]
The sidebars overflow on scroll and should always stretch to the remaining viewport height. Using `calc` is not possible, as the sidebars aren't locked to the viewport until scrolled besides a certain height. Furthermore, the footer limits the sidebars when scrolled into view. Thus, the behavior is dynamic and not representable through `calc`. See the screenshots:

<img width="1552" alt="bildschirmfoto 2019-02-11 um 11 14 35" src="https://user-images.githubusercontent.com/932156/52556980-6ca91f00-2dee-11e9-897e-16c9ac54bea2.png">
<img width="1552" alt="bildschirmfoto 2019-02-11 um 11 14 37" src="https://user-images.githubusercontent.com/932156/52556991-6f0b7900-2dee-11e9-869d-39db1f280276.png">
<img width="1552" alt="bildschirmfoto 2019-02-11 um 11 14 39" src="https://user-images.githubusercontent.com/932156/52556992-703ca600-2dee-11e9-8b1f-a95139ad28ff.png">

If you want to override the setting via CSS you can using `!important` should do the trick.

**Comment by AuHau** [comment]
Oh, thanks for the throrough explanation! Unfortunately, you can not override the inline CSS with `!important`, it is on top of cascade's hierarchy.

Do you have any idea how to approach this? I mean for my use-case it is "good enough" even with this problem, but of course would be better to solve it...

**Comment by squidfunk** [comment]
`!important` will override inline styles, as those declarations are with priority to non-important rules. See the CSS2 specification, [section 6.4](https://www.w3.org/TR/CSS2/cascade.html#cascade) for a detailed explanation.

**Comment by AuHau** [comment]
Ups, you are right, my brain was still sleeping when I was validating my claim 😅 

Ok, I guess that is an alright solution for me.

Thanks for the answers!
