### ISSUE TITLE
S and F disabled when editable content is on the screen

### ISSUE THREAD

**Issue by mgdickinson** [squidfunk/mkdocs-material#997]
## Description

S and F keys bring up search bar even when there is contentEditable content on screen. 

### Expected behavior

Not have search bar appear

### Actual behavior

Search opens and website crashes. 

### Steps to reproduce the bug

1. Set any Div attribute to contentEditable
2. Type an S
3. Try to do anything on the page.

**Comment by squidfunk** [comment]
I'll take a look when I find the time. If you want to try it yourself, the code which needs to be adjusted is here:

https://github.com/squidfunk/mkdocs-material/blob/b17e06c1c4e4c26aaddbfbc9e3da486144af9f3f/src/assets/javascripts/application.js#L416-L424

**Comment by mgdickinson** [comment]
Awesome! I could get around it by using an html editing library instead of using the contentEditable feature so I'm not sure it's that important now. I'll adjust the code if I have a second today, regardless. Thanks!

**Comment by mgdickinson** [comment]
haha it actually looks like it conflicts with portions of the library too. Perhaps a config option to remove hotkeys?

**Comment by squidfunk** [comment]
Well, to me it appears as using `contentEditable` in a documentation project (which is static by default) is a real edge case. There probably won't be a `mkdocs.yml` option to remove the hotkeys, but I'm currently thinking about a RxJS-based rewrite which would make everything more easily overridable by extending/customizing the theme's JavaScript. However, I cannot put a timeline on this. It will probably take a few months (or even a year) until this reaches maturity.

**Comment by mgdickinson** [comment]
no worries. yeah it's definitely a unique case. thanks for taking a look
